locations/spiders/hyundai_id.py
locations/spiders/hyundai_kr.py
locations/spiders/hyundai_th.py

Add Hyundai (TH) (34 dealers)

---

locations/spiders/hyundai_gb.py

'atp/brand/Hyundai': 330,
'atp/brand_wikidata/Q55931': 330,
'atp/category/shop/car': 164,
'atp/category/shop/car_repair': 166,
Fixes #8437

Add Hyundai (GB) (330 features)

---

locations/spiders/hyundai_cz.py
locations/spiders/hyundai_gb.py

'atp/brand/Hyundai': 182,
'atp/brand_wikidata/Q55931': 182,
'atp/category/shop/car': 61,
'atp/category/shop/car_parts': 60,
'atp/category/shop/car_repair': 61,
Fixes #8449

Add Hyundai (CZ) (182 features)

---

locations/spiders/hyundai_ch.py
locations/spiders/hyundai_gb.py

'atp/brand/Hyundai': 228,
'atp/brand_wikidata/Q55931': 228,
'atp/category/shop/car': 112,
'atp/category/shop/car_parts': 1,
'atp/category/shop/car_repair': 115,
Fixes #8452

Add Hyundai (CH) (228 features)

---

locations/spiders/hyundai_be.py
locations/spiders/hyundai_gb.py

'atp/brand/Hyundai': 238,
'atp/brand_wikidata/Q55931': 238,
'atp/category/shop/car': 78,
'atp/category/shop/car_parts': 80,
'atp/category/shop/car_repair': 80,
Fixes #8453

Add Hyundai (BE) (238 features)

---

locations/spiders/hyundai_gb.py
locations/spiders/hyundai_pl.py

'atp/brand/Hyundai': 175,
'atp/brand_wikidata/Q55931': 175,
'atp/category/shop/car': 63,
'atp/category/shop/car_parts': 47,
'atp/category/shop/car_repair': 65,
Fixes #8448

Add Hyundai (PL) (175 features)

---

locations/spiders/hyundai_gb.py
locations/spiders/hyundai_sk.py

'atp/brand/Hyundai': 61,
'atp/brand_wikidata/Q55931': 61,
'atp/category/shop/car': 31,
'atp/category/shop/car_repair': 30,
Fixes #8458

Add Hyundai (SK) (61 features)

---

locations/spiders/landi_ch.py

[landi_ch] fix spider

---

ci/run_pr_spiders.sh
locations/spiders/toyota_sacu.py

```
'atp/brand/Hino Motors': 50,
'atp/brand/Lexus': 15,
'atp/brand/Toyota': 176,
'atp/brand/Toyota;Hino Motors': 16,
'atp/brand/Toyota;Lexus': 12,
'atp/brand_wikidata/Q35919': 15,
'atp/brand_wikidata/Q53268': 176,
'atp/brand_wikidata/Q53268;Q35919': 12,
'atp/brand_wikidata/Q53268;Q867667': 16,
'atp/brand_wikidata/Q867667': 50,
'atp/category/shop/car': 209,
'atp/category/shop/car_repair': 10,
'atp/category/shop/truck': 50,
'atp/field/branch/missing': 269,
'atp/field/brand_wikidata/invalid': 28,
'atp/field/image/missing': 269,
'atp/field/opening_hours/missing': 269,
'atp/field/operator/missing': 269,
'atp/field/operator_wikidata/missing': 269,
'atp/field/postcode/missing': 14, …
```

[toyota_sacu] Also collect Lexus and Hino

---

locations/spiders/edward_jones.py

I would be tempted to drop the coords collection entirely. The spider never completes, it's a lot of extra requests and time.

[EdwardJones] Fix crash

---

locations/google_url.py
locations/spiders/buco_na_za.py
tests/test_google_url.py

```
'atp/brand/BUCO': 94,
'atp/brand_wikidata/Q116771533': 94,
'atp/category/shop/hardware': 94,
'atp/cdn/cloudflare/response_count': 96,
'atp/cdn/cloudflare/response_status_count/200': 96,
'atp/field/city/missing': 94,
'atp/field/country/from_reverse_geocoding': 94,
'atp/field/email/missing': 94,
'atp/field/operator/missing': 94,
'atp/field/operator_wikidata/missing': 94,
'atp/field/postcode/missing': 94,
'atp/field/street_address/missing': 94,
'atp/field/website/missing': 94,
'atp/item_scraped_host_count/www.buco.co.za': 94,
'atp/nsi/perfect_match': 94,
```

[buco_na_za] Add spider

---

locations/spiders/chase_us.py

```python
{'atp/brand/Chase': 5382,
'atp/brand_wikidata/Q524629': 5382,
'atp/category/amenity/atm': 507,
'atp/category/amenity/bank': 4874,
'atp/cdn/cloudflare/response_count': 5387,
'atp/cdn/cloudflare/response_status_count/200': 5387,
'atp/field/branch/missing': 5382,
'atp/field/email/missing': 5382,
'atp/field/image/missing': 5382,
'atp/field/lat/missing': 25,
'atp/field/lon/missing': 25,
'atp/field/opening_hours/missing': 268,
'atp/field/operator/missing': 4875,
'atp/field/operator_wikidata/missing': 4875,
'atp/field/twitter/missing': 5382,
'atp/item_scraped_host_count/locator.chase.com': 5382,
'atp/nsi/cc_match': 5381,
'atp/operator/Chase': 507,
'atp/operator_wikidata/Q524629': 507, …
```

[Chase US] Fix spider

---

locations/spiders/speedy_services_gb.py

Fix https://github.com/alltheplaces/alltheplaces/issues/10275

Add speedy_services_gb

---

locations/spiders/fotoprix_es.py
locations/spiders/fotoprix_fr.py

Fix https://github.com/alltheplaces/alltheplaces/issues/10278

Add fotoprix

---

locations/spiders/hss.py
locations/spiders/hss_hire_gb.py

Add HSS Hire

---

locations/spiders/mondialtissus_fr.py

Add Mondial Tissus

---

locations/spiders/boels.py

Add Boels Rentals (Multiple countries)

---

templates/spiders/structured_data_sitemap.tmpl

Not all sites are going to be https, but most will be.

Update structured_data_sitemap.tmpl to adjust the default sitemap url

---

locations/spiders/hirebase_gb.py

Fix https://github.com/alltheplaces/alltheplaces/issues/10270

Add Hirebase (GB)

---

locations/categories.py
locations/spiders/five_guys_ae.py
locations/spiders/five_guys_at.py
locations/spiders/five_guys_au.py
locations/spiders/five_guys_be.py
locations/spiders/five_guys_bh.py
locations/spiders/five_guys_ca.py
locations/spiders/five_guys_ch.py
locations/spiders/five_guys_cn.py
locations/spiders/five_guys_de.py
locations/spiders/five_guys_es.py
locations/spiders/five_guys_fr.py
locations/spiders/five_guys_gb.py
locations/spiders/five_guys_hk.py
locations/spiders/five_guys_ie.py
locations/spiders/five_guys_it.py
locations/spiders/five_guys_kr.py
locations/spiders/five_guys_kw.py
locations/spiders/five_guys_lu.py
locations/spiders/five_guys_mo.py
locations/spiders/five_guys_my.py
locations/spiders/five_guys_nl.py
locations/spiders/five_guys_qa.py
locations/spiders/five_guys_sa.py
locations/spiders/five_guys_sg.py
locations/spiders/five_guys_us.py
locations/storefinders/yext_answers.py
locations/storefinders/yext_search.py

Several of the Five Guys spiders have been broken for a while, however they all use Yext, mostly answers and a couple using search.
All now work and there's more data that we can now parse as well.

Refactor all Five Guys Spiders to Yext, collect more attributes through YextAnswersSpider

---

locations/spiders/heron_foods_gb.py
locations/storefinders/wordpress_heron_foods_spider.py

Rel: https://github.com/alltheplaces/alltheplaces/pull/10192#issuecomment-2360629921
The server has a max radius of 250 miles. @CloCkWeRX You might want to check the other WordpressHeronFoodsSpider spiders you added.

[Heron Foods GB] Collect all locations

---

locations/spiders/shoe_city_bw_na_za.py

```
'atp/brand/Shoe City': 135,
'atp/brand_wikidata/Q116620945': 135,
'atp/category/shop/shoes': 135,
'atp/field/email/missing': 135,
'atp/field/image/missing': 135,
'atp/field/operator/missing': 135,
'atp/field/operator_wikidata/missing': 135,
'atp/field/twitter/missing': 135,
'atp/field/website/missing': 135,
'atp/item_scraped_host_count/amaicdn.com': 135,
'atp/nsi/perfect_match': 135
```

[shoe_city_bw_na_za] Add spider

---

locations/spiders/puuilo_fi.py

Rel: https://github.com/osmlab/name-suggestion-index/pull/9966

[Puuilo FI] Add spider

---

locations/items.py
locations/spiders/starbucks_cn.py

Follow up to #10246 and #10325

[starbucks_cn] Use merge_items, add comments and small fixes

---

locations/spiders/kindred_healthcare.py
locations/spiders/safeway_ca.py

The old sitemap filtering behaviour matched no URLs, so safe to remove.
Unclear if by filtering wanted type to Hospital I have omitted any results

Refactor Kindred healthcare to sitemap, structureddataspider

---

locations/spiders/undiz.py

```
'atp/brand/Undiz': 214,
'atp/brand_wikidata/Q105306275': 214,
'atp/category/shop/clothes': 214,
'atp/field/email/invalid': 5,
'atp/field/image/missing': 214,
'atp/field/operator/missing': 214,
'atp/field/operator_wikidata/missing': 214,
'atp/field/phone/missing': 22,
'atp/field/state/missing': 214,
'atp/field/twitter/missing': 214,
'atp/field/website/missing': 214,
'atp/item_scraped_host_count/api.woosmap.com': 214,
'atp/nsi/perfect_match': 214,
```

[undiz] Add spider

---

locations/spiders/side_step.py

```
'atp/brand/Side Step': 172,
'atp/brand_wikidata/Q116894527': 172,
'atp/category/shop/shoes': 172,
'atp/field/city/missing': 172,
'atp/field/country/from_reverse_geocoding': 172,
'atp/field/email/missing': 172,
'atp/field/image/missing': 172,
'atp/field/opening_hours/missing': 172,
'atp/field/operator/missing': 172,
'atp/field/operator_wikidata/missing': 172,
'atp/field/phone/missing': 172,
'atp/field/postcode/missing': 172,
'atp/field/street_address/missing': 172,
'atp/field/twitter/missing': 172,
'atp/field/website/missing': 172,
'atp/item_scraped_host_count/www.side-step.co.za': 172, …
```

[side_step] Add Spider

---

locations/spiders/spitz_za.py

```
'atp/brand/Spitz': 68,
'atp/brand_wikidata/Q116620967': 68,
'atp/category/shop/shoes': 68,
'atp/cdn/cloudflare/response_count': 76,
'atp/cdn/cloudflare/response_status_count/200': 76,
'atp/field/city/missing': 68,
'atp/field/country/from_spider_name': 68,
'atp/field/image/missing': 68,
'atp/field/state/missing': 68,
'atp/field/street_address/missing': 68,
'atp/item_scraped_host_count/www.spitz.co.za': 68,
'atp/nsi/perfect_match': 68,
```

[spitz_za] Add spider

---

locations/spiders/rage_za.py

```
'atp/brand/Rage': 666,
'atp/brand_wikidata/Q116377890': 666,
'atp/category/office/company': 1,
'atp/category/shop/clothes': 511,
'atp/category/shop/shoes': 154,
'atp/field/city/missing': 666,
'atp/field/country/from_spider_name': 666,
'atp/field/email/missing': 666,
'atp/field/image/missing': 666,
'atp/field/opening_hours/missing': 666,
'atp/field/operator/missing': 666,
'atp/field/operator_wikidata/missing': 666,
'atp/field/phone/invalid': 21,
'atp/field/postcode/missing': 666,
'atp/field/state/missing': 666,
'atp/field/street_address/missing': 666,
'atp/field/twitter/missing': 666,
'atp/field/website/missing': 666,
'atp/item_scraped_host_count/shop.ragesa.co.za': 666, …
```

[rage_za] Add spider

---

locations/spiders/starbucks_jp.py

```
'atp/brand/Starbucks': 1967,
'atp/brand_wikidata/Q37158': 1967,
'atp/category/amenity/cafe': 1967,
'atp/field/city/missing': 65,
'atp/field/country/from_spider_name': 1967,
'atp/field/email/missing': 1967,
'atp/field/image/missing': 1967,
'atp/field/operator/missing': 1967,
'atp/field/operator_wikidata/missing': 1967,
'atp/field/phone/missing': 1967,
'atp/field/postcode/missing': 1967,
'atp/field/street_address/missing': 1967,
'atp/field/twitter/missing': 1967,
'atp/item_scraped_host_count/hn8madehag.execute-api.ap-northeast-1.amazonaws.com': 1967,
'atp/nsi/cc_match': 1967,
'downloader/request_bytes': 36223,
'downloader/request_count': 57,
'downloader/request_method_count/GET': 57,
'downloader/response_bytes': 872206,
'downloader/response_count': 57, …
```

[starbucks_jp] Add spider

---

locations/spiders/yuppiechef_za.py

That was too much effort for 21 locations with no coordinates, but I've done it now.
Waiting on https://github.com/osmlab/name-suggestion-index/commit/11d9984d79eda6e33197134088e2c6212b4a6ac9 for category
```
'atp/brand/Yuppiechef': 21,
'atp/brand_wikidata/Q24234053': 21,
'atp/category/missing': 21,
'atp/field/country/from_spider_name': 21,
'atp/field/lat/missing': 21,
'atp/field/lon/missing': 21,
'atp/field/name/missing': 21,
'atp/field/state/missing': 21,
'atp/field/website/missing': 21,
'atp/item_scraped_host_count/www.yuppiechef.com': 21,
'atp/nsi/brand_missing': 21, …
```

[yuppiechef_za] Add spider

---

locations/spiders/webbers_za.py

```
'atp/brand/Webbers': 128,
'atp/brand_wikidata/Q116619741': 128,
'atp/category/shop/clothes': 128,
'atp/field/country/from_spider_name': 128,
'atp/field/email/missing': 128,
'atp/field/image/missing': 128,
'atp/field/operator/missing': 128,
'atp/field/operator_wikidata/missing': 128,
'atp/field/postcode/missing': 128,
'atp/field/street_address/missing': 128,
'atp/field/twitter/missing': 128,
'atp/item_scraped_host_count/www.webbers.co.za': 128,
'atp/nsi/perfect_match': 128,
```

[webbers_za] Add spider

---

locations/spiders/miladys_za.py

```
'atp/brand/Miladys': 255,
'atp/brand_wikidata/Q116619751': 255,
'atp/category/shop/clothes': 255,
'atp/cdn/cloudflare/response_count': 264,
'atp/cdn/cloudflare/response_status_count/200': 264,
'atp/field/city/missing': 255,
'atp/field/country/from_spider_name': 255,
'atp/field/email/missing': 255,
'atp/field/image/missing': 255,
'atp/field/operator/missing': 255,
'atp/field/operator_wikidata/missing': 255,
'atp/field/phone/missing': 255,
'atp/field/postcode/missing': 255,
'atp/field/state/missing': 255,
'atp/field/street_address/missing': 255,
'atp/field/twitter/missing': 255,
'atp/item_scraped_host_count/www.miladys.com': 255,
'atp/nsi/perfect_match': 255,
```

[miladys_za] Add spider

---

locations/spiders/tgi_fridays_au.py

I am not clear why we are going to the google maps listing though.

Fix spider: tgi fridays AU

---

locations/spiders/webuyanycar_gb.py

Require GB proxy for webbuyanycar_gb

---

locations/spiders/supa_roof_za.py

```
'atp/brand/Supa-Roof': 29,
'atp/brand_wikidata/Q116474839': 29,
'atp/category/shop/trade': 29,
'atp/field/city/missing': 29,
'atp/field/postcode/missing': 29,
'atp/field/street_address/missing': 29,
'atp/item_scraped_host_count/suparoof.co.za': 62,
'atp/nsi/perfect_match': 29,
```

[supa_roof_za] Add spider

---

locations/spiders/perfume_garden_za.py

No coordinates available
```
'atp/brand/The Perfume Garden': 16,
'atp/brand_wikidata/Q116462359': 16,
'atp/category/shop/perfumery': 16,
'atp/field/city/missing': 16,
'atp/field/lat/missing': 16,
'atp/field/lon/missing': 16,
'atp/field/state/missing': 16,
'atp/field/street_address/missing': 16,
'atp/field/website/missing': 16,
'atp/item_scraped_host_count/www.perfumegarden.co.za': 16,
'atp/nsi/perfect_match': 16,
```

[perfume_garden_za] Add spider

---

locations/spiders/russells_za.py
locations/spiders/sleepmasters.py

```
'atp/brand/Russells': 246,
'atp/brand_wikidata/Q116620465': 246,
'atp/category/shop/furniture': 246,
'atp/field/email/missing': 158,
'atp/field/image/missing': 246,
'atp/field/operator/missing': 246,
'atp/field/operator_wikidata/missing': 246,
'atp/field/street_address/missing': 246,
'atp/field/twitter/missing': 246,
'atp/item_scraped_host_count/www.russells.co.za': 246,
'atp/nsi/perfect_match': 246,
```

[russells_za] Add spider

---

locations/spiders/coach.py

```python
{'atp/brand/Coach': 49,
'atp/brand_wikidata/Q727697': 49,
'atp/category/shop/bag': 49,
'atp/cdn/cloudflare/response_count': 104,
'atp/cdn/cloudflare/response_status_count/200': 104,
'atp/field/branch/missing': 49,
'atp/field/image/missing': 49,
'atp/field/operator/missing': 49,
'atp/field/operator_wikidata/missing': 49,
'atp/field/state/missing': 49,
'atp/item_scraped_host_count/de.coach.com': 7,
'atp/item_scraped_host_count/es.coach.com': 15,
'atp/item_scraped_host_count/fr.coach.com': 4,
'atp/item_scraped_host_count/it.coach.com': 8,
'atp/item_scraped_host_count/uk.coach.com': 15,
'atp/nsi/perfect_match': 49,
'downloader/request_bytes': 145609,
'downloader/request_count': 104, …
```

[Coach] Fix spider

---

locations/spiders/pollo_tropical_us.py

```python
{'atp/brand/Pollo Tropical': 126,
'atp/brand_wikidata/Q3395356': 126,
'atp/category/amenity/fast_food': 126,
'atp/cdn/cloudflare/response_count': 130,
'atp/cdn/cloudflare/response_status_count/200': 130,
'atp/field/branch/missing': 126,
'atp/field/email/missing': 126,
'atp/field/image/missing': 126,
'atp/field/operator/missing': 126,
'atp/field/operator_wikidata/missing': 126,
'atp/item_scraped_host_count/locations.pollotropical.com': 126,
'atp/nsi/perfect_match': 126,
'downloader/request_bytes': 51856,
'downloader/request_count': 130,
'downloader/request_method_count/GET': 130,
'downloader/response_bytes': 1582839,
'downloader/response_count': 130,
'downloader/response_status_count/200': 130,
'elapsed_time_seconds': 1.400776, …
```

[Pollo Tropical US] Fix spider (Fixes #10487)

---

locations/spiders/ard_discount.py

rel: https://github.com/osmlab/name-suggestion-index/pull/9977

[Ard Discount] Add spider

---

locations/spiders/five_guys_us.py
locations/spiders/starbucks_mena.py
locations/storefinders/yext_search.py

A number of YextSearchSpiders are broken in this run because I made an error in my refactoring in #10367
This fixes it and I've checked that all of the others work now

[YextSearchSpider] Fix spiders

---

locations/name_suggestion_index.py
tests/test_name_suggestion_index.py

Reference: https://github.com/alltheplaces/alltheplaces/pull/10357/files#r1768235926

name_suggestion_index: improve normalisation before matching

---

locations/spiders/edgars.py
locations/storefinders/amai_promap.py

```
'atp/brand/Edgars': 135,
'atp/brand_wikidata/Q97276073': 135,
'atp/category/shop/department_store': 135,
'atp/field/email/missing': 135,
'atp/field/image/missing': 135,
'atp/field/opening_hours/missing': 135,
'atp/field/operator/missing': 135,
'atp/field/operator_wikidata/missing': 135,
'atp/field/twitter/missing': 135,
'atp/field/website/missing': 135,
'atp/item_scraped_host_count/amaicdn.com': 135,
'atp/nsi/perfect_match': 135,
```

[edgars] Add spider

---

ci/check_spider_naming_consistency.py
locations/spiders/paul_arabia.py
locations/spiders/paul_be.py
locations/spiders/paul_cz.py
locations/spiders/paul_fr.py
locations/spiders/paul_ga.py
locations/spiders/paul_gb.py
locations/spiders/paul_ro.py
locations/spiders/paul_za.py
locations/storefinders/yext_search.py

There are other countries with Paul in them (https://www.paul-bakeries.com/) but maybe just one in some countries, or no website, or a website but only a few locations and no coordinates.
I didn't check every one though, so someone else can feel free to.

Add Paul bakery spiders

---

locations/spiders/gov_dfe_gias_gb.py

Despite working in #10254 it didn't work in the weekly run. I suspect this is because it ran early in the morning and maybe the file wasn't there or wasn't ready. So try getting the previous day's file instead.

[gov_dfe_gias_gb] Try fix

---

locations/categories.py
locations/spiders/akhona_za.py

Despite the map on the page, I can't see the coordinates anywhere
```
'atp/brand/Akhona': 7,
'atp/brand_wikidata/Q116620476': 7,
'atp/category/shop/furniture': 6,
'atp/field/country/from_spider_name': 7,
'atp/field/lat/missing': 7,
'atp/field/lon/missing': 7,
'atp/field/operator/missing': 7,
'atp/field/operator_wikidata/missing': 7,
'atp/field/twitter/missing': 7,
'atp/field/website/missing': 7,
'atp/item_scraped_host_count/www.akhonafurn.co.za': 7,
```

[akhona_za] Add spider

---

locations/spiders/five_below_us.py

```python
{'atp/brand/Five Below': 1727,
'atp/brand_wikidata/Q5455836': 1727,
'atp/category/shop/variety_store': 1727,
'atp/cdn/cloudflare/response_count': 1729,
'atp/cdn/cloudflare/response_status_count/200': 1729,
'atp/field/branch/missing': 1727,
'atp/field/email/missing': 1727,
'atp/field/image/missing': 1727,
'atp/field/operator/missing': 1727,
'atp/field/operator_wikidata/missing': 1727,
'atp/item_scraped_host_count/locations.fivebelow.com': 1727,
'atp/nsi/perfect_match': 1727,
'downloader/request_bytes': 675277,
'downloader/request_count': 1729,
'downloader/request_method_count/GET': 1729,
'downloader/response_bytes': 55333075,
'downloader/response_count': 1729, …
```

[Five Below US] Only query POI webpages

---

locations/spiders/furnmart.py

```
'atp/brand/Furnmart': 160,
'atp/brand_wikidata/Q118185771': 160,
'atp/category/shop/furniture': 160,
'atp/field/city/missing': 160,
'atp/field/country/from_website_url': 160,
'atp/field/email/missing': 160,
'atp/field/image/missing': 160,
'atp/field/opening_hours/missing': 160,
'atp/field/operator/missing': 160,
'atp/field/operator_wikidata/missing': 160,
'atp/field/postcode/missing': 160,
'atp/field/state/missing': 160,
'atp/field/street_address/missing': 160,
'atp/field/twitter/missing': 160,
'atp/item_scraped_host_count/www.furnmart.co.bw': 61,
'atp/item_scraped_host_count/www.furnmart.co.za': 52,
'atp/item_scraped_host_count/www.furnmart.com.na': 47, …
```

[furnmart] Add spider

---

locations/spiders/style_fashion.py
locations/storefinders/amai_promap.py

Waiting on https://github.com/osmlab/name-suggestion-index/commit/6fa6fcabcdd5a6827b06ca5880bab0c71f89a96d for categories
```
'atp/brand/Style': 105,
'atp/brand_wikidata/Q130350929': 105,
'atp/category/missing': 105,
'atp/field/country/from_reverse_geocoding': 6,
'atp/field/email/missing': 105,
'atp/field/name/missing': 105,
'atp/field/operator/missing': 105,
'atp/field/operator_wikidata/missing': 105,
'atp/field/phone/invalid': 31,
'atp/field/phone/missing': 16, …
```

[style_fashion] Add spider

---

locations/spiders/beauty_zone_za.py

No coordinates available
```
'atp/brand/Beauty Zone': 41,
'atp/brand_wikidata/Q118185921': 41,
'atp/category/shop/cosmetics': 41,
'atp/field/city/missing': 41,
'atp/field/country/from_spider_name': 41,
'atp/field/lat/missing': 41,
'atp/field/lon/missing': 41,
'atp/field/phone/missing': 41,
'atp/field/postcode/missing': 41,
'atp/field/state/missing': 41,
'atp/field/website/missing': 41,
'atp/item_scraped_host_count/beautyzone.co.za': 41,
'atp/nsi/perfect_match': 41,
```

[beauty_zone_za] Add spider

---

locations/spiders/hilton.py

- I use requests directly (I know it's not a scrapy way of doing things) as anything else doesn't work. It's only ~100 of lightweight requests, so it should be fine.
Stats:
```json
{
"atp/brand/AutoCamp": 8,
"atp/brand/Canopy": 45,
"atp/brand/Conrad": 51,
"atp/brand/Curio Collection": 186,
"atp/brand/DoubleTree": 722,
"atp/brand/Embassy Suites": 273,
"atp/brand/Graduate": 34,
"atp/brand/Hampton": 3110,
"atp/brand/Hilton": 634,
"atp/brand/Hilton Garden Inn": 1084,
"atp/brand/Hilton Grand Vacations": 84,
"atp/brand/Home2 Suites": 782,
"atp/brand/Homewood Suites": 554,
"atp/brand/LXR Hotels & Resorts": 14,
"atp/brand/Motto": 8,
"atp/brand/NoMad": 1,
"atp/brand/Signia": 4,
"atp/brand/Small Luxury Hotels of the World": 293,
"atp/brand/Spark by Hilton": 104,
"atp/brand/Tapestry Collection": …
```

[hilton] revamp and fix the spider (8k locations)

---

locations/spiders/burger_king_ru.py

rel to: https://github.com/alltheplaces/alltheplaces/issues/10468

[burger_king_ru] restore spider, set proxy to RU

---

locations/spiders/pam_golding.py

```
'atp/brand/Pam Golding Properties': 284,
'atp/brand_wikidata/Q65051429': 284,
'atp/category/office/estate_agent': 284,
'atp/field/image/missing': 284,
'atp/field/lat/missing': 32,
'atp/field/lon/missing': 32,
'atp/field/opening_hours/missing': 67,
'atp/field/operator/missing': 284,
'atp/field/operator_wikidata/missing': 284,
'atp/field/phone/invalid': 9,
'atp/field/street_address/missing': 284,
'atp/field/twitter/missing': 284,
'atp/item_scraped_host_count/www.pamgolding.co.za': 284,
'atp/nsi/perfect_match': 284,
```

[pam_golding] Add spider

---

locations/spiders/kauai_za.py

```
'atp/brand/Kauai': 200,
'atp/brand_wikidata/Q116498799': 200,
'atp/category/amenity/restaurant': 200,
'atp/field/city/missing': 200,
'atp/field/country/from_spider_name': 200,
'atp/field/email/missing': 200,
'atp/field/image/missing': 200,
'atp/field/operator/missing': 200,
'atp/field/operator_wikidata/missing': 200,
'atp/field/postcode/missing': 200,
'atp/field/state/missing': 200,
'atp/field/street_address/missing': 200,
'atp/field/twitter/missing': 200,
'atp/nsi/perfect_match': 200,
```

[kauai_za] Add spider

---

locations/spiders/gov_goriva_si.py

[Gov Goriva SI] Add spider

---

locations/spiders/library_institute_hu.py

Takes a while, but has decent data.
```json
{
"atp/category/amenity/library": 3878,
"atp/field/branch/missing": 3878,
"atp/field/brand/missing": 3878,
"atp/field/brand_wikidata/missing": 3878,
"atp/field/city/missing": 3878,
"atp/field/email/missing": 3878,
"atp/field/image/missing": 3878,
"atp/field/opening_hours/missing": 3878,
"atp/field/operator/missing": 3878,
"atp/field/operator_wikidata/missing": 3878,
"atp/field/phone/invalid": 63,
"atp/field/phone/missing": 997,
"atp/field/postcode/missing": 3878,
"atp/field/state/missing": 3878,
"atp/field/street_address/missing": 3878,
"atp/field/twitter/missing": 3878,
"atp/field/website/invalid": 60,
"atp/field/website/missing": 2636,
"atp/item_scraped_host_count/konyvtarakadatbazisa.oszk.hu": 3878, …
```

[library_institute_hu] Added Spider for Hungarian Libraries (3878 items)

---

locations/spiders/gov_goriva_si.py

Rel: https://github.com/alltheplaces/alltheplaces/pull/10567/files#r1773864456

[Gov Goriva SI] Collect lpg data

---

locations/storefinder_detector.py
locations/storefinders/algolia.py

Added for https://github.com/alltheplaces/alltheplaces/pull/10571

Add new pattern for Algolia detection

---

locations/spiders/nasz_sklep_pl.py

Rel: https://github.com/alltheplaces/alltheplaces/pull/9369#issuecomment-2373818608
No coords :(

[Nasz Sklep PL] Improve output

---

ci/check_spider_naming_consistency.py
locations/spiders/burger_king_ng.py

```
'atp/brand/Burger King': 15,
'atp/brand_wikidata/Q177054': 15,
'atp/burger_king_ng/order_type/OrderTypePreorder': 15,
'atp/category/amenity/fast_food': 15,
'atp/field/country/from_spider_name': 15,
'atp/field/phone/missing': 15,
'atp/field/state/missing': 15,
'atp/item_scraped_host_count/api-mena.menu.app': 15,
'atp/nsi/cc_match': 15,
```

[burger_king_ng] Add spider

---

locations/dict_parser.py
locations/spiders/burger_king_jp.py

```
'atp/brand/Burger King': 229,
'atp/brand_wikidata/Q177054': 229,
'atp/burger_king_jp/hours/failed': 1,
'atp/category/amenity/fast_food': 229,
'atp/field/city/missing': 229,
'atp/field/country/from_spider_name': 229,
'atp/field/email/missing': 229,
'atp/field/image/missing': 229,
'atp/field/operator/missing': 229,
'atp/field/operator_wikidata/missing': 229,
'atp/field/postcode/missing': 229,
'atp/field/state/missing': 229,
'atp/field/twitter/missing': 229,
'atp/field/website/missing': 229,
'atp/item_scraped_host_count/www.burgerking.co.jp': 229,
'atp/nsi/cc_match': 229,
```

[burger_king_jp] Add spider

---

ci/check_spider_naming_consistency.py
locations/spiders/burger_king_gh.py
locations/spiders/burger_king_ke.py

burger_king_ke:
```
'atp/brand/Burger King': 5,
'atp/brand_wikidata/Q177054': 5,
'atp/category/amenity/fast_food': 5,
'atp/field/country/from_spider_name': 5,
'atp/field/operator/missing': 5,
'atp/field/operator_wikidata/missing': 5,
'atp/field/twitter/missing': 5,
'atp/item_scraped_host_count/burgerking.ke': 5,
'atp/nsi/cc_match': 5,
```
burger_king_gh:
```
'atp/brand/Burger King': 3,
'atp/brand_wikidata/Q177054': 3,
'atp/category/amenity/fast_food': 3, …
```

[burger_king_ke] and [burger_king_gh] Add spiders

---

locations/spiders/burger_king_eg.py
locations/spiders/burger_king_eg_sa.py

```
{'atp/brand/Burger King': 25,
'atp/brand_wikidata/Q177054': 25,
'atp/category/amenity/fast_food': 25,
'atp/field/postcode/missing': 25,
'atp/field/street_address/missing': 25,
'atp/field/website/missing': 25,
'atp/item_scraped_host_count/api.solo.skylinedynamics.com': 25,
'atp/nsi/cc_match': 25,
```

[burger_king_eg] Add spider

---

locations/spiders/burger_king_ma.py

```
'atp/brand/Burger King': 34,
'atp/brand_wikidata/Q177054': 34,
'atp/category/amenity/fast_food': 34,
'atp/field/city/missing': 34,
'atp/field/image/missing': 34,
'atp/field/operator/missing': 34,
'atp/field/operator_wikidata/missing': 34,
'atp/field/postcode/missing': 34,
'atp/field/state/missing': 34,
'atp/field/street_address/missing': 34,
'atp/field/twitter/missing': 34,
'atp/field/website/missing': 34,
'atp/item_scraped_host_count/api.solo.skylinedynamics.com': 34,
'atp/nsi/cc_match': 34,
```

[burger_king_ma] Add spider

---

locations/spiders/fournos_za.py

```
'atp/brand/Fournos Bakery': 13,
'atp/brand_wikidata/Q116740976': 13,
'atp/category/amenity/restaurant': 13,
'atp/category/multiple': 1,
'atp/field/city/missing': 13,
'atp/field/country/from_spider_name': 13,
'atp/field/postcode/missing': 13,
'atp/field/state/missing': 13,
'atp/field/street_address/missing': 13,
'atp/field/website/missing': 13,
'atp/item_scraped_host_count/www.fournos.co.za': 13,
'atp/nsi/perfect_match': 13,
```

[fournos_za] Add spider

---

locations/dict_parser.py
locations/spiders/burger_king_cn.py

```
'atp/brand/Burger King': 1245,
'atp/brand_wikidata/Q177054': 1245,
'atp/category/amenity/fast_food': 1245,
'atp/field/country/from_spider_name': 1245,
'atp/field/email/missing': 1245,
'atp/field/image/missing': 1245,
'atp/field/opening_hours/missing': 1245,
'atp/field/operator/missing': 1245,
'atp/field/operator_wikidata/missing': 1245,
'atp/field/phone/invalid': 19,
'atp/field/phone/missing': 115,
'atp/field/postcode/missing': 1182,
'atp/field/street_address/missing': 1245,
'atp/field/twitter/missing': 1245,
'atp/field/website/missing': 1245,
'atp/item_scraped_host_count/www.bkchina.cn': 1245,
'atp/nsi/cc_match': 1245,
```

[burger_king_cn] Add spider

---

ci/check_spider_naming_consistency.py
locations/spiders/burger_king_bd.py

```
'atp/brand/Burger King': 8,
'atp/brand_wikidata/Q177054': 8,
'atp/category/amenity/fast_food': 8,
'atp/field/city/missing': 8,
'atp/field/country/from_spider_name': 8,
'atp/item_scraped_host_count/www.burgerkingbangladesh.com': 8,
'atp/nsi/cc_match': 8,
```

[burger_king_bd] Add spider

---

locations/spiders/burger_king_ie.py

More info may be available, but I get a 403 when clicking on the more details button on https://www.whopper.ie/locations/
```
'atp/brand/Burger King': 48,
'atp/brand_wikidata/Q177054': 48,
'atp/category/amenity/fast_food': 48,
'atp/field/branch/missing': 48,
'atp/field/city/missing': 18,
'atp/field/email/missing': 48,
'atp/field/image/missing': 48,
'atp/field/opening_hours/missing': 48,
'atp/field/operator/missing': 48,
'atp/field/operator_wikidata/missing': 48,
'atp/field/phone/missing': 48,
'atp/field/street_address/missing': 48,
'atp/field/twitter/missing': 48,
'atp/field/website/missing': 48,
```

[burger_king_ie] Add spider

---

locations/spiders/a101_tr.py
locations/spiders/migros_tr.py

rel: https://github.com/osmlab/name-suggestion-index/pull/9739

[migros_tr][a101_tr] add category

---

locations/spiders/habit_burger.py

```python
{'atp/brand/The Habit Burger Grill': 389,
'atp/brand_wikidata/Q18158741': 389,
'atp/category/amenity/fast_food': 389,
'atp/field/email/missing': 389,
'atp/field/image/dropped': 389,
'atp/field/image/missing': 389,
'atp/field/operator/missing': 389,
'atp/field/operator_wikidata/missing': 389,
'atp/field/state/from_reverse_geocoding': 12,
'atp/field/twitter/missing': 389,
'atp/item_scraped_host_count/www.habitburger.com': 389,
'atp/nsi/perfect_match': 389,
'downloader/request_bytes': 152045,
'downloader/request_count': 397,
'downloader/request_method_count/GET': 397,
'downloader/response_bytes': 6536839,
'downloader/response_count': 397, …
```

[Habit Burger] Fix name, collect branch

---

locations/spiders/hyundai_ee_fi_lt_lv.py
locations/spiders/hyundai_et_fi_lt_lv.py

Add Hyundai (EE/FI/LT/LV) (57 dealers)

---

locations/spiders/hyundai_ie.py

'atp/brand/Hyundai': 62,
'atp/brand_wikidata/Q55931': 62,
'atp/category/shop/car': 31,
'atp/category/shop/car_repair': 31,
Fixes #8444

Add Hyundai (IE) (62 features)

---

locations/spiders/tentworld_au.py

Change tentworld_au to graphql

---

locations/spiders/hyundai_bw_ls_na_sz_za.py
locations/spiders/hyundai_za.py

'atp/brand/Hyundai': 296,
'atp/brand_wikidata/Q55931': 296,
'atp/category/shop/car': 102,
'atp/category/shop/car_parts': 96,
'atp/category/shop/car_repair': 98,
Fixes #8461

Add Hyundai (BW/LS/NA/SZ/ZA) (296 features)

---

locations/spiders/us_army_national_guard.py

TBA: What's the best category? Old spider did not have it

Fix domain for us_national_guard

---

locations/spiders/hyundai_fr.py

Add Hyundai (FR) (200 dealers)

---

locations/dict_parser.py
locations/spiders/hyundai_ca.py

'atp/brand/Hyundai': 669,
'atp/brand_wikidata/Q55931': 669,
'atp/category/shop/car': 223,
'atp/category/shop/car_parts': 223,
'atp/category/shop/car_repair': 223,
Fixes #8442

Add Hyundai (CA) (669 features)

---

locations/dict_parser.py
locations/spiders/hyundai_us.py

'atp/brand/Hyundai': 135,
'atp/brand_wikidata/Q55931': 135,
'atp/category/shop/car': 45,
'atp/category/shop/car_parts': 45,
'atp/category/shop/car_repair': 45,
Fixes #8443

Add Hyundai (US) (135 features)

---

locations/spiders/meny_dk.py

Add Meny (DK) (116 stores)

---

locations/spiders/comtesse_du_barry_fr.py

```python
{
'atp/brand/Comtesse du Barry': 47,
'atp/brand_wikidata/Q17176547': 47,
'atp/category/shop/deli': 47,
'atp/field/branch/missing': 47,
'atp/field/state/missing': 47,
'atp/item_scraped_host_count/boutiques.comtessedubarry.com': 47,
'atp/nsi/perfect_match': 47,
'downloader/request_bytes': 25753,
'downloader/request_count': 49,
'downloader/request_method_count/GET': 49,
'downloader/response_bytes': 1397779,
'downloader/response_count': 49,
'downloader/response_status_count/200': 49,
'elapsed_time_seconds': 64.10436,
'finish_time': datetime.datetime(2024, 9, 26, 21, 21, 11, 884954, tzinfo=datetime.timezone.utc), …
```

[ComtesseDuBarryFR] Added Spider for Comtesse du Barry

---

locations/spiders/sok_tr.py

rel: https://github.com/osmlab/name-suggestion-index/pull/9739

[sok_tr] Added category to ensure proper nsi detection

---

locations/spiders/quiktrip_us.py

Remove generic image: quiktrip_us

---

locations/spiders/taco_bell.py

Update taco_bell.py to remove logo based image

---

locations/spiders/burger_king_cy.py

```
'atp/brand/Burger King': 10,
'atp/brand_wikidata/Q177054': 10,
'atp/category/amenity/fast_food': 10,
'atp/field/city/missing': 10,
'atp/item_scraped_host_count/burgerking.com.cy': 10,
'atp/nsi/cc_match': 10,
```

[burger_king_cy] Add spider

---

locations/spiders/hyundai_bw_ls_na_sz_za.py

Follow up to #10610, ping @davidhicks
I felt that this was giving duplicate items, a car shop that sells parts and services a car is one point, not three, I think.
```
'atp/brand/Hyundai': 103,
'atp/brand_wikidata/Q55931': 103,
'atp/category/shop/car': 103,
'atp/field/branch/missing': 103,
'atp/field/city/missing': 103,
'atp/field/country/from_reverse_geocoding': 103,
'atp/field/email/invalid': 9,
'atp/field/image/missing': 103,
'atp/field/opening_hours/missing': 74,
'atp/field/operator/missing': 103,
'atp/field/operator_wikidata/missing': 103,
'atp/field/postcode/missing': 103, …
```

[hyundai_bw_ls_na_sz_za] Fix duplicates and country

---

locations/spiders/burger_king_gt.py

```
'atp/brand/Burger King': 53,
'atp/brand_wikidata/Q177054': 53,
'atp/category/amenity/fast_food': 53,
'atp/field/city/missing': 53,
'atp/field/country/from_spider_name': 53,
'atp/field/email/missing': 53,
'atp/field/image/missing': 53,
'atp/field/opening_hours/missing': 53,
'atp/field/operator/missing': 53,
'atp/field/operator_wikidata/missing': 53,
'atp/field/phone/missing': 53,
'atp/field/postcode/missing': 53,
'atp/field/state/missing': 53,
'atp/field/street_address/missing': 53,
'atp/field/twitter/missing': 53,
'atp/item_scraped_host_count/bk.gt': 53,
'atp/nsi/cc_match': 53,
```

[burger_king_gt] Add spider

---

ci/check_spider_naming_consistency.py
locations/spiders/burger_king_nc.py

```
'atp/brand/Burger King': 4,
'atp/brand_wikidata/Q177054': 4,
'atp/category/amenity/fast_food': 4,
'atp/field/country/from_spider_name': 4,
'atp/field/image/missing': 4,
'atp/field/operator/missing': 4,
'atp/field/operator_wikidata/missing': 4,
'atp/field/twitter/missing': 4,
'atp/item_scraped_host_count/www.burgerking.nc': 4,
'atp/nsi/cc_match': 4,
```

[burger_king_nc] Add spider

---

ci/check_spider_naming_consistency.py
locations/spiders/burger_king_mn.py

```
'atp/brand/Burger King': 12,
'atp/brand_wikidata/Q177054': 12,
'atp/category/amenity/fast_food': 12,
'atp/field/city/missing': 12,
'atp/field/country/from_spider_name': 12,
'atp/field/postcode/missing': 12,
'atp/field/street_address/missing': 12,
'atp/field/website/missing': 12,
'atp/item_scraped_host_count/delivery-backend-3psaay575a-as.a.run.app': 12,
'atp/nsi/cc_match': 12,
```

[burger_king_mn] Add spider

---

locations/spiders/burger_king_kz.py

```
'atp/brand/Burger King': 51,
'atp/brand_wikidata/Q177054': 51,
'atp/category/amenity/fast_food': 51,
'atp/field/country/from_spider_name': 51,
'atp/field/email/missing': 51,
'atp/field/image/missing': 51,
'atp/field/lat/missing': 46,
'atp/field/lon/missing': 46,
'atp/field/operator/missing': 51,
'atp/field/operator_wikidata/missing': 51,
'atp/field/phone/invalid': 14,
'atp/field/phone/missing': 19,
'atp/field/postcode/missing': 51,
'atp/field/state/missing': 51,
'atp/field/twitter/missing': 51,
'atp/field/website/missing': 51,
'atp/item_scraped_host_count/burgerking.kz': 51,
'atp/nsi/cc_match': 51,
```

[burger_king_kz] Add spider

---

locations/spiders/burger_king_il.py

```
'atp/brand/Burger King': 17,
'atp/brand_wikidata/Q177054': 17,
'atp/category/amenity/fast_food': 17,
'atp/field/country/from_spider_name': 17,
'atp/item_scraped_host_count/www.burgerking.co.il': 17,
'atp/nsi/cc_match': 17,
```

[burger_king_il] Add spider

---

locations/categories.py
locations/spiders/burger_king_in.py

```
'atp/brand/Burger King': 460,
'atp/brand_wikidata/Q177054': 460,
'atp/category/amenity/fast_food': 460,
'atp/field/branch/missing': 460,
'atp/field/email/missing': 460,
'atp/field/image/dropped': 460,
'atp/field/image/missing': 460,
'atp/field/operator/missing': 460,
'atp/field/operator_wikidata/missing': 460,
'atp/field/twitter/missing': 460,
'atp/item_scraped_host_count/stores.burgerking.in': 1380,
'atp/nsi/cc_match': 460,
```

[burger_king_in] Add spider

---

locations/spiders/auntie_annes.py

The image field is a generic stock art image, and not an individual image for each store.

auntie_annes: drop image field

---

locations/spiders/mt_bank_us.py

mt_bank_us: drop image field

---

locations/spiders/papa_johns.py

papa_johns: drop image field

---

ci/run_pr_spiders.sh

Warn on low uniqueness for image URLs

---

locations/storefinder_detector.py
locations/storefinders/amai_promap.py

Part of https://github.com/alltheplaces/alltheplaces/issues/10032

Amai - Autodetection

---

locations/hours.py
locations/spiders/burger_king_kr.py

```
'atp/brand/Burger King': 505,
'atp/brand_wikidata/Q177054': 505,
'atp/category/amenity/fast_food': 505,
'atp/field/city/missing': 505,
'atp/field/country/from_spider_name': 505,
'atp/field/email/missing': 505,
'atp/field/image/missing': 505,
'atp/field/opening_hours/missing': 74,
'atp/field/operator/missing': 505,
'atp/field/operator_wikidata/missing': 505,
'atp/field/postcode/missing': 505,
'atp/field/state/missing': 505,
'atp/field/twitter/missing': 505,
'atp/field/website/missing': 505,
'atp/item_scraped_host_count/burgerking.co.kr': 505,
'atp/nsi/cc_match': 505,
```

[burger_king_kr] Add spider

---

locations/google_url.py
locations/spiders/burger_king_my.py
locations/spiders/burger_king_sg.py
tests/test_google_url.py

Also additions to `url_to_coords` because apparently it is valid to put the lat/lon with degrees or to use a space instead of a comma

[burger_king_my] Add spider (191 locations) and [burger_king_sg] (68 locations)

---

ci/run_pr_spiders.sh

For https://github.com/alltheplaces/alltheplaces/issues/10679

Add unique emails check

---

locations/spiders/o2_cz.py

Coordinates parsed from HTML attributes, opening hours parsed from HTML table.
Address taken from Google Maps URL, no easy way to parse it, as it usually contains a shopping center name.

[o2_cz]: Add spider (159 locations)

---

locations/spiders/dominos_pizza_pk.py

```
"atp/brand/Domino's": 67,
'atp/brand_wikidata/Q839466': 67,
'atp/category/amenity/fast_food': 67,
'atp/field/city/missing': 67,
'atp/field/country/from_spider_name': 67,
'atp/field/email/invalid': 11,
'atp/field/image/missing': 67,
'atp/field/opening_hours/missing': 67,
'atp/field/operator/missing': 67,
'atp/field/operator_wikidata/missing': 67,
'atp/field/phone/missing': 49,
'atp/field/postcode/missing': 67,
'atp/field/state/missing': 67,
'atp/field/street_address/missing': 67,
'atp/field/twitter/missing': 67,
'atp/field/website/missing': 67,
'atp/item_scraped_host_count/www.dominos.com.pk': 67,
'atp/nsi/cc_match': 67,
```

[dominos_pizza_pk] Add spider

---

locations/spiders/harcourts.py
locations/spiders/harcourts_za.py

```
'atp/brand/Harcourts': 81,
'atp/brand/RentalsDotCom': 11,
'atp/brand_wikidata/Q5655056': 92,
'atp/category/office/estate_agent': 92,
'atp/field/country/from_spider_name': 92,
'atp/field/image/missing': 92,
'atp/field/opening_hours/missing': 92,
'atp/field/operator/missing': 92,
'atp/field/operator_wikidata/missing': 92,
'atp/field/state/missing': 92,
'atp/field/street_address/missing': 92,
'atp/field/twitter/missing': 92,
'atp/item_scraped_host_count/www.harcourts.co.za': 92,
'atp/nsi/perfect_match': 92,
```

[harcourts_za] Add spider

---

locations/spiders/rawson_za.py

```
'atp/brand/Rawson Property Group': 261,
'atp/brand_wikidata/Q130379454': 261,
'atp/category/office/estate_agent': 261,
'atp/field/branch/missing': 261,
'atp/field/city/missing': 261,
'atp/field/country/from_spider_name': 261,
'atp/field/email/missing': 261,
'atp/field/image/missing': 261,
'atp/field/opening_hours/missing': 261,
'atp/field/operator/missing': 261,
'atp/field/operator_wikidata/missing': 261,
'atp/field/postcode/missing': 261,
'atp/field/state/missing': 261,
'atp/field/twitter/missing': 261,
'atp/item_scraped_host_count/rawson.co.za': 261,
'atp/nsi/perfect_match': 261,
```

[rawson_za] Add spider

---

locations/spiders/incredible.py

```
'atp/brand/Incredible': 88,
'atp/brand_wikidata/Q130377046': 88,
'atp/category/shop/electronics': 83,
'atp/category/shop/mobile_phone': 5,
'atp/field/street_address/missing': 88,
'atp/item_scraped_host_count/www.incredible.co.za': 88,
```

[incredible] Add spider

---

locations/spiders/rochester_za.py

```
'atp/brand/Rochester': 49,
'atp/brand_wikidata/Q130377132': 49,
'atp/category/shop/furniture': 49,
'atp/field/image/missing': 49,
'atp/field/operator/missing': 49,
'atp/field/operator_wikidata/missing': 49,
'atp/field/street_address/missing': 49,
'atp/field/twitter/missing': 49,
'atp/item_scraped_host_count/www.rochester.co.za': 49,
'atp/nsi/perfect_match': 49,
```

[rochester_za] Add spider

---

locations/spiders/burger_king_vn.py

```
'atp/brand/Burger King': 11,
'atp/brand_wikidata/Q177054': 11,
'atp/category/amenity/fast_food': 11,
'atp/field/city/missing': 11,
'atp/field/image/missing': 11,
'atp/field/state/missing': 11,
'atp/field/street_address/missing': 11,
'atp/item_scraped_host_count/burgerking.vn': 11,
'atp/nsi/cc_match': 11,
```

[burger_king_vn] Add spider

---

locations/spiders/virginia_health_inspection_blue_ridge.py

Correctly page the data and limit to the last 6 months.
I stopped working on this because it stated to feel like My Health Department was an aggregator of different health departments. I no longer think that, [virginia.gov](https://www.vdh.virginia.gov/environmental-health/food-safety-in-virginia/) links directly to them. However each area has slightly different format and categories, so I'll leave that to someone more interested.
```python
{'atp/category/amenity/fast_food': 55,
'atp/category/amenity/hospital': 4,
'atp/category/amenity/restaurant': 147,
'atp/category/amenity/school': 55,
'atp/category/missing': 89,
'atp/field/branch/missing': 350,
'atp/field/brand/missing': 350,
'atp/field/brand_wikidata/missing': 350,
'atp/field/country/missing': 350, …
```

[VirginiaHealthInspectionBlueRidge] Fix pageing

---

locations/hours.py
locations/spiders/burger_king_hr.py

```
'atp/brand/Burger King': 8,
'atp/brand_wikidata/Q177054': 8,
'atp/category/amenity/fast_food': 8,
'atp/field/country/from_spider_name': 8,
'atp/item_scraped_host_count/burgerking.hr': 8,
'atp/nsi/cc_match': 8,
```

[burger_king_hr] Add spider

---

locations/spiders/northern_tool.py
locations/spiders/northern_tool_us.py

First spider, lmk if you need anything else. Thanks

Add Northern Tool + Equipment (141 locations)

---

locations/spiders/burger_king_ee_lt_lv.py

```
'atp/brand/Burger King': 21,
'atp/brand_wikidata/Q177054': 21,
'atp/category/amenity/fast_food': 21,
'atp/field/city/missing': 21,
'atp/field/country/from_reverse_geocoding': 21,
'atp/field/website/missing': 21,
'atp/item_scraped_host_count/www.burgerking.ee': 21,
'atp/nsi/cc_match': 21,
```

[burger_king_ee_lt_lv] Add spider

---

locations/spiders/amtrak.py

Noticed there wasn't any wikidata qcodes attached to the POIs. SO I added them

[amtrak] Added network and network:wikidata to POIs

---

locations/spiders/vanharen_be_nl.py

Update vanharen_be_nl.py to drop images

---

locations/spiders/best_buy_ca.py

Update best_buy_ca.py to drop images

---

locations/spiders/ubreakifix.py

Update ubreakifix.py to drop images

---

locations/spiders/burger_king_bs.py
locations/spiders/burger_king_hu.py

```
'atp/brand/Burger King': 56,
'atp/brand_wikidata/Q177054': 56,
'atp/category/amenity/fast_food': 56,
'atp/field/state/missing': 56,
'atp/field/website/missing': 56,
'atp/item_scraped_host_count/burgerking.hu': 1535,
'atp/nsi/cc_match': 56,
```

[burger_king_hu] Add spider

---

locations/spiders/pf_changs.py

Update pf_changs.py to drop image

---

locations/spiders/halifax_gb.py

Update halifax_gb.py to drop images

---

locations/spiders/petit_bateau.py

Update petit_bateau.py to drop images

---

locations/spiders/burger_king_cl.py
locations/spiders/burger_king_ng.py

```
'atp/brand/Burger King': 79,
'atp/brand_wikidata/Q177054': 79,
'atp/burger_king_cl/unhandled_order_type/OrderTypeDineIn': 21,
'atp/burger_king_cl/unhandled_order_type/OrderTypePreorder': 74,
'atp/category/amenity/fast_food': 79,
'atp/field/city/missing': 29,
'atp/field/country/from_spider_name': 79,
'atp/field/email/missing': 79,
'atp/field/image/missing': 79,
'atp/field/operator/missing': 79,
'atp/field/operator_wikidata/missing': 79,
'atp/field/phone/invalid': 9,
'atp/field/state/missing': 79,
'atp/field/twitter/missing': 79,
'atp/item_scraped_host_count/api-lac.menu.app': 79,
'atp/nsi/cc_match': 79,

[burger_king_cl] Add spider

---

locations/dict_parser.py
tests/test_dict_parser.py

[DictParser] Safer geojson geometry parsing

---

locations/spiders/autour_de_bebe_fr.py

Update autour_de_bebe_fr.py to drop images

---

locations/spiders/amtrak_ca_us.py
locations/spiders/amtrak_us.py

Runs in #10732 failed because network is not a main field, so moving it to extras.
This doesn't work locally as I get an empty response on the start_url, but could be a geo issue.

[amtrak_us] Fix and rename

---

locations/spiders/sos_br.py

Changed to amenity=training as the company seems to only have courses on technology. Fixes #10229

[sos_br] Changed category to amenity=training from office=business

---

locations/spiders/american_golf_gb.py

Was crashing on 1 `009:00 - 18:00`

[American Golf GB] Fix spider

---

locations/spiders/masoutis_gr.py

[Masoutis GR] Improve category

---

locations/spiders/california_closets_us.py

Drop images for california_closets_us

---

locations/spiders/hussar_grill_za_zm.py

```
'atp/brand/The Hussar Grill': 27,
'atp/brand_wikidata/Q130232305': 27,
'atp/category/amenity/restaurant': 27,
'atp/cdn/cloudflare/response_count': 32,
'atp/cdn/cloudflare/response_status_count/200': 32,
'atp/field/country/from_reverse_geocoding': 26,
'atp/item_scraped_host_count/www.hussargrill.co.za': 27, …
```

[hussar_grill_za_zm] Add spider

---

locations/spiders/vets4pets_gb.py

Going to say this is "ready", as the exception is a malformed response and an existing bug

Drop images for vets4pets_gb, rewrite to structured dataspider

---

locations/spiders/nike.py

I don't quite understand the website is invalid bit, as it only is set one possible way.

Drop images for nike #10679

---

locations/spiders/ticketmaster_au.py

```
'atp/brand/Ticketmaster': 17,
'atp/brand_wikidata/Q2609162': 17,
'atp/category/shop/ticket': 17,
'atp/field/country/from_spider_name': 17,
'atp/item_scraped_host_count/www.ticketmaster.com.au': 17,
'atp/nsi/perfect_match': 17,
```

[ticketmaster_au] Add spider

---

locations/spiders/topt_za.py

```
'atp/brand/TopT': 93,
'atp/brand_wikidata/Q116474797': 93,
'atp/category/shop/doityourself': 93,
'atp/field/city/missing': 93,
'atp/field/country/from_spider_name': 93,
'atp/field/image/missing': 93,
'atp/field/postcode/missing': 93,
'atp/field/twitter/missing': 93,
'atp/item_scraped_host_count/www.topt.co.za': 93,
```

[topt_za] Add spider

---

locations/spiders/careone_us.py
locations/spiders/vertiche_mx.py

Seem to have been forgotten in #9916

[WPStoreLocatorSpider] Drop depricated parse_item

---

locations/spiders/mathnasium.py

[Mathnasium] Restore opening hours

---

locations/spiders/van_schaik_bw_na_za.py

No coordinates available
```
'atp/brand/Van Schaik': 57,
'atp/brand_wikidata/Q116741158': 57,
'atp/category/shop/books': 57,
'atp/field/city/missing': 57,
'atp/field/image/missing': 57,
'atp/field/lat/missing': 57,
'atp/field/lon/missing': 57,
'atp/field/operator/missing': 57,
'atp/field/operator_wikidata/missing': 57,
'atp/field/postcode/missing': 57,
'atp/field/street_address/missing': 57,
'atp/field/twitter/missing': 57,
'atp/field/website/missing': 57,
'atp/item_scraped_host_count/www.vanschaik.com': 57,
'atp/nsi/perfect_match': 57,
```

[van_schaik_bw_na_za] Add spider

---

locations/spiders/italtile_bw_za.py

Waiting on https://github.com/osmlab/name-suggestion-index/commit/c5d00d132fd505c4c9eac79e4cfbe41c9f20997f for category
```
'atp/brand/Italtile': 16,
'atp/brand_wikidata/Q130415617': 16,
'atp/category/missing': 16,
'atp/field/city/missing': 16,
'atp/field/name/missing': 16,
'atp/field/postcode/missing': 16,
'atp/field/street_address/missing': 16,
'atp/item_scraped_host_count/www.italtile.co.za': 16,
'atp/nsi/brand_missing': 16,
```

[italtile_bw_za] Add spider

---

locations/spiders/nu_za.py

Waiting on https://github.com/osmlab/name-suggestion-index/commit/128f57fe54150163727d60b2477dce7281dc2a47 for category
```
{'atp/brand/Nü': 13,
'atp/brand_wikidata/Q130400175': 13,
'atp/category/missing': 13,
'atp/field/city/missing': 13,
'atp/field/country/from_website_url': 13,
'atp/field/postcode/missing': 13,
'atp/field/state/missing': 13,
'atp/field/street_address/missing': 13,
'atp/item_scraped_host_count/nu10.goreview.co.za': 1,
'atp/item_scraped_host_count/nu11.goreview.co.za': 1,
'atp/item_scraped_host_count/nu12.goreview.co.za': 1,
'atp/item_scraped_host_count/nu13.goreview.co.za': 1, …
```

[nu_za] Add spider

---

locations/spiders/econo_foods_za.py

Waiting on https://github.com/osmlab/name-suggestion-index/commit/5865617f0e980e1915b82745f7ee80d98aadcd26 for category
```
{'atp/brand/Econo Foods': 44,
'atp/brand_wikidata/Q130406968': 44,
'atp/category/missing': 44,
'atp/field/city/missing': 44,
'atp/field/country/from_spider_name': 44,
'atp/field/email/missing': 44,
'atp/field/image/missing': 44,
'atp/field/name/missing': 44,
'atp/field/operator/missing': 44,
'atp/field/operator_wikidata/missing': 44,
'atp/field/postcode/missing': 44,
'atp/field/state/missing': 44,
'atp/field/street_address/missing': 44,
'atp/field/twitter/missing': 44,
'atp/item_scraped_host_count/econofoods01.goreview.co.za': 1, …
```

[econo_foods_za] Add spider

---

locations/spiders/dr_max.py

```
{'atp/brand/Dr. Max': 3198,
'atp/brand_wikidata/Q56317371': 3198,
'atp/category/amenity/pharmacy': 3198,
'atp/category/multiple': 3198,
'atp/cdn/cloudflare/response_count': 10,
'atp/cdn/cloudflare/response_status_count/200': 5,
'atp/cdn/cloudflare/response_status_count/400': 5,
'atp/field/branch/missing': 59,
'atp/field/city/missing': 50,
'atp/field/email/missing': 2176,
'atp/field/image/invalid': 21,
'atp/field/image/missing': 2795,
'atp/field/lat/invalid': 4,
'atp/field/lat/missing': 272,
'atp/field/lon/invalid': 4,
'atp/field/lon/missing': 272,
'atp/field/opening_hours/missing': 390,
'atp/field/operator/missing': 3198,
'atp/field/operator_wikidata/missing': 3198,
'atp/field/phone/invalid': 38,
'atp/field/phone/missing': 419,
'atp/field/postcode/missing': 133, …
```

[DrMax] Add RO locations and fix some bugs (3198 locations)

---

locations/spiders/school_of_rock.py

```
'atp/brand/School of Rock': 419,
'atp/brand_wikidata/Q7756376': 419,
'atp/category/amenity/music_school': 419,
'atp/field/branch/missing': 419,
'atp/field/country/from_reverse_geocoding': 358,
'atp/field/country/from_website_url': 61,
'atp/field/image/missing': 419,
'atp/field/opening_hours/missing': 41,
'atp/field/operator/missing': 419,
'atp/field/operator_wikidata/missing': 419,
'atp/field/postcode/missing': 22,
'atp/field/twitter/missing': 419,
'atp/item_scraped_host_count/www.schoolofrock.com': 358,
'atp/item_scraped_host_count/www.schoolofrock.com.br': 55,
'atp/item_scraped_host_count/www.schoolofrock.com.pt': 2,
'atp/item_scraped_host_count/www.schoolofrock.com.tw': 1, …
```

[school_of_rock] Add spider

---

locations/spiders/ecco.py

Missing a store on Oxford Street.

[Ecco] Update spider to add missing store(s)

---

locations/spiders/booker_gb.py

Fixes https://github.com/alltheplaces/alltheplaces/issues/9208

[Booker GB] add spider

---

locations/spiders/pho_gb.py

Fix https://github.com/alltheplaces/alltheplaces/issues/10590

Add Pho (GB)

---

locations/spiders/whole_foods.py
locations/spiders/whole_foods_gb.py

US/CA
```python
{'atp/brand/Whole Foods Market': 531,
'atp/brand_wikidata/Q1809448': 531,
'atp/category/shop/supermarket': 531,
'atp/field/country/from_reverse_geocoding': 531,
'atp/field/email/missing': 531,
'atp/field/image/missing': 531,
'atp/field/operator/missing': 531,
'atp/field/operator_wikidata/missing': 531,
'atp/item_scraped_host_count/www.wholefoodsmarket.com': 531,
'atp/nsi/cc_match': 531,
'downloader/request_bytes': 544974,
'downloader/request_count': 547,
'downloader/request_method_count/GET': 547,
'downloader/response_bytes': 72236394,
'downloader/response_count': 547,
'downloader/response_status_count/200': 540,
'downloader/response_status_count/301': 4,
'downloader/response_status_count/302': 3,
'elapsed_time_seconds': 5.439519, …
```

[Whole Foods] Fix GB spider and modernise US

---

locations/spiders/chipotle.py

Better name stripping in Chipotle

---

locations/spiders/hm.py

Fix https://github.com/alltheplaces/alltheplaces/issues/10886

H&M: Specify category, as NSI lists them also as a surviellance operator?

---

locations/spiders/coop_no.py

Fix https://github.com/alltheplaces/alltheplaces/issues/10883

coop_no: Categories

---

locations/spiders/pdq_us.py

Fix https://github.com/alltheplaces/alltheplaces/issues/10458

PDQ Chicken 

---

locations/spiders/moo_moo_za.py

Ref #10030
```
'atp/brand/Moo Moo Meet & Whine': 6,
'atp/brand_wikidata/Q130378128': 6,
'atp/category/amenity/restaurant': 6,
'atp/field/country/from_spider_name': 6,
'atp/field/street_address/missing': 6,
'atp/item_scraped_host_count/moo1.goreview.co.za': 1,
'atp/item_scraped_host_count/moo2.goreview.co.za': 1,
'atp/item_scraped_host_count/moomoo5.goreview.co.za': 1, …
```

[moo_moo_za] Add spider

---

locations/spiders/colcacchio.py
locations/spiders/colcacchio_za.py

Ref #10030
```
"atp/brand/Col'Cacchio Pizzeria": 23,
'atp/brand_wikidata/Q25613087': 23,
'atp/category/amenity/restaurant': 23,
'atp/field/country/from_spider_name': 23,
'atp/field/postcode/missing': 23,
'atp/field/state/missing': 23,
'atp/item_scraped_host_count/col02.goreview.co.za': 1,
'atp/item_scraped_host_count/col03.goreview.co.za': 1,
'atp/item_scraped_host_count/col04.goreview.co.za': 1,
'atp/item_scraped_host_count/col06.goreview.co.za': 1,
'atp/item_scraped_host_count/col08.goreview.co.za': 1, …
```

[colcacchio_za] Add spider

---

locations/spiders/bossa_za.py

Ref #10030
```
{'atp/brand/Bossa': 25,
'atp/brand_wikidata/Q130376269': 25,
'atp/category/amenity/restaurant': 25,
'atp/field/country/from_spider_name': 25,
'atp/field/postcode/missing': 25,
'atp/field/street_address/missing': 25,
'atp/item_scraped_host_count/boss1.goreview.co.za': 1,
'atp/item_scraped_host_count/boss10.goreview.co.za': 1,
'atp/item_scraped_host_count/boss12.goreview.co.za': 1,
'atp/item_scraped_host_count/boss13.goreview.co.za': 1, …
```

[bossa_za] Add spider

---

locations/spiders/brow_art_23_us.py
locations/spiders/legends_barbers_za.py
locations/storefinders/yith.py

Add Yith Storefinder

---

locations/linked_data_parser.py
locations/spiders/cef_gb.py
locations/spiders/first_hotels.py
locations/spiders/go_outdoors.py
locations/spiders/great_western_railway_gb.py
locations/spiders/great_wolf_resorts_us.py

Fix https://github.com/alltheplaces/alltheplaces/issues/10399

Add parsing of hasMap to LinkedDataParser

---

locations/spiders/migros_tr.py

Migros is a bit messy in NSI currently...
```json
{
"atp/brand/Kiosk": 69,
"atp/brand/Macrocenter": 117,
"atp/brand/Migros": 2100,
"atp/brand/Migros Jet": 1174,
"atp/brand/Mion": 96,
"atp/brand_wikidata/Q123194881": 117,
"atp/brand_wikidata/Q1754510": 3439,
"atp/category/shop/chemist": 96,
"atp/category/shop/convenience": 1243,
"atp/category/shop/supermarket": 2187,
"atp/category/shop/wholesale": 30,
"atp/field/city/missing": 3556,
"atp/field/country/from_spider_name": 3556,
"atp/field/email/missing": 3556,
"atp/field/image/missing": 3556,
"atp/field/name/missing": 3439,
"atp/field/opening_hours/missing": 98,
"atp/field/operator/missing": 3556,
"atp/field/operator_wikidata/missing": 3556,
"atp/field/phone/missing": 4,
"atp/field/postcode/missing": 3556,
"atp/field/twitter/missing": 3556, …
```

[migros_tr] use another api, improve branding, parse hours

---

locations/spiders/hornbach_de.py

```python
{'atp/brand/HORNBACH': 97,
'atp/brand_wikidata/Q685926': 97,
'atp/category/shop/doityourself': 97,
'atp/field/operator/missing': 97,
'atp/field/operator_wikidata/missing': 97,
'atp/field/state/missing': 97,
'atp/field/twitter/missing': 97,
'atp/item_scraped_host_count/www.hornbach.de': 97,
'atp/nsi/cc_match': 97,
'downloader/request_bytes': 53276,
'downloader/request_count': 101,
'downloader/request_method_count/GET': 101,
'downloader/response_bytes': 7760576,
'downloader/response_count': 101,
'downloader/response_status_count/200': 101,
'elapsed_time_seconds': 2.866078,
'finish_time': datetime.datetime(2024, 10, 6, 18, 46, 20, 800998, …
```

[Hornbach DE] Use http2 + collect coords

---

locations/spiders/tesla.py

Fix https://github.com/alltheplaces/alltheplaces/issues/10892

Tesla - Update email if its a dict

---

locations/pipelines/address_clean_up.py
tests/test_address_clean_up.py

Fix https://github.com/alltheplaces/alltheplaces/issues/10889

William hill gb (and others) - Strip "N/A" from addresses

---

locations/spiders/gov_bio123_de.py

Update gov_bio123_de.py to fix "extras"

---

locations/pipelines/phone_clean_up.py
tests/test_pipeline_phone_cleanup.py

Ref #10694
This would get most of them, with the exception of things like "+48" and "2000000"

Reject phone numbers with no digits or all zeros

---

locations/spiders/burger_king_eg.py

Broken in the most recent run, should be more robust now

[burger_king_eg] Fix spider

---

locations/spiders/scouts_gg_gb_im_je.py

They seem to have changed to title case keys, rather than all lower case

[scouts_gg_gb_im_je] Fix spider

---

locations/spiders/vodacom_za.py

[vodacom_za] Add category

---

locations/spiders/topgolf_us.py

```py
{'atp/brand/Topgolf': 96,
'atp/brand_wikidata/Q7824379': 96,
'atp/category/leisure/sports_centre': 96,
'atp/field/email/missing': 96,
'atp/field/operator/missing': 96,
'atp/field/operator_wikidata/missing': 96,
'atp/field/twitter/missing': 96,
'atp/item_scraped_host_count/topgolf.com': 96,
'atp/nsi/perfect_match': 96,
'downloader/request_bytes': 973,
'downloader/response_bytes': 281921,
'elapsed_time_seconds': 3.081045,
'finish_time': datetime.datetime(2024, 10, 7, 20, 56, 11, 853098, …
```

New spider: Topgolf (96 locations)

---

locations/spiders/pls_us.py

```py
{'atp/brand/PLS Financial Services': 217,
'atp/brand_wikidata/Q126717580': 217,
'atp/category/shop/money_lender': 217,
'atp/field/branch/missing': 217,
'atp/field/city/missing': 217,
'atp/field/country/from_spider_name': 217,
'atp/field/email/missing': 217,
'atp/field/image/dropped': 217,
'atp/field/image/missing': 217,
'atp/field/opening_hours/missing': 175,
'atp/field/operator/missing': 217,
'atp/field/operator_wikidata/missing': 217,
'atp/field/postcode/missing': 217,
'atp/field/street_address/missing': 217,
'atp/field/twitter/missing': 217,
'atp/item_scraped_host_count/pls247.com': 217,
'atp/nsi/brand_missing': 217,
'downloader/request_bytes': 114231,
'downloader/request_count': 253,
'downloader/request_method_count/GET': 253,
'downloader/response_bytes': 1550524, …
```

New spider: PLS Financial Services (217 locations)

---

locations/dict_parser.py
locations/spiders/lego.py

```
'atp/brand/Lego': 516,
'atp/brand_wikidata/Q1063455': 516,
'atp/category/shop/toys': 516,
'atp/field/country/from_reverse_geocoding': 516,
'atp/field/email/missing': 516,
'atp/field/image/missing': 516,
'atp/field/opening_hours/missing': 90,
'atp/field/operator/missing': 516,
'atp/field/operator_wikidata/missing': 516,
'atp/field/phone/missing': 36,
'atp/field/postcode/missing': 44,
'atp/field/twitter/missing': 516,
'atp/item_scraped_host_count/www.lego.com': 557,
'atp/nsi/perfect_match': 516,
```

[lego] Add spider

---

locations/spiders/trader_joes_us.py
locations/storefinders/where2getit.py

Also move `name` to `branch`, detect warehouses and wine stores, and parse hours differently

Trader Joe's: Fix location and add extra tags

---

locations/commands/nsi.py
locations/name_suggestion_index.py

That brings me down to just 17 brands missing by wikidata in South Africa.

Skip dissolved brands when checking wikidata for missing

---

locations/spiders/the_fish_and_chip_co_za.py
locations/spiders/the_fish_and_chip_company_za.py

Rel: https://github.com/osmlab/name-suggestion-index/commit/2b4557713f66e236502cfe7998f9c9fdca452529

[The Fish & Chip Co ZA] Add spider

---

locations/spiders/misenso_ch.py

Fixes :` code has been refactored to use sitemap spider.`
{'atp/brand/Misenso': 27,
'atp/brand_wikidata/Q116151325': 27,
'atp/category/shop/optician': 27,
'atp/field/branch/missing': 27,
'atp/field/country/from_spider_name': 27,
'atp/field/lat/missing': 27,
'atp/field/lon/missing': 27,
'atp/item_scraped_host_count/www.misenso.ch': 27,
'atp/nsi/brand_missing': 27,
'downloader/request_bytes': 11880,
'downloader/request_count': 30,
'downloader/request_method_count/GET': 30,
'downloader/response_bytes': 253947, …

[Misenso CH] Fix Spider

---

locations/spiders/kuveyt_turk_tr.py

This was essentially broken as it was only returning one result.
Also fixes #10935
```
'atp/brand/Kuveyt Türk': 1715,
'atp/brand_wikidata/Q6036058': 1715,
'atp/category/amenity/atm': 1251,
'atp/category/amenity/bank': 464,
'atp/field/country/from_spider_name': 1715,
'atp/field/email/missing': 1715,
'atp/field/image/missing': 1715,
'atp/field/name/missing': 1251,
'atp/field/opening_hours/missing': 1715,
'atp/field/operator/missing': 464,
'atp/field/operator_wikidata/missing': 464,
'atp/field/phone/missing': 1250,
'atp/field/postcode/missing': 1715,
'atp/field/twitter/missing': 1715,
'atp/field/website/missing': 1715,
'atp/item_scraped_host_count/www.kuveytturk.com.tr': 1715,
'atp/nsi/cc_match': 1715,
'atp/operator/Kuveyt Türk': …
```

[kuveyt_turk_tr] Fix spider

---

locations/spiders/supa_quick.py

There have been a lot of timeout errors in the runs of this spider, including leading to some locations never being returned, so trying a longer timeout.

[supa_quick] Try longer timeout

---

locations/spiders/shell.py

Some locations are charging stations only, e.g. https://find.shell.com/us/fuel/13140386-53-third-ave. 
```json
{
"atp/brand/Shell": 42851,
"atp/brand/Shell Select": 6758,
"atp/brand_wikidata/Q110716465": 42851,
"atp/brand_wikidata/Q124359752": 6758,
"atp/category/amenity/charging_station": 1570,
"atp/category/amenity/fuel": 41281,
"atp/category/shop/convenience": 6758,
"atp/field/branch/missing": 49609,
"atp/field/city/missing": 2101,
"atp/field/email/missing": 49609,
"atp/field/image/missing": 49609,
"atp/field/name/missing": 1570,
"atp/field/opening_hours/missing": 18715,
"atp/field/operator/missing": 48039,
"atp/field/operator_wikidata/missing": 48039,
"atp/field/phone/invalid": 764,
"atp/field/phone/missing": 11831,
"atp/field/postcode/missing": 13042,
"atp/field/state/missing": 3591, …
```

[shell] change category for charging stations

---

locations/spiders/postbank_bg.py

Use Cyrillic brand name for postbank_bg.py

---

locations/spiders/leroy_merlin.py
locations/spiders/leroy_merlin_pl.py

New `man_made=surveillance` [entry has added to NSI](https://nsi.guide/index.html?t=operators&k=man_made&v=surveillance&tt=q889624) for this brand.

[leroy_merlin][leroy_merlin_pl] add category

---

locations/spiders/chss_gb.py

based on how it is mapped in OSM

fix name in chss_gb.py

---

locations/spiders/chris_willemse_cycles_za.py
locations/spiders/cycle_lab_za.py
locations/spiders/the_pro_shop_za.py

Waiting on https://github.com/osmlab/name-suggestion-index/commit/7714366474c0141c40b16ff1b4a9866db511fd41 and https://github.com/osmlab/name-suggestion-index/commit/3a38d3f6339b302e424e0701a25ef0cc58d9327b for categories
```
'atp/brand/The Pro Shop': 36,
'atp/brand_wikidata/Q130488660': 36,
'atp/category/missing': 36,
'atp/field/city/missing': 36,
'atp/field/country/from_spider_name': 36,
'atp/field/name/missing': 36,
'atp/field/postcode/missing': 36,
'atp/field/state/missing': 36,
'atp/field/website/missing': 36, …
```

[the_pro_shop_za] [chris_willemse_cycles_za] [cycle_lab_za] Add spiders

---

locations/spiders/steers_za.py
locations/storefinders/yext_search.py

```
'atp/brand/Steers': 666,
'atp/brand_wikidata/Q3056765': 666,
'atp/category/amenity/fast_food': 666,
'atp/cdn/cloudflare/response_count': 14,
'atp/cdn/cloudflare/response_status_count/200': 14,
'atp/field/image/missing': 666,
'atp/field/operator/missing': 666,
'atp/field/operator_wikidata/missing': 666,
'atp/field/twitter/missing': 666,
'atp/item_scraped_host_count/location.steers.co.za': 666,
'atp/nsi/perfect_match': 666,
```

[steers_za] Refactor to YextSearchSpider

---

locations/spiders/la_halle_fr.py

`Structured Data` is no longer present, hence code refactored using API to fix the spider.
```
{'atp/brand/La Halle': 328,
'atp/brand_wikidata/Q100728296': 328,
'atp/category/shop/clothes': 328,
'atp/field/email/missing': 328,
'atp/field/image/missing': 328,
'atp/field/operator/missing': 328,
'atp/field/operator_wikidata/missing': 328,
'atp/field/twitter/missing': 328,
'atp/item_scraped_host_count/www.lahalle.com': 328,
'atp/nsi/perfect_match': 328,
'downloader/request_bytes': 408,
'downloader/response_bytes': 103726, …
```

[LaHalleFR] Fix Spider

---

locations/spiders/usps_collection_boxes.py

[usps_collection_boxes] process post box type

---

locations/spiders/sportsmans_warehouse_na_za.py

Waiting on https://github.com/osmlab/name-suggestion-index/commit/4523da3399faaa41cc732828313f7d48c8108720 for category
```
'atp/brand/Sportsmans Warehouse': 49,
'atp/brand_wikidata/Q130485344': 49,
'atp/category/missing': 49,
'atp/field/country/from_reverse_geocoding': 49,
'atp/field/image/missing': 49,
'atp/field/name/missing': 49,
'atp/field/operator/missing': 49,
'atp/field/operator_wikidata/missing': 49,
'atp/field/twitter/missing': 49,
'atp/item_scraped_host_count/www.sportsmanswarehouse.co.za': 49,
'atp/nsi/brand_missing': 49,
```

[sportsmans_warehouse_na_za] Add spider

---

locations/spiders/outdoor_warehouse_na_za.py
locations/spiders/outdoor_warehouse_za.py

Waiting on https://github.com/osmlab/name-suggestion-index/commit/3a5d670a6644cd12f33b253c5b6cad47458bb1e0 for category
```
'atp/brand/Outdoor Warehouse': 37,
'atp/brand_wikidata/Q130485369': 37,
'atp/category/missing': 37,
'atp/field/country/from_spider_name': 37,
'atp/field/image/missing': 37,
'atp/field/name/missing': 37,
'atp/field/operator/missing': 37,
'atp/field/operator_wikidata/missing': 37,
'atp/field/twitter/missing': 37,
'atp/item_scraped_host_count/www.outdoorwarehouse.co.za': 37,
'atp/nsi/brand_missing': 37,
```

[outdoor_warehouse_za] Add spider

---

locations/spiders/fibank_bg.py

Based on quick remote check and comparing with OSM.
@Dimitar5555 can you check also here?

fix name for fibank_bg

---

locations/spiders/ccbank_bg.py

@Dimitar5555 can you check also here?
Based on quick remote check and comparing with OSM.

name for ccbank_bg

---

locations/spiders/econt_bg.py

@Dimitar5555 can you check also here?
Based on quick remote check and comparing with OSM.

English name in Bulgaria - econt_bg

---

locations/spiders/t_market_bg.py

@Dimitar5555 - can you take a quick look at this one?

fix name for t_market_bg

---

locations/spiders/technopolis_bg.py

@Dimitar5555 - can you take a quick look at this one?

fix name in technopolis_bg

---

locations/spiders/roadhouse_it.py

[Roadhouse IT] Add spider (Fixes #11019)

---

locations/spiders/jeff_de_bruges.py

Fixes : code refactored to use sitemap spider to fix spider.
{'atp/brand/Jeff de Bruges': 518,
'atp/brand_wikidata/Q3176626': 518,
'atp/category/shop/chocolate': 518,
'atp/field/branch/missing': 518,
'atp/field/city/missing': 518,
'atp/field/country/from_spider_name': 518,
'atp/field/operator/missing': 518,
'atp/field/operator_wikidata/missing': 518,
'atp/field/postcode/missing': 518,
'atp/field/state/missing': 518,
'atp/field/street_address/missing': 518,
'atp/field/twitter/missing': 518,
'atp/item_scraped_host_count/www.jeff-de-bruges.com': 519,
'atp/nsi/perfect_match': 518,
'downloader/request_bytes': 244463,
'downloader/request_count': 521, …

[JeffDeBruges] Fix Spider

---

locations/spiders/avoska_ru.py

[avoska_ru] Fix coordinates for avoska_ru spider

---

locations/spiders/ikes.py
locations/spiders/ikes_us.py

```
{"atp/brand/Ike's Love & Sandwiches": 102,
'atp/brand_wikidata/Q112028897': 102,
'atp/category/amenity/fast_food': 102,
'atp/field/email/missing': 102,
'atp/field/image/dropped': 102,
'atp/field/image/missing': 102,
'atp/field/operator/missing': 102,
'atp/field/operator_wikidata/missing': 102,
'atp/item_scraped_host_count/locations.ikessandwich.com': 102,
'atp/nsi/perfect_match': 102,
'downloader/request_bytes': 54160,
'downloader/request_count': 110,
'downloader/request_method_count/GET': 110,
'downloader/response_bytes': 2105491,
'downloader/response_count': 110,
'downloader/response_status_count/200': 106,
'downloader/response_status_count/301': 4,
'dupefilter/filtered': 3,
'elapsed_time_seconds': 1.90704, …
```

[Ikes] Fix Spider

---

locations/spiders/sephora_mx.py

note that https://github.com/alltheplaces/alltheplaces/blob/master/locations/spiders/sephora_pl.py is already correct
see https://www.sephora.com.mx/

[Sephora MX] Chanege to shop=cosmetics

---

locations/spiders/kfc_my.py

This has been finishing with an error in the last few runs, but should now be more robust.
Currently all hours are being parsed

[kfc_my] Fix parsing of hours

---

locations/spiders/shoe_zone_gb.py

I'm sure that there must be an easier way to get the structured data spider to get the opening hours from scraping the page.

[Shoe Zone GB] Add address and opening hours

---

locations/spiders/mcdonalds_gt.py

maybe, maybe these should be put into branch key

mcdonalds_gt - item.pop("name")

---

locations/spiders/jewson_gb.py

maybe, maybe these should be put into branch key

drop name in jewson_gb.py

---

locations/spiders/yoursclothing_gb.py

https://www.openstreetmap.org/search?query=YoursClothing
https://www.openstreetmap.org/search?query=Yours+Clothing

add space to yoursclothing_gb name

---

locations/spiders/kaiser_permanente_us.py

* Work around redirects being counted as duplicate requests
* Work around missing StructuredData
* Use a numeric ref instead of URL
* Omit corporate Facebook and Twitter
* Omit corporate phone number

Kaiser Permanente: Fix missing entries

---

locations/spiders/vkusno_i_tochka_ru.py

Nothing indicates that latinization of Вкусно – и точка is used

Put local name in vkusno_i_tochka_ru

---

locations/spiders/fjallraven.py

also based on OpenStreetMap tagging

fjallraven - set SHOP_OUTDOOR

---

locations/spiders/dpd_de.py

If it is a post partner, then it is not a post office but just an additional aspect/facet of another POI

fix dpd_de tagging

---

locations/spiders/milky_lane_za.py

Waiting on https://github.com/osmlab/name-suggestion-index/commit/6b5e66967a16f788fa3d108789a3b4fe80555ce4 for category
```
'atp/brand/Milky Lane': 108,
'atp/brand_wikidata/Q128223693': 108,
'atp/category/missing': 108,
'atp/field/image/missing': 108,
'atp/field/operator/missing': 108,
'atp/field/operator_wikidata/missing': 108,
'atp/field/twitter/missing': 108,
'atp/item_scraped_host_count/location.milkylane.co.za': 108,
'atp/nsi/brand_missing': 108,
```

[milky_lane_za] Add spider

---

locations/spiders/louisa_coffee_tw.py

based on checking OSM data like other similar

use non-english letters in louisa_coffee_tw

---

locations/spiders/intersport_fi.py

swap lat lon in intersport_fi

---

locations/spiders/kop_and_kande.py

from quick look at their website and OSM it seems rather SHOP_HOUSEWARE

change kop_and_kande type

---

locations/spiders/papa_johns_gb.py

Ref #11100
Also remove generic facebook

[papa_johns_gb] Fix website

---

locations/spiders/starbucks_tw.py

[starbucks_tw] Fix brand

---

locations/spiders/ever_new_ca.py

[Ever New] Fix brand

---

locations/spiders/kafkas_gr.py

[Kafkas GR] Drop hardcoded brand

---

locations/spiders/ben_and_jerrys.py

[ben_and_jerrys] Try to filter out more suppliers

---

locations/spiders/king_pie_za.py

[king_pie_za] Remove generic website

---

locations/spiders/better_gb.py

but keep unique ones, there are 5 unique facebook links, and all current twitter links are generic.

[better_gb] drop generic social media links

---

locations/spiders/philz_coffee_us.py

maybe some pipeline can do it for all spiders and fields? Doing it manually seems waste of time but I can create another list enumerating cases where this happens.

[philz_coffee_us] remove whitespace suffix in branch

---

locations/spiders/keurslager_nl.py

Fixes : code has been refactored to fix the spider using new approach.
{'atp/brand/Keurslager': 190,
'atp/brand_wikidata/Q114637402': 190,
'atp/category/shop/butcher': 190,
'atp/field/branch/missing': 190,
'atp/field/city/missing': 190,
'atp/field/country/from_spider_name': 190,
'atp/field/image/missing': 190,
'atp/field/operator/missing': 190,
'atp/field/operator_wikidata/missing': 190,
'atp/field/postcode/missing': 190,
'atp/field/state/missing': 190,
'atp/field/twitter/missing': 190,
'atp/field/website/invalid': 2,
'atp/item_scraped_host_count/www.keurslager.nl': 190,
'atp/nsi/perfect_match': 190,
'downloader/request_bytes': 92005,
'downloader/request_count': 192, …

[KeurslagerNL] Fix Spider

---

locations/spiders/mussala_bg.py

[Mussala BG] Collect opening hours

---

locations/spiders/mio_amore_in.py

Rel: https://github.com/osmlab/name-suggestion-index/pull/10055

[Mio Amore IN] Add spider

---

locations/spiders/ernst_young.py

ernst_young addr:full `One Commerce Square 2005 Market Street, Suite 700`  and addr:country `US` 
ernst_young addr:full `2100 One PPG Place`  and addr:country `US` 
ernst_young addr:full `Parque Las Americas 1 235 Federico Costa St. - Suite 410 -`  and addr:country `US` 
ernst_young addr:full `EY Providence 40 Westminster Street 8th Floor`  and addr:country `US` 
ernst_young addr:full `2 W. Washington, Suite 901`  and addr:country `US` 
ernst_young addr:full `1110 Market Street, Suite 216`  and addr:country `US`
ernst_young addr:full `6070 Poplar Ave, Suite 370`  and addr:country `US` 
ernst_young addr:full `222 2nd Avenue South, Suite 2100`  and addr:country `US` 
ernst_young addr:full `401 Congress, Suite 3200`  and addr:country `US` 
ernst_young addr:full `One Victory Park, 2323 …

[ernst_young] put address, generally without country etc into street_address

---

locations/spiders/netto_salling_de.py
locations/spiders/netto_salling_dk.py
locations/spiders/netto_salling_pl.py

Sitemap for DE and DK from netto_salling  changed and were no longer providing data.  Only locations for PL were coming from spider.  
I created new spiders for DE and DK, and renamed original netto_salling spider to represent PL only.

Fix Netto Salling

---

locations/spiders/rituals.py

Add [Rituals](https://www.rituals.com/) cosmetics stores worldwide.

[rituals] Add spider (1165 stores)

---

locations/spiders/wuerth_de.py

Add [Würth](https://www.wuerth.de/), a B2B hardware store chain in DE.

[wuerth_de] Add spider (598 stores)

---

locations/spiders/spring_market_us.py

Add supermarket tag to Spring Market US

---

locations/spiders/grandvision.py

Removed Grandvision social media tags because they aren't POI-specific

---

locations/microdata_parser.py
tests/test_microdata_parser.py

This is probably not the most "correct" way to parse a new format, but it's close enough and it works. The change is only a few lines of code but I'm splitting it into a separate PR because it could affect lots of other spiders.

Tweak MicrodataParser to also support RDFa

---

locations/spiders/ernstings_family.py

[Ernsting's family](https://www.ernstings-family.de/) is a clothes store chain in DE and AT.

[ernstings_family] Add spider (1937 shops)

---

locations/spiders/leeann_chin_us.py

`Structured Data` is no longer present, hence spider code refactored to utilize `JSON Blob`.
```
{'atp/brand/Leeann Chin': 41,
'atp/brand_wikidata/Q6515716': 41,
'atp/category/amenity/restaurant': 41,
'atp/field/street_address/missing': 41,
'atp/item_scraped_host_count/www.leeannchin.com': 41,
'atp/nsi/brand_missing': 41,
'downloader/request_bytes': 617,
'downloader/response_bytes': 42164,
'elapsed_time_seconds': 2.78494, …
```

[Leeann Chin US] Fix spider

---

locations/spiders/hsbc_tw.py
locations/spiders/loop_fitness_dk.py
locations/spiders/pizzeria_105_pl.py
locations/spiders/wickes_gb.py
locations/structured_data_spider.py

Rel: https://github.com/alltheplaces/alltheplaces/pull/11210
> the page contains Microdata for both Place and Restaurant both were producing POIs. Josh was right Place to too generic to be included in the default wanted types.
I would also like to drop some of the rare types from the default list as well, but I don't actually have a valid reason right now other than personal preference.

[Core] Drop Place from default wanted_types

---

locations/spiders/starbucks_eu.py

Starbucks changed api version on the website.
```json
{
"atp/brand/Starbucks": 3457,
"atp/brand_wikidata/Q37158": 3457,
"atp/category/amenity/cafe": 3457,
"atp/cdn/cloudflare/response_count": 18245,
"atp/cdn/cloudflare/response_status_count/200": 18244,
"atp/cdn/cloudflare/response_status_count/404": 1,
"atp/field/email/missing": 3457,
"atp/field/image/missing": 3457,
"atp/field/opening_hours/missing": 429,
"atp/field/operator/missing": 3457,
"atp/field/operator_wikidata/missing": 3457,
"atp/field/phone/invalid": 14,
"atp/field/phone/missing": 2239,
"atp/field/postcode/missing": 94,
"atp/field/state/missing": 3457,
"atp/field/street_address/missing": 9,
"atp/field/twitter/missing": 3457,
"atp/field/website/missing": 3457,
"atp/item_scraped_host_count/www.starbucks.co.uk": 531847, …
```

[starbucks_eu] fix spider

---

locations/spiders/metro_cash_and_carry.py

`xpath` and `user_agent` modified to fix the spider.
```
{'atp/brand/Makro': 106,
'atp/brand/Metro': 531,
'atp/brand_wikidata/Q13610282': 531,
'atp/brand_wikidata/Q704606': 106,
'atp/category/shop/wholesale': 637,
'atp/field/branch/missing': 637,
'atp/field/city/missing': 637,
'atp/field/country/from_reverse_geocoding': 47,
'atp/field/country/from_website_url': 590,
'atp/field/image/missing': 637,
'atp/field/opening_hours/missing': 637,
'atp/field/operator/missing': 637,
'atp/field/operator_wikidata/missing': 637,
'atp/field/postcode/missing': 637,
'atp/field/state/missing': 590,
'atp/field/street_address/missing': 637,
'atp/field/twitter/missing': 637, …
```

[Metro Cash And Carry] Fix spider

---

locations/spiders/mcdonalds_il.py

Spider was using wrong q-code.   IL has it's own qcode for McDonald's as per [NSI](https://nsi.guide/index.html?t=brands&k=amenity&v=fast_food&tt=q12061542).   Israel is excluded from [Q38076](https://nsi.guide/index.html?t=brands&k=amenity&v=fast_food&tt=q38076).
stats:
```
{"atp/brand/McDonald's": 230,
'atp/brand_wikidata/Q12061542': 230,
'atp/category/amenity/fast_food': 230,
'atp/cdn/cloudflare/response_count': 232,
'atp/cdn/cloudflare/response_status_count/200': 232,
'atp/field/branch/missing': 230,
'atp/field/city/missing': 230,
'atp/field/country/from_spider_name': 230,
'atp/field/email/missing': 230,
'atp/field/image/missing': 230,
'atp/field/opening_hours/missing': 230,
'atp/field/operator/missing': 230,
'atp/field/operator_wikidata/missing': 230,
'atp/field/postcode/missing': …
```

[mcdonalds_il] Fix spider by updating qcode (230 locations)

---

locations/spiders/coffee_fellows.py

Add [Coffee Fellows](https://coffee-fellows.com/), a coffee chain mostly in DE and some other countries.

[coffee_fellows] Add spider (259 locations)

---

locations/spiders/losteria.py

Add [L’Osteria](https://losteria.net/), an Italian-style restaurant chain mostly in DE, but also AT and the neighbor countries.

[losteria] Add spider (153 locations)

---

locations/spiders/smashburger.py

This wasn't actually broken, just getting 403s so this probably wont fix the spider. It runs fine locally from GB, the issue was duplicates, the page contains Microdata for both `Place` and `Restaurant` both were producing POIs. Josh was right `Place` to too generic to be included in the default wanted types.
```python
{'atp/brand/Smashburger': 204,
'atp/brand_wikidata/Q17061332': 204,
'atp/category/amenity/fast_food': 204,
'atp/cdn/cloudflare/response_count': 261,
'atp/cdn/cloudflare/response_status_count/200': 259,
'atp/cdn/cloudflare/response_status_count/403': 2,
'atp/field/branch/missing': 204,
'atp/field/email/missing': 204,
'atp/field/operator/missing': 204,
'atp/field/operator_wikidata/missing': 204,
'atp/field/twitter/missing': 204, …
```

[Smashburger] Remove duplicates

---

locations/spiders/dsw.py

```python
{'atp/brand/DSW': 524,
'atp/brand_wikidata/Q5206207': 524,
'atp/category/shop/shoes': 524,
'atp/cdn/cloudflare/response_count': 528,
'atp/cdn/cloudflare/response_status_count/200': 528,
'atp/field/email/missing': 524,
'atp/field/image/missing': 524,
'atp/field/operator/missing': 524,
'atp/field/operator_wikidata/missing': 524,
'atp/item_scraped_host_count/stores.dsw.ca': 26,
'atp/item_scraped_host_count/stores.dsw.com': 498,
'atp/nsi/perfect_match': 524,
'downloader/request_bytes': 301952,
'downloader/request_count': 528,
'downloader/request_method_count/GET': 528,
'downloader/response_bytes': 13414672,
'downloader/response_count': 528,
'downloader/response_status_count/200': 528,
'elapsed_time_seconds': 6.327109, …
```

[DSW] Modernise spider

---

locations/spiders/mcdonalds_it.py
locations/spiders/metro_cash_and_carry.py

Rel: https://github.com/alltheplaces/alltheplaces/issues/11016#issuecomment-2433330530

[McDonald's IT] Flag proxy

---

locations/spiders/larosas.py
locations/spiders/metro_cash_and_carry.py

`Fixes : code refactored to use structured data to fix spider`
{"atp/brand/Larosa's": 59,
'atp/brand_wikidata/Q6460833': 59,
'atp/category/amenity/restaurant': 59,
'atp/field/branch/missing': 59,
'atp/field/email/missing': 59,
'atp/field/opening_hours/missing': 59,
'atp/field/operator/missing': 59,
'atp/field/operator_wikidata/missing': 59,
'atp/item_scraped_host_count/www.larosas.com': 59,
'atp/nsi/perfect_match': 59,
'downloader/request_bytes': 42760,
'downloader/request_count': 64,
'downloader/request_method_count/GET': 64,
'downloader/response_bytes': 670714,
'downloader/response_count': 64,
'downloader/response_status_count/200': 62,
'dupefilter/filtered': 1,
'elapsed_time_seconds': 79.356485,
'finish_time': …

[Larosas] Fix Spider

---

locations/spiders/metro_cash_and_carry.py
locations/spiders/studenac_hr.py

```json
{
"atp/brand/Studenac": 1318,
"atp/brand_wikidata/Q65156084": 1318,
"atp/category/shop/convenience": 1318,
"atp/field/branch/missing": 1318,
"atp/field/city/missing": 1318,
"atp/field/country/from_spider_name": 1318,
"atp/field/email/missing": 1318,
"atp/field/image/missing": 1318,
"atp/field/opening_hours/missing": 15,
"atp/field/operator/missing": 1318,
"atp/field/operator_wikidata/missing": 1318,
"atp/field/phone/missing": 1318,
"atp/field/postcode/missing": 1318,
"atp/field/state/missing": 1318,
"atp/field/street_address/missing": 1318,
"atp/field/twitter/missing": 1318,
"atp/item_scraped_host_count/www.studenac.hr": 1318,
"atp/nsi/perfect_match": 1318,
"downloader/exception_count": 2,
"downloader/exception_type_count/twisted.internet.error.TCPTimedOutError": 2, …
```

[studenac_hr] fix spdier

---

locations/spiders/medical_city_healthcare.py

{'atp/brand/Medical City Healthcare': 118,
'atp/category/amenity/clinic': 53,
'atp/category/amenity/hospital': 56,
'atp/category/healthcare/centre': 6,
'atp/category/healthcare/psychotherapist': 2,
'atp/category/healthcare/rehabilitation': 1,
'atp/category/multiple': 109,
'atp/field/branch/missing': 118,
'atp/field/brand_wikidata/missing': 118,
'atp/field/country/from_reverse_geocoding': 118,
'atp/field/email/missing': 118,
'atp/field/image/missing': 118,
'atp/field/opening_hours/missing': 118,
'atp/field/operator/missing': 118,
'atp/field/operator_wikidata/missing': 118,
'atp/field/website/missing': 4,
'atp/item_scraped_host_count/www.medicalcityhealthcare.com': 118, …

[MedicalCityHealthcare] Fix Spider

---

locations/spiders/inpost_gb.py

```python
{'atp/brand/InPost': 8122,
'atp/brand_wikidata/Q3182097': 8122,
'atp/category/amenity/parcel_locker': 8122,
'atp/field/branch/missing': 8122,
'atp/field/country/from_spider_name': 8122,
'atp/field/email/missing': 8122,
'atp/field/image/missing': 8122,
'atp/field/operator/missing': 8122,
'atp/field/operator_wikidata/missing': 8122,
'atp/field/phone/missing': 8122,
'atp/field/twitter/missing': 8122,
'atp/item_scraped_host_count/api-uk-global-points.easypack24.net': 8122,
'atp/nsi/cc_match': 8122,
'downloader/request_bytes': 64909,
'downloader/request_count': 110,
'downloader/request_method_count/GET': 110,
'downloader/response_bytes': 1439929, …
```

[InPost GB] Safer opening hours parsing

---

locations/spiders/kindred_healthcare.py

`Fixes: updated parse method along with sitemap url to fix spider`
{'atp/brand/Kindred Healthcare': 61,
'atp/brand_wikidata/Q921363': 61,
'atp/category/amenity/hospital': 61,
'atp/category/multiple': 61,
'atp/field/branch/missing': 61,
'atp/field/city/missing': 61,
'atp/field/email/missing': 61,
'atp/field/image/missing': 61,
'atp/field/lat/missing': 61,
'atp/field/lon/missing': 61,
'atp/field/opening_hours/missing': 61,
'atp/field/postcode/missing': 61,
'atp/field/state/missing': 61,
'atp/field/street_address/missing': 61,
'atp/field/twitter/missing': 61,
'atp/item_scraped_host_count/www.kindredhospitals.com': 61,
'atp/nsi/perfect_match': 61,
'atp/operator/Kindred Healthcare': 61,
'atp/operator_wikidata/Q921363': 61,
'downloader/request_bytes': 26547, …

[KindredHealthcare] Fix Spider

---

locations/spiders/traficon_cz.py

Related NSI PR: https://github.com/osmlab/name-suggestion-index/pull/10087

[traficon_cz] Add spider (185 locations)

---

locations/spiders/godiva_chocolatier_jp.py

based on provided image, their website and typical markings in OSM: they use shorter name version

[Godiva JP] Update brand - Needs to be changed in NSI as well.

---

locations/spiders/dracik.py

Add spider for Dráčik in Czechia, Slovakia.
The have server-rendered framents for branch detail modals. HTML extraction is fairly easy.
Card and wheelchair accessibility are little hacky. Opening hours extraction works well.

[dracik] Add spider (144 locations)

---

locations/spiders/caseys_general_store.py

I've not ran the spider though, it's very heavy on the geoblocking, but looking at the last run, the pages were fetched, just not parsed correctly.

[Casey's General Store] Fix spider

---

locations/spiders/landi_ch.py

based on feedback from OSM IRC

[Landi CH] Change Landi to country store

---

locations/spiders/lidl_at.py

I also tested other big Lidl spiders that inherit from `LidlATSpider` to make sure I don't break hours there.

[lidl_it][lidl_cy] fix opening hours

---

locations/spiders/united_dairy_farmers_us.py

[united_dairy_farmers_us] put street address into street_address

---

locations/spiders/anthropologie.py

fixes #11246
removes 256 "addr:full" like "5406 Kingston Pike"
addr:street_address is present 256 times

anthropologie - it is not actually addr:full

---

locations/spiders/montblanc.py

Spider was failing due to error in parsing now non existent opening times. Code removed.

[MontBlanc] Remove opening times

---

locations/spiders/sunglass_hut_in.py

Fixing errors like this
2024-10-26 01:14:42 [sunglass_hut_in] ERROR: Invalid type int on postcode, expected (<class 'str'>,)

[SunglassHutIN] Fix postcode type error

---

locations/spiders/meny_dk.py

Fix errors of this type
2024-10-26 00:26:42 [meny_dk] ERROR: Invalid type list on name, expected (<class 'str'>,)

[MenyDK] Fix name type error

---

locations/spiders/minimart_bg.py

{'atp/brand/Minimart': 120,
'atp/brand_wikidata/Q119168386': 120,
'atp/category/shop/convenience': 120,
'atp/field/branch/missing': 120,
'atp/field/email/missing': 120,
'atp/field/image/missing': 120,
'atp/field/operator/missing': 120,
'atp/field/operator_wikidata/missing': 120,
'atp/field/phone/missing': 120,
'atp/field/postcode/missing': 113,
'atp/field/state/missing': 120,
'atp/field/street_address/missing': 120,
'atp/field/twitter/missing': 120,
'atp/item_scraped_host_count/mini-mart.bg': 120,
'atp/nsi/perfect_match': 120,
'downloader/request_bytes': 642,
'downloader/response_bytes': 9196, …

[MinimartBG] Fix Spider

---

locations/spiders/anthropologie.py

fixes #11199
state before PR: https://github.com/alltheplaces/alltheplaces/pull/11269#issuecomment-2443217416

[anthropologie] drop nonexisting ones

---

locations/spiders/pos_indonesia_id.py

Ref: https://en.wikipedia.org/wiki/Pos_Indonesia
Around 4k post office locations: https://www.posindonesia.co.id/en
```
{'atp/brand/Pos Indonesia': 4202,
'atp/brand_wikidata/Q4273095': 4202,
'atp/category/amenity/mailroom': 13,
'atp/category/amenity/post_office': 4189,
'atp/field/branch/missing': 4202,
'atp/field/city/missing': 3123,
'atp/field/country/from_spider_name': 4202,
'atp/field/email/missing': 4202,
'atp/field/image/missing': 4202,
'atp/field/lat/invalid': 47,
'atp/field/lat/missing': 182,
'atp/field/lon/invalid': 4,
'atp/field/lon/missing': 182,
'atp/field/opening_hours/missing': 4202,
'atp/field/phone/missing': 283,
'atp/field/postcode/missing': 4202, …
```

[Pos Indonesia ID] Add Spider (4202 locations)

---

locations/spiders/tvoe_ru.py

Exactly 300 POIs is suspicious, but that's what I see on https://tvoe.ru/contacts/ too.

[tvoe_ru] add spider (300 pois)

---

locations/spiders/dog_haus_us.py

```py
{'atp/brand/Dog Haus': 60,
'atp/brand_wikidata/Q105529843': 60,
'atp/category/amenity/fast_food': 60,
'atp/category/multiple': 55,
'atp/item_scraped_host_count/locations.doghaus.com': 60,
'atp/nsi/perfect_match': 60,
'downloader/request_bytes': 812,
'downloader/response_bytes': 552878, …
```

DogHausUS: Rewrite to use new API

---

locations/spiders/max.py

Max burgers is originally from SE but also present in DK, NO and PL. Add their locations by scraping the country-specific locator pages.
```
2024-11-04 21:27:37 [scrapy.statscollectors] INFO: Dumping Scrapy stats:
{'atp/brand/Max': 194,
'atp/brand_wikidata/Q1912172': 194,
'atp/category/amenity/fast_food': 194,
'atp/field/branch/missing': 194,
'atp/field/email/missing': 194,
'atp/field/image/missing': 194,
'atp/field/opening_hours/missing': 194,
'atp/field/operator/missing': 194,
'atp/field/operator_wikidata/missing': 194,
'atp/field/phone/missing': 194,
'atp/field/state/missing': 194,
'atp/field/twitter/missing': 194,
'atp/field/website/missing': 194,
'atp/item_scraped_host_count/www.max.dk': 5,
'atp/item_scraped_host_count/www.max.se': 155, …
```

[max] Re-add countries DK, NO, PL

---

locations/spiders/food_city_us.py
locations/spiders/raleys_us.py

Might also want to consider renaming to avoid confusion with the other Food City (which is what has the other QID)

Rewrite FoodCityUS

---

locations/spiders/independent_financial_us.py

{'atp/brand/Independent Financial': 178,
'atp/brand_wikidata/Q6016398': 178,
'atp/category/amenity/atm': 86,
'atp/category/amenity/bank': 92,
'atp/cdn/cloudflare/response_count': 181,
'atp/cdn/cloudflare/response_status_count/200': 181,
'atp/field/branch/missing': 178,
'atp/field/image/dropped': 87,
'atp/field/image/missing': 87,
'atp/field/operator/missing': 178,
'atp/field/operator_wikidata/missing': 178,
'atp/item_scraped_host_count/locations.ifinancial.com': 178,
'atp/nsi/brand_missing': 178,
'downloader/request_bytes': 101031,
'downloader/request_count': 181,
'downloader/request_method_count/GET': 181,
'downloader/response_bytes': 3762640,
'downloader/response_count': 181, …

[IndependentFinancialUS] Fix Spider

---

locations/spiders/bmo.py
locations/spiders/food_city_arizona_us.py
locations/spiders/food_city_southeast_us.py

```py
{'atp/brand/Food City': 147,
'atp/brand_wikidata/Q16981107': 147,
'atp/category/shop/supermarket': 147,
'atp/field/branch/missing': 147,
'atp/field/country/from_spider_name': 147,
'atp/field/email/missing': 147,
'atp/field/image/missing': 147,
'atp/field/operator/missing': 147,
'atp/field/operator_wikidata/missing': 147,
'atp/field/twitter/missing': 147,
'atp/geometry/null_island': 3,
'atp/item_scraped_host_count/www.foodcity.com': 157,
'atp/nsi/perfect_match': 147,
'downloader/request_bytes': 18648,
'downloader/request_method_count/GET': 17,
'downloader/response_bytes': 304131,
'downloader/response_count': 17,
'downloader/response_status_count/200': 17, …
```

Add the other Food City (147 locations)

---

locations/spiders/bim_tr.py

```
{'atp/brand/BİM': 11782,
'atp/brand_wikidata/Q1022075': 11782,
'atp/category/shop/supermarket': 11782,
'atp/field/country/from_spider_name': 11782,
'atp/field/email/missing': 11782,
'atp/field/image/missing': 11782,
'atp/field/lat/missing': 11782,
'atp/field/lon/missing': 11782,
'atp/field/opening_hours/missing': 11782,
'atp/field/operator/missing': 11782,
'atp/field/operator_wikidata/missing': 11782,
'atp/field/phone/missing': 11782,
'atp/field/postcode/missing': 11782,
'atp/field/state/missing': 11782,
'atp/field/street_address/missing': 11782,
'atp/field/twitter/missing': 11782,
'atp/item_scraped_host_count/www.bim.com.tr': 11782,
'atp/nsi/cc_match': 11782,
'downloader/exception_count': 21,
'downloader/exception_type_count/twisted.internet.error.NoRouteError': 18, …
```

[bim_tr] Add Spider (11.7k locations)

---

locations/spiders/nkd.py

Add [NKD](https://www.nkd.com/), a clothes store chain mostly in DE and other European countries.
| country | count |
| ------- | -----:|
| DE      | 1.296 |
| AT      |   328 |
| IT      |   303 |
| HR      |    75 |
| SI      |    66 |
| CZ      |    38 |

[nkd] Add spider (2106 locations)

---

locations/spiders/leyland_sdm_gb.py
locations/storefinders/amasty_store_locator.py

{'atp/brand/Leyland SDM': 35,
'atp/brand_wikidata/Q110437963': 35,
'atp/category/shop/doityourself': 35,
'atp/field/branch/missing': 35,
'atp/field/country/from_spider_name': 35,
'atp/field/opening_hours/missing': 35,
'atp/item_scraped_host_count/leylandsdm.co.uk': 35,
'atp/nsi/perfect_match': 35,
'downloader/request_bytes': 614, …

[LeylandSdmGB] Fix Spider

---

locations/spiders/manufaktura.py

```python
{'atp/brand/Manufaktura': 55,
'atp/brand_wikidata/Q107740958': 55,
'atp/category/shop/cosmetics': 55,
'atp/field/branch/missing': 55,
'atp/field/state/missing': 55,
'atp/item_scraped_host_count/manufakturashop.com': 55,
'atp/nsi/perfect_match': 55,
'downloader/request_bytes': 21295,
'downloader/request_count': 57,
'downloader/request_method_count/GET': 57,
'downloader/response_bytes': 1087810,
'downloader/response_count': 57,
'downloader/response_status_count/200': 57,
'elapsed_time_seconds': 69.757505,
'finish_time': datetime.datetime(2024, 11, 10, 14, 53, 20, 817934, …
```

[manufaktura] Add spider (55 locations)

---

locations/spiders/pep.py

I've made a similar change to branding in NSI as PEP is always styled in capital letters.

PEP branding and branch

---

locations/spiders/budni_de.py

Add [Budni](https://www.budni.de/), a chemist chain in DE.
```
2024-11-11 21:40:27 [scrapy.statscollectors] INFO: Dumping Scrapy stats:
{'atp/brand/Budni': 195,
'atp/brand_wikidata/Q1001516': 195,
'atp/category/shop/chemist': 195,
'atp/field/branch/missing': 195,
'atp/field/operator/missing': 195,
'atp/field/operator_wikidata/missing': 195,
'atp/field/phone/missing': 195,
'atp/field/state/missing': 195,
'atp/field/twitter/missing': 195,
'atp/item_scraped_host_count/www.budni.de': 195,
'atp/nsi/perfect_match': 195,
```

[budni_de] Add spider (195 locations)

---

locations/spiders/dominos_pizza_fr.py

Address data no longer fits neat pattern so get the complete address only.

Dominos pizza fix

---

locations/spiders/debra_gb.py

{'atp/brand/Debra': 89,
'atp/brand_wikidata/Q104535435': 89,
'atp/category/shop/charity': 89,
'atp/field/branch/missing': 89,
'atp/item_scraped_host_count/www.debra.org.uk': 89,
'atp/nsi/perfect_match': 89,
'downloader/request_bytes': 34353,
'downloader/request_count': 93,
'downloader/request_method_count/GET': 93,
'downloader/response_bytes': 2361767,
'downloader/response_count': 93,
'downloader/response_status_count/200': 92, …

[DebraGB] Fix Spider

---

locations/spiders/new_york_pizza_nl_de.py

Add [New York Pizza](https://www.newyorkpizza.nl/vestigingen), a pizza chain mostly in NL, but also in DE.
```
2024-11-12 21:57:18 [scrapy.statscollectors] INFO: Dumping Scrapy stats:
{'atp/brand/New York Pizza': 303,
'atp/brand_wikidata/Q2639128': 303,
'atp/category/amenity/fast_food': 303,
'atp/field/email/missing': 303,
'atp/field/image/missing': 303,
'atp/field/operator/missing': 303,
'atp/field/operator_wikidata/missing': 303,
'atp/field/state/missing': 303,
'atp/field/twitter/missing': 303,
'atp/item_scraped_host_count/www.newyorkpizza.de': 21,
'atp/item_scraped_host_count/www.newyorkpizza.nl': 282,
'atp/nsi/perfect_match': 303,
```

[new_york_pizza_nl_de] Add spider (303 locations)

---

locations/spiders/carrefour_es.py

Got [403 response](https://alltheplaces-data.openaddresses.io/runs/2024-11-09-13-32-11/stats/carrefour_es.json) in last few weekly, but works on my locals.

[carrefour_es] enable proxy

---

locations/spiders/bens_cookies.py

Rel: https://github.com/osmlab/name-suggestion-index/commit/b6c8cf5a1d77463185ea75fb47eb948cf0452155 name and category to come after the next NSI release.

[Ben's Cookies] Add spider (Fixes #11388)

---

locations/spiders/duffys.py

Opening hours - multiple formats, lengthy code - not worth maintaining this for 30 POIs!

[Duffys] Use DictParser, remove opening hours

---

locations/spiders/kbp_foods.py
locations/spiders/kbp_foods_us.py

`Fixes : refactored code to fix spider`
{'atp/brand/KBP Foods': 249,
'atp/category/missing': 249,
'atp/field/brand_wikidata/missing': 249,
'atp/field/city/missing': 249,
'atp/field/country/from_reverse_geocoding': 249,
'atp/field/email/missing': 249,
'atp/field/image/missing': 249,
'atp/field/opening_hours/missing': 249,
'atp/field/operator/missing': 249,
'atp/field/operator_wikidata/missing': 249,
'atp/field/phone/missing': 224,
'atp/field/postcode/missing': 249,
'atp/field/street_address/missing': 249,
'atp/field/twitter/missing': 249,
'atp/item_scraped_host_count/kbp-foods.com': 249,
'downloader/request_bytes': 3155,
'downloader/request_count': 7,
'downloader/request_method_count/POST': 6,
'downloader/response_bytes': 37719, …

[KbpFoods] Fix Spider

---

locations/spiders/little_free_library.py

Use new API call to minimise total number of requests needed.
Massively slow down spider to avoid hitting rate limits (which are quite aggressive).

little_free_library: fix spider

---

locations/spiders/la_halle_fr.py

[la_halle_fr] join the proxy club

---

locations/commands/sitemap.py

sometimes sites in other countries object to being probed

add a --requires-proxy option to the sitemap command

---

locations/spiders/dbe_gov_schools_za.py

```
'atp/category/amenity/kindergarten': 18,
'atp/category/amenity/school': 25487,
'atp/dbe_gov_schools_za/unknown_phase/HOSPITAL SCHOOL': 4,
'atp/dbe_gov_schools_za/unknown_phase/SCHOOL OF SKILLS': 24,
'atp/field/branch/missing': 25505,
'atp/field/brand/missing': 25505,
'atp/field/brand_wikidata/missing': 25505,
'atp/field/city/missing': 6361,
'atp/field/country/from_spider_name': 25505,
'atp/field/email/missing': 25505,
'atp/field/image/missing': 25505,
'atp/field/lat/missing': 241,
'atp/field/lon/missing': 241,
'atp/field/opening_hours/missing': 25505,
'atp/field/operator/missing': 2515,
'atp/field/operator_wikidata/missing': 2515,
'atp/field/phone/invalid': 1628,
'atp/field/phone/missing': 3960,
'atp/field/postcode/missing': 25505,
'atp/field/street_address/missing': 25505, …
```

[dbe_gov_schools_za] Add spider

---

locations/spiders/change_group.py

[Change Group] Add spider

---

locations/spiders/dbe_gov_ecd_za.py

```
'atp/category/amenity/kindergarten': 41568,
'atp/closed_check': 2,
'atp/field/branch/missing': 41568,
'atp/field/brand/missing': 41568,
'atp/field/brand_wikidata/missing': 41568,
'atp/field/city/missing': 917,
'atp/field/city/wrong_type': 2,
'atp/field/country/from_spider_name': 41568,
'atp/field/email/missing': 41568,
'atp/field/image/missing': 41568,
'atp/field/lat/missing': 73,
'atp/field/lon/missing': 73,
'atp/field/name/missing': 2,
'atp/field/name/wrong_type': 4,
'atp/field/opening_hours/missing': 41568,
'atp/field/operator/missing': 41568,
'atp/field/operator_wikidata/missing': 41568,
'atp/field/phone/missing': 37302,
'atp/field/postcode/missing': 41568,
'atp/field/street_address/missing': 41568,
'atp/field/twitter/missing': 41568, …
```

[dbe_gov_ecd_za] Add spider

---

locations/spiders/easyfitness_de.py

Add [EasyFitness](https://easyfitness.club/), a fitness chain in DE.

[easyfitness_de] Add spider (194 locations)

---

locations/spiders/hungry_lion_ao.py
locations/spiders/hungry_lion_bw.py
locations/spiders/hungry_lion_na.py
locations/spiders/hungry_lion_za.py
locations/spiders/hungry_lion_zm.py

AO:
{'atp/brand/Hungry Lion': 10,
'atp/brand_wikidata/Q115636930': 10,
'atp/category/amenity/fast_food': 10,
'atp/item_scraped_host_count/api.locationbank.net': 10,
'downloader/request_bytes': 701,
'downloader/response_bytes': 6271, …

[Hungry Lion] Fix  spiders using Location Bank API

---

locations/spiders/e5_be.py

`Fixes : updated xpath to fix spider`
{'atp/brand/e5 Mode': 56,
'atp/brand_wikidata/Q85313633': 56,
'atp/category/shop/clothes': 56,
'atp/field/branch/missing': 56,
'atp/field/state/missing': 56,
'atp/field/street_address/missing': 56,
'atp/item_scraped_host_count/www.e5.be': 56,
'atp/nsi/perfect_match': 56,
'downloader/request_bytes': 607,
'downloader/response_bytes': 93903,
'elapsed_time_seconds': 3.921963, …

[E5BE] Fix Spider

---

locations/spiders/koerperformen.py

Add [Körperformen](https://www.körperformen.com/), a fitness chain from DE, with a few locations in CH, IT, UK.

[koerperformen] Add spider (270 locations)

---

locations/spiders/club_car_wash_us.py

Fixes #11450
Will get name and category after the next NSI release: https://github.com/osmlab/name-suggestion-index/commit/94368f55ca2b4311e30b3c949f5366e03f120ae1

[Club Car Wash US] Add spider

---

locations/spiders/sobeys_ca.py

Rel: https://github.com/osmlab/name-suggestion-index/commit/109d36bb82715324c3742326d8fcdbf367771516

[Sobeys CA] Collect pharmacies and liquor stores

---

locations/spiders/traffic_england_gb.py

Inspired by #11437 from @davidhicks and its encroachment on my native Scotland I have pushed south with this one. Not as far south as David. Still England is kind, they give direct image URLs.

[traffic_england_gb] 2713 highway cameras

---

locations/spiders/georgia_dot_us.py

Note very much the same as Nevada. This pattern will no doubt be repeated in some (certainly not all) other states and the spiders code consolidated better when that happens.

[georgia_dot_us] 3676 cameras in Georgia

---

locations/spiders/south_carolina_dot_us.py

South Carolina do it a different way.

[south_carolina_dot_us] add 649 cameras in South Carolina

---

locations/spiders/nevada_dot_us.py
locations/spiders/utah_dot_us.py

Also altered the Nevada spider a little bit for these things to share code.

[utah_dot_us] add 1901 cameras in Utah

---

locations/spiders/natuzzi.py

Italian company with worldwide presence. Will probably add to NSI.

[natuzzi] add spider (300+ furniture shops)

---

locations/spiders/arizona_dot_us.py
locations/spiders/florida_dot_us.py
locations/spiders/georgia_dot_us.py
locations/spiders/louisiana_dot_us.py
locations/spiders/wisconsin_dot_us.py

[DOT spiders] refactor to use common code

---

locations/dict_parser.py
locations/spiders/iccu_it.py

feat: add ICCU spider (IT, 13739)

---

locations/spiders/oregon_dot_us.py

Has a few TODO's but good to go I think. I am planning to do a bulk add of the DOT records to NSI against `man_made=surveillance` at some point soon.

[oregon_dot_us] add 984 cameras, mainly in Oregon

---

locations/spiders/hilton.py

```python
{'atp/brand/AutoCamp': 8,
'atp/brand/Canopy': 46,
'atp/brand/Conrad': 52,
'atp/brand/Curio Collection': 188,
'atp/brand/DoubleTree': 727,
'atp/brand/Embassy Suites': 272,
'atp/brand/Graduate': 34,
'atp/brand/Hampton': 3136,
'atp/brand/Hilton': 631,
'atp/brand/Hilton Garden Inn': 1096,
'atp/brand/Hilton Grand Vacations': 84,
'atp/brand/Home2 Suites': 807,
'atp/brand/Homewood Suites': 557,
'atp/brand/LXR Hotels & Resorts': 16,
'atp/brand/Motto': 8,
'atp/brand/NoMad': 1,
'atp/brand/Signia': 4,
'atp/brand/Small Luxury Hotels of the World': 393,
'atp/brand/Spark by Hilton': 141,
'atp/brand/Tapestry Collection': 174,
'atp/brand/Tempo': 5,
'atp/brand/Tru': 302,
'atp/brand/Waldorf Astoria': 38,
'atp/brand_wikidata/Q109275422': 174,
'atp/brand_wikidata/Q112144335': 4, …
```

[Hilton] Fix spider

---

locations/spiders/od_store_it.py

feat: add ODStore (IT, 115)

---

locations/spiders/yettel_bg.py

Opening times now have multiple inconsistent format so removed as not worth the effort for small number of POIs.

[Yettel BG] Fix opening times

---

locations/spiders/washington_dot_us.py

Added Washington state. Will circle back and try and clean any outstanding PRs now if necessary. Some work sunbmitted and merge into NSI: https://github.com/osmlab/name-suggestion-index/pull/10175

[washington_dot_us] add 1497 cameras in Washington state

---

locations/spiders/opentransportdata_swiss.py

96428 features as of November 28, 2024

Spider for OpenTransportData.swiss

---

locations/spiders/mts_ru.py

Was generating 0 POIs, now:
{'atp/brand/МТС': 4276,

[MTS RU] Fix start url

---

locations/spiders/goodstart.py

{'atp/brand/GoodStart Early Learning': 651,
'atp/brand_wikidata/Q24185325': 651,
'atp/category/amenity/childcare': 651,
'atp/field/branch/missing': 651,
'atp/field/country/from_website_url': 651,
'atp/field/email/missing': 651,
'atp/field/operator/missing': 651,
'atp/field/operator_wikidata/missing': 651,
'atp/field/twitter/missing': 651,
'atp/item_scraped_host_count/www.goodstart.org.au': 651,
'atp/nsi/brand_missing': 651,
'downloader/request_bytes': 1028,
'downloader/response_bytes': 146191, …

[Goodstart] Fix Spider

---

locations/spiders/genesis_rehab.py
locations/spiders/genesis_rehab_us.py

{'atp/brand/Genesis Rehab Services': 171,
'atp/brand_wikidata/Q5532813': 171,
'atp/category/amenity/social_facility': 171,
'atp/field/branch/missing': 171,
'atp/field/country/from_reverse_geocoding': 171,
'atp/field/email/missing': 171,
'atp/field/image/missing': 171,
'atp/field/opening_hours/missing': 171,
'atp/field/phone/missing': 171,
'atp/field/twitter/missing': 171,
'atp/item_scraped_host_count/www.genesishcc.com': 171,
'atp/nsi/perfect_match': 171,
'atp/operator/Genesis HealthCare': 171,
'atp/operator_wikidata/Q5532813': 171,
'downloader/request_bytes': 646,
'downloader/response_bytes': 2258279, …

[GenesisRehab] Fix Spider

---

locations/spiders/game_za.py

{'atp/brand/Game': 106,
'atp/brand_wikidata/Q129263113': 106,
'atp/category/missing': 106,
'atp/field/branch/missing': 106,
'atp/field/country/from_spider_name': 106,
'atp/field/image/missing': 106,
'atp/field/operator/missing': 106,
'atp/field/operator_wikidata/missing': 106,
'atp/field/state/missing': 106,
'atp/field/twitter/missing': 106,
'atp/item_scraped_host_count/www.game.co.za': 106,
'atp/nsi/brand_missing': 106,
'downloader/request_bytes': 939,
'downloader/response_bytes': 23890,
'elapsed_time_seconds': 3.378919, …

[GameZA] Fix Spider

---

locations/spiders/essentiel_antwerp.py

`Fixes : code refactored to use crawlspider to fix spider`
{'atp/brand/Essentiel Antwerp': 42,
'atp/brand_wikidata/Q117456339': 42,
'atp/category/shop/clothes': 42,
'atp/field/branch/missing': 42,
'atp/field/city/missing': 42,
'atp/field/country/from_reverse_geocoding': 41,
'atp/field/image/missing': 42,
'atp/field/operator/missing': 42,
'atp/field/operator_wikidata/missing': 42,
'atp/field/postcode/missing': 41,
'atp/field/twitter/missing': 42,
'atp/item_scraped_host_count/www.essentiel-antwerp.com': 42,
'atp/nsi/perfect_match': 42,
'downloader/request_bytes': 19140, …

[EssentielAntwerp] Fix Spider

---

locations/spiders/eggs_up_grill_us.py

Name and category coming soon: https://github.com/osmlab/name-suggestion-index/pull/10168
```python
{'atp/brand/Eggs Up Grill': 97,
'atp/brand_wikidata/Q131319129': 97,
'atp/category/missing': 97,
'atp/cdn/cloudflare/response_count': 100,
'atp/cdn/cloudflare/response_status_count/200': 100,
'atp/field/email/missing': 97,
'atp/field/image/dropped': 97,
'atp/field/image/missing': 97,
'atp/field/name/missing': 97,
'atp/field/operator/missing': 97,
'atp/field/operator_wikidata/missing': 97,
'atp/field/twitter/missing': 97,
'atp/item_scraped_host_count/locations.eggsupgrill.com': 97,
'atp/nsi/brand_missing': 97,
'downloader/request_bytes': 37857,
'downloader/request_count': 100,
'downloader/request_method_count/GET': 100, …
```

[Eggs Up Grill US] Add spider

---

locations/spiders/montana_dot_us.py

It's really true, there is not much in Montana.

[montana_dot_us] 41 cameras in / bordering Montana

---

locations/spiders/hangerclinic.py
locations/spiders/hangerclinic_us.py

{'atp/brand/Hanger Clinic': 797,
'atp/category/amenity/clinic': 797,
'atp/category/multiple': 797,
'atp/cdn/cloudflare/response_count': 799,
'atp/cdn/cloudflare/response_status_count/200': 799,
'atp/field/branch/missing': 797,
'atp/field/brand_wikidata/missing': 797,
'atp/field/city/missing': 797,
'atp/field/country/from_reverse_geocoding': 797,
'atp/field/email/missing': 797,
'atp/field/image/missing': 797,
'atp/field/name/missing': 20,
'atp/field/opening_hours/missing': 87,
'atp/field/operator/missing': 797,
'atp/field/operator_wikidata/missing': 797,
'atp/field/postcode/missing': 797,
'atp/field/twitter/missing': 797,
'atp/item_scraped_host_count/hangerclinic.com': 797,
'downloader/request_bytes': 309950,
'downloader/request_count': 799, …

[HangerClinic] Fix Spider

---

locations/spiders/donut_king_au.py

`Fixes : code refactored to use StorepointSpider to fix spider`
{'atp/brand/Donut King': 210,
'atp/brand_wikidata/Q5296921': 210,
'atp/category/amenity/fast_food': 210,
'atp/field/branch/missing': 210,
'atp/field/city/missing': 210,
'atp/field/country/from_spider_name': 210,
'atp/field/email/missing': 210,
'atp/field/image/missing': 210,
'atp/field/operator/missing': 210,
'atp/field/operator_wikidata/missing': 210,
'atp/field/postcode/missing': 210,
'atp/field/state/missing': 210,
'atp/field/street_address/missing': 210,
'atp/field/twitter/missing': 210,
'atp/item_scraped_host_count/api.storepoint.co': 210,
'atp/nsi/perfect_match': 210,
'downloader/request_bytes': 340, …

[DonutKingAU] Fix Spider

---

DATA_FORMAT.md

link identifier docs

---

locations/spiders/houlihans_us.py

{"atp/brand/Houlihan's": 29,
'atp/brand_wikidata/Q5913100s': 29,
'atp/category/amenity/restaurant': 29,
'atp/field/branch/missing': 29,
'atp/field/brand_wikidata/invalid': 29,
'atp/item_scraped_host_count/www.houlihans.com': 29,
'atp/nsi/brand_missing': 29,
'downloader/request_bytes': 15357,
'downloader/request_count': 31,
'downloader/request_method_count/GET': 31,
'downloader/response_bytes': 895530,
'downloader/response_count': 31,
'downloader/response_status_count/200': 31,
'elapsed_time_seconds': 39.608912, …

[HoulihansUS] Fix Spider

---

locations/spiders/first_national_bank_us.py

`Fixes : updated parse_item method`
{'atp/brand/First National Bank': 1514,
'atp/brand_wikidata/Q5426765': 1514,
'atp/category/amenity/atm': 1162,
'atp/category/amenity/bank': 352,
'atp/cdn/cloudflare/response_count': 32,
'atp/cdn/cloudflare/response_status_count/200': 31,
'atp/field/email/missing': 1512,
'atp/field/image/missing': 1514,
'atp/field/operator/missing': 352,
'atp/field/operator_wikidata/missing': 352,
'atp/field/twitter/missing': 1514,
'atp/field/website/missing': 118,
'atp/item_scraped_host_count/liveapi.yext.com': 1514,
'atp/nsi/cc_match': 1514,
'atp/operator/First National Bank': 1162,
'atp/operator_wikidata/Q5426765': 1162,
'downloader/request_bytes': 30212,
'downloader/request_count': 32, …

[FirstNationalBankUS] Fix Spider

---

locations/spiders/technopolis_bg.py

ref: https://nsi.guide/index.html?t=brands&k=shop&v=electronics&tt=Technopolis

Update brand name for Technopolis

---

README.md

Remove the $'s in front of commands in the docs

---

contrib/hooks/pre-commit
templates/spiders/crawl.tmpl
templates/spiders/csvfeed.tmpl
templates/spiders/json_blob.tmpl
templates/spiders/structured_data_crawl.tmpl
templates/spiders/structured_data_sitemap.tmpl

chore: check naming consistency in pre-commit

fix: use apply_category in templates

---

locations/hours.py
locations/spiders/pos_indonesia_id.py

Hours are stored in another endpoint so we have to do an extra request.
Haven't run it till completion, stats of my partial run:
```
{
"atp/category/amenity/mailroom": 6,
"atp/category/amenity/post_office": 1152,
"atp/field/brand/missing": 1158,
"atp/field/brand_wikidata/missing": 1158,
"atp/field/city/missing": 944,
"atp/field/country/from_spider_name": 1158,
"atp/field/email/missing": 1158,
"atp/field/image/missing": 1158,
"atp/field/lat/invalid": 1,
"atp/field/lat/missing": 35,
"atp/field/lon/missing": 35,
"atp/field/name/missing": 1158,
"atp/field/opening_hours/missing": 145,
"atp/field/phone/invalid": 3,
"atp/field/phone/missing": 28,
"atp/field/postcode/missing": 1158,
"atp/field/state/missing": 218,
"atp/field/street_address/missing": 1,
"atp/field/twitter/missing": 1158, …
```

[pos_indonesia_id] parse hours and move name to branch

---

locations/spiders/poste_italiane_it.py

Fixes #11529
```js
{'atp/brand/Poste Italiane': 12995,
'atp/brand_wikidata/Q495026': 12995,
'atp/category/amenity/parcel_locker': 41,
'atp/category/amenity/post_office': 12954,
'atp/category/missing': 2035,
'atp/category/shop/tobacco': 16488,
'atp/field/branch/missing': 18564,
'atp/field/brand/missing': 18523,
'atp/field/brand_wikidata/missing': 18523,
'atp/field/country/from_spider_name': 31518,
'atp/field/email/missing': 31518,
'atp/field/image/missing': 31518,
'atp/field/opening_hours/missing': 148,
'atp/field/operator/missing': 18523,
'atp/field/operator_wikidata/missing': 18523,
'atp/field/phone/invalid': 125,
'atp/field/phone/missing': 280,
'atp/field/state/missing': 31518,
'atp/field/twitter/missing': 31518,
'atp/field/website/missing': 31518, …
```

feat: add Poste Italiane (IT, 31518)

---

locations/spiders/eco_store_it.py

feat: add Eco Store (IT, 205)

---

locations/spiders/marketplace_fresh_au.py

{'atp/brand/MarketPlace Fresh': 15,
'atp/brand_wikidata/Q117847717': 15,
'atp/category/shop/greengrocer': 15,
'atp/field/branch/missing': 15,
'atp/field/country/from_spider_name': 15,
'atp/field/postcode/wrong_type': 15,
'atp/item_scraped_host_count/marketplacefresh.com.au': 15,
'atp/nsi/perfect_match': 15,
'downloader/response_bytes': 57935, …

[MarketplaceFresh] Fix Spider

---

locations/spiders/golds_gym.py

{"atp/brand/Gold's Gym": 214,
'atp/brand_wikidata/Q1536234': 214,
'atp/category/leisure/fitness_centre': 214,
'atp/cdn/cloudflare/response_count': 216,
'atp/cdn/cloudflare/response_status_count/200': 216,
'atp/field/branch/missing': 214,
'atp/field/city/missing': 214,
'atp/field/country/from_reverse_geocoding': 213,
'atp/field/image/missing': 214,
'atp/field/opening_hours/missing': 214,
'atp/field/operator/missing': 214,
'atp/field/operator_wikidata/missing': 214,
'atp/field/postcode/missing': 214,
'atp/field/street_address/missing': 214, …

[GoldsGym] Fix Spider

---

locations/spiders/california_department_of_transportation_rwis_us.py

RWIS is Road Weather Information Systems (RWIS).

Add California DOT RWIS (148 sites)

---

locations/spiders/firehouse_subs.py

<details> 
<summary>Stats</summary> 
```
{'atp/brand/Firehouse Subs': 1337,
'atp/brand_wikidata/Q5451873': 1337,
'atp/category/amenity/fast_food': 1337,
'atp/field/image/missing': 1337,
'atp/field/operator/missing': 40,
'atp/field/operator_wikidata/missing': 1337,
'atp/field/phone/missing': 43,
'atp/field/twitter/missing': 1337,
'atp/item_scraped_host_count/czqk28jt.apicdn.sanity.io': 1337,
'atp/nsi/perfect_match': 1337,
'atp/operator/ CTRG STATION 16 LLC': 1, …
```

[Firehouse Subs] Fix spider and add CA locations

---

locations/spiders/aldi_nord_fr.py

This is the quick fix. Long term we should support "FX" from NSI.

[ALDI FR] Restore name and brand

---

locations/spiders/carrefour_br.py

This should fix the request, but I can't work out what they are doing to coords, and I can't access https://www.carrefour.com.br/ to see :(

[Carrefour BR] Flag proxy

---

locations/spiders/evereve_us.py

{'atp/brand/EVEREVE': 119,
'atp/brand_wikidata/Q69891997': 119,
'atp/category/shop/clothes': 119,
'atp/field/branch/missing': 119,
'atp/field/email/missing': 119,
'atp/field/image/missing': 119,
'atp/field/lat/missing': 119,
'atp/field/lon/missing': 119,
'atp/field/operator/missing': 119,
'atp/field/operator_wikidata/missing': 119,
'atp/field/twitter/missing': 119,
'atp/item_scraped_host_count/evereve.com': 119,
'atp/nsi/perfect_match': 119,
'downloader/request_bytes': 1262, …

[EvereveUS] Fix Spider

---

locations/spiders/floor_and_decor.py
locations/spiders/floor_and_decor_us.py

{'atp/brand/Floor and Decor': 176,
'atp/brand_wikidata/Q56280964': 176,
'atp/category/shop/flooring': 176,
'atp/cdn/cloudflare/response_count': 51,
'atp/cdn/cloudflare/response_status_count/200': 35,
'atp/cdn/cloudflare/response_status_count/410': 16,
'atp/field/branch/missing': 176,
'atp/field/email/missing': 176,
'atp/field/image/missing': 176,
'atp/field/opening_hours/missing': 176,
'atp/field/operator/missing': 176,
'atp/field/operator_wikidata/missing': 176,
'atp/field/twitter/missing': 176,
'atp/item_scraped_host_count/www.flooranddecor.com': 177,
'atp/nsi/perfect_match': 176,
'downloader/request_bytes': 41706,
'downloader/request_count': 51,
'downloader/request_method_count/POST': 51,
'downloader/response_bytes': 854567, …

[FloorAndDecor] Fix Spider

---

locations/spiders/sainsburys.py

bureau de change waiting on NSI release.

[Sainsbury's GB] Clean name and branch

---

locations/spiders/la_casa_de_las_carcasas_es.py

We'll get name and category once something is decided in https://github.com/osmlab/name-suggestion-index/pull/10214

[La Casa de las Carcasas ES] Add spider

---

locations/spiders/journeys.py

```python
{'atp/brand/Journeys': 995,
'atp/brand_wikidata/Q61994838': 995,
'atp/category/shop/shoes': 995,
'atp/cdn/cloudflare/response_count': 1065,
'atp/cdn/cloudflare/response_status_count/200': 1065,
'atp/field/branch/missing': 995,
'atp/field/email/missing': 995,
'atp/field/image/missing': 995,
'atp/field/lat/missing': 995,
'atp/field/lon/missing': 995,
'atp/field/operator/missing': 995,
'atp/field/operator_wikidata/missing': 995,
'atp/item_scraped_host_count/www.journeys.ca': 37,
'atp/item_scraped_host_count/www.journeys.com': 958,
'atp/nsi/match_failed': 995,
'downloader/request_bytes': 622526,
'downloader/request_count': 1065,
'downloader/request_method_count/GET': 999,
'downloader/request_method_count/POST': 66,
'downloader/response_bytes': 19527105, …
```

[Journeys] Improve brand, name and collect street_address

---

locations/spiders/pizza_hut_qa.py

{'atp/brand/Pizza Hut': 52,
'atp/brand_wikidata/Q191615': 52,
'atp/category/amenity/restaurant': 52,
'atp/field/branch/missing': 52,
'atp/field/city/missing': 52,
'atp/field/country/from_spider_name': 52,
'atp/field/image/missing': 52,
'atp/field/lat/invalid': 8,
'atp/field/lon/invalid': 8,
'atp/field/phone/missing': 48,
'atp/field/postcode/missing': 52,
'atp/field/state/missing': 52,
'atp/field/twitter/missing': 52,
'atp/item_scraped_host_count/www.qatar.pizzahut.me': 52,
'atp/nsi/cc_match': 52, …

[PizzaHutQA] Fix Spider

---

locations/spiders/burger_king_hu.py

{'atp/brand/Burger King': 58,
'atp/brand_wikidata/Q177054': 58,
'atp/category/amenity/fast_food': 58,
'atp/field/branch/missing': 58,
'atp/field/city/missing': 58,
'atp/field/country/from_spider_name': 58,
'atp/field/image/missing': 58,
'atp/field/opening_hours/missing': 58,
'atp/field/operator/missing': 58,
'atp/field/operator_wikidata/missing': 58,
'atp/field/phone/missing': 58,
'atp/field/state/missing': 58,
'atp/field/twitter/missing': 58,
'atp/item_scraped_host_count/burgerking.hu': 58,
'atp/nsi/cc_match': 58,
'downloader/request_bytes': 609,
'downloader/response_bytes': 36754, …

[BurgerKingHU] Fix Spider

---

locations/spiders/pudo_tr.py

Pudo is a parcel locker company that has around 1200 parcel lockers in Turkey.
Wikidata: https://www.wikidata.org/wiki/Q131450632

Add pudo_tr spider (~1200 parcel lockers in Turkey)

---

locations/spiders/hertz.py

{'atp/brand/Hertz': 6232,
'atp/brand_wikidata/Q1543874': 6232,
'atp/category/amenity/car_rental': 6232,
'atp/field/branch/missing': 6232,
'atp/field/email/invalid': 23,
'atp/field/email/missing': 4154,
'atp/field/image/missing': 6232,
'atp/field/opening_hours/missing': 848,
'atp/field/operator/missing': 6232,
'atp/field/operator_wikidata/missing': 6232,
'atp/field/phone/invalid': 75,
'atp/field/phone/missing': 597,
'atp/field/postcode/missing': 532,
'atp/field/state/from_reverse_geocoding': 16,
'atp/field/state/missing': 3153,
'atp/field/twitter/missing': 6232,
'atp/field/website/invalid': 3659, …

[Hertz] Fix Spider

---

locations/spiders/travis_perkins_gb.py

`Fixes : updated graphql query to fix spider`
{'atp/brand/Benchmarx': 225,
'atp/brand/Travis Perkins': 315,
'atp/brand_wikidata/Q102181127': 225,
'atp/brand_wikidata/Q2450664': 315,
'atp/category/shop/doityourself': 315,
'atp/category/shop/kitchen': 225,
'atp/field/branch/missing': 540,
'atp/field/country/from_spider_name': 540,
'atp/field/email/invalid': 4,
'atp/field/image/missing': 540,
'atp/field/operator/missing': 540,
'atp/field/operator_wikidata/missing': 540,
'atp/field/state/missing': 540,
'atp/field/twitter/missing': 540,
'atp/item_scraped_host_count/www.travisperkins.co.uk': 540,
'atp/nsi/perfect_match': 540,
'downloader/request_bytes': 1726, …

[TravisPerkins] Fix Spider

---

locations/spiders/speedway_us.py

{'atp/brand/Speedway': 3004,
'atp/brand_wikidata/Q7575683': 3004,
'atp/category/amenity/fuel': 3004,
'atp/field/branch/missing': 3004,
'atp/field/email/missing': 3004,
'atp/field/image/missing': 3004,
'atp/field/opening_hours/missing': 3004,
'atp/field/operator/missing': 3004,
'atp/field/operator_wikidata/missing': 3004,
'atp/field/phone/missing': 50,
'atp/field/twitter/missing': 3004,
'atp/item_scraped_host_count/apis.7-eleven.com': 3004,
'atp/nsi/cc_match': 3004,
'downloader/request_bytes': 4519,
'downloader/request_method_count/POST': 2,
'downloader/response_bytes': 391643,
'downloader/response_status_count/502': …

[SpeedwayUS] Fix Spider

---

locations/spiders/la_piadineria.py

feat: add La Piadineria (462)

---

locations/spiders/invitro_ru.py

[Website](https://www.invitro.ru/) itself is not accessible. Perhaps only available for certain regions, might require proxy.

[Invitro RU] Try Fixing  Spider by flagging as requires proxy

---

locations/spiders/murphy_usa_us.py

[POI locator](https://murphyusa.com/murphyusa/find-a-store) is not accessible.

[Murphy USA US] Try fixing Spider by flagging as requires proxy

---

locations/spiders/bargain_books_za.py

{'atp/brand/Bargain Books': 86,
'atp/brand_wikidata/Q116741024': 86,
'atp/category/shop/books': 86,
'atp/field/city/missing': 86,
'atp/field/country/from_spider_name': 86,
'atp/field/email/invalid': 3,
'atp/field/email/missing': 79,
'atp/field/lat/missing': 86,
'atp/field/lon/missing': 86,
'atp/field/postcode/missing': 86,
'atp/field/state/missing': 86,
'atp/field/street_address/missing': 86,
'atp/item_scraped_host_count/www.bargainbooks.co.za': 86,
'atp/nsi/perfect_match': 86,
'downloader/request_bytes': 630, …

[BargainBooksZA] Fix Spider

---

locations/spiders/ackermans.py

{'atp/brand/Ackermans': 1021,
'atp/brand_wikidata/Q4674255': 1021,
'atp/category/shop/clothes': 1021,
'atp/field/branch/missing': 1021,
'atp/field/image/missing': 1021,
'atp/field/operator/missing': 1021,
'atp/field/operator_wikidata/missing': 1021,
'atp/field/phone/invalid': 42,
'atp/field/street_address/missing': 68,
'atp/field/twitter/missing': 1021,
'atp/item_scraped_host_count/ackermans.commercebridge.tech': 1021,
'atp/nsi/perfect_match': 1021, …

[Ackermans] Fix Spider

---

locations/spiders/game_gb.py

Fixes #11668
```python
{'atp/brand/Game': 369,
'atp/brand_wikidata/Q5519813': 369,
'atp/category/shop/video_games': 369,
'atp/field/city/missing': 369,
'atp/field/email/missing': 369,
'atp/field/image/missing': 369,
'atp/field/operator/missing': 369,
'atp/field/operator_wikidata/missing': 369,
'atp/field/state/missing': 369,
'atp/field/street_address/missing': 369,
'atp/field/twitter/missing': 369,
'atp/item_scraped_host_count/www.game.co.uk': 369,
'atp/nsi/perfect_match': 369,
'downloader/request_bytes': 655762,
'downloader/request_count': 371,
'downloader/request_method_count/GET': 371,
'downloader/response_bytes': 22545699,
'downloader/response_count': 371,
'downloader/response_status_count/200': 371, …
```

[Game] Fix address and coord collection

---

locations/spiders/prada.py

{'atp/brand/Prada': 390,
'atp/brand_wikidata/Q193136': 390,
'atp/category/shop/clothes': 390,
'atp/cdn/cloudflare/response_count': 10,
'atp/cdn/cloudflare/response_status_count/200': 9,
'atp/field/branch/missing': 390,
'atp/field/email/missing': 390,
'atp/field/image/missing': 390,
'atp/field/opening_hours/missing': 390,
'atp/field/operator/missing': 390,
'atp/field/operator_wikidata/missing': 390,
'atp/field/postcode/missing': 30,
'atp/field/state/missing': 47,
'atp/field/twitter/missing': 390,
'atp/item_scraped_host_count/cdn.yextapis.com': 390,
'atp/nsi/perfect_match': 390,
'downloader/request_bytes': 6555,
'downloader/request_count': 10, …

[Prada] Fix Spider

---

locations/spiders/spotlight.py

{'atp/brand/Spotlight': 146,
'atp/brand_wikidata/Q105960982': 146,
'atp/category/shop/fabric': 146,
'atp/cdn/cloudfront/response_count': 8,
'atp/cdn/cloudfront/response_status_count/302': 8,
'atp/field/branch/missing': 146,
'atp/field/city/missing': 146,
'atp/field/country/from_reverse_geocoding': 146,
'atp/field/image/missing': 146,
'atp/field/operator/missing': 146,
'atp/field/operator_wikidata/missing': 146,
'atp/field/postcode/missing': 146,
'atp/field/street_address/missing': 146,
'atp/item_scraped_host_count/www.spotlightstores.com': 146,
'atp/nsi/perfect_match': 146,
'downloader/request_bytes': 263184,
'downloader/request_count': 181, …

[Spotlight] Fix Spider

---

ci/check_spider_naming_consistency.py
locations/spiders/poste_italiane_it.py

fix: some ids and add post_office=bureau

feat: improve Poste Italiane

---

locations/spiders/a1_bg.py

for example, this values: бул. Витоша 40
бул. Мадрид 18
ул. Орфей 12А
ул. Лоза 1
ул. Искър 4
пл. България 2
ул."Свобода" 1
ул. Свобода 3
ул. Оборище 18
пл. Свобода 20

[a1_bg] - this is addr:street_address rather than addr:full

---

locations/settings.py

Reference: https://github.com/scrapy/scrapy/commit/6f73dc0e676b5ff440daae7f064e855eb0de428f

settings: remove deprecated REQUEST_FINGERPRINTER_IMPLEMENTATION

---

locations/spiders/menchies.py

Mostly-US ice cream shop chain
```py
{"atp/brand/Menchie's": 323,
'atp/brand_wikidata/Q6816528': 323,
'atp/category/amenity/ice_cream': 323,
'atp/field/branch/missing': 323,
'atp/field/city/missing': 323,
'atp/field/country/from_reverse_geocoding': 316,
'atp/field/country/missing': 7,
'atp/field/email/missing': 323,
'atp/field/image/missing': 323,
'atp/field/opening_hours/invalid': 3,
'atp/field/operator/missing': 323,
'atp/field/operator_wikidata/missing': 323,
'atp/field/postcode/missing': 323, …
```

Add Menchie's spider (323 locations)

---

locations/spiders/ifly_ca_us.py

for example, this values: 997 US-1
9540 Katy Fwy
5520 Park Pl

[ifly_ca_us] - this is addr:street_address rather than addr:full

---

locations/spiders/buildit.py

for example, this values: 33 Hoofweg
37 Market Str
15 Main Road
R33 Main Road
1 Haysom Road
4 2nd Avenue
Stand 602
Shop No 1 R37
ERF 462 Ext 1
C33 Main Road

[buildit] - this is addr:street_address rather than addr:full

---

locations/spiders/victorias_secret_gb.py

```python
{"atp/brand/Victoria's Secret": 55,
'atp/brand_wikidata/Q332477': 55,
'atp/category/shop/clothes': 55,
'atp/field/city/missing': 55,
'atp/field/lat/missing': 55,
'atp/field/lon/missing': 55,
'atp/field/state/missing': 55,
'atp/field/street_address/missing': 55,
'atp/field/website/missing': 55,
'atp/item_scraped_host_count/www.victoriassecret.co.uk': 55,
'atp/nsi/perfect_match': 55,
'downloader/request_bytes': 793,
'downloader/response_bytes': 61760, …
```

[Victoria's Secret GB] Fix spider

---

locations/spiders/trussell_trust_gb.py

{'atp/category/amenity/social_facility': 1173,
'atp/field/brand/missing': 1173,
'atp/field/brand_wikidata/missing': 1173,
'atp/field/country/from_spider_name': 1173,
'atp/field/image/missing': 1173,
'atp/field/opening_hours/missing': 1173,
'atp/field/phone/invalid': 51,
'atp/field/phone/missing': 15,
'atp/field/state/missing': 337,
'atp/field/street_address/missing': 312,
'atp/field/twitter/missing': 1173,
'atp/item_scraped_host_count/www.trussell.org.uk': 1173,
'atp/nsi/perfect_match': 1173,
'atp/operator/The Trussell Trust': 1173,
'atp/operator_wikidata/Q15621299': 1173,
'downloader/request_bytes': 71277,
'downloader/request_count': 148,
'downloader/request_method_count/GET': 148,
'downloader/response_bytes': 2669097, …

[Trussell Trust GB] Fix Spider

---

locations/spiders/wells_fargo.py

for example, this values: 1000 LAKES DR
RTE 4 & RTE 41
HWY 73 MAIN ST
HWY 70 W
HWY 158 & 801
HIGHWAY 191
HIGHWAY 160
HIGHWAY 150
9 N MAIN ST
99 HARVEY RD

[wells_fargo] - this is addr:street_address rather than addr:full

---

locations/spiders/vallarta_us.py

for example, this value: 13715 Vanowen St

[vallarta_us] - this is addr:street rather than addr:full

---

locations/hours.py
locations/pipelines/address_clean_up.py
locations/spiders/sinsay.py

feat: add Sinsay (world, 1370)

---

locations/spiders/swedbank_ee.py

for example, this values: Kalda tee 43
Jaani 4
Erika 14
Kopli 1
Kopli 1
Võru mnt 81
Kalda tee 1
Endla 52
Pärnu mnt 180
Rakvere 40

[swedbank_ee] - this is addr:street_address rather than addr:full

---

locations/spiders/paint_spot_au.py

for example, this values: 493 Grimshaw Street
11 Geelong Street
2 Levanswell Road
390 Keilor Road
142 McIntyre Road
138 Queen Street

[paint_spot_au] - this is addr:street_address rather than addr:full

---

locations/spiders/move_yourself_au.py

for example, this values: 1 Main Road
30 Links Ave
100 Dawson st
229 Bourke St
1 Blade Close
267 Wright Rd
22 Market St
32 Bay Rd
123 Smith St
94 Main St

[move_yourself_au] - this is addr:street_address rather than addr:full

---

locations/spiders/kaiser_permanente_us.py

Attempting to fix `Dubious tag type = Dental Office` reported by my validator
```
{
'ref': '309381',
'brand': 'Kaiser Permanente',
'brand_wikidata': 'Q1721601',
'amenity': 'clinic',
'healthcare': 'clinic',
'type': 'Dental Office',
'@source_uri': 'https://healthy.kaiserpermanente.org/oregon-washington/facilities/aloha-dental-office-309381',
'@spider': 'kaiser_permanente_us',
'addr:street_address': '17675 SW Tualatin Valley Hwy',
'addr:city': 'Beaverton',
'addr:state': 'OR',
'addr:postcode': '97003',
'addr:country': 'US',
'name': 'Aloha Dental Office',
'phone': '+1 800-813-2000',
'website': 'https://healthy.kaiserpermanente.org/oregon-washington/facilities/aloha-dental-office-309381',
'image': 'https://healthy.kaiserpermanente.org/content/dam/kporg/final/images/places/medical-facility/nw/alo …
```

kaiser_permanente_us - more dentists

---

locations/spiders/thelins_konditori_se.py

for example, this values: Karlaplan 13
Kungsgatan 51
Golfvägen 6
Golfvägen 4
Forumvägen 14
Nybrogatan 36
Odengatan 34
Landsvägen 62

[thelins_konditori_se] - this is addr:street_address rather than addr:full

---

locations/spiders/nissan_cz.py

for example, this values: Žižkova 660
Doubská 660
Lidická 211
Čepirožská 5
Tečovice 362
V Lukách 1407
Tečovská 1052
Olomoucká 176
Východní 2134
Pražská 285

[nissan_cz] - this is addr:street_address rather than addr:full

---

locations/spiders/ljsilvers.py

for example, this values: 5167 Plank Rd
1306 2nd Ave.
2058 FM 2920
378 S. Avenue
3400 S. 10th
2040 Lee Hwy.
801 Hardy Rd.
910 Hwy. 28
2839 Teal Rd.
8055 U.S. 42

[ljsilvers] - this is addr:street_address rather than addr:full

---

locations/spiders/carinos.py

for example, this values: 1201 Airway
2425 Parkway

[carinos] - this is addr:street_address rather than addr:full

---

locations/spiders/plus_pl.py

for example, this values: Ogrodowa 15
Złota 59
Rynek 33
Katowicka 10
Rynek 17
Ełcka 22
Kaliska 120
4 Stycznia 43
Zdrojowa 31
Radomska 2

[plus_pl] - this is addr:street_address rather than addr:full

---

locations/spiders/videopro_au.py

for example, this values: 26 Agnes St

[videopro_au] - this is addr:street_address rather than addr:full

---

locations/spiders/ziko_apteka_pl.py

for example, this values: ul. Łużycka 7
ul. Grażyny 4
ul. Rynek 35
ul. Basaja 4
ul. Dobra 27
ul. 3 Maja 3
ul. 1 Maja 2
ul. 1 Maja 40
ul. 3 Maja 7
ul. Odkryta 4

[ziko_apteka_pl] - this is addr:street_address rather than addr:full

---

locations/spiders/play_pl.py

for example, this values: Ul. Wspólna 1
Ul. Rynek 8
Ul. 1 Maja 11
Ul. Rynek 2
Ul. Witosa 32
Ul. Rynek 21
Ul. Polna 40
Ul. Rynek 25
Ul. 3 Maja 22
Ul. 1 Maja 18

[play_pl] - this is addr:street_address rather than addr:full

---

locations/spiders/gamestop.py

for example, this values: Via Amoretti 1
Via De Amicis 2
Via Portico 71
Via Togliatti 4
Via Asiago 2
S.S. 235
Via Graziani 48
Via Spagna 12
Via Trentino 1
Via Novi 31

[gamestop] - this is addr:street_address rather than addr:full

---

locations/spiders/coop_alleanza_it.py

for example, this values: via Colombo 18
via Mengoli 34
Via Musile 9
via Schio 15
via Saffi 90
Via Recanati 6
Via Forlanini 46
Via Reghena 1
via Barberia 30
Via Airoldi 44

[coop_alleanza_it] - this is addr:street_address rather than addr:full

---

locations/spiders/empik_pl.py

for example, this values: ul. Biała Droga 2
ul. Mazurska 4
ul. Kolejowa 6
ul. Brzeska 27
ul. Hetmańska 16
ul. Jurowiecka 1
ul. Sarni Stok 2
ul. Mostowa 2
ul. 3 Maja 13
ul. Hutnicza 7A

[empik_pl] - this is addr:street_address rather than addr:full

---

locations/spiders/dsk_bank_bg.py

for example, this values: ул. "Бор" № 3
ул. "Май" № 1
ул. "Сава" 2
ул. Девня №24
"Широка" № 1
ул. "Люляк" 5
ул. "Дунав" 2
ул Първа 19
пл.Свобода 2
бул. Руски 44

[dsk_bank_bg] - this is addr:street_address rather than addr:full

---

locations/spiders/bauhaus_de.py

Add Bauhaus (shop/doityourself) (DE) (161 stores)

---

locations/spiders/noppes_nl.py
locations/storefinders/store_locator_plus_self.py

Add Noppes (shop/second_hand) (NL) (51 stores)

---

locations/hours.py
locations/spiders/pizzalonga_away_it.py

feat(spider): add Pizzalonga Away (IT, 78)

---

locations/spiders/tag_heuer.py

for example, this values: 449 Oxford Street
73 High Street
6000 Glades Road
149 Dongbu-ro
50 Rideau Street
600 Kingsway
70 Bond Street
23 South John Street
Graben 21
5 James Street

[tag_heuer] - this is addr:street_address rather than addr:full

---

locations/spiders/kaisercraft_au.py

for example, this values: 1 Central Ave
84 Kerr Street
17 McPhillips Road
217 Auburn Street
52/74 Fitzroy St
16 Amazons Pl
272 Anzac Ave
2 Acacia Ave
38-74 Wembley Road
12-20 Ocean St

[kaisercraft_au] - this is addr:street_address rather than addr:full

---

locations/spiders/torchys_tacos.py

for example, this values: 3562 S Soncy Rd.
1929 Broadway
1556 E. 2nd Street
3510 W Cary St.
1315 Huguenot Road
11120 West Broad Street
801 S 5th St
1500 N. I-35
306 E. 5th St
1671 East Broad Street

[torchys_tacos] - this is addr:street_address rather than addr:full

---

locations/spiders/petstock_au.py

for example, this values: 107A Gamon Street
101 Princes Highway
190 Lutwyche Road
129 Hammond Avenue
339 Brisbane Street
2/222 Anzac Avenue
82 Fyans St
290 Princes Hwy
2/38 William St
2/20 Pacific Hwy

[petstock_au] - this is addr:street_address rather than addr:full

---

locations/spiders/ccbank_bg.py

for example, this values: ул."Речна" 8
ул."Шипка" 23
ул."Русе" 59
ул."Рила" 8
ул."Орфей" 2
ул."Искър" 1
ул."Преспа" 5
ул."Охрид" 16
ул."Емине" 23
ул."Скопие" 1

[ccbank_bg] - this is addr:street_address rather than addr:full

---

locations/spiders/kfc_it.py

for example, this values: Via Noicattaro 2
Via Portico 71
Via IV Novembre 2
Via Italia 197
Via Tiracollo 13
Via del Mare 16
Via Casilina 1002
Via Fiumara 15/16
Via Dei Pioppi 7
Via Dogali 24/26

[kfc_it] - this is addr:street_address rather than addr:full

---

locations/spiders/snap_fitness.py

for example, this values: 92 Main Street
66A Church Street
1/130 High Street
32 Alice Street
1/53 Indwarra Avenue
250 Olsen Ave
10 McCormacks Road
14 Mount Street
22 Queen Street
20 Station Street

[snap_fitness] - this is addr:street_address rather than addr:full

---

locations/spiders/fastned.py

for example, this values: Bospoort A4
't Haasje A2
De Horn A7
Kruisoord A7
Rijksweg 471
Ruwiel A2
Akermaat A9
Haarrijn A2
1 Tolvaddon Rd
Mandelan A32

[fastned] - this is addr:street_address rather than addr:full

---

locations/spiders/byd_auto_au.py

for example, this values: 494 Gardeners Rd
789 Nepean Highway
358 Wickham St
221 Mulgrave Road
22 Josephson St
54 Macquarie Rd
93 Lonsdale Street
50 Riley St
270 Main Road
1 Racecourse Rd

[byd_auto_au] - this is addr:street_address rather than addr:full

---

locations/spiders/bauhaus_es.py

Add Bauhaus (shop/doityourself) (ES) (11 stores)

---

locations/spiders/bauhaus_nl.py

Add Bauhaus (shop/doityourself) (NL) (4 stores)

---

locations/spiders/bauhaus_hr.py

Add Bauhaus (shop/doityourself) (HR) (8 stores)

---

locations/spiders/bauhaus_at.py
locations/storefinders/woosmap.py

Add Bauhaus (shop/doityourself) (AT) (21 stores)

---

locations/spiders/himo_cn.py

Add Himo (shop/photo) (CN) (665 stores)

---

locations/spiders/accessorize_gb_gg_ie_je.py
locations/storefinders/uberall.py

Add Accessorize (shop/fashion_accessories) (GB/GG/IE/JE) (125 stores)

---

locations/hours.py
locations/spiders/bellaflora_at.py

Add Bellaflora (shop/garden_centre) (AT) (28 stores)

---

locations/hours.py
locations/spiders/brainwash_nl.py

Add BrainWash (shop/hairdresser) (NL) (155 stores)

---

locations/spiders/q_park.py

<details><summary>Full Stats</summary>
```json
{
"atp/brand/Q-Park": 1206,
"atp/brand_wikidata/Q1127798": 1206,
"atp/category/amenity/parking": 1206,
"atp/field/branch/missing": 1206,
"atp/field/city/missing": 318,
"atp/field/country/from_website_url": 470,
"atp/field/email/missing": 1206,
"atp/field/image/missing": 1206,
"atp/field/lat/missing": 208,
"atp/field/lon/missing": 208,
"atp/field/name/missing": 4,
"atp/field/opening_hours/missing": 1206,
"atp/field/phone/missing": 730,
"atp/field/postcode/missing": 293,
"atp/field/state/missing": 1206,
"atp/field/street_address/missing": 292,
"atp/field/twitter/missing": 1206,
"atp/geometry/null_island": 13,
"atp/item_scraped_host_count/www.q-park.be": 42,
"atp/item_scraped_host_count/www.q-park.co.uk": 81, …
```

[q_park] Added Q Park Spider (1206 items)

---

locations/spiders/avia_pl.py

{'atp/brand/Avia': 130,
'atp/brand_wikidata/Q300147': 130,
'atp/category/amenity/fuel': 130,
'atp/field/branch/missing': 130,
'atp/field/country/from_spider_name': 130,
'atp/field/email/missing': 130,
'atp/field/image/missing': 130,
'atp/field/opening_hours/missing': 130,
'atp/field/operator/missing': 130,
'atp/field/operator_wikidata/missing': 130,
'atp/field/state/missing': 130,
'atp/field/street_address/missing': 130,
'atp/field/twitter/missing': 130,
'atp/field/website/missing': 130,
'atp/item_scraped_host_count/api.mapa.aviapolska.pl': 130,
'atp/nsi/cc_match': 130,
'downloader/request_bytes': 981,
'downloader/response_bytes': 139852, …

[Avia PL] Fix Spider

---

locations/spiders/ymca.py

for example, this values: 422 E Broad St
170 Elm St
220 Clark St
67 maple street
112 Oak Street
112 Oak St
1409 NW 6th Street
651 Broadway
99 Morris Ave
65 High St

[ymca] - this is addr:street_address rather than addr:full

---

locations/spiders/wingstop.py

for example, this values: 66 Taylor Hwy
66 Taylor Hwy
7332 Antoine
3002 SR 436
2030 S Cooper
3882 MO-141
1395 E Tyler Street
2933 Kirk Rd
3425 Salida Street
5917 Niles St

[wingstop] - this is addr:street_address rather than addr:full

---

locations/spiders/tops.py

for example, this values: 100 Main Street
8417 Oswego Road
6308 U.S. 9
3870 Harlem Road
3865 Union Road
71 Nelson Street
Rt. 5 & Oxbow Road
5150 North Street
28 Railroad Street
198 West Main Street

[tops] - this is addr:street_address rather than addr:full

---

locations/hours.py
locations/spiders/bauhaus_at.py
locations/spiders/bauhaus_ch.py
locations/spiders/bauhaus_de.py
locations/spiders/bauhaus_es.py
locations/spiders/bauhaus_hr.py
locations/spiders/bauhaus_nl.py
locations/storefinders/woosmap.py

Add Bauhaus (shop/doityourself) (CH) (5 stores)

---

locations/spiders/ottos_ch.py

{'atp/brand/Otto’s': 140,
'atp/brand_wikidata/Q2041507': 140,
'atp/category/shop/variety_store': 140,
'atp/field/branch/missing': 140,
'atp/field/email/missing': 140,
'atp/field/image/missing': 140,
'atp/field/operator/missing': 140,
'atp/field/operator_wikidata/missing': 140,
'atp/field/state/missing': 139,
'atp/field/state/wrong_type': 1,
'atp/item_scraped_host_count/api.ottos.ch': 140,
'atp/nsi/perfect_match': 140,
'downloader/exception_type_count/twisted.internet.error.TimeoutError': 1,
'downloader/request_bytes': 1979, …

[Ottos CH] Fix Spider

---

locations/spiders/designer_sofas.py
locations/spiders/designer_sofas_gb.py

Natuzzi is re-branding in the UK: https://www.wikidata.org/wiki/Q131695219

[designer_sofas_gb] furniture chain (33 items)

---

locations/spiders/sklavenitis_gr.py

looking at https://www.sklavenitis.gr/about/katastimata/ and OSM they seem to rather use Greek alphabet in Greece

[Sklavenitis GR] Sync brand with NSI

---

locations/spiders/alertcalifornia_us.py

Add ALERTCalifornia (man_made/surveillance) (US) (1153 cameras)

---

locations/spiders/greyhound.py

Fixes https://github.com/alltheplaces/alltheplaces/issues/10599

Rewrite greyhound for new website

---

locations/spiders/topgolf_us.py

Topgolf: Make "building:levels", "rooms", and "screens" values strings

---

locations/spiders/unicredit_bulbank_bg.py

for example, this values: пл. Саранск 2
ул. Пирин 3
пл. Свобода 2
бул. Мадрид 1
ул. Аксаков 8
ул. Скопие 1
ул. Водопад 2
ул. Охрид 7
ул. Яворов 2
ул. Кракра 41

[unicredit_bulbank_bg] - this is addr:street_address rather than addr:full

---

locations/spiders/naf_naf_grill_us.py

[Naf Naf Grill US] Add spider

---

locations/spiders/united_energy_au.py

Feature types extracted:
'atp/category/power/substation': 56,
'atp/category/power/transformer': 15353,

Add United Energy (power/(substation|transformer)) (AU) (15409 features)

---

locations/spiders/primark.py

fixes  #11876 and https://github.com/alltheplaces/alltheplaces/commit/fbe8859d8b563f9720aee34f0875cedef1adfc1f
not sure is {{placeholder}}} a typo or a real fake data

primark - drop also addr:postcode = {{placeholder}}

---

locations/spiders/patel_brothers_us.py

{'atp/brand/Patel Brothers': 51,
'atp/brand_wikidata/Q55641396': 51,
'atp/category/shop/supermarket': 51,
'atp/country/US': 51,
'atp/field/country/from_spider_name': 51,
'atp/field/image/missing': 51,
'atp/field/opening_hours/missing': 51,
'atp/field/operator/missing': 51,
'atp/field/operator_wikidata/missing': 51,
'atp/field/street_address/missing': 51,
'atp/field/twitter/missing': 51,
'atp/field/website/missing': 51,
'atp/item_scraped_host_count/www.patelbros.com': 51,
'atp/nsi/perfect_match': 51,
'downloader/response_bytes': 40707,
'elapsed_time_seconds': 10.209397, …

[Patel Brothers US] Fix Spider

---

locations/spiders/thiele_dk.py

for example, this values: Søndergade 11
Nørregade 12
10 Strøget
Bredgade 23
Adelgade 84 A
Brødregade 9
Immervad 3
Ryesgade 12
Nørregade 16
Vestergade 2

[thiele_dk] - this is addr:street_address rather than addr:full

---

locations/spiders/7_brew_us.py

Coffee shop in the US, 282 locations
Solves https://github.com/alltheplaces/alltheplaces/issues/8899

Add 7 Brew spider

---

locations/spiders/equatorial_coffee_za.py

for example, this values: 27 Commercial Road
381 Boshoff Street
120 Durban Road
186 Inanda Road
1 Molangeni Street
1 Spine Road
N3 National Road
8 Grobbler Street
108 Essenwood Road
41 Knysna Road

[equatorial_coffee_za] - this is addr:street_address rather than addr:full

---

locations/spiders/smythstoys_gb.py

`Fixes : code refactored to use woosmap spider to fix spider`
{'atp/brand/SmythsToys': 127,
'atp/brand_wikidata/Q7546779': 127,
'atp/category/shop/toys': 127,
'atp/field/branch/missing': 127,
'atp/field/email/missing': 127,
'atp/field/image/missing': 127,
'atp/field/operator/missing': 127,
'atp/field/operator_wikidata/missing': 127,
'atp/field/phone/missing': 127,
'atp/field/state/missing': 127,
'atp/field/twitter/missing': 127,
'atp/field/website/missing': 127,
'atp/item_scraped_host_count/api.woosmap.com': 127,
'atp/nsi/perfect_match': 127,
'downloader/request_bytes': 732, …

[Smythstoys GB] Fix Spider

---

locations/spiders/toyota_au.py

for example, this values: 14 Hutchins Street
14 Hutchins Street
14 Hutchins Street
267 Argyle Street
267 Argyle Street
267 Argyle Street
80 Hobart Road
80 Hobart Road
80 Hobart Road
41 Best Street

[toyota_au] - this is addr:street_address rather than addr:full

---

locations/spiders/kaiser_permanente_us.py

[kaiser_permanente_us] brand_wikidata -> brand:wikidata

---

locations/spiders/a1_mk.py

From what I see Albanian is supposed to be in sq, see https://wiki.openstreetmap.org/wiki/Key:name:sq
al is country code of Albania

Albanian is sq

---

locations/spiders/mkrf_ru.py

Fixed TypeError described in https://github.com/alltheplaces/alltheplaces/pull/11897#issuecomment-2585878338.

[mkrf_ru] fix error when no category field supplied in the data

---

locations/categories.py
locations/spiders/coop_alleanza_it.py
locations/spiders/coop_centro_italia_it.py

Make departments use `sells:` prefix where appropriate

fix(coop_*_it): departments

---

locations/spiders/midcounties_cooperative_gb.py

tried to fix it, failed due to lacking data

document data issue in [data midcounties_cooperative_gb]

---

locations/spiders/sony_gb.py

[Sony GB] Fix phone numbers

---

DATA_FORMAT.md
docs/EXTRA_ATTRIBUTES.md
docs/SITEMAP.md
docs/WIKIDATA.md
locations/categories.py
locations/hours.py
locations/name_suggestion_index.py
locations/storefinders/closeby.py
locations/storefinders/rio_seo.py
locations/storefinders/storemapper.py
locations/storefinders/virtualearth.py

fix some typos

---

locations/spiders/bcc_it.py

feat(bcc_it): add BCC banks and atms (IT, 6938)

---

locations/hours.py
locations/spiders/isuzu_th.py

'atp/category/shop/car': 325,
'atp/category/shop/car_repair': 325,
'atp/category/shop/truck': 260,
'atp/category/shop/truck_repair': 248,

Add Isuzu (shop/(car|car_repair|truck|truck_repair)) (TH) (1158 feats)

---

locations/spiders/ssangyong_au.py

Add SsangYong (shop/car) (AU) (78 dealers)

---

locations/spiders/kennards_hire_au.py
locations/spiders/kennards_hire_nz.py

Add Kennards Hire (shop/plant_hire) (AU/NZ) (214 locations)

---

locations/spiders/kruidvat.py

```json
{
"atp/brand/Kruidvat": 1470,
"atp/brand_wikidata/Q2226366": 1470,
"atp/category/shop/chemist": 1470,
"atp/country/BE": 345,
"atp/country/NL": 1125,
"atp/field/branch/missing": 1470,
"atp/field/city/missing": 1470,
"atp/field/country/from_website_url": 1470,
"atp/field/email/missing": 1470,
"atp/field/image/missing": 1470,
"atp/field/lat/missing": 185,
"atp/field/lon/missing": 185,
"atp/field/opening_hours/missing": 4,
"atp/field/operator/missing": 1470,
"atp/field/operator_wikidata/missing": 1470,
"atp/field/phone/missing": 1470,
"atp/field/state/missing": 12,
"atp/field/street_address/missing": 1470,
"atp/field/twitter/missing": 1470,
"atp/geometry/null_island": 185,
"atp/item_scraped_host_count/www.kruidvat.be": 345,
"atp/item_scraped_host_count/www.kruidvat.nl": 1125, …
```

[kruidvat] add missing category

---

locations/spiders/weigels_us.py

Rel: https://github.com/osmlab/name-suggestion-index/issues/10366

[Weigel's US] Add spider

---

locations/spiders/fireaway_gb.py

[Fireaway GB] Add spider

---

locations/spiders/supercuts.py

{'atp/brand/Supercuts': 1869,
'atp/brand_wikidata/Q7643239': 1869,
'atp/category/shop/hairdresser': 1869,
'atp/country/CA': 11,
'atp/country/US': 1858,
'atp/field/email/missing': 1869,
'atp/field/image/missing': 1869,
'atp/field/operator_wikidata/missing': 1869,
'atp/field/twitter/missing': 1869,
'atp/item_scraped_host_count/api.regiscorp.com': 1869,
'atp/nsi/perfect_match': 1869,
'downloader/request_bytes': 713208,
'downloader/request_count': 1920,
'downloader/request_method_count/GET': 1920,
'downloader/response_bytes': 6449713,
'downloader/response_count': 1920,
'downloader/response_status_count/200': 1920,
'elapsed_time_seconds': 2348.197835, …

[Supercuts] Fix Spider

---

locations/categories.py
locations/dict_parser.py
locations/hours.py
locations/spiders/inpost_it.py
locations/spiders/paczkomat_inpost_pl.py

feat(inpost): add extensible Inpost for IT, and use it for PL

---

locations/spiders/landi_ch.py

landi_ch - drop unspecific websites, prefer POI-specific ones

---

locations/spiders/scania.py

`Fixes : start_urls and parse method updated to fix spider`
{'atp/brand/Scania': 1662,
'atp/brand_wikidata/Q219960': 1662,
'atp/category/shop/truck_repair': 1662,
'atp/country/AE': 5,
'atp/country/AL': 1,
'atp/country/AR': 25,
'atp/country/AT': 17,
'atp/country/AU': 89,
'atp/country/BA': 1,
'atp/country/BE': 17,
'atp/country/BG': 5,
'atp/country/BR': 107,
'atp/country/BW': 2,
'atp/country/CA': 69,
'atp/country/CH': 27,
'atp/country/CL': 8,
'atp/country/CN': 14,
'atp/country/CZ': 18,
'atp/country/DE': 153,
'atp/country/DK': 22,
'atp/country/EE': 4,
'atp/country/ES': 58,
'atp/country/FI': 26,
'atp/country/FR': 102,
'atp/country/GH': 3,
'atp/country/HK': 1,
'atp/country/HR': 4,
'atp/country/HU': 7,
'atp/country/IE': 10,
'atp/country/IT': 79,
'atp/country/JP': 48,
'atp/country/KR': 23, …

[Scania] Fix Spider

---

locations/spiders/gabriels_be.py

Name waiting on https://github.com/osmlab/name-suggestion-index/commit/e52db0984680de8fc88983651a16aca944cb3b52

[Gabriëls BE] Add spider

---

locations/spiders/burger_king_ru.py

`Cookies` added to `API` request to get the desired data. Also fixed the missing `street_address` field.
```
{'atp/brand/Бургер Кинг': 853,
'atp/brand_wikidata/Q177054': 853,
'atp/category/amenity/fast_food': 853,
'atp/country/RU': 853,
'atp/field/branch/missing': 853,
'atp/field/city/missing': 853,
'atp/field/country/from_spider_name': 853,
'atp/field/image/missing': 853,
'atp/field/operator/missing': 853,
'atp/field/operator_wikidata/missing': 853,
'atp/field/phone/invalid': 828,
'atp/field/postcode/missing': 853,
'atp/field/state/missing': 853,
'atp/field/twitter/missing': 853,
'atp/field/website/missing': 853,
'atp/item_scraped_host_count/orderapp.burgerkingrus.ru': 853,
'atp/nsi/cc_match': 853,
'downloader/request_bytes': 1849, …
```

[Burger King RU] Fix spider

---

locations/spiders/clever_fit.py

Add [Clever Fit](https://www.clever-fit.com/), a fitness chain present mostly in DE, but also AT, CH and other countries.

[clever_fit] Add spider (523 locations)

---

locations/spiders/bos_coffee_ph.py

There are no store specific websites.

[BosCoffee PH] Override default incorrect website

---

locations/spiders/pandora.py

it is half clarification request: what it even means? Does it carry even a potentially useful info?

[pandora] emit only Pandora branded as being Pandora branded

---

locations/spiders/lounges_gb.py

Went to [`Hesco Lounge` ](https://thelounges.co.uk/hesco/) the other day: https://www.openstreetmap.org/#map=19/53.844147/-1.507747
Quite nice and when I discovered there were ~250 such "Lounges" in the UK decided it deserved a little spider. No coords though.

[lounges_gb] add 248 restaurant/cafe in GB

---

locations/spiders/insta_volt_gb.py

`Fixes : updated start_urls and parse method to fix spider`
{'atp/brand/InstaVolt': 700,
'atp/brand_wikidata/Q111173904': 700,
'atp/category/amenity/charging_station': 700,
'atp/country/GB': 700,
'atp/field/country/from_spider_name': 700,
'atp/field/email/missing': 700,
'atp/field/image/missing': 700,
'atp/field/opening_hours/missing': 700,
'atp/field/phone/missing': 700,
'atp/field/state/missing': 700,
'atp/field/street_address/missing': 700,
'atp/field/twitter/missing': 700,
'atp/item_scraped_host_count/instavolt.co.uk': 700,
'atp/nsi/cc_match': 700,
'atp/operator/InstaVolt': 700,
'atp/operator_wikidata/Q111173904': 700,
'downloader/request_bytes': 1452, …

[Insta Volt GB] Fix Spider

---

locations/spiders/seat.py
locations/spiders/volkswagen_be.py

When doing `item.update({"brand": "SEAT", "brand_wikidata": "Q188217", "extras": Categories.SHOP_CAR.value})` and then `apply_category` - objects were updated unexpectedly, producing:
```
{"type": "Feature", "id": "b0zktW3WLgsSvqsok14PVdeaz2w=", "properties": {"ref": "WOLO100013SE", "shop": "car;car;car;car;car;car;car;car;car;car;car;car;car;car;car;car;car;car;car;car;car;car;car;car;car;car;car;car;car;car;car;car;car;car;car;car;car;car;car;car;car;car;car;car;car;car;car;car;car;car;car;car;car;car;car;car;car;car;car;car;car;car;car;car;car;car;car;car;car;car;car;car;car;car;car;car;car;car;car;car;car;car;car;car;car;car;car;car;car;car;car;car;car;car;car;car;car;car;car;car;car;car;car;car;car;car;car;car;car;car;car;car;car;car;car;car;car;car;car;car;car;car;car;car;car;car;car …
```

[volkswagen_be] fix spider

---

locations/spiders/poczta_polska_pl.py

`Fixes : updated FormRequest by adding headers to fix spider`
{'atp/brand/Poczta Polska': 6712,
'atp/brand_wikidata/Q168833': 6712,
'atp/category/amenity/post_office': 6712,
'atp/country/PL': 6712,
'atp/field/branch/missing': 6712,
'atp/field/country/from_spider_name': 6712,
'atp/field/email/missing': 6712,
'atp/field/image/missing': 6712,
'atp/field/opening_hours/missing': 987,
'atp/field/operator/missing': 6712,
'atp/field/operator_wikidata/missing': 6712,
'atp/field/phone/invalid': 175,
'atp/field/state/missing': 6712,
'atp/field/street_address/missing': 6712,
'atp/field/twitter/missing': 6712,
'atp/field/website/missing': 6712,
'atp/item_scraped_host_count/www.poczta-polska.pl': 6712,
'atp/nsi/cc_match': 6712,
'downloader/request_bytes': 5415415, …

[Poczta Polska PL] Fix Spider

---

locations/spiders/coccinelle_fr.py

```python
{'atp/brand/CocciMarket': 504,
'atp/brand/CocciMarket City': 47,
'atp/brand/Coccinelle Express': 166,
'atp/brand/Coccinelle Supermarché': 79,
'atp/brand_wikidata/Q90020459': 79,
'atp/brand_wikidata/Q90020479': 166,
'atp/brand_wikidata/Q90020480': 504,
'atp/brand_wikidata/Q90020481': 47,
'atp/category/shop/convenience': 551,
'atp/category/shop/supermarket': 245,
'atp/country/FR': 796,
'atp/field/branch/missing': 796,
'atp/field/email/missing': 425,
'atp/field/image/missing': 796,
'atp/field/opening_hours/missing': 796,
'atp/field/operator/missing': 796,
'atp/field/operator_wikidata/missing': 796,
'atp/field/phone/missing': 56,
'atp/field/state/missing': 796,
'atp/field/twitter/missing': …
```

[Coccinelle FR] Add spider

---

locations/spiders/putka_pl.py

```python
{'atp/brand/Putka': 254,
'atp/brand_wikidata/Q113093586': 254,
'atp/category/shop/bakery': 254,
'atp/country/PL': 254,
'atp/field/branch/missing': 254,
'atp/field/country/from_spider_name': 254,
'atp/field/email/missing': 254,
'atp/field/operator/missing': 254,
'atp/field/operator_wikidata/missing': 254,
'atp/field/state/missing': 254,
'atp/field/twitter/missing': 254,
'atp/item_scraped_host_count/www.putka.pl': 254,
'atp/nsi/perfect_match': 254,
'downloader/request_bytes': 127774,
'downloader/request_count': 311,
'downloader/request_method_count/GET': 311,
'downloader/response_bytes': 2947233,
'downloader/response_count': 311,
'downloader/response_status_count/200': 311,
'dupefilter/filtered': 2359, …
```

[Putka PL] Collect more palatable url

---

locations/spiders/dekra_fr.py

```python
{'atp/brand/DEKRA': 153,
'atp/brand_wikidata/Q383711': 153,
'atp/category/amenity/vehicle_inspection': 153,
'atp/country/FR': 153,
'atp/field/city/missing': 153,
'atp/field/country/from_spider_name': 153,
'atp/field/email/missing': 153,
'atp/field/image/missing': 153,
'atp/field/opening_hours/missing': 153,
'atp/field/operator/missing': 153,
'atp/field/operator_wikidata/missing': 153,
'atp/field/postcode/missing': 153,
'atp/field/state/missing': 153,
'atp/field/twitter/missing': 153,
'atp/item_scraped_host_count/www.dekra-pl.com': 153,
'atp/nsi/perfect_match': 153,
'downloader/request_bytes': 77653,
'downloader/request_count': 169,
'downloader/request_method_count/GET': 169,
'downloader/response_bytes': 9747385,
'downloader/response_count': 169, …
```

[Dekra FR] Add spider

---

locations/spiders/nicolas.py

```python
{'atp/brand/Nicolas': 534,
'atp/brand_wikidata/Q3340012': 534,
'atp/category/shop/alcohol': 534,
'atp/country/BE': 5,
'atp/country/BG': 1,
'atp/country/BJ': 1,
'atp/country/ES': 3,
'atp/country/FR': 482,
'atp/country/GB': 7,
'atp/country/GF': 2,
'atp/country/GP': 1,
'atp/country/LB': 1,
'atp/country/MA': 11,
'atp/country/MG': 3,
'atp/country/MQ': 2,
'atp/country/MU': 2,
'atp/country/PT': 1,
'atp/country/RE': 9,
'atp/country/RO': 1,
'atp/country/TN': 1,
'atp/country/TW': 1,
'atp/field/country/from_reverse_geocoding': 45,
'atp/field/email/missing': 64,
'atp/field/image/missing': 534,
'atp/field/opening_hours/missing': 534,
'atp/field/operator/missing': 534,
'atp/field/operator_wikidata/missing': 534, …
```

[Nicolas] Add spider

---

locations/spiders/5asec.py
locations/spiders/five_asec.py

```python
{'atp/brand/5àsec': 199,
'atp/brand_wikidata/Q2817899': 199,
'atp/category/shop/dry_cleaning': 199,
'atp/country/FR': 195,
'atp/country/MQ': 4,
'atp/field/branch/missing': 199,
'atp/field/country/from_reverse_geocoding': 199,
'atp/field/email/missing': 199,
'atp/field/image/missing': 199,
'atp/field/opening_hours/missing': 199,
'atp/field/operator/missing': 199,
'atp/field/operator_wikidata/missing': 199,
'atp/field/postcode/missing': 199,
'atp/field/twitter/missing': 199,
'atp/item_scraped_host_count/www.5asec.fr': 199,
'atp/nsi/perfect_match': 199,
'downloader/request_bytes': 84100,
'downloader/request_count': 201,
'downloader/request_method_count/GET': 201,
'downloader/response_bytes': 8447767,
'downloader/response_count': 201,
'downloader/response_status_count/200': 201, …
```

[5àsec] Add spider

---

locations/spiders/vinnies_au.py

https://www.wikidata.org/wiki/Q7592120
https://en.wikipedia.org/w/index.php?title=St._Vincent_de_Paul_Thrift_Store&oldid=647143127 before it was merged

[Vinnies AU] Remove brand

---

ci/run_pr_spiders.sh
locations/spiders/pep.py

Non functional API replaced by new one to fix the spider.
```
{'atp/brand/PEP': 1696,
'atp/brand/PEP Cell': 537,
'atp/brand/PEP Home': 395,
'atp/brand_wikidata/Q128802022': 395,
'atp/brand_wikidata/Q128802743': 537,
'atp/brand_wikidata/Q7166182': 1696,
'atp/category/shop/clothes': 1696,
'atp/category/shop/houseware': 395,
'atp/category/shop/mobile_phone': 537,
'atp/country/BW': 77,
'atp/country/LS': 36,
'atp/country/NA': 127,
'atp/country/SZ': 27,
'atp/country/ZA': 2361,
'atp/field/image/missing': 2628,
'atp/field/lat/missing': 10,
'atp/field/lon/missing': 10,
'atp/field/operator/missing': 2628,
'atp/field/operator_wikidata/missing': 2628, …
```

[Pep] Fix spider

---

locations/spiders/opentransportdata_swiss.py

https://opentransportdata.swiss/en/ckan-new-plattform-2025-01-08-en/

[OpenTranportData.swiss] Adjust spider to new site structure

---

locations/spiders/national_bank_of_greece_gr.py

Some of the ATMs are right outside the banks. I could use a combo of the Lat and Lon as a ref to grab branches first then just discard ATMs that have same lat and longitude. Currently it grabs everything which is probably fine.

[national_bank_of_greece_gr] Added spider (1687 items)

---

locations/spiders/whole_foods_gb.py

```
{'atp/brand/Whole Foods Market': 6,
'atp/brand_wikidata/Q1809448': 6,
'atp/category/shop/supermarket': 6,
'atp/country/GB': 6,
'atp/field/branch/missing': 6,
'atp/field/street_address/missing': 6,
'atp/item_scraped_host_count/www.wholefoodsmarket.co.uk': 6,
'atp/nsi/cc_match': 6,
'downloader/request_bytes': 704,
'downloader/response_bytes': 23479, …
```

[Whole Foods GB] Fix Spider

---

locations/spiders/louisa_coffee_tw.py

{'atp/brand/路易莎咖啡': 533,
'atp/brand_wikidata/Q96390921': 533,
'atp/category/amenity/cafe': 533,
'atp/country/TW': 533,
'atp/field/branch/missing': 533,
'atp/field/country/from_spider_name': 533,
'atp/field/email/missing': 533,
'atp/field/image/missing': 533,
'atp/field/lat/missing': 39,
'atp/field/lon/missing': 39,
'atp/field/opening_hours/missing': 533,
'atp/field/operator/missing': 533,
'atp/field/operator_wikidata/missing': 533,
'atp/field/phone/missing': 533,
'atp/field/postcode/missing': 533,
'atp/field/state/missing': 533,
'atp/field/street_address/missing': 533,
'atp/field/twitter/missing': 533,
'atp/field/website/missing': 533,
'atp/geometry/null_island': 37,
'atp/item_scraped_host_count/www.louisacoffee.co': 533, …

[Louisa Coffee TW] Fix Spider

---

locations/spiders/abn_amro_nl.py

Rel: https://github.com/osmlab/name-suggestion-index/commit/c6be44866ec1b2fda0114beb24dd78f1dbc6089f
> Geldmaat: the ATM for everyone
> Our ABN AMRO ATMs have been replaced by Geldmaat ATMs. Aside from the yellow color and the new name, little has changed. You can still withdraw money and check your balance as often as you like, using your own debit card.
https://www.abnamro.nl/en/personal/contact/find-a-branch-or-an-atm.html

[ABN AMRO NL] Rebrand ATMs to Geldmaat

---

locations/spiders/elements_massage_ca_us.py

```py
{'atp/brand/Elements Massage': 245,
'atp/brand_wikidata/Q113642393': 245,
'atp/category/shop/massage': 245,
'atp/country/CA': 1,
'atp/country/US': 244,
'atp/field/email/missing': 245,
'atp/field/image/missing': 245,
'atp/field/operator/missing': 245,
'atp/field/operator_wikidata/missing': 245,
'atp/field/twitter/missing': 245,
'atp/item_scraped_host_count/elementsmassage.com': 245,
'atp/nsi/perfect_match': 245,
'downloader/request_bytes': 26790,
'downloader/request_count': 73,
'downloader/request_method_count/GET': 73,
'downloader/response_bytes': 562226,
'downloader/response_count': 73,
'downloader/response_status_count/200': 73,
'elapsed_time_seconds': 88.873178, …
```

New spider: Elements Massage (245 locations)

---

locations/spiders/kia_au.py

Also tested other Kia spiders using KiaAUSpider

[Kia FJ] Fix Kia AU email handling to fix non running FJ spider

---

locations/spiders/7_brew_us.py

{'atp/brand/7 Brew': 334,
'atp/brand_wikidata/Q127688691': 334,
'atp/category/shop/coffee': 334,
'atp/country/US': 334,
'atp/field/branch/missing': 334,
'atp/field/city/missing': 334,
'atp/field/country/from_spider_name': 334,
'atp/field/email/missing': 334,
'atp/field/image/missing': 334,
'atp/field/lat/missing': 334,
'atp/field/lon/missing': 334,
'atp/field/operator/missing': 334,
'atp/field/operator_wikidata/missing': 334,
'atp/field/phone/missing': 334,
'atp/field/postcode/missing': 334,
'atp/field/state/missing': 334,
'atp/field/twitter/missing': 334,
'atp/item_scraped_host_count/7brew.com': 334,
'atp/nsi/brand_missing': 334,
'downloader/request_bytes': 122444,
'downloader/request_count': 337,
'downloader/request_method_count/GET': 337, …

[Seven Brew US] Fix Spider

---

locations/spiders/pizza_hut_qa.py

`Fixes : updated url to fix spider`
{'atp/brand/Pizza Hut': 37,
'atp/brand_wikidata/Q191615': 37,
'atp/category/amenity/restaurant': 37,
'atp/country/QA': 37,
'atp/field/branch/missing': 37,
'atp/field/country/from_spider_name': 37,
'atp/field/image/missing': 37,
'atp/field/operator/missing': 37,
'atp/field/operator_wikidata/missing': 37,
'atp/field/phone/missing': 37,
'atp/field/postcode/missing': 37,
'atp/field/state/missing': 37,
'atp/field/street_address/missing': 37,
'atp/field/twitter/missing': 37,
'atp/item_scraped_host_count/www.qatar.pizzahut.me': 37,
'atp/nsi/cc_match': 37,
'downloader/request_bytes': 650, …

[Pizza Hut QA] Fix Spider

---

locations/categories.py
locations/spiders/banyule_city_council_au.py

'atp/category/amenity/bicycle_repair_station': 6,
'atp/category/amenity/community_centre': 7,
'atp/category/amenity/kindergarten': 26,
'atp/category/amenity/library': 3,
'atp/category/healthcare/nurse': 12,
'atp/category/leisure/park': 123,
'atp/category/leisure/sports_centre': 8,

Add Banyule City Council (AU) (185 features)

---

locations/spiders/intermarche.py

```
{'atp/brand/Intermarché': 2407,
'atp/brand/Intermarché Contact': 270,
'atp/brand/Intermarché Express': 225,
'atp/brand/Intermarché Hyper': 128,
'atp/brand/Intermarché Super': 1294,
'atp/brand_wikidata/Q3153200': 2407,
'atp/brand_wikidata/Q98278022': 128,
'atp/brand_wikidata/Q98278038': 1294,
'atp/brand_wikidata/Q98278043': 225,
'atp/brand_wikidata/Q98278049': 270,
'atp/category/amenity/car_wash': 1074,
'atp/category/amenity/fuel': 1333,
'atp/category/missing': 155,
'atp/category/shop/convenience': 495,
'atp/category/shop/supermarket': 1422,
'atp/country/FR': 4479,
'atp/field/branch/missing': 4479,
'atp/field/brand/missing': 155,
'atp/field/brand_wikidata/missing': 155,
'atp/field/image/missing': 4479,
'atp/field/name/missing': …
```

[Intermarche] Set cookies and add custom settings to fix spider

---

locations/spiders/the_body_shop.py

{'atp/brand/The Body Shop': 636,
'atp/brand_wikidata/Q837851': 636,
'atp/category/shop/cosmetics': 636,
'atp/country/AD': 1,
'atp/country/AT': 23,
'atp/country/AU': 98,
'atp/country/CA': 61,
'atp/country/DE': 54,
'atp/country/DK': 2,
'atp/country/ES': 100,
'atp/country/FO': 1,
'atp/country/FR': 3,
'atp/country/GB': 115,
'atp/country/IE': 1,
'atp/country/NL': 27,
'atp/country/PT': 50,
'atp/country/SE': 68,
'atp/country/SG': 32,
'atp/field/email/missing': 636,
'atp/field/image/missing': 636,
'atp/field/lat/missing': 17,
'atp/field/lon/missing': 17,
'atp/field/opening_hours/missing': 636,
'atp/field/operator/missing': 636,
'atp/field/operator_wikidata/missing': 636,
'atp/field/phone/missing': …

[The Body Shop] Fix Spider

---

locations/spiders/burger_king_pe.py

**_Fixes : updated start_requests to fix spider_**
```python
{'atp/brand/Burger King': 27,
'atp/brand_wikidata/Q177054': 27,
'atp/category/amenity/fast_food': 27,
'atp/country/PE': 27,
'atp/field/branch/missing': 27,
'atp/field/country/from_spider_name': 27,
'atp/field/phone/missing': 27,
'atp/field/website/missing': 27,
'atp/item_scraped_host_count/apiprod.pidelo.digital': 27,
'atp/nsi/cc_match': 27, …
```

[Burger King PE ] Fix Spider

---

locations/storefinders/arcgis_feature_server.py

* Fix minor documentation errors and typos.
* Correctly compare data modification timestamp using UTC dates (not local dates).
* Fix broken debug message.

ArcGISFeatureServerSpider: minor fixes

---

locations/spiders/burger_king_jp.py

**_Fixes: code refactored to fix spider_**
```python
{'atp/brand/Burger King': 264,
'atp/brand_wikidata/Q177054': 264,
'atp/category/amenity/fast_food': 264,
'atp/country/JP': 264,
'atp/field/city/missing': 264,
'atp/field/country/from_spider_name': 264,
'atp/field/email/missing': 264,
'atp/field/image/missing': 264,
'atp/field/opening_hours/missing': 264,
'atp/field/operator/missing': 264,
'atp/field/operator_wikidata/missing': 264,
'atp/field/phone/missing': 264,
'atp/field/postcode/missing': 264,
'atp/field/state/missing': 264,
'atp/field/street_address/missing': 264,
'atp/field/twitter/missing': 264,
'atp/item_scraped_host_count/www.burgerking.co.jp': 264,
'atp/nsi/cc_match': 264,
'downloader/request_bytes': 1168, …
```

[Burger King JP] Fix Spider

---

locations/spiders/dennys.py
locations/spiders/dennys_us.py

Fixes : code refactored to use sitemap to fix spider
```python
{"atp/brand/Denny's": 1324,
'atp/brand_wikidata/Q1189695': 1324,
'atp/category/amenity/restaurant': 1324,
'atp/country/US': 1324,
'atp/field/branch/missing': 1324,
'atp/field/email/missing': 1324,
'atp/field/image/missing': 1324,
'atp/field/operator/missing': 1324,
'atp/field/operator_wikidata/missing': 1324,
'atp/item_scraped_host_count/locations.dennys.com': 1324,
'atp/nsi/perfect_match': 1324,
'downloader/request_bytes': 719456,
'downloader/request_count': 1326,
'downloader/request_method_count/GET': 1326,
'downloader/response_bytes': 23736015,
'downloader/response_count': 1326,
'downloader/response_status_count/200': 1326,
'elapsed_time_seconds': 1627.778104,
'finish_time': …
```

[Dennys] Fix Spider

---

locations/spiders/denner_ch.py

```python
{'atp/brand/Denner': 871,
'atp/brand_wikidata/Q379911': 871,
'atp/category/shop/supermarket': 871,
'atp/country/CH': 871,
'atp/field/branch/missing': 871,
'atp/field/country/from_spider_name': 871,
'atp/field/email/missing': 871,
'atp/field/image/missing': 871,
'atp/field/operator/missing': 871,
'atp/field/operator_wikidata/missing': 871,
'atp/field/phone/missing': 871,
'atp/field/state/missing': 871,
'atp/field/twitter/missing': 871,
'atp/item_scraped_host_count/www.denner.ch': 871,
'atp/nsi/perfect_match': 871,
'downloader/request_bytes': 426305,
'downloader/request_count': 873,
'downloader/request_method_count/GET': 873,
'downloader/response_bytes': 14988913,
'downloader/response_count': 873, …
```

[Denner CH] Fix Spider

---

locations/spiders/godfathers_pizza.py

**_Fixes :  code refactored to fix spider_**
```python
{"atp/brand/Godfather's Pizza": 612,
'atp/brand_wikidata/Q5576353': 612,
'atp/category/amenity/restaurant': 612,
'atp/country/US': 612,
'atp/field/branch/missing': 612,
'atp/field/email/missing': 612,
'atp/field/image/missing': 612,
'atp/field/opening_hours/missing': 612,
'atp/field/operator/missing': 612,
'atp/field/operator_wikidata/missing': 612,
'atp/field/twitter/missing': 612,
'atp/field/website/missing': 600,
'atp/item_scraped_host_count/oxb.pxsweb.com': 612,
'atp/nsi/perfect_match': 612, …
```

[Godfathers Pizza] Fix Spider

---

locations/spiders/goldsmiths_gb.py

```python
{'atp/brand/Goldsmiths': 156,
'atp/brand_wikidata/Q16993095': 156,
'atp/category/shop/jewelry': 156,
'atp/country/GB': 154,
'atp/country/GG': 1,
'atp/country/JE': 1,
'atp/field/branch/missing': 156,
'atp/field/image/missing': 156,
'atp/field/operator/missing': 156,
'atp/field/operator_wikidata/missing': 156,
'atp/field/state/missing': 156,
'atp/field/twitter/missing': 156,
'atp/item_scraped_host_count/www.goldsmiths.co.uk': 156,
'atp/nsi/perfect_match': 156,
'downloader/request_bytes': 19789,
'downloader/request_count': 34,
'downloader/request_method_count/GET': 34,
'downloader/response_bytes': 203339,
'downloader/response_count': 34,
'downloader/response_status_count/200': 34,
'elapsed_time_seconds': 4.65954, …
```

[Goldsmith GB] Fix spider

---

locations/spiders/access_storage_gb.py

https://github.com/osmlab/name-suggestion-index/issues/10518

[Access Self Storage GB] Update brand

---

locations/categories.py
locations/spiders/greater_geelong_city_council_crossings_au.py

Formal children/school crossings of roads.

Add Greater Geelong City Council crossings (AU) (172 crossings)

---

locations/spiders/burger_king_pe.py

**_Fixes : updated start_request to fix spider_**
```python
{'atp/brand/Burger King': 27,
'atp/brand_wikidata/Q177054': 27,
'atp/category/amenity/fast_food': 27,
'atp/country/PE': 27,
'atp/field/branch/missing': 27,
'atp/field/country/from_spider_name': 27,
'atp/field/phone/missing': 27,
'atp/field/website/missing': 27,
'atp/item_scraped_host_count/apiprod.pidelo.digital': 27,
'atp/nsi/cc_match': 27, …
```

[Burger King PE] Fix Spider

---

locations/spiders/action.py

**_Fixes : code refactored to use sitemap spider to fix spider_**
```python
{'atp/brand/Action': 2937,
'atp/brand_wikidata/Q2634111': 2937,
'atp/category/shop/variety_store': 2937,
'atp/cdn/cloudflare/response_count': 3174,
'atp/cdn/cloudflare/response_status_count/200': 3165,
'atp/cdn/cloudflare/response_status_count/404': 9,
'atp/country/AT': 116,
'atp/country/BE': 221,
'atp/country/CZ': 87,
'atp/country/DE': 585,
'atp/country/ES': 68,
'atp/country/FR': 858,
'atp/country/IT': 145,
'atp/country/LU': 11,
'atp/country/NL': 418,
'atp/country/PL': 388,
'atp/country/PT': 10,
'atp/country/SK': 30,
'atp/field/email/missing': 2937,
'atp/field/image/dropped': 2937,
'atp/field/image/missing': 2937,
'atp/field/opening_hours/missing': 2937,
'atp/field/operator/missing': …
```

[Action] Fix Spider

---

locations/spiders/cic.py
locations/spiders/cic_fr.py

**_Fixes : updated start_urls and parse method to fix spider_**
```python
{'atp/brand_wikidata/Q746525': 1262,
'atp/category/amenity/bank': 1262,
'atp/country/FR': 1262,
'atp/field/branch/missing': 1262,
'atp/field/brand/missing': 1262,
'atp/field/country/from_website_url': 1262,
'atp/field/email/missing': 1262,
'atp/field/image/missing': 1262,
'atp/field/operator/missing': 1262,
'atp/field/operator_wikidata/missing': 1262,
'atp/field/state/missing': 1262,
'atp/item_scraped_host_count/www.cic.fr': 1262,
'atp/nsi/match_failed': 1262,
'downloader/request_bytes': 1777306,
'downloader/request_count': 2351,
'downloader/request_method_count/GET': 2351,
'downloader/response_bytes': 53765824,
'downloader/response_count': 2351, …
```

[CIC] Fix Spider

---

locations/spiders/iron_mountain.py

**_Fixes : code updated to use structured data spider_**
```python
{'atp/brand/Iron Mountain': 509,
'atp/brand_wikidata/Q1673079': 509,
'atp/category/office/company': 509,
'atp/cdn/cloudflare/response_count': 931,
'atp/cdn/cloudflare/response_status_count/200': 930,
'atp/cdn/cloudflare/response_status_count/502': 1,
'atp/country/CA': 49,
'atp/country/PR': 4,
'atp/country/US': 456,
'atp/field/branch/missing': 509,
'atp/field/email/missing': 509,
'atp/field/opening_hours/missing': 509,
'atp/field/operator/missing': 509,
'atp/field/operator_wikidata/missing': 509,
'atp/item_scraped_host_count/locations.ironmountain.com': 509,
'atp/nsi/perfect_match': 509,
'downloader/request_bytes': 357135,
'downloader/request_count': 933,
'downloader/request_method_count/GET': 933, …
```

[Iron Mountain] Fix Spider

---

locations/spiders/beefeater_gb.py

**_Fixes : added user_agent to fix spider_**
```python
{'atp/brand/Beefeater': 115,
'atp/brand_wikidata/Q4879766': 115,
'atp/category/amenity/restaurant': 115,
'atp/country/GB': 115,
'atp/field/branch/missing': 115,
'atp/field/city/missing': 115,
'atp/field/country/from_spider_name': 115,
'atp/field/email/missing': 115,
'atp/field/image/missing': 115,
'atp/field/opening_hours/missing': 115,
'atp/field/operator/missing': 115,
'atp/field/operator_wikidata/missing': 115,
'atp/field/state/missing': 115,
'atp/field/twitter/missing': 115,
'atp/item_scraped_host_count/www.beefeater.co.uk': 115,
'atp/nsi/perfect_match': 115,
'downloader/request_bytes': 991,
'downloader/response_bytes': 15951, …
```

[Beefeater GB] Fix Spider

---

locations/spiders/chris_willemse_cycles_za.py

Only one location left and no valid coordinates are available. I was going to delete this chain but it is part of a broader group and therefore even a single location may be of interest. I started working on it before realising the coordinates are invalid. Oh well. Here is one single shop with a seemingly valid address and phone number.

chris_willemse_cycles_za: fix spider

---

locations/spiders/houlihans_us.py

Rel: https://github.com/osmlab/name-suggestion-index/commit/d0fbbfd7ff81d9e4e7d7c050d15e1f481555e3a3

[Houlihan's] Fix wikidata

---

locations/spiders/caffe_nero.py

_**Fixes : Flag robotstxt as false to fix spider**_
```python
{'atp/brand/Caffè Nero': 923,
'atp/brand_wikidata/Q675808': 923,
'atp/category/amenity/cafe': 923,
'atp/country/AE': 22,
'atp/country/CY': 21,
'atp/country/GB': 624,
'atp/country/IE': 22,
'atp/country/PL': 79,
'atp/country/SE': 13,
'atp/country/TR': 102,
'atp/country/US': 40,
'atp/field/city/missing': 923,
'atp/field/country/from_reverse_geocoding': 844,
'atp/field/country/from_website_url': 79,
'atp/field/email/missing': 923,
'atp/field/image/missing': 923,
'atp/field/operator/missing': 923,
'atp/field/operator_wikidata/missing': 923,
'atp/field/phone/missing': 40,
'atp/field/postcode/missing': 283,
'atp/field/state/missing': 80,
'atp/field/street_address/missing': 923, …
```

[Caffe Nero] Fix Spider

---

locations/spiders/vakifbank_tr.py

```python
{'atp/brand/Vakıfbank': 5038,
'atp/brand_wikidata/Q1148521': 5038,
'atp/category/amenity/atm': 4068,
'atp/category/amenity/bank': 970,
'atp/country/TR': 5038,
'atp/field/branch/missing': 4068,
'atp/field/city/missing': 5038,
'atp/field/country/from_spider_name': 5038,
'atp/field/email/missing': 5038,
'atp/field/image/missing': 5038,
'atp/field/opening_hours/missing': 5038,
'atp/field/operator/missing': 970,
'atp/field/operator_wikidata/missing': 970,
'atp/field/phone/missing': 5038,
'atp/field/postcode/missing': 5038,
'atp/field/state/missing': 5038,
'atp/field/street_address/missing': 5038,
'atp/item_scraped_host_count/apigw.vakifbank.com.tr:8443': 5038,
'atp/nsi/cc_match': 5038,
'atp/operator/Vakıfbank': 4068, …
```

[Vakifbank TR] Fix Spider

---

locations/spiders/black_bear_diner_us.py

also use named matches which I should have been doing already

Black Bear Diner: Fix spider by making regex more tolerant

---

.isort.cfg
locations/spiders/netto_de.py

Kinda hard to test for, if the spider stats suggests it works and counts normalise (currently 4402 for me) this should be added to all http2 spiders/settings.py
Possibly fixes #12326

[Netto DE] Retry on http2 network errors

---

locations/spiders/german_american_us.py

```python
{'atp/brand/German American': 84,
'atp/brand_wikidata/Q120753420': 84,
'atp/category/amenity/atm': 9,
'atp/category/amenity/bank': 75,
'atp/country/US': 84,
'atp/field/city/missing': 84,
'atp/field/country/from_spider_name': 84,
'atp/field/email/missing': 84,
'atp/field/image/missing': 84,
'atp/field/lat/missing': 84,
'atp/field/lon/missing': 84,
'atp/field/name/missing': 9,
'atp/field/opening_hours/missing': 84,
'atp/field/postcode/missing': 84,
'atp/field/state/missing': 84,
'atp/field/twitter/missing': 84,
'atp/item_scraped_host_count/germanamerican.com': 84,
'atp/nsi/cc_match': 84,
'atp/operator/German American': 9,
'atp/operator_wikidata/Q120753420': 9, …
```

[German American US] Fix Spider

---

locations/commands/insights.py

Given the march of time and in particular #12365 it is a good moment to trim some of the less relevant options to the `insights` command where the function / data is pretty much in the stats JSON output. Probably a little bit more to come in this area.

[insights command] drop a few long in the tooth options

---

locations/spiders/fantastic_sams_ca_us.py

```py
{'atp/brand/Fantastic Sams': 509,
'atp/brand_wikidata/Q5434222': 509,
'atp/category/shop/hairdresser': 509,
'atp/country/CA': 3,
'atp/country/US': 506,
'atp/field/branch/missing': 509,
'atp/field/email/missing': 509,
'atp/field/image/missing': 509,
'atp/field/opening_hours/missing': 509,
'atp/field/operator/missing': 509,
'atp/field/operator_wikidata/missing': 509,
'atp/field/twitter/missing': 509,
'atp/item_scraped_host_count/www.fantasticsams.com': 509,
'atp/nsi/perfect_match': 509,
'downloader/request_bytes': 171887,
'downloader/request_count': 511,
'downloader/request_method_count/GET': 511,
'downloader/response_bytes': 10351896,
'downloader/response_count': 511,
'downloader/response_status_count/200': 511,
'elapsed_time_seconds': 624.243289, …
```

New spider: Fantastic Sams (509 locations)

---

locations/spiders/primark.py
locations/structured_data_spider.py

```python
{'atp/brand/Primark': 452,
'atp/brand_wikidata/Q137023': 452,
'atp/category/shop/clothes': 452,
'atp/country/AT': 5,
'atp/country/BE': 8,
'atp/country/CZ': 3,
'atp/country/DE': 27,
'atp/country/ES': 62,
'atp/country/FR': 27,
'atp/country/GB': 196,
'atp/country/IE': 35,
'atp/country/IT': 19,
'atp/country/NL': 20,
'atp/country/PL': 7,
'atp/country/PT': 11,
'atp/country/RO': 2,
'atp/country/SI': 1,
'atp/country/SK': 1,
'atp/country/US': 28,
'atp/field/city/missing': 81,
'atp/field/email/missing': 452,
'atp/field/image/missing': 452,
'atp/field/operator/missing': 452,
'atp/field/operator_wikidata/missing': 452,
'atp/field/postcode/missing': 81,
'atp/field/state/from_reverse_geocoding': 28,
'atp/field/state/missing': …
```

[Primark] Fix coord and country extraction

---

locations/spiders/skipton_gb.py

```python
{'atp/brand/Skipton Building Society': 82,
'atp/brand_wikidata/Q16931747': 82,
'atp/category/amenity/bank': 82,
'atp/country/GB': 82,
'atp/field/city/missing': 82,
'atp/field/country/from_spider_name': 82,
'atp/field/image/missing': 82,
'atp/field/opening_hours/missing': 82,
'atp/field/operator/missing': 82,
'atp/field/operator_wikidata/missing': 82,
'atp/field/phone/missing': 82,
'atp/field/street_address/missing': 82,
'atp/field/twitter/missing': 82,
'atp/item_scraped_host_count/www.skipton.co.uk': 82,
'atp/nsi/cc_match': 82,
'downloader/request_bytes': 653,
'downloader/response_bytes': 10835, …
```

[Skipton GB] Fix Spider

---

locations/spiders/mcdonalds_es.py

**_Fixes : updated key to fix spider_**
```python
{'atp/brand/McCafé': 539,
"atp/brand/McDonald's": 630,
'atp/brand_wikidata/Q3114287': 539,
'atp/brand_wikidata/Q38076': 630,
'atp/category/amenity/cafe': 539,
'atp/category/amenity/fast_food': 630,
'atp/clean_strings/addr_full': 41,
'atp/clean_strings/city': 20,
'atp/clean_strings/postcode': 49,
'atp/country/ES': 1169,
'atp/field/branch/missing': 2,
'atp/field/country/from_spider_name': 1169,
'atp/field/email/missing': 1169,
'atp/field/image/missing': 1169,
'atp/field/opening_hours/missing': 539,
'atp/field/operator/missing': 1169,
'atp/field/operator_wikidata/missing': 1169,
'atp/field/phone/invalid': 24,
'atp/field/phone/missing': 74, …
```

[Mcdonalds ES] Fix Spider

---

locations/spiders/rush_hair_gb.py

Rel: https://github.com/osmlab/name-suggestion-index/pull/10611

[Rush Hair GB] Add spider

---

locations/spiders/mitsubishi.py

Stats:
```json
{
"atp/brand/Mitsubishi": 1428,
"atp/brand_wikidata/Q36033": 1428,
"atp/category/missing": 2,
"atp/category/shop/car": 1142,
"atp/category/shop/car_repair": 284,
"atp/clean_strings/addr_full": 1,
"atp/clean_strings/city": 1,
"atp/clean_strings/name": 1,
"atp/country/AT": 105,
"atp/country/BH": 5,
"atp/country/CA": 98,
"atp/country/EG": 27,
"atp/country/ES": 107,
"atp/country/FI": 52,
"atp/country/GR": 31,
"atp/country/IT": 176,
"atp/country/KW": 4,
"atp/country/MX": 56,
"atp/country/NL": 61,
"atp/country/NO": 62,
"atp/country/OM": 41,
"atp/country/PR": 20,
"atp/country/PT": 43,
"atp/country/QA": 7,
"atp/country/RO": 24,
"atp/country/TH": 194,
"atp/country/US": 315,
"atp/field/branch/missing": 1428,
"atp/field/city/missing": 894,
"atp/field/email/missing": 1183, …
```

[mitsubishi] add spider (1.4K locations, various countries)

---

.pre-commit-config.yaml
locations/spiders/mitsubishi_de.py

Stats:
```json
{
"atp/brand/Mitsubishi": 538,
"atp/brand_wikidata/Q36033": 538,
"atp/category/shop/car": 451,
"atp/category/shop/car_repair": 87,
"atp/cdn/cloudflare/response_count": 540,
"atp/cdn/cloudflare/response_status_count/200": 540,
"atp/clean_strings/city": 20,
"atp/clean_strings/email": 28,
"atp/clean_strings/name": 33,
"atp/clean_strings/phone": 22,
"atp/clean_strings/postcode": 20,
"atp/clean_strings/street_address": 27,
"atp/country/DE": 538,
"atp/field/branch/missing": 538,
"atp/field/country/from_spider_name": 538,
"atp/field/email/missing": 2,
"atp/field/image/missing": 538,
"atp/field/opening_hours/missing": 538,
"atp/field/operator/missing": 538,
"atp/field/operator_wikidata/missing": 538,
"atp/field/phone/invalid": 6,
"atp/field/state/missing": 538, …
```

[mitsubishi_de] add spider (538 locations)

---

locations/spiders/mitsubishi_fr.py

```json
{
"atp/brand/Mitsubishi": 117,
"atp/brand_wikidata/Q36033": 117,
"atp/category/shop/car": 101,
"atp/category/shop/car_repair": 16,
"atp/clean_strings/addr_full": 7,
"atp/clean_strings/city": 1,
"atp/clean_strings/name": 2,
"atp/clean_strings/phone": 3,
"atp/country/FR": 117,
"atp/field/branch/missing": 117,
"atp/field/country/from_spider_name": 117,
"atp/field/email/missing": 117,
"atp/field/image/missing": 117,
"atp/field/opening_hours/missing": 117,
"atp/field/operator/missing": 117,
"atp/field/operator_wikidata/missing": 117,
"atp/field/phone/invalid": 2,
"atp/field/phone/missing": 1,
"atp/field/state/missing": 117,
"atp/field/street_address/missing": 117,
"atp/field/twitter/missing": 117,
"atp/item_scraped_host_count/www.mitsubishi-motors.fr": 117,
"atp/nsi/cc_match": 117, …
```

[mitsubishi_fr] add spider (117 locations)

---

locations/spiders/total_energies.py

Rel: https://github.com/osmlab/name-suggestion-index/pull/10474

[Total Energies] Update Cepsa brand

---

locations/spiders/aspen_dental_us.py

```py
{'atp/brand/Aspen Dental': 1113,
'atp/brand_wikidata/Q4807808': 1113,
'atp/category/amenity/dentist': 1113,
'atp/category/multiple': 1113,
'atp/country/US': 1113,
'atp/field/country/from_spider_name': 1113,
'atp/field/email/missing': 1113,
'atp/field/image/missing': 1113,
'atp/field/operator/missing': 1113,
'atp/field/operator_wikidata/missing': 1113,
'atp/field/twitter/missing': 1113,
'atp/item_scraped_host_count/www.aspendental.com': 1113,
'atp/nsi/perfect_match': 1113,
'downloader/request_bytes': 1573,
'downloader/response_bytes': 103053, …
```

New spider: Aspen Dental (1113 locations)

---

locations/spiders/fireaway_gb.py

```python
{'atp/brand/Fireaway': 160,
'atp/brand_wikidata/Q110484131': 160,
'atp/category/amenity/fast_food': 160,
'atp/clean_strings/housenumber': 2,
'atp/clean_strings/postcode': 1,
'atp/clean_strings/street': 38,
'atp/country/GB': 160,
'atp/field/country/from_spider_name': 160,
'atp/field/email/missing': 160,
'atp/field/image/missing': 160,
'atp/field/opening_hours/missing': 160,
'atp/field/operator/missing': 160,
'atp/field/operator_wikidata/missing': 160,
'atp/field/phone/missing': 160,
'atp/field/state/missing': 160,
'atp/field/street_address/missing': 160,
'atp/field/twitter/missing': 160, …
```

[Fireaway GB] Update API to fix spider

---

locations/spiders/mercy_health_us.py

`Sitemap` based spider is unstable and sometimes fails to crawl, like it happened in one of [previous run](https://alltheplaces-data.openaddresses.io/runs/2025-01-25-13-31-58/stats/mercy_health_us.json). Hence, code refactored using `API` to make it stable and also to get increased count by about `160` POIs. Also done some code enhancement for category mapping.
```python
{'atp/category/amenity/clinic': 669,
'atp/category/amenity/doctors': 150,
'atp/category/amenity/hospital': 23,
'atp/category/amenity/pharmacy': 17,
'atp/category/amenity/social_facility': 1,
'atp/category/emergency/emergency_ward_entrance': 32,
'atp/category/healthcare/audiologist': 6,
'atp/category/healthcare/birthing_centre': 16,
'atp/category/healthcare/hospice': 17,
'atp/category/healthcare/laboratory': 97, …
```

[Mercy Health US] Make Spider more stable using API and get higher POIs count

---

locations/spiders/under_armour_ae_sa.py

#12240
```
{'atp/brand/Under Armour': 35,
'atp/brand_wikidata/Q2031485': 35,
'atp/category/shop/clothes': 35,
'atp/cdn/cloudflare/response_status_count/200': 4,
'atp/clean_strings/name': 3,
'atp/country/AE': 14,
'atp/country/SA': 21,
'atp/field/branch/missing': 35,
'atp/field/opening_hours/invalid': 26,
'atp/field/website/missing': 35,
'atp/item_scraped_host_count/www.underarmour.ae': 14, …
```

New spider: Under Armour AE/SA (35 locations)

---

locations/spiders/mitsubishi_au.py

There are exactly 200 dealers in Australia: https://www.mitsubishi-motors.com.au/company/company-profile.html
```json
{
"atp/brand/Mitsubishi": 200,
"atp/brand_wikidata/Q36033": 200,
"atp/category/shop/car": 194,
"atp/category/shop/car_repair": 6,
"atp/clean_strings/street": 1,
"atp/country/AU": 200,
"atp/field/branch/missing": 200,
"atp/field/email/missing": 200,
"atp/field/image/missing": 200,
"atp/field/opening_hours/missing": 200,
"atp/field/operator/missing": 200,
"atp/field/operator_wikidata/missing": 200,
"atp/field/street_address/missing": 200,
"atp/field/twitter/missing": 200,
"atp/field/website/missing": 200,
"atp/item_scraped_host_count/store.mitsubishi-motors.com.au": 200,
"atp/nsi/cc_match": 200,
"downloader/request_bytes": 2617, …
```

[mitsubishi_au] add spider (200 locations)

---

locations/spiders/mcdonalds_pt.py

I can't remember if I pushed this and forgot to open the PR, or if I didn't open for a reason..

[Mcdonalds PT] Collect attributes and opening hours

---

locations/spiders/one_stop_gb.py

**_Fixes : updated start_requests and parse method to fix spider_**
```python
{'atp/brand/One Stop': 1082,
'atp/brand_wikidata/Q65954217': 1082,
'atp/category/shop/convenience': 1082,
'atp/country/GB': 1082,
'atp/field/branch/missing': 1082,
'atp/field/city/missing': 1082,
'atp/field/country/from_spider_name': 1082,
'atp/field/email/missing': 1082,
'atp/field/image/missing': 1082,
'atp/field/operator/missing': 1082,
'atp/field/operator_wikidata/missing': 1082,
'atp/field/phone/missing': 69,
'atp/field/state/missing': 1082,
'atp/field/twitter/missing': 1082,
'atp/item_scraped_host_count/www.onestop.co.uk': 9538,
'atp/nsi/perfect_match': 1082,
'atp/one_stop_gb/store_format/Check': …
```

[One Stop GB] Fix Spider

---

locations/spiders/mitsubishi.py

I've added a fallback for the case if country/language combination is not available in the API, which resulted in additional 70 POIs from Philippines.
```json
{
"atp/brand/Mitsubishi": 1498,
"atp/brand_wikidata/Q36033": 1498,
"atp/category/missing": 7,
"atp/category/shop/car": 1206,
"atp/category/shop/car_repair": 285,
"atp/clean_strings/city": 1,
"atp/clean_strings/name": 1,
"atp/country/AT": 105,
"atp/country/BH": 5,
"atp/country/CA": 98,
"atp/country/EG": 27,
"atp/country/ES": 107,
"atp/country/FI": 52,
"atp/country/GR": 31,
"atp/country/IT": 176,
"atp/country/KW": 4,
"atp/country/MX": 56,
"atp/country/NL": 61,
"atp/country/NO": 62,
"atp/country/OM": 41,
"atp/country/PH": 70,
"atp/country/PR": 20,
"atp/country/PT": 43,
"atp/country/QA": 7,
"atp/country/RO": 24,
"atp/country/TH": 194, …
```

[mitsubishi] add PH (+70 locations)

---

locations/spiders/fnb_atm_za.py

Summary generated below is before adding the code for handling the `IndexError` .
```python
{'atp/brand/FNB': 4623,
'atp/brand_wikidata/Q3072956': 4623,
'atp/category/amenity/atm': 4623,
'atp/country/ZA': 4623,
'atp/field/city/missing': 4623,
'atp/field/country/from_spider_name': 4623,
'atp/field/email/missing': 4623,
'atp/field/image/missing': 4623,
'atp/field/name/missing': 4623,
'atp/field/opening_hours/missing': 4623,
'atp/field/phone/missing': 4623,
'atp/field/postcode/missing': 4623,
'atp/field/state/missing': 4623,
'atp/field/street_address/missing': 4623,
'atp/field/twitter/missing': 4623,
'atp/field/website/missing': 4623,
'atp/geometry/null_island': 3,
'atp/item_scraped_host_count/www.fnb.co.za': 4623,
'atp/nsi/cc_match': …
```

[Fnb Atm ZA] Fix spider against blockage to regain POIs count

---

locations/spiders/mitsubishi_vn.py

Stats:
```json
{
"atp/brand/Mitsubishi": 63,
"atp/brand_wikidata/Q36033": 63,
"atp/category/shop/car": 63,
"atp/clean_strings/name": 1,
"atp/clean_strings/phone": 1,
"atp/country/VN": 63,
"atp/field/branch/missing": 63,
"atp/field/city/missing": 27,
"atp/field/country/from_spider_name": 63,
"atp/field/email/missing": 63,
"atp/field/image/missing": 63,
"atp/field/opening_hours/missing": 63,
"atp/field/operator/missing": 63,
"atp/field/operator_wikidata/missing": 63,
"atp/field/phone/missing": 1,
"atp/field/postcode/missing": 23,
"atp/field/street_address/missing": 63,
"atp/field/twitter/missing": 63,
"atp/field/website/missing": 1,
"atp/item_scraped_host_count/www.mitsubishi-motors.com.vn": 63,
"atp/nsi/cc_match": 63,
"downloader/request_bytes": 654, …
```

[mitsubishi_vn] add spider (63 locations)

---

locations/spiders/bambu.py

Same change as #12580. Maybe this is a store finder? The query itself is different though.

Bambu: Add authorization header to fix spider

---

locations/json_blob_spider.py

Fixes an AttributeError in mountain_america_credit_union_us spider

JSONBlobSpider: Skip null entries in parse_feature_dict

---

locations/spiders/wendys_gb.py

Unfortunately drive through opening hours are no longer available

[Wendys GB] Collect wifi attribute

---

locations/spiders/coles_au.py

Rel: https://github.com/osmlab/name-suggestion-index/pull/10618
```python
{'atp/brand/Coles': 575,
'atp/brand/First Choice Liquor': 57,
'atp/brand/Liquorland': 552,
'atp/brand/Reddy Express': 432,
'atp/brand/Vintage Cellars': 23,
'atp/brand_wikidata/Q1108172': 575,
'atp/brand_wikidata/Q2283837': 552,
'atp/brand_wikidata/Q4596269': 57,
'atp/brand_wikidata/Q5144653': 432,
'atp/brand_wikidata/Q7932815': 23,
'atp/category/shop/alcohol': 632,
'atp/category/shop/convenience': 432,
'atp/category/shop/supermarket': 575,
'atp/country/AU': 1639,
'atp/field/country/from_spider_name': 1639,
'atp/field/email/missing': 1639,
'atp/field/image/missing': 1639,
'atp/field/operator/missing': 1064,
'atp/field/operator_wikidata/missing': 1064,
'atp/field/twitter/missing': 1639, …
```

[Coles AU] Update brands and collect opening hours

---

locations/spiders/travel_midwest_us.py

'atp/operator/DuPage County Division of Transportation': 154,
'atp/operator/Illinois Department of Transportation': 551,
'atp/operator/Illinois State Toll Highway Authority': 15,
'atp/operator/Indiana Department of Transportation': 56,
'atp/operator/Kentucky Transportation Cabinet': 6,
'atp/operator/Lake County Division of Transportation': 395,
'atp/operator/Wisconsin Department of Transportation': 255,

Add Travel Midwest (US) (1432 traffic cameras)

---

locations/spiders/my_dentist_gb.py

```python
{'atp/brand/My Dentist': 504,
'atp/brand_wikidata/Q65118035': 504,
'atp/category/amenity/dentist': 504,
'atp/category/missing': 13,
'atp/category/multiple': 504,
'atp/cdn/cloudflare/response_count': 803,
'atp/cdn/cloudflare/response_status_count/200': 802,
'atp/cdn/cloudflare/response_status_count/500': 1,
'atp/country/GB': 517,
'atp/field/branch/missing': 517,
'atp/field/brand/missing': 13,
'atp/field/brand_wikidata/missing': 13,
'atp/field/city/missing': 517,
'atp/field/country/from_website_url': 517,
'atp/field/email/missing': 517,
'atp/field/image/missing': 517,
'atp/field/operator/missing': 517,
'atp/field/operator_wikidata/missing': 517,
'atp/field/state/missing': 517,
'atp/field/street_address/missing': 517,
'atp/field/twitter/missing': 517, …
```

[My Dentist GB] Fix spider

---

locations/spiders/binnys.py
locations/spiders/binnys_us.py

```python
{"atp/brand/Binny's Beverage Depot": 47,
'atp/brand_wikidata/Q30687714': 47,
'atp/category/shop/alcohol': 47,
'atp/cdn/cloudflare/response_count': 51,
'atp/cdn/cloudflare/response_status_count/200': 51,
'atp/country/US': 47,
'atp/field/country/from_reverse_geocoding': 47,
'atp/field/opening_hours/missing': 47,
'atp/field/website/missing': 47,
'atp/item_scraped_host_count/www.binnys.com': 47,
'atp/nsi/perfect_match': 47,
'downloader/exception_type_count/twisted.internet.error.TimeoutError': 1,
'downloader/request_bytes': 44222,
'downloader/request_count': 52,
'downloader/request_method_count/GET': 52, …
```

[Binnys] Fix non running spider

---

locations/spiders/mitsubishi_pe.py

```python
{'atp/brand/Mitsubishi': 42,
'atp/brand_wikidata/Q36033': 42,
'atp/category/shop/car': 32,
'atp/category/shop/car_parts': 2,
'atp/category/shop/car_repair': 8,
'atp/clean_strings/addr_full': 3,
'atp/country/PE': 42,
'atp/field/city/missing': 42,
'atp/field/country/from_spider_name': 42,
'atp/field/image/missing': 42,
'atp/field/lat/missing': 39,
'atp/field/lon/missing': 39,
'atp/field/name/missing': 2,
'atp/field/opening_hours/missing': 42,
'atp/field/operator/missing': 42,
'atp/field/operator_wikidata/missing': 42,
'atp/field/postcode/missing': 42,
'atp/field/state/missing': 42,
'atp/field/street_address/missing': 42,
'atp/field/twitter/missing': 42, …
```

[Mitsubishi PE] Add Spider (42 locations)

---

locations/spiders/aldi_nord_de.py
locations/spiders/aldi_nord_fr.py
locations/spiders/aldi_sud_de.py
locations/spiders/aldi_sud_ie.py
locations/spiders/edeka_de.py
locations/spiders/rewe_de.py

https://github.com/osmlab/name-suggestion-index/pull/10738

Clean up German brand drama

---

locations/spiders/mitsubishi_uy.py

```python
{'atp/brand/Mitsubishi': 27,
'atp/brand_wikidata/Q36033': 27,
'atp/category/shop/car': 27,
'atp/clean_strings/addr_full': 4,
'atp/country/UY': 27,
'atp/field/country/from_spider_name': 27,
'atp/field/opening_hours/missing': 27,
'atp/field/website/missing': 27,
'atp/item_scraped_host_count/www.mitsubishi-motors.com.uy': 27,
'atp/nsi/cc_match': 27,
'downloader/request_bytes': 330, …
```

[Mitsubishi UY] Add Spider (27 locations)

---

locations/spiders/mitsubishi_my.py

```python
{'atp/brand/Mitsubishi': 134,
'atp/brand_wikidata/Q36033': 134,
'atp/category/shop/car': 63,
'atp/category/shop/car_painting': 5,
'atp/category/shop/car_parts': 2,
'atp/category/shop/car_repair': 64,
'atp/clean_strings/email': 1,
'atp/country/MY': 134,
'atp/field/branch/missing': 134,
'atp/field/city/missing': 134,
'atp/field/country/from_spider_name': 134,
'atp/field/email/invalid': 8,
'atp/field/opening_hours/missing': 134,
'atp/field/operator/missing': 134,
'atp/field/operator_wikidata/missing': 134,
'atp/field/postcode/missing': 134,
'atp/field/street_address/missing': 134,
'atp/field/twitter/missing': 134,
'atp/field/website/missing': 134, …
```

[Mitsubishi MY] Add spider (134 locations)

---

locations/spiders/meijer_us.py

```python
{'atp/brand/Meijer': 760,
'atp/brand_wikidata/Q1917753': 760,
'atp/category/amenity/fuel': 208,
'atp/category/amenity/pharmacy': 276,
'atp/category/multiple': 276,
'atp/category/shop/supermarket': 276,
'atp/country/US': 760,
'atp/field/email/missing': 760,
'atp/field/image/missing': 760,
'atp/field/name/missing': 276,
'atp/field/operator/missing': 760,
'atp/field/operator_wikidata/missing': 760,
'atp/field/twitter/missing': 760,
'atp/item_scraped_host_count/www.meijer.com': 760,
'atp/nsi/cc_match': 484,
'atp/nsi/match_failed': 276,
'downloader/request_bytes': 704184,
'downloader/request_count': 281,
'downloader/request_method_count/GET': 281,
'downloader/response_bytes': 1121535, …
```

[Meijer US] Collect fuel stations

---

locations/spiders/mitsubishi_cl.py

```python
{'atp/brand/Mitsubishi': 82,
'atp/brand_wikidata/Q36033': 82,
'atp/category/shop/car': 52,
'atp/category/shop/car_parts': 30,
'atp/country/CL': 82,
'atp/field/country/from_spider_name': 82,
'atp/field/email/missing': 82,
'atp/field/image/missing': 82,
'atp/field/lat/missing': 15,
'atp/field/lon/missing': 15,
'atp/field/name/missing': 30,
'atp/field/opening_hours/missing': 82,
'atp/field/operator/missing': 82,
'atp/field/operator_wikidata/missing': 82,
'atp/field/postcode/missing': 82,
'atp/field/twitter/missing': 82,
'atp/field/website/missing': 82,
'atp/item_scraped_host_count/mitsubishi-motors.cl': …
```

[Mitsubishi CL] Add Spider (82 locations)

---

locations/spiders/mitsubishi_pa_ni_sv.py

```python
{'atp/brand/Mitsubishi': 17,
'atp/brand_wikidata/Q36033': 17,
'atp/category/shop/car': 17,
'atp/clean_strings/addr_full': 10,
'atp/clean_strings/email': 6,
'atp/clean_strings/phone': 9,
'atp/country/NI': 3,
'atp/country/PA': 10,
'atp/country/SV': 4,
'atp/field/email/invalid': 3,
'atp/field/lat/missing': 9,
'atp/field/lon/missing': 9, …
```

[Mitsubishi Pa Ni Sv] Add Spider (17 locations)

---

locations/spiders/mitsubishi_cz_sk.py

```python
{'atp/brand/Mitsubishi': 38,
'atp/brand_wikidata/Q36033': 38,
'atp/category/shop/car': 27,
'atp/category/shop/car_repair': 11,
'atp/clean_strings/phone': 38,
'atp/country/CZ': 25,
'atp/country/SK': 13,
'atp/field/branch/missing': 38,
'atp/field/country/from_website_url': 38,
'atp/item_scraped_host_count/www.mitsubishi-motors.cz': 25,
'atp/item_scraped_host_count/www.mitsubishi-motors.sk': 13,
'atp/nsi/cc_match': 38,
'downloader/request_bytes': 35128, …
```

[Mistubishi CZ SK] Update Mistubishi CZ Spider to add SK locations

---

locations/spiders/mitsubishi_pl.py

```python
{'atp/brand/Mitsubishi': 34,
'atp/brand_wikidata/Q36033': 34,
'atp/category/shop/car': 31,
'atp/category/shop/car_repair': 3,
'atp/clean_strings/phone': 20,
'atp/country/PL': 34,
'atp/field/branch/missing': 34,
'atp/field/country/from_spider_name': 34,
'atp/field/image/missing': 34,
'atp/field/opening_hours/missing': 34,
'atp/field/operator/missing': 34,
'atp/field/operator_wikidata/missing': 34,
'atp/field/state/missing': 34,
'atp/field/street_address/missing': 34,
'atp/field/twitter/missing': 34,
'atp/item_scraped_host_count/www.mitsubishi.pl': 34,
'atp/nsi/cc_match': 34,
'downloader/request_bytes': 1794,
'downloader/request_method_count/POST': …
```

[Mitsubishi PL] Add spider (34 locations)

---

locations/spiders/national.py

This was getting `brand=NATIONAL` from the source data.

[National] Sync brand with NSI and clean name

---

locations/spiders/ubb_bg.py

Ref: https://github.com/osmlab/name-suggestion-index/commit/a8610c93317af87468f5d56b9bbeadd1c7bd9f76

[Ubb BG] Update brand string

---

locations/spiders/walmart_us.py

I am confidant this spider will NOT work in the action or in the next weekly, however there was a [week](https://www.alltheplaces.xyz/spiders.html?search=walmart_us) where the gods let us in, and if that happens again, we should be correctly categorised.

[Walmart US] Improve categories

---

locations/spiders/mitsubishi_ua.py

```python
{'atp/brand/Mitsubishi': 29,
'atp/brand_wikidata/Q36033': 29,
'atp/category/shop/car': 29,
'atp/country/UA': 29,
'atp/field/branch/missing': 29,
'atp/field/state/missing': 29,
'atp/item_scraped_host_count/mitsubishi-motors.com.ua': 29,
'atp/nsi/cc_match': 29,
'downloader/request_bytes': 318,
'downloader/response_bytes': 26582, …
```

[Mitsubishi UA] Add spider (29 locations)

---

locations/spiders/mitsubishi_ma.py

```python
{'atp/brand/Mitsubishi': 33,
'atp/brand_wikidata/Q36033': 33,
'atp/category/shop/car': 33,
'atp/country/MA': 33,
'atp/field/country/from_spider_name': 33,
'atp/field/email/missing': 33,
'atp/field/image/missing': 33,
'atp/field/opening_hours/missing': 33,
'atp/field/operator/missing': 33,
'atp/field/operator_wikidata/missing': 33,
'atp/field/postcode/missing': 33,
'atp/field/state/missing': 33,
'atp/field/twitter/missing': 33,
'atp/field/website/missing': 33,
'atp/item_scraped_host_count/www.mitsubishi-motors.ma': 33,
'atp/nsi/cc_match': 33,
'downloader/request_bytes': 315,
'downloader/response_bytes': 182423, …
```

[Mitsubishi MA] Add Spider (33 locations)

---

locations/spiders/seven_eleven_se.py

Seems to be the same parent company or outsourced store finder/web design company as pressbyran_se. Refactor this spider to match pressbyran_se as both spiders are almost identical.

seven_eleven_se: refactor spider

---

locations/spiders/starbucks_za.py

**_Fixes : updated url & post_process_item method  to fix spider_** 
```python
{'atp/brand/Starbucks': 72,
'atp/brand_wikidata/Q37158': 72,
'atp/category/amenity/cafe': 72,
'atp/cdn/cloudflare/response_count': 36,
'atp/cdn/cloudflare/response_status_count/200': 36,
'atp/country/ZA': 72,
'atp/field/image/missing': 72,
'atp/field/opening_hours/missing': 72,
'atp/field/state/missing': 72,
'atp/field/street_address/missing': 72,
'atp/field/twitter/missing': 72,
'atp/field/website/missing': 72,
'atp/item_scraped_host_count/www.starbucks.co.za': 258,
'atp/nsi/cc_match': 72,
'downloader/request_bytes': 17489, …
```

[Starbucks ZA] Fix Spider

---

locations/spiders/dollars_and_sense_au.py

No coordinates available as source only provides a link to a Google Map search for each branch name.

Add Dollars and Sense (AU) (21 variety stores)

---

locations/spiders/wildberries.py

A small update was needed to correctly process the latest API.

fix(wildberries): updates API usage

---

locations/spiders/infrastructure/seattle_parks_and_recreation_dog_parks_us.py

Add Seattle Parks and Recreation dog parks (US) (15 parks)

---

locations/spiders/infrastructure/seattle_parks_and_recreation_baseball_fields_us.py

Add Seattle Parks and Recreation baseball fields (US) (83 facilities)

---

locations/categories.py
locations/spiders/infrastructure/seattle_parks_and_recreation_gardens_us.py

Add Seattle Parks and Recreation gardens (US) (7 gardens)

---

locations/spiders/infrastructure/seattle_parks_and_recreation_football_fields_us.py

Add Seattle Parks and Recreation football fields (US) (21 fields)

---

locations/spiders/infrastructure/seattle_parks_and_recreation_tennis_courts_us.py

Add Seattle Parks and Recreation tennis courts (US) (53 facilities)

---

locations/spiders/infrastructure/seattle_parks_and_recreation_soccer_fields_us.py

Add Seattle Parks and Recreation soccer fields (US) (83 fields)

---

locations/spiders/infrastructure/seattle_parks_and_recreation_skate_parks_us.py

Add Seattle Parks and Recreation skate parks (US) (12 parks)

---

locations/spiders/infrastructure/seattle_parks_and_recreation_playgrounds_us.py

Add Seattle Parks and Recreation playgrounds (US) (156 playgrounds)

---

locations/spiders/infrastructure/seattle_parks_and_recreation_parks_us.py

Add Seattle Parks and Recreation parks (US) (484 parks)

---

locations/spiders/infrastructure/seattle_parks_and_recreation_benches_us.py

Add Seattle Parks and Recreation benches (US) (3045 benches)

---

locations/spiders/ecopack_bg.py

Added ecopack_bg spider

---

locations/spiders/ocharleys_us.py

The old one redirected to the website for a different brand

O'Charley's: Rewrite to use new website

---

locations/storefinders/nomnom.py

Rel: https://github.com/alltheplaces/alltheplaces/pull/12743/files#r2025062369

[NomNom] Update delivery hours key

---

locations/spiders/starbucks_us.py

Unfortunately not expecting this to work in CI or weekly.

[Starbucks US] set located_in

---

locations/spiders/toyota_ca.py

```python
{'atp/brand/Toyota': 247,
'atp/brand_wikidata/Q53268': 247,
'atp/category/shop/car': 247,
'atp/clean_strings/name': 3,
'atp/country/CA': 247,
'atp/field/branch/missing': 247,
'atp/field/country/from_spider_name': 247,
'atp/field/image/missing': 247,
'atp/field/opening_hours/missing': 247,
'atp/field/operator/missing': 247,
'atp/field/operator_wikidata/missing': 247,
'atp/field/twitter/missing': 247,
'atp/item_scraped_host_count/www.toyota.ca': 247,
'atp/nsi/cc_match': 247,
'downloader/request_bytes': 1043,
'downloader/response_bytes': 26724, …
```

[Toyota CA] Fix Spider

---

locations/spiders/discount_tire.py

**_Fixes : updated url and query to fix spider_**
```python
{'atp/brand/Discount Tire': 1094,
'atp/brand_wikidata/Q5281735': 1094,
'atp/category/shop/tyres': 1094,
'atp/country/US': 1094,
'atp/field/branch/missing': 1094,
'atp/field/image/missing': 1094,
'atp/field/operator/missing': 1094,
'atp/field/operator_wikidata/missing': 1094,
'atp/field/twitter/missing': 1094,
'atp/item_scraped_host_count/www.discounttire.com': 1094,
'atp/nsi/perfect_match': 1094,
'downloader/exception_type_count/twisted.web._newclient.ResponseNeverReceived': 1,
'downloader/request_bytes': 2799598,
'downloader/request_count': 2202,
'downloader/request_method_count/GET': 1107,
'downloader/request_method_count/POST': 1095,
'downloader/response_bytes': 261444810, …
```

[Discount Tire] Fix Spider

---

locations/spiders/sopharmacy_bg.py

Pipelines expect Feature, not dict.

[Sopharmacy BG] Ensure Feature is returned

---

locations/spiders/canada_post_ca.py

```python
{'atp/brand/Canada Post': 5618,
'atp/brand_wikidata/Q1032001': 5618,
'atp/category/amenity/post_office': 5618,
'atp/category/missing': 179,
'atp/country/CA': 5797,
'atp/field/branch/missing': 5797,
'atp/field/brand/missing': 179,
'atp/field/brand_wikidata/missing': 179,
'atp/field/city/missing': 5797,
'atp/field/country/from_spider_name': 5797,
'atp/field/email/missing': 5797,
'atp/field/image/missing': 5797,
'atp/field/operator/missing': 5618,
'atp/field/operator_wikidata/missing': 5797,
'atp/field/phone/missing': 5797,
'atp/field/state/from_reverse_geocoding': 5797,
'atp/field/state/missing': 123,
'atp/field/street_address/missing': 70,
'atp/field/twitter/missing': 5797,
'atp/field/website/missing': 5797, …
```

[Canada Post CA] Recover lost POIs for the spider

---

locations/spiders/minimart_bg.py

This is the chain's website, not a website for each individual location

[Minimart BG] Drop website

---

.isort.cfg
ci/run_pr_spiders.sh
locations/spiders/ecobulpack_bg.py
pyproject.toml

Based on https://gist.github.com/jleedev/7fbeb9f497c7a0c04424b8c3cf48e8f9

[ecobulpack_bg] Add spider

---

locations/storefinders/nomnom.py

Fix for https://github.com/alltheplaces/alltheplaces/pull/12743#discussion_r2019717383. It's more correct to use the same function signature as the overridden function.

NomNom: Check type of response

---

locations/spiders/freddys_us.py

```py
{"atp/brand/Freddy's": 543,
'atp/brand_wikidata/Q5496837': 543,
'atp/category/amenity/fast_food': 543,
'atp/country/US': 543,
'atp/field/email/missing': 543,
'atp/field/image/missing': 543,
'atp/field/operator/missing': 543,
'atp/field/operator_wikidata/missing': 543,
'atp/field/twitter/missing': 543,
'atp/item_scraped_host_count/www.freddys.com': 543,
'atp/nsi/perfect_match': 543,
'downloader/request_bytes': 983,
'downloader/response_bytes': 98578, …
```

New spider: Freddy's Frozen Custard & Steakburgers (543 locations)

---

locations/spiders/mueller.py

```python
{'atp/brand/Müller': 947,
'atp/brand_wikidata/Q1958759': 947,
'atp/category/shop/chemist': 947,
'atp/country/AT': 109,
'atp/country/CH': 89,
'atp/country/DE': 581,
'atp/country/ES': 15,
'atp/country/HR': 92,
'atp/country/HU': 34,
'atp/country/LI': 1,
'atp/country/SI': 26,
'atp/field/country/from_reverse_geocoding': 947,
'atp/field/image/missing': 947,
'atp/field/operator/missing': 947,
'atp/field/operator_wikidata/missing': 947,
'atp/field/twitter/missing': 947,
'atp/field/website/missing': 947,
'atp/item_scraped_host_count/backend.prod.ecom.mueller.de': 947,
'atp/nsi/perfect_match': 947,
'downloader/request_bytes': 98242,
'downloader/request_count': 56,
'downloader/request_method_count/GET': 7, …
```

[Mueller] Fix spider

---

locations/spiders/infrastructure/seattle_city_light_poles_us.py

Add Seattle City Light poles (US) (111k poles)

---

ci/run_all_spiders.sh

Bump up the max tile size to try and resolve the individual tile size problem that's been failing the builds.
Also let the tippecanoe run fail in the weekly run.

Handle tippecanoe failure

---

locations/spiders/savers_ca_us.py

Also fixes savers_au non running spider

[Savers CA US AU] Fix extras to fix non running spiders

---

locations/spiders/change_group.py

Opening hours data is multiple format and different to when this code was written. Some of the data is confused in use of AM/PM for Noon. Other errors in data too e.g. open 5AM, close 2AM etc. Too brittle.

[ChangeGroup] Remove opening hours code to generate more POIs

---

locations/spiders/the_bargain_shop_ca.py

Rel: https://github.com/osmlab/name-suggestion-index/pull/10798
```python
{'atp/brand/Red Apple': 98,
'atp/brand/The Bargain! Shop': 43,
'atp/brand_wikidata/Q16953670': 43,
'atp/category/shop/variety_store': 141,
'atp/country/CA': 141,
'atp/field/brand_wikidata/missing': 98,
'atp/field/city/missing': 141,
'atp/field/country/from_spider_name': 141,
'atp/field/email/missing': 141,
'atp/field/image/missing': 141,
'atp/field/operator/missing': 141,
'atp/field/operator_wikidata/missing': 141,
'atp/field/postcode/missing': 141,
'atp/field/state/from_reverse_geocoding': 141,
'atp/field/twitter/missing': 141,
'atp/item_scraped_host_count/www.thebargainshop.com': 141,
'atp/nsi/perfect_match': 43, …
```

[The Bargain! Shop CA] Add spider

---

locations/storefinders/aheadworks.py

**_Fixes : updated aheadworks module to fix animates_nz spider_**
```python
{'atp/brand/Animates': 55,
'atp/brand_wikidata/Q110299350': 55,
'atp/category/shop/pet': 55,
'atp/clean_strings/city': 7,
'atp/clean_strings/postcode': 47,
'atp/clean_strings/street_address': 9,
'atp/country/NZ': 55,
'atp/field/branch/missing': 55,
'atp/item_scraped_host_count/www.animates.co.nz': 55,
'atp/nsi/cc_match': 55,
'downloader/request_bytes': 311,
'downloader/response_bytes': 992294, …
```

[Animates NZ] Fix Spider

---

locations/spiders/baskin_robbins_in.py
locations/storefinders/stockist.py

```python
{'atp/brand/Baskin-Robbins': 954,
'atp/brand_wikidata/Q584601': 954,
'atp/category/amenity/ice_cream': 954,
'atp/cdn/cloudflare/response_count': 24,
'atp/cdn/cloudflare/response_status_count/200': 23,
'atp/cdn/cloudflare/response_status_count/400': 1,
'atp/country/IN': 889,
'atp/country/NO': 65,
'atp/field/branch/missing': 954,
'atp/field/email/missing': 954,
'atp/field/image/missing': 954,
'atp/field/opening_hours/missing': 954,
'atp/field/operator/missing': 954,
'atp/field/operator_wikidata/missing': 954,
'atp/field/phone/missing': 954,
'atp/field/street_address/missing': 954,
'atp/field/twitter/missing': 954,
'atp/field/website/missing': 954,
'atp/item_scraped_host_count/stockist.co': 2000,
'atp/nsi/cc_match': 954, …
```

[Baskin Robbins IN] Fix  Spider

---

locations/spiders/pepco.py

Shop details are not longer all included in the store listing, but instead need to be paged from a backend service.

[pepco] Fix spider after website change

---

locations/spiders/infrastructure/kingston_city_council_waste_baskets_au.py

'atp/category/amenity/recycling': 186,
'atp/category/amenity/waste_basket': 804,

Add Kingston City Council waste baskets (AU) (990 bins)

---

locations/spiders/applebees.py

I'm sad this is required, and sad none of us will know to remove this when they eventually fix the data.

[Applebees] Fix website links

---

locations/spiders/infrastructure/bureau_of_meteorology_weather_stations_au.py

Includes many historical locations of weather stations which are useful ot extract because of historical weather data potentially being available for that location.

Add Bureau of Meteorology weather stations (AU and territories) (19k)

---

locations/spiders/go_outdoors_gb.py

Removing opening hours which have broken spider.

[Go Outdoors GB] Fix spider

---

locations/spiders/infrastructure/epcor_manholes_ca.py

Add EPCOR manholes (CA) (104k manholes)

---

locations/spiders/infrastructure/epcor_outfalls_ca.py

Add EPCOR outfalls (CA) (268 outfalls)

---

locations/spiders/cross_fit.py

[cross_fit] - address handling

---

locations/spiders/pko_bank_polski_pl.py

for example, this values: ul. Targowa 2/4
ul. Mostowa 7
Rynek 19
ul. 1-go Maja 6
ul. Główna 17b
ul. Duńska 38
ul. Brzezińska 23
Rynek 24
ul. Sportowa 3
ul. Kopernika 1A

[pko_bank_polski_pl] - this is addr:street_address rather than addr:full

---

locations/spiders/city_market_mx.py
locations/spiders/fresko_mx.py
locations/spiders/la_comer_mx.py
locations/spiders/sumesa_mx.py

* La Comer (the supermarket chain, not the parent holding company)
* City Market
* Fresko
* Sumesa
Note the different Wikidata items for the parent holding company for all these supermarket brands (Q26765126) versus the brand name of the "La Comer" supermarket chain (Q134237561) within this group of brands.

Add La Comer (MX) supermarket brands

---

locations/spiders/mitsubishi_pl.py

```python
{'atp/brand/Mitsubishi': 31,
'atp/brand_wikidata/Q36033': 31,
'atp/category/shop/car': 21,
'atp/category/shop/car_repair': 10,
'atp/clean_strings/postcode': 18,
'atp/clean_strings/state': 7,
'atp/clean_strings/street_address': 7,
'atp/country/PL': 31,
'atp/field/country/from_spider_name': 31,
'atp/field/opening_hours/missing': 31,
'atp/field/phone/missing': 31,
'atp/item_scraped_host_count/www.mitsubishi-motors.pl': 31,
'atp/nsi/cc_match': 31,
'downloader/request_bytes': 1692, …
```

[Mitsubishi PL] Fix Spider

---

locations/spiders/specsavers.py

```python
{'atp/brand/Specsavers': 2788,
'atp/brand_wikidata/Q2000610': 2788,
'atp/category/healthcare/audiologist': 1302,
'atp/category/healthcare/optometrist': 1486,
'atp/category/multiple': 2788,
'atp/country/AU': 713,
'atp/country/CA': 157,
'atp/country/GB': 1917,
'atp/country/JE': 1,
'atp/field/branch/missing': 2788,
'atp/field/image/missing': 2788,
'atp/field/opening_hours/missing': 2788,
'atp/field/operator/missing': 2788,
'atp/field/operator_wikidata/missing': 2788,
'atp/field/phone/missing': 60,
'atp/field/twitter/missing': 2788,
'atp/item_scraped_host_count/www.specsavers.ca': 157,
'atp/item_scraped_host_count/www.specsavers.co.uk': 1918, …
```

[Specsavers] Use custom settings with playwright to fix spider

---

locations/spiders/mochachos.py

Prevoiusly used `WpGoMapsSpider` no longer working, couldn't find any way to fix using the same, hence code refactored using `Sitemap`. Also couldn't find any data to distinguish other brands.
```python
{'atp/brand/Mochachos': 123,
'atp/brand_wikidata/Q116619117': 123,
'atp/category/amenity/fast_food': 123,
'atp/field/city/missing': 123,
'atp/field/country/missing': 123,
'atp/field/email/missing': 123,
'atp/field/image/missing': 123,
'atp/field/lat/missing': 123,
'atp/field/lon/missing': 123,
'atp/field/opening_hours/missing': 123,
'atp/field/operator/missing': 123,
'atp/field/operator_wikidata/missing': 123,
'atp/field/postcode/missing': 123,
'atp/field/state/missing': 123,
'atp/field/street_address/missing': 123, …
```

[Mochachos] Fix spider

---

locations/spiders/l_and_l_hawaiian_barbecue_us.py

Instead of just updating the location data URL in the spider, update the spider to fetch the main webpage and get the location data URL from there.

L&L Hawaiian Barbecue: Fix spider & make more robust

---

locations/spiders/volvo.py

```python
{'atp/brand/Volvo': 858,
'atp/brand_wikidata/Q215293': 858,
'atp/category/shop/car': 858,
'atp/clean_strings/email': 3,
'atp/country/BE': 62,
'atp/country/DE': 273,
'atp/country/ES': 93,
'atp/country/FR': 123,
'atp/country/GB': 107,
'atp/country/IT': 117,
'atp/country/NL': 83,
'atp/field/branch/missing': 858,
'atp/field/image/missing': 858,
'atp/field/opening_hours/missing': 487,
'atp/field/operator/missing': 858,
'atp/field/operator_wikidata/missing': 858,
'atp/field/postcode/missing': 751,
'atp/field/state/missing': 858,
'atp/field/street_address/missing': 858,
'atp/field/twitter/missing': 858,
'atp/field/website/invalid': 6,
'atp/field/website/missing': 13,
'atp/item_scraped_host_count/www.volvocars.com': 863, …
```

[Volvo] Fix spider

---

locations/spiders/subway_south_america.py

I lost stats from the full run, but there are ~4800 locations in total with most in Brazil and Mexico.
Partial run stats:
```json
{
"atp/brand/Subway": 67,
"atp/brand_wikidata/Q244457": 67,
"atp/category/amenity/fast_food": 67,
"atp/country/AG": 3,
"atp/country/AR": 46,
"atp/country/AW": 6,
"atp/country/BB": 1,
"atp/country/BO": 1,
"atp/country/BQ": 1,
"atp/country/BR": 1,
"atp/country/CL": 1,
"atp/country/CO": 1,
"atp/country/CW": 1,
"atp/country/EC": 1,
"atp/country/GD": 1,
"atp/country/GT": 1,
"atp/country/KY": 1,
"atp/country/SV": 1,
"atp/field/branch/missing": 67,
"atp/field/city/missing": 3,
"atp/field/email/missing": 67,
"atp/field/image/missing": 2,
"atp/field/opening_hours/missing": 7,
"atp/field/operator/missing": 67,
"atp/field/operator_wikidata/missing": 67, …
```

[subway_south_america] add spider (4.8k locations)

---

locations/spiders/euromaster_nl.py

**_Fixes : updated requested url to fix spider_**
```python
{'atp/brand/Euromaster': 103,
'atp/brand_wikidata/Q3060668': 103,
'atp/category/shop/car_repair': 103,
'atp/country/NL': 103,
'atp/field/branch/missing': 103,
'atp/field/country/from_spider_name': 103,
'atp/field/email/missing': 103,
'atp/field/image/missing': 103,
'atp/field/operator/missing': 103,
'atp/field/operator_wikidata/missing': 103,
'atp/field/state/missing': 103,
'atp/field/twitter/missing': 103,
'atp/item_scraped_host_count/www.euromaster.nl': 103,
'atp/nsi/perfect_match': 103,
'downloader/request_bytes': 98477,
'downloader/request_count': 206,
'downloader/request_method_count/GET': 206,
'downloader/response_bytes': 4534676,
'downloader/response_count': 206, …
```

[Euromaster NL] Fix Spider

---

locations/spiders/euromaster_fr.py

**_Fixes : updated request url to fix spider_**
```python
{'atp/brand/Euromaster': 386,
'atp/brand_wikidata/Q3060668': 386,
'atp/category/shop/car_repair': 386,
'atp/country/FR': 386,
'atp/field/branch/missing': 386,
'atp/field/country/from_spider_name': 386,
'atp/field/email/missing': 386,
'atp/field/image/missing': 386,
'atp/field/operator/missing': 386,
'atp/field/operator_wikidata/missing': 386,
'atp/field/state/missing': 386,
'atp/field/twitter/missing': 386,
'atp/item_scraped_host_count/www.euromaster.fr': 386,
'atp/nsi/perfect_match': 386,
'downloader/exception_count': 3,
'downloader/exception_type_count/twisted.internet.error.DNSLookupError': 3,
'downloader/request_bytes': 431902,
'downloader/request_count': 879, …
```

[Euromaster FR] Fix Spider

---

locations/spiders/abbotts_frozen_custard.py
locations/spiders/abbotts_frozen_custard_us.py

love it when a sitemap and structured data spider come together

add Abbott's Frozen Custard sitemap spider

---

locations/spiders/tom_wahls_us.py

add tom wahls

---

locations/spiders/blank_street_coffee.py

This pull request introduces a new spider for scraping location data from Blank Street Coffee's website. The spider leverages structured data and a sitemap-based approach to efficiently gather information.
* [`locations/spiders/blank_street_coffee.py`](diffhunk://#diff-a0ebf8a31ea20a7c8a36e8f8c41e846948a6b573d270191441fec5d62a83ef0aR1-R27): Added a new spider class `BlankStreetCoffeeSpider` that inherits from `SitemapSpider` and `StructuredDataSpider`. It scrapes location data from Blank Street Coffee's sitemap, processes structured data for cafes, and extracts additional details like reference IDs and branch names from the URLs and item names.

Add Blank Street Coffee spider

---

locations/spiders/decathlon_ma.py

```python
{'atp/brand/Decathlon': 18,
'atp/brand_wikidata/Q509349': 18,
'atp/category/shop/sports': 18,
'atp/cdn/cloudflare/response_count': 20,
'atp/cdn/cloudflare/response_status_count/200': 20,
'atp/country/MA': 18,
'atp/field/branch/missing': 18,
'atp/item_scraped_host_count/www.decathlon.ma': 18,
'atp/nsi/cc_match': 18,
'downloader/request_bytes': 24442,
'downloader/request_count': 21,
'downloader/request_method_count/GET': 21,
'downloader/response_bytes': 815173, …
```

[Decathlon MA] Fix spider

---

locations/spiders/pizza_hut_lu.py

Code Refactored using API to fix  the spider.
```python
{'atp/brand/Pizza Hut': 9,
'atp/brand_wikidata/Q191615': 9,
'atp/category/amenity/restaurant': 9,
'atp/country/LU': 9,
'atp/field/city/missing': 9,
'atp/field/country/from_spider_name': 9,
'atp/field/opening_hours/missing': 9,
'atp/field/street_address/missing': 9,
'atp/field/website/missing': 9,
'atp/item_scraped_host_count/takeout.pizzahut.lu': 9,
'atp/nsi/cc_match': 9,
'downloader/request_bytes': 697, …
```

[Pizza Hut LU]  Fix spider

---

locations/spiders/einstein_bros_us.py

```python
{'atp/brand/Einstein Bros. Bagels': 553,
'atp/brand_wikidata/Q5349788': 553,
'atp/category/amenity/fast_food': 553,
'atp/cdn/cloudflare/response_count': 556,
'atp/cdn/cloudflare/response_status_count/200': 556,
'atp/country/US': 553,
'atp/field/email/missing': 553,
'atp/field/operator/missing': 553,
'atp/field/operator_wikidata/missing': 553,
'atp/field/twitter/missing': 553,
'atp/item_scraped_host_count/locations.einsteinbros.com': 553,
'atp/nsi/perfect_match': 553,
'downloader/request_bytes': 237351,
'downloader/request_count': 557,
'downloader/request_method_count/GET': 557,
'downloader/response_bytes': 10366474,
'downloader/response_count': 557,
'downloader/response_status_count/200': 556, …
```

[Einstein Bros] Rename & fix spider

---

locations/spiders/baskin_robbins_in.py

Sometimes there addresses are off by 1 :(
```python
{'atp/brand/Baskin-Robbins': 954,
'atp/brand_wikidata/Q584601': 954,
'atp/category/amenity/ice_cream': 954,
'atp/cdn/cloudflare/response_count': 24,
'atp/cdn/cloudflare/response_status_count/200': 23,
'atp/cdn/cloudflare/response_status_count/400': 1,
'atp/country/IN': 954,
'atp/field/branch/missing': 954,
'atp/field/email/missing': 954,
'atp/field/image/missing': 954,
'atp/field/opening_hours/missing': 954,
'atp/field/operator/missing': 954,
'atp/field/operator_wikidata/missing': 954,
'atp/field/phone/missing': 954,
'atp/field/street_address/missing': 954,
'atp/field/twitter/missing': 954,
'atp/field/website/missing': 954,
'atp/item_scraped_host_count/stockist.co': 2000,
'atp/nsi/cc_match': 954, …
```

[Baskin-Robbins IN] Fix addresses

---

locations/spiders/essanelle_de.py

```python
{'atp/brand/essanelle': 101,
'atp/brand_wikidata/Q121888190': 101,
'atp/category/shop/hairdresser': 101,
'atp/country/DE': 101,
'atp/field/branch/missing': 101,
'atp/field/country/from_spider_name': 101,
'atp/field/email/missing': 101,
'atp/field/state/missing': 101,
'atp/item_scraped_host_count/essanelle-friseur.de': 101,
'atp/nsi/perfect_match': 101,
'downloader/request_bytes': 946, …
```

[Essanelle DE] Fix spider

---

locations/spiders/hss_hire_gb.py

**_Fixes : code refactored to use sitemap to fix spider_**
```python
{'atp/brand/HSS Hire': 141,
'atp/brand_wikidata/Q5636000': 141,
'atp/category/shop/tool_hire': 141,
'atp/country/GB': 141,
'atp/field/branch/missing': 141,
'atp/field/city/missing': 141,
'atp/field/country/from_spider_name': 141,
'atp/field/image/missing': 141,
'atp/field/operator/missing': 141,
'atp/field/operator_wikidata/missing': 141,
'atp/field/state/missing': 141,
'atp/field/street_address/missing': 141,
'atp/field/twitter/missing': 141,
'atp/item_scraped_host_count/www.hss.com': 141,
'atp/nsi/perfect_match': 141,
'downloader/request_bytes': 68804,
'downloader/request_count': 143,
'downloader/request_method_count/GET': 143, …
```

[HSS Hire GB] Fix Spider

---

locations/spiders/cosmo_de.py

```python
{'atp/brand/Cosmo': 61,
'atp/brand_wikidata/Q121888284': 61,
'atp/category/shop/hairdresser': 61,
'atp/country/DE': 61,
'atp/field/branch/missing': 61,
'atp/field/country/from_spider_name': 61,
'atp/field/email/missing': 61,
'atp/field/image/missing': 61,
'atp/field/operator/missing': 61,
'atp/field/operator_wikidata/missing': 61,
'atp/field/state/missing': 61,
'atp/field/twitter/missing': 61,
'atp/item_scraped_host_count/cosmohairshop.de': 61,
'atp/nsi/brand_missing': 61,
'downloader/request_bytes': 2754,
'downloader/response_bytes': 29845,
'downloader/response_count': 5, …
```

[Cosmo DE] Fix spider

---

locations/spiders/bleu_libellule_fr.py

```
{'atp/brand/Bleu Libellule': 234,
'atp/brand_wikidata/Q101830610': 234,
'atp/category/shop/hairdresser_supply': 234,
'atp/country/FR': 229,
'atp/country/GP': 2,
'atp/country/NC': 1,
'atp/country/RE': 2,
'atp/field/operator/missing': 234,
'atp/field/operator_wikidata/missing': 234,
'atp/field/state/missing': 234,
'atp/field/twitter/missing': 234,
'atp/item_scraped_host_count/magasins.bleulibellule.com': 234,
'atp/nsi/perfect_match': 234,
'downloader/request_bytes': 108168,
'downloader/request_count': 236,
'downloader/request_method_count/GET': 236,
'downloader/response_bytes': 7336752,
'downloader/response_count': 236,
'downloader/response_status_count/200': 236,
'elapsed_time_seconds': 3.882071, …
```

[Bleu Libellule FR] Fix spider

---

locations/spiders/kia_us.py

Category was missing before
```
{
"atp/brand/Kia": 797,
"atp/brand_wikidata/Q35349": 797,
"atp/category/shop/car": 797,
"atp/cdn/cloudflare/response_count": 243,
"atp/cdn/cloudflare/response_status_count/200": 243,
"atp/clean_strings/street_address": 796,
"atp/country/US": 797,
"atp/field/branch/missing": 797,
"atp/field/country/from_spider_name": 797,
"atp/field/email/missing": 797,
"atp/field/image/missing": 797,
"atp/field/opening_hours/missing": 797,
"atp/field/operator/missing": 797,
"atp/field/operator_wikidata/missing": 797,
"atp/field/phone/missing": 2,
"atp/field/twitter/missing": 797,
"atp/item_scraped_host_count/www.kia.com": 4840,
"atp/lineage": "S_?",
"atp/nsi/cc_match": 797,
"downloader/request_bytes": 109229,
"downloader/request_count": 243, …
```

[Kia US] Fix category + collect better website

---

locations/spiders/cosmo_de.py
locations/spiders/supercut_de.py

```python
{'atp/brand/Super Cut': 61,
'atp/brand_wikidata/Q64139077': 61,
'atp/category/shop/hairdresser': 61,
'atp/country/DE': 61,
'atp/field/branch/missing': 61,
'atp/field/country/from_spider_name': 61,
'atp/field/email/missing': 61,
'atp/field/image/missing': 61,
'atp/field/operator/missing': 61,
'atp/field/operator_wikidata/missing': 61,
'atp/field/state/missing': 61,
'atp/field/twitter/missing': 61,
'atp/item_scraped_host_count/supercut-friseur.de': 61,
'atp/nsi/perfect_match': 61,
'downloader/request_bytes': 949,
'downloader/response_bytes': 28558, …
```

[Supercut DE] Fix spider

---

locations/spiders/john_dorys_za.py

```python
{"atp/brand/John Dory's": 43,
'atp/brand_wikidata/Q130140080': 43,
'atp/category/amenity/restaurant': 43,
'atp/cdn/cloudflare/response_count': 47,
'atp/cdn/cloudflare/response_status_count/200': 47,
'atp/country/ZA': 43,
'atp/field/branch/missing': 43,
'atp/field/image/missing': 43,
'atp/field/opening_hours/missing': 43,
'atp/field/street_address/missing': 43,
'atp/field/twitter/missing': 43,
'atp/item_scraped_host_count/www.johndorys.com': 43,
'atp/nsi/perfect_match': 43,
'downloader/request_bytes': 19658,
'downloader/request_count': 47, …
```

[John Dorys ZA] Fix Spider

---

locations/spiders/farmers_home_furniture_us.py

```python
{'atp/brand/Farmers Home Furniture': 265,
'atp/brand_wikidata/Q121586393': 265,
'atp/category/shop/furniture': 265,
'atp/country/US': 265,
'atp/field/branch/missing': 265,
'atp/field/city/missing': 265,
'atp/field/email/missing': 265,
'atp/field/image/missing': 265,
'atp/field/opening_hours/missing': 265,
'atp/field/operator/missing': 265,
'atp/field/operator_wikidata/missing': 265,
'atp/field/postcode/missing': 265,
'atp/field/state/from_reverse_geocoding': 265,
'atp/field/street_address/missing': 265,
'atp/field/twitter/missing': 265,
'atp/item_scraped_host_count/www.farmershomefurniture.com': 265,
'atp/nsi/perfect_match': 265,
'downloader/request_bytes': 101592,
'downloader/request_count': 267,
'downloader/request_method_count/GET': 267, …
```

[Farmers Home Furniture] Rename and fix spider

---

locations/spiders/infrastructure/los_angeles_county_department_of_public_works_sewer_pump_stations_us.py

Add Los Angeles County Department of Public Works sewer pump stations

---

locations/spiders/erie_insurance_us.py

```python
{'atp/brand/Erie Insurance': 3166,
'atp/brand_wikidata/Q5388314': 3166,
'atp/category/office/insurance': 3166,
'atp/country/US': 3166,
'atp/field/branch/missing': 3166,
'atp/field/country/from_spider_name': 3166,
'atp/field/image/missing': 3166,
'atp/field/opening_hours/missing': 51,
'atp/field/operator/missing': 3166,
'atp/field/operator_wikidata/missing': 3166,
'atp/field/phone/missing': 3166,
'atp/item_scraped_host_count/www.erieinsurance.com': 3166,
'atp/nsi/perfect_match': 3166,
'downloader/request_bytes': 1290381,
'downloader/request_count': 1827,
'downloader/request_method_count/GET': 1827, …
```

[Erie Insurance US] Fix Spider

---

locations/spiders/outdoor_supply_hardware_us.py

```python
{'atp/brand/Outdoor Supply Hardware': 13,
'atp/brand_wikidata/Q119104427': 13,
'atp/category/shop/hardware': 13,
'atp/country/US': 13,
'atp/field/website/missing': 13,
'atp/item_scraped_host_count/www.outdoorsupplyhardware.com': 13,
'atp/nsi/perfect_match': 13,
'downloader/request_bytes': 302,
'downloader/response_bytes': 56009,
'elapsed_time_seconds': 2.854704, …
```

[Outdoor Supply Hardware US] Fix spider

---

locations/spiders/sams_club.py

```python
{"atp/brand/Sam's Club": 1128,
'atp/brand_wikidata/Q1972120': 1128,
'atp/category/amenity/fuel': 529,
'atp/category/shop/wholesale': 599,
'atp/country/US': 1128,
'atp/field/branch/missing': 1128,
'atp/field/email/missing': 1128,
'atp/field/image/missing': 1128,
'atp/field/operator/missing': 1128,
'atp/field/operator_wikidata/missing': 1128,
'atp/field/twitter/missing': 1128,
'atp/item_scraped_host_count/www.samsclub.com': 1128,
'atp/nsi/cc_match': 1128,
'downloader/request_bytes': 2104319,
'downloader/request_count': 638,
'downloader/request_method_count/GET': 638,
'downloader/response_bytes': 65503583,
'downloader/response_count': 638,
'downloader/response_status_count/200': 605,
'downloader/response_status_count/301': 33, …
```

[Sam's Club US] Collect fuel stations

---

locations/spiders/infrastructure/national_parks_board_trees_sg.py

national_parks_board_trees_sg: fix height range extraction

---

locations/spiders/kasikorn_bank_th.py

**_Fixes : added start_request to fix spider_**
```python
{'atp/brand/ธนาคารกสิกรไทย': 10735,
'atp/brand_wikidata/Q276557': 10735,
'atp/category/amenity/atm': 9968,
'atp/category/amenity/bank': 767,
'atp/cdn/akamai/response_count': 1,
'atp/cdn/akamai/response_status_count/403': 1,
'atp/clean_strings/branch': 4139,
'atp/country/TH': 10735,
'atp/field/city/missing': 10735,
'atp/field/country/from_spider_name': 10735,
'atp/field/email/missing': 10735,
'atp/field/image/missing': 10735,
'atp/field/name/missing': 9968,
'atp/field/opening_hours/missing': 10735,
'atp/field/operator/missing': 767,
'atp/field/operator_wikidata/missing': 767,
'atp/field/phone/missing': 9969,
'atp/field/postcode/missing': 10735,
'atp/field/state/missing': 10735, …
```

[Kasikorn Bank TH] Fix Spider

---

locations/spiders/svetofor_ru.py

[Svetofor RU] Try using proxy to fix  spider

---

locations/spiders/hudsons_bay_ca.py

No coords, but good addresses.

[Hudson's Bay CA] Add spider

---

locations/spiders/pizza_hut_ae_sa.py

```python
{'atp/brand/Pizza Hut': 258,
'atp/brand_wikidata/Q191615': 258,
'atp/category/amenity/restaurant': 258,
'atp/clean_strings/addr_full': 9,
'atp/country/AE': 161,
'atp/country/SA': 97,
'atp/field/branch/missing': 258,
'atp/field/city/missing': 258,
'atp/field/email/missing': 258,
'atp/field/image/missing': 258,
'atp/field/opening_hours/missing': 258,
'atp/field/operator/missing': 258,
'atp/field/operator_wikidata/missing': 258,
'atp/field/phone/missing': 137,
'atp/field/postcode/missing': 258,
'atp/field/state/missing': 258,
'atp/field/street_address/missing': 258,
'atp/field/twitter/missing': 258,
'atp/item_scraped_host_count/saudi.pizzahut.me': 97, …
```

[Pizza Hut AE SA] Fix spider

---

locations/spiders/pizza_hut_vn.py

The spider had problem with auth token before
```
{
"atp/brand/Pizza Hut": 118,
"atp/brand_wikidata/Q191615": 118,
"atp/category/amenity/restaurant": 118,
"atp/clean_strings/addr_full": 8,
"atp/clean_strings/branch": 2,
"atp/clean_strings/lat": 1,
"atp/clean_strings/lon": 117,
"atp/country/VN": 118,
"atp/field/city/missing": 118,
"atp/field/country/from_spider_name": 118,
"atp/field/email/missing": 118,
"atp/field/image/missing": 118,
"atp/field/operator/missing": 118,
"atp/field/operator_wikidata/missing": 118,
"atp/field/phone/missing": 118,
"atp/field/postcode/missing": 118,
"atp/field/state/missing": 118,
"atp/field/street_address/missing": 118,
"atp/field/twitter/missing": 118,
"atp/field/website/missing": 118,
"atp/item_scraped_host_count/rwapi.pizzahut.vn": 118,
"atp/lineage": …
```

[pizza_hut_vn] fixing spider

---

locations/spiders/fraser_hart_gb.py

This uses elfsight but isn't configured quite right to use the storefinder.

[Fraser Hart GB] Add spider

---

locations/spiders/xian_famous_foods.py

```python
{"atp/brand/Xi'an Famous Foods": 18,
'atp/brand_wikidata/Q8044020': 18,
'atp/category/amenity/restaurant': 18,
'atp/country/US': 18,
'atp/field/branch/missing': 18,
'atp/field/phone/missing': 18,
'atp/item_scraped_host_count/www.xianfoods.com': 18,
'atp/nsi/perfect_match': 18,
'downloader/request_bytes': 762,
'downloader/response_bytes': 9409, …
```

[Xian Famous Foods] Fix spider

---

locations/spiders/toyota_us.py

- Used API from Toyota official website
- Increased number of POIs
- Decreased execution time
```
{
"atp/brand/Toyota": 1242,
"atp/brand_wikidata/Q53268": 1242,
"atp/category/shop/car": 1242,
"atp/country/US": 1242,
"atp/duplicate_count": 611,
"atp/field/branch/missing": 1242,
"atp/field/country/from_spider_name": 1242,
"atp/field/email/missing": 1242,
"atp/field/image/missing": 1242,
"atp/field/opening_hours/missing": 1242,
"atp/field/operator/missing": 1242,
"atp/field/operator_wikidata/missing": 1242,
"atp/field/state/from_reverse_geocoding": 1242,
"atp/field/twitter/missing": 1242,
"atp/field/website/invalid": 1,
"atp/item_scraped_host_count/api.ws.dpcmaps.toyota.com": 1853,
"atp/lineage": "S_?",
"atp/nsi/cc_match": 1242,
"downloader/request_bytes": 2869,
"downloader/request_count": …
```

[toyota_us] Improving toyota_us spider (1242 locations)

---

locations/spiders/cake_box_gb.py

fixes https://github.com/alltheplaces/alltheplaces/issues/13408

[Cake Box GB] Add branch

---

locations/spiders/ecars.py
tests/test_item_attributes.py

Unfortunately tests will still fail until an NSI release with https://github.com/osmlab/name-suggestion-index/pull/11051

[Ecars] Update brand

---

locations/spiders/chemist_warehouse_au.py

```python
{'atp/brand/Chemist Warehouse': 525,
'atp/brand_wikidata/Q48782120': 525,
'atp/category/amenity/pharmacy': 525,
'atp/category/multiple': 525,
'atp/cdn/cloudflare/response_count': 358,
'atp/cdn/cloudflare/response_status_count/200': 357,
'atp/country/AU': 525,
'atp/duplicate_count': 16242,
'atp/field/image/missing': 525,
'atp/field/operator/missing': 525,
'atp/field/operator_wikidata/missing': 525,
'atp/field/twitter/missing': 525,
'atp/field/website/missing': 525,
'atp/item_scraped_host_count/api.chemistwarehouse.com.au': 16767,
'atp/nsi/perfect_match': 525,
'downloader/request_bytes': 186739,
'downloader/request_count': 358, …
```

[Chemist Warehouse AU] Fix spider

---

locations/spiders/dollar_general.py

Summary generated for limited POIs.
```python
{'atp/brand/Dollar General': 66,
'atp/brand_wikidata/Q145168': 66,
'atp/category/shop/variety_store': 66,
'atp/country/US': 66,
'atp/field/branch/missing': 66,
'atp/field/email/missing': 66,
'atp/field/image/missing': 66,
'atp/field/operator/missing': 66,
'atp/field/operator_wikidata/missing': 66,
'atp/field/twitter/missing': 66,
'atp/item_scraped_host_count/www.dollargeneral.com': 66,
'atp/nsi/match_failed': 66,
'downloader/request_bytes': 36034,
'downloader/request_count': 68,
'downloader/request_method_count/GET': 68,
'downloader/response_bytes': 1945135,
'downloader/response_count': 68,
'downloader/response_status_count/401': 66,
'elapsed_time_seconds': 84.619479, …
```

[Dollar General] Fix spider

---

locations/spiders/ministop_jp.py

'atp/brand/MINISOF': 7,
'atp/brand/Ministop': 1761,
'atp/brand/cisca': 3,
'atp/brand_wikidata/Q1038929': 1761,
'atp/brand_wikidata/Q134958024': 7,
'atp/brand_wikidata/Q134958099': 3,

[Ministop JP] Add spider (and MINISOF and cisca sub-brands)

---

tests/test_item_attributes.py

Rel: #13431
To be merged after NSI releases

[TEST] Remove ecars exclusion

---

locations/spiders/central_food_retail_th.py

'atp/brand/Tops': 43,
'atp/brand/Tops Fine Food': 2,
'atp/brand/Tops Food Hall': 20,
'atp/brand/Tops Market': 113,
'atp/brand/Tops Wine Cellar': 6,
'atp/brand_wikidata/Q134932513': 20,
'atp/brand_wikidata/Q134932553': 113,
'atp/brand_wikidata/Q134932619': 2,
'atp/brand_wikidata/Q134932632': 6,
'atp/brand_wikidata/Q7825140': 43,
'atp/category/shop/supermarket': 178,
'atp/category/shop/wine': 6,

[Central Food Retail TH] Add spider (multiple brands)

---

locations/spiders/aeon_big_my.py

No `coordinates` available.
```python
{'atp/brand/AEON BiG': 21,
'atp/brand_wikidata/Q8077280': 21,
'atp/category/shop/supermarket': 21,
'atp/country/MY': 21,
'atp/field/city/missing': 21,
'atp/field/country/from_spider_name': 21,
'atp/field/lat/missing': 21,
'atp/field/lon/missing': 21,
'atp/item_scraped_host_count/aeonbig.com.my': 21,
'atp/nsi/perfect_match': 21,
'downloader/request_bytes': 746,
'downloader/response_bytes': 18517, …
```

[Aeon Big MY] Fix spider

---

locations/spiders/hygieia_pl.py

Coordinates not available. Only a Google Places ID.
Fixes #5909

[Hygieia PL] Add spider

---

locations/spiders/hruska_cz.py

No coordinates available. References not always available.
Fixes #13499

[Hruška CZ] Add spider

---

locations/spiders/bertuccis.py
locations/spiders/bertuccis_us.py

```python
{"atp/brand/Bertucci's": 15,
'atp/brand_wikidata/Q4895917': 15,
'atp/category/amenity/restaurant': 15,
'atp/clean_strings/addr_full': 15,
'atp/country/US': 15,
'atp/item_scraped_host_count/www.bertuccis.com': 15,
'atp/nsi/perfect_match': 15,
'downloader/response_bytes': 49172, …
```

[Bertuccis] Fix Spider

---

locations/spiders/brnenka_cz.py

[Brněnka CZ] Add spider

---

locations/spiders/little_john_bikes_de.py

No coordinates provided.
Fixes #7080

[Little John Bikes DE] Add spider

---

locations/spiders/blinds_to_go.py

**_Fixes : code refactored to use sitemap spider_**
```python
{'atp/brand/Blinds to Go': 91,
'atp/brand_wikidata/Q123409913': 91,
'atp/category/shop/window_blind': 91,
'atp/cdn/cloudflare/response_count': 94,
'atp/cdn/cloudflare/response_status_count/200': 94,
'atp/clean_strings/phone': 89,
'atp/country/CA': 43,
'atp/country/US': 46,
'atp/field/branch/missing': 2,
'atp/field/city/missing': 91,
'atp/field/country/from_reverse_geocoding': 89,
'atp/field/country/missing': 2,
'atp/field/email/missing': 91,
'atp/field/image/missing': 91,
'atp/field/opening_hours/missing': 91,
'atp/field/operator/missing': 91,
'atp/field/operator_wikidata/missing': 91,
'atp/field/postcode/missing': 91, …
```

[Blinds To Go] Fix Spider

---

locations/spiders/brandywine_living.py

```python
{'atp/category/missing': 28,
'atp/country/US': 28,
'atp/field/brand/missing': 28,
'atp/field/brand_wikidata/missing': 28,
'atp/field/name/missing': 28,
'atp/field/state/from_reverse_geocoding': 28,
'atp/item_scraped_host_count/www.brandycare.com': 28,
'downloader/request_bytes': 2273,
'downloader/response_bytes': 70149, …
```

[Brandywine Living] Fix Spider

---

locations/categories.py

Reference: https://wiki.openstreetmap.org/wiki/Proposal:Utility_facilities

categories: remove deprecated street_cabinet=power tag

---

locations/spiders/sigma_it.py

[Sigma IT] Rewrite to improve tagging robustness

---

locations/spiders/easy_bathrooms_gb.py

[Easy Bathrooms GB] Collect coords

---

locations/spiders/market_liquors_na_za.py

Coordinates not available. No references available.
Fixes #7018

[Market Liquors NA ZA] Add spider

---

locations/spiders/general_logistics_systems_de.py

```python
{'atp/category/amenity/parcel_locker': 173,
'atp/category/amenity/yes': 3980,
'atp/cdn/cloudflare/response_count': 277,
'atp/cdn/cloudflare/response_status_count/200': 276,
'atp/clean_strings/city': 6,
'atp/clean_strings/housenumber': 1,
'atp/clean_strings/name': 30,
'atp/clean_strings/postcode': 2,
'atp/clean_strings/street': 64,
'atp/country/DE': 4153,
'atp/duplicate_count': 937,
'atp/field/branch/missing': 4153,
'atp/field/brand/missing': 4153,
'atp/field/brand_wikidata/missing': 4153,
'atp/field/email/missing': 4153,
'atp/field/image/missing': 4153,
'atp/field/operator/missing': 4153,
'atp/field/operator_wikidata/missing': 4153,
'atp/field/phone/missing': 4153,
'atp/field/state/missing': 4153, …
```

[GLS DE] Modernise spider

---

locations/country_utils.py
tests/test_country_utils.py

Rel to: https://github.com/alltheplaces/alltheplaces/pull/13557/commits/fee232ad932aac45f4da2e8aeac112a26c9c9a7a
Made  function to find country codes only in the end of the spider name, not in the middle or beginning. Diff below illustrates the issue:
| spider name | old function output | new function output |
|------------|--------------|--------------|
| 47_street_ar | 'None' | 'AR' |
| 99_bikes_au | 'None' | 'AU' |
| 99_ranch_market_us | 'None' | 'US' |
| ag_warehouse_au | 'None' | 'AU' |
| alabama_department_of_transportation_us | 'None' | 'US' |
| alaska_department_of_transportation_and_public_facilities_us | 'None' | 'US' |
| alberta_ministry_of_transportation_ca | 'None' | 'CA' |
| an_post_ie | 'None' | 'IE' |
| arizona_department_of_transportation_us | 'None' | 'US' |
| …

[core] fine tune country code from spider name function

---

locations/spiders/toyota_africa.py

Also improved locations parsing
```
{
"atp/brand/Toyota": 107,
"atp/brand_wikidata/Q53268": 107,
"atp/category/missing": 1,
"atp/category/shop/car": 65,
"atp/category/shop/car_parts": 3,
"atp/category/shop/car_repair": 38,
"atp/cdn/cloudflare/response_count": 111,
"atp/cdn/cloudflare/response_status_count/200": 110,
"atp/cdn/cloudflare/response_status_count/404": 1,
"atp/country/BF": 2,
"atp/country/BJ": 2,
"atp/country/CD": 7,
"atp/country/CF": 1,
"atp/country/CM": 5,
"atp/country/GM": 1,
"atp/country/GN": 1,
"atp/country/GQ": 2,
"atp/country/GW": 1,
"atp/country/KE": 25,
"atp/country/LR": 1,
"atp/country/MG": 3,
"atp/country/ML": 1,
"atp/country/MR": 3,
"atp/country/MZ": 15,
"atp/country/NE": 1,
"atp/country/NG": 6,
"atp/country/RW": 2,
"atp/country/SL": 1,
"atp/country/SN": 4, …
```

Adding categories for toyota_africa spider 

---

locations/spiders/cornerstone_healthcare_group_us.py

```python
{'atp/brand/Cornerstone Healthcare Group': 9,
'atp/category/amenity/hospital': 9,
'atp/category/multiple': 9,
'atp/country/US': 9,
'atp/field/brand_wikidata/missing': 9,
'atp/field/city/missing': 9,
'atp/field/country/from_spider_name': 9,
'atp/field/opening_hours/missing': 9,
'atp/field/state/from_reverse_geocoding': 9,
'atp/field/street_address/missing': 9,
'atp/item_scraped_host_count/www.cornerstonehospitals.com': 9,
'downloader/request_bytes': 5168, …
```

[Cornerstone Healthcare Group US ] Fix Spider

---

locations/spiders/dominos_pizza_be.py

**_Fixes : updated sitemap_rules and parse method to fix spider_**
```python
{"atp/brand/Domino's": 118,
'atp/brand_wikidata/Q839466': 118,
'atp/category/amenity/fast_food': 118,
'atp/clean_strings/street_address': 118,
'atp/country/BE': 118,
'atp/field/branch/missing': 118,
'atp/field/city/missing': 118,
'atp/field/country/from_spider_name': 118,
'atp/field/email/missing': 118,
'atp/field/opening_hours/missing': 118,
'atp/field/operator/missing': 118,
'atp/field/operator_wikidata/missing': 118,
'atp/field/phone/missing': 118,
'atp/field/postcode/missing': 118,
'atp/field/state/missing': 118,
'atp/item_scraped_host_count/www.dominos.be': 118,
'atp/nsi/cc_match': 118,
'downloader/request_bytes': 111389, …
```

[Dominos Pizza BE] Fix Spider

---

locations/spiders/pizza_hut_fi.py

```python
{'atp/brand/Pizza Hut': 21,
'atp/brand_wikidata/Q191615': 21,
'atp/category/amenity/restaurant': 21,
'atp/country/FI': 21,
'atp/field/city/missing': 21,
'atp/field/country/from_spider_name': 21,
'atp/field/opening_hours/missing': 21,
'atp/field/state/missing': 21,
'atp/item_scraped_host_count/www.pizzahut.fi': 21,
'atp/nsi/cc_match': 21,
'downloader/request_bytes': 8889,
'downloader/request_count': 23,
'downloader/request_method_count/GET': 23,
'downloader/response_bytes': 221601,
'downloader/response_count': 23, …
```

[Pizza Hut Fi ] Fix Spider

---

locations/spiders/united_petroleum_au.py

Was generating 2 POIs, now more.

[UnitedPetroleum AU] Fix extras

---

locations/spiders/save_a_lot_us.py

**_Fixes : code updated to use sitemap to fix spider_**
```python
{'atp/brand/Save-A-Lot': 703,
'atp/brand_wikidata/Q7427972': 703,
'atp/category/shop/supermarket': 703,
'atp/clean_strings/branch': 2,
'atp/country/US': 703,
'atp/field/email/missing': 703,
'atp/field/operator/missing': 703,
'atp/field/operator_wikidata/missing': 703,
'atp/field/phone/missing': 703,
'atp/field/twitter/missing': 703,
'atp/item_scraped_host_count/savealot.com': 703,
'atp/nsi/perfect_match': 703,
'downloader/request_bytes': 1672948,
'downloader/request_count': 713,
'downloader/request_method_count/GET': 713,
'downloader/response_bytes': 41555726,
'downloader/response_count': 713,
'downloader/response_status_count/200': 708, …
```

[Save A Lot US] Fix Spider

---

locations/storefinders/socrata.py

It appears at least for a few Socrata instances or datasets, such as https://data.edmonton.ca/api/views/6waz-yxqq.json, that an older "date of last data modification" field may have been replaced with a "view last modified" field. Try both and then fail gracefully, instead of always assuming metadata fields are present and receiving a key error.

storefinders/socrata: use new (?) data last modification date field

---

locations/spiders/continente_pt.py

[Continente PT] Drop MAXMAT locations

---

ci/run_all_spiders.sh

Add a bit of insurance that the pmtiles will finish for #13488

Double max tile size for global pmtiles build

---

locations/spiders/oazis_hu.py

Rel: https://github.com/osmlab/name-suggestion-index/issues/11143

[OÁZIS HU] Add spider

---

locations/spiders/bps_pl.py

```python
{'atp/brand/Bank Polskiej Spółdzielczości': 2315,
'atp/brand_wikidata/Q9165001': 2315,
'atp/category/amenity/atm': 2303,
'atp/category/amenity/bank': 12,
'atp/clean_strings/street': 1,
'atp/country/PL': 2315,
'atp/field/country/from_spider_name': 2315,
'atp/field/email/missing': 2315,
'atp/field/image/missing': 2315,
'atp/field/opening_hours/missing': 2315,
'atp/field/phone/missing': 2303,
'atp/field/street_address/missing': 2315,
'atp/field/twitter/missing': 2315,
'atp/field/website/missing': 2303,
'atp/item_scraped_host_count/www.bankbps.pl': 2315, …
```

[BPS PL] Add Spider (12 branches, 2k ATMs)

---

locations/storefinders/yext_answers.py

```python
{"atp/brand/Domino's": 7132,
'atp/brand_wikidata/Q839466': 7132,
'atp/category/amenity/fast_food': 7132,
'atp/cdn/cloudflare/response_count': 144,
'atp/cdn/cloudflare/response_status_count/200': 143,
'atp/closed_check': 42,
'atp/country/US': 7132,
'atp/field/branch/missing': 8,
'atp/field/email/missing': 7132,
'atp/field/image/missing': 7132,
'atp/field/opening_hours/missing': 47,
'atp/field/operator/missing': 7132,
'atp/field/operator_wikidata/missing': 7132,
'atp/field/twitter/missing': 7132,
'atp/item_scraped_host_count/prod-cdn.us.yextapis.com': 7132,
'atp/nsi/cc_match': 7132,
'downloader/exception_type_count/twisted.internet.error.TimeoutErr …
```

[Dominos Pizza US]  Fix spider

---

locations/spiders/elysium_healthcare.py

It's an operator now: https://nsi.guide/index.html?t=operators&k=amenity&v=hospital&tt=q39086513

[elysium_healthcare] switch to operator, sync with NSI

---

locations/spiders/toyota_sacu.py

I also split POIs into repair and shop category
```
{
"atp/brand/Hino Motors": 141,
"atp/brand/Lexus": 26,
"atp/brand/Toyota": 398,
"atp/brand_wikidata/Q35919": 26,
"atp/brand_wikidata/Q53268": 398,
"atp/brand_wikidata/Q867667": 141,
"atp/category/shop/car": 204,
"atp/category/shop/car_repair": 220,
"atp/category/shop/truck": 70,
"atp/category/shop/truck_repair": 71,
"atp/clean_strings/street_address": 202,
"atp/country/BW": 24,
"atp/country/LS": 3,
"atp/country/NA": 34,
"atp/country/SZ": 8,
"atp/country/ZA": 496,
"atp/field/branch/missing": 565,
"atp/field/email/missing": 4,
"atp/field/image/missing": 565,
"atp/field/lat/missing": 4,
"atp/field/lon/missing": 4,
"atp/field/opening_hours/missing": 565,
"atp/field/operator/missing": 565,
"atp/field/operator_wikidata/missing": 565, …
```

Fix branding for toyota_sacu spider

---

locations/spiders/dominos_pizza_nl.py

```python
{"atp/brand/Domino's": 377,
'atp/brand_wikidata/Q839466': 377,
'atp/category/amenity/fast_food': 377,
'atp/country/NL': 377,
'atp/duplicate_count': 1632,
'atp/field/city/missing': 377,
'atp/field/email/missing': 377,
'atp/field/image/missing': 377,
'atp/field/opening_hours/missing': 377,
'atp/field/operator/missing': 377,
'atp/field/operator_wikidata/missing': 377,
'atp/field/phone/missing': 377,
'atp/field/state/missing': 377,
'atp/field/twitter/missing': 377,
'atp/item_scraped_host_count/www.dominos.nl': 2009,
'atp/nsi/cc_match': 377,
'downloader/request_bytes': 133459,
'downloader/request_count': 202,
'downloader/request_method_count/GET': 202,
'downloader/response_bytes': 520448, …
```

[Dominos Pizza NL] Fix Spider

---

locations/spiders/greystar.py

The API is now blocked in robots.txt, and it's probably more polite to use the sitemap than to override robots.txt.

[Greystar] Rewrite to SitemapSpider+StructuredDataSpider to fix spider

---

locations/spiders/toyota_ca.py

```
{
"atp/brand/Lexus": 80,
"atp/brand/Toyota": 494,
"atp/brand_wikidata/Q35919": 80,
"atp/brand_wikidata/Q53268": 494,
"atp/category/shop/car": 287,
"atp/category/shop/car_repair": 287,
"atp/cdn/cloudflare/response_count": 3,
"atp/cdn/cloudflare/response_status_count/200": 3,
"atp/clean_strings/name": 4,
"atp/country/CA": 574,
"atp/field/branch/missing": 574,
"atp/field/country/from_spider_name": 574,
"atp/field/email/missing": 6,
"atp/field/image/missing": 574,
"atp/field/opening_hours/missing": 574,
"atp/field/operator/missing": 574,
"atp/field/operator_wikidata/missing": 574,
"atp/field/twitter/missing": 574,
"atp/field/website/invalid": 4,
"atp/item_scraped_host_count/www.toyota.ca": 574,
"atp/lineage": "S_?",
"atp/nsi/cc_match": 574,
"downloader/request_bytes": 1834, …
```

[Toyota CA] Add Lexus

---

locations/spiders/econofitness_ca.py

```python
{'atp/brand/Éconofitness': 76,
'atp/brand_wikidata/Q123073582': 76,
'atp/category/leisure/fitness_centre': 76,
'atp/country/CA': 76,
'atp/field/city/missing': 76,
'atp/field/country/from_spider_name': 76,
'atp/field/image/missing': 76,
'atp/field/opening_hours/missing': 76,
'atp/field/operator/missing': 76,
'atp/field/operator_wikidata/missing': 76,
'atp/field/phone/missing': 76,
'atp/field/postcode/missing': 76,
'atp/field/state/from_reverse_geocoding': 76,
'atp/field/street_address/missing': 76,
'atp/field/twitter/missing': 76,
'atp/item_scraped_host_count/econofitness.ca': 76,
'atp/nsi/perfect_match': 76,
'downloader/request_bytes': 712, …
```

[Econofitness CA] Fix Spider

---

locations/spiders/commerzbank_de.py

**_Added atm availability status _** 
```python
{'atp/brand/Commerzbank': 527,
'atp/brand_wikidata/Q157617': 527,
'atp/category/amenity/bank': 527,
'atp/country/DE': 527,
'atp/field/branch/missing': 527,
'atp/field/email/missing': 527,
'atp/field/opening_hours/missing': 124,
'atp/field/operator/missing': 527,
'atp/field/operator_wikidata/missing': 527,
'atp/field/phone/missing': 124,
'atp/field/postcode/missing': 124,
'atp/field/state/missing': 527,
'atp/item_scraped_host_count/filialsuche.commerzbank.de': 527,
'atp/nsi/cc_match': 527,
'downloader/request_bytes': 247598,
'downloader/request_count': 529,
'downloader/request_method_count/GET': 529,
'downloader/response_bytes': 3667914,
'downloader/response_count': 529,
'downloader/response_status_count/200': 529, …
```

[Commerz Bank DE] Added ATM details

---

locations/spiders/mazda_my.py

[Mazda MY] Add spider

---

locations/spiders/mazda_ua.py

[Mazda UA] Add spider

---

locations/spiders/foodworks_au.py

```python
{'atp/brand/Foodworks': 326,
'atp/brand_wikidata/Q5465579': 326,
'atp/category/shop/supermarket': 326,
'atp/clean_strings/branch': 7,
'atp/clean_strings/street_address': 326,
'atp/country/AU': 326,
'atp/field/city/missing': 326,
'atp/field/country/from_spider_name': 326,
'atp/field/email/missing': 326,
'atp/field/image/missing': 326,
'atp/field/lat/missing': 326,
'atp/field/lon/missing': 326,
'atp/field/opening_hours/missing': 326,
'atp/field/operator/missing': 326,
'atp/field/operator_wikidata/missing': 326,
'atp/field/postcode/missing': 326,
'atp/field/state/missing': 326,
'atp/field/twitter/missing': 326,
'atp/field/website/missing': …
```

[Foodworks AU] Fix Spider

---

locations/spiders/dropa_ch.py

Rel: https://github.com/osmlab/name-suggestion-index/issues/11211

[Dropa CH] Add spider

---

locations/spiders/super_hotel_jp.py

Since hotel name is already covered in 'brand' it seems better to just change the specific location name to 'branch' instead.

super_hotel_jp: change 'name' to 'branch'

---

locations/spiders/card_factory_gb.py

Fix name, branch, opening hours and street address.

[Card Factory GB] Add details

---

locations/spiders/toyota_ar.py
locations/spiders/toyota_br.py
locations/spiders/toyota_ve.py

```
{
"atp/brand/Toyota": 600,
"atp/brand_wikidata/Q53268": 600,
"atp/category/shop/car": 301,
"atp/category/shop/car_repair": 299,
"atp/clean_strings/phone": 4,
"atp/clean_strings/postcode": 6,
"atp/clean_strings/street": 4,
"atp/country/BR": 600,
"atp/field/branch/missing": 600,
"atp/field/country/from_spider_name": 600,
"atp/field/email/missing": 4,
"atp/field/image/missing": 600,
"atp/field/opening_hours/missing": 11,
"atp/field/operator/missing": 600,
"atp/field/operator_wikidata/missing": 600,
"atp/field/phone/invalid": 6,
"atp/field/phone/missing": 10,
"atp/field/street_address/missing": 600,
"atp/field/twitter/missing": 600,
"atp/field/website/missing": 2,
"atp/item_scraped_host_count/www.toyota.com.br": 600,
"atp/lineage": "S_?",
"atp/nsi/cc_match": 600, …
```

Adding Toyota spiders for Argentina and Venezuela (refactoring toyota_br) 

---

locations/spiders/mcdonalds_pt.py

**_Fixes : Flag robotstxt as False to fix spider_**
```python
{'atp/brand/McCafé': 104,
"atp/brand/McDonald's": 214,
'atp/brand_wikidata/Q3114287': 104,
'atp/brand_wikidata/Q38076': 214,
'atp/category/amenity/cafe': 104,
'atp/category/amenity/fast_food': 214,
'atp/clean_strings/branch': 3,
'atp/clean_strings/city': 82,
'atp/clean_strings/state': 54,
'atp/clean_strings/street_address': 183,
'atp/country/PT': 318,
'atp/field/email/missing': 318,
'atp/field/image/dropped': 318,
'atp/field/image/missing': 318,
'atp/field/operator/missing': 318,
'atp/field/operator_wikidata/missing': 318,
'atp/field/phone/missing': 318, …
```

[Mcdonalds PT] Fix Spider

---

locations/spiders/matsukiyo_jp.py

[Matsukiyo JP] add spider

---

locations/spiders/safeway_ca.py

_**Fixes : code refactored to fix spider**_
```python
{'atp/brand/Safeway': 138,
'atp/brand_wikidata/Q17111901': 138,
'atp/category/shop/supermarket': 138,
'atp/country/CA': 138,
'atp/field/branch/missing': 138,
'atp/field/image/missing': 138,
'atp/item_scraped_host_count/www.safeway.ca': 138,
'atp/nsi/perfect_match': 138,
'downloader/request_bytes': 60449,
'downloader/request_count': 141,
'downloader/request_method_count/GET': 141,
'downloader/response_bytes': 17050901,
'downloader/response_count': 141,
'downloader/response_status_count/200': 141, …
```

[Safeway CA] Fix Spider

---

locations/spiders/takarakuji_jp.py

[Takarakuji lottery and ATMs JP] add spider

---

locations/spiders/uniform_destination_us.py

```py
{'atp/brand/Uniform Destination': 47,
'atp/brand_wikidata/Q110677262': 47,
'atp/category/shop/clothes': 47,
'atp/country/US': 47,
'atp/field/city/missing': 47,
'atp/field/country/from_spider_name': 47,
'atp/field/opening_hours/missing': 47,
'atp/field/postcode/missing': 47,
'atp/field/state/from_reverse_geocoding': 47,
'atp/field/street_address/missing': 47,
'atp/field/website/invalid': 47,
'atp/item_scraped_host_count/api.storepoint.co': 47,
'atp/nsi/perfect_match': 47,
'downloader/request_bytes': 367, …
```

[Uniform Destination] New spider (47 locations)

---

locations/spiders/brooks_brothers_us.py

```py
{'atp/brand/Brooks Brothers': 137,
'atp/brand_wikidata/Q929722': 137,
'atp/category/shop/clothes': 137,
'atp/cdn/cloudflare/response_count': 139,
'atp/cdn/cloudflare/response_status_count/200': 139,
'atp/country/US': 137,
'atp/field/email/missing': 137,
'atp/field/image/missing': 137,
'atp/field/operator/missing': 137,
'atp/field/operator_wikidata/missing': 137,
'atp/field/twitter/missing': 137,
'atp/item_scraped_host_count/stores.brooksbrothers.com': 137,
'atp/nsi/perfect_match': 137,
'downloader/request_bytes': 84628,
'downloader/request_count': 139,
'downloader/request_method_count/GET': 139,
'downloader/response_bytes': 1316073,
'downloader/response_count': 139,
'downloader/response_status_count/200': 139,
'elapsed_time_seconds': 172.17387, …
```

[Brooks Brothers] New spider (137 locations)

---

locations/spiders/lounges_gb.py

```python
{'atp/brand/Lounges': 280,
'atp/brand_wikidata/Q114313933': 280,
'atp/category/amenity/restaurant': 280,
'atp/cdn/cloudflare/response_count': 284,
'atp/cdn/cloudflare/response_status_count/200': 284,
'atp/clean_strings/phone': 7,
'atp/country/GB': 280,
'atp/field/branch/missing': 14,
'atp/field/city/missing': 280,
'atp/field/country/from_spider_name': 280,
'atp/field/image/missing': 280,
'atp/field/lat/missing': 20,
'atp/field/lon/missing': 20,
'atp/field/name/missing': 280,
'atp/field/opening_hours/missing': 21,
'atp/field/operator/missing': 280,
'atp/field/operator_wikidata/missing': 280,
'atp/field/state/missing': 280, …
```

[Lounges GB] Fix Spider

---

locations/spiders/western_dental_us.py

There is a sitemap, but unfortunately it's broken, requiring the use of CrawlSpider :disappointed:
```py
{'atp/brand/Western Dental': 243,
'atp/brand_wikidata/Q64211989': 243,
'atp/category/amenity/dentist': 243,
'atp/category/multiple': 243,
'atp/country/US': 243,
'atp/field/branch/missing': 243,
'atp/field/email/missing': 243,
'atp/field/image/missing': 243,
'atp/field/operator/missing': 243,
'atp/field/operator_wikidata/missing': 243,
'atp/field/twitter/missing': 243,
'atp/item_scraped_host_count/www.westerndental.com': 243,
'atp/nsi/match_failed': 243,
'downloader/request_bytes': 186945,
'downloader/request_count': 405,
'downloader/request_method_count/GET': 405,
'downloader/response_bytes': 10301281,
'downloader/response_count': 405, …
```

[WesternDentalUS] Rewrite to use StructuredDataSpider to fix spider

---

locations/spiders/an_post_ie.py

**_Fixes : updated start_request to fix spider_**
```python
{'atp/category/amenity/parcel_locker': 9,
'atp/category/amenity/post_office': 892,
'atp/category/amenity/yes': 235,
'atp/country/IE': 1136,
'atp/duplicate_count': 9,
'atp/field/branch/missing': 1136,
'atp/field/brand/missing': 1136,
'atp/field/brand_wikidata/missing': 1136,
'atp/field/email/missing': 1136,
'atp/field/image/missing': 1136,
'atp/field/opening_hours/missing': 1136,
'atp/field/operator/missing': 235,
'atp/field/operator_wikidata/missing': 235,
'atp/field/phone/missing': 21,
'atp/field/street_address/missing': 1136,
'atp/field/twitter/missing': 1136,
'atp/item_scraped_host_count/apim-anpost-apwebapis.anpost.com': 1145, …
```

[An Post IE] Fix Spider

---

locations/spiders/sunglass_hut_gb.py

The Yext spider for Sunglass Hut does not find all the UK stores.

[Sunglass Hut GB] Add spider

---

locations/spiders/addresses/us/mn/us_mn_hennepin_addresses_us.py

Add addresses for Hennepin county, MN

---

locations/spiders/intesa_sanpaolo_it.py

```python
{'atp/brand/Intesa Sanpaolo': 7755,
'atp/brand_wikidata/Q1343118': 7755,
'atp/category/amenity/atm': 5427,
'atp/category/amenity/bank': 2328,
'atp/clean_strings/street_address': 2,
'atp/country/IT': 7755,
'atp/field/branch/missing': 7755,
'atp/field/country/from_spider_name': 7755,
'atp/field/email/invalid': 141,
'atp/field/email/missing': 5568,
'atp/field/image/missing': 7755,
'atp/field/opening_hours/missing': 5427,
'atp/field/operator/missing': 7755,
'atp/field/operator_wikidata/missing': 7755,
'atp/field/phone/missing': 5481,
'atp/field/postcode/missing': 7755,
'atp/field/twitter/missing': 7755,
'atp/field/website/missing': 7755,
'atp/item_scraped_host_count/api.intesasanpaolo.com': 7755,
'atp/nsi/match_failed': 7755, …
```

[Intesa Sanpaolo IT] Add Spider (7755 locations)

---

locations/spiders/kpn_nl.py

Rel: https://github.com/osmlab/name-suggestion-index/pull/11331

[KPN NL] Sync category with NSI

---

locations/spiders/ally_fashion_au.py

```python
{'atp/brand/Ally Fashion': 86,
'atp/brand_wikidata/Q19870623': 86,
'atp/category/shop/clothes': 86,
'atp/clean_strings/city': 3,
'atp/clean_strings/state': 2,
'atp/country/AU': 86,
'atp/field/opening_hours/missing': 86,
'atp/item_scraped_host_count/allyfashion.com': 86,
'atp/nsi/perfect_match': 86,
'downloader/request_bytes': 1090, …
```

[Ally Fashion AU] Fix Spider

---

locations/spiders/pizza_hut_kr.py

```python
{'atp/brand/Pizza Hut': 209,
'atp/brand_wikidata/Q191615': 209,
'atp/category/amenity/restaurant': 209,
'atp/clean_strings/addr_full': 3,
'atp/country/KR': 209,
'atp/duplicate_count': 121,
'atp/field/branch/missing': 209,
'atp/field/country/from_spider_name': 209,
'atp/field/email/missing': 209,
'atp/field/image/missing': 209,
'atp/field/operator/missing': 209,
'atp/field/operator_wikidata/missing': 209,
'atp/field/postcode/missing': 209,
'atp/field/state/missing': 209,
'atp/field/street_address/missing': 209,
'atp/field/twitter/missing': 209,
'atp/field/website/missing': 209,
'atp/item_scraped_host_count/www.pizzahut.co.kr': 330,
'atp/nsi/cc_match': 209, …
```

[Pizza Hut KR] Fix low scraped count for spider

---

locations/spiders/tahinis_ca.py
locations/storefinders/closeby.py

Rel: https://github.com/osmlab/name-suggestion-index/issues/11309

[Tahini's CA] Add spider

---

locations/spiders/audi.py

```
{
"atp/brand/Audi": 7962,
"atp/brand_wikidata/Q23317": 7962,
"atp/category/shop/car": 3205,
"atp/category/shop/car_repair": 4757,
"atp/clean_strings/name": 1,
"atp/clean_strings/postcode": 6,
"atp/clean_strings/street": 1,
"atp/clean_strings/website": 2,
"atp/country/AE": 11,
"atp/country/AL": 2,
"atp/country/AM": 2,
"atp/country/AQ": 29,
"atp/country/AR": 41,
"atp/country/AT": 274,
"atp/country/AU": 112,
"atp/country/AZ": 2,
"atp/country/BA": 12,
"atp/country/BD": 2,
"atp/country/BE": 130,
"atp/country/BG": 14,
"atp/country/BH": 2,
"atp/country/BN": 4,
"atp/country/BO": 6,
"atp/country/BR": 89,
"atp/country/CA": 110,
"atp/country/CH": 158,
"atp/country/CL": 10,
"atp/country/CN": 1495,
"atp/country/CO": 24,
"atp/country/CR": 4,
"atp/country/CU": 2,
"atp/country/CW": 2, …
```

[audi] Improving categorization + adding hours

---

locations/spiders/specsavers.py

**_Fixes : removed playwright to fix spider_**
```python
{'atp/brand/Specsavers': 2852,
'atp/brand_wikidata/Q2000610': 2852,
'atp/category/healthcare/audiologist': 1317,
'atp/category/healthcare/optometrist': 1535,
'atp/category/multiple': 2852,
'atp/country/AU': 719,
'atp/country/CA': 201,
'atp/country/GB': 1931,
'atp/country/JE': 1,
'atp/field/image/missing': 2852,
'atp/field/opening_hours/missing': 2852,
'atp/field/operator/missing': 2852,
'atp/field/operator_wikidata/missing': 2852,
'atp/field/phone/missing': 63,
'atp/field/twitter/missing': 2852,
'atp/item_scraped_host_count/www.specsavers.ca': 201, …
```

[Specsavers] Fix Spider

---

locations/spiders/pharmasave_ca.py

```python
{'atp/brand/Pharmasave': 707,
'atp/brand_wikidata/Q17093822': 707,
'atp/category/amenity/pharmacy': 707,
'atp/category/multiple': 707,
'atp/cdn/cloudflare/response_count': 709,
'atp/cdn/cloudflare/response_status_count/200': 709,
'atp/country/CA': 707,
'atp/field/branch/missing': 707,
'atp/field/country/from_spider_name': 707,
'atp/field/email/missing': 707,
'atp/field/image/missing': 707,
'atp/field/operator/missing': 707,
'atp/field/operator_wikidata/missing': 707,
'atp/field/twitter/missing': 707,
'atp/item_scraped_host_count/pharmasave.com': 707,
'atp/nsi/perfect_match': 707,
'downloader/exception_count': 21,
'downloader/exception_type_count/twisted.internet.error.TimeoutError': 21, …
```

[Pharmasave CA] Fix Spider

---

locations/spiders/jd_sports_de.py
locations/spiders/jd_sports_es.py
locations/spiders/jd_sports_fr.py
locations/spiders/jd_sports_ie.py
locations/spiders/jd_sports_it.py
locations/spiders/jd_sports_pt.py

**_Flagged jd_sports_de as requires proxy to fix spider._**

[Jd Sports DE] Flag jd_sports_de as requires_proxy

---

locations/spiders/stonehouse_gb.py

**_Flag stonehouse_gb as requires proxy_**

[Stone House GB] Fix Spider

---

locations/spiders/east_of_england_coop.py
locations/spiders/east_of_england_coop_gb.py

```python
{'atp/brand/East of England CO-OP': 221,
'atp/brand_wikidata/Q5329759': 221,
'atp/category/amenity/post_office': 29,
'atp/category/shop/funeral_directors': 49,
'atp/category/shop/supermarket': 128,
'atp/category/shop/travel_agency': 15,
'atp/clean_strings/branch': 3,
'atp/country/GB': 221,
'atp/field/email/missing': 221,
'atp/field/image/missing': 221,
'atp/field/phone/invalid': 48,
'atp/field/state/missing': 221,
'atp/field/twitter/missing': 221,
'atp/item_scraped_host_count/www.eastofengland.coop': 221,
'atp/nsi/cc_match': 128,
'atp/nsi/match_failed': 93,
'atp/operator/East of …
```

[East Of England Coop] Fix Spider

---

locations/spiders/flight_centre_au.py

```python
{'atp/brand/Flight Centre': 309,
'atp/brand_wikidata/Q5459202': 309,
'atp/category/shop/travel_agency': 309,
'atp/cdn/cloudfront/response_count': 1,
'atp/cdn/cloudfront/response_status_count/200': 1,
'atp/clean_strings/street_address': 190,
'atp/country/AU': 309,
'atp/field/branch/missing': 309,
'atp/field/country/from_spider_name': 309,
'atp/field/email/missing': 309,
'atp/field/image/missing': 309,
'atp/field/operator/missing': 309,
'atp/field/operator_wikidata/missing': 309,
'atp/field/phone/missing': 309, …
```

[Flight Centre AU] Fix Spider

---

locations/spiders/vibra_hotels_es.py

[Vibra Hotels ES] Add spider

---

locations/spiders/wanderhotels.py

[Wanderhotels] Add spider

---

locations/spiders/ih_hotels_it.py

No lat lon. Different brand to ihg_hotels.py

[iHHotels IT] Add spider

---

locations/spiders/schuh_gb.py

Opening hours no longer available

[Schuh GB] Remove opening hours

---

locations/spiders/mitsubishi_pe.py

```python
{'atp/brand/Mitsubishi': 88,
'atp/brand_wikidata/Q36033': 88,
'atp/category/shop/car': 31,
'atp/category/shop/car_parts': 29,
'atp/category/shop/car_repair': 28,
'atp/clean_strings/addr_full': 7,
'atp/clean_strings/phone': 6,
'atp/country/PE': 88,
'atp/field/city/missing': 88,
'atp/field/country/from_spider_name': 88,
'atp/field/lat/missing': 84,
'atp/field/lon/missing': 84,
'atp/field/name/missing': 29,
'atp/field/opening_hours/missing': 88,
'atp/field/phone/invalid': 20,
'atp/field/postcode/missing': 88,
'atp/field/street_address/missing': …
```

[Misubishi PE] Fix Spider

---

locations/categories.py
locations/spiders/maserati.py

```json
{
"atp/brand/Maserati": 687,
"atp/brand_wikidata/Q35962": 687,
"atp/category/shop/car": 322,
"atp/category/shop/car_repair": 365,
"atp/country/AE": 7,
"atp/country/AT": 4,
"atp/country/AU": 13,
"atp/country/AZ": 2,
"atp/country/BE": 6,
"atp/country/BG": 2,
"atp/country/BH": 2,
"atp/country/BR": 2,
"atp/country/BY": 2,
"atp/country/CA": 25,
"atp/country/CH": 22,
"atp/country/CL": 2,
"atp/country/CN": 66,
"atp/country/CR": 2,
"atp/country/CY": 4,
"atp/country/CZ": 3,
"atp/country/DE": 40,
"atp/country/DK": 3,
"atp/country/DO": 2,
"atp/country/EC": 2,
"atp/country/EE": 2,
"atp/country/EG": 2,
"atp/country/ES": 15,
"atp/country/FR": 21,
"atp/country/GB": 22,
"atp/country/GR": 2,
"atp/country/GT": 2,
"atp/country/HK": 2,
"atp/country/HU": 2,
"atp/country/ID": 1,
"atp/country/IL": 2, …
```

[maserati] parse hours & improve categories

---

locations/spiders/matchbox_au.py

**_Fixes : used chompjs to parse raw_data to json to fix spider_**
```python
{'atp/brand/Matchbox': 19,
'atp/brand_wikidata/Q117854120': 19,
'atp/category/shop/houseware': 19,
'atp/country/AU': 19,
'atp/field/branch/missing': 19,
'atp/field/postcode/missing': 19,
'atp/field/street_address/missing': 19, …
```

[Matchbox AU] Fix Spider
