locations/spiders/dick_blick.py

Add Dick Blick

---

locations/spiders/bed_bath_beyond.py

Add Bed Bath and Beyond

---

locations/spiders/dennys.py

Add Denny's scraper

---

locations/spiders/sweetgreen.py

Add Sweetgreen spider

---

locations/spiders/bojangles.py

Add Bojangles scraper

---

README.md
locations/spiders/louisa_coffee.py

Trying this out with a Taiwanese coffee chain I've been enjoying here in Taipei.

Louisa Coffee

---

locations/spiders/planned_parenthood.py

Add a spider for Planned Parenthood

---

ci/run_spiders_on_travis.sh
locations/spiders/goddard_school.py
locations/spiders/learning_experience.py
locations/spiders/montessori_school.py

Childcare!

---

locations/spiders/mcdonalds.py

This pulls in locations for United States, Canada, and Great Britain. The same API should work for other countries, but they seem to error out. Other countries might have their own store locator APIs.

Add McDonald's spider

---

locations/spiders/whataburger.py

Add Whataburger spider

---

locations/spiders/wellsfargo.py

Add Wells Fargo spider

---

locations/spiders/homedepot.py

Add Home Depot spider

---

.travis.yml
locations/spiders/sephora.py

Add Sephora

---

locations/spiders/fiveguys.py

Add Five Guys spider

---

locations/spiders/chickfila.py

Add Chick-Fil-A spider

---

locations/spiders/portillos.py

Add Portillo's

---

locations/spiders/sonic_drivein.py

Add a Sonic Drive-in spider

---

locations/spiders/superamerica.py

This only gets ~50 items and doesn't spider out any farther yet.

Add SuperAmerica spider

---

locations/spiders/superamerica.py

Don't need the second SuperAmerica call

---

locations/spiders/blue_bottle_cafe.py

Fixes #157.
Is there a defined set of properties that the GeojsonPointItems need to contain, or should they just contain everything that can be pulled off the page that isn't redundant.
Otherwise, I think this is all set.

Blue Bottle Cafe

---

.gitignore
locations/spiders/tjmaxx.py

Fixes #208
TjMaxx has 1224 stores, this scraper scraps all.
However the store_hours are not too consistent
for instance,
Mon-Wed: 9:30a-9:30p,
Thanksgiving Day: CLOSED, <- This is skipped.
Fri-Sat: 7a-10p,
Sun: 9a-10p
Let me know if i need to do otherwise.

Tj Maxx Crawler

---

locations/spiders/brueggers.py

Add Brueggers

---

locations/spiders/marshalls.py

Initial commit of Marshally Spider, hours need to be parsed to OSM.

---

locations/spiders/noodles_and_company.py

Fixes #206.
The site says there are 479 locations, and my scraper scraped 477 total. This is likely due to 2 of them not being listed.
The scraper doesn't include the "opening_hours" field in the properties of the output. I wasn't sure if this was important to scrape because I saw other spiders that didn't include it. Please let me know if you'd like this field included.

Added scraper for noodles and company.

---

locations/spiders/marshalls.py

Closes #207 
@iandees Removed unneeded keys and normalized

Normalized the address keys and removed unneeded keys

---

README.md
locations/spiders/bathandbodyworks.py

Fixes #186. Scrapes US and global locations.

Added spider for bathandbodyworks

---

locations/spiders/afcurgentcare.py

Added spider for afcurgentcare.com

---

locations/spiders/medexpress.py

Added spider for medexpress.com

---

locations/spiders/coastal.py

Fixes #155 
Please review it and let me know the result.
Thanks.

#155 coastalfarm

---

locations/spiders/gattispizza.py

I made a spider for Gattispizza. Please check.

Gattispizza

---

locations/spiders/coastal.py
locations/spiders/wilco_farm.py

Fixes #154 
Please review it and let me know.
Thanks.

154 wilcofarmstores

---

locations/spiders/jamba_juice.py

Added Jamba Juice Spider

---

dollartree.py
locations/spiders/dollartree.py

Dollar Tree

---

locations/spiders/tacocabana.py

Taco Cabana

---

locations/spiders/concentra.py

Added spider for concentra.com

---

locations/spiders/qualitydairy.py
locations/spiders/quiznos.py

Qualitydiary

---

locations/spiders/beer_store.py

Beer Store

---

locations/spiders/redlobster.py

Red Lobster

---

locations/spiders/beacon_bridge_market.py

Beacon & Bridge Market spider. fixed #125

---

locations/spiders/villageinn.py

Village Inn

---

locations/spiders/tractorsupply.py

Fixes #153.
Having issues sending properties to GeojsonPointItem.
"KeyError: 'GeojsonPointItem does not support field: fieldname"
Any ideas why I run into this..? Thanks!
Also, my spider runs so fast that eventually their servers block my IP.
Should I use a simple sleep to avoid any issues?

TractorSupply

---

locations/spiders/northern_california_breweries.py

Northern California Breweries

---

locations/spiders/dairy_queen.py

OSM Hours not completed. Will be adding OSM hours.

Dairy Queen Spider

---

locations/spiders/innout.py

From https://github.com/alltheplaces/alltheplaces/pull/246
Fixes #89.

Add In-n-out spider

---

Pipfile
Pipfile.lock
locations/spiders/potbelly_sandwichshop.py

Fixes #124.
@iandees , I have taken "pickup_menu_url" for "website" field.
But there is also "facebook_url".
I am not sure if it is correct to pull "pickup_menu_url" for "website".
Thanks.

potbelly sandwich

---

locations/spiders/crown_burgers.py

Crown Burgers

---

locations/spiders/nextcare.py

Added spider for nextcare.com

---

locations/spiders/pandaexpress.py

Fixes #58.
This crawler queries each state for almost 2k current Panda Express locations @nvkelso @iandees

Panda Express Crawler

---

locations/spiders/labreweries.py

Fixes #262
There is no geo data on these pages. How should that be handled?

LA Breweries

---

locations/spiders/albert_and_walter.py

Fixes #112.
@iandees, please have a look Albert and Walter's spider.
Thanks.

Albert and Walter

---

locations/spiders/mcmenamins.py

Fixes #156.
www.mcmenamins.com
let's check

www.mcmenamins.com

---

locations/spiders/hihostels.py

Hi Hostels #260

---

locations/spiders/sweet_tomatoes.py

Sweet-Tomatoes

---

locations/spiders/olivegarden.py

Olive Garden

---

locations/spiders/timhortons.py

Tim Hortons

---

locations/spiders/red_robbin.py

Fixes #109.
@iandees , Please review this spider.
Thanks.

Red Robbin

---

locations/spiders/shopko.py

Shopko #117

---

locations/spiders/mcmenamins.py

Removing debugging code

---

locations/spiders/timhortons.py

Tim Horton's

---

locations/spiders/Monicals_pizza.py

Monicals Pizza spider

---

locations/spiders/krystal.py

Krystal Spider, need to add OSM hours

---

locations/spiders/mcdonalds_localizer.py

For #1
This spider will be expanded further if there are some websites which has similar format.
At this time, Puerto Rico and Costa Rica countries were added.

McLocalizer

---

locations/spiders/whidbeycoffee.py

whidbeycoffee

---

locations/spiders/checkers.py

Added spider for checkers.com

---

locations/spiders/beermapping.py

Beer Mapping Project

---

.dockerignore
Dockerfile
ci/run_all_spiders.py
ci/run_all_spiders.sh
locations/pipelines.py
locations/spiders/anthonys_restaurants.py
locations/spiders/cvs.py
locations/spiders/dairy_queen.py
locations/spiders/labreweries.py
locations/spiders/marshalls.py
locations/spiders/mcmenamins.py
locations/spiders/noodles_and_company.py
locations/spiders/superonefoods.py
locations/spiders/whidbeycoffee.py

Add Dockerfile and scripts to support a build that runs all the scrapers and uploads the results to be used on the website.

Global build

---

Dockerfile
Pipfile
ci/run_all_spiders.py
ci/run_all_spiders.sh

Add awscli to dev dependencies so pushing to s3 works

---

locations/spiders/club_milanesa.py

Fixes #100.
Club Milanesa spider. No lat or lon present

El Club de la Milanesa

---

locations/spiders/bigboy.py

Added bigboy spinder

---

locations/spiders/pigglywiggly.py

For #113 
Currently, this spider only gathers location data from their stores not in Wisconsin and Illinois.
Gathering data from those locations involves sending a request to an api that is specifically for their stores in those two states. I couldn't quite get the request to work and figured my time would be better spent on a different issue.

Added spider for pigglywiggly.com

---

locations/spiders/jackinthebox.py

Added spider for jackinthebox.com

---

locations/spiders/woods_coffee.py

Woods Coffee

---

locations/spiders/laveneciana.py

laveneciana

---

locations/spiders/schlotzskys.py

Fixes #143.
Deleted the lat and lon sections for now.
Everything else seems to be running smoothly. Was a little unsure about the ref section of the GeojsonPointItem, used the current url for that.
Up to change it if needed.

Schlotzskys

---

locations/spiders/pizzaranch.py

Pizza Ranch

---

locations/spiders/dunhams_sports.py

Dunham's Sports

---

locations/spiders/dominos_pizza.py
locations/spiders/mcmenamins.py

Dominos pizza

---

ci/run_all_spiders.py
ci/run_all_spiders.sh

Trying to debug hanging on scrapy run

---

locations/spiders/wawa.py

Added wawa spider, OSM hours remaining

---

locations/spiders/dunkin.py

Fixes #50.
Dunkin Donuts website claims more than 8k locations in North America. Scraper output aligns with that figure. @iandees @nvkelso

Dunkin Donuts

---

locations/spiders/western_family.py

Western Family

---

locations/spiders/mcdonalds_nl.py

For #1.
Created the Spider for Netherlands of McDonalds.
Please review this.
thanks.

McDonalds - Netherlands

---

locations/spiders/mcdonalds_localizer.py

For #1.
Added McDonalds's Argentina to McLocalizer Spider.
I think this spider is also related with issue #98

McLocalizer(Argentina)

---

locations/spiders/mcdonalds_au.py

For #1.
Made another Spider for McDonalds' Australia because it has different response result.

McDonalds - Australia

---

locations/spiders/mcdonalds_localizer.py

Fix #1 
Added McDonalds' Panama to McLocalizerSpider.

McLocalizer(Panama)

---

Pipfile.lock
locations/spiders/serious_coffee.py

Serious Coffee

---

locations/spiders/lou_grey.py

Lou & Grey

---

locations/spiders/mcdonalds_de.py

For #1 
Created the Spider for Germany of McDonalds.
please review this.
thanks.

McDonalds - Germany

---

locations/spiders/advanceautoparts.py

Advance Auto Parts

---

locations/spiders/arbys.py

Arbys Spider

---

locations/spiders/carrefour.py

Closes #74 . Will complete OSM tomorrow

Carrefour Spider

---

locations/spiders/carrefour.py

Carrefour.com.ar

---

locations/spiders/mcdonalds_fr.py

For #1 
Created spider for France of McDonalds.

McDonalds - France

---

locations/spiders/amctheatres.py

AMC Theatres

---

locations/spiders/mcdonalds.py

For #1 
Added url for sweden to mcdonalds.py file.

McDonalds - Sweden

---

locations/spiders/mcdonalds_gt.py

For #1 
Created the spider for Guatemala of McDonalds.

McDonalds - Guatemala

---

locations/spiders/mcdonalds_hk.py

For #1 
Created the Spider for Hong Kong of McDonalds.

McDonalds - Hong Kong

---

locations/spiders/mcdonalds_qstore.py

For #1 
Merged Australia and New Zealand into one new Spider - mcdonalds_qstore.
Removed McDonaldsAUSpider(mcdonalds_au.py).

McDonaldsQStore

---

locations/spiders/catherines.py

Catherine's

---

locations/spiders/lagenovesa.py

99-legenovesa

---

locations/spiders/justice.py

Added spider for shopjustice.com

---

locations/spiders/lane_bryant.py

Lane Bryant

---

locations/spiders/harborfreight.py

harbor freight

---

locations/spiders/whole_foods.py

Whole Foods

---

locations/spiders/disco_argentina.py

Disco Argentina

---

locations/spiders/mcdonalds_ch.py

For #1 
Created the spider for Switzerland of McDonalds.

McDonalds - Switzerland

---

locations/spiders/mcdonalds_locator.py

For #1 
Merged the Ireland and Hong Kong into one Spider - mcdonalds_locator.py.
Removed mcdonalds_hk.py.

Mcdonalds - Locator

---

locations/spiders/caribou_coffee.py

Complete Caribou Coffee Spider

---

locations/spiders/bobs_burgers.py

Fixes #103
no lat/lon but full address included. Hours are present in nested tables with inconsistent html. Can continue to work on extracting hours if desired. Currently 13 locations.

Bob's Burgers

---

locations/spiders/steak_n_shake.py

Steak 'n' Shake

---

locations/spiders/premierurgentcare.py

Working spider for Premier Urgent Care, part of issue #185.
All hours are 9am-9pm, so added an exception handler that will raise if they add a store that breaks the mould.

premierurgentcare

---

locations/spiders/mcdonalds_at.py

For #1 
Created the spider for Austria of McDonalds.

McDonalds - Austria

---

locations/spiders/moka_house.py

Moka House (BC)

---

locations/spiders/county_market.py

County Market Spider, Completed

---

locations/spiders/sainsburys.py

Sainsburys

---

locations/spiders/mcdonalds_localizer.py

For #1 
Added the Brazil to McdonaldsLocalizer Spider

McDonaldsLocalizer(Brazil)

---

locations/spiders/mcdonalds_sg.py

For #1 
Created the Spider for Singapore of McDonalds.
I put raw opening_hours because of its response.
Please see comments #1

McDonalds - Singapore

---

locations/spiders/mcdonalds.py

For #1 
Added Denmark to existing McDonaldsSpider - mcdonalds.py

McDonalds - Denmark

---

locations/spiders/mcdonalds_my.py

For #1 
Created the Spider for Malaysia of Mcdonalds.

McDonalds - Malaysia

---

locations/spiders/mcdonalds_locator.py

For #1 
Added the Taiwan to McdonaldsLocatorSpider - mcdonalds_locator.py.

McDonalds - Taiwan

---

locations/spiders/mcdonalds.py
locations/spiders/mcdonalds_my.py

For #1 
Added the Norway to McdonaldsSpider.

McDonalds - Norway

---

locations/spiders/Safeway.py
locations/spiders/albertsons.py

65-albertsons

---

locations/spiders/market_basket.py

28 market basket

---

locations/spiders/whitecastle.py

Whitecastle

---

locations/spiders/homebase.py

422 homebase

---

locations/spiders/carphone_warehouse.py

carphone_warehouse

---

locations/spiders/tacotote.py

http://tacotote.com

---

locations/spiders/mcdonalds_fi.py

for #1 
Created the Spider for Finland of McDonalds.

McDonalds - Finland

---

locations/spiders/hamptoninn.py

Hampton Inn

---

locations/spiders/mcdonalds_lu.py

For #1 
Created the Spider for Luxembourg of McDonalds

McDonalds - Luxembourg

---

locations/spiders/mcdonalds_localizer.py

For #1 
Added Venezuela to McDonaldsLocalizerSpider - mcdonalds_localizer.py.

McDonalds - Venezuela

---

locations/spiders/coopfood.py

make coopfood

---

locations/spiders/taco_bueno.py

Taco Bueno

---

locations/spiders/ace_hardware.py

ace-hardware

---

locations/spiders/oreilly.py

Oreilly Spider

---

locations/spiders/sherwin_williams.py

sherwin-williams #372

---

locations/spiders/mcdonalds_tr.py

For #1 
Create the Spider for Turkey of McDonalds.

McDonalds - Turkey

---

locations/spiders/mcdonalds_localizer.py

For #1 
Added Mexico to McDonaldsLocalizer Spider - mcdonalds_localizer.py

McDonalds - Mexico

---

locations/spiders/dollar_general.py

Dollar General

---

locations/spiders/costco.py

added costco spider

---

locations/spiders/dress_barn.py

DressBarn spider

---

locations/spiders/biggby.py

Biggby Coffee

---

locations/spiders/hangerclinic.py

Fixes #77 
~1% of hours not formatting ideally

working spider for Hanger Clinic #77

---

locations/spiders/ross_dress.py

Ross Dress for Less

---

locations/spiders/quiznos.py

updated Quiznos

---

locations/spiders/shopnsave.py

Shop 'n' Save

---

locations/spiders/coffee_time.py

Coffee Time

---

locations/spiders/autozone.py

Autozone Spider

---

locations/spiders/superstore.py

Superstore.

---

locations/spiders/mcdonalds_rs.py

For #1 
Create the Spider for Serbia of McDonalds.

McDonalds - Serbia

---

locations/spiders/gamestop.py

'Gamestop'

---

locations/spiders/primark.py

Needs some work, some of the urls I'm creating from store names in the JSON blob are resulting in 404s, and the address field is proving difficult to parse, since the format varies between stores. Pulling the addr_full field, and postcode when it's obvious (5 digits). 
Otherwise, returning valuable results so far. 
Should be ~ 353 stores based on the JSON.

primark #424

---

locations/spiders/mcdonalds.py

For #1 
Added the Saudi Arabia to McDonaldsSpider - mcdonalds.py

McDonalds - Saudi Arabia

---

locations/spiders/mcdonalds.py

For #1 
Added Kuwait to McDonaldsSpider - mcdonalds.py

McDonalds - Kuwait

---

locations/spiders/mcdonalds.py

For #1 
Added Oman to McDonaldsSpider - mcdonalds.py

McDonalds - Oman

---

locations/spiders/papa_johns.py

Papa Johns Spider

---

locations/spiders/lees_famous_recipe.py

Lee's Famous Recipe

---

locations/spiders/brighthorizons.py

Bright Horizons

---

locations/spiders/allstate_insurance_agents.py

524 allstate insurance agents

---

locations/spiders/mcdonalds_pl.py

For #1 
Created the Spider for Poland of McDonalds.

McDonalds - Poland

---

locations/spiders/mcdonalds_localizer.py

For #1 
Added  Uruguay to McDonaldsLocalizerSpider.

McDonaldsLocalizer(Uruguay)

---

locations/spiders/mcdonalds_cz.py

For #1 
Created the Spider for Czech Republic of McDonalds.

McDonalds - Czech Republic

---

locations/spiders/mcdonalds_localizer.py

For #1 
Added the Chile to McLocalizerSpider.

McDonaldsLocalizer(Chile)

---

locations/spiders/bannerhealth.py

Banner Health

---

locations/spiders/thirty_foods.py

Thirfty Foods

---

locations/spiders/fairway_market.py

Fairway's Market.

---

locations/spiders/mcdonalds_it.py

For #1 
Created the Spider for Italy of McDonalds.

McDonalds - Italy

---

locations/spiders/mcdonalds.py

For #1 
Added Bahrain to McDonaldsSpider.

McDonalds - Bahrain

---

locations/spiders/mcdonalds.py

For #1 
Added  United Arab Emirates to McDonaldsSpider

McDonalds -  United Arab Emirates

---

locations/spiders/mcdonalds_th.py

For #1 
Created the Spider for Thailand of McDonalds.

McDonalds - Thailand

---

locations/spiders/mcdonalds_jp.py

For #1 
Created the Spider for Japan of McDonalds.

McDonalds - Japan

---

locations/spiders/freshmarket.py

Fresh Market

---

locations/spiders/mcdonalds_ma.py

For #1 
Created the Spider for Morocco of McDonalds.

McDonalds - Morocco

---

locations/spiders/mcdonalds_ru.py

For #1 
created the Spider for Russia of McDonalds.

McDonalds - Russia

---

locations/spiders/jerseymikes.py

Jersey Mikes

---

locations/spiders/stop_and_shop.py

Stop & Shop 

---

locations/spiders/mcdonalds_hu.py

For #1 
Created the Spider for Hungary of McDonalds.

McDonalds - Hungary

---

locations/spiders/save_on_foods.py

Save on Foods. 

---

locations/spiders/cititrends.py

Citi Trends

---

locations/spiders/chrome_industries.py

chrome industries

---

ci/run_all_spiders.py
locations/exporters.py
locations/settings.py

Improve the GeoJSON Feature ID

---

locations/spiders/farmers_insurance.py

farmer's insurance

---

locations/spiders/mcdonalds_il.py

For #1 
Created the Spider for Israel of McDonalds.

McDonalds - Israel

---

locations/spiders/planet_fitness.py

Planet Fitness

---

locations/spiders/anytime_fitness.py

Anytime Fitness

---

locations/spiders/payless.py

(Payless) fixed formatting... again.

---

locations/spiders/lush_cosmetics.py

Lush Cosmetics

---

locations/spiders/sentryfoods.py

Sentry Foods

---

locations/spiders/ljsilvers.py

Long John Silver's

---

locations/spiders/mcdonalds_si.py

For #1 
Created the Spider for Slovenia of McDonalds.

McDonalds - Slovenia

---

locations/spiders/mcdonalds_eg.py

For #1 
Created the Spider for Egypt of McDonalds.

McDonalds - Egypt

---

locations/spiders/michaelkors.py

732 michaelkors

---

locations/spiders/lifetime.py

Lifetime Fitness

---

locations/spiders/erbertandgerberts.py

Erbert's and Gerbert's

---

locations/spiders/mcdonalds_pt.py

For #1 
Created the Spider for Portugal of McDonalds.

McDonalds - Portugal

---

locations/spiders/chuckecheese.py

Chuck E Cheese

---

locations/spiders/bass_pro.py

Fixes #650
Added spider for Bass Pro Shops

Bass Pro Shops

---

locations/spiders/tijuanaflats.py

Tijuana Flats

---

locations/spiders/menards.py

For #116 
Pulled lat/lon and address from script tag

Menards lat/lon and address one request

---

locations/spiders/thebarrecode.py

Added spider for thebarrecode.com

---

locations/spiders/surlatable.py

Sur La Table

---

locations/spiders/albert_heijn.py

albert heijn

---

locations/spiders/joann_fabrics.py

Now extracting latitude, longitude, and store hours. 
Fixes #679.

Joann fabrics

---

locations/spiders/marcustheatres.py

Marcus Theatres

---

locations/spiders/mcdonalds_lv.py

For #1 
Created the Spider for Latvia of McDonalds.

McDonalds - Latvia

---

locations/spiders/mcdonalds_bg.py

For #1 
Created the Spider for Bulgaria of McDonalds.

McDonalds - Bulgaria

---

locations/spiders/dillards.py

753 dillards

---

locations/spiders/soulcycle.py

Soul Cycle

---

locations/spiders/neiman_marcus.py

Neiman Marcus

---

locations/spiders/hugoboss.py

766 hugo boss

---

locations/spiders/cell-only.py

cell-only.com

---

locations/spiders/barmethod.py

fixes #685
No lat/lon on page.

Bar Method

---

locations/spiders/finishline.py

Finish Line

---

locations/spiders/regis_salon.py

For #655 
Added spider for Regis Salons

Regis Salons

---

locations/spiders/regis_salon_uk.py

For #655 
Added Regis Salon UK spider

Regis Salon UK stores

---

locations/spiders/hm.py
locations/spiders/wafflehouse.py

Fixes #742 
Wafflehouse has 1906 locations has locations managed by sweetiq.com
This fetches all locations.

Waffle House

---

locations/spiders/fuddruckers.py

Added Fuddruckers spider, includes international locations.    ~~Happy New Year

Fuddruckers

---

locations/spiders/mcdonalds_et.py

For #1 
Created the Spider for Estonia of McDonalds

McDonalds - Estonia

---

locations/spiders/athleta.py
locations/spiders/bananarepublic.py
locations/spiders/gap.py
locations/spiders/oldnavy.py

Fixes #579 
Fixes #775 
US stores

Spiders for Gap, Old Navy, Banana Republic & Athleta #579

---

locations/spiders/mcdonalds_sk.py

For #1 
Created the Spider for Slovakia of McDonalds.

McDonalds - Slovakia

---

locations/spiders/mcdonalds_localizer.py

FOR #1 
added the Colombia to McLocalizer Spider.

Mcdonalds - Colombia

---

locations/spiders/mcdonalds_mt.py

For #1 
Created the Spider for Malta of Mcdonalds.

McDonalds - Malta

---

locations/spiders/mcdonalds.py

For #1 
Added the Qatar to McDonaldsSpider.

McDonalds - Qatar

---

locations/spiders/mcdonalds_za.py

For #1 
Created the Spider for South Africa of McDonalds.
This website has no lat/lng and opening_hours. so left these informations.

McDonalds - South Africa

---

locations/spiders/old_chicago.py

Old Chicago

---

locations/spiders/regal_theaters.py

Regal Theaters

---

locations/spiders/jimmy_johns.py

Jimmy John's #75

---

locations/spiders/stater_bros.py

Stater Brothers #873

---

ci/run_all_spiders.sh

Use geojson exporter instead of ndgeojson

---

locations/spiders/tmobile_us.py

T-Mobile US.

---

locations/spiders/tacobell.py

added tacobell spider

---

locations/spiders/albertsons.py

Add jewel osco to albertson's spider

---

locations/hours.py
locations/spiders/ulta_beauty.py

Ulta beauty

---

locations/spiders/frys_electronics.py

Frys spider

---

locations/exporters.py
locations/spiders/walmart.py

Use the Walmart sitemap to get all US walmarts

---

locations/hours.py
locations/spiders/banfield_pet_hospital.py
tests/test_opening_hours.py

Fixes #872 
1037/1037 scraped.
Also included an update to hours.OpeningHours where previously not adding a range for a day (ie, store is closed) would still create an entry for that day.
Eg: ``"Mo-Sa 07:00-14:00; Su "`` instead of ``"Mo-Sa 07:00-14:00"``

Banfield pet hospital spider

---

locations/spiders/papamurphys.py

Fixes #786
1387/1387 locations scraped

Add spider for Papa Murphys

---

locations/spiders/gianteagle.py

Fixes #852
Scrapes 425/425 locations

Add spider for Giant Eagle

---

locations/spiders/dickssportinggoods.py

Fixes #680
733 locations scraped, 0 errors

Dick's Sporting Goods spider

---

locations/spiders/einsteinbros.py

Add spider for Einstein Bros. Closes #784

---

locations/spiders/pilot_flyingj.py

Add Pilot Flying J spider; closes #774

---

locations/spiders/rue21.py

Scraped 750/750 locations.
Fixes #940

Added spider for rue21

---

locations/spiders/chilis.py

Add Chilis spider; Closes #778

---

locations/spiders/hyatt.py

I had to add the download_delay to avoid getting blocked.  Takes about 30 min to run now.
906 hotels scraped.
Closes #676

Add spider for Hyatt hotels; closes #676

---

locations/spiders/lafitness.py

Add spider for LA Fitness; closes #689

---

locations/spiders/fifththirdbank.py

Closes #797 
1118/1118 locations scraped

Add spider for Fifth Third Bank; closes #797

---

locations/spiders/california_pizza_kitchen.py

Scraped 203/203 locations.
Closes #964

California Pizza Kitchen

---

locations/spiders/whataburger.py

Fixes the url, city, and addr_full xpaths. 250/250 locations.

Repaired the Whataburger spider

---

locations/spiders/guitar_center.py

Closes #995
546/546 locations scraped

Added spider for Guitar Center; closes #995

---

locations/spiders/aubonpain.py

211 locations scraped.  There's 214 listed locations but two have 404s on the store detail page and another is a duplicate.

Add spider for Au Bon Pain; closes #783

---

locations/spiders/elpolloloco.py

This adds **483** El Pollo Loco locations.
It does not include the 5 locations listed as "(Coming Soon)"

Added El Pollo Loco

---

locations/spiders/half_price_books.py

Scrapes 124/124 locations. Closes #1000

Adds spider for Half Price Books

---

locations/spiders/petsmart.py

Scraped 1517/1517 locations. Closes #1030

Adds spider for PetSmart

---

locations/spiders/family_dollar.py

Add Family Dollar spider

---

locations/spiders/avis.py

Scrapes 4999 locations worldwide

Add spider for Avis; closes #636

---

locations/spiders/sunglass_hut.py

Adds scraper for https://stores.sunglasshut.com/

Added sunglass_hut.py

---

locations/spiders/jcpenney.py

Closes #602 
Scrapes 865/865 locations.

Add spider for JCPenney

---

locations/spiders/deloitte.py

Closes #1072 
Some of the international offices have limited attributes available, but there should at least be some information for each of the locations.

Add spider for Deloitte

---

locations/spiders/starbucks.py

Starbuck spider using points

---

locations/spiders/penske.py

Add spider for Penske

---

locations/spiders/xpo_logistics.py

Add spider for XPO Logistics

---

locations/spiders/bass_pro.py

Cabela's and Bass Pro Shops have merged so I updated this spider to get both Bass Pro Shops and Cabela's locations.

Add Cabela's to Bass Pro Shops spider

---

locations/spiders/michaels.py

Add spider for Michales

---

locations/spiders/vca.py

Add spider for VCA Animal Hospitals

---

locations/spiders/pizza_hut.py

Closes #9 
Scraped 7,593 of 7,593 locations 🍕

add pizza_hut spider

---

locations/spiders/buybuybaby.py

Add spider for Buy Buy Baby

---

locations/spiders/costplus_worldmarket.py

Closes #1062
Scrapes 274/274 retail locations

Add spider for Cost Plus World Market

---

locations/spiders/merrilllynch.py

Scrapes 595 Merrill Lynch office locations (subsidiary of Bank of America)

Add spider for Merrill Lynch offices

---

locations/spiders/olivegarden.py

Olive Garden spider currently yields 0 records.
Updated to match on https urls and switch to better data source within location pages.
862 locations scraped.

Fix broken Olive Garden spider

---

locations/spiders/pizzaranch.py

fixed pizzaranch spider

---

locations/spiders/burger_king.py

Previously only captured 4,470 stores. Updated to capture all 7,233/7233 stores in the US.

fix Burger King spider

---

locations/spiders/lowes.py

Fixes Lowe's spider. Scrapes 1724/1724 US locations.

Fix Lowe's spider

---

locations/spiders/barnesandnoble.py

Scrapes 630/630 stores.
Closes #580

Add spider for Barnes & Noble

---

locations/spiders/homedepot.py

Scrapes 1985/1985 US store locations.

fixes the home depot spider

---

locations/spiders/benihana.py

Added spider for Benihana

---

locations/spiders/upsstore.py

Scrapes 4774/4774 locations (37 duplicate/redirects)
Closes #536

Add spider for UPS Store

---

locations/spiders/harristeeter.py

Fixed ref and store name for Harris Teeter

---

locations/spiders/express.py

Fix spider (currently scraping 0 locations)
Scrapes 208 Express Factory Outlets and 434 Express locations.

Fix Express spider and add international locations

---

locations/spiders/chase.py

Scrapes 5509 branch and ATM locations

Fix Chase spider

---

locations/spiders/dennys.py

Sorry, this one is perfect now. Address targets needed to be updated in previous commit.

Fix address targets

---

locations/spiders/dunkin.py

Spider was missing some locations in dense areas. Changed to use radius search with lat/long points.

Fix Dunkin spider

---

locations/spiders/dollartree.py

updated urls: allowed_domains and start_urls

Fix dollartree.py

---

locations/spiders/medexpress.py

#185 
Filters out 20 closed locations.

Update spider to filter out closed stores

---

locations/spiders/finishline.py

Was previously skipping Finish Line at Macy's locations and dropping some locations due to bad refs.

Fix Finish Line spider

---

locations/spiders/dunhams_sports.py

Added name field and fixed ref so that blank "duplicates" no longer get dropped. Now properly scrapes all 234 locations.

Fix spider for Dunham's Sports

---

locations/spiders/casino.py

This is a spider for French shops Casino.
This spider retrieve 408 shops from https://magasins.supercasino.fr/fr and all sub pages.
I added `addr_2_housenumber` because some supermarkets have multiple numbers.

feat(spider): add Casino spider

---

locations/spiders/anytime_fitness.py

Fixes #850
eg:
"720 St. Michael's Dr., None" is now "720 St. Michael's Dr."
Also added store name/number.

Fix addr_full 

---

locations/spiders/24_hour_fitness.py

Scrapes 443/443 locations. Closes #971

Add spider for 24 Hour Fitness

---

locations/spiders/belk.py

Scrapes 292/292 retail locations. Closes #897

Add spider for Belk

---

locations/spiders/choicehotels.py

Included hotel brands:
- Comfort Inn
- Comfort Inn & Suites
- Quality Inn
- Sleep Inn
- Clarion
- Cambria
- Mainstay Suites
- Suburban Extended Stay Hotel
- Econo Lodge
- Rodeway Inn
Closes #334

Add spider for Choice Hotels International

---

locations/spiders/goldsgym.py

Add spider for Gold's Gym; closes #614

---

locations/spiders/statefarm.py

For #519
Scrapes 19,182 State Farm agent offices

Add spider for State Farm Agents; closes #519

---

locations/spiders/rentacenter.py

Add spider for rentacenter; closes #528

---

locations/spiders/bloomingdales.py

Fix Macy's (site change); Add Bloomingdale's

---

locations/spiders/apple.py

#342 
Lots of empty fields before; also grabs international locations now.
Scrapes 506 locations.

Fix Apple Store spider and get international locations

---

locations/spiders/dominos_pizza.py

Looks like they changed their site.
Now scrapes 5957 locations
#122

Fix Dominos Pizza spider

---

locations/spiders/planet_fitness.py

#615 
Now grabs lat/long coordinates again and gets all 1918 locations

fix spider for planet fitness

---

locations/spiders/hyatt.py

This PR implements the quick fix for parsing Hyatt hotels mentioned in #1136.

Quick fix for Hyatt Parsing Bug

---

locations/spiders/walmart.py

Scrapes 5239/5239 US locations.
Appears Walmart changed their website recently. Updated the scraper to capture data from the script tag. Captures Sam's Club and Walmart Neighborhood Markets in addition to the Supercenters. 
Also it's probably a separate issue, but should also resolve #904.

Fixes Walmart spider

---

locations/spiders/bootbarn.py

Add spider for Boot Barn; closes #1060

---

locations/spiders/bbvacompass.py

Add spider for BBVA Compass bank; closes #1106

---

locations/spiders/bjswholesale.py

Add spider for BJ's Wholesale; closes #898'

---

locations/spiders/loves.py

Add spider for Love's Travel Stops

---

locations/spiders/ernst_young.py
locations/spiders/ey.py

Scrapes 816 EY office locations worldwide

Add spider for Ernst & Young

---

locations/spiders/pricewaterhousecoopers.py

Scrapes 74 PricewaterhouseCoopers locations in the US

Add spider for PricewaterhouseCoopers

---

locations/spiders/tesla.py

Captures 379/379 locations. Closes #1155
Includes international store locations and service centers. I added an extras property to help distinguish between stores/galleries and service centers.

adds spider for Tesla

---

locations/spiders/citi.py

Scrapes 62014 Branch/ATM and Partner ATM locations in US (and some in Mexico that are within 100 miles of the border).
I added "type" as an extra field - Citi ATMs are "atm", Citi braches are "branch" and partner ATMs are "moneypassatm".

Add spider for Citi Bank/Group

---

locations/spiders/tesla.py

Improves address handling and captures missing street addresses for Paramus, NJ and Bethesda, MD locations.

Refactored tesla spider to improve address handling

---

locations/spiders/cvs.py

Fixes CVS spider - most all attributes were missing due to changing store details page.
Scrapes 9762 CVS Health locations.

Fix CVS spider

---

locations/spiders/providence_health_services.py

Added spider for providence health & services.  Fixed comments from other pull request (which I closed due to accidentally leaving tim hortons edits in that branch)

Add spider for providence health & services

---

locations/spiders/homedepot_ca.py

Scrapes 182/182 Canadian Home Depot stores.  Closes #1179

Adds spider for Canadian The Home Depot locations

---

locations/spiders/jefferson_univ_hosp.py

Add spider for Thomas Jefferson University and Hospitals

---

locations/spiders/haggen.py

Add spider for Haggen: http://www.haggen.com/find-our-stores/
Latitude/Longitude not available (they are being geocoded via google on the fly)

Add spider for Haggen

---

locations/spiders/christmas_tree_shops.py

Scrapes 82/82 Christmas Tree Shops locations. Closes #1188

Adds spider for Christmas Tree Shops

---

locations/spiders/massage_envy.py

Add Massage Envy

---

locations/spiders/riteaid.py

Fixed the scraper to capture all locations & capture brand information for Rite Aid, RediClinic, and Walgreens.

Fixed Rite Aid spider

---

locations/spiders/pier1.py

Scrapes 879/879 US store locations.

Adds spider for Pier1 - US stores

---

locations/spiders/footlocker.py

Closes https://github.com/alltheplaces/alltheplaces/issues/1058

Add spider for footlocker

---

locations/spiders/signet_jewelers.py

Some store sites are down for construction so some errors are present when running the script

Signet jewelers

---

locations/spiders/gnc.py

Repairs the GNC spider which previously returned an empty result. Scrapes 5,599 US locations.
Initially attempted to use the searchable points however GNC’s site only permits a low number and very slow frequency of requests. Fortunately their search radius is pretty flexible (500mi) and each store’s metadata is stored as geojson on the store list page making it possible to limit the number of requests to the 52 states/territories where they’re present.

Repairs GNC spider

---

locations/spiders/sallybeauty.py

Sallybeauty

---

locations/spiders/bestbuy.py

reduced code duplication since xpath for city & state are the same.

refactor bestbuy scraper parse

---

locations/spiders/bestbuy_ca.py

Fix BestBuy CA scraper

---

locations/spiders/completecash.py

add completecash spider

---

locations/spiders/lenscrafters.py

@iandees added spider for lenscrafters

Add spider for lenscrafters

---

locations/spiders/staples.py

Fixed spider, grabs all 1102 locations

Fix spider for Staples

---

locations/spiders/dollartree.py

Also cleaned up opening hours to make use of the OpeningHours class.

Fix Dollar Tree (was scraping 0 locations)

---

locations/spiders/journeys.py

Scrapes 1093 locations in US.   Was unable to find lat/lons.

Add spider for Journeys

---

locations/spiders/7_11.py

They now have a store directory so this spider now uses that instead of the old api

Fix 7-11 spider, was scraping 0 locations

---

locations/spiders/att.py

Repairs AT&T spider which was returning 0 results. Now captures 5734/5734 retail locations, also now incorporates the OpeningHours class.

Repairs AT&T spider

---

locations/spiders/kfc.py

Now scrapes all 4012/4012 US locations.

Repairs kfc spider

---

locations/spiders/kfc_ca.py

Scrapes 664/664 Canadian KFC locations.

Adds spider for Canadian KFC locations

---

locations/spiders/whitehouseblackmarket.py

Add spider for White House Black Market

---

locations/spiders/pearle_vision.py

A couple places are missing addresses on their store page which causes the 2 errors

Add spider for Pearle Vision

---

locations/spiders/sherwin_williams.py

Scrapes 246 paint, commercial paint, and other facilities in US and CA.

Add spider for Sherwin Williams

---

locations/spiders/victoriassecret.py

Add spider for Victoria's Secret

---

locations/spiders/ross_dress.py

Needed to update the hours parsing, which was causing it to stop getting locations after 1.

Fix Ross dress to get all locations

---

locations/spiders/sonic_drivein.py

Added parsing for the cities with multiple locations. Now gets all 3000+ locations instead of only the ~1890 single-city locations.

Fix Sonic spider to get all locations

---

locations/spiders/goodwill.py

Captures 4,150 locations, including retail stores, outlets, donation sites, and job centers. Indirectly closes #1049.

Adds spider for Goodwill

---

locations/spiders/farmers_insurance.py

Farmers Insurance spider was not scraping locations, fixed spider to scrape all locations.

Fixed Farmers Insurance spider.

---

locations/spiders/california_pizza_kitchen.py

Adds store number for the California Pizza Kitchen Spider.

Update C.P.K. to include store number

---

locations/spiders/pricerite.py
locations/spiders/shoprite.py
locations/spiders/thefreshgrocer.py

Closes #865 
Closes #1235
Closes #864 
Closes #863

Add spiders for Shop Rite, Price Rite and The Fresh Grocer

---

locations/spiders/lush_cosmetics.py

It was only scraping 11 stores previously, now it gets all 200+.

Fix Lush Cosmetics spider

---

locations/spiders/lush_cosmetics.py

This adds Canadian locations for Lush Cosmetics
#677

Add CA locations to Lush spider

---

locations/spiders/regal_theaters.py

Spider was scraping 0 locations.

Fix for REGAL theaters

---

locations/spiders/vitamin_shoppe.py

Add name and remove redundant phone attribute.

Add name to The Vitamin Shoppe spider

---

locations/spiders/tacobell.py

postalcode field was collecting the locality instead, so I updated it to grab the postalcode

Fix Taco Bell spider to collect postal code

---

locations/spiders/ncp.py

NCP is a chain of private car parks with locations in the UK.

add spider for NCP

---

locations/spiders/marks_and_spencer.py

add spider for Marks & Spencer

---

locations/spiders/maurices.py

Update spider to account for site changes. Now scrapes 930/930 locations in US and Canada.
#364

Fix Maurices spider

---

locations/spiders/dress_barn.py

Updated to account for site changes.  Now scrapes 536 locations.
#363

Fix Dressbarn spider

---

locations/spiders/loft.py

Fix url patterns causing a few stores to get skipped; add Loft Outlet locations and a few extra properties. Fix opening hours.
#369

Add Loft Outlet and fix missing stores for Loft

---

locations/spiders/lane_bryant.py

Spider was scraping 0 locations

Fix spider for Lane Bryant

---

locations/spiders/Follett.py

Scrapes 1190/1190 Follett bookstore locations.

Adds spider for Follett bookstores

---

locations/spiders/ace_hardware.py

Add street address to Ace Hardware spider

---

locations/spiders/starbucks.py

Gets Canadian Starbucks now
#64

Add Canadian locations to Starbucks spider and additional attributes

---

locations/spiders/lids.py

Add spider for Lids.

---

locations/spiders/kwik_trip.py

Repairs the Kwik Trip spider which was returning 0 results - looks like they just moved the store-list page. Scrapes 694/694 locations.

Repairs Kwik Trip spider

---

locations/spiders/heb.py

Fixed broken spider for HEB

---

locations/spiders/circle_k.py

The spider was scraping 0 locations

Fix spider for Circle K

---

locations/spiders/harborfreight.py

Repairs Harbor and Freight spider. Was returning 0 results now captures all 1017 locations.

Repairs Harbor and Freight spider

---

locations/spiders/abercrombie_and_fitch.py

Add Scraper for Abercrombie & Fitch

Amb and fitch

---

locations/spiders/harborfreight.py

Fixes '@' typo in the address xpath.

Fix Harbor Freight typo

---

locations/spiders/vue.py
locations/spiders/vue_cinemas.py

Vue is a chain of cinemas with branches in the UK and Republic of Ireland. This spider covers both countries.

add spider for Vue Cinemas

---

locations/spiders/99centsonly.py

Add spider for 99 Cents Only Stores

---

locations/spiders/hyvee.py

Spider was no longer working due to site changes. Also updated so it collects all stores when there are multiple stores in a city.
#347

Fix Hyvee spider

---

locations/spiders/nordstrom.py

Repairs the Nordstrom spider which was previously returning 0 results. Now collects all 360 locations.

Repairs nordstrom spider

---

locations/spiders/michaelkors.py

I fixed the scraper to now get address, locality, and country.

Fix for Michael Kors spider

---

locations/spiders/homegoods.py
locations/spiders/homesense.py
locations/spiders/sierra.py
locations/spiders/tjx_ca.py

Scrapes the following brands in US/CA:
HomeSense (US)
HomeGoods (US)
Sierra (US)
Winners (CA)
Marshalls (CA)
HomeSense (CA)
Closes #944

Remaining TJX Companies US + CA

---

locations/spiders/firehouse_subs.py
locations/spiders/golden_corral.py

- Spider for Firehouse Subs
- Also, more defensive coding comment correction for Golden Corral

Fixes: #682 Add spider for Firehouse Subs

---

locations/spiders/arbys.py

Don't break when the store page doesn't list hours

Improve Arby's

---

locations/spiders/corepower_yoga.py
locations/spiders/shake_shack.py

Retrieves 178 out of 189 locations

Shake Shack spider

---

locations/spiders/omni_hotels.py

Omni hotels

---

locations/spiders/chickfila.py

Fixes issue #2. To fix spider, re-worked spider completely.

Fix spider for chickfila

---

locations/spiders/pandaexpress.py

Fix spider for Panda Express

---

locations/spiders/hibachisan.py

Subsidiary of Panda Restaurant Group.

Add spider for Hibachi-San

---

locations/spiders/hilton.py

Some site changes were causing ~50% of the hotels to fail.
Also updated subsidiary brand names.
#675

Fix Hilton spider

---

locations/spiders/us_army_national_guard.py

Add spider for Army National Guard

---

locations/spiders/papa_johns.py

fixed broken papa johns spider

---

ci/run_all_spiders.sh
locations/extensions.py
locations/settings.py

+ fix a few things in ci script --> -f is file existence, wasn't checking for GITHUB_WORKSPACE

New extension to log json stats for each spider

---

locations/spiders/pigglywiggly.py

Repairs the spider to capture the 98 locations in WI and IL as well as the locations from https://www.pigglywiggly.com/store-locations. Added coordinates and store hours for WI and IL as well. Should close #113

Repairs Piggly Wiggly spider

---

locations/spiders/katespade.py

Add spider for Kate Spade.

---

locations/spiders/motel6.py

Add spider for Motel 6.

---

locations/spiders/ashleyhomestore.py

Also fixed the CA store opening hours.

Fix Ashley HomeStore spider to collect US locations

---

locations/spiders/abercrombie_and_fitch.py
locations/spiders/albertsons.py
locations/spiders/choicehotels.py
locations/spiders/creditunion.py
locations/spiders/deloitte.py
locations/spiders/dollartree.py
locations/spiders/express.py
locations/spiders/finishline.py
locations/spiders/homegoods.py
locations/spiders/jcpenney.py
locations/spiders/jcrew.py
locations/spiders/journeys.py
locations/spiders/marriott.py
locations/spiders/stater_bros.py

fix all the spiders with brand in 'extras'

---

locations/spiders/sallybeauty.py

Modified Sally Beauty to include Canadian searchable points

---

locations/spiders/canadiantire.py

Canadian Tire

---

locations/spiders/petsmart.py

adding canada domain / locations to spider

---

locations/spiders/royallepage.py

Scrapes 661/661 office locations in CA

Add spider for Royal LePage

---

locations/spiders/dollarama.py

Add spider for Dollarama

---

locations/spiders/ardene.py

New spider for Ardene.

---

locations/spiders/dickeys_barbecue_pit.py

Notes: 
- lat/long are not included, because these do not seem to appear in the network traffic at all
- A few URLs return HTTP 500.  This does not appear to be due to the spider; the same response was observed for these URLs from Chrome and Firefox, as well.

Add spider for Dickey's Barbecue Pit

---

locations/spiders/interior_health.py

Scrapes 456 Interior Health CA locations. No coordinates available.

Adds spider for Interior Health

---

locations/spiders/delawarenorth.py

This is a bare-bones spider... :skull_and_crossbones: 
The address was inconsistent & included international addresses, so instead of parsing the address, I left all the properties in addr_full.
Hope this is okay! :spider:

Adding locations for Delaware North

---

locations/spiders/dierbergs.py

Correct location information is being captured now.

Fixed spider, it was yielding incorrect location information

---

locations/spiders/new_york_public_library.py

Scrapes 92 New York Public Library locations.

Adds spider for NY Public Libraries

---

locations/spiders/greyhound_ca.py

Scrapes 196 Canadian Greyhound locations

Adds Canadian locations for Greyhound

---

locations/spiders/canadaPost.py

Add spider for Canada Post.

---

locations/spiders/mueller.py

The script is to add scraper for website https://www.mueller.de/

Add spider for mueller.de

---

locations/spiders/giantfood.py

#146 
Noticed a bunch of stores were missing (was scraping about ~60 of 162 locations).  Switched to using the store directory instead of the API since it was limited to stores within 10 miles of the queried location.

Fix Giant Food

---

locations/spiders/cgi_group.py

add spider for CGI group

---

locations/spiders/rossmann_de.py

This scraper scrape the stores locations from https://www.rossmann.de/de/filialen/index.html.
It only consider the stores belongs to Germany region.

Add spider for rossmann.de

---

locations/spiders/dm.py

This scraper is to scrape the store locations for dm.de website.
Areas covered,
> Germany
> Austria
> Czech Republic

Feature/add scraper for dm.de

---

locations/spiders/sparkasse.py

Add spider for sparkasse.de

---

locations/spiders/earth_fare.py

Scrapes 50/50 Earth Fare locations. Closes #1418

Adds spider for Earth Fare

---

locations/spiders/davita.py

Scrapes 3570 DaVita dialysis centers.

Add spider for DaVita dialysis centers

---

locations/spiders/iceland.py
locations/spiders/iceland_foods.py

Add Iceland spider

---

locations/spiders/iceland_foods.py
locations/spiders/therange.py

Add The Range spider

---

locations/spiders/bq.py

Add B&Q Spider

---

locations/spiders/extended_stay_america.py

Add spider for Extended Stay America hotels

---

locations/spiders/jiffylube.py

Fixed broken spider for Jiffy Lube.
Spider is now scraping 1930 locations.

Fixed broken spider for Jiffy Lube

---

locations/spiders/morrisons.py

Scrapes 495 locations, was previously returning zero results. Minor updates to the api key and address extraction.

Fix Morrisons spider

---

locations/spiders/target.py

This was returning zero results before due to the search url returning
503.

Convert Target to use sitemap and use ld+json

---

locations/spiders/kroger.py

- When I ran it initially, it hang on the initial request. So using more
browser like headers allowed the response to complete. I was able to
get some requests in, but eventually it started returning 403s. I added
a delay, but I have no idea what will keep it below their crawling
threshold.
- Added wikidata.

Convert Kroger to use sitemap and ld+json

---

locations/spiders/sonic_drivein.py

This was returning zero results. Adds wikidata.

Update sonic spider to use ld+json

---

locations/spiders/wendys.py

This was returning zero results. Also adds wikidata.  Simplifies link
finding in the dom to not rely on long chains of html.

Convert Wendy's to use microdata

---

locations/spiders/boots.py
locations/spiders/boots_no.py
locations/spiders/boots_th.py

Repaired the Boots spider to fix the IndexErrors, now scrapes 2964 store locations. Also added separate spiders for their locations in Norway (164 locations) and Thailand (319 locations).

Repair Boots spider. Add NO and TH spiders.

---

locations/spiders/specsavers.py

Note that this has a 5-second delay to avoid 429 errors, so it takes a few hours to run.

Add spider for Specsavers in UK

---

locations/spiders/arbys.py

This was returning zero results. Uses ld+json metadata from page.
Doesn't attempt to parse the opening hours. Adds comment for wikidata.
```
{'downloader/request_bytes': 1941604,
'downloader/request_count': 5899,
'downloader/request_method_count/GET': 5899,
'downloader/response_bytes': 95793769,
'downloader/response_count': 5899,
'downloader/response_status_count/200': 5899,
'elapsed_time_seconds': 1450.921109,
'finish_time': datetime.datetime(2020, 4, 7, 20, 17, 42, 147575),
'item_scraped_count': 3409,
'log_count/DEBUG': 9308,
'log_count/INFO': 33,
'memusage/max': 96530432,
'memusage/startup': 63643648,
'request_depth_max': 3,
'response_received_count': 5899,
'scheduler/dequeued': 5899,
'scheduler/dequeued/memory': 5899,
'scheduler/enqueued': 5899, …
```

Fix Arbys spider

---

locations/spiders/lidl_de.py

Their DE site has a branch directory.

Add spider for Lidl DE

---

locations/spiders/lidl_fr.py
locations/spiders/lidl_uk.py
locations/spiders/lidl_us.py

Add Lidl spiders for UK, US, and FR

---

locations/spiders/aldi_de.py

Uses the new eu searchable points to scrape 3,949 DE locations.

Adds spider for Aldi DE

---

locations/spiders/aldi_nord_be.py
locations/spiders/aldi_nord_de.py
locations/spiders/aldi_nord_dk.py
locations/spiders/aldi_nord_es.py
locations/spiders/aldi_nord_lu.py
locations/spiders/aldi_nord_nl.py
locations/spiders/aldi_nord_pl.py
locations/spiders/aldi_nord_pt.py

Adds Aldi Nord locations for various countries in Europe. They do not not include latlons on their site.

Adds Aldi Nord locations for BE, DE, DK, ES, LU, NL, PL, PT

---

locations/spiders/arco.py

I was going to go to bed, but then I realized that the ARCO store locator just loads a CSV directly. 😄

Add ARCO Gas Stations (US/MX)

---

Pipfile
Pipfile.lock
locations/spiders/tapetro.py

Strawperson PR to see if want to add a new dependency to parse the xls per https://github.com/alltheplaces/alltheplaces/issues/1430

Add TravelCenters of America spider

---

locations/spiders/arco.py
locations/spiders/bp.py
locations/spiders/caseys_general_store.py
locations/spiders/chevron.py
locations/spiders/circle_k.py
locations/spiders/costco.py
locations/spiders/exxonmobil.py
locations/spiders/phillips_66_conoco_76.py
locations/spiders/shell.py

* standardizes gas station amenity and fuel tagging to use an OSM-like tag structure
* adds additional amenity and fuel tagging to gas stations

Improve extended data for Gas Stations

---

locations/spiders/royal_farms.py

(This spider still doesn't emit coordinates for geometry, since they aren't on the site anywhere. 😞 )

Improve Royal Farms spider

---

locations/spiders/valero.py

Add Valero Gas Stations

---

locations/spiders/lowes.py

This is outputting zero locations currently. Migrate to https, add
toilets attributes.

Update lowes spider for css changes

---

locations/spiders/tacobell.py

This is outputting zero locations currently.
```
2020-05-15 00:50:51 [scrapy.core.scraper] DEBUG: Scraped from <200 https://locations.tacobell.com/ky/bowling-green/1802-russellville-rd-.html>
{'addr_full': '1802 Russellville Rd.',
'brand': 'Taco Bell',
'brand_wikidata': 'Q752941',
'city': 'Bowling Green',
'extras': {'@spider': 'tacobell'},
'lat': 36.98128560870606,
'lon': -86.46554752260278,
'opening_hours': 'Mo-Su 10:00-00:00',
'phone': '(270) 846-9976',
'postcode': '42101',
'ref': '027653',
'state': 'KY',
'website': 'https://locations.tacobell.com/ky/bowling-green/1802-russellville-rd-.html'}
2020-05-15 00:50:51 [scrapy.core.engine] INFO: Closing spider (finished)
2020-05-15 00:50:51 [scrapy.extensions.feedexport] INFO: Stored geojson feed (4266 items) in: output/output/tacobell.geojson …
```

Update tacobell spider for css changes

---

locations/spiders/terrible_herbst.py

This spider doesn't include geodata, because this particular KML export from Google Maps only includes addresses and no lat/lon. 😭

Add Terrible Herbst gas stations

---

locations/spiders/advanceautoparts.py

This is returning zero locations currently.
```
2020-05-15 19:52:04 [scrapy.core.scraper] DEBUG: Scraped from <200 https://stores.advanceautoparts.com/il/aurora/1386-butterfield-rd>
{'addr_full': '1386 Butterfield Rd',
'brand': 'Advance Auto Parts',
'brand_wikidata': 'Q4686051',
'city': 'Aurora',
'extras': {'@spider': 'advanceautoparts', 'shop': 'car_parts'},
'lat': '41.81358422225105',
'lon': '-88.28196199254307',
'name': 'Aurora',
'opening_hours': 'Mo-Sa 07:30-20:00; Su 09:00-20:00',
'phone': '(630) 454-8000',
'postcode': '60502',
'ref': '7910',
'state': 'IL',
'website': 'https://stores.advanceautoparts.com/il/aurora/1386-butterfield-rd'}
2020-05-15 19:52:04 [scrapy.core.engine] INFO: Closing spider (finished)
2020-05-15 19:52:04 [scrapy.extensions.feedexport] INFO: Stored geojson feed …
```

Update advanceautoparts spider html/css parsing

---

locations/spiders/gulf.py

This spider doesn't provide lat/lon info, since it's not available on their site.

Add Gulf gas stations

---

locations/spiders/dominos_pizza_au.py
locations/spiders/dominos_pizza_de.py

Added:
- Dominos Pizza  Australia
- Dominos Pizza  Germany

Adding international locations for Dominos Pizza

---

locations/spiders/auchan.py

Add spider for Auchan France

---

locations/spiders/dominos_pizza_jp.py

Scrapes 740 JP Domino's locations.

Adds spider for Dominos in Japan

---

locations/spiders/superdrug.py

Please note that **this spider requires a user agent** setting in oreder to successfully run. **I did not include the user agent in this commit.**

Adding new spider for Superdrug

---

locations/spiders/rei.py

Added spider for REI

---

locations/spiders/university_maryland_medical_system.py

Previously the address of the parent organization was being extracted.

Pull correct addresses for locations

---

locations/spiders/pf_changs.py

I was able to scrape the address, city, state, postal code, phone, website, latitude and longitude! @thekuiperbelt, could you please review and let me know if any changes are needed?

Added PF Changs spider

---

locations/spiders/tanger_outlet.py

Done with the second one too :) @iandees @thekuiperbelt, could you please review?

Added Tanger Outlet spider

---

locations/spiders/childcare_network.py

Added Childcare Network spider

---

locations/spiders/kona_grill.py

Fix #1564
- Add spider to crawl konagrill
Ran locally and completed successfully

KonaGrill spider

---

locations/spiders/ralph_lauren.py

This is https://github.com/alltheplaces/alltheplaces/pull/1585 for #1562 but the PR had a merge conflict that I needed to fix here.

Ralph Lauren

---

locations/spiders/bertuccis.py

Closed #1565 
Scrapes 54 locations
**Sample Output**
```
{"type": "Feature", "id": "ioo_TBXSBQMR7-uei6fcsMHqpHU=", "properties": {"ref": "9905811", "@spider": "bertuccis", "addr:street": "500 West Germantown Pike", "addr:city": "Plymouth Meeting", "addr:state": "Pennsylvania", "addr:postcode": "19462", "addr:country": "USA", "name": "Bertucci's Plymouth Meeting", "phone": "(610) 397-0650", "website": "https://locations.bertuccis.com/us/pa/plymouth-meeting/500-west-germantown-pike", "opening_hours": "Mo-Su 11:00-21:00", "brand": "Bertuccis"}, "geometry": {"type": "Point", "coordinates": [-75.2816573, 40.1171732]}},
{"type": "Feature", "id": "ExpwOvZNSlod_ZrUiLa1YlnzmSg=", "properties": {"ref": "10446409", "@spider": "bertuccis", "addr:street": "860 Bethlehem Pike", "addr:city": "North …
```

Adds Bertuccis

---

locations/spiders/amf_bowling.py

Added AMF Bowling spider

---

locations/spiders/ralph_lauren.py

updated the spider to scrape all 416 locations, had to change the way of scraping which should be better now.

updated ralph lauren spider

---

locations/spiders/ati_pt.py

Fix #862 
- Add ATI PT spider
- Set the delay to honor robot.txt
Tested locally

I862 ati pt

---

locations/spiders/screwfix.py

Fixes #1557. 
@iandees, could you please review? I wasn't able to reliably extract the city/state/postcode since the format seems different in the few different locations I checked. I got the full address instead, is it okay?

add Screwfix spider

---

locations/spiders/deichmann.py
locations/spiders/langham_hotels.py

closes #1590
added Deichmann (shoe store) location spider.

added Deichmann locations

---

locations/spiders/vancouver_coastal_health.py

Scrapes 978 locations. Closes #1427

Adds spider for Vancouver Coastal Health

---

locations/spiders/dsw.py

Fix #782 
- Add DSW spider works for both ca and us

Add DSW spider

---

locations/spiders/aurecongroup.py

Fixes issue #1556 
@iandees could you please review this?

add Aurecon Group spider

---

locations/spiders/hallmark.py

Closed #790
Scrapes 1595 Hallmark Locations

Adds Hallmark Spider

---

locations/spiders/ihop.py

Updates to fix IHOP spider after page changes

Fix IHOP spider

---

locations/spiders/academy.py
locations/spiders/american_eagle_outfitters.py
locations/spiders/cinemark.py
locations/spiders/thebigbiscuit.py

Merge in some PRs using the newer CI configuration

---

locations/spiders/thebigbiscuit.py

Closes #1178
Scrapes 18 locations

Adds The Big Biscuit Spider

---

locations/spiders/academy.py

Add spider for Academy Sports & Outdoors

---

locations/spiders/american_eagle_outfitters.py

1273 stores worldwide - spider scrapes 1274 (found 1 extra url in MX which has a similar address to another but different unit number)
closes #1052

Add spider for American Eagle Outfitters

---

locations/spiders/cinemark.py

https://github.com/alltheplaces/alltheplaces/issues/1054

Add Cinemark site

---

locations/spiders/rona.py

Closes #1355 . Had to add a 30 sec delay to avoid 429 errors.

Adds spider for Rona locations

---

locations/spiders/lloyds_pharmacy.py

Scrapes 1433 locations. Closes #1609

Adds spider for LloydsPharmacy

---

locations/spiders/adeg.py

Add spider for ADEG (Austria)

---

locations/spiders/merkur.py

Add spider for Merkur (Austria)

---

locations/spiders/davids_bridal.py

Adds spider for David's Bridal

---

locations/spiders/zumiez.py

Fix: #858 
- Adds zumiez spider

Add zumiez spider

---

locations/spiders/lululemon.py

Fix: #670 
- Add LuLuLemon spider

Add lululemon spider

---

locations/spiders/camillelavie.py

Add spider for Camille La Vie

---

locations/spiders/pet_suites.py

added pet suites spider (#1579)

---

locations/spiders/habit_burger.py

Add spider for Habit Burger

---

locations/spiders/kroger.py

This is merging in #1516, but I don't have the ability to make changes to that branch.

Kroger brands spider

---

locations/spiders/orkin.py

No coordinates available. 
Closes #1171

Add spider for Orkin

---

locations/spiders/curaleaf.py

Closes #1173 
Added spider for curaleaf mention here https://github.com/alltheplaces/alltheplaces/issues/1173
Still a bit of a beginner so please let me know if I did something incorrectly. 
Also wondering what the main motivations/goals for the repository are? What can all this data ultimately be used for? 
Thanks.

added curaleaf spider

---

locations/spiders/livingspaces.py

Add spider for Living Spaces

---

locations/spiders/care_one.py

Add spider for Care One

---

locations/spiders/buffalo_wild_wings.py

Add spider for Buffalo Wild Wings

---

locations/spiders/taco_johns.py

Hi, I opted to find a site on my own to scrape. I am counting this toward Hacktoberfest. Thank you!

Add Taco John's Scraper

---

locations/spiders/pkequipment.py

Add spider for P&K Equipment

---

locations/spiders/equinox.py

added spider for equinox (#1142)

---

locations/spiders/farmershomefurniture.py

Fixes #1159 
Sample output: 
`{"type": "Feature", "id": "QjvtM2xnZyU3RTUAr0iFVTx92yo=", "properties": {"ref": "covingtonga", "@spider": "farmershomefurniture", "addr:full": "3197 N ELM ST", "addr:city": "COVINGTON", "addr:state": "GA", "phone": "770-786-1705", "opening_hours": "Mo-Fr 09:00-07:00; Sa 09:00-05:00", "brand": "Farmers Home Furniture"}, "geometry": {"type": "Point", "coordinates": [-83.856689, 33.60239]}},`

[#1159] Add spider for farmershomefurniture

---

locations/spiders/taco_johns.py

My code worked, but I found a couple of bugs in the regex. The `.` should have been escaped, but wasn't and I don't think the parenthesis negation was needed, so I changed the pattern.

Improve regex

---

locations/spiders/iowa_university.py

updated iowa university (#1638)

---

locations/spiders/target_au.py

Should I create an issue for new scrapers?

added australian target

---

locations/spiders/floor_and_decor.py

Scrapes 136 Floor & Decor locations. Closes #1651

Adds spider for Floor & Decor

---

locations/spiders/kaiser_permanente.py

Scrapes 2108 Kaiser Permanente locations

Add spider for Kaiser Permanente

---

locations/spiders/h_r_block.py

Repairs the H&R Block spider which was returning 0 results. Updated to use the sitemap.

Repair H&R Block spider

---

locations/spiders/insomnia_cookies.py

Closes #1670 . Scrapes 193 US locations.

Adds spider for Insomnia Cookies

---

locations/spiders/my_eye_dr.py

Closes #1672 . Scrapes 634 US locations.

Adds spider for MyEyeDr

---

locations/spiders/sbarro.py

Add spider for Sbarro

---

locations/spiders/thorntons.py

Closes #1683 . Scrapes 206 US locations.

Add spider for Thorntons

---

locations/spiders/visionworks.py

Closes #1679 . Scrapes 595 US locations.

Adds spider for Visionworks

---

locations/spiders/ponderosa.py

Add spider for Ponderosa Steakhouse

---

locations/spiders/barnesandnoble_college.py

Closes #580 
Problematic website - cannot scrape all locations at the moment.

Adding spider for Barnes & Noble College

---

locations/spiders/wendys.py

Now grabs all 6000+ locations instead of just like 3700 of them.

Fix spider for Wendy's

---

locations/spiders/kindred_healthcare.py

Closes #1690 . Scrapes 646 US locations.

Adds spider for Kindred Healthcare

---

locations/spiders/medical_city_healthcare.py

Scrapes 108 locations, closes #1698

Adds spider for Medical City Healthcare

---

locations/spiders/roundtablepizza.py

13 of the locations are missing lat/lon coordinates. What is the correct way to handle these locations?

Added roundtable pizza

---

locations/spiders/baylorscottwhitehealth.py

Add spider for Baylor Scott & White Health

---

.github/workflows/spider_pr.yaml

See https://github.com/aws/aws-cli/issues/5262

Fix build problem with awscli

---

locations/spiders/wellstar.py

Add spider for WellStar Health System

---

locations/spiders/fresenius_kindey_care.py

Adding spider for Fresenius Kidney Care

---

locations/spiders/kbp_foods.py

Scrapes all 760 KBP Foods locations using the 100mi searchable points.

Adds spider for KBP Foods

---

locations/spiders/bojangles.py

Was missing a lot of locations, now scrapes all

Fix for Bojangles spider

---

locations/spiders/whataburger.py

Updates the xpath for the store hours, spider once again returns all 848 locations! 🍔

Fix Whataburger spider

---

locations/spiders/caliber_home_loans.py

Scrapes 349 Caliber Home Loans locations. Closes #1718

Adds spider for Caliber Home Loans

---

locations/spiders/longhorn_steakhouse.py

Scrapes 536 US locations. Closes #1724

Add spider for LongHorn Steakhouse

---

locations/spiders/northside_hospital.py

Add spider for Northside Hospital

---

locations/spiders/scooters_coffee.py

Scrapes 325 US locations. Closes #1728

Adds spider for Scooter's Coffee

---

locations/spiders/subway.py

- Switch from a search to using their store directory
- Remove the crawl delay as it was unnecessary
Now produces 31343 items

Fix subway

---

locations/spiders/pdq.py

See https://github.com/scrapy/scrapy/pull/4901

Remove is_gzipped because Scrapy deprecated it

---

locations/spiders/liberty_mutual.py

Scrapes 181 US locations. Closes #1738

Add spider for Liberty Mutual

---

locations/spiders/ingles.py

Add spider for Ingles

---

locations/spiders/coen_markets.py

55 locations in PA, WV, and OH; some former Cogo's.

Add coen markets

---

locations/spiders/tractorsupply.py

Update spider for Tractor Supply Co

---

locations/spiders/pnc.py

add spider for pnc

---

locations/spiders/capital_one.py

Scrapes Capital One branch and cafe locations (excludes atm locations). Closes #799

Capital One

---

locations/spiders/viva_chicken.py

Adds spider for Viva Chicken and closes #1758. Guessing the capital one changes are showing up since that specific pull request hasn't been merged yet?

Viva Chicken

---

locations/spiders/xl_parts.py

Scrapes 119 locations. Closes #1764

Add spider for XL Parts

---

locations/spiders/geico.py

Scrapes 300 GEICO agent locations (excluding corporate offices). Closes #1770

Add spider for GEICO

---

locations/spiders/orangetheory_fitness.py

Scrapes 1489 locations across 23 countries. Closes #686

Add spider for Orangetheory Fitness

---

locations/spiders/alamo.py

Add new locations for Alamo

---

locations/spiders/national.py

new spider for national

---

locations/spiders/enterprise.py

fix spider for Enterprise

---

locations/spiders/vetco_clinic.py

Warning this scraper uses searchable_points us_zcta file - resource heavy.

Adding spider for Vetco

---

locations/spiders/moneygram.py

Add Moneygram

---

.github/workflows/spider_pr.yaml

This also fixes a deprecation warning for output filetype.

Write to logstats file and use that for calculating features written

---

.github/workflows/spider_pr.yaml
locations/spiders/autonation.py
locations/spiders/fiestamart.py
locations/spiders/harveys.py
locations/spiders/norma_de.py
locations/spiders/northside_hospital.py

Removes print statements that clog logs and also make the spider names more consistent.

Remove prints

---

locations/spiders/sallybeauty.py

Fix errors in Sally Beauty

---

locations/spiders/texas_roadhouse.py

Fix Texas Roadhouse

---

locations/spiders/tgifridays.py

Fix TGI Fridays

---

locations/spiders/tesla.py

Include superchargers and handle case when no addr_full

---

locations/spiders/quiznos.py

Fix Quiznos

---

locations/spiders/public_storage.py

Fix Public Storage

---

locations/spiders/bestbuy.py

Previously was picking up locations from the "nearby locations" panel and causing a bunch of duplicate urls to get skipped.

Updates to Best Buy spider to pick up missing locations

---

locations/spiders/aldi_uk.py

Fixes #1814
Fixes #1824 
Fixes #1886 
Fixes #1940

Fixed spider for Aldi UK

---

locations/spiders/nandos_uk.py

Add spider for Nandos UK

---

locations/spiders/coopfood.py

Updated api url and a few data fixes

Fix Coop Food (UK) spider

---

locations/spiders/nandos_ae.py
locations/spiders/nandos_au.py
locations/spiders/nandos_bh.py
locations/spiders/nandos_ca.py
locations/spiders/nandos_in.py
locations/spiders/nandos_my.py
locations/spiders/nandos_nz.py
locations/spiders/nandos_om.py
locations/spiders/nandos_pk.py
locations/spiders/nandos_qa.py
locations/spiders/nandos_sa.py
locations/spiders/nandos_sg.py
locations/spiders/nandos_us.py
locations/spiders/nandos_zm.py
locations/spiders/nandos_zw.py

Adds a set of spiders for more of Nandos international locations (US, CA, AU, etc.) Most individual country sites had their own structure and specific quirks so I organized them into their own files. I didn’t include a spider for South Africa or Botswana. These two were not easily scrapable without searchable points - maybe a good excuse to work on some points for Africa in the future 😄

Add additional countries for Nandos

---

locations/spiders/aaa.py

Scrapes 1308 US and CA locations using the searchable points. Closes #811

Add spider for AAA

---

locations/spiders/discount_tire.py

Scrapes 944 US locations. Closes #1936

Discount tire

---

locations/spiders/next_uk.py

Fix Spider for Next UK

---

locations/spiders/premierinn.py

Updated the spider to use all address parts in address full, makes more sense.

Updated the spider to use all address parts in address full

---

locations/spiders/uhaul.py

Fix UHaul spider

---

locations/spiders/tmobile_us.py

Fix TMobile US

---

locations/spiders/tesco.py

Rewrites the Tesco spider to use the sitemap to scrape 3108 UK locations. Closes #1856

Fix Tesco spider

---

locations/spiders/ikea_us.py

Repairs the Ikea US spider and scrapes 52/52 locations. Closes #2239

Repair Ikea US spider

---

locations/spiders/sunoco.py

Fix Sunoco

---

locations/spiders/ikea_uk.py

Repairs the Ikea UK spider. Unfortunately doesn't look like coordinates are available to capture anymore.
Closes #2238 , closes #2175 .

Repair Ikea UK spider

---

locations/spiders/academy.py

Fix Academy

---

locations/spiders/sheetz.py

Allow for missing phone number
Fixes #2203
Fixes #2079

Fix Sheetz

---

locations/spiders/afcurgentcare.py

Rewrite the spider entirely
Fixes #1807

Fix afcurgentcare

---

locations/spiders/albertsons.py

Fix crawling store links
Parse json instead of dom
Add kings

Fix albertsons

---

locations/spiders/schlotzskys.py

Fixes #2071 
Fixes #2514 
Fixes #2624

Update Schlotskys spider

---

locations/spiders/officedepot.py

Fixes #2057 
Fixes #2372 
Fixes #2611

Update Office Depot

---

locations/spiders/motel6.py

Update Motel 6

---

locations/spiders/papa_johns.py

Fixes #2066 
Fixes #2185 
Fixes #2381 
Fixes #2422 
Fixes #2620

Update Papa Johns

---

locations/spiders/cvs.py

Update CVS to update lat/lon

---

locations/spiders/costco.py

Update Costco user agent

---

locations/spiders/tmobile_us.py

Fix T-Mobile US

---

locations/spiders/sheetz.py

Update Sheetz spider

---

locations/spiders/holiday_stationstores.py

Update Holiday spider

---

locations/spiders/advanceautoparts.py

Make advance autoparts easier to read

---

locations/spiders/texas_roadhouse.py

Tweak code style to trigger another Texas Roadhouse build

---

locations/spiders/leslies_poolmart.py

Scrapes 892 locations. Closes #2648

Add spider for Leslie's Poolmart

---

locations/spiders/busy_beaver.py

25 hardware stores in PA, OH, and WV.

Add Busy Beaver

---

locations/spiders/anthonys_restaurants.py

Fixes #1827 
Fixes #1889 
Fixes #1943 
Fixes #1978

Fix anthonys_restaurants

---

locations/spiders/applebees.py

Fixes #2656
Fixes #2158
Fixes #2106
Fixes #2011
Fixes #1980
Fixes #1945
Fixes #1891
Fixes #1829

Fix Applebees

---

locations/spiders/acme_markets.py

Scrapes 162/162 US locations. Closes #2806

Add spider for Acme Markets

---

locations/spiders/arbys.py

Correct start url
Fix telephone, change ref
Workaround broken json 
Fixes #2657
Fixes #1946
Fixes #1892
Fixes #1830

Fix Arby's

---

locations/spiders/planned_parenthood.py

Fixes #2683
Fixes #2434
Fixes #2196
Fixes #1832

Fix planned_parenthood

---

locations/spiders/palm_beach_tan.py

Scraped 541 US locations. Closes #2811

Adding a spider for Palm Beach Tan

---

locations/spiders/popeyes.py

Fixes #2685
Fixes #2435
Fixes #2197
Fixes #1833

Fix Popeyes

---

locations/spiders/pricerite.py

Fixes #2687
Fixes #2437
Fixes #2200
Fixes #1835

Fix pricerite

---

locations/spiders/primark.py

Fixes #2688
Fixes #2438
Fixes #1836

Fix Primark

---

locations/spiders/providence_health_services.py

Rewrite spider using sitemap.xml and ldjson
Seems to be serving 500's quite often, including for the sitemap. Not sure how to handle those.

Fix providence_health_services

---

locations/spiders/publix.py

Has no store directory anymore, search by lat/lon.
Item counts seem to line up with what's listed [here](https://corporate.publix.com/about-publix/company-overview/facts-figures).
```
¶ <publix.geojson jq '.features[].properties."addr:state"' | huniq -cs
19 "VA"
49 "NC"
50 "TN"
65 "SC"
80 "AL"
192 "GA"
821 "FL"
```
Fixes #1839

Fix Publix

---

locations/spiders/cintas.py

Add spider for Cintas

---

locations/spiders/regis_salon.py

Fix regis salons

---

locations/spiders/regis_salon_uk.py

- Handle time formats
- Omit certain index pages
- Add delay sufficient to avoid 429 errors and/or temporary ip blackhole
Fixes #2506
Fixes #1843

Fix regis_uk

---

locations/spiders/rubios.py

Fix rubios

---

locations/spiders/safeway_ca.py

Fixes #2512
Fixes #2069
Fixes #1850

Fix safeway_ca

---

locations/spiders/cintas.py

Fixing bug found in Cintas Spider.

Fixing bug in Cintas

---

locations/spiders/tgifridays.py

Fixes #2760
Fixes #2692
Fixes #2534
Fixes #1859

Fix tgifridays

---

locations/spiders/tacocabana.py

Fixes #2755
Fixes #2528
Fixes #1852

Fix tacocabana

---

locations/spiders/thales_fr.py

Read kml instead of parsing the google my maps javascript
Fix misuse of local variables that produced incorrect results
Fixes #2761
Fixes #2693
Fixes #2535
Fixes #1860

Fix thales_fr

---

locations/spiders/tacotote.py

Fixes #2756
Fixes #2529
Fixes #1853

Fix tacotote

---

locations/spiders/thefreshgrocer.py

(Copy pasted from pricerite)
Fixes #2764
Fixes #2696
Fixes #2538
Fixes #2267
Fixes #1863

Fix thefreshgrocer

---

locations/spiders/tijuanaflats.py

Fixes #2943
Fixes #2767
Fixes #2699
Fixes #2541
Fixes #2270
Fixes #1866

Fix tijuanaflats

---

locations/spiders/tiffany.py

Fixes #2766
Fixes #2698
Fixes #2540
Fixes #2269
Fixes #1865
Closes #757

Fix tiffany

---

locations/spiders/albert_heijn.py

Fix albert_heijn

---

locations/spiders/banfield_pet_hospital.py

Fix banfield_pet_hospital

---

locations/spiders/awrestaurants.py

Fix awrestaurants

---

locations/spiders/aunt_annes.py

Fix auntie_annes

---

locations/spiders/camp_bow_wow.py

Add spider for Camp Bow Wow

---

locations/spiders/uniteddairyfarmers.py

Adding United Dairy Farmers spider.

United Dairy Farmers spider

---

locations/spiders/bankofamerica.py

Add download delay
Avoid choking on a broken and irrelevant ldjson
Fixes #1902

Fix bankofamerica

---

locations/spiders/ljsilvers.py

Fix ljsilvers

---

locations/spiders/south_carolina.py

Adding spider for South Carolina.

Spider for South Carolina

---

locations/spiders/elysium_healthcare.py

Scrapes 75 UK locations, excluding a handful of coming soon locations. Closes #3117

Adds spider for Elysium Healthcare

---

locations/spiders/whsmith_uk.py

Spider will take awhile to run as I couldn't find active store ids so I had to loop through all 4 digit ids.

Add spider for WHSmith UK

---

locations/spiders/freshthyme.py

Closes #883
Scrapes 70 Fresh Thyme Locations
Here's the sample output:
```json
{"type": "Feature", "id": "T0Q3LfXyAcobXTXFNMMtMsPHH_U=", "properties": {"ref": "126", "@spider": "freshthyme", "addr:street": "14727 Fresh Thyme Market Dr.", "addr:city": "Carmel", "addr:state": "IN", "addr:postcode": "46033", "addr:country": "US", "name": "Carmel, IN", "phone": "317-975-7203", "website": "www.freshthyme.com/stores/207", "opening_hours": "Mo-Su 07:00-21:00", "brand": "Fresh Thyme"}, "geometry": {"type": "Point", "coordinates": [-86.10813, 40.00102]}},
{"type": "Feature", "id": "Xgy2YQvsXvpIBTOEJNWNLUjuYjg=", "properties": {"ref": "116", "@spider": "freshthyme", "addr:street": "2500 N. Elston Ave.", "addr:city": "Chicago", "addr:state": "IL", "addr:postcode": "60647", "addr:country": "US", …
```

Adds Fresh Thyme Spider

---

locations/spiders/bucadibeppo.py

Scrapes 71 [locations](https://locations.bucadibeppo.com/index.html)
Closes #791
Here's the sample output:
```json
{"type": "Feature", "id": "GPC_0I5JCHQB9fE04AyoErqdrm8=", "properties": {"ref": "0523", "@spider": "bucadibeppo", "addr:street": "26940 Theater Dr", "addr:city": "Santa Clarita", "addr:state": "California", "addr:postcode": "91355", "addr:country": "US", "name": "Buca di Beppo Valencia", "phone": "(661) 253-1900", "website": "https://locations.bucadibeppo.com/us/ca/santa-clarita/26940-theater-dr", "opening_hours": "Mo-We 11:00-21:30; Th-Sa 11:00-22:00; Su 11:00-21:30", "brand": "Buca di Beppo"}, "geometry": {"type": "Point", "coordinates": [-118.560813, 34.418315]}},
{"type": "Feature", "id": "BNHbf3fiOKFx_Nkcw3VJHpJe7yA=", "properties": {"ref": "7111-w-ray-rd", "@spider": …
```

Adds Buca di Beppo Spider

---

locations/spiders/jimmy_johns.py

Fixes #2748
Fixes #1987
Fixes #3086

Fix for #2748

---

locations/spiders/steak_n_shake.py

Closes #3021
Closes #2931 
Closes #2263

Fix spider for Steak N Shake

---

locations/spiders/mariner_finance.py

Scrapes 469 US locations. Closes #3131

Add spider for Mariner Finance

---

locations/spiders/jjill.py

Scrapes 261 locations
Sample output:
```json
{"type": "Feature", "id": "gSq82mO8iFlibPSyOL5IAN9iJeg=", "properties": {"ref": "677", "@spider": "jjill", "addr:street": "6256 Topanga Canyon Blvd.", "addr:city": "Woodland Hills", "addr:state": "CA", "addr:postcode": "91367", "addr:country": "US", "name": "Topanga Village", "phone": "818.346.5455", "website": "https://locations.jjill.com/ca/woodland-hills/677/", "opening_hours": "Mo 11am - 8pm; Tu 11am - 8pm; We 11am - 8pm; Th 11am - 8pm; Fr 10am - 9pm; Sa 10am - 9pm; Su 11am - 7pm", "brand": "J.Jill"}, "geometry": {"type": "Point", "coordinates": [-118.6046218, 34.1847081]}},
{"type": "Feature", "id": "UNnsGJNi-44QMlNBVvohAus9p1c=", "properties": {"ref": "125", "@spider": "jjill", "addr:street": "3815 State Street", "addr:city": "Santa …
```

Adds J.Jill Spider

---

locations/spiders/whidbeycoffee.py

Fixes #1928
Fixes #1969
Fixes #2446
Fixes #2792 
Fixes #3050 
Fixes #3248 
Fixes #3293 
Major overhaul of this spider, as the site structure appears to have changed dramatically
Recommended future improvements:
* Better edge case handling for Opening Hours parsing - currently not parsing this field for 2 of the 12 locations due to structural differences on the page and how the hours are represented.

Fix Whidbey Coffee spider

---

locations/spiders/lululemon.py

- Update to use new name of fields and data structure
Fixes #1910

Fix lululemon

---

locations/spiders/torchys_tacos.py

Add Torchy's tacos spider

---

locations/spiders/tjmaxx.py

Fixes #3382
Fixes #3177
Fixes #2945
Fixes #2769
Fixes #2701
Fixes #2543
Fixes #2272
Fixes #2141
Fixes #1868

Fixing TJMaxx spider

---

.github/workflows/spider-pr.yaml
locations/spiders/anytime_fitness.py

Fix anytime_fitness spider

---

locations/spiders/bmo_harris.py

Fix bmo harris spider

---

locations/spiders/insomnia_cookies.py

Fixes #3208
Fixes #3075
Fixes #2737
Fixes #2502
Fixes #2241
Fixes #2178

Rewrite the insomnia cookies spider

---

locations/spiders/blue_pearl_pet_hospital.py

Website is missing coordinates

Add spider for Blue Pearl Pet Hospital

---

locations/spiders/cornerstone_healthcare_group.py

Scraped 25 US locations. Closes #3418

Add spider for Cornerstone Healthcare Group

---

locations/spiders/jerseymikes.py

I don't see a ticket for this one, but it executed without errors and 0 locations when I ran it. Site looks like it's changed a little, so I made some small changes and it's running again and returning locations.

fixing Jersey Mikes spider

---

locations/spiders/scotiabank.py

Scrapes Scotiabank branch locations in CA.

Add spider for Scotiabank

---

locations/spiders/big_w.py

Replaces https://github.com/alltheplaces/alltheplaces/pull/1643

Add Big W spider

---

locations/spiders/wyndham.py

Fix Wyndham

---

locations/spiders/tegut_de.py

Replaces #1786 with a little bit of formatting.

Create Tegut spider

---

locations/spiders/ppgpaints.py

Finds 4953 features (For the curious: 500ish PPG retail stores, 1966 Home Depots, and various hardware stores.)

Add PPG Paints

---

locations/spiders/valero.py

Fixes #3392
Fixes #3235
Fixes #3037
Fixes #2956
Fixes #2780
Fixes #2280

Fix Valero

---

locations/spiders/rei.py

- Updates base URL
- Uses `.get()` method on dicts to ensure KeyError doesn't occur if a key is changed
- Extracts `countryCode` and `storeNumber` from different part of webpage so they're not returned as `None`

Fixes REI spider

---

locations/spiders/statefarm.py

Fix statefarm

---

locations/spiders/public_storage.py

Fix public_storage

---

locations/spiders/bluerhino.py

Yields 58592 locations across the 50 States and Puerto Rico.

Add spider for Blue Rhino

---

locations/spiders/accor.py
locations/spiders/goodstart.py
locations/spiders/guzmany_gomez.py
locations/spiders/gyg.py
locations/spiders/hungryjacks.py
locations/spiders/woolworths.py

Closes #3482 
Closes #3481
This cherry-picks in some of @boomerwv1's commits on top of master (after the AU searchable points were added) and fixes a couple whitespace issues.

Add some Aussie spiders

---

ci/run_all_spiders.sh
locations/spiders/smilebrands.py

Attempt to get latest.json and history.json working

Fix jq command

---

locations/spiders/dominos_pizza.py

Parse the sitemap better to target restaurant urls only

Handle errors better in dominos pizza

---

.github/workflows/black.yml
locations/spiders/lowes_foods.py

Add Lowes Foods spider

---

locations/spiders/chase.py
locations/spiders/lowes_foods.py

Old: 5578 features
New: 8087 features

Fix error in chase

---

locations/spiders/main_event.py

Add Main Event spider

---

locations/spiders/churchs_chicken.py

Add spider for Church's Chicken

---

locations/spiders/churchs_chicken.py
locations/spiders/jim_n_nicks_bbq.py
locations/spiders/vallarta.py

Scrapes 39 locations - no latlons unfortunately. Closes #3517

Add spider for Jim N Nicks

---

locations/spiders/mcalisters_deli.py

Add spider for McAlister's Deli

---

locations/spiders/krispy_kreme.py

Add Krispy Kreme spider

---

locations/spiders/genghis_grill.py

Add spider for Genghis Grill

---

locations/spiders/chuys.py

Add spider for Chuy's

---

locations/spiders/smashburger.py

Adding spider for smashburger

---

locations/spiders/burger_king_uk.py

Adding `addr:full`, and reducing it down to only one request.

Burger King UK improvments

---

locations/spiders/mcdonalds_uk.py

Move to the new API. And reduce the network requests, `maxResults` is the limiting factor here, not `radius`.

Fix McDonald's UK

---

locations/spiders/aldi_uk.py

Fix opening hours format
Improve addr

Improve aldi_uk

---

locations/spiders/starbucks_eu.py

Fix `addr:full`
Add `drive_through`, `payment:app` and `internet_access` extras

Improve starbucks_eu

---

locations/spiders/c_and_a.py

Add C&A Spider fixes #663

---

locations/spiders/costacoffee.py
locations/spiders/costacoffee_gb.py
locations/spiders/costacoffee_ie.py
locations/spiders/costacoffee_pl.py

If you ever want to cry, checkout the [IE API](https://www.costaireland.ie/api/cf/).

Improve Costa Coffee spiders

---

locations/spiders/davids_bridal.py

Exotic formatting in opening hours and blank pages with 200 status

Fix errors in davids bridal

---

locations/spiders/marcs.py

Add spider for Marc's

---

locations/spiders/superdrug.py

Fixes #3027, Fixes #2937, Fixes #2133

Fix Superdrug

---

locations/spiders/grimaldis_pizzeria.py

Added a crawler for Grimaldi's Pizzeria.
Fixes https://github.com/alltheplaces/alltheplaces/issues/3519
Closes #3605.

Add a crawler for Grimaldi's Pizzeria

---

locations/spiders/sullivans_steakhouse.py

Add Sullivan's Steakhouse spider

---

locations/spiders/hardees_carlsjr.py

Add spider for Hardee's and Carl's Jr

---

locations/spiders/dillards.py

Fix dillards

---

locations/spiders/tesco.py

The spider was failing due to being blocked, I think it was ip address related so this may not fix it for the weekly run. But it does work locally.
It's a shame there are no rules in [robots.txt](https://www.tesco.com/robots.txt) to tell us anything.
closes #1856 closes #2532 closes #2759 closes #3167

Improve Tesco spider

---

locations/spiders/wafflehouse.py

Fixes #3287
Fixes #3243
Fixes #3045
Fixes #2787
Fixes #2441
Fixes #1924

Checking if Waffle House is working

---

locations/spiders/giantfoodstores.py

Eastern Pennsylvania supermarkets

Add spider for Giant (Carlisle)

---

locations/spiders/argos.py

Fixes #2658, fixes #1893, fixes #1831

Fix Argos spider

---

locations/spiders/ljsilvers.py

Adds website and hours; moreover old site might have been out of date

Update Long John Silver's

---

preview/index.html

Add attribution to the preview map

---

locations/spiders/cgi_group.py

A website update had broken the spider. Unfortunately I don't think the coordinates are published any more.

Fix CGI Group

---

locations/spiders/dsw.py

Moving this to a sitemap spider fixes the page detection, and reduces the complexity.

Fix dsw Spider

---

locations/spiders/woods_coffee.py

Site change, but we can use an API now.

Fix Woods Coffee

---

locations/spiders/victoriassecret_gb.py

I went to fix the US one, but it wont let me view the site from the UK. This keeps happening, I'm going to have to get a VPN.

Add Victoria's Secret GB Spider

---

locations/spiders/baylorscottwhitehealth.py

The v2 API has stopped working between the last 2 weekly runs, also added `opening_hours`.

Fix baylorscottwhite

---

.github/workflows/spider-pr.yaml
locations/spiders/asda.py
locations/spiders/lidl_fr.py
locations/spiders/lidl_gb.py
locations/spiders/lidl_ie.py
locations/spiders/lidl_ni.py
locations/spiders/phillips_66_conoco_76.py

Also slightly improved the filters and only ask for the fields we use to shrink the response.

Standardize virtualearth pagination

---

locations/spiders/hugoboss.py

https://github.com/alltheplaces/alltheplaces/issues/3202

fix: hugo boss scraper

---

locations/spiders/crackerbarrel.py

Override the bad urls in the sitemap

Fix Cracker Barrel Spider

---

locations/spiders/e_leclerc.py

Scraped 5290 POI's
```
{
"type":"Feature",
"id":"PtkPHtV19iDDQtv2OFkZJ2iKLcA=",
"properties":{
"ref":"9793t102t1",
"store_type":"Super",
"@spider":"e_leclerc",
"addr:street_address":"4 rue des Lilas",
"addr:city":"Saint Benoit",
"addr:postcode":"97412",
"name":"E.Leclerc Express Bras-Panon",
"phone":"262.262.73.27.27",
"website":"https://e.leclerc/mag/e-leclerc-express-bras-panon",
"opening_hours":"Mo 12:00-20:00; Tu-Sa 08:30-20:00; Su 08:30-12:00",
"brand":"E.Leclerc",
"brand:wikidata":"Q1273376"
},
"geometry":{
"type":"Point",
"coordinates":[
55.67722,
-21.002447
]
}
},
```

fix: E.Leclerc

---

locations/spiders/ahern.py

ref has store name due to JSON not giving a store_id, if you have another idea to define store_id I'm open to it. Otherwise I think store name should be enough for the quantity.

fix ahern.py

---

locations/spiders/lush_cosmetics.py

Was getting blocked by robots.txt. 266 scraped.

fix: lush_cosmetics.py

---

locations/spiders/longhorn_steakhouse.py

Was getting stuck by robots.txt. Lowered download delay. Scraped 556.

fix: longhorn_steakhouse.py

---

locations/spiders/lowes.py

Was getting blocked by robots.txt, lowered download_delay.
Scraped 1729 now.

fix: lowes.py

---

locations/hours.py
locations/spiders/primark.py
locations/spiders/primark_gb.py

Primark GB has unfortunately moved to it's own site. The rest of Primark could be moved to a generic Microdata parser.

Fix Primark GB

---

locations/linked_data_parser.py
locations/pipelines.py
locations/spiders/greene_king_inns.py
locations/spiders/greene_king_pubs.py
locations/spiders/holland_and_barrett.py
locations/spiders/hsbc_uk.py

The HSBC UK website has been going through some changes lately, unfortunately usually for the worse. This currently works, but I'd bet that this it's the first of the bunch to break.
Holland & Barrett has recently moved from just ".com" tld to multiple, I think I'm missing at least 1, but it's an easy add when we find it.

Add some more Linked Data spiders

---

locations/spiders/quiktrip.py

Was getting blocked by robots.txt

fix: quiktrip.py
