alltheplaces/alltheplaces

- locations/spiders/waitrose.py
[Waitrose](http://www.waitrose.com/) is a chain of supermarkets (mostly) in the UK. Their store finder interface (usually) contains data about location, address, contact details and opening hours. It appears that some or all of these are manually entered, and so occasionally are missing or have typos.
This is the first one of these that I've attempted, so please let me know if it's outputting an acceptable set of properties in the GeoJSON, and if the `scrapy` use is idiomatic.
> Add Waitrose

- ci/run_spiders_on_travis.sh
They do the same thing as cron-triggered builds.
> Support Travis API-triggered builds

- locations/exporters.py
- Add an `id` property on the GeoJSON feature that is a base64 encoded SHA1 hash of the spider name and the item's `ref` field
- This also always casts that lat and lon to float so the spiders don't have to do it.
> GeoJSON exporter improvements

- locations/spiders/enterprise.py
Fixes #523.
Scrapes 3776 locations, although Wikipedia says they have more than 5400 locations. This spider accesses all of the locations in their site's location hierarchy (based on my own spot checks), and therefore this is likely due in part to not all of them not being listed in the location pages on their website.
> Added spider for enterprise.com

- locations/spiders/ashleyhomestore.py
Fixes #895 
608/610 locations for USA (the 2 missing (closed?) locations either return a 404 or redirect to main store locator page)
61/61 locations for CA
> Add spider for Ashley HomeStore US/Canada; closes #895

- locations/spiders/ihg_hotels.py
4595 hotels scraped.
Covers the following hotel brands:
- Holiday Inn
- Holiday Inn Express
- InterContinental
- Crowne Plaza
- Hotel Indigo
- Candlewood Suites
- Staybridge Suites
- Holiday Inn Resorts
- Regent Hotels
- Kimpton Hotels
- Holiday Inn Club Vacations
- Even Hotels
- Avid
- Hualuxe
> Add spider for IHG Hotels (Holiday Inn, etc); closes #672

- locations/spiders/manhattanbagels.py
- locations/spiders/noahsnybagels.py
Fix Bruegger's Bagels scraper (was scraping 0 items).  Also add the two remaining bagel chains under the Coffee & Bagel parent company, which all use the same store listing format.
Closes #1014
Closes #1013
> Fix Brueggers Bagels spider; add rest of brands under Coffee & Bagel empire

- locations/spiders/creditunion.py
I found a way to search by state so no zipcode search was needed. 
After I was mostly done with this spider, I looked at #486 where the PR was closed w/out merging.  IMO, the site being scraped isn't really an "aggregator", more of an "industry group" which the individual credit unions belong to.  Still not a primary source, but better than some random aggregator.  (There were other issues with that PR as well though, like it only captured branches in one zipcode).
This spider scrapes the branch locations, not ATMs.  There's 5500 branch locations.
Closes #45
> Add spider for co-op credit union branch finder

- locations/spiders/marriott.py
Closes #673 
This spider scrapes 6743 of the 7398 location count listed here: https://www.marriott.com/hotel-search.mi
The ~650 missing locations are new/upcoming locations that are not listed in the sitemap xml yet.  
Getting the links to the individual hotels via the search page relies on cookies and javascript redirects, which I don't know how to handle with scrapy... I gave up on it and went with the sitemap, which is a little out of date (but will hopefully be updated at some point).
Hotel brands included:
- Ritz-Carton Reserve
- MOXY Hotels
- Delta Hotels and Resorts
- Element Hotels
- Residence Inn
- W Hotels
- Courtyard
- Aloft Hotels
- St. Regis
- EDITION Hotels
- Marriott Vacation Club
- Ritz-Carlton
- Autograph Collection
- Tribute Portfolio
- AC Hotels
- Marriott Hotels & …
> Add spider for Marriott hotels group

- locations/spiders/costco.py
Costco removed its list of warehouses and they are now only available via lat/long searches.
Scrapes 538/538 stores in the US.
> Fix Costco spider

- locations/spiders/supercuts.py
- locations/spiders/toysrus.py
`pipenv run scrapy check` works with v1.7.1 after removing these BaseSpider imports (they were both unused)
> Remove unused BaseSpider imports

- locations/spiders/subway.py
Add spider for Subway (US) locations. Subway limits access, so a default request delay of 2 seconds is required. This makes the data acquisition very slow, but it can be run successfully from a home machine. To get worldwide locations, we will need searchable points for other countries. 
Current set-up and searchable points will pull in non-US subways near US borders.
> Subway Scraper - progress made on Issue #20

- locations/spiders/upsstore.py
#536 
Null ref id was causing about 40 stores to be flagged as duplicates
> Fix Null refs for ups store spider

- locations/spiders/victra.py
Victra is an authorized Verizon reseller so it looks like these would also be scraped by the Verizon spider.
Not sure if having multiple sources for the same locations would be useful to the project, so feel free to close this PR if not.
> Add spider for Victra mobile phone stores

- locations/spiders/albertsons.py
Fixed spider to capture street address and locality.
Also updated spider to capture Albertsons subsidiaries:
-         acme markets
-         albertsons market.
-         amigos united
-         andronicos
-         carrs
-         jewel osco
-         lucky low prices
-         market street united
-         pavilions
-         randalls
-         shaws
-         star market
-         tom thumb.com
-         united super markets
-         vons
> Fixed spider for Albertsons

- locations/spiders/7_11_ca.py
Scrapes 591 7-Eleven stores in Canada
> Add spider for 7-Eleven Canada

- locations/spiders/first_cash.py
I had to use the searchable points for this scraper which got all the stores in the US.  But 60% of first cash stores are in latin america, so this spider will need to be updated once we have searchable points for that region of the world.
> Add spider for First Cash

- locations/spiders/family_dollar.py
Around 12 records were missing due to an opening hours error (they did not have opening hours).  I added a try except to account for these
> Fix for family dollar

- locations/spiders/aunt_annes.py
Repairs the Auntie Anne's spider which was returning 0 results. Looks like the old api is no longer active/accessible. 
Uses the US searchable points to scrape 1233 US locations (including a few food trucks as well).
> Repairs Auntie Anne's spider

- locations/spiders/waterstones.py
Waterstones is a book retailer with stores in the UK, Republic of Ireland, Belgium and the Netherlands. This spider covers locations in all four countries.
> add spider for Waterstones

- locations/spiders/fedex_office.py
Scrapes 2784 Fedex Office US locations including FedEx Freight and FedEx Ship Centers. Excludes drop box locations. 
I included in the extras the location type and location code in case anyone needs to filter the output to specific locations types. There is a considerable run time ~ 13hrs. Their site doesn’t allow for the searchable points so in order to circumvent the zipcode search I had to visit each state’s list of cities which also returns nearby cities leading to duplicate filtering.
> Fedex Office

- locations/spiders/verizon.py
Previously returned 0 results. Now scrapes 5,620 verizon locations. I added extra attributes to include the business name and store type incase anyone wants to filter out 3rd party sellers.
> Repairs Verizon spider

- locations/spiders/sephora.py
One store, https://www.sephora.com/happening/stores/new-york-5th-avenue does not have store properties in the same format as all the other stores, 1 error for this.
> Fixed broken spider for Sephora

- locations/spiders/pizza_hut.py
Previous name attribute was grabbing the information from the 'nearby locations' at the bottom of the branch page instead of from the top.
> fixed name attribute for pizza_hut

- locations/spiders/sears.py
Sears has store locations available across three different sites based on the store type. Scrapes 708 stores total, excluding the stores that have recently closed e.g. the sears outlet in Des Moines is listed in the sitemap, but appears to be closed (404). The outlet stores do not include latlons.
> Adds spider for Sears

- locations/spiders/sears.py
Looks like the longitude key for the home town stores is slightly different than the latitude key. Should now include latlons for the home town stores as well.
> Add longitude key for Sears hometown stores

- locations/spiders/greyhound.py
Scrapes 1820 Greyhound locations, including a handful of locations in Mexico - the Canadian locations appear to be hosted on a separate site. 
I included an extra attribute 'location_type' to hopefully help indicate which locations are bus stops only so they can be filtered out depending on the use case. Also encountered a handful of 500 response for locations like Richmond, IN. These appear to be broken pages when viewed through the browser.
> Adds spider for Greyhound

- locations/spiders/famous_footwear.py
Scrapes 923 locations for Famous Footwear. Their sitemap doesn't appear to include individual store pages, and the search appears to be restricted to either city-state or zipcode. Used the new us_zcta file to collect the locations.
> Adds spider for Famous Footwear

- locations/spiders/bankofamerica.py
Looks like some of the CSS has changed such that this was returning zero
results. Picked some new arbitrary CSS to key off of. Also uses ld+json in
the leaf to get opening hours. [Nit] Moves parse_center to a 4 space indent.
> Update spider for Bank of America

- locations/spiders/safeway.py
- Doesn't look like the ref was unique anymore, so was dropping items
- Pulls name from meta itemprop (many were None)
- Adds wikidata
```
2020-04-07 14:52:05 [scrapy.core.scraper] ERROR: Spider error processing <GET https://local.safeway.com/safeway/ca/saint-helena/1026-hunt-ave.html> (referer: https://local.safeway.com/sitemap.xml)
File "/usr/lib/python3/dist-packages/scrapy/utils/defer.py", line 102, in iter_errback
yield next(it)
File "/usr/lib/python3/dist-packages/scrapy/core/spidermw.py", line 84, in evaluate_iterable
for r in iterable:
File "/usr/lib/python3/dist-packages/scrapy/spidermiddlewares/offsite.py", line 29, in process_spider_output
for x in result:
File "/usr/lib/python3/dist-packages/scrapy/core/spidermw.py", line 84, in …
```
> Fix safeway hours parsing, name, and ref

- locations/spiders/subway.py
Looks like the underlying file changed and removed a field. The state
column wasn't used in this spider, so dropping is a no-op.
> Remove the state column from subway spider

- locations/spiders/chevron.py
Using the 10mi centroid grid because spot testing showed that a 25 mile
radius was often enough to hit their max number of results (50).
Added log output to alert when/if this limit is hit on the 10mi grid.
Closes #556
> Add Chevron/Texaco (US) spider

- locations/spiders/bp.py
BP uses the same hosted locator service that Shell does, so this reusues the same technique as the ShellSpider
> Add BP, Amoco, and Aral Gas Stations

- locations/spiders/walmart.py
This small fix addresses an issue whereby the original XPath query was pulling the wrong `<script>`
tag to look for location data. The minor adjustment makes the XPath query roughly equivalent to
the actual data extraction regular expression.
The result of the fix is around ~4300 locations found, and is visualized below (via the preview page):
> Fix bug in Wal-mart spider

- locations/spiders/pilot_flyingj.py
The existing parser was failing on the individual store pages. This rewrites it using a CSV export available on their site. It takes quite a while to resolve the CSV download, but once it does we get all the records at once.
This also adds differentiation between the Pilot and Flying J brands for individual stations.
Alternatively, I found that appending `.json` to the end of any store page returns a nice JSON payload: https://locations.pilotflyingj.com/us/pa/mill-hall/5868-nittany-valley-drive.json
> Fix Pilot Flying J parser: rewrite using CSV export, add fuel tags

- locations/spiders/whataburger.py
This is outputting zero locations currently.
```
2020-05-15 13:23:00 [scrapy.core.scraper] DEBUG: Scraped from <200 https://locations.whataburger.com/al/birmingham/5931-trussville-crossings-pkwy.html>
{'addr_full': '5931 Trussville Crossings Pkwy',
'brand': 'Whataburger',
'brand_wikidata': 'Q376627',
'city': 'Birmingham', 
'extras': {'@spider': 'whataburger'},
'lat': 33.64291205352172,
'lon': -86.62591406508915,
'opening_hours': '24/7',
'phone': '(205) 655-4513',
'postcode': '35235',  
'ref': 'https://locations.whataburger.com/al/birmingham/5931-trussville-crossings-pkwy.html',
'state': 'AL',
'website': 'https://locations.whataburger.com/al/birmingham/5931-trussville-crossings-pkwy.html'}
2020-05-15 13:23:00 [scrapy.core.engine] INFO: Closing spider (finished)
2020-05-15 13:23:00 …
```
> Update whataburger spider to directory url, city handling

- locations/spiders/texas_roadhouse.py
This is currently returning zero locations.
```
2020-05-15 18:13:23 [scrapy.core.scraper] DEBUG: Scraped from <200 https://www.texasroadhouse.com/locations>
{'addr_full': '365 Zane Street',
'brand': 'Texas Roadhouse',
'brand_wikidata': 'Q7707945',
'city': 'Zanesville',
'country': 'USA',
'extras': {'@spider': 'texas_roadhouse', 'amenity:toilets': True},
'lat': 0,
'lon': 0,
'opening_hours': '',
'phone': '740-562-6551',
'postcode': '43701',
'ref': '/locations/ohio/',
'state': 'OH',
'website': 'https://www.texasroadhouse.com/locations/ohio/'}
2020-05-15 18:13:23 [scrapy.core.engine] INFO: Closing spider (finished)
2020-05-15 18:13:23 [scrapy.extensions.feedexport] INFO: Stored geojson feed (594 items) in: output/output/texas_roadhouse.geojson
2020-05-15 18:13:23 [scrapy.statscollectors] INFO: …
```
> Update texas_roadhouse spider to use some embedded json

- locations/spiders/fiveguys.py
This is currently returning zero locations. Looks like the data is the same, just one less level of indirection in the json.
```
2020-05-15 18:31:13 [scrapy.core.scraper] DEBUG: Scraped from <200 https://www.fiveguys.com/5gapi/stores/ByDistance?lat=45.0&lng=-90.0&distance=25000&secondaryDistance=250&lang=en&lat=45.0&lng=-90.0&dista
nce=25000&secondaryDistance=250&lang=en>
{'addr_full': 'Unit #01-32/33/34C/35',
'brand': 'Five Guys',
'brand_wikidata': 'Q1131810',
'city': 'Singapore',
'country': 'SG',
'extras': {'@spider': 'fiveguys'},
'lat': 1.2997339963912964,
'lon': 103.84444427490234,
'name': 'Plaza Singapura',
'phone': '69764385',
'postcode': '238839',
'ref': '3039',
'state': 'Singapore'}
2020-05-15 18:31:13 [scrapy.core.engine] INFO: Closing spider (finished)
2020-05-15 18:31:13 …
```
> Update fiveguys spider parsing of json

- locations/spiders/7_11.py
The most recent change to this spider switched from hitting an API endpoint to scraping data from the HTML directly. Enough things had broken in the HTML structure since then that I switched it back to hitting the API.
The API endpoint seems to be protected in two ways:
1. It requires an OAuth Bearer token to access
For anonymous sessions, this token is fetched using a static set of client credentials before first use. It's possible that this client ID / secret is rotated regularly with website deploys, but I haven't seen any evidence of that in a few days of testing.
2. It requires a set of `X-SEI-*` headers on every request.
These headers seem to be used in tandem to validate the request. The X-SEI-TRIP-ID appears to be a base64-encoded hash of info from the user agent, time zone, …
> Fix and improve US 7-Eleven spider

- locations/exporters.py
For #1517
This skips all float conversion ValueErrors by just not outputting the geometry part of the GeoJSON.
> Fix sunoco

- locations/spiders/kroger.py
Since all of Kroger's sub-brands run the same website software, the Kroger scraper can apply to all of them. 
That said, I'm leaving this as a draft PR because running this last week locally ran into rate limiting restrictions and my IP still can't access any of the Kroger store sites.
A better approach might be to use Kroger's public locations API: https://developer.kroger.com
The locations endpoint requires authentication with client credentials, which we probably wouldn't just want to publish here. Is there a mechanism in place for exposing secrets to the spider runs?
> Update Kroger spider to include subbrands and more info

- locations/spiders/panera_bread.py
I noticed some Panera Bread locations in my area were missing from the alltheplaces data. I investigated it a bit and it turned out that for cities that had more than one location, it wasn't crawling the right pages (404 error) so it just wasn't getting added to the output geojson. I wrote a small fix and tested it, I was able to get it to produce the locations in Tucson, AZ; Fort Wayne, IN; Evansville, IN, which all have more than one location. This should add around 888 new locations if the total number of locations [here](https://locations.panerabread.com/index.html) is right.
> Panera Bread - Fix parsing of cities with multiple locations

- locations/spiders/microsoft.py
Repairs the Microsoft store spider. Looks like they no longer include coordinates on their pages unfortunately which was causing the spider to error out. Added `name` and `country` properties.
> Repairs Microsoft stores spider

- locations/spiders/nike.py
Nike spider was previously returning zero results, now scrapes 1495 Nike locations internationally.
> Repairs Nike spider

- locations/spiders/target.py
JSON script body contains character entity references; switch to the
parsel selector method that replaces these.
> Fix target

- ci/run_all_spiders.sh
This adds a bit to the run_all_spiders.sh script that gets run weekly to create new issues when a spider returns errors or zero results.
- It looks for an existing github issue in this repo with the label "bug" and with the title "Spider <spider name> is broken"
- If this spider run resulted in >0 errors or =0 scraped results
- If there is an existing ticket
- If the ticket is closed, reopen it
- Post a comment that says the spider is still broken
- If there is not an existing ticket
- Create a new ticket that says the spider is broken
- Else (==0 errors and >0 scraped results)
- If there is an existing ticket
- If the ticket is open, close it
- Post a comment saying the spider is fixed
- If there is not an existing ticket
- Do nothing
> Add issue filing to run_all_spiders.sh

- locations/spiders/cookout.py
Repairs the Cook Out spider which was only returning 27 results. Now scrapes all 297 locations, using the searchable points.
> Repairs Cook Out spider

- locations/spiders/aldi_uk.py
changed spider class name to 'AldiUKSpider' and name variable to 'aldi_uk' to keep with the naming conventions of other aldi spiders
> Renamed aldi_uk.py spider class and name

- locations/spiders/verizon.py
Fixes #3394 
* Use `StoreHours` instead of `OpeningHoursSpecification` from the store JSON, because it appears to be more consistent
* Better handling around parsing `extras` because of intermittent issues with how the store JSON populates
Full local run log is attached
[verizon.log](https://github.com/alltheplaces/alltheplaces/files/7447089/verizon.log)
> Fix Verizon spider

- locations/spiders/verve_coffee_roasters.py
Adds spider for Verve Coffee Roasters. Scrapes 15/15 locations. This site unfortunately doesn't appear to include coordinates. Closes #3432
> Add spider for Verve Coffee Roasters

- locations/spiders/target_au.py
It appears that Akamai Ghost is happy to talk given:
1. A browser user-agent (and certain accept-* headers)
2. Over HTTP/2
Note that [HTTP/2 support in Scrapy is experimental][1].
[1]: https://docs.scrapy.org/en/latest/topics/settings.html?highlight=http2#download-handlers-base
I tested this successfully from GCP and AWS.
> Fix target_au

- ci/run_all_spiders.sh
If the file was empty then the jq expression wouldn't work. Correctly initialize the file.
e.g.
```
¶ </dev/null jq '. += [1]' 
¶ <<<'[]' jq -c '. += [1]' 
[1]
¶ 
```
> Fix history.json

- DATA_FORMAT.md
- locations/exporters.py
- locations/items.py
As discussed in #3579 add `street_address` which gets outputted to `addr:streetAddress`.
I've not deprecated `addr:housenumber`and `addr:street` as they are useful if the spider can reliably separate them, but for most the data I've looked at, that isn't being done.
> Add street_address field

- locations/hours.py
- locations/spiders/heronfoods.py
It can currently be done with one request, that may need to change at some point but it works fine for now.
I've also changed `add_range` from `OpeningHours` to silently reject "closed", technically OSM opening hours can be outputted as "off" instead of a time range, but I don't know enough Python to support this.
> Add Heronfoods spider

- locations/spiders/bayshore_healthcare.py
- locations/spiders/bc_pizza.py
- locations/spiders/beacon_bridge_market.py
- locations/spiders/boston_market.py
- locations/spiders/buc-ees.py
- locations/spiders/busy_beaver.py
- locations/spiders/cell-only.py
- locations/spiders/coastal.py
- locations/spiders/cookout.py
- locations/spiders/dunhams_sports.py
- locations/spiders/gattispizza.py
- locations/spiders/heronfoods.py
- locations/spiders/kbp_foods.py
- locations/spiders/krystal.py
- locations/spiders/kum_and_go.py
- locations/spiders/mcdonalds_gt.py
- locations/spiders/mcdonalds_sg.py
- locations/spiders/mobilelink.py
- locations/spiders/premierurgentcare.py
- locations/spiders/smilebrands.py
- locations/spiders/speedee.py
- locations/spiders/steak_n_shake.py
- locations/spiders/superamerica.py
- locations/spiders/sweet_tomatoes.py
- locations/spiders/viva_chicken.py
Untested edit of any spiders accessing "wp-admin/admin-ajax.php" to ignore robots.txt as WordPress blocks them.
> Ignore Robots.txt on WordPress API spiders

- locations/spiders/albertsons.py
- locations/spiders/exxonmobil.py
- locations/spiders/phillips_66_conoco_76.py
[Q4712282](https://www.wikidata.org/wiki/Q4712282) -> [Q2831861](https://www.wikidata.org/wiki/Q2831861) is a pure redirect
[Q4781944](https://www.wikidata.org/wiki/Q4781944) -> [Q109675651](https://www.wikidata.org/wiki/Q109675651) is former Exxon to current Exxon by ExxonMobil
[Q1126518](https://www.wikidata.org/wiki/Q1126518) -> [Q214763](https://www.wikidata.org/wiki/Q214763) I'm not 100% on this one but its Conoco Inc. to ConocoPhillips
> Update Wikidata ids

- locations/hours.py
- locations/spiders/marks_and_spencer.py
So, M&S returns "24:00" sometimes, Python doesn't like it so I'm changing it to "00:00", or "23:59". However "24:00" is allowed in [OSM opening_hours](https://wiki.openstreetmap.org/wiki/Key:opening_hours), so I'm converting it back when we turn convert it.
> Fix M&S Spider

- locations/spiders/worldcat.py
Retry a few times when response is empty json array, and determine the number of pages in a smarter way.
> Fix worldcat

- locations/spiders/western_union.py
This one is slow to start as it starts up and immediately enqueues half
a million scrapy Request objects in memory. Supplying
`scrapy crawl western_union -s JOBDIR=western_union-job/`
allows it to flush the Request objects to disk until they are needed and
reduces the amount of heap it needs. Might not be an issue on a machine
with sufficient RAM.
The site is happy to serve 800 pages/min, completes in under 8 hours,
produces 393778 items.
> Add spider for Western Union

- locations/settings.py
Several sites seem to respond to generic terms like curl, Python-urllib,
Scrapy with 403 errors, apparently as a cheap "I've written a robot!"
deterrent.
Still identify ourselves clearly by default and include the version
number of scrapy. We can of course use a generic user-agent for sites
which require it.
Appears to fix walmart, at least.
> Remove 'Scrapy' from user agent string

- locations/spiders/walmart.py
Move to CrawlSpider. The sitemap has bad urls and old stores that soft 404.
```patch
+https://www.walmart.com/store/3081/sacramento-ca
-https://www.walmart.com/store/3081-sacramento-ca
```
I don't know if this will work without being banned, I ran it with a 2.5 delay and got 1,384 stores before being blocked.
> Fix Walmart

- locations/linked_data_parser.py
- locations/spiders/costcutter_gb.py
- tests/test_ld_parser.py
So costcutter_gb uses ld+json but lists all the brands it stocks rather than itself, it does so in a way causing the library parser to error (exception). You see how I have subverted this is the spider code.
However, @Cj-Malone it does beg the question as to why we would decode the brand data? The wikidata code / brand name that by convention we put in the spider is likely the correct brand reference. My reading of the code paths is that picking up the brand from ld+json will stop it being copied from the spider "item_attributes".
> Add costcutter_gb (1472 stores)

- locations/dict_parser.py
- locations/spiders/poundland.py
- locations/spiders/pret_a_manger.py
- tests/test_dict_parser.py
The idea here is that the vast majority of the keys are the same. Just like the Linked Data parser, it isn't perfect, there will often have to be fixes before or after in spider code. I've written Poundland and Pret spiders while writing the `DictParser`. They both have clean up, Poundland has a better `ref` then it's `id`, and Pret has bad street addresses.
The spider code also handled extra data + opening hours. I don't think it's feasible to have a generic opening hours parser.
Fixes #3571, Fixes #3716
> Add generic parser

- locations/microdata_parser.py
- locations/spiders/fifththirdbank.py
- locations/spiders/greatclips.py
- locations/spiders/northwest_bank.py
- locations/spiders/sunglass_hut.py
To address:
Converts the HTML5 Microdata directly to JSON-LD in a similar format to (nearly) all of the JSON-LD seen in the wild.
Steps of this process:
1. Run the algorithm to extract the microdata given at <https://html.spec.whatwg.org/multipage/microdata.html>, _not_ the one at <https://www.w3.org/TR/microdata-rdf/>. [Note]
2. Convert the HTML Microdata JSON output to a JSON-LD format.
While the algorithm to extract the microdata is implemented more or less to spec, this is entirely ad-hoc. If the root item seems to be in the schema.org namespace, produce a correct-looking output.
Flatten lists of property values if there is only one element.
Duplicated string values are removed; this is a side effect of what would happen if you actually ran this through an RDF processor.
3. Take the …
> Add a Microdata parser.

- locations/linked_data_parser.py
- tests/test_ld_parser.py
As noted we sometimes get `item["phone"] == " 123456789"`, this PR adds `LinkedDataParser.get_clean` which will trim string values.
I've also added `get_case_insensitive` for the address keys.
> Trim Linked Data values

- ci/run_all_spiders.sh
Follow up to #3827.
`bmo_harris`, `moneygram` and `western_union` are hitting the 4h limit.
> Change timeout to 8 hours

- locations/spiders/walmart.py
This moves the Walmart Spider to `__NEXT_DATA__` data since the old `window.__WML_REDUX_INITIAL_STATE__` is gone.
GH will fail because CrawlSpider will crawl the directory before doing the store pages. I've not ran it against the whole of the US, but it works on Alabama.
> Fix Walmart Spider

- locations/spiders/lundsandbyerlys.py
Set `addr_full` to null because DictParser sets it with the street address in this case.
Trim unused attributes from URL.
Convert close of "00:00" to "24:00".
> Lunds & Byerlys edits

- locations/spiders/webuyanycar_gb.py
- locations/spiders/welcome.py
- locations/spiders/wickes_gb.py
- locations/spiders/wrenkitchens_gb.py
- locations/structured_data_spider.py
`StructuredDataSpider` can be inherited by any spider, including `SitemapSpider` and `CrawlSpider`s.
It gives us `parse_sd` which does the normal Microdata/LinkedData stuff, using a `wanted_types` attribute. It also does some smarts with getting refs from the url (only when none is set from source), it will try to grab a regex group from `rules` or `sitemap_rules`. If not it falls back to the full url. It can also try to pull phone and email addresses from the response.
There is also `inspect_item` callback where we can do clean up in spider.
> Add StructuredDataSpider

- locations/dict_parser.py
So `set(key)` was adding treating key as a char array, adding each letter on there own. We want it as a string.
> Fix DictParser key variations

- locations/spiders/first_cash.py
The spider was using the `brand` field which wasn't normalized. Each brand had the store ID attached to the brand which in my opinion shouldn't be the case.
> fix: First Cash brand names

- locations/spiders/autonation.py
Auto Nation scraper was setting as a brand what brands the dealership was selling, which isn't the brand of the store locator.
> fix: AutoNation brand incorrect

- locations/commands/insights.py
- locations/commands/nsi.py
- locations/name_suggestion_index.py
- tests/test_name_suggestion_index.py
Add tests. Make NSI into a lazy loaded singleton. nsi scrapy command will now output any matching NSI data gainst a successful Q-code query i.e. loactions sets and suggested tags.
For example, Greggs in the UK:
$ pipenv run scrapy nsi --code Q3403981
"Greggs", "Q3403981"
-> https://www.wikidata.org/wiki/Q3403981
-> https://www.wikidata.org/wiki/Special:EntityData/Q3403981.json
-> bakery chain in the United Kingdom
-> https://www.greggs.co.uk/
-> item_attributes = {"brand": "Greggs", "brand_wikidata": "Q3403981"}
**-> {'displayName': 'Greggs', 'id': 'greggs-45095e', 'locationSet': {'include': ['gb']}, 'tags': {'amenity': 'fast_food', 'brand': 'Greggs', 'brand:wikidata': 'Q3403981', 'cuisine': 'sandwich;bakery', 'name': 'Greggs', 'takeaway': 'yes'}}**
McDonald's is a bit more fun:
$ pipenv …
> Slightly extend, and add tests for NSI client

- locations/settings.py
- locations/spiders/western_union.py
Just to be polite to the servers, can still be lowered in spiders, or increased if needed.
Western Union is already hitting the 8 hour limit, so I've explicitly lowered it's limit. Other spiders that are at or near the 8 hour limit already have delays.
> Add a default download delay

- README.md
- locations/linked_data_parser.py
- locations/structured_data_spider.py
- tests/test_ld_parser.py
Fixes #4062
I couldn't expand `inspect_item` to take an extra argument without breaking existing spiders, so I renamed it to `post_process_item(self, item, response, ld_data, **kwargs)` the `**kwargs` will hopefully allow us to add new arguments in the future.
I've also added `pre_process_data(self, ld_data, **kwargs)` where we can clean up source data before it's passed to the LinkedDataParser.
If wanted `wanted_types` contains an array, it will require all of them to be considered a match.
Default `wanted_types` have also been added. Obviously it can still be overridden in spider.
> Enhance StructuredDataSpider

- locations/spiders/family_dollar.py
Treat 301 as a retryable error; rewrite using ld json.
Still gives up on certain pages but avoids losing entire subdirectories.
'item_scraped_count': 8120,
'retry/count': 396,
'retry/max_reached': 70,
> Fix family_dollar

- ci/fetch_all_stats.sh
- locations/pipelines.py
- locations/settings.py
- locations/spiders/bank_of_scotland_gb.py
- locations/spiders/chase.py
So this started out as me trying to add categories from NSI, and hopefully we'll end up there. But I think we need some stats first.
- `atp/nsi/brand_missing` for times when NSI is missing an entry with the Wikidata ID
- `atp/nsi/perfect_match` for when there is a single NSI match for the Wikidata ID
- `atp/nsi/multiple_hits` for when there are multiple NSI matches with the Wikidata ID
You can see the commit log for some ideas I've had to filter the multiple NSI matches, but ultimately I want to see the stats and identify the specific spiders before I go to far there. This is the TODO on line 229.
Removing line 236 would apply the NSI tags to the output, not overriding any tags set by the spider, applied to the item or extras depending. I'd be happy for us to start doing this right away, …
> Add stats for NSI matching

- locations/spiders/starbucks.py
The id url redirects to this, but it's still better for us to have the canonical url. + black messes it up
> Add slug to starbucks url

- locations/spiders/us_army_national_guard.py
- locations/spiders/xfinity.py
As discussed in #4146, US territories aren't included in `GeonamesCache().get_us_states()`. This fixes the xfinity spider that I degraded with the last PR, hopefully in future people will use this `US_TERRITORIES`, and not define a new list.
> Readd US_TERRITORIES to xfinity spider

- locations/commands/insights.py
- locations/country_utils.py
- locations/pipelines.py
- tests/test_country_utils.py
- tests/test_pipeline_country_code_cleanup.py
CJ's recent commit to try and standardise country code fields to ISO2 alpha as best we can has been extended further with code that will set the country code from our spider naming convention if appropriate and also as a final resort the item website URL.
As part of this CountryUtils has been pulled out of the insights.py command file and put in "core" ATP library code where it should be.
This means we will get more POIs with country codes which means that the NSI categorisation pipeline code should pick up more items.
Also means that going forward people in many cases will not need to set the country code field "by hand" in the spider.
> extend country code clean up pipeline

- docs/SPIDER_NAMING.md
The top level README will get too unwieldy for some of the things we should be saying (we have quite a few things to say). I think we should break things down into little vignettes that we can tie together in the main README or wherever.
The files will serve as reference but also single links that can be pasted into a PR to help the reviewer get a point across in a particular area. Who likes typing? :-)
> some doc about spider naming convention

- locations/commands/sitemap.py
A complementary twin to the "sd" command. A quick command to see if scrapy can read any sitemap index support that may be present e.g.
$ pipenv run scrapy sitemap https://smashburger.com https://smashburger.com/sitemap_index.xml
https://smashburger.com/post-sitemap.xml
https://smashburger.com/page-sitemap.xml
https://smashburger.com/store-sitemap.xml
https://smashburger.com/give_forms-sitemap.xml
https://smashburger.com/promo-sitemap.xml
https://smashburger.com/item_type-sitemap.xml
can be followed with:
$ pipenv run scrapy sitemap https://smashburger.com/store-sitemap.xml --pages https://smashburger.com/locations/us/co/glendale/1120-s-colorado-blvd/ https://smashburger.com/locations/us/co/lafayette/2755-dagny-way/ https://smashburger.com/locations/us/co/wheatridge/3356-youngfield-st/ …
> a command to poke a website robots.txt / sitemap.xml

- locations/commands/sd.py
Quickly run a minimum structured data spider against a web page or file.
**$ pipenv run scrapy sd https://www.nisalocally.co.uk/stores/city-of-edinburgh/edinburgh/77-warrender-park-rd**
{'city': 'Edinburgh',
'country': 'GB',
'email': None,
'image': 'https://www.nisalocally.co.uk/stores/permanent-b0b701/assets/images/nisa-logo-blue.88689a6b.svg',
'lat': '55.938520097370755',
'lon': '-3.1976409867417033',
'name': 'Margiotta Ltd 77 Warrender Park Rd',
'opening_hours': 'Mo-Su 07:00-23:00',
'phone': '0131 229 8228',
'postcode': 'EH9 1ES',
'ref': 'https://www.nisalocally.co.uk/stores/#13429806',
'state': None,
'street_address': '77 Warrender Park Rd Midlothian',
'website': 'https://www.nisalocally.co.uk/stores/city-of-edinburgh/edinburgh/77-warrender-park-rd'}
Has a few more options like …
> Add "sd" command to decode a web page or file for structured data

- docs/SPIDER_NAMING.md
- docs/WIKIDATA.md
- locations/spiders/mcdonalds_baltics.py
- locations/spiders/mcdonalds_pt.py
Cleaned up a little bit my previous SPIDER_NAMING commit. In particular made the linked spiders as best as they could be given that people might be looking at them!
The new document page is a first stab at the subject and has a fuller description of the "scrapy nsi" command than is in the top level README.
> add a docs page about wikidata/nsi/atp

- DATA_FORMAT.md
- locations/exporters.py
- locations/items.py
- locations/pipelines.py
I can't really envision us setting the `nsi_id` in spider to a real value, but we we'll have the option. However I can foresee us wanting to skip `ApplyNSICategoriesPipeline`, now we can `nsi_id=0` and it'll be skipped.
> Document nsi_id and skip ApplyNSICategoriesPipeline when it's set

- locations/spiders/naptan_gb.py
So NaPTAN is a gov dataset of public transit in England, Wales and Scotland. I don't know if it's in scope for ATP but OSM UK is considering a Quarterly Project using the data, so I wrote it for that, and here seems like a decent home for it.
BTW `HTTPCACHE_ENABLED` and `HTTPCACHE_EXPIRATION_SECS` were useful while testing this, I don't know if it makes sense to be set in `settings.py`, or for me to continue to use it locally. I don't think it'd be affect the weeklies as there is no persistence between them.
> Add NaPTAN spider

- locations/pipelines.py
I added `if key is "extras":` which adds a warning at the start of every spider run.
state checks were duplicated when street_address checks were added.
> Pipeline fixes

- locations/spiders/jdsports_gb.py
It's broken in the weekly, but worked fine locally, presumably they block AWS ips. `download_delay` increased to the default 1 seconds, but still don't really expect this to work in the weeklies.
> Convert JDSports GB Spider StructuredDataSpider

- locations/name_suggestion_index.py
Apple -> Q312
Current version: 
```
nsi.iter_nsi("Q312")
empty
```
Fix:
```
nsi.iter_nsi("Q312")
[
{
"displayName": "Apple Inc.",
"id": "appleinc-918717",
"locationSet": {
"include": [
"001"
]
},
"tags": {
"operator": "Apple Inc.",
"operator:wikidata": "Q312",
"telecom": "data_center"
}
}
]
```
> fix: iter_nsi

- locations/spiders/decathlon.py
Add additional hosts for Decathlon. The added hosts follow the same contract as those already present.
There are more hosts (e.g. sk, se, cn), but they use a different mechanism to locate the store. So, I didn't include those since required code changes are much more substantial.
> Add additional Decathlon hosts

- locations/pipelines.py
- locations/spiders/designer_shoe_warehouse.py
- locations/spiders/erieinsurance.py
- locations/spiders/footlocker.py
- locations/spiders/homebase_gb_ie.py
- locations/spiders/jll.py
- locations/spiders/nandos.py
- locations/spiders/northern_california_breweries.py
A couple issues, with the auto extraction. We could have a spider in 2 regions, called "homebase_gb_ie", we shouldn't guess in pipeline. And an issue where multiple countries of POI are served from one tld, eg where GB and IE use the same ".co.uk" domain. Erroneously applying GB to IE POIs.
My solution is `skip_auto_cc = True` on the spider.
We also have a little issue because ".com" isn't mapped to "US", I agree with this decision, we'd have loads of false positives if we did, but we have to handle it in spider sometimes. After this PR I think everything is working as expected.
```bash
$ ./check_stats.sh 2022-11-12-13-31-47 atp/field/country/from_website_url
2022-11-12-13-31-47/bestbuy-ca.json: 164
2022-11-12-13-31-47/casino.json: 419
2022-11-12-13-31-47/dsw.json: 25 …
```
> Add a spider attribute to skip auto cc extraction

- locations/spiders/gbfs.py
```python
{'atp/field/brand_wikidata/missing': 78059,
'atp/field/city/missing': 78059,
'atp/field/email/missing': 78059,
'atp/field/image/missing': 78059,
'atp/field/opening_hours/missing': 78059,
'atp/field/phone/missing': 78059,
'atp/field/postcode/missing': 73370,
'atp/field/state/missing': 78059,
'atp/field/street_address/missing': 52605,
'atp/field/twitter/missing': 78059,
'atp/field/website/invalid': 37,
'downloader/request_bytes': 649027,
'downloader/request_count': 1410,
'downloader/request_method_count/GET': 1410,
'downloader/response_bytes': 7527562,
'downloader/response_count': 1410,
'downloader/response_status_count/200': 1322,
'downloader/response_status_count/302': 2, …
```
> Add GBFS Spider

- DATA_FORMAT.md
- locations/exporters.py
- locations/pipelines.py
Some spiders are currently setting ref as hashes, random or even index order (eg BunningsSpider). Lets just embrace that some sources don't provide ids. `no_refs = True` on the spider allow it and skip de dup for them.
> Allow spiders to not set refs

- ci/run_all_spiders.sh
- docs/WEEKLY_RUN.md
The size of the compressed dump is about the same: 146M vs. 147M with the current dump, which isn’t surprising given that both formats use the same compression algorithm. But other than with tar, the files in a ZIP archive can be accessed separately without having to read the entire stream. This property of ZIP allows processing the weekly dump files in parallel with multiple threads/processes/machines.
Closes https://github.com/alltheplaces/alltheplaces/issues/4227.
> Change format of weekly dump files to `*.zip` instead of `*.tar.gz`

- locations/spiders/e_leclerc.py
- locations/spiders/mcdonalds_fr.py
- locations/storefinders/woosmap.py
I started the day off thinking that Woosmap was third party data. But it's not, it's first party data on a hosted store finder. And I found a better end point that we don't have to mess around with lat/lons or grids.
I want everyones opinions on some kind of base spiders, specifically for third party store finders. @jleedev @iandees @mjoe999 You can checkout the specific implementation, but I just rushed it, it's the idea that really want your opinions on.
> Add base Woosmap Spider

- locations/microdata_parser.py
- tests/test_microdata_parser.py
Add a test case that was triggering this and a reasonable enough parse.
(Observation: The validator.schema.org parser creates an event with the same location property twice.)
> Implement the "continue" part of "there is a microdata error; continue".

- .github/workflows/spider-pr.yaml
See https://github.com/alltheplaces/alltheplaces/issues/4269 for the problem this is trying to fix. To test this change, probably the easiest way will be to merge this PR, then send a dummy PR on a spider, and check if the caching works as expected without generating warnings.
> Update spider-pr to use actions/cache@v3

- locations/spiders/deichmann.py
```python
{'atp/field/brand_wikidata/missing': 2799,
'atp/field/opening_hours/invalid': 3,
'atp/field/state/missing': 2799,
'atp/field/twitter/missing': 2799,
'downloader/request_bytes': 1126498,
'downloader/request_count': 2803,
'downloader/request_method_count/GET': 2803,
'downloader/response_bytes': 31939535,
'downloader/response_count': 2803,
'downloader/response_status_count/200': 2801,
'downloader/response_status_count/404': 2,
'elapsed_time_seconds': 40.609692,
'finish_time': datetime.datetime(2022, 12, 5, 16, 21, 2, 172588),
'httpcache/hit': 2803, …
```
> Fix Deichmann Spider

- locations/spiders/nationwide_gb.py
Fixes #4283
Kinda fixes #4282
```python
{'atp/field/email/missing': 607,
'atp/field/lon/invalid': 4,
'atp/field/state/missing': 607,
'atp/field/twitter/missing': 607,
'atp/nsi/category_match': 607,
'downloader/request_bytes': 473888,
'downloader/request_count': 1202,
'downloader/request_method_count/GET': 1202,
'downloader/response_bytes': 36243710,
'downloader/response_count': 1202,
'downloader/response_status_count/200': 1202,
'dupefilter/filtered': 7873,
'elapsed_time_seconds': 42.093066,
'finish_time': datetime.datetime(2022, 12, 6, 18, 29, 38, 807869),
'httpcache/hit': 1202,
'httpcompression/response_bytes': 235722408,
'httpcompression/response_count': 1201, …
```
> Improve Nationwide spider

- locations/spiders/joules.py
```python
{'atp/field/city/missing': 82,
'atp/field/country/from_reverse_geocoding': 133,
'atp/field/email/missing': 133,
'atp/field/image/missing': 33,
'atp/field/twitter/missing': 133,
'atp/nsi/perfect_match': 133,
'downloader/request_bytes': 164929,
'downloader/request_count': 171,
'downloader/request_method_count/GET': 171,
'downloader/response_bytes': 7886121,
'downloader/response_count': 171,
'downloader/response_status_count/200': 136,
'downloader/response_status_count/404': 34,
'dupefilter/filtered': 7,
'elapsed_time_seconds': 9.800239,
'finish_time': datetime.datetime(2022, 12, 8, 16, 36, 10, 297169), …
```
> Add Joules Spider

- locations/categories.py
- locations/pipelines.py
- locations/spiders/nike.py
My change last week crashes when `include` isn't a string array. Nike was the only spider effected.
> Fix ApplyNSICategoriesPipeline crash

- .github/workflows/spider-pr.yaml
Don't use the `actions/cache` workflow, let `actions/setup-python` do it.
> Let setup-python do pipenv caching

- locations/structured_data_spider.py
Following on from #4338, data consumers may be more trusting of Structured Data as it's essentially published data. While they may be more scared of data obtained from an API. that may be closer to private data.
> Add source to StructuredDataSpider output

- locations/spiders/whsmith_gb.py
```python
{'atp/category/shop/newsagent': 760,
'atp/field/email/missing': 760,
'atp/field/image/missing': 760,
'atp/field/lon/invalid': 7,
'atp/field/twitter/missing': 760,
'atp/nsi/category_match': 760,
'downloader/request_bytes': 2631,
'downloader/response_bytes': 70629,
'downloader/response_count': 6,
'elapsed_time_seconds': 2.990674,
'finish_time': datetime.datetime(2023, 1, 3, 15, 26, 19, 268701),
'httpcache/hit': 6,
'httpcompression/response_bytes': …
```
> Fix WHSmith Spider

- locations/items.py
- locations/pipelines.py
As mentioned in https://github.com/alltheplaces/alltheplaces/pull/4548#discussion_r1060390390 always having extras will make some things simpler, and remove us having to do the check every time.
I've also added a check in `CheckItemPropertiesPipeline` for `OpeningHours` and convert it the OSM string, and skipped the format check since the output of `as_opening_hours` should always be valid. I think we could prepopulate this too, like `extras`, but I've not checked to see if it'd backfire anywhere.
> Always populate extras

- locations/google_url.py
- locations/pipelines.py
- locations/spiders/vue_cinemas.py
- tests/test_google_url.py
- tests/test_pipeline_extract_gb_postcode.py
```python
{'atp/category/amenity/cinema': 91,
'atp/field/city/missing': 91,
'atp/field/country/from_reverse_geocoding': 90,
'atp/field/email/missing': 91,
'atp/field/image/missing': 91,
'atp/field/opening_hours/missing': 91,
'atp/field/phone/missing': 91,
'atp/field/state/missing': 91,
'atp/field/street_address/missing': 91,
'atp/field/twitter/missing': 91,
'atp/nsi/perfect_match': 91,
'downloader/request_bytes': 93473,
'downloader/request_count': 93,
'downloader/request_method_count/GET': 93,
'downloader/response_bytes': 1704503,
'downloader/response_count': 93,
'downloader/response_status_count/200': 93,
'elapsed_time_seconds': 2.576302, …
```
> Fix Vue Spider

- locations/spiders/blooms_the_chemist_au.py
- locations/storefinders/storepoint.py
Fixes #4585
```python
{'atp/category/amenity/pharmacy': 112,
'atp/category/multiple': 112,
'atp/field/city/missing': 112,
'atp/field/country/from_spider_name': 112,
'atp/field/image/missing': 112,
'atp/field/postcode/missing': 112,
'atp/field/state/missing': 112,
'atp/field/street_address/missing': 112,
'atp/field/twitter/missing': 112,
'atp/nsi/perfect_match': 112,
'downloader/request_bytes': 339,
'downloader/response_bytes': 11817,
'elapsed_time_seconds': 2.875097,
'finish_time': datetime.datetime(2023, 1, …
```
> Add Blooms The Chemist Spider

- locations/spiders/dunelm_gb.py
Missing email address in source data causes store["email"] to give an error. Email addresses already captured by DictParser.parse(store) so we can remove that line anyway.
> Fix Dunelm spider crash (closes #4632)

- locations/categories.py
- locations/spiders/goldsgym.py
- locations/spiders/rsg_group.py
- locations/storefinders/woosmap.py
```python
{'atp/category/leisure/fitness_centre': 344,
'atp/field/brand/missing': 9,
'atp/field/brand_wikidata/missing': 9,
'atp/field/country/missing': 4,
'atp/field/email/missing': 344,
'atp/field/image/missing': 344,
'atp/field/lat/missing': 344,
'atp/field/lon/missing': 344,
'atp/field/phone/missing': 45,
'atp/field/state/missing': 344,
'atp/field/twitter/missing': 344,
'atp/nsi/brand_missing': 59,
'atp/nsi/perfect_match': 276,
'downloader/request_bytes': 1662,
'downloader/response_bytes': 254777, …
```
> Add RSG Spider

- locations/hours.py
- tests/test_opening_hours.py
There had already been a unit test for sorting multiple opening hours on the same day, but the implementation had not actually sorted the hours. Before this change, the results thus got formatted in pseudo-random order depending on the value of Python’s built-in hash function. Accidentally, the existing test case happened to give the expected sorting order.
> Sort same-day opening hours

- locations/pipelines.py
eg "Mo 08:00-12:00,13:00-17:30"
Then after the next weekly we should get better stats on `atp/field/opening_hours/invalid` so we know which ones need fixing.
> Improve opening_hours regex to allow for multiple time ranges

- ci/restore_history.py
- ci/run_all_spiders.sh
The history.json file is getting the wrong size for the output because `du` is reporting in blocks of kilobytes. Switch that to bytes to report apparent size.
> Have du report in bytes instead of kb

- locations/spiders/att.py
```python
{'atp/category/shop/mobile_phone': 259,
'atp/field/email/missing': 259,
'atp/field/opening_hours/missing': 259,
'atp/field/twitter/missing': 259,
'atp/nsi/perfect_match': 259,
'downloader/request_bytes': 304021,
'downloader/request_count': 263,
'downloader/request_method_count/GET': 263,
'downloader/response_bytes': 29939897,
'downloader/response_count': 263,
'downloader/response_status_count/200': 263,
'elapsed_time_seconds': 64.083954,
'finish_time': datetime.datetime(2023, 1, 17, 17, 38, 28, 349369),
'httpcache/firsthand': 40,
'httpcache/hit': 223,
'httpcache/miss': 40,
'httpcache/store': 40,
'httpcompression/response_bytes': 431070350,
'httpcompression/response_count': 263,
'item_scraped_count': 259,
'log_count/DEBUG': 532,
'log_count/INFO': 10, …
```
> Fix AT&T Spider

- locations/categories.py
- locations/spiders/goodstart.py
Fixing the Goodstart spider.
Some remarks: 
- The changes to the website removed the original ref. The new version has an `id` field that is taken by the `DictParser`, but it's different compared to older scraped results from https://data.alltheplaces.xyz/runs/2022-12-10-13-32-28/output/goodstart.geojson. Does it make sense to try to recreate them?
- The JSON result contains a suburb, but not a city. PR #4615 seems to state that suburb is not used in our model. What should I do with this?
- A center can have different services: kindergarten-preschool, nursery, toddler, ... I used the `amenity=childcare` since I can find this the most on OSM. It might make sense to go more granular, but I guess I can't add multiple amenities to a single place.
> Fix Goodstart spider

- locations/spiders/shurgard.py
```python
{'atp/brand/Shurgard': 257,
'atp/brand_wikidata/Q3482670': 257,
'atp/category/missing': 257,
'atp/field/city/missing': 216,
'atp/field/country/from_reverse_geocoding': 257,
'atp/field/email/missing': 257,
'atp/field/image/missing': 257,
'atp/field/opening_hours/missing': 257,
'atp/field/state/missing': 257,
'atp/field/twitter/missing': 257,
'atp/nsi/brand_missing': 257,
'downloader/request_bytes': 437734,
'downloader/request_count': 342,
'downloader/request_method_count/GET': 342,
'downloader/response_bytes': 16345343,
'downloader/response_count': 342,
'downloader/response_status_count/200': 342,
'elapsed_time_seconds': 14.327777,
'finish_time': datetime.datetime(2023, 1, 20, 10, 27, 27, …
```
> Add Shurgard Spider

- locations/spiders/jumbo_ar.py
There's no wikidata entry. Jumbo Argentina is, in fact, a brand from [Cencosud](https://www.wikidata.org/wiki/Q1053372) and not from the Dutch supermarket chain [Jumbo](https://www.wikidata.org/wiki/Q2262314). However, that's not present in Wikidata. Should this be added to Wikidata and NSI?
> Fix Jumbo Argentina spider

- locations/exporters.py
geojson.io complains when using a "properties" field on a FeatureCollection. The spec is a bit hard to parse but I think geojson.io is right. The GeoJSONL exporter already uses "dataset_attributes", so this unifies them.
> Rename FeatureCollection properties to dataset_attributes

- locations/dict_parser.py
- locations/spiders/footgear_za.py
```python
{'atp/brand/Footgear': 221,
'atp/brand_wikidata/Q116290280': 221,
'atp/category/missing': 221,
'atp/field/email/missing': 221,
'atp/field/image/missing': 221,
'atp/field/postcode/missing': 73,
'atp/field/twitter/missing': 221,
'atp/nsi/brand_missing': 221,
'downloader/request_bytes': 660,
'downloader/response_bytes': 19477,
'elapsed_time_seconds': 4.551088,
'finish_time': datetime.datetime(2023, 1, 23, 10, 8, 37, 739683),
'httpcompression/response_bytes': 203239,
'item_scraped_count': 221, …
```
> Add Footgear ZA spider

- locations/linked_data_parser.py
- locations/spiders/la_halle_fr.py
- tests/test_ld_parser.py
Didn't run to completion, but:
```python
{'atp/brand/La Halle': 74,
'atp/brand_wikidata/Q100728296': 74,
'atp/category/shop/clothes': 74,
'atp/field/city/missing': 74,
'atp/field/email/missing': 74,
'atp/field/twitter/missing': 74,
'atp/nsi/perfect_match': 74,
'downloader/request_bytes': 73388,
'downloader/request_count': 94,
'downloader/request_method_count/GET': 94,
'downloader/response_bytes': 2864543,
'downloader/response_count': 94,
'downloader/response_status_count/200': 94,
'elapsed_time_seconds': 25.190468,
'finish_time': datetime.datetime(2023, 1, 24, 19, 44, 25, 303478),
'httpcache/firsthand': 19,
'httpcache/hit': 75,
'httpcache/miss': 19,
'httpcache/store': 19, …
```
> Add La Halle FR Spider

- locations/spiders/foschini.py
- locations/spiders/tops_at_spar.py
```python
{'atp/brand/Foschini': 352,
'atp/brand_wikidata/Q116391780': 352,
'atp/category/missing': 352,
'atp/field/country/from_reverse_geocoding': 352,
'atp/field/email/missing': 352,
'atp/field/image/missing': 352,
'atp/field/phone/invalid': 54,
'atp/field/state/missing': 352,
'atp/field/twitter/missing': 352,
'atp/field/website/missing': 352,
'atp/nsi/brand_missing': 352,
'downloader/request_bytes': 3391,
'downloader/response_bytes': 142202,
'downloader/response_status_count/302': 2,
'elapsed_time_seconds': 12.076063, …
```
> Add Foschini Spider

- locations/dict_parser.py
- locations/spiders/otr_au.py
```python
{'atp/brand/OTR': 165,
'atp/brand_wikidata/Q116394019': 165,
'atp/category/amenity/fuel': 35,
'atp/category/multiple': 35,
'atp/category/shop/convenience': 130,
'atp/field/country/from_spider_name': 165,
'atp/field/email/missing': 165,
'atp/field/image/missing': 165,
'atp/field/phone/missing': 165,
'atp/nsi/brand_missing': 165,
'downloader/request_bytes': 693,
'downloader/response_bytes': 215821,
'elapsed_time_seconds': 4.029237,
'finish_time': …
```
> Add OTR Spider

- locations/spiders/truworths.py
```python
{'atp/brand/Identity': 238,
'atp/brand/Loads of Living': 8,
'atp/brand/Office London': 18,
'atp/brand/Truworths': 443,
'atp/brand_wikidata/Q116378109': 238,
'atp/brand_wikidata/Q116418894': 18,
'atp/brand_wikidata/Q116418933': 8,
'atp/brand_wikidata/Q24233998': 443,
'atp/category/shop/clothes': 708,
'atp/field/brand/missing': 1,
'atp/field/brand_wikidata/missing': 1,
'atp/field/country/from_reverse_geocoding': 687,
'atp/field/country/missing': 21,
'atp/field/email/missing': 708,
'atp/field/image/missing': 708,
'atp/field/lat/missing': 21,
'atp/field/lon/missing': 21,
'atp/field/opening_hours/missing': 708,
'atp/field/phone/invalid': 37,
'atp/field/state/missing': 708,
'atp/field/twitter/missing': 708,
'atp/field/website/missing': 708, …
```
> Add Truworths Spider

- locations/spiders/brico_io_it.py
```python
{'atp/brand/Brico Io': 113,
'atp/brand_wikidata/Q15965705': 113,
'atp/category/missing': 113,
'atp/field/image/missing': 113,
'atp/field/twitter/missing': 113,
'atp/nsi/brand_missing': 113,
'downloader/response_bytes': 16992,
'elapsed_time_seconds': 2.699473,
'finish_time': datetime.datetime(2023, 1, 25, 14, 40, 13, 456695),
'httpcompression/response_bytes': 212496,
'item_scraped_count': 113,
'log_count/DEBUG': …
```
> Add Brico io IT Spider

- locations/dict_parser.py
- locations/spiders/inver.py
```python
{'atp/brand/Inver': 94,
'atp/brand_wikidata/Q112579016': 94,
'atp/category/amenity/fuel': 94,
'atp/category/multiple': 9,
'atp/field/city/missing': 94,
'atp/field/email/missing': 94,
'atp/field/opening_hours/missing': 94,
'atp/field/phone/missing': 94,
'atp/field/postcode/missing': 82,
'atp/field/street_address/missing': 94,
'atp/field/website/missing': 94,
'atp/nsi/brand_missing': 94,
'downloader/request_bytes': 993,
'downloader/response_bytes': 10340,
'elapsed_time_seconds': 1.871383,
'finish_time': datetime.datetime(2023, 1, 27, 15, 31, …
```
> Add Inver Spider

- locations/dict_parser.py
- locations/pipelines.py
- locations/spiders/aroma_rs.py
```python
{'atp/brand/Арома': 63,
'atp/brand_wikidata/Q116446961': 63,
'atp/category/missing': 63,
'atp/field/email/missing': 63,
'atp/field/image/missing': 63,
'atp/field/opening_hours/missing': 63,
'atp/field/phone/missing': 63,
'atp/field/street_address/missing': 63,
'atp/field/twitter/missing': 63,
'atp/field/website/missing': 63,
'atp/nsi/brand_missing': 63,
'downloader/request_bytes': 609,
'downloader/response_bytes': 17475,
'elapsed_time_seconds': 1.59354,
'finish_time': datetime.datetime(2023, 1, 27, 14, 24, 34, 831454), …
```
> Add Aroma RS Spider

- locations/spiders/odeon_gb.py
Fixes #4696
```python
{'atp/brand/Odeon': 110,
'atp/brand_wikidata/Q6127470': 110,
'atp/category/amenity/cinema': 110,
'atp/field/city/missing': 110,
'atp/field/country/from_spider_name': 110,
'atp/field/email/missing': 110,
'atp/field/image/missing': 110,
'atp/field/opening_hours/missing': 110,
'atp/field/phone/missing': 110,
'atp/field/state/missing': 110,
'atp/field/street_address/missing': 110,
'atp/field/twitter/missing': 110,
'atp/nsi/perfect_match': 110,
'downloader/request_bytes': 771,
'downloader/response_bytes': 27347,
'elapsed_time_seconds': 2.54261, …
```
> Add Odeon GB Spider

- locations/spiders/petrol.py
https://github.com/osmlab/name-suggestion-index/pull/7725
```python
{'atp/brand/Crodux': 93,
'atp/brand/Petrol': 503,
'atp/brand_wikidata/Q174824': 503,
'atp/brand_wikidata/Q62274622': 93,
'atp/category/amenity/fuel': 93,
'atp/category/missing': 503,
'atp/field/email/missing': 596,
'atp/field/image/missing': 596,
'atp/field/phone/missing': 596,
'atp/field/state/missing': 596,
'atp/field/street_address/missing': 596,
'atp/field/twitter/missing': 596,
'atp/field/website/missing': 596,
'atp/nsi/brand_missing': 503,
'downloader/request_bytes': 4458,
'downloader/response_bytes': 1562314,
'downloader/response_status_count/200': 8, …
```
> Add Petrol Spider

- locations/geo.py
- locations/spiders/via313.py
Amend code in two files to allow ATP to be run with earlier versions of Python (specifically Python 3.8 in Ubuntu 20.04) for greater portability. These changes shouldn't affect any functionality.
> Python 3.8

- locations/spiders/krefel_be.py
```python
{'atp/brand/Krëfel': 75,
'atp/brand_wikidata/Q3200093': 75,
'atp/category/shop/electronics': 75,
'atp/field/country/from_spider_name': 75,
'atp/field/email/missing': 75,
'atp/field/state/missing': 75,
'atp/field/street_address/missing': 75,
'atp/nsi/perfect_match': 75,
'downloader/request_bytes': 637,
'downloader/response_bytes': 11563,
'elapsed_time_seconds': 1.206226,
'finish_time': datetime.datetime(2023, 2, 6, …
```
> Add Krefel BE Spider

- Dockerfile
The weekly run failed this past weekend because the script path in the Docker image changed.
> Fix CMD path in the Dockerfile

- locations/spiders/decathlon.py
These were being matched as [vending machines](https://nsi.guide/index.html?t=brands&k=amenity&v=vending_machine&tt=Q509349#decathlonradtourretter-a242c5)
> Add Decathlon category

- locations/spiders/shell.py
It was being blocked at 0.5 seconds. I ran this until 10k pois with no errors, we should expect 41,534 pois.
This and the BP spider share a lot of code. We should make a geo.me base spider at some point, however currently BP only uses v1 of the API, while Shell can use both. Once they both use v2 (or another geo.me spider comes along) I'll write a base spider.
> Fix Shell spider

- locations/spiders/prada.py
Note that this spider currently extracts 373 stores, but the store finder on the website indicates only 368 stores exist. There could be a few recently closed stores that are being extracted from the sitemap? It isn't clear yet why the difference exists and if it were due to recently closed stores, how these stores could be enumerated and removed from the sites extracted.
The street_address field extracted from linked data is very messy. Sometimes it really is street_address, sometimes it is full_addr, but most of the time it is neither and is a street_address and state combined in a myriad of creative ways. Many street_address fields are completely in other languages such as Simplified Chinese or Korean.
Closes issue #4721
> Add Prada (Global) (373 stores)

- locations/spiders/jackinthebox.py
There's an error in the JSON (trailing `}`). `chompjs` does the trick.
> Fix Jack in the Box spider

- locations/spiders/edwardjones.py
Changes in the website removed the `lat/lon` from the pages. There's some workaround to contact an API (`https://www.edwardjones.com/api/v3/financial-advisor/results?q=" + postcode + "&distance=50&distance_unit=mi&page=1&matchblock=&searchtype=2`), but it's quite cumbersome to get it right and not get blocked.
I'll mark the PR as a draft and think further on it.
> Fix Edward Jones spider

- locations/spiders/ace_hardware.py
KiboSpider reduces the number of requests from 4413 to 5 for ace_hardware and significantly simplifies ace_hardware to just a single start URL for the Kibo Storefront Location API URI of ace_hardware.
> ace_hardware: rewrite to use KiboSpider

- locations/storefinders/kibo.py
Extract the city field.
Fix paging logic so that an extra request to the API for 0 remaining records does not occur.
shippingOriginContact fields not guaranteed to exist.
> KiboSpider: minor bugfixes

- locations/spiders/bunnings.py
The Bunnings API used for locating stores requires a guest/anonymous OAUTH login process to be completed, and an Authorization Bearer header to be sent when calling the API.
The spider has largely been rewritten using DictParser, fixing numerous incorrect field values in the process.
The rewritten spider also extracts New Zealand Bunnings stores.
Currently 351 stores are returned by the API, with 41 being in New Zealand and the remainder in Australia.
> bunnings: fix spider and include New Zealand stores

- locations/spiders/specsavers_gb.py
This spider previously used the Specsavers' sitemap at https://www.specsavers.co.uk/sitemap.xml but by comparing the data with OSM, I noticed a number of stores were missing from the sitemap. Specsavers also has a 'Full Store List' web page at https://www.specsavers.co.uk/stores/full-store-list which appears to be more complete.
I'm not sure if how I've coded it is the best way to do it, but when run locally the new spider appears to work, and returns 913 stores, compared to 838 from the current spider at the last ATP run.
This seems to be a big improvement. However, there's still at least one store that's missing from the Full Store List page: https://www.specsavers.co.uk/stores/addlestone .
> Switch from using Sitemap to 'Full Store List' web page for Specsavers

- locations/exporters.py
- tests/test_exporters.py
Weirdly not outputting `geometry` is against the spec, it wants `"geometry": null` when there isn't any.
> Always output geometry

- preview/index.html
It turns out that creating hundreds of thousands of images in a web page isn't the best rendering technique.
Incorporate Supercluster (https://github.com/mapbox/supercluster) when the number of features exceeds a threshold (500) to allow interactively browsing a gigantic collection of points. The cluster styling is per their sample code (after the Leaflet MarkerCluster style).
Other approaches that worked, but not as well:
- The Leaflet MarkerCluster (https://github.com/Leaflet/Leaflet.markercluster) includes nice touches like animating a circle of unclustered markers when they overlap, but it was significantly slower.
- It is actually possible to get the map to render without clustering, by setting { preferCanvas: true }, and asking L.geoJson to create an L.circleMarker for point …
> Speed up preview map; modernize code

- locations/spiders/spar_gb.py
Some searches with no results would give us an empty array, others would give unexpected data. Moving to a all stores API over the postcode search removes that issue, doesn't give scrapy duplicates and is more efficient.
> Fix Spar crashes and add extra details

- locations/spiders/papa_johns_gb.py
Correct store page regex, update deprecated `inspect_item` function, remove broken position extraction (Google URL no longer contains lat/lon).
Unfortunately, it seems that the store pages no longer provide a lat/lon for each store. It might be possible to add some geocoding based on the address and postcode, but for now I haven't done so.
Run locally, this new version returns 479 stores.
> Fix broken papa_johns_gb spider

- locations/spiders/papa_johns_gb.py
e.g. https://www.papajohns.co.uk/stores/st.ives-cambridge
> Correct regex for additional characters in store URLs

- locations/spiders/kfc_au.py
746 open stores from 759 stores parsed and 2 dummy stores. Note that the 13 non-open stores appear to be stores that are temporarily closed (for renovations or otherwise) or under construction and not yet trading and these stores when parsed return a HTTP 400 error.
> Add KFC (AU) (746 stores)

- locations/hours.py
- tests/test_opening_hours.py
add_ranges_from_string is added as a parser function designed to help translate from opening hours provided as human readable text in a fuzzy format.
This function is intended to add opening hours ranges based on the following type of ranges that may be found in source data:
1. Monday-Wednesday: 5pm - 7pm
2. Monday-Wednesday 08:00-14:00
3. Monday to Tuesday: 15:00:01 to 16:35
4. Thurs 2PM-6:30PM
5.  Fri    9am  -  11am
6. Weekends: 8:00 AM to 6:00 PM
7. Monday to Thursday 7am to 7pm, Friday 7am to 10pm, Weekends CLOSED
This function works with a source that may mix and match from the type of examples listed above. For example, if a source uses both 12h and 24h times to describe opening hours.
This function does not currently support extraction of multiple opening hours on the same day of …
> OpeningHours: introduce add_ranges_from_string

- locations/middlewares/cdnstats.py
- locations/settings.py
Count cloudflare and akamai requests and there status codes. The stats after the next weekly would be interesting, I wonder if we have any akamai results, the broken lowes spider gets nothing. For some sites Cloudflare lets us through, others we use Playwright, we probably have a ton of spiders failing just because of it or maybe even failing half way though. Anyway, it'll be interesting.
> Add CDNStatsMiddleware

- locations/spiders/eurochange_gb.py
The spider runs locally for me, returning 188 "Eurochange" branches and 3 "NM Money" branches.
However, I can't figure out why the StructuredDataSpider isn't picking up the opening hours though, as they're present in the embedded ld+json. If anyone has any thoughts...
I don't know if it's the right thing to do or not, but I've removed the Facebook and image field as they were just generic brand links.
> Add Spider for Eurochange (UK Bureau de Change)

- locations/spiders/bunnings.py
E-mail field appears to be optional, so use .get() for e-mail (and phone) fields instead of just assuming these fields are always populated.
> bunnings: fix spider

- locations/spiders/fantastic_furniture_au.py
A public holiday this week in Australia has demonstrated that opening hours for Fantastic Furniture are sometimes changed to align with public holidays due in the next week. In this case, Friday is "CLOSED", so the spider needs to be able to accomodate these temporary changes to hours. Unfortunately there is no information available to determine whether hours are normal or holiday hours, so the opening hours for this spider will seemingly fluctuate regularly.
> fantastic_furniture_au: fix spider

- locations/spiders/jax_tyres_and_auto_au.py
With upcoming public holidays in Australia this week, this spider is broken due to unhandled day names such as "Good Friday". Unfortunately for such weeks with a public holiday, there is no place on the website showing what the usual hours would have been. Thus the hours for this spider will constantly fluctuate depending on whether the given week has a public holiday.
> jax_tyres_and_auto_au: fix spider

- locations/spiders/enterprise.py
Returns 7306 results from across the world.
Note that other API queries can extract opening hours, the website and other details of each location however this would result in 7306 additional queries, hence is not yet implemented in this updated spider.
> enterprise: fix spider

- .github/workflows/docker-publish.yml
With all the action on the repo, the image repository is filling up fast. Instead of scaling with the number of commits, I want it to scale with time, so I'm adjusting the image build to happen every 6 hours instead of every commit.
> Build the docker image every 6 hours instead of on every merge

- locations/spiders/family_dollar_us.py
This spider should have been rewritten as part of commit 1bf9caadafbe3d27f47006beaa6164dd9b90cba6 but was accidentally forgotton to be rewritten.
> family_dollar_us: fix spider

- locations/pipelines/country_code_clean_up.py
- locations/pipelines/state_clean_up.py
By default, reverse_geocoder uses multiple threads since we only ever ask for 1 POI at a time, it wastes a lot of CPU time setting them up.
```python
from scrapy.spiders import Spider
from locations.items import Feature
class Test2Spider(Spider):
name = "test2"
start_urls = ["data:,"]
def parse(self, response, **kwargs):
for i in range(10000):
yield Feature(ref=str(i), lat=45, lon=-90)
```
mode=2 (default) took 721 seconds
mode=1 took 2.734139 seconds
> Switch to reverse_geocoder single threaded mode

- locations/spiders/supercheap_auto.py
This spider was returning errors for each NZ location due to a few problems in handling of opening hours.
OpeningHours.add_ranges_from_string() is now used instead to simplify this spider.
> supercheap_auto: fix opening hours for NZ locations

- .github/workflows/pytest-pr.yaml
- locations/pipelines/country_code_clean_up.py
Some of the geocoding tests are failing because coords were ints.
I'll check why the tests didn't trigger on the last PR tomorrow, or Monday.
> Ensure coords aren't turned to ints

- locations/dict_parser.py
- locations/spiders/cloud_9_smoke_shop_australia_au.py
- locations/spiders/just_watches_in.py
- locations/spiders/mr_liquor_au.py
- locations/storefinders/metizsoft.py
Metizsoft is a store locator plugin for Shopify that appears to be widely used amongst smaller brands to allow look-up of stockists at independent or other retail chain stores. However, Metizsoft store locator is also used by some small brands for locating their brick and mortar stores.
> Add Metizsoft store finder and sample brands

- locations/spiders/7_11_us.py
- locations/spiders/aaa.py
- locations/spiders/apcoa_be.py
- locations/spiders/ashley_furniture.py
- locations/spiders/ashley_homestore.py
- locations/spiders/batteriesplus.py
- locations/spiders/baylorscottwhitehealth.py
- locations/spiders/bestone_gb.py
- locations/spiders/designer_shoe_warehouse.py
- locations/spiders/fuddruckers.py
- locations/spiders/holland_and_barrett.py
- locations/spiders/iron_mountain.py
- locations/spiders/lululemon.py
- locations/spiders/mcdonalds_baltics.py
- locations/spiders/mexx.py
- locations/spiders/new_look_gb.py
- locations/spiders/papa_johns_gb.py
- locations/spiders/potbelly_sandwichshop.py
- locations/spiders/premier_gb.py
- locations/spiders/redlion.py
- locations/spiders/scotiabank.py
- locations/spiders/specsavers_gb.py
- locations/spiders/sullivans_steakhouse.py
- locations/spiders/tacobell.py
- locations/spiders/thebodyshop.py
- locations/spiders/toolstation.py
- locations/spiders/whidbey_coffee.py
- locations/spiders/wyndham.py
A few general clean ups around download_delay. Should not be too contentious. We should think about some of the other non-default values  perhaps.
> download_delay of 1s is the default, remove from spiders where that is the value set

- locations/spiders/waterstones.py
The existing implementation crawls through a paginated list starting from https://www.waterstones.com/bookshops/viewall . However, a coding error by Waterstones means only 15 pages are linked, ending at https://www.waterstones.com/bookshops/viewall?page=15 . But in fact there's a hidden page 16: https://www.waterstones.com/bookshops/viewall?page=16 that contains the last few stores at the end of the alphabet.
This means the existing spider misses around 20 stores. This PR should fix this, by instead polling the 26 alphabetical pages.
> Update Waterstones spider to use alphabetical directory

- locations/spiders/pret_a_manger.py
The API used in the Pret a Manger scraper https://api1.pret.com/v1/shops lists 603 stores, but the spider is currently only returning 181 of them.
The problem is that an error that occurs when a time of "0:59" is given to `oh.add_range(DAYS[i], rule[0], rule[1], "%I:%M%p")`. There's already an attempt in the code to convert "0:XX" to "12:XX" to work with the %I time format, but this only deals with some specific cases. This PR aims to convert all instances of "0:XX" to "12:XX".
The new code avoids the error. When run locally, I now get all 603 stores returned (596 pret + 7 veggie pret).
> More generic handling of 0:XX opening-hours times in pret_a_manger spider

- locations/spiders/circle_k.py
Use a new Circle API which returns global results. The last page which can be requested is
https://www.circlek.com/stores_master.php?lat=0&lng=0&page=959 and with 10 locations returned per page, and page 0 being the first, that equals a count of 9597 locations returned by this API.
Previously before this spider broke, approximately 6600 results were returned from the USA only.
> circle_k: fix spider and make international

- locations/items.py
- locations/pipelines/check_item_properties.py
- locations/pipelines/country_code_clean_up.py
- locations/pipelines/state_clean_up.py
- tests/test_bad_coords.py
So, currently we are not validating `geometry` at all. This puts Points through the same validation as raw `lat`/`lon`.
Currently we complain (`atp/field/lon/invalid`) about anything within +-0.1 of 0, but still output it, unless lat or lon == 0.0. This complains (`atp/geometry/null_island`) and discards coords of anything within `3.0, 3.0, -3.0, -3.0`.
> Validate geometry the same as lat/lon

- locations/categories.py
- locations/dict_parser.py
- locations/spiders/caffe_nero.py
- locations/spiders/caffe_nero_gb.py
* caffe_nero_gb has been split from caffe_nero because GB stores now use a different store locator method from other countries.
* caffe_nero updated to ignore GB stores.
* caffe_nero_gb now has greatly expanded extra tags for toilets, etc as the new locator method has more data available.
* Fix an error with apply_yes_no that would always apply Extras.WIFI even if disabled/not available for a location.
* Add additional Extras to categories.py.
> caffe_nero: fix and split caffe_nero_gb which needs new spider

- locations/spiders/denizbank.py
```
{'atp/brand/Denizbank': 3817,
'atp/brand_wikidata/Q1115064': 3817,
'atp/category/amenity/atm': 3068,
'atp/category/amenity/bank': 749,
'atp/field/city/missing': 3817,
'atp/field/country/from_spider_name': 3817,
'atp/field/email/missing': 3817,
'atp/field/image/missing': 3817,
'atp/field/lat/missing': 86,
'atp/field/lon/missing': 86,
'atp/field/opening_hours/missing': 3817,
'atp/field/phone/invalid': 18,
'atp/field/phone/missing': 3068,
'atp/field/postcode/missing': 3817,
'atp/field/state/missing': 3817,
'atp/field/street_address/missing': 3817,
'atp/field/twitter/missing': 3817,
'atp/field/website/missing': 3817,
'atp/nsi/category_match': 3817,
'downloader/request_bytes': 913,
'downloader/response_bytes': 314854, …
```
> Add Denizbank (TR) (3817 locations)

- locations/spiders/wrenkitchens_gb.py
* Allow hyphens in store URLs (underscores already included in \w). This adds three previously missing stores, e.g. https://www.wrenkitchens.com/showrooms/tunbridge-wells
* Upgrade from deprecated `inspect_item`
* Use final URL for store websites (some store links from the `/showrooms/` page redirect to the final URL)
> Tweaks to Wren Kitchens GB Spider

- locations/spiders/tacotote.py
The "-old" added in the URL doesn't mean it is out of date. All location pages now officially have an "-old" suffix.
> tacotote: fix spider

- locations/spiders/americas_kids_us.py
"atp/brand/America's Kids": 11,
'atp/brand/Kids World': 1,
'atp/brand/Lazarus': 1,
'atp/brand/Young Land': 1,
'atp/brand/Young World': 6,
> Add America's Kids (US) (20 stores)

- locations/spiders/biedronka_pl.py
```python
{'atp/brand/Biedronka': 3419,
'atp/brand_wikidata/Q857182': 3419,
'atp/category/shop/supermarket': 3419,
'atp/field/country/from_spider_name': 3419,
'atp/field/email/missing': 3419,
'atp/field/image/missing': 3419,
'atp/field/lat/missing': 494,
'atp/field/lon/missing': 494,
'atp/field/opening_hours/missing': 61,
'atp/field/phone/missing': 3419,
'atp/field/state/missing': 3419,
'atp/field/street_address/missing': 3419,
'atp/field/twitter/missing': 3419,
'atp/nsi/perfect_match': 3419,
'downloader/request_bytes': 654132,
'downloader/request_count': 1358,
'downloader/request_method_count/GET': 1358,
'downloader/response_bytes': 7480817,
'downloader/response_count': 1358,
'downloader/response_status_count/200': 1358,
'dupefilter/filtered': 3,
'elapsed_time_seconds': 5.957987, …
```
> Add Biedronka PL Spider (3,419 locations)

- locations/spiders/red_rooster_au.py
Salesforce data within store list data no longer exists to obtain a store number from. Fall back to using the last 4 digits of the store e-mail address as the store number.
> red_rooster_au: fix spider

- locations/spiders/rooms_to_go_us.py
'atp/brand/Rooms To Go': 114,
'atp/brand/Rooms to Go Kids': 86,
> Add Rooms To Go brands (US) (200 stores)

- Dockerfile
The Docker image build fails with:
```
File "/home/ubuntu/.pyenv/versions/3.11.4/bin/pipenv", line 8, in <module>
sys.exit(cli())
^^^^^
File "/home/ubuntu/.pyenv/versions/3.11.4/lib/python3.11/site-packages/pipenv/vendor/click/core.py", line 1130, in __call__
return self.main(*args, **kwargs)
^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/home/ubuntu/.pyenv/versions/3.11.4/lib/python3.11/site-packages/pipenv/cli/options.py", line 58, in main
return super().main(*args, **kwargs, windows_expand_args=False)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/home/ubuntu/.pyenv/versions/3.11.4/lib/python3.11/site-packages/pipenv/vendor/click/core.py", line 1055, in main
rv = self.invoke(ctx)
^^^^^^^^^^^^^^^^
File …
```
> Pin pipenv to 2023.6.26

- locations/spiders/lenta_ru.py
Stats:
```python
{'atp/brand/Лента': 794,
'atp/brand_wikidata/Q4258608': 794,
'atp/category/shop/pet': 14,
'atp/category/shop/supermarket': 780,
'atp/field/country/from_spider_name': 794,
'atp/field/email/missing': 794,
'atp/field/image/missing': 794,
'atp/field/phone/missing': 794,
'atp/field/postcode/missing': 794,
'atp/field/state/missing': 794,
'atp/field/street_address/missing': 794,
'atp/field/twitter/missing': 794,
'atp/field/website/missing': 794,
'atp/nsi/perfect_match': 794,
'downloader/exception_type_count/twisted.web._newclient.ResponseNeverReceived': 1,
'downloader/request_bytes': 634,
'downloader/response_bytes': 250172, …
```
> Add Lenta (RU) (794 locations)

- locations/spiders/moneygram.py
Some Polish post office locations had incorrect data and were being reported by MoneyGram as being located outside of Poland. Ignore these locations as they're incorrect.
Fixes #5510
> moneygram: remove incorrect Polish post office locations

- locations/spiders/bp_pulse_gb.py
Hi, this is my first PR here.
I had to "pipenv install exceptiongroup".
Fix to category for BP Pulse GB. 
NSI has 2 categories, namely amenity=charging_station and man_made=charge_point, so explicitly set to resolve.
WAS
{'atp/brand/bp pulse': 3235,
'atp/brand_wikidata/Q39057719': 3235,
'atp/category/missing': 3235,
'atp/field/city/missing': 3235,
'atp/field/email/missing': 3235,
'atp/field/image/missing': 3235,
'atp/field/opening_hours/missing': 3235,
'atp/field/phone/missing': 3235,
'atp/field/postcode/missing': 3235,
'atp/field/state/missing': 3235,
'atp/field/street_address/missing': 3235,
'atp/field/twitter/missing': 3235,
'atp/field/website/missing': 3235,
'atp/nsi/match_failed': 3235,
...
NOW:
{'atp/brand/bp pulse': 3235,
'atp/brand_wikidata/Q39057719': 3235, …
> Fix Category for BP Pulse GB

- locations/spiders/chargy_gb.py
char.gy has 2 NSI entries, namely amenity=charging_station and man_made=charge_point. Set category to resolve this.
WAS
{'atp/brand/char.gy': 2836,
'atp/brand_wikidata/Q113465698': 2836,
'atp/category/missing': 2836,
'atp/field/city/missing': 2836,
'atp/field/email/missing': 2836,
'atp/field/image/missing': 2836,
'atp/field/opening_hours/missing': 2836,
'atp/field/phone/missing': 2836,
'atp/field/state/missing': 2836,
'atp/field/twitter/missing': 2836,
'atp/nsi/match_failed': 2836,
...
NOW:
{'atp/brand/char.gy': 2836,
'atp/brand_wikidata/Q113465698': 2836,
'atp/category/amenity/charging_station': 2836,
'atp/field/city/missing': 2836,
'atp/field/email/missing': 2836,
'atp/field/image/missing': 2836,
'atp/field/opening_hours/missing': 2836,
'atp/field/phone/missing': 2836, …
> Fix category for Chargy GB

- locations/spiders/charge_place_scotland_gb.py
ChargePlace Scotland has 2 NSI entries, namely amenity=charging_station and man_made=charge_point. Explicity set category to resolve this.
WAS
{'atp/brand/ChargePlace Scotland': 2635,
'atp/brand_wikidata/Q105359316': 2635,
'atp/category/missing': 2635,
'atp/field/email/missing': 2635,
'atp/field/image/missing': 2381,
'atp/field/opening_hours/missing': 2635,
'atp/field/phone/missing': 2635,
'atp/field/state/missing': 2635,
'atp/field/street_address/missing': 2635,
'atp/field/twitter/missing': 2635,
'atp/nsi/match_failed': 2635,
...
NOW:
{'atp/brand/ChargePlace Scotland': 2635,
'atp/brand_wikidata/Q105359316': 2635,
'atp/category/amenity/charging_station': 2635,
'atp/field/email/missing': 2635,
'atp/field/image/missing': 2381,
'atp/field/opening_hours/missing': 2635, …
> Fix category for ChargePlace Scotland GB

- locations/spiders/beev_gb.py
Resolve multiple NSI entries by setting category.
WAS:
{'atp/brand/Be.EV': 1817,
'atp/brand_wikidata/Q118263083': 1817,
'atp/category/missing': 1817,
'atp/field/email/missing': 1817,
'atp/field/image/missing': 1817,
'atp/field/phone/missing': 1817,
'atp/field/state/missing': 1817,
'atp/field/twitter/missing': 1817,
'atp/field/website/missing': 1817,
'atp/nsi/match_failed': 1817,
...
NOW:
{'atp/brand/Be.EV': 1817,
'atp/brand_wikidata/Q118263083': 1817,
'atp/category/amenity/charging_station': 1817,
'atp/field/email/missing': 1817,
'atp/field/image/missing': 1817,
'atp/field/phone/missing': 1817, …
> Fix category for Beev GB

- locations/spiders/action.py
Whilst a GraphQL API still exists, it has changed and no longer provides in the list of all locations the required IETF language tag (e.g. fr-FR) for each location. Some language variants of the Action website use a much simpler API that returns the same information previously captured, just without the fuss of having to reverse geocode coordinates and map countries to IETF language tags. Language variants of the Action website which use a GraphQL based store locator are broken because whilst they show a marker for a location in every country, details of locations in countries not using the same IETF language tag as the store locator language variant will not load.
> action: fix spider

- ci/run_all_spiders.sh
Currently, the start time of a build is saved in history.json. Also saving the end time of a build allows for statistics to be more easily captured for how long it is taking to complete each complete build. With this data, it may then be possible to see the effect of efforts to optimise spider crawls to reduce overall build times.
> ci/run_all_spiders.sh: save end time of each build to history.json

- locations/spiders/jefferson_university_hospital.py
This spider was returning an error from a page that is missing and redirects back to a location finder page, where the spider is unable to extract required data. Ignoring redirects removes this single error.
> jefferson_university_hospital: fix spider to remove an error

- locations/microdata_parser.py
- locations/spiders/albertsons.py
* microdata_parser was erroring on incorrect URLs in Albertson's store webpages which contain e.g.: a href="https://www.[c_bannerURLName].com/pharmacy/covid-19.html" (example: https://local.pharmacy.acmemarkets.com/pa/west-chester/907-paoli-pike.html)
* Facebook and Twitter fields are not store specific, so ignore them.
> albertsons: fix errors in spider

- locations/spiders/zabka_pl.py
Polish Convenience store brand.
I have extracted the API endpoint and key from the store's app: https://play.google.com/store/apps/details?id=pl.zabka.apb2c&hl=en_US
It is better than the one that can be found on the website, because it returns all the shops in one huge JSON along with all the data for each shop. The website API would need to make a HTTP request for each of the 9000 shops separately. 
I have added opening hours for Monday-Saturday, but due to Polish law Sundays are considered non-working days, but the shops can be open if the owner or the owner's family member is working there. This means that each franchisee sets the opening hours for each specific Sunday, and it ends up in the `"nonTradingDays"` field:
```json
"nonTradingDays": [
{
"date": "2023-07-16",
"openTime": …
```
> Add Żabka spider (~9506 stores)

- locations/spiders/maggianos_little_italy.py
Apologies, I messed up the last pull request (#5581) and opened a new one.  All fixes should be resolved @iandees and @davidhicks 
Added addr_full and street_address
Return just opening_hours instead of the textual representation generated through opening_hours.as_opening_hours().
No need to check if hours:, you can safety return a 'blank' OpeningHours object here.
> Add Spider for Maggianos Little Italy and Fixes

- locations/spiders/gov_mot_gb.py
So a little to unpack here.
MOT is a test on cars every year. Garages that do the test register with the government.
This is a gov dataset, not first party. So I've prefixed it with `gov_`. I've not thought about this much, so there may be a better solution.
I've added `brand:wikidata` for the bigger chains
```
127 FORMULA ONE AUTOCENTRES LIMITED
141 ARNOLD CLARK
189 ATS EUROMASTER LIMITED
506 HALFORDS AUTOCENTRE
530 KWIK FIT
```
But it's the smaller/independent ones that are quite interesting, we wouldn't usually see that data and its license is compatible with OSM.
> Add GB car repair spider

- locations/spiders/caffe_nero_gb.py
There are 2 entries in NSI, namely Caffe Nero and Caffe Nero Express, so the category is not being set.
Set the category to amenity=cafe and cuisine=coffee_shop rather than shop=coffee (a shop selling coffee products)
Before:
{'atp/brand/Caffe Nero': 597,
'atp/brand/Nero Express': 33,
'atp/brand_wikidata/Q675808': 630,
'atp/category/missing': 630,
'atp/field/city/missing': 630,
'atp/field/country/from_spider_name': 630,
'atp/field/email/missing': 630,
'atp/field/image/missing': 630,
'atp/field/state/missing': 630,
'atp/field/street_address/missing': 630,
'atp/field/twitter/missing': 630,
'atp/field/website/missing': 630,
'atp/nsi/match_failed': 630,
After: …
> Set category for Caffe Nero GB

- locations/spiders/nisalocal_gb.py
There are two NSI entries, namely "Nisa" and "Nisa Local" so the NSI match is failing and we are not picking up the category. They are all convenience stores so category set.
Before:
{'atp/brand/Nisa': 1298,
'atp/brand_wikidata/Q16999069': 1298,
'atp/category/missing': 1298,
'atp/cdn/cloudflare/response_count': 248,
'atp/cdn/cloudflare/response_status_count/200': 248,
'atp/field/email/missing': 1298,
'atp/field/opening_hours/missing': 96,
'atp/field/phone/missing': 182,
'atp/field/state/missing': 1298,
'atp/field/twitter/invalid': 1298,
'atp/nsi/match_failed': 1298,
After:
{'atp/brand/Nisa': 1298,
'atp/brand_wikidata/Q16999069': 1298,
'atp/category/shop/convenience': 1298,
'atp/cdn/cloudflare/response_count': 248,
'atp/cdn/cloudflare/response_status_count/200': 248, …
> Set category for Nisa Local

- locations/commands/sd.py
- locations/linked_data_parser.py
- locations/pipelines/check_item_properties.py
- locations/pipelines/closed.py
- locations/spiders/fedex.py
Test me with `scrapy sd https://local.fedex.com/pl-pl/zyrardow/wawek`.
The microdata contains nested itemprop=name, which gets translated as an array of names. Teach LinkedDataParser to use the first name when a list is found.
When an item contains an array of names, an exception is thrown. Teach ClosePipeline to guard against this so that it does not cause items to be lost.
The `scrapy sd` command prints out the found item, then a message saying "failed to decode structured data", which does not explain anything. Change its log level from disabled to warning so that exceptions are not swallowed but it otherwise remains terse.
Sort the stats output from `scrapy sd`.
Fix isinstance() call in CheckItemProperties.
> Fix FedEx.

- locations/linked_data_parser.py
Commit 530406b4d3d1a29198799e285969bd066da22e9a introduced the concept of "enhanced field extraction" from linked data. For example, a "hotel" type may have a star rating field that can be extracted, but this field is not applicable to some other types.
It is possible for some locations to have multiple types (e.g. banfield_pet_hospital). Commit 530406b4d3d1a29198799e285969bd066da22e9a was not able to handle multiple types, causing spiders such as banfield_pet_hospital to break.
With this fix, the "enhanced field extraction" is now applied for each and every type for linked data, e.g. "localbusiness" and "hotel" would trigger the enhanced field extraction twice, once for "localbusiness" and once for "hotel".
> linked_data_parser: fix enhanced field extraction

- locations/items.py
Makes the logged output less confusing as we have moved these fields elsewhere, not accidentally populated them with nothing.
> Delete lat/lon instead of None

- locations/spiders/accor.py
- locations/spiders/carrefour_fr.py
- locations/spiders/cora_fr.py
- locations/spiders/e_leclerc.py
- locations/spiders/leroy_merlin.py
- locations/spiders/mcdonalds_fr.py
- locations/spiders/rsg_group.py
- locations/spiders/total_energies.py
- locations/spiders/united_colors_of_benetton.py
- locations/storefinders/woosmap.py
Woosmap always requires an "Origin" HTTP header to be provided. Update the store finder to require an "origin" attribute be supplied, that is then sent to the Woosmap API along with the API key for the brand.
Woosmap additionally appears to allow opening hours to be specified as "default" e.g. hours applying across all days of the week. Allow this "default" hours specification method to be used.
> storefinders/woosmap: add origin as a required class attribute

- locations/spiders/sainsburys.py
At least one location did not have the "other_name" field populated, meaning that the name of the store was being extracted as a None value, causing a fatal error due to invalid handling of the None value. The number of stores returned by this spider has therefore been incorrect, as results have been truncated.
This change will only use the "other_name" field if it contains a value, otherwise, the abbreviated "name" field will be used.
> sainsburys: fix spider

- locations/categories.py
- locations/spiders/lukoil.py
- I use `lukoil.bg` domain as regular `lukoil.ru` is blocked for my IP, as a result all addresses in RU became Latin (instead of Cyrilic).
- Not sure if I added new `FuelCards` correctly, I tried to keep them [in line with OSM](https://wiki.openstreetmap.org/wiki/Key:payment:*#Fuel_cards). Please let me know if I'm wrong.
<details>
<summary><b>Stats:</b></summary>
```python
{'atp/brand/Teboil': 408,
'atp/brand/Лукойл': 4369,
'atp/brand_wikidata/Q329347': 4369,
'atp/brand_wikidata/Q7692079': 408,
'atp/category/amenity/fuel': 4778,
'atp/field/brand/missing': 1,
'atp/field/brand_wikidata/missing': 1,
'atp/field/city/missing': 824,
'atp/field/country/from_reverse_geocoding': 4771,
'atp/field/country/missing': 7,
'atp/field/email/invalid': 112,
'atp/field/email/missing': 3652, …
```
> Add Lukoil Spdier (4778 locations).

- locations/storefinders/woosmap.py
An Origin header needs to be sent on every API request, but a previous change had forgotten to send the Origin header on page 2..n requests.
Also do not send a referrer header for page 1 -> page 2 -> page 3 -> etc.
> storefinders/woosmap: fix pagination search

- locations/linked_data_parser.py
Fixes errors such as those found at
https://data.alltheplaces.xyz/runs/2023-08-26-13-32-00/logs/dunkin_us.txt where LinkedDataParser iter_linked_data was yielding None's, and StructuredDataSpider was not expecting this.
This error could occur if source LD+JSON data was a list of different structured data dictionaries, including a null value.
> linked_data_parser: don't return None values from LD+JSON objects

- locations/spiders/wyndham.py
Vienna Hotels and ECHO Suites were missing as brands.
Brands list sorted alphabetically.
> wyndham: update brands

- locations/categories.py
- locations/spiders/omv.py
<details>
<summary>Run stats</summary>
```python
{'atp/brand/Avanti': 134,
'atp/brand/Hofer Diskont': 76,
'atp/brand/OMV': 961,
'atp/brand/Petrom': 456,
'atp/brand_wikidata/Q107803455': 76,
'atp/brand_wikidata/Q168238': 1095,
'atp/brand_wikidata/Q1755034': 456,
'atp/category/amenity/fuel': 1627,
'atp/field/email/missing': 1627,
'atp/field/image/missing': 1627,
'atp/field/name/missing': 1627,
'atp/field/phone/missing': 120,
'atp/field/state/missing': 1627,
'atp/field/twitter/missing': 1627,
'atp/field/website/missing': 1627,
'atp/nsi/category_match': 663,
'atp/nsi/cc_match': 432,
'atp/nsi/perfect_match': 532,
'atp/omv/paymentDetails/failed/ARBÖ Card': 1, …
```
> Add OMV spider (1627 locations).

- Dockerfile
- ci/run_all_spiders.sh
This adds Tippecanoe to the Docker image used in the weekly run and then calls it as part of the weekly run to generate a pmtiles file that will get uploaded as part of the artifacts generated by the build.
This can then by used so @jleedev doesn't have to regenerate the mbtiles with [alltheplaces-serve](https://github.com/jleedev/alltheplaces-serve/tree/main) and we can load them up in [Rapid editor](https://github.com/facebook/Rapid/discussions/993).
> Pmtiles support in weekly run

- ci/run_all_spiders.sh
Tippecanoe can consume the directory of GeoJSON files with more CPU if we ask it to with `--read-parallel`.
Consuming the input is even more efficient if it is a GeoJSONSeq instead of GeoJSON, but that's probably not worth it.
> Read json with more CPUs

- locations/categories.py
- locations/spiders/exxonmobil.py
My goal for this was to align `FuelCards` to use [common tagging](https://wiki.openstreetmap.org/wiki/Key:payment:*#Fuel_cards).
Currently `exxonmobil.py` is a consumer of most of the cards, I haven't looked at this spider in detail, so please feel free to adjust `FuelCards` if necessary.
> Fuel cards cleanup in categories.py.

- locations/spiders/beacon_and_bridge_market_us.py
* Fix spider (store location titles no longer have suffixes)
* Add Wikidata item
* Rename to beacon_and_bridge_market_us as only locations are MI, US
> beacon_and_bridge: fix spider and rename to beacon_and_bridge_market_us

- locations/spiders/fantastiko_bg.py
Currently the refs look like `https://www.fantastico.bg/shops/f{number}` when they should be a simple number. This PR addresses this problem.
> Fixed the format for Fantastiko's refs

- locations/logformatter.py
- locations/pipelines/duplicates.py
- locations/settings.py
We currently see ~2.5m duplicates for a full run. That's a lot of log lines.
The log formatter changes the log level from `WARNING` to `DEBUG`.
(~800k `starbucks`, ~460k `usps`)
> fix: Don't flood logs with warnings for duplicate items

- locations/spiders/orlen.py
For most POIs in this spider NSI match failed due to ambiguous match so category was not assigned ([stats ](https://data.alltheplaces.xyz/runs/2023-09-09-13-32-00/stats/orlen.json) from last ATP run)
```
"atp/category/missing": 2781,
"atp/nsi/match_failed": 2670,
```
It's fixed now.
<details><summary> Stats after fix</summary>
```json
{
"atp/brand/Bliska": 14,
"atp/brand/ORLEN Benzina": 307,
"atp/brand/Orlen": 1936,
"atp/brand/Ventus": 2,
"atp/brand/star": 565,
"atp/brand_wikidata/Q109930371": 565,
"atp/brand_wikidata/Q11130894": 307,
"atp/brand_wikidata/Q4016378": 14,
"atp/brand_wikidata/Q971649": 1936,
"atp/category/amenity/charging_station;fuel": 153,
"atp/category/amenity/fuel": 2780,
"atp/field/brand/missing": 109,
"atp/field/brand_wikidata/missing": 111, …
```
> [Orlen] Fix POIs without category.

- locations/storefinders/wp_store_locator.py
If a radius search returns max_results, it is a sign that truncation of locations has occurred. Raise an exception to make it clear that this truncation is occurring, and that parameters for the spider need adjusting to pick more granular searchable points and a smaller radius for search.
> storefinders/wp_store_locator: raise error on radius search truncation

- locations/categories.py
- https://wiki.openstreetmap.org/wiki/Key:fuel#How_to_map
- https://taginfo.openstreetmap.org/keys/fuel%3Ataxfree_diesel#overview
> Change untaxed diesel tag to be close to OSM.

- locations/spiders/yettel_bg.py
That info is not useful because all stores have the same value - "123 for Yettel subscribers, 089 123 for other operators, +359 89 123 for subscribers abroad". Also 123 is their national phone number, not an individual shop's phone number.
> Discard `phone` from yettel_bg.py

- locations/storefinders/wp_store_locator.py
If autoload=1 as a parameter to WP Store Locator and the server has been configured to support returning all locations at once, we should not check self.max_results versus the number of locations returned, as there is no maximum that should be checked against.
> storefinders/wp_store_locator: don't check max_results error on autoload

- locations/categories.py
- locations/spiders/specsavers.py
- locations/spiders/specsavers_au_nz.py
'atp/category/healthcare/audiologist': 1208,
'atp/category/healthcare/optometrist': 1403,
Removes specsavers_au_nz spider which was broken. New Zealand and European locations for Specsavers use a different store locator (not based on Sparql queries).
Partially reverses #5319 now that the store locator for some countries has changed to Sparql, and the Cloudflare blocking of the past is no longer in place.
> Add Specsavers (GB/GG/JE/IM/CA/AU) (2611 locations)

- locations/hours.py
- locations/spiders/fastbreak_us.py
- locations/spiders/ribcrib_us.py
- locations/storefinders/storerocket.py
- tests/test_opening_hours.py
1. Support multiple time ranges in a single day (or across a range of days) being specified. E.g. Mon-Fri 08:00-13:00, 14:00-18:00. There is no limit to how many ranges can exist per day (e.g. 3 or more are allowed, even though it is unlikely a use case for this exists).
2. Support named times such as Midday and Midnight. These named times can be localised into different languages as required.
3. Split overly complex add_ranges_from_string function into smaller functions.
4. Update StoreRocket store finder to use add_ranges_from_string
Replaces #5009
> add_ranges_from_string: improve function

- locations/spiders/mcdonalds.py
The various McDonald's spiders using `item_attributes` from `mcdonalds.py` were failing to apply NSI attribution due to multiple category values for the wikidata code. Supply the nudge by adding the desired category in the `item_attribues`.
> fix categories for a whole bunch of McDonald's spiders

- locations/spiders/mcdonalds_pl.py
Similar to #5954.
```json
{
"atp/brand/McDonald's": 532,
"atp/brand_wikidata/Q38076": 532,
"atp/category/amenity/fast_food": 532,
"atp/field/country/from_spider_name": 532,
"atp/field/email/missing": 532,
"atp/field/image/missing": 532,
"atp/field/name/missing": 532,
"atp/field/twitter/missing": 532,
"atp/field/website/missing": 532,
"atp/nsi/category_match": 532,
"downloader/request_bytes": 607,
"downloader/response_bytes": 88650,
"elapsed_time_seconds": 2.708991,
"finish_time": "2023-09-27T07:41:08.994143", …
```
> [mcdonalds_pl] Fix broken spider + more attributes.

- locations/spiders/total_energies.py
- I noticed that `unb` means unbranded or independent in most cases so we probably don't want to have it as a `brand`. 
- Also don't write brand abbreviations to `brand` field.
> [totalenergies] Improve brand names.

- locations/spiders/fastned.py
Category does not get added in apply_nsi_categories as there are ambiguous matches.
```python
{'atp/brand/Fastned': 280,
'atp/brand_wikidata/Q19935749': 280,
'atp/category/amenity/charging_station': 280,
'atp/field/email/missing': 280,
'atp/field/image/missing': 280,
'atp/field/opening_hours/missing': 280,
'atp/field/phone/missing': 280,
'atp/field/postcode/missing': 278,
'atp/field/state/missing': 280,
'atp/field/street_address/missing': 280,
'atp/field/twitter/missing': 280,
'atp/field/website/missing': 280,
'atp/nsi/category_match': 242,
'atp/nsi/match_failed': 38,
'downloader/request_bytes': 618,
'downloader/response_bytes': 13531, …
```
> Added Charging Station Category to Fastned

- locations/spiders/nordea_se.py
NSI has atm and bank so could not put the category on the item. Thus added apply_category here.
```python
{'atp/brand/Nordea': 210,
'atp/brand_wikidata/Q1123823': 210,
'atp/category/amenity/bank': 210,
'atp/field/city/missing': 210,
'atp/field/country/from_spider_name': 210,
'atp/field/email/missing': 210,
'atp/field/image/missing': 210,
'atp/field/name/missing': 210,
'atp/field/phone/missing': 210,
'atp/field/twitter/missing': 210,
'atp/field/website/missing': 210,
'atp/nsi/category_match': 210,
'downloader/request_bytes': 1066,
'downloader/response_bytes': 182759, …
```
> Added Bank Category to Nordea Brand

- locations/spiders/easypay.py
- locations/spiders/easypay_bg.py
Fixes #6032 
So, as there is no country data in the csv, the country is set to `None` for all items. The pipeline then runs [country_code_clean_up.py](https://github.com/alltheplaces/alltheplaces/blob/master/locations/pipelines/country_code_clean_up.py#L20). And it extracts the country from the **spider name**, which in this case is `easypay_bg`. This is why all countries were set to `BG`. The reverse geocoding did not even happen.
So the sipder name is changed to `easypay`. Now reverse geocoding takes care of all the countries. The distribution is as follows:
BG-3267
RO-24
CY-14
GR-10
MK-3
AT-1
In the future, if more spiders for easypay were to be created, the spider name can be changed to `easypay_1`.
The file name, and the class name can also be changed  if required, in order to match …
> Fixed the bug easypay_bg.py that caused countries of all items to be set to BG

- locations/spiders/midas_au.py
I added apply_category to apply the category. But not sure if we should instead change the brand qcode. The qcode is correct, but the global/US https://www.wikidata.org/wiki/Q3312613 Midas qcode is in NSI as Car Repair and includes the globe. Curious what others think, should we add another Midas AU in NSI?
```python
{'atp/brand/Midas': 79,
'atp/brand_wikidata/Q118383658': 79,
'atp/category/shop/car_repair': 79,
'atp/field/city/missing': 79,
'atp/field/country/from_spider_name': 79,
'atp/field/image/missing': 79,
'atp/field/postcode/missing': 79,
'atp/field/state/missing': 79,
'atp/field/street_address/missing': 79,
'atp/field/twitter/missing': 79,
'atp/nsi/brand_missing': 79, …
```
> Added car repair category tag to Midas_au Brand

- locations/spiders/carhartt_wip.py
Just created a wikidata page for Carhartt WIP brand and also have a PR for NSI addition.
https://github.com/osmlab/name-suggestion-index/pull/8788
```python
{'atp/brand/Carhartt Work in Progress': 86,
'atp/brand_wikidata/Q123015694': 86,
'atp/category/missing': 86,
'atp/field/state/missing': 84,
'atp/nsi/brand_missing': 86,
'downloader/request_bytes': 7856,
'downloader/request_method_count/POST': 3,
'downloader/response_bytes': 134920, …
```
> Added new brandname and wikidata code for Carhartt WIP

- locations/spiders/boots_no.py
The qcode pointed to Boots in the united kingdom. But Apotek is the pharmacy chain that is in norway.
```python
{'atp/brand/Apotek': 153,
'atp/brand_wikidata/Q4581428': 153,
'atp/category/amenity/pharmacy': 153,
'atp/category/multiple': 153,
'atp/field/city/missing': 153,
'atp/field/email/missing': 153,
'atp/field/image/missing': 153,
'atp/field/opening_hours/missing': 153,
'atp/field/phone/missing': 153,
'atp/field/postcode/missing': 153,
'atp/field/state/missing': 153,
'atp/field/street_address/missing': 153,
'atp/field/twitter/missing': 153,
'atp/nsi/perfect_match': 153,
'downloader/request_bytes': 115978,
'downloader/request_count': 309,
'downloader/request_method_count/GET': 309,
'downloader/response_bytes': 5131379,
'downloader/response_count': 309, …
```
> Add category to Boots NO

- locations/spiders/volvo.py
```python
{'atp/brand/Volvo': 883,
'atp/brand_wikidata/Q215293': 883,
'atp/category/shop/car': 883,
'atp/field/email/invalid': 43,
'atp/field/image/missing': 883,
'atp/field/opening_hours/missing': 492,
'atp/field/state/missing': 883,
'atp/field/twitter/missing': 883,
'atp/field/website/invalid': 3,
'atp/field/website/missing': 11,
'atp/nsi/category_match': 883,
'downloader/request_bytes': 2207,
'downloader/response_bytes': 343506,
'downloader/response_status_count/200': 8,
'elapsed_time_seconds': 8.450076,
'finish_time': datetime.datetime(2023, 10, 11, 19, 28, …
```
> Added dealer url for united kingdom and netherlands

- locations/spiders/united_dairy_farmers_us.py
Is in NSI but as advertising, fuel, and ice cream shop. Thus added fueld category tag.
```python
{'atp/brand/United Dairy Farmers': 178,
'atp/brand_wikidata/Q7887677': 178,
'atp/category/amenity/fuel': 178,
'atp/cdn/cloudflare/response_count': 180,
'atp/cdn/cloudflare/response_status_count/200': 180,
'atp/field/email/missing': 178,
'atp/field/image/missing': 178,
'atp/field/opening_hours/missing': 178,
'atp/field/street_address/missing': 178,
'atp/field/twitter/missing': 178,
'atp/field/website/missing': 178,
'atp/nsi/category_match': 178,
'downloader/request_bytes': 69288,
'downloader/request_count': 180, …
```
> Added fuel category tag for UDF brand

- locations/spiders/f24.py
Brands are in NSI, but have same QID for different categories, thus category never gets added.
```python
{'atp/brand/F24': 140,
'atp/brand/Q8': 107,
'atp/brand_wikidata/Q12310853': 140,
'atp/brand_wikidata/Q1634762': 107,
'atp/category/amenity/fuel': 247,
'atp/field/country/from_website_url': 247,
'atp/field/email/missing': 247,
'atp/field/image/missing': 247,
'atp/field/postcode/missing': 247,
'atp/field/state/missing': 247,
'atp/field/twitter/missing': 247,
'atp/nsi/category_match': 247,
'downloader/request_bytes': 673,
'downloader/response_bytes': 366766, …
```
> Added fuel station category tag for f24 brand

- locations/spiders/ralph_lauren.py
Rel: https://github.com/alltheplaces/alltheplaces/pull/5949
I see it worked one week, but then not again. I'm in the same situation as before, it fails from GB due to redirects. US vpn works:
```python
{'atp/brand/Polo Ralph Lauren': 481,
'atp/brand_wikidata/Q1641437': 481,
'atp/category/shop/clothes': 481,
'atp/field/brand/missing': 481,
'atp/field/country/from_reverse_geocoding': 19,
'atp/field/email/invalid': 4,
'atp/field/email/missing': 440,
'atp/field/image/missing': 481,
'atp/field/opening_hours/missing': 481,
'atp/field/postcode/missing': 26,
'atp/field/state/missing': 208,
'atp/field/twitter/missing': 481,
'atp/nsi/perfect_match': 481, …
```
> [Ralph Lauren] Flag as requiring a proxy

- locations/spiders/audi_be.py
QCode has multiple NSI entries, thus category is not being added.
```python
{'atp/brand/Audi': 64,
'atp/brand_wikidata/Q23317': 64,
'atp/category/shop/car': 64,
'atp/field/image/missing': 64,
'atp/field/state/missing': 64,
'atp/field/twitter/missing': 64,
'atp/nsi/category_match': 64,
'downloader/request_bytes': 372,
'downloader/response_bytes': 257910,
'elapsed_time_seconds': 4.437273,
'finish_time': datetime.datetime(2023, 10, 12, 15, 56, …
```
> Added Car Shop Category Tag

- locations/spiders/hilton.py
- locations/user_agents.py
Hilton website now likes only latest browsers.
```json
{
"atp/brand/Canopy by Hilton": 43,
"atp/brand/Conrad Hotels & Resorts": 50,
"atp/brand/DoubleTree by Hilton": 696,
"atp/brand/Embassy Suites": 273,
"atp/brand/Hampton by Hilton": 2985,
"atp/brand/Hilton Garden Inn": 1023,
"atp/brand/Hilton Hotels & Resorts": 619,
"atp/brand/Home2 Suites by Hilton": 684,
"atp/brand/Homewood Suites by Hilton": 544,
"atp/brand/LXR Hotels & Resorts": 9,
"atp/brand/Motto by Hilton": 8,
"atp/brand/Tru by Hilton": 263,
"atp/brand/Waldorf Astoria": 36,
"atp/brand_wikidata/Q112144350": 8,
"atp/brand_wikidata/Q1162859": 1023,
"atp/brand_wikidata/Q24907770": 263,
"atp/brand_wikidata/Q2504643": 696,
"atp/brand_wikidata/Q30632909": 43,
"atp/brand_wikidata/Q3239392": 36, …
```
> [hilton] fix broken spider.

- locations/spiders/radisson_hotels.py
I could not get the last scrapy request to return something. . But I noticed that the city, postal code, and the country are also in the 2nd request. Thus, we lose extracting the email and phone. I turned the robotstxt obey setting to false and still nothing returned. 
```python
{'atp/brand/Art’otel': 7,
'atp/brand/Country Inn & Suites by Radisson': 15,
'atp/brand/Park Inn by Radisson': 111,
'atp/brand/Park Plaza Hotels & Resorts': 36,
'atp/brand/Prizeotel': 14,
'atp/brand/Radisson': 96,
'atp/brand/Radisson Blu': 333,
'atp/brand/Radisson Collection': 36,
'atp/brand/Radisson Individuals': 41,
'atp/brand/Radisson RED': 19,
'atp/brand_wikidata/Q14516231': 7,
'atp/brand_wikidata/Q1751979': 96,
'atp/brand_wikidata/Q2052550': 36, …
```
> Reformatted radisson hotels to get it working again.

- locations/spiders/central_england_cooperative.py
- locations/spiders/chelmsford_star_coop_gb.py
- locations/spiders/heart_of_england_cooperative_gb.py
- locations/spiders/midcounties_cooperative_gb.py
- locations/spiders/southern_coop.py
- locations/spiders/the_cooperative_group.py
I'm sure there are still issues, but it's an improvement.
"Coop" in GB is a PATA, it's a mix of companies (I think like Goodwill in US), however they have had internal drama. So the don't actually share a brand any more, but do share the mindshare.
I have 2 within 5 mins of my flat. 1 is a Southern (aka green), I always thought the other was Central, but it's actually Group.
Group is the big one, the small ones stayed with it. They are a coop of coops and (mostly) share a brand (aka blue). The mid sized ones fragmented.
Thanks for reading my anecdote.
> Improve coop GB tagging

- locations/hours.py
Rel: https://github.com/alltheplaces/alltheplaces/pull/6148#discussion_r1359878410
These dicts are for converting supplied days to OSM days, common spelling mistakes and acronyms are expected.
> Restore PL spelling mistake

- locations/spiders/liberty_au.py
Added a `liberty_au` spider for Liberty fuel stations in Australia.
Closes #6071
> Add liberty_au spider (92 locations)

- locations/categories.py
- locations/spiders/childcare_network_us.py
A collection of daycares for little youngsters to young for primary, middle, and secondary schools.
```python
{'atp/category/amenity/kindergarten': 228,
'atp/field/brand/missing': 228,
'atp/field/brand_wikidata/missing': 228,
'atp/field/country/from_spider_name': 228,
'atp/field/email/missing': 228,
'atp/field/image/dropped': 228,
'atp/field/image/missing': 228,
'downloader/request_bytes': 92613,
'downloader/request_count': 232,
'downloader/request_method_count/GET': 232,
'downloader/response_bytes': 4431461,
'downloader/response_count': 232,
'downloader/response_status_count/200': 231,
'elapsed_time_seconds': 3.954842,
'finish_time': datetime.datetime(2023, 10, 5, 12, 46, 52, …
```
> Added Kindergarten Category Tag

- locations/spiders/jysk.py
Rel: #6180 
I noticed that we can visit every country specific site without listing them explicitly.
Also Jysk does not block my IP.
Stats:
```json
{
"atp/brand/JYSK": 3142,
"atp/brand_wikidata/Q138913": 3142,
"atp/category/shop/furniture": 3142,
"atp/field/country/from_website_url": 3142,
"atp/field/email/missing": 3142,
"atp/field/image/missing": 72,
"atp/field/opening_hours/missing": 11,
"atp/field/phone/invalid": 3,
"atp/field/phone/missing": 98,
"atp/field/state/missing": 3142,
"atp/field/street_address/missing": 3142,
"atp/field/twitter/missing": 3142,
"atp/nsi/cc_match": 3142,
"downloader/request_bytes": 1170399,
"downloader/request_count": 3368,
"downloader/request_method_count/GET": 3368,
"downloader/response_bytes": 4509409,
"downloader/response_count": 3368, …
```
> [jysk] Improve spider.

- locations/spiders/techcombank_vn.py
Has multiple NSI IDs. Thus the category cannot be determined from NSI alone.
```python
{'atp/brand/Techcombank': 297,
'atp/brand_wikidata/Q10541776': 297,
'atp/category/amenity/bank': 297,
'atp/field/city/missing': 297,
'atp/field/country/from_spider_name': 297,
'atp/field/email/missing': 297,
'atp/field/image/missing': 297,
'atp/field/opening_hours/missing': 297,
'atp/field/phone/invalid': 15,
'atp/field/postcode/missing': 297,
'atp/field/state/missing': 297,
'atp/field/street_address/missing': 297,
'atp/field/twitter/missing': 297,
'atp/field/website/missing': 297,
'atp/nsi/category_match': 297, …
```
> Added category Bank for items (297 Items)

- locations/spiders/petrol.py
NSI has mutliple entries thus category can not be determined.
```python
{'atp/brand/Crodux': 92,
'atp/brand/Petrol': 503,
'atp/brand_wikidata/Q174824': 503,
'atp/brand_wikidata/Q62274622': 92,
'atp/category/amenity/fuel': 595,
'atp/field/email/missing': 595,
'atp/field/image/missing': 595,
'atp/field/phone/missing': 595,
'atp/field/state/missing': 595,
'atp/field/street_address/missing': 595,
'atp/field/twitter/missing': 595,
'atp/field/website/missing': 595,
'atp/nsi/category_match': 595,
'downloader/request_bytes': 4466,
'downloader/response_bytes': 1572004,
'downloader/response_status_count/200': 8,
'elapsed_time_seconds': 19.088117, …
```
> Added category for Petrol Brand (595 Items)

- locations/spiders/jysk.py
It seems like there are no duplicated refs across the websites so there is no point in using the URL address as a ref.
> Use actual ref for JYSK store

- locations/spiders/east_of_england_coop.py
Multiple NSI entries. Thus Category tag is not added.
```python
{'atp/brand/East of England Co-op': 178,
'atp/brand_wikidata/Q5329759': 178,
'atp/category/shop/supermarket': 178,
'atp/field/email/missing': 178,
'atp/field/image/missing': 178,
'atp/field/opening_hours/missing': 178,
'atp/field/twitter/missing': 178,
'atp/nsi/category_match': 178,
'downloader/request_bytes': 121140,
'downloader/request_count': 230,
'downloader/request_method_count/GET': 230,
'downloader/response_bytes': 6577448,
'downloader/response_count': 230,
'downloader/response_status_count/200': 222,
'downloader/response_status_count/302': 1,
'downloader/response_status_count/404': 2, …
```
> Added shop=supermarket category tag for East of England Coop Brand (178 Items)

- locations/spiders/sonic_ca.py
NSI has two entries, thus category does not get added.
```python
{'atp/brand/Sonic': 290,
'atp/brand_wikidata/Q118669677': 290,
'atp/category/amenity/fuel': 290,
'atp/field/city/missing': 290,
'atp/field/country/from_spider_name': 290,
'atp/field/email/missing': 290,
'atp/field/image/missing': 290,
'atp/field/opening_hours/missing': 290,
'atp/field/phone/missing': 290,
'atp/field/postcode/missing': 290,
'atp/field/state/from_reverse_geocoding': 290,
'atp/field/street_address/missing': 290,
'atp/field/twitter/missing': 290,
'atp/field/website/missing': 290,
'atp/nsi/category_match': 290,
'downloader/request_bytes': 682,
'downloader/response_bytes': 17701, …
```
> Added fuel station category tag for Sonic_ca (290 Items)

- locations/spiders/safeway_ca.py
Not sure if I should add the brand to NSI or not. Kind of a toss up. As Safeway Canada https://www.wikidata.org/wiki/Q17111901 is independent (as of 2013) from safeway USA https://www.wikidata.org/wiki/Q1508234. Although it still uses the same logo and such as its USA counterpart. The USA counterpart does have an entry in NSI with the same name. 
Maybe the the USA entry in NSI should change the include to be "us" instead of "001". Then we could include "ca" for canadian one.
```python
{'atp/brand/Safeway': 145,
'atp/brand_wikidata/Q17111901': 145,
'atp/category/shop/supermarket': 145,
'atp/cdn/cloudflare/response_count': 154,
'atp/cdn/cloudflare/response_status_count/200': 154,
'atp/field/country/from_spider_name': 145,
'atp/field/email/missing': 145, …
```
> Added supermarket category to brand (145 Items)

- locations/spiders/true_value_us.py
- locations/storefinders/where2getit.py
There was a problem with use of the api_filter attribute due to incorrect merging of dictionaries together into a single filter query.
> storefinders/where2getit: fix use of api_filter

- locations/spiders/nhs_scotland_gb.py
Absolute URLs are now used instead of relative URLs.
> nhs_scotland_gb: fix spider

- locations/spiders/bulgarian_posts_bg.py
Gracefully ignore invalid opening hours (e.g. 145:15 as a HH:MM).
> bulgarian_posts_bg: fix spider

- locations/storefinders/wp_store_locator.py
The default time format was incorrect as %H:%S instead of %H:%M.
> storefinders/wp_store_locator: fix opening hours format

- locations/storefinders/geo_me.py
The `bp` spider has changed opening hours data to use inconsistent formats such as "%H:%M" and "%H:%M:%S". The geo_me storefinder is thus updated to accomodate spiders with inconsistent time formats.
> storefinders/geo_me: improve opening hours extraction

- locations/spiders/j_d_wetherspoon.py
Sitemap is out of date
```python
{'atp/brand/Wetherspoon': 820,
'atp/brand_wikidata/Q6109362': 820,
'atp/category/amenity/pub': 820,
'atp/field/country/from_reverse_geocoding': 820,
'atp/field/email/missing': 820,
'atp/field/twitter/missing': 820,
'atp/nsi/perfect_match': 820,
'downloader/request_bytes': 394676,
'downloader/request_count': 822,
'downloader/request_method_count/GET': 822,
'downloader/response_bytes': 55605849,
'downloader/response_count': 822,
'downloader/response_status_count/200': 822,
'elapsed_time_seconds': 1001.767391,
'finish_time': datetime.datetime(2023, 10, 30, …
```
> [JSWethersoon] Switch to crawl spider

- locations/spiders/spotlight.py
Corrected brand_wikidata so it will [match NSI](https://nsi.guide/index.html?t=brands&k=shop&v=fabric&tt=spotlight).
> [spotlight] correct brand_wikidata.

- locations/spiders/aldi_sud_hu.py
The display name that was found using dict parser was not good giving a 3 letter code and 3 digit number. Thus we are changing the name to be closer to what store locator shows. Which is just ALDI
```python
{'atp/brand/ALDI': 168,
'atp/brand_wikidata/Q41171672': 168,
'atp/category/shop/supermarket': 168,
'atp/field/email/missing': 168,
'atp/field/image/missing': 168,
'atp/field/state/missing': 168,
'atp/field/twitter/missing': 168,
'atp/field/website/missing': 168,
'atp/nsi/cc_match': 168,
'downloader/request_bytes': 958,
'downloader/response_bytes': 81124,
'elapsed_time_seconds': 2.897858, …
```
> Overwrote name as many were given as BIA-188 (168 items)

- locations/commands/nsi.py
The current system is printing the wikidata label in the `item_attributes` template, and I think it's causing some confusion, we should be using the NSI brand, not the Wikidata label.
> Print accurate item_attributes

- locations/spiders/vans.py
There were duplicates because the POIs were being collected by both the city list pages and the actual page. (The list pages have bad data)
```patch
+https://www.vans.com/en-us/stores/tx/cedar-park/usa196
-https://www.vans.com/en-us/stores/cedar-park/usa196
```
The [stockets](https://www.vans.com/en-us/stores/nc/raleigh/journ-cvm4325ga1) have ids like `famou-3699h95bca` where the first bit maps to the company like `famou` -> "Famous Footwear".
Whereas it looks like real vans never contain a `-`.
> [Vans] Remove duplicates and stockists

- locations/spiders/econofitness_ca.py
Rel: https://github.com/osmlab/name-suggestion-index/pull/8904
```python
{'atp/brand/Éconofitness': 68,
'atp/brand_wikidata/Q123073582': 68,
'atp/category/missing': 68,
'atp/field/image/dropped': 68,
'atp/field/image/missing': 68,
'atp/field/name/missing': 68,
'atp/field/state/from_reverse_geocoding': 68,
'atp/nsi/brand_missing': 68,
'downloader/request_bytes': 48094,
'downloader/request_count': 70,
'downloader/request_method_count/GET': 70,
'downloader/response_bytes': 2155675,
'downloader/response_count': 70,
'downloader/response_status_count/200': 70,
'elapsed_time_seconds': 2.148722,
'finish_time': datetime.datetime(2023, 11, 6, 23, 3, 41, …
```
> [EconofitnessCA] Add spider

- locations/spiders/rocket_us.py
Rel: https://github.com/osmlab/name-suggestion-index/issues/8828
Fixes #6182
```python
{'atp/brand/Rocket': 453,
'atp/brand_wikidata/Q121513516': 453,
'atp/category/shop/convenience': 453,
'atp/field/email/missing': 453,
'atp/field/image/missing': 453,
'atp/field/name/missing': 453,
'atp/field/opening_hours/missing': 453,
'atp/field/twitter/missing': 453,
'atp/field/website/missing': 453,
'atp/nsi/brand_missing': 453,
'downloader/request_bytes': 633,
'downloader/response_bytes': 309376,
'elapsed_time_seconds': 2.831167,
'finish_time': …
```
> [RocketUS] Add spider

- locations/spiders/crocs_eu.py
```python
{'atp/brand/Crocs': 169,
'atp/brand_wikidata/Q926699': 169,
'atp/category/shop/shoes': 169,
'atp/field/email/missing': 169,
'atp/field/image/missing': 169,
'atp/field/opening_hours/missing': 169,
'atp/field/phone/missing': 131,
'atp/field/postcode/missing': 30,
'atp/field/state/missing': 158,
'atp/field/twitter/missing': 169,
'atp/field/website/missing': 169,
'atp/nsi/perfect_match': 169,
'downloader/request_bytes': 951,
'downloader/response_bytes': 71673,
'elapsed_time_seconds': 0.591903,
'finish_time': datetime.datetime(2023, …
```
> [CrocsEU] Remove stockists

- locations/spiders/mckesson_ca.py
'atp/brand/Guardian': 477,
'atp/brand/I.D.A.': 622,
"atp/brand/Remedy'sRx": 315,
'atp/brand/Uniprix': 305,
Fixes #902
> Add McKesson Canada pharmacy brands (CA) (1719 locations)

- locations/spiders/bnp_paribas_bank_pl.py
```python
{'atp/brand/BNP Paribas Bank Polska': 934,
'atp/brand/Euronet': 6861,
'atp/brand/Planet Cash': 4084,
'atp/brand_wikidata/Q117744569': 4084,
'atp/brand_wikidata/Q20744004': 934,
'atp/brand_wikidata/Q5412010': 6861,
'atp/category/amenity/atm': 11503,
'atp/category/amenity/bank': 376,
'atp/field/country/from_spider_name': 11879,
'atp/field/email/missing': 11503,
'atp/field/image/missing': 11879,
'atp/field/phone/missing': 11879,
'atp/field/state/missing': 11879,
'atp/field/twitter/missing': 11879,
'atp/field/website/missing': 11879,
'atp/nsi/category_match': 934,
'atp/nsi/perfect_match': 10945,
'downloader/request_bytes': 1226,
'downloader/response_bytes': 447347, …
```
> [BNPParibasBankPL] Don't crash on records missing ids

- locations/spiders/delikatesy_centrum_pl.py
There are 2 categories in NSI, namely shop=convenience and shop=supermarket.
Nothing in the data we scrape to indicate size of store.
Hence set to supermarket.
{'atp/brand/Delikatesy Centrum': 1459,
'atp/brand_wikidata/Q11693824': 1459,
'atp/category/shop/supermarket': 1459,
'atp/field/country/from_spider_name': 1459,
'atp/field/email/missing': 1459,
'atp/field/image/missing': 1459,
'atp/field/phone/missing': 1459,
'atp/field/state/missing': 1459,
'atp/field/street_address/missing': 1459,
'atp/field/twitter/missing': 1459,
'atp/field/website/missing': 1459,
'atp/nsi/category_match': 1459,
'downloader/request_bytes': 1014, …
> [DelikatesyCentrumPL] Fix category

- locations/spiders/taco_time_northwest_us.py
```python
{'atp/brand/Taco Time Northwest': 76,
'atp/brand_wikidata/Q7673970': 76,
'atp/category/amenity/fast_food': 76,
'atp/field/city/missing': 76,
'atp/field/opening_hours/missing': 76,
'atp/field/postcode/missing': 76,
'atp/field/state/from_reverse_geocoding': 76,
'atp/field/street_address/missing': 76,
'atp/field/twitter/missing': 76,
'atp/nsi/perfect_match': 76,
'downloader/request_bytes': 608,
'downloader/response_bytes': 20969,
'elapsed_time_seconds': 0.803331, …
```
> [TacoTimeNorthwestUS] Collect menu and website

- locations/spiders/lewiatan_pl.py
There are 2 categories in NSI, namely shop=convenience and shop=supermarket.
Nothing in the data we scrape to indicate size of store.
Hence set to supermarket.
{'atp/brand/Lewiatan': 2863,
'atp/brand_wikidata/Q11755396': 2863,
'atp/category/shop/supermarket': 2863,
'atp/field/country/from_spider_name': 2863,
'atp/field/email/missing': 2863,
'atp/field/image/missing': 2863,
'atp/field/name/missing': 2863,
'atp/field/opening_hours/missing': 2863,
'atp/field/phone/invalid': 381,
'atp/field/phone/missing': 1385,
'atp/field/state/missing': 2863,
'atp/field/twitter/missing': 2863,
'atp/nsi/category_match': 2863,
'downloader/request_bytes': 612,
'downloader/response_bytes': 1301467, …
> [LewiatanPL] Fix category

- locations/spiders/staples_ca.py
```python
{'atp/brand/Staples': 300,
'atp/brand_wikidata/Q17149420': 300,
'atp/category/shop/stationery': 300,
'atp/field/country/from_spider_name': 300,
'atp/field/email/missing': 300,
'atp/field/image/dropped': 300,
'atp/field/image/missing': 300,
'atp/nsi/match_failed': 300,
'downloader/request_bytes': 117036,
'downloader/request_count': 304,
'downloader/request_method_count/GET': 304,
'downloader/response_bytes': 6715867,
'downloader/response_count': 304,
'downloader/response_status_count/200': 303,
'elapsed_time_seconds': 2.387351,
'finish_time': datetime.datetime(2023, 11, 16, 10, 50, 8, 698591),
'httpcache/hit': 304,
'httpcompression/response_bytes': 41734087, …
```
> [StaplesCA] Add spider

- locations/spiders/netto_salling.py
```python
{'atp/brand/Netto': 1189,
'atp/brand_wikidata/Q552652': 1189,
'atp/category/shop/supermarket': 1189,
'atp/cdn/cloudflare/response_count': 1197,
'atp/cdn/cloudflare/response_status_count/200': 1195,
'atp/cdn/cloudflare/response_status_count/524': 1,
'atp/field/country/from_website_url': 1189,
'atp/field/email/missing': 1189,
'atp/field/opening_hours/missing': 13,
'atp/field/phone/missing': 529,
'atp/field/state/missing': 1189,
'atp/field/twitter/missing': 660,
'atp/nsi/perfect_match': 1189,
'downloader/request_bytes': 741130,
'downloader/request_count': 1200,
'downloader/request_method_count/GET': 1200,
'downloader/response_bytes': 74598575,
'downloader/response_count': 1200,
'downloader/response_status_count/200': 1195, …
```
> [NettoSalling] Fix HTML escaping

- locations/spiders/swarco_e_connect.py
{'atp/brand/Swarco E.Connect': 1033,
'atp/brand_wikidata/Q118383410': 1033,
'atp/category/amenity/charging_station': 1033,
'atp/field/country/from_reverse_geocoding': 1031,
'atp/field/country/missing': 2,
'atp/field/email/missing': 1033,
'atp/field/image/missing': 1033,
'atp/field/name/missing': 1033,
'atp/field/opening_hours/missing': 1033,
'atp/field/phone/missing': 1033,
'atp/field/postcode/missing': 1033,
'atp/field/street_address/missing': 1033,
'atp/field/twitter/missing': 1033,
'atp/field/website/missing': 1033,
'atp/nsi/category_match': 1031,
'atp/nsi/match_failed': 2,
'downloader/request_bytes': 633, …
> [SwarcoEConnect] Add category

- locations/spiders/cenex.py
Added category here as there are multiple NSI entries.
```python
{'atp/brand/Cenex': 1317,
'atp/brand_wikidata/Q62127191': 1317,
'atp/category/amenity/fuel': 1317,
'atp/field/email/missing': 1317,
'atp/field/image/missing': 1317,
'atp/field/opening_hours/missing': 317,
'atp/field/twitter/missing': 1317,
'atp/field/website/missing': 1317,
'atp/nsi/category_match': 1317,
'downloader/request_bytes': 1231,
'downloader/response_bytes': 965754,
'elapsed_time_seconds': 4.999585,
'finish_time': …
```
> [cenex] Added Fuel Category Tag (1317 items)

- locations/spiders/vinnies_au.py
Wikidata has 2 Q codes for this brand.
NSI has an entry with a Q code.
Changed this spider to use the Wikidata Q code which matches the NSI entry.
It then picks up the correct category.
{'atp/brand/Vinnies': 651,
'atp/brand_wikidata/Q117547405': 651,
'atp/category/shop/charity': 651,
'atp/field/city/missing': 651,
'atp/field/country/from_spider_name': 651,
'atp/field/email/missing': 651,
'atp/field/image/missing': 651,
'atp/field/opening_hours/missing': 18,
'atp/field/postcode/missing': 651,
'atp/field/state/missing': 651,
'atp/field/street_address/missing': 651,
'atp/field/twitter/missing': 651,
'atp/nsi/perfect_match': 651,
'downloader/request_bytes': 808, …
> [VinniesAU] Fix category by adding NSI Q code

- locations/spiders/ecars.py
{'atp/brand/ecars': 699,
'atp/brand_wikidata/Q3050566': 699,
'atp/category/amenity/charging_station': 699,
'atp/field/city/missing': 141,
'atp/field/country/from_reverse_geocoding': 699,
'atp/field/email/missing': 699,
'atp/field/image/missing': 699,
'atp/field/name/missing': 699,
'atp/field/opening_hours/missing': 699,
'atp/field/phone/missing': 699,
'atp/field/postcode/missing': 694,
'atp/field/state/missing': 21,
'atp/field/street_address/missing': 699,
'atp/field/twitter/missing': 699,
'atp/field/website/missing': 699,
'atp/nsi/category_match': 699,
'downloader/request_bytes': 454,
'downloader/response_bytes': 29029, …
> [ecars] Add category

- locations/spiders/opendata_mos_household_services_ru.py
Open Data Portal of Moscow Government moved to a new API URL recently.
Tested both spiders and they work fine from my end using RU ip.
> [OpendataMosSpider] update API URL.

- locations/spiders/dunelm_gb.py
NSI has 2 entries, namely amenity/cafe, and shop/interior_decoration.
To disambiguate category is set more correctly, I believe, to shop/houseware.
{'atp/brand/Dunelm': 182,
'atp/brand_wikidata/Q5315020': 182,
'atp/category/shop/houseware': 182,
'atp/field/image/missing': 182,
'atp/field/state/missing': 113,
'atp/field/twitter/missing': 182,
'atp/nsi/match_failed': 182,
'downloader/request_bytes': 1116,
'downloader/response_bytes': 171769, …
> [DunelmGB] Add category

- locations/spiders/osprey_gb.py
{'atp/brand/Osprey': 305,
'atp/brand_wikidata/Q117706577': 305,
'atp/category/amenity/charging_station': 305,
'atp/field/city/missing': 305,
'atp/field/country/from_spider_name': 305,
'atp/field/email/missing': 305,
'atp/field/image/missing': 305,
'atp/field/name/missing': 305,
'atp/field/opening_hours/missing': 305,
'atp/field/phone/missing': 305,
'atp/field/postcode/missing': 303,
'atp/field/state/missing': 305,
'atp/field/street_address/missing': 305,
'atp/field/twitter/missing': 305,
'atp/field/website/missing': 305,
'atp/nsi/category_match': 305,
'downloader/request_bytes': 734,
'downloader/response_bytes': 22123, …
> [OspreyGB] Add category

- locations/spiders/casino_fr.py
3 entries in NSI - for fuel stations, advertising totem, and supermarkets
Disambiguate this by setting category explicitly to supermarket for these POIs
{'atp/brand/Casino Supermarchés': 376,
'atp/brand_wikidata/Q89029184': 376,
'atp/category/shop/supermarket': 376,
'atp/field/country/from_spider_name': 376,
'atp/field/email/missing': 376,
'atp/field/image/missing': 376,
'atp/field/state/missing': 376,
'atp/nsi/category_match': 376,
'downloader/request_bytes': 185936,
'downloader/request_count': 378,
'downloader/request_method_count/GET': 378,
'downloader/response_bytes': 19044361,
'downloader/response_count': 378,
'downloader/response_status_count/200': 377, …
> [CasinoFR] Add category

- locations/spiders/howardhanna.py
{'atp/brand/Howard Hanna': 386,
'atp/brand_wikidata/Q119573413': 386,
'atp/category/office/estate_agent': 386,
'atp/field/country/from_reverse_geocoding': 386,
'atp/field/email/missing': 386,
'atp/field/image/missing': 386,
'atp/field/opening_hours/missing': 386,
'atp/field/phone/missing': 15,
'atp/field/postcode/missing': 386,
'atp/field/street_address/missing': 386,
'atp/field/twitter/missing': 386,
'atp/nsi/perfect_match': 386,
'downloader/request_bytes': 406481,
'downloader/request_count': 774,
'downloader/request_method_count/GET': 774,
'downloader/response_bytes': 28266855,
'downloader/response_count': 774,
'downloader/response_status_count/200': 774,
'elapsed_time_seconds': 936.509029,
'finish_time': datetime.datetime(2023, 11, 22, 12, 32, 15, 422825, …
> [HowardHanna] Add wikidata Q code to fix category

- locations/spiders/tax_assist_gb.py
Rel: https://github.com/osmlab/name-suggestion-index/pull/8959
```python
{'atp/brand/TaxAssist Accountants': 414,
'atp/brand_wikidata/Q122459380': 414,
'atp/category/missing': 414,
'atp/cdn/cloudflare/response_count': 416,
'atp/cdn/cloudflare/response_status_count/200': 416,
'atp/field/country/from_spider_name': 139,
'atp/field/email/missing': 414,
'atp/field/image/missing': 189,
'atp/field/state/missing': 414,
'atp/nsi/brand_missing': 414,
'downloader/request_bytes': 452894,
'downloader/request_count': 416,
'downloader/request_method_count/GET': 416,
'downloader/response_bytes': 6045432,
'downloader/response_count': 416,
'downloader/response_status_count/200': 416, …
```
> [TaxAssistGB] Add spider

- locations/spiders/ionity.py
2 entries in NSI namely charging_station and charge point, so category set explicitly.
{'atp/brand/Ionity': 549,
'atp/brand_wikidata/Q42717773': 549,
'atp/category/amenity/charging_station': 549,
'atp/field/country/from_reverse_geocoding': 549,
'atp/field/email/missing': 549,
'atp/field/image/missing': 549,
'atp/field/phone/missing': 549,
'atp/field/postcode/missing': 499,
'atp/field/street_address/missing': 498,
'atp/field/twitter/missing': 549,
'atp/field/website/missing': 549,
'atp/nsi/match_failed': 549,
'downloader/request_bytes': 603,
'downloader/response_bytes': 146443, …
> [Ionity] Add category

- locations/spiders/mediamarkt.py
```python
{'atp/brand/MediaMarkt': 285,
'atp/brand_wikidata/Q2381223': 285,
'atp/category/shop/electronics': 285,
'atp/cdn/cloudflare/response_count': 288,
'atp/cdn/cloudflare/response_status_count/200': 287,
'atp/field/email/missing': 284,
'atp/field/phone/invalid': 279,
'atp/field/state/missing': 285,
'atp/nsi/perfect_match': 285,
'downloader/request_bytes': 366275,
'downloader/request_count': 574,
'downloader/request_method_count/GET': 574,
'downloader/response_bytes': 31060020,
'downloader/response_count': 574,
'downloader/response_status_count/200': 287,
'downloader/response_status_count/301': 286,
'elapsed_time_seconds': 696.439155, …
```
> [media_markt] Fixed Spider (285 Items)

- locations/spiders/pjs_coffee_us.py
{"atp/brand/PJ's Coffee of New Orleans": 180,
'atp/brand_wikidata/Q7119454': 180,
'atp/category/amenity/cafe': 180,
'atp/field/brand/missing': 180,
'atp/field/country/from_spider_name': 180,
'atp/field/email/missing': 180,
'atp/field/image/dropped': 180,
'atp/field/image/missing': 180,
'atp/field/name/missing': 180,
'atp/field/phone/missing': 16,
'atp/nsi/perfect_match': 180,
'downloader/request_bytes': 115848,
'downloader/request_count': 304,
'downloader/request_method_count/GET': 304,
'downloader/response_bytes': 5284785,
'downloader/response_count': 304,
'downloader/response_status_count/200': 304,
'dupefilter/filtered': 230,
'elapsed_time_seconds': 376.49412,
'finish_time': datetime.datetime(2023, 11, 23, 9, 9, 59, …
> [PJsCoffeeUS] Correct Q code to fix category

- locations/spiders/gas_nz.py
{'atp/brand/G.A.S.': 123,
'atp/brand_wikidata/Q112189761': 123,
'atp/category/amenity/fuel': 123,
'atp/field/city/missing': 123,
'atp/field/country/from_spider_name': 123,
'atp/field/image/missing': 123,
'atp/field/postcode/missing': 123,
'atp/field/state/missing': 123,
'atp/field/street_address/missing': 123,
'atp/field/twitter/missing': 123,
'atp/field/website/missing': 123,
'atp/nsi/category_match': 123,
'downloader/response_bytes': 27572,
'elapsed_time_seconds': 2.243424,
'finish_time': datetime.datetime(2023, 11, 23, 10, 32, 51, …
> [GasNZ] Add category

- locations/spiders/scrubs_and_beyond.py
This just needs the wikidata Q code because then that picks up the NSI category correctly.
{'atp/brand/Scrubs and Beyond': 122,
'atp/brand_wikidata/Q119972011': 122,
'atp/category/shop/clothes': 122,
'atp/field/country/from_reverse_geocoding': 122,
'atp/field/email/missing': 122,
'atp/field/image/dropped': 122,
'atp/field/image/missing': 122,
'atp/nsi/perfect_match': 122,
'downloader/request_bytes': 52791,
'downloader/request_count': 126,
'downloader/request_method_count/GET': 126,
'downloader/response_bytes': 3923992,
'downloader/response_count': 126,
'downloader/response_status_count/200': 126,
'elapsed_time_seconds': 152.081706,
'finish_time': datetime.datetime(2023, 11, 23, 10, 55, 47, 234679, …
> [Scrubsandbeyond] Add Q code to add NSI category

- locations/spiders/yves_rocher_it.py
{'atp/brand/Yves Rocher': 110,
'atp/brand_wikidata/Q1477321': 110,
'atp/category/shop/beauty': 110,
'atp/field/email/missing': 110,
'atp/field/twitter/missing': 110,
'atp/field/website/missing': 110,
'atp/nsi/brand_missing': 110,
'downloader/response_bytes': 17539,
'elapsed_time_seconds': 3.467926,
'finish_time': datetime.datetime(2023, 11, 23, 11, 22, 44, 595617, tzinfo=datetime.timezone.utc),
'httpcompression/response_bytes': 112402,
'item_scraped_count': 110,
'log_count/DEBUG': 123, …
> [YvesRocherIT] Add category

- locations/spiders/decathlon_fr.py
For almost all Decathlon spiders NSI match failed due [to multiple categories for the same wikidata](https://nsi.guide/?t=brands&tt=Q509349). This PR is adding category to `item_attributes` of `decathlon_fr` which all Decathlon spiders use.
> Fix category for all Decathlon spiders

- locations/spiders/leons_ca.py
{"atp/brand/Leon's": 89,
'atp/brand_wikidata/Q6524456': 89,
'atp/category/shop/furniture': 89,
'atp/field/name/missing': 89,
'atp/field/opening_hours/missing': 89,
'atp/field/postcode/missing': 89,
'atp/field/state/from_reverse_geocoding': 89,
'atp/field/website/missing': 89,
'atp/nsi/match_failed': 89,
'downloader/request_bytes': 433,
'downloader/response_bytes': 18593,
'elapsed_time_seconds': 1.258176,
'finish_time': …
> [LeonsCA] Add brand and category

- locations/spiders/liberty_au.py
{'atp/brand/Liberty Oil': 94,
'atp/brand_wikidata/Q106687078': 94,
'atp/category/amenity/fuel': 94,
'atp/field/email/missing': 94,
'atp/field/name/missing': 94,
'atp/field/website/missing': 93,
'atp/nsi/brand_missing': 94,
'downloader/request_bytes': 684,
'downloader/response_bytes': 86221,
'elapsed_time_seconds': 5.102635,
'finish_time': datetime.datetime(2023, 11, 23, 11, 42, 42, 20051, tzinfo=datetime.timezone.utc),
'item_scraped_count': 94, …
> [LibertyAU] Add category

- locations/spiders/handelsbanken_se.py
The only other location type that was scraped is CRS. Which I looked up and mean Cash Receiving System. I assume these are the same thing in the eyes of OSM.  I looked up 5 of the ones that were CRS (there were about 600) on google street view and they looked like ATMs to me. 
```python
{'atp/brand/Handelsbanken': 1465,
'atp/brand_wikidata/Q1421630': 1465,
'atp/category/amenity/atm': 1260,
'atp/category/amenity/bank': 205,
'atp/field/email/missing': 1260,
'atp/field/image/missing': 1465,
'atp/field/opening_hours/missing': 1264,
'atp/field/phone/missing': 1260,
'atp/field/state/missing': 1465,
'atp/field/twitter/missing': 1465,
'atp/field/website/invalid': 205,
'atp/field/website/missing': 1260,
'atp/nsi/category_match': 1465, …
```
> [handelsbanken_se] Added Category (1465 items)

- locations/spiders/jefferson_university_hospital.py
Added the clinic category as the type coming in from the response all said MedicalClinic.
Also I noticed that some of the names coming in were identical to the address, thus I changed up the name if that is the case.
```python
{'atp/brand/Jefferson University Hospital': 451,
'atp/brand_wikidata/Q59676202': 451,
'atp/category/amenity/clinic': 451,
'atp/category/multiple': 451,
'atp/field/country/from_reverse_geocoding': 446,
'atp/field/country/missing': 5,
'atp/field/email/missing': 451,
'atp/field/image/missing': 451,
'atp/field/opening_hours/missing': 451,
'atp/field/state/from_reverse_geocoding': 6,
'atp/field/twitter/missing': 451, …
```
> [jefferson_univ_hosp] Added Clinic category (451 items)

- locations/spiders/hibbett_sports.py
Did not have wikidata qcode for hibbett sports
```python
{'atp/brand/Hibbett Sports': 673,
'atp/brand_wikidata/Q5750671': 673,
'atp/category/shop/sports': 673,
'atp/field/email/missing': 669,
'atp/field/image/missing': 673,
'atp/field/state/from_reverse_geocoding': 6,
'atp/field/twitter/missing': 673,
'atp/field/website/missing': 673,
'atp/nsi/perfect_match': 673,
'downloader/request_bytes': 459,
'downloader/response_bytes': 48843, …
```
> [hibbett_sports] Added qcode for hibbett sports spider (673 items)

- locations/spiders/aveda.py
Category was not captured via NSI due to multiple entries.
```python
{'atp/brand/Aveda': 250,
'atp/brand_wikidata/Q4827965': 250,
'atp/category/amenity/training': 13,
'atp/category/multiple': 13,
'atp/category/shop/cosmetics': 237,
'atp/field/email/invalid': 9,
'atp/field/email/missing': 139,
'atp/field/image/missing': 250,
'atp/field/opening_hours/missing': 250,
'atp/field/phone/invalid': 25,
'atp/field/twitter/missing': 250,
'atp/field/website/invalid': 10,
'atp/field/website/missing': 138,
'atp/nsi/category_match': 126,
'atp/nsi/cc_match': 13,
'atp/nsi/match_failed': 111,
'downloader/request_bytes': 1280, …
```
> [aveda] Added category for aveda (250 items)

- locations/spiders/kfc_ru.py
Website's backend moved to a new URL.
Stats:
```json
{
"atp/brand/KFC": 678,
"atp/brand_wikidata/Q524757": 678,
"atp/category/amenity/fast_food": 678,
"atp/field/country/from_spider_name": 678,
"atp/field/email/missing": 678,
"atp/field/image/missing": 678,
"atp/field/lat/invalid": 1,
"atp/field/lat/missing": 17,
"atp/field/lon/invalid": 1,
"atp/field/lon/missing": 17,
"atp/field/phone/invalid": 234,
"atp/field/phone/missing": 16,
"atp/field/postcode/missing": 678,
"atp/field/state/missing": 678,
"atp/field/street_address/missing": 678,
"atp/field/twitter/missing": 678,
"atp/field/website/missing": 678,
"atp/nsi/cc_match": 678,
"downloader/request_bytes": 688, …
```
> [kfc_ru] fix broken spider

- locations/spiders/gov_cma_fuel_gb.py
https://www.gov.uk/guidance/access-fuel-price-data
This is "temporary" dataset for fuel prices, but it is nice for locations too. As it's big brands, it's 100% branded.
> Add CMA Fuel spider

- locations/spiders/baskin_robbins_us.py
They did have structured coords when I added it, but they seem to have changes the site :(
```python
{'atp/brand/Baskin-Robbins': 2207,
'atp/brand_wikidata/Q584601': 2207,
'atp/category/amenity/ice_cream': 2207,
'atp/cdn/cloudflare/response_count': 2233,
'atp/cdn/cloudflare/response_status_count/200': 2233,
'atp/field/email/missing': 2207,
'atp/field/lat/missing': 24,
'atp/field/lon/missing': 24,
'atp/field/phone/missing': 41,
'atp/nsi/cc_match': 2207,
'downloader/request_bytes': 1273204,
'downloader/request_count': 2233,
'downloader/request_method_count/GET': 2233,
'downloader/response_bytes': 61191555,
'downloader/response_count': 2233,
'downloader/response_status_count/200': 2233,
'elapsed_time_seconds': 25.568343, …
```
> [BaskinRobbinsUS] Collect coords again

- locations/spiders/hypovereinsbank_de.py
- locations/spiders/unicredit_de.py
I was going to add categories to unicredit_de but noticed that Unicredit is present in Germany under HypoVereinsbank brand for which we already have a spider with exactly the same data source and good categories.
> [unicredit_de] remove superfluous spider

- locations/spiders/lincolnshire_cooperative.py
There seems to be another lincolnshire wikidata [Q6551231](https://www.wikidata.org/wiki/Q6551231), This is in NSI as supermarkets, but from the ones I saw of the Co-ops they looked closer to convenience stores then full on grocery stores. 
```python
{'atp/brand/Lincolnshire Co-operative': 184,
'atp/brand_wikidata/Q5329759': 184,
'atp/category/amenity/cafe': 1,
'atp/category/amenity/fuel': 1,
'atp/category/amenity/pharmacy': 44,
'atp/category/missing': 3,
'atp/category/multiple': 44,
'atp/category/shop/convenience': 100,
'atp/category/shop/florist': 1,
'atp/category/shop/funeral_directors': 21,
'atp/category/shop/travel_agency': 13,
'atp/field/email/missing': 184,
'atp/field/image/dropped': 2,
'atp/field/image/invalid': 182,
'atp/field/image/missing': …
```
> [lincolnshire_cooperative] Added categories for different types of shops of lincolnshire (184 items)

- locations/spiders/dunelm_gb.py
Duplicate NSI Entries means category tag does not get added.
```python
{'atp/brand/Dunelm': 182,
'atp/brand_wikidata/Q5315020': 182,
'atp/category/shop/interior_decoration': 182,
'atp/field/image/missing': 182,
'atp/field/operator/missing': 182,
'atp/field/operator_wikidata/missing': 182,
'atp/field/state/missing': 113,
'atp/field/twitter/missing': 182,
'atp/nsi/category_match': 181,
'downloader/request_bytes': 1116,
'downloader/response_bytes': 170325, …
```
> [dunelm_gb] Added category for dunelm_gb (182 items)

- locations/spiders/under_armour.py
Duplicate NSI entries means it does not get the shop=clothes tag.
```python
{'atp/brand/Under Armour': 199,
'atp/brand_wikidata/Q2031485': 199,
'atp/category/shop/clothes': 199,
'atp/field/email/missing': 199,
'atp/field/opening_hours/missing': 199,
'atp/field/state/from_reverse_geocoding': 22,
'atp/field/twitter/missing': 199,
'atp/nsi/match_failed': 199,
'downloader/request_bytes': 80591,
'downloader/request_count': 202,
'downloader/request_method_count/GET': 202,
'downloader/response_bytes': 6466826,
'downloader/response_count': 202,
'downloader/response_status_count/200': 202,
'elapsed_time_seconds': 245.959147,
'finish_time': datetime.datetime(2023, 11, 30, 19, 37, 44, 340297, tzinfo=datetime.timezone.utc), …
```
> [under_armour] Added Clothes Category (199 items)

- locations/spiders/vtb_ru.py
Data on website has changed and this broke the spider. All good now.
Stats:
```json
{
"atp/brand/ВТБ": 1239,
"atp/brand_wikidata/Q1549389": 1239,
"atp/category/amenity/bank": 1239,
"atp/field/country/from_spider_name": 1239,
"atp/field/email/missing": 1239,
"atp/field/image/missing": 1239,
"atp/field/name/missing": 1239,
"atp/field/opening_hours/missing": 58,
"atp/field/operator/missing": 1239,
"atp/field/operator_wikidata/missing": 1239,
"atp/field/phone/missing": 1239,
"atp/field/postcode/missing": 1239,
"atp/field/state/missing": 1239,
"atp/field/street_address/missing": 1239,
"atp/field/twitter/missing": 1239,
"atp/field/website/missing": 1239,
"atp/nsi/category_match": 1239,
"downloader/request_bytes": 657, …
```
> [vtb_ru] fix broken spider

- locations/spiders/ricoh_europe.py
Could use a 2nd opinion about this company. Bloomberg says it is mainly a holding company. On it's main page and on it's linked in page it seems more of an IT consulting company. Thus I put the category as just an office company. Not sure if we should add this to NSI or if that is the correct category.
```python
{'atp/brand/Ricoh': 135,
'atp/category/office/company': 135,
'atp/field/brand_wikidata/missing': 135,
'atp/field/email/missing': 135,
'atp/field/image/missing': 135,
'atp/field/opening_hours/missing': 135,
'atp/field/operator/missing': 135,
'atp/field/operator_wikidata/missing': 135,
'atp/field/phone/invalid': 34,
'atp/field/twitter/missing': 135,
'atp/field/website/missing': 135,
'downloader/request_bytes': 8205, …
```
> 135 items)[ricoh_europe] Added category (135 items)

- locations/spiders/cox_health.py
Added some categories.
```python
{'atp/brand/CoxHealth': 55,
'atp/brand_wikidata/Q5179867': 55,
'atp/category/amenity/clinic': 22,
'atp/category/amenity/hospital': 3,
'atp/category/amenity/pharmacy': 3,
'atp/category/healthcare/dialysis': 4,
'atp/category/missing': 23,
'atp/category/multiple': 28,
'atp/field/opening_hours/missing': 55,
'atp/field/website/missing': 55,
'atp/nsi/brand_missing': 55,
'downloader/request_bytes': 37714,
'downloader/request_count': 86,
'downloader/request_method_count/GET': 86, …
```
> [cox_health] dded some Categories for Healthcare (55 items)

- locations/spiders/go_ape_gb.py
As aerialway is not a top level tag I added sports centre. Will to debate or change if there is another tag better suited for a ropes course with ziplining.
```python
{'atp/brand/Go Ape': 37,
'atp/brand_wikidata/Q5574692': 37,
'atp/category/leisure/sports_centre': 37,
'atp/cdn/cloudflare/response_count': 40,
'atp/cdn/cloudflare/response_status_count/200': 40,
'atp/field/email/missing': 37,
'atp/field/operator/missing': 37,
'atp/field/operator_wikidata/missing': 37,
'atp/field/phone/missing': 36,
'atp/nsi/brand_missing': 37,
'downloader/request_bytes': 16319, …
```
> [go_ape_gb] Added category for go ape gb (37 items)

- locations/spiders/ace_safes_gb.py
Do not think this needs to be added to NSI as there are very few safe retail stores. Also shop=safe is not used often.
```python
{'atp/brand/Ace Safes': 50,
'atp/brand_wikidata/Q119157844': 50,
'atp/category/shop/safe': 50,
'atp/field/country/from_spider_name': 50,
'atp/field/opening_hours/missing': 50,
'atp/field/postcode/missing': 50,
'atp/field/state/missing': 50,
'atp/field/street_address/missing': 50,
'atp/field/website/missing': 50,
'atp/nsi/brand_missing': 50, …
```
> [ace_safes_gb] Added category for Ace Safes GB (50 items)

- locations/categories.py
- locations/spiders/bridgestone_select.py
TBH I would be happy to just use `brand:wikidata=Q179433` and let pipeline to apply category from NSI, but I'm not sure if it's right to use a brand from NSI here. 
@davidhicks what do you think? [It looks like OSM has most of these POIs with `brand:wikidata=Q179433`.](https://overpass-turbo.eu/s/1Elt)
> [bridgestone_select] add category

- locations/spiders/gbfs.py
OSMs gbfs ref has always been `:` separated, not `-`. My bad.
There is currently a conversation about turning `ref:gbfs` into a namespace (`ref:gbfs:hellocycling=123`) instead of the current usage (`ref:gbfs=hellocycling:123`). I've changed it so we output both, the OSM community can decide which they want use.
> [GBFS] Improve ref

- locations/spiders/benchmarx_gb.py
```python
{'atp/brand/Benchmarx': 165,
'atp/brand_wikidata/Q102181127': 165,
'atp/category/shop/kitchen': 165,
'atp/field/image/missing': 165,
'atp/field/name/missing': 165,
'atp/field/operator/missing': 165,
'atp/field/operator_wikidata/missing': 165,
'atp/nsi/perfect_match': 165,
'downloader/request_bytes': 688,
'downloader/response_bytes': 407174,
'elapsed_time_seconds': 0.603349,
'finish_time': datetime.datetime(2023, 12, 11, 15, 14, 54, 766747, …
```
> [BenchmarxGB] Add spider

- locations/spiders/marks_ca.py
```python
{"atp/brand/Mark's": 379,
'atp/brand_wikidata/Q6766373': 379,
'atp/category/shop/clothes': 379,
'atp/field/city/missing': 379,
'atp/field/image/missing': 379,
'atp/field/name/missing': 379,
'atp/field/operator/missing': 379,
'atp/field/operator_wikidata/missing': 379,
'atp/field/twitter/missing': 379,
'atp/nsi/match_failed': 379,
'downloader/request_bytes': 759164,
'downloader/request_count': 386,
'downloader/request_method_count/GET': 386,
'downloader/response_bytes': 758255,
'downloader/response_count': 386,
'downloader/response_status_count/200': 381,
'downloader/response_status_count/400': 4, …
```
> [MarksCA] Add spider

- locations/spiders/voyagecare.py
```python
{'atp/brand/Voyage Care': 352,
'atp/category/amenity/social_facility': 352,
'atp/field/brand_wikidata/missing': 352,
'atp/field/city/missing': 125,
'atp/field/email/missing': 352,
'atp/field/image/missing': 352,
'atp/field/name/missing': 3,
'atp/field/opening_hours/missing': 352,
'atp/field/phone/missing': 352,
'atp/field/postcode/missing': 41,
'atp/field/state/missing': 63,
'atp/field/street_address/missing': 352,
'atp/field/twitter/missing': 352,
'downloader/response_bytes': 180833,
'elapsed_time_seconds': 8.164059,
'finish_time': …
```
> [voyagecare] Added Category (352 items)

- locations/spiders/bar_burrito_ca.py
Rel: https://github.com/osmlab/name-suggestion-index/pull/9029
```python
{'atp/brand/Barburrito': 326,
'atp/brand_wikidata/Q123765650': 326,
'atp/category/missing': 326,
'atp/field/email/missing': 326,
'atp/field/image/missing': 326,
'atp/field/name/missing': 326,
'atp/field/opening_hours/missing': 326,
'atp/field/operator/missing': 326,
'atp/field/operator_wikidata/missing': 326,
'atp/field/phone/missing': 39,
'atp/field/twitter/missing': 326,
'atp/nsi/brand_missing': 326,
'downloader/request_bytes': 675,
'downloader/response_bytes': 29578,
'elapsed_time_seconds': 2.411987, …
```
> [BarBurritoCA] Add spider

- locations/spiders/di.py
They sell many things. But to me it looks like Make up is the biggest product.
```python
{'atp/brand/Di': 105,
'atp/category/shop/cosmetics': 105,
'atp/field/brand_wikidata/missing': 105,
'atp/field/opening_hours/missing': 105,
'atp/field/operator/missing': 105,
'atp/field/operator_wikidata/missing': 105,
'atp/field/state/missing': 105,
'atp/field/street_address/missing': 105,
'atp/field/twitter/missing': 105,
'downloader/request_bytes': 803,
'downloader/response_bytes': 19009,
'elapsed_time_seconds': 1.567031,
'finish_time': …
```
> [di] Added cosmetics category for di brand (105 items)

- locations/spiders/fastned.py
- locations/spiders/fire_and_rescue_nsw_au.py
- locations/spiders/great_western_railway_gb.py
- locations/spiders/marks_and_spencer.py
- locations/spiders/midcounties_cooperative_gb.py
- locations/spiders/national_rail_gb.py
- locations/spiders/northern_railway_gb.py
- locations/spiders/nsw_ambulance_au.py
- locations/spiders/scotrail_gb.py
- locations/spiders/southeastern_railway_gb.py
- locations/spiders/transport_for_wales_gb.py
- locations/spiders/winterthur_ch.py
Commit fd3a6c24df32d7f9a2b06f8d5fb68bfe5b87f753 accidentally used "operator:wikidata" as a field of locations.items.Feature, instead of "operator_wikidata" (correct field name).
> Fix incorrect operator:wikidata field typos

- locations/spiders/optical_center.py
Rel: https://github.com/osmlab/name-suggestion-index/issues/9018
```python
{'atp/brand/Optical Center': 882,
'atp/brand_wikidata/Q3354448': 882,
'atp/category/shop/optician': 882,
'atp/field/operator/missing': 882,
'atp/field/operator_wikidata/missing': 882,
'atp/field/state/from_reverse_geocoding': 10,
'atp/field/state/missing': 872,
'atp/field/twitter/missing': 882,
'atp/nsi/perfect_match': 882,
'downloader/request_bytes': 504184,
'downloader/request_count': 920,
'downloader/request_method_count/GET': 920,
'downloader/response_bytes': 35732726,
'downloader/response_count': 920,
'downloader/response_status_count/200': 884,
'downloader/response_status_count/301': 36, …
```
> [OpticalCenter] Add spider

- locations/hours.py
- locations/spiders/willys_se.py
```python
{'atp/brand/Willys': 234,
'atp/brand_wikidata/Q10720214': 234,
'atp/category/shop/supermarket': 234,
'atp/field/country/from_spider_name': 234,
'atp/field/email/missing': 234,
'atp/field/image/missing': 234,
'atp/field/name/missing': 234,
'atp/field/operator/missing': 234,
'atp/field/operator_wikidata/missing': 234,
'atp/field/state/missing': 234,
'atp/field/twitter/missing': 234,
'atp/nsi/perfect_match': 234,
'downloader/request_bytes': 648,
'downloader/response_bytes': 21497,
'elapsed_time_seconds': 0.633671,
'finish_time': datetime.datetime(2023, 12, 21, …
```
> [WillysSE] Add spider

- locations/spiders/black_red_white_pl.py
The site is giving `https://www.brw.pl/logo.svg` as all the refs, I guess that's why the `no_refs` was enabled. However we can use the url as the ref.
> [BlackRedWhitePL] Fix refs

- locations/spiders/neuroth.py
Rel: https://github.com/osmlab/name-suggestion-index/pull/9061
```python
{'atp/brand/Neuroth': 438,
'atp/brand_wikidata/Q15836645': 438,
'atp/category/shop/hearing_aids': 438,
'atp/field/image/missing': 438,
'atp/field/name/missing': 438,
'atp/field/operator/missing': 438,
'atp/field/operator_wikidata/missing': 438,
'atp/field/state/missing': 438,
'atp/field/twitter/missing': 438,
'atp/nsi/perfect_match': 438,
'downloader/request_bytes': 4571,
'downloader/request_count': 14,
'downloader/request_method_count/GET': 14,
'downloader/response_bytes': 75319,
'downloader/response_count': 14,
'downloader/response_status_count/200': 14,
'elapsed_time_seconds': 0.969645,
'finish_time': …
```
> [Neuroth] Add spider

- locations/spiders/hemkop_se.py
Adding spider for Hemköp (a Swedish supermarket chain).
```bash
{'atp/brand/Hemköp': 199,
'atp/brand_wikidata/Q10521746': 199,
'atp/category/shop/supermarket': 199,
'atp/field/country/from_spider_name': 199,
'atp/field/email/missing': 199,
'atp/field/image/missing': 199,
'atp/field/name/missing': 199,
'atp/field/operator/missing': 199,
'atp/field/operator_wikidata/missing': 199,
'atp/field/state/missing': 199,
'atp/field/twitter/missing': 199,
'atp/nsi/perfect_match': 199,
'downloader/request_bytes': 648,
'downloader/response_bytes': 18691,
'elapsed_time_seconds': 3.213838, …
```
> Hemköp SE (Supermarket chain Sweden) adding spider (199 items)

- locations/items.py
- locations/spiders/bupa_gb.py
- tests/test_closed.py
Fixes #6562
" - Closed" seems to be a really common suffix, maybe we should move this to a pipeline at some stage.
```python
{'atp/brand/Bupa': 388,
'atp/brand/Total Dental Care': 5,
'atp/brand_wikidata/Q931628': 393,
'atp/category/amenity/dentist': 393,
'atp/category/multiple': 393,
'atp/cdn/cloudflare/response_count': 398,
'atp/cdn/cloudflare/response_status_count/200': 398,
'atp/field/city/missing': 393,
'atp/field/country/from_spider_name': 365,
'atp/field/email/missing': 393,
'atp/field/opening_hours/missing': 393,
'atp/field/operator/missing': 393,
'atp/field/operator_wikidata/missing': 393,
'atp/field/state/missing': 393,
'atp/nsi/category_match': 393,
'downloader/request_bytes': 179405,
'downloader/request_count': 399, …
```
> [BupaGB] Flag closed POIs

- locations/spiders/hemkop_se.py
- locations/spiders/ica_se.py
```
{'atp/brand/ICA': 1322,
'atp/brand_wikidata/Q1663776': 1322,
'atp/category/shop/supermarket': 1322,
'atp/field/email/missing': 1322,
'atp/field/image/dropped': 1322,
'atp/field/image/missing': 1322,
'atp/field/lat/missing': 12,
'atp/field/lon/missing': 12,
'atp/field/operator/missing': 1322,
'atp/field/operator_wikidata/missing': 1322,
'atp/field/state/missing': 1322,
'atp/nsi/match_failed': 1322,
'downloader/request_bytes': 793403,
'downloader/request_count': 1342,
'downloader/request_method_count/GET': 1342,
'downloader/response_bytes': 55826198,
'downloader/response_count': 1342,
'downloader/response_status_count/200': 1341,
'elapsed_time_seconds': 1626.437517, …
```
> Add spider for ICA supermarkets in Sweden (1322 entries)

- locations/spiders/petstock_au.py
Gracefully ignore holiday hours instead of causing an error.
> petstock_au: fix spider

- locations/spiders/lincraft_au.py
Simplify opening hours extraction and ensure it gracefully fails when holiday opening hours are present. Unfortunately normal business hours are replaced with holiday hours, so around holiday times, this spider won't return opening hours information.
> lincraft_au: fix spider

- locations/spiders/pague_menos_br.py
Fixes #6602
```python
{'atp/brand/Pague Menos': 1104,
'atp/brand_wikidata/Q7124466': 1104,
'atp/category/amenity/pharmacy': 1104,
'atp/category/multiple': 1104,
'atp/field/country/from_spider_name': 1104,
'atp/field/email/missing': 1104,
'atp/field/image/missing': 1104,
'atp/field/lat/missing': 1104,
'atp/field/lon/missing': 1104,
'atp/field/name/missing': 1104,
'atp/field/opening_hours/missing': 1104,
'atp/field/operator/missing': 1104,
'atp/field/operator_wikidata/missing': 1104,
'atp/field/phone/invalid': 54,
'atp/field/twitter/missing': 1104,
'atp/nsi/perfect_match': 1104,
'downloader/request_bytes': 1577,
'downloader/response_bytes': 2793591, …
```
> [PagueMenosBR] Add Spider

- locations/spiders/blackberrys_in.py
Rel: https://github.com/osmlab/name-suggestion-index/commit/7acec782848b55ebddda833ddc6c18ba71a3bbd5
```python
{'atp/category/missing': 354,
'atp/field/brand/missing': 354,
'atp/field/brand_wikidata/missing': 354,
'atp/field/email/missing': 354,
'atp/field/image/missing': 354,
'atp/field/opening_hours/missing': 354,
'atp/field/operator/missing': 354,
'atp/field/operator_wikidata/missing': 354,
'atp/field/twitter/missing': 354,
'downloader/request_bytes': 172121,
'downloader/request_count': 428,
'downloader/request_method_count/GET': 428,
'downloader/response_bytes': 7359030,
'downloader/response_count': 428,
'downloader/response_status_count/200': 416,
'downloader/response_status_count/404': 12,
'dupefilter/filtered': 120,
'elapsed_time_seconds': 510.855306, …
```
> [BlackberrysIN] Add spider

- locations/spiders/a1_si.py
I've set this to shop=telecommunications rather than shop=mobile because they sell services related to mobiles but also phones and broadband/TV/entertainment packages.
{'atp/brand/A1': 57,
'atp/brand_wikidata/Q68755': 57,
'atp/category/shop/telecommunication': 57,
'atp/field/country/from_reverse_geocoding': 57,
'atp/field/email/missing': 57,
'atp/field/image/missing': 57,
'atp/field/operator/missing': 57,
'atp/field/operator_wikidata/missing': 57,
'atp/field/twitter/missing': 57,
'atp/field/website/missing': 57,
'atp/nsi/brand_missing': 57,
'downloader/request_bytes': 764,
'downloader/response_bytes': 263515,
'elapsed_time_seconds': 3.969052, …
> [A1SI] Fix category

- locations/spiders/ferguson_plarres_bakehouse_au.py
Fix category by using correct wikidata code, which allows NSI to be matched.
```python
{"atp/brand/Ferguson Plarre's Bakehouse": 79,
'atp/brand_wikidata/Q5444249': 79,
'atp/category/shop/bakery': 79,
'atp/field/image/missing': 79,
'atp/field/operator/missing': 79,
'atp/field/operator_wikidata/missing': 79,
'atp/field/street_address/missing': 79,
'atp/field/twitter/missing': 79,
'atp/nsi/perfect_match': 79,
'downloader/request_bytes': 793,
'downloader/response_bytes': 258452,
'elapsed_time_seconds': 3.869256,
'finish_time': …
```
> [FergusonPlarresBakehouseAU] Use correct wikidata code

- locations/spiders/photome_gb.py
```python
{'atp/brand/Photo-Me': 3553,
'atp/brand_wikidata/Q123456627': 3553,
'atp/category/amenity/photo_booth': 3553,
'atp/field/city/missing': 3553,
'atp/field/country/from_spider_name': 3553,
'atp/field/email/missing': 3553,
'atp/field/image/missing': 3553,
'atp/field/opening_hours/missing': 3553,
'atp/field/operator/missing': 3553,
'atp/field/operator_wikidata/missing': 3553,
'atp/field/phone/missing': 3553,
'atp/field/state/missing': 3553,
'atp/field/street_address/missing': 3553,
'atp/field/twitter/missing': 3553,
'atp/field/website/missing': 3553,
'atp/nsi/perfect_match': 3553,
'downloader/request_bytes': 3446,
'downloader/response_bytes': 143737,
'downloader/response_count': 5, …
```
> [PhotoMeGB] Add spider

- locations/spiders/tcc_us.py
```python
{'atp/brand/Verizon': 498,
'atp/brand_wikidata/Q919641': 498,
'atp/category/shop/mobile_phone': 498,
'atp/cdn/cloudflare/response_count': 500,
'atp/cdn/cloudflare/response_status_count/200': 500,
'atp/field/email/missing': 498,
'atp/nsi/perfect_match': 498,
'atp/operator/The Cellular Connection': 498,
'atp/operator_wikidata/Q121336519': 498,
'downloader/request_bytes': 277043,
'downloader/request_count': 500,
'downloader/request_method_count/GET': 500,
'downloader/response_bytes': 6111818,
'downloader/response_count': 500,
'downloader/response_status_count/200': 500,
'elapsed_time_seconds': 499.057112,
'finish_time': datetime.datetime(2024, 1, 9, 15, 14, 43, 536188, …
```
> [TccUS] Add Spider

- locations/categories.py
- locations/dict_parser.py
- locations/spiders/williams_sonoma_us_ca.py
New API is used, and this also returns Pottery Barn locations since this brand was acquired by Williams-Sonoma.
'atp/brand/Pottery Barn': 168,
'atp/brand/Williams-Sonoma': 156,
> williams_sonoma_us_ca: fix spider

- locations/spiders/cgi_group.py
{'atp/brand/CGI Group': 282,
'atp/brand_wikidata/Q1798370': 282,
'atp/category/office/company': 282,
'atp/field/country/missing': 282,
'atp/field/email/missing': 282,
'atp/field/image/missing': 282,
'atp/field/lat/missing': 282,
'atp/field/lon/missing': 282,
'atp/field/opening_hours/missing': 282,
'atp/field/operator/missing': 282,
'atp/field/operator_wikidata/missing': 282,
'atp/field/phone/invalid': 56,
'atp/field/phone/missing': 48,
'atp/field/state/missing': 282,
'atp/field/street_address/missing': 282,
'atp/field/twitter/missing': 282,
'atp/field/website/missing': 282,
'atp/nsi/brand_missing': 282,
'downloader/request_bytes': 718,
'downloader/response_bytes': 81074, …
> [CGIGroup] Add category

- locations/spiders/maxol_ie.py
```python
{'atp/brand/Maxol': 240,
'atp/brand_wikidata/Q3302837': 240,
'atp/category/amenity/fuel': 240,
'atp/cdn/cloudflare/response_count': 243,
'atp/cdn/cloudflare/response_status_count/200': 243,
'atp/field/email/missing': 240,
'atp/field/image/missing': 240,
'atp/field/operator/missing': 240,
'atp/field/operator_wikidata/missing': 240,
'atp/field/phone/missing': 240,
'atp/field/twitter/missing': 240,
'atp/nsi/category_match': 240,
'downloader/request_bytes': 91241,
'downloader/request_count': 243,
'downloader/request_method_count/GET': 243,
'downloader/response_bytes': 2916116,
'downloader/response_count': 243,
'downloader/response_status_count/200': 243,
'elapsed_time_seconds': 1.559781, …
```
> [MaxolIE] Collect coords

- locations/spiders/caesars.py
I've made this "resort" rather than "hotel" because this venue sells gambling services primarily rather than hotel services (ref [this page](https://wiki.openstreetmap.org/wiki/Tag:leisure%3Dresort))
So, leisure=resort and amenity=casino.
{'atp/brand/Caesars Entertainment': 58,
'atp/brand_wikidata/Q18636524': 58,
'atp/category/amenity/casino': 58,
'atp/category/multiple': 58,
'atp/field/image/missing': 58,
'atp/field/opening_hours/missing': 58,
'atp/field/operator/missing': 58,
'atp/field/operator_wikidata/missing': 58,
'atp/field/twitter/missing': 58, …
> [Caesars] Add category

- locations/spiders/big_10_mart_us.py
{'atp/brand/Big 10 Mart': 17,
'atp/brand_wikidata/Q116867087': 17,
'atp/category/shop/convenience': 17,
'atp/field/country/from_reverse_geocoding': 17,
'atp/nsi/brand_missing': 17,
'downloader/response_bytes': 9134,
'elapsed_time_seconds': 2.271411, …
> [Big10MartUS] Apply category

- locations/spiders/adriatic_furniture_au.py
{'atp/brand/Adriatic Furniture': 8,
'atp/brand_wikidata/Q117856796': 8,
'atp/category/shop/furniture': 8,
'atp/nsi/brand_missing': 8,
'downloader/request_bytes': 731,
'downloader/response_bytes': 2202,
'elapsed_time_seconds': 3.375364,
'finish_time': datetime.datetime(2024, 1, 11, 14, 31, 56, 452400, tzinfo=datetime.timezone.utc),
'httpcompression/response_bytes': 7924, …
> [AdriaticFurnitureAU] Add category

- locations/spiders/teds_camera_stores_au.py
{"atp/brand/Ted's Camera Stores": 19,
'atp/brand_wikidata/Q117958394': 19,
'atp/category/shop/camera': 19,
'atp/field/postcode/missing': 19,
'atp/field/street_address/missing': 19,
'atp/nsi/brand_missing': 19,
'downloader/request_bytes': 9778,
'downloader/request_count': 21,
'downloader/request_method_count/GET': 20,
'downloader/response_bytes': 1637320,
'downloader/response_count': 21,
'downloader/response_status_count/200': 21,
'elapsed_time_seconds': 24.806141,
'finish_time': …
> [TedsCameraStoresAU] Add category

- locations/spiders/louisa_coffee.py
Use wikidata code from NSI to fix category
{'atp/brand/Louisa Coffee': 10,
'atp/brand_wikidata/Q96390921': 10,
'atp/category/amenity/cafe': 10,
'atp/field/country/from_reverse_geocoding': 10,
'atp/field/lat/missing': 7,
'atp/field/lon/missing': 7,
'atp/geometry/null_island': 7,
'downloader/request_bytes': 1562, …
> [LouisaCoffee] Fix wikidata code

- locations/spiders/sephora_br.py
NSI category does not resolve because there is amenity/vending_machine as well as shop/cosmetics. So set explicitly.
{'atp/brand/Sephora': 34,
'atp/brand_wikidata/Q2408041': 34,
'atp/category/shop/cosmetics': 34,
'atp/field/city/missing': 34,
'atp/field/country/from_spider_name': 34,
'atp/field/email/missing': 34,
'atp/field/image/missing': 34,
'atp/field/opening_hours/missing': 34,
'atp/field/operator/missing': 34,
'atp/field/operator_wikidata/missing': 34,
'atp/field/state/missing': 34,
'atp/field/street_address/missing': 34,
'atp/field/twitter/missing': 34,
'atp/field/website/missing': 34,
'atp/nsi/category_match': 34,
'downloader/request_bytes': 529, …
> [SephoraBR] Add category

- locations/spiders/lundsandbyerlys.py
{'atp/brand/Lunds & Byerlys': 29,
'atp/brand_wikidata/Q19903424': 29,
'atp/category/shop/supermarket': 29,
'atp/field/website/invalid': 27,
'atp/nsi/brand_missing': 29,
'downloader/request_bytes': 679,
'downloader/response_bytes': 3061,
'elapsed_time_seconds': 2.15833,
'finish_time': datetime.datetime(2024, 1, 11, 10, 51, 48, 174253, tzinfo=datetime.timezone.utc),
'httpcompression/response_bytes': 11220, …
> [LundsAndByerlys] Add category

- locations/spiders/aldi_nord_dk.py
{'atp/brand/ALDI': 15,
'atp/brand_wikidata/Q41171373': 15,
'atp/category/shop/supermarket': 15,
'atp/field/website/missing': 15,
'atp/nsi/match_failed': 15,
'downloader/request_bytes': 681,
'downloader/response_bytes': 2864,
'elapsed_time_seconds': 1.522757,
'finish_time': datetime.datetime(2024, 1, 11, 12, 51, 26, 113042, tzinfo=datetime.timezone.utc),
'httpcompression/response_bytes': 12187, …
> [AldiNordDK] Add category

- locations/spiders/camping_world_au.py
{'atp/brand/Camping World': 13,
'atp/brand_wikidata/Q124062618': 13,
'atp/category/shop/outdoor': 13,
'atp/field/country/from_spider_name': 13,
'atp/field/website/missing': 13,
'atp/nsi/brand_missing': 13,
'downloader/request_bytes': 813,
'downloader/response_bytes': 3854,
'elapsed_time_seconds': 4.492398,
'finish_time': datetime.datetime(2024, 1, 12, 9, 50, 50, 516025, tzinfo=datetime.timezone.utc),
'httpcompression/response_bytes': 17020, …
> [CampingWorldAU] Add category

- locations/spiders/habitania_au.py
{'atp/brand/Habitania': 14,
'atp/brand_wikidata/Q117923291': 14,
'atp/category/shop/houseware': 14,
'atp/field/country/from_spider_name': 14,
'atp/nsi/brand_missing': 14,
'downloader/request_bytes': 723,
'downloader/response_bytes': 2616,
'elapsed_time_seconds': 2.789785,
'finish_time': …
> [HabitaniaAU] Add category

- locations/spiders/big_louies_us.py
{"atp/brand/Big Louie's": 6,
'atp/brand_wikidata/Q119157997': 6,
'atp/category/amenity/restaurant': 6,
'atp/field/country/from_spider_name': 5,
'atp/field/state/from_reverse_geocoding': 6,
'atp/field/street_address/missing': 6,
'atp/nsi/brand_missing': 6,
'downloader/response_bytes': 8871, …
> [BigLouiesUS] Add category

- locations/spiders/bioped_ca.py
Rel: https://github.com/osmlab/name-suggestion-index/pull/8932
```python
{'atp/brand/BioPed': 96,
'atp/brand_wikidata/Q123409898': 96,
'atp/category/missing': 96,
'atp/field/image/missing': 96,
'atp/field/opening_hours/missing': 96,
'atp/field/twitter/missing': 96,
'atp/nsi/brand_missing': 96,
'downloader/request_bytes': 708,
'downloader/response_bytes': 12886, …
```
> [BiopedCA] Add spider

- locations/spiders/nicholsons_pubs_gb.py
```python
{"atp/brand/Nicholson's": 77,
'atp/brand_wikidata/Q113130666': 77,
'atp/category/amenity/pub': 77,
'atp/cdn/cloudflare/response_count': 81,
'atp/cdn/cloudflare/response_status_count/200': 80,
'atp/field/email/missing': 77,
'atp/field/image/missing': 77,
'atp/field/operator/missing': 77,
'atp/field/operator_wikidata/missing': 77,
'atp/nsi/perfect_match': 77,
'downloader/request_bytes': 33087,
'downloader/request_count': 81,
'downloader/request_method_count/GET': 81,
'downloader/response_bytes': 1516803,
'downloader/response_count': 81,
'downloader/response_status_count/200': 80,
'elapsed_time_seconds': 1.370684, …
```
> [NicholsonsPubsGB] Add Spider

- locations/spiders/beefeater_gb.py
```python
{'atp/brand/Beefeater': 172,
'atp/brand_wikidata/Q4879766': 172,
'atp/category/amenity/restaurant': 172,
'atp/field/city/missing': 172,
'atp/field/country/from_spider_name': 172,
'atp/field/email/missing': 172,
'atp/field/image/missing': 172,
'atp/field/opening_hours/missing': 172,
'atp/field/operator/missing': 172,
'atp/field/operator_wikidata/missing': 172,
'atp/field/state/missing': 172,
'atp/field/twitter/missing': 172,
'atp/nsi/perfect_match': 172,
'downloader/request_bytes': 637,
'downloader/response_bytes': 13333,
'elapsed_time_seconds': 0.867883, …
```
> [BeefeaterGB] Add spider

- locations/spiders/karwei_nl.py
```python
{'atp/brand/Karwei': 130,
'atp/brand_wikidata/Q2097480': 130,
'atp/category/shop/doityourself': 130,
'atp/field/country/from_spider_name': 130,
'atp/field/email/missing': 130,
'atp/field/image/missing': 130,
'atp/field/operator/missing': 130,
'atp/field/operator_wikidata/missing': 130,
'atp/field/state/missing': 130,
'atp/field/twitter/missing': 130,
'atp/nsi/perfect_match': 130,
'downloader/request_bytes': 72872,
'downloader/request_count': 133,
'downloader/request_method_count/GET': 133,
'downloader/response_bytes': 1561196,
'downloader/response_count': 133,
'downloader/response_status_count/200': 132, …
```
> [KarweiNL] Add spider

- locations/spiders/dpd_de.py
```python
{'atp/brand/DPD': 5040,
'atp/brand_wikidata/Q541030': 5040,
'atp/category/missing': 5040,
'atp/field/country/from_spider_name': 5040,
'atp/field/email/missing': 5040,
'atp/field/image/missing': 5040,
'atp/field/opening_hours/missing': 4635,
'atp/field/operator/missing': 5040,
'atp/field/operator_wikidata/missing': 5040,
'atp/field/phone/missing': 5040,
'atp/field/state/missing': 5040,
'atp/field/street_address/missing': 5040,
'atp/field/twitter/missing': 5040,
'atp/field/website/missing': 5040,
'atp/nsi/match_failed': 5040,
'downloader/request_bytes': 244433252,
'downloader/request_count': 10940,
'downloader/request_method_count/POST': 10937,
'downloader/response_bytes': 954977886,
'downloader/response_count': 10940, …
```
> [DPD DE] Fix opening hours

- locations/spiders/nhs_scotland_gb.py
```python
{'atp/category/amenity/clinic': 66,
'atp/category/amenity/dentist': 988,
'atp/category/amenity/doctors': 1071,
'atp/category/amenity/hospital': 141,
'atp/category/amenity/pharmacy': 930,
'atp/category/multiple': 3196,
'atp/category/shop/optician': 462,
'atp/field/brand/missing': 3658,
'atp/field/brand_wikidata/missing': 3658,
'atp/field/city/missing': 3658,
'atp/field/country/from_spider_name': 3658,
'atp/field/email/missing': 3658,
'atp/field/image/missing': 3658,
'atp/field/lat/missing': 74,
'atp/field/lon/missing': 74,
'atp/field/name/missing': 42,
'atp/field/opening_hours/missing': 118,
'atp/field/operator/missing': 3658,
'atp/field/operator_wikidata/missing': 3658,
'atp/field/phone/missing': 3658,
'atp/field/state/missing': 3658, …
```
> [NHSScotlandGB] Fix spider

- locations/spiders/cooplands_doncaster_gb.py
Change to use wikidata code referenced by NSI.
Rename spider to pickup country code from name.
{'atp/brand/Cooplands': 24,
'atp/brand_wikidata/Q5167971': 24,
'atp/category/shop/bakery': 24,
'atp/field/city/missing': 24,
'atp/field/country/from_spider_name': 24,
'atp/field/email/missing': 24,
'atp/field/lat/missing': 24,
'atp/field/lon/missing': 24,
'atp/field/street_address/missing': 24,
'atp/field/website/missing': 24,
'atp/nsi/perfect_match': 24,
'downloader/request_bytes': 662,
'downloader/response_bytes': 7085, …
> [CooplandsDoncasterGB] Add category

- locations/spiders/the_barre_code_us.py
{'atp/brand/The Barre Code': 25,
'atp/brand_wikidata/Q118870170': 25,
'atp/category/leisure/fitness_centre': 25,
'atp/cdn/cloudflare/response_count': 27,
'atp/cdn/cloudflare/response_status_count/200': 27,
'atp/field/country/from_spider_name': 25,
'atp/field/postcode/missing': 25,
'atp/field/state/from_reverse_geocoding': 25,
'atp/field/street_address/missing': 25,
'atp/nsi/brand_missing': 25,
'downloader/request_bytes': 10056,
'downloader/request_count': 27,
'downloader/request_method_count/GET': 27,
'downloader/response_bytes': 287578,
'downloader/response_count': 27, …
> [TheBarreCodeUS] Add category

- locations/spiders/speedy_stop_us.py
{'atp/brand/Speedy Stop': 26,
'atp/brand_wikidata/Q123419843': 26,
'atp/category/amenity/fuel': 26,
'atp/field/city/missing': 26,
'atp/field/country/from_spider_name': 26,
'atp/field/postcode/missing': 26,
'atp/field/state/from_reverse_geocoding': 26,
'atp/field/street_address/missing': 26,
'atp/nsi/brand_missing': 26, …
> [SpeedyStopUS] Add category

- locations/spiders/cue.py
Was yielding 1 POI due to no ref being set. Now:
{'atp/brand/Cue': 36,
'atp/brand_wikidata/Q5192554': 36,
'atp/category/shop/clothes': 36,
'atp/cdn/cloudflare/response_count': 11,
'atp/cdn/cloudflare/response_status_count/200': 11,
'atp/field/website/missing': 36,
'atp/nsi/brand_missing': 36,
'downloader/request_bytes': 3969,
'downloader/request_count': 11,
'downloader/request_method_count/POST': 10,
'downloader/response_bytes': 18210,
'downloader/response_count': 11, …
> [Cue] Add category and ref

- locations/spiders/xtreme_communications_au.py
{'atp/brand/Xtreme Communications': 8,
'atp/brand_wikidata/Q116866326': 8,
'atp/category/shop/mobile_phone': 8,
'atp/field/city/missing': 8,
'atp/field/country/from_spider_name': 6,
'atp/nsi/brand_missing': 8,
'downloader/response_bytes': 7694,
'elapsed_time_seconds': 2.084781, …
> [XtremeCommunicationsAU] Add category

- locations/spiders/doors_plus_au.py
{'atp/brand/Doors Plus': 22,
'atp/brand_wikidata/Q78945358': 22,
'atp/category/shop/doors': 22,
'atp/nsi/brand_missing': 22,
'downloader/request_bytes': 681,
'downloader/response_bytes': 4477,
'elapsed_time_seconds': 3.328035,
'finish_time': datetime.datetime(2024, 1, 16, 8, 58, 8, 327025, tzinfo=datetime.timezone.utc),
'httpcompression/response_bytes': 35242,
'item_scraped_count': 22,
'log_count/DEBUG': 35, …
> [DoorsPlusAU] Add category

- locations/spiders/great_wolf_us.py
{'atp/brand/ Great Wolf Resorts': 21,
'atp/brand_wikidata/Q5600260': 21,
'atp/category/leisure/water_park': 21,
'atp/cdn/cloudflare/response_count': 23,
'atp/cdn/cloudflare/response_status_count/200': 23,
'atp/field/country/from_spider_name': 21,
'atp/field/opening_hours/missing': 21,
'atp/nsi/brand_missing': 21,
'downloader/request_bytes': 11467,
'downloader/request_count': 23,
'downloader/request_method_count/GET': 23,
'downloader/response_bytes': 305147,
'downloader/response_count': 23,
'downloader/response_status_count/200': 23, …
> [GreatWolfResortsUS] Add category

- locations/spiders/caffe_nero_gb.py
Fixes #6729
```python
{'atp/brand/Caffe Nero': 582,
'atp/brand/Nero Express': 33,
'atp/brand_wikidata/Q675808': 615,
'atp/category/amenity/cafe': 615,
'atp/field/city/missing': 615,
'atp/field/country/from_spider_name': 615,
'atp/field/email/missing': 615,
'atp/field/image/missing': 615,
'atp/field/name/missing': 615,
'atp/field/operator/missing': 615,
'atp/field/operator_wikidata/missing': 615,
'atp/field/state/missing': 615,
'atp/field/street_address/missing': 615,
'atp/field/twitter/missing': 615,
'atp/nsi/match_failed': 615,
'downloader/request_bytes': 2244,
'downloader/response_bytes': 588666, …
```
> [CaffeNeroGB] Use live url

- locations/spiders/poundland.py
Possibly fixes #6673, I want @rjw62 to review.
The drops the numbers:
```patch
'atp/brand/Pep&Co': 769,
- 'atp/brand/Poundland': 807,
+ 'atp/brand/Poundland': 793,
```
But it leaves us with some ones that I'm questioning. They end up with 3 pois in proximity, a Poundland with it's Pep and a near by Pep (Which used to have a Poundland). They may be bad source data, or they may be valid.
1. B25 8UJ
2. PE21 6EH/PE21 6QX
3. L20 4XX
4. N9 0TZ
> [Poundland] Drop extra locations

- locations/spiders/videopro_au.py
{'atp/brand/Videopro': 3,
'atp/brand_wikidata/Q120648551': 3,
'atp/category/shop/electronics': 3,
'downloader/request_bytes': 1451,
'downloader/response_bytes': 6009,
'elapsed_time_seconds': 3.817519,
'finish_time': datetime.datetime(2024, 1, 16, 11, 37, 52, …
> [VideoproAU] Add category

- locations/spiders/potters_ace_home_center_us.py
{"atp/brand/Potter's Ace Home Center": 21,
'atp/brand_wikidata/Q119141289': 21,
'atp/category/shop/doityourself': 21,
'atp/field/city/missing': 21,
'atp/field/state/from_reverse_geocoding': 21,
'atp/field/website/missing': 21,
'atp/nsi/brand_missing': 21,
'downloader/response_bytes': 7773,
'elapsed_time_seconds': 2.61411, …
> [PottersAceHomeCenterUS] Add category

- locations/spiders/fitness19_us.py
Rel: https://github.com/osmlab/name-suggestion-index/pull/9142
```python
{'atp/brand/Fitness 19': 76,
'atp/brand_wikidata/Q121787953': 76,
'atp/category/missing': 76,
'atp/field/country/from_spider_name': 76,
'atp/field/image/dropped': 76,
'atp/field/image/missing': 76,
'atp/field/opening_hours/missing': 76,
'atp/field/operator/missing': 76,
'atp/field/operator_wikidata/missing': 76,
'atp/nsi/brand_missing': 76,
'downloader/request_bytes': 32993,
'downloader/request_count': 78,
'downloader/request_method_count/GET': 78,
'downloader/response_bytes': 3461824,
'downloader/response_count': 78,
'downloader/response_status_count/200': 78,
'elapsed_time_seconds': 1.654713, …
```
> [Fitness19US] Add spider

- locations/spiders/fastrac_cafe_us.py
NSI has the fuel station as well as the advertising totem, so set the category explicitly.
{'atp/brand/Fastrac Cafe': 70,
'atp/brand_wikidata/Q117324848': 70,
'atp/category/amenity/fuel': 70,
'atp/field/country/from_spider_name': 70,
'atp/field/email/missing': 70,
'atp/field/image/missing': 70,
'atp/field/opening_hours/missing': 70,
'atp/field/operator/missing': 70,
'atp/field/operator_wikidata/missing': 70,
'atp/field/twitter/missing': 70,
'atp/nsi/category_match': 70,
'downloader/request_bytes': 848,
'downloader/response_bytes': 7432,
'elapsed_time_seconds': 1.996971, …
> [Fastrac] Add category

- locations/spiders/spar_pl.py
{'atp/brand/Eurospar': 34,
'atp/brand/Spar': 186,
'atp/brand_wikidata/Q12309283': 34,
'atp/brand_wikidata/Q610492': 186,
'atp/category/shop/convenience': 186,
'atp/category/shop/supermarket': 34,
'atp/field/country/from_spider_name': 220,
'atp/field/email/missing': 220,
'atp/field/image/missing': 220,
'atp/field/name/missing': 186,
'atp/field/opening_hours/missing': 220,
'atp/field/operator/missing': 220,
'atp/field/operator_wikidata/missing': 220,
'atp/field/phone/missing': 220,
'atp/field/state/missing': 220,
'atp/field/twitter/missing': 220,
'atp/nsi/match_failed': 186,
'atp/nsi/perfect_match': 34,
'downloader/request_bytes': 707, …
> [SparPL] Add category

- locations/spiders/northern_california_breweries.py
{'atp/category/craft/brewery': 343,
'atp/field/brand/missing': 343,
'atp/field/brand_wikidata/missing': 343,
'atp/field/email/missing': 343,
'atp/field/image/missing': 343,
'atp/field/lat/missing': 343,
'atp/field/lon/missing': 343,
'atp/field/name/missing': 343,
'atp/field/opening_hours/missing': 343,
'atp/field/operator/missing': 343,
'atp/field/operator_wikidata/missing': 343,
'atp/field/phone/missing': 343,
'atp/field/postcode/missing': 343,
'atp/field/twitter/missing': 343,
'downloader/request_bytes': 2681,
'downloader/response_bytes': 236074,
'downloader/response_count': 6,
'downloader/response_status_count/301': 3, …
> [NorthernCaliforniaBreweries] Add category

- locations/spiders/coen_markets_us.py
{'atp/brand/Coen Markets Inc': 54,
'atp/brand_wikidata/Q122856721': 54,
'atp/category/shop/convenience': 54,
'atp/field/city/missing': 54,
'atp/field/country/from_spider_name': 54,
'atp/field/postcode/missing': 54,
'atp/field/state/from_reverse_geocoding': 54,
'atp/field/street_address/missing': 54,
'atp/field/website/missing': 54,
'downloader/request_bytes': 820,
'downloader/response_bytes': 132531, …
> [CoenMarketsUS] Add category

- locations/spiders/lenscrafters.py
```python
{'atp/brand/LensCrafters': 932,
'atp/brand_wikidata/Q6523209': 932,
'atp/category/shop/optician': 932,
'atp/cdn/cloudflare/response_count': 937,
'atp/cdn/cloudflare/response_status_count/200': 937,
'atp/closed_poi': 1,
'atp/field/email/missing': 932,
'atp/field/operator/missing': 932,
'atp/field/operator_wikidata/missing': 932,
'atp/nsi/cc_match': 927,
'atp/nsi/match_failed': 5,
'downloader/request_bytes': 396911,
'downloader/request_count': 937,
'downloader/request_method_count/GET': 937,
'downloader/response_bytes': 18390740,
'downloader/response_count': 937,
'downloader/response_status_count/200': 937,
'elapsed_time_seconds': 6.336417,
'finish_time': datetime.datetime(2024, 1, 17, 13, 58, 33, 7455, …
```
> [LensCrafters] Fix spider

- locations/spiders/clark_rubber_au.py
{'atp/brand/Clark Rubber': 60,
'atp/brand_wikidata/Q124003720': 60,
'atp/category/shop/houseware': 60,
'atp/field/country/from_spider_name': 60,
'atp/field/email/missing': 60,
'atp/field/state/missing': 60,
'atp/field/website/missing': 60,
'atp/nsi/brand_missing': 60,
'downloader/request_bytes': 641,
'downloader/response_bytes': 7966,
'elapsed_time_seconds': 2.167189, …
> [ClarkRubberAU] Add category

- locations/spiders/starbucks_au.py
```python
{'atp/brand/Starbucks': 68,
'atp/brand_wikidata/Q37158': 68,
'atp/category/amenity/cafe': 68,
'atp/field/city/missing': 68,
'atp/field/country/from_spider_name': 68,
'atp/field/image/missing': 68,
'atp/field/phone/missing': 68,
'atp/field/state/missing': 68,
'atp/field/street_address/missing': 68,
'atp/nsi/match_failed': 68,
'downloader/response_bytes': 60527, …
```
> Added starbucks_au (68 items)

- locations/spiders/aurecongroup.py
{'atp/brand/Aurecon Group': 28,
'atp/brand_wikidata/Q2871849': 28,
'atp/category/office/construction_company': 28,
'atp/field/country/from_reverse_geocoding': 27,
'atp/field/name/missing': 28,
'atp/field/street_address/missing': 28,
'atp/nsi/brand_missing': 28,
'downloader/request_bytes': 793, …
> [Aurecon] Add category

- locations/spiders/ab_gr.py
```python
{'atp/brand/AB': 622,
'atp/brand_wikidata/Q4721807': 622,
'atp/category/shop/convenience': 20,
'atp/category/shop/supermarket': 602,
'atp/field/email/missing': 622,
'atp/field/image/missing': 622,
'atp/field/opening_hours/missing': 622,
'atp/field/operator/missing': 622,
'atp/field/operator_wikidata/missing': 622,
'atp/field/phone/invalid': 11,
'atp/field/phone/missing': 194,
'atp/field/state/missing': 622,
'atp/field/twitter/missing': 622,
'downloader/request_bytes': 1078,
'downloader/response_bytes': 92886,
'elapsed_time_seconds': 0.54019,
'finish_time': …
```
> [AB GR] Add Spider

- locations/spiders/caltex.py
Previously this was setting category only for fuel stations with fuel types listed. Those without fuel types are also fuel stations so category set for all.
{'atp/brand/Caltex': 1894,
'atp/brand_wikidata/Q277470': 1894,
'atp/category/amenity/fuel': 1894,
'atp/field/city/missing': 457,
'atp/field/country/from_reverse_geocoding': 755,
'atp/field/email/missing': 1894,
'atp/field/image/missing': 1894,
'atp/field/opening_hours/missing': 1894,
'atp/field/operator/missing': 1894,
'atp/field/operator_wikidata/missing': 1894,
'atp/field/phone/invalid': 82,
'atp/field/phone/missing': 797,
'atp/field/postcode/missing': 670,
'atp/field/state/missing': 572,
'atp/field/street_address/missing': 1894,
'atp/field/twitter/missing': 1894,
'atp/field/website/missing': 1894,
'atp/nsi/category_match': 1893, …
> [Caltex] Add category

- locations/spiders/burger_king.py
- locations/spiders/burger_king_tr.py
NSI match fails without setting category, probably due to [this commit in NSI](https://github.com/osmlab/name-suggestion-index/commit/b973204b2a7f69a84ea51171c4116e86a9c38ba4), so I set category to all BK spiders.
`burger_king_tr` stats:
```json
{
"atp/brand/Burger King": 715,
"atp/brand_wikidata/Q177054": 715,
"atp/category/amenity/fast_food": 715,
"atp/field/country/from_spider_name": 715,
"atp/field/email/missing": 715,
"atp/field/image/missing": 715,
"atp/field/opening_hours/missing": 715,
"atp/field/operator/missing": 715,
"atp/field/operator_wikidata/missing": 715,
"atp/field/phone/missing": 715,
"atp/field/postcode/missing": 715,
"atp/field/twitter/missing": 715,
"atp/field/website/missing": 715,
"atp/nsi/category_match": 715,
"downloader/request_bytes": 726, …
```
> [burger_king_tr] add spider + add category to all Burger King spiders

- locations/spiders/eg_america_us.py
Most of these have multiple entries in NSI, so setting category explicitly.
{'atp/brand/Certified Oil': 66,
'atp/brand/Cumberland Farms': 577,
'atp/brand/Fastrac': 70,
'atp/brand/Kwik Shop': 115,
"atp/brand/Loaf 'N Jug": 168,
'atp/brand/Minit Mart': 90,
'atp/brand/Quik Stop': 115,
'atp/brand/Sprint': 34,
'atp/brand/TomThumb': 117,
'atp/brand/Turkey Hill': 262,
'atp/brand_wikidata/Q100148356': 66,
'atp/brand_wikidata/Q105141709': 115,
'atp/brand_wikidata/Q1143685': 577,
'atp/brand_wikidata/Q117324848': 70,
'atp/brand_wikidata/Q123012206': 117,
'atp/brand_wikidata/Q123012447': 34,
'atp/brand_wikidata/Q18154470': 90,
'atp/brand_wikidata/Q42376970': 262,
'atp/brand_wikidata/Q6450417': 115,
'atp/brand_wikidata/Q6663398': 168,
'atp/category/amenity/fuel': 1614,
'atp/category/multiple': 90, …
> [EgAmericaUS] Add category

- locations/spiders/edeka_de.py
Some POIs do not match the specific brands, but these are supermarkets, so set them to the "parent" brand EDEKA.
{'atp/brand/CAP': 64,
'atp/brand/E-Center': 328,
'atp/brand/EDEKA': 4536,
'atp/brand/EDEKA aktiv markt': 42,
'atp/brand/EDEKA xpress': 38,
'atp/brand/Elli': 16,
'atp/brand/HERKULES Ecenter': 37,
'atp/brand/MARKTKAUF': 124,
'atp/brand/Markt-Bäckerei': 126,
'atp/brand/NP': 230,
'atp/brand/diska': 106,
'atp/brand/nah und gut': 503,
'atp/brand_wikidata/Q1022827': 64,
'atp/brand_wikidata/Q1533254': 124,
'atp/brand_wikidata/Q15836148': 230,
'atp/brand_wikidata/Q1719433': 126,
'atp/brand_wikidata/Q62390177': 106,
'atp/brand_wikidata/Q701755': 5500,
'atp/category/shop/bakery': 126,
'atp/category/shop/supermarket': 6024,
'atp/field/country/from_spider_name': 6150, …
> [EdekaDE] Add category

- locations/spiders/qdoba.py
```python
{'atp/brand/Qdoba': 769,
'atp/brand_wikidata/Q1363885': 769,
'atp/category/amenity/fast_food': 769,
'atp/cdn/cloudflare/response_count': 771,
'atp/cdn/cloudflare/response_status_count/200': 771,
'atp/field/email/missing': 767,
'atp/field/opening_hours/missing': 22,
'atp/field/operator/missing': 769,
'atp/field/operator_wikidata/missing': 769,
'atp/field/phone/missing': 30,
'atp/nsi/perfect_match': 769,
'downloader/request_bytes': 424853,
'downloader/request_count': 771,
'downloader/request_method_count/GET': 771,
'downloader/response_bytes': 10439921,
'downloader/response_count': 771,
'downloader/response_status_count/200': 771,
'elapsed_time_seconds': 911.1332, …
```
> [Qdoba] Collect all locations

- locations/spiders/one_stop_gb.py
The constructed URLs are of the form https://www.onestop.co.uk/store?store=f4094509-df6f-43c8-bea2-e83f7658c2ab , but they redirect to https://www.onestop.co.uk/store/?store=f4094509-df6f-43c8-bea2-e83f7658c2ab . Note the additional forward slash after the first "store".
> Correct One Stop website URLs

- locations/spiders/crossroads_iga_us.py
If there is no data in "filters" (which identifies supermarket and fuel station), then it is the one DIY store.
{'atp/brand/Crossroads IGA': 19,
'atp/brand_wikidata/Q119141723': 19,
'atp/category/amenity/fuel': 18,
'atp/category/multiple': 18,
'atp/category/shop/doityourself': 1,
'atp/field/postcode/missing': 19,
'atp/field/state/from_reverse_geocoding': 19,
'atp/field/street_address/missing': 19,
'atp/nsi/brand_missing': 19, …
> [CrossroadsIGAUS] Add category

- locations/spiders/lincolnshire_cooperative.py
{'atp/brand/Lincolnshire Co-operative': 184,
'atp/brand_wikidata/Q5329759': 184,
'atp/category/amenity/cafe': 1,
'atp/category/amenity/fuel': 1,
'atp/category/amenity/pharmacy': 44,
'atp/category/healthcare/podiatry': 3,
'atp/category/multiple': 44,
'atp/category/shop/convenience': 100,
'atp/category/shop/florist': 1,
'atp/category/shop/funeral_directors': 21,
'atp/category/shop/travel_agency': 13,
'atp/field/email/missing': 184,
'atp/field/image/dropped': 2,
'atp/field/image/invalid': 182,
'atp/field/operator/missing': 84,
'atp/field/operator_wikidata/missing': 84,
'atp/field/state/missing': 184,
'atp/field/twitter/missing': 184,
'atp/nsi/category_match': 100,
'atp/nsi/match_failed': 84,
'atp/operator/East of England …
> [LincolnshireCooperative] Add category

- locations/spiders/subway_tw.py
```python
{'atp/brand/Subway': 129,
'atp/brand_wikidata/Q244457': 129,
'atp/category/amenity/fast_food': 129,
'atp/field/city/missing': 129,
'atp/field/country/from_spider_name': 129,
'atp/field/email/missing': 129,
'atp/field/image/missing': 129,
'atp/field/lat/missing': 129,
'atp/field/lon/missing': 129,
'atp/field/opening_hours/missing': 129,
'atp/field/operator/missing': 129,
'atp/field/operator_wikidata/missing': 129,
'atp/field/postcode/missing': 129,
'atp/field/state/missing': 129,
'atp/field/street_address/missing': 129,
'atp/field/twitter/missing': 129,
'atp/nsi/cc_match': 129,
'downloader/request_bytes': 6754,
'downloader/request_count': 15,
'downloader/request_method_count/GET': 15,
'downloader/response_bytes': 104747, …
```
> [subway_tw] Created Spider for subway_tw (126 items)

- locations/spiders/rsg_group.py
If there is no provided sub-brand data, then set to parent brand as default.
{'atp/brand/JOHN REED Fitness': 50,
'atp/brand/McFit': 300,
'atp/brand_wikidata/Q106434148': 50,
'atp/brand_wikidata/Q871302': 300,
'atp/category/leisure/fitness_centre': 350,
'atp/field/country/from_reverse_geocoding': 4,
'atp/field/email/missing': 350,
'atp/field/image/missing': 350,
'atp/field/operator/missing': 350,
'atp/field/operator_wikidata/missing': 350,
'atp/field/state/from_reverse_geocoding': 3,
'atp/field/state/missing': 343,
'atp/field/twitter/missing': 350, …
> [RsgGroup] Add category

- locations/spiders/deutsche_telekom_de.py
```python
{'atp/brand/Deutsche Telekom': 534,
'atp/brand_wikidata/Q9396': 534,
'atp/category/missing': 534,
'atp/closed_poi': 5,
'atp/field/country/from_spider_name': 534,
'atp/field/operator/missing': 534,
'atp/field/operator_wikidata/missing': 534,
'atp/field/state/missing': 534,
'atp/field/street_address/missing': 534,
'atp/field/twitter/missing': 534,
'atp/nsi/match_failed': 534,
'downloader/request_bytes': 94503,
'downloader/request_count': 241,
'downloader/request_method_count/GET': 241,
'downloader/response_bytes': 661555,
'downloader/response_count': 241,
'downloader/response_status_count/200': 240,
'elapsed_time_seconds': 25.398611, …
```
> [DeutscheTelekomDE] Add spider

- locations/spiders/badcock_us.py
Rel: https://github.com/osmlab/name-suggestion-index/commit/773e969fb686ef7d82df93699a05f9c116c4b980
```python
{'atp/brand/Badcock': 356,
'atp/brand_wikidata/Q4840663': 356,
'atp/category/missing': 356,
'atp/field/city/missing': 356,
'atp/field/country/from_spider_name': 356,
'atp/field/email/missing': 356,
'atp/field/image/missing': 356,
'atp/field/name/missing': 356,
'atp/field/opening_hours/missing': 356,
'atp/field/operator/missing': 356,
'atp/field/operator_wikidata/missing': 356,
'atp/field/phone/missing': 356,
'atp/field/postcode/missing': 356,
'atp/field/state/from_reverse_geocoding': 356,
'atp/field/twitter/missing': 356,
'atp/nsi/brand_missing': 356,
'downloader/request_bytes': 692, …
```
> [BadcockUS] Add spider

- locations/spiders/planet_smoothie_us.py
{'atp/brand/Planet Smoothie': 163,
'atp/brand_wikidata/Q7201170': 163,
'atp/category/amenity/fast_food': 163,
'atp/field/email/missing': 163,
'atp/field/image/missing': 163,
'atp/field/name/missing': 163,
'atp/field/opening_hours/missing': 163,
'atp/field/operator/missing': 163,
'atp/field/operator_wikidata/missing': 163,
'atp/field/twitter/missing': 163,
'atp/nsi/brand_missing': 163,
'downloader/response_bytes': 48545,
'elapsed_time_seconds': 3.905603,
'finish_time': datetime.datetime(2024, …
> [PlanetSmoothieUS] Add category

- locations/spiders/circle_k_se.py
```python
{'atp/brand/Circle K': 444,
'atp/brand_wikidata/Q3268010': 444,
'atp/category/amenity/fuel': 444,
'atp/field/email/missing': 444,
'atp/field/image/missing': 444,
'atp/field/opening_hours/missing': 235,
'atp/field/operator/missing': 444,
'atp/field/operator_wikidata/missing': 444,
'atp/field/state/missing': 444,
'atp/field/twitter/missing': 444,
'atp/nsi/category_match': 444,
'downloader/request_bytes': 170106,
'downloader/request_count': 446,
'downloader/request_method_count/GET': 446,
'downloader/response_bytes': 5371861,
'downloader/response_count': 446,
'downloader/response_status_count/200': 446,
'elapsed_time_seconds': 3.838555,
'finish_time': datetime.datetime(2024, 1, 22, 11, 47, 15, 620293, …
```
> [CircleK SE] Add spider

- locations/spiders/loxam_fr.py
```python
{'atp/brand/Loxam': 1049,
'atp/brand_wikidata/Q3264407': 1049,
'atp/category/shop/tool_hire': 1049,
'atp/field/email/missing': 1049,
'atp/field/image/missing': 1049,
'atp/field/operator/missing': 1049,
'atp/field/operator_wikidata/missing': 1049,
'atp/field/state/missing': 1049,
'atp/field/twitter/missing': 1049,
'atp/nsi/perfect_match': 1049,
'downloader/request_bytes': 527869,
'downloader/request_count': 1053,
'downloader/request_method_count/GET': 1053,
'downloader/response_bytes': 24230468,
'downloader/response_count': 1053,
'downloader/response_status_count/200': 1053,
'elapsed_time_seconds': 1275.127449,
'finish_time': datetime.datetime(2024, 1, 18, 19, 15, 24, 242285, …
```
> [loxam_fr] Created a sitemapspider for Loxam in France (1049 items)

- locations/spiders/kohls_us.py
```python
{"atp/brand/Kohl's": 1154,
'atp/brand_wikidata/Q967265': 1154,
'atp/category/shop/department_store': 1154,
'atp/field/country/from_spider_name': 1154,
'atp/field/email/missing': 1154,
'atp/field/image/missing': 1154,
'atp/field/operator/missing': 1154,
'atp/field/operator_wikidata/missing': 1154,
'atp/field/twitter/missing': 1154,
'atp/nsi/perfect_match': 1154,
'downloader/request_bytes': 1612577,
'downloader/request_count': 1159,
'downloader/request_method_count/GET': 1159,
'downloader/response_bytes': 58330517,
'downloader/response_count': 1159,
'downloader/response_status_count/200': 1156,
'downloader/response_status_count/301': 3,
'elapsed_time_seconds': 11.942035,
'finish_time': …
```
> [KohlsUS] Fix spider

- locations/commands/duplicate_wikidata.py
- locations/spiders/vodafone_de.py
- locations/spiders/vodafone_es.py
- locations/spiders/vodafone_it.py
Command can give some insight into the relationship between spiders and their wikidata codes. It can help us move towards being a little more DRY where it makes sense. For example in the proposed tidy up to the vodafone_* spiders. Where the relationship is more more complex e.g.
```
2024-01-22 18:01:39 [locations.commands.duplicate_wikidata] INFO: Q25172225 -> {'locations/spiders/tesco_gb.py', 'locations/spiders/visionexpress_gb.py'}
```
.. I would not propose sharing the definition at present.
Full output at present:
```
2024-01-22 18:00:44 [scrapy.utils.log] INFO: Scrapy 2.11.0 started (bot: locations)
2024-01-22 18:00:44 [scrapy.utils.log] INFO: Versions: lxml 5.0.0.0, libxml2 2.12.3, cssselect 1.2.0, parsel 1.8.1, w3lib 2.1.2, Twisted 22.10.0, Python 3.10.12 (main, Nov 20 2023, …
```
> new command to show spiders sharing hard coded wikidata information

- locations/spiders/carrefour_es.py
Getting benefit of Sitemap-StructuredData combination doesn't look feasible here, as it require about 1 minute of download_delay (mentioned in robots.txt file) between two requests, any value less than that will result in loss of POI pages, because server sends captcha page. (Keeping in mind we have more than 1700 POIs.)
```python
{'atp/brand/Carrefour': 367,
'atp/brand/Carrefour BIO': 2,
'atp/brand/Carrefour Express': 1053,
'atp/brand/Carrefour Market': 152,
'atp/brand/Carrefour Viajes': 193,
'atp/brand_wikidata/Q116483791': 193,
'atp/brand_wikidata/Q217599': 367,
'atp/brand_wikidata/Q2689639': 152,
'atp/brand_wikidata/Q2940190': 1053,
'atp/brand_wikidata/Q55221138': 2,
'atp/category/amenity/fuel': 147,
'atp/category/shop/convenience': 1053, …
```
> [carrefour_es] Created spider for carrefour_es (1765 items)

- locations/spiders/biogroup_fr.py
```python
{'atp/brand/Biogroup': 908,
'atp/brand_wikidata/Q101559741': 908,
'atp/category/healthcare/laboratory': 908,
'atp/cdn/cloudflare/response_count': 911,
'atp/cdn/cloudflare/response_status_count/200': 911,
'atp/field/city/missing': 907,
'atp/field/country/from_spider_name': 908,
'atp/field/image/missing': 32,
'atp/field/opening_hours/missing': 373,
'atp/field/operator/missing': 908,
'atp/field/operator_wikidata/missing': 908,
'atp/field/state/missing': 908,
'atp/nsi/perfect_match': 908,
'downloader/request_bytes': 515426,
'downloader/request_count': 911,
'downloader/request_method_count/GET': 911,
'downloader/response_bytes': 29036798,
'downloader/response_count': 911,
'downloader/response_status_count/200': 911, …
```
> [Biogroup FR] Add spider

- locations/spiders/kinki_nl.py
Rel: https://github.com/osmlab/name-suggestion-index/pull/9185
```python
{'atp/brand/Kinki Kappers': 41,
'atp/brand_wikidata/Q124152910': 41,
'atp/category/missing': 41,
'atp/field/country/from_spider_name': 41,
'atp/field/name/missing': 41,
'atp/field/opening_hours/missing': 41,
'atp/field/state/missing': 41,
'atp/nsi/brand_missing': 41,
'downloader/request_bytes': 722,
'downloader/response_bytes': 5229, …
```
> [Kinki NL] Add spider

- locations/spiders/shoe_carnival_us.py
```python
{'atp/brand/Shoe Carnival': 373,
'atp/brand_wikidata/Q7500007': 373,
'atp/category/shop/shoes': 373,
'atp/field/country/from_spider_name': 373,
'atp/field/email/missing': 373,
'atp/field/operator/missing': 373,
'atp/field/operator_wikidata/missing': 373,
'atp/nsi/perfect_match': 373,
'downloader/request_bytes': 156444,
'downloader/request_count': 378,
'downloader/request_method_count/GET': 378,
'downloader/response_bytes': 14258401,
'downloader/response_count': 378,
'downloader/response_status_count/200': 378,
'elapsed_time_seconds': 350.461103,
'finish_time': datetime.datetime(2024, 1, 23, 14, 0, 29, 313924, tzinfo=datetime.timezone.utc),
'httpcache/firsthand': 290,
'httpcache/hit': 88, …
```
> [ShoeCarnival US] Add spider

- locations/spiders/subway_kr.py
```python
{'atp/brand/Subway': 580,
'atp/brand_wikidata/Q244457': 580,
'atp/category/amenity/fast_food': 580,
'atp/field/city/missing': 580,
'atp/field/country/from_spider_name': 580,
'atp/field/email/missing': 580,
'atp/field/image/missing': 580,
'atp/field/lat/missing': 11,
'atp/field/lon/missing': 11,
'atp/field/opening_hours/missing': 580,
'atp/field/operator/missing': 580,
'atp/field/operator_wikidata/missing': 580,
'atp/field/phone/invalid': 9,
'atp/field/postcode/missing': 580,
'atp/field/state/missing': 580,
'atp/field/street_address/missing': 580,
'atp/field/twitter/missing': 580,
'atp/geometry/null_island': 8,
'atp/nsi/cc_match': 580,
'downloader/request_bytes': 400317,
'downloader/request_count': 639, …
```
> [subway_kr] Created spider for Subway in KR (580 items)

- locations/spiders/circle_k_no.py
```python
{'atp/brand/Circle K': 462,
'atp/brand_wikidata/Q3268010': 462,
'atp/category/amenity/fuel': 462,
'atp/field/email/missing': 462,
'atp/field/image/missing': 462,
'atp/field/opening_hours/missing': 283,
'atp/field/operator/missing': 462,
'atp/field/operator_wikidata/missing': 462,
'atp/field/state/missing': 462,
'atp/field/twitter/missing': 462,
'atp/nsi/category_match': 462,
'downloader/request_bytes': 303670,
'downloader/request_count': 464,
'downloader/request_method_count/GET': 464,
'downloader/response_bytes': 5595718,
'downloader/response_count': 464,
'downloader/response_status_count/200': 464,
'elapsed_time_seconds': 558.655768, …
```
> [Circle K NO] Add spider

- locations/spiders/vival_fr.py
```python
{'atp/brand/Vival': 1493,
'atp/brand_wikidata/Q7937525': 1493,
'atp/category/shop/convenience': 1493,
'atp/field/email/missing': 1490,
'atp/field/image/dropped': 38,
'atp/field/operator/missing': 1493,
'atp/field/operator_wikidata/missing': 1493,
'atp/field/phone/missing': 104,
'atp/field/state/missing': 1493,
'atp/field/twitter/missing': 1493,
'atp/nsi/perfect_match': 1493,
'downloader/request_bytes': 611202,
'downloader/request_count': 1453,
'downloader/request_method_count/GET': 1453,
'downloader/response_bytes': 11763079,
'downloader/response_count': 1453,
'downloader/response_status_count/200': 1447,
'downloader/response_status_count/301': 5, …
```
> [Vival FR] Add spider

- locations/spiders/starbucks_ar_cl.py
```python
{'atp/brand/Starbucks': 280,
'atp/brand_wikidata/Q37158': 280,
'atp/category/amenity/cafe': 280,
'atp/field/email/missing': 280,
'atp/field/image/missing': 280,
'atp/field/operator/missing': 280,
'atp/field/operator_wikidata/missing': 280,
'atp/field/phone/missing': 280,
'atp/field/twitter/missing': 280,
'atp/nsi/match_failed': 280,
'downloader/request_bytes': 51213,
'downloader/request_count': 143,
'downloader/request_method_count/POST': 141,
'downloader/response_bytes': 344526,
'downloader/response_count': 143,
'downloader/response_status_count/200': 143,
'elapsed_time_seconds': 152.380076,
'finish_time': datetime.datetime(2024, 1, 24, 16, 25, 35, 362875, …
```
> [starbucks_ar_cl] Created spider for starbucks_ar_cl (280 items)

- locations/spiders/epaka.py
- locations/spiders/seven_eleven_dk.py
{'atp/brand/Epaka.pl': 360,
'atp/brand_wikidata/Q123028724': 360,
'atp/category/amenity/post_office': 360,
'atp/field/country/from_spider_name': 360,
'atp/field/image/missing': 360,
'atp/field/name/missing': 360,
'atp/field/operator/missing': 360,
'atp/field/operator_wikidata/missing': 360,
'atp/field/state/missing': 360,
'atp/field/street_address/missing': 360,
'atp/field/twitter/missing': 360,
'atp/nsi/brand_missing': 360,
'downloader/request_bytes': 310,
'downloader/response_bytes': 32516,
'elapsed_time_seconds': 4.602628,
'finish_time': datetime.datetime(2024, 1, 24, 10, …
> [Epaka] Add category

- locations/spiders/nsw_national_parks_and_wildlife_service_au.py
- locations/spiders/seven_eleven_dk.py
'atp/category/tourism/camp_site': 360,
'atp/category/tourism/yes': 92,
tourism=yes sites are not readily taggable, but are various types of accommodation ranging from lodging, chatels, remote huts, hotels, ensuite cabins, etc. See justification in source file for lack of detailed tagging.
> Add NSW National Parks and Wildlife Service (AU) (452 locations)

- locations/spiders/careone_us.py
{'atp/brand/CareOne': 58,
'atp/brand_wikidata/Q25108589': 58,
'atp/category/amenity/social_facility': 58,
'atp/field/image/missing': 58,
'atp/field/opening_hours/missing': 53,
'atp/field/operator/missing': 58,
'atp/field/operator_wikidata/missing': 58,
'atp/field/twitter/missing': 58,
'atp/field/website/missing': 58,
'atp/nsi/brand_missing': 58,
'downloader/request_bytes': 706,
'downloader/response_bytes': 69191,
'elapsed_time_seconds': 2.947493,
'finish_time': datetime.datetime(2024, 1, 25, 10, 39, 35, 555236, tzinfo=datetime.timezone.utc),
'httpcompression/response_bytes': 174, …
> [CareOneUS] Add category

- locations/spiders/promedica_us.py
{'atp/brand/ProMedica': 138,
'atp/brand_wikidata/Q7246673': 138,
'atp/category/amenity/social_facility': 138,
'atp/field/country/from_spider_name': 138,
'atp/nsi/brand_missing': 138,
'downloader/request_bytes': 682,
'downloader/response_bytes': 15697,
'elapsed_time_seconds': 3.821786,
'finish_time': datetime.datetime(2024, 1, 25, 13, 36, 26, 236785, tzinfo=datetime.timezone.utc), …
> [ProMedicaUS] Add category

- locations/spiders/tigota_it.py
```python
{'atp/brand/Tigotà': 699,
'atp/brand_wikidata/Q107464330': 699,
'atp/category/shop/chemist': 699,
'atp/field/country/from_spider_name': 699,
'atp/field/email/missing': 699,
'atp/field/operator/missing': 699,
'atp/field/operator_wikidata/missing': 699,
'atp/nsi/perfect_match': 699,
'downloader/request_bytes': 521941,
'downloader/request_count': 902,
'downloader/request_method_count/GET': 902,
'downloader/response_bytes': 15381685,
'downloader/response_count': 902,
'downloader/response_status_count/200': 902,
'dupefilter/filtered': 442,
'elapsed_time_seconds': 203.345305,
'finish_time': datetime.datetime(2024, 1, 25, 14, 3, 24, 485229, …
```
> [Tigota IT] Add spider

- locations/spiders/oshkosh_us.py
```python
{"atp/brand/OshKosh B'gosh": 466,
'atp/brand_wikidata/Q1417347': 466,
'atp/category/shop/clothes': 466,
'atp/field/country/from_spider_name': 42,
'atp/field/email/missing': 466,
'atp/field/image/missing': 466,
'atp/field/operator/missing': 466,
'atp/field/operator_wikidata/missing': 466,
'atp/field/twitter/missing': 466,
'atp/nsi/perfect_match': 466,
'downloader/request_bytes': 417285,
'downloader/request_count': 943,
'downloader/request_method_count/GET': 943,
'downloader/response_bytes': 227578159,
'downloader/response_count': 943,
'downloader/response_status_count/200': 943,
'dupefilter/filtered': 1212,
'elapsed_time_seconds': 1139.843153,
'finish_time': …
```
> [Oshkosh US] Add spider

- locations/spiders/aldi_sud_ch.py
Name was being populated by the ref, eg `DOM-39`.
> [Aldi CH] Fix name

- locations/spiders/dockx_be.py
{'atp/brand/Dockx': 24,
'atp/category/amenity/car_rental': 24,
'atp/field/brand_wikidata/missing': 24,
'downloader/request_bytes': 651,
'downloader/response_bytes': 67006,
'elapsed_time_seconds': 2.032939,
'finish_time': datetime.datetime(2024, 1, 26, 14, 20, 54, 791188, tzinfo=datetime.timezone.utc),
'httpcompression/response_bytes': 278654,
'item_scraped_count': 24,
'log_count/DEBUG': 27,
'log_count/INFO': …
> [DockxBE] Add category

- locations/spiders/mitre_10_nz.py
{'atp/brand/Mitre 10': 88,
'atp/brand_wikidata/Q6882394': 88,
'atp/category/shop/doityourself': 88,
'atp/nsi/match_failed': 88,
'downloader/request_bytes': 906,
'downloader/response_bytes': 29008,
'elapsed_time_seconds': 3.629911, …
> [Mitre10NZ] Add category

- locations/spiders/bash_za.py
- locations/spiders/cinemark.py
- locations/spiders/moes.py
- locations/spiders/papa_johns.py
- locations/spiders/sats.py
- locations/spiders/simple_simons_pizza_us.py
- locations/spiders/xfinity.py
Sats is the biggest offender of the closed check, with 37 occurrences. So it's not a massive issue, but not ideal. This PR is all the spiders with more than 15 occurrences.
I've sort of decided to drop "coming soon" locations. I've no strong opinion, but if we want to keep them, I'd like a way to tag them. I've ignored (left in) a few "temporarily closed" locations, again no strong opinion from me.
> Flag closed locatons

- locations/spiders/starbucks_pe.py
```python
{'atp/brand/Starbucks': 116,
'atp/brand_wikidata/Q37158': 116,
'atp/category/amenity/cafe': 116,
'atp/field/email/missing': 116,
'atp/field/image/missing': 116,
'atp/field/opening_hours/missing': 116,
'atp/field/operator/missing': 116,
'atp/field/operator_wikidata/missing': 116,
'atp/field/phone/invalid': 11,
'atp/field/phone/missing': 105,
'atp/nsi/match_failed': 116,
'downloader/request_bytes': 58363,
'downloader/request_count': 132,
'downloader/request_method_count/GET': 132,
'downloader/response_bytes': 808100,
'downloader/response_count': 132,
'downloader/response_status_count/200': 132,
'elapsed_time_seconds': 164.492468,
'finish_time': datetime.datetime(2024, 1, 30, 14, 0, 22, …
```
> [starbucks_pe] Created Spider (116 items)

- locations/spiders/benchmark_hospitality.py
{'atp/category/amenity/conference_centre': 4,
'atp/category/leisure/resort': 23,
'atp/category/tourism/hotel': 32,
'atp/field/brand/missing': 59,
'atp/field/brand_wikidata/missing': 59,
'atp/field/country/from_reverse_geocoding': 59,
'atp/field/email/missing': 59,
'atp/field/image/missing': 59,
'atp/field/opening_hours/missing': 59,
'atp/field/operator/missing': 59,
'atp/field/operator_wikidata/missing': 59,
'atp/field/phone/wrong_type': 118,
'atp/field/postcode/missing': 59,
'atp/field/street_address/missing': 59,
'atp/field/twitter/missing': 59,
'downloader/request_bytes': 98341,
'downloader/request_count': 108,
'downloader/request_method_count/GET': 108,
'downloader/response_bytes': 4793356,
'downloader/response_count': 108, …
> [BenchmarkHospitality] Add category

- locations/spiders/pizza_hut_hk.py
<details><summary>stats</summary>
```python
{'atp/brand/Pizza Hut': 97,
'atp/brand_wikidata/Q191615': 97,
'atp/category/amenity/restaurant': 97,
'atp/field/city/missing': 97,
'atp/field/country/from_spider_name': 97,
'atp/field/email/missing': 97,
'atp/field/image/missing': 97,
'atp/field/operator/missing': 97,
'atp/field/operator_wikidata/missing': 97,
'atp/field/postcode/missing': 97,
'atp/field/state/missing': 97,
'atp/field/street_address/missing': 97,
'atp/field/twitter/missing': 97,
'atp/nsi/cc_match': 97,
'downloader/request_bytes': 653,
'downloader/response_bytes': 5445849, …
```
> [pizza_hut_hk] Created pizzahut hk spider (97 items)

- locations/spiders/circle_k_ie.py
- locations/spiders/circle_k_ireland.py
```python
{'atp/brand/Circle K': 410,
'atp/brand_wikidata/Q3268010': 410,
'atp/category/amenity/fuel': 410,
'atp/field/email/missing': 410,
'atp/field/image/missing': 410,
'atp/field/opening_hours/missing': 410,
'atp/field/operator/missing': 410,
'atp/field/operator_wikidata/missing': 410,
'atp/field/phone/missing': 234,
'atp/field/state/missing': 410,
'atp/nsi/category_match': 410,
'downloader/request_bytes': 157141,
'downloader/request_count': 412,
'downloader/request_method_count/GET': 412,
'downloader/response_bytes': 3669928,
'downloader/response_count': 412,
'downloader/response_status_count/200': 412,
'elapsed_time_seconds': 504.615983,
'finish_time': datetime.datetime(2024, 2, 2, 15, 35, 21, 335104, …
```
> [CircleK Ireland] Add Spider

- locations/spiders/northside_hospital_us.py
Where category field had no date, this was being used to set the category.
I've examined the names of the POIs with no category and concluded default = clinic.
> [NorthsideHospitalUS] Add categories

- locations/spiders/well_gb.py
```python
{'atp/brand/Well Pharmacy': 736,
'atp/brand_wikidata/Q7726524': 736,
'atp/category/amenity/pharmacy': 736,
'atp/category/multiple': 736,
'atp/cdn/cloudflare/response_count': 740,
'atp/cdn/cloudflare/response_status_count/200': 740,
'atp/field/email/missing': 736,
'atp/field/image/missing': 736,
'atp/field/operator/missing': 736,
'atp/field/operator_wikidata/missing': 736,
'atp/nsi/perfect_match': 736,
'downloader/request_bytes': 398529,
'downloader/request_count': 740,
'downloader/request_method_count/GET': 740,
'downloader/response_bytes': 13370068,
'downloader/response_count': 740,
'downloader/response_status_count/200': 740,
'elapsed_time_seconds': 4.482592, …
```
> [Well GB] Add spider

- locations/spiders/latagliatella_es.py
- locations/storefinders/amrest_eu.py
Stats:
```json
{
"atp/brand/La Tagliatella": 223,
"atp/brand_wikidata/Q113426257": 223,
"atp/category/amenity/restaurant": 223,
"atp/field/country/from_spider_name": 223,
"atp/field/email/missing": 223,
"atp/field/image/missing": 223,
"atp/field/operator/missing": 223,
"atp/field/operator_wikidata/missing": 223,
"atp/field/state/missing": 223,
"atp/field/street_address/missing": 223,
"atp/field/twitter/missing": 223,
"atp/field/website/missing": 1,
"atp/nsi/perfect_match": 223,
"downloader/request_bytes": 236971,
"downloader/request_count": 226,
"downloader/request_method_count/GET": 225,
"downloader/request_method_count/POST": 1,
"downloader/response_bytes": 553970,
"downloader/response_count": 226,
"downloader/response_status_count/200": 225, …
```
> [latagliatella_es] add spider (223 locations)

- locations/spiders/kfc_in.py
```python
{'atp/brand/KFC': 927,
'atp/brand_wikidata/Q524757': 927,
'atp/category/amenity/fast_food': 927,
'atp/field/city/missing': 927,
'atp/field/country/from_spider_name': 927,
'atp/field/email/missing': 927,
'atp/field/image/missing': 927,
'atp/field/opening_hours/missing': 927,
'atp/field/operator/missing': 927,
'atp/field/operator_wikidata/missing': 927,
'atp/field/postcode/missing': 927,
'atp/field/state/missing': 927,
'atp/field/twitter/missing': 927,
'atp/nsi/cc_match': 927,
'downloader/request_bytes': 34349,
'downloader/request_count': 96,
'downloader/request_method_count/GET': 96,
'downloader/response_bytes': 1117869,
'downloader/response_count': 96,
'downloader/response_status_count/200': 96,
'dupefilter/filtered': 188,
'elapsed_time_seconds': 121.928913, …
```
> [KFC IN] Add spider

- locations/categories.py
- locations/spiders/casper_us.py
Fix https://github.com/alltheplaces/alltheplaces/issues/7113
2024-02-11 06:58:46 [scrapy.statscollectors] INFO: Dumping Scrapy stats:
{'atp/brand/Casper': 72,
'atp/brand_wikidata/Q20539294': 72,
'atp/category/shop/bed': 72,
'atp/cdn/cloudflare/response_count': 74,
'atp/cdn/cloudflare/response_status_count/200': 74,
'atp/field/country/from_spider_name': 72,
'atp/nsi/perfect_match': 72,
'downloader/request_bytes': 40050,
'downloader/request_count': 74, …
> Casper (US) (shop/bed) (Sitemap + Structured Data) (72 stores)

- locations/spiders/spa_world_au_nz.py
Fix https://github.com/alltheplaces/alltheplaces/issues/6543
```
{'atp/brand/Spa World': 20,
'atp/brand_wikidata/Q124003802': 20,
'atp/category/shop/swimming_pool': 20,
'atp/field/lat/missing': 20,
'atp/field/lon/missing': 20,
'atp/field/postcode/wrong_type': 20,
'downloader/request_bytes': 19465,
'downloader/request_count': 50,
'downloader/request_method_count/GET': 50,
'downloader/response_bytes': 3379371,
'downloader/response_count': 50,
'downloader/response_status_count/200': 50,
'elapsed_time_seconds': 45.427371,
'finish_time': datetime.datetime(2024, 2, 12, 21, 49, 57, 185529, …
```
> Add Spa World (AU, NZ) (shop/swimming_pool? for spa) (20 locations)

- locations/spiders/kennards_self_storage_nz.py
Fix https://github.com/alltheplaces/alltheplaces/issues/6545
```
{'atp/brand/Kennards Self Storage': 10,
'atp/brand_wikidata/Q115565997': 10,
'atp/category/shop/storage_rental': 10,
'atp/field/twitter/invalid': 10,
'downloader/request_bytes': 9536,
'downloader/request_count': 18,
'downloader/request_method_count/GET': 18,
'downloader/response_bytes': 2956458,
'downloader/response_count': 18,
'downloader/response_status_count/200': 18,
'elapsed_time_seconds': 21.487144,
'finish_time': datetime.datetime(2024, 2, 12, 8, 34, 53, 940520, tzinfo=datetime.timezone.utc),
'item_scraped_count': 10,
'log_count/DEBUG': 52,
'memusage/max': …
```
> Add Kennards Self Storage (NZ)  (shop/storage_rental) (10 locations)

- locations/spiders/kennards_self_storage_au.py
Fix https://github.com/alltheplaces/alltheplaces/issues/6545
Related: https://github.com/alltheplaces/alltheplaces/pull/7164
```
{'atp/brand/Kennards Self Storage': 104,
'atp/brand_wikidata/Q115565997': 104,
'atp/category/shop/storage_rental': 104,
'atp/field/operator/missing': 104,
'atp/field/operator_wikidata/missing': 104,
'atp/field/twitter/invalid': 104,
'atp/nsi/perfect_match': 104,
'downloader/request_bytes': 91482,
'downloader/request_count': 140,
'downloader/request_method_count/GET': 140,
'downloader/response_bytes': 36502921,
'downloader/response_count': 140,
'downloader/response_status_count/200': 140,
'elapsed_time_seconds': 169.873442,
'finish_time': datetime.datetime(2024, 2, …
```
> Add Kennards Self Storage (AU) (shop/storage_rental) (104 locations)

- locations/spiders/obriens_ie.py
Fix https://github.com/alltheplaces/alltheplaces/issues/7024
```
2024-02-12 07:41:56 [scrapy.core.scraper] DEBUG: Scraped from <200 https://storemapper-herokuapp-com.global.ssl.fastly.net/api/users/5830/stores.js>
{'addr_full': '178 Templeogue Road, Templeogue, Dublin 6W',
'brand': "O'Briens",
'brand_wikidata': 'Q113151266',
'city': None,
'country': 'IE',
'email': 'templeogue@obrienswine.ie',
'extras': {'@spider': 'obriens_ie', 'shop': 'alcohol'},
'geometry': {'coordinates': [-6.3031479, 53.29836], 'type': 'Point'},
'name': 'Templeogue',
'nsi_id': 'obriens-986e1f',
'phone': '+353 1 492 0334',
'postcode': None,
'ref': 11844016,
'state': None,
'street_address': None,
'website': None}
2024-02-12 07:41:56 [scrapy.core.engine] INFO: Closing spider …
```
> Add O'Briens (IE) (shop/alcohol) (storemapper) (35 stores)

- locations/spiders/99_bikes.py
Fix https://github.com/alltheplaces/alltheplaces/issues/7037 (I'm not going to bother with the NZ store, as it doesn't have this API)
```
{'brand': '99 Bikes',
'brand_wikidata': 'Q110288298',
'city': 'Upper Coomera',
'country': 'AU',
'email': 'coomera@99bikes.com.au',
'extras': {'@spider': '99_bikes_au', 'shop': 'bicycle'},
'geometry': {'coordinates': [153.30186651, -27.85163952], 'type': 'Point'},
'name': 'Coomera',
'nsi_id': '99bikes-0d00fa',
'opening_hours': 'Mo-Fr 09:00-05:30; Sa 09:00-05:00; Su 10:00-04:00',
'phone': '+61 7 5648 3758',
'postcode': '4209',
'ref': '91',
'state': 'QLD',
'street_address': '8/15 City Centre Drive'}
2024-02-13 10:21:46 [scrapy.core.engine] INFO: Closing spider (finished)
2024-02-13 10:21:46 [locations.pipelines.duplicates] INFO: Dropped 0 duplicate items …
```
> Add 99 bikes (AU) (shop/bike) (62 locations)

- locations/spiders/total_energies.py
Agip gas stations in Germany have incorrect location:
Flipping the coordinates fixes this, other gas stations in Germany are located correctly.
> [TotalEnergies] Fix flipped coordinates

- locations/spiders/maisondelaliterie.py
Fix https://github.com/alltheplaces/alltheplaces/issues/7121
{'atp/brand/Maison de la Literie': 145,
'atp/brand_wikidata/Q80955776': 145,
'atp/category/shop/bed': 145,
'atp/field/country/from_website_url': 5,
'atp/field/image/missing': 145,
'atp/field/opening_hours/missing': 145,
'atp/field/operator/missing': 145,
'atp/field/operator_wikidata/missing': 145,
'atp/field/state/missing': 138,
'atp/field/twitter/missing': 145,
'atp/nsi/perfect_match': 145,
'downloader/request_bytes': 651,
'downloader/response_bytes': 42338, …
> Maison de la Literie (FR) (shop/bed) (145 locations)

- locations/spiders/mattress_depot_us.py
Fix https://github.com/alltheplaces/alltheplaces/issues/7122
```
{'atp/brand/Mattress Depot USA': 31,
'atp/brand_wikidata/Q108413386': 31,
'atp/category/shop/bed': 31,
'atp/field/state/from_reverse_geocoding': 22,
'atp/nsi/perfect_match': 31,
'downloader/response_bytes': 4474,
'elapsed_time_seconds': 3.537212,
'finish_time': datetime.datetime(2024, 2, 18, 10, 23, 13, 433271, tzinfo=datetime.timezone.utc), …
```
> Add Mattress Depot USA (US) (shop/bed) (31 locations)

- locations/spiders/teboil_ru.py
TODO -> include RU in NSI: https://nsi.guide/index.html?t=brands&tt=teboil
Stats:
```json
{
"atp/brand_wikidata/Q7692079": 334,
"atp/category/amenity/fuel": 334,
"atp/field/brand/missing": 334,
"atp/field/city/missing": 334,
"atp/field/country/from_spider_name": 334,
"atp/field/email/missing": 334,
"atp/field/image/missing": 334,
"atp/field/name/missing": 334,
"atp/field/opening_hours/missing": 334,
"atp/field/operator/missing": 334,
"atp/field/operator_wikidata/missing": 334,
"atp/field/phone/missing": 334,
"atp/field/postcode/missing": 334,
"atp/field/state/missing": 334,
"atp/field/street_address/missing": 334,
"atp/field/twitter/missing": 334,
"atp/field/website/missing": 334,
"atp/nsi/match_failed": 334,
"downloader/request_bytes": 677, …
```
> [teboil_ru] add spider (334 locations)

- locations/spiders/swing_kitchen.py
```python
{'atp/brand/Swing Kitchen': 14,
'atp/brand_wikidata/Q116943226': 14,
'atp/category/amenity/fast_food': 14,
'atp/field/country/from_reverse_geocoding': 12,
'atp/nsi/perfect_match': 14,
'downloader/request_bytes': 681,
'downloader/response_bytes': 2170,
'elapsed_time_seconds': 5.903173,
'finish_time': datetime.datetime(2024, 2, 20, 22, 0, 5, …
```
> [SwingKitchen] Add spider (14 locations)

- locations/spiders/sanders_backstube_de.py
Fix https://github.com/alltheplaces/alltheplaces/issues/7297
2024-02-20 22:22:19 [scrapy.statscollectors] INFO: Dumping Scrapy stats:
{"atp/brand/sander's backstube": 24,
'atp/brand_wikidata/Q66207337': 24,
'atp/category/shop/bakery': 24,
'atp/field/country/from_spider_name': 24,
'atp/field/email/missing': 24,
'atp/field/phone/invalid': 21,
'atp/field/website/missing': 24,
'atp/nsi/perfect_match': 24,
'downloader/request_bytes': 727,
'downloader/response_bytes': 3512, …
> Sanders Backstube (DE) (shop/bakery) (24 locations)

- locations/spiders/mediamarkt_de.py
This is a country-specific spider, see e.g. the number of countries for brand MediaMarkt at https://www.alltheplaces.xyz/wikidata
> [MediaMarkt] Rename spider to media_markt_de

- locations/pipelines/drop_logo.py
- locations/spiders/papa_johns_gb.py
```python
{"atp/brand/Papa John's": 458,
'atp/brand_wikidata/Q2759586': 458,
'atp/category/amenity/fast_food': 458,
'atp/cdn/cloudflare/response_count': 468,
'atp/cdn/cloudflare/response_status_count/200': 458,
'atp/cdn/cloudflare/response_status_count/404': 10,
'atp/field/email/missing': 458,
'atp/field/image/dropped': 458,
'atp/field/image/missing': 458,
'atp/field/operator/missing': 458,
'atp/field/operator_wikidata/missing': 458,
'atp/nsi/cc_match': 458,
'downloader/request_bytes': 621083,
'downloader/request_count': 470,
'downloader/request_method_count/GET': 470,
'downloader/response_bytes': 14285708,
'downloader/response_count': 470,
'downloader/response_status_count/200': 460,
'downloader/response_status_count/404': 10, …
```
> [PapaJohns GB] Enable proxy

- locations/spiders/cadera_de.py
Fix https://github.com/alltheplaces/alltheplaces/issues/7298
```
{'atp/brand/Cadera': 25,
'atp/brand_wikidata/Q62086410': 25,
'atp/category/shop/bakery': 25,
'atp/field/country/from_spider_name': 25,
'atp/nsi/perfect_match': 25,
'downloader/request_bytes': 659,
'downloader/response_bytes': 48594,
'elapsed_time_seconds': 4.638495,
'finish_time': datetime.datetime(2024, 2, 21, 12, 33, 46, …
```
> Cadera (DE) (shop/bakery) (Wordpress) 

- locations/spiders/outdoor_supply_hardware_us.py
Outdoor Supply Hardware
Hardware store chain in the United States
Q119104427 https://www.wikidata.org/wiki/Q119104427
https://www.outdoorsupplyhardware.com/Locations
```py
{'atp/brand/Outdoor Supply Hardware': 14,
'atp/brand_wikidata/Q119104427': 14,
'atp/category/shop/hardware': 14,
'atp/nsi/perfect_match': 14,
'downloader/request_bytes': 319,
'downloader/response_bytes': 53912, …
```
> Add Outdoor Supply Hardware spider (14 locations)

- locations/spiders/wheel_works_us.py
Wheel Works
Tire retailer in California, US
Q121088283 https://www.wikidata.org/wiki/Q121088283
https://www.wheelworks.net/locate/display-map/ 
https://www.wheelworks.net/site-map/
```py
{'atp/brand/Wheel Works': 28,
'atp/brand_wikidata/Q121088283': 28,
'atp/category/shop/tyres': 28,
'atp/field/image/invalid': 2,
'atp/nsi/perfect_match': 28,
'downloader/request_bytes': 40313,
'downloader/request_count': 82,
'downloader/request_method_count/GET': 82,
'downloader/response_bytes': 581618,
'downloader/response_count': 82,
'downloader/response_status_count/200': 31,
'downloader/response_status_count/301': 42,
'downloader/response_status_count/404': 9, …
```
> Add Wheel Works spider (28 locations)

- locations/spiders/kfc_gb.py
```python
{'atp/brand/KFC': 1040,
'atp/brand_wikidata/Q524757': 1040,
'atp/category/amenity/fast_food': 1040,
'atp/field/email/missing': 1040,
'atp/field/image/missing': 1040,
'atp/field/operator/missing': 1040,
'atp/field/operator_wikidata/missing': 1040,
'atp/field/phone/missing': 1040,
'atp/field/twitter/missing': 1040,
'atp/nsi/cc_match': 1040,
'downloader/request_bytes': 534,
'downloader/response_bytes': 3696381,
'elapsed_time_seconds': 1.572946,
'finish_time': …
```
> [KFC GB] Require proxy

- locations/spiders/hooters.py
```python
{'atp/brand/Hooters': 375,
'atp/brand_wikidata/Q1025921': 375,
'atp/category/amenity/restaurant': 375,
'atp/field/city/missing': 54,
'atp/field/country/from_reverse_geocoding': 375,
'atp/field/email/missing': 375,
'atp/field/image/missing': 375,
'atp/field/opening_hours/missing': 31,
'atp/field/operator/missing': 375,
'atp/field/operator_wikidata/missing': 375,
'atp/field/phone/invalid': 16,
'atp/field/postcode/missing': 374,
'atp/field/twitter/missing': 375,
'atp/nsi/perfect_match': 375,
'downloader/request_bytes': 220479,
'downloader/request_count': 377,
'downloader/request_method_count/GET': 377,
'downloader/response_bytes': 585886,
'downloader/response_count': 377,
'downloader/response_status_count/200': 377, …
```
> [Hooters] Fix spider

- locations/spiders/bricks_minifigs_ca_us.py
Fixes https://github.com/alltheplaces/alltheplaces/issues/7485
{'atp/brand/Bricks & Minifigs': 123,
'atp/brand_wikidata/Q109329121': 123,
'atp/category/shop/toys': 123,
'atp/field/email/missing': 107,
'atp/field/image/missing': 123,
'atp/field/operator/missing': 123,
'atp/field/operator_wikidata/missing': 123,
'atp/field/phone/missing': 76,
'atp/field/state/from_reverse_geocoding': 3,
'atp/field/twitter/missing': 123,
'atp/nsi/perfect_match': 123,
'downloader/request_bytes': 683,
'downloader/response_bytes': 11917, …
> Add Bricks and Minifigs (CA, US) 123 Locations

- locations/storefinders/kibo.py
Sometimes, only a label is supplied, rather than an open time and close time. The label is a text version of the time range the store is open on a given day.
> storefinders/kibo: improve hours extraction

- locations/spiders/usave_gb.py
Fixes https://github.com/alltheplaces/alltheplaces/issues/7502
{'atp/brand/USave': 245,
'atp/brand_wikidata/Q121435010': 245,
'atp/category/shop/convenience': 245,
'atp/field/city/missing': 109,
'atp/field/email/missing': 245,
'atp/field/image/missing': 245,
'atp/field/lat/missing': 12,
'atp/field/lon/missing': 12,
'atp/field/opening_hours/missing': 239,
'atp/field/operator/missing': 245,
'atp/field/operator_wikidata/missing': 245,
'atp/field/phone/missing': 123,
'atp/field/state/missing': 245,
'atp/field/twitter/missing': 245,
'atp/field/website/missing': 245,
'atp/nsi/perfect_match': 245,
'downloader/request_bytes': 725, …
> Add USAVE (GB) 245 locations

- locations/spiders/kitchen_connection_au.py
Fixes https://github.com/alltheplaces/alltheplaces/issues/7515
Again, hours are available but weird:
```
"hours": "    <div class=\"showroom-hours-section\">\n                    <header>\n                <h4>Casula</h4>\n                <h6>Opening Hours</h6>\n            </header>\n                <table class=\"showroom-hours\">\n            <tbody>\n                        <tr>\n                <th>Mon - Wed:</th>\n                <td>9.00am - 5.30pm</td>\n                            <tr>\n                <th>Thursday:</th>\n                <td>9.00am - 7.00pm</td>\n                            <tr>\n                <th>Friday:</th>\n                <td>9.00am - 5.30pm</td>\n                            <tr>\n                <th>Saturday:</th>\n                <td>9.00am - 5.00pm</td>\n …
```
> Add Kitchen Connection (AU) 22 locations

- locations/spiders/sct.py
- locations/spiders/sct_gb.py
Fix https://github.com/alltheplaces/alltheplaces/issues/7301
{'atp/brand/Spitalfields Crypt Trust': 11,
'atp/brand_wikidata/Q107463316': 11,
'atp/category/shop/charity': 11,
'atp/field/image/missing': 11,
'atp/field/website/missing': 11,
'atp/nsi/perfect_match': 11,
'downloader/response_bytes': 2069,
'elapsed_time_seconds': 2.681129,
'finish_time': datetime.datetime(2024, 2, 24, 3, 15, …
> Add Spitalfields Crypt Trust (GB) (shop/charity) (Wordpress) 11 locations

- locations/spiders/petland_us.py
Fix https://github.com/alltheplaces/alltheplaces/issues/7517
{'atp/brand/Petland': 234,
'atp/brand_wikidata/Q17111474': 234,
'atp/category/shop/pet': 234,
'atp/field/email/missing': 231,
'atp/field/image/missing': 234,
'atp/field/opening_hours/missing': 179,
'atp/field/operator/missing': 234,
'atp/field/operator_wikidata/missing': 234,
'atp/field/phone/missing': 65,
'atp/field/postcode/missing': 67,
'atp/field/twitter/missing': 234,
'atp/field/website/missing': 7,
'atp/nsi/perfect_match': 234,
'downloader/response_bytes': 19099, …
> Add Petland (US) 234 locations

- locations/spiders/ohio_cat_us.py
Fix https://github.com/alltheplaces/alltheplaces/issues/7486
{'atp/brand/Ohio CAT': 13,
'atp/brand_wikidata/Q115486235': 13,
'atp/category/shop/trade': 13,
'atp/nsi/perfect_match': 13,
'downloader/response_bytes': 64117,
'elapsed_time_seconds': 3.169997,
'finish_time': datetime.datetime(2024, 2, 25, 21, 19, 13, 745162, tzinfo=datetime.timezone.utc),
'item_scraped_count': 13, …
> Add Ohio CAT (US)

- locations/spiders/reformhaus_bacher_de.py
Fix https://github.com/alltheplaces/alltheplaces/issues/7514
{'atp/brand/Reformhaus Bacher': 50,
'atp/brand_wikidata/Q19816424': 50,
'atp/category/shop/health_food': 50,
'atp/field/country/from_spider_name': 50,
'atp/field/opening_hours/missing': 50,
'atp/nsi/perfect_match': 50,
'downloader/response_bytes': 19421, …
> Add Reformhaus Bacher (DE)

- locations/spiders/markgrafen_getraenkemarkt_de.py
Solves: https://github.com/alltheplaces/alltheplaces/issues/7564
```python
{'atp/brand/Markgrafen Getränkemarkt': 158,
'atp/brand_wikidata/Q100324493': 158,
'atp/category/shop/beverages': 158,
'atp/field/country/from_spider_name': 158,
'atp/field/image/missing': 158,
'atp/field/operator/missing': 158,
'atp/field/operator_wikidata/missing': 158,
'atp/field/state/missing': 157,
'atp/field/twitter/missing': 158,
'atp/field/website/invalid': 157,
'atp/nsi/perfect_match': 158,
'downloader/response_bytes': 220280,
'elapsed_time_seconds': 4.405265, …
```
> [MarkgrafenGetraenkemarktDE] Add spider (158 locations) (#7564)

- locations/spiders/obi_de.py
- locations/spiders/obi_ru.py
Only 29 stores, but these stores are large and popular.
Stats:
```json
{
"atp/brand/OBI": 29,
"atp/brand_wikidata/Q300518": 29,
"atp/category/shop/doityourself": 29,
"atp/closed_poi": 5,
"atp/field/country/from_spider_name": 29,
"atp/field/image/missing": 29,
"atp/field/operator/missing": 29,
"atp/field/operator_wikidata/missing": 29,
"atp/field/phone/invalid": 24,
"atp/field/street_address/missing": 29,
"atp/field/twitter/missing": 29,
"atp/field/website/missing": 29,
"atp/nsi/perfect_match": 29,
"downloader/request_bytes": 310,
"downloader/response_bytes": 355086,
"elapsed_time_seconds": 1.518221, …
```
> [obi_ru] add spider (29 locations)

- locations/spiders/jackinthebox.py
```python
{'atp/brand/Jack in the Box': 2204,
'atp/brand_wikidata/Q1538507': 2204,
'atp/category/amenity/fast_food': 2204,
'atp/field/email/missing': 2204,
'atp/field/image/missing': 2204,
'atp/field/operator/missing': 2204,
'atp/field/operator_wikidata/missing': 2204,
'atp/nsi/perfect_match': 2204,
'downloader/request_bytes': 1254806,
'downloader/request_count': 2206,
'downloader/request_method_count/GET': 2206,
'downloader/response_bytes': 27270055,
'downloader/response_count': 2206,
'downloader/response_status_count/200': 2206,
'elapsed_time_seconds': 14.429617,
'finish_time': datetime.datetime(2024, 2, 26, 13, 42, 23, 832364, tzinfo=datetime.timezone.utc), …
```
> [JackInTheBox] Collect opening hours

- locations/pipelines/apply_nsi_categories.py
- locations/spiders/tier.py
I just want to have another think about the pipeline change, make sure I'm not breaking anything.
Brands that aren't in NSI end up with `wikidata_cache["q123"] = []`. This fails the existing `not wikidata_cache.get`, so we loop NSI on every POI, causing quite a slow down on this spider.
> [Tier] Add spider

- locations/spiders/vlh_de.py
Add spider for german tax advisor: Vereinigte Lohnsteuerhilfe e.V.
```
{'atp/brand/Vereinigte Lohnsteuerhilfe e.V.': 2916,
'atp/brand_wikidata/Q15852617': 2916,
'atp/category/office/tax_advisor': 2916,
'atp/field/country/from_spider_name': 2916,
'atp/field/image/missing': 2916,
'atp/field/opening_hours/missing': 1624,
'atp/field/operator/missing': 2916,
'atp/field/operator_wikidata/missing': 2916,
'atp/field/phone/missing': 37,
'atp/field/state/missing': 2916,
'atp/field/twitter/missing': 2916,
'atp/nsi/perfect_match': 2916,
'downloader/request_bytes': 1065305,
'downloader/request_count': 2918,
'downloader/request_method_count/GET': 2918,
'downloader/response_bytes': 42586355,
'downloader/response_count': 2918,
'downloader/response_status_count/200': 2918, …
```
> [vhlDE] Add Spider (2916 locations)

- DATA_FORMAT.md
- locations/exporters/geojson.py
To some degree, this is just noise. Anyone consuming OSM data has to be able to consume both. However `email` is more popular, with double the usage of `contact:email`. When I added email (`contact:email`), relatively recently, I was fighting the `contact` namespace fight is OSM, that fight is over. No namespace has won, we may as well fall in line with the de facto.
Social media (eg `contact:facebook`) is still far more popular than the none namespaced equivalent, lets stick with the popular version.
> [Exporters] Swicth email key

- locations/hours.py
- locations/storefinders/wp_store_locator.py
Fix https://github.com/alltheplaces/alltheplaces/issues/7360
I feel this is slightly better for wordpress instances as:
- English is still tried first
- As soon as a match is detected the assumption is made spider wide that everything else will be in that language, so the iteration cost is only for the first few matches
- Existing spiders that have set the days to a particular value remain unchanged/that is the way to optimise this.
I've only done it to the wpstorelocator spider for now as it tends to hit mainly one url / it's an API.
But this approach should be applicable more widely.
> WPStoreLocator: Attempt to detect days by frequency

- locations/spiders/hizi_hair_nl.py
Fixes https://github.com/alltheplaces/alltheplaces/issues/7519
{'atp/brand/Hizi Hair': 75,
'atp/brand_wikidata/Q122903761': 75,
'atp/category/shop/hairdresser': 75,
'atp/field/country/from_spider_name': 6,
'atp/field/state/missing': 75,
'atp/field/website/invalid': 68,
'atp/nsi/perfect_match': 75,
'downloader/request_bytes': 671,
'downloader/response_bytes': 7346, …
> Add Hizi Hair (NL)

- locations/spiders/leader_br.py
Fix https://github.com/alltheplaces/alltheplaces/issues/7505
2024-02-29 11:20:30 [scrapy.statscollectors] INFO: Dumping Scrapy stats:
{'atp/brand/Leader': 23,
'atp/brand_wikidata/Q10316732': 23,
'atp/category/shop/department_store': 23,
'atp/field/country/from_spider_name': 6,
'atp/nsi/perfect_match': 23,
'downloader/request_bytes': 705,
'downloader/response_bytes': 3045, …
> Add Leader(BR)

- locations/spiders/sanel_napa.py
Fix https://github.com/alltheplaces/alltheplaces/issues/7372
{'atp/brand/Sanel NAPA': 46,
'atp/brand_wikidata/Q122564780': 46,
'atp/category/shop/car_parts': 46,
'atp/field/email/missing': 46,
'atp/field/image/missing': 46,
'atp/field/opening_hours/missing': 46,
'atp/field/operator/missing': 46,
'atp/field/operator_wikidata/missing': 46,
'atp/field/twitter/missing': 46,
'atp/nsi/perfect_match': 46,
'downloader/request_bytes': 667,
'downloader/response_bytes': 4672,
'elapsed_time_seconds': 2.79168,
'finish_time': datetime.datetime(2024, 2, 29, 11, 5, 13, 633860, tzinfo=datetime.timezone.utc), …
> Add Sanel NAPA (shop/car_parts) (Wordpress)

- locations/linked_data_parser.py
- locations/spiders/belhaven_pubs_gb.py
This is both, 1. good for users to be able to click through, and 2. helpful for conflation when using multiple POI sources.
> [LinkedData] Extract Tripadvisor URLs

- locations/spiders/skechers.py
Fixes https://github.com/alltheplaces/alltheplaces/issues/7560
```
2024-03-02 15:13:04 [scrapy.core.scraper] DEBUG: Scraped from <200 https://hosted.where2getit.com//rest/getlist>
{'brand': 'Skechers',
'brand_wikidata': 'Q2945643',
'city': 'Niagara Falls',
'email': None,
'extras': {'@spider': 'skechers', 'shop': 'shoes'},
'geometry': {'coordinates': [-78.9811362, 43.0880235], 'type': 'Point'},
'name': 'SKECHERS Niagara Consumer Square',
'nsi_id': 'skechers-9b62dc',
'phone': '+1 716-402-5052',
'postcode': '14304',
'ref': 'Store 1365',
'state': 'NY',
'street_address': '7260 Niagara Falls Blvd',
'website': None}
2024-03-02 15:13:04 [scrapy.core.engine] INFO: Closing spider (finished)
2024-03-02 15:13:04 [locations.pipelines.duplicates] …
```
> Add skechers

- locations/spiders/alltown_us.py
Fixes https://github.com/alltheplaces/alltheplaces/issues/7500
Note: 
The URL does https://www.alltown.com/wp-admin/admin-ajax.php?action=store_search&....&max_results=100&search_radius=1000&skip_cache=1
So the 50 results I think is just... 50 results.
{'atp/brand/Alltown': 50,
'atp/brand_wikidata/Q119586667': 50,
'atp/category/missing': 50,
'atp/field/opening_hours/missing': 50,
'atp/nsi/match_failed': 50,
'downloader/request_bytes': 1303, …
> Add Alltown (US)

- locations/spiders/alltown_fresh_us.py
Fixes https://github.com/alltheplaces/alltheplaces/issues/7495
Note: There's a seperate one for alltown carwashes (self service) and alltown service stations it seems
{'atp/brand/Alltown Fresh': 16,
'atp/brand_wikidata/Q119591365': 16,
'atp/category/shop/convenience': 16,
'atp/nsi/perfect_match': 16,
'downloader/response_bytes': 4020, …
> Add Alltown Fresh (US)

- locations/spiders/nothing_bundt_cakes_us_ca.py
Fixes https://github.com/alltheplaces/alltheplaces/issues/1665
```
{'brand': 'Nothing Bundt Cakes',
'brand_wikidata': 'Q62082526',
'city': 'Santa Fe',
'email': 'SantaFe-NM@nothingbundtcakes.com',
'extras': {'@spider': 'nothing_bundt_cakes_us_ca', 'shop': 'pastry'},
'facebook': 'https://www.facebook.com/nothingbundtcakes/',
'geometry': {'coordinates': [-105.9522934, 35.6726808], 'type': 'Point'},
'image': None,
'name': 'Santa Fe NM Bakery & Cake Shop',
'nsi_id': 'nothingbundtcakes-e06bde',
'opening_hours': 'Mo-Fr 09:00-18:00; Sa 10:00-18:00',
'phone': '+1 505-230-1325',
'postcode': '87505',
'ref': 'https://www.nothingbundtcakes.com/find-a-bakery/nm/santafe/bakery-471.html',
'state': 'NM',
'street_address': '524A W Cordova Rd',
'website': …
```
> Add Nothing Bundt Cakes (US, CA)

- locations/spiders/daylight_donuts_us.py
- locations/storefinders/wp_store_locator.py
Fixes https://github.com/alltheplaces/alltheplaces/issues/941
```
{'atp/brand/Daylight Donuts': 323,
'atp/brand_wikidata/Q48970508': 323,
'atp/category/amenity/fast_food': 323,
'atp/closed_check': 2,
'atp/field/country/from_spider_name': 217,
'atp/field/email/missing': 264,
'atp/field/image/missing': 323,
'atp/field/operator/missing': 323,
'atp/field/operator_wikidata/missing': 323,
'atp/field/twitter/missing': 323,
'atp/field/website/missing': 317,
'atp/nsi/perfect_match': 323,
'downloader/request_bytes': 851,
'downloader/response_bytes': 85413, …
```
> Add Daylight Donuts (US) (and fix small but important wordpress regression)

- locations/spiders/van_wall_us.py
Fixes https://github.com/alltheplaces/alltheplaces/issues/1674
No wikidata entry
2024-03-03 03:12:35 [scrapy.core.engine] INFO: Closing spider (finished)
2024-03-03 03:12:35 [locations.pipelines.duplicates] INFO: Dropped 0 duplicate items
2024-03-03 03:12:35 [scrapy.statscollectors] INFO: Dumping Scrapy stats:
{'atp/brand/Van Wall': 31,
'atp/category/shop/plant_hire': 31,
'atp/field/brand_wikidata/missing': 31,
'downloader/request_bytes': 734, …
> Add Van Wall (US) 31 locations

- locations/dict_parser.py
- tests/test_dict_parser.py
Commit e3ecda5778fdff7ba8261ca4fd3a2cc678abfde7 tried to standardise case of reference keys. The idea was that the variation function would try all possibilities of case for each key (camel case, title case, uppercase, lowercase, etc).
Unfortunately it was forgotten that the "ID" acronym in reference keys cannot be handled well by the variations function. It is common for a reference key to always capitalise acronyms, particularly "ID", whilst using some other case for everything else.
This change should fix a number of spiders that were returning 0 or 1 result due to lack of ability to set unique references for each location scraped.
> DictParser: fix reference keys

- locations/spiders/natwest_gb.py
Fixes #5782
```python
{'atp/brand/NatWest': 446,
'atp/brand_wikidata/Q2740021': 446,
'atp/category/amenity/bank': 446,
'atp/field/email/missing': 446,
'atp/field/image/missing': 446,
'atp/field/operator/missing': 446,
'atp/field/operator_wikidata/missing': 446,
'atp/field/phone/missing': 446,
'atp/field/twitter/missing': 446,
'atp/nsi/category_match': 446,
'downloader/request_bytes': 771457,
'downloader/request_count': 989,
'downloader/request_method_count/GET': 989,
'downloader/response_bytes': 19182624,
'downloader/response_count': 989,
'downloader/response_status_count/200': 989,
'elapsed_time_seconds': 49.007578,
'finish_reason': 'cancelled',
'finish_time': datetime.datetime(2024, 3, 3, 10, 1, 31, …
```
> [NatWest GB] Add spider

- locations/spiders/aldi_sud_de.py
Because it no longer has a country code in [NSI](https://github.com/osmlab/name-suggestion-index/pull/9274), we can't match against it so I've manually added the name.
> [Aldi Sud DE] Restore name

- locations/spiders/brewers_gb.py
Fixes #7688
```python
{'atp/brand/Brewers': 200,
'atp/brand_wikidata/Q121435210': 200,
'atp/category/shop/paint': 200,
'atp/field/operator/missing': 200,
'atp/field/operator_wikidata/missing': 200,
'atp/nsi/perfect_match': 200,
'downloader/request_bytes': 192187,
'downloader/request_count': 202,
'downloader/request_method_count/GET': 202,
'downloader/response_bytes': 3175885,
'downloader/response_count': 202,
'downloader/response_status_count/200': 202,
'elapsed_time_seconds': 1.674184,
'finish_time': datetime.datetime(2024, 3, 5, 13, 51, 22, 962362, tzinfo=datetime.timezone.utc),
'httpcache/hit': 202,
'httpcompression/response_bytes': 13382312,
'httpcompression/response_count': 201, …
```
> [Brewers GB] Add spider

- locations/spiders/united_petroleum_au.py
I know you have some concerns over outputting multiple POIs at one location, but outputting:
```
name=United Wynyard
amenity=fast_food;fuel;restaurant
shop=convenience
```
For [this](https://www.google.com/maps/place/United+Petroleum+Wynyard+(Pie+Face)/@-40.9897012,145.723124,3a,75y,178.48h,86.72t/data=!3m7!1e1!3m5!1sBkFzYZWTWucmpMjAnMImeA!2e0!6shttps:%2F%2Fstreetviewpixels-pa.googleapis.com%2Fv1%2Fthumbnail%3Fpanoid%3DBkFzYZWTWucmpMjAnMImeA%26cb_client%3Dmaps_sv.tactile.gps%26w%3D203%26h%3D100%26yaw%3D110.145294%26pitch%3D0%26thumbfov%3D100!7i16384!8i8192!4m7!3m6!1s0xaa7bf3d5b0c609f3:0x350b13086e92c7f4!8m2!3d-40.9898671!4d145.7231398!10e5!16s%2Fg%2F11b6ntfml_?entry=ttu) isn't usable. If you really don't want to output these, I'd vote to drop them, not merge them into the fuel station.
> [UnitedPetroleum AU] Seperate Pie Face and Quick Stop POIs

- locations/spiders/europam_it.py
```python
{'atp/brand/Europam': 208,
'atp/brand_wikidata/Q115268198': 208,
'atp/category/amenity/fuel': 208,
'atp/cdn/cloudflare/response_count': 214,
'atp/cdn/cloudflare/response_status_count/200': 214,
'atp/field/country/from_spider_name': 208,
'atp/field/email/missing': 208,
'atp/field/opening_hours/missing': 208,
'atp/field/operator/missing': 208,
'atp/field/operator_wikidata/missing': 208,
'atp/field/phone/missing': 208,
'atp/field/state/missing': 208,
'atp/field/twitter/missing': 208,
'atp/nsi/category_match': 208,
'downloader/request_bytes': 89465,
'downloader/request_count': 217,
'downloader/request_method_count/GET': 217,
'downloader/response_bytes': 5685899,
'downloader/response_count': 217,
'downloader/response_status_count/200': 214, …
```
> [Europam IT] Add Spider

- locations/spiders/gov_osservaprezzi_carburanti_it.py
The names coming out of this are quite bad, I wouldn't be surprised if they are operators/legal entities, eg `EUROPAM CASTELNUOVO BOCCA D'ADDA`.
I propose, we use the NSI name when possible, and use the supplied brand as the name otherwise. That just leaves the independent POIs with unappealing names.
> [Gov Osservaprezzi Carburanti IT] Clean up names

- .isort.cfg
- locations/categories.py
- locations/spiders/avia_de.py
- locations/spiders/avia_hu.py
- locations/spiders/avia_pl.py
- locations/spiders/avia_rs.py
- tests/test_categories.py
<details><summary> avia_pl stats</summary>
```json
{
"atp/brand/Avia": 127,
"atp/brand_wikidata/Q300147": 127,
"atp/category/amenity/fuel": 127,
"atp/field/city/missing": 127,
"atp/field/country/from_spider_name": 127,
"atp/field/email/missing": 127,
"atp/field/image/missing": 127,
"atp/field/opening_hours/missing": 52,
"atp/field/operator/missing": 127,
"atp/field/operator_wikidata/missing": 127,
"atp/field/phone/missing": 54,
"atp/field/postcode/missing": 127,
"atp/field/state/missing": 127,
"atp/field/street_address/missing": 127,
"atp/field/twitter/missing": 127,
"atp/nsi/category_match": 127,
"downloader/request_bytes": 1233,
"downloader/request_count": 4,
"downloader/request_method_count/GET": 4,
"downloader/response_bytes": 41954, …
```
> [avia_pl][avia_de] add spiders, use shared attributes, add map_payment utility

- locations/spiders/kvickly_coop_dk.py
Fixes https://github.com/alltheplaces/alltheplaces/issues/7681
{'atp/brand/Kvickly': 65,
'atp/brand_wikidata/Q7061148': 65,
'atp/category/shop/supermarket': 65,
'atp/field/country/from_spider_name': 65,
'atp/field/opening_hours/missing': 65,
'atp/field/state/missing': 65,
'downloader/request_bytes': 435,
'downloader/response_bytes': 5663, …
> Kvickly (DK)

- locations/spiders/second_cup_ca.py
Fix https://github.com/alltheplaces/alltheplaces/issues/67
{'atp/brand/Second Cup': 170,
'atp/brand_wikidata/Q862180': 170,
'atp/category/amenity/cafe': 170,
'atp/field/email/missing': 170,
'atp/field/image/missing': 170,
'atp/field/opening_hours/missing': 88,
'atp/field/operator/missing': 170,
'atp/field/operator_wikidata/missing': 170,
'atp/field/state/from_reverse_geocoding': 3,
'atp/nsi/perfect_match': 170,
'downloader/request_bytes': 71893,
'downloader/request_count': 191,
'downloader/request_method_count/GET': 191,
'downloader/response_bytes': 5715917,
'downloader/response_count': 191,
'downloader/response_status_count/200': 190, …
> Add Second Cup (CA)

- locations/spiders/golden_discs_ie.py
Fix https://github.com/alltheplaces/alltheplaces/issues/7738
{'atp/brand/Golden Discs': 19,
'atp/brand_wikidata/Q5579324': 19,
'atp/category/shop/music': 19,
'atp/field/postcode/missing': 18,
'atp/field/street_address/missing': 19,
'atp/nsi/perfect_match': 19,
'downloader/request_bytes': 367,
'downloader/response_bytes': 3155, …
> Add Golden Discs (IE)

- locations/hours.py
- locations/spiders/bolo_da_madre_br.py
Fix https://github.com/alltheplaces/alltheplaces/issues/7668
{'atp/brand/Bolo da Madre': 29,
'atp/brand_wikidata/Q121322483': 29,
'atp/category/shop/pastry': 29,
'atp/field/city/missing': 29,
'atp/field/country/missing': 29,
'atp/field/lat/missing': 29,
'atp/field/lon/missing': 29,
'atp/field/phone/invalid': 23,
'atp/field/postcode/missing': 29,
'atp/field/state/missing': 29,
'atp/field/street_address/missing': 29,
'atp/nsi/perfect_match': 29, …
> Add Bolo da Madre (BR)

- locations/spiders/goddard_school.py
Fix https://github.com/alltheplaces/alltheplaces/issues/2166
{'atp/brand/Goddard School': 648,
'atp/brand_wikidata/Q5576260': 648,
'atp/category/amenity/kindergarten': 648,
'atp/field/country/from_reverse_geocoding': 648,
'atp/field/image/missing': 648,
'atp/field/operator/missing': 648,
'atp/field/operator_wikidata/missing': 648,
'atp/field/twitter/missing': 648,
'atp/nsi/perfect_match': 648,
'downloader/request_bytes': 325,
'downloader/response_bytes': 115400,
'elapsed_time_seconds': 30.901684,
'finish_time': datetime.datetime(2024, 3, 10, 4, 51, 58, 588141, …
> Fix Goddard School

- locations/spiders/dick_blick.py
Fixes https://github.com/alltheplaces/alltheplaces/issues/2729
{'atp/brand/Dick Blick': 64,
'atp/brand_wikidata/Q5272692': 64,
'atp/category/missing': 64,
'atp/closed_check': 3,
'atp/field/city/missing': 57,
'atp/field/operator/missing': 64,
'atp/field/operator_wikidata/missing': 64,
'atp/field/state/from_reverse_geocoding': 56,
'atp/nsi/brand_missing': 64,
'downloader/request_bytes': 24942,
'downloader/request_count': 75,
'downloader/request_method_count/GET': 75,
'downloader/response_bytes': 15349783,
'downloader/response_count': 75,
'downloader/response_status_count/200': 75,
'elapsed_time_seconds': 93.344526,
'finish_time': datetime.datetime(2024, 3, 10, 7, 26, 34, 118392, tzinfo=datetime.timezone.utc), …
> Fix Dick Blick

- locations/spiders/oreilly_auto.py
Fix https://github.com/alltheplaces/alltheplaces/issues/3015
Works for me when I run it
```2024-03-10 06:26:59 [scrapy.core.scraper] DEBUG: Scraped from <200 https://locations.oreillyauto.com/al/evergreen/autoparts-2286.html>
{'brand': "O'Reilly Auto Parts",
'brand_wikidata': 'Q7071951',
'city': 'Evergreen',
'email': None,
'extras': {'@spider': 'oreilly', 'shop': 'car_parts'},
'facebook': 'https://www.facebook.com/OreillyAutoParts',
'geometry': {'coordinates': [-86.957833, 31.432002], 'type': 'Point'},
'image': None,
'name': "Your Evergreen O'Reilly Auto Parts Store",
'nsi_id': 'oreillyautoparts-bb9baa',
'opening_hours': 'Mo-Sa 07:00-20:00; Su 08:00-19:00',
'phone': '+1 251-578-1610',
'postcode': '36401',
'ref': 'https://locations.oreillyauto.com/al/evergreen/autoparts-228 …
```
> O'Rielly Auto Parts - Flag for Proxy

- locations/spiders/argos.py
Fix https://github.com/alltheplaces/alltheplaces/issues/3063
Works when I run it.
Partial run:
```
{'atp/brand/Argos': 83,
'atp/brand_wikidata/Q4789707': 83,
'atp/category/shop/catalogue': 83,
'atp/field/country/from_website_url': 83,
'atp/field/email/missing': 83,
'atp/field/image/missing': 83,
'atp/field/operator/missing': 83,
'atp/field/operator_wikidata/missing': 83,
'atp/field/state/missing': 83,
'atp/nsi/perfect_match': 83,
'downloader/request_bytes': 105724,
'downloader/request_count': 88,
'downloader/request_method_count/GET': 88,
'downloader/response_bytes': 4170305,
'downloader/response_count': 88,
'downloader/response_status_count/200': 85, …
```
> Argos - Flag for proxy

- locations/spiders/jcpenney.py
Fix https://github.com/alltheplaces/alltheplaces/issues/3082
Another one where it works when I run it, so proxy likely the issue.
Partial run:
```
{'atp/brand/JCPenney': 192,
'atp/brand_wikidata/Q920037': 192,
'atp/category/shop/department_store': 192,
'atp/cdn/cloudflare/response_count': 210,
'atp/cdn/cloudflare/response_status_count/200': 210,
'atp/field/email/missing': 192,
'atp/field/operator/missing': 192,
'atp/field/operator_wikidata/missing': 192,
'atp/field/twitter/missing': 192,
'atp/nsi/category_match': 191,
'downloader/request_bytes': 309207,
'downloader/request_count': 217,
'downloader/request_method_count/GET': 217,
'downloader/response_bytes': 11466611,
'downloader/response_count': 217, …
```
> JCPenney - Flag for proxy

- locations/spiders/sentryfoods.py
Fix https://github.com/alltheplaces/alltheplaces/issues/3102
{'atp/brand/Sentry Foods': 9,
'atp/brand_wikidata/Q7451397': 9,
'atp/category/missing': 9,
'atp/nsi/brand_missing': 9,
'downloader/request_bytes': 647,
'downloader/response_bytes': 3907,
'elapsed_time_seconds': 2.271459,
'finish_time': datetime.datetime(2024, 3, 10, 6, 7, 3, 295120, …
> Rewrite SentryFoods as FreshOp

- locations/spiders/johnlewis.py
Fix https://github.com/alltheplaces/alltheplaces/issues/3087 maybe
Works happily when I run it, so assume proxy issue.
{'atp/brand/John Lewis': 36,
'atp/brand_wikidata/Q1918981': 36,
'atp/category/shop/department_store': 36,
'atp/field/country/from_reverse_geocoding': 36,
'atp/nsi/perfect_match': 36,
'downloader/request_bytes': 104526,
'downloader/request_count': 46,
'downloader/request_method_count/GET': 46,
'downloader/response_bytes': 1435631,
'downloader/response_count': 46,
'downloader/response_status_count/200': 38,
'downloader/response_status_count/303': 8, …
> John Lewis - Mark as needing proxy

- locations/spiders/lavieclare_fr.py
Fix https://github.com/alltheplaces/alltheplaces/issues/7780
Partial run:
```
{'brand': 'La Vie Claire',
'brand_wikidata': 'Q3213589',
'city': 'Paris',
'country': 'FR',
'email': None,
'extras': {'@spider': 'lavieclaire_fr'},
'facebook': 'https://www.facebook.com/Lavieclaire/',
'geometry': {'coordinates': [2.378632, 48.85606], 'type': 'Point'},
'image': 'https://magasins.lavieclaire.com/uploads/other/image-60643d04450c24.60763451.jpeg',
'name': 'Magasin bio La Vie Claire Paris Ledru Rollin',
'opening_hours': 'Mo-Sa 09:30-20:00; Su 09:00-12:30',
'phone': '+33 1 40 09 09 42',
'postcode': '75011',
'ref': 'https://magasins.lavieclaire.com/lavieclaire/fr/store/france/ile-de-france/paris/paris/paris-ledru-rollin/17521',
'state': None,
'street_address': '163, avenue Ledru Rollin',
'twitter': …
```
> Add La Vie Claire (FR)

- locations/spiders/nails_for_you_ca.py
Fix https://github.com/alltheplaces/alltheplaces/issues/7139
{'atp/brand/Nails for You': 107,
'atp/brand_wikidata/Q123410053': 107,
'atp/category/shop/beauty': 107,
'atp/field/email/missing': 104,
'atp/field/image/missing': 107,
'atp/field/operator/missing': 107,
'atp/field/operator_wikidata/missing': 107,
'atp/field/street_address/missing': 6,
'atp/field/twitter/missing': 107,
'atp/field/website/missing': 78,
'atp/nsi/perfect_match': 107,
'downloader/request_bytes': 672, …
> Add Nails for You (CA)

- locations/spiders/gall_and_gall_nl.py
Fix https://github.com/alltheplaces/alltheplaces/issues/7002
{'atp/brand/Gall & Gall': 636,
'atp/brand_wikidata/Q13639185': 636,
'atp/category/shop/alcohol': 636,
'atp/field/email/missing': 636,
'atp/field/image/missing': 636,
'atp/field/operator/missing': 636,
'atp/field/operator_wikidata/missing': 636,
'atp/field/state/missing': 636,
'atp/field/twitter/missing': 636,
'atp/nsi/perfect_match': 636,
'downloader/request_bytes': 365,
'downloader/response_bytes': 61969,
'elapsed_time_seconds': 4.268416,
'finish_time': datetime.datetime(2024, 3, 11, 3, …
> Add Gall & Gall

- locations/spiders/chinnaholic_us.py
Fix https://github.com/alltheplaces/alltheplaces/issues/7806
```
{'atp/brand/Cinnaholic': 116,
'atp/brand_wikidata/Q48965480': 116,
'atp/category/shop/bakery': 116,
'atp/field/image/missing': 116,
'atp/field/opening_hours/missing': 116,
'atp/field/operator/missing': 116,
'atp/field/operator_wikidata/missing': 116,
```
> Cinnaholic (US)

- locations/spiders/shoppers_food_us.py
FIx https://github.com/alltheplaces/alltheplaces/issues/7792
{'atp/brand/Shoppers Food & Pharmacy': 29,
'atp/brand_wikidata/Q7501183': 29,
'atp/category/shop/supermarket': 29,
'atp/field/city/missing': 12,
'atp/field/lat/missing': 29,
'atp/field/lon/missing': 29,
'atp/field/postcode/missing': 12,
'atp/field/street_address/missing': 12,
'atp/field/twitter/invalid': 29,
'atp/nsi/perfect_match': 29,
'downloader/request_bytes': 20614,
'downloader/request_count': 31,
'downloader/request_method_count/GET': 31, …
> Shoppers food

- locations/spiders/lab_corp_us.py
```python
{'atp/brand/LabCorp': 2116,
'atp/brand_wikidata/Q6466630': 2116,
'atp/category/healthcare/laboratory': 2116,
'atp/field/email/missing': 2116,
'atp/field/image/dropped': 2116,
'atp/field/image/missing': 2116,
'atp/field/lat/invalid': 8,
'atp/field/opening_hours/missing': 2116,
'atp/field/operator/missing': 2116,
'atp/field/operator_wikidata/missing': 2116,
'atp/field/twitter/missing': 2116,
'atp/nsi/perfect_match': 2116,
'downloader/request_bytes': 796479,
'downloader/request_count': 2119,
'downloader/request_method_count/GET': 2119,
'downloader/response_bytes': 58822323,
'downloader/response_count': 2119,
'downloader/response_status_count/200': 2119, …
```
> [LabCorp US] Add spider

- locations/spiders/mcdonalds_cz.py
The `name` tag contained the address instead of the actual name. It seems that this is the case for other McDonald's scrapers as well but there are exceptions, for example `mcdonalds_hr`.
> fix mcdonalds_cz name attribute

- locations/spiders/nhs_england_gb.py
```python
{'atp/category/amenity/dentist': 6132,
'atp/category/amenity/doctors': 8558,
'atp/category/multiple': 14690,
'atp/cdn/akamai/response_count': 9,
'atp/cdn/akamai/response_status_count/403': 9,
'atp/field/brand/missing': 14690,
'atp/field/brand_wikidata/missing': 14690,
'atp/field/city/missing': 14690,
'atp/field/country/from_spider_name': 14690,
'atp/field/email/invalid': 14,
'atp/field/email/missing': 6898,
'atp/field/image/missing': 14690,
'atp/field/opening_hours/missing': 846,
'atp/field/operator/missing': 14690,
'atp/field/operator_wikidata/missing': 14690,
'atp/field/phone/invalid': 20,
'atp/field/phone/missing': 623,
'atp/field/state/missing': 14690,
'atp/field/street_address/missing': 14690, …
```
> [NHS England] Fix GPs

- locations/spiders/spar_no.py
Fix https://github.com/alltheplaces/alltheplaces/issues/2923
{'atp/brand/Spar': 288,
'atp/brand_wikidata/Q610492': 288,
'atp/category/missing': 288,
'atp/field/country/from_spider_name': 288,
'atp/field/image/missing': 288,
'atp/field/opening_hours/missing': 288,
'atp/field/operator/missing': 288,
'atp/field/operator_wikidata/missing': 288,
'atp/field/twitter/missing': 288,
'atp/nsi/match_failed': 288,
'downloader/response_bytes': 232705,
'elapsed_time_seconds': 4.04131, …
> Fix Spar (NO)

- locations/spiders/narbutikken_no.py
Fix https://github.com/alltheplaces/alltheplaces/issues/7880
{'atp/brand/Nærbutikken': 141,
'atp/brand_wikidata/Q108810007': 141,
'atp/category/shop/supermarket': 141,
'atp/field/country/from_spider_name': 141,
'atp/field/image/missing': 141,
'atp/field/opening_hours/missing': 141,
'atp/field/operator/missing': 141,
'atp/field/operator_wikidata/missing': 141,
'atp/field/twitter/missing': 141,
'atp/nsi/perfect_match': 141,
'downloader/response_bytes': 110904,
'elapsed_time_seconds': 4.786184, …
> Add Nærbutikken (NO)

- locations/storefinders/sylinder.py
#7862
Turns out, you can just do an API call filtered by chainId for everything.
> Extend Sylinder storefinder to get hours by default

- locations/spiders/shell.py
Whenever there is a shop attached to the shell fuel station I think we should add a separate POI with the same address and coords. As a lot of the times it is not a shell convenience store that is attached. Now we do not know the name of the shop but we can still add it. Curious at peoples thoughts about this.
```python
{'atp/brand/Shell': 63876,
'atp/brand_wikidata/Q110716465': 63876,
'atp/category/amenity/fuel': 41602,
'atp/category/shop/convenience': 22274,
'atp/field/city/missing': 1137,
'atp/field/email/missing': 63876,
'atp/field/image/missing': 63876,
'atp/field/name/missing': 22274,
'atp/field/opening_hours/missing': 39389,
'atp/field/operator/missing': 63876,
'atp/field/operator_wikidata/missing': 63876,
'atp/field/phone/invalid': 778, …
```
> [shell] Create convenience POI when shop is in amenitites (63876 items)

- locations/spiders/naturalia_fr.py
Fix https://github.com/alltheplaces/alltheplaces/issues/7885
Partial run:
2024-03-17 01:46:15 [scrapy.statscollectors] INFO: Dumping Scrapy stats:
{'atp/brand/Naturalia': 156,
'atp/brand_wikidata/Q3337081': 156,
'atp/category/shop/supermarket': 156,
'atp/field/email/missing': 156,
'atp/field/operator/missing': 156,
'atp/field/operator_wikidata/missing': 156,
'atp/field/state/missing': 156,
'atp/nsi/perfect_match': 156,
'downloader/request_bytes': 81697,
'downloader/request_count': 160,
'downloader/request_method_count/GET': 160,
'downloader/response_bytes': 2647618,
'downloader/response_count': 160,
'downloader/response_status_count/200': 159, …
> Add Naturalia (FR)

- locations/spiders/animates_nz.py
- locations/storefinders/aheadworks.py
Fix https://github.com/alltheplaces/alltheplaces/issues/7663
{'atp/brand/Animates': 53,
'atp/brand_wikidata/Q110299350': 53,
'atp/category/shop/pet': 53,
'atp/field/image/missing': 53,
'atp/field/operator/missing': 53,
'atp/field/operator_wikidata/missing': 53,
'atp/field/twitter/missing': 53,
'atp/nsi/category_match': 53,
'downloader/request_bytes': 620,
'downloader/response_bytes': 923750,
'elapsed_time_seconds': 3.095533,
'finish_time': datetime.datetime(2024, 3, 17, 2, 50, 45, 364818, tzinfo=datetime.timezone.utc),
'httpcompression/response_bytes': 1867, …
> Add Animates(NZ) and a base class for the Aheadworks Storefinder

- locations/spiders/storcash_no.py
- locations/storefinders/sylinder.py
Fixes #7908.
Unfortunately tricky to avoid the hardcoding of chains unless I match the store names.
{'atp/brand/Storcash': 8,
'atp/category/shop/wholesale': 8,
'atp/field/brand_wikidata/missing': 8,
'atp/field/country/from_spider_name': 8,
'downloader/request_bytes': 645,
'downloader/response_bytes': 10483540,
'elapsed_time_seconds': 34.937097,
'finish_time': datetime.datetime(2024, 3, 17, 3, 31, 55, …
> Add Storcash (NO)

- locations/spiders/linde_direct_us.py
Fix https://github.com/alltheplaces/alltheplaces/issues/810
{'atp/brand/Linde Gas & Equipment': 325,
'atp/brand_wikidata/Q902780': 325,
'atp/category/missing': 325,
'atp/field/country/from_spider_name': 325,
'atp/field/email/missing': 325,
'atp/field/image/missing': 325,
'atp/field/operator/missing': 325,
'atp/field/operator_wikidata/missing': 325,
'atp/field/street_address/missing': 325,
'atp/field/twitter/missing': 325,
'atp/nsi/brand_missing': 325,
'downloader/request_bytes': 736,
'downloader/response_bytes': 132503,
'elapsed_time_seconds': 2.959334,
'finish_time': datetime.datetime(2024, 3, 17, 8, 0, 19, …
> Add Linde Gas & Equipment (US) (formerly Praxis)

- locations/spiders/kiwi_no.py
https://github.com/alltheplaces/alltheplaces/issues/7862
{'atp/brand/Kiwi': 707,
'atp/brand_wikidata/Q1613639': 707,
'atp/category/shop/supermarket': 707,
'atp/field/country/from_spider_name': 707,
'atp/field/image/missing': 707,
'atp/field/operator/missing': 707,
'atp/field/operator_wikidata/missing': 707,
'atp/field/twitter/missing': 707,
'atp/nsi/perfect_match': 707,
'downloader/request_bytes': 658,
'downloader/response_bytes': 4050447,
'elapsed_time_seconds': 17.354155, …
> Add KIWI (NO)

- locations/spiders/a3_sport_cz.py
Fix https://github.com/alltheplaces/alltheplaces/issues/7920
{'atp/brand/A3 Sport': 43,
'atp/brand_wikidata/Q58170961': 43,
'atp/category/shop/sports': 43,
'atp/field/country/from_website_url': 43,
'atp/field/image/missing': 43,
'atp/field/state/missing': 43,
'atp/field/street_address/missing': 43,
'atp/field/twitter/missing': 43,
'atp/nsi/perfect_match': 43,
'downloader/request_bytes': 639,
'downloader/response_bytes': 17590,
'elapsed_time_seconds': 4.009077, …
> Add A3 Sport (CZ)

- locations/spiders/refuel_double_quick_us.py
'atp/brand/Double Quick': 50,
'atp/brand/Refuel': 177,
Fixes #7982
> Add Refuel and Double Quick (US) (227 locations)

- locations/spiders/foodland_us.py
'atp/brand/Foodland': 22,
'atp/brand/Foodland Farms': 6,
"atp/brand/Sack 'N Save": 5,
Fixes #7551
> Add Foodland, Foodland Farms and Sack N Save (US) (34 locations)

- locations/spiders/waitrose.py
Fixes #7994
https://gist.github.com/Cj-Malone/4d7703ece53a426e910921ef8b417abe
```python
{'atp/brand/Little Waitrose': 107,
'atp/brand/Waitrose': 309,
'atp/brand_wikidata/Q771734': 416,
'atp/category/shop/convenience': 107,
'atp/category/shop/supermarket': 309,
'atp/cdn/cloudflare/response_count': 423,
'atp/cdn/cloudflare/response_status_count/200': 419,
'atp/cdn/cloudflare/response_status_count/404': 4,
'atp/field/email/missing': 416,
'atp/field/image/missing': 416,
'atp/field/operator/missing': 416,
'atp/field/operator_wikidata/missing': 416,
'atp/field/state/missing': 413,
'atp/field/twitter/missing': 416,
'atp/nsi/category_match': 307,
'atp/nsi/match_failed': 109,
'downloader/request_bytes': 605493,
'downloader/request_count': 426, …
```
> [Waitrose] Fix spider

- locations/categories.py
- locations/spiders/kwik_trip.py
```python
{'atp/brand/Kwik Star': 131,
'atp/brand/Kwik Trip': 743,
'atp/brand_wikidata/Q123269534': 131,
'atp/brand_wikidata/Q6450420': 743,
'atp/category/amenity/fuel': 847,
'atp/category/shop/convenience': 14,
'atp/category/shop/tobacco': 13,
'atp/field/country/from_reverse_geocoding': 874,
'atp/field/email/missing': 874,
'atp/field/image/missing': 874,
'atp/field/operator/missing': 874,
'atp/field/operator_wikidata/missing': 874,
'atp/field/twitter/missing': 874,
'atp/nsi/category_match': 861,
'atp/nsi/match_failed': 13,
'downloader/request_bytes': 759912,
'downloader/request_count': 879,
'downloader/request_method_count/GET': 879,
'downloader/response_bytes': 1295660,
'downloader/response_count': 879,
'downloader/response_status_count/200': 878, …
```
> [KwikTrip] Collect opening hours and more attributes

- locations/spiders/costco_ca.py
```python
{'atp/brand/Costco': 108,
'atp/brand_wikidata/Q715583': 108,
'atp/category/shop/wholesale': 108,
'atp/field/country/from_spider_name': 108,
'atp/field/email/missing': 108,
'atp/field/image/missing': 108,
'atp/field/opening_hours/missing': 108,
'atp/field/operator/missing': 108,
'atp/field/operator_wikidata/missing': 108,
'atp/field/twitter/missing': 108,
'atp/nsi/match_failed': 108,
'downloader/request_bytes': 432914,
'downloader/request_count': 119,
'downloader/request_method_count/GET': 119,
'downloader/response_bytes': 11841509,
'downloader/response_count': 119,
'downloader/response_status_count/200': 117,
'downloader/response_status_count/404': 2,
'elapsed_time_seconds': 4.47827,
'finish_time': …
```
> [Costco CA] Add spider

- locations/spiders/enterprise.py
Category was a bit inconsistent, e.g. in last weekly:
```
"atp/category/amenity/car_rental": 2591,
"atp/category/shop/rental": 6028,
```
Now it's car rental as it should be.
> [enterprise] apply category manually

- ci/buildspec.yml
- locations/spiders/amc_theatres_us.py
This adds a step to cache Python dependencies to S3 so that install of dependencies doesn't take ~60 seconds every time.
> Cache Python dependencies to S3 for CodeBuild to run faster

- ci/buildspec.yml
- locations/spiders/aerie.py
Rel: https://github.com/osmlab/name-suggestion-index/pull/9328
```python
{'atp/brand/Aerie': 182,
'atp/brand_wikidata/Q25351619': 182,
'atp/category/shop/clothes': 182,
'atp/cdn/cloudflare/response_count': 1108,
'atp/cdn/cloudflare/response_status_count/200': 1108,
'atp/field/email/missing': 182,
'atp/field/operator/missing': 182,
'atp/field/operator_wikidata/missing': 182,
'atp/field/twitter/missing': 182,
'atp/nsi/perfect_match': 182,
'downloader/request_bytes': 423013,
'downloader/request_count': 1109,
'downloader/request_method_count/GET': 1109,
'downloader/response_bytes': 18658932,
'downloader/response_count': 1109,
'downloader/response_status_count/200': 1109, …
```
> [Aerie] Add spider

- locations/spiders/bank_of_cyprus_cp.py
Stats:
```python
{'atp/brand/Bank of Cyprus': 111,
'atp/brand_wikidata/Q806678': 111,
'atp/category/amenity/atm': 12,
'atp/category/amenity/bank': 99,
'atp/field/country/from_spider_name': 111,
'atp/field/email/missing': 111,
'atp/field/image/missing': 111,
'atp/field/name/missing': 12,
'atp/field/opening_hours/missing': 111,
'atp/field/operator/missing': 99,
'atp/field/operator_wikidata/missing': 99,
'atp/field/phone/missing': 111,
'atp/field/postcode/missing': 111,
'atp/field/state/missing': 111,
'atp/field/twitter/missing': 111,
'atp/field/website/missing': 111,
'atp/nsi/category_match': 111,
'atp/operator/Bank of Cyprus': 12,
'atp/operator_wikidata/Q806678': 12,
'downloader/request_bytes': 5650,
'downloader/request_count': 7,
'downloader/request_method_count/GET': 7, …
```
> [bankofcyprus_cy] add spider (111 locations)

- locations/spiders/kfc_nl.py
Individual urls per POI seems available (e.g. https://www.kfc.nl/locaties/sontplein-3/?id=625), but they don't work when I try to open them in a new tab.
Stats:
```json
{
"atp/brand/KFC": 90,
"atp/brand_wikidata/Q524757": 90,
"atp/category/amenity/fast_food": 90,
"atp/field/country/from_spider_name": 90,
"atp/field/email/missing": 90,
"atp/field/image/missing": 90,
"atp/field/operator/missing": 90,
"atp/field/operator_wikidata/missing": 90,
"atp/field/phone/missing": 90,
"atp/field/state/missing": 90,
"atp/field/twitter/missing": 90,
"atp/field/website/missing": 90,
"atp/nsi/cc_match": 90,
"downloader/request_bytes": 783,
"downloader/request_method_count/POST": 1,
"downloader/response_bytes": 9525, …
```
> [kfc_nl] add spider (90 locations)

- locations/spiders/seven_eleven_ph.py
The spider is geo-based, but amount of requests is acceptable I hope.
Stats:
```json
{
"atp/brand/7-Eleven": 3344,
"atp/brand_wikidata/Q259340": 3344,
"atp/category/missing": 3344,
"atp/closed_poi": 118,
"atp/field/city/missing": 424,
"atp/field/country/from_spider_name": 3344,
"atp/field/email/missing": 3344,
"atp/field/image/missing": 3344,
"atp/field/name/missing": 3344,
"atp/field/operator/missing": 3344,
"atp/field/operator_wikidata/missing": 3344,
"atp/field/phone/invalid": 1237,
"atp/field/phone/missing": 2048,
"atp/field/postcode/missing": 3344,
"atp/field/street_address/missing": 3344,
"atp/field/twitter/missing": 3344,
"atp/field/website/missing": 3344,
"atp/nsi/match_failed": 3344,
"downloader/request_bytes": 197037,
"downloader/request_count": 461, …
```
> [seven_eleven_ph] add spider (3k locations)

- locations/spiders/poundbakery_gb.py
```python
{'atp/brand/Poundbakery': 82,
'atp/brand_wikidata/Q21061591': 82,
'atp/category/shop/bakery': 82,
'atp/field/city/missing': 82,
'atp/field/country/from_spider_name': 82,
'atp/field/email/missing': 82,
'atp/field/image/dropped': 14,
'atp/field/opening_hours/missing': 82,
'atp/field/operator/missing': 82,
'atp/field/operator_wikidata/missing': 82,
'atp/field/street_address/missing': 82,
'atp/field/twitter/missing': 82,
'atp/nsi/perfect_match': 82,
'downloader/request_bytes': 31879,
'downloader/request_count': 86,
'downloader/request_method_count/GET': 86,
'downloader/response_bytes': 703001,
'downloader/response_count': 86, …
```
> [Poundbakery GB] Add spider

- locations/spiders/western_union.py
b90e2c1ad54c1f5496a63ba25fa07d89095b7557 changed the point_locations function to return floats for lat and lon, rather than strings. The Western Union spider needs to send lat and lon as JSON strings, not JSON floats.
> western_union: fix spider

- locations/spiders/aaa.py
b90e2c1ad54c1f5496a63ba25fa07d89095b7557 changed the point_locations function to return floats for lat and lon, rather than strings. The AAA spider needs to concatenate the two floats into a single string sent in a request to the server.
> aaa: fix spider

- locations/spiders/tjx.py
b90e2c1ad54c1f5496a63ba25fa07d89095b7557 changed the point_locations function to return floats for lat and lon, rather than strings. The TJX spider needs to send lat and lon as strings not integers in FormRequest.
> tjx: fix spider

- locations/spiders/la_anonima_ar.py
At some point in the future, we may need to discus refs. For us `ref`, it's a unique id per spider, that then gets turned into a `id` which is unique across ATP. However not all refs are equal, some like this are seen by the users, they are essentially advertised. (I think CVS is an example in the US). Some of our refs are slugs or urls or even uuids from the source, they aren't advertised, they shouldn't make it into OSMs `ref`, however there are examples of it happening. And they shouldn't be shown to end users.
Right now, I wouldn't advise anyone who shows ATP data to end users to show any of our `ref`s, however I could see a world where someone wants to show some refs (CVS, or this).
I've used `ref:branch` here, but only because I didn't want to needlessly break the `id` as it's …
> [LaAnonima AR] Fix name

- locations/spiders/ingo_dk.py
```python
{'atp/brand/Ingo': 196,
'atp/brand_wikidata/Q17048617': 196,
'atp/category/amenity/fuel': 196,
'atp/field/email/missing': 196,
'atp/field/image/missing': 196,
'atp/field/opening_hours/missing': 192,
'atp/field/operator/missing': 196,
'atp/field/operator_wikidata/missing': 196,
'atp/field/state/missing': 196,
'atp/field/twitter/missing': 196,
'atp/nsi/category_match': 196,
'downloader/request_bytes': 73235,
'downloader/request_count': 198,
'downloader/request_method_count/GET': 198,
'downloader/response_bytes': 1652707,
'downloader/response_count': 198,
'downloader/response_status_count/200': 198,
'elapsed_time_seconds': 1.418007,
'finish_time': datetime.datetime(2024, 4, 7, 11, 10, 5, 8963, tzinfo=datetime.timezone.utc),
'httpcache/hit': 198, …
```
> [Ingo DK] Add spider

- locations/spiders/oreilly_auto.py
The spider was also parsing the [Spanish](https://locations.oreillyauto.com/ak/juneau/autopartes-3826.html) page, and services pages such as [Battery Testing](https://locations.oreillyauto.com/ak/juneau/battery-testing-3826.html) and [Windshield Wiper Blade Installation](https://locations.oreillyauto.com/ak/juneau/wiper-installation-3826.html)
```python
{"atp/brand/O'Reilly Auto Parts": 6141,
'atp/brand_wikidata/Q7071951': 6141,
'atp/category/shop/car_parts': 6141,
'atp/field/email/missing': 6141,
'atp/field/image/dropped': 6141,
'atp/field/image/missing': 6141,
'atp/field/operator/missing': 6141,
'atp/field/operator_wikidata/missing': 6141,
'atp/field/twitter/missing': 6141,
'atp/nsi/perfect_match': 6141, …
```
> [Oreilly US] Drop duplicates

- locations/spiders/autozone_us.py
Store IDs and unique store names are no longer provided on store information pages.
> autozone_us: fix spider

- locations/geo.py
1e14402677f05b46b3d19f89cc3c83cc9a974442 introduced a typo in a modified error message string.
> locations/geo: fix typo in error message

- locations/spiders/hilton.py
It failed in several weekly runs due to `403` responses.
> [hilton] enable proxy

- locations/spiders/kfc_de.py
```python
{'atp/brand/KFC': 206,
'atp/brand_wikidata/Q524757': 206,
'atp/category/amenity/fast_food': 206,
'atp/field/country/from_spider_name': 206,
'atp/field/email/missing': 206,
'atp/field/image/missing': 206,
'atp/field/operator/missing': 206,
'atp/field/operator_wikidata/missing': 206,
'atp/field/phone/missing': 206,
'atp/field/state/missing': 206,
'atp/field/twitter/missing': 206,
'atp/nsi/cc_match': 206,
'downloader/request_bytes': 274,
'downloader/response_bytes': 40967,
'elapsed_time_seconds': 0.562306, …
```
> [KFC DE] Fix spider

- locations/spiders/carlsjr_fr.py
```python
{"atp/brand/Carl's Jr.": 7,
'atp/brand_wikidata/Q1043486': 7,
'atp/category/amenity/fast_food': 7,
'atp/field/country/from_spider_name': 7,
'atp/field/operator/missing': 7,
'atp/field/operator_wikidata/missing': 7,
'atp/field/street_address/missing': 7,
'atp/field/twitter/missing': 7,
'atp/nsi/perfect_match': 7,
'downloader/request_bytes': 3419,
'downloader/request_count': 9,
'downloader/request_method_count/GET': 9,
'downloader/response_bytes': 139492,
'downloader/response_count': 9,
'downloader/response_status_count/200': 9, …
```
> [carlsjr_fr] Added carls jr for france (7 items)

- locations/spiders/peugeot_nl_fr.py
```python
{'atp/brand/Peugeot': 2266,
'atp/brand_wikidata/Q6742': 2266,
'atp/category/shop/car': 2266,
'atp/field/country/from_reverse_geocoding': 123,
'atp/field/country/from_website_url': 2143,
'atp/field/image/missing': 2266,
'atp/field/opening_hours/missing': 2266,
'atp/field/operator/missing': 2266,
'atp/field/operator_wikidata/missing': 2266,
'atp/field/state/missing': 764,
'atp/field/street_address/missing': 2266,
'atp/field/twitter/missing': 2266,
'atp/field/website/missing': 121,
'atp/nsi/cc_match': 2266,
'downloader/request_bytes': 1517,
'downloader/response_bytes': 325028, …
```
> [peugeot_nl_fr] Create peugeot spider for NL and FR (2266 items)

- locations/spiders/amc_theatres_us.py
```python
{'atp/brand/AMC': 555,
'atp/brand_wikidata/Q294721': 555,
'atp/category/amenity/cinema': 557,
'atp/field/brand/missing': 2,
'atp/field/brand_wikidata/missing': 2,
'atp/field/country/from_spider_name': 557,
'atp/field/email/missing': 557,
'atp/field/image/missing': 557,
'atp/field/opening_hours/missing': 557,
'atp/field/operator/missing': 557,
'atp/field/operator_wikidata/missing': 557,
'atp/field/phone/missing': 557,
'atp/field/twitter/missing': 557,
'atp/nsi/perfect_match': 555,
'downloader/request_bytes': 639,
'downloader/response_bytes': 465396,
'elapsed_time_seconds': 5.812337, …
```
> [AMC US] Fix spider

- locations/spiders/champs_sports_us.py
A US sports shop brand:
'atp/brand/Champs Sports': 410,
'atp/brand_wikidata/Q2955924': 410,
'atp/category/shop/sports': 410,
'atp/field/country/from_spider_name': 410,
'atp/field/email/missing': 410,
'atp/field/image/dropped': 410,
'atp/field/image/missing': 410,
'atp/field/operator/missing': 410,
'atp/field/operator_wikidata/missing': 410,
'atp/field/twitter/missing': 410,
'atp/nsi/perfect_match': 410
> [champs_sports_us] add spider (410 locations)

- locations/spiders/nespresso.py
```python
{'atp/brand/Nespresso': 480,
'atp/brand_wikidata/Q301301': 480,
'atp/category/shop/coffee': 480,
'atp/field/email/missing': 480,
'atp/field/image/missing': 480,
'atp/field/opening_hours/missing': 480,
'atp/field/operator/missing': 480,
'atp/field/operator_wikidata/missing': 480,
'atp/field/phone/missing': 286,
'atp/field/state/from_reverse_geocoding': 74,
'atp/field/state/missing': 406,
'atp/field/twitter/missing': 480,
'atp/field/website/missing': 480,
'atp/nsi/perfect_match': 480,
'downloader/request_bytes': 5192,
'downloader/request_count': 12,
'downloader/request_method_count/GET': 12,
'downloader/response_bytes': 73012, …
```
> [nespresso] Added Austria and Denmark to countries list (480 items)

- locations/spiders/nespresso.py
```python
{'atp/brand/Nespresso': 487,
'atp/brand_wikidata/Q301301': 487,
'atp/category/shop/coffee': 487,
'atp/field/email/missing': 487,
'atp/field/image/missing': 487,
'atp/field/opening_hours/missing': 487,
'atp/field/operator/missing': 487,
'atp/field/operator_wikidata/missing': 487,
'atp/field/phone/missing': 293,
'atp/field/state/from_reverse_geocoding': 74,
'atp/field/state/missing': 413,
'atp/field/twitter/missing': 487,
'atp/field/website/missing': 487,
'atp/nsi/perfect_match': 487,
'downloader/request_bytes': 5648,
'downloader/request_count': 13,
'downloader/request_method_count/GET': 13,
'downloader/response_bytes': 75925, …
```
> [nespresso] Added hungary to nespresso spider (487 items)

- locations/spiders/suzuki_fr.py
```python
{'atp/brand/Suzuki': 219,
'atp/brand_wikidata/Q181642': 219,
'atp/category/missing': 219,
'atp/field/city/missing': 219,
'atp/field/country/from_spider_name': 219,
'atp/field/email/missing': 219,
'atp/field/image/missing': 219,
'atp/field/lat/missing': 219,
'atp/field/lon/missing': 219,
'atp/field/opening_hours/missing': 219,
'atp/field/operator/missing': 219,
'atp/field/operator_wikidata/missing': 219,
'atp/field/postcode/missing': 219,
'atp/field/state/missing': 219,
'atp/field/twitter/missing': 219,
'atp/nsi/match_failed': 219,
'downloader/request_bytes': 84665,
'downloader/request_count': 221,
'downloader/request_method_count/GET': 221,
'downloader/response_bytes': 72108108,
'downloader/response_count': 221, …
```
> [suzuki_fr] Create Spider for Suzuki France (219 items)

- locations/spiders/kia_at_fr_de.py
```python
{'atp/brand/Kia': 857,
'atp/brand_wikidata/Q35349': 857,
'atp/category/shop/car': 857,
'atp/field/country/from_reverse_geocoding': 348,
'atp/field/country/from_website_url': 509,
'atp/field/email/invalid': 17,
'atp/field/email/missing': 233,
'atp/field/image/missing': 857,
'atp/field/opening_hours/missing': 857,
'atp/field/operator/missing': 857,
'atp/field/operator_wikidata/missing': 857,
'atp/field/phone/invalid': 47,
'atp/field/state/missing': 509,
'atp/field/twitter/missing': 857,
'atp/field/website/invalid': 7,
'atp/nsi/perfect_match': 857,
'downloader/request_bytes': 1343,
'downloader/response_bytes': 245169, …
```
> [kia_at_fr_de] Created spider for kia in AT, FR, DE (857 items)

- locations/spiders/bp.py
```python
{'atp/brand/BP': 17846,
'atp/brand/BP Connect': 38,
'atp/brand_wikidata/Q152057': 17884,
'atp/category/amenity/fuel': 17846,
'atp/category/shop/convenience': 38,
'atp/closed_check': 5,
'atp/field/email/missing': 17884,
'atp/field/image/missing': 17884,
'atp/field/opening_hours/missing': 989,
'atp/field/operator/missing': 17615,
'atp/field/operator_wikidata/missing': 17615,
'atp/field/phone/invalid': 212,
'atp/field/phone/missing': 530,
'atp/field/postcode/missing': 269,
'atp/field/state/missing': 8115,
'atp/field/twitter/missing': 17884,
'atp/field/website/missing': 15551,
'atp/nsi/cc_match': 17847,
'atp/nsi/match_failed': 37,
'atp/operator/BP': 269,
'atp/operator_wikidata/Q152057': 269, …
```
> [bp] Add more tags for bp (17884 items)

- locations/spiders/bucees_us.py
3818d225b6ac75d0b551ebe9e85146e45a96aa83 introduced a new attribute to parse_opening_hours() of WPStoreLocatorSpider. BuceesUSSpider thus needs to accomodate this new attribute when overriding parse_opening_hours()
> bucees_us: fix spider

- locations/spiders/bar_burrito_ca.py
3818d225b6ac75d0b551ebe9e85146e45a96aa83 introduced a new attribute to parse_opening_hours() of WPStoreLocatorSpider. BarBurritoCASpider thus needs to accomodate this new attribute when overriding parse_opening_hours()
This change also implements parse_opening_hours(), as this overridden function was previously just a placeholder.
> bar_burrito_ca: fix spider and parse opening hours

- locations/spiders/allianz_de.py
- locations/spiders/applebees.py
- locations/spiders/asics_us.py
- locations/spiders/bp_pulse_gb.py
- locations/spiders/cic.py
- locations/spiders/citizens_us.py
- locations/spiders/claires.py
- locations/spiders/croix_rouge_francaise_fr.py
- locations/spiders/dairy_queen_us.py
- locations/spiders/dominos_pizza_in.py
- locations/spiders/dominos_pizza_jp.py
- locations/spiders/dominos_pizza_mx.py
- locations/spiders/enterprise.py
- locations/spiders/familymart_tw.py
- locations/spiders/ford_dealers_us.py
- locations/spiders/kfc_jp.py
- locations/spiders/marriott_hotels.py
- locations/spiders/mcdonalds_jp.py
- locations/spiders/millennium_bank_pl.py
- locations/spiders/paczkomat_inpost_pl.py
- locations/spiders/papa_johns.py
- locations/spiders/penny_de.py
- locations/spiders/penske.py
- locations/spiders/pnc.py
- locations/spiders/ross_dress_for_less_us.py
- locations/spiders/skoda.py
- locations/spiders/the_courier_guy.py
- locations/spiders/ubitricity.py
- locations/spiders/us_bank.py
- locations/spiders/vlh_de.py
These are the bigger spiders where our brand string is different to NSI. Some of ours looks like Wikidata/old NSI ones eg Allianz SE. I've removed some as well, as long as we match NSI we'll still get them in the output, eg Applebees, where I think NSI should change, Penny VS PENNY which seem controversial in NSI so may change again in the future and FamilyMart which NSI has in Japanese.
> Sync brand strings with NSI

- locations/spiders/super_bio_markt_de.py
- locations/storefinders/agile_store_locator.py
Fix https://github.com/alltheplaces/alltheplaces/issues/8114
2024-04-24 08:29:16 [scrapy.statscollectors] INFO: Dumping Scrapy stats:
{'atp/brand/SuperBioMarkt': 26,
'atp/brand_wikidata/Q2367009': 26,
'atp/category/shop/supermarket': 26,
'atp/field/country/from_spider_name': 26,
'atp/nsi/perfect_match': 26,
'downloader/request_bytes': 684,
'downloader/response_bytes': 3597, …
> Add SuperBioMarkt (DE) and fix issue with empty hours

- locations/spiders/seat.py
```python
{'atp/brand/SEAT': 1953,
'atp/brand_wikidata/Q188217': 1953,
'atp/category/shop/car': 1953,
'atp/closed_check': 4,
'atp/field/email/invalid': 23,
'atp/field/email/missing': 228,
'atp/field/image/missing': 1953,
'atp/field/opening_hours/missing': 1953,
'atp/field/operator/missing': 1953,
'atp/field/operator_wikidata/missing': 1953,
'atp/field/phone/invalid': 72,
'atp/field/state/missing': 1953,
'atp/field/twitter/missing': 1953,
'atp/field/website/invalid': 856,
'atp/field/website/missing': 617,
'atp/nsi/perfect_match': 1953,
'downloader/request_bytes': 8548,
'downloader/request_count': 20,
'downloader/request_method_count/GET': 20,
'downloader/response_bytes': 5016034,
'downloader/response_count': 20, …
```
> [seat] Added PL to seat spider (1953 items)

- locations/spiders/taco_bell_nl.py
```python
{'atp/brand/Taco Bell': 10,
'atp/brand_wikidata/Q752941': 10,
'atp/category/amenity/fast_food': 10,
'atp/field/city/missing': 10,
'downloader/request_bytes': 632,
'downloader/response_bytes': 36181, …
```
> [taco_bell_nl] Added taco bell to NL (10 items)

- locations/spiders/kia.py
```python
{'atp/brand/Kia': 1208,
'atp/brand_wikidata/Q35349': 1208,
'atp/category/shop/car': 1208,
'atp/field/country/from_reverse_geocoding': 699,
'atp/field/country/from_website_url': 509,
'atp/field/email/invalid': 23,
'atp/field/email/missing': 236,
'atp/field/image/missing': 1208,
'atp/field/opening_hours/missing': 1208,
'atp/field/operator/missing': 1208,
'atp/field/operator_wikidata/missing': 1208,
'atp/field/phone/invalid': 49,
'atp/field/state/missing': 509,
'atp/field/twitter/missing': 1208,
'atp/field/website/invalid': 30,
'atp/field/website/missing': 108,
'atp/nsi/perfect_match': 1208,
'downloader/request_bytes': 2037, …
```
> [kia] Added ES and NL to Kia (1208 items)

- locations/spiders/toyota_eu.py
```python
{'atp/brand/Toyota': 2381,
'atp/brand_wikidata/Q53268': 2381,
'atp/category/shop/car': 2381,
'atp/field/email/missing': 62,
'atp/field/image/missing': 2381,
'atp/field/lat/missing': 27,
'atp/field/lon/missing': 27,
'atp/field/opening_hours/missing': 2381,
'atp/field/operator/missing': 2381,
'atp/field/operator_wikidata/missing': 2381,
'atp/field/phone/invalid': 30,
'atp/field/phone/missing': 44,
'atp/field/state/missing': 461,
'atp/field/twitter/missing': 2381,
'atp/field/website/invalid': 13,
'atp/field/website/missing': 575,
'atp/geometry/null_island': 27,
'atp/nsi/cc_match': 2381,
'downloader/request_bytes': 11546,
'downloader/request_count': 30,
'downloader/request_method_count/GET': 30, …
```
> [toyota_eu] Fixed toyota eu and added CZ (2381 items)

- locations/spiders/peugeot_se_cz_es.py
```python
{'atp/brand/Peugeot': 500,
'atp/brand_wikidata/Q6742': 500,
'atp/category/missing': 419,
'atp/category/shop/car': 63,
'atp/category/shop/car_repair': 18,
'atp/field/country/from_reverse_geocoding': 2,
'atp/field/country/from_website_url': 498,
'atp/field/email/missing': 128,
'atp/field/image/missing': 500,
'atp/field/opening_hours/missing': 500,
'atp/field/operator/missing': 500,
'atp/field/operator_wikidata/missing': 500,
'atp/field/street_address/missing': 500,
'atp/field/twitter/missing': 500,
'atp/nsi/cc_match': 81,
'atp/nsi/match_failed': 419,
'downloader/request_bytes': 2369, …
```
> [peugeot_se_cz_es] Added Peugeot CZ, ES to Peugeot SE (500 items)

- locations/spiders/hyundai_se_dk.py
```python
{'atp/brand/Hyundai': 105,
'atp/brand_wikidata/Q55931': 105,
'atp/category/shop/car': 105,
'atp/cdn/cloudflare/response_status_count/200': 4,
'atp/field/country/from_reverse_geocoding': 105,
'atp/field/email/missing': 104,
'atp/field/operator/missing': 105,
'atp/field/operator_wikidata/missing': 105,
'atp/field/twitter/missing': 105,
'atp/field/website/missing': 105,
'atp/nsi/cc_match': 105,
'downloader/request_bytes': 1296,
'downloader/response_bytes': 18853,
'downloader/response_status_count/200': 4,
'elapsed_time_seconds': 2.277063, …
```
> [hyundai_se_dk] Added Germany to Hyundai SE spider (105 items)

- locations/spiders/fiat_dk.py
```python
{'atp/brand/Fiat': 35,
'atp/brand_wikidata/Q27597': 35,
'atp/category/missing': 35,
'atp/field/opening_hours/missing': 35,
'atp/field/street_address/missing': 35,
'atp/nsi/match_failed': 35,
'downloader/request_bytes': 699,
'downloader/response_bytes': 4564,
'elapsed_time_seconds': 2.906065,
'finish_time': datetime.datetime(2024, 4, 25, …
```
> [fiat_dk] Added fiat dealerships in Denmark (35 items)

- locations/spiders/carlsjr_es.py
```python
{"atp/brand/Carl's Jr.": 44,
'atp/brand_wikidata/Q1043486': 44,
'atp/category/amenity/fast_food': 44,
'atp/field/city/missing': 44,
'atp/field/country/from_spider_name': 44,
'atp/field/email/missing': 44,
'atp/field/image/missing': 44,
'atp/field/lat/missing': 44,
'atp/field/lon/missing': 44,
'atp/field/opening_hours/missing': 44,
'atp/field/operator/missing': 44,
'atp/field/operator_wikidata/missing': 44,
'atp/field/phone/missing': 44,
'atp/field/postcode/missing': 44,
'atp/field/state/missing': 44,
'atp/field/street_address/missing': 44,
'atp/nsi/perfect_match': 44,
'downloader/request_bytes': 17118,
'downloader/request_count': 46,
'downloader/request_method_count/GET': 46,
'downloader/response_bytes': 1392374, …
```
> [carlsjr_es] Added Carls Jr in Spain (44 items)

- locations/spiders/carlsjr_nz.py
```python
{"atp/brand/Carl's Jr.": 17,
'atp/brand_wikidata/Q1043486': 17,
'atp/category/amenity/fast_food': 17,
'atp/field/country/from_spider_name': 17,
'atp/nsi/perfect_match': 17,
'downloader/response_bytes': 26883, …
```
> [carlsjr_nz] Added Carls Jr in New Zealand (17 items)

- locations/spiders/ihg_hotels.py
```python
{'atp/brand/Army Hotels': 71,
'atp/brand/Avid Hotels': 51,
'atp/brand/Candlewood Suites': 356,
'atp/brand/Crowne Plaza': 371,
'atp/brand/Even Hotels': 22,
'atp/brand/Holiday Inn': 1074,
'atp/brand/Holiday Inn Express': 2950,
'atp/brand/Hotel Indigo': 128,
'atp/brand/InterContinental': 213,
'atp/brand/Kimpton': 62,
'atp/brand/Staybridge Suites': 307,
'atp/brand/Voco Hotels': 6,
'atp/brand_wikidata/Q16994722': 71,
'atp/brand_wikidata/Q1825730': 213,
'atp/brand_wikidata/Q2717882': 1074,
'atp/brand_wikidata/Q2746220': 371,
'atp/brand_wikidata/Q5032010': 356,
'atp/brand_wikidata/Q5416522': 22,
'atp/brand_wikidata/Q5880423': 2950,
'atp/brand_wikidata/Q5911596': 128,
'atp/brand_wikidata/Q60749907': 51,
'atp/brand_wikidata/Q60750454': 6, …
```
> [ihg_hotels] Fixed IHG Hotels spider (5687 items)

- locations/spiders/carlsjr_ca.py
```python
{"atp/brand/Carl's Jr.": 19,
'atp/brand_wikidata/Q1043486': 19,
'atp/category/amenity/fast_food': 19,
'atp/field/lat/missing': 19,
'atp/field/lon/missing': 19,
'atp/field/postcode/missing': 19,
'atp/nsi/perfect_match': 19,
'downloader/exception_count': 2,
'downloader/exception_type_count/twisted.internet.error.TimeoutError': 2,
'downloader/request_bytes': 1218, …
```
> [carlsjr_ca] Added Carls Jr to Canada (19 items)

- locations/spiders/van_dal_nl.py
Rel: https://github.com/osmlab/name-suggestion-index/commit/ccb95b2680c164479af5c8310dfd0823382848cd
```python
{'atp/brand/Van Dal': 39,
'atp/brand_wikidata/Q125580449': 39,
'atp/category/missing': 39,
'atp/cdn/cloudflare/response_count': 43,
'atp/cdn/cloudflare/response_status_count/200': 43,
'atp/field/country/from_website_url': 39,
'atp/field/email/missing': 39,
'atp/field/image/missing': 39,
'atp/field/name/missing': 39,
'atp/field/opening_hours/missing': 39,
'atp/field/operator/missing': 39,
'atp/field/operator_wikidata/missing': 39,
'atp/field/state/missing': 39,
'atp/field/twitter/missing': 39,
'atp/nsi/brand_missing': 39,
'downloader/request_bytes': 20816,
'downloader/request_count': 43,
'downloader/request_method_count/GET': 43,
'downloader/response_bytes': 1103526, …
```
> [Van Dal NL] Add spider

- locations/spiders/anicura.py
Rel: https://github.com/osmlab/name-suggestion-index/commit/79c982bc10d93d60c3ede5e49ed7cdcc23e4efb7
```python
{'atp/brand/AniCura': 436,
'atp/brand_wikidata/Q21100245': 436,
'atp/category/missing': 436,
'atp/cdn/cloudflare/response_count': 501,
'atp/cdn/cloudflare/response_status_count/200': 500,
'atp/field/country/from_website_url': 255,
'atp/field/image/missing': 436,
'atp/field/lat/missing': 11,
'atp/field/lon/missing': 11,
'atp/field/name/missing': 436,
'atp/field/opening_hours/missing': 436,
'atp/field/operator/missing': 436,
'atp/field/operator_wikidata/missing': 436,
'atp/field/phone/invalid': 16, …
```
> [AniCura] Add spider

- locations/spiders/tasmanian_government_free_wifi_au.py
Reference/source data: https://freewifi.tas.gov.au/
> Add Tasmanian Government Free WiFi (AU) (121 hotspots)

- locations/spiders/city_of_darwin_cctv.py
This is all fixed (non PTZ) cameras. The coordinates correspond to poles where PTZ cameras also appear to be mounted, even though a feature is not able to be extracted for each PTZ camera.
Compare with `CameraCount` field of
https://www.arcgis.com/apps/mapviewer/index.html?url=https://services6.arcgis.com/tVfesLETUHNU9Vna/ArcGIS/rest/services/CCTV_Cameras/FeatureServer&source=sd to see where PTZ cameras are likely to exist.
One *could* extract PTZ camera locations but it would require somewhat complex queries of the `CameraCount` field in the `CCTV_Cameras` layer versus counting camera points from the `CCTV_Points` layer nearby to each point in the `CCTV_Cameras` layer, showing differences generally of 1 PTZ camera here and there.
> Add City of Darwin CCTV (106 cameras)

- locations/spiders/grilld_au.py
Some newer stores don't have a specified slug/website yet, so we have to treat this field as optional.
> grilld_au: fix spider

- locations/spiders/forty_winks_au.py
Sometimes, day names are missing in provided opening hours data. If there is only one missing day name, we can deduce what it is by process of elimination (can't be any of the other 6 day names which are specified).
> forty_winks_au: fix spider

- locations/spiders/zoloto_585_ru.py
```python
{'atp/brand_wikidata/Q125730875': 211,
'atp/category/missing': 211,
'atp/field/brand/missing': 211,
'atp/field/city/missing': 211,
'atp/field/country/from_spider_name': 211,
'atp/field/email/missing': 211,
'atp/field/image/invalid': 5,
'atp/field/name/missing': 211,
'atp/field/opening_hours/missing': 211,
'atp/field/operator/missing': 211,
'atp/field/operator_wikidata/missing': 211,
'atp/field/phone/missing': 211,
'atp/field/postcode/missing': 211,
'atp/field/state/missing': 211,
'atp/field/twitter/missing': 211,
'atp/nsi/brand_missing': 211,
'downloader/request_bytes': 170739,
'downloader/request_count': 240,
'downloader/request_method_count/GET': 240,
'downloader/response_bytes': 10010035,
'downloader/response_count': 240,
'downloader/response_status_count/200': 214, …
```
> [585 Gold RU] Add spider

- locations/spiders/crunch_fitness.py
- locations/spiders/the_cheesecake_shop.py
- locations/storefinders/storerocket.py
5 spiders were outputting `instagram` not `contact:instagram`. https://taginfo.openstreetmap.org/search?q=instagram#keys
> Unify instagram tagging

- locations/spiders/united_rentals.py
Stats:
```py
{'atp/brand/United Rentals': 1472,
'atp/brand_wikidata/Q7889101': 1472,
'atp/category/shop/plant_hire': 1472,
'atp/field/country/from_reverse_geocoding': 1472,
'atp/field/email/missing': 1472,
'atp/field/image/missing': 1472,
'atp/field/opening_hours/missing': 1472,
'atp/field/operator/missing': 1472,
'atp/field/operator_wikidata/missing': 1472,
'atp/field/phone/invalid': 34,
'atp/field/twitter/missing': 1472,
'atp/nsi/perfect_match': 1472,
'downloader/request_bytes': 818,
'downloader/response_bytes': 105328, …
```
> United Rentals: Add spider (1472 locations)

- locations/pipelines/address_clean_up.py
Apparently `\s` includes `\n`, so when #8320 replaced them with ` `, and the tests started failing.
> [Core] Fix clean_address with new lines

- locations/spiders/pandaexpress.py
```python
{'atp/brand/Panda Express': 2138,
'atp/brand_wikidata/Q1358690': 2138,
'atp/category/amenity/fast_food': 2138,
'atp/cdn/cloudflare/response_count': 2156,
'atp/cdn/cloudflare/response_status_count/200': 2140,
'atp/cdn/cloudflare/response_status_count/403': 16,
'atp/field/email/missing': 2138,
'atp/field/image/dropped': 2138,
'atp/field/image/missing': 2138,
'atp/field/operator/missing': 2138,
'atp/field/operator_wikidata/missing': 2138,
'atp/field/phone/missing': 45,
'atp/nsi/perfect_match': 2138,
'downloader/request_bytes': 809758,
'downloader/request_count': 2434,
'downloader/request_method_count/GET': 2434,
'downloader/response_bytes': 68088563, …
```
> [pandaexpress] Added a user agent and delay for pandaexpress (2138 items)

- locations/spiders/puregym_gb.py
Fixes #8339
```python
{'atp/brand/PureGym': 399,
'atp/brand_wikidata/Q18345898': 399,
'atp/category/leisure/fitness_centre': 399,
'atp/cdn/cloudflare/response_count': 401,
'atp/cdn/cloudflare/response_status_count/200': 401,
'atp/field/image/missing': 399,
'atp/field/opening_hours/missing': 399,
'atp/field/operator/missing': 399,
'atp/field/operator_wikidata/missing': 399,
'atp/field/state/missing': 399,
'atp/nsi/perfect_match': 399,
'downloader/request_bytes': 172813,
'downloader/request_count': 401,
'downloader/request_method_count/GET': 401,
'downloader/response_bytes': 14408548,
'downloader/response_count': 401,
'downloader/response_status_count/200': 401,
'elapsed_time_seconds': 3.824414,
'finish_time': …
```
> [PureGym GB] Fix spider

- locations/hours.py
This has been causing some errors in unexpected places. Traditionally `from_linked_data` was safe, (but `add_range` was never safe).
> [Core] Make _parse_opening_hours_specification safer

- locations/spiders/hot_pot_buffet_th.py
```python
{'atp/brand/HOT POT Buffet': 60,
'atp/brand_wikidata/Q125919341': 60,
'atp/category/missing': 60,
'atp/field/country/from_spider_name': 60,
'atp/field/email/missing': 60,
'atp/field/opening_hours/missing': 60,
'atp/field/state/missing': 60,
'atp/field/website/missing': 60,
'atp/nsi/brand_missing': 60,
'downloader/request_bytes': 268,
'downloader/response_bytes': 13488, …
```
> [hot_pot_buffet_th] Added a spider for hot_pot_buffet_th (60 items)

- locations/spiders/wendys.py
Fixes #8373 
The default structured data parser was mixing standard store opening hours with breakfast hours (and sometimes drive-through hours). I added post-processing to be more explicit about these two sets of hours.
> Improve Wendy's hours parsing

- locations/spiders/risparmio_casa_it.py
Rel: https://github.com/osmlab/name-suggestion-index/pull/9495
```python
{'atp/brand/Risparmio Casa': 164,
'atp/brand_wikidata/Q125936928': 164,
'atp/category/missing': 164,
'atp/field/city/missing': 164,
'atp/field/country/from_spider_name': 164,
'atp/field/email/missing': 164,
'atp/field/image/missing': 164,
'atp/field/name/missing': 164,
'atp/field/opening_hours/missing': 164,
'atp/field/operator/missing': 164,
'atp/field/operator_wikidata/missing': 164,
'atp/field/phone/invalid': 18,
'atp/field/postcode/missing': 164,
'atp/field/state/missing': 164,
'atp/field/street_address/missing': 164,
'atp/field/twitter/missing': 164,
'atp/nsi/brand_missing': 164,
'downloader/request_bytes': 67119,
'downloader/request_count': 167, …
```
> [RisparmioCasa IT] Add spider

- locations/spiders/three_gb.py
Social tags are not location-specific hence we should ignore them.
> three_gb: ignore brand-wide social tags

- ci/buildspec.yml
Don't run the spiders when the commit that triggered a CI run came from the pre-commit bot.
> Don't run if the change is from pre-commit

- locations/spiders/starbucks.py
Output format of the API was changed, they got rid of `paging`.
I haven't run spider till completion but it worked for ~6k POIs.
```json
{
"atp/brand/Starbucks": 5855,
"atp/brand_wikidata/Q37158": 5855,
"atp/category/amenity/cafe": 5855,
"atp/field/email/missing": 5855,
"atp/field/image/missing": 5855,
"atp/field/opening_hours/missing": 66,
"atp/field/operator/missing": 5855,
"atp/field/operator_wikidata/missing": 5855,
"atp/field/phone/invalid": 3,
"atp/field/phone/missing": 61,
"atp/field/twitter/missing": 5855,
"atp/nsi/match_failed": 5855,
"downloader/request_bytes": 3005673,
"downloader/request_count": 5871,
"downloader/request_method_count/GET": 5871,
"downloader/response_bytes": 199111907,
"downloader/response_count": 5871,
"downloader/response_status_count/200": 5871, …
```
> [starbucks] fix spider, add hours

- locations/spiders/lasik_plus_us.py
Rel: https://github.com/osmlab/name-suggestion-index/issues/6211
```python
{'atp/brand/LasikPlus': 52,
'atp/brand_wikidata/Q126111242': 52,
'atp/category/amenity/clinic': 52,
'atp/category/multiple': 52,
'atp/cdn/cloudflare/response_count': 140,
'atp/cdn/cloudflare/response_status_count/200': 140,
'atp/field/email/missing': 52,
'atp/field/state/from_reverse_geocoding': 52,
'atp/nsi/perfect_match': 52,
'downloader/request_bytes': 55980,
'downloader/request_count': 140,
'downloader/request_method_count/GET': 140,
'downloader/response_bytes': 8905348,
'downloader/response_count': 140,
'downloader/response_status_count/200': 140,
'elapsed_time_seconds': 3.883534, …
```
> [LasikPlus US] Add spider

- locations/storefinders/yext_answers.py
While working on converting data to parquet, the conversion tool complained about inconsistent column types. The website is normally a string, but every once and a while a spider emits a dict instead. It looks like all/most of these cases are the Yext Answers spider pulling out the container dict instead of using a null.
In the case of a missing URL, the `websiteUrl` property looks like:
```json
{
"websiteUrl":{
"preferDisplayUrl":false
}
}
```
In the normal case:
```json
{
"websiteUrl":{
"url":"https://restaurantes.fiveguys.es/comunidad-de-madrid/paseo-de-la-castellana-259-e",
"displayUrl":"https://restaurantes.fiveguys.es/comunidad-de-madrid/paseo-de-la-castellana-259-e",
"preferDisplayUrl":false
}
}
```
This adjusts the Yext Answers API spider to handle this situation.
> Fix Yext Answers API website extraction

- locations/spiders/claires.py
- locations/storefinders/rio_seo.py
There is an issue with RioSEO hosted sitemaps and Canadian URLs, eg: https://stores.claires.com/ca/mb/brandon/2544.html is in the sitemap, but gets redirected to https://stores.claires.com/us/ca/ when it should be/go to https://stores.claires.com/mb/brandon/2544.html
I expect this issues is in other sitemap spiders on sites hosted by RioSEO.
> [Claires] Switch to RioSEO Spider

- locations/spiders/puma_tw.py
```python
{'atp/brand/Puma': 38,
'atp/brand_wikidata/Q157064': 38,
'atp/category/shop/clothes': 38,
'atp/field/lat/missing': 38,
'atp/field/lon/missing': 38,
'atp/field/website/missing': 38,
'atp/nsi/match_failed': 38,
'downloader/request_bytes': 18536,
'downloader/request_count': 46,
'downloader/request_method_count/GET': 46, …
```
> [puma_tw] Created puma taiwan spider (38 items)

- locations/spiders/chevrolet.py
```python
{'atp/brand/Chevrolet': 2876,
'atp/brand_wikidata/Q29570': 2876,
'atp/category/shop/car': 2876,
'atp/field/email/missing': 2876,
'atp/field/image/missing': 2876,
'atp/field/operator/missing': 2876,
'atp/field/operator_wikidata/missing': 2876,
'atp/field/state/from_reverse_geocoding': 13,
'atp/field/twitter/missing': 2876,
'atp/field/website/missing': 100,
'atp/nsi/cc_match': 2876,
'downloader/exception_count': 5,
'downloader/exception_type_count/twisted.internet.error.TimeoutError': 5,
'downloader/request_bytes': 3060939,
'downloader/request_count': 1575,
'downloader/request_method_count/GET': 1575, …
```
> [chevrolet] added canada to chevrolet spider (2876 items)

- locations/spiders/bricofer_it.py
- locations/storefinders/woosmap.py
```python
{'atp/brand/Bricofer': 100,
'atp/brand_wikidata/Q126012596': 100,
'atp/category/shop/doityourself': 100,
'atp/field/image/missing': 100,
'atp/field/operator/missing': 100,
'atp/field/operator_wikidata/missing': 100,
'atp/field/state/missing': 100,
'atp/field/twitter/missing': 100,
'atp/nsi/perfect_match': 100,
'downloader/request_bytes': 728,
'downloader/response_bytes': 13098, …
```
> [bricofer_it] Added bricofer_it (100 items)

- locations/spiders/foodlion_us.py
```python
{'atp/brand/Food Lion': 1172,
'atp/brand_wikidata/Q1435950': 1172,
'atp/category/shop/supermarket': 1172,
'atp/cdn/cloudflare/response_count': 1174,
'atp/cdn/cloudflare/response_status_count/200': 1174,
'atp/field/city/missing': 1172,
'atp/field/country/from_spider_name': 1172,
'atp/field/email/missing': 1172,
'atp/field/operator/missing': 1172,
'atp/field/operator_wikidata/missing': 1172,
'atp/nsi/perfect_match': 1172,
'downloader/request_bytes': 643784,
'downloader/request_count': 1174,
'downloader/request_method_count/GET': 1174,
'downloader/response_bytes': 31900011,
'downloader/response_count': 1174,
'downloader/response_status_count/200': 1174,
'elapsed_time_seconds': 1435.657082, …
```
> [foodlion_us] Simplified Foodlion (1172 items)

- locations/spiders/galeria_de.py
- locations/spiders/karstadt_de.py
- locations/spiders/wiener_feinbacker_heberer_de.py
All Karstadts are Galerias now, POIs on the website were rebranded:
- https://www.galeria.de/filialen
- https://en.wikipedia.org/wiki/Galeria_Karstadt_Kaufhof
- https://nsi.guide/index.html?t=brands&k=shop&v=department_store&tt=karstadt%20
> [karstadt -> galeria] change brand and rename the spider

- locations/spiders/gap_tw.py
```python
{'atp/brand/Gap': 15,
'atp/brand_wikidata/Q420822': 15,
'atp/category/missing': 15,
'atp/field/postcode/missing': 15,
'atp/field/street_address/missing': 15,
'atp/nsi/match_failed': 15,
'downloader/request_bytes': 763,
'downloader/response_bytes': 3431, …
```
> [gap_tw] Added Gap TW (15 items)

- locations/spiders/hsbc_tw.py
```python
{'atp/brand/HSBC': 26,
'atp/brand_wikidata/Q190464': 26,
'atp/category/amenity/bank': 26,
'atp/field/email/missing': 26,
'atp/field/image/dropped': 26,
'atp/field/phone/missing': 26,
'atp/field/state/missing': 26,
'atp/nsi/cc_match': 26,
'downloader/request_bytes': 33188,
'downloader/request_count': 54,
'downloader/request_method_count/GET': 54,
'downloader/response_bytes': 538535,
'downloader/response_count': 54,
'downloader/response_status_count/200': 28,
'downloader/response_status_count/301': 26,
'elapsed_time_seconds': 66.582598,
'finish_time': datetime.datetime(2024, 6, …
```
> [hsbc_tw] Added HSBC in Taiwan (26 items)

- locations/spiders/burger_king_tw.py
```python
{'atp/brand/Burger King': 95,
'atp/brand_wikidata/Q177054': 95,
'atp/category/amenity/fast_food': 95,
'atp/field/country/from_spider_name': 95,
'atp/field/email/missing': 95,
'atp/field/image/missing': 95,
'atp/field/operator_wikidata/missing': 95,
'atp/field/state/missing': 95,
'atp/field/street_address/missing': 95,
'atp/field/twitter/missing': 95,
'atp/nsi/cc_match': 95,
'atp/operator/家城股份有限公司': 95,
'downloader/request_bytes': 921,
'downloader/response_bytes': 30601,
'elapsed_time_seconds': 3.356421, …
```
> [burger_king_tw] Added Burger King in Taiwan (95 itmes)

- locations/spiders/sushi_express_tw.py
```python
{'atp/brand/Sushi Express': 281,
'atp/brand_wikidata/Q15920674': 281,
'atp/category/amenity/restaurant': 281,
'atp/field/country/from_spider_name': 281,
'atp/field/email/missing': 281,
'atp/field/image/missing': 281,
'atp/field/opening_hours/missing': 24,
'atp/field/operator/missing': 281,
'atp/field/operator_wikidata/missing': 281,
'atp/field/street_address/missing': 281,
'atp/field/twitter/missing': 281,
'atp/field/website/missing': 281,
'atp/nsi/cc_match': 281,
'downloader/request_bytes': 634,
'downloader/response_bytes': 252789, …
```
> [sushi_express_tw] Added Sushi Express (281 items)

- locations/spiders/krispy_kreme_mx.py
Might not have great attribution. But I did spot check some of the addresses and they are at them. Thus, I think it could still be useful even if it was just to use some reverse geocoding to get the latitude and longitude.
```python
{'atp/brand/Krispy Kreme': 250,
'atp/brand_wikidata/Q1192805': 250,
'atp/category/amenity/fast_food': 250,
'atp/field/city/missing': 250,
'atp/field/country/from_spider_name': 250,
'atp/field/email/missing': 250,
'atp/field/image/missing': 250,
'atp/field/lat/missing': 250,
'atp/field/lon/missing': 250,
'atp/field/opening_hours/missing': 250,
'atp/field/operator/missing': 250,
'atp/field/operator_wikidata/missing': 250,
'atp/field/phone/missing': 250,
'atp/field/postcode/missing': 250,
'atp/field/state/missing': 250, …
```
> [krispy_kreme_mx] Add krispy kreme mexico (250 items)

- locations/spiders/ziko_apteka_pl.py
yes, they are missing from published data
yes, website redirects there
> add trailing slashes on website tags for Ziko

- locations/hours.py
- locations/pipelines/check_item_properties.py
- tests/test_opening_hours.py
My comment in #8626: For the locations with explicitly closed hours, e.g. `<tr itemprop="openingHours" content="Mo Closed">` (etc.), I would much prefer to see the output contain `"opening_hours":"Mo-Su closed"`.
For the issue of KFC specifically, this isn't actually interesting, since all 373 items lacking opening hours do say Mo-Su closed in the microdata, but it's generally useful and would allow consumers to confidently filter out these items, such as for the MapRoulette case of creating missing POIs.
In the stats counters, we might also want to distinguish "opening_hours/missing" from "opening_hours/always_closed" or some such.
> Record days with closed hours

- locations/spiders/caffe_nero_gb.py
Caffe Nero seems to have changed its website slightly, and the URLs being returned by the spider are all broken. This fixes then.
> Correct URLs in Caffe Nero GB spider

- locations/spiders/rite_aid_us.py
```python
{'atp/brand/Rite Aid': 3212,
'atp/brand_wikidata/Q3433273': 3212,
'atp/category/amenity/pharmacy': 1606,
'atp/category/multiple': 1606,
'atp/category/shop/chemist': 1606,
'atp/cdn/cloudflare/response_count': 1606,
'atp/cdn/cloudflare/response_status_count/200': 1606,
'atp/field/email/missing': 3212,
'atp/field/image/missing': 3212,
'atp/field/opening_hours/missing': 34,
'atp/field/operator/missing': 3212,
'atp/field/operator_wikidata/missing': 3212,
'atp/field/twitter/missing': 3212,
'atp/nsi/cc_match': 3212,
'downloader/request_bytes': 648527,
'downloader/request_count': 1610,
'downloader/request_method_count/GET': 1610,
'downloader/response_bytes': 67199387,
'downloader/response_count': 1610,
'downloader/response_status_count/200': 1610,
'elapsed_time_seconds': 1965.771078, …
```
> [RiteAid US] Collect pharmacy opening hours

- locations/spiders/krispy_krunchy_chicken_us.py
```python
{'atp/brand/Krispy Krunchy Chicken': 2918,
'atp/brand_wikidata/Q65087447': 2918,
'atp/category/amenity/fast_food': 2918,
'atp/cdn/cloudflare/response_count': 2924,
'atp/cdn/cloudflare/response_status_count/200': 2924,
'atp/field/country/from_spider_name': 2806,
'atp/field/email/missing': 2918,
'atp/field/image/missing': 2918,
'atp/field/opening_hours/missing': 2918,
'atp/field/operator/missing': 2918,
'atp/field/operator_wikidata/missing': 2918,
'atp/field/phone/missing': 2918,
'atp/field/twitter/missing': 2918,
'atp/nsi/perfect_match': 2918,
'downloader/request_bytes': 1165758,
'downloader/request_count': 2924,
'downloader/request_method_count/GET': 2924, …
```
> [KrispyKrunchyChicken US] Add spider (2.9k locations)

- locations/spiders/box_now.py
I can't really debug this one. It runs fine from my GB ip, and my US vpn, however something is happening in the weekly.
```python
{'atp/brand/Box Now': 2771,
'atp/brand_wikidata/Q117195372': 580,
'atp/brand_wikidata/Q117195375': 613,
'atp/brand_wikidata/Q117195376': 1578,
'atp/category/amenity/parcel_locker': 2771,
'atp/field/city/missing': 2771,
'atp/field/email/missing': 2771,
'atp/field/image/missing': 2771,
'atp/field/opening_hours/missing': 2771,
'atp/field/operator/missing': 2771,
'atp/field/operator_wikidata/missing': 2771,
'atp/field/phone/missing': 2771,
'atp/field/postcode/missing': 2771,
'atp/field/state/missing': 2771,
'atp/field/street_address/missing': 2771,
'atp/field/twitter/missing': 2771,
'atp/field/website/missing': 2771,
'atp/nsi/perfect_match': 2771, …
```
> [Box Now] Requeire proxy

- locations/spiders/burger_king_fr.py
The old code was working fine for me locally, without a VPN. However it was having [issues](https://www.alltheplaces.xyz/spiders.html?search=burger_king_fr) in the weekly, with or without a VPN. I wanna try this API, the [store finder](https://burgerking.fr/restaurants) fetches both datasets, not totally sure why.
```python
{'atp/brand/Burger King': 532,
'atp/brand_wikidata/Q177054': 532,
'atp/category/amenity/fast_food': 532,
'atp/field/city/missing': 532,
'atp/field/country/from_spider_name': 532,
'atp/field/email/missing': 532,
'atp/field/image/missing': 532,
'atp/field/operator/missing': 532,
'atp/field/operator_wikidata/missing': 532,
'atp/field/postcode/missing': 532,
'atp/field/state/missing': 532, …
```
> [BurgerKing FR] Use new API

- locations/spiders/arbys_ca.py
- locations/spiders/arbys_us.py
CA:
```python
{"atp/brand/Arby's": 56,
'atp/brand_wikidata/Q630866': 56,
'atp/category/amenity/fast_food': 56,
'atp/field/country/from_spider_name': 56,
'atp/field/image/dropped': 56,
'atp/nsi/perfect_match': 56,
'downloader/request_bytes': 22124,
'downloader/request_count': 58,
'downloader/request_method_count/GET': 58,
'downloader/response_bytes': 684615,
'downloader/response_count': 58,
'downloader/response_status_count/200': 58,
'elapsed_time_seconds': 71.044544,
'finish_time': datetime.datetime(2024, 6, 21, 16, 20, 29, 853152, …
```
> [Arbys] Fix spider

- locations/spiders/bangkok_bank_th.py
```python
{'atp/brand/Bangkok Bank': 13,
'atp/brand/ธนาคารกรุงเทพ': 6742,
'atp/brand/盤谷銀行 Bangkok Bank': 1,
'atp/brand_wikidata/Q806483': 6756,
'atp/category/amenity/atm': 5928,
'atp/category/amenity/bank': 828,
'atp/field/city/missing': 6756,
'atp/field/email/missing': 6756,
'atp/field/image/missing': 6756,
'atp/field/lat/missing': 1995,
'atp/field/lon/missing': 1995,
'atp/field/name/missing': 5928,
'atp/field/opening_hours/missing': 6756,
'atp/field/operator/missing': 828,
'atp/field/operator_wikidata/missing': 828,
'atp/field/phone/invalid': 6692,
'atp/field/twitter/missing': 6756,
'atp/field/website/missing': 6756,
'atp/nsi/cc_match': 6756,
'atp/operator/ธนาคารกรุงเทพ': 5928,
'atp/operator_wikidata/Q806483': 5928,
'downloader/request_bytes': 227667, …
```
> [BangkokBank] Fix spider

- locations/hours.py
- locations/spiders/aldi_sud_au.py
- tests/test_opening_hours.py
I have the same worries about `closed` as I did about `off` in the `apply_yes_no` discussion. I don't think we should set negative attributes when we aren't certain. If we incorrectly say someone is closed on Sunday, or doesn't have a drive through it's a lot more drama than just leaving it null.
That being said, `apply_yes_no` has a safer way to handle this, I'm OK with opening hours having it too, when we are careful.
(Bad)
```python
item["extras"]["drive_through"] = "yes" if services.get("Drive Through") else "no"
```
If they changed `Drive Through` to `drive-through`, or anything, we'd be outputting `drive_through=no` on everything.
(Safe)
```python
apply_yes_no(Extras.DT, item, services.get("Drive Through") is True)
```
We'd be outputting nothing.
(Safe negative)
```python …
```
> [Hours] Add set_closed function

- locations/spiders/nhs_scotland_gb.py
regex was failing due to additional request parameters added.
Was in loop because of way link carousel has been redesigned.
Was running for 8+ hrs. Now 
{'atp/category/amenity/clinic': 66,
'atp/category/amenity/dentist': 1014,
'atp/category/amenity/doctors': 30,
'atp/category/amenity/hospital': 141,
'atp/category/amenity/pharmacy': 1140,
'atp/category/multiple': 2391,
'atp/category/shop/optician': 39,
'atp/field/brand/missing': 2430,
'atp/field/brand_wikidata/missing': 2430,
'atp/field/city/missing': 2430,
'atp/field/country/from_spider_name': 2430,
'atp/field/email/missing': 2430,
'atp/field/image/missing': 2430,
'atp/field/lat/missing': 1688,
'atp/field/lon/missing': 1688,
'atp/field/name/missing': 1678,
'atp/field/opening_hours/missing': 1696,
'atp/field/operator/missing': 2430, …
> [NHSScotlandGB] Fix long run time

- locations/spiders/leroy_merlin_pl.py
some locations are in Yemen/ocean near Oman, and as Poland has no colonies this is clearly broken. Address data present there confirms that coordinates are garbage (general area looks like switched lat-lons, but not tried confirming this theory)
I am not entirely sure how to best do it, other spiders are likely to be also affected (look at ATP global map, note supposed POIs in the middle of oceans). Maybe it should be separate pipeline, however these are defined?
It would be also possible for data consumers to do nothing and keep this claims as stated. And each data consumer skipping these data manually, I guess, but that seems overall vastly significant effort and keeping known trap for data users.
> drop clearly broken leroy_merlin_pl locations

- locations/spiders/seven_eleven_mx.py
There is a new API on a website where I haven't noticed any fuel stations.
```json
{
"atp/brand/7-Eleven": 1829,
"atp/brand_wikidata/Q259340": 1829,
"atp/category/shop/convenience": 1829,
"atp/field/city/missing": 1829,
"atp/field/country/from_spider_name": 1829,
"atp/field/email/missing": 1829,
"atp/field/image/missing": 1829,
"atp/field/opening_hours/missing": 1829,
"atp/field/operator/missing": 1829,
"atp/field/operator_wikidata/missing": 1829,
"atp/field/phone/missing": 1829,
"atp/field/postcode/missing": 1829,
"atp/field/state/missing": 1829,
"atp/field/street_address/missing": 1829,
"atp/field/twitter/missing": 1829,
"atp/field/website/missing": 1829,
"atp/nsi/cc_match": 1829,
"atp/seven_eleven_mx/skip": 503,
"downloader/request_bytes": 629, …
```
> [seven_eleven_mx] fix spider

- locations/spiders/skoda.py
Rel: https://github.com/osmlab/name-suggestion-index/pull/9643 - I've added a template to NSI, for every `shop=car` brand `shop=car_repair` NSI entry will be created. This will impact all `shop=car` spiders where category is not set explicitly.
> [skoda] add category, use DictParser

- locations/spiders/box_now.py
This runs fine from my residential GB ip, but `requires_proxy = True` will default to US, it's probably the wrong location for a EU spider.
```python
{'atp/brand/Box Now': 2780,
'atp/brand_wikidata/Q117195372': 564,
'atp/brand_wikidata/Q117195375': 618,
'atp/brand_wikidata/Q117195376': 1598,
'atp/category/amenity/parcel_locker': 2780,
'atp/field/city/missing': 2780,
'atp/field/email/missing': 2780,
'atp/field/image/missing': 2780,
'atp/field/opening_hours/missing': 2780,
'atp/field/operator/missing': 2780,
'atp/field/operator_wikidata/missing': 2780,
'atp/field/phone/missing': 2780,
'atp/field/postcode/missing': 2780,
'atp/field/state/missing': 2780,
'atp/field/street_address/missing': 2780,
'atp/field/twitter/missing': 2780,
'atp/field/website/missing': 2780, …
```
> [BoxNow] Switch to local proxy

- locations/spiders/dino_pl.py
Found an issue with regex string for parsing the decryption parameters. I fixed it by adding some white space and different quoting characters. 
The next issue is with getting the encrypted GeoJSON from the api. Both the api and the robots.txt for `api-dino.appchance.shop` say that the site is under maintenance mode. With that I am not sure why it seems to work with `https://marketdino.pl/map`.
> [dino_pl] Fixed issue with parsing decryption parameters

- locations/spiders/aarons.py
```python
{"atp/brand/Aaron's": 1234,
'atp/brand_wikidata/Q10397787': 1234,
'atp/category/shop/furniture': 1234,
'atp/cdn/cloudflare/response_count': 1237,
'atp/cdn/cloudflare/response_status_count/200': 1237,
'atp/field/email/missing': 1234,
'atp/field/image/missing': 1234,
'atp/field/operator/missing': 1234,
'atp/field/operator_wikidata/missing': 1234,
'atp/field/twitter/missing': 1234,
'atp/nsi/perfect_match': 1234,
'downloader/request_bytes': 549242,
'downloader/request_count': 1237,
'downloader/request_method_count/GET': 1237,
'downloader/response_bytes': 66352513,
'downloader/response_count': 1237,
'downloader/response_status_count/200': 1237,
'elapsed_time_seconds': 29.450292, …
```
> [Aarons] Fix spider

- locations/spiders/societe_generale.py
Previous sitemap URL was redirecting to another domain which was not present in `allowed_domains`.
> [societe_generale] fix spider

- locations/spiders/rewe_de.py
```python
{'atp/brand/REWE': 3732,
'atp/brand_wikidata/Q16968817': 3732,
'atp/category/shop/supermarket': 3732,
'atp/field/country/from_spider_name': 3732,
'atp/field/email/missing': 3732,
'atp/field/image/missing': 3732,
'atp/field/operator/missing': 3732,
'atp/field/operator_wikidata/missing': 3732,
'atp/field/twitter/missing': 3732,
'atp/geometry/null_island': 5,
'atp/nsi/match_failed': 3732,
'downloader/request_bytes': 5874817,
'downloader/request_count': 3737,
'downloader/request_method_count/GET': 3737,
'downloader/response_bytes': 1635732012,
'downloader/response_count': 3737,
'downloader/response_status_count/200': 3734, …
```
> [REWE DE] Fix spider

- locations/spiders/tomtom.py
I've been vocal in that some brands should be looking after their own spiders, when they are, we should document a contact method for them. In theory it could be plumed in to email them automatically when there is an issue with a spider.
> Add contacts attribute on spider

- locations/spiders/brow_art_23_us.py
```python
{'atp/brand/Brow Art 23': 113,
'atp/brand_wikidata/Q115675881': 113,
'atp/category/shop/beauty': 113,
'atp/field/city/missing': 113,
'atp/field/country/from_reverse_geocoding': 113,
'atp/field/email/missing': 113,
'atp/field/image/missing': 113,
'atp/field/opening_hours/missing': 113,
'atp/field/operator/missing': 113,
'atp/field/operator_wikidata/missing': 113,
'atp/field/postcode/missing': 113,
'atp/field/street_address/missing': 113,
'atp/field/twitter/missing': 113,
'atp/nsi/perfect_match': 113,
'downloader/request_bytes': 695,
'downloader/response_bytes': 19448,
'elapsed_time_seconds': 0.756287, …
```
> [BrowArt23 US] Add spider

- locations/spiders/best_and_less_au.py
```python
{'atp/brand/Best & Less': 190,
'atp/brand_wikidata/Q4896542': 190,
'atp/category/shop/clothes': 190,
'atp/field/email/missing': 187,
'atp/field/image/missing': 190,
'atp/field/operator/missing': 190,
'atp/field/operator_wikidata/missing': 190,
'atp/field/twitter/missing': 190,
'atp/nsi/perfect_match': 190,
'downloader/request_bytes': 5307,
'downloader/request_count': 12,
'downloader/request_method_count/GET': 12,
'downloader/response_bytes': 44348,
'downloader/response_count': 12,
'downloader/response_status_count/200': 11,
'elapsed_time_seconds': 1.761716,
'finish_time': datetime.datetime(2024, 6, 28, 14, 22, 11, 164318, …
```
> [BestAndLess AU] Fix spider

- locations/spiders/castorama_pl.py
fixes #8658 - and closes #8608 as it would be treated as a mistake
I though about putting them into `branch` but these, as far as I checked, are not even real branch names
I guess that just dropping them would be possible?
> fix Castorama names

- locations/spiders/vlh_de.py
Sitemap was changed as well as some html tags on individual pages. I also preferred name from NSI, <title> has it just as brand name + address e.g. `Beratungsstelle der Vereinigten Lohnsteuerhilfe  Apolda 99510, Goldgasse 7`.
```json
{
"atp/brand/Vereinigte Lohnsteuerhilfe": 2950,
"atp/brand_wikidata/Q15852617": 2950,
"atp/category/office/tax_advisor": 2950,
"atp/field/country/from_spider_name": 2950,
"atp/field/image/missing": 2950,
"atp/field/opening_hours/missing": 1296,
"atp/field/operator/missing": 2950,
"atp/field/operator_wikidata/missing": 2950,
"atp/field/phone/missing": 33,
"atp/field/state/missing": 2950,
"atp/field/twitter/missing": 2950,
"atp/nsi/perfect_match": 2950,
"downloader/request_bytes": 1018717,
"downloader/request_count": 2952,
"downloader/request_method_count/GET": …
```
> [vhl_de] fix spider, use name from NSI

- locations/spiders/virsi_lv.py
Rel: https://github.com/osmlab/name-suggestion-index/pull/9660
```python
{'atp/brand/Virši': 78,
'atp/brand_wikidata/Q50378789': 78,
'atp/category/amenity/fuel': 78,
'atp/field/city/missing': 78,
'atp/field/country/from_spider_name': 78,
'atp/field/email/missing': 77,
'atp/field/image/missing': 78,
'atp/field/name/missing': 78,
'atp/field/opening_hours/missing': 78,
'atp/field/operator/missing': 78,
'atp/field/operator_wikidata/missing': 78,
'atp/field/postcode/missing': 78,
'atp/field/state/missing': 78,
'atp/field/street_address/missing': 78,
'atp/field/twitter/missing': 78,
'atp/field/website/missing': 78,
'atp/nsi/brand_missing': 78, …
```
> [Virsi LV] Add spider

- locations/spiders/burger_king_cz.py
Weirdly `allowed_domains` isn't enforced in `start_requests` for me locally, however it appears that's not the case in the weekly.
> [BurgerKing CZ] Fix allowed domains

- locations/spiders/natwest_gb.py
"The telephone number for the venue" in https://github.com/alltheplaces/alltheplaces/blob/master/DATA_FORMAT.md promises venue-specific one
Note: `callcenter_phone` is something that I invented on the spot
> fix #8740 - keep shared phone out of phone tag

- locations/pipelines/check_item_properties.py
There has been an increase of `atp/field/opening_hours/invalid`, not because we output more broken hours (still just wellsfargo, vivacom_bg and fantastiko_bg), but because we now output closed days. I've updated the regex, but this is regex and OSM opening hours are far more complex. Up until now I've had a soft preference for outputting `OpeningHours` directly, not a string, so we can skip the regex test. I want this to now be a strong recommendation for everyone, no more `.as_opening_hours()` without a good reason.
> [Hours] Update regex pattern to allow closed days

- locations/pipelines/check_item_properties.py
For a while now, we've been able to output either a string or a `OpeningHours` object. Using the object allows us to skip validation in the pipeline. However recently empty `OpeningHours` have been showing up as a class in DEBUG output:
```python
{'extras': {'@spider': 'test_1'},
'opening_hours': <locations.hours.OpeningHours object at 0x738cf5f9bfe0>,
'ref': 'none_null'}
```
In #8631 `OpeningHours` was given `__bool__`. This is good, and behaves as I'd expect, False when there is no data, and True when there is someing to output. However it also tricks me, eg the following exception will never happen:
```python
item["opening_hours"] = OpeningHours()
if item.get("opening_hours"):
raise Exception()  # Never gonna happen
```
It also tricks the pipeline, empty `OpeningHours` fails the `if` …
> [Hours] Drop empty OpeningHours before DEBUG logging and the exporter

- locations/hours.py
- tests/test_opening_hours.py
Fixes #6537
As mentioned before `opening_hours=24/7` actually means `opening_hours=Mo-Su,PH 00:00-24:00`, but we don't (and never will) collect `PH`. We probably will collect specific days in the future.
> [Hours] Stop outputting 24/7

- locations/spiders/upsstore.py
I did a quick check and was not able to find any stores that are closed, so assume that the website gives only operational stores.
Stats:
```json
{
"atp/brand/UPS Store": 3221,
"atp/brand_wikidata/Q7771029": 3221,
"atp/category/amenity/post_office": 3221,
"atp/category/multiple": 3221,
"atp/cdn/cloudflare/response_count": 3258,
"atp/cdn/cloudflare/response_status_count/200": 3258,
"atp/closed_check": 1,
"atp/field/lat/missing": 7,
"atp/field/lon/missing": 7,
"atp/field/operator/missing": 3221,
"atp/field/operator_wikidata/missing": 3221,
"atp/field/phone/missing": 129,
"atp/field/twitter/missing": 46,
"atp/nsi/perfect_match": 3221,
"downloader/request_bytes": 1824991,
"downloader/request_count": 3258,
"downloader/request_method_count/GET": 3258,
"downloader/response_bytes": 145656195, …
```
> [upsstore] fix spider, convert to SitemapSpider

- locations/spiders/zaxbys_us.py
Fixes #8806
The data in the ld is always `opening_hours=Mo-Su 10:30-23:00`. Probably a templating issue with them. Actual opening hours are only available via an API call to `https://zapi.zaxbys.com/v1/stores/174855/calendars?from=2024-07-10&to=2024-07-16`
> [Zaxbys US] Drop opening hours

- locations/spiders/a101.py
I'll comeback at some point to try to collect more locations.
```json
{
"atp/brand/A101": 5545,
"atp/brand_wikidata/Q6034496": 5545,
"atp/category/shop/supermarket": 5545,
"atp/field/email/missing": 5545,
"atp/field/image/missing": 5545,
"atp/field/opening_hours/missing": 5545,
"atp/field/operator/missing": 5545,
"atp/field/operator_wikidata/missing": 5545,
"atp/field/phone/missing": 5545,
"atp/field/postcode/missing": 5545,
"atp/field/state/missing": 2,
"atp/field/twitter/missing": 5545,
"atp/field/website/missing": 5545,
"atp/nsi/perfect_match": 5545,
"downloader/request_bytes": 177740,
"downloader/request_count": 395,
"downloader/request_method_count/GET": 395,
"downloader/response_bytes": 729082,
"downloader/response_count": 395,
"downloader/response_status_count/200": 392, …
```
> [a101_tr] add spider (5k locations)

- locations/spiders/dominos_pizza_in.py
The amount decreased by about two thirds compared to previous runs and I can see how this is somewhat of a hack way to fix it. But open to other ideas. Maybe crawl [this](https://www.dominos.co.in/restaurants-near-me) instead.
Summary of the changes is changing the sitemap urls from store-locations to store-location. 
```python
{"atp/brand/Domino's": 588,
'atp/brand_wikidata/Q839466': 588,
'atp/category/amenity/fast_food': 588,
'atp/field/city/missing': 588,
'atp/field/country/from_spider_name': 588,
'atp/field/email/missing': 588,
'atp/field/image/missing': 588,
'atp/field/opening_hours/missing': 588,
'atp/field/operator/missing': 588,
'atp/field/operator_wikidata/missing': 588, …
```
> [dominos_pizza_in] Fixed spider as all store pages keep return 500 (588 items)

- locations/spiders/loves.py
`highway=service` is for roads, `highway=services` is for truck stops/rest areas.
```python
{"atp/brand/Love's": 646,
'atp/brand/Speedco': 53,
'atp/brand_wikidata/Q112455073': 53,
'atp/brand_wikidata/Q1872496': 646,
'atp/category/highway/services': 646,
'atp/category/shop/truck_repair': 53,
'atp/field/country/from_reverse_geocoding': 699,
'atp/field/image/missing': 699,
'atp/field/opening_hours/missing': 699,
'atp/field/operator/missing': 699,
'atp/field/operator_wikidata/missing': 699,
'atp/field/twitter/missing': 699,
'atp/nsi/cc_match': 646,
'atp/nsi/perfect_match': 53,
'downloader/request_bytes': 16027,
'downloader/request_method_count/GET': 17,
'downloader/response_bytes': 4135509,
'downloader/response_count': 17, …
```
> [Loves] Improve branding and categories

- locations/spiders/dorevitch_pathology_au.py
I was looking at the website and looks like there are many other brands (which we have spiders for) under Healius name.  Such as Abbott, Laverty, QML, TML, and Western_diagnostic_pathology. What is the standard for these. Should we merge all these together under just a HealiusPathologyAU spider?
> [dorevitch_pathology_au] Fix Spider by new url (462 items)

- locations/spiders/jumbo_ch.py
updated sitemap
```python
{'atp/brand/Jumbo': 123,
'atp/brand_wikidata/Q1713190': 123,
'atp/category/shop/doityourself': 123,
'atp/field/email/missing': 123,
'atp/field/operator/missing': 123,
'atp/field/operator_wikidata/missing': 123,
'atp/field/state/missing': 123,
'atp/field/twitter/missing': 123,
'atp/nsi/perfect_match': 123,
'downloader/request_bytes': 234437,
'downloader/request_count': 274,
'downloader/request_method_count/GET': 274,
'downloader/response_bytes': 9729808,
'downloader/response_count': 274,
'downloader/response_status_count/404': 7,
'elapsed_time_seconds': 338.729687,
'finish_time': datetime.datetime(2024, 7, 11, 15, 29, 6, 557790, tzinfo=datetime.timezone.utc),
'httpcompression/response_bytes': 41257644,
'httpcompression/response_count': 132, …
```
> [jumbo_ch] Fix Spider

- .isort.cfg
- Pipfile.lock
- ci/concatenate_parquet.py
Prompted by the discussion in https://github.com/alltheplaces/alltheplaces/pull/8798#issuecomment-2226903728, I rewrote the concatenation script that the weekly script uses to generate a single parquet for the output of all the spiders to use pyarrow directly instead of going through geopandas. Running this locally on a recent run, I see a maximum memory usage of ~5GB.
I spent a bunch of time trying to rewrite the Parquet item exporter to use pyarrow directly, but I gave up after dealing with the translation between "list of dictionaries/rows" to "list of columns" that is required. And it helps to have geopandas there for producing a valid geoparquet, too.
> Use pyarrow to concatenate parquet files instead of geopandas

- locations/spiders/audi.py
```python
{'atp/brand/Audi': 5162,
'atp/brand_wikidata/Q23317': 5162,
'atp/category/shop/car': 5162,
'atp/field/country/from_reverse_geocoding': 5162,
'atp/field/email/missing': 5162,
'atp/field/image/missing': 5162,
'atp/field/opening_hours/missing': 5162,
'atp/field/operator/missing': 5162,
'atp/field/operator_wikidata/missing': 5162,
'atp/field/phone/invalid': 69,
'atp/field/phone/missing': 16,
'atp/field/twitter/missing': 5162,
'atp/field/website/missing': 5162,
'atp/nsi/cc_match': 5162,
'downloader/request_bytes': 145643,
'downloader/request_count': 114,
'downloader/request_method_count/POST': 114,
'downloader/response_bytes': 5215770,
'downloader/response_count': 114,
'downloader/response_status_count/200': 114, …
```
> [Audi] Fix spider

- locations/spiders/orange_pl.py
(again, dropping them completely would be likely better but per https://github.com/alltheplaces/alltheplaces/pull/8782 it seems that keeping them is required)
> drop not really real names - orange_pl

- locations/spiders/mccoys.py
```python
{"atp/brand/McCoy's Building Supply": 87,
'atp/brand_wikidata/Q27877295': 87,
'atp/category/shop/doityourself': 87,
'atp/cdn/cloudflare/response_count': 89,
'atp/cdn/cloudflare/response_status_count/200': 89,
'atp/field/operator/missing': 87,
'atp/field/operator_wikidata/missing': 87,
'atp/nsi/perfect_match': 87,
'downloader/request_bytes': 39848,
'downloader/response_bytes': 702695,
'downloader/response_count': 89,
'elapsed_time_seconds': 109.294493,
'finish_time': datetime.datetime(2024, 7, 15, 19, 56, 0, 903943, tzinfo=datetime.timezone.utc),
'httpcompression/response_bytes': 3735074,
'httpcompression/response_count': 89,
'item_scraped_count': 87,
'log_count/DEBUG': 192,
'log_count/INFO': 10,
'request_depth_max': 1, …
```
> [mccoys] Fix Spider (87 locations)

- locations/spiders/cinemark.py
Also limit parsing to theater pages, and don't include logo image
> [Cinemark] Add download delay to prevent HTTP 429 errors

- locations/spiders/morrisons_gb.py
(again, dropping them completely may be better as it is not exactly a branch but per #8782 it seems that keeping them is required)
warning: I never visited UK, I am not familiar with this chain but this guess seems safe
> 'Newcastle-under-Lyme - Milehouse Lane Petrol Station' is not an actual name

- locations/spiders/dino_pl.py
resubmission of #8782 code removal
this is merely some web listing name
"Lubiąż 1" from https://www.alltheplaces.xyz/map/#19.53/51.2662366/16.467911 does not appear in shop or even on receipt
Likely the same should be done with
- https://github.com/alltheplaces/alltheplaces/pull/8839/files
- https://github.com/alltheplaces/alltheplaces/pull/8836/files
- https://github.com/alltheplaces/alltheplaces/pull/8835/files
- https://github.com/alltheplaces/alltheplaces/pull/8834/files
Created as in https://github.com/alltheplaces/alltheplaces/pull/8837 the web listing code was removed, instead of shunted into `branch` so maybe the same can succeed here?
(can gave photo of receipt from this shop if anyone wants - "Lubiąż 1" is really not listed there, company name, company address and shop address …
> this is not a branch code

- locations/spiders/warby_parker.py
```py
{'atp/brand/Warby Parker': 272,
'atp/brand_wikidata/Q7968882': 272,
'atp/category/shop/optician': 272,
'atp/cdn/cloudflare/response_count': 7,
'atp/field/email/missing': 272,
'atp/field/image/missing': 272,
'atp/field/opening_hours/missing': 14,
'atp/field/operator/missing': 272,
'atp/field/operator_wikidata/missing': 272,
'atp/field/twitter/missing': 272,
'atp/nsi/perfect_match': 272,
'downloader/request_bytes': 6099,
'downloader/request_count': 7,
'downloader/request_method_count/GET': 7,
'downloader/response_bytes': 400109,
'downloader/response_count': 7,
'elapsed_time_seconds': 8.41435, …
```
> [WarbyParker] New spider (272 locations)

- locations/spiders/pressed_us.py
```py
{'atp/brand/Pressed': 106,
'atp/brand_wikidata/Q123005477': 106,
'atp/category/amenity/fast_food': 106,
'atp/field/country/from_spider_name': 106,
'atp/field/email/missing': 106,
'atp/field/image/missing': 106,
'atp/field/operator/missing': 106,
'atp/field/operator_wikidata/missing': 106,
'atp/field/twitter/missing': 106,
'atp/nsi/perfect_match': 106,
'downloader/request_bytes': 1300,
'downloader/response_bytes': 11685,
'elapsed_time_seconds': 1.764303, …
```
> [PressedUS] New spider (106 locations)

- locations/spiders/ollies_bargain_outlet.py
I added proxy since this only runs in the US.
Now that it is running I notice that it was creating 4 POIs for stores that are marked as coming soon. These were being created with no opening hours so misleading.
So excluding these.
> [OlliesBargainOutlet] Do not create POI for opening soon

- locations/spiders/barrys.py
Template generated by autospidergen/sf.
```py
{"atp/brand/Barry's": 93,
'atp/brand_wikidata/Q96373178': 93,
'atp/category/leisure/fitness_centre': 93,
'atp/field/city/missing': 93,
'atp/field/country/from_reverse_geocoding': 93,
'atp/field/image/missing': 93,
'atp/field/opening_hours/missing': 93,
'atp/field/phone/missing': 30,
'atp/field/postcode/missing': 87,
'atp/field/street_address/missing': 93,
'atp/field/twitter/missing': 93,
'atp/field/website/missing': 9,
'downloader/request_bytes': 367,
'downloader/response_bytes': 10813, …
```
> [Barrys] New spider (93 locations)

- locations/spiders/laseraway_us.py
Template generated by autospidergen/sf.
```py
{'atp/brand/LaserAway': 172,
'atp/brand_wikidata/Q119982751': 172,
'atp/category/shop/beauty': 172,
'atp/field/image/missing': 172,
'atp/field/operator/missing': 172,
'atp/field/operator_wikidata/missing': 172,
'atp/field/twitter/missing': 172,
'atp/nsi/perfect_match': 172,
'downloader/request_bytes': 675,
'downloader/response_bytes': 14067,
'elapsed_time_seconds': 2.395632, …
```
> [LaserawayUS] New spider (172 locations)

- locations/spiders/paczkomat_inpost_pl.py
1. FIX of regression caused by #8881. State is needed to generate website, without it `https://inpost.pl/paczkomat-staniatki-sit01m-staniatki-paczkomaty` would generate instead of `https://inpost.pl/paczkomat-staniatki-sit01m-staniatki-paczkomaty-malopolskie` 
2. Some POI have streets like `Ułańska/Tysiąclecia` which is not valid in OSM and should be removed
3. Some POI have house number also at the end of street, these should be removed
> [paczkomat_inpost_pl] cleanup POI, fix generation of webiste

- locations/spiders/dominos_pizza_tw.py
```python
{"atp/brand/Domino's": 187,
'atp/brand_wikidata/Q839466': 187,
'atp/category/amenity/fast_food': 187,
'atp/field/city/missing': 187,
'atp/field/country/from_spider_name': 187,
'atp/field/email/missing': 187,
'atp/field/image/missing': 187,
'atp/field/postcode/missing': 187,
'atp/field/state/missing': 187,
'atp/field/street_address/missing': 187,
'atp/field/twitter/missing': 187,
'atp/field/website/missing': 187,
'atp/nsi/cc_match': 187,
'atp/operator/晶華國際酒店集團': 187,
'atp/operator_wikidata/Q11090227': 187,
'downloader/request_bytes': 134651,
'downloader/request_count': 188,
'downloader/request_method_count/GET': 188,
'downloader/response_bytes': 330432,
'downloader/response_count': 188,
'downloader/response_status_count/200': 188, …
```
> [dominos_pizza_tw] Added Dominos in Taiwan (187 items)

- ci/concatenate_parquet.py
Follows #8827 
We were getting the following error during builds:
```
File ""/home/ubuntu/ci/concatenate_parquet.py", line 95, in <module>
main()
File ""/home/ubuntu/ci/concatenate_parquet.py", line 53, in main
parquet_file = pyarrow.parquet.ParquetFile(parquet_filename)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File ""/home/ubuntu/.pyenv/versions/3.11.9/lib/python3.11/site-packages/pyarrow/parquet/core.py", line 317, in __init__
self.reader.open(
File "pyarrow/_parquet.pyx", line 1480, in pyarrow._parquet.ParquetReader.open
File "pyarrow/error.pxi", line 91, in pyarrow.lib.check_status
pyarrow.lib.ArrowInvalid: Parquet file size is 0 bytes
```
This attempts to catch that error and skip the file instead of crashing the whole thing.
> Skip over empty parquet files during concat

- locations/spiders/paczkomat_inpost_pl.py
If `street` and `city` is that same, that usually means that it is not a city but a village, and should not have `city` nor `street` tag, but a `place`
> [paczkomat_inpost_pl] detect Village

- locations/spiders/burger_king_th.py
```
{'atp/brand/Burger King': 109,
'atp/brand_wikidata/Q177054': 109,
'atp/category/amenity/fast_food': 109,
'atp/field/city/missing': 109,
'atp/field/country/from_spider_name': 109,
'atp/field/email/missing': 109,
'atp/field/image/missing': 109,
'atp/field/opening_hours/missing': 109,
'atp/field/operator/missing': 109,
'atp/field/operator_wikidata/missing': 109,
'atp/field/postcode/missing': 109,
'atp/field/state/missing': 109,
'atp/field/street_address/missing': 109,
'atp/field/twitter/missing': 109,
'atp/field/website/missing': 109,
'atp/nsi/cc_match': 109,
'downloader/request_bytes': 1011, …
```
> [burger_king_th] Add Spider (109 locations)

- locations/spiders/paczkomat_inpost_pl.py
Appkomat InPost is a special type of paczkomat, which can be operated only using app. No NSI nor WIKIDATA for now.
> [paczkomat_inpost_pl] different tags for appkomat

- locations/spiders/paczkomat_inpost_pl.py
Seems like it is not applied from NSI
"Osiedle" should be put in `addr:place`
> [paczkomat_inpost_pl] readd parcel_locker for appkomat, move "Osiedle" to `addr:place`

- locations/spiders/marks_and_spencer.py
Improve is the key word here. It's not perfect, I think that's partially because they are in the middle of own rebrands eg `M&S Simply Food` to `M&S Food`, which I don't fully understand, also I think the data isn't always right. eg [Foodhall](https://www.google.com/maps/place/M%26S+Simply+Food/@55.9281543,-3.2093829,3a,41.5y,247.22h,86.18t/data=!3m6!1e1!3m4!1sicIhDQ8XV30brrc-XrEu5w!2e0!7i16384!8i8192!4m12!1m5!3m4!2zNTXCsDU1JzQyLjQiTiAzwrAxMiczNS4zIlc!8m2!3d55.92844!4d-3.2098!3m5!1s0x4887c70bc1600b8f:0xcd095eaec99af19d!8m2!3d55.9280948!4d-3.209776!16s%2Fg%2F1tfgjd1n?coh=205409&entry=ttu) or [Simply Food](https://www.marksandspencer.com/stores/edinburgh-morningside-simply-food-6211).
This isn't perfect, simply improved.
> [Marks & Spencer] Improve branding and store types

- locations/spiders/smart_charge_gb.py
```python
{'atp/brand/Smart Charge': 52,
'atp/brand_wikidata/Q127686420': 52,
'atp/category/amenity/charging_station': 52,
'atp/field/city/missing': 52,
'atp/field/country/from_spider_name': 52,
'atp/field/email/missing': 52,
'atp/field/image/missing': 52,
'atp/field/phone/missing': 52,
'atp/field/state/missing': 52,
'atp/field/twitter/missing': 52,
'atp/field/website/missing': 52,
'atp/nsi/brand_missing': 52,
'downloader/response_bytes': 34593, …
```
> [Smart Charge GB] Add spider

- locations/spiders/mobilelink.py
```
{'atp/brand/Mobilelink': 455,
'atp/category/missing': 455,
'atp/field/brand_wikidata/missing': 455,
'atp/field/city/missing': 455,
'atp/field/country/from_reverse_geocoding': 455,
'atp/field/email/missing': 455,
'atp/field/image/missing': 455,
'atp/field/name/missing': 455,
'atp/field/operator/missing': 455,
'atp/field/operator_wikidata/missing': 455,
'atp/field/postcode/missing': 455,
'atp/field/website/missing': 455,
'downloader/request_bytes': 616,
'downloader/response_bytes': 340734,
'elapsed_time_seconds': 3.572048, …
```
> [mobilelink] Fix Spider (455 locations)

- Dockerfile
- ci/run_all_spiders.sh
- locations/spiders/albertsons.py
- locations/spiders/goodwill.py
- locations/spiders/lidl_bg.py
- locations/spiders/via313.py
Follows #8798
For #8932 
The latest weekly build failed with an error like:
```
File "/home/ubuntu/ci/concatenate_parquet.py", line 106, in <module>
main()
File "/home/ubuntu/ci/concatenate_parquet.py", line 88, in main
unified_schema = pyarrow.unify_schemas(schemas, promote_options="permissive")
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "pyarrow/types.pxi", line 3444, in pyarrow.lib.unify_schemas
File "pyarrow/error.pxi", line 154, in pyarrow.lib.pyarrow_internal_check_status
File "pyarrow/error.pxi", line 91, in pyarrow.lib.check_status
pyarrow.lib.ArrowTypeError: Unable to merge: Field nsi_id has incompatible types: string vs int64
```
Basically: the `nsi_id` field is usually a `string` but sometimes its an `int64`, and the …
> Try to resolve parquet concatenation again

- locations/spiders/nuffield_health_gb.py
```python
{'atp/brand/Nuffield Health Fitness & Wellbeing': 113,
'atp/brand_wikidata/Q7068711': 113,
'atp/category/leisure/fitness_centre': 113,
'atp/cdn/cloudflare/response_count': 132,
'atp/cdn/cloudflare/response_status_count/200': 132,
'atp/field/city/missing': 113,
'atp/field/country/from_spider_name': 113,
'atp/field/email/missing': 112,
'atp/field/image/missing': 113,
'atp/field/opening_hours/missing': 113,
'atp/field/operator/missing': 113,
'atp/field/operator_wikidata/missing': 113,
'atp/field/state/missing': 113,
'atp/field/street_address/missing': 113,
'atp/field/twitter/missing': 113,
'atp/nsi/perfect_match': 113,
'downloader/request_bytes': 49575, …
```
> [Nuffield Health GB] Add spider (fixes #8927)

- locations/spiders/bob_evans_us.py
> bob_evans_us - remove name

- locations/spiders/vodafone_de.py
After name was removed from use in #8948, this variable was no longer needed. I'm removing it here.
> No need to extract name here

- locations/exporters/geoparquet.py
1. When capturing items for the `GeoparquetExporter`, convert the attributes to strings so that the parquet columns are stored as strings. Without this, the `concatenate_parquet.py` script was having a very hard time unifying the schema types.
2. When a spider fails or otherwise doesn't scrape items, the `GeoparquetExporter` throws an exception because GeoPandas doesn't want to write out an empty parquet file. Instead of throwing that exception, just skip the writing of the parquet file.
> A couple Parquet output fixes

- locations/spiders/away.py
```py
{'atp/brand/Away': 17,
'atp/brand_wikidata/Q48743138': 17,
'atp/category/shop/bag': 17,
'atp/field/country/from_reverse_geocoding': 17,
'atp/field/postcode/missing': 16,
'atp/nsi/brand_missing': 17,
'downloader/request_bytes': 691,
'downloader/response_bytes': 39451,
'elapsed_time_seconds': 2.054558,
'finish_time': datetime.datetime(2024, 7, 25, 2, 39, 37, 924458, tzinfo=datetime.timezone.utc), …
```
> [Away] New spider (17 locations)

- locations/spiders/travismathew_us.py
```py
{'atp/brand/TravisMathew': 54,
'atp/category/shop/clothes': 54,
'atp/field/brand_wikidata/missing': 54,
'atp/field/city/missing': 54,
'atp/field/country/from_spider_name': 54,
'atp/field/postcode/missing': 54,
'atp/field/state/from_reverse_geocoding': 54,
'atp/field/street_address/missing': 54,
'downloader/request_bytes': 144152,
'downloader/request_count': 111,
'downloader/request_method_count/GET': 111,
'downloader/response_bytes': 5174817,
'downloader/response_count': 111,
'downloader/response_status_count/200': 57,
'downloader/response_status_count/301': 54, …
```
> [TravismathewUS] New spider (54 locations)

- locations/spiders/mendocino_farms.py
```py
{'atp/brand/Mendocino Farms': 72,
'atp/brand_wikidata/Q110671982': 72,
'atp/category/amenity/fast_food': 72,
'atp/cdn/cloudflare/response_count': 75,
'atp/cdn/cloudflare/response_status_count/200': 75,
'atp/field/twitter/missing': 72,
'atp/nsi/perfect_match': 72,
'downloader/request_bytes': 73245,
'downloader/request_count': 75,
'downloader/request_method_count/GET': 75,
'downloader/response_bytes': 496240,
'downloader/response_count': 75,
'downloader/response_status_count/200': 75,
'elapsed_time_seconds': 88.722342,
'finish_time': …
```
> [MendocinoFarms] New spider (72 locations)

- locations/spiders/fogo_de_chao.py
```py
{'atp/brand/Fogo de Chão': 91,
'atp/brand_wikidata/Q5464133': 91,
'atp/category/amenity/restaurant': 91,
'atp/field/city/missing': 91,
'atp/field/country/from_reverse_geocoding': 91,
'atp/field/email/missing': 91,
'atp/field/image/missing': 91,
'atp/field/opening_hours/missing': 91,
'atp/field/operator/missing': 91,
'atp/field/operator_wikidata/missing': 91,
'atp/field/postcode/missing': 91,
'atp/field/twitter/missing': 91,
'atp/nsi/perfect_match': 91,
'downloader/request_bytes': 610,
'downloader/response_bytes': 37708, …
```
> [FogoDeChao] New spider (91 locations)

- locations/spiders/brandy_melville.py
I'm not sure if this one is worth it, since so few results have valid coordinates.
Also, sorry for the PR spam! I forget to push sometimes…
```py
{'atp/brand/Brandy Melville': 85,
'atp/brand_wikidata/Q25387414': 85,
'atp/category/shop/clothes': 85,
'atp/field/email/missing': 85,
'atp/field/image/missing': 85,
'atp/field/lat/missing': 74,
'atp/field/lon/missing': 74,
'atp/field/operator/missing': 85,
'atp/field/operator_wikidata/missing': 85,
'atp/field/postcode/missing': 85,
'atp/field/state/missing': 41,
'atp/field/twitter/missing': 85, …
```
> [BrandyMelville] New spider (85 locations)

- locations/spiders/starbucks_eu.py
From https://github.com/alltheplaces/alltheplaces/pull/8993#issuecomment-2254338471
>  starbucks_eu.geojson has "addr:full": "undefined, BA11 4QE Frome", "addr:street_address": "undefined"
> Clean up specifically starbucks_eu addresses

- locations/spiders/posta_si.py
Pošta Slovenije is the Slovenian national postal service operator. This spider is based on the API behind their location finder: https://en.posta.si/post-offices
I couldn't find an endpoint that returns all the data at once, but the minimum length for a search query is 1, so iterating through the alphabet gets you everything without too many requests (26).
The two locations that appear in Italy are also there on the website, so this is an issue at the source, not the spider. I've already informed them about it.
> Added Pošta Slovenije spider (456 locations)

- locations/spiders/seven_eleven_th.py
The website should have 14k locations, but the spider is getting only 6k at the moment. 
I'll comeback at some point to try to collect more locations.
```json
{
"atp/brand/7-Eleven": 6208,
"atp/brand_wikidata/Q259340": 6208,
"atp/category/shop/convenience": 6208,
"atp/field/city/missing": 6208,
"atp/field/country/from_spider_name": 6208,
"atp/field/email/missing": 6208,
"atp/field/image/missing": 6208,
"atp/field/opening_hours/missing": 6208,
"atp/field/operator/missing": 6208,
"atp/field/operator_wikidata/missing": 6208,
"atp/field/phone/invalid": 2408,
"atp/field/phone/missing": 2,
"atp/field/postcode/missing": 2,
"atp/field/state/missing": 4,
"atp/field/street_address/missing": 6208,
"atp/field/twitter/missing": 6208,
"atp/field/website/missing": 6208,
"atp/nsi/cc_match": 6208, …
```
> [seven_eleven_th] add spider (6k locations)

- locations/spiders/kia.py
```
{'atp/brand/Kia': 1853,
'atp/brand_wikidata/Q35349': 1853,
'atp/category/shop/car': 1548,
'atp/category/shop/car_repair': 305,
'atp/field/country/from_reverse_geocoding': 31,
'atp/field/country/from_website_url': 20,
'atp/field/email/missing': 323,
'atp/field/image/missing': 1853,
'atp/field/opening_hours/missing': 1853,
'atp/field/operator/missing': 1853,
'atp/field/operator_wikidata/missing': 1853,
'atp/field/phone/invalid': 35,
'atp/field/phone/missing': 31,
'atp/field/state/missing': 1822,
'atp/field/twitter/missing': 1853,
'atp/nsi/cc_match': 1853,
'downloader/request_bytes': 6789,
'downloader/request_count': 19,
'downloader/request_method_count/GET': 19,
'downloader/response_bytes': 412757,
'downloader/response_count': 19, …
```
> [Kia] Add more countries,  apply some fixes and add category (1853 locations)

- DATA_FORMAT.md
This `opening_hours=Mo-Su closed` can easily confuse people, especially as ATP is not using lifecycle prefixes in such cases (it is still `amenity=fast_food` etc) so warning at least in docs would be nice
> note Mo-Su closed
