locations/spiders/riesbeck.py
=> Add spider for Riesbeck's Food Markets

locations/hours.py, locations/linked_data_parser.py, locations/spiders/greene_king_inns.py, locations/spiders/matalan.py, locations/spiders/oak_furnitureland.py, locations/spiders/optical_express.py
I can't remember the exact numbers, but the Optical Express opening hours fuckery got us the vast majority of the opening hours. Going forward I wont be putting that much effort into bad opening hours.
=> Add Matalan, Oak Furnitureland and Optical Express spiders

locations/google_url.py, locations/spiders/greggs.py, locations/spiders/tui_gb.py, tests/test_google_url.py, tests/test_ld_parser.py, tests/test_opening_hours.py
Also fix some tests, and add Google Maps directions url parsing.
=> Add TUI GB and Greggs spiders

locations/pipelines.py, locations/spiders/lidl_gb.py, tests/test_pipeline_extract_gb_postcode.py
=> Improve Lidl address

locations/linked_data_parser.py, locations/spiders/wyndham.py
It hasn't finished running locally, but I think we're good.
=> Fix Wyndham spider

locations/spiders/fcbanking.py
- Somebody decided that the //-style comments in a json document should
now have \r line terminators
- Modernize code
=> Fix fcbanking

locations/linked_data_parser.py, locations/spiders/cubesmart.py
Teach LinkedDataParser iterate over "@graph" key.
Still narrowly avoiding having to implement any W3C specifications here.
=> Add spider for CubeSmart

locations/spiders/claires.py, locations/spiders/pandora.py
Also fix the phone number, opening hours and ref.
By trimming the ref from the whole URL to just to just the store ID we drop a few duplicates as before Canadian stores we're being scraped in both French and English.
=> Combine Pandora and Claire's spiders

.github/workflows/spider-pr.yaml
=> Update PR workflow to use latest ubuntu image.

locations/spiders/boots.py
=> Fix Boots Opticians detection

.github/workflows/pytest-pr.yaml, Pipfile, Pipfile.lock
So, I've actually no idea what I'm doing here, with Pipfile or GH workflows.
The idea is that any PR that changes core code should have the tests ran against them.
=> Add pytest workflow

.github/workflows/pytest-pr.yaml, Pipfile, Pipfile.lock
Like I said last time, don't really know what I'm doing. But hopefully this fixes the workflow.
=> Fix pytest

locations/geo.py, locations/spiders/aaa.py, locations/spiders/petsathome_gb.py, locations/spiders/whitecastle.py
Move a method into library code.
Picked a few first spiders to use it. Both have had fixes applied to existing small problems .... that's how it goes .... you will see more White Castle locations slide in as they say.
=> Move centroid points support to library code, modify some spiders to use

locations/spiders/johnsoncleaners_gb.py, locations/spiders/timpson_gb.py
Timpson owns Johnson Cleaners.
=> Add timpson_gb and johnsoncleaners_gb: ~1600 stores

locations/spiders/bre_wingz.py
=> Add BreWingz Spider

locations/dict_parser.py, locations/spiders/festival_foods.py
=> Add Festival Foods Spider

locations/spiders/yettel_bg.py
=> Add Yettel Spider

locations/spiders/chargy_gb.py
=> Add char.gy spider

Pipfile.lock, ci/run_all_spiders.sh, locations/commands/spider_filename.py, locations/settings.py
Get the filename of the spider and save it in the output JSON for the weekly run.
=> Add custom command to get filename of spider

locations/microdata_parser.py, locations/spiders/fiveguys.py
Also allow microdata to run on earlier versions of python.
=> Update Five Guys to use microdata

locations/spiders/vivacom.py, locations/spiders/vivacom_bg.py
Ideally @Dimitar5555 will check the output on this one.
Fixes #3713
=> Add Vivacom spider

locations/dict_parser.py
The dict parser will need to have its dictionary extended as we move forward.
Based on the experience of using a similar function in my own project I have
contributed what I consider a reasonable dictionary. It is based on the
experience of hundreds of spiders and shoudl save a bit of work going forward.
The separation of the data diciotnary from the logic I also think makes
life clearer.
=> Extend the dictionary of dict parser

locations/spiders/dutchbros.py
Delicious coffee stand addition.
=> Add a Dutch Bros spider.

locations/spiders/fuzzys_tacos.py
Yeah the LinkedData stuff is awesome!
=> Fuzzy's Taco Shop scraper.

locations/dict_parser.py, tests/test_dict_parser.py
This avoids us having to write "lon", "Lon", "LON" for every key
=> Compute key variations for DictParser

locations/dict_parser.py, locations/spiders/bmo_harris.py, locations/spiders/riteaid.py, locations/spiders/speedway.py
The old spider has been inconstant because it was hitting the 4 hour limit, the limit has now been increased but this would still hit it. approx 40,000 in the US with a 0.5 second delay would still run for around 5 days.
This gives us 43,477 across US and CA in about 15 minuets. And technically we could drop the 0.5 delay.
=> Fix BMO Haris Spider

locations/spiders/walgreens.py
While investigating why no output in last few runs then
had cause to simplify spider. Slowed down the request rate
as they definitely throttle. Let's see what happens.
=> Improve? Fix? Walgreens spider

locations/spiders/pricechopper.py
130 supermarkets in New England
=> Add spider for Price Chopper

locations/spiders/holland_and_barrett.py
Typo in the sitemap list! Also make holland_and_barrett spider
a good citizen as they throttle and stop the spider quite quickly.
=> Fix holland_and_barret sitemap URLs

locations/spiders/edible_arrangements.py
=> Fix Edible Arrangements hours typo

locations/hours.py, locations/spiders/supercuts.py, tests/test_opening_hours.py
Add day_range method and support day ranges where the start-end are
reversed from the conventional Mo-Su ordering.
=> Fix supercuts

locations/spiders/webuyanycar_gb.py
Anyone getting tired off:
**from locations.linked_data_parser import LinkedDataParser
from locations.microdata_parser import MicrodataParser
MicrodataParser.convert_to_json_ld(response)
LinkedDataParser.parse(response, "BLAH"):**
appearing everwhere, and could possibly envisage:
**from locations.microdata_parser import MicrodataParser
MicrodataParser.parse(response, "BLAH")**
.. being added to do this!
=> Add webuyanycar_gb (500 used car dealers)

locations/google_url.py, locations/spiders/wrenkitchens_gb.py, tests/test_google_url.py
Required tweak to static embedded map parse. We are a bit in the dark with this.
=> Add wrenkitchens_gb (100+ showrooms)

locations/spiders/nike.py
"addr_full" was shooting blanks as they say.
=> Clean up Nike, get correct store URL, also image URL

locations/spiders/gucci.py
If you like discussions about what constitues and individual store then this one is just for you.
=> Fix Gucci, worldwide ~450 stores

locations/spiders/planet_fitness.py
It looks like they have Cloudflare bot blocking enabled, though.
=> Update Planet Fitness

locations/spiders/snarfs.py
Most excellent sandwich chain based in Colorado (30+ locations).
=> Scraper for Snarf's Sandwiches.

locations/spiders/ikes.py
West coast sandwich chain (103 locations).
=> Spider for Ike's Love & Sandwiches.

locations/spiders/burgerville.py
Burgerville is a chain in Oregon and it is extremely delicious (41 locations).
=> Burgerville spider.

locations/linked_data_parser.py, locations/spiders/ikes.py, tests/test_ld_parser.py
Also document default type for geo, address, country and image objects
=> Properly handle country dict in Linked Data parser

locations/hours.py, tests/test_opening_hours.py
Most spiders that have opening hours have to do some kind of sanitation on the day, most of it could be shared code.
=> Allow more day values in OH

locations/spiders/burger_fi.py
I had already written this one, but hadn't committed it for some reason. Sorry to dup the effort.
=> Exclude burgerfi test restaurant

locations/spiders/primrose_schools.py
=> Fix Primrose Schools error on no results

locations/spiders/dominos_pizza_jp.py
=> Fix dominos_pizza_jp

locations/linked_data_parser.py, locations/spiders/modpizza.py
I had to tweak the linked_data_parser as the geo tag was nested under the "location", not sure if this was a good idea though...  If there's a better way, let me know.
=> MOD Pizza spider.

locations/spiders/deltaco.py
I confess I have never eaten here even though there is one nearby.
=> Del Taco Spider (592 locations).

locations/pipelines.py, locations/spiders/costacoffee_gb.py
No more lat lon search, resulting in 13,661 items in 20 seconds.
Fixes #3805
=> Another Costa PR

locations/spiders/natural_grocers.py
This grocery store is amazing.
=> Spider for Natural Grocers (165 stores).

locations/spiders/vapestore_gb.py
Locations wont be extracted on this one until #3963 is merged and adds support for this url format.
=> Add vapestore Spider

locations/spiders/costacoffee_gb.py
This literally broke between [this PR](https://github.com/alltheplaces/alltheplaces/pull/3958) on the 14th, and the weekly on the 17th.
=> Fix Costa GB Opening Hours parsing

locations/spiders/advanceautoparts.py, locations/spiders/aldi_de.py, locations/spiders/bluerhino.py, locations/spiders/chase.py, locations/spiders/cricket_wireless.py, locations/spiders/dollar_general.py, locations/spiders/dunkin.py, locations/spiders/general_logistics_systems.py, locations/spiders/kaiser_permanente.py, locations/spiders/little_caesars.py, locations/spiders/pizza_hut.py, locations/spiders/ppgpaints.py, locations/spiders/safeway.py, locations/spiders/statefarm.py, locations/spiders/timhortons.py, locations/spiders/tmobile_us.py, locations/spiders/vr_bank.py, locations/spiders/wellsfargo.py
I used insights from #3883 to find spiders without a country code. This is just the top ones, that were easy to fix, there is a long tale.
=> Add country codes to spiders

locations/dict_parser.py, locations/spiders/whsmith_gb.py
Slightly improves the amount of stores we get, but is significantly quicker, and now honors robots.txt
@rjw62 this picks up some more airport shops, if it's still missing some let me know.
=> Move WHSmith to an API

locations/dict_parser.py, locations/spiders/decathlon.py
Required slight tweak to DictParser.get_nested_key to go looking in lists also.
=> Add decathlon spider (~930 stores)

locations/spiders/famous_footwear.py
=> Fix Famous Footwear lat/lon

locations/google_url.py, locations/spiders/usavingsbank.py
Parse marker from google staticmap
=> Add spider for Union Savings Bank (Ohio)

locations/spiders/bq.py
This can very nearly be a StructuredDataSpider, it's just missing a full sitemap, or a page we can crawl. Since we have to use the API to get a list of stores, we may as well use it to get all the data.
=> Fix B&Q Spider

locations/spiders/hm.py
=> Fix H&M Spider

locations/spiders/homegoods.py
From 954 errors, 0 locations in 6.5 hours, to 877 locations, 0 errors in 4 mins.
=> Fix Homegoods

locations/spiders/pandaexpress.py
From 31092 errors to 2163 locations
=> Fix Panda Express

locations/dict_parser.py, locations/spiders/marriott_hotels.py
I say fix but who knows what state it was in before. The Marriott estate is complex as hopefully is clear from the code and comments. One thing for sure, would not have liked to do this without:
$ pipenv run scrapy nsi --name protea
"Protea Hotels", "Q17092570"
-> https://www.wikidata.org/wiki/Q17092570
-> https://www.wikidata.org/wiki/Special:EntityData/Q17092570.json
-> South African-based hotel chain
-> http://protea.marriott.com/
-> item_attributes = {"brand": "Protea Hotels", "brand_wikidata": "Q17092570"}
=> Fix, to some level, Marriott (~7K sites)

locations/spiders/petco.py
=> Fix Petco, convert to StructuredDataSpider (~1500 sites)

locations/spiders/farmerboys.py
Scrapes 100 [locations](https://www.farmerboys.com/locations/)
Closes https://github.com/alltheplaces/alltheplaces/issues/3530
Here's the sample output:
```json
{"type": "Feature", "id": "8UiK4I64urhrJQSZF3xz5ySVQxE=", "properties": {"ref": "baldwin-park-merced-ave", "@spider": "farmerboys", "addr:street": "14430 Merced Ave.", "addr:city": "Baldwin Park", "addr:state": "CA", "addr:postcode": "91706", "addr:country": "US", "name": "Baldwin Park - Merced Ave.", "phone": "(626) 856-1000", "website": "https://www.farmerboys.com/locations/location-detail.php?loc=baldwin-park-merced-ave", "opening_hours": "Mon-Sun  6:00a-12:00a", "brand": "Farmer Boy's"}, "geometry": {"type": "Point", "coordinates": [-117.962104, 34.072683]}},
{"type": "Feature", "id": "JBXNafOxNrkP615zMzgBWMSxWsA=", …
```
=> Adds Farmer Boy's Spider

locations/spiders/carrabbasitaliangrill.py
=> Fix Carrabbas Italian Grill Spider

locations/spiders/cafe_zupas.py
=> Add spider for Cafe Zupas

locations/microdata_parser.py
=> Handle "www." schema.org in microdata to json

locations/spiders/alicedelice.py
This is my first pull request on this repo
I created this first spider for a brand of houseware located in France.
I hope this will meet your standards
=> Adding French houseware brand Alice Delice

locations/spiders/hilton.py
So Hilton stopped working in the last run. Picked up easily of course. As noted in spider when committed a few months ago, it looks like the group was in a little bit if flux. Looks like that has settled down now. Use CJ's latestand greatest StructuredDataSpider incarnation, Hilton estate now working and even better than before. Yay.
=> Fix hilton, now an extra 2.5K locations

locations/spiders/davidstea.py
=> Add David's tea spider

locations/spiders/thecheesecakefactory.py
Uses sitemapspider and structreddataspider to crawl and parse locations
Fixes #822
=> Add the cheesecake factory spider

ci/run_all_spiders.sh
This runs the command added in #4072 after all the spiders are done, saves it in the stats/ dir, and includes the URL in the build summary JSON.
=> Run the insights command as part of weekly build

locations/commands/nsi.py, locations/spiders/bathandbodyworks.py, locations/spiders/biggby.py, locations/spiders/brookdale.py, locations/spiders/coldstone_creamery.py, locations/spiders/general_logistics_systems.py, locations/spiders/hard_rock.py, locations/spiders/intermarche.py, locations/spiders/jbhifi.py, locations/spiders/kruidvat.py, locations/spiders/spirithalloween.py
Inspired by @Romeo-PHILLIPS and @Cj-Malone a few more wikidata codes, no more planned today!
Also a slight tweak to the NSI query command to output category info also if there is a single name match.
=> A few more wikidata code for the pot

locations/spiders/cooplands_doncaster.py
=> Add Cooplands Doncaster spider

locations/spiders/thecheesecakefactory.py
=> Add filter to tccf spider

locations/spiders/barlouie.py
=> 3524: Added spider - Bar Louie

locations/linked_data_parser.py, locations/structured_data_spider.py
This used to be set by LinkedDataParser.parse but that's no longer used.
=> Fix website in StructuredDataSpider

README.md
=> 4099: Update readme for fetching brand_wikidata information

locations/spiders/crateandbarrel.py, locations/spiders/davidstea.py
=> 765: Adding spider: Crate And Barrel

locations/spiders/sprouts.py
=> 1055: Added spider: Sprouts Farmers Markets

locations/spiders/gelsons.py
=> Add gelsons spider

locations/spiders/bashas.py, locations/spiders/gelsons.py
=> Add Bashas' spider

locations/spiders/ridleys.py
Fixes https://github.com/alltheplaces/alltheplaces/issues/889
=> feat: Ridley's Family Markets

locations/spiders/freebirds.py
Fixes https://github.com/alltheplaces/alltheplaces/issues/3527
=> feat: Freebirds

locations/spiders/carrefour_ar.py
> TODO: Figure out why the hash changed. Will this happen again?
Unfortunately I think the answer is yes. So if it breaks again, we'll have to investigate further.
```json
{
"persistedQuery": {
"version": 1,
"sha256Hash": "a84a4ca92ba8036fe76fd9e12c2809129881268d3a53a753212b6387a4297537",
"sender": "lyracons.lyr-store-locator@0.x",
"provider": "vtex.store-graphql@2.x"
},
"variables": "eyJhY2NvdW50IjoiY2FycmVmb3VyYXIifQ=="
}
```
The only thing that changed was `sha256Hash`, `variables` is `{"account":"carrefourar"}` base64 and stayed the same. So I don't think `sha256Hash` is a hash of the request, but more likely an ID of a stored sql query, and that changed. Potentially they just improved the query, but if the query has a date in it, it's going to be a pain for us.
=> Fix Carrefour AR Spider

locations/spiders/teds_montana_grill.py
=> feat: Add Ted's Montana Grill spider

locations/spiders/shell.py
And get the extras to be a little closer to OSM.
=> Fix Shell QID

locations/hours.py, locations/spiders/duffys.py
https://github.com/alltheplaces/alltheplaces/issues/3518
Opening hours a bit ugly but it works
=> feat: Duffys

locations/pipelines.py, locations/settings.py, locations/spiders/aldi_sud_us.py
Also add a pipeline to try and clean up countries codes. Fixes #3795
=> Filter potential NSI matches by country code

locations/spiders/allied_universal.py
=> feat: Add Allied Universal spider

locations/spiders/cava.py
=> feat: Add Cava spider

locations/spiders/safelite.py
=> feat: Add Safelite spider

locations/spiders/farmershomefurniture.py
Ended up getting a bit more involved than I thought, but it's done now.
=> Fix farmershomefurniture error

locations/spiders/steak_n_shake.py
These headers were all broken due the the extra spaces in them, but turns out they aren't needed anyway.
=> Clean up steak_n_shake

Pipfile, Pipfile.lock, locations/spiders/mcdonalds_my.py
Required adding brotli decompression library. McDonalds MY **insist** on using this compression!
I committed my changed Pipfile.lock, I am not sure if that is the right thing to do!
=> Fix mcdonalds_my spider

locations/dict_parser.py, locations/spiders/sainsburys.py
Plus loads of "facilities" metadata
=> Expand Sainsburys to collect Travel Money, Cafes and Petrol stations

DATA_FORMAT.md
... and also the format of the output.
=> Add a little bit more information about IDs

docs/STRUCTURED_DATA.md, locations/spiders/petco.py, locations/spiders/subway.py, locations/spiders/webuyanycar_gb.py, locations/spiders/wickes_gb.py
=> more doc, clean up of referenced example spiders

docs/PULL_REQUEST.md, docs/SITEMAP.md
I will do a STRUCTURED_DATA.md page next.
=> more incremental doc additions

locations/spiders/intermarche.py
@Romeo-PHILLIPS perhaps you could provide some insight on this one? Particularly around `modelLabel` at line 54+, and maybe [NSI](https://nsi.guide/index.html?t=brands&tt=Intermarch%C3%A9) isn't perfect?
=> Fix Intermarche Spider

locations/structured_data_spider.py
I've not actually encounted anywhere where this is needed, but at least on paper we should prefer canonical urls when available.
=> Prefer canonical url in StructuredDataSpider

docs/GETTING_STARTED.md, docs/HARD_WORK_SPIDER.md, docs/OPENING_HOURS.md, docs/WHY_SPIDER.md, docs/WIKIDATA.md, locations/spiders/greggs_gb.py
This writing game is harder work than code! You get to the point of boring yourself. Once again I have expressed some sentiments that might not be agreed with or are sloppily worded etc. @iandees: sorry to make you read this! We can chop it however you like but I think we start to have the some reasonably useful "bones".
=> More docs and one associated spider edit

locations/hours.py, locations/spiders/ubreakifix.py, tests/test_opening_hours.py
I wanna rewrite the structured data opening hours parser at some point, so extra tests or documented cases of things not being parsed when maybe they should be would be appreciated.
=> Add uBreak iFix Spider

locations/dict_parser.py, locations/spiders/woolworths.py, locations/spiders/woolworths_au.py, tests/test_dict_parser.py
More stores, less requests.
Unfortunately I don't think it works from the US, so weekly is still broken.
=> Woolworths

locations/spiders/penny.py
Unfortunately the penny de website uses a different API, but all the other countries use a standard API.
=> Add Penny Spider

locations/spiders/pandaexpress.py
For 2k POIs we can try 10 requests. Still no completely effective, but hopefully it'll work more frequently.
=> Bump panda express retries

locations/spiders/cubesmart.py, locations/spiders/extended_stay_america.py, locations/spiders/frankie_and_bennys_gb.py, locations/spiders/intermarche.py, locations/spiders/moncler.py
These are broken in the weekly, but work locally.
=> Flag spiders as needing proxies

locations/spiders/decathlon_nl.py, locations/spiders/decathlon_sk.py
As noted in #4217, some Decathlon regions are still missing.
=> Add Decathlon NL and SK spiders

locations/spiders/pizza_hut_gb.py
=> Drop closed Pizza Huts

locations/spiders/stadt_zuerich_ch.py
There’s a _lot_ more data that could be converted here, but let’s start small.
=> Add spider for Stadt Zürich, 2425 places

locations/spiders/wolseley_gb.py
Unfortunately the linked data is now loaded via js, but we can use there API.
=> Fix Wolseley GB Spider

locations/spiders/stadt_zuerich_ch.py
This includes all the schools, kindergardens, after-school facilities, and special-needs schools that are operated by the City of Zürich. Any schools run by other operators (such as cantonal schools, private schools, universities, etc.) are not part of the city data feed.
=> City of Zürich: Add schools (1015 places)

locations/google_url.py
https://www.google.com/maps/embed?pb=
https://www.google.com/maps/embed/v1/place
=> Match both embed url formats on iframes

locations/spiders/carrefour_fr.py
Trying out the new spider :)
3591 -> 4038
=> update: Carrefour Woosmap

locations/spiders/accor.py
=> fix: accor

locations/pipelines.py, tests/test_pipeline_phone_cleanup.py
@brawer I can't add you as a reviewer, but I want your opinion. I don't think I did anything controversial though.
=> Catch exceptions in PhoneCleanUpPipeline

locations/country_utils.py, tests/test_country_utils.py
=> Handle accents in country names

locations/spiders/total.py
=> feat: TotalEnergies

Dockerfile, ci/run_all_spiders.sh
=> Protect against missing zip

ci/restore_history.py
For https://github.com/alltheplaces/alltheplaces/issues/4258
=> Add script to restore history.json from S3 bucket

locations/hours.py, locations/spiders/denner_ch.py, tests/test_opening_hours.py
Closes https://github.com/alltheplaces/alltheplaces/issues/841.
=> Add spider for Denner, supermarkets in Switzerland, 855 places

locations/spiders/academy.py, locations/structured_data_spider.py
This is. a fix for the Academy spider (Thanks @Cj-Malone for the tip on SitemapSpider/StructuredDataSpider ! )
=> Fix academy Spider

locations/spiders/anatomie.py
This is a fix for the Anatomie spider
=> Fix Anatomie Spider

locations/spiders/nhs_england_gb.py, locations/spiders/nhs_scotland_gb.py, locations/structured_data_spider.py
So the NHS is big. Very big. Just doctors and dentists in England add 15K sites.
One contentious change is to structured_data_spider.py
What was there before is obviously wrong.
But us my change good? @Cj-Malone ?
=> Add nhs_england_gb (~15,000 locations)

locations/spiders/athleta.py
This is a fix for the Athleta spider
=> Fix Athleta Spider

locations/pipelines.py, locations/spiders/lloyds_bank_gb.py
In a perfect world we would be able to use the extra data, but we can't yet
=> Only use the country from NSIs locationSet for matching

locations/spiders/andpizza.py
This is a fix for the Andpizza spider
=> Fix Andpizza Spider

locations/spiders/bass_pro_shops.py
This is a fix for the bassproshops spider
=> fix Bassproshops spider

.github/workflows/pytest-pr.yaml, locations/microdata_parser.py, locations/spiders/halifax_gb.py, tests/test_microdata_parser.py
=> Drop empty microdata objects

locations/spiders/barmethod.py
This is a fix for the Barmethod spider
=> fix Barmethod spider

locations/spiders/holland_and_barrett.py
=> Fix website for Holland and Barrett

locations/spiders/bc_pizza.py
This is a fix for the bcpizza spider
=> fix Bcpizza spider

locations/spiders/averitt.py
This is a fix for the Averitt spider
=> fix Averitt spider

locations/linked_data_parser.py, locations/spiders/belk.py, locations/spiders/officedepot.py
=> Update json5 spiders

README.md
Could someone validate the Slack link please.
@brawer @Romeo-PHILLIPS @jancallewaert @abbensid2 the Slack isn't that active, but it'd be nice to see you there.
=> Add contact details

locations/spiders/via313.py
A small brand, but an olive branch
=> Add Via 313 Spider

locations/spiders/creditunion.py
The lat and lon of the Credit Unions have disappeared from their site. I don't know if we allow a spidered POI without lat/lon.
=> Fix CreditUnion spider

locations/exporters.py, locations/spiders/stadt_zuerich_ch.py
For the motivation of this change, see
https://github.com/alltheplaces/alltheplaces/issues/4338.
=> Allow spiders to tag output with machine-readable metadata

locations/spiders/fiveguys.py
=> Use sitemap_follows to be more specific about Five Guys URLs

.flake8, .github/workflows/pytest-pr.yaml, .github/workflows/spider-pr.yaml, .pre-commit-config.yaml, locations/spiders/obi_de.py
Trying to make dependency caching work.
=> Install into pipenv virtualenv instead of system so that caching works

locations/spiders/leon.py
```python
{'atp/field/email/missing': 154,
'atp/field/image/missing': 154,
'atp/field/opening_hours/invalid': 1,
'atp/field/opening_hours/missing': 70,
'atp/field/phone/missing': 154,
'atp/field/state/missing': 154,
'atp/field/street_address/missing': 154,
'atp/field/twitter/missing': 154,
'atp/nsi/category_match': 147,
'atp/nsi/cc_match': 4,
'atp/nsi/match_failed': 3,
'downloader/request_bytes': 1196,
'downloader/response_bytes': 1068162,
'downloader/response_status_count/404': 2,
'elapsed_time_seconds': 10.967461,
'finish_time': datetime.datetime(2022, 12, 23, 9, 23, 24, 636362), …
```
=> Add LEON Spider

locations/spiders/canada_post.py
=> Fix and update spider canadapost

locations/spiders/guzmany_gomez.py
eg https://www.guzmanygomez.com.au/locations/Hoxton-Park/
=> Collect mulitiple Guzman y Gomez opening times

locations/spiders/ihg_hotels.py
Brand name and wikidata to check.
=> Fix and update spider ihg_hotels

locations/spiders/calvin_klein.py, locations/spiders/calvin_klein_au.py, locations/spiders/calvin_klein_ca_us.py
US/CA
```python
{'atp/field/email/missing': 157,
'atp/field/twitter/missing': 157,
'atp/nsi/perfect_match': 157,
'downloader/request_bytes': 59477,
'downloader/request_count': 160,
'downloader/request_method_count/GET': 160,
'downloader/response_bytes': 3392922,
'downloader/response_count': 160,
'downloader/response_status_count/200': 160,
'elapsed_time_seconds': 259.544032,
'finish_time': datetime.datetime(2022, 12, 29, 11, 3, 44, 791270),
'httpcache/hit': 160,
'httpcompression/response_bytes': 14081009,
'httpcompression/response_count': 159,
'item_scraped_count': 157,
'log_count/DEBUG': 327,
'log_count/INFO': 13,
'log_count/WARNING': 1,
'memusage/max': 251908096, …
```
=> Fix Calvin Klein Spiders

locations/spiders/goodlifefitness.py
@Cj-Malone that's good for you!
We missed opening_hours
=> update spider goodlifefitness

locations/spiders/remax_de.py
@Cj-Malone  that's good for you
=> Update spider remax de

.github/workflows/spider-pr.yaml
The PR script seems to fail occasionally, so I'm adding a log to hopefully see why.
=> Add log for pr file changes script

locations/pipelines.py, locations/settings.py, tests/test_pipeline_count_categories.py
The `missing` counter is particularly interesting, but why not count them all.
=> Count categories of harvested items

locations/spiders/new_look_gb.py
=> Fix New Look website

locations/spiders/homebase_gb_ie.py
=> Adjust regex for Homebase spider

locations/spiders/loft.py
=> update spider loft

.github/workflows/spider-pr.yaml
=> Add auth headers for PR files get

locations/spiders/primark_gb.py
```python
{'atp/category/shop/clothes': 185,
'atp/field/email/missing': 185,
'atp/field/image/missing': 185,
'atp/field/state/missing': 185,
'atp/field/twitter/missing': 185,
'atp/nsi/cc_match': 185,
'downloader/request_bytes': 132057,
'downloader/request_count': 199,
'downloader/request_method_count/GET': 199,
'downloader/response_bytes': 15942892,
'downloader/response_count': 199,
'downloader/response_status_count/200': 187,
'downloader/response_status_count/500': 12,
'elapsed_time_seconds': 233.544291,
'finish_time': datetime.datetime(2023, 1, 2, 18, 30, 7, 299180),
'httpcache/firsthand': 191,
'httpcache/hit': 8,
'httpcache/miss': 191,
'httpcache/store': 191,
'httpcompression/response_bytes': 99659951, …
```
=> Fix primark_gb

locations/spiders/pdq.py
NSI PR: https://github.com/osmlab/name-suggestion-index/pull/7609
=> Add PDQ wikidata

locations/exporters.py
Closes https://github.com/alltheplaces/alltheplaces/issues/4537.
=> Mark data from spiders that ignore robots.txt

locations/spiders/bathandbodyworks.py, locations/spiders/bathandbodyworks_us.py
bathandbodyworks_us
```python
{'atp/category/shop/cosmetics': 1692,
'atp/field/email/missing': 1692,
'atp/field/image/missing': 1692,
'atp/field/twitter/missing': 1692,
'atp/field/website/missing': 1692,
'atp/nsi/perfect_match': 1692,
'downloader/request_bytes': 470,
'downloader/response_bytes': 102335,
'elapsed_time_seconds': 3.731219,
'finish_time': datetime.datetime(2023, 1, 3, 17, 5, 9, 27589),
'httpcache/hit': 1,
'httpcompression/response_bytes': 803747, …
```
=> Split and fix Bath and Body Works US

locations/spiders/chemist_warehouse_au.py
=> Add spider for Chemist Warehouse (AU) (491 stores)

locations/spiders/simonmalls.py, locations/user_agents.py
```python
{'atp/category/shop/mall': 201,
'atp/field/email/missing': 201,
'atp/field/image/invalid': 2,
'atp/field/twitter/missing': 2,
'atp/nsi/perfect_match': 201,
'downloader/request_bytes': 251,
'downloader/response_bytes': 887506,
'elapsed_time_seconds': 4.058149,
'finish_time': datetime.datetime(2023, 1, 4, 14, 40, 8, 812508),
'httpcache/firsthand': 1,
'httpcache/miss': 1,
'httpcache/store': 1,
'httpcompression/response_bytes': 6072670, …
```
=> Fix simonmalls spider

contrib/fetch_all_stats.sh
Sometimes my internet drops and I have to re run it.
=> Don't redownload stat files

locations/spiders/franprix.py, locations/spiders/franprix_fr.py
=> feat: Franprix

locations/pipelines.py, locations/spiders/c_and_a.py
https://github.com/alltheplaces/alltheplaces/issues/4340
=> fix: c_and_a

locations/spiders/lidl_de.py, locations/spiders/saturn_de.py
Continuing on from @Ebubeker  in #4403
```python
{'atp/category/shop/supermarket': 3232,
'atp/field/email/missing': 3232,
'atp/field/image/missing': 3232,
'atp/field/phone/missing': 3232,
'atp/field/state/missing': 3232,
'atp/field/twitter/missing': 3232,
'atp/field/website/missing': 3232,
'atp/nsi/category_match': 3232,
'downloader/request_bytes': 11304,
'downloader/request_count': 15,
'downloader/request_method_count/GET': 15,
'downloader/response_bytes': 358956,
'downloader/response_count': 15,
'downloader/response_status_count/200': 14,
'elapsed_time_seconds': 6.359686,
'finish_time': datetime.datetime(2023, 1, 5, 12, 40, 51, 780198),
'httpcache/hit': 15, …
```
=> Improve Lidl DE yield

locations/spiders/amcal_au.py
```python
{'atp/category/amenity/pharmacy': 196,
'atp/category/multiple': 196,
'atp/field/country/from_spider_name': 196,
'atp/field/email/missing': 166,
'atp/field/image/missing': 196,
'atp/field/opening_hours/missing': 196,
'atp/field/twitter/missing': 196,
'atp/nsi/perfect_match': 196,
'downloader/request_bytes': 399085,
'downloader/request_count': 206,
'downloader/request_method_count/GET': 206,
'downloader/response_bytes': 9794618,
'downloader/response_count': 206,
'downloader/response_status_count/200': 206,
'dupefilter/filtered': 64,
'elapsed_time_seconds': 8.547422,
'finish_time': datetime.datetime(2023, 1, 8, 16, 44, 20, 357368),
'httpcache/hit': 206, …
```
=> Add Amcal AU Spider

locations/spiders/guardian_au.py
=> Add Guardian Spider

locations/exporters.py
Apply dataset_attributes and export geometry
=> Fix ndgeojson exporter

README.md, locations/items.py, locations/spiders/exxonmobil.py, locations/spiders/stadt_zuerich_ch.py
After this change, `git grep GeojsonPointItem` finds no matches in the AllThePlaces codebase.
=> Finish renaming of `GeojsonPointItem` to `Feature`

locations/exporters.py, tests/test_exporters.py
This unifies the behavour with all other item attributes
=> Don't export empty extras

locations/spiders/grape_tree_gb.py
```python
{'atp/category/shop/health_food': 137,
'atp/field/email/missing': 137,
'atp/field/twitter/missing': 137,
'atp/field/website/missing': 137,
'atp/nsi/perfect_match': 137,
'downloader/request_bytes': 668,
'downloader/response_bytes': 17592,
'elapsed_time_seconds': 1.57349,
'finish_time': datetime.datetime(2023, 1, 9, 15, 41, 40, 661283),
'httpcompression/response_bytes': 127326,
'item_scraped_count': 137,
'log_count/DEBUG': 149,
'log_count/WARNING': 1, …
```
=> Add Grape Tree Spider

.github/workflows/spider-pr.yaml
It was missing a variable declaration.
Also, don't run on more than 5 spiders.
=> Fix PR builder

locations/spiders/7_11_au.py
```python
{'atp/category/amenity/fuel': 604,
'atp/category/shop/convenience': 135,
'atp/field/city/missing': 739,
'atp/field/email/missing': 739,
'atp/field/image/missing': 739,
'atp/field/twitter/missing': 739,
'atp/field/website/missing': 739,
'atp/nsi/category_match': 739,
'downloader/response_bytes': 1584128,
'elapsed_time_seconds': 2.799791,
'finish_time': datetime.datetime(2023, 1, 9, 16, 51, 30, 669080),
'httpcompression/response_bytes': 90, …
```
=> Add 7/11 AU Spider

locations/categories.py, locations/spiders/federal_savings_bank.py
Fix spider, no wikidata entry exists.
=> Fix Federal Savings Bank

locations/spiders/mccoys.py
We'll get categories the Sunday after https://github.com/osmlab/name-suggestion-index/pull/7608 is merged too.
=> Reuse linked data dict

locations/hours.py, locations/spiders/7_11_dk.py
```python
{'atp/category/amenity/fuel': 56,
'atp/category/shop/convenience': 118,
'atp/field/country/from_spider_name': 36,
'atp/field/email/missing': 174,
'atp/field/image/missing': 174,
'atp/field/state/missing': 174,
'atp/field/twitter/missing': 174,
'atp/field/website/invalid': 21,
'atp/nsi/category_match': 174,
'downloader/request_bytes': 641,
'downloader/response_bytes': 64043,
'elapsed_time_seconds': 1.260182,
'finish_time': datetime.datetime(2023, …
```
=> Add 7-11 DK spider

locations/spiders/technomarket.py
=> Add Technomarket spider

locations/spiders/goldsmiths_gb.py
```python
{'atp/category/shop/jewelry': 142,
'atp/field/image/missing': 142,
'atp/field/state/missing': 142,
'atp/field/twitter/missing': 142,
'atp/nsi/perfect_match': 142,
'downloader/request_bytes': 16906,
'downloader/request_count': 31,
'downloader/request_method_count/GET': 31,
'downloader/response_bytes': 849961,
'downloader/response_count': 31,
'downloader/response_status_count/200': 31,
'elapsed_time_seconds': 30.440259,
'finish_time': datetime.datetime(2023, 1, 13, 14, 9, 39, 250342),
'httpcache/firsthand': 27,
'httpcache/hit': 4,
'httpcache/miss': 27,
'httpcache/store': 27,
'item_scraped_count': 142,
'log_count/DEBUG': …
```
=> Add Goldsmiths GB Spider

locations/spiders/crew_clothing_gb.py
```python
{'atp/category/shop/clothes': 90,
'atp/field/country/from_spider_name': 44,
'atp/field/email/missing': 90,
'atp/field/twitter/missing': 90,
'atp/nsi/perfect_match': 90,
'downloader/request_bytes': 56750,
'downloader/request_count': 92,
'downloader/request_method_count/GET': 92,
'downloader/response_bytes': 1362156,
'downloader/response_count': 92,
'downloader/response_status_count/200': 92,
'elapsed_time_seconds': 4.06127,
'finish_time': datetime.datetime(2023, 1, 13, 13, 18, 13, 858261),
'httpcache/hit': 92,
'httpcompression/response_bytes': 6718918, …
```
=> Add Crew Spider

locations/hours.py, locations/spiders/sunglass_hut.py, locations/spiders/sunglass_hut_gb.py
```python
{'atp/category/shop/optician': 55,
'atp/field/website/missing': 55,
'atp/nsi/perfect_match': 55,
'downloader/request_bytes': 1087,
'downloader/response_bytes': 17132,
'elapsed_time_seconds': 2.050694,
'finish_time': datetime.datetime(2023, 1, 13, 12, 50, 46, 733392),
'httpcompression/response_bytes': 137724, …
```
=> Add Sunglass Hut GB Spider

locations/spiders/reiss_gb.py
```python
{'atp/category/shop/clothes': 54,
'atp/field/state/missing': 54,
'downloader/request_bytes': 101694,
'downloader/request_count': 78,
'downloader/request_method_count/GET': 78,
'downloader/response_bytes': 5549743,
'downloader/response_count': 78,
'downloader/response_status_count/200': 75,
'downloader/response_status_count/500': 3,
'elapsed_time_seconds': 7.446079,
'finish_time': datetime.datetime(2023, 1, 15, 15, 47, 57, 158452),
'httpcache/hit': 78,
'httpcompression/response_bytes': 13163578,
'httpcompression/response_count': 57, …
```
=> Add Reiss GB Spider

locations/spiders/arctic_circle_us.py
```python
{'atp/category/amenity/fast_food': 69,
'atp/field/country/from_spider_name': 69,
'atp/field/email/missing': 69,
'atp/field/image/missing': 69,
'atp/field/opening_hours/missing': 69,
'atp/field/twitter/missing': 69,
'atp/field/website/missing': 69,
'atp/nsi/perfect_match': 69,
'downloader/response_bytes': 5264,
'elapsed_time_seconds': 3.645645,
'finish_time': datetime.datetime(2023, 1, 17, 18, 37, 50, 691007),
'httpcache/firsthand': 2,
'httpcache/miss': 2,
'httpcache/store': 2, …
```
=> Add Arctic Circle US Spider (Fixes #3505)

locations/spiders/cousins_subs_us.py
```python
{'atp/category/missing': 94,
'atp/field/country/from_spider_name': 94,
'atp/field/email/missing': 94,
'atp/field/opening_hours/missing': 94,
'atp/nsi/brand_missing': 94,
'downloader/request_bytes': 795,
'downloader/response_bytes': 31994,
'elapsed_time_seconds': 4.793182,
'finish_time': datetime.datetime(2023, 1, 17, 19, 1, 38, 763907),
'httpcache/firsthand': 2,
'httpcache/miss': 2,
'httpcache/store': 2,
'httpcompression/response_bytes': 219686,
'item_scraped_count': 94, …
```
=> Add Cousins Subs US Spider (Fixes #3512)

locations/spiders/dan_john.py
```python
{'atp/brand/Dan John': 133,
'atp/brand_wikidata/Q116304215': 133,
'atp/category/missing': 133,
'atp/field/email/invalid': 11,
'atp/field/opening_hours/missing': 133,
'atp/field/twitter/missing': 133,
'atp/nsi/brand_missing': 133,
'downloader/request_bytes': 652,
'downloader/response_bytes': 151809,
'elapsed_time_seconds': 3.489086,
'finish_time': datetime.datetime(2023, 1, 23, 9, 47, 49, 104555), …
```
=> Add Dan John Spider

locations/spiders/tops_at_spar.py
```python
{'atp/brand/Tops': 920,
'atp/brand_wikidata/Q116377563': 920,
'atp/category/missing': 920,
'atp/field/city/missing': 114,
'atp/field/country/missing': 920,
'atp/field/email/missing': 920,
'atp/field/image/missing': 920,
'atp/field/lat/missing': 212,
'atp/field/lon/missing': 207,
'atp/field/opening_hours/missing': 920,
'atp/field/phone/invalid': 991,
'atp/field/phone/missing': 21,
'atp/field/postcode/missing': 920,
'atp/field/state/missing': 920,
'atp/field/street_address/missing': 9,
'atp/field/twitter/missing': 920,
'atp/nsi/brand_missing': 920,
'downloader/request_bytes': 696,
'downloader/response_bytes': 85720, …
```
=> Add Tops Spider

locations/categories.py, locations/pipelines.py, locations/spiders/total_energies.py
Fixes #4672
```python
{'atp/brand/AS 24': 496,
'atp/brand/Agip': 417,
'atp/brand/Aral': 2314,
'atp/brand/Avia': 696,
'atp/brand/BP': 1770,
'atp/brand/Cepsa': 3069,
'atp/brand/Elan': 799,
'atp/brand/Esso': 492,
'atp/brand/MOL': 763,
'atp/brand/Shell': 205,
'atp/brand/Slovnaft': 213,
'atp/brand/Total': 15626,
'atp/brand/Total Access': 758,
'atp/brand/Total Express': 170,
'atp/brand/TotalEnergies': 1180,
'atp/brand/Westfalen': 258,
'atp/brand/deal': 4,
'atp/brand/diver': 3,
'atp/brand/dyn': 112,
'atp/brand/elf': 18,
'atp/brand/em': 1,
'atp/brand/eos': 159,
'atp/brand/filt': 103,
'atp/brand/fin': 1,
'atp/brand/freie': 151,
'atp/brand/g&v': 1,
'atp/brand/gul': 106,
'atp/brand/haa': 20,
'atp/brand/omv': 15,
'atp/brand/sup': 25,
'atp/brand/totfa': 32,
'atp/brand/unb': 1454,
'atp/brand/wei': 20, …
```
=>  Filter Total Energies Spider output 

locations/spiders/relay_jeans.py
```
{'atp/brand/Relay Jeans': 100,
'atp/brand_wikidata/Q116378360': 100,
'atp/category/missing': 100,
'atp/field/country/from_reverse_geocoding': 100,
'atp/field/email/missing': 100,
'atp/field/image/missing': 100,
'atp/field/phone/invalid': 14,
'atp/field/state/missing': 100,
'atp/field/twitter/missing': 100,
'atp/field/website/missing': 100,
'atp/nsi/brand_missing': 100,
'downloader/request_bytes': 3143,
'downloader/response_bytes': 52278,
'downloader/response_status_count/302': 2,
'elapsed_time_seconds': 87.574268, …
```
=> Add Relay Jeans spider

locations/spiders/dial_a_bed_za.py
```python
{'atp/brand/Dial-a-Bed': 73,
'atp/brand_wikidata/Q116429178': 73,
'atp/category/missing': 73,
'atp/field/country/from_spider_name': 73,
'atp/field/email/missing': 73,
'atp/field/image/missing': 73,
'atp/field/opening_hours/missing': 73,
'atp/field/postcode/missing': 73,
'atp/field/state/missing': 73,
'atp/field/twitter/missing': 73,
'atp/nsi/brand_missing': 73,
'downloader/request_bytes': 627,
'downloader/response_bytes': 20006,
'elapsed_time_seconds': 2.376296,
'finish_time': datetime.datetime(2023, 1, 27, 15, 2, 32, 356395), …
```
=> Add Dial A Bed ZA Spider

locations/spiders/walmart.py
Fixing spider by getting back as a SitemapSpider. I know it has been a sitemap spider in the past and was converted in a crawler. However, it seems a crawler doesn't work correctly while a sitemaps spider for me does work...
=> Fix walmart spider

locations/hours.py, locations/spiders/yettel_rs.py
=> Yettel Serbia

locations/google_url.py, locations/hours.py, locations/spiders/cef_gb.py
Category will come soon: https://github.com/osmlab/name-suggestion-index/issues/7710
```python
{'atp/brand/City Electrical Factors': 209,
'atp/brand_wikidata/Q116495226': 209,
'atp/category/missing': 209,
'atp/field/country/from_spider_name': 209,
'atp/field/email/missing': 209,
'atp/field/twitter/missing': 209,
'atp/nsi/brand_missing': 209,
'downloader/request_bytes': 134710,
'downloader/request_count': 232,
'downloader/request_method_count/GET': 232,
'downloader/response_bytes': 8187043,
'downloader/response_count': 232,
'downloader/response_status_count/200': 232,
'dupefilter/filtered': 22,
'elapsed_time_seconds': 52.025626, …
```
=> Add CEF Spider

locations/dict_parser.py, locations/spiders/denmans_gb.py, tests/test_dict_parser.py
From https://www.denmans.co.uk/den/store-finder
=> First go at Denmans GB scraper (74 locations, but enables many similar ones)

locations/spiders/paperchase_gb.py, locations/spiders/vpz_gb.py, locations/storefinders/storemapper.py
Paperchase is in the process of going bankrupt, so it'll be a short lived spider. But I think it's an interesting time to have data for.
=> Add Paperchase spider

locations/hours.py, locations/spiders/lewis_stores.py
NSI is coming: https://github.com/osmlab/name-suggestion-index/pull/7744
```python
{'atp/brand/Lewis Stores': 493,
'atp/brand_wikidata/Q116474928': 493,
'atp/category/missing': 493,
'atp/field/email/missing': 493,
'atp/field/image/missing': 493,
'atp/field/state/missing': 493,
'atp/field/twitter/missing': 493,
'atp/field/website/missing': 493,
'atp/nsi/brand_missing': 493,
'downloader/request_bytes': 702,
'downloader/response_bytes': 52533,
'elapsed_time_seconds': 7.43798, …
```
=> Add Lewis Stores Spider

locations/spiders/centra_gb.py, locations/spiders/centra_ie.py
centra_ie
```python
{'atp/brand/Centra': 473,
'atp/brand_wikidata/Q747678': 473,
'atp/category/shop/convenience': 473,
'atp/field/city/missing': 473,
'atp/field/country/from_spider_name': 473,
'atp/field/email/missing': 473,
'atp/field/image/missing': 473,
'atp/field/opening_hours/missing': 473,
'atp/field/state/missing': 473,
'atp/field/street_address/missing': 473,
'atp/field/twitter/missing': 473,
'atp/field/website/missing': 473,
'atp/nsi/category_match': 473,
'downloader/request_bytes': 327,
'downloader/response_bytes': 60471, …
```
=> Add Centra spiders

locations/categories.py, locations/spiders/applegreen.py
https://github.com/osmlab/name-suggestion-index/pull/7745
```python
{'atp/brand/Applegreen': 189,
'atp/brand_wikidata/Q7178908': 189,
'atp/category/amenity/fuel': 189,
'atp/field/city/missing': 189,
'atp/field/country/from_reverse_geocoding': 189,
'atp/field/email/missing': 78,
'atp/field/image/missing': 189,
'atp/field/opening_hours/missing': 189,
'atp/field/postcode/missing': 78,
'atp/field/state/missing': 189,
'atp/field/street_address/missing': 189,
'atp/field/twitter/missing': 189,
'atp/field/website/missing': 189,
'atp/nsi/perfect_match': 189,
'downloader/request_bytes': 87784,
'downloader/request_count': 191,
'downloader/request_method_count/GET': 191,
'downloader/response_bytes': 154629, …
```
=> Add Applegreen Spider

locations/spiders/maxol_ie.py
rel: https://github.com/osmlab/name-suggestion-index/pull/7745
=> Add Maxol IE Spider

locations/spiders/mccolls_gb.py
- Avoid unnecessary fetching of individual store pages (responses were unused previously)
- Assign correct brand tags for different store fascias
- Add shop types based on source data descriptions
- Include full address in addr:full in output
=> Improve McColl's Spider

locations/spiders/baby_bunting.py
=> Add Baby Bunting (AU/NZ) (70 stores)

locations/spiders/anaconda_au.py
=> Add Anaconda (AU) (78 stores)

locations/spiders/evyve_gb.py
Car chargers. Category coming soon: https://github.com/osmlab/name-suggestion-index/commit/13dd952308763a6a1a38b3e3ad3b58b76b02b241
=> Add Evyve GB Spider

locations/spiders/barbeques_galore_au.py
=> Add Barbequeus Galore (AU) (90 stores)

locations/spiders/usps.py
https://data.alltheplaces.xyz/runs/2023-01-28-13-31-49/logs/usps.txt
=> Fix USPS errors

locations/spiders/fastbreak_us.py, locations/storefinders/storerocket.py
https://github.com/osmlab/name-suggestion-index/issues/7759
=> Add Fastbreak Spider

locations/spiders/primanti_bros_us.py
https://github.com/osmlab/name-suggestion-index/pull/7760
=> Add Primanti Bros US Spider

locations/spiders/vocelli_pizza_us.py
https://github.com/osmlab/name-suggestion-index/pull/7756
=> Add Vocelli Pizza US Spider

locations/spiders/boots_th.py
There are also addresses available in Thai through a different URL. Do we localize the names?
=> Fix Boots TH spider

locations/spiders/novus_ua.py
https://github.com/osmlab/name-suggestion-index/pull/7764
=> Add Novus UA Spider

locations/spiders/quest_diagnostics.py
Linked data is no longer available on the website.
=> Fix Quest Diagnostics spider

locations/spiders/fastbreak_us.py, locations/storefinders/momentfeed.py, locations/storefinders/storemapper.py, locations/storefinders/storepoint.py, locations/storefinders/storerocket.py, locations/storefinders/uberall.py, locations/storefinders/virtualearth.py, locations/storefinders/where2getit.py, locations/storefinders/woosmap.py
Briefly mentioned in https://github.com/alltheplaces/alltheplaces/issues/4757#issuecomment-1424639884
Similar to StructuredDataSpider, and the licenses by @brawer we want to give data consumers details about the source of the data so they can make a decision.
=> Document apis in the output

locations/spiders/francescas_us.py
=> Add Francesca's (US) (454 stores)

locations/spiders/boscovs_us.py
=> Add Boscov's (US) (50 stores)

locations/hours.py, locations/spiders/jmclaughlin_us.py
=> Add J. McLaughlin (US) (138 stores)

locations/spiders/london_drugs_ca.py
=> Add London Drugs (CA) (79 stores)

locations/spiders/mitre_10_au.py
=> Add Mitre 10 (AU) (414 stores)

locations/spiders/mitre_10_nz.py
=> Add Mitre 10 (NZ) (86 stores)

locations/spiders/national_seating_mobility.py, locations/storefinders/store_locator_plus.py
https://github.com/osmlab/name-suggestion-index/issues/7771
=> Add National Seating & Mobility Spider

.flake8, locations/__init__.py, locations/settings.py
=> Wrap install_cache

locations/spiders/century_21.py, locations/spiders/century_21_fr.py, locations/spiders/century_21_gb.py
=> Fix Century 21 GB country code

locations/spiders/waterstones.py
=> Fix waterstones

locations/linked_data_parser.py, tests/test_ld_parser.py
=> Clean LinkedDataParser coords

locations/spiders/spar_nl.py
I need help with this one, I'm using SitemapSpider x StructuredDataSpider but its not managing to get the coordinates. Even though I see them available it doesn't seem able to extract them. I even tried to force set them in `post_process_item` but doesn't work
=> feat: Spar NL

locations/spiders/vancouver_coastal_health.py
a) The old spider seemed to picking up services vs locations, hence the count difference
b) Someone else is gonna have to finish the categories, health care isn't my strong point.
=> Fix Vancouver Coastal Health Spider

locations/spiders/f24.py, locations/spiders/okq8.py, locations/spiders/q8.py, locations/spiders/q8_italia.py
Rel https://github.com/alltheplaces/alltheplaces/pull/4848#issuecomment-1438804346
I don't like this brand, its sub brands or its APIs.
=> Add Q8 Spiders

locations/spiders/guess.py
We were crashing on a few broken redirects.
=> Fix Guess crashes

locations/spiders/gamma.py
=> Use better Gamma API

locations/spiders/screwfix_gb.py
=> Fix broken Screwfix spider

locations/spiders/albert_heijn.py
1120 stores returned of which 73 are BE and 1047 are NL.
=> albert_heijn: fix spider

locations/spiders/apple.py
Starting @Cj-Malone 's wishlist #4878
=> feat: Apple Update

locations/categories.py, locations/spiders/albert_and_walter.py
Add wikidata (And category)
Fix opening hours
Add website
=> Clean up Albert And Walter Spider

locations/spiders/truevalue.py, locations/structured_data_spider.py
The sitemap returns an incomplete XML.
=> Fix TrueValue spider. 

locations/spiders/scapino_nl.py
=> feat: add new spider for scapino_nl

locations/spiders/caffe_nero_gb.py
=> Add Caffe Nero GB Spider

.github/workflows/pytest-pr.yaml, locations/pipelines.py, locations/spiders/suzuki_be.py, tests/test_pipeline_phone_cleanup.py
I noticed that the phone numbers in #4912 were not getting parsed properly. I'm adding a test here to see why.
=> Add a test for Belgium phone number cleanup

locations/spiders/kwantum.py
Rel https://github.com/osmlab/name-suggestion-index/pull/7796
=> Add Kwantum Spider

locations/spiders/mcdonalds.py
=> Collect mcdonalds drive through details

locations/spiders/sonic_drivein.py
=> Modernise Sonic Drive-In

locations/spiders/muffin_break_au.py
Depends on https://github.com/alltheplaces/alltheplaces/pull/4893 as the opening hours for this store are very messy and include multiple formatting styles, day ranges, some typos, etc.
=> Add Muffin Break (AU) (173 stores)

locations/spiders/middys_au.py
Corresponding NSI changes (already merged) are https://github.com/osmlab/name-suggestion-index/pull/7882
=> Add Middy's (AU) (109 stores)

locations/spiders/ferguson_plarres_bakehouse_au.py
Corresponding NSI change that will add categories: https://github.com/osmlab/name-suggestion-index/pull/7881
=> Add Ferguson Plarre's Bakehouse (AU) (84 stores)

locations/spiders/night_owl_au.py
Rel https://github.com/osmlab/name-suggestion-index/pull/7889
=> Add NightOwl Spider

locations/commands/insights.py
Usage: `scrapy insights --html-encoding file/files`
Rel #5022
=> Add html encoding check to scrapy insights

locations/pipelines.py
E.Leclerc wasn't getting a country because it's using `WoosmapSpider` which sets `geometry` not `lat`/`lon`. Without a country it's phone numbers weren't being formatted properly either.
I'd also like to turn `skip_auto_cc` into a more fine grain option. I added it because there was some issues with getting the country from the TLD (eg IE data on .co.uk domain). It'd be better to just be able to disable that, and still use the geocoder. Maybe `skip_auto_cc_domain`? + `skip_auto_cc_spider_name` + `skip_auto_cc_geocoder`. Opinions?
=> Use geometry for geocoding when available

locations/spiders/soul_origin_au.py
Rel https://github.com/osmlab/name-suggestion-index/pull/7895
=> Add Soul Origin AU Spider

locations/spiders/caribou_coffee.py
=> Modernise Caribou Coffee

locations/categories.py, locations/spiders/exxonmobil.py, tests/test_categories.py
Drop the weird shrinking bbox, gain a multitude of API endpoints, and collect some more countries. Replaces #4974
Somebody else may want to finish the fuel types. Until a few weeks ago I though there were 2 types: Petrol and Diesel.
```python
{'atp/brand/Esso': 8970,
'atp/brand/Exxon': 6536,
'atp/brand/Mobil': 6093,
'atp/brand_wikidata/Q109675651': 6536,
'atp/brand_wikidata/Q109676002': 6093,
'atp/brand_wikidata/Q867662': 8970,
'atp/category/amenity/fuel': 21661,
'atp/field/brand/missing': 62,
'atp/field/brand_wikidata/missing': 62,
'atp/field/country/from_website_url': 39,
'atp/field/email/missing': 21661,
'atp/field/image/missing': 21661,
'atp/field/lon/invalid': 7,
'atp/field/phone/invalid': 48,
'atp/field/phone/missing': 2330,
'atp/field/postcode/missing': 42, …
```
=> Expand ExxonMobil Spider to more countries

locations/spiders/specsavers_nl.py
The brand has changed their website (making XPath extraction difficult) but they have now introduced structured data, so this is an easy fix.
=> specsavers_nl: fix spider and convert to structured data

locations/spiders/bashas.py, locations/spiders/bootbarn.py, locations/spiders/brueggers.py, locations/spiders/crackerbarrel.py, locations/spiders/einsteinbros.py, locations/spiders/gbfs.py, locations/spiders/gelsons.py, locations/spiders/ingles.py, locations/spiders/manhattanbagel.py, locations/spiders/noahsnybagels.py, locations/spiders/staples.py, locations/spiders/whitecastle.py
Identified with `git grep -E '"%H:%M\s?%p"'`, I've tested these, the one that remains is a broken spider.
=> Fix 12h times being parsed as 24h

locations/spiders/the_good_guys_au.py
Rel: https://github.com/alltheplaces/alltheplaces/commit/18cb00a222aa5d05ed812e090e0a00e6822c50c1#r106280672
=> Revert to old The Good Guys oh method

locations/spiders/bestwestern.py
how to add a delay between requests to avoid CAPTCHA?
=> feat: bestwestern world

locations/spiders/target_au.py
It was crashing on the http2 handler, I guess something changed with an old scrapy release? Anyway, it works with a fake useragent alone now.
=> Fix target_au

locations/dict_parser.py, locations/spiders/ship_and_go_ro.py
Rel: https://github.com/osmlab/name-suggestion-index/issues/7502
=> Add Ship & Go parcel lockers

locations/spiders/journeys.py
Expand to CA
Fix opening hours, which were failing to null.
Add category
Convert to StructuredDataSpider
=> Modernise Journeys

locations/spiders/carrefour_fr.py
Rel: https://github.com/osmlab/name-suggestion-index/commit/4ee650b28bbda87368d33223b5c052d71fc295ed https://github.com/osmlab/name-suggestion-index/commit/af8e80de2aa744acbe746ae9db4627add66ddd9e
=> Improve carrefour_fr brands and categories

locations/categories.py, locations/spiders/petstock_au.py
'atp/brand/Best Friends': 30,
'atp/brand/FurLife': 2,
'atp/brand/My Pet Warehouse': 13,
'atp/brand/Petstock': 222,
'atp/category/amenity/veterinary': 26,
'atp/category/shop/pet': 241,
=> Add Petstock brands (AU) (267 stores)

locations/spiders/greencross_au.py
'atp/brand/City Farmers': 16,
'atp/brand/Greencross Vets': 93,
'atp/brand/Petbarn': 209,
'atp/category/amenity/animal_boarding': 9,
'atp/category/amenity/veterinary': 135,
'atp/category/amenity/veterinary;animal_boarding': 8,
'atp/category/multiple': 97,
'atp/category/shop/pet': 123,
'atp/category/shop/pet;pet_grooming': 43,
=> Add Greencross brands (AU) (319 stores)

locations/spiders/matalan_gb.py, locations/storefinders/yext.py
=> matalan_gb: fix spider

locations/spiders/costacoffee_us.py
=> costacoffee_us: fix spider

locations/spiders/update_fitness_ch.py
Rel: https://github.com/osmlab/name-suggestion-index/issues/7953
=> Add update Fitness Spider

locations/spiders/america_today.py
Rel https://github.com/osmlab/name-suggestion-index/pull/7884
=> Add America Today Spider

locations/spiders/paper_source_us.py
Paper Source returns 125 stores, with partial information returned via Amasty Store Finder API and the bulk of information returned via XPath query of the website of each store.
=> paper_source_us: fix spider

Pipfile.lock
This started as an attempt to resolve a security issue (https://nvd.nist.gov/vuln/detail/CVE-2017-14158) with Scrapy, but it hasn't been resolved yet (see https://github.com/scrapy/scrapy/issues/482), so I'm just updating other dependencies instead.
=> pipenv update

locations/spiders/santander_pl.py
Rel https://github.com/osmlab/name-suggestion-index/issues/7944
=> Add Santander PL Spider

locations/spiders/black_sheep_coffee.py, locations/storefinders/yext.py
https://github.com/osmlab/name-suggestion-index/pull/7964
=> Add Black Sheep Coffee Spider

locations/spiders/geox.py
For some reason gives us ~10 more POIs
=> Move Geox Spider to international API

locations/spiders/storebox.py
Rel: https://github.com/osmlab/name-suggestion-index/pull/7966
=> Add Storebox Spider

locations/spiders/eldi_be.py, locations/storefinders/amasty_store_locator.py
Rel https://github.com/osmlab/name-suggestion-index/pull/7972
=> Add Eldi BE Spider

locations/spiders/continente_pt.py
Rel https://github.com/osmlab/name-suggestion-index/pull/7986
=> Add Continente Spider

locations/google_url.py, locations/spiders/baby_bunting.py, locations/spiders/banfield_pet_hospital.py, locations/spiders/baptist_health_arkansas.py, locations/spiders/bar_and_block_gb.py, locations/spiders/barmethod.py, locations/spiders/barnesandnoble_college.py, locations/spiders/bass_pro_shops.py, locations/spiders/bassett_furniture.py, locations/spiders/bayshore_healthcare.py, locations/spiders/bc_pizza.py, locations/spiders/bed_bath_beyond.py, locations/spiders/bestbuy.py, locations/spiders/bestbuy_ca.py, locations/spiders/biggby.py, locations/spiders/bjswholesale.py, locations/spiders/bloomingdales.py, locations/spiders/bluerhino.py, locations/spiders/bostonpizza.py, locations/spiders/bq.py, locations/spiders/brandywine_living.py, locations/spiders/buffalo_wild_wings.py, locations/spiders/busy_beaver.py
=> Clean up addr_full

locations/spiders/ecco.py
Fixes some comments I had on #5142
=> Directly add Ecco opening times

locations/spiders/eyes_and_more.py
Rel https://github.com/osmlab/name-suggestion-index/pull/7969
=> Add eyes + more Spider

locations/spiders/pearle_studio_nl.py
Rel https://github.com/osmlab/name-suggestion-index/pull/7969
=> Add Pearle Studio NL Spider

locations/spiders/charge_your_car_gb.py
=> Add Charge Your Car GB Spider

locations/spiders/pod_point.py
=> Add Pod Point Spider

locations/spiders/osprey_gb.py
Rel https://github.com/osmlab/name-suggestion-index/commit/337a5162490fa93a2659517272e3483a8a2c501a
@rjw62
=> Add Osprey GB Spider

locations/spiders/insta_volt_gb.py
=> Add InstaVolt GB Spider

locations/spiders/gridserve_gb.py
=> Add Gridserve GB Spider

locations/spiders/fastned.py
@rjw62 only a few in GB so probably not worth your time
=> Add Fastned Spider

locations/categories.py, locations/spiders/genie_point_gb.py
=> Add GeniePoint GB Spider

locations/spiders/calvin_klein_ca_us.py
Commit 1bf9caadafbe3d27f47006beaa6164dd9b90cba6 should have updated this spider, but it was forgotten.
Also fix the name of the spider to match the filename.
=> calvin_klein_ca_us: fix spider

locations/spiders/the_north_face_eu.py
This spider should have been updated with commit
1bf9caadafbe3d27f47006beaa6164dd9b90cba6 but was forgotten by accident.
=> the_north_face_eu: fix spider

locations/spiders/extreme_intimo.py, locations/spiders/jasmil.py
Rel https://github.com/osmlab/name-suggestion-index/pull/7923
=> Add Jasmil and Extreme Intimo Spiders

locations/spiders/charge_place_scotland_gb.py
@rjw62 another one for you please.
=> Add ChargePlace Scotland Spider

locations/spiders/bre_wingz.py, locations/spiders/bucees_us.py, locations/spiders/busy_beaver.py, locations/spiders/carpet_court_nz.py, locations/spiders/curves_nl.py, locations/spiders/food_city_us.py, locations/spiders/footgear_za.py, locations/spiders/intersport_au.py, locations/spiders/lundsandbyerlys.py, locations/spiders/smilebrands.py, locations/spiders/soul_pattinson_chemist_au.py, locations/spiders/superconti_it.py, locations/storefinders/wp_store_locator.py
=> Add WP Store Locator base spider

locations/spiders/aristocrazy.py
Rel: https://github.com/osmlab/name-suggestion-index/pull/8015
=> Add Aristocrazy Spider

locations/dict_parser.py, locations/spiders/ampol_au.py
'atp/brand/Ampol': 761,
'atp/brand/Ampol Foodary': 553,
'atp/brand/EG Ampol': 528,
=> Add Ampol (AU) (1842 locations)

locations/spiders/leightons_gb.py
Rel: https://github.com/osmlab/name-suggestion-index/commit/80f0d9bfbd8464e92fbb610001ad55db09d09b6d
=> Add Leightons GB Spider

locations/spiders/fossil.py
=> Add Fossil (Worldwide) (311 stores)

locations/spiders/dexy_rs.py, locations/structured_data_spider.py
Rel: https://github.com/osmlab/name-suggestion-index/pull/7766
=> Add Dexy RS Spider

locations/spiders/poundland.py
=> Fix Poundland address

locations/google_url.py
Some initial steps to address #5234.
=> Safer checks on URL parameters to capture more locations and avoid errors

locations/spiders/neuhaus.py
Rel https://github.com/osmlab/name-suggestion-index/pull/8067
=> Add Neuhaus Spider

locations/spiders/fiesta_mart_us.py, locations/spiders/fiestamart.py
Rel https://github.com/osmlab/name-suggestion-index/commit/213b61f7b4ce2ef8ce0a2025bb34796dae6f3af6
=> Add wikidata to Fiesta Mart US Spider

locations/spiders/waterstones.py, locations/structured_data_spider.py
The updated extraction and cleaning functions came from my adventures [crawling the wild internet](https://maproulette.org/browse/challenges/38762), but I'm sure they'll help here.
=> Collect Waterstones social media accounts

locations/spiders/dangelos_us.py
Rel: https://github.com/osmlab/name-suggestion-index/pull/8101
=> Add Dangelos US Spider

locations/spiders/yha_gb.py
Rel: https://github.com/osmlab/name-suggestion-index/commit/3851cd65104f2561358173f11b3a7de355f7a4a6
=> Add YHA GB Spider

locations/spiders/fast_shift_am.py
Rel: https://github.com/osmlab/name-suggestion-index/pull/8130
=> Add Fast Shift AM Spider

.github/workflows/docker-publish.yml, ci/run_all_spiders.sh
For #5261 
What if we disable requests_cache during scrapy list?
=> Dont use requests cache on list

locations/dict_parser.py, locations/spiders/just_group.py
'atp/brand/Dotti': 105,
'atp/brand/Jacqui E': 95,
'atp/brand/Jay Jays': 200,
'atp/brand/Just Jeans': 235,
'atp/brand/Peter Alexander': 125,
'atp/brand/Portmans': 91,
'atp/brand/Smiggle': 305,
=> Add Just Group (AU/NZ/GB/SG/MY/IE) (1156 stores)

locations/spiders/sun_auto_service_us.py
Rel: https://github.com/osmlab/name-suggestion-index/issues/8144
=> Add Sun Auto Service US Spider

locations/spiders/good_2_go_stores_us.py
=> Add Good 2 Go Stores Spider

locations/spiders/fountain_tire_ca.py
Rel: https://github.com/osmlab/name-suggestion-index/issues/8134
=> Add Fountain Tire CA Spider

locations/spiders/kreatos_be.py
Rel: https://github.com/osmlab/name-suggestion-index/pull/8148
=> Add Kreatos BE Spider

locations/spiders/aje.py
'atp/brand/AJE': 24,
'atp/brand/Aje Athletica': 14,
=> Add Aje and Aje Athletica (AU/NZ) (38 stores)

locations/commands/insights.py
During the weekly run that I kicked off, I saw this error:
```
--
File "/home/ubuntu/.pyenv/versions/3.10.11/bin/scrapy", line 8, in <module>
sys.exit(execute())
File "/home/ubuntu/.pyenv/versions/3.10.11/lib/python3.10/site-packages/scrapy/cmdline.py", line 158, in execute
_run_print_help(parser, _run_command, cmd, args, opts)
File "/home/ubuntu/.pyenv/versions/3.10.11/lib/python3.10/site-packages/scrapy/cmdline.py", line 111, in _run_print_help
func(*a, **kw)
File "/home/ubuntu/.pyenv/versions/3.10.11/lib/python3.10/site-packages/scrapy/cmdline.py", line 166, in _run_command
cmd.run(args, opts)
File "/home/ubuntu/locations/commands/insights.py", line 99, in run
self.analyze_atp_nsi_osm(args, opts.outfile)
File …
```
=> Use pagination to fetch Taginfo counts

locations/spiders/camping_world_us.py, locations/spiders/campingworld.py
This adds a spider for Camping World locations via https://rv.campingworld.com/locations
=> Add Camping World spider

locations/spiders/interparking_be.py
Rel: https://github.com/osmlab/name-suggestion-index/pull/8161
=> Add Interparking BE Spider

locations/spiders/landmark_cinemas_ca.py
Rel: https://github.com/osmlab/name-suggestion-index/pull/8165
=> Add Landmark Cinemas CA Spider

locations/spiders/toolstation.py
Fixes #5310 
I've left this as 1 spider as I think it's reasonably likely the other countries will convert to the new format. Otherwise I would argue they should be split into multiple spiders.
=> Fix Toolstation Spider in GB

locations/categories.py, locations/spiders/australia_post_au.py, locations/spiders/fitness_first_au.py, locations/spiders/jamaica_blue_au.py, locations/spiders/jaycar_au.py, locations/spiders/telstra_au.py, locations/spiders/vapestore_gb.py
@davidhicks hopefully these help you, I'll probably do some more over the weekend, or Monday if not.
=> Add some upside down spiders

locations/spiders/petsathome_gb.py, locations/structured_data_spider.py
Partial fix in #5309 as the website is causing issues.
@rjw62 I think the only missing POI is [Guernsey](https://community.petsathome.com/store/guernsey/), but overall this should be better for the Chain Reaction.
=> Skip Pets at Home web crawl

locations/spiders/denizbank.py
Now name comes from source data (https://github.com/alltheplaces/alltheplaces/pull/5324).
=> denizbank_tr: parsed names

locations/spiders/gloria_jeans_coffees_au.py
@tijmensmit it would be awesome if there was a way locations out of WP Store Locator without lat/lon searches.
=> Add Gloria Jeans Coffees AU Spider

locations/spiders/pur_and_simple_ca.py
Rel: https://github.com/osmlab/name-suggestion-index/pull/8192
=> Add Pür & Simple CA Spider

locations/spiders/turkiye_is_bankasi.py
```
{'atp/brand/Türkiye İş Bankası': 5819,
'atp/brand_wikidata/Q909613': 5819,
'atp/category/amenity/atm': 4705,
'atp/category/amenity/bank': 1114,
'atp/field/city/missing': 122,
'atp/field/country/from_spider_name': 111,
'atp/field/email/missing': 5819,
'atp/field/image/missing': 5819,
'atp/field/opening_hours/missing': 5819,
'atp/field/phone/invalid': 23,
'atp/field/phone/missing': 4705,
'atp/field/postcode/missing': 5817,
'atp/field/state/missing': 5819,
'atp/field/street_address/missing': 5819,
'atp/field/twitter/missing': 5819,
'atp/field/website/missing': 5819,
'atp/nsi/category_match': 5697,
'atp/nsi/match_failed': 122,
'downloader/request_bytes': 82379,
'downloader/request_count': 90,
'downloader/request_method_count/POST': 88, …
```
=> Add Turkiye Is Bankasi (5819 locations)

locations/spiders/mountain_equipment_company_ca.py, locations/structured_data_spider.py
Rel: https://github.com/osmlab/name-suggestion-index/pull/8090
I've also rearranged StructuredDataSpider so we aren't parsing every `//script[@type="application/ld+json"]` 18 times per POI.
=> Add Mountain Equipment Company CA Spider

locations/spiders/condado_tacos_us.py
Rel: https://github.com/osmlab/name-suggestion-index/commit/eb8ab01ce7626716d6a1469605ba503c7f0091d8
=> Fix and rename Condado Tacos US Spider

locations/spiders/sonic_ca.py
Rel: https://github.com/osmlab/name-suggestion-index/commit/9ac3b7004e95fa2e0e54c30fcbf87b8f18be1e7c
=> Add Sonic CA Spider

locations/spiders/sizzler.py
81 locations returned which plausibly seems to be accurate vs. 84 locations returned at the start of April using the previous spider.
=> sizzler: fix spider

locations/spiders/choice_hotels.py
Rel: https://github.com/alltheplaces/alltheplaces/issues/5354
=> Update Choice Hotels brands and categories

locations/categories.py, locations/spiders/e_leclerc.py
Rel: https://github.com/osmlab/name-suggestion-index/commit/f28b6284aca2226af1c1a2b3296a1e621292b15d
=> Add E.Leclerc categories

.github/workflows/docker-publish.yml, Dockerfile, ci/run_all_spiders.sh
=> Try baking the git commit into the image and write it out during CI

.github/workflows/docker-publish.yml
=> Allow manual execution of Docker publish

Pipfile, Pipfile.lock
=> Explicitly include exceptiongroup in Pipfile

locations/spiders/oggi_sorvetes_br.py
Rel: https://github.com/osmlab/name-suggestion-index/commit/c4ddfc388fe6e405d8580428ded3f7d243c28f5d
=> Add Oggi Sorvetes BR Spider

locations/spiders/pod_point.py
The newest release of chompjs falls over on large blobs... This looks like the only spider with issue in the last run though.
=> Fix Pod Point Spider

locations/spiders/bunnings.py
=> bunnings: fix parsing error in opening hours

locations/spiders/enterprise.py
Returns 7304 locations vs. 7313 the last time this spider was properly working, thus it looks OK.
Fixes #5312
=> enterprise: fix spider

locations/spiders/choice_hotels.py
Make selecting the "property" more reliable
=> Fix Choice Hotels Spider

locations/spiders/pharmasave_au.py
=> Add PharmaSave (AU) (50 stores)

locations/spiders/ufs_au.py
=> Add UFS (AU) (21 stores)

locations/spiders/pharmacy_4_less_au.py
=> Add Pharmacy 4 Less (AU) (63 stores)

locations/spiders/carrefour_it.py
'atp/brand/Carrefour Express': 702,
'atp/brand/Carrefour Iper': 46,
'atp/brand/Carrefour Market': 287,
=> Add Carrefour brands (IT) (1035 stores)

locations/spiders/brico_io_it.py
Opening hours data format has changed.
=> brico_io_it: fix spider

locations/spiders/carrefour_tw.py
'atp/brand/Carrefour': 68,
'atp/brand/Carrefour Market': 246,
=> Add Carrefour brands (TW) (314 stores)

locations/spiders/regal_theaters.py
Uses Cloudflare to restrict access to US clients only.
=> regal_theaters: georestricted to US

locations/spiders/universal_store_au.py
'atp/brand/Perfect Stranger': 6,
'atp/brand/Universal Store': 77,
=> Add Universal Store brands (AU) (83 stores)

locations/commands/insights.py
A relation to https://github.com/alltheplaces/alltheplaces.xyz/pull/35
The insights.json was showing NSI brand and NSI description fields but there were in fact wikidata label and description fields.
This PR with its friend corrects the misnaming from the insights command and makes sure a "nsi_brand" field in insights.json is populated where possible.
=> ensure that NSI brand in insights JSON is correct

locations/spiders/minerd_do.py
Fixes #5481
```python
{'atp/category/amenity/school': 10365,
'atp/field/brand/missing': 10365,
'atp/field/brand_wikidata/missing': 10365,
'atp/field/city/missing': 10365,
'atp/field/country/from_spider_name': 10365,
'atp/field/email/missing': 10365,
'atp/field/image/missing': 10365,
'atp/field/opening_hours/missing': 10365,
'atp/field/phone/missing': 10365,
'atp/field/postcode/missing': 10365,
'atp/field/state/missing': 10365,
'atp/field/street_address/missing': 10365,
'atp/field/twitter/missing': 10365,
'atp/field/website/missing': 10365,
'downloader/request_bytes': 2402,
'downloader/request_method_count/POST': 3,
'downloader/response_bytes': 4574100, …
```
=> Add Minerd DO Spider

locations/spiders/dixy_ru.py
```
{'atp/brand/Дикси': 2215,
'atp/brand_wikidata/Q4161561': 2215,
'atp/category/shop/supermarket': 2215,
'atp/field/country/from_spider_name': 2215,
'atp/field/email/missing': 2215,
'atp/field/image/missing': 2215,
'atp/field/opening_hours/invalid': 1,
'atp/field/phone/missing': 2215,
'atp/field/postcode/missing': 2215,
'atp/field/state/missing': 2215,
'atp/field/twitter/missing': 2215,
'atp/field/website/missing': 2215,
'atp/nsi/perfect_match': 2215,
'downloader/request_bytes': 344,
'downloader/response_bytes': 1285324,
'elapsed_time_seconds': 3.442219, …
```
=> Add Dixy (RU) (2215 locations)

locations/spiders/burger_king_ru.py
Stats:
```
{'atp/brand/Бургер Кинг': 812,
'atp/brand_wikidata/Q177054': 812,
'atp/category/amenity/fast_food': 812,
'atp/field/city/missing': 812,
'atp/field/country/from_spider_name': 812,
'atp/field/email/missing': 812,
'atp/field/image/missing': 812,
'atp/field/phone/invalid': 10,
'atp/field/phone/missing': 22,
'atp/field/postcode/missing': 812,
'atp/field/state/missing': 812,
'atp/field/street_address/missing': 812,
'atp/field/twitter/missing': 812,
'atp/field/website/missing': 812,
'atp/nsi/cc_match': 812,
'downloader/request_bytes': 781,
'downloader/response_bytes': 595456, …
```
=> Add Burger King (RU) (812 locations)

Pipfile.lock
Trying to fix dockerfile not building.
=> Rebuild pipfile.lock with 3.11

locations/spiders/fantastiko_bg.py
=> Add Fantastiko BG Spider

locations/spiders/wards_restaurant_us.py
Rel: https://github.com/osmlab/name-suggestion-index/issues/8360
=> Add Ward's Restaurant US Spider

locations/spiders/easypay_bg.py
=> Add Easypay BG Spider

locations/spiders/metro_diner_us.py
Rel: https://github.com/osmlab/name-suggestion-index/pull/8372
=> Add Metro Diner US Spider

locations/spiders/hb1_pharmacy_ph.py
Rel: https://github.com/osmlab/name-suggestion-index/pull/8350
=> Add HB1 Pharmacy PH Spider

locations/spiders/ultra_tune_au.py
Rel: https://github.com/osmlab/name-suggestion-index/pull/8306
=> Add Ultra Tune AU Spider

locations/spiders/big_w_au.py
A new JSON blob format is now used.
=> big_w_au: fix spider

locations/spiders/nsw_state_emergency_service_au.py
'atp/category/amenity/rescue_station': 262,
'atp/category/emergency/water_rescue': 52,
'atp/category/office/government': 11,
=> Add NSW State Emergency Service (AU) (325 locations)

locations/spiders/max_and_co.py
Rel: https://github.com/osmlab/name-suggestion-index/pull/8384
=> Add MAX&Co. Spider

locations/spiders/retail_apparel_group.py
'atp/brand/Connor': 188,
'atp/brand/Johnny Bigg': 77,
'atp/brand/Rockwear': 73,
'atp/brand/Tarocash': 116,
'atp/brand/yd.': 100,
=> Add Retail Apparel Group (AU/NZ) (554 stores)

locations/__init__.py, locations/extensions.py
This makes the `LOGSTATS_FILE` export closer to the dump we see at the end of the run.
=> Improve exported stats readablilty

locations/spiders/electrify_america.py
Multiple NSI entries, so set category.
WAS:
{'atp/brand/Electrify America': 881,
'atp/brand_wikidata/Q59773555': 881,
'atp/category/missing': 881,
'atp/field/email/missing': 881,
'atp/field/image/missing': 881,
'atp/field/opening_hours/missing': 881,
'atp/field/phone/missing': 881,
'atp/field/street_address/missing': 881,
'atp/field/twitter/missing': 881,
'atp/field/website/missing': 881,
'atp/nsi/match_failed': 881,
NOW:
{'atp/brand/Electrify America': 881,
'atp/brand_wikidata/Q59773555': 881,
'atp/category/amenity/charging_station': 881,
'atp/field/email/missing': 881,
'atp/field/image/missing': 881, …
=> Fix category for Electrify America

locations/spiders/adairs.py
Removes errors and now returns full 171 expected locations.
=> adairs: fix hours extraction

locations/hours.py, locations/spiders/teremok_ru.py
```
{'atp/brand/Теремок': 329,
'atp/brand_wikidata/Q4455593': 329,
'atp/category/amenity/fast_food': 329,
'atp/field/country/from_spider_name': 329,
'atp/field/email/missing': 329,
'atp/field/image/missing': 329,
'atp/field/phone/missing': 329,
'atp/field/postcode/missing': 329,
'atp/field/state/missing': 329,
'atp/field/street_address/missing': 329,
'atp/field/twitter/missing': 329,
'atp/nsi/perfect_match': 329,
'downloader/request_bytes': 1829,
'downloader/response_bytes': 49593,
'downloader/response_count': 5,
'downloader/response_status_count/200': 5,
'elapsed_time_seconds': 5.990802,
'finish_time': …
```
=> Add Teremok (RU) (329 locations).

locations/dict_parser.py, locations/spiders/kfc_amrest.py
AmRest is an operator of the KFC brand in multiple european countries. They appear to be using one system across multiple countries. This spider scraapes loctions in Poland, Hungary, Czechia, Croatia and Serbia.
See: https://www.amrest.eu/en/our-brands (not all countries they work in have the same system so I have omitted them, French and Spanish website display "Forbidden" for me so I did not check them)
=> Add KFC AmRest spider (~427 locations)

locations/spiders/orlen.py
A big Polish energy conglomerate. Owns multiple brands across central europe, which are available via their website.
=> Add Orlen spider (~2941 gas stations)

locations/spiders/dr_max.py
Pharmacy chain in Poland, Czechia, Slovakia and Italy.
=> Add Dr. Max spider (~974 pharmacies)

locations/pipelines/phone_clean_up.py, locations/spiders/ameriprise.py, locations/spiders/ameriprise_us.py, tests/test_pipeline_phone_cleanup.py
Don't convert {"fax":None} to the string 'None'.
=> Add spider for Ameriprise

locations/spiders/cue.py, locations/spiders/godfathers_pizza.py, locations/spiders/quick_be_lu.py, locations/spiders/ucla_health.py, locations/spiders/z_energy_nz.py
Rel: https://github.com/alltheplaces/alltheplaces/issues/5598#issuecomment-1659907080
=> Ensure string postcode

locations/exporters/geojson.py, locations/exporters/ld_geojson.py, locations/exporters/osm.py, locations/settings.py, tests/test_exporters.py
I wont feel bad if you don't want to merge this. I don't really want anyone to use it. I've added `upload=never` to stop JOSM uploading these files, but obviously someone can remove that. Also people could upload the GeoJSON, so we can't actually stop people doing stupid things.
My problem is, loading GeoJSON into JOSM is broken. If there are 2 or more points with the same coords, they get merged into one node.
=> Add OSM XML Exporter

locations/spiders/frittenwerk_de.py
Rel: https://github.com/osmlab/name-suggestion-index/pull/8470
=> Add Frittenwerk DE Spider

locations/structured_data_spider.py
Website parses as an empty list, so handle this edge case
=> Fix home_bargains_gb website errors via StructuredDataSpider

locations/spiders/marionnaud.py
https://github.com/osmlab/name-suggestion-index/pull/8490
=> Add Marionnaud spider

locations/spiders/city_electric_supply.py
Rel: https://github.com/osmlab/name-suggestion-index/commit/4a45cfbdfa057fed91fdf08a0e5fee522aee3a8f
=> Add City Electric Supply Spider

locations/spiders/chemist_warehouse_au.py
Residential IP addresses appear to be required. Data centre IP addresses (at least those I've tried) appear to be blocked.
=> chemist_warehouse_au: add requires_proxy

locations/spiders/kaisercraft_au.py
Reference: https://changelog.shopify.com/posts/changes-to-asset-urls
=> kaisercraft_au: use new URL

locations/spiders/tiger_wheel_and_tyre_za.py
Some of the fields in the JSON response message for store locations have been removed.
=> tiger_wheel_and_tyre_za: fix spider

locations/spiders/favorite_chicken_gb.py
Rel: https://github.com/osmlab/name-suggestion-index/pull/8498
=> Add Favorite Chicken GB Spider

locations/spiders/cigusto_fr.py
https://github.com/osmlab/name-suggestion-index/commit/faae5e0a5065e35c537aaaa7c5ee5e343dfd2b7d
=> Add Cigusto FR Spider

locations/spiders/las_iguanas_gb.py
Rel: https://github.com/osmlab/name-suggestion-index/pull/8512
=> Add Las Iguanas GB Spider

locations/spiders/team_sport_gb.py
Rel: https://github.com/osmlab/name-suggestion-index/pull/8512
=> Add Team Sport GB Spider

locations/exporters/geojson.py
=> Add start time to the exported data

locations/spiders/bp_pulse_gb.py
=> bp_pulse_gb: fix spider

locations/categories.py, locations/spiders/gap_us.py, locations/spiders/hugoboss.py
Modernise spider, fixing it in the process so that all 1729 locations are returned.
Re-use the clothes categories implemented in 'gap_us'.
=> hugoboss: fix spider and rename to hugo_boss

locations/spiders/noriel_ro.py
Rel: https://github.com/osmlab/name-suggestion-index/pull/8520
=> Add Noriel RO Spider

locations/spiders/cineworld_gb.py, locations/spiders/cineworld_gb_je.py
Unfortunately this seems to be blocked from none GB ips.
=> Add Cineworld GB/JE Spider

locations/spiders/sweetfrog_us.py
=> Add sweetFrog (US) (218 stores)

locations/spiders/winterthur_ch.py
* Update location of upstream data feed
* Import playground reference numbers for emergency calls
* Support newly added address tags
=> Change spider `winterthur_ch`

locations/spiders/champion.py, locations/spiders/champion_us.py
Rel: https://github.com/osmlab/name-suggestion-index/pull/8543
=> Add Champion Spiders

locations/spiders/czech_post_cz.py
So, this may or may not work. When I wrote this on Saturday it didn't (fixes #5701). But now it does ¯\\_(ツ)_/¯
I think it does something weird with cookies, so right now I just want to test on the CI to see what happens.
Also I asked someone to check the categories, so hopefully they have an opinion.
=> Add Czech Post CZ Spider

locations/spiders/giunti_al_punto_it.py
Rel: https://github.com/osmlab/name-suggestion-index/issues/8547
=> Add Giunti al Punto Spider

locations/spiders/techcombank_vn.py
Rel: https://github.com/osmlab/name-suggestion-index/issues/8550
=> Add Techcombank VN Spider

locations/spiders/baskin_robbins_us.py
=> Add Baskin Robbins US Spider

locations/spiders/visa.py
=> Add Visa Spider

locations/spiders/sleep_outfitters_us.py
Rel: https://github.com/osmlab/name-suggestion-index/pull/8565
=> Add Sleep Outfitters US Spider

locations/spiders/pjs_coffee_us.py
Rel: https://github.com/osmlab/name-suggestion-index/pull/8566
=> Add PJs Coffee US Spider

locations/spiders/access_storage_gb.py
Rel: https://github.com/osmlab/name-suggestion-index/commit/f042164843df2121a2e1b59e2783ac83516d5cc9
=> Add Access Storage GB Spider

locations/spiders/deka_lash.py
Rel: https://github.com/osmlab/name-suggestion-index/pull/8564
=> Add Deka Lash Spider

locations/hours.py, locations/spiders/foodtown_us.py
=> Add Foodtown (US) (64 stores)

locations/spiders/food_fair_market_us.py
=> Add Food Fair Market (US) (19 locations)

locations/spiders/ribcrib_us.py
=> Add RibCrib (US) (52 stores)

locations/spiders/black_sheep_coffee.py, locations/spiders/chick_fil_a.py, locations/spiders/citizens_us.py, locations/spiders/ibis_nl.py, locations/spiders/recipe_unlimited.py, locations/storefinders/yext.py
amenity/atm: 2831
amenity/bank: 1108
Fixes #1664
=> Add Citizens (US)

locations/spiders/independent_financial_us.py
amenity/atm: 85
amenity/bank: 92
Fixes #1031
=> Add Independent Financial (US)

locations/spiders/snap_fitness.py
=> Add Snap Fitness (worldwide) (1032 locations)

locations/spiders/cenex.py
We now have to talk about multiple categories on 1 POI. I know some OSM mappers map fuel stations and convenience stores as 1 POI, but the reality is, most of the time the shop has [separate brand](https://github.com/alltheplaces/alltheplaces/pull/5766) or opening hours, so it gets mapped as 2 pois. [blue is one POI, orange 2](https://overpass-turbo.eu/s/1zEl)
I think we need to consider `amenity=fuel`+`shop=convenience` an error. It breaks most OSM tooling (including us). Right now, I can accept `amenity=fuel`+`shop=yes`. I can argue `shop=yes` becomes an attribute of `amenity=fuel`, TBH, I don't agree, but it's not a fight I want to fight right now.
TL;DR I think the best solution is 2 branded POIs when possible ([separate …
=> [Cenex] Improve tagging

locations/spiders/arco.py
=> Improve Arco tagging

locations/spiders/holiday_stationstores_us.py
=> [HolidayStationstores] Improve tagging

locations/spiders/safeway.py
=> [Safeway] Improve tagging

locations/spiders/road_ranger_us.py
=> [RoadRangerUS] Fix spider

locations/spiders/pilot_flyingj.py
=> [PilotFlyingJ] Improve tagging

locations/categories.py, locations/spiders/phillips_66_conoco_76.py
Rel: https://github.com/alltheplaces/alltheplaces/pull/5764 https://github.com/alltheplaces/alltheplaces/pull/5767
=> [Phillips66Conoco76] Improve tagging

locations/categories.py, tests/test_categories.py
Rel: https://github.com/alltheplaces/alltheplaces/pull/5770#discussion_r1312291747
=> Add shop=yes test

locations/spiders/kocca_it.py
Rel: https://github.com/osmlab/name-suggestion-index/pull/8575
=> [KoccaIT] Add spider

locations/spiders/bremer_bank_us.py
Also: Do we prefer to consistently parse US states to abbreviations?
=> bremer_bank_us: Fix address, phone no. parsing

locations/commands/insights.py
The insights command is somewhat insistent on being given GeoJSON format files to work over. Still support that but also recognise that people may want to work with line delimited GeoJSON which is one of our supported output formats.
=> extend insights command to handle .ndgeojson format

locations/spiders/credit_mutuel_fr.py
Fixes (partially, doesn't include ATMs) #5779
=> Add Credit Mutuel (FR)

locations/spiders/sofology_gb.py
Rel: https://github.com/osmlab/name-suggestion-index/commit/5e034dc1060c1b7156b0deb8d7ce008a49177c7b
=> Add Sofology GB Spider

locations/spiders/dia_es.py
=> Add Dia (ES)

locations/categories.py, locations/spiders/gnp_it.py
Rel: https://github.com/osmlab/name-suggestion-index/issues/8278
=> Add GNP IT Spider

locations/spiders/waxing_the_city_us.py
Rel: https://github.com/osmlab/name-suggestion-index/pull/8577
=> Add Waxing The City US Spider

locations/spiders/barre3.py
https://github.com/osmlab/name-suggestion-index/pull/8590
=> Add Barre3 Spider

locations/spiders/box_now.py
=> Add Box Now (BG/GR/HR) (2156 locations)

locations/spiders/rompetrol.py
=> Add Rompetrol (BG/GE/MD/RO) (701 locations)

locations/spiders/bulgarian_posts_bg.py
=> Add Bulgarian Posts (BG) (3007 locations)

locations/spiders/dm.py
=> Update dm websites per country

.github/workflows/spider-pr.yaml, locations/middlewares/zyte_api_by_country.py, locations/settings.py, locations/spiders/caseys_general_store.py, locations/spiders/homedepot.py, locations/spiders/hyatt.py, locations/spiders/ihg_hotels.py, locations/spiders/marathon.py, locations/spiders/olivegarden.py, locations/spiders/walmart.py, locations/spiders/wyndham.py, tests/test_proxy_location.py
Rel: https://github.com/alltheplaces/alltheplaces/pull/5820#discussion_r1318709864
I actually don't have credentials, so I can't test this. I saw some spiders work on CI, if the secrets are in GitHub, this should work.
=> Add middleware proxy to honour requires_proxy

locations/storefinders/geo_me.py
Previously, a single duplicate search URL (e.g. caused when two locations had the same coordinates) would result in the spider stopping mid crawl. This is due to the duplicates filter never calling the function parsing the response, and thus no further URL was requested.
Fixes #5818
=> storefinders/geo_me: fix spider to return all locations

locations/spiders/terrible_herbst.py
Rel: #5764 
```json
{
"atp/brand/Terrible Herbst": 151,
"atp/brand_wikidata/Q7703648": 151,
"atp/category/amenity/fuel": 151,
"atp/field/email/missing": 151,
"atp/field/image/missing": 151,
"atp/field/lat/missing": 151,
"atp/field/lon/missing": 151,
"atp/field/opening_hours/missing": 151,
"atp/field/phone/missing": 10,
"atp/field/state/missing": 1,
"atp/field/street_address/missing": 151,
"atp/field/twitter/missing": 151,
"atp/field/website/missing": 151,
"atp/nsi/category_match": 151,
"downloader/request_bytes": 1238,
"downloader/request_count": 3,
"downloader/request_method_count/GET": 3,
"downloader/response_bytes": 12949,
"downloader/response_count": 3,
"downloader/response_status_count/302": 1, …
```
=> [Terrible Herbst] Refresh spider.

locations/spiders/leons_ca.py
Rel: https://github.com/osmlab/name-suggestion-index/pull/8624
=> Add Leons CA Spider

locations/spiders/samsonite_eu.py
Fixes #5840
I'd like @eisams to check the data on this one, if possible.
=> [samsonite_eu] Drop stockists

locations/spiders/murphy_usa_us.py
Similar to #5850.
```
"atp/category/missing": 1548,
```
=> [murphy_usa_us] Add category.

locations/spiders/madame_frigo_ch.py
Rel: https://github.com/osmlab/name-suggestion-index/pull/8649
=> Add Madame Frigo CH Spider

locations/spiders/santander_pl.py
=> Drop descriptive names from Santander PL Spider

locations/spiders/pepco.py
=> Add Pepco Spider

locations/spiders/castorama_pl.py
=> Add Castorama PL Spider

locations/spiders/lewiatan_pl.py
Fixes #5894
@matkoniecz NSI has this as convenience stores and supermarkets, can you see a way for us to tell from the data?
https://www.lewiatan.pl/api/stores
=> Add Lewiatan PL Spider

locations/spiders/ikea.py
Similar to #5850.
```json
{
"atp/brand/IKEA": 439,
"atp/brand_wikidata/Q54078": 439,
"atp/category/shop/furniture": 439,
"atp/cdn/akamai/response_count": 1,
"atp/cdn/akamai/response_status_count/403": 1,
"atp/field/city/missing": 1,
"atp/field/country/from_reverse_geocoding": 35,
"atp/field/email/missing": 439,
"atp/field/image/missing": 439,
"atp/field/opening_hours/missing": 4,
"atp/field/phone/missing": 439,
"atp/field/postcode/missing": 9,
"atp/field/state/from_reverse_geocoding": 16,
"atp/field/state/missing": 334,
"atp/field/street_address/missing": 1,
"atp/field/twitter/missing": 439,
"atp/field/website/missing": 2,
"atp/nsi/category_match": 333,
"atp/nsi/cc_match": 106,
"downloader/request_bytes": 41662,
"downloader/request_count": 50, …
```
=> [IKEA] add category.

locations/middlewares/playwright_middleware.py, locations/middlewares/zyte_api_by_country.py, locations/pipelines/country_code_clean_up.py, locations/pipelines/drop_logo.py, locations/settings.py
Mostly fixes #5882
Drops almost 90k images, keeps almost 300k. Based on the last weekly.
=> Add pipeline to drop logos

locations/categories.py, locations/spiders/total_energies.py
To be more in line with Total -> TotalEnergies rebranding: https://en.wikipedia.org/wiki/TotalEnergies#2021%E2%80%93present:_Rebranding_to_TotalEnergies
=> [TotalEnergies] Update brand names.

locations/spiders/rossmann_pl.py
=> Add Rossmann (PL) (1711 stores)

locations/spiders/delikatesy_centrum_pl.py
=> Add Delikatesy Centrum (PL) (1472 locations)

locations/spiders/wellsfargo.py
The spider scraped [0 POIs in last weekly run](https://data.alltheplaces.xyz/runs/2023-09-16-13-32-02/stats/wellsfargo.json).
```json
{
"atp/brand/Wells Fargo": 7192,
"atp/brand_wikidata/Q744149": 7192,
"atp/category/amenity/atm": 2638,
"atp/category/amenity/bank": 4347,
"atp/category/missing": 207,
"atp/field/city/missing": 206,
"atp/field/email/missing": 7192,
"atp/field/image/missing": 7192,
"atp/field/lat/missing": 206,
"atp/field/lon/missing": 206,
"atp/field/name/missing": 7192,
"atp/field/opening_hours/invalid": 1,
"atp/field/opening_hours/missing": 2868,
"atp/field/phone/missing": 206,
"atp/field/postcode/missing": 206,
"atp/field/state/missing": 206,
"atp/field/street_address/missing": 7192,
"atp/field/twitter/missing": 7192, …
```
=> [wellsfargo] Fix spider, scrape ATMs.

locations/hours.py, locations/spiders/lilly_rs.py
=> Add Lilly (RS)

locations/spiders/sdek.py
```json
{
"atp/brand/\u0421\u0414\u042d\u041a": 8058,
"atp/brand_wikidata/Q28665980": 8058,
"atp/category/amenity/parcel_locker": 3583,
"atp/category/amenity/post_office": 4475,
"atp/field/country/from_website_url": 8058,
"atp/field/email/invalid": 1,
"atp/field/email/missing": 3580,
"atp/field/image/missing": 8058,
"atp/field/name/missing": 8058,
"atp/field/phone/invalid": 144,
"atp/field/postcode/missing": 8058,
"atp/field/state/missing": 8058,
"atp/field/twitter/missing": 8058,
"atp/nsi/category_match": 4475,
"atp/nsi/match_failed": 3583,
"downloader/request_bytes": 15665397,
"downloader/request_count": 8060,
"downloader/request_method_count/POST": 8058,
"downloader/response_bytes": 7089788, …
```
=> Add Sdek spider (8k locations).

locations/spiders/lilly_bg.py
=> Add Lilly (BG) (113 stores)

locations/spiders/amcal_au.py
The "openstatus" field is actually a real time indicator of whether a store is open right now.
=> amcal_au: fix spider

locations/spiders/rompetrol.py
=> [Rompetrol] Namespace ref

locations/hours.py, locations/spiders/inpost_pl.py, tests/test_opening_hours.py
'atp/category/amenity/parcel_locker': 20992,
'atp/category/amenity/product_pickup': 3568,
Fixes #5912
=> Add InPost (PL) (24560 locations)

locations/spiders/giggling_squid_gb.py
Rel: https://github.com/osmlab/name-suggestion-index/pull/8692
=> Add Giggling Squid GB Spider

locations/spiders/ralph_lauren.py
So I need a proxy for this as well as slowing it down, but that's because I get redirected to the UK site. I think it will work without a proxy from US ips.
=> [RalphLauren] Fix spider

locations/spiders/mcdonalds_cz.py
```json
{
"atp/brand/McDonald's": 118,
"atp/brand_wikidata/Q38076": 118,
"atp/category/amenity/fast_food": 118,
"atp/cdn/cloudflare/response_count": 1,
"atp/cdn/cloudflare/response_status_count/200": 1,
"atp/field/country/from_spider_name": 118,
"atp/field/email/missing": 118,
"atp/field/image/missing": 118,
"atp/field/state/missing": 118,
"atp/field/twitter/missing": 118,
"atp/field/website/missing": 118,
"atp/nsi/category_match": 118,
"downloader/request_bytes": 378,
"downloader/response_bytes": 17698,
"elapsed_time_seconds": 1.361703, …
```
=> [mcdonalds_cz] Fix broken spider.

preview/index.html
Fixes https://github.com/alltheplaces/alltheplaces/issues/5952
=> Make preview map a bit easier to see on mobile

locations/spiders/24_hour_fitness.py, locations/spiders/gulf_pr_us.py
Also deleted the conditional for convenience store as all of the pois have gulf fuel. Thus I think the fuel station is more important category then the convenience store feature.
=> Added Fuel Station Category to Gulf Brand.

locations/spiders/a1_at.py
=> Add A1 (AT) (65 stores)

locations/spiders/zizzi_gb.py
=> [ZizziGB] Fix country code

locations/spiders/a1_hr.py
=> Add A1 (HR) (27 stores)

locations/spiders/a1_si.py
=> Add A1 (SI) (55 stores)

locations/hours.py, locations/spiders/a1_rs.py
=> Add A1 (RS) (56 stores)

locations/spiders/a1_mk.py
=> Add A1 (MK) (28 stores)

contrib/gen_overture2osm.py
Quick little script to convert https://wiki.openstreetmap.org/wiki/Overture_Categories into json.
=> Add script to fetch Overture tags

locations/spiders/yettel_hu.py
=> Add Yettel (HU) (131 stores)

locations/spiders/kik.py
=> kik: fix spider to include all locations globally

locations/spiders/mcdonalds_za.py
=> [McDonaldsZA] Fix spider

locations/spiders/mcdonalds_bg.py
Started to Parse Hours. But across the 44 items they are not very standard. Thus I left alone.
Also no Coordinates either.
=> [McDonaldsBG] Fixed Spider

locations/spiders/arnold_clark.py
NSI has car-rental and shop for this brand. I added a car shop category as each of the URLs in the sitemap are all find-a-dealer. 
```python
{'atp/brand/Arnold Clark': 195,
'atp/brand_wikidata/Q29344371': 195,
'atp/category/shop/car': 195,
'atp/field/country/from_reverse_geocoding': 195,
'atp/field/email/missing': 195,
'atp/field/twitter/missing': 195,
'atp/nsi/category_match': 195,
'downloader/request_bytes': 160768,
'downloader/request_count': 197,
'downloader/request_method_count/GET': 197,
'downloader/response_bytes': 4491845,
'downloader/response_count': 197,
'downloader/response_status_count/200': 197,
'elapsed_time_seconds': 239.22182,
'finish_time': …
```
=> Added Bank Category to Arnold Clark Brand

locations/spiders/chicos.py
Does not get added via NSI as there are Chico's and Chico's Off the Rack Brands with same county and QCode.
=> Added Shop=clothes Category tag to Chicos Brand

locations/spiders/odido_pl.py
=> Add Odido PL (1664 stores)

locations/spiders/good_lood_pl.py
=> Add Good Lood (PL) (35 stores)

locations/spiders/bealls_florida.py, locations/spiders/bealls_florida_us.py
=> Add BeallsFlorida spider

locations/spiders/orange_pl.py
```json
{
"atp/brand/Orange": 607,
"atp/brand_wikidata/Q1431486": 607,
"atp/category/shop/mobile_phone": 607,
"atp/field/email/missing": 607,
"atp/field/image/missing": 607,
"atp/field/state/missing": 607,
"atp/field/twitter/missing": 607,
"atp/nsi/category_match": 607,
"downloader/request_bytes": 486705,
"downloader/request_count": 1218,
"downloader/request_method_count/GET": 1218,
"downloader/response_bytes": 1842439,
"downloader/response_count": 1218,
"downloader/response_status_count/200": 1216,
"downloader/response_status_count/301": 1,
"elapsed_time_seconds": 750.452362,
"finish_time": "2023-10-10T16:44:10.699910", …
```
=> Add Orange (PL) (607 locations).

locations/categories.py, locations/spiders/bnp_paribas_bank_pl.py
```json
{
"atp/brand/BNP Paribas Bank Polska": 949,
"atp/brand/Euronet": 6935,
"atp/brand/Planet Cash": 4088,
"atp/brand_wikidata/Q117744569": 4088,
"atp/brand_wikidata/Q20744004": 949,
"atp/brand_wikidata/Q5412010": 6935,
"atp/category/amenity/atm": 11586,
"atp/category/amenity/bank": 386,
"atp/field/country/from_spider_name": 11972,
"atp/field/email/missing": 11586,
"atp/field/image/missing": 11972,
"atp/field/phone/missing": 11972,
"atp/field/state/missing": 11972,
"atp/field/twitter/missing": 11972,
"atp/field/website/missing": 11972,
"atp/nsi/category_match": 949,
"atp/nsi/perfect_match": 11023,
"downloader/request_bytes": 718,
"downloader/response_bytes": 451703, …
```
=> Add BNP Paribas (PL) (~12k locations).

locations/spiders/poczta_polska_pl.py
```json
{
"atp/brand/Poczta Polska": 6783,
"atp/brand_wikidata/Q168833": 6783,
"atp/category/amenity/post_office": 6783,
"atp/field/country/from_spider_name": 6783,
"atp/field/email/missing": 6783,
"atp/field/image/missing": 6783,
"atp/field/opening_hours/missing": 6783,
"atp/field/phone/invalid": 22,
"atp/field/phone/missing": 19,
"atp/field/twitter/missing": 6783,
"atp/field/website/missing": 6783,
"atp/nsi/category_match": 6783,
"downloader/request_bytes": 10724,
"downloader/request_count": 18,
"downloader/request_method_count/GET": 18,
"downloader/response_bytes": 8818792,
"downloader/response_count": 18,
"downloader/response_status_count/200": 18,
"elapsed_time_seconds": 26.243869,
"finish_reason": …
```
=> Add Poczta Polska (PL) (~7k locations).

locations/spiders/credit_agricole_pl.py, locations/spiders/tmobile_pl.py
Phone in bank office pois is always `19019` which is a hotline number.
=> Add Credit Agricole (PL) (~9k locations).

locations/spiders/i_and_g_brokers.py
Fixes #5916 
added custom spider for I&G Brokers.
=> added spider for I&G Brokers

locations/spiders/bricomarche_pl.py
Stats:
```json
{
"atp/brand/Bricomarch\u00e9": 196,
"atp/brand_wikidata/Q2925147": 196,
"atp/category/shop/doityourself": 196,
"atp/cdn/cloudflare/response_count": 2,
"atp/cdn/cloudflare/response_status_count/200": 2,
"atp/field/city/missing": 1,
"atp/field/country/from_spider_name": 196,
"atp/field/email/missing": 2,
"atp/field/image/missing": 196,
"atp/field/lat/missing": 2,
"atp/field/lon/missing": 2,
"atp/field/opening_hours/missing": 196,
"atp/field/phone/missing": 8,
"atp/field/postcode/missing": 1,
"atp/field/street_address/missing": 196,
"atp/field/twitter/missing": 196,
"atp/geometry/null_island": 1,
"atp/nsi/perfect_match": 196,
"downloader/request_bytes": 633,
"downloader/response_bytes": 18033, …
```
=> Add Bricomarche (PL) (196 locations).

locations/spiders/leroy_merlin_pl.py
Stats:
```json
{
"atp/brand/Leroy Merlin": 78,
"atp/brand_wikidata/Q889624": 78,
"atp/category/shop/doityourself": 78,
"atp/field/country/from_spider_name": 78,
"atp/field/email/missing": 78,
"atp/field/image/missing": 78,
"atp/field/opening_hours/missing": 78,
"atp/field/phone/missing": 3,
"atp/field/state/missing": 78,
"atp/field/twitter/missing": 78,
"atp/nsi/cc_match": 78,
"downloader/request_bytes": 339,
"downloader/response_bytes": 6245,
"elapsed_time_seconds": 1.395648,
"finish_time": "2023-10-11T13:22:18.505795",
"httpcompression/response_bytes": 48145, …
```
=> Add Leroy Merlin (PL) (78 locations).

locations/spiders/mail_boxes_etc_gb_ie.py
```python
{'atp/brand/Mail Boxes Etc.': 140,
'atp/brand_wikidata/Q92922921': 140,
'atp/category/amenity/post_office': 140,
'atp/field/country/from_reverse_geocoding': 140,
'atp/field/image/missing': 140,
'atp/field/opening_hours/missing': 140,
'atp/field/street_address/missing': 140,
'atp/nsi/brand_missing': 140,
'downloader/request_bytes': 699,
'downloader/response_bytes': 71316,
'elapsed_time_seconds': 3.354814,
'finish_time': datetime.datetime(2023, 10, 11, 17, 23, 1, …
```
=> Add post office category for MBE Brand

locations/spiders/quickchek_us.py
=> Add QuickChek (US) (convenience stores) (169 locations)

locations/spiders/bayshore_healthcare.py
```python
{'atp/brand/Bayshore Healthcare': 184,
'atp/category/amenity/clinic': 85,
'atp/category/amenity/pharmacy': 10,
'atp/category/missing': 5,
'atp/category/multiple': 95,
'atp/category/office/healthcare': 84,
'atp/field/brand_wikidata/missing': 184,
'atp/field/email/missing': 184,
'atp/field/image/missing': 184,
'atp/field/opening_hours/missing': 184,
'atp/field/phone/missing': 100,
'atp/field/twitter/missing': 184,
'downloader/request_bytes': 502,
'downloader/response_bytes': 15365,
'elapsed_time_seconds': 1.972079, …
```
=> Added category for different healthcare establishments under bayshore brand

locations/spiders/evereve_us.py
=> Add EVEREVE (US) (clothing store) (94 locations)

locations/spiders/dirt_cheap_us.py
=> Add Dirt Cheap (US) (65 locations)

locations/hours.py, locations/spiders/sobeys_ca.py, tests/test_opening_hours.py
=> Add Sobeys (CA) (supermarket) (241 locations)

locations/spiders/juiceland.py
Added new Wikidata Page for Juiceland and also to NSI
https://github.com/osmlab/name-suggestion-index/pull/8797
=> Added Juiceland Wikidata Qcode

locations/categories.py, locations/spiders/bash_za.py
Added categories for small brands that are not in NSI
=> Added categories for bash south africa

locations/spiders/apotek_1_no.py
Rel: https://github.com/alltheplaces/alltheplaces/pull/6112
=> [Apotek1NO] Add spider

locations/spiders/dhl_express_de.py, locations/spiders/dhl_express_es.py, locations/spiders/dhl_express_fr.py, locations/spiders/dhl_express_gb.py, locations/spiders/dhl_express_us_ca.py
As DHL's qcode is with several NSI categories. Thus the categories need to be added here.
=> Added Category for all the dhl express spiders

locations/spiders/argos.py
Their data is surprisingly bad
=> [Argos] Fix spider

locations/spiders/kutchenhaus_gb.py
Category will come soon too
https://github.com/osmlab/name-suggestion-index/commit/e6a1f6583a7ea22fd089cf1fb66f78327a1698b5
=> [KutchenhausGB] Add wikidata

locations/spiders/texcycle_bg.py
=> Add texcycle_bg spider (#6039)

locations/spiders/mtexx_bg.py
=> Add M-Texx (BG) (362 locations)

locations/hours.py, locations/spiders/epaka.py
I also fixed typo in Polish weekday name.
=> Add Epaka.pl spider (360 locations)

locations/spiders/great_wolf_us.py
=> Add great wolf resort spider

locations/spiders/bjrestaurants.py, locations/spiders/halloweencity.py, locations/spiders/lowes_foods.py, locations/spiders/planet_fitness.py, locations/spiders/spirithalloween.py, locations/spiders/stater_bros.py, locations/spiders/vitamin_shoppe.py
=> Use underscore instead of dash in spider names

locations/spiders/gucci.py, locations/spiders/iowa_university.py, locations/spiders/lids.py, locations/spiders/national.py, locations/spiders/remax_fr.py
I didn't modify spiders
which return 0 results for me:
- kbp_foods
- longhorn_steakhouse
- sinonmed
- tractorsupply
- wellstar
Related #4878
=> Use BROWSER_DEFAULT when possible

locations/categories.py, locations/spiders/timpson_gb.py
Timpson has multiple NSI IDs thus it cannot discern which entry. Thus I added the categories.
```python
{'atp/brand/Timpson': 1317,
'atp/brand_wikidata/Q7807658': 1317,
'atp/category/craft/key_cutter': 31,
'atp/category/missing': 9,
'atp/category/shop/hairdresser': 1,
'atp/category/shop/laundry': 3,
'atp/category/shop/photo': 1,
'atp/category/shop/shoe_repair': 1272,
'atp/field/email/missing': 1317,
'atp/field/image/missing': 1317,
'atp/field/opening_hours/missing': 1317,
'atp/field/state/missing': 1187,
'atp/field/twitter/missing': 1317,
'atp/nsi/category_match': 1,
'atp/nsi/cc_match': 5,
'atp/nsi/match_failed': 1311,
'downloader/exception_count': 9, …
```
=> Added categories for brand

locations/spiders/adidas.py
=> Add Adidas (1947 stores)

locations/spiders/choice_hotels.py
It works for pages that actually have hotels listed. Some of the links will give errors. These are mainly tourist attractions or non-hotel pages. 
I do not have stats as I ran it for 24 hours straight and it still was not finished. Not sure if there is a timeout feature that could be activated.
=> Fixed code to run hotels

locations/spiders/citroen.py
```python
{'atp/brand/Citroen': 516,
'atp/brand_wikidata/Q6746': 516,
'atp/category/shop/car': 412,
'atp/category/shop/car_repair': 104,
'atp/field/email/missing': 102,
'atp/field/image/missing': 516,
'atp/field/opening_hours/missing': 209,
'atp/field/state/missing': 516,
'atp/field/twitter/missing': 516,
'atp/field/website/invalid': 3,
'atp/nsi/category_match': 516,
'downloader/request_bytes': 1848,
'downloader/response_bytes': 72595,
'downloader/response_status_count/200': 4,
'elapsed_time_seconds': 1.114317,
'finish_time': datetime.datetime(2023, 10, 24, …
```
=> Added Categories for citreon brand (516 items)

locations/spiders/b_and_m.py
```python
{'atp/brand/B&M': 714,
'atp/brand_wikidata/Q4836931': 714,
'atp/category/shop/variety_store': 714,
'atp/field/city/missing': 29,
'atp/field/email/missing': 714,
'atp/field/image/missing': 714,
'atp/field/opening_hours/missing': 714,
'atp/nsi/match_failed': 714,
'downloader/request_bytes': 431580,
'downloader/request_count': 716,
'downloader/request_method_count/GET': 716,
'downloader/response_bytes': 76580167,
'downloader/response_count': 716,
'downloader/response_status_count/200': 716,
'elapsed_time_seconds': 890.318964,
'finish_time': datetime.datetime(2023, 10, 24, 19, 49, 58, 304276),
'httpcompression/response_bytes': 1071400833,
'httpcompression/response_count': 716,
'item_scraped_count': 714, …
```
=> Added Variety Store Category for b_and_m shops (714 locations)

locations/spiders/kontanten_se.py
```python
{'atp/brand/Kontanten': 471,
'atp/brand_wikidata/Q122831839': 471,
'atp/category/amenity/atm': 471,
'atp/field/email/missing': 471,
'atp/field/image/missing': 471,
'atp/field/name/missing': 86,
'atp/field/opening_hours/missing': 471,
'atp/field/phone/missing': 471,
'atp/field/state/missing': 471,
'atp/field/twitter/missing': 471,
'atp/field/website/missing': 471,
'atp/nsi/brand_missing': 471,
'downloader/request_bytes': 701,
'downloader/response_bytes': 134769,
'elapsed_time_seconds': 9.35361,
'finish_time': …
```
=> Added Category and Brand Wikidata for Kontanten (471 items)

locations/spiders/blaze_pizza.py
```python
{'atp/brand/Blaze Pizza': 278,
'atp/brand_wikidata/Q23016666': 278,
'atp/category/amenity/restaurant': 278,
'atp/cdn/cloudflare/response_count': 280,
'atp/cdn/cloudflare/response_status_count/200': 279,
'atp/closed_check': 11,
'atp/field/email/missing': 278,
'atp/field/image/missing': 278,
'atp/field/opening_hours/missing': 278,
'atp/field/twitter/missing': 278,
'atp/nsi/perfect_match': 278,
'downloader/request_bytes': 117959,
'downloader/request_count': 280,
'downloader/request_method_count/GET': 280,
'downloader/response_bytes': 501551,
'downloader/response_count': 280,
'downloader/response_status_count/200': 279, …
```
=> Added qcode and add underscore in spider_name (278 Items)

locations/spiders/alh_hotels_au.py
```python
{'atp/brand/ALH Hotels': 346,
'atp/brand_wikidata/Q119159708': 346,
'atp/category/amenity/bar': 3,
'atp/category/amenity/cafe': 2,
'atp/category/amenity/pub': 2,
'atp/category/amenity/restaurant': 86,
'atp/category/missing': 23,
'atp/category/tourism/hotel': 230,
'atp/field/city/missing': 346,
'atp/field/country/from_spider_name': 338,
'atp/field/email/missing': 346,
'atp/field/image/missing': 346,
'atp/field/opening_hours/missing': 346,
'atp/field/postcode/missing': 346,
'atp/field/state/missing': 346,
'atp/field/street_address/missing': 346,
'atp/field/twitter/missing': 346,
'atp/nsi/brand_missing': 346, …
```
=> Added categories by what is in theas many had key words in the name (346 Items)

locations/spiders/sephora_mx.py
Multiple entries in NSI. Thus adding category here.
```python
{'atp/brand/Sephora': 36,
'atp/brand_wikidata/Q2408041': 36,
'atp/category/shop/beauty': 36,
'atp/field/city/missing': 36,
'atp/field/country/from_spider_name': 36,
'atp/field/lat/missing': 10,
'atp/field/lon/missing': 10,
'atp/field/state/missing': 36,
'atp/field/website/missing': 36,
'atp/nsi/match_failed': 36,
'downloader/request_bytes': 541,
'downloader/response_bytes': 48541, …
```
=> Added category (36 items)

locations/spiders/halloweencity.py
Added qcode for brand Party City (also known as halloween city).
=> Added qcode for halloween city

locations/spiders/coen_markets.py
Added entry to NSI https://github.com/osmlab/name-suggestion-index/pull/8882 and created the wikidata page for it.
=> Added wikidata qcode to coen markets

locations/spiders/taco_time.py
=> Add TacoTime spider

locations/spiders/suzuki_be.py
Added category as multiple NSI entries.
```python
{'atp/brand/Suzuki': 76,
'atp/brand_wikidata/Q181642': 76,
'atp/category/shop/car': 76,
'atp/field/country/from_spider_name': 76,
'atp/field/image/missing': 76,
'atp/field/opening_hours/missing': 76,
'atp/field/state/missing': 76,
'atp/field/twitter/missing': 76,
'atp/field/website/missing': 76,
'atp/nsi/category_match': 76,
'downloader/request_bytes': 521,
'downloader/response_bytes': 228161,
'elapsed_time_seconds': 1.969166,
'finish_time': datetime.datetime(2023, 10, …
```
=> Added category (76 items)

locations/spiders/dats24.py
```python
{'atp/brand/DATS 24': 146,
'atp/brand_wikidata/Q15725576': 146,
'atp/category/amenity/fuel': 146,
'atp/field/country/from_spider_name': 146,
'atp/field/image/missing': 146,
'atp/field/opening_hours/missing': 146,
'atp/field/phone/missing': 146,
'atp/field/state/missing': 146,
'atp/field/website/missing': 146,
'atp/nsi/category_match': 146,
'downloader/request_bytes': 646,
'downloader/response_bytes': 148251,
'elapsed_time_seconds': 2.286187,
'finish_time': datetime.datetime(2023, 10, 28, 22, 47, 32, …
```
=> Added fuel category for and types of fuel tags (146 Items)

locations/spiders/vodafone_it.py
=> vodafone_it: fix spider

locations/spiders/pandora.py
Ignore some Japanese locations with ?????? in the URL path as these are invalid URLs.
=> pandora: fix spider

locations/spiders/doz_apotek_se.py
https://github.com/osmlab/name-suggestion-index/commit/366b2667c936fbb64b01c3073bf5a0394c86d5e6
=> [DozApotekSE] Add Spider

locations/spiders/ncp_gb.py
{'atp/category/amenity/parking': 643,
'atp/cdn/cloudflare/response_count': 659,
'atp/cdn/cloudflare/response_status_count/200': 659,
'atp/field/brand/missing': 643,
'atp/field/brand_wikidata/missing': 643,
'atp/field/city/missing': 643,
'atp/field/country/from_spider_name': 643,
'atp/field/email/missing': 643,
'atp/field/image/missing': 643,
'atp/field/opening_hours/missing': 56,
'atp/field/phone/missing': 392,
'atp/field/postcode/missing': 643,
'atp/field/state/missing': 643,
'atp/field/twitter/missing': 643,
'downloader/request_bytes': 520444,
'downloader/request_count': 1316,
'downloader/request_method_count/GET': 1316,
'downloader/response_bytes': 13116792,
'downloader/response_count': 1316,
'downloader/response_status_count/200': 659,
'downloader/response_status_count/301': 657, …
=> [ncp_gb] Updating spider to SitemapSpider to add more POIs

locations/spiders/allegro_one_box.py
Adds parcel lockers mentioned in https://github.com/alltheplaces/alltheplaces/issues/6055
While it returns all the parcel lockers in one request, the results only include id, lat and lon. For more details, making request for each parcel locker or using an API requiring an API key would be needed.
=> Add Allegro One Box (3144 locations)

locations/spiders/accor.py
All addresses in raw data are actually full addresses.
=> [accor] change from street to full.

locations/spiders/adidas.py
I tried to set `https://www.adidas.com/` as base url for POIs, but unfortunately it does not work with slugs, so I set `https://www.adidas.co.uk/`, it's not localised, but I think it's good enough.
=> [adidas] more attributes, shorter link.

locations/spiders/fleet_feet_us.py
Rel: https://github.com/osmlab/name-suggestion-index/issues/8895
```python
{'atp/brand/Fleet Feet': 152,
'atp/brand_wikidata/Q117062761': 152,
'atp/category/missing': 152,
'atp/field/city/missing': 46,
'atp/field/country/from_spider_name': 152,
'atp/field/email/missing': 152,
'atp/field/image/missing': 152,
'atp/field/name/missing': 152,
'atp/field/opening_hours/missing': 152,
'atp/field/phone/missing': 152,
'atp/field/postcode/missing': 46,
'atp/field/state/from_reverse_geocoding': 46,
'atp/field/twitter/missing': 152,
'atp/nsi/brand_missing': 152,
'downloader/response_bytes': 66238, …
```
=> [FleetFeetUS] Add Spider

locations/categories.py, locations/spiders/stonegate_gb.py
```python
{'atp/brand/Be At One': 39,
'atp/brand/Craft Union': 551,
'atp/brand/Crafted Social': 141,
'atp/brand/Fever': 11,
'atp/brand/Great UK Pubs': 309,
'atp/brand/Popworld': 40,
'atp/brand/Slug & Lettuce': 80,
'atp/brand/Walkabout': 20,
'atp/brand_wikidata/Q110016786': 39,
'atp/brand_wikidata/Q7542224': 80,
'atp/brand_wikidata/Q7962149': 20,
'atp/category/amenity/bar': 39,
'atp/category/amenity/nightclub': 51,
'atp/category/amenity/pub': 1186,
'atp/cdn/cloudflare/response_count': 1429,
'atp/cdn/cloudflare/response_status_count/200': 1340,
'atp/cdn/cloudflare/response_status_count/403': 89,
'atp/field/brand/missing': 85,
'atp/field/brand_wikidata/missing': 1137,
'atp/field/email/invalid': 44,
'atp/field/email/missing': 548,
'atp/field/image/missing': 1276, …
```
=> [Stonegate] Fix spider

locations/spiders/its_fashions_us.py
Rel: https://github.com/osmlab/name-suggestion-index/pull/8901
=> [ItsFashionsUS] Add spider

locations/spiders/bhf_gb.py
Rel: https://github.com/osmlab/name-suggestion-index/issues/6954
The urls are surprisingly in consistent, but this will collect more locations and better categorise them.
=> [BritishHeartFoundationGB] Collect more locations

locations/categories.py, locations/spiders/tim_hortons.py
Rel: https://github.com/alltheplaces/alltheplaces/pull/6084
=> [TimHortons] Fix email seperator

locations/spiders/fantastiko_bg.py
Removed phone and Facebook since they are the same for the whole brand. I've also corrected the opening hours since there were places where leading zeros were missing.
=> Improve fantastiko_bg spider

locations/spiders/an_post_ie.py
```python
{'atp/category/amenity/parcel_locker': 43,
'atp/category/amenity/post_office': 913,
'atp/category/missing': 211,
'atp/field/brand/missing': 1167,
'atp/field/brand_wikidata/missing': 1167,
'atp/field/email/missing': 1167,
'atp/field/image/missing': 1167,
'atp/field/phone/missing': 72,
'atp/field/street_address/missing': 1167,
'atp/field/twitter/missing': 1167,
'downloader/request_bytes': 876,
'downloader/response_bytes': 1641257,
'elapsed_time_seconds': 1.025215, …
```
=> [AnPostIE] Add spider

locations/spiders/postbank_bg.py
=> Create spider for postbank_bg

locations/spiders/technopolis_bg.py
=> Create spider for technopolis_bg

locations/spiders/pokawa.py
Rel: https://github.com/osmlab/name-suggestion-index/pull/8912
```python
{'atp/brand/Pokawa': 130,
'atp/brand_wikidata/Q123018553': 130,
'atp/category/missing': 130,
'atp/field/city/missing': 90,
'atp/field/country/from_reverse_geocoding': 41,
'atp/field/email/missing': 130,
'atp/field/opening_hours/missing': 130,
'atp/field/phone/missing': 130,
'atp/field/postcode/missing': 130,
'atp/field/street_address/missing': 130,
'atp/field/twitter/missing': 130,
'atp/nsi/brand_missing': 130,
'downloader/response_bytes': 12373, …
```
=> [Pokawa] Add spider

locations/spiders/bedshed_au.py
Rel: https://github.com/osmlab/name-suggestion-index/pull/8913
```python
{'atp/brand/Bedshed': 42,
'atp/brand_wikidata/Q84452962': 42,
'atp/category/shop/bed': 42,
'atp/cdn/cloudflare/response_count': 44,
'atp/cdn/cloudflare/response_status_count/200': 44,
'atp/field/twitter/missing': 42,
'atp/nsi/perfect_match': 42,
'downloader/request_bytes': 49304,
'downloader/response_bytes': 5145013,
'downloader/response_count': 44,
'downloader/response_status_count/200': 44,
'elapsed_time_seconds': 1.611671,
'finish_time': datetime.datetime(2023, 11, 7, 15, 13, 58, 15581),
'httpcache/hit': 44, …
```
=> [BedshedAU] Add spider

locations/spiders/banka_kombetare_tregtare_al.py
Rel: https://github.com/osmlab/name-suggestion-index/pull/8889
```python
{'atp/brand/Banka Kombëtare Tregtare': 186,
'atp/brand_wikidata/Q806702': 186,
'atp/category/amenity/atm': 124,
'atp/category/amenity/bank': 62,
'atp/field/country/from_spider_name': 186,
'atp/field/image/missing': 186,
'atp/field/opening_hours/missing': 186,
'atp/field/postcode/missing': 186,
'atp/field/state/missing': 186,
'atp/field/street_address/missing': 186,
'atp/field/twitter/missing': 186,
'atp/field/website/missing': 186,
'atp/nsi/brand_missing': 186,
'downloader/response_bytes': 110273, …
```
=> [BankaKombetareTregtareAL] Add spider

locations/spiders/ewiva_it.py
Rel: https://github.com/osmlab/name-suggestion-index/pull/8897
```python
{'atp/category/amenity/charging_station': 213,
'atp/field/brand/missing': 213,
'atp/field/brand_wikidata/missing': 213,
'atp/field/country/from_spider_name': 213,
'atp/field/email/missing': 213,
'atp/field/image/missing': 213,
'atp/field/name/missing': 213,
'atp/field/opening_hours/missing': 213,
'atp/field/phone/missing': 213,
'atp/field/postcode/missing': 213,
'atp/field/street_address/missing': 213,
'atp/field/twitter/missing': 213,
'atp/field/website/missing': 213,
'downloader/request_bytes': 623,
'downloader/response_bytes': 31684, …
```
=> [EwivaIT] Add Spider

locations/spiders/dairy_queen_us.py
Instead of item.update(...) which could break due to the "extras" dict, use a more future proof approach to extracting extra information.
=> dairy_queen_us: improve extras extraction

locations/spiders/ifly_us.py
=> Add iFLY (US) (41 locations)

locations/spiders/touchstone_medical_imaging_us.py
=> Add Touchstone Medical Imaging (US) (61 locations)

locations/spiders/promedica_us.py
=> Add ProMedica (US) (141 locations)

locations/spiders/versace.py
=> Add Versace (worldwide) (207 locations)

locations/spiders/empres_us.py
=> Add EmpRes (US) (46 locations)

locations/spiders/modern_market_us.py
=> Add Modern Market (US) (35 locations)

locations/spiders/george_webb_us.py
=> Add George Webb (US) (25 locations)

locations/spiders/pure_barre_us.py
=> Add Pure Barre (US) (638 locations)

locations/spiders/karstadt_de.py
=> Add Karstadt (DE) (110 locations)

locations/spiders/century_21_fr.py
Stockists is the wrong word for these, but they weren't Century 21 locations.
The [website says 950](https://www.century21.fr/), with 1 [broken page](https://www.century21.fr/trouver_agence/d-31_haute_garonne/) we'd have 946. A bit closer than 41,219 in the last weekly. 
```python
{'atp/brand/Century 21': 922,
'atp/brand_wikidata/Q1054480': 922,
'atp/category/office/estate_agent': 922,
'atp/field/email/missing': 922,
'atp/field/image/missing': 922,
'atp/field/opening_hours/missing': 922,
'atp/field/state/missing': 922,
'atp/field/twitter/missing': 922,
'atp/nsi/cc_match': 922,
'downloader/request_bytes': 48428,
'downloader/request_count': 117,
'downloader/request_method_count/GET': 117,
'downloader/response_bytes': 1776720,
'downloader/response_count': 117, …
```
=> [Century21FR] Remove bad data

locations/spiders/iceland_foods.py
```python
{'atp/brand/Iceland': 823,
'atp/brand_wikidata/Q721810': 823,
'atp/category/shop/frozen_food': 823,
'atp/cdn/cloudflare/response_count': 1084,
'atp/cdn/cloudflare/response_status_count/200': 1084,
'atp/field/email/missing': 823,
'atp/field/image/dropped': 823,
'atp/field/image/missing': 823,
'atp/field/lat/missing': 15,
'atp/field/lon/missing': 15,
'atp/field/name/missing': 823,
'atp/field/state/missing': 13,
'atp/nsi/perfect_match': 823,
'downloader/request_bytes': 1745093,
'downloader/request_count': 1086,
'downloader/request_method_count/GET': 1086,
'downloader/response_bytes': 171895971, …
```
=> [IcelandFoods] Drop closed stores

locations/spiders/speedy_stop_us.py, locations/spiders/universal_store_au.py, locations/storefinders/closeby.py
* Add Speedy Stop as an example.
* Convert universal_store_au to ClosebySpider to fix spider.
Fixes #6088
=> Add Closeby storefinder

locations/categories.py, locations/spiders/blinds_to_go.py
Rel: https://github.com/osmlab/name-suggestion-index/pull/8932
```python
{'atp/brand/Blinds to Go': 87,
'atp/brand_wikidata/Q123409913': 87,
'atp/category/shop/window_blind': 87,
'atp/cdn/cloudflare/response_count': 90,
'atp/cdn/cloudflare/response_status_count/200': 90,
'atp/field/image/invalid': 26,
'atp/nsi/brand_missing': 87,
'downloader/request_bytes': 48348,
'downloader/request_count': 90,
'downloader/request_method_count/GET': 90,
'downloader/response_bytes': 2406021,
'downloader/response_count': 90,
'downloader/response_status_count/200': 90,
'elapsed_time_seconds': 1.643054,
'finish_time': datetime.datetime(2023, 11, 16, 8, 54, 51, 490264),
'httpcache/hit': 90, …
```
=> [BlindsToGo] Add spider

locations/spiders/access_storage_ca.py
Rel: https://github.com/osmlab/name-suggestion-index/pull/8932
```python
{'atp/brand/Access Storage': 146,
'atp/brand_wikidata/Q123409757': 146,
'atp/category/shop/storage_rental': 146,
'atp/field/country/from_spider_name': 146,
'atp/field/name/missing': 146,
'atp/field/postcode/missing': 146,
'atp/field/state/from_reverse_geocoding': 146,
'atp/field/street_address/missing': 146,
'atp/nsi/brand_missing': 146,
'downloader/request_bytes': 789,
'downloader/response_bytes': 294398, …
```
=> [AccessStorageCA] Add spider

locations/spiders/first_cash.py
{'atp/brand/0Irst Cash Pawn': 1,
'atp/brand/39Th Street Pawn': 1,
'atp/brand/Action Pawn': 11,
'atp/brand/All That Glitters': 5,
'atp/brand/Arcadia Pawn': 1,
'atp/brand/Bennys Pawn Shop': 8,
'atp/brand/Big Deal Pawn & Shop': 1,
'atp/brand/Bills Pawn Shop': 1,
'atp/brand/Capital Pawn': 20,
'atp/brand/Cash America': 637,
'atp/brand/Cash America Pawn': 59,
'atp/brand/Cash Plus Pawn': 3,
'atp/brand/Cash Ya! Empeno': 1,
'atp/brand/Cashland': 25,
'atp/brand/Choice Pawn': 1,
'atp/brand/Coastal Pawn & Jewelry': 1,
'atp/brand/Dans Discount Jewelry': 8,
'atp/brand/Doc Holiday Pawn': 2,
'atp/brand/Famous Jewelry & Loan': 1,
'atp/brand/Famous Pawnbrokers': 5,
'atp/brand/Fast Cash': 8,
'atp/brand/First Cash': 12,
'atp/brand/First Cash Advance': 1,
'atp/brand/First Cash Jewelry & Exch': 1, …
=> [FirstCash] Improve category and brands

locations/categories.py, locations/spiders/lhw.py
Not entirely sure if `The Leading Hotels of the World` should be a brand as it's a marketing company. To me it' looks more like a brand.
Stats:
```json
{
"atp/brand/The Leading Hotels of the World": 414,
"atp/brand_wikidata/Q834396": 414,
"atp/category/tourism/hotel": 414,
"atp/field/country/from_reverse_geocoding": 15,
"atp/field/email/missing": 414,
"atp/field/opening_hours/missing": 414,
"atp/field/phone/missing": 414,
"atp/field/postcode/missing": 405,
"atp/field/state/missing": 365,
"atp/field/street_address/missing": 414,
"atp/field/twitter/missing": 414,
"atp/nsi/brand_missing": 414,
"downloader/request_bytes": 327,
"downloader/response_bytes": 369966, …
```
=> Add Leading Hotels of the World (LHW) spider (414 locations)

locations/spiders/kum_and_go.py
Stats:
```json
{
"atp/brand/Kum & Go": 396,
"atp/brand_wikidata/Q6443340": 396,
"atp/category/amenity/fuel": 395,
"atp/category/shop/convenience": 1,
"atp/field/email/missing": 396,
"atp/field/image/missing": 396,
"atp/field/opening_hours/missing": 14,
"atp/field/twitter/missing": 396,
"atp/field/website/missing": 396,
"atp/nsi/category_match": 396,
"downloader/request_bytes": 3827,
"downloader/request_count": 12,
"downloader/request_method_count/GET": 12,
"downloader/response_bytes": 5268108,
"downloader/response_count": 12,
"downloader/response_status_count/200": 11,
"elapsed_time_seconds": 14.26544,
"finish_time": "2023-11-17T13:17:43.984690+00:00", …
```
=> [kum_and_go] add category + improve spider

locations/spiders/vtb_ru.py
Stats:
```json
{
"atp/brand/\u0412\u0422\u0411": 1136,
"atp/brand_wikidata/Q1549389": 1136,
"atp/category/amenity/bank": 1136,
"atp/field/country/from_spider_name": 1136,
"atp/field/email/missing": 1136,
"atp/field/image/missing": 1136,
"atp/field/name/missing": 1136,
"atp/field/opening_hours/missing": 49,
"atp/field/phone/missing": 1136,
"atp/field/postcode/missing": 1136,
"atp/field/state/missing": 1136,
"atp/field/street_address/missing": 1136,
"atp/field/twitter/missing": 1136,
"atp/field/website/missing": 1136,
"atp/nsi/category_match": 1136,
"downloader/request_bytes": 657,
"downloader/response_bytes": 68952, …
```
=> [vtb_ru] add spider (1136 locations).

locations/spiders/nissan_be.py
```json
{
"atp/brand/Nissan": 54,
"atp/brand_wikidata/Q20165": 54,
"atp/category/shop/car": 54,
"atp/field/image/missing": 54,
"atp/field/opening_hours/missing": 54,
"atp/field/state/missing": 54,
"atp/field/twitter/missing": 54,
"atp/field/website/missing": 2,
"atp/nsi/category_match": 54,
"downloader/request_bytes": 42566,
"downloader/request_count": 55,
"downloader/request_method_count/GET": 55,
"downloader/response_bytes": 68307,
"downloader/response_count": 55,
"downloader/response_status_count/200": 55,
"elapsed_time_seconds": 69.050195,
"finish_time": "2023-11-21T16:20:08.512355+00:00",
"httpcompression/response_bytes": 106856,
"httpcompression/response_count": 55,
"item_scraped_count": 54, …
```
=> [nissan_be] apply category.

locations/spiders/dominos_pizza_de.py
```python
{"atp/brand/Domino's": 406,
'atp/brand_wikidata/Q839466': 406,
'atp/category/amenity/fast_food': 406,
'atp/field/email/missing': 406,
'atp/field/image/missing': 406,
'atp/field/opening_hours/missing': 406,
'atp/field/phone/missing': 406,
'atp/field/state/missing': 406,
'atp/field/twitter/missing': 406,
'atp/nsi/cc_match': 406,
'downloader/request_bytes': 414177,
'downloader/request_count': 415,
'downloader/request_method_count/GET': 415,
'downloader/response_bytes': 12903211,
'downloader/response_count': 415,
'downloader/response_status_count/200': 409,
'downloader/response_status_count/302': 2, …
```
=> [dominos_pizza_de] Fixed Spider (406 items)

locations/spiders/dominos_pizza_be.py
```python
{"atp/brand/Domino's": 127,
'atp/brand_wikidata/Q839466': 127,
'atp/category/amenity/fast_food': 127,
'atp/field/email/missing': 127,
'atp/field/image/missing': 127,
'atp/field/opening_hours/missing': 127,
'atp/field/phone/missing': 127,
'atp/field/state/missing': 127,
'atp/field/twitter/missing': 127,
'atp/nsi/cc_match': 127,
'downloader/request_bytes': 124062,
'downloader/request_count': 129,
'downloader/request_method_count/GET': 129,
'downloader/response_bytes': 4863452,
'downloader/response_count': 129,
'downloader/response_status_count/200': 129,
'elapsed_time_seconds': 154.986188,
'finish_time': datetime.datetime(2023, 11, 21, 16, 3, 57, …
```
=> [dominos_pizza_be] Fixed Spider (127 items)

locations/spiders/dominos_pizza_jp.py
```python
{"atp/brand/Domino's": 1009,
'atp/brand_wikidata/Q839466': 1009,
'atp/category/amenity/fast_food': 1009,
'atp/field/city/missing': 1009,
'atp/field/email/missing': 1009,
'atp/field/image/missing': 1009,
'atp/field/opening_hours/missing': 1009,
'atp/field/state/missing': 1009,
'atp/field/street_address/missing': 1009,
'atp/field/twitter/missing': 1009,
'atp/nsi/cc_match': 1009,
'downloader/request_bytes': 2086455,
'downloader/request_count': 2084,
'downloader/request_method_count/GET': 2084,
'downloader/response_bytes': 58112666,
'downloader/response_count': 2084, …
```
=> [dominos_pizza_jp] Fixed (1009 items)

locations/spiders/mer_gb.py
{'atp/brand/Mer': 662,
'atp/brand_wikidata/Q100821564': 662,
'atp/category/amenity/charging_station': 662,
'atp/field/city/missing': 662,
'atp/field/country/from_spider_name': 662,
'atp/field/email/missing': 662,
'atp/field/image/missing': 662,
'atp/field/name/missing': 662,
'atp/field/opening_hours/missing': 662,
'atp/field/phone/missing': 662,
'atp/field/postcode/missing': 662,
'atp/field/state/missing': 662,
'atp/field/street_address/missing': 662,
'atp/field/twitter/missing': 662,
'atp/field/website/missing': 662,
'atp/nsi/category_match': 662,
'downloader/request_bytes': 449,
'downloader/response_bytes': 22964, …
=> [MerGB] Add category

locations/spiders/genie_point_gb.py
{'atp/brand/GeniePoint': 669,
'atp/brand_wikidata/Q111363966': 669,
'atp/category/amenity/charging_station': 669,
'atp/field/city/missing': 669,
'atp/field/country/from_spider_name': 669,
'atp/field/email/missing': 669,
'atp/field/image/missing': 669,
'atp/field/opening_hours/missing': 669,
'atp/field/phone/missing': 669,
'atp/field/postcode/missing': 669,
'atp/field/state/missing': 669,
'atp/field/street_address/missing': 669,
'atp/field/twitter/missing': 669,
'atp/field/website/missing': 669,
'atp/nsi/category_match': 669,
'downloader/request_bytes': 640,
'downloader/response_bytes': 445999, …
=> [GeniePointGB] Add category

locations/spiders/source_london_gb.py
{'atp/brand/Source London': 1033,
'atp/brand_wikidata/Q7565133': 1033,
'atp/category/amenity/charging_station': 1033,
'atp/field/country/from_spider_name': 1033,
'atp/field/email/missing': 1033,
'atp/field/image/missing': 1033,
'atp/field/opening_hours/missing': 1033,
'atp/field/phone/missing': 1033,
'atp/field/postcode/missing': 1033,
'atp/field/state/missing': 1033,
'atp/field/street_address/missing': 1033,
'atp/field/twitter/missing': 1033,
'atp/field/website/missing': 1033,
'atp/nsi/category_match': 1033,
'downloader/request_bytes': 630,
'downloader/response_bytes': 5803072,
'elapsed_time_seconds': 6.228671, …
=> [SourceLondonGB] Add category

locations/spiders/albert_heijn.py
Reason for the massive change in code was due to the authorization being denied when making query requests using GraphQL.
<details><summary>NL Stats</summary>
```python
{'atp/brand/Albert Heijn': 1197,
'atp/brand_wikidata/Q1653985': 1197,
'atp/category/shop/supermarket': 1197,
'atp/field/email/missing': 1197,
'atp/field/image/missing': 1197,
'atp/field/phone/missing': 16,
'atp/field/state/missing': 1197,
'atp/field/street_address/missing': 1197,
'atp/field/twitter/missing': 1197,
'atp/field/website/missing': 1197,
'atp/nsi/perfect_match': 1197,
'downloader/request_bytes': 1947740,
'downloader/request_count': 1200,
'downloader/request_method_count/GET': 1200,
'downloader/response_bytes': 28035303, …
```
=> [albert_heijn] Fixed Spider (1272 Items)

locations/spiders/marks_and_spencer.py
I found some conflicting stuff. for Simply Food vs Foodhall. I think I got it correct, putting convenience for Simply Food as wikipedia said it was with some BP Oil petrol stations. Then Foodhall in wikipedia sounded like a supermarket. Would not mind another opinion on this one.
```python
{'atp/brand/M&S Foodhall': 100,
'atp/brand/M&S Outlet': 29,
'atp/brand/M&S Simply Food': 250,
'atp/brand/Marks and Spencer': 717,
'atp/brand_wikidata/Q714491': 1096,
'atp/category/shop/convenience': 250,
'atp/category/shop/department_store': 746,
'atp/category/shop/supermarket': 100,
'atp/field/country/from_reverse_geocoding': 3,
'atp/field/email/missing': 1096,
'atp/field/image/missing': 1096,
'atp/field/phone/missing': 226, …
```
=> [marks_and_spencer] Added Category Tags (1096 items)

locations/spiders/esb_energy_gb.py
{'atp/brand/ESB Energy': 187,
'atp/brand_wikidata/Q118261834': 187,
'atp/category/amenity/charging_station': 187,
'atp/field/city/missing': 187,
'atp/field/country/from_spider_name': 187,
'atp/field/email/missing': 187,
'atp/field/image/missing': 187,
'atp/field/name/missing': 187,
'atp/field/opening_hours/missing': 187,
'atp/field/phone/missing': 187,
'atp/field/postcode/missing': 187,
'atp/field/state/missing': 187,
'atp/field/twitter/missing': 187,
'atp/field/website/missing': 187,
'atp/nsi/category_match': 187,
'downloader/request_bytes': 459,
'downloader/response_bytes': 7354,
'elapsed_time_seconds': 0.97828, …
=> [ESBEnergy] Add brand and category

locations/spiders/ingles.py
{'atp/brand/Ingles': 189,
'atp/brand_wikidata/Q6032595': 189,
'atp/category/shop/supermarket': 189,
'atp/field/country/from_reverse_geocoding': 189,
'atp/field/email/missing': 189,
'atp/field/image/missing': 189,
'atp/field/twitter/missing': 189,
'atp/nsi/category_match': 189,
'downloader/request_bytes': 95885,
'downloader/request_count': 196,
'downloader/request_method_count/GET': 196,
'downloader/response_bytes': 731659,
'downloader/response_count': 196,
'downloader/response_status_count/200': 196,
'elapsed_time_seconds': 236.834941,
'finish_time': datetime.datetime(2023, 11, 22, 15, 18, 15, 881078, tzinfo=datetime.timezone.utc),
'item_scraped_count': 189,
'log_count/DEBUG': 396,
'log_count/INFO': 12,
'memusage/max': 408944640,
'memusage/startup': 133971968, …
=> [Ingles] Add category

locations/spiders/bjswholesale.py
{"atp/brand/BJ's Wholesale": 252,
'atp/brand_wikidata/Q4835754': 252,
'atp/category/shop/wholesale': 252,
'atp/field/email/missing': 252,
'atp/field/image/missing': 252,
'atp/field/twitter/missing': 252,
'atp/nsi/category_match': 252,
'downloader/request_bytes': 734622,
'downloader/request_count': 254,
'downloader/request_method_count/POST': 252,
'downloader/response_bytes': 662057,
'downloader/response_count': 254,
'downloader/response_status_count/200': 253,
'elapsed_time_seconds': 302.050206,
'finish_time': datetime.datetime(2023, 11, 22, 14, 35, 30, 815037, tzinfo=datetime.timezone.utc),
'httpcompression/response_bytes': 1167058, …
=> [BJsWholesale] Add category

locations/spiders/salvos_au.py
{'atp/brand/Salvos': 397,
'atp/brand_wikidata/Q120646407': 397,
'atp/category/shop/charity': 397,
'atp/field/country/from_spider_name': 397,
'atp/field/email/missing': 397,
'atp/field/image/missing': 397,
'atp/field/street_address/missing': 397,
'atp/field/twitter/missing': 397,
'atp/nsi/brand_missing': 397,
'downloader/request_bytes': 641,
'downloader/response_bytes': 85740,
'elapsed_time_seconds': 8.236624,
'finish_time': datetime.datetime(2023, 11, 22, 11, 53, …
=> [SalvosAU] Add category

locations/spiders/pro_hockey_life_ca.py
Rel: https://github.com/osmlab/name-suggestion-index/pull/8945
```python
{'atp/brand/Pro Hockey Life': 16,
'atp/brand_wikidata/Q123466336': 16,
'atp/category/shop/sports': 16,
'atp/field/name/missing': 16,
'atp/nsi/perfect_match': 16,
'downloader/request_bytes': 1876,
'downloader/response_bytes': 54560,
'elapsed_time_seconds': 0.601667, …
```
=> [ProHockeyLifeCA] Add Spider

locations/spiders/gridserve_gb.py
{'atp/brand/Gridserve': 178,
'atp/brand_wikidata/Q89575318': 178,
'atp/category/amenity/charging_station': 178,
'atp/field/email/missing': 178,
'atp/field/image/missing': 178,
'atp/field/opening_hours/missing': 178,
'atp/field/phone/missing': 178,
'atp/field/state/missing': 178,
'atp/field/street_address/missing': 178,
'atp/field/twitter/missing': 178,
'atp/field/website/missing': 178,
'atp/nsi/category_match': 178,
'downloader/request_bytes': 658,
'downloader/response_bytes': 54359,
'elapsed_time_seconds': 3.100745,
'finish_time': datetime.datetime(2023, 11, 23, 9, 16, …
=> [GridserveGB] Add category

locations/spiders/quickchek_us.py
{'atp/brand/QuickChek': 168,
'atp/brand_wikidata/Q7271689': 168,
'atp/category/shop/convenience': 168,
'atp/field/city/missing': 168,
'atp/field/country/from_spider_name': 168,
'atp/field/email/missing': 168,
'atp/field/image/missing': 168,
'atp/field/phone/missing': 168,
'atp/field/postcode/missing': 168,
'atp/field/state/from_reverse_geocoding': 168,
'atp/field/street_address/missing': 168,
'atp/field/twitter/missing': 168,
'atp/field/website/missing': 168,
'atp/nsi/category_match': 168,
'downloader/request_bytes': 771,
'downloader/response_bytes': 10190, …
=> [QuickChekUS] Add category

locations/spiders/dusk_au.py
{'atp/brand/dusk': 147,
'atp/brand_wikidata/Q120669167': 147,
'atp/category/shop/houseware': 147,
'atp/field/country/from_spider_name': 147,
'atp/field/email/missing': 147,
'atp/field/image/missing': 147,
'atp/field/opening_hours/missing': 147,
'atp/field/phone/missing': 147,
'atp/field/twitter/missing': 147,
'atp/nsi/brand_missing': 147,
'downloader/request_bytes': 623,
'downloader/response_bytes': 40101,
'elapsed_time_seconds': 3.327645,
'finish_time': datetime.datetime(2023, 11, 23, 9, 49, 23, 260679, tzinfo=datetime.timezone.utc),
'httpcompression/response_bytes': 418739, …
=> [DuskAU] Add category

locations/spiders/yha_gb.py
{'atp/brand/YHA': 140,
'atp/brand_wikidata/Q118234608': 140,
'atp/category/tourism/hostel': 140,
'atp/field/city/missing': 140,
'atp/field/country/from_spider_name': 140,
'atp/field/email/missing': 140,
'atp/field/image/missing': 140,
'atp/field/name/missing': 140,
'atp/field/opening_hours/missing': 140,
'atp/field/phone/missing': 140,
'atp/field/state/missing': 140,
'atp/field/street_address/missing': 140,
'atp/nsi/brand_missing': 140,
'downloader/request_bytes': 788,
'downloader/response_bytes': 464102,
'elapsed_time_seconds': 8.951095,
'finish_time': datetime.datetime(2023, 11, …
=> [YHAGB] Add category

locations/spiders/chicos_offtherack.py
{"atp/brand/Chico's Off The Rack": 118,
'atp/brand_wikidata/Q5096393': 118,
'atp/category/shop/clothes': 118,
'atp/field/email/missing': 118,
'atp/field/image/missing': 118,
'atp/field/opening_hours/missing': 118,
'atp/field/phone/missing': 118,
'atp/nsi/match_failed': 118,
'downloader/request_bytes': 22070,
'downloader/request_count': 30,
'downloader/request_method_count/GET': 30,
'downloader/response_bytes': 45646,
'downloader/response_count': 30,
'downloader/response_status_count/200': 11,
'downloader/response_status_count/400': 19,
'elapsed_time_seconds': 36.354998,
'finish_time': datetime.datetime(2023, 11, 23, 11, 13, 55, 971057, tzinfo=datetime.timezone.utc),
'httpcompression/response_bytes': 341589, …
=> [ChicosOffTheRack] Add category

locations/spiders/poundland.py
```python
{'atp/brand/Pep&Co': 592,
'atp/brand/Poundland': 873,
'atp/brand_wikidata/Q1434528': 873,
'atp/brand_wikidata/Q24908166': 592,
'atp/category/shop/clothes': 592,
'atp/category/shop/variety_store': 873,
'atp/field/country/from_reverse_geocoding': 1465,
'atp/field/email/missing': 1465,
'atp/field/image/missing': 1465,
'atp/field/name/missing': 1465,
'atp/field/phone/missing': 122,
'atp/field/twitter/missing': 1465,
'atp/field/website/missing': 1465,
'atp/nsi/perfect_match': 1465,
'downloader/request_bytes': 1584, …
```
=> [Poundland] Fix spider

locations/spiders/mcdonalds_be.py
```python
{"atp/brand/McDonald's": 111,
'atp/brand_wikidata/Q38076': 111,
'atp/category/amenity/fast_food': 111,
'atp/field/country/from_spider_name': 111,
'atp/field/email/missing': 111,
'atp/field/image/missing': 111,
'atp/field/state/missing': 111,
'atp/field/street_address/missing': 111,
'atp/field/twitter/missing': 111,
'atp/nsi/category_match': 111,
'downloader/request_bytes': 649,
'downloader/response_bytes': 548166,
'elapsed_time_seconds': 2.532097,
'finish_time': datetime.datetime(2023, 11, 23, 16, 38, 40, 825022, …
```
=> [McDonaldsBE] Collect urls in more languages

locations/spiders/life_time.py, locations/spiders/life_time_us.py, locations/spiders/lifetime.py
To some degree this is just noise. No benefit other than maintainability.
=> [Lifetime] Switch to StructuredDataSpider

locations/spiders/evyve_gb.py
{'atp/brand/evyve': 109,
'atp/brand_wikidata/Q116698197': 109,
'atp/category/amenity/charging_station': 109,
'atp/field/city/missing': 109,
'atp/field/email/missing': 109,
'atp/field/image/missing': 109,
'atp/field/opening_hours/missing': 109,
'atp/field/phone/missing': 109,
'atp/field/state/missing': 109,
'atp/field/street_address/missing': 109,
'atp/field/twitter/missing': 109,
'atp/field/website/missing': 109,
'atp/nsi/category_match': 109,
'downloader/request_bytes': 604,
'downloader/response_bytes': 93424,
'elapsed_time_seconds': 2.764788,
'finish_time': datetime.datetime(2023, 11, 23, 11, 29, 30, 986762, …
=> [evyveGB] Add category

locations/spiders/burger_king_fi.py
Stats:
```json
{
"atp/brand/Burger King": 65,
"atp/brand_wikidata/Q177054": 65,
"atp/category/amenity/fast_food": 65,
"atp/field/country/from_spider_name": 65,
"atp/field/email/missing": 65,
"atp/field/image/missing": 65,
"atp/field/opening_hours/missing": 65,
"atp/field/state/missing": 65,
"atp/field/twitter/missing": 65,
"atp/field/website/missing": 65,
"atp/nsi/cc_match": 65,
"downloader/request_bytes": 620,
"downloader/response_bytes": 7146,
"elapsed_time_seconds": 1.406826,
"finish_time": "2023-11-24T13:14:59.129200+00:00",
"httpcompression/response_bytes": 64634, …
```
=> [Burger King FI] add spider (65 locations)

locations/spiders/burger_king_dk.py, locations/spiders/burger_king_se.py
Stats:
```json
{
"atp/brand/Burger King": 58,
"atp/brand_wikidata/Q177054": 58,
"atp/category/amenity/fast_food": 58,
"atp/field/city/missing": 58,
"atp/field/country/from_spider_name": 58,
"atp/field/email/missing": 58,
"atp/field/image/missing": 58,
"atp/field/phone/missing": 58,
"atp/field/postcode/missing": 58,
"atp/field/state/missing": 58,
"atp/field/twitter/missing": 58,
"atp/field/website/invalid": 4,
"atp/nsi/cc_match": 58,
"downloader/request_bytes": 30031,
"downloader/request_count": 60,
"downloader/request_method_count/GET": 60,
"downloader/response_bytes": 98503,
"downloader/response_count": 60,
"downloader/response_status_count/200": 59,
"elapsed_time_seconds": 71.269478, …
```
=> [Burger King DK] Add spider (58 locations)

locations/categories.py, locations/spiders/meta.py
Categories will be fixed soon: https://github.com/osmlab/name-suggestion-index/commit/3e7ef7c46878827665347b9196fb1d76c308481c
```python
{'atp/brand/Meta': 115,
'atp/brand_wikidata/Q380': 115,
'atp/category/multiple': 77,
'atp/category/office/it': 77,
'atp/category/telecom/data_center': 38,
'atp/field/country/from_reverse_geocoding': 115,
'atp/field/email/missing': 115,
'atp/field/image/missing': 115,
'atp/field/name/missing': 115,
'atp/field/opening_hours/missing': 115,
'atp/field/phone/missing': 115,
'atp/field/postcode/missing': 115,
'atp/field/street_address/missing': 115,
'atp/field/twitter/missing': 115,
'atp/field/website/invalid': 2, …
```
=> Add Meta Spider

locations/spiders/albertsons.py
These are the ones in use in NSI
=> [Albertsons] Update wikidata codes

locations/spiders/auto_zone_us.py
Possibly a proxy thing. We'll see
=> [AutoZoneUS] Fix spider

locations/spiders/shellrecharge.py
Hi,
This is my first commit to alltheplaces, I'm adding category to shellrecharge.
Any feedback will be much appreciated!
Thanks,
=> [ShellRecharge] Add category 

locations/spiders/burger_king_fr.py
Stats:
```json
{
"atp/brand/Burger King": 522,
"atp/brand_wikidata/Q177054": 522,
"atp/category/amenity/fast_food": 522,
"atp/field/city/missing": 522,
"atp/field/country/from_spider_name": 522,
"atp/field/email/missing": 522,
"atp/field/image/missing": 522,
"atp/field/opening_hours/missing": 4,
"atp/field/phone/missing": 13,
"atp/field/postcode/missing": 522,
"atp/field/state/missing": 522,
"atp/field/street_address/missing": 522,
"atp/field/twitter/missing": 522,
"atp/field/website/invalid": 1,
"atp/nsi/cc_match": 522,
"downloader/request_bytes": 236050,
"downloader/request_count": 524,
"downloader/request_method_count/GET": 524,
"downloader/response_bytes": 2676479,
"downloader/response_count": 524,
"downloader/response_status_count/200": 523, …
```
=> [Burger King FR] add spider (522 locations)

locations/spiders/express.py
```python
{'atp/brand/Express': 335,
'atp/brand/Express - CLOSED': 1,
'atp/brand/Express - Closed': 5,
'atp/brand/Express Factory Outlet': 194,
'atp/brand/Express Men': 1,
'atp/brand_wikidata/Q1384784': 536,
'atp/category/shop/clothes': 536,
'atp/cdn/cloudflare/response_count': 645,
'atp/cdn/cloudflare/response_status_count/200': 645,
'atp/field/email/missing': 536,
'atp/field/image/missing': 536,
'atp/field/twitter/missing': 536,
'atp/nsi/match_failed': 536,
'downloader/request_bytes': 351285,
'downloader/request_count': 645,
'downloader/request_method_count/GET': 645,
'downloader/response_bytes': 28489730,
'downloader/response_count': 645, …
```
=> [express] Added Shop=Clothes category (536 items)

locations/spiders/follett.py
```python
{'atp/category/shop/books': 928,
'atp/field/brand/missing': 928,
'atp/field/brand_wikidata/missing': 928,
'atp/field/email/missing': 928,
'atp/field/image/missing': 928,
'atp/field/lat/missing': 928,
'atp/field/lon/missing': 928,
'atp/field/opening_hours/missing': 399,
'atp/field/twitter/missing': 897,
'downloader/exception_count': 8,
'downloader/exception_type_count/twisted.internet.error.NoRouteError': 7,
'downloader/exception_type_count/twisted.internet.error.TimeoutError': 1,
'downloader/request_bytes': 498310,
'downloader/request_count': 1009,
'downloader/request_method_count/GET': 1009,
'downloader/response_bytes': 8473420,
'downloader/response_count': 1001, …
```
=> [follett] Added category for brand (928 items)

locations/spiders/norma_de.py
Hi,
Fixed regex to get the missing attributes like city, postcode and co-ordinates.
Thanks,
=> [norma_de] fix spider (608 items)

locations/spiders/kfc_de.py
Stats:
```json
{
"atp/brand/KFC": 207,
"atp/brand_wikidata/Q524757": 207,
"atp/category/amenity/fast_food": 207,
"atp/closed_check": 6,
"atp/field/country/from_spider_name": 207,
"atp/field/email/missing": 207,
"atp/field/image/missing": 207,
"atp/field/opening_hours/missing": 5,
"atp/field/phone/missing": 207,
"atp/field/postcode/missing": 1,
"atp/field/state/missing": 207,
"atp/field/twitter/missing": 207,
"atp/nsi/cc_match": 207,
"downloader/request_bytes": 269,
"downloader/response_bytes": 40078,
"elapsed_time_seconds": 0.745599,
"finish_time": …
```
=> [KFC DE] add spider (207 locations)

locations/spiders/distriktstandvarden_se.py
No coords unfortunately, but I'm asking them to add them.
=> [DistriktstandvardenSE] Add spider

locations/spiders/mercy.py
Added a couple more spiders from the unmatched category types.
```python
{'atp/brand/Mercy': 1538,
'atp/brand_wikidata/Q30289045': 1538,
'atp/category/amenity/centre': 29,
'atp/category/amenity/clinic': 57,
'atp/category/amenity/doctors': 834,
'atp/category/amenity/hospital': 127,
'atp/category/amenity/pharmacy': 54,
'atp/category/amenity/social_centre': 56,
'atp/category/healthcare/counselling': 18,
'atp/category/healthcare/laboratory': 156,
'atp/category/healthcare/midwife': 8,
'atp/category/healthcare/physiotherapist': 100,
'atp/category/healthcare/vaccination_centre': 4,
'atp/category/missing': 95,
'atp/category/multiple': 1072, …
```
=> [mercy] Added more categories for mercy spider (1538 items)

locations/categories.py, locations/spiders/wyndham.py
Stats:
```json
{
"atp/brand/AmericInn": 218,
"atp/brand/Baymont by Wyndham": 544,
"atp/brand/Caesars Rewards": 13,
"atp/brand/Days Inn": 1512,
"atp/brand/Dazzler": 14,
"atp/brand/Dolce Hotels and Resorts": 18,
"atp/brand/ECHO Suites": 7,
"atp/brand/Esplendor by Wyndham": 9,
"atp/brand/Hawthorn Suites by Wyndham": 74,
"atp/brand/Howard Johnson": 286,
"atp/brand/La Quinta by Wyndham": 917,
"atp/brand/Microtel Inns & Suites": 363,
"atp/brand/Ramada": 923,
"atp/brand/Registry Collection": 17,
"atp/brand/Super 8": 2049,
"atp/brand/TRYP": 55,
"atp/brand/Trademark Collection by Wyndham": 244,
"atp/brand/Travelodge": 447,
"atp/brand/Vienna House": 40,
"atp/brand/Wingate by Wyndham": 209,
"atp/brand/Wyndham Alltra": 4,
"atp/brand/Wyndham Garden": 162,
"atp/brand/Wyndham Grand": 79, …
```
=> [wyndham] add category

locations/spiders/peugeot_se.py
```python
{'atp/brand/Peugeot': 94,
'atp/brand_wikidata/Q6742': 94,
'atp/category/shop/car': 68,
'atp/category/shop/car_repair': 25,
'atp/field/country/from_spider_name': 94,
'atp/field/opening_hours/missing': 94,
'atp/field/operator/missing': 94,
'atp/field/operator_wikidata/missing': 94,
'atp/field/street_address/missing': 94,
'atp/nsi/category_match': 93,
'downloader/request_bytes': 804,
'downloader/response_bytes': 10553, …
```
=> [peugeot_se] Added categories for peugeot (94 items)

locations/spiders/kfc_ph.py
Stats:
```json
{
"atp/brand/KFC": 340,
"atp/brand_wikidata/Q524757": 340,
"atp/category/amenity/fast_food": 340,
"atp/field/email/missing": 340,
"atp/field/image/missing": 340,
"atp/field/operator/missing": 340,
"atp/field/operator_wikidata/missing": 340,
"atp/nsi/cc_match": 340,
"downloader/request_bytes": 203933,
"downloader/request_count": 447,
"downloader/request_method_count/GET": 447,
"downloader/response_bytes": 3797942,
"downloader/response_count": 447,
"downloader/response_status_count/200": 447,
"elapsed_time_seconds": 546.620175,
"finish_time": "2023-12-05T13:19:31.490747+00:00",
"httpcompression/response_bytes": 16962248,
"httpcompression/response_count": 447,
"item_scraped_count": 340, …
```
=> [KFC PH] add spider (340 locations)

locations/spiders/hopdoddy_burger_bar.py
Created Wikidata page and made PR for [NSI](https://github.com/osmlab/name-suggestion-index/pull/9011)
=> [hopdoddy_burger_bar] Added wikidata qcode and brand for HopDoddy Burger Bar (47 items)

locations/spiders/catherines.py, locations/spiders/curves.py, locations/spiders/floor_and_decor.py, locations/spiders/jim_n_nicks_bbq.py
These spiders are broken & require some rework, I don't really have time to fix them now, but at least I'll contribute by adding missing wikidata.
=> [jim_n_nicks][floor_and_decor][curves][catherines] add brand wikidata

locations/spiders/cafe_zupas.py
Created Wikidata Page and added to [NSI](https://github.com/osmlab/name-suggestion-index/pull/9004).
=> [cafe_zupas] Added wikidata qcode

locations/spiders/medical_city_healthcare.py
```python
{'atp/brand/Medical City Healthcare': 120,
'atp/category/amenity/clinic': 56,
'atp/category/amenity/hospital': 40,
'atp/category/healthcare/psychotherapist': 4,
'atp/category/healthcare/rehabilitation': 3,
'atp/category/missing': 17,
'atp/category/multiple': 96,
'atp/field/brand_wikidata/missing': 120,
'atp/field/country/from_reverse_geocoding': 120,
'atp/field/email/missing': 120,
'atp/field/image/missing': 120,
'atp/field/opening_hours/missing': 120,
'atp/field/operator/missing': 120,
'atp/field/operator_wikidata/missing': 120,
'atp/field/twitter/missing': 120,
'atp/medical_city_healthcare/unmatched_category/ Hospital': 1,
'atp/medical_city_healthcare/unmatched_category/Cancer_Center': 1, …
```
=> [medical_city_healthcare] Added categories (120 items)

locations/spiders/tatneft_ru.py
Stats:
```json
{
"atp/brand/Татнефть": 832,
"atp/brand_wikidata/Q1616858": 832,
"atp/category/amenity/fuel": 832,
"atp/field/city/missing": 832,
"atp/field/country/from_spider_name": 832,
"atp/field/email/missing": 832,
"atp/field/image/missing": 34,
"atp/field/name/missing": 832,
"atp/field/opening_hours/missing": 832,
"atp/field/operator/missing": 832,
"atp/field/operator_wikidata/missing": 832,
"atp/field/phone/missing": 832,
"atp/field/postcode/missing": 832,
"atp/field/street_address/missing": 832,
"atp/field/twitter/missing": 832,
"atp/field/website/missing": 832,
"atp/nsi/category_match": 832,
"atp/tatneft_ru/feature/failed/1": 508,
"atp/tatneft_ru/feature/failed/10": 81,
"atp/tatneft_ru/feature/failed/13": 63,
"atp/tatneft_ru/feature/failed/14": 689, …
```
=> [tatneft_ru] add spider (832 locations)

locations/spiders/mt_bank_us.py
Rel: https://github.com/osmlab/name-suggestion-index/issues/9023
```python
{'atp/brand/M&T Bank': 1616,
'atp/brand_wikidata/Q3272257': 1616,
'atp/category/amenity/atm': 681,
'atp/category/amenity/bank': 935,
'atp/cdn/cloudflare/response_count': 1632,
'atp/cdn/cloudflare/response_status_count/200': 1632,
'atp/field/city/missing': 1616,
'atp/field/email/missing': 1616,
'atp/field/name/missing': 1616,
'atp/field/operator/missing': 1616,
'atp/field/operator_wikidata/missing': 1616,
'atp/nsi/category_match': 1616,
'atp/operator/M&T Bank': 681,
'atp/operator_wikidata/Q3272257': 681,
'downloader/request_bytes': 926361,
'downloader/request_count': 1632,
'downloader/request_method_count/GET': 1632, …
```
=> [MTBankUS] Add spider

locations/spiders/familia_ru.py
Stats:
```json
{
"atp/brand/Familia": 440,
"atp/category/shop/clothes": 440,
"atp/field/brand_wikidata/missing": 440,
"atp/field/city/missing": 440,
"atp/field/country/from_spider_name": 440,
"atp/field/email/missing": 440,
"atp/field/image/missing": 440,
"atp/field/operator/missing": 440,
"atp/field/operator_wikidata/missing": 440,
"atp/field/postcode/missing": 440,
"atp/field/state/missing": 440,
"atp/field/twitter/missing": 440,
"atp/field/website/missing": 440,
"downloader/request_bytes": 602,
"downloader/response_bytes": 76325,
"elapsed_time_seconds": 1.902127, …
```
=> [familia_ru] add spider (440 locations)

locations/spiders/fix_price.py
POIs for 8 countries are available.
Stats:
```json
{
"atp/brand/Fix Price": 6275,
"atp/brand_wikidata/Q4038791": 6275,
"atp/category/shop/variety_store": 6275,
"atp/cdn/cloudflare/response_count": 10,
"atp/cdn/cloudflare/response_status_count/200": 9,
"atp/cdn/cloudflare/response_status_count/404": 1,
"atp/field/city/missing": 6275,
"atp/field/email/missing": 6275,
"atp/field/image/missing": 6275,
"atp/field/name/missing": 6275,
"atp/field/opening_hours/missing": 38,
"atp/field/operator/missing": 6275,
"atp/field/operator_wikidata/missing": 6275,
"atp/field/phone/missing": 6275,
"atp/field/postcode/missing": 6275,
"atp/field/state/missing": 6275,
"atp/field/street_address/missing": 6275,
"atp/field/twitter/missing": 6275,
"atp/field/website/missing": 6275,
"atp/nsi/perfect_match": 6275, …
```
=> [fix_price] add spider (6275 locations)

locations/spiders/bannerhealth.py
Adding category to bannerhealth
=> [bannerhealth] added category

locations/spiders/interior_health_ca.py
Adding category to interior_health_ca
=> [interior_health_ca] added category

locations/spiders/nutrition_warehouse_au.py
Hi,
I'm adding category to nutrition_warehouse spider.
=> [nutrition_warehouse_au] added category

locations/spiders/lidl_cy.py, locations/spiders/lidl_ee.py, locations/spiders/lidl_lt.py, locations/spiders/lidl_lv.py
Added some more lidl country spiders.
=> [lidl_lt][lidl_cy][lidl_ee][lidl_lv] Added new lidl country spiders

locations/spiders/best_in_parking.py
Stats:
```json
{
"atp/category/amenity/parking": 169,
"atp/field/brand/missing": 169,
"atp/field/brand_wikidata/missing": 169,
"atp/field/city/missing": 169,
"atp/field/email/missing": 169,
"atp/field/opening_hours/missing": 169,
"atp/field/phone/missing": 169,
"atp/field/postcode/missing": 2,
"atp/field/state/missing": 169,
"atp/field/street_address/missing": 7,
"atp/field/twitter/missing": 169,
"atp/nsi/perfect_match": 169,
"atp/operator/Best in Parking": 169,
"atp/operator_wikidata/Q112118218": 169,
"downloader/request_bytes": 650,
"downloader/response_bytes": 153187,
"elapsed_time_seconds": 1.999895, …
```
=> [Best in Parking] add spider (169 locations)

locations/spiders/tobys_sports_ph.py
Adding category to tobys_sports_ph
=> [tobys_sports_ph] add category

locations/spiders/goodlife_pharmacy_ke.py
Hi,
Adding category to goodlife_pharmacy_ke
Thanks,
=> [goodlife_pharmacy_ke] add category

locations/spiders/betts_au.py
=> [betts_au] add category

locations/spiders/scotmid.py
Added supermarket and funeral directors categories for this. Based on type.
=> [scotmid] Added Categories for scotmid

locations/spiders/burger_king_br.py
Minor amount of hours (32) is bit messy - `%I:%M%p` mixed with `%H:%M`.
Stats:
```json
{
"atp/brand/Burger King": 910,
"atp/brand_wikidata/Q177054": 910,
"atp/category/amenity/fast_food": 910,
"atp/field/country/from_spider_name": 910,
"atp/field/email/missing": 910,
"atp/field/image/missing": 910,
"atp/field/opening_hours/missing": 235,
"atp/field/operator/missing": 910,
"atp/field/operator_wikidata/missing": 910,
"atp/field/phone/missing": 910,
"atp/field/postcode/missing": 910,
"atp/field/twitter/missing": 910,
"atp/nsi/cc_match": 910,
"downloader/request_bytes": 897,
"downloader/request_method_count/POST": 1,
"downloader/response_bytes": 83172, …
```
=> [burger_king_br] add spider (910 locations)

locations/spiders/tacobell.py
```python
{'atp/brand/Taco Bell': 8204,
'atp/brand_wikidata/Q111972226': 30,
'atp/brand_wikidata/Q752941': 8174,
'atp/category/amenity/fast_food': 8204,
'atp/cdn/cloudflare/response_count': 12932,
'atp/cdn/cloudflare/response_status_count/200': 12931,
'atp/field/city/missing': 174,
'atp/field/country/from_website_url': 174,
'atp/field/email/missing': 8204,
'atp/field/opening_hours/missing': 672,
'atp/field/operator/missing': 8204,
'atp/field/operator_wikidata/missing': 8204,
'atp/field/phone/missing': 54,
'atp/field/state/missing': 137,
'atp/field/twitter/missing': 8204,
'atp/nsi/perfect_match': 8204,
'downloader/request_bytes': 5003669,
'downloader/request_count': 12932,
'downloader/request_method_count/GET': 12932, …
```
=> [TacoBell] Collect FR website and improve brand

locations/spiders/lidl_at.py, locations/spiders/lidl_be.py, locations/spiders/lidl_ch.py, locations/spiders/lidl_cy.py, locations/spiders/lidl_cz.py, locations/spiders/lidl_de.py, locations/spiders/lidl_dk.py, locations/spiders/lidl_ee.py, locations/spiders/lidl_es.py, locations/spiders/lidl_fi.py, locations/spiders/lidl_fr.py, locations/spiders/lidl_gr.py, locations/spiders/lidl_hu.py, locations/spiders/lidl_it.py, locations/spiders/lidl_lt.py, locations/spiders/lidl_lv.py, locations/spiders/lidl_nl.py, locations/spiders/lidl_pl.py, locations/spiders/lidl_pt.py, locations/spiders/lidl_se.py, locations/spiders/lidl_sk.py
I made lidl_at and lidl_be parent spiders as many others were the almost the exact same except for days, key, dataset_id, and dataset_name.
=> [lidl] Cleaned up spiders.

locations/spiders/elysium_healthcare.py
Added categories to the best of my ability in what the descriptions of each division gave. 
Neurological, Mental Health and Wellbeing, Learning Disabilities & Autism, and Children & Education.
```python
{'atp/brand/Elysium Healthcare': 86,
'atp/brand_wikidata/Q39086513': 86,
'atp/category/amenity/social_facility': 76,
'atp/category/healthcare/yes': 9,
'atp/category/multiple': 2,
'atp/field/city/missing': 86,
'atp/field/email/missing': 86,
'atp/field/opening_hours/missing': 86,
'atp/field/phone/missing': …
```
=> [elysium_healthcare] Added categories by the types of services offered. (86 items)

locations/spiders/ribcrib_us.py
Hi,
Adding category to ribcrib_us.
Thanks,
=> [ribcrib_us] add category

locations/categories.py
Adding animal_boarding category to enum to update https://github.com/alltheplaces/alltheplaces/pull/6508
=> adding category to enum

locations/spiders/burger_king_ru.py
Something changed on the website. We now need to ignore robots.txt and give api some headers.
=> [burger_king_ru] fix broken spider

locations/hours.py, locations/spiders/coach.py, locations/spiders/coach_ca.py, locations/spiders/coach_us.py
Coach US
```python
{'atp/brand/Coach': 301,
'atp/brand_wikidata/Q727697': 301,
'atp/category/shop/bag': 301,
'atp/cdn/cloudflare/response_count': 366,
'atp/cdn/cloudflare/response_status_count/200': 366,
'atp/field/operator/missing': 301,
'atp/field/operator_wikidata/missing': 301,
'atp/nsi/perfect_match': 301,
'downloader/request_bytes': 210048,
'downloader/request_count': 367,
'downloader/request_method_count/GET': 367,
'downloader/response_bytes': 11512922,
'downloader/response_count': 367,
'downloader/response_status_count/200': 367,
'dupefilter/filtered': 25,
'elapsed_time_seconds': 4.451809,
'finish_time': datetime.datetime(2023, 12, 18, 11, 56, 23, 2705, …
```
=> [Coach] Add spiders

locations/spiders/yarche_ru.py
Stats:
```json
{
"atp/brand/Ярче!": 964,
"atp/brand_wikidata/Q102254456": 964,
"atp/category/shop/supermarket": 964,
"atp/field/city/missing": 964,
"atp/field/country/from_spider_name": 964,
"atp/field/email/missing": 964,
"atp/field/image/missing": 964,
"atp/field/lat/missing": 1,
"atp/field/lon/missing": 1,
"atp/field/name/missing": 964,
"atp/field/opening_hours/missing": 964,
"atp/field/operator/missing": 964,
"atp/field/operator_wikidata/missing": 964,
"atp/field/phone/missing": 964,
"atp/field/postcode/missing": 964,
"atp/field/state/missing": 964,
"atp/field/twitter/missing": 964,
"atp/field/website/missing": 964,
"atp/nsi/perfect_match": 964,
"downloader/request_bytes": 6916,
"downloader/request_count": 16,
"downloader/request_method_count/GET": 16,
"downloader/response_bytes": …
```
=> [yarche_ru] add spider (964 locations)

locations/spiders/pet_paradise.py
Adding category and wikidata to pet paradise
=> [pet_paradise] add category

locations/spiders/mkrf_ru.py
Adjusted `ref` to be unique which allows to disable `no_refs`.
Stats:
```json
{
"atp/category/amenity/cinema": 1456,
"atp/category/amenity/community_centre": 23163,
"atp/category/amenity/library": 22663,
"atp/category/tourism/museum": 5919,
"atp/field/brand/missing": 53201,
"atp/field/brand_wikidata/missing": 53201,
"atp/field/city/missing": 53201,
"atp/field/country/from_spider_name": 53201,
"atp/field/email/invalid": 21,
"atp/field/email/missing": 17614,
"atp/field/opening_hours/missing": 500,
"atp/field/operator/missing": 53201,
"atp/field/operator_wikidata/missing": 53201,
"atp/field/phone/invalid": 428,
"atp/field/phone/missing": 15626,
"atp/field/postcode/missing": 53201,
"atp/field/state/missing": 53201,
"atp/field/street_address/missing": 1003,
"atp/field/twitter/missing": 53201, …
```
=> [mkrf_rf] disable no_refs

locations/spiders/the_brass_tap_us.py
=> Add The Brass Tap (US) (43 locations)

locations/spiders/williams_sonoma_us_ca.py, locations/user_agents.py
=> Add Williams Sonoma (US/CA) (163 locations)

locations/spiders/clark_rubber_au.py
=> Add Clark Rubber (AU) (60 locations)

locations/spiders/battery_world_au.py
=> Add Battery World (AU) (110 locations)

locations/spiders/lou_malnatis_pizzeria_us.py
=> Add Lou Malnati's Pizzeria (US) (80 locations)

locations/spiders/bishops_arms_se.py
Rel: https://github.com/osmlab/name-suggestion-index/pull/9095
```python
{'atp/brand/Bishops Arms': 46,
'atp/brand_wikidata/Q10430084': 46,
'atp/category/amenity/pub': 39,
'atp/category/tourism/hotel': 7,
'atp/field/name/missing': 46,
'atp/field/operator/missing': 46,
'atp/field/operator_wikidata/missing': 46,
'atp/field/state/missing': 46,
'atp/field/twitter/missing': 46,
'atp/nsi/brand_missing': 46,
'downloader/request_bytes': 18103,
'downloader/request_count': 49,
'downloader/request_method_count/GET': 49,
'downloader/response_bytes': 631258,
'downloader/response_count': 49,
'downloader/response_status_count/200': 49,
'elapsed_time_seconds': 1.621565,
'finish_time': datetime.datetime(2023, 12, 30, 11, 41, 6, 433138, tzinfo=datetime.timezone.utc), …
```
=> [BishopsArmsSE] Add Spider

locations/spiders/verniy_ru.py
Stats:
```json
{
"atp/brand/Верный": 1223,
"atp/brand_wikidata/Q110037370": 1223,
"atp/category/shop/supermarket": 1223,
"atp/field/brand/missing": 1223,
"atp/field/city/missing": 1223,
"atp/field/country/from_spider_name": 1223,
"atp/field/email/missing": 1223,
"atp/field/image/missing": 1223,
"atp/field/name/missing": 1223,
"atp/field/opening_hours/missing": 27,
"atp/field/operator/missing": 1223,
"atp/field/operator_wikidata/missing": 1223,
"atp/field/phone/missing": 1223,
"atp/field/postcode/missing": 1223,
"atp/field/state/missing": 1223,
"atp/field/street_address/missing": 1223,
"atp/field/twitter/missing": 1223,
"atp/field/website/missing": 1223,
"atp/nsi/perfect_match": 1223,
"downloader/request_bytes": 611, …
```
=> [vernyi_ru] add spider (1223 locations)

locations/spiders/damira_gb.py
Rel: https://github.com/osmlab/name-suggestion-index/commit/0a7d4a624a6ca58b33c6401e70e372cfc1daa7a5
```python
{'atp/brand/Damira': 33,
'atp/brand_wikidata/Q117210318': 33,
'atp/category/missing': 33,
'atp/field/city/missing': 33,
'atp/field/country/from_spider_name': 33,
'atp/field/email/missing': 33,
'atp/field/name/missing': 33,
'atp/field/opening_hours/missing': 33,
'atp/field/operator/missing': 33,
'atp/field/operator_wikidata/missing': 33,
'atp/field/phone/missing': 33,
'atp/field/state/missing': 33,
'atp/field/street_address/missing': 33,
'atp/field/twitter/missing': 33,
'atp/nsi/brand_missing': 33, …
```
=> [DamiraGB] Add spider

locations/spiders/z_energy_nz.py
There are two uses of @data-props, and only one is wanting to be parsed.
=> z_energy_nz: fix spider

locations/categories.py, locations/spiders/qstar_se.py
Stats:
```json
{
"atp/brand/Bilisten": 10,
"atp/brand/Pump": 2,
"atp/brand/Qstar": 315,
"atp/brand_wikidata/Q10647961": 315,
"atp/category/amenity/fuel": 330,
"atp/field/brand/missing": 3,
"atp/field/brand_wikidata/missing": 15,
"atp/field/city/missing": 99,
"atp/field/country/from_spider_name": 330,
"atp/field/email/missing": 330,
"atp/field/image/missing": 330,
"atp/field/opening_hours/missing": 330,
"atp/field/operator/missing": 330,
"atp/field/operator_wikidata/missing": 330,
"atp/field/phone/missing": 2,
"atp/field/postcode/missing": 330,
"atp/field/state/missing": 330,
"atp/field/street_address/missing": 99,
"atp/field/twitter/missing": 330,
"atp/field/website/missing": 330,
"atp/nsi/category_match": 315,
"downloader/request_bytes": 657, …
```
=> [qstar_se] add category + fuel types

locations/spiders/bever_nl.py
Rel: https://github.com/osmlab/name-suggestion-index/pull/9109
```python
{'atp/brand/Bever': 42,
'atp/brand_wikidata/Q123596881': 42,
'atp/category/missing': 42,
'atp/field/country/from_spider_name': 42,
'atp/field/operator/missing': 42,
'atp/field/operator_wikidata/missing': 42,
'atp/field/state/missing': 42,
'atp/nsi/brand_missing': 42,
'downloader/request_bytes': 17037,
'downloader/response_bytes': 5527011,
'downloader/response_count': 44,
'downloader/response_status_count/200': 44,
'elapsed_time_seconds': 3.484008,
'finish_time': datetime.datetime(2024, 1, 2, 10, 54, 14, …
```
=> [BeverNL] Add Spider

locations/spiders/travelcenters_of_america_us.py, locations/structured_data_spider.py
'atp/brand/Petro': 76,
'atp/brand/TA': 181,
'atp/brand/TA Express': 43,
=> travelcenters_of_america_us: fix spider

locations/spiders/bunnings.py
There is a new method for obtaining a guest authorization bearer token.
=> bunnings: fix spider

locations/dict_parser.py, locations/spiders/cloud_9_smoke_shop_australia_au.py
Brand has switched to StockistSpider.
=> cloud_9_smoke_shop_australia_au: fix spider

locations/spiders/sleep_doctor_au.py
Brand no longer users ShopAppsSpider.
=> sleep_doctor_au: fix spider

locations/spiders/stc_se.py
These are gyms - add category.
```python
{'atp/brand/STC': 213,
'atp/brand_wikidata/Q124061743': 213,
'atp/category/leisure/fitness_centre': 213,
'atp/field/country/from_spider_name': 213,
'atp/field/image/missing': 213,
'atp/field/name/missing': 213,
'atp/field/operator/missing': 213,
'atp/field/operator_wikidata/missing': 213,
'atp/field/state/missing': 213,
'atp/field/twitter/missing': 213,
'atp/nsi/brand_missing': 213,
'downloader/request_bytes': 609,
'downloader/response_bytes': 95450,
'elapsed_time_seconds': 3.538983,
'finish_time': datetime.datetime(2024, 1, 9, 14, 9, 16, 682141, …
```
=> [StcSE] Add category

locations/spiders/rowlands_pharmacy_gb.py
```python
{'atp/brand/Rowlands Pharmacy': 362,
'atp/brand_wikidata/Q62663235': 362,
'atp/category/amenity/pharmacy': 362,
'atp/category/multiple': 362,
'atp/field/email/missing': 362,
'atp/field/image/missing': 359,
'atp/field/operator/missing': 362,
'atp/field/operator_wikidata/missing': 362,
'atp/field/twitter/missing': 362,
'atp/nsi/perfect_match': 362,
'downloader/response_bytes': 39630,
'elapsed_time_seconds': 0.764641,
'finish_time': datetime.datetime(2024, 1, 9, 14, 2, 16, 396356, tzinfo=datetime.timezone.utc),
'httpcache/hit': …
```
=> [RowlandsPharmacyGB] Add spider

locations/spiders/genghis_grill_us.py
This is a Mongolian BBQ style restaurant.
```python
{'atp/brand/Genghis Grill': 45,
'atp/brand_wikidata/Q29470710': 45,
'atp/category/amenity/restaurant': 45,
'atp/field/country/from_spider_name': 45,
'atp/field/email/missing': 45,
'atp/field/image/dropped': 45,
'atp/field/image/missing': 45,
'atp/field/name/missing': 45,
'atp/field/operator/missing': 45,
'atp/field/operator_wikidata/missing': 45,
'atp/nsi/brand_missing': 45,
'downloader/request_bytes': 19897,
'downloader/request_count': 49,
'downloader/request_method_count/GET': 49,
'downloader/response_bytes': 599450,
'downloader/response_count': 49,
'downloader/response_status_count/200': 49,
'elapsed_time_seconds': 59.756821,
'finish_time': datetime.datetime(2024, 1, 9, 15, 16, 36, 821883, …
```
=> [GenghisGrillUS] Add category

locations/spiders/hunting_and_fishing_nz.py
{'atp/brand/Hunting & Fishing New Zealand': 39,
'atp/brand_wikidata/Q124062188': 39,
'atp/category/shop/outdoor': 39,
'atp/field/country/from_spider_name': 39,
'atp/field/image/missing': 39,
'atp/field/operator/missing': 39,
'atp/field/operator_wikidata/missing': 39,
'atp/field/state/missing': 39,
'atp/field/twitter/missing': 39,
'atp/nsi/brand_missing': 39,
'downloader/request_bytes': 639,
'downloader/response_bytes': 77785,
'elapsed_time_seconds': 2.418126,
'finish_time': datetime.datetime(2024, 1, 10, 14, 59, 50, 943740, …
=> [HuntingAndFishingNZ] Add category

locations/spiders/festival_foods_us.py
{'atp/brand/Festival Foods': 41,
'atp/brand_wikidata/Q5445707': 41,
'atp/category/shop/supermarket': 41,
'atp/field/country/from_spider_name': 30,
'atp/field/phone/invalid': 41,
'atp/nsi/brand_missing': 41,
'downloader/response_bytes': 51496,
'elapsed_time_seconds': 3.365838,
'finish_time': datetime.datetime(2024, 1, 10, 14, 43, 15, 546871, tzinfo=datetime.timezone.utc), …
=> [FestivalFoodsUS] Add category

locations/spiders/rsea_safety_au.py
{'atp/brand/RSEA Safety': 85,
'atp/brand_wikidata/Q122418895': 85,
'atp/category/shop/safety_equipment': 85,
'atp/field/country/from_spider_name': 62,
'atp/field/email/missing': 81,
'atp/field/image/missing': 85,
'atp/field/operator/missing': 85,
'atp/field/operator_wikidata/missing': 85,
'atp/field/twitter/missing': 85,
'atp/nsi/brand_missing': 85,
'downloader/request_bytes': 1498,
'downloader/response_bytes': 162321,
'elapsed_time_seconds': 5.532064,
'finish_time': datetime.datetime(2024, 1, 10, 13, 48, 9, 529129, …
=> [RSEASafetyAU] Add category

locations/spiders/dirt_cheap_us.py
{'atp/brand/Dirt Cheap': 68,
'atp/brand_wikidata/Q123013019': 68,
'atp/category/shop/variety_store': 68,
'atp/nsi/brand_missing': 68,
'downloader/response_bytes': 62376,
'elapsed_time_seconds': 2.928973,
'finish_time': datetime.datetime(2024, 1, 10, 9, 2, 44, 949357, tzinfo=datetime.timezone.utc),
'item_scraped_count': 68,
'log_count/DEBUG': 81,
'memusage/max': …
=> [DirtCheapUS] Add category

locations/spiders/bank_of_ireland.py
```python
{'atp/brand/Bank of Ireland': 201,
'atp/brand_wikidata/Q806689': 201,
'atp/category/amenity/atm': 19,
'atp/category/amenity/bank': 182,
'atp/field/city/missing': 42,
'atp/field/country/from_reverse_geocoding': 198,
'atp/field/country/missing': 3,
'atp/field/email/missing': 201,
'atp/field/image/missing': 201,
'atp/field/name/missing': 19,
'atp/field/opening_hours/missing': 201,
'atp/field/operator/missing': 182,
'atp/field/operator_wikidata/missing': 182,
'atp/field/phone/missing': 201,
'atp/field/street_address/missing': 201,
'atp/field/twitter/missing': 201,
'atp/nsi/category_match': 201,
'atp/operator/Bank of Ireland': 19, …
```
=> [BankOfIreland] Add spider

locations/spiders/allied_irish_banks_ie.py
```python
{'atp/brand/AIB': 175,
'atp/brand_wikidata/Q1642179': 175,
'atp/category/amenity/bank': 175,
'atp/cdn/cloudflare/response_count': 178,
'atp/cdn/cloudflare/response_status_count/200': 178,
'atp/field/city/missing': 157,
'atp/field/country/from_spider_name': 175,
'atp/field/email/missing': 175,
'atp/field/image/dropped': 8,
'atp/field/opening_hours/missing': 24,
'atp/field/operator/missing': 175,
'atp/field/operator_wikidata/missing': 175,
'atp/field/phone/missing': 175,
'atp/field/postcode/missing': 175,
'atp/nsi/category_match': 175,
'downloader/request_bytes': 95292,
'downloader/request_count': 178,
'downloader/request_method_count/GET': 178,
'downloader/response_bytes': 1482155,
'downloader/response_count': 178, …
```
=> [AlliedIrishBanksIE] Add Spider

locations/spiders/supervalu_ie.py
```python
{'atp/brand/SuperValu': 221,
'atp/brand_wikidata/Q7642081': 221,
'atp/category/shop/supermarket': 221,
'atp/field/city/missing': 8,
'atp/field/country/from_spider_name': 221,
'atp/field/email/missing': 219,
'atp/field/image/missing': 221,
'atp/field/opening_hours/missing': 221,
'atp/field/operator/missing': 221,
'atp/field/operator_wikidata/missing': 221,
'atp/field/postcode/missing': 220,
'atp/field/twitter/missing': 221,
'atp/field/website/missing': 221,
'atp/nsi/perfect_match': 221,
'downloader/request_bytes': 609,
'downloader/response_bytes': 36528, …
```
=> [SupervaluIE] Add spider

locations/spiders/camera_house_au.py
{'atp/brand/Camera House': 50,
'atp/brand_wikidata/Q124062505': 50,
'atp/category/shop/camera': 50,
'atp/field/country/from_spider_name': 50,
'atp/nsi/brand_missing': 50,
'downloader/request_bytes': 637,
'downloader/response_bytes': 136510,
'elapsed_time_seconds': 3.539851,
'finish_time': datetime.datetime(2024, 1, 10, 11, 23, 38, 638253, tzinfo=datetime.timezone.utc),
'httpcompression/response_bytes': 2055, …
=> [CameraHouseAU] Add category

locations/spiders/compleat_angler_au.py
{'atp/brand/Compleat Angler': 34,
'atp/brand_wikidata/Q124062620': 34,
'atp/category/shop/fishing': 34,
'atp/field/country/from_spider_name': 34,
'atp/field/image/missing': 34,
'atp/field/operator/missing': 34,
'atp/field/operator_wikidata/missing': 34,
'atp/field/twitter/missing': 34,
'atp/field/website/missing': 34,
'atp/nsi/brand_missing': 34,
'downloader/request_bytes': 757,
'downloader/response_bytes': 45611,
'elapsed_time_seconds': 4.615791,
'finish_time': datetime.datetime(2024, 1, 10, 15, 24, 27, 447293, tzinfo=datetime.timezone.utc),
'item_scraped_count': 34,
'log_count/DEBUG': 47, …
=> [CompleatAnglerAU] Add category

locations/spiders/all_secure_self_storage_us.py
{'atp/brand/All Secure Self Storage': 32,
'atp/brand_wikidata/Q119141885': 32,
'atp/category/shop/storage_rental': 32,
'atp/field/city/missing': 32,
'atp/field/operator/missing': 32,
'atp/field/operator_wikidata/missing': 32,
'atp/field/postcode/missing': 32,
'atp/field/state/from_reverse_geocoding': 32,
'atp/field/street_address/missing': 32,
'atp/field/twitter/missing': 32,
'atp/field/website/missing': 32,
'atp/nsi/brand_missing': 32,
'downloader/response_bytes': 10468, …
=> [AllSecureSelfStorageUS] Add category

locations/pipelines/extract_gb_postcode.py, locations/spiders/tim_hortons_gb.py
Tim Hortons is expanding in the UK:
'atp/brand/Tim Hortons': 78,
'atp/brand_wikidata/Q175106': 78,
'atp/category/amenity/cafe': 78,
'atp/field/country/from_spider_name': 78,
'atp/field/email/missing': 78,
'atp/field/image/missing': 78,
'atp/field/opening_hours/missing': 78,
'atp/field/operator/missing': 78,
'atp/field/operator_wikidata/missing': 78,
'atp/field/phone/missing': 78,
'atp/field/state/missing': 78,
'atp/field/street_address/missing': 78,
'atp/field/twitter/missing': 78,
'atp/nsi/cc_match': 78,
'downloader/response_bytes': 179110,
'elapsed_time_seconds': 0.656679,
=> [tim_hortons_gb] add new spider (78 locations)

locations/spiders/woods_coffee_us.py
{'atp/brand/Woods Coffee': 20,
'atp/brand_wikidata/Q8033255': 20,
'atp/category/amenity/cafe': 20,
'downloader/response_bytes': 3397,
'elapsed_time_seconds': 1.608385,
'finish_time': datetime.datetime(2024, 1, 11, 14, 6, …
=> [WoodsCoffeeUS] Add category

locations/spiders/verve_coffee_roasters.py
{'atp/brand/Verve Coffee Roasters': 14,
'atp/brand_wikidata/Q17030230': 14,
'atp/category/amenity/cafe': 14,
'atp/field/country/from_reverse_geocoding': 14,
'atp/field/postcode/missing': 14,
'atp/field/street_address/missing': 14,
'atp/nsi/brand_missing': 14,
'downloader/request_bytes': 340,
'downloader/response_bytes': 40464,
'elapsed_time_seconds': 1.684707,
'finish_time': …
=> [VerveCoffeeRoasters] Add category

locations/spiders/myhouse_au.py
{'atp/brand/MyHouse': 30,
'atp/brand_wikidata/Q28854270': 30,
'atp/category/shop/houseware': 30,
'atp/field/email/missing': 30,
'atp/field/image/missing': 30,
'atp/nsi/brand_missing': 30,
'downloader/response_bytes': 5098,
'elapsed_time_seconds': 2.455756,
'finish_time': datetime.datetime(2024, 1, 11, 9, 7, 6, 756927, tzinfo=datetime.timezone.utc),
'httpcompression/response_bytes': 28773, …
=> [MyHouseAU] Add category

locations/spiders/billini_au.py
{'atp/brand/Billini': 29,
'atp/brand_wikidata/Q117747826': 29,
'atp/category/shop/clothes': 29,
'atp/nsi/brand_missing': 29,
'downloader/response_bytes': 4107,
'elapsed_time_seconds': 2.674499,
'finish_time': datetime.datetime(2024, 1, 11, 9, 15, 31, …
=> [BilliniAU] Add category

locations/spiders/forcast_au.py
{'atp/brand/Forcast': 31,
'atp/brand_wikidata/Q118384540': 31,
'atp/category/shop/clothes': 31,
'atp/nsi/brand_missing': 31,
'downloader/response_bytes': 5543,
'elapsed_time_seconds': 3.096458,
'finish_time': datetime.datetime(2024, 1, 11, 9, 46, 42, …
=> [ForcastAU] Add category

locations/spiders/neverland_au.py
{'atp/brand/Neverland': 31,
'atp/brand_wikidata/Q117747218': 31,
'atp/category/shop/clothes': 31,
'atp/field/website/missing': 31,
'atp/nsi/brand_missing': 31,
'downloader/request_bytes': 856,
'downloader/response_bytes': 9996, …
=> [NeverlandAU] Add category

locations/spiders/dollar_curtains_and_blinds_au.py
{'atp/brand/dollar curtains+blinds': 31,
'atp/brand_wikidata/Q122430680': 31,
'atp/category/shop/houseware': 31,
'atp/field/street_address/missing': 31,
'atp/nsi/brand_missing': 31,
'downloader/request_bytes': 703,
'downloader/response_bytes': 5475,
'elapsed_time_seconds': 2.681231,
'finish_time': datetime.datetime(2024, 1, 11, 10, 9, 34, 293375, tzinfo=datetime.timezone.utc),
'httpcompression/response_bytes': 27175,
'item_scraped_count': …
=> [DollarCurtainsAndBlindsAU] Add category

locations/spiders/jo_mercer_au.py
{'atp/brand/Jo Mercer': 28,
'atp/brand_wikidata/Q117961451': 28,
'atp/category/shop/shoes': 28,
'atp/nsi/brand_missing': 28,
'downloader/response_bytes': 4281,
'elapsed_time_seconds': 3.079609,
'finish_time': datetime.datetime(2024, 1, 11, 11, 0, 11, 691882, …
=> [JoMercerAU] Add category

locations/spiders/captain_jays_us.py
{"atp/brand/Captain Jay's": 31,
'atp/brand_wikidata/Q119157361': 31,
'atp/category/amenity/restaurant': 31,
'atp/field/city/missing': 31,
'atp/field/postcode/missing': 31,
'atp/field/state/from_reverse_geocoding': 31,
'atp/field/street_address/missing': 31,
'atp/field/website/missing': 31,
'atp/nsi/brand_missing': 31,
'downloader/response_bytes': 9396,
'elapsed_time_seconds': 2.851712, …
=> [CaptainJaysUS] Add category

locations/spiders/william_penn_in.py
{'atp/brand/William Penn': 26,
'atp/brand_wikidata/Q122439152': 26,
'atp/category/shop/stationery': 26,
'atp/field/country/from_spider_name': 26,
'atp/field/email/missing': 26,
'atp/field/state/missing': 26,
'atp/field/street_address/missing': 26,
'atp/field/website/missing': 26,
'atp/nsi/brand_missing': 26,
'downloader/request_bytes': 698, …
=> [WilliamPennIN] Add category

locations/spiders/lands_end_us.py
{"atp/brand/Lands' End": 26,
'atp/brand_wikidata/Q839555': 26,
'atp/category/shop/clothes': 26,
'atp/field/country/from_spider_name': 26,
'atp/field/email/missing': 26,
'atp/field/website/missing': 26,
'atp/nsi/brand_missing': 26,
'downloader/request_bytes': 379,
'downloader/response_bytes': 3894,
'elapsed_time_seconds': 0.955329,
'finish_time': datetime.datetime(2024, 1, 11, 11, 51, 19, 541749, tzinfo=datetime.timezone.utc), …
=> [LandsEndUS] Add category

locations/spiders/tentworld_au.py
{'atp/brand/Tentworld': 15,
'atp/brand_wikidata/Q117747711': 15,
'atp/category/shop/outdoor': 15,
'atp/field/website/missing': 15,
'atp/nsi/brand_missing': 15,
'downloader/request_bytes': 841,
'downloader/response_bytes': 7469, …
=> [TentWorldAU] Add category

locations/spiders/ron_jon_surf_shop.py
{'atp/brand/Ron Jon Surf Shop': 13,
'atp/brand_wikidata/Q7363993': 13,
'atp/category/shop/surf': 13,
'atp/field/opening_hours/missing': 13,
'atp/nsi/brand_missing': 13,
'downloader/request_bytes': 671,
'downloader/response_bytes': 2882,
'elapsed_time_seconds': 2.383465,
'finish_time': datetime.datetime(2024, 1, 12, 10, 2, 52, 114310, …
=> [RonJonSurfShop] Add category

locations/spiders/paint_spot_au.py
{'atp/brand/Paint Spot': 15,
'atp/brand_wikidata/Q117852598': 15,
'atp/category/shop/paint': 15,
'atp/field/street_address/missing': 15,
'atp/field/website/invalid': 15,
'atp/nsi/brand_missing': 15,
'downloader/response_bytes': 16919,
'elapsed_time_seconds': 2.496611,
'finish_time': datetime.datetime(2024, 1, 12, 10, 47, 29, 115729, tzinfo=datetime.timezone.utc),
'httpcompression/response_bytes': 139755, …
=> [PaintSpotAU] Add category

locations/spiders/twoxu_au.py
{'atp/brand/2XU': 14,
'atp/brand_wikidata/Q16823650': 14,
'atp/category/shop/clothes': 14,
'atp/nsi/brand_missing': 14,
'downloader/response_bytes': 3001,
'elapsed_time_seconds': 2.801052,
'finish_time': datetime.datetime(2024, 1, 12, 11, 7, 39, 347091, tzinfo=datetime.timezone.utc), …
=> [TwoXUAU] Add category

locations/spiders/paddy_pallin_au.py
{'atp/brand/Paddy Pallin': 11,
'atp/brand_wikidata/Q117949623': 11,
'atp/category/shop/sports': 11,
'atp/field/country/from_spider_name': 11,
'atp/field/street_address/missing': 11,
'atp/nsi/brand_missing': 11,
'downloader/request_bytes': 7537,
'downloader/request_count': 13,
'downloader/request_method_count/GET': 12,
'downloader/response_bytes': 1056019,
'downloader/response_count': 13,
'downloader/response_status_count/200': 13,
'elapsed_time_seconds': 16.278371,
'finish_time': datetime.datetime(2024, 1, 12, 11, 16, 30, 583111, tzinfo=datetime.timezone.utc),
'httpcompression/response_bytes': 3585180, …
=> [PaddyPallinAU] Add category

locations/spiders/the_plantbase_store_gb.py
{'atp/brand/The Plantbase Store': 11,
'atp/brand_wikidata/Q119157083': 11,
'atp/category/shop/supermarket': 11,
'atp/field/city/missing': 11,
'atp/field/state/missing': 11,
'atp/field/street_address/missing': 11,
'atp/field/website/missing': 11,
'atp/nsi/brand_missing': 11,
'downloader/response_bytes': 8904,
'elapsed_time_seconds': 1.508812, …
=> [ThePlantbaseStoreGB] Add category

locations/spiders/sleep_doctor_au.py
{'atp/brand/Sleep Doctor': 10,
'atp/brand_wikidata/Q122435030': 10,
'atp/category/shop/bed': 10,
'atp/nsi/brand_missing': 10,
'downloader/request_bytes': 991,
'downloader/response_bytes': 28023,
'elapsed_time_seconds': 2.254055, …
=> [SleepDoctorAU] Add category

locations/spiders/manning_cartell_au.py
{'atp/brand/Manning Cartell': 7,
'atp/brand_wikidata/Q117746697': 7,
'atp/category/shop/clothes': 7,
'atp/field/operator/missing': 7,
'atp/field/operator_wikidata/missing': 7,
'atp/field/twitter/missing': 7,
'atp/nsi/brand_missing': 7,
'downloader/request_bytes': 850,
'downloader/response_bytes': 7354, …
=> [ManningCartellAU] Add category

locations/spiders/indie_kids_au.py
{'brand': 'Indie Kids',
'brand_wikidata': 'Q117746093',
'city': 'Bankstown Aerodrome',
'country': 'AU',
'email': None,
'extras': {'@spider': 'indie_kids_au', 'shop': 'clothes'},
'geometry': {'coordinates': [150.9968811, -33.9305838], 'type': 'Point'},
'name': 'Milperra',
'opening_hours': 'Mo-Fr 09:30-18:00; Sa-Su 09:00-18:00',
'phone': '+61 2 9139 1322',
'postcode': '2200',
'ref': '97',
'state': 'NSW',
'street_address': '343 Milperra Road',
'website': None}
2024-01-12 13:53:09 [scrapy.core.engine] INFO: Closing spider (finished)
2024-01-12 13:53:09 [locations.pipelines.duplicates] INFO: Dropped 0 duplicate items
2024-01-12 13:53:09 [scrapy.statscollectors] INFO: Dumping Scrapy stats:
{'atp/brand/Indie Kids': 6,
'atp/brand_wikidata/Q117746093': 6, …
=> [IndieKidsAU] Add category

locations/spiders/dusk_nz.py
{'atp/brand/dusk': 3,
'atp/brand_wikidata/Q120669167': 3,
'atp/category/shop/houseware': 3,
'downloader/response_bytes': 21699,
'elapsed_time_seconds': 1.632461,
'finish_time': datetime.datetime(2024, 1, 12, 14, 4, 43, 880315, …
=> [DuskNZ] Add category

locations/spiders/sams_club_mx.py
```python
{"atp/brand/Sam's Club": 171,
'atp/brand_wikidata/Q1972120': 171,
'atp/category/shop/wholesale': 171,
'atp/field/email/missing': 171,
'atp/field/image/missing': 171,
'atp/field/opening_hours/missing': 171,
'atp/field/operator/missing': 171,
'atp/field/operator_wikidata/missing': 171,
'atp/field/twitter/missing': 171,
'atp/field/website/missing': 171,
'atp/nsi/cc_match': 171,
'downloader/request_bytes': 995,
'downloader/response_bytes': 19066,
'elapsed_time_seconds': 4.048832,
'finish_time': …
```
=> [SamsClubMX] Add spider

locations/spiders/oxxo.py
'atp/brand/Oxxo': 17810,
'atp/brand_wikidata/Q1342538': 17810,
'atp/category/amenity/fuel': 327,
'atp/category/multiple': 327,
'atp/category/shop/convenience': 17483,
=> Add Oxxo (17810 locations)

.pre-commit-config.yaml, ci/restore_history.py, locations/spiders/bobevans_us.py, locations/spiders/dsk_bank_bg.py, locations/spiders/dunelm_gb.py, locations/spiders/empres_us.py, locations/spiders/fantastiko_bg.py, locations/spiders/fifththirdbank.py, locations/spiders/gadisa_es.py, locations/spiders/ica_se.py, locations/spiders/kipling_us.py, locations/spiders/nutrition_warehouse_au.py, locations/spiders/reiss_gb.py, locations/spiders/signet_jewelers.py, locations/spiders/sweetfrog_us.py
=> Add autoflake to remove unused imports

locations/spiders/interparking.py
{'atp/brand/Interparking': 345,
'atp/brand_wikidata/Q1895863': 345,
'atp/category/amenity/parking': 345,
'atp/field/city/missing': 345,
'atp/field/country/from_website_url': 345,
'atp/field/email/missing': 345,
'atp/field/opening_hours/missing': 345,
'atp/field/phone/missing': 345,
'atp/field/postcode/missing': 345,
'atp/field/state/missing': 345,
'atp/field/street_address/missing': 345,
'atp/field/twitter/missing': 345,
'atp/nsi/perfect_match': 345,
'downloader/request_bytes': 10158,
'downloader/request_count': 29,
'downloader/request_method_count/GET': 20,
'downloader/request_method_count/POST': 9,
'downloader/response_bytes': 1331311,
'downloader/response_count': 29,
'downloader/response_status_count/200': 16,
'downloader/response_status_count/301': 13,
'dupefilter/filtered': 1, …
=> Updated Interparking - added more countries (345 locations)

locations/spiders/svetofor_ru.py
One poi gives an error, but I'll leave it for now.
Stats:
```json
{
"atp/brand/Светофор": 728,
"atp/brand_wikidata/Q61875920": 728,
"atp/category/shop/supermarket": 728,
"atp/cdn/cloudflare/response_count": 2,
"atp/cdn/cloudflare/response_status_count/200": 2,
"atp/field/city/missing": 728,
"atp/field/country/from_spider_name": 728,
"atp/field/email/missing": 728,
"atp/field/image/missing": 728,
"atp/field/opening_hours/missing": 728,
"atp/field/operator/missing": 728,
"atp/field/operator_wikidata/missing": 728,
"atp/field/phone/missing": 728,
"atp/field/postcode/missing": 728,
"atp/field/state/missing": 728,
"atp/field/street_address/missing": 728,
"atp/field/twitter/missing": 728,
"atp/field/website/invalid": 1,
"atp/nsi/perfect_match": 728,
"downloader/request_bytes": 612, …
```
=> [svetofor_ru] add spider (728 locations)

locations/spiders/repsol_mx.py
Reference: https://github.com/alltheplaces/alltheplaces/pull/6697/commits/05707c6b84dd4610671f60dfa44e5be81ebb3d2a
=> repsol_mx: fix coordinates (lat/lon flipped)

locations/spiders/just_for_pets_gb.py
```python
{'atp/brand/Just For Pets': 23,
'atp/category/shop/pet': 23,
'atp/field/brand_wikidata/missing': 23,
'atp/field/country/from_spider_name': 23,
'atp/field/state/missing': 23,
'downloader/request_bytes': 368,
'downloader/response_bytes': 4176,
'elapsed_time_seconds': 0.649281, …
```
=> [JustForPetsGB] Add Spider

locations/spiders/365_discount_dk.py
Rel: https://github.com/osmlab/name-suggestion-index/pull/9052
```python
{'atp/brand/365discount': 366,
'atp/brand_wikidata/Q104671354': 366,
'atp/category/shop/supermarket': 366,
'atp/field/country/from_spider_name': 366,
'atp/field/email/missing': 366,
'atp/field/image/missing': 366,
'atp/field/opening_hours/missing': 366,
'atp/field/operator/missing': 366,
'atp/field/operator_wikidata/missing': 366,
'atp/field/state/missing': 366,
'atp/field/twitter/missing': 366,
'atp/nsi/perfect_match': 366,
'downloader/request_bytes': 451,
'downloader/response_bytes': 27172, …
```
=> [365DiscountDK] Add spider

locations/spiders/retravision_au.py
{'atp/brand/Retravision': 22,
'atp/brand_wikidata/Q7316908': 22,
'atp/category/shop/electronics': 22,
'atp/cdn/cloudflare/response_count': 25,
'atp/cdn/cloudflare/response_status_count/200': 25,
'atp/field/lat/missing': 22,
'atp/field/lon/missing': 22,
'atp/nsi/brand_missing': 22,
'downloader/request_bytes': 26338,
'downloader/request_count': 25,
'downloader/request_method_count/GET': 25,
'downloader/response_bytes': 1510464,
'downloader/response_count': 25,
'downloader/response_status_count/200': 25,
'elapsed_time_seconds': 40.792189,
'finish_time': datetime.datetime(2024, 1, 15, 14, 6, 18, 66114, …
=> [RetravisionAU] Add category

locations/spiders/greatclips.py
(Didn't run to completion)
```python
{'atp/brand/Great Clips': 486,
'atp/brand_wikidata/Q5598967': 486,
'atp/category/shop/hairdresser': 486,
'atp/cdn/cloudflare/response_count': 493,
'atp/cdn/cloudflare/response_status_count/200': 493,
'atp/field/email/missing': 486,
'atp/field/image/missing': 471,
'atp/field/operator/missing': 486,
'atp/field/operator_wikidata/missing': 486,
'atp/nsi/perfect_match': 486,
'downloader/request_bytes': 271296,
'downloader/request_count': 493,
'downloader/request_method_count/GET': 493,
'downloader/response_bytes': 8391969,
'downloader/response_count': 493,
'downloader/response_status_count/200': 493,
'elapsed_time_seconds': 90.454325,
'finish_time': datetime.datetime(2024, 1, 15, …
```
=> [GreatClips] Fix spider

locations/spiders/afters_ice_cream_us.py
{'atp/brand/Afters Ice Cream': 22,
'atp/brand_wikidata/Q119264038': 22,
'atp/category/shop/ice_cream': 22,
'atp/field/phone/missing': 22,
'atp/field/website/missing': 22,
'atp/nsi/brand_missing': 22,
'downloader/response_bytes': 2853,
'elapsed_time_seconds': 1.98431,
'finish_time': …
=> [AftersIceCreamUS] Add category

locations/spiders/the_afl_store_au.py
{'atp/brand/The AFL Store': 23,
'atp/brand_wikidata/Q117851311': 23,
'atp/category/shop/sports': 23,
'downloader/response_bytes': 4877,
'elapsed_time_seconds': 2.525925,
'finish_time': datetime.datetime(2024, 1, 15, …
=> [TheAFLStoreAU] Add category

locations/spiders/aquila_au.py
{'atp/brand/Aquila': 23,
'atp/brand_wikidata/Q17985574': 23,
'atp/category/shop/shoes': 23,
'downloader/request_bytes': 842,
'downloader/response_bytes': 8815, …
=> [AquilaAU] Add category

locations/spiders/rains.py
{'atp/brand/Rains': 24,
'atp/brand_wikidata/Q119440481': 24,
'atp/category/shop/clothes': 24,
'atp/field/state/missing': 20,
'atp/field/website/missing': 24,
'atp/nsi/brand_missing': 24,
'downloader/response_bytes': 4334,
'elapsed_time_seconds': 3.158161,
'finish_time': datetime.datetime(2024, 1, 15, 11, 31, …
=> [Rains] Add Category

locations/spiders/busy_beaver.py
{'atp/brand/Busy Beaver': 25,
'atp/brand_wikidata/Q108394482': 25,
'atp/category/shop/doityourself': 25,
'atp/nsi/brand_missing': 25,
'downloader/request_bytes': 832,
'downloader/response_bytes': 5163,
'elapsed_time_seconds': 3.631489,
'finish_time': datetime.datetime(2024, 1, 15, 9, 38, 3, 846344, tzinfo=datetime.timezone.utc), …
=> [BusyBeaver] Add category

locations/spiders/george_webb_us.py
{'atp/brand/George Webb': 25,
'atp/brand_wikidata/Q5546110': 25,
'atp/category/amenity/fast_food': 25,
'atp/field/postcode/missing': 25,
'atp/field/website/missing': 25,
'atp/nsi/brand_missing': 25,
'downloader/response_bytes': 1982,
'elapsed_time_seconds': 2.373013,
'finish_time': datetime.datetime(2024, 1, 15, 9, 17, 42, 284602, …
=> [GeorgeWebbUS] Add category

locations/spiders/lee_au.py
{'atp/brand/Lee': 3,
'atp/brand_wikidata/Q1632681': 3,
'atp/category/shop/clothes': 3,
'downloader/response_bytes': 6170,
'elapsed_time_seconds': 2.790848, …
=> [LeeAU] Add category

locations/spiders/eq_saddlery_au.py
{'atp/brand/EQ Saddlery': 6,
'atp/brand_wikidata/Q117746041': 6,
'atp/category/shop/sports': 6,
'atp/nsi/brand_missing': 6,
'downloader/request_bytes': 846,
'downloader/response_bytes': 6497, …
=> [EQSaddleryAU] Add category

locations/spiders/alive_pharmacy_warehouse_au.py
{'atp/brand/Alive Pharmacy Warehouse': 7,
'atp/brand_wikidata/Q119258489': 7,
'atp/category/amenity/pharmacy': 7,
'atp/category/multiple': 7,
'atp/field/operator/missing': 7,
'atp/field/operator_wikidata/missing': 7,
'atp/field/twitter/missing': 7,
'atp/field/website/missing': 7,
'atp/nsi/brand_missing': 7,
'downloader/response_bytes': 2359,
'elapsed_time_seconds': 2.246651,
'finish_time': datetime.datetime(2024, 1, 16, 14, …
=> [AlivePharmacyWarehouseAU] Add category

locations/spiders/matchbox_au.py
{'atp/brand/Matchbox': 22,
'atp/brand_wikidata/Q117854120': 22,
'atp/category/shop/houseware': 22,
'atp/field/city/missing': 22,
'atp/field/country/from_spider_name': 22,
'atp/field/postcode/missing': 22,
'atp/field/state/missing': 22,
'atp/field/street_address/missing': 22,
'atp/nsi/brand_missing': 22,
'downloader/request_bytes': 1004,
'downloader/response_bytes': 76940, …
=> [MatchboxAU] Add category

locations/spiders/crown_burgers.py
{'atp/brand/Crown Burgers': 8,
'atp/brand_wikidata/Q5189316': 8,
'atp/category/amenity/restaurant': 8,
'atp/field/country/from_reverse_geocoding': 7,
'atp/nsi/brand_missing': 8,
'downloader/request_bytes': 315,
'downloader/response_bytes': 2121, …
=> [CrownBurgers] Add category

locations/spiders/scooter_hut_au.py
{'atp/brand/Scooter Hut': 15,
'atp/brand_wikidata/Q117747623': 15,
'atp/category/shop/scooter': 15,
'atp/field/website/missing': 15,
'atp/nsi/brand_missing': 15,
'downloader/request_bytes': 847,
'downloader/response_bytes': 8007,
'elapsed_time_seconds': 2.862914, …
=> [ScooterHutAU] Add category
