alltheplaces/alltheplaces

locations/spiders/sals_pizza_us.py
{"atp/brand/Sal's Pizza": 14,
'atp/brand_wikidata/Q7403249': 14,
'atp/category/amenity/restaurant': 14,
'atp/field/city/missing': 14,
'atp/field/country/from_spider_name': 9,
'atp/field/postcode/missing': 14,
'atp/field/state/from_reverse_geocoding': 14,
'atp/field/street_address/missing': 14,
'atp/nsi/brand_missing': 14,
'downloader/response_bytes': 8871, …
=> [SalsPizzaUS] Add category

locations/spiders/bags_to_go_au.py
{'atp/brand/Bags To Go': 4,
'atp/brand_wikidata/Q117745930': 4,
'atp/category/shop/bag': 4,
'atp/field/image/missing': 4,
'atp/field/operator/missing': 4,
'atp/field/operator_wikidata/missing': 4,
'atp/field/twitter/missing': 4,
'atp/field/website/missing': 4,
'atp/nsi/brand_missing': 4,
'downloader/response_bytes': 6263,
'elapsed_time_seconds': 2.584487, …
=> [BagsToGoAU] Add category

locations/spiders/speedo_au.py
{'atp/brand/Speedo': 4,
'atp/brand_wikidata/Q1425519': 4,
'atp/category/shop/clothes': 4,
'atp/field/image/missing': 4,
'atp/field/operator/missing': 4,
'atp/field/operator_wikidata/missing': 4,
'atp/field/twitter/missing': 4,
'atp/field/website/missing': 4,
'atp/nsi/brand_missing': 4,
'downloader/request_bytes': 838,
'downloader/response_bytes': 6339,
'elapsed_time_seconds': 2.758277, …
=> [SpeedoAU] Add category

locations/spiders/nique_au.py
{'atp/brand/Nique': 3,
'atp/brand_wikidata/Q117747324': 3,
'atp/category/shop/clothes': 3,
'downloader/request_bytes': 841,
'downloader/response_bytes': 6116,
'elapsed_time_seconds': 2.686598, …
=> [NiqueAU] Add category

locations/spiders/riders_by_lee_au.py
{'atp/brand/Riders by Lee': 3,
'atp/brand_wikidata/Q117747538': 3,
'atp/category/shop/clothes': 3,
'downloader/request_bytes': 843,
'downloader/response_bytes': 6184, …
=> [RidersByLeeAU] Add category

locations/spiders/zomp_au.py
{'atp/brand/ZOMP': 2,
'atp/brand_wikidata/Q117747772': 2,
'atp/category/shop/shoes': 2,
'atp/field/operator/missing': 2,
'atp/field/operator_wikidata/missing': 2,
'atp/field/twitter/missing': 2,
'atp/nsi/brand_missing': 2,
'downloader/request_bytes': 841,
'downloader/response_bytes': 5995,
'elapsed_time_seconds': 2.759822, …
=> [ZompAU] Add category

locations/spiders/lenscrafters.py
{'atp/brand/Lenscrafters': 1,
'atp/brand_wikidata/Q6523209': 1,
'atp/category/shop/optician': 1,
'atp/field/operator/missing': 1,
'atp/field/operator_wikidata/missing': 1,
'downloader/request_bytes': 779, …
=> [LensCrafters] Add category

locations/spiders/oxford_au.py
{'atp/brand/Oxford': 20,
'atp/brand_wikidata/Q117747475': 20,
'atp/category/shop/clothes': 20,
'downloader/request_bytes': 846,
'downloader/response_bytes': 8790, …
=> [OxfordAU] Add category

locations/hours.py, locations/spiders/mts_ru.py
Stats:
```json
{
"atp/brand/МТС": 4634,
"atp/brand_wikidata/Q1368919": 4634,
"atp/category/shop/telecommunication": 4634,
"atp/field/city/missing": 4634,
"atp/field/country/from_spider_name": 4634,
"atp/field/email/missing": 4634,
"atp/field/image/missing": 4634,
"atp/field/lat/missing": 1,
"atp/field/lon/missing": 1,
"atp/field/opening_hours/missing": 1069,
"atp/field/operator/missing": 4634,
"atp/field/operator_wikidata/missing": 4634,
"atp/field/phone/missing": 4634,
"atp/field/postcode/missing": 4634,
"atp/field/state/missing": 4634,
"atp/field/street_address/missing": 4634,
"atp/field/twitter/missing": 4634,
"atp/field/website/missing": 4634,
"atp/geometry/null_island": 1,
"atp/nsi/category_match": 4634,
"downloader/request_bytes": 1424,
"downloader/request_count": 3, …
```
=> [mts_ru] add spider (4k locations)

locations/spiders/roler_au.py
{'atp/brand/Roler': 1,
'atp/brand_wikidata/Q117747576': 1,
'atp/category/shop/clothes': 1,
'atp/field/operator/missing': 1,
'atp/field/operator_wikidata/missing': 1,
'atp/nsi/brand_missing': 1,
'downloader/request_bytes': 842,
'downloader/response_bytes': 5801,
'elapsed_time_seconds': 3.086383, …
=> [RolerAU] Add category

locations/spiders/purebaby_au.py
{'atp/brand/Purebaby': 16,
'atp/brand_wikidata/Q122431533': 16,
'atp/category/shop/clothes': 16,
'atp/field/city/missing': 16,
'atp/field/postcode/missing': 16,
'atp/field/state/missing': 16,
'atp/field/street_address/missing': 16,
'atp/nsi/brand_missing': 16,
'downloader/request_bytes': 654,
'downloader/response_bytes': 40701,
'elapsed_time_seconds': 2.272596,
'finish_time': …
=> [PureBabyAU] Add category

locations/spiders/rationale.py
{'atp/brand/RATIONALE': 17,
'atp/brand_wikidata/Q119442596': 17,
'atp/category/shop/cosmetics': 17,
'atp/field/country/from_reverse_geocoding': 17,
'atp/field/street_address/missing': 16,
'atp/field/website/missing': 16,
'atp/nsi/brand_missing': 17,
'downloader/response_bytes': 11569, …
=> [Rationale] Add category

locations/spiders/black_rooster_peri_peri_gb.py
{'atp/brand/Black Rooster Peri Peri': 17,
'atp/brand_wikidata/Q119158787': 17,
'atp/category/amenity/fast_food': 17,
'atp/nsi/brand_missing': 17,
'downloader/response_bytes': 8383,
'elapsed_time_seconds': 2.089718, …
=> [BlackRoosterPeriPeriGB] Add category

locations/spiders/americas_kids_us.py
{"atp/brand/America's Kids": 11,
'atp/brand/Kids World': 1,
'atp/brand/Lazarus': 1,
'atp/brand/Young Land': 1,
'atp/brand/Young World': 6,
'atp/brand_wikidata/Q119141496': 11,
'atp/brand_wikidata/Q119141641': 6,
'atp/brand_wikidata/Q119141643': 1,
'atp/brand_wikidata/Q119141646': 1,
'atp/brand_wikidata/Q119141647': 1,
'atp/category/shop/clothes': 20,
'atp/field/city/missing': 20,
'atp/field/postcode/missing': 20,
'atp/field/state/from_reverse_geocoding': 20,
'atp/field/street_address/missing': 20, …
=> [AmericasKidsUS] Add category

locations/spiders/camp_bow_wow.py
{'atp/brand/Camp Bow Wow': 227,
'atp/brand_wikidata/Q121322343': 227,
'atp/category/amenity/animal_boarding': 227,
'atp/field/email/missing': 227,
'atp/field/image/missing': 227,
'atp/field/opening_hours/missing': 227,
'atp/field/operator/missing': 227,
'atp/field/operator_wikidata/missing': 227,
'atp/field/twitter/missing': 227,
'atp/field/website/missing': 227,
'atp/nsi/brand_missing': 227,
'downloader/request_bytes': 641,
'downloader/response_bytes': 758167,
'elapsed_time_seconds': 6.198774,
'finish_time': datetime.datetime(2024, 1, 17, 8, 52, 37, 30881, …
=> [CampBowWow] Add brand, wikidata code and category

locations/spiders/western_union.py
=> [WesternUnion] Remove top level tag

locations/spiders/planet_smoothie_us.py
Rel: https://github.com/osmlab/name-suggestion-index/pull/9146
```python
{'atp/brand/Planet Smoothie': 166,
'atp/brand_wikidata/Q7201170': 166,
'atp/category/missing': 166,
'atp/field/email/missing': 166,
'atp/field/image/missing': 166,
'atp/field/opening_hours/missing': 166,
'atp/field/operator/missing': 166,
'atp/field/operator_wikidata/missing': 166,
'atp/field/twitter/missing': 166,
'atp/nsi/brand_missing': 166,
'downloader/response_bytes': 49007,
'elapsed_time_seconds': 1.565711, …
```
=> [PlanetSmoothieUS] Add spider

locations/spiders/afgri_equipment_au.py
{'atp/brand/AFGRI Equipment': 20,
'atp/brand_wikidata/Q119264464': 20,
'atp/category/shop/tractor': 20,
'atp/field/city/missing': 20,
'atp/field/postcode/missing': 20,
'atp/field/state/missing': 20,
'atp/field/street_address/missing': 20,
'downloader/request_bytes': 340,
'downloader/response_bytes': 2443,
'elapsed_time_seconds': 0.841615,
'finish_time': …
=> [AfgriAU] Add category

locations/spiders/the_exercise_coach_us.py
https://github.com/osmlab/name-suggestion-index/pull/9144
```python
{'atp/brand/The Exercise Coach': 206,
'atp/brand_wikidata/Q121502262': 206,
'atp/category/missing': 206,
'atp/field/image/missing': 206,
'atp/field/name/missing': 206,
'atp/field/opening_hours/missing': 205,
'atp/field/operator/missing': 206,
'atp/field/operator_wikidata/missing': 206,
'atp/field/twitter/missing': 206,
'atp/nsi/brand_missing': 206,
'downloader/response_bytes': 19782, …
```
=> [TheExerciseCoachUS] Add spider

locations/spiders/man_truck_and_bus.py
{'atp/brand/MAN Truck & Bus': 2053,
'atp/brand_wikidata/Q708667': 2053,
'atp/category/shop/truck': 2053,
'atp/field/country/from_reverse_geocoding': 2,
'atp/field/email/missing': 2053,
'atp/field/image/missing': 2053,
'atp/field/opening_hours/missing': 2053,
'atp/field/operator/missing': 2053,
'atp/field/operator_wikidata/missing': 2053,
'atp/field/phone/invalid': 55,
'atp/field/state/from_reverse_geocoding': 60,
'atp/field/state/missing': 1991,
'atp/field/twitter/missing': 2053,
'atp/field/website/missing': 2053,
'atp/nsi/brand_missing': 2053,
'downloader/response_bytes': 175733, …
=> [ManTruckAndBus] Add category

locations/spiders/wrangler_au.py
{'atp/brand/Wrangler': 3,
'atp/brand_wikidata/Q1445358': 3,
'atp/category/shop/clothes': 3,
'downloader/response_bytes': 6167,
'elapsed_time_seconds': 2.478014, …
=> [WranglerAU] Add category

locations/spiders/super_hotel_jp.py
Rel: https://github.com/osmlab/name-suggestion-index/pull/9159
```python
{'atp/brand_wikidata/Q11313858': 173,
'atp/category/missing': 173,
'atp/field/brand/missing': 173,
'atp/field/city/missing': 173,
'atp/field/country/from_spider_name': 173,
'atp/field/email/missing': 173,
'atp/field/image/missing': 173,
'atp/field/opening_hours/missing': 173,
'atp/field/operator/missing': 173,
'atp/field/operator_wikidata/missing': 173,
'atp/field/state/missing': 173,
'atp/field/twitter/missing': 173,
'atp/nsi/brand_missing': 173,
'downloader/request_bytes': 1101,
'downloader/response_bytes': 15719, …
```
=> [SuperHotelJP] Add spider

locations/spiders/hy_vee_us.py
{'atp/brand/Hy-Vee': 279,
'atp/brand_wikidata/Q1639719': 279,
'atp/category/shop/supermarket': 279,
'atp/cdn/cloudflare/response_count': 303,
'atp/cdn/cloudflare/response_status_count/200': 281,
'atp/cdn/cloudflare/response_status_count/302': 22,
'atp/field/city/missing': 279,
'atp/field/country/missing': 279,
'atp/field/email/missing': 279,
'atp/field/image/invalid': 11,
'atp/field/lat/missing': 279,
'atp/field/lon/missing': 279,
'atp/field/operator/missing': 279,
'atp/field/operator_wikidata/missing': 279,
'atp/field/phone/invalid': 280,
'atp/field/postcode/missing': 279,
'atp/field/state/missing': 279,
'atp/field/street_address/missing': 279,
'atp/field/twitter/missing': 279,
'atp/nsi/category_match': 279, …
=> [HyVeeUS] Add category

locations/spiders/rock_bottom.py
{'atp/brand/Rock Bottom': 11,
'atp/brand_wikidata/Q73504866': 11,
'atp/category/amenity/restaurant': 11,
'atp/nsi/brand_missing': 11,
'downloader/request_bytes': 12606,
'downloader/request_count': 18,
'downloader/request_method_count/GET': 18,
'downloader/response_bytes': 246922,
'downloader/response_count': 18,
'downloader/response_status_count/200': 15,
'downloader/response_status_count/301': 3,
'dupefilter/filtered': 1,
'elapsed_time_seconds': 10.50305,
'finish_time': datetime.datetime(2024, 1, 17, 14, 9, 23, 188362, tzinfo=datetime.timezone.utc),
'httpcompression/response_bytes': 704077,
'httpcompression/response_count': 15,
'item_scraped_count': 11, …
=> [RockBottom] Add category

locations/spiders/the_fresh_grocer_us.py
{'atp/brand/The Fresh Grocer': 21,
'atp/brand_wikidata/Q18389721': 21,
'atp/category/shop/supermarket': 21,
'atp/nsi/brand_missing': 21,
'downloader/request_bytes': 616,
'downloader/response_bytes': 388752,
'elapsed_time_seconds': 4.045968,
'finish_time': datetime.datetime(2024, 1, 17, 14, 23, 17, 937020, …
=> [TheFreshGrocerUS] Add category

locations/spiders/haggen.py
{'atp/brand/Haggen': 15,
'atp/brand_wikidata/Q5638683': 15,
'atp/category/shop/supermarket': 15,
'atp/cdn/cloudflare/response_count': 33,
'atp/cdn/cloudflare/response_status_count/200': 33,
'atp/nsi/brand_missing': 15,
'downloader/exception_type_count/scrapy.exceptions.IgnoreRequest': 1,
'downloader/request_bytes': 17276,
'downloader/request_count': 33,
'downloader/request_method_count/GET': 33,
'downloader/response_bytes': 395281,
'downloader/response_count': 33,
'downloader/response_status_count/200': 33,
'elapsed_time_seconds': 38.427595,
'finish_time': datetime.datetime(2024, 1, 17, …
=> [Haggen] Add category

locations/spiders/usavingsbank.py
{'atp/brand/Union Savings Bank': 40,
'atp/brand_wikidata/Q69206498': 40,
'atp/category/amenity/bank': 40,
'atp/cdn/cloudflare/response_count': 43,
'atp/cdn/cloudflare/response_status_count/200': 43,
'atp/field/email/missing': 40,
'atp/field/image/missing': 40,
'atp/field/operator/missing': 40,
'atp/field/operator_wikidata/missing': 40,
'atp/field/twitter/missing': 40,
'atp/nsi/category_match': 40,
'downloader/request_bytes': 24124,
'downloader/response_bytes': 501008,
'downloader/response_count': 44,
'downloader/response_status_count/200': 43,
'downloader/response_status_count/302': 1,
'elapsed_time_seconds': 51.088143,
'finish_time': …
=> [UnionSavingsBank] Add category

locations/spiders/radisson_hotels.py
{'atp/brand/Art’otel': 7,
'atp/brand/Country Inn & Suites by Radisson': 13,
'atp/brand/Park Inn by Radisson': 97,
'atp/brand/Park Plaza Hotels & Resorts': 36,
'atp/brand/Prizeotel': 14,
'atp/brand/Radisson': 101,
'atp/brand/Radisson Blu': 327,
'atp/brand/Radisson Collection': 38,
'atp/brand/Radisson Individuals': 54,
'atp/brand/Radisson RED': 19,
'atp/brand_wikidata/Q14516231': 7,
'atp/brand_wikidata/Q1751979': 101,
'atp/brand_wikidata/Q2052550': 36,
'atp/brand_wikidata/Q28233721': 19,
'atp/brand_wikidata/Q5177332': 13,
'atp/brand_wikidata/Q60711675': 97,
'atp/brand_wikidata/Q60716706': 38,
'atp/brand_wikidata/Q7281341': 327,
'atp/category/tourism/hotel': 706,
'atp/field/brand_wikidata/missing': 68,
'atp/field/email/missing': 706,
'atp/field/image/missing': 706, …
=> [RadissonHotels] Add category

locations/spiders/samsonite_eu.py
{'atp/brand/Chic Accent': 24,
'atp/brand/Samsonite': 119,
'atp/brand_wikidata/Q1203426': 119,
'atp/category/shop/bag': 143,
'atp/field/brand_wikidata/missing': 24,
'atp/field/country/from_reverse_geocoding': 2,
'atp/field/image/missing': 143,
'atp/field/name/missing': 24,
'atp/field/opening_hours/missing': 143,
'atp/field/operator/missing': 143,
'atp/field/operator_wikidata/missing': 143,
'atp/field/state/missing': 141,
'atp/field/twitter/missing': 143,
'atp/field/website/missing': 21,
'atp/nsi/perfect_match': 119,
'downloader/request_bytes': 16808,
'downloader/request_count': 39,
'downloader/request_method_count/GET': 39,
'downloader/response_bytes': 1721513,
'downloader/response_count': 39, …
=> [SamsoniteEU] Add category

locations/spiders/golub_corporation_us.py
{'atp/brand/Market 32': 41,
'atp/brand/Market Bistro': 1,
'atp/brand/Price Chopper': 88,
'atp/brand_wikidata/Q123370878': 41,
'atp/brand_wikidata/Q123370887': 1,
'atp/brand_wikidata/Q7242574': 88,
'atp/category/shop/supermarket': 130,
'atp/cdn/cloudflare/response_count': 249,
'atp/cdn/cloudflare/response_status_count/200': 249,
'atp/field/country/from_spider_name': 130,
'atp/field/email/missing': 130,
'atp/field/image/dropped': 130,
'atp/field/image/missing': 130,
'atp/field/operator/missing': 130,
'atp/field/operator_wikidata/missing': 130,
'atp/field/twitter/missing': 130,
'atp/nsi/brand_missing': 42,
'downloader/request_bytes': 136488,
'downloader/request_count': 249,
'downloader/request_method_count/GET': 249,
'downloader/response_bytes': 6576987, …
=> [GolubCorporationUS] Add category

locations/spiders/regis_salon.py
{'atp/brand/Regis': 22,
'atp/brand_wikidata/Q7309325': 22,
'atp/category/shop/hairdresser': 22,
'atp/cdn/cloudflare/response_count': 24,
'atp/cdn/cloudflare/response_status_count/200': 24,
'atp/field/opening_hours/missing': 22,
'atp/nsi/cc_match': 2,
'atp/nsi/match_failed': 20,
'downloader/request_bytes': 13819,
'downloader/request_count': 24,
'downloader/request_method_count/GET': 24,
'downloader/response_bytes': 417066,
'downloader/response_count': 24,
'downloader/response_status_count/200': 24,
'elapsed_time_seconds': 4.743693,
'finish_time': datetime.datetime(2024, 1, 18, 9, 33, 34, …
=> [Regis] Add category

locations/spiders/hard_rock.py
{'atp/brand/Hard Rock Cafe': 161,
'atp/brand/Hard Rock Casino': 4,
'atp/brand/Hard Rock Hotel': 25,
'atp/brand/Hard Rock Hotel & Casino': 10,
'atp/brand/Hard Rock Live': 5,
'atp/brand_wikidata/Q109275902': 25,
'atp/brand_wikidata/Q5655372': 5,
'atp/brand_wikidata/Q918151': 161,
'atp/category/amenity/casino': 4,
'atp/category/amenity/music_venue': 5,
'atp/category/amenity/restaurant': 161,
'atp/category/tourism/hotel': 35,
'atp/field/brand_wikidata/missing': 14,
'atp/field/email/missing': 205,
'atp/field/image/missing': 205,
'atp/field/opening_hours/missing': 205,
'atp/field/operator/missing': 205,
'atp/field/operator_wikidata/missing': 205, …
=> [HardRock] Add category

locations/spiders/subway_sg.py
```python
{'atp/brand/Subway': 126,
'atp/brand_wikidata/Q244457': 126,
'atp/category/amenity/fast_food': 126,
'atp/field/country/from_spider_name': 126,
'atp/field/email/missing': 126,
'atp/field/image/missing': 126,
'atp/field/operator/missing': 126,
'atp/field/operator_wikidata/missing': 126,
'atp/field/street_address/missing': 126,
'atp/field/twitter/missing': 126,
'atp/field/website/missing': 126,
'atp/nsi/cc_match': 126,
'downloader/response_bytes': 10556,
'elapsed_time_seconds': 4.907246,
'finish_time': datetime.datetime(2024, 1, 18, 20, 47, …
```
=> [subway_sg] Created subway spider for Singapore (126 items)

locations/spiders/circle_k_vn.py
```python
{'atp/brand/Circle K': 445,
'atp/brand_wikidata/Q3268010': 445,
'atp/category/shop/convenience': 445,
'atp/field/city/missing': 445,
'atp/field/country/from_spider_name': 445,
'atp/field/email/missing': 445,
'atp/field/image/missing': 445,
'atp/field/opening_hours/missing': 445,
'atp/field/operator/missing': 445,
'atp/field/operator_wikidata/missing': 445,
'atp/field/phone/missing': 445,
'atp/field/postcode/missing': 445,
'atp/field/state/missing': 445,
'atp/field/street_address/missing': 445,
'atp/field/twitter/missing': 445,
'atp/nsi/category_match': 445,
'downloader/response_bytes': 61493, …
```
=> [circle_k_vn] Created spider for circle k in Vietnam (445 Items)

locations/spiders/dominos_pizza_in.py
```python
{"atp/brand/Domino's Pizza": 1573,
'atp/brand_wikidata/Q839466': 1573,
'atp/category/amenity/fast_food': 1573,
'atp/field/email/missing': 1573,
'atp/field/image/missing': 1573,
'atp/field/lat/missing': 6,
'atp/field/lon/missing': 6,
'atp/field/opening_hours/missing': 1573,
'atp/field/operator/missing': 1573,
'atp/field/operator_wikidata/missing': 1573,
'atp/field/postcode/missing': 194,
'atp/field/street_address/missing': 1573,
'atp/nsi/cc_match': 1573,
'downloader/request_bytes': 1686026,
'downloader/request_count': 1780,
'downloader/request_method_count/GET': 1780,
'downloader/response_bytes': 51448369,
'downloader/response_count': 1780,
'downloader/response_status_count/200': 1671, …
```
=> [Dominos IN] Add spider

locations/spiders/yesss_gb.py
{'atp/brand/Yesss Electrical': 96,
'atp/brand_wikidata/Q91307483': 96,
'atp/category/shop/electrical': 96,
'atp/field/name/missing': 4,
'atp/field/opening_hours/missing': 96,
'atp/field/operator/missing': 96,
'atp/field/operator_wikidata/missing': 96,
'atp/field/state/missing': 96,
'atp/field/twitter/missing': 96,
'atp/nsi/cc_match': 92,
'atp/nsi/match_failed': 4,
'downloader/request_bytes': 632,
'downloader/response_bytes': 23773,
'elapsed_time_seconds': 2.047212,
'finish_time': datetime.datetime(2024, 1, 18, 15, 56, 0, …
=> [YesssGB] Add category

locations/spiders/loves.py
{"atp/brand/Love's": 712,
'atp/brand_wikidata/Q1872496': 712,
'atp/category/highway/service': 640,
'atp/category/shop/truck_repair': 53,
'atp/category/tourism/hotel': 19,
'atp/field/country/from_reverse_geocoding': 712,
'atp/field/image/missing': 712,
'atp/field/opening_hours/missing': 712,
'atp/field/operator/missing': 712,
'atp/field/operator_wikidata/missing': 712,
'atp/field/twitter/missing': 712,
'atp/field/website/missing': 712,
'atp/nsi/match_failed': 712,
'downloader/request_bytes': 19430,
'downloader/request_method_count/GET': 16,
'downloader/response_bytes': 3888543,
'downloader/response_count': 17,
'downloader/response_status_count/200': 17,
'elapsed_time_seconds': 49.887399, …
=> [Loves] Add category

locations/spiders/subway_hk.py
```python
{'atp/brand/Subway': 47,
'atp/brand_wikidata/Q244457': 47,
'atp/category/amenity/fast_food': 47,
'atp/field/city/missing': 47,
'atp/field/country/from_spider_name': 47,
'atp/field/opening_hours/missing': 47,
'atp/field/postcode/missing': 47,
'atp/field/state/missing': 47,
'atp/field/street_address/missing': 47,
'atp/nsi/cc_match': 47,
'downloader/request_bytes': 622,
'downloader/response_bytes': 22162, …
```
=> [subway_hk] Created subway_hk spider (47 items)

locations/spiders/dominos_pizza_mx.py
```python
{"atp/brand/Domino's Pizza": 905,
'atp/brand_wikidata/Q839466': 905,
'atp/category/amenity/fast_food': 905,
'atp/field/city/missing': 45,
'atp/field/country/from_spider_name': 905,
'atp/field/email/missing': 905,
'atp/field/image/missing': 905,
'atp/field/opening_hours/missing': 905,
'atp/field/operator/missing': 905,
'atp/field/operator_wikidata/missing': 905,
'atp/field/phone/invalid': 19,
'atp/field/phone/missing': 47,
'atp/field/postcode/missing': 54,
'atp/field/state/missing': 45,
'atp/field/street_address/missing': 44,
'atp/field/twitter/missing': 905,
'atp/field/website/missing': 905,
'atp/nsi/cc_match': 905,
'downloader/request_bytes': 436,
'downloader/response_bytes': 1390847, …
```
=> [Dominos MX] Add spider

locations/spiders/super_hotel_jp.py
{'atp/brand_wikidata/Q11313858': 173,
'atp/category/tourism/hotel': 173,
'atp/field/brand/missing': 173,
'atp/field/city/missing': 173,
'atp/field/country/from_spider_name': 173,
'atp/field/email/missing': 173,
'atp/field/image/missing': 173,
'atp/field/opening_hours/missing': 173,
'atp/field/operator/missing': 173,
'atp/field/operator_wikidata/missing': 173,
'atp/field/state/missing': 173,
'atp/field/twitter/missing': 173,
'atp/nsi/brand_missing': 173,
'downloader/request_bytes': 1103,
'downloader/response_bytes': 15721,
'elapsed_time_seconds': 3.240691,
'finish_time': …
=> [SuperHotelJP] Add category

locations/spiders/stop_and_shop.py
{'atp/brand/Stop and Shop': 396,
'atp/brand_wikidata/Q3658429': 396,
'atp/category/shop/supermarket': 396,
'atp/field/email/missing': 396,
'atp/field/image/missing': 396,
'atp/field/opening_hours/missing': 396,
'atp/field/operator/missing': 396,
'atp/field/operator_wikidata/missing': 396,
'atp/field/phone/missing': 396,
'atp/field/street_address/missing': 396,
'atp/field/twitter/missing': 396,
'atp/field/website/missing': 396,
'atp/nsi/category_match': 396,
'downloader/request_bytes': 984,
'downloader/response_bytes': 77515, …
=> [StopAndShop] Add category

locations/spiders/ingo_se.py
```python
{'atp/brand/Ingo': 299,
'atp/brand_wikidata/Q17048617': 299,
'atp/category/amenity/fuel': 299,
'atp/field/email/missing': 299,
'atp/field/image/missing': 299,
'atp/field/opening_hours/missing': 299,
'atp/field/operator/missing': 299,
'atp/field/operator_wikidata/missing': 299,
'atp/field/state/missing': 299,
'atp/field/twitter/missing': 299,
'atp/nsi/category_match': 299,
'downloader/request_bytes': 110885,
'downloader/request_count': 301,
'downloader/request_method_count/GET': 301,
'downloader/response_bytes': 2333903,
'downloader/response_count': 301,
'downloader/response_status_count/200': 301,
'elapsed_time_seconds': 2.193638,
'finish_time': datetime.datetime(2024, 1, 22, 11, 42, 1, 676334, …
```
=> [Ingo SE] Add Spider

locations/spiders/pinch_a_penny_us.py
Rel: https://github.com/osmlab/name-suggestion-index/commit/3816ebd4ca7686b45994b19c9603ff2f5028a6b4
```python
{'atp/brand/Pinch A Penny': 289,
'atp/brand_wikidata/Q121436109': 289,
'atp/category/missing': 289,
'atp/cdn/cloudflare/response_count': 291,
'atp/cdn/cloudflare/response_status_count/200': 291,
'atp/field/country/from_spider_name': 289,
'atp/field/email/missing': 289,
'atp/field/image/dropped': 105,
'atp/field/name/missing': 289,
'atp/field/operator/missing': 289,
'atp/field/operator_wikidata/missing': 289,
'atp/field/twitter/missing': 289,
'atp/nsi/brand_missing': 289,
'downloader/request_bytes': 309810,
'downloader/request_count': 291,
'downloader/request_method_count/GET': 291, …
```
=> [PinchAPennyUS] Add spider

locations/spiders/cato_us.py
```python
{'atp/brand/Cato': 917,
'atp/brand_wikidata/Q16956136': 917,
'atp/category/shop/clothes': 917,
'atp/cdn/cloudflare/response_count': 920,
'atp/cdn/cloudflare/response_status_count/200': 920,
'atp/field/city/missing': 917,
'atp/field/country/from_spider_name': 917,
'atp/field/email/missing': 917,
'atp/field/operator/missing': 917,
'atp/field/operator_wikidata/missing': 917,
'atp/nsi/perfect_match': 917,
'downloader/request_bytes': 510281,
'downloader/request_count': 920,
'downloader/request_method_count/GET': 920,
'downloader/response_bytes': 37476499,
'downloader/response_count': 920,
'downloader/response_status_count/200': 920,
'elapsed_time_seconds': 1088.41322,
'finish_time': datetime.datetime(2024, 1, …
```
=> [CatoUS] Add spider

locations/spiders/carla_zampatti.py
{'atp/brand/Carla Zampatti': 12,
'atp/brand_wikidata/Q87377342': 12,
'atp/category/shop/clothes': 12,
'atp/field/image/missing': 12,
'atp/field/website/missing': 12,
'atp/nsi/brand_missing': 12,
'downloader/request_bytes': 859,
'downloader/response_bytes': 9081,
'elapsed_time_seconds': 2.897535, …
=> [CarlaZampatti] Add category

locations/spiders/xsport_fitness_us.py
Rel: https://github.com/osmlab/name-suggestion-index/pull/9163
=> [XSportFitnessUS] Add spider

locations/spiders/beacon_and_bridge_market_us.py
{'atp/brand/Beacon & Bridge Market': 23,
'atp/brand_wikidata/Q122209684': 23,
'atp/category/amenity/fuel': 23,
'atp/field/country/from_spider_name': 23,
'atp/field/lat/missing': 23,
'atp/field/lon/missing': 23,
'downloader/request_bytes': 620,
'downloader/response_bytes': 8880,
'elapsed_time_seconds': 2.171756,
'finish_time': datetime.datetime(2024, 1, 22, 8, 49, 29, 966231, …
=> [BeaconAndBridgeMarketUS] Add category

locations/spiders/world_finance_us.py
Rel: https://github.com/osmlab/name-suggestion-index/pull/9167
=> [WorldFinanceUS] Add spider

locations/spiders/the_exercise_coach_us.py
{'atp/brand/The Exercise Coach': 206,
'atp/brand_wikidata/Q121502262': 206,
'atp/category/leisure/fitness_centre': 206,
'atp/field/image/missing': 206,
'atp/field/name/missing': 206,
'atp/field/opening_hours/missing': 205,
'atp/field/operator/missing': 206,
'atp/field/operator_wikidata/missing': 206,
'atp/field/twitter/missing': 206,
'atp/nsi/brand_missing': 206,
'downloader/response_bytes': 19805, …
=> [TheExerciseCoachUS] Add category

locations/spiders/completecash.py
{'atp/brand/Complete Cash': 20,
'atp/category/shop/pawnbroker': 20,
'atp/field/brand_wikidata/missing': 20,
'atp/field/state/from_reverse_geocoding': 20,
'downloader/request_bytes': 8393,
'downloader/request_count': 22,
'downloader/request_method_count/GET': 22,
'downloader/response_bytes': 2795003,
'downloader/response_count': 22,
'downloader/response_status_count/200': 22,
'elapsed_time_seconds': 27.115678,
'finish_time': datetime.datetime(2024, 1, 22, 15, 58, 40, 163505, tzinfo=datetime.timezone.utc),
'item_scraped_count': 20,
'log_count/DEBUG': 43,
'memusage/max': 135503872,
'memusage/startup': …
=> [CompleteCash] Add category

locations/spiders/twenty_four_hour_fitness_us.py
{'atp/brand/24 Hour Fitness': 29,
'atp/brand/24 Hour Fitness Sport': 101,
'atp/brand/24 Hour Fitness Super Sport': 144,
'atp/brand_wikidata/Q4631849': 274,
'atp/category/leisure/fitness_centre': 274,
'atp/field/country/from_spider_name': 274,
'atp/field/email/missing': 274,
'atp/field/image/missing': 274,
'atp/field/opening_hours/missing': 274,
'atp/field/operator/missing': 274,
'atp/field/operator_wikidata/missing': 274,
'atp/field/twitter/missing': 274,
'atp/nsi/match_failed': 274,
'downloader/request_bytes': 645,
'downloader/response_bytes': 155285,
'elapsed_time_seconds': 2.303341,
'finish_time': …
=> [TwentyFourHourFitnessUS] Add category

locations/spiders/taco_bell.py, locations/spiders/taco_bell_au.py, locations/spiders/taco_bell_es.py, locations/spiders/taco_bell_fi.py, locations/spiders/taco_bell_in.py
also rename primary tacobell -> taco_bell spider for consistency
=> [taco_bell] share wikidata across all spiders

locations/spiders/seven_eleven_au.py, locations/spiders/seven_eleven_ca.py, locations/spiders/seven_eleven_dk.py, locations/spiders/seven_eleven_mx.py, locations/spiders/seven_eleven_se.py, locations/spiders/seven_eleven_us.py
making the bigger brands a little more DRY wrt wikidata codes
=> [seven_eleven] share wikidata across all spiders

locations/spiders/profile_nl.py
Rel: https://github.com/osmlab/name-suggestion-index/pull/9184
```python
{'atp/brand/Profile': 47,
'atp/brand_wikidata/Q124339994': 47,
'atp/category/missing': 47,
'atp/field/state/missing': 47,
'atp/nsi/brand_missing': 47,
'downloader/request_bytes': 21140,
'downloader/request_count': 50,
'downloader/request_method_count/GET': 50,
'downloader/response_bytes': 2752567,
'downloader/response_count': 50,
'downloader/response_status_count/200': 50,
'elapsed_time_seconds': 1.712421,
'finish_time': datetime.datetime(2024, 1, 23, 15, 20, 6, 257717, tzinfo=datetime.timezone.utc), …
```
=> [Profile NL] Add spider

locations/spiders/arcaplanet_it.py
```python
{'atp/brand/Arcaplanet': 554,
'atp/brand_wikidata/Q105530937': 554,
'atp/category/shop/pet': 554,
'atp/cdn/cloudflare/response_count': 557,
'atp/cdn/cloudflare/response_status_count/200': 557,
'atp/field/email/missing': 554,
'atp/field/image/missing': 554,
'atp/field/opening_hours/missing': 554,
'atp/field/operator/missing': 554,
'atp/field/operator_wikidata/missing': 554,
'atp/field/twitter/missing': 554,
'atp/nsi/perfect_match': 554,
'downloader/request_bytes': 311298,
'downloader/request_count': 557,
'downloader/request_method_count/GET': 557,
'downloader/response_bytes': 16612771,
'downloader/response_count': 557,
'downloader/response_status_count/200': 557,
'elapsed_time_seconds': 651.36543, …
```
=> [Arcaplanet IT] Add spider

locations/spiders/pizza_hut_in.py
```python
{'atp/brand/Pizza Hut': 898,
'atp/brand_wikidata/Q191615': 898,
'atp/category/amenity/restaurant': 898,
'atp/field/city/missing': 898,
'atp/field/country/from_spider_name': 898,
'atp/field/email/missing': 898,
'atp/field/image/missing': 898,
'atp/field/opening_hours/missing': 898,
'atp/field/operator/missing': 898,
'atp/field/operator_wikidata/missing': 898,
'atp/field/postcode/missing': 898,
'atp/field/state/missing': 898,
'atp/field/street_address/missing': 898,
'atp/field/twitter/missing': 898,
'atp/nsi/category_match': 898,
'downloader/request_bytes': 34192,
'downloader/request_count': 93,
'downloader/request_method_count/GET': 93,
'downloader/response_bytes': 1065962,
'downloader/response_count': 93,
'downloader/response_status_count/200': 93, …
```
=> [PizzaHut IN] Add spider

locations/spiders/starbucks_kz.py
```python
{'atp/brand/Starbucks': 35,
'atp/brand_wikidata/Q37158': 35,
'atp/category/amenity/cafe': 35,
'atp/cdn/cloudflare/response_count': 24,
'atp/cdn/cloudflare/response_status_count/200': 24,
'atp/field/city/missing': 35,
'atp/field/country/from_spider_name': 35,
'atp/field/opening_hours/missing': 35,
'atp/field/phone/missing': 30,
'atp/field/street_address/missing': 35,
'atp/nsi/match_failed': 35,
'downloader/request_bytes': 9048,
'downloader/request_count': 24,
'downloader/request_method_count/GET': 24, …
```
=> [starbucks_kz] Created spider for starbucks in KZ (35 items)

locations/spiders/salon_centric_us.py
Rel: https://github.com/osmlab/name-suggestion-index/commit/3762fd814ecf2879b0aadebbe47271782a28c2bc
```python
{'atp/brand/SalonCentric': 624,
'atp/brand_wikidata/Q124339481': 624,
'atp/category/missing': 624,
'atp/cdn/cloudflare/response_count': 628,
'atp/cdn/cloudflare/response_status_count/200': 628,
'atp/closed_poi': 4,
'atp/field/city/missing': 624,
'atp/field/country/from_spider_name': 624,
'atp/field/image/dropped': 4,
'atp/field/image/missing': 4,
'atp/field/name/missing': 624,
'atp/field/operator/missing': 624,
'atp/field/operator_wikidata/missing': 624,
'atp/field/twitter/missing': 624,
'atp/nsi/brand_missing': 624,
'downloader/request_bytes': 337534,
'downloader/request_count': 628, …
```
=> [SalonCentric US] Add spider

locations/spiders/burger_king.py, locations/spiders/burger_king_be_lu.py, locations/spiders/burger_king_br.py, locations/spiders/burger_king_cz.py, locations/spiders/burger_king_es_pt.py, locations/spiders/burger_king_fi.py, locations/spiders/burger_king_fr.py, locations/spiders/burger_king_it.py, locations/spiders/burger_king_mx.py, locations/spiders/burger_king_pl.py, locations/spiders/burger_king_se.py, locations/spiders/burger_king_tr.py
cleaning up some of the bigger duplicated wikidata brands
=> [burger_king] share wikidata across all spiders

locations/spiders/dunkin_at.py, locations/spiders/dunkin_be_nl.py, locations/spiders/dunkin_ch.py, locations/spiders/dunkin_de.py, locations/spiders/dunkin_us.py
cleaning up some of the bigger duplicated wikidata brands
=> [dunkin] share wikidata across all spiders

locations/spiders/european_wax_center_us.py
```python
{'atp/brand/European Wax Center': 1063,
'atp/brand_wikidata/Q5413426': 1063,
'atp/category/shop/beauty': 1063,
'atp/field/country/from_spider_name': 1063,
'atp/field/email/missing': 1063,
'atp/field/image/dropped': 1063,
'atp/field/image/missing': 1063,
'atp/field/operator/missing': 1063,
'atp/field/operator_wikidata/missing': 1063,
'atp/nsi/perfect_match': 1063,
'downloader/request_bytes': 463463,
'downloader/request_count': 1127,
'downloader/request_method_count/GET': 1127,
'downloader/response_bytes': 57496754,
'downloader/response_count': 1127,
'downloader/response_status_count/200': 1127,
'elapsed_time_seconds': 1334.728792, …
```
=> [EuropeanWaxCenter US] Add spider

locations/spiders/seven_eleven_dk.py
A file that is not formatted by black sneaked into other PRs.
rel: https://github.com/alltheplaces/alltheplaces/pull/6869
=> [seven_eleven_dk] remove empty line from spider file

locations/categories.py, locations/spiders/parks_victoria_au.py, locations/spiders/seven_eleven_dk.py
Only bookable camp site grounds are included.
=> Add Parks Victoria (AU) (73 locations)

locations/spiders/vestis_uniform_services_us.py
{'atp/brand/Vestis': 281,
'atp/brand/Vestis Cleanroom Services': 10,
'atp/brand_wikidata/Q122947676': 291,
'atp/category/shop/laundry': 291,
'atp/field/email/missing': 291,
'atp/field/image/missing': 291,
'atp/field/opening_hours/missing': 291,
'atp/field/operator/missing': 291,
'atp/field/operator_wikidata/missing': 291,
'atp/field/twitter/missing': 291,
'atp/nsi/brand_missing': 291,
'downloader/request_bytes': 4708,
'downloader/request_method_count/POST': 3,
'downloader/response_bytes': 22964,
'downloader/response_status_count/200': 4,
'elapsed_time_seconds': 5.553261, …
=> [VestisUniformServicesUS] Add category

locations/spiders/serious_coffee.py, locations/spiders/seven_eleven_dk.py
{'atp/brand/Serious Coffee': 12,
'atp/category/amenity/cafe': 12,
'atp/field/brand_wikidata/missing': 12,
'atp/field/country/from_reverse_geocoding': 11,
'atp/field/image/missing': 12,
'atp/field/name/missing': 12,
'atp/field/opening_hours/invalid': 1,
'atp/field/street_address/missing': 12,
'downloader/request_bytes': 8310,
'downloader/request_count': 20,
'downloader/request_method_count/GET': 20,
'downloader/response_bytes': 103935,
'downloader/response_count': 20,
'downloader/response_status_count/200': 18, …
=> [SeriousCoffee] Add category

locations/spiders/seven_eleven_dk.py, locations/spiders/tacotote.py
{'atp/brand/El Taco Tote': 23,
'atp/brand_wikidata/Q16992316': 23,
'atp/category/amenity/restaurant': 23,
'atp/field/country/from_reverse_geocoding': 23,
'atp/field/postcode/missing': 23,
'downloader/request_bytes': 8831,
'downloader/request_count': 22,
'downloader/request_method_count/GET': 22,
'downloader/response_bytes': 1213475,
'downloader/response_count': 22,
'downloader/response_status_count/200': 22, …
=> [TacoTote] Add category

locations/spiders/seven_eleven_dk.py, locations/spiders/viva_chicken.py
{'atp/brand/Viva Chicken': 17,
'atp/category/amenity/restaurant': 17,
'atp/field/brand_wikidata/missing': 17,
'atp/field/country/from_reverse_geocoding': 17,
'downloader/response_bytes': 33436,
'elapsed_time_seconds': 1.448955, …
=> [VivaChicken] Add category

locations/spiders/seven_eleven_dk.py, locations/spiders/whidbey_coffee.py
{'atp/brand/Whidbey Coffee': 12,
'atp/category/amenity/cafe': 12,
'atp/cdn/cloudflare/response_count': 26,
'atp/cdn/cloudflare/response_status_count/200': 26,
'atp/field/brand_wikidata/missing': 12,
'atp/field/country/from_reverse_geocoding': 12,
'atp/field/image/missing': 12,
'atp/field/state/from_reverse_geocoding': 9,
'atp/field/street_address/missing': 12,
'downloader/request_bytes': 20400,
'downloader/request_count': 26,
'downloader/request_method_count/GET': 26,
'downloader/response_bytes': 673269,
'downloader/response_count': 26, …
=> [WhidbeyCoffee] Add category

locations/spiders/seven_eleven_dk.py, locations/spiders/timpson_gb.py
{'atp/brand/Timpson': 1318,
'atp/brand_wikidata/Q7807658': 1318,
'atp/category/craft/key_cutter': 33,
'atp/category/shop/hairdresser': 1,
'atp/category/shop/laundry': 4,
'atp/category/shop/photo': 1,
'atp/category/shop/shoe_repair': 1279,
'atp/field/email/missing': 1318,
'atp/field/image/missing': 1318,
'atp/field/opening_hours/missing': 1318,
'atp/field/operator/missing': 1318,
'atp/field/operator_wikidata/missing': 1318,
'atp/field/state/missing': 1190,
'atp/field/twitter/missing': 1318,
'atp/nsi/category_match': 1,
'atp/nsi/cc_match': 5,
'atp/nsi/match_failed': 1312,
'downloader/exception_type_count/scrapy.exceptions.IgnoreRequest': 1, …
=> [TimpsonGB] Add category

locations/spiders/conad_it.py, locations/spiders/seven_eleven_dk.py
{'atp/brand/Conad': 1223,
'atp/brand/Conad City': 999,
'atp/brand/Conad Superstore': 251,
'atp/brand/Margherita Conad': 353,
'atp/brand/Parafarmacia Conad': 2,
'atp/brand/Petstore': 140,
'atp/brand/Sapori & Dintorni Conad': 17,
'atp/brand/Spazio Conad': 80,
'atp/brand/Spesa Facile': 19,
'atp/brand/Tuday Conad': 32,
'atp/brand_wikidata/Q118129616': 251,
'atp/brand_wikidata/Q118130063': 80,
'atp/brand_wikidata/Q57543102': 999,
'atp/brand_wikidata/Q639075': 1176,
'atp/category/amenity/fuel': 47,
'atp/category/amenity/pharmacy': 2,
'atp/category/multiple': 2,
'atp/category/shop/convenience': 421,
'atp/category/shop/pet': 140,
'atp/category/shop/supermarket': 2506,
'atp/field/brand_wikidata/missing': 610,
'atp/field/city/missing': 3116,
'atp/field/country/from_spider_name': 3116, …
=> [ConadIT] Add category

locations/spiders/groszek_pl.py, locations/spiders/seven_eleven_dk.py
{'atp/brand/Groszek': 1927,
'atp/brand_wikidata/Q9280965': 1927,
'atp/category/shop/convenience': 1657,
'atp/category/shop/supermarket': 270,
'atp/field/country/from_spider_name': 1927,
'atp/field/email/missing': 1927,
'atp/field/image/missing': 1927,
'atp/field/opening_hours/missing': 1927,
'atp/field/operator/missing': 1927,
'atp/field/operator_wikidata/missing': 1927,
'atp/field/phone/missing': 1927,
'atp/field/street_address/missing': 1927,
'atp/field/twitter/missing': 1927,
'atp/field/website/missing': 1927,
'atp/nsi/category_match': 1927,
'downloader/request_bytes': 764,
'downloader/response_bytes': 86862, …
=> [GroszekPL] Add category

locations/categories.py, locations/spiders/premium_outlets.py
```python
{'atp/brand/Premium Outlets': 74,
'atp/category/shop/mall': 74,
'atp/field/brand_wikidata/missing': 74,
'atp/field/operator/missing': 74,
'atp/field/operator_wikidata/missing': 74,
'downloader/request_bytes': 55610,
'downloader/request_count': 76,
'downloader/request_method_count/GET': 76,
'downloader/response_bytes': 12879897,
'downloader/response_count': 76,
'downloader/response_status_count/200': 76,
'elapsed_time_seconds': 1.908956,
'finish_time': datetime.datetime(2024, 1, 24, 20, 16, 38, 755753, tzinfo=datetime.timezone.utc),
'httpcache/hit': 76,
'httpcompression/response_bytes': 61806069,
'httpcompression/response_count': 76, …
```
=> [Premium Outlets] Add spider

locations/spiders/tanger.py, locations/spiders/tanger_us.py
```python
{'atp/brand/Tanger Outlets': 36,
'atp/brand_wikidata/Q7682888': 36,
'atp/category/shop/mall': 36,
'atp/field/city/missing': 36,
'atp/field/country/from_spider_name': 36,
'atp/field/phone/missing': 36,
'atp/field/postcode/missing': 36,
'atp/field/state/from_reverse_geocoding': 36,
'atp/nsi/perfect_match': 36,
'downloader/request_bytes': 29738,
'downloader/request_count': 40,
'downloader/request_method_count/GET': 40,
'downloader/response_bytes': 2368209,
'downloader/response_count': 40, …
```
=> [Tanger] Add spider

locations/spiders/circle_k_pl.py, locations/spiders/seven_eleven_dk.py
rel: [ #6849](https://github.com/alltheplaces/alltheplaces/pull/6849#issuecomment-1905944613)
=> [circle_k_pl] improve fuel map

locations/spiders/bremer_bank_us.py
{'atp/brand/Bremer Bank': 71,
'atp/brand_wikidata/Q907603': 71,
'atp/category/amenity/bank': 71,
'atp/field/country/from_reverse_geocoding': 71,
'atp/field/email/missing': 71,
'atp/field/image/missing': 71,
'atp/field/name/missing': 71,
'atp/field/opening_hours/missing': 71,
'atp/field/operator/missing': 71,
'atp/field/operator_wikidata/missing': 71,
'atp/field/twitter/missing': 71,
'atp/field/website/missing': 71,
'atp/nsi/brand_missing': 71,
'downloader/request_bytes': 26170,
'downloader/request_count': 73,
'downloader/request_method_count/GET': 73,
'downloader/response_bytes': 3531737,
'downloader/response_count': 73,
'downloader/response_status_count/200': 72, …
=> [BremerBankUS] Add category

locations/spiders/iowa_university_us.py
{'atp/brand/University of Iowa Hospitals and Clinics': 43,
'atp/brand_wikidata/Q7895561': 43,
'atp/category/amenity/clinic': 8,
'atp/category/amenity/hospital': 35,
'atp/category/multiple': 43,
'atp/field/country/from_spider_name': 43,
'atp/field/email/missing': 43,
'atp/field/image/missing': 43,
'atp/field/opening_hours/missing': 43,
'atp/field/twitter/missing': 43,
'atp/nsi/brand_missing': 43,
'downloader/request_bytes': 3843,
'downloader/request_method_count/POST': 4,
'downloader/response_bytes': 16044,
'downloader/response_count': 6,
'downloader/response_status_count/200': 4, …
=> [IowaUniversityUS] Add category

locations/spiders/sams_club_mx.py
```python
{"atp/brand/Sam's Club": 171,
'atp/brand_wikidata/Q1972120': 171,
'atp/category/shop/wholesale': 171,
'atp/field/email/missing': 171,
'atp/field/image/missing': 171,
'atp/field/opening_hours/missing': 171,
'atp/field/operator/missing': 171,
'atp/field/operator_wikidata/missing': 171,
'atp/field/twitter/missing': 171,
'atp/nsi/cc_match': 171,
'downloader/request_bytes': 733,
'downloader/response_bytes': 18684,
'elapsed_time_seconds': 0.585441,
'finish_time': datetime.datetime(2024, 1, 25, 10, 52, 2, …
```
=> [SamsClub MX] Add website

locations/spiders/mcmenamins_us.py
{'atp/brand/McMenamins': 64,
'atp/brand_wikidata/Q6802345': 64,
'atp/category/amenity/pub': 64,
'atp/field/email/missing': 64,
'atp/field/image/missing': 64,
'atp/field/lat/missing': 64,
'atp/field/lon/missing': 64,
'atp/field/name/missing': 64,
'atp/field/operator/missing': 64,
'atp/field/operator_wikidata/missing': 64,
'atp/field/twitter/missing': 64,
'atp/nsi/category_match': 64,
'downloader/request_bytes': 26787,
'downloader/request_count': 66,
'downloader/request_method_count/GET': 66,
'downloader/response_bytes': 4097924,
'downloader/response_count': 66,
'downloader/response_status_count/200': 66,
'elapsed_time_seconds': 84.976956,
'finish_time': datetime.datetime(2024, 1, …
=> [McMenamins] Add category

locations/spiders/ovs.py
```python
{'atp/brand/OVS': 1440,
'atp/brand_wikidata/Q2042514': 1440,
'atp/category/shop/clothes': 1440,
'atp/field/image/missing': 1440,
'atp/field/opening_hours/missing': 318,
'atp/field/operator/missing': 1440,
'atp/field/operator_wikidata/missing': 1440,
'atp/field/phone/invalid': 113,
'atp/field/phone/missing': 246,
'atp/field/postcode/missing': 29,
'atp/field/state/missing': 305,
'atp/field/twitter/missing': 1440,
'atp/field/website/missing': 78,
'atp/nsi/perfect_match': 1440,
'downloader/request_bytes': 1323, …
```
=> [OVS] Add spider

locations/spiders/wellstar_us.py
{'atp/brand/WellStar Health System': 250,
'atp/brand_wikidata/Q7981073': 250,
'atp/category/amenity/clinic': 26,
'atp/category/amenity/doctors': 184,
'atp/category/amenity/hospital': 14,
'atp/category/amenity/pharmacy': 2,
'atp/category/amenity/social_facility': 1,
'atp/category/emergency/emergency_ward_entrance': 12,
'atp/category/healthcare/laboratory': 2,
'atp/category/healthcare/rehabilitation': 9,
'atp/category/multiple': 226,
'atp/field/country/from_spider_name': 250,
'atp/field/email/missing': 250,
'atp/field/image/missing': 250,
'atp/field/operator/missing': 250,
'atp/field/operator_wikidata/missing': 250,
'atp/field/street_address/missing': 250, …
=> [WellstarUS] Rename, use DictParser and add categories

locations/spiders/chetyre_lapy_ru.py
Stats:
```json
{
"atp/brand/Четыре лапы": 504,
"atp/brand_wikidata/Q62390783": 504,
"atp/category/shop/pet": 504,
"atp/cdn/cloudflare/response_count": 90,
"atp/cdn/cloudflare/response_status_count/200": 90,
"atp/field/city/missing": 504,
"atp/field/country/from_spider_name": 504,
"atp/field/email/missing": 504,
"atp/field/operator/missing": 504,
"atp/field/operator_wikidata/missing": 504,
"atp/field/postcode/missing": 504,
"atp/field/state/missing": 504,
"atp/field/street_address/missing": 504,
"atp/field/twitter/missing": 504,
"atp/nsi/perfect_match": 504,
"downloader/request_bytes": 39222,
"downloader/request_count": 90,
"downloader/request_method_count/GET": 90,
"downloader/response_bytes": 2038657,
"downloader/response_count": 90,
"downloader/response_status_count/200": 90, …
```
=> [chetyre_lapy_ru] add spider (504 locations)

locations/spiders/pkequipment.py, locations/spiders/seven_eleven_dk.py
{'atp/brand/P&K Equipment': 20,
'atp/category/shop/tractor': 20,
'atp/field/brand_wikidata/missing': 20,
'atp/field/country/from_reverse_geocoding': 20,
'atp/field/phone/missing': 20,
'downloader/request_bytes': 9444,
'downloader/request_count': 22,
'downloader/request_method_count/GET': 22,
'downloader/response_bytes': 927874,
'downloader/response_count': 22,
'downloader/response_status_count/200': 22,
'elapsed_time_seconds': 5.891493,
'finish_time': datetime.datetime(2024, 1, 24, 11, 32, 59, 808170, tzinfo=datetime.timezone.utc), …
=> [PKEquipment] Add category

locations/spiders/ridleys.py, locations/spiders/seven_eleven_dk.py
{"atp/brand/Ridley's Family Markets": 27,
'atp/brand_wikidata/Q7332999': 27,
'atp/category/shop/supermarket': 27,
'atp/field/opening_hours/missing': 27,
'atp/field/website/missing': 27,
'atp/nsi/brand_missing': 27,
'downloader/response_bytes': 2598,
'elapsed_time_seconds': 2.568602,
'finish_time': datetime.datetime(2024, 1, 24, 11, 50, 36, 929229, tzinfo=datetime.timezone.utc),
'httpcompression/response_bytes': …
=> [Ridleys] Add category

locations/spiders/activ_fitness_ch.py
Rel: https://github.com/osmlab/name-suggestion-index/pull/9206
=> [ActivFitness CH] Add spider

DATA_FORMAT.md
per https://github.com/alltheplaces/alltheplaces/issues/6562#issuecomment-1872906888 it is kept due to TT request
document this so this will be less surprising (I would not expect nonexisting places to be listed)
=> mention end_date=yes

locations/spiders/anthropologie.py
Possibly fixes #6909, even with my VPN I'm blocked.
=> [Anthropologie] Flip coords

DATA_FORMAT.md
based on https://github.com/alltheplaces/alltheplaces/pull/6933#pullrequestreview-1850407890 comments
=> discuss data quality - add warning

locations/spiders/popeyes_ae.py
```python
{'atp/brand/Popeyes': 38,
'atp/brand_wikidata/Q1330910': 38,
'atp/category/amenity/fast_food': 38,
'atp/nsi/perfect_match': 38,
'downloader/request_bytes': 700,
'downloader/response_bytes': 6642, …
```
=> [popeyes_ae] Created popeyes_ae spider (38 items)

locations/spiders/popeyes_sg.py
```python
{'atp/brand/Popeyes': 11,
'atp/brand_wikidata/Q1330910': 11,
'atp/category/amenity/fast_food': 11,
'atp/field/city/missing': 11,
'atp/field/country/from_spider_name': 11,
'atp/field/image/missing': 11,
'atp/field/lat/missing': 11,
'atp/field/lon/missing': 11,
'atp/field/postcode/missing': 11,
'atp/field/state/missing': 11,
'atp/field/street_address/missing': 11,
'atp/nsi/perfect_match': 11,
'downloader/response_bytes': 10343, …
```
=> [popeyes_sg] Created spider for popeyes_sg (11 items)

locations/spiders/clean_eatz_us.py
Rel: https://github.com/osmlab/name-suggestion-index/pull/9215
```python
{'atp/brand/Clean Eatz': 121,
'atp/brand_wikidata/Q124412638': 121,
'atp/category/missing': 121,
'atp/field/country/from_spider_name': 121,
'atp/field/image/dropped': 121,
'atp/field/image/missing': 121,
'atp/field/name/missing': 121,
'atp/field/operator/missing': 121,
'atp/field/operator_wikidata/missing': 121,
'atp/field/phone/missing': 20,
'atp/field/twitter/missing': 120,
'atp/nsi/brand_missing': 121,
'downloader/request_bytes': 49783,
'downloader/request_count': 125,
'downloader/request_method_count/GET': 125,
'downloader/response_bytes': 1443469,
'downloader/response_count': 125,
'downloader/response_status_count/200': 125, …
```
=> [CleanEatz US] Add spider

locations/spiders/bealls_us.py
```python
{'atp/brand/Bealls': 580,
'atp/brand_wikidata/Q4876153': 580,
'atp/category/shop/department_store': 580,
'atp/field/country/from_spider_name': 580,
'atp/field/email/missing': 580,
'atp/field/operator/missing': 580,
'atp/field/operator_wikidata/missing': 580,
'atp/nsi/perfect_match': 580,
'downloader/request_bytes': 230519,
'downloader/request_count': 586,
'downloader/request_method_count/GET': 586,
'downloader/response_bytes': 22354416,
'downloader/response_count': 586,
'downloader/response_status_count/200': 586,
'elapsed_time_seconds': 8.291773,
'finish_time': datetime.datetime(2024, 2, 2, 16, 2, 7, …
```
=> [Bealls US] Add spider

locations/spiders/franco_manca_gb.py
Replaced my local Pizza Express!
```
'atp/brand/Franco Manca': 71,
'atp/brand_wikidata/Q28404417': 71,
'atp/category/amenity/restaurant': 71,
'atp/field/city/missing': 71,
'atp/field/country/from_spider_name': 71,
'atp/field/email/missing': 71,
'atp/field/image/missing': 71,
'atp/field/opening_hours/missing': 71,
'atp/field/operator/missing': 71,
'atp/field/operator_wikidata/missing': 71,
'atp/field/postcode/missing': 71,
'atp/field/state/missing': 71,
'atp/field/street_address/missing': 71,
'atp/field/twitter/missing': 71,
'atp/nsi/perfect_match': 71,
```
=> [franco_manca_gb] added, a growing UK pizza chain (70+ locations)

locations/spiders/bufkes_nl.py
Rel: https://github.com/osmlab/name-suggestion-index/pull/9204
=> [Bufkes NL] Add spider

locations/spiders/bayshore_healthcare.py
Set the default category to clinic.
=> [BayshoreHealthcare] Add category

locations/spiders/kokoro_gb.py
Rel: https://github.com/osmlab/name-suggestion-index/issues/9220
=> [Kokoro GB] Add spider

locations/spiders/solidcore_us.py
Rel: https://github.com/osmlab/name-suggestion-index/commit/c24c37099385133c6806d8241103061c8f021cbe
No coords :(
=> [Solidcore US] Add spider

locations/spiders/ismash_gb.py
Rel: https://github.com/osmlab/name-suggestion-index/pull/8914
=> [iSmash GB] Add spider

locations/spiders/aster_pharmacy_ae.py
Rel: https://github.com/osmlab/name-suggestion-index/pull/9229
=> [AsterPharmacy AE] Add spider

locations/spiders/spar_za.py
=> [SparZA] Add spider (1106 locations)

locations/spiders/marionnaud.py
It works fine locally. May be a proxy issue.
=> [Marionnaud] Flag as needing proxy

locations/spiders/liquorland_nz.py
=> Add Liquorland (NZ) (169 stores)

locations/spiders/prestons_za.py
=> Add Prestons (ZA) (22 stores)

locations/spiders/thirsty_camel_au.py
=> Add Thirsty Camel (AU) (265 stores)

locations/spiders/rotten_robbie_us.py
=> [RottenRobbieUS] Add spider (37 locations)

locations/spiders/endlich_ohn_de.py
Fix https://github.com/alltheplaces/alltheplaces/issues/7129
```
2024-02-11 07:27:21 [scrapy.statscollectors] INFO: Dumping Scrapy stats:
{'atp/brand/Endlich Ohne': 24,
'atp/brand_wikidata/Q119982663': 24,
'atp/category/shop/beauty': 24,
'atp/field/opening_hours/missing': 24,
'atp/field/state/missing': 22,
'atp/nsi/perfect_match': 24,
'downloader/request_bytes': 679, …
```
=> Endlich Ohn (DE) (shop/beauty) (WPStoreLocator) (24 locations)

locations/spiders/bilgro_de.py
Fix https://github.com/alltheplaces/alltheplaces/issues/7131
2024-02-11 07:20:43 [scrapy.statscollectors] INFO: Dumping Scrapy stats:
{'atp/brand/bilgro': 117,
'atp/brand_wikidata/Q108029888': 117,
'atp/category/shop/beverages': 117,
'atp/field/country/from_spider_name': 117,
'atp/field/opening_hours/missing': 117,
'atp/field/phone/invalid': 26,
'atp/field/state/missing': 114,
'atp/field/website/missing': 117,
'atp/nsi/perfect_match': 117,
'downloader/request_bytes': 731, …
=> bilgro (DE) (shop/beverages) (WPStoreLocator) (117 stores)

locations/spiders/tanning_shop_ie.py
Fix https://github.com/alltheplaces/alltheplaces/issues/7127
```
{'atp/brand/Tanning Shop': 101,
'atp/brand_wikidata/Q123101132': 101,
'atp/category/shop/beauty': 101,
'atp/field/email/missing': 101,
'atp/field/opening_hours/missing': 101,
'atp/nsi/perfect_match': 101,
'downloader/request_bytes': 684,
'downloader/response_bytes': 18009, …
```
=> Tanning Shop (IE) (shop/beauty) (AgileStoreLocator) (101 locations)

locations/spiders/blue_bottle_liquors_za.py
Fix https://github.com/alltheplaces/alltheplaces/issues/6997
2024-02-11 22:27:31 [scrapy.core.scraper] DEBUG: Scraped from <200 https://bluebottleliquors.co.za/wp-admin/admin-ajax.php?action=asl_load_stores&load_all=1>
{'brand': 'Blue Bottle Liquors',
'brand_wikidata': 'Q116861688',
'city': 'Groblersdal',
'country': 'ZA',
'email': None,
'extras': {'@spider': 'blue_bottle_liquors_za'},
'geometry': {'coordinates': [29.397561, -25.16667296], 'type': 'Point'},
'name': 'ZCW Blue Bottle Liquors XL',
'opening_hours': None,
'phone': None,
'postcode': None,
'ref': '453',
'state': 'Limpopo',
'street_address': '5 Hereford Street, Groblersdal',
'website': None}
2024-02-11 22:27:31 [scrapy.core.scraper] DEBUG: Scraped from <200 …
=> Add Blue Bottle Liquors (ZA) (440 locations)

locations/spiders/goodfeet.py
https://github.com/alltheplaces/alltheplaces/issues/1649
```
{'atp/brand/Good Feet': 65,
'atp/category/missing': 65,
'atp/field/brand_wikidata/missing': 65,
'downloader/request_bytes': 376414,
'downloader/request_count': 347,
'downloader/request_method_count/GET': 347,
'downloader/response_bytes': 5917218,
'downloader/response_count': 347,
'downloader/response_status_count/200': 347,
'elapsed_time_seconds': 485.697923,
'finish_time': datetime.datetime(2024, 2, 12, 8, 56, 9, 536276, …
```
=> The Good Feet Store (Worldwide) (Structured Data) (65 locations)

locations/spiders/eb_games_nz.py
Fix https://github.com/alltheplaces/alltheplaces/issues/6994
NZ version of https://github.com/alltheplaces/alltheplaces/pull/5340/files
```
2024-02-12 08:17:38 [scrapy.statscollectors] INFO: Dumping Scrapy stats:
{'atp/brand/EB Games': 39,
'atp/brand_wikidata/Q4993686': 39,
'atp/category/shop/video_games': 39,
'atp/field/city/missing': 39,
'atp/field/country/from_website_url': 39,
'atp/field/email/missing': 39,
'atp/field/image/missing': 39,
'atp/field/opening_hours/missing': 39,
'atp/field/operator/missing': 39,
'atp/field/operator_wikidata/missing': 39,
'atp/field/postcode/missing': 39,
'atp/field/state/missing': 39,
'atp/field/street_address/missing': 39,
'atp/nsi/perfect_match': 39,
'downloader/request_bytes': 34184,
'downloader/request_count': 41, …
```
=> Add EB Games (NZ) (shop/video_games) (39 stores)

locations/spiders/winelab_ru.py
rel: #7053 
Stats:
```json
{
"atp/brand/\u0412\u0438\u043d\u043b\u0430\u0431": 773,
"atp/brand_wikidata/Q109907753": 773,
"atp/category/shop/alcohol": 773,
"atp/field/email/missing": 773,
"atp/field/image/missing": 773,
"atp/field/operator/missing": 773,
"atp/field/operator_wikidata/missing": 773,
"atp/field/postcode/missing": 773,
"atp/field/state/missing": 773,
"atp/field/street_address/missing": 773,
"atp/field/twitter/missing": 773,
"atp/nsi/perfect_match": 773,
"downloader/request_bytes": 808,
"downloader/response_bytes": 108583,
"elapsed_time_seconds": 2.35444, …
```
=> [winelab_ru] add spider (773 locations)

locations/spiders/eb_games_au.py, locations/spiders/eb_games_nz.py
Change wikidata to the AU/NZ offshoot
Fixes https://github.com/alltheplaces/alltheplaces/issues/7178
=> Update EB Games (AU, NZ) - wikidata

locations/spiders/baby_city.py
=> [BabyCity] Add spider (52 locations)

locations/spiders/checkers_za.py
'atp/brand/Checkers': 213,
'atp/brand/Checkers Hyper': 37,
'atp/brand_wikidata/Q116518886': 37,
'atp/brand_wikidata/Q5089126': 213,
Fixes #7016
=> Add Checkers and Checkers Hyper (ZA) (250 stores)

locations/spiders/bike_totaal_nl.py, locations/structured_data_spider.py
=> Add Bike Totaal (NL) (146 stores)

locations/spiders/dirck_iii_nl.py
=> Add Dirck III (NL) (94 stores)

locations/spiders/liquorshop_za.py
=> Add LiquorShop (ZA) (210 stores)

locations/spiders/combi_de.py
=> [CombiDE] Add spider (192 locations)

locations/spiders/micromania_fr.py
=> Add Micromania (FR) (314 stores)

locations/spiders/ultra_liquors_za.py
=> [UltraLiquors] Add spider (23 locations)

locations/spiders/winetime_ua.py
=> Add WINETIME (UA) (35 shops)

locations/spiders/nordsee.py
The spider outputs locations in Austria and it gives them an incorrect country label.
=> [NordseeDE] Rename spider

locations/spiders/costco.py, locations/spiders/costco_us.py
It works locally so I tried adding `requires_proxy=true`
Logs from last run: https://alltheplaces-data.openaddresses.io/runs/2024-02-10-13-31-58/logs/costco.txt
=> Attempt to fix `costco` spider with proxy

locations/spiders/costco.py
```python
{'atp/brand/Costco': 574,
'atp/brand_wikidata/Q715583': 574,
'atp/category/shop/wholesale': 574,
'atp/field/country/from_reverse_geocoding': 571,
'atp/field/country/missing': 3,
'atp/field/email/missing': 574,
'atp/field/image/missing': 574,
'atp/field/operator/missing': 574,
'atp/field/operator_wikidata/missing': 574,
'atp/field/twitter/missing': 574,
'atp/nsi/match_failed': 574,
'downloader/request_bytes': 3073096,
'downloader/request_count': 576,
'downloader/request_method_count/GET': 576, …
```
=> [Costco] Collect opening hours

locations/spiders/sani_dump_nl.py
=> Add Sani-Dump (NL) (40 stores)

locations/spiders/disc_replay_us.py
=> Add Disc Replay (US) (36 stores)

locations/dict_parser.py, locations/spiders/carpet_one_floor_and_home_ca.py, locations/spiders/carpet_one_floor_and_home_us.py
=> Add Carpet One Floor & Home (US+CA) (624+74 stores)

locations/spiders/salvatore_ca.py
Rel: https://github.com/osmlab/name-suggestion-index/pull/9251
=> [SalvatoreCA] Add spider

locations/spiders/newspower_au.py
=> newspower_au: use proxy and explain use of SitemapSpider

locations/spiders/easy_bathrooms_gb.py
=> Add Easy Bathrooms (GB) (138 stores)

locations/spiders/tesco_eu.py
Stats:
```json
{
"atp/brand/Tesco": 403,
"atp/brand/Tesco Express": 130,
"atp/brand/Tesco Extra": 24,
"atp/brand_wikidata/Q25172225": 24,
"atp/brand_wikidata/Q487494": 403,
"atp/brand_wikidata/Q98456772": 130,
"atp/category/shop/convenience": 130,
"atp/category/shop/supermarket": 427,
"atp/field/email/missing": 557,
"atp/field/image/missing": 557,
"atp/field/operator/missing": 557,
"atp/field/operator_wikidata/missing": 557,
"atp/field/phone/invalid": 3,
"atp/field/phone/missing": 211,
"atp/field/state/missing": 557,
"atp/field/twitter/missing": 557,
"atp/field/website/invalid": 1,
"atp/nsi/category_match": 403,
"atp/nsi/perfect_match": 154,
"downloader/request_bytes": 2255,
"downloader/request_count": 6,
"downloader/request_method_count/GET": 6,
"downloader/response_bytes": 4769985, …
```
=> [tesco_eu] add spider (557 locations)

locations/spiders/selfast_za.py
=> Add Selfast (ZA) (46 stores)

docs/SITEMAP.md
disclaimer: I am not a native speaker
but it seems much better to me, repeated forward sounded a bit weird
(I hope that it actually improves thing, sorry if it does not)
=> try better phrasing

locations/spiders/hit_de.py, locations/spiders/wiener_feinbacker_heberer_de.py
=> Add Wiener Feinbäcker Heberer (DE) (181 stores)

docs/STRUCTURED_DATA.md
=> try to get rid of red marker

locations/spiders/hema.py
```python
{'atp/brand/HEMA': 838,
'atp/brand_wikidata/Q903805': 838,
'atp/category/shop/department_store': 838,
'atp/cdn/cloudflare/response_count': 165,
'atp/cdn/cloudflare/response_status_count/200': 165,
'atp/field/country/from_reverse_geocoding': 740,
'atp/field/country/missing': 98,
'atp/field/email/missing': 838,
'atp/field/image/missing': 838,
'atp/field/lat/missing': 98,
'atp/field/lon/missing': 98,
'atp/field/opening_hours/missing': 180,
'atp/field/operator/missing': 838,
'atp/field/operator_wikidata/missing': 838,
'atp/field/phone/invalid': 78,
'atp/field/state/missing': 98,
'atp/field/twitter/missing': 838,
'atp/field/website/missing': 838,
'atp/nsi/perfect_match': 838,
'downloader/request_bytes': 467034,
'downloader/request_count': 165, …
```
=> [Hema] Add spider

locations/spiders/helzberg_diamonds.py
No structured data.
Was yielding 0 POIs.
=> [HelzbergDiamonds] Fix error in address xpath and remove StructuredDataSpider

locations/spiders/sigma_it.py, locations/storefinders/agile_store_locator.py
=> Add Sigma (IT) (572 stores)

locations/spiders/tonys_fresh_market_us.py
=> Add Tony's Fresh Market (US) (21 stores)

locations/spiders/peluquerias_low_cost_es.py
=> Add Peluquerías Low Cost (ES) (494 stores)

locations/spiders/hinnerbaecker_de.py
Fix https://github.com/alltheplaces/alltheplaces/issues/7290
2024-02-24 02:48:11 [scrapy.statscollectors] INFO: Dumping Scrapy stats:
{'atp/brand/Hinnerbäcker': 65,
'atp/brand_wikidata/Q107985183': 65,
'atp/category/shop/bakery': 65,
'atp/field/state/missing': 59,
'downloader/response_bytes': 8852,
'elapsed_time_seconds': 5.175819,
'finish_time': …
=> Add Hinnerbäcker (DE) (shop/bakery) (AgileStoreLocator) 65 locations 

locations/storefinders/uberall.py
Only 1x of the methods here works without JS.
However, on the off chance someone manually loads these bundles in to the DOM, it will work.
=> Uberall - Autodetect

locations/spiders/aarons.py
=> Add Aaron's (CA/US) (1244 stores)

locations/spiders/proper_job_gb.py
Fixes https://github.com/alltheplaces/alltheplaces/issues/7516
{'atp/brand/Proper Job': 20,
'atp/brand_wikidata/Q83741810': 20,
'atp/category/shop/hardware': 20,
'atp/nsi/perfect_match': 20,
'downloader/request_bytes': 675,
'downloader/response_bytes': 29261,
'elapsed_time_seconds': 3.207815,
'finish_time': datetime.datetime(2024, 2, 25, 7, 1, 31, 864085, …
=> Add Proper Job (GB) 20 locations

locations/spiders/sparkasse_de.py
Fix #4571
- update sitemap url
- rename spider to _sparkasse_de_
=> [SparkasseDE] Fix spider

locations/spiders/speedy_auto_service_ca.py
Fix https://github.com/alltheplaces/alltheplaces/issues/7371
{'atp/brand/Speedy Auto Service': 50,
'atp/brand_wikidata/Q22318193': 50,
'atp/category/shop/car_repair': 50,
'atp/field/website/missing': 50,
'atp/nsi/perfect_match': 50,
'downloader/request_bytes': 843,
'downloader/response_bytes': 4721,
'elapsed_time_seconds': 2.814362,
'finish_time': datetime.datetime(2024, 2, 25, 21, 22, 32, 12207, tzinfo=datetime.timezone.utc), …
=> Add Speedy Auto Service (CA)

locations/spiders/kokoro_gb.py
NSI decided on fast food. https://github.com/osmlab/name-suggestion-index/issues/9220
=> [Kokoro GB] Switch to fast food

locations/spiders/primanti_bros_us.py
=> primanti_bros_us: fix spider by converting to YextSpider

ci/run_all_spiders.sh
See https://github.com/alltheplaces/alltheplaces.xyz/issues/52
=> Use Bunny.net API to purge its cache after uploading new data

locations/spiders/bauspezi_de.py
Fixes https://github.com/alltheplaces/alltheplaces/issues/7521
{'atp/brand/BauSpezi': 89,
'atp/brand_wikidata/Q85324366': 89,
'atp/category/shop/doityourself': 89,
'atp/field/opening_hours/missing': 89,
'atp/field/phone/missing': 89,
'atp/field/postcode/missing': 89,
'atp/field/website/missing': 89,
'atp/nsi/perfect_match': 89,
'downloader/request_bytes': 709,
'downloader/response_bytes': 9976, …
=> Implement very basic bauspezi_de

locations/spiders/coffee_like.py
Stats:
```json
{
"atp/brand/Coffee Like": 1075,
"atp/brand_wikidata/Q55662627": 1075,
"atp/category/amenity/cafe": 1075,
"atp/field/country/from_reverse_geocoding": 1075,
"atp/field/email/missing": 1075,
"atp/field/image/missing": 831,
"atp/field/lat/missing": 1,
"atp/field/lon/invalid": 1,
"atp/field/lon/missing": 1,
"atp/field/opening_hours/missing": 322,
"atp/field/operator/missing": 1075,
"atp/field/operator_wikidata/missing": 1075,
"atp/field/phone/missing": 1075,
"atp/field/postcode/missing": 1075,
"atp/field/street_address/missing": 1075,
"atp/field/twitter/missing": 1075,
"atp/field/website/missing": 1075,
"atp/nsi/perfect_match": 1075,
"downloader/request_bytes": 617,
"downloader/response_bytes": 138566, …
```
=> [coffee_like] add spider (1075 locations)

README.md
Closes https://github.com/alltheplaces/alltheplaces/pull/7549
=> Mention docker and codespaces in readme

locations/spiders/service_apotheek_nl.py
Rel: https://github.com/osmlab/name-suggestion-index/pull/9279
=> [Service Apotheek NL] Add Spider

locations/spiders/mightyflame.py
5500 ish propane exchange locations (gas stations, hardware stores) in US and CA.
=> Add spider for Mighty Flame

locations/spiders/ok_nl.py
Rel: https://github.com/osmlab/name-suggestion-index/pull/9277
=> [OK NL] Add spider

locations/spiders/chicken_street.py
Rel: https://github.com/osmlab/name-suggestion-index/pull/9278
=> [ChickenStreet] Add spider

locations/spiders/fussl_at_de.py
Fixes https://github.com/alltheplaces/alltheplaces/issues/7365
{'atp/brand/Fussl': 194,
'atp/brand_wikidata/Q24266366': 194,
'atp/category/shop/clothes': 194,
'atp/field/country/from_reverse_geocoding': 163,
'atp/field/country/from_website_url': 31,
'atp/field/email/missing': 188,
'atp/field/image/missing': 194,
'atp/field/operator/missing': 194,
'atp/field/operator_wikidata/missing': 194,
'atp/field/state/missing': 31,
'atp/field/twitter/missing': 194,
'atp/field/website/missing': 163,
'atp/nsi/perfect_match': 194,
'downloader/request_bytes': 668,
'downloader/response_bytes': 21142, …
=> Add Fussl (AT)

locations/spiders/dimmeys_au.py
Fixes https://github.com/alltheplaces/alltheplaces/issues/7506
{'atp/brand/Dimmeys': 19,
'atp/brand_wikidata/Q17003075': 19,
'atp/category/shop/department_store': 19,
'atp/nsi/perfect_match': 19,
'downloader/response_bytes': 2759, …
=> Add Dimmeys (AU)

locations/spiders/econsave_my.py
Fixes https://github.com/alltheplaces/alltheplaces/issues/7550
{'atp/brand/Econsave': 193,
'atp/brand_wikidata/Q61776608': 193,
'atp/category/shop/supermarket': 193,
'atp/field/email/missing': 193,
'atp/field/image/missing': 193,
'atp/field/operator/missing': 193,
'atp/field/operator_wikidata/missing': 193,
'atp/field/phone/invalid': 58,
'atp/field/phone/missing': 27,
'atp/field/twitter/missing': 193,
'atp/field/website/missing': 193,
'atp/nsi/category_match': 192,
'downloader/request_bytes': 674,
'downloader/response_bytes': 16533,
'elapsed_time_seconds': 6.246005,
'finish_time': …
=> Add Econsave (MY)

README.md, docs/NSI_MATCHING.md, docs/PIPELINES.md, docs/WIKIDATA.md
Fixes #7119, Rel: https://github.com/alltheplaces/alltheplaces/issues/6907#issuecomment-1966206809
I've always done Markdown with a line per sentence, it makes the git diffs nicer. However I noticed you changed the warping on some of the docs recently. No strong opinion if you want to do it here as well.
I also wont feel bad if anyone wants to rewrite parts of this, docs aren't my strong point.
=> [Docs] Document Pipelines and NSI matching

locations/spiders/dollar_general.py
```python
{'atp/brand/Dollar General': 19924,
'atp/brand_wikidata/Q145168': 19924,
'atp/category/shop/variety_store': 19924,
'atp/field/email/missing': 19924,
'atp/field/image/missing': 19924,
'atp/field/opening_hours/missing': 22,
'atp/field/operator/missing': 19924,
'atp/field/operator_wikidata/missing': 19924,
'atp/field/twitter/missing': 19924,
'atp/geometry/null_island': 3,
'atp/nsi/category_match': 19924,
'downloader/request_bytes': 7823328,
'downloader/request_count': 19945,
'downloader/request_method_count/GET': 19945, …
```
=> [DollarGeneral] Fix street address collection

locations/spiders/aldi_sud_de.py
=> [AldiSud DE] Improve names

locations/spiders/jiffy_mart.py
Fixes https://github.com/alltheplaces/alltheplaces/issues/7494
{'atp/brand/Jiffy Mart': 45,
'atp/brand_wikidata/Q119592174': 45,
'atp/category/shop/convenience': 45,
'atp/field/country/from_reverse_geocoding': 45,
'atp/field/email/missing': 45,
'atp/field/image/missing': 45,
'atp/field/operator/missing': 45,
'atp/field/operator_wikidata/missing': 45,
'atp/field/twitter/missing': 45,
'atp/nsi/perfect_match': 45,
'downloader/request_bytes': 844,
'downloader/response_bytes': 5250,
'elapsed_time_seconds': 5.512225,
'finish_time': …
=> Add jiffy mart

locations/spiders/cvs_us.py
```python
{'atp/brand/CVS Pharmacy': 9255,
'atp/brand/Longs Drugs': 36,
'atp/brand/Navarro': 27,
'atp/brand_wikidata/Q16931196': 36,
'atp/brand_wikidata/Q2078880': 9255,
'atp/brand_wikidata/Q6982161': 27,
'atp/category/amenity/pharmacy': 9318,
'atp/category/multiple': 9318,
'atp/cvs_us/hours/failed': 18,
'atp/cvs_us/unmapped_store_type/MinuteClinic': 197,
'atp/cvs_us/unmapped_store_type/Oak St. Health now part of CVS Health': 2,
'atp/field/email/missing': 9318,
'atp/field/image/missing': 9318,
'atp/field/operator/missing': 9282,
'atp/field/operator_wikidata/missing': 9282,
'atp/nsi/brand_missing': 27,
'atp/nsi/category_match': 36,
'atp/nsi/match_failed': 9255,
'atp/operator/CVS Pharmacy': 36, …
```
=> [CVS US] Clean up name and street_address

locations/spiders/sleep_number_us.py
Fixes #1650
```
2024-03-02 00:59:36 [scrapy.core.scraper] DEBUG: Scraped from <200 https://www.sleepnumber.com/api/storefront/store-locations?lat=42.8473561&lng=-106.26166833&limit=10000&radius=25000>
{'brand': 'Sleep Number',
'brand_wikidata': 'Q7447640',
'city': 'Kapolei',
'email': None,
'extras': {'@spider': 'sleep_number_us', 'shop': 'bed'},
'geometry': {'coordinates': [-158.09032388, 21.32881817], 'type': 'Point'},
'name': 'Sleep Number',
'nsi_id': 'sleepnumber-032196',
'opening_hours': 'Mo-Su 11:00-19:00',
'phone': None,
'postcode': '96707',
'ref': '1443546729213642636',
'state': 'HI',
'street_address': '4460 Kapolei Parkway',
'website': 'https://www.sleepnumber.com/stores/hi/kapolei/4460-kapolei-pkwy'}
2024-03-02 00:59:36 …
```
=> Add Sleep Number (US)

locations/spiders/vanharen_be_nl.py
Fixes https://github.com/alltheplaces/alltheplaces/issues/7558
{'atp/brand/vanHaren': 126,
'atp/brand_wikidata/Q62390668': 126,
'atp/category/shop/shoes': 126,
'atp/cdn/cloudflare/response_count': 128,
'atp/cdn/cloudflare/response_status_count/200': 127,
'atp/field/operator/missing': 126,
'atp/field/operator_wikidata/missing': 126,
'atp/field/state/missing': 126,
'atp/field/twitter/missing': 126,
'atp/nsi/perfect_match': 126,
'downloader/request_bytes': 71537,
'downloader/request_count': 128,
'downloader/request_method_count/GET': 128,
'downloader/response_bytes': 1975102,
'downloader/response_count': 128,
'downloader/response_status_count/200': 127,
'elapsed_time_seconds': 157.721625, …
=> Add vanHaren (BE, NL)

locations/spiders/dr_kong_hk.py
Fixes https://github.com/alltheplaces/alltheplaces/issues/7563
2024-03-02 14:59:16 [scrapy.statscollectors] INFO: Dumping Scrapy stats:
{'atp/brand/Dr. Kong': 65,
'atp/brand_wikidata/Q116547631': 65,
'atp/category/shop/shoes': 65,
'atp/field/country/from_reverse_geocoding': 64,
'atp/field/postcode/missing': 65,
'downloader/response_bytes': 8596, …
=> Add Dr Kong

locations/spiders/foodland_grocery_us.py
Fixes https://github.com/alltheplaces/alltheplaces/issues/7556
{'atp/brand/FoodLand': 38,
'atp/brand_wikidata/Q5465271': 38,
'atp/category/shop/supermarket': 38,
'atp/field/website/invalid': 37,
'atp/nsi/perfect_match': 38,
'downloader/request_bytes': 690,
'downloader/response_bytes': 5391, …
=> Add FoodLand (US) (Agile)

locations/spiders/halia_baluvana_ua.py
Fixes https://github.com/alltheplaces/alltheplaces/issues/7508
{'atp/brand/Галя Балувана': 177,
'atp/brand_wikidata/Q117744813': 177,
'atp/category/shop/frozen_food': 177,
'atp/field/country/from_spider_name': 177,
'atp/field/email/missing': 177,
'atp/field/image/missing': 177,
'atp/field/operator/missing': 177,
'atp/field/operator_wikidata/missing': 177,
'atp/field/phone/missing': 177,
'atp/field/state/missing': 163,
'atp/field/twitter/missing': 177,
'atp/field/website/missing': 177,
'atp/nsi/perfect_match': 177,
'downloader/response_bytes': 8736, …
=> Add Галя Балувана (UA)

locations/spiders/dominos_pizza_gb.py
This works from my residential GB ip.
=> [Dominios GB] Flag as requiring proxy

locations/spiders/carre_blanc.py, locations/spiders/carre_blanc_fr.py
Fixes https://github.com/alltheplaces/alltheplaces/issues/7653
{'atp/brand/Carré blanc': 140,
'atp/brand_wikidata/Q55596025': 140,
'atp/category/shop/household_linen': 140,
'atp/field/country/from_spider_name': 140,
'atp/field/email/missing': 140,
'atp/field/opening_hours/missing': 140,
'atp/field/operator/missing': 140,
'atp/field/operator_wikidata/missing': 140,
'atp/field/postcode/missing': 13,
'atp/field/state/missing': 140,
'atp/nsi/perfect_match': 140,
'downloader/request_bytes': 85346,
'downloader/request_count': 164,
'downloader/request_method_count/GET': 164,
'downloader/response_bytes': 5449873,
'downloader/response_count': 164,
'downloader/response_status_count/200': 162,
'dupefilter/filtered': 110, …
=> Add Carre blanc

locations/spiders/linvosges_fr.py
Fixes https://github.com/alltheplaces/alltheplaces/issues/7657
2024-03-04 20:56:51 [scrapy.statscollectors] INFO: Dumping Scrapy stats:
{'atp/brand/Linvosges': 42,
'atp/brand_wikidata/Q94359140': 42,
'atp/category/shop/household_linen': 42,
'atp/field/opening_hours/missing': 42,
'atp/field/operator/missing': 42,
'atp/field/operator_wikidata/missing': 42,
'atp/field/state/missing': 42,
'atp/field/twitter/missing': 42,
'atp/nsi/perfect_match': 42,
'downloader/request_bytes': 21156,
'downloader/response_bytes': 7900662,
'downloader/response_count': 44,
'downloader/response_status_count/200': 44,
'elapsed_time_seconds': 54.278498,
'finish_time': …
=> Add Linvosges (FR)

locations/spiders/brico_ok_it.py
Rel: https://github.com/osmlab/name-suggestion-index/issues/9289
=> [Brico OK IT] Add Spider

locations/spiders/holland_bakery_id.py
Rel: https://github.com/osmlab/name-suggestion-index/pull/9293
=> [Holland Bakery ID] Add Spider

locations/spiders/dunnedwards_us.py
Fix https://github.com/alltheplaces/alltheplaces/issues/7696
{'atp/brand/Dunn-Edwards Paints': 157,
'atp/brand_wikidata/Q110586577': 157,
'atp/category/shop/paint': 157,
'atp/field/operator/missing': 157,
'atp/field/operator_wikidata/missing': 157,
'atp/nsi/perfect_match': 157,
'downloader/request_bytes': 60611,
'downloader/request_count': 159,
'downloader/request_method_count/GET': 159,
'downloader/response_bytes': 4650689,
'downloader/response_count': 159,
'downloader/response_status_count/200': 159,
'elapsed_time_seconds': 193.268155,
'finish_time': datetime.datetime(2024, 3, 6, 21, 1, 31, 300431, tzinfo=datetime.timezone.utc),
'httpcompression/response_bytes': 31785746,
'httpcompression/response_count': 159, …
=> Add Dunn-Edwards (US)

locations/spiders/best_friends_au.py
Fixes https://github.com/alltheplaces/alltheplaces/issues/7669
{'atp/brand/Best Friends': 30,
'atp/brand_wikidata/Q106540748': 30,
'atp/category/shop/pet': 30,
'atp/field/email/missing': 30,
'atp/field/image/missing': 30,
'atp/field/opening_hours/missing': 30,
'atp/field/state/missing': 30,
'atp/nsi/perfect_match': 30,
'downloader/request_bytes': 12313,
'downloader/request_count': 32,
'downloader/request_method_count/GET': 32,
'downloader/response_bytes': 1594131,
'downloader/response_count': 32,
'downloader/response_status_count/200': 32,
'elapsed_time_seconds': 39.583643,
'finish_time': datetime.datetime(2024, 3, 6, 21, 13, 23, 594797, …
=> Add Best Friends (AU)

locations/spiders/optie1_nl.py
Fix https://github.com/alltheplaces/alltheplaces/issues/7523
{'atp/brand/Optie1': 41,
'atp/brand_wikidata/Q62393564': 41,
'atp/category/shop/mobile_phone': 41,
'atp/field/country/from_spider_name': 5,
'atp/nsi/perfect_match': 41,
'downloader/request_bytes': 667,
'downloader/response_bytes': 4506,
'elapsed_time_seconds': 6.470902,
'finish_time': datetime.datetime(2024, 3, 9, 4, 18, 36, …
=> Add Optie1 (NL)

locations/spiders/dw_fresh_market_us.py
Fix https://github.com/alltheplaces/alltheplaces/issues/7554
2024-03-09 04:24:25 [scrapy.core.scraper] DEBUG: Scraped from <200 https://api.freshop.com/1/stores?app_key=dw_fresh_market>
{'brand': 'D&W Fresh Market',
'brand_wikidata': 'Q5203035',
'city': 'Williamston',
'email': None,
'extras': {'@spider': 'dw_fresh_market_us',
'delivery': 'no',
'shop': 'supermarket'},
'geometry': {'coordinates': [-84.284414, 42.688466], 'type': 'Point'},
'name': 'D&W Fresh Market - Williamston',
'nsi_id': 'dandwfreshmarket-dde59d',
'opening_hours': 'Mo-Fr 06:00-24:00,09:00-19:00; Sa 06:00-24:00,09:00-17:00; '
'Su 06:00-24:00',
'phone': '(517) 655-2230\n\n**Pharmacy Phone:**\n(517) 655-1372',
'postcode': '48895',
'ref': '1903',
'state': 'MI', …
=> Add DW Fresh Market

locations/spiders/burger_king_ro.py
Fix https://github.com/alltheplaces/alltheplaces/issues/7700
{'atp/brand/Burger King': 21,
'atp/brand_wikidata/Q177054': 21,
'atp/category/amenity/fast_food': 21,
'atp/field/state/missing': 21,
'atp/nsi/category_match': 21,
'downloader/request_bytes': 1011,
'downloader/response_bytes': 22685,
'elapsed_time_seconds': 3.660501,
'finish_time': datetime.datetime(2024, 3, 9, 7, 18, …
=> Burger King (RO)

locations/spiders/leeann_chin_us.py
Fixes https://github.com/alltheplaces/alltheplaces/issues/695
{'atp/brand/Leeann Chin': 41,
'atp/brand_wikidata/Q6515716': 41,
'atp/category/missing': 41,
'atp/field/twitter/invalid': 41,
'atp/nsi/brand_missing': 41,
'downloader/request_bytes': 17023,
'downloader/request_count': 43,
'downloader/request_method_count/GET': 43,
'downloader/response_bytes': 673646,
'downloader/response_count': 43,
'downloader/response_status_count/200': 43,
'elapsed_time_seconds': 50.882446,
'finish_time': datetime.datetime(2024, 3, 9, 6, 39, 11, 330470, tzinfo=datetime.timezone.utc),
'httpcompression/response_bytes': 3409104,
'httpcompression/response_count': 43, …
=> Leeann Chin (US)

.devcontainer/devcontainer.json
As per https://github.com/alltheplaces/alltheplaces/blob/master/docs/PULL_REQUEST.md#submitting-a-pr
=> [Tools] Add git hooks to dev container by default

locations/spiders/abercrombie_and_fitch.py
Fixes https://github.com/alltheplaces/alltheplaces/issues/1803 ?
Works for me in a browser, not so much from codespaces; so.. adding proxy flag.
=> Abercrombie and Fitch - Add proxy

locations/spiders/premierurgentcare.py
Fix https://github.com/alltheplaces/alltheplaces/issues/2686
=> Fix Premier Urgent Care

locations/spiders/societe_generale.py
Fix https://github.com/alltheplaces/alltheplaces/issues/3115
=> Fix societe_generale 

locations/spiders/hollister.py
Fix https://github.com/alltheplaces/alltheplaces/issues/3195 ?
Works for my browser, not in code spaces
=> Hollister - Flag for proxy

locations/spiders/vea.py
Fix https://github.com/alltheplaces/alltheplaces/issues/3393 maybe - geoblocked
=> Vea - Mark as needing proxy

locations/spiders/tractorsupply.py
Fix https://github.com/alltheplaces/alltheplaces/issues/3387 hopefully.
#7767 created to extract the common parts out
=> Tractor Supply: Ignore robots

locations/spiders/planet_fitness.py
Works in my browser
403 from codespaces.
Fix https://github.com/alltheplaces/alltheplaces/issues/2433 ?
=> Planet Fitness - Flag as needing proxy

locations/spiders/t_market_bg.py
=> Add T-Market spider (BG)

locations/spiders/grainger_us.py
=> [Grainger US] Add Spider

locations/spiders/upim.py
```python
{'atp/brand/Blukids': 373,
'atp/brand/Upim': 388,
'atp/brand_wikidata/Q1414836': 388,
'atp/category/missing': 70,
'atp/category/shop/clothes': 373,
'atp/category/shop/department_store': 388,
'atp/field/brand/missing': 70,
'atp/field/brand_wikidata/missing': 443,
'atp/field/email/missing': 831,
'atp/field/image/missing': 831,
'atp/field/opening_hours/missing': 831,
'atp/field/operator/missing': 831,
'atp/field/operator_wikidata/missing': 831,
'atp/field/phone/missing': 225,
'atp/field/state/missing': 93,
'atp/field/twitter/missing': 831,
'atp/nsi/perfect_match': 388,
'downloader/request_bytes': 643, …
```
=> [Upim] Add spider

locations/spiders/mavis_us.py
```python
{'atp/brand/Mavis Discount Tire': 833,
'atp/brand_wikidata/Q65058420': 833,
'atp/category/shop/tyres': 833,
'atp/cdn/cloudflare/response_count': 835,
'atp/cdn/cloudflare/response_status_count/200': 835,
'atp/field/email/missing': 833,
'atp/field/image/missing': 833,
'atp/field/opening_hours/missing': 833,
'atp/field/operator/missing': 833,
'atp/field/operator_wikidata/missing': 833,
'atp/field/street_address/missing': 833,
'atp/field/twitter/missing': 833,
'atp/nsi/perfect_match': 833,
'downloader/request_bytes': 332520,
'downloader/request_count': 835,
'downloader/request_method_count/GET': 835,
'downloader/response_bytes': 16230934,
'downloader/response_count': 835,
'downloader/response_status_count/200': 835,
'elapsed_time_seconds': 6.086247, …
```
=> [Mavis US] Add spider

locations/spiders/securcare_self_storage_us.py
Rel: https://github.com/osmlab/name-suggestion-index/commit/8c0fe618495408e65ab9af2141273cddead84e83
```python
{'atp/brand/SecurCare Self Storage': 252,
'atp/category/shop/storage_rental': 252,
'atp/field/brand_wikidata/missing': 252,
'atp/field/country/from_spider_name': 252,
'atp/field/email/missing': 252,
'atp/field/name/missing': 252,
'atp/field/operator/missing': 252,
'atp/field/operator_wikidata/missing': 252,
'downloader/request_bytes': 367092,
'downloader/request_count': 256,
'downloader/request_method_count/GET': 256,
'downloader/response_bytes': 7489679,
'downloader/response_count': 256,
'downloader/response_status_count/200': 255,
'elapsed_time_seconds': 3.27138, …
```
=> [SecurCare Self Storage US] Add spider

locations/spiders/aje.py
Existing wikidata code was for [Guess](https://www.wikidata.org/wiki/Q2470307)
=> Change to wikidata code and add category

locations/spiders/mercator_sl.py
Fixes https://github.com/alltheplaces/alltheplaces/issues/7856
=> Add Mercator (SL)

locations/spiders/mavis_us.py
Rel: https://github.com/alltheplaces/alltheplaces/pull/7828#discussion_r1523041337
```python
{'atp/brand/Mavis': 833,
'atp/brand_wikidata/Q65058420': 833,
'atp/category/shop/tyres': 833,
'atp/cdn/cloudflare/response_count': 835,
'atp/cdn/cloudflare/response_status_count/200': 835,
'atp/field/email/missing': 833,
'atp/field/image/missing': 833,
'atp/field/opening_hours/missing': 833,
'atp/field/operator/missing': 833,
'atp/field/operator_wikidata/missing': 833,
'atp/field/street_address/missing': 833,
'atp/field/twitter/missing': 833,
'atp/nsi/perfect_match': 833,
'downloader/request_bytes': 332520,
'downloader/request_count': 835,
'downloader/request_method_count/GET': 835,
'downloader/response_bytes': 16230934,
'downloader/response_count': 835, …
```
=> [Mavis US] Seperate "Mavis Tires & Brakes" and "Mavis Discount Tire"

locations/spiders/dm.py
prev:
`name=dm drogerie markt s.r.o. - prod.313`
now:
`name=dm`
=> fix dm name

locations/spiders/mcdonalds_cz.py
=> [McDonald's CZ] Restore branch

locations/spiders/burger_king_cz.py
`name`s
```
Burger King Karviná Korso
Burger King Ostrava Outlet
Burger King Ostrava Nová Karolina
Burger King Ostrava Poruba
BK Frydek Mistek OC Fryda
Burger King Olomouc Šantovka
Hradec Kralove Brnenska
Burger King Palác Pardubice
Burger King Liberec Forum
BK Liberec Nisa
```
`branch`es
```
Karviná Korso
Ostrava Outlet
Ostrava Nová Karolina
Ostrava Poruba
Frydek Mistek OC Fryda
Olomouc Šantovka
Hradec Kralove Brnenska
Palác Pardubice
Liberec Forum
Liberec Nisa
```
=> move burger_king_cz name to branch

locations/spiders/burger_king_fr.py
```python
{'atp/brand/Burger King': 539,
'atp/brand_wikidata/Q177054': 539,
'atp/category/amenity/fast_food': 539,
'atp/field/city/missing': 539,
'atp/field/country/from_spider_name': 539,
'atp/field/email/missing': 539,
'atp/field/operator/missing': 539,
'atp/field/operator_wikidata/missing': 539,
'atp/field/postcode/missing': 539,
'atp/field/state/missing': 539,
'atp/field/street_address/missing': 539,
'atp/field/twitter/missing': 539,
'atp/nsi/category_match': 539,
'downloader/request_bytes': 245134,
'downloader/request_count': 541,
'downloader/request_method_count/GET': 541,
'downloader/response_bytes': 2546371,
'downloader/response_count': 541, …
```
=> [BurgerKing FR] Fix spider

locations/spiders/jjill.py
Was yielding 0 POIs due to error in opening times.
=> [JJill] Fix opening hours

locations/spiders/kfc_amrest.py, locations/spiders/latagliatella_es.py, locations/spiders/pizza_hut_amrest.py, locations/storefinders/amrest_eu.py
previously:
`name` = `KFC Pardubice Palac`
now:
`name` = `KFC`
`branch` = `KFC Pardubice Palac`
=> [Pizza Hut Amrest][La Tagliatella ES][KFC Amrest] Collect branch

locations/spiders/studenac_hr.py
Was generating 0 POIs due to errors with opening times.
=> [StudenacHR] Fix to opening times

locations/spiders/tesco_eu.py
name:
```
Hypermarket Komárno
EXTRA Bratislava Zlaté piesky
Supermarket Poltár
Supermarket Sečovce
TESCO Szeged Szupermarket
TESCO expressz Sopron - Lackner K. utca
TESCO Expressz Bp. - Ady Endre utca
TESCO Gyöngyös Hipermarket
Hypermarket Uherské Hradiště
Expres Praha Mendelova
Supermarket Odolena Voda
Expres Nový Bor
```
name:
```
Tesco
Tesco Extra
Tesco
Tesco
Tesco
Tesco Express
Tesco Express
Tesco
Tesco
Tesco Express
Tesco
Tesco Express
```
branch:
```
Hypermarket Komárno
EXTRA Bratislava Zlaté piesky
Supermarket Poltár
Supermarket Sečovce
Szeged Szupermarket
expressz Sopron - Lackner K. utca
Expressz Bp. - Ady Endre utca
Gyöngyös Hipermarket
Hypermarket Uherské Hradiště
Expres Praha Mendelova
Supermarket Odolena Voda
Expres Nový Bor
```
=> move `name` into `branch` for `tesco_eu`

locations/spiders/joker_no.py
Part of https://github.com/alltheplaces/alltheplaces/issues/7862
{'atp/brand/Joker': 448,
'atp/brand_wikidata/Q716328': 448,
'atp/category/shop/supermarket': 448,
'atp/field/country/from_spider_name': 448,
'atp/field/image/missing': 448,
'atp/field/opening_hours/missing': 448,
'atp/field/operator/missing': 448,
'atp/field/operator_wikidata/missing': 448,
'atp/field/twitter/missing': 448,
'atp/nsi/perfect_match': 448,
'downloader/response_bytes': 358782,
'elapsed_time_seconds': 4.401031, …
=> Add Joker (NO)

locations/spiders/avia_pl.py, locations/spiders/grainger_us.py, locations/spiders/ntb_us.py, locations/spiders/pizza_hut_fr.py
Leftovers from https://github.com/alltheplaces/alltheplaces/pull/7568
=> Clean address lines  - extras

locations/spiders/deli_de_luca_no.py
Fix https://github.com/alltheplaces/alltheplaces/issues/7910
{'atp/brand/Deli de Luca': 23,
'atp/brand_wikidata/Q11965047': 23,
'atp/category/missing': 23,
'atp/field/country/from_website_url': 23,
'downloader/request_bytes': 658,
=> Add Deli de Luca (NO)

locations/spiders/crown_decorating_centres_gb.py
=> Add Crown Decorating Centres (GB) (156 locations)

locations/spiders/dulux_decorator_centre_gb.py
=> Add Dulux Decorator Centre (GB) (232 locations)

locations/spiders/kfc_at.py
=> Add KFC (AT) (13 locations)

locations/spiders/commerce_bank_us.py
Fix https://github.com/alltheplaces/alltheplaces/issues/966
{'atp/brand/Commerce Bank': 265,
'atp/brand_wikidata/Q5152411': 265,
'atp/category/amenity/atm': 116,
'atp/category/amenity/bank': 149,
'atp/field/country/from_spider_name': 265,
'atp/field/email/missing': 265,
'atp/field/image/missing': 265,
'atp/field/opening_hours/missing': 110,
'atp/field/operator/missing': 149,
'atp/field/operator_wikidata/missing': 149,
'atp/field/street_address/missing': 265,
'atp/field/twitter/missing': 265,
'atp/nsi/category_match': 265,
'atp/operator/Commerce Bank': 116,
'atp/operator_wikidata/Q5152411': 116,
'downloader/request_bytes': 708,
'downloader/response_bytes': 77925, …
=> Add Commerce Bank (US)

locations/spiders/united_bank_us.py
Fix https://github.com/alltheplaces/alltheplaces/issues/1047
{'atp/brand/United Bank': 261,
'atp/brand_wikidata/Q16920636': 261,
'atp/category/amenity/atm': 42,
'atp/category/amenity/bank': 219,
'atp/field/country/from_spider_name': 261,
'atp/field/email/missing': 261,
'atp/field/image/missing': 261,
'atp/field/opening_hours/missing': 42,
'atp/field/operator/missing': 219,
'atp/field/operator_wikidata/missing': 219,
'atp/field/phone/missing': 42,
'atp/field/street_address/missing': 261,
'atp/field/twitter/missing': 261,
'atp/nsi/category_match': 261,
'atp/operator/United Bank': 42,
'atp/operator_wikidata/Q16920636': 42,
'downloader/request_bytes': 745,
=> Add United Bank (US)

locations/hours.py, locations/spiders/norfa_lt.py
Fix #7891 
{'atp/brand/Norfa': 157,
'atp/brand_wikidata/Q1998983': 157,
'atp/category/shop/supermarket': 157,
'atp/field/city/missing': 157,
'atp/field/country/from_spider_name': 157,
'atp/field/email/missing': 157,
'atp/field/image/missing': 157,
'atp/field/operator/missing': 157,
'atp/field/operator_wikidata/missing': 157,
'atp/field/postcode/missing': 157,
'atp/field/state/missing': 157,
'atp/field/twitter/missing': 157,
'atp/field/website/missing': 157,
'atp/nsi/perfect_match': 157,osed (finished)
=> Add Norfa (LT)

locations/spiders/eko_gr.py, locations/storefinders/lighthouse.py
#7938 
https://github.com/alltheplaces/alltheplaces/issues/7902
{'atp/brand/EKO': 839,
'atp/brand_wikidata/Q31283948': 839,
'atp/category/amenity/fuel': 839,
'atp/field/city/missing': 839,
'atp/field/country/from_spider_name': 839,
'atp/field/email/missing': 839,
'atp/field/image/missing': 839,
'atp/field/opening_hours/missing': 839,
'atp/field/operator/missing': 839,
'atp/field/operator_wikidata/missing': 839,
'atp/field/postcode/missing': 839,
'atp/field/state/missing': 839,
'atp/field/twitter/missing': 839,
'atp/field/website/missing': 839,
'atp/nsi/category_match': 839,
'downloader/request_bytes': 613,
'downloader/response_bytes': 126773, …
=> Add Lighthouse Storefinder and Eko (GR)

locations/spiders/aswak_assalam_ma.py
Fix https://github.com/alltheplaces/alltheplaces/issues/7917
{'atp/brand/Aswak Assalam': 10,
'atp/brand_wikidata/Q2868678': 10,
'atp/category/shop/supermarket': 10,
'atp/field/lat/missing': 10,
'atp/field/lon/missing': 10, …
=> Add Aswak Assalam (MA)

locations/spiders/belle_tire_us.py
Fix https://github.com/alltheplaces/alltheplaces/issues/7679
Partial run:
2024-03-17 01:50:36 [scrapy.statscollectors] INFO: Dumping Scrapy stats:
{'atp/brand/Belle Tire': 71,
'atp/brand_wikidata/Q16984061': 71,
'atp/category/shop/tyres': 71,
'atp/field/email/missing': 71,
'atp/field/opening_hours/missing': 71,
'atp/field/operator/missing': 71,
'atp/field/operator_wikidata/missing': 71,
'atp/field/twitter/missing': 71,
'atp/nsi/perfect_match': 71,
'downloader/request_bytes': 32209,
'downloader/request_count': 84,
'downloader/request_method_count/GET': 84,
'downloader/response_bytes': 3015231,
'downloader/response_count': 84,
'downloader/response_status_count/200': 84,
'elapsed_time_seconds': 102.621017,
'finish_time': datetime.datetime(2024, 3, 17, 1, 50, 36, …
=> Add Belle Tire (US)

locations/spiders/gigis_cupcakes_us.py, locations/storefinders/easylocator.py
Fix https://github.com/alltheplaces/alltheplaces/issues/954
{"atp/brand/Gigi's Cupcakes": 37,
'atp/category/shop/bakery': 37,
'atp/field/brand_wikidata/missing': 37,
'atp/field/country/from_spider_name': 37,
'atp/field/image/missing': 37,
'atp/field/operator/missing': 37,
'atp/field/operator_wikidata/missing': 37,
'atp/field/twitter/missing': 37,
'downloader/request_bytes': 697,
'downloader/response_bytes': 10173,
'elapsed_time_seconds': 2.316272,
'finish_time': …
=> Add EasyLocator storefinder and Gigi's Cupcakes US

locations/spiders/pilot_flyingj.py
https://nsi.guide/index.html?t=brands&k=amenity&v=fuel&tt=flying%20j
=> [Pilot Flying J] Sync Flying J wikidata with NSI

locations/categories.py, locations/spiders/xy.py
Rel: https://github.com/osmlab/name-suggestion-index/commit/55dc34cdc1507309e0eb6e7196084ddfab23634e
=> [XY] Add spider

locations/spiders/godiva_chocolatier_jp.py
=> Add Godiva Chocolatier (JP) (357 stores)

locations/spiders/godiva_chocolatier_au.py
=> Add Godiva Chocolatier (AU) (7 stores)

locations/spiders/chicos.py
Was producing 0 POIs with 60 errors.
=> [Chicos] Change to sitemap and structured data spider

locations/spiders/99_ranch_market_us.py
=> Add 99 Ranch Market (US) (62 stores)

locations/spiders/jeff_de_bruges.py
=> Add Jeff de Bruges (worldwide) (524 stores)

locations/spiders/talbots.py
Was producing 0 POIs due to errors.
=> [Talbots] Fix name and address errors

locations/spiders/vinmonopolet_no.py
=> Add Vinmonopolet (NO) (350 stores)

locations/spiders/clothing_junction_za.py, locations/storefinders/storelocatorwidgets.py
=> Add Clothing Junction (ZA) (237 stores)

locations/spiders/rouses_us.py
=> Add Rouses (US) (59 stores)

locations/spiders/bi_mart_us.py, locations/storefinders/kibo.py
=> Add Bi-Mart (US) (79 stores)

locations/spiders/peavey_mart_ca.py
=> Add Peavey Mart (CA) (94 stores)

locations/spiders/mydentist_gb.py
Added emails to spider.
```python
{'atp/brand/My Dentist': 433,
'atp/brand_wikidata/Q65118035': 433,
'atp/category/amenity/dentist': 433,
'atp/category/missing': 101,
'atp/category/multiple': 433,
'atp/cdn/cloudflare/response_count': 916,
'atp/cdn/cloudflare/response_status_count/200': 916,
'atp/field/brand/missing': 101,
'atp/field/brand_wikidata/missing': 101,
'atp/field/city/missing': 68,
'atp/field/country/from_spider_name': 534,
'atp/field/email/invalid': 66,
'atp/field/email/missing': 468,
'atp/field/image/missing': 534,
'atp/field/lat/missing': 29,
'atp/field/lon/missing': 29,
'atp/field/name/missing': 68,
'atp/field/operator/missing': 534,
'atp/field/operator_wikidata/missing': 534,
'atp/field/state/missing': …
```
=> [mydentist_gb] Added email for mydentist_gb (534 items)

locations/spiders/bank_leumi_il.py
I would like someone local to look at it, but current output looks good enough for me.
=> [bank_leumi_il] add spider (200 locations)

locations/spiders/rema_1000_dk.py
=> Add REMA 1000 (DK) (403 stores)

locations/spiders/rema_1000_no.py
=> Add REMA 1000 (NO) (679 stores)

locations/spiders/poiesz_supermarkten_nl.py
Fix https://github.com/alltheplaces/alltheplaces/issues/7953
=> Add Poiesz Supermarkten (NL)

locations/spiders/plaza_vea_pe.py
=> Add Plaza Vea (PE)

locations/spiders/rabba_ca.py
=> Add Rabba (CA) (35 stores)

locations/spiders/redners_us.py
"atp/brand/Redner's": 44,
"atp/brand/Redner's Quick Shoppe": 42,
'atp/brand_wikidata/Q125102841': 42,
'atp/brand_wikidata/Q7306166': 44,
'atp/category/amenity/fuel': 21,
'atp/category/shop/convenience': 21,
'atp/category/shop/supermarket': 44,
Fixes #7977
=> Add Redner's (US) (86 locations)

locations/hours.py, locations/spiders/santa_isabel_cl.py
=> Add Santa Isabel (CL) (191 stores)

locations/spiders/mix_markt_gr.py
Fix https://github.com/alltheplaces/alltheplaces/issues/7497
=> Add Mix Markt (GR)

locations/spiders/cobasi_br.py
Fix https://github.com/alltheplaces/alltheplaces/issues/7680
=> Add Cobasi (BR)

locations/spiders/penzeys_us.py
Fix https://github.com/alltheplaces/alltheplaces/issues/7582
=> Penzeys (US)

locations/spiders/la_anonima_ar.py
Fix https://github.com/alltheplaces/alltheplaces/issues/7685
=> La Anonima (AR)

locations/spiders/mego_lv.py
=> Add Mego (LV)

locations/hours.py, locations/spiders/bauspezi_de.py, locations/spiders/grycan_pl.py, locations/spiders/rosauers_us.py, locations/spiders/rotten_robbie_us.py, locations/spiders/sonic_ca.py, locations/spiders/tacotote.py, locations/storefinders/wp_go_maps.py
Fix https://github.com/alltheplaces/alltheplaces/issues/7999 though I cant get it to run in codespaces (geoblocking?)
Fix https://github.com/alltheplaces/alltheplaces/issues/7591
=> Add Rosauers Supermarkets, Storefinder for WpGoMaps, and refactor existing spiders

locations/spiders/revolution_laundry.py
Fix https://github.com/alltheplaces/alltheplaces/issues/7586
=> Add Revolution Laundry

locations/spiders/mcdonalds_mt.py
https://mcdonalds.com.mt/locate/ has token embedded in it, but this page is blocked by Cloudflare.
=> [mcdonalds_mt] Fixed spider

locations/spiders/bangkok_bank_th.py
Stats:
```json
{
"atp/brand/Bangkok Bank": 13,
"atp/brand/\u0e18\u0e19\u0e32\u0e04\u0e32\u0e23\u0e01\u0e23\u0e38\u0e07\u0e40\u0e17\u0e1e": 6856,
"atp/brand/\u76e4\u8c37\u9280\u884c Bangkok Bank": 1,
"atp/brand_wikidata/Q806483": 6870,
"atp/category/amenity/atm": 6021,
"atp/category/amenity/bank": 849,
"atp/field/city/missing": 6870,
"atp/field/email/missing": 6870,
"atp/field/image/missing": 6870,
"atp/field/lat/missing": 2050,
"atp/field/lon/missing": 2050,
"atp/field/name/missing": 6021,
"atp/field/opening_hours/missing": 6870,
"atp/field/operator/missing": 849,
"atp/field/operator_wikidata/missing": 849,
"atp/field/phone/invalid": 6805,
"atp/field/postcode/missing": 7,
"atp/field/twitter/missing": 6870,
"atp/field/website/missing": 6870,
"atp/nsi/category_match": 6870, …
```
=> [bangkok_bank] add spider (6870 locations)

locations/spiders/bravoitalian_us.py, locations/spiders/mix_markt_gr.py
Fix https://github.com/alltheplaces/alltheplaces/issues/793
=> Add Bravo Italian (US)

locations/spiders/mcdonalds_mt.py
=> [McDonalds MT] Drop hardcoded token

ci/buildspec.yml, locations/spiders/rosselkhozbank_ru.py
Stats:
```json
{
"atp/brand/Россельхозбанк": 1395,
"atp/brand_wikidata/Q3920226": 1395,
"atp/category/amenity/bank": 1395,
"atp/field/city/missing": 1395,
"atp/field/country/from_spider_name": 1395,
"atp/field/email/missing": 1395,
"atp/field/image/missing": 1395,
"atp/field/lat/missing": 2,
"atp/field/lon/missing": 2,
"atp/field/opening_hours/missing": 216,
"atp/field/operator/missing": 1395,
"atp/field/operator_wikidata/missing": 1395,
"atp/field/phone/invalid": 154,
"atp/field/phone/missing": 6,
"atp/field/postcode/missing": 1395,
"atp/field/state/missing": 1395,
"atp/field/street_address/missing": 1395,
"atp/field/twitter/missing": 1395,
"atp/field/website/missing": 1395,
"atp/geometry/null_island": 1,
"atp/hours/failed": 72,
"atp/nsi/category_match": 1395,
"downloader/request_bytes": …
```
=> [rosselkhozbank_ru] add spider (1395 locations)

locations/spiders/bluerhino.py
Some of these are remarkably old, the oldest being 2009-03-21.
```python
{'atp/brand/Blue Rhino': 64769,
'atp/brand_wikidata/Q65681213': 64769,
'atp/category/amenity/vending_machine': 64769,
'atp/field/email/missing': 64769,
'atp/field/image/missing': 64769,
'atp/field/lat/missing': 104,
'atp/field/lon/missing': 104,
'atp/field/opening_hours/missing': 64769,
'atp/field/operator/missing': 64769,
'atp/field/operator_wikidata/missing': 64769,
'atp/field/phone/invalid': 73,
'atp/field/phone/missing': 198,
'atp/field/twitter/missing': 64769,
'atp/field/website/missing': 64769,
'atp/geometry/null_island': 104,
'atp/nsi/perfect_match': 64769,
'downloader/request_bytes': 566, …
```
=> [BlueRhino] Collect last delivery date

locations/spiders/kiwoko.py
Was creating 0 POIs due to error.
=> [Kiwoko] Fix to address

locations/spiders/creams_gb.py
Rel: https://github.com/osmlab/name-suggestion-index/pull/9319
```python
{'atp/brand/Creams': 99,
'atp/brand_wikidata/Q111811895': 99,
'atp/category/amenity/ice_cream': 99,
'atp/field/city/missing': 99,
'atp/field/country/from_spider_name': 99,
'atp/field/image/missing': 99,
'atp/field/opening_hours/missing': 99,
'atp/field/operator/missing': 99,
'atp/field/operator_wikidata/missing': 99,
'atp/field/state/missing': 99,
'atp/field/street_address/missing': 99,
'atp/field/twitter/missing': 99,
'atp/nsi/perfect_match': 99,
'downloader/request_bytes': 46017,
'downloader/request_count': 103,
'downloader/request_method_count/GET': 103, …
```
=> [Creams GB] Add spider

locations/spiders/tamburi_at.py
Rel: https://github.com/osmlab/name-suggestion-index/pull/9336
=> [Tamburi AT] Add spider

locations/spiders/mix_markt_gr.py
German supermarket chain operating throughout Europe.
=> [MixMarktGR] Add brand wikidata and category

locations/spiders/spar_no.py
@iandees Sorry! I pushed a new commit just as you merged the previous PR. Hope this is ok. Let me know if I should delete this and create a new branch. Thank you!
=> Spar no category

locations/spiders/myflexbox.py
Rel: https://github.com/osmlab/name-suggestion-index/pull/9337
=> [Myflexbox] Add spider

locations/spiders/shopwise_ph.py
=> Add Shopwise (PH) (16 stores)

locations/spiders/prix_quality_it.py
Fix https://github.com/alltheplaces/alltheplaces/issues/7959
=> Add Prix Quality (IT)

locations/spiders/strack_and_van_til_us.py, locations/storefinders/store_locator_plus_self.py
Fix https://github.com/alltheplaces/alltheplaces/issues/8099
=> Strack & Van Til (US)

locations/spiders/pedros.py
Rel: https://github.com/osmlab/name-suggestion-index/pull/9210
=> [Pedros] Add spider

locations/spiders/tesco_gb.py
Rel: https://github.com/osmlab/name-suggestion-index/commit/ab213c5d4acc2626a06379531e7f760488ee9455
=> [Tesco GB] Clean up names

locations/spiders/new_hampshire_liquour_and_wine_us.py, locations/spiders/new_hampshire_wine_and_liquor_us.py
Fix https://github.com/alltheplaces/alltheplaces/issues/7021
=> New Hampshire Liquor & Wine (US)

locations/spiders/nslc_ca.py
Fix https://github.com/alltheplaces/alltheplaces/issues/7023
Far from perfect.
=> Add NSLC (CA)

locations/hours.py, locations/linked_data_parser.py, locations/spiders/new_seasons_market_us.py, tests/test_ld_parser.py
Fix https://github.com/alltheplaces/alltheplaces/issues/7890
=> Add New Seasons Market (US) and fix LinkedData parsing of OpeningHoursSpecification when only dealing with a dict

locations/items.py, locations/spiders/samsonite_eu.py, tests/test_social_media.py
As @davidhicks said in https://github.com/alltheplaces/alltheplaces/pull/7570#discussion_r1501833283, this should be an enum.
=> Add SocialMedia enum

locations/spiders/hsbc.py
Stats:
```json
{
"atp/brand/HSBC": 454,
"atp/brand_wikidata/Q190464": 454,
"atp/category/amenity/bank": 454,
"atp/closed_check": 1,
"atp/field/email/invalid": 6,
"atp/field/email/missing": 448,
"atp/field/image/dropped": 454,
"atp/field/image/missing": 454,
"atp/field/opening_hours/missing": 29,
"atp/field/operator/missing": 454,
"atp/field/operator_wikidata/missing": 454,
"atp/field/phone/missing": 454,
"atp/field/postcode/missing": 170,
"atp/field/state/missing": 454,
"atp/field/twitter/missing": 287,
"atp/field/website/invalid": 86,
"atp/nsi/category_match": 454,
"downloader/request_bytes": 365524,
"downloader/request_count": 963,
"downloader/request_method_count/GET": 963,
"downloader/response_bytes": 11423484,
"downloader/response_count": 963,
"downloader/response_status_count/200": …
```
=> [hsbc] fix spider

locations/spiders/poundstretcher_gb.py
=> [Poundstretcher GB] Add spider

locations/spiders/aeon_big_my.py
=> Add AEON BiG (MY) (21 stores)

locations/spiders/rodda_paint_us.py
=> Add Rodda Paint (US) (61 stores)

locations/spiders/societe_generale.py
```python
{'atp/brand/Société Générale': 2165,
'atp/brand_wikidata/Q270363': 2165,
'atp/category/amenity/bank': 2165,
'atp/field/email/missing': 2165,
'atp/field/opening_hours/missing': 27,
'atp/field/operator/missing': 2165,
'atp/field/operator_wikidata/missing': 2165,
'atp/field/state/missing': 2165,
'atp/nsi/category_match': 2165,
```
=> [SocieteGenerale] Fix category

locations/spiders/five_guys_ae.py, locations/spiders/five_guys_at.py, locations/spiders/five_guys_au.py, locations/spiders/five_guys_be.py, locations/spiders/five_guys_bh.py, locations/spiders/five_guys_ca.py, locations/spiders/five_guys_ch.py, locations/spiders/five_guys_cn.py, locations/spiders/five_guys_hk.py, locations/spiders/five_guys_ie.py, locations/spiders/five_guys_it.py, locations/spiders/five_guys_kr.py, locations/spiders/five_guys_kw.py, locations/spiders/five_guys_lu.py, locations/spiders/five_guys_my.py, locations/spiders/five_guys_nl.py, locations/spiders/five_guys_qa.py, locations/spiders/five_guys_sa.py, locations/spiders/five_guys_sg.py, locations/spiders/five_guys_us.py
All these have the same backend that has recently got slightly broken json linked data. Most the other Five Guys sites have microdata, I can't remember, and haven't checked, what they all used to be, but presumably they are migrating in one direction.
=> [FiveGuys AE AT AU BE BH CH KW NL] Fix coords and urls

locations/spiders/howdens_gb.py
```python
{'atp/brand/Howdens Joinery': 831,
'atp/brand_wikidata/Q5921438': 831,
'atp/category/shop/kitchen': 831,
'atp/field/country/from_spider_name': 831,
'atp/field/email/missing': 831,
'atp/field/image/dropped': 831,
'atp/field/image/missing': 831,
'atp/field/operator/missing': 831,
'atp/field/operator_wikidata/missing': 831,
'atp/field/phone/missing': 824,
'atp/field/state/missing': 831,
'atp/field/twitter/missing': 831,
'atp/nsi/perfect_match': 831,
'downloader/request_bytes': 682882,
'downloader/request_count': 842,
'downloader/request_method_count/GET': 842,
'downloader/response_bytes': 24457010,
'downloader/response_count': 842,
'downloader/response_status_count/200': 842,
'elapsed_time_seconds': 6.162554,
'finish_time': datetime.datetime(2024, 4, …
```
=> [Howdens GB] Add spider

locations/spiders/dinosol_es.py
'atp/brand/HiperDino': 57,
'atp/brand/HiperDino Express': 83,
'atp/brand/SuperDino': 96,
'atp/brand_wikidata/Q105955292': 57,
'atp/brand_wikidata/Q105955304': 96,
'atp/brand_wikidata/Q105955317': 83,
'atp/category/shop/convenience': 83,
'atp/category/shop/supermarket': 153,
Fixes #8117
=> Add DinoSol (ES) brands (236 stores)

locations/dict_parser.py, locations/spiders/supercor_es.py
=> Add Supercor (ES) (162 stores)

locations/spiders/super_del_norte_mx.py
=> Add Super del Norte (MX) (38 stores)

locations/spiders/kfc_gb.py
```python
{'atp/brand/KFC': 1036,
'atp/brand_wikidata/Q524757': 1036,
'atp/category/amenity/fast_food': 1036,
'atp/field/email/missing': 1036,
'atp/field/image/missing': 1036,
'atp/field/operator/missing': 1036,
'atp/field/operator_wikidata/missing': 1036,
'atp/field/phone/missing': 1036,
'atp/field/twitter/missing': 1036,
'atp/nsi/cc_match': 1036,
'downloader/request_bytes': 293,
'downloader/response_bytes': 393905,
'elapsed_time_seconds': 1.053,
'finish_time': datetime.datetime(2024, 4, 10, 13, 27, …
```
=> [KFC GB] Fix spider

locations/dict_parser.py, locations/spiders/todis_it.py
=> Add Todis (IT) (315 stores)

locations/spiders/topaz_pl.py
=> Add Topaz (PL) (115 stores)

locations/spiders/super_c_ca.py
=> Add Super C (CA) (107 stores)

locations/spiders/teboil_ru.py
I completely missed to wire fuels in #7306.
=> [teboil_ru] wire fuels, add brand

locations/spiders/pacific_my.py, locations/spiders/the_store_my.py
=> Add Pacific (MY) (10 stores)

locations/spiders/super_jimat_my.py
=> Add Super Jimat (MY) (6 stores)

locations/spiders/milimewa_my.py
=> Add Milimewa (MY) (11 stores)

locations/spiders/milimewa_my.py, locations/spiders/pacific_my.py, locations/spiders/super_jimat_my.py, locations/spiders/the_store_my.py
=> Add The Store (MY) (28 stores)

locations/spiders/metro_pe.py
=> Add Metro (PE) (73 stores)

docs/PIPELINES.md, locations/pipelines/drop_attributes.py, locations/settings.py, locations/spiders/aldi_sud_us.py, locations/spiders/banfield_pet_hospital.py, locations/spiders/champs_sports_us.py, locations/spiders/safeway.py, locations/spiders/tcc_us.py, tests/test_pipeline_drop_attributes.py
Rel: https://github.com/alltheplaces/alltheplaces/pull/8175#issuecomment-2051921316
I don't know how useful this will be, but it feels like we are writing the same code again and again.
If we want to go this way, I'll add some tests. If not, no hard feelings we can continue overriding functions.
=> [Core] Drop attributes pipeline

locations/spiders/groen_rijk_nl.py
Rel: https://github.com/osmlab/name-suggestion-index/pull/9365
=> [GroenRijk NL] Add spider

locations/spiders/break_and_wash_pl.py
I think this is ready to go, but I'm gonna wait for some opinions on categories: https://github.com/osmlab/name-suggestion-index/issues/9366
=> [BreakAndWash PL] Add spider

locations/spiders/otpbank_hu.py
This should match against NSI after the next release.
=> [OTP Bank HU] Add spider

locations/spiders/alamo.py
=> [Alamo] Sync brand with NSI

locations/spiders/our_airports.py
Explicitly Public Domain https://ourairports.com/data/
=> Add OurAirports spider

locations/spiders/credit_agricole.py, locations/spiders/credit_agricole_pl.py
Seem to have forgotten to `git add` these ones. My bad. Rel: #8228
=> [CreditAgricole] Sync brand string with NSI

ci/buildspec.yml, locations/spiders/choice_hotels.py
Rel: https://github.com/alltheplaces/alltheplaces/pull/8203
The spider doesn't really work on weekly without proxy.
=> [choice_hotels] enable proxy

locations/spiders/baylorscottwhitehealth.py, locations/spiders/bc_pizza.py, locations/spiders/cumberland_farms.py, locations/spiders/decathlon_sk.py, locations/spiders/foodlion_us.py, locations/spiders/goldsmiths_gb.py, locations/spiders/pawinespirits.py, locations/storefinders/momentfeed.py, locations/storefinders/woosmap.py
pre-commit started flagging these as errors some time in the last 24 hours.
=> Fix issues that showed up from pre-commit

locations/spiders/gbfs.py
Some [502's popped up in weeklys](https://alltheplaces-data.openaddresses.io/runs/2024-04-20-13-31-46/logs/gbfs.txt).
=> [gbfs] increase delay, map physical presence

locations/spiders/kfc_gr.py
```python
{'atp/brand/KFC': 18,
'atp/brand_wikidata/Q524757': 18,
'atp/category/amenity/fast_food': 18,
'atp/field/city/missing': 18,
'atp/field/country/from_spider_name': 18,
'atp/field/opening_hours/missing': 18,
'atp/field/postcode/missing': 18,
'atp/nsi/cc_match': 18,
'downloader/response_bytes': 43639, …
```
=> [kfc_gr] Added KFC_GR spider (18 items_

locations/spiders/nissan_cz.py
```python
{'atp/brand/Nissan': 23,
'atp/brand_wikidata/Q20165': 23,
'atp/category/shop/car': 23,
'atp/field/country/from_spider_name': 23,
'atp/nsi/cc_match': 23,
'downloader/request_bytes': 630,
'downloader/response_bytes': 16709,
'elapsed_time_seconds': 2.716099,
'finish_time': …
```
=> [nissan_cz] Added Nissan CZ Spider (23 items)

locations/spiders/caprinos_gb.py
Rel: https://github.com/osmlab/name-suggestion-index/commit/981e22175e92dd725d85c7084c8cd97d002f03ab
=> [Caprinos GB] Add spider

locations/spiders/cbrfree_au.py
Reference/source data: https://www.cmtedd.act.gov.au/digital/cbrfree-public-wifi
=> Add CBRfree (AU) (467 hotspots)

locations/categories.py, locations/spiders/citywatch_au.py
Reference/source data: https://perth.wa.gov.au/community/community-services-and-facilities/security-and-surveillance
=> Add CityWatch (AU) (657 surveillance cameras)

locations/categories.py, locations/spiders/city_of_sydney_street_safety_cameras_au.py, locations/spiders/citywatch_au.py
Reference/source data: https://www.cityofsydney.nsw.gov.au/public-health-safety-programs/street-safety-cameras
=> Add City of Sydney street safety cameras (AU) (106 surveillance cameras)

locations/categories.py, locations/spiders/cbrfree_au.py, locations/spiders/perth_wifi_au.py, locations/spiders/tasmanian_government_free_wifi_au.py, locations/spiders/vicfreewifi_au.py
Reference/source data: https://www.vic.gov.au/victorias-free-public-wifi
=> Add VicFreeWiFi (AU) (516 hotspots)

locations/spiders/chick_fil_a.py, locations/storefinders/yext_search.py
```python
{'atp/brand/Chick-fil-A': 3040,
'atp/brand_wikidata/Q491516': 3040,
'atp/category/amenity/fast_food': 3040,
'atp/cdn/cloudflare/response_count': 62,
'atp/cdn/cloudflare/response_status_count/200': 62,
'atp/closed_poi': 2,
'atp/field/email/missing': 3040,
'atp/field/image/missing': 3040,
'atp/field/opening_hours/invalid': 72,
'atp/field/opening_hours/missing': 2968,
'atp/field/operator/missing': 3040,
'atp/field/operator_wikidata/missing': 3040,
'atp/field/phone/missing': 3040,
'atp/field/twitter/missing': 3040,
'atp/nsi/perfect_match': 3040,
'downloader/request_bytes': 38323,
'downloader/request_count': 62,
'downloader/request_method_count/GET': 62,
'downloader/response_bytes': 5837645,
'downloader/response_count': 62, …
```
=> [Chick-fil-A] Fix spider (Fixes #7852)

locations/spiders/pga_tour_superstore_us.py
Rel: https://github.com/osmlab/name-suggestion-index/commit/1e4cbac83f124f1a9c52fc8d0eafa13b7cc4fd37
```python
{'atp/brand_wikidata/Q125705404': 68,
'atp/category/missing': 68,
'atp/cdn/cloudflare/response_count': 84,
'atp/cdn/cloudflare/response_status_count/200': 84,
'atp/field/brand/missing': 68,
'atp/field/name/missing': 68,
'atp/field/opening_hours/missing': 68,
'atp/nsi/brand_missing': 68,
'downloader/request_bytes': 93288,
'downloader/request_count': 84,
'downloader/request_method_count/GET': 84,
'downloader/response_bytes': 2340581,
'downloader/response_count': 84,
'downloader/response_status_count/200': 84,
'elapsed_time_seconds': 1.659632, …
```
=> [PGA Tour Superstore US] Add spider

locations/spiders/kid_strong.py
Rel: https://github.com/osmlab/name-suggestion-index/commit/f7e4b3fd34c72664140168db7db620a535a84501
=> [KidStrong] Add spider

locations/spiders/calliope.py
Rel: https://github.com/osmlab/name-suggestion-index/pull/9420
=> [Calliope] Add spider

locations/spiders/nravizza_by.py
Rel: https://github.com/osmlab/name-suggestion-index/commit/c1b0fa3741035c674a5d62b16e2ef5ea72281e22
=> [Nravizza BY] Add spider

locations/spiders/krung_thai_th.py
```python
{'atp/brand/ธนาคารกรุงไทย': 924,
'atp/brand_wikidata/Q962865': 924,
'atp/category/amenity/bank': 924,
'atp/field/city/missing': 924,
'atp/field/country/from_spider_name': 924,
'atp/field/email/missing': 924,
'atp/field/image/missing': 924,
'atp/field/opening_hours/missing': 924,
'atp/field/operator/missing': 924,
'atp/field/operator_wikidata/missing': 924,
'atp/field/phone/missing': 924,
'atp/field/postcode/missing': 924,
'atp/field/state/missing': 924,
'atp/field/street_address/missing': 924,
'atp/field/twitter/missing': 924,
'atp/field/website/missing': 924,
'atp/nsi/cc_match': 924,
'downloader/exception_count': 2,
'downloader/exception_type_count/twisted.internet.error.TimeoutError': 2,
'downloader/request_bytes': 2817, …
```
=> [Krungthai TH] Add spider

locations/spiders/comet_it.py
Rel: https://github.com/osmlab/name-suggestion-index/pull/9434
=> [Comet IT] Add spider

locations/spiders/providence_us.py
Was yielding only 80 POIs due to name error (no name). Now 1923 POIs.
=> [ProvidenceUS] Fix name error

locations/spiders/capital_one_us.py, locations/spiders/carpet_one_floor_and_home_us.py, locations/spiders/cellarbrations_au.py, locations/spiders/cex.py, locations/spiders/city_beach_au.py, locations/spiders/coffee_1_gb.py, locations/spiders/corepower_yoga_us.py, locations/spiders/costa_coffee_gg_gb_im_je.py, locations/spiders/costplus_worldmarket.py, locations/spiders/crust_au.py
=> Use clean_address to join and clean addresses (4)

locations/spiders/guzmany_gomez.py, locations/spiders/hairhouse_au.py, locations/spiders/harvey_norman.py, locations/spiders/hm.py, locations/spiders/home_bargains_gb.py, locations/spiders/house_au.py, locations/spiders/ifly_ca_us.py, locations/spiders/jamaica_blue_au.py, locations/spiders/jardiland_fr.py, locations/spiders/jbhifi.py
=> Use clean_address to join and clean addresses (8)

locations/spiders/marathon_petroleum_us.py, locations/spiders/marinemax_us.py, locations/spiders/mcdonalds.py, locations/spiders/micromania_fr.py, locations/spiders/midcounties_cooperative_gb.py, locations/spiders/modern_market_us.py, locations/spiders/morrisons_gb.py, locations/spiders/mosaic_brands.py, locations/spiders/mr_bricolage_be.py, locations/spiders/munchs_supply_us.py
=> Use clean_address to join and clean addresses (10)

locations/spiders/domayne_au.py, locations/spiders/east_of_england_coop.py, locations/spiders/ekoplaza_nl.py, locations/spiders/enterprise.py, locations/spiders/esprit.py, locations/spiders/exxonmobil.py, locations/spiders/family_dollar_us.py, locations/spiders/fantastic_furniture_au.py, locations/spiders/flight_centre_au.py, locations/spiders/follett.py
=> Use clean_address to join and clean addresses (6)

locations/spiders/freshthyme.py, locations/spiders/gamestop_us.py, locations/spiders/gamma.py, locations/spiders/gant.py, locations/spiders/geico.py, locations/spiders/godiva_chocolatier_jp.py, locations/spiders/goldsmiths_gb.py, locations/spiders/greencross_au.py, locations/spiders/greggs_gb.py, locations/spiders/gull_nz.py
=> Use clean_address to join and clean addresses (7)

locations/spiders/johnstones_decorating_centre.py, locations/spiders/key_food_us.py, locations/spiders/kfc_au.py, locations/spiders/kipling_us.py, locations/spiders/kpn_nl.py, locations/spiders/life_time.py, locations/spiders/lj_hooker_au_nz.py, locations/spiders/loblaws.py, locations/spiders/lovisa.py, locations/spiders/m_j_bale_au.py
=> Use clean_address to join and clean addresses (9)

locations/spiders/total_wine_and_more_us.py, locations/spiders/truworths.py, locations/spiders/tyrepower_au.py, locations/spiders/urbn.py, locations/spiders/versace.py, locations/spiders/visa.py, locations/spiders/waffle_house_us.py, locations/spiders/walmart_us.py, locations/spiders/whsmith.py, locations/spiders/wolseley_gb.py
=> Use clean_address to join and clean addresses (15)

locations/spiders/woolworths_au.py, locations/spiders/zambrero_au.py, locations/spiders/zizzi_gb.py
=> Use clean_address to join and clean addresses (16)

locations/spiders/bathandbodyworks_us.py, locations/spiders/battery_world_au.py, locations/spiders/baylorscottwhitehealth.py, locations/spiders/bed_bath_n_table.py, locations/spiders/best_and_less_au.py, locations/spiders/biggby_coffee_us.py, locations/spiders/bjswholesale.py, locations/spiders/blue_rhino_pr_us.py, locations/spiders/bmo.py, locations/spiders/bolo_da_madre_br.py
=> Use clean_address to join and clean addresses (2)

locations/pipelines/address_clean_up.py, locations/spiders/alamo.py, locations/spiders/alicedelice.py, locations/spiders/amart_furniture_au.py, locations/spiders/anthropologie.py, locations/spiders/anytime_fitness.py, locations/spiders/ardene.py, locations/spiders/aristocrazy_es.py, locations/spiders/att_us.py, locations/spiders/avera_us.py, locations/spiders/bash_za.py
=> Use clean_address to join and clean addresses (1)

locations/categories.py, locations/spiders/bashneft_ru.py
```json
{
"atp/bashneft_ru/card/failed/Топливная карта": 537,
"atp/bashneft_ru/card/failed/Яндекс.Заправки": 499,
"atp/bashneft_ru/fuel/failed/M": 3,
"atp/bashneft_ru/service/failed/Магазин": 377,
"atp/bashneft_ru/service/failed/Программа лояльности": 532,
"atp/bashneft_ru/service/failed/Терминал оплаты услуг": 3,
"atp/brand/Башнефть": 540,
"atp/brand_wikidata/Q809985": 540,
"atp/category/amenity/fuel": 540,
"atp/field/city/missing": 540,
"atp/field/country/from_spider_name": 540,
"atp/field/email/missing": 540,
"atp/field/image/missing": 540,
"atp/field/opening_hours/missing": 540,
"atp/field/operator/missing": 540,
"atp/field/operator_wikidata/missing": 540,
"atp/field/phone/missing": 540,
"atp/field/postcode/missing": 540,
"atp/field/state/missing": 540, …
```
=> [bashneft_ru] add spider (540 fuel stations)

locations/spiders/smeshnie_ceny_ru.py
```json
{
"atp/brand/Смешные цены": 79,
"atp/category/shop/clothes": 79,
"atp/field/brand_wikidata/missing": 79,
"atp/field/city/missing": 79,
"atp/field/country/from_spider_name": 79,
"atp/field/email/missing": 79,
"atp/field/image/missing": 79,
"atp/field/name/missing": 79,
"atp/field/operator/missing": 79,
"atp/field/operator_wikidata/missing": 79,
"atp/field/phone/missing": 79,
"atp/field/postcode/missing": 79,
"atp/field/state/missing": 79,
"atp/field/street_address/missing": 79,
"atp/field/twitter/missing": 79,
"atp/field/website/missing": 79,
"downloader/request_bytes": 30314,
"downloader/request_count": 81,
"downloader/request_method_count/GET": 81,
"downloader/response_bytes": 977175,
"downloader/response_count": 81,
"downloader/response_status_count/200": 81, …
```
=> [smeshnie_ceny_ru] add spider

locations/spiders/dan_murphys_au.py
[This](https://api.danmurphys.com.au/apis/ui/StoreLocator/Stores/bws) sometimes works for me, sometimes doesn't. I want to see if the Zyte proxy helps.
=> [DanMurphys AU] Fix spider

locations/spiders/carlsjr_tr.py
```python
{"atp/brand/Carl's Jr.": 22,
'atp/brand_wikidata/Q1043486': 22,
'atp/category/amenity/fast_food': 22,
'atp/field/city/missing': 22,
'atp/field/country/from_spider_name': 22,
'atp/field/opening_hours/missing': 22,
'atp/field/postcode/missing': 22,
'atp/field/state/missing': 22,
'atp/field/street_address/missing': 22,
'atp/nsi/perfect_match': 22,
'downloader/request_bytes': 630,
'downloader/response_bytes': 44269, …
```
=> [carlsjr_tr] Create Carls JR in Turkey (22 items)

locations/spiders/fazolis_us.py
=> fazolis_us: fix spider

locations/spiders/five_guys_de.py, locations/spiders/five_guys_de_es_fr_gb.py, locations/spiders/five_guys_es.py, locations/spiders/five_guys_fr.py, locations/spiders/five_guys_gb.py
=> five_guys_de_es_fr_gb: fix and split spider

locations/spiders/scotmid.py
https://www.wikidata.org/wiki/Q125940846
=> Add more specific brand tags for Scotmid Funerals

locations/spiders/latvijas_pasts_lv.py
Rel: https://github.com/osmlab/name-suggestion-index/pull/9500
=> [LatvijasPasts LV] Add spider

locations/spiders/byd_auto_au.py
'atp/category/shop/car': 24,
'atp/category/shop/car_repair': 16,
=> Add BYD Auto (AU) (40 locations)

locations/spiders/toyota_au.py
'atp/category/shop/car': 314,
'atp/category/shop/car_parts': 314,
'atp/category/shop/car_repair': 314,
=> Add Toyota (AU) (942 locations)

locations/spiders/mazda_au.py
'atp/category/shop/car': 147,
'atp/category/shop/car_parts': 143,
'atp/category/shop/car_repair': 147,
=> Add Mazda (AU) (437 locations)

locations/spiders/kia_sg.py
'atp/category/shop/car': 2,
'atp/category/shop/car_repair': 4,
=> Add Kia (SG) (6 dealers)

locations/spiders/hopdoddy_us.py
Rel: https://github.com/osmlab/name-suggestion-index/issues/6967
=> [Hopdoddy US] Add spider

locations/spiders/x2o_be.py
Rel: https://github.com/osmlab/name-suggestion-index/commit/58b31cc2f5837dbea9f57e72930a99b5c43b812a
=> [X2O BE] Add spider

locations/spiders/vuori.py
Rel: https://github.com/osmlab/name-suggestion-index/issues/7354
=> [Vuori] Add spider

locations/categories.py, locations/spiders/oxford_learning.py
Rel: https://github.com/osmlab/name-suggestion-index/pull/9078
=> [OxfordLearning] Add spider

locations/spiders/tower_loan_us.py
Rel: https://github.com/osmlab/name-suggestion-index/commit/9bdebbae6d5d761e913886cb3cfa604d494242b9
=> [TowerLoan US] Add spider

locations/spiders/el_jannah_au.py
=> Add El Jannah (AU) (31 locations)

locations/spiders/bedsrus_nz.py
=> Add BedsRus (NZ) (51 locations)

locations/dict_parser.py, locations/spiders/beds_r_us_au.py
=> Add Beds R Us (AU) (73 locations)

locations/spiders/house_au.py
=> house_au: differentiate House Bed & Bath brand

locations/spiders/kwik_kopy_au.py
=> Add Kwik Kopy (AU) (92 locations)

locations/spiders/liquor_legends_au.py
=> Add Liquor Legends (AU) (243 locations)

locations/spiders/robins_kitchen_au.py
=> Add Robins Kitchen (AU) (62 locations)

locations/spiders/jersey_mikes_ca.py, locations/spiders/jersey_mikes_us.py
Unfortunately the US ones have no coords, but the address looks good enough to be geocoded at some point.
=> [JerseyMikes] Restore US POIs

locations/spiders/go_vita_au.py
=> Add Go Vita (AU) (114 locations)

locations/spiders/ollies_place_au.py
=> Add Ollies Place (AU) (45 locations)

locations/spiders/arb_4x4_accessories.py
=> Add ARB 4×4 Accessories (worldwide) (79 locations)

locations/spiders/move_yourself_au.py
=> Add Move Yourself (AU) (934 locations)

locations/spiders/sushi_sushi_au.py
=> Add Sushi Sushi (AU) (150 locations)

locations/spiders/dorevitch_pathology_au.py
=> Add Dorevitch Pathology (AU) (467 locations)

locations/spiders/dorevitch_pathology_au.py, locations/spiders/western_diagnostic_pathology_au.py
=> Add Western Diagnostic Pathology (AU) (205 locations)

locations/spiders/dorevitch_pathology_au.py, locations/spiders/qml_pathology_au.py
=> Add QML Pathology (AU) (493 locations)

locations/spiders/mister_minit_asia_pacific.py
=> Add Mister Minit (AU/NZ/SG/MY) (395 locations)

locations/spiders/dorevitch_pathology_au.py, locations/spiders/laverty_pathology_au.py
=> Add Laverty Pathology (AU) (571 locations)

locations/spiders/move_yourself_au.py
Reference: a0a017399d743094b6a58125f5077ebe29e9c0c8
=> move_yourself_au: fix included_in for BP

locations/spiders/dorevitch_pathology_au.py, locations/spiders/tml_pathology_au.py
=> Add TML Pathology (AU) (19 locations)

locations/spiders/tab_au.py, locations/user_agents.py
=> Add TAB (AU) (1996 locations)

locations/spiders/berlin_doner_kebap_pl.py
Rel: https://github.com/osmlab/name-suggestion-index/pull/9580
=> [BerlinDonerKebap PL] Add spider

locations/spiders/press_shop_be.py
Rel: https://github.com/osmlab/name-suggestion-index/pull/9594
=> [PressShop BE] Add spider

locations/spiders/obi_eu.py
https://github.com/alltheplaces/alltheplaces/pull/8586#issuecomment-2154916386
```json
{
"atp/brand/OBI": 518,
"atp/brand_wikidata/Q300518": 518,
"atp/category/shop/doityourself": 518,
"atp/field/city/missing": 518,
"atp/field/country/from_website_url": 518,
"atp/field/email/missing": 53,
"atp/field/image/missing": 518,
"atp/field/lat/missing": 6,
"atp/field/lon/missing": 6,
"atp/field/operator/missing": 518,
"atp/field/operator_wikidata/missing": 518,
"atp/field/postcode/missing": 518,
"atp/field/state/missing": 518,
"atp/field/street_address/missing": 518,
"atp/field/twitter/missing": 518,
"atp/nsi/perfect_match": 518,
"downloader/request_bytes": 301100,
"downloader/request_count": 616,
"downloader/request_method_count/GET": 616, …
```
=> [obi_eu] fix spider

locations/spiders/lowes_us.py
```python
{"atp/brand/Lowe's": 1746,
'atp/brand_wikidata/Q1373493': 1746,
'atp/category/shop/doityourself': 1746,
'atp/field/country/from_spider_name': 1746,
'atp/field/email/missing': 1746,
'atp/field/image/missing': 1746,
'atp/field/operator/missing': 1746,
'atp/field/operator_wikidata/missing': 1746,
'atp/field/twitter/missing': 1746,
'atp/nsi/perfect_match': 1746,
'downloader/request_bytes': 5354724,
'downloader/request_count': 1748,
'downloader/request_method_count/GET': 1748,
'downloader/response_bytes': 95314094,
'downloader/response_count': 1748,
'downloader/response_status_count/200': 1748,
'elapsed_time_seconds': 2136.614517,
'finish_time': datetime.datetime(2024, 6, 7, 14, 8, 5, 655223, …
```
=> [lowes_us] Added a user_agent to Lowes_us(1746 items)

locations/spiders/ptt_th.py
```python
{'atp/brand/Jiffy': 158,
'atp/brand/Texas Chicken': 37,
'atp/brand/ป.ต.ท.': 2194,
'atp/brand_wikidata/Q1089932': 37,
'atp/brand_wikidata/Q16770436': 158,
'atp/brand_wikidata/Q1810389': 2194,
'atp/category/amenity/fast_food': 37,
'atp/category/amenity/fuel': 2194,
'atp/category/shop/convenience': 158,
'atp/field/country/from_spider_name': 2389,
'atp/field/email/missing': 2389,
'atp/field/image/missing': 2389,
'atp/field/name/missing': 37,
'atp/field/opening_hours/missing': 2389,
'atp/field/operator/missing': 2389,
'atp/field/operator_wikidata/missing': 2389,
'atp/field/phone/missing': 2389,
'atp/field/postcode/missing': 2389, …
```
=> [ptt_th] Update the code to include more. (2389 items)

locations/spiders/aldi_nord_be.py, locations/spiders/aldi_nord_de.py, locations/spiders/aldi_nord_dk.py, locations/spiders/aldi_nord_es.py, locations/spiders/aldi_nord_fr.py, locations/spiders/aldi_nord_lu.py, locations/spiders/aldi_nord_nl.py, locations/spiders/aldi_nord_pl.py, locations/spiders/aldi_nord_pt.py, locations/spiders/aldi_sud_au.py, locations/spiders/aldi_sud_ch.py, locations/spiders/aldi_sud_cn.py, locations/spiders/aldi_sud_gb.py, locations/spiders/aldi_sud_hu.py, locations/spiders/aldi_sud_ie.py, locations/spiders/aldi_sud_it.py, locations/spiders/aldi_sud_us.py
So NSI has just flip flopped on Aldi branding, causing us be different and fail matching (so no category). I've hardcoded the category, and in most cases, removed the brand so we get it from them. I expect there will be more drama, at least in Germany, but I'll keep an eye out for it.
=> [Aldi] Brand updates

locations/spiders/taco_bell_es.py
I was a little concerned about the auth token, but I wrote this spider > 2 days ago and it still works.
=> [TacoBell ES] Fix spider

locations/spiders/culvers_us.py
Opening hours were missing Saturday. + Now including drive through times.
=> [Culvers US] Fix opening hours

locations/spiders/o_tacos.py
Rel: https://github.com/osmlab/name-suggestion-index/pull/9627
=> [O'Tacos] Add spider

locations/spiders/ever_green_tw.py
```python
{'atp/brand/Ever Green': 28,
'atp/brand_wikidata/Q126369781': 28,
'atp/category/amenity/pharmacy': 28,
'atp/category/multiple': 28,
'atp/field/city/missing': 28,
'atp/field/country/from_spider_name': 28,
'atp/field/lat/missing': 28,
'atp/field/lon/missing': 28,
'atp/field/state/missing': 28,
'atp/field/street_address/missing': 28,
'atp/nsi/brand_missing': 28,
'downloader/request_bytes': 627, …
```
=> [ever_green_tw] Add Ever Green in Taiwan (28 items)

locations/spiders/f24.py, locations/spiders/gov_osservaprezzi_carburanti_it.py, locations/spiders/q8.py, locations/spiders/q8_italia.py, locations/spiders/tango.py
Rel: https://github.com/osmlab/name-suggestion-index/commit/a4b49c0dfb657f6582708c46e1badfb8b72ac6af
=> [Q8][Tango] Update wikidata ids

locations/spiders/lewiatan_pl.py
=> [Lewiatan PL] Drop "missing" phone numbers

locations/spiders/kfc.py, locations/spiders/kfc_amrest.py, locations/spiders/kfc_at.py, locations/spiders/kfc_au.py, locations/spiders/kfc_ca.py, locations/spiders/kfc_de.py, locations/spiders/kfc_fr.py, locations/spiders/kfc_gb.py, locations/spiders/kfc_gr.py, locations/spiders/kfc_in.py, locations/spiders/kfc_it.py, locations/spiders/kfc_my.py, locations/spiders/kfc_nl.py, locations/spiders/kfc_nz.py, locations/spiders/kfc_ph.py, locations/spiders/kfc_sg.py, locations/spiders/kfc_th.py, locations/spiders/kfc_us.py, locations/spiders/rostics_ru.py
Potential fix for #8626
Remove old and broken GB parsing
Remove bad name
Set closed on items without opening hours
=> [KFC] Modernise code

locations/categories.py, locations/spiders/lincolnshire_cooperative.py
These are shops not specialist doctor clinics.
Fixes #8634
=> lincolnshire_cooperative: fix incorrect use of healthcare:speciality

locations/spiders/nhs_scotland_gb.py
This runs using GB proxy so changing to require proxy.
=> [NHSScotlandGB] Add requires proxy to non running spider

locations/spiders/burger_king_cz.py
```python
{'atp/brand/Burger King': 53,
'atp/brand_wikidata/Q177054': 53,
'atp/category/amenity/fast_food': 53,
'atp/field/country/from_spider_name': 51,
'atp/field/email/missing': 53,
'atp/field/image/missing': 53,
'atp/field/operator_wikidata/missing': 53,
'atp/field/phone/missing': 33,
'atp/field/twitter/missing': 53,
'atp/nsi/cc_match': 53,
'atp/operator/AmRest s.r.o.': 33,
'atp/operator/BK Team, a.s.': 5,
'atp/operator/Lagardere Travel Retail, a.s': 3,
'atp/operator/Rex Concepts BK Czech s.r.o.': 9,
'downloader/request_bytes': 2860, …
```
=> [BurgerKing CZ] Fix spider

locations/spiders/burger_king_cz.py, locations/spiders/burger_king_ro.py
```python
{'atp/brand/Burger King': 27,
'atp/brand_wikidata/Q177054': 27,
'atp/category/amenity/fast_food': 27,
'atp/nsi/cc_match': 27,
'atp/operator/AmRest Food SRL': 10,
'atp/operator/Rex Concepts BK Romania s.r.l.': 14,
'downloader/request_bytes': 2860,
'downloader/response_bytes': 4835, …
```
=> [BurgerKing RO] Fix spider

locations/spiders/auchan_ru.py
```json
{
"atp/auchan_ru/hours/failed": 1,
"atp/brand/Атак": 78,
"atp/brand/Ашан": 157,
"atp/brand_wikidata/Q110053013": 157,
"atp/brand_wikidata/Q2868738": 78,
"atp/category/shop/supermarket": 235,
"atp/field/city/missing": 235,
"atp/field/country/from_spider_name": 235,
"atp/field/image/missing": 235,
"atp/field/operator/missing": 235,
"atp/field/operator_wikidata/missing": 235,
"atp/field/postcode/missing": 235,
"atp/field/state/missing": 235,
"atp/field/street_address/missing": 235,
"atp/field/twitter/missing": 235,
"atp/field/website/missing": 235,
"atp/nsi/perfect_match": 235,
"downloader/request_bytes": 706,
"downloader/response_bytes": 74389,
"downloader/response_count": …
```
=> [auchan_ru] add spider (235 locations)

.isort.cfg, locations/spiders/yermolino_ru.py
Stats:
```json
{
"atp/brand/Ермолино": 2919,
"atp/brand_wikidata/Q109995205": 2919,
"atp/category/shop/convenience": 2919,
"atp/field/country/from_spider_name": 2919,
"atp/field/email/missing": 2919,
"atp/field/image/missing": 2919,
"atp/field/opening_hours/missing": 2,
"atp/field/operator/missing": 2919,
"atp/field/operator_wikidata/missing": 2919,
"atp/field/phone/missing": 2919,
"atp/field/postcode/missing": 2919,
"atp/field/street_address/missing": 2919,
"atp/field/twitter/missing": 2919,
"atp/field/website/missing": 2919,
"atp/nsi/perfect_match": 2919,
"downloader/request_bytes": 644,
"downloader/response_bytes": 151691, …
```
=> [yermolino_ru] add spider (2.9k locations)

locations/spiders/fix_price.py
The spider works on my locals under RU IP and fails in weekly with proxy enabled, let's see if setting a country in proxy helps.
=> [fix_price] set country in proxy

locations/spiders/bmo.py, locations/spiders/circle_k.py
```python
{'atp/brand/Circle K': 7370,
'atp/brand/Clean Freak Car Wash': 23,
'atp/brand/Corner Store': 11,
'atp/brand/Couche-Tard': 607,
'atp/brand/Holiday': 437,
'atp/brand/Kangaroo Express': 109,
"atp/brand/Mac's": 13,
'atp/brand/On the Run': 95,
'atp/brand/Rainstorm Car Wash': 37,
'atp/brand_wikidata/Q16931259': 95,
'atp/brand_wikidata/Q2836957': 607,
'atp/brand_wikidata/Q3268010': 7370,
'atp/brand_wikidata/Q4043527': 13,
'atp/brand_wikidata/Q5880490': 437,
'atp/brand_wikidata/Q61747408': 109,
'atp/category/amenity/car_wash': 60,
'atp/category/amenity/fuel': 7070,
'atp/category/shop/convenience': 1572,
'atp/field/brand_wikidata/missing': 71,
'atp/field/email/missing': 8702,
'atp/field/image/missing': 8702,
'atp/field/lat/missing': 18,
'atp/field/lon/missing': 18, …
```
=> [CircleK] Improve branding

locations/spiders/relay_fr.py
fixes #8701 (not fully sure is it actual fix given https://github.com/alltheplaces/alltheplaces/issues/6433)
=> mark as requiring FR proxy

locations/spiders/pijalniewedel.py
entry for subbrand for hot chocolate cafe chain was deleted
note: I have no idea who owns/operates each of this brandings, but as far as public perception goes it is a single brand
=> fix brand tag

locations/spiders/rossmann_pl.py
Proper fix for https://github.com/alltheplaces/alltheplaces/pull/8703
=> Change rossmann_pl url, much more keys can be now extracted

locations/spiders/paczkomat_inpost_pl.py
Fixes #8717 (filter out `post_office`s)
=> [paczkomat_inpost_pl.py] Fixes #8717 (filter out `post_office`s)

locations/spiders/general_logistics_systems.py
Fixed the spider
```python
{'atp/brand/General Logistics Systems': 3971,
'atp/brand_wikidata/Q46495823': 3971,
'atp/category/missing': 3971,
'atp/cdn/cloudflare/response_count': 277,
'atp/cdn/cloudflare/response_status_count/200': 276,
'atp/field/email/missing': 3971,
'atp/field/image/missing': 3971,
'atp/field/operator/missing': 3971,
'atp/field/operator_wikidata/missing': 3971,
'atp/field/phone/missing': 3971,
'atp/field/state/missing': 3971,
'atp/field/street_address/missing': 3971,
'atp/field/twitter/missing': 3971,
'atp/field/website/missing': 3971,
'atp/nsi/match_failed': 3971,
'downloader/request_bytes': 107279,
'downloader/request_count': 277,
'downloader/request_method_count/GET': 277, …
```
=> [gls_de] Fixed spider (3971 items)

locations/spiders/orlen_paczka_pl.py
=> Fix #8716 - filter out what is not a parcel machine

locations/spiders/tomtom.py, locations/storefinders/alltheplaces.py
I've written this code several times for when I want to format shift a file from the weekly into .osm (because JOSM struggles with geojson files). It may as well go in master in case anyone else wants to use it. It also has the massive benefit of if an organisation wanted to publish their data in the ATP format, we could ingest it in basically no code, see the attached spider.
=> Add ATP ingest code

locations/spiders/tmobile_us.py
I'm on mobile internet now so only ran spider on NY state, but result looks good so far. If we will be making too many requests on weekly then we potentially can switch to `us_centroids_50mile_radius_state.csv`, although I'm not sure about this at the moment.
Stats on NY:
```json
{
"atp/brand/T-Mobile": 501,
"atp/brand_wikidata/Q3511885": 501,
"atp/category/shop/mobile_phone": 501,
"atp/field/city/missing": 501,
"atp/field/country/from_spider_name": 501,
"atp/field/email/missing": 501,
"atp/field/image/missing": 501,
"atp/field/opening_hours/missing": 2,
"atp/field/operator/missing": 501,
"atp/field/operator_wikidata/missing": 501,
"atp/field/phone/missing": 501,
"atp/field/postcode/missing": 501,
"atp/field/state/from_reverse_geocoding": 501,
"atp/field/street_address/missing": 501, …
```
=> [tmobile_us] fix spider

locations/spiders/camping_world_us.py
```python
{'atp/brand/Camping World': 214,
'atp/brand_wikidata/Q5028383': 214,
'atp/category/shop/caravan': 214,
'atp/field/email/missing': 214,
'atp/field/image/missing': 214,
'atp/field/opening_hours/missing': 214,
'atp/field/operator/missing': 214,
'atp/field/operator_wikidata/missing': 214,
'atp/field/twitter/missing': 214,
'atp/field/website/invalid': 59,
'atp/nsi/perfect_match': 214,
'downloader/request_bytes': 2269,
'downloader/response_bytes': 831350,
'elapsed_time_seconds': 10.453424, …
```
=> [CampingWorld US] Fix spider

locations/spiders/burger_king_ru.py
```python
{'atp/brand/Бургер Кинг': 835,
'atp/brand_wikidata/Q177054': 835,
'atp/category/amenity/fast_food': 835,
'atp/field/city/missing': 835,
'atp/field/country/from_spider_name': 835,
'atp/field/image/missing': 835,
'atp/field/operator/missing': 835,
'atp/field/operator_wikidata/missing': 835,
'atp/field/phone/invalid': 762,
'atp/field/postcode/missing': 835,
'atp/field/state/missing': 835,
'atp/field/street_address/missing': 835,
'atp/field/twitter/missing': 835,
'atp/field/website/missing': 835,
'atp/nsi/cc_match': 835,
'downloader/request_bytes': 272,
'downloader/response_bytes': 2293195, …
```
=> [BurgerKing RU] Fix spider

locations/spiders/burger_king_mx.py
I can't get more than 69 POIs out of the website, even as a user. The last weekly that succeeded had 420.
=> [BurgerKing MX] Fix spider

locations/spiders/opel_rent_de.py
Rel: https://github.com/osmlab/name-suggestion-index/commit/b17b108af87e5af61165edf8fb2565f85290f194
```python
{'atp/brand/Opel Rent': 365,
'atp/brand_wikidata/Q40966': 365,
'atp/category/amenity/car_rental': 365,
'atp/field/country/from_spider_name': 365,
'atp/field/email/invalid': 26,
'atp/field/image/missing': 365,
'atp/field/opening_hours/missing': 44,
'atp/field/operator/missing': 365,
'atp/field/operator_wikidata/missing': 365,
'atp/field/phone/invalid': 61,
'atp/field/phone/missing': 24,
'atp/field/state/missing': 365,
'atp/field/twitter/missing': 365,
'atp/nsi/match_failed': 365,
'downloader/request_bytes': 163289,
'downloader/request_count': 367,
'downloader/request_method_count/GET': 367,
'downloader/response_bytes': 4861612, …
```
=> [OpelRent DE] Add spider

locations/spiders/freddy_fresh_de.py
Rel: https://github.com/osmlab/name-suggestion-index/commit/7355b1f6e47bcbc1776ecea572669b257df8161c
```python
{'atp/brand/Freddy Fresh': 83,
'atp/brand_wikidata/Q124255344': 83,
'atp/category/amenity/fast_food': 83,
'atp/field/email/missing': 83,
'atp/field/image/dropped': 83,
'atp/field/image/missing': 83,
'atp/field/name/missing': 83,
'atp/field/opening_hours/missing': 83,
'atp/field/operator/missing': 83,
'atp/field/operator_wikidata/missing': 83,
'atp/field/twitter/missing': 83,
'atp/nsi/brand_missing': 83,
'downloader/request_bytes': 215663,
'downloader/request_count': 85,
'downloader/request_method_count/GET': 85,
'downloader/response_bytes': 2897912,
'downloader/response_count': 85,
'downloader/response_status_count/200': 85,
'elapsed_time_seconds': 3.234353, …
```
=> [FreddyFresh DE] Add spider

locations/spiders/chorten_pl.py
I tried 
```
def post_process_item(self, item, response, ld_data, **kwargs):
item["extras"]["shop"] = "yes"
yield item
```
but apparently with callback it is not working
=> fix Chorten

locations/spiders/abc_pl.py
see say  https://www.openstreetmap.org/?mlat=50.042003&mlon=20.060863#map=19/50.04192/20.06127
=> not all abs shops are abc branded or having abc name

locations/spiders/kate_spade_au_nz.py
<details><summary>stats</summary>
```python
{'atp/brand/Kate Spade New York': 10,
'atp/brand_wikidata/Q6375797': 10,
'atp/category/shop/clothes': 10,
'downloader/request_bytes': 488,
'downloader/response_bytes': 3457,
'elapsed_time_seconds': 1.558215,
'httpcompression/response_bytes': 20012,
'item_scraped_count': 10, …
```
=> [kate_spade_au_nz] Fix Spider (10 locations)

locations/spiders/pizza_hut_ae_sa.py
=> [PizzaHutAUSA] Ignore robots.txt

locations/spiders/chetyre_lapy_ru.py
```python
{'atp/brand/Четыре лапы': 534,
'atp/brand_wikidata/Q62390783': 534,
'atp/category/shop/pet': 534,
'atp/field/country/from_spider_name': 534,
'atp/field/email/missing': 534,
'atp/field/image/missing': 136,
'atp/field/operator/missing': 534,
'atp/field/operator_wikidata/missing': 534,
'atp/field/postcode/missing': 534,
'atp/field/state/missing': 534,
'atp/field/street_address/missing': 534,
'atp/field/twitter/missing': 534,
'atp/nsi/perfect_match': 534,
'downloader/request_bytes': 3008,
'downloader/response_bytes': 240297, …
```
=> [ChetyreLapy RU] Fix spider

locations/spiders/leroy_merlin_pl.py
Rel: #8766 
Stats:
```json
{
"atp/brand/Leroy Merlin": 80,
"atp/brand_wikidata/Q889624": 80,
"atp/category/shop/doityourself": 80,
"atp/cdn/cloudflare/response_count": 2,
"atp/cdn/cloudflare/response_status_count/200": 1,
"atp/cdn/cloudflare/response_status_count/404": 1,
"atp/field/image/missing": 80,
"atp/field/operator/missing": 80,
"atp/field/operator_wikidata/missing": 80,
"atp/field/state/missing": 80,
"atp/field/twitter/missing": 80,
"atp/nsi/cc_match": 80,
"downloader/request_bytes": 731,
"downloader/response_bytes": 9575,
"elapsed_time_seconds": 1.93263, …
```
=> [leroy_merlin_pl] fix spider

locations/spiders/target_us.py
```python
{'atp/brand/Target': 1963,
'atp/brand_wikidata/Q1046951': 1963,
'atp/category/shop/department_store': 1741,
'atp/category/shop/supermarket': 222,
'atp/field/email/missing': 1963,
'atp/field/image/dropped': 1963,
'atp/field/image/missing': 1963,
'atp/field/operator/missing': 1963,
'atp/field/operator_wikidata/missing': 1963,
'atp/field/twitter/missing': 1963,
'atp/nsi/cc_match': 1963,
'downloader/request_bytes': 1037401,
'downloader/request_count': 1967,
'downloader/request_method_count/GET': 1967,
'downloader/response_bytes': 148133084,
'downloader/response_count': 1967,
'downloader/response_status_count/200': 1966,
'elapsed_time_seconds': 19.91618, …
```
=> [Target US] Fix spider

locations/spiders/hubo_nl.py, locations/structured_data_spider.py
Removed the duplicated "HardwareStore" from the list of wanted types in structured data spider.
=> [HuboNL] Add Hubo NL spider and remove dup SD wanted type

locations/spiders/kona_grill.py
```python
{'atp/brand/Kona Grill': 26,
'atp/brand_wikidata/Q6428706': 26,
'atp/category/amenity/restaurant': 26,
'atp/field/country/from_reverse_geocoding': 26,
'atp/field/email/missing': 26,
'atp/nsi/perfect_match': 26,
'downloader/request_bytes': 607,
'downloader/response_bytes': 30861,
'elapsed_time_seconds': 2.700882, …
```
=> [kona_grill] Fix Spider (26 locations)

locations/spiders/manning_cartell_au.py
<details><summary></summary>
```python
{'atp/brand/Manning Cartell': 6,
'atp/brand_wikidata/Q117746697': 6,
'atp/category/shop/clothes': 6,
'downloader/request_bytes': 497,
'downloader/response_bytes': 3351,
'elapsed_time_seconds': 1.911041,
'finish_time': datetime.datetime(2024, 7, 5, 15, 42, 7, 423699, tzinfo=datetime.timezone.utc),
'httpcompression/response_bytes': 13718, …
```
=> [manning_cartell_au] Fix Spider

locations/spiders/discount_tire.py
```python
{'atp/brand/Discount Tire': 1050,
'atp/brand_wikidata/Q5281735': 1050,
'atp/category/shop/tyres': 1050,
'atp/field/image/missing': 1050,
'atp/field/operator/missing': 1050,
'atp/field/operator_wikidata/missing': 1050,
'atp/field/twitter/missing': 1050,
'atp/nsi/perfect_match': 1050,
'downloader/request_bytes': 1513223,
'downloader/request_count': 1055,
'downloader/request_method_count/POST': 1055,
'downloader/response_bytes': 1799249,
'downloader/response_count': 1055,
'downloader/response_status_count/200': 1055,
'elapsed_time_seconds': 1277.711108,
'finish_time': datetime.datetime(2024, 7, 8, 18, 6, 57, 911783, tzinfo=datetime.timezone.utc),
'httpcompression/response_bytes': 2594977, …
```
=> [discount_tire] Rewrote spider to fix (1050 items)

Dockerfile
=> Upgrade pipenv in sync with readme

locations/spiders/regal_theaters.py
=> [RegalTheaters] Change to schema wanted type

locations/spiders/ritzcarlton.py
=> [RitzCarlton] Change to sitemap

locations/spiders/subway_kw.py
<details><summary></summary>
```python
{'atp/brand/Subway': 58,
'atp/brand_wikidata/Q244457': 58,
'atp/category/amenity/fast_food': 58,
'atp/field/image/missing': 58,
'atp/field/opening_hours/missing': 58,
'atp/field/operator/missing': 58,
'atp/field/operator_wikidata/missing': 58,
'atp/field/phone/missing': 58,
'atp/field/postcode/missing': 52,
'atp/field/state/missing': 58,
'atp/field/twitter/missing': 58,
'atp/field/website/missing': 58,
'atp/nsi/cc_match': 58,
'downloader/request_bytes': 26259,
'downloader/request_count': 19,
'downloader/request_method_count/GET': 19,
'downloader/response_bytes': 5531400,
'downloader/response_count': 19,
'downloader/response_status_count/200': 18, …
```
=> [subway_kw] Add Spider (58 locations)

locations/spiders/kooperatifmarket_tr.py
rel: https://github.com/osmlab/name-suggestion-index/pull/9713
```json
{
"atp/brand/Türkiye Tarım Kredi Kooperatif Market": 2333,
"atp/brand_wikidata/Q127328776": 2333,
"atp/category/shop/supermarket": 2333,
"atp/field/city/missing": 2333,
"atp/field/country/from_spider_name": 2333,
"atp/field/email/missing": 2333,
"atp/field/image/missing": 2333,
"atp/field/name/missing": 2333,
"atp/field/opening_hours/missing": 2333,
"atp/field/operator/missing": 2333,
"atp/field/operator_wikidata/missing": 2333,
"atp/field/phone/missing": 2333,
"atp/field/postcode/missing": 2333,
"atp/field/street_address/missing": 2333,
"atp/field/twitter/missing": 2333,
"atp/field/website/missing": 2333,
"atp/nsi/brand_missing": 2333,
"downloader/request_bytes": 805, …
```
=> [kooperatifmarket_tr] add spider (2k locations)

locations/spiders/state_farm_us.py
Haven't run this till completion, let's see if it works in weekly.
=> [state_farm_us] fix spider

locations/spiders/timpson_gb.py
There are 403s on weekly, let's see if proxy helps.
=> [timpson_gb] enable proxy

locations/storefinders/stockinstore.py
I tested 5 random spiders that used StockInStoreSpider and they all did not work before and do know. I assume this will propogate to the other 35 that use it.
=> Fix spiders by disobeying the robotstxt

locations/spiders/natwest_gb.py
no idea are there any there now and on which stage of pipeline numbers are formatted...
But in the worst case it provides a bit of futureproofing
=> handle spaces if any are present

locations/spiders/dino_pl.py
and I have not confirmed is it fitting `branch` - and these are unusual in Poland
see also #8739
(I expect that many like this will be needed before I will be able to trust ATP data)
=> [Dino PL] Improve name

locations/spiders/empik_pl.py
based on #8782 solution
edited in browser, waiting for test run
=> drop not really real names

locations/spiders/family_dollar_us.py
at least I assume so, based also on OSM (but I never ever visited USA!)
=> [Family Dollar US] Improve name

locations/spiders/pizza_hut_us.py
=> [PizzaHut US] Improve name

locations/spiders/the_container_store.py
```py
{'atp/brand/The Container Store': 106,
'atp/brand_wikidata/Q7727445': 106,
'atp/category/shop/houseware': 106,
'atp/field/email/missing': 106,
'atp/field/operator/missing': 106,
'atp/field/operator_wikidata/missing': 106,
'atp/field/twitter/missing': 106,
'atp/nsi/perfect_match': 106,
'downloader/request_bytes': 106106,
'downloader/request_count': 108,
'downloader/request_method_count/GET': 108,
'downloader/response_bytes': 11742898,
'downloader/response_count': 108,
'downloader/response_status_count/200': 108,
'elapsed_time_seconds': 128.716524,
'finish_time': datetime.datetime(2024, 7, 16, 20, 56, 50, 546871, tzinfo=datetime.timezone.utc), …
```
=> [TheContainerStore] New spider

locations/spiders/peets_coffee_us.py
Similar to #8837, #8838, #8839, etc.
=> [PeetsCoffeeUS] "name" in response should go in "branch" field

locations/spiders/delikatesy_centrum_pl.py
say 'PIECHOWICE KRYSZTAŁOWA 64' - that is just address written in a weird way
=> this is neither name nor branch

locations/spiders/paczkomat_inpost_pl.py
=> [paczkomat_inpost_pl] fix #8844, rename key name -> description

locations/spiders/crateandbarrel.py
=> [CrateAndBarrel] Use browser user agent

locations/spiders/oporto_au.py
Was timing out after 15s.
Some stores don't have address so fixed that.
=> [OportoAU] Fix non running spider and address errors

locations/spiders/odido_pl.py
=> [OdidoPL] Change to use sitemap

locations/spiders/paczkomat_inpost_pl.py
`boundary=administrative` is used for that
=> [paczkomat_inpost_pl] addr:state is not used in Poland

locations/spiders/baptist_health_arkansas_us.py, locations/spiders/blue_bottle_coffee.py, locations/spiders/dunelm_gb.py, locations/spiders/iowa_university_us.py, locations/spiders/jbhifi.py, locations/spiders/marinemax_us.py, locations/spiders/orange_pl.py, locations/spiders/warhammer.py, locations/storefinders/algolia.py
Also migrate BaptistHealthArkansasUS, DunelmGB, IowaUniversityUS, Jbhifi, MarinemaxUS, OrangePL, and Warhammer to the new storefinder. In doing so, IowaUniversityUS gained 20 new locations; Jbhifi, 46; OrangePL, 227; and Warhammer, 19.
Side note: The storefinder class uses the "Search multiple indices" API endpoint, which is a bit overkill since we're not searching, and all spiders only use one index. But not all sites give access to the "browse" endpoint, and this one works with all of them.
=> New storefinder: Algolia; and new spider BlueBottleCoffee that uses it (85 locations)

locations/spiders/hsbc_us.py, locations/spiders/move_yourself_au.py, locations/spiders/tgi_fridays_au.py, locations/spiders/wiener_feinbacker_heberer_de.py
=> Fix some spider class name imports

locations/spiders/paczkomat_inpost_pl.py
1. Remove `-go` ex. `1-go Maja` should be `1 Maja`
2. Replace `oś.` -> `Osiedle`
=> [paczkomat_inpost_pl] Cleanup

locations/spiders/agata_meble_pl.py
=> Remove name from agata_meble_pl

locations/spiders/systeme_u.py
following  up from #8578 .
The PR is to fix the address, opening_hours, phone, city, postcode and name.
This is my first contribution in this project, please let me know if there is any guideline that I need to follow.
=> [SystemeU] Fix fields

locations/spiders/fibank_bg.py
Resolves https://github.com/alltheplaces/alltheplaces/issues/7903
It looks like it's not caching the opening hours and the phone correctly. Also I'm unsure on how to tag "Blind access" for the ATMs, which is why it's commented.
=> Add Fibank spider

locations/spiders/dominos_pizza_fr.py
This PR adds phone field scraping
=> [Dominos_Pizza_FR] add phone field

locations/spiders/jardiland_fr.py
This PR is to add 'magasin' to the url path
=> [Jardiland FR] fix website field

locations/spiders/delikatesy_centrum_pl.py
Add website tag for delikatesy centrum
```json
{
"pageProps": {
"shops": [
{
"id": 1,
"external_id": 1996,
"shop_code": "100494",
"network_type": "DC",
"name": "ALBIGOWA \\nDELIKATESY CENTRUM",
"description": null,
"opening_hours": [
```
external_id can be used for obtaining website of selected shop like:
https://www.delikatesy.pl/sklepy/1996 from example above
=> [delikatesy_centrum_pl] Add website tag

locations/spiders/allegro_one_box_pl.py
Not sure if it will be fast enough..
Fixes #8900
=> [allegro_one_box_pl] filter for only PL points, try to extract more data

locations/spiders/pandora.py
This PR fixes the tag website which was missing the href lang tags
=> [Pandora] fix tag website

locations/spiders/media_expert_pl.py, locations/spiders/mediaexpert_pl.py
=> [MediaExpertPL] Add spider (581 locations)

locations/spiders/lubaszka_pl.py
(example of data: "ul.Światowida paw. 32")
=> remove name from lubaszka_pl

locations/spiders/picard_fr.py
Added a spider for the [Picard](https://magasins.picard.fr/) stores.
There are currently 1142 stores.
=> [PicardFR] Added Spider for Picard (1142 locations)

locations/spiders/da_ru.py
rel: https://github.com/osmlab/name-suggestion-index/pull/9750
=> [da_ru] add spider

locations/spiders/cic.py
example value: 'CIC AGENCE MONACO - CIC MONACO FONTVIELLE'
=> remove name from cic

locations/spiders/grycan_pl.py
example value: 'Lodziarnia Firmowa Gdańsk'
=> remove name from grycan_pl

locations/spiders/le_crobag_de.py
=> remove trailing comma from city name in le_crobag_de.py

locations/spiders/lidl_de.py
`name=Bergeborbeck`
maybe, maybe it should be put into `branch` - but checking this would require local knowledge which I am lacking
=> lidl_de  - remove names

locations/spiders/vodafone_de.py
=> remove name from vodafone_de

locations/spiders/hypovereinsbank_de.py
example: HypoVereinsbank Günzburg
=> remove name from hypovereinsbank_de

locations/spiders/h_e_b_us.py
```
{'atp/brand/H-E-B': 295,
'atp/brand/H-E-B Pharmacy': 301,
'atp/brand/H-E-B plus!': 39,
'atp/brand_wikidata/Q830621': 635,
'atp/category/amenity/pharmacy': 301,
'atp/category/multiple': 301,
'atp/category/shop/supermarket': 334,
'atp/field/email/missing': 635,
'atp/field/image/missing': 635,
'atp/field/operator/missing': 635,
'atp/field/operator_wikidata/missing': 635,
'atp/field/twitter/missing': 635,
'atp/nsi/cc_match': 301,
'atp/nsi/match_failed': 334,
'downloader/request_bytes': 2186,
'downloader/response_bytes': 56621,
'elapsed_time_seconds': 5.467493,
'finish_time': …
```
=> [HEB US] Fix Spider and add H-E-B Pharmacy locations

locations/spiders/the_counter_us.py
```py
{'atp/brand/The Counter': 13,
'atp/brand_wikidata/Q7727763': 13,
'atp/category/amenity/restaurant': 13,
'atp/field/country/from_spider_name': 13,
'atp/nsi/perfect_match': 13,
'downloader/request_bytes': 5946,
'downloader/request_count': 15,
'downloader/request_method_count/GET': 15,
'downloader/response_bytes': 166658,
'downloader/response_count': 15,
'downloader/response_status_count/200': 14,
'elapsed_time_seconds': 17.104431,
'finish_time': datetime.datetime(2024, 7, 27, 5, 14, 11, 748469, …
```
=> [TheCounterUS] New spider (13 locations)

locations/spiders/tommy_bahama.py
```py
{'atp/brand/Tommy Bahama': 148,
'atp/brand_wikidata/Q3531299': 148,
'atp/category/amenity/restaurant': 23,
'atp/category/multiple': 23,
'atp/category/shop/clothes': 125,
'atp/field/country/from_reverse_geocoding': 24,
'atp/field/email/missing': 148,
'atp/field/image/dropped': 125,
'atp/field/image/missing': 148,
'atp/field/operator/missing': 148,
'atp/field/operator_wikidata/missing': 148,
'atp/field/postcode/missing': 23,
'atp/field/twitter/missing': 148,
'atp/field/website/invalid': 91,
'atp/nsi/perfect_match': 148, …
```
=> [TommyBahama] New spider (148 locations)

locations/spiders/kendra_scott_us.py
```py
{'atp/brand/Kendra Scott': 149,
'atp/brand_wikidata/Q120885584': 149,
'atp/category/shop/jewelry': 149,
'atp/field/city/missing': 149,
'atp/field/country/from_spider_name': 149,
'atp/field/image/missing': 149,
'atp/field/opening_hours/missing': 45,
'atp/field/operator/missing': 149,
'atp/field/operator_wikidata/missing': 149,
'atp/field/postcode/missing': 149,
'atp/field/state/from_reverse_geocoding': 148,
'atp/field/street_address/missing': 149,
'atp/field/twitter/missing': 149,
'atp/field/website/invalid': 6,
'atp/nsi/perfect_match': 149, …
```
=> [KendraScottUS] New spider (149 locations)

locations/items.py, locations/spiders/mall_maverick.py
=> Fix Mall Maverick social media extraction

locations/spiders/politix_au.py
=> Add Politix (AU)

locations/spiders/bob_jane_tmarts_au.py
Fix https://github.com/alltheplaces/alltheplaces/issues/8488
=> Add Bob Jane T-Marts (AU)

locations/spiders/screwfix_gb.py
=> screwfix_gb - remove call center phone

locations/pipelines/address_clean_up.py, locations/storefinders/storerocket.py, tests/test_address_clean_up.py
Fix https://github.com/alltheplaces/alltheplaces/issues/8830
=> Remove 'undefined' street addresses

locations/spiders/b_and_m.py, locations/spiders/bella_italia_gb.py, locations/spiders/bhf_gb.py, locations/spiders/lloyds_bank_gb.py, locations/spiders/nationwide_gb.py, locations/spiders/next.py, locations/spiders/premier_gb.py, locations/spiders/screwfix_gb.py, locations/spiders/tsb_gb.py
=> fix phone removal condition

locations/spiders/bleu_libellule_fr.py
Fix https://github.com/alltheplaces/alltheplaces/issues/9037
=> Add Bleu Libellule

locations/spiders/west_marine_us.py
Fix https://github.com/alltheplaces/alltheplaces/issues/9029
=> Add West Marine (US)

locations/spiders/familia_ru.py
rel: https://github.com/osmlab/name-suggestion-index/pull/9755
=> [familia_ru] fix spider, add wikidata

locations/spiders/nationwide_gb.py
https://github.com/alltheplaces/alltheplaces/blob/master/DATA_FORMAT.md
>image
>A URL of an image for the venue. We try to make this specific to the venue and not generic for the brand that is operating the venue.
=> remove generic image

locations/spiders/nationwide_gb.py
=> Nationwide GB Ignore "is opening" messages

locations/spiders/ted_baker.py, locations/spiders/ted_baker_us.py
```py
{'atp/brand/Ted Baker': 30,
'atp/brand_wikidata/Q2913458': 30,
'atp/category/shop/clothes': 30,
'atp/field/image/missing': 30,
'atp/field/opening_hours/missing': 30,
'atp/field/website/missing': 30,
'atp/nsi/perfect_match': 30,
'downloader/response_bytes': 5822,
'elapsed_time_seconds': 2.182936,
'finish_time': datetime.datetime(2024, 7, 31, 0, 54, 12, …
```
=> [TedBaker] New spider (auto-generated) (30 locations)

locations/spiders/leonidas.py
This PR takes into consideration shops that close in the middle of the day
=> [Leonidas] fix opening_hours midday break

locations/commands/insights.py
This adds a new subcommand, `--nsi-overrides`, under the `insights` command, that reports any spiders that emit a tag that conflicts with the tags specified by the spider's NSI preset. I thought something like this would be helpful in the quest to move spiders from `name` to `branch`, as well as catch any tagging inconsistencies between ATP and NSI. I'm not sure the `insights` command is the right place to put the functionality though—like maybe it should be a pipeline instead, that reports mismatches as a statistic. The subcommand respects `preserveTags` from NSI, so things that are supposed to have unique names, like car retailers or theaters, aren't reported.
=> Add a new insight to list tags from spiders that differ from NSI

locations/spiders/phillips_66_conoco_76.py
https://github.com/osmlab/name-suggestion-index/pull/9768
=> [Conoco] Update wikidata

locations/spiders/dollar_tree.py
Data contains "DollarTree" however NSI uses "Dollar Tree"
=> [Dollar Tree] Fix name

locations/spiders/sdek.py
I was not able to get any result from my locals - there is a Qrator blocking on a website, let's see if Zyte can bypass it.
=> [sdek] attempt to fix spider by enabling proxy

locations/spiders/dia_ar.py
```json
{
"atp/brand/Dia": 1074,
"atp/brand_wikidata/Q925132": 1074,
"atp/category/shop/supermarket": 1074,
"atp/field/country/from_spider_name": 1074,
"atp/field/email/missing": 1074,
"atp/field/image/missing": 1074,
"atp/field/lat/missing": 26,
"atp/field/lon/missing": 26,
"atp/field/opening_hours/missing": 1074,
"atp/field/operator/missing": 1074,
"atp/field/operator_wikidata/missing": 1074,
"atp/field/phone/missing": 1074,
"atp/field/postcode/missing": 1074,
"atp/field/twitter/missing": 1074,
"atp/field/website/missing": 1074,
"atp/item_scraped_host_count/diaonline.supermercadosdia.com.ar": 1074,
"atp/nsi/cc_match": 1074,
"downloader/request_bytes": 666,
"downloader/response_bytes": 46403, …
```
=> [dia_ar] add spider (1k locations)

locations/spiders/p_terrys_us.py
Fix https://github.com/alltheplaces/alltheplaces/issues/9279
=> P. Terry's

locations/spiders/royal_donuts_de.py
Fix https://github.com/alltheplaces/alltheplaces/issues/9277
=> Royal Donuts

locations/spiders/smoothie_king_kr_us.py
Fix https://github.com/alltheplaces/alltheplaces/issues/9256
=> Add Smoothie King

locations/spiders/waba_grill_us.py
Fix https://github.com/alltheplaces/alltheplaces/issues/9255
=> Waba Grill

locations/spiders/pommesfreunde_at_de.py
Fix https://github.com/alltheplaces/alltheplaces/issues/9269
=> Add Pommesfreunde

locations/spiders/south_street_burger_ca.py
Fix https://github.com/alltheplaces/alltheplaces/issues/9272
=> Add South Street Burger

locations/spiders/thai_express_ca_us.py
Fix https://github.com/alltheplaces/alltheplaces/issues/9274
=> Add Thai Express

locations/spiders/villa_madina_ca.py
Fix https://github.com/alltheplaces/alltheplaces/issues/9276
=> Add Villa Madina

locations/spiders/original_tommys.py
Fix https://github.com/alltheplaces/alltheplaces/issues/9280
=> Original Tommys

locations/spiders/mikucha_th.py
Fix https://github.com/alltheplaces/alltheplaces/issues/9201
=> Mikucha (TH)

locations/spiders/bob_and_berts_gb_ie.py
Fix https://github.com/alltheplaces/alltheplaces/issues/9175
=> Bob and berts

locations/spiders/mochachos.py, locations/spiders/mochachos_za.py
Fix https://github.com/alltheplaces/alltheplaces/issues/9263
=> Add Mochachos

locations/spiders/bos_coffee_ph.py
Fix https://github.com/alltheplaces/alltheplaces/issues/9185
=> Add Bo's Coffee (PH)

locations/spiders/chocolate_company_nl.py
Fix https://github.com/alltheplaces/alltheplaces/issues/9187
=> Add Chocolate Company (NL)

locations/spiders/wallace_bishop_au.py
Fix https://github.com/alltheplaces/alltheplaces/issues/9211
=> Add Wallace Bishop (AU)

locations/spiders/penningtons_ca.py
Fix https://github.com/alltheplaces/alltheplaces/issues/9213
@davidhicks as a FYI, may want to add the SweetIQ endpoints to the allowed domains in this auto generated spider.
=> Add Penningtons (CA)

locations/spiders/french_connection.py
Fix https://github.com/alltheplaces/alltheplaces/issues/9227
TODO: Change to company_id for #8983 later
=> Add French Connection

locations/spiders/c_and_a.py
This PR adds crawling of the phone number again
=> [C&A] fix phone field

locations/spiders/jazen_tea_ca_us.py
Fix https://github.com/alltheplaces/alltheplaces/issues/9193
=> Add Jazen Tea

locations/spiders/patisserie_valerie_gb.py
Fix https://github.com/alltheplaces/alltheplaces/issues/9205
=> Add Patisserie Valerie

locations/spiders/giant_my.py
Fix https://github.com/alltheplaces/alltheplaces/issues/7491
=> Add Giant Hypermarket (MY)

locations/spiders/coffee_republic.py
Fix https://github.com/alltheplaces/alltheplaces/issues/9190
=> Add coffee_republic

locations/spiders/country_style_ca.py
Fix https://github.com/alltheplaces/alltheplaces/issues/9165
=> Add Country Style (CA)

locations/spiders/coffeeshop_company.py
Fix https://github.com/alltheplaces/alltheplaces/issues/9206
=> Add Coffeeshop Company

locations/spiders/veggie_grill_us.py
```py
{'atp/brand/Veggie Grill': 16,
'atp/brand_wikidata/Q18636427': 16,
'atp/category/amenity/fast_food': 16,
'atp/nsi/perfect_match': 16,
'downloader/request_bytes': 620,
'downloader/response_bytes': 19493,
'elapsed_time_seconds': 3.979596,
'finish_time': datetime.datetime(2024, 8, 2, 18, 17, 50, 746806, tzinfo=datetime.timezone.utc), …
```
=> [VeggieGrillUS] New spider (16 locations)

docs/PIPELINES.md, locations/pipelines/email_clean_up.py, locations/settings.py, tests/test_pipeline_email_clean_up.py
Fix #9126.
I haven't specifically looked at https://pypi.org/project/email-validator/ in great detail, but it may be an option to do this 'properly'
=> Add really basic email clean up pipeline

locations/dict_parser.py, locations/spiders/wasgau_de.py
=> Add Wasgau (DE) and german key names for DictParser

locations/spiders/yves_rocher.py
```json
{
"atp/brand/Yves Rocher": 1933,
"atp/brand_wikidata/Q28496595": 1933,
"atp/category/shop/beauty": 1933,
"atp/field/country/from_website_url": 272,
"atp/field/email/missing": 1933,
"atp/field/image/missing": 1933,
"atp/field/lat/missing": 7,
"atp/field/lon/missing": 7,
"atp/field/opening_hours/missing": 25,
"atp/field/operator/missing": 1933,
"atp/field/operator_wikidata/missing": 1933,
"atp/field/phone/invalid": 16,
"atp/field/phone/missing": 21,
"atp/field/street_address/missing": 1,
"atp/field/twitter/missing": 1933,
"atp/nsi/cc_match": 1933,
"downloader/request_bytes": 13487,
"downloader/request_count": 33,
"downloader/request_method_count/GET": 33,
"downloader/response_bytes": 1507223,
"downloader/response_count": 33,
"downloader/response_status_count/200": 24, …
```
=> [yves_rocher] bump download timeout

locations/spiders/auchan_ua.py
=> Update auchan_ua.py wikidata ID

locations/categories.py, locations/spiders/suzuki_marine_au.py
Fix https://github.com/alltheplaces/alltheplaces/issues/8519
=> Suzuki marine au

locations/spiders/gong_cha_us.py
Fix https://github.com/alltheplaces/alltheplaces/issues/9317
=> Gong Cha (US)

locations/spiders/bridgehead_ca.py
Fix https://github.com/alltheplaces/alltheplaces/issues/9186
=> Add Bridgehead (CA)

locations/spiders/revive_herbal_health_za.py
Fix #9288 
35 stores, but they have only put 8 on the map!
=> Add Revive Herbal Health (ZA)

locations/spiders/work_world.py, locations/spiders/work_world_us.py
=> Add Work World (US)

locations/spiders/magasin_vert_fr.py
=> Add Magasin Vert (FR)

locations/spiders/farmfoods_sk.py
Fix https://github.com/alltheplaces/alltheplaces/issues/9323
=> Add Farmfoods (SK)

locations/spiders/lewiatan_pl.py
Fix https://github.com/alltheplaces/alltheplaces/issues/9210
=> Lewiatan (PL): Drop bracketed content from city names

locations/spiders/supermacs_gb_ie.py
FIx https://github.com/alltheplaces/alltheplaces/issues/9259
=> Add Supermacs (GB, IE)

locations/spiders/playa_bowls_us.py
Fix https://github.com/alltheplaces/alltheplaces/issues/9265
=> Playa bowls (US)

locations/spiders/handels_ice_cream_us.py
```py
{"atp/brand/Handel's Homemade Ice Cream": 151,
'atp/brand_wikidata/Q16983222': 151,
'atp/category/amenity/ice_cream': 151,
'atp/field/city/missing': 151,
'atp/field/country/from_spider_name': 151,
'atp/field/email/missing': 151,
'atp/field/image/missing': 151,
'atp/field/operator/missing': 151,
'atp/field/operator_wikidata/missing': 151,
'atp/field/phone/missing': 151,
'atp/field/postcode/missing': 151,
'atp/field/state/from_reverse_geocoding': 151,
'atp/field/street_address/missing': 151,
'atp/field/twitter/missing': 151,
'atp/item_scraped_host_count/handelsicecream.com': 151,
'atp/nsi/perfect_match': 151,
'downloader/request_bytes': 610, …
```
=> [HandelsIceCreamUS] New spider (151 locations)

locations/spiders/fosters_freeze_us.py
```py
{'atp/brand/Fosters Freeze': 64,
'atp/brand_wikidata/Q5473851': 64,
'atp/category/amenity/fast_food': 64,
'atp/field/city/missing': 64,
'atp/field/email/missing': 64,
'atp/field/image/missing': 64,
'atp/field/operator/missing': 64,
'atp/field/operator_wikidata/missing': 64,
'atp/field/phone/missing': 64,
'atp/field/postcode/missing': 64,
'atp/field/state/from_reverse_geocoding': 64,
'atp/field/street_address/missing': 64,
'atp/field/twitter/missing': 64,
'atp/field/website/missing': 64,
'atp/item_scraped_host_count/fostersfreeze.com': 64,
'atp/nsi/perfect_match': 64,
'downloader/request_bytes': 616, …
```
=> [FostersFreezeUS] New spider (64 locations)

locations/spiders/truly_nolen_us.py
Fix https://github.com/alltheplaces/alltheplaces/issues/9286
=> Add Truly Nolan (US)

docs/SPIDER_NAMING.md
=> Add a hint about scrapy's built in generators to the onboarding pathway

locations/spiders/cashterminal_bg.py
The domain has been changed, no other changes to their site.
=> Fix cashterminal_bg

locations/spiders/crew_clothing_gb.py
Fix https://github.com/alltheplaces/alltheplaces/issues/9315
=> Fix Crew Clothing to crawl more branches

locations/spiders/famous_footwear.py
=> StructuredDataSpiders - FamousFootwear - Drop usage of deprecated inspect_item

docs/HARD_WORK_SPIDER.md
=> Document some common patterns seen in hard work spiders

locations/storefinders/storefrontgateway.py
Save on foods:
```
2024-08-11 04:03:49 [scrapy.statscollectors] INFO: Dumping Scrapy stats:
{'atp/brand/Save-On-Foods': 187,
'atp/brand_wikidata/Q7427974': 187,
'atp/category/shop/supermarket': 187,
'atp/field/email/missing': 186,
'atp/field/image/missing': 187,
'atp/field/opening_hours/missing': 176,
'atp/field/operator/missing': 187,
'atp/field/operator_wikidata/missing': 187,
'atp/field/twitter/missing': 187,
'atp/field/website/missing': 187,
'atp/item_scraped_host_count/storefrontgateway.saveonfoods.com': 187,
'atp/nsi/perfect_match': 187,
'downloader/request_bytes': 851, …
```
=> Storefinders - Storefrontgateway - Refactor to pre and post processing hooks

docs/API_SPIDER.md
Part of https://github.com/alltheplaces/alltheplaces/pull/9419/files
=> Storefinders - Update API Spider documentation to highlight the pre and post processing pattern

locations/spiders/game_gb.py
Last run was 345 items, runs happily locally; unclear why it times out in CI
=> StructuredDataSpiders - Game GB - Drop usage of deprecated inspect_item

.github/ISSUE_TEMPLATE/spider_bug_report.yaml
Fix #9349 
Trial it out: https://github.com/CloCkWeRX/alltheplaces/issues/new?assignees=&labels=bug&projects=&template=spider_bug_report.yaml
=> Create an issue template specifically for broken or malformed spiders

.github/ISSUE_TEMPLATE/request.yaml
Slight variation to #9348 and #9347 
To play with it:
https://github.com/CloCkWeRX/alltheplaces/issues/new?assignees=&labels=new-spider&projects=&template=request.yaml
Sample issue:
https://github.com/CloCkWeRX/alltheplaces/issues/4
Has a 'new-spider' label optionally.
=> Ask more optional questions on the new spider form

locations/storefinders/closeby.py
Part of https://github.com/alltheplaces/alltheplaces/pull/9419
patisserie_valerie_gb:
```
{'atp/brand/Patisserie Valerie': 255,
'atp/brand_wikidata/Q22101966': 255,
'atp/category/amenity/cafe': 255,
'atp/field/city/missing': 255,
'atp/field/country/from_spider_name': 255,
'atp/field/email/missing': 255,
'atp/field/image/missing': 255,
'atp/field/opening_hours/missing': 255,
'atp/field/operator/missing': 255,
'atp/field/operator_wikidata/missing': 255,
'atp/field/state/missing': 255,
'atp/field/street_address/missing': 255,
'atp/field/twitter/missing': 255,
'atp/item_scraped_host_count/www.closeby.co': 255,
'atp/nsi/perfect_match': 255, …
```
=> Storefinders - Closeby - Add pre_process_data, post_process_item

locations/spiders/kahve_dunyasi.py
Kahve Dünyası is a Turkish coffee shop chain with around 300 locations in multiple countries. 
Wikidata: https://www.wikidata.org/wiki/Q28008050
=> Add kahve_dunyasi spider (~300 locations)

ci/run_all_spiders.sh
=> Fix the redirect URL to use the whole URL

locations/spiders/asda_gb.py, locations/spiders/lidl_at.py, locations/spiders/lidl_be.py, locations/spiders/lidl_bg.py, locations/spiders/lidl_de.py, locations/spiders/lidl_gb.py, locations/spiders/lidl_hr.py, locations/spiders/lidl_ie.py, locations/spiders/lidl_ni.py, locations/spiders/lidl_ro.py, locations/spiders/lidl_si.py, locations/storefinders/virtualearth.py
https://github.com/alltheplaces/alltheplaces/pull/6526
=> Refactoring: VirtualEarth variable name changes from Autospidergen branch

locations/hours.py
https://github.com/alltheplaces/alltheplaces/discussions/9502
=> Slightly improve documentation of set_closed

locations/spiders/migros_tr.py, locations/spiders/sok_tr.py
ŞOK is one of the largest Turkish supermarket chains with around 11000 locations in Turkey.
Wikidata: https://www.wikidata.org/wiki/Q19613992
=> Add sok_tr spider (~11000 locations across Turkey)

ci/check_spider_naming_consistency.py, locations/categories.py, locations/spiders/nandos_bh.py, locations/spiders/nandos_bw.py, locations/spiders/nandos_in.py, locations/spiders/nandos_mu.py, locations/spiders/nandos_om.py, locations/spiders/nandos_qa.py, locations/spiders/nandos_za.py, locations/spiders/nandos_zm.py, locations/spiders/nandos_zw.py
Several of the Nando's spiders have been broken for a while due to the website format apparently changing.
PK website appears to be currently broken (issue #9533) but other than that this should fix the remainder.
=> Fix broken Nandos spiders and add BW and MU

locations/spiders/mitre_10_nz.py
allowed_domains was incorrect.
=> mitre_10_nz: fix spider

locations/spiders/leonidas.py
This PR adds FR/DE/NL localisation of the website url.
I tried to make it the most easily maintainable but I'm not a legit programmer so please feel free to make it more future-proof.
=> [Leonidas] localised url

locations/spiders/sok_tr.py
Aligned sok_tr spider's brand_name and tagging according to [NSI](https://nsi.guide/index.html?t=brands&k=shop&v=supermarket&tt=q19613992). Fixes #9536
=> [sok_tr] aligned sok_tr spider name and tagging with NSI

locations/spiders/pilot_flying_j.py
```python
{'atp/brand/Flying J': 228,
'atp/brand/ONE9': 33,
'atp/brand/Pilot': 401,
'atp/brand/Town Pump': 18,
'atp/brand_wikidata/Q64128179': 401,
'atp/brand_wikidata/Q64130592': 228,
'atp/brand_wikidata/Q7830004': 18,
'atp/category/amenity/fuel': 733,
'atp/cdn/cloudflare/response_count': 1004,
'atp/cdn/cloudflare/response_status_count/200': 1004,
'atp/field/brand/missing': 53,
'atp/field/brand_wikidata/missing': 86,
'atp/field/email/missing': 733,
'atp/field/image/missing': 733,
'atp/field/opening_hours/missing': 733,
'atp/field/operator/missing': 733,
'atp/field/operator_wikidata/missing': 733,
'atp/field/phone/missing': 22,
'atp/field/twitter/missing': 733,
'atp/item_scraped_host_count/locations.pilotflyingj.com': 733,
'atp/nsi/cc_match': 629,
'atp/nsi/match_failed': 18, …
```
=> [PilotFlyingJ] Improve branding

locations/spiders/c_and_a.py
This PR merges duplicated opening_hours on multiple days
=> [C&A] improve opening_hours formatting

locations/spiders/systeme_u.py
This PR improves the opening_hours field, targeting only the main shop and not the sub shops
=> [Systeme_U] fix opening_hours

locations/spiders/hays_travel_gb.py
Only a single API request for all branches.
=> simpler spider: hays_travel_gb

locations/spiders/revive_herbal_health_za.py
=> Fix Revive Herbal Health (ZA) to get all stores and phone

locations/spiders/believ_gb.py
Rel: https://github.com/osmlab/name-suggestion-index/issues/9795
=> [Believ GB] Add spider

locations/spiders/nandos_za.py
Follow-up to #9531 after not changing the handling of multiple phones in #9548
=> Fix multiple phones in NandosZA

locations/spiders/chase_us.py, locations/structured_data_spider.py
Fix https://github.com/alltheplaces/alltheplaces/issues/9557
=> StructuredDataSpider - Add hooks for extracting and mapping amenityFeatures

locations/spiders/levis.py
```py
{'atp/brand/Dockers': 27,
"atp/brand/Levi's": 1036,
'atp/brand_wikidata/Q127962': 1036,
'atp/brand_wikidata/Q538792': 27,
'atp/category/shop/clothes': 1063,
'atp/field/email/missing': 1063,
'atp/field/operator/missing': 1063,
'atp/field/operator_wikidata/missing': 1063,
'atp/field/phone/missing': 85,
'atp/field/twitter/missing': 1063,
'atp/geometry/null_island': 4,
'atp/item_scraped_host_count/maps.levi.com': 1064,
'atp/nsi/brand_missing': 27,
'atp/nsi/perfect_match': 1036,
'downloader/request_bytes': 1113, …
```
=> [Levis] New spider (1063 locations)

locations/spiders/markant_de.py
Fix https://github.com/alltheplaces/alltheplaces/issues/7796
=> Add Markant (DE)

locations/spiders/profi_ro.py
=> Profi (RO)

locations/spiders/thelins_konditori_se.py
=> Thelins Konditori SE

locations/spiders/pyaterochka_ru.py
It works under VPN and hopefully should work in weeklys. 
If not then spider can be changed to use bbox api e.g. `https://5ka.ru/api/v2/stores/?bbox=55.73262698483946,37.563372770639624,55.79911382927404,37.85742870936035` to fetch data in smaller pieces.
```json
{
"atp/brand/Пятёрочка": 21654,
"atp/brand_wikidata/Q1768969": 21654,
"atp/category/shop/supermarket": 21654,
"atp/field/city/missing": 2,
"atp/field/country/from_spider_name": 21654,
"atp/field/email/missing": 21654,
"atp/field/image/missing": 21654,
"atp/field/operator/missing": 21654,
"atp/field/operator_wikidata/missing": 21654,
"atp/field/phone/missing": 21654,
"atp/field/postcode/missing": 21654,
"atp/field/state/missing": 21654,
"atp/field/street_address/missing": 21654,
"atp/field/twitter/missing": 21654, …
```
=> [pyaterochka_ru] add spider (21k locations)

locations/spiders/claudia_strater_nl.py
Fix https://github.com/alltheplaces/alltheplaces/issues/9224
=> Add Claudia Strater (NL)

locations/spiders/robert_harris_nz.py
Fix https://github.com/alltheplaces/alltheplaces/issues/9202
=> Add Robert Harris (NZ)

locations/spiders/sklavenitis_gr.py
=> Add Sklavenitis (GR)

locations/spiders/jack_wills_gb.py
Fix https://github.com/alltheplaces/alltheplaces/issues/9228
{'atp/brand/Jack Wills': 21,
'atp/brand_wikidata/Q6115814': 21,
'atp/category/shop/clothes': 21,
'atp/field/state/missing': 14,
'atp/item_scraped_host_count/www.jackwills.com': 21,
'atp/nsi/perfect_match': 21,
'downloader/request_bytes': 374,
'downloader/response_bytes': 35392,
'elapsed_time_seconds': 1.64792, …
=> Add Jack Wills

locations/hours.py, locations/spiders/backhaus_nahrstedt_de.py, locations/structured_data_spider.py
=> Add Backhaus Nahrstedt(DE), and add Bakeries to wanted types

locations/spiders/petshop_science_za.py
Waiting on NSI update to get category and name.
```
'atp/brand/Petshop Science': 96,
'atp/brand_wikidata/Q129202801': 96,
'atp/category/missing': 96,
'atp/field/email/missing': 96,
'atp/field/image/missing': 96,
'atp/field/name/missing': 96,
'atp/field/opening_hours/missing': 79,
'atp/field/operator/missing': 96,
'atp/field/operator_wikidata/missing': 96,
'atp/field/phone/missing': 59,
'atp/field/state/missing': 26,
'atp/field/twitter/missing': 96,
'atp/item_scraped_host_count/www.petshopscience.co.za': 96,
'atp/nsi/brand_missing': 96,
```
=> Add PetshopScienceZASpider (96 locations)

locations/spiders/crocs_es.py
Share item_attributes and use DictParser.
=> [crocs_es] slight refresh of spider

locations/spiders/vida_caffe.py, locations/spiders/vida_caffe_za.py
=> Add Vida Caffe

locations/spiders/the_good_feet_store.py, locations/spiders/topaz_pl.py
These don't quite fit, but this at least labels the "extract json" bit in a consistent fashion
=> Refactor The Good Feet Store, Topaz to a similar pattern to JSON Blob Spider

locations/spiders/check_n_go_us.py
=> Add Check n Go

locations/spiders/heron_foods.py
Fix https://github.com/alltheplaces/alltheplaces/issues/8469
=> Fix Heron Foods

locations/spiders/woops_us.py
=> Add Woops!

locations/spiders/primaprix.py
Fix https://github.com/alltheplaces/alltheplaces/issues/7954
=> Add Primaprix

locations/spiders/fedex.py
=> Fedex - Flag as needing proxy

locations/spiders/alaska_commercial_company.py
Fix https://github.com/alltheplaces/alltheplaces/issues/1720
=> Add Alaska Commercial Company

locations/spiders/mcdonalds_gt.py
Fix https://github.com/alltheplaces/alltheplaces/issues/2593 - or well, this was already working
=> Mcdonalds (GT) - Refactor to JSON Blob Spider

locations/dict_parser.py, locations/spiders/laveneciana.py, locations/spiders/laveneciana_ar.py
Fix https://github.com/alltheplaces/alltheplaces/issues/3270
=> Fix Laveneciana

locations/categories.py, locations/spiders/coastal_country.py, locations/structured_data_spider.py
=> Fix Coastal; add support for PaymentsAccepted to the Structured Data Spider

locations/spiders/tops.py
Fix https://github.com/alltheplaces/alltheplaces/issues/9658 ?
=> Add category to Tops

locations/spiders/house_and_home.py, locations/spiders/ok_furniture.py, locations/spiders/studio_88.py
All three are under Shoprite holdings and have almost identical store pages.
```
'atp/brand/OK Furniture': 287,
'atp/brand_wikidata/Q116474866': 287,
'atp/category/shop/furniture': 287,
'atp/field/city/missing': 287,
'atp/field/country/from_website_url': 287,
'atp/field/email/missing': 287,
'atp/field/image/missing': 287,
'atp/field/opening_hours/missing': 287,
'atp/field/operator/missing': 287,
'atp/field/operator_wikidata/missing': 287,
'atp/field/phone/invalid': 25,
'atp/field/postcode/missing': 287,
'atp/field/state/missing': 287,
'atp/field/street_address/missing': 287,
'atp/field/twitter/missing': 287,
'atp/item_scraped_host_count/www.okfurniture.co.za': 287,
'atp/nsi/perfect_match': 287,
```
```
'atp/brand/House & Home': 43, …
```
=> OK Furniture (287 locations), House & Home (43 locations), Studio 88 (397 locations) (Southern Africa)

locations/spiders/coop_no.py
Fix https://github.com/alltheplaces/alltheplaces/issues/9556 (Partially? fully? Not sure)
=> Add category to Coop Elecktro

locations/spiders/carpet_barn_gb.py
It's a small chain, but it's a nice website and a friend works there.
=> [CarpetBarn GB] Add spider

locations/spiders/chicken_licken.py
`JSONBlobSpider` has cut a few lines of boiler plate here.
=> [chicken_licken] add 308 primarily southern Africa locations

locations/spiders/absa_za.py
I believe ABSA also has operations in Kenya and Ghana.
Fixes https://github.com/alltheplaces/alltheplaces/issues/827
=> [absa_za] add spider (551 banks, 2985 ATMs)

locations/spiders/pure_gym_dk.py
Fitness World in DK has rebranded as Pure Gym.
=> [PureGymDK] Add spider

locations/spiders/kop_and_kande.py
=> [KopAndKande] Add spider

locations/spiders/pie_city_za.py, locations/spiders/tiger_wheel_and_tyre_za.py
This is just the same as tiger_wheel_and_tyre, but I can't find any more of their clients. If/when I do come across more I'll make a dedicated storefinder, rather than cross-inheriting like this.
=> Pie City ZA spider

locations/spiders/romans_pizza.py, locations/spiders/romans_pizza_za.py
```
"atp/brand/Roman's Pizza": 253,
'atp/brand_wikidata/Q65079427': 253,
'atp/category/amenity/fast_food': 253,
'atp/field/city/missing': 253,
'atp/field/country/from_spider_name': 253,
'atp/field/email/missing': 253,
'atp/field/image/missing': 253,
'atp/field/opening_hours/invalid': 33,
'atp/field/operator/missing': 253,
'atp/field/operator_wikidata/missing': 253,
'atp/field/postcode/missing': 253,
'atp/field/state/missing': 253,
'atp/field/street_address/missing': 253,
'atp/field/twitter/missing': 253,
'atp/field/website/missing': 253,
'atp/item_scraped_host_count/romanspizza.co.za': 253,
'atp/nsi/perfect_match': 253,
```
=> Romans Pizza ZA Spider (253 locations)

locations/spiders/rosneft_ru.py
```json
{
"atp/brand/ПТК": 1,
"atp/brand/Роснефть": 2246,
"atp/brand/ТНК": 35,
"atp/brand_wikidata/Q1141123": 2246,
"atp/brand_wikidata/Q2298901": 35,
"atp/brand_wikidata/Q3486584": 34,
"atp/brand_wikidata/Q4360193": 1,
"atp/category/amenity/fuel": 2316,
"atp/field/brand/missing": 34,
"atp/field/city/missing": 2316,
"atp/field/country/from_spider_name": 2316,
"atp/field/email/missing": 2316,
"atp/field/image/missing": 2316,
"atp/field/opening_hours/missing": 2316,
"atp/field/operator/missing": 2316,
"atp/field/operator_wikidata/missing": 2316,
"atp/field/phone/missing": 2316,
"atp/field/postcode/missing": 2316,
"atp/field/state/missing": 2316,
"atp/field/street_address/missing": 2316,
"atp/field/twitter/missing": 2316,
"atp/field/website/missing": 2316, …
```
=> [rosneft_ru] add spider (2k locations)

locations/spiders/intersport_se.py
```
{'atp/brand/Intersport': 89,
'atp/brand_wikidata/Q666888': 89,
'atp/category/shop/sports': 89,
'atp/field/opening_hours/missing': 89,
'atp/field/postcode/missing': 89,
'atp/item_scraped_host_count/www.intersport.se': 89,
'atp/nsi/cc_match': 89,
'downloader/request_bytes': 618,
'downloader/response_bytes': 55340, …
```
=> [intersport_se] fix spider (89 locations)

locations/spiders/banana_republic_home_us.py, locations/storefinders/stockist.py
=> Add Banana Republic Home (US) (32 stores)

locations/spiders/up_and_running_gb.py
=> Add Up & Running (GB) (28 stores)

locations/spiders/honda_au.py
=> Add Honda (AU) (87 dealers)

locations/categories.py, locations/spiders/truckline_au.py
=> Add Truckline (AU) (52 stores)

locations/spiders/roof_racks_galore_au.py
=> Add Roof Racks Galore (AU) (27 stores)

locations/spiders/taco_cabana_us.py
=> Fix Taco Cabana

locations/spiders/bubbakoos_burritos_us.py
Fix https://github.com/alltheplaces/alltheplaces/issues/9816
=> Add bubbakoos_burritos_us

locations/spiders/nekter_juice_bar_us.py
Fix https://github.com/alltheplaces/alltheplaces/issues/9822
=> Add nekter_juice_bar_us

locations/spiders/burgermeister.py, locations/spiders/burgermeister_de.py
Fix https://github.com/alltheplaces/alltheplaces/issues/9807
=> Add burgermeister

locations/spiders/american_deli_us.py
Fix https://github.com/alltheplaces/alltheplaces/issues/9830
=> Add american_deli_us

locations/spiders/cuisinella.py, locations/spiders/cuisinella_fr.py
=> Add cuisinella

locations/spiders/chaayos_in.py
```
File "/home/ubuntu/locations/spiders/chaayos_in.py", line 15, in parse_item
item["extras"].pop("instagram")
KeyError: 'instagram'
```
=> Fix chaayos_in

locations/spiders/hero_certified_burgers_ca.py
Fix https://github.com/alltheplaces/alltheplaces/issues/9823
=> Add Hero Certified Burgers CA

locations/spiders/fat_bastard_burrito_ca.py
=> Add Fat Bastard Burrito

locations/spiders/chicken_street.py, locations/spiders/flippin_pizza_us.py, locations/spiders/king_pie_za.py, locations/storefinders/super_store_finder.py
FIx https://github.com/alltheplaces/alltheplaces/issues/9803
=> Add Flippin Pizza (US) and document alternative superstorefinder pattern

locations/spiders/mucho_burrito.py
Fix https://github.com/alltheplaces/alltheplaces/issues/9805
=> Add Mucho Burrito

locations/spiders/extreme_pita_ca_us.py
=> Add Extreme Pita

locations/spiders/kfc_au.py
Fix https://github.com/alltheplaces/alltheplaces/issues/9742
=> Update kfc_au.py to remove testing location

locations/spiders/amcal_au.py
Attempt to fix https://github.com/alltheplaces/alltheplaces/issues/9796
=> Update amcal_au opening hours

locations/spiders/hyundai_at.py
=> [Hyundai AT] Add spider

locations/spiders/spar_za.py
spar_za has had no results for the past few runs, and was showing 403 error in the logs, however it does run locally.
=> Use proxy for SparZA

locations/spiders/capitec_bank_za.py
=> Use proxy for CapitecBankZA

locations/spiders/espacolaser.py, locations/spiders/espacolaser_br.py
Fix https://github.com/alltheplaces/alltheplaces/issues/9012
=> Add Espacolaser

locations/spiders/bobali_es.py, locations/spiders/bobali_es_it.py
Fix https://github.com/alltheplaces/alltheplaces/issues/9222 ?
https://www.boboli.es/es/boboli-store claims:
So I am not 100% what "store type: offline" means vs that
=> Add Boboli 

locations/spiders/mochachos.py
=> Mochachos details

locations/spiders/chamas_tacos_fr.py
=> Add chamas_tacos_fr

locations/spiders/flash_coffee.py, locations/spiders/flash_coffee_id.py
Fix https://github.com/alltheplaces/alltheplaces/issues/9191
=> Flash coffee

locations/spiders/natixis.py
Got all items that had an `ld+json`
=> [natixis] Added Spider (31 items)

locations/spiders/togos_us.py
```py
{"atp/brand/Togo's": 148,
'atp/brand_wikidata/Q3530375': 148,
'atp/category/amenity/fast_food': 148,
'atp/field/branch/missing': 148,
'atp/field/email/missing': 148,
'atp/field/image/missing': 148,
'atp/field/operator/missing': 148,
'atp/field/operator_wikidata/missing': 148,
'atp/field/twitter/missing': 148,
'atp/field/website/missing': 7,
'atp/item_scraped_host_count/www.togos.com': 148,
'atp/nsi/perfect_match': 148,
'downloader/request_bytes': 759,
'downloader/response_bytes': 36732,
'elapsed_time_seconds': 2.847117, …
```
=> New spider: Togo's (148 locations)

locations/spiders/equatorial_coffee_za.py
=> Add EquatorialCoffeeZASpider

locations/spiders/legit_za.py
Fix https://github.com/alltheplaces/alltheplaces/issues/9218
=> Add LEGiT (ZA)

locations/spiders/wolle_rodel_de.py
=> Add Wolle Rodel

locations/spiders/bestdrive_bw_na_za.py
```
'atp/brand/BestDrive': 134,
'atp/brand_wikidata/Q63057183': 134,
'atp/category/shop/car_repair': 134,
'atp/field/email/invalid': 3,
'atp/field/image/missing': 134,
'atp/field/opening_hours/missing': 134,
'atp/field/operator/missing': 134,
'atp/field/operator_wikidata/missing': 134,
'atp/field/twitter/missing': 134,
'atp/item_scraped_host_count/www.bestdrive.co.za': 134,
'atp/nsi/perfect_match': 134,
```
=> Add BestDriveBWNAZASpider (134 locations)

locations/spiders/john_dorys_za.py, locations/structured_data_spider.py
Please check changes made in `structured_data_spider.py`. I was getting a list of length 1 for payment methods and this fixed it, whilst keeping the previous functionality.
Awaiting NSI update
```
"atp/brand/John Dory's": 39,
'atp/brand_wikidata/Q130140080': 39,
'atp/category/amenity/restaurant': 39,
'atp/cdn/cloudflare/response_count': 50,
'atp/cdn/cloudflare/response_status_count/200': 42,
'atp/cdn/cloudflare/response_status_count/404': 8,
'atp/field/image/dropped': 3,
'atp/field/name/missing': 39,
'atp/field/operator/missing': 39,
'atp/field/operator_wikidata/missing': 39,
'atp/field/twitter/missing': 39,
'atp/item_scraped_host_count/www.johndorys.com': 39,
'atp/nsi/brand_missing': 39,
```
=> Add JohnDorysZASpider (39 locations)

locations/spiders/dedeman.py
```python
{'atp/brand/Dedeman': 17,
'atp/brand/Park Dedeman': 11,
'atp/category/tourism/hotel': 38,
'atp/cdn/cloudflare/response_count': 40,
'atp/cdn/cloudflare/response_status_count/200': 40,
'atp/field/branch/missing': 38,
'atp/field/brand/missing': 10,
'atp/field/brand_wikidata/missing': 38,
'atp/field/country/from_reverse_geocoding': 38,
'atp/item_scraped_host_count/www.dedeman.com': 38,
'downloader/request_bytes': 14312, …
```
=> [Dedeman] Add spider

locations/spiders/yogurtland.py
```py
{'atp/brand/Yogurtland': 228,
'atp/brand_wikidata/Q8054428': 228,
'atp/category/amenity/ice_cream': 228,
'atp/cdn/cloudflare/response_count': 77,
'atp/cdn/cloudflare/response_status_count/200': 77,
'atp/field/email/missing': 228,
'atp/field/operator/missing': 228,
'atp/field/operator_wikidata/missing': 228,
'atp/field/phone/invalid': 14,
'atp/field/twitter/missing': 228,
'atp/item_scraped_host_count/www.yogurtland.com': 228,
'atp/nsi/perfect_match': 228,
'downloader/request_bytes': 33352,
'downloader/request_count': 77,
'downloader/request_method_count/GET': 77,
'downloader/response_bytes': 719236,
'downloader/response_count': 77, …
```
=> Add Yogurtland spider (288 locations)

locations/spiders/legit_za.py
=> LegitZASpider add brand and move name to branch

locations/spiders/fishaways_za.py, locations/storefinders/yext_search.py
Also now collecting phone for YextSearch. I checked the other YextSearch spiders for phone keys and it was only really `mainPhone`, but the others can be present for Fishaways.
=> Add FishawaysZASpider

locations/dict_parser.py, locations/spiders/build_it.py, locations/spiders/buildit.py
```
'atp/brand/Build it': 418,
'atp/brand_wikidata/Q116755810': 418,
'atp/category/shop/doityourself': 418,
'atp/field/country/from_reverse_geocoding': 305,
'atp/field/country/missing': 113,
'atp/field/email/invalid': 9,
'atp/field/image/missing': 418,
'atp/field/lat/missing': 113,
'atp/field/lon/missing': 113,
'atp/field/opening_hours/missing': 418,
'atp/field/operator/missing': 418,
'atp/field/operator_wikidata/missing': 418,
'atp/field/phone/invalid': 106,
'atp/field/postcode/missing': 418,
'atp/field/state/missing': 116,
'atp/field/street_address/missing': 418,
'atp/field/twitter/missing': 418,
'atp/item_scraped_host_count/www.buildit.co.za': 418,
'atp/nsi/perfect_match': 418,
```
=> BuildItSpider 418 locations

locations/spiders/castorama_fr.py
=> [Castorama FR] Add spider

locations/spiders/millies_gb.py
```
{"atp/brand/Millie's": 41,
'atp/brand_wikidata/Q1935533': 41,
'atp/category/shop/bakery': 41,
'atp/field/branch/missing': 41,
'atp/field/country/from_spider_name': 41,
'atp/field/street_address/missing': 41,
'atp/field/website/missing': 41,
'atp/item_scraped_host_count/www.milliescookies.com': 41,
'atp/nsi/perfect_match': 41,
'downloader/request_bytes': 776, …
```
=> [millies_gb] Fix spider (41 locations)

locations/spiders/dis_chem.py
```
'atp/brand/Dis-Chem': 237,
'atp/brand_wikidata/Q97274558': 237,
'atp/category/amenity/pharmacy': 237,
'atp/category/multiple': 237,
'atp/cdn/cloudflare/response_count': 245,
'atp/cdn/cloudflare/response_status_count/200': 245,
'atp/field/city/missing': 237,
'atp/field/country/from_reverse_geocoding': 235,
'atp/field/country/missing': 2,
'atp/field/email/missing': 237,
'atp/field/image/missing': 237,
'atp/field/operator/missing': 237,
'atp/field/operator_wikidata/missing': 237,
'atp/field/postcode/missing': 237,
'atp/field/street_address/missing': 237,
'atp/field/twitter/missing': 237,
'atp/item_scraped_host_count/www.dischem.co.za': 237, …
```
=> Add Dis-Chem (237 locations)

locations/spiders/barbarossa_baeckerei_de.py, tests/test_item_attributes.py
It was failing with `AttributeError: 'Categories' object has no attribute 'items'`.
I've also added basic pytest to check `item_attributes`  and `extras` types to spot these errors earlier.
=> [barbarossa_baeckerei_de] fix spider

locations/spiders/brookshires.py, locations/spiders/brookshires_us.py
Fix #870 
Geoblocking
Part of Wakefern (#10061); using #10063
=> Add Brookshires

locations/spiders/big_5_sporting_goods_us.py
```py
{'atp/brand/Big 5 Sporting Goods': 426,
'atp/brand_wikidata/Q4904902': 426,
'atp/category/shop/sports': 426,
'atp/field/country/from_spider_name': 426,
'atp/field/email/missing': 426,
'atp/field/image/missing': 426,
'atp/field/operator/missing': 426,
'atp/field/operator_wikidata/missing': 426,
'atp/field/twitter/missing': 426,
'atp/field/website/missing': 426,
'atp/item_scraped_host_count/www.big5sportinggoods.com': 426,
'atp/nsi/perfect_match': 426,
'downloader/request_bytes': 364,
'downloader/response_bytes': 114821,
'elapsed_time_seconds': 3.947763, …
```
=> New spider: Big 5 Sporting Goods (426 locations)

locations/spiders/spring_market_us.py
=> Add Spring-Market

locations/spiders/cub.py, locations/spiders/cub_foods_us.py
Fix #1161 
Geoblocking
Using #10063
=> Add CUB Foods

locations/spiders/skoda.py
We need to have the right locale for the API to return the address. I also fixed the mistake with country codes for ones with naff cords.
=> [Škoda] Collect address

locations/spiders/icebolethu_za.py
I guess the website changed a bit as this broke in the latest run
=> Fix icebolethu_za

locations/categories.py, locations/spiders/mugg_and_bean_africa.py, locations/spiders/mugg_and_bean_za.py, locations/storefinders/yext_search.py
There does not seem to be a consistent key for `branch` in YextSearchSpiders, so it needs to be done on an individual basis
=> Add mugg_and_bean_za and mugg_and_bean_africa

locations/spiders/total_energies.py
Various ATMs and a few obvious other services
=> total_energies more services

locations/hours.py, locations/spiders/old_mutual_za.py
Needs NSI update to sort out categories
Changes in locations/hours feel like it would be better done using `time_format` somehow, but this worked for now.
=> Add OldMutualZASpider

locations/pipelines/email_clean_up.py, locations/spiders/doppio_zero.py
Waiting for NSI update for category
I've also included some additions to the email_clean_up to allow for multiple email addresses and to save stripping "mailto:" from extracted links. If that's ok, we could then go through and tidy such things off other spiders.
=> DoppioZeroSpider (28 locations)

locations/spiders/eighty_five_degrees_c_au.py, locations/spiders/eighty_five_degrees_c_tw.py, locations/spiders/eighty_five_degrees_c_us.py
Unfortunately, even the smallest ISEA DGG radius of 24km is too large for the US store locator's measly maximum of 6 results. But, a non-comprehensive is better than no spider.
```py
{'atp/brand/85°C': 15,
'atp/brand_wikidata/Q4644852': 15,
'atp/category/amenity/cafe': 15,
'atp/field/city/missing': 15,
'atp/field/country/from_spider_name': 15,
'atp/field/postcode/missing': 15,
'atp/field/state/missing': 15,
'atp/field/street_address/missing': 15, …
```
=> New spider: 85°C AU/TW/US (477 total locations)

locations/spiders/dog_haus_us.py
```py
{'atp/brand/Dog Haus': 67,
'atp/brand_wikidata/Q105529843': 67,
'atp/category/amenity/fast_food': 63,
'atp/category/craft/caterer': 4,
'atp/field/branch/missing': 8,
'atp/field/email/missing': 67,
'atp/field/image/missing': 67,
'atp/field/operator/missing': 67,
'atp/field/operator_wikidata/missing': 67,
'atp/field/twitter/missing': 67,
'atp/item_scraped_host_count/locations.doghaus.com': 67,
'atp/nsi/brand_missing': 67,
'downloader/request_bytes': 668,
'downloader/response_bytes': 293934,
'elapsed_time_seconds': 3.190239, …
```
=> New spider: Dog Haus (67 locations)

docs/DETECTION_AND_CODE_GENERATION.md
=> Autospidergen - First pass of documentation

locations/spiders/sleepmasters.py
Almost the same as Bradlows, #10056 
```
'atp/brand/Sleepmasters': 259,
'atp/brand_wikidata/Q116475002': 259,
'atp/category/shop/bed': 259,
'atp/field/email/invalid': 4,
'atp/field/image/missing': 259,
'atp/field/operator/missing': 259,
'atp/field/operator_wikidata/missing': 259,
'atp/field/street_address/missing': 259,
'atp/field/twitter/missing': 259,
'atp/item_scraped_host_count/www.sleepmasters.co.za': 259,
'atp/nsi/perfect_match': 259,
```
=> Add SleepmastersSpider

locations/spiders/bash.py
- Items are not just ZA, but several other countries.
- Sort out state and countries
- Log unknown brands
- Refactor to JsonBlob
- Get hash for fetch from the page (see #9458 where the hash had changed so the spider broke)
```
'atp/bash/unknown_brand/CARD REPLEN': 1,
'atp/bash/unknown_brand/GALAXY LEFIC ONLINE': 1,
'atp/bash/unknown_brand/GG CLAREMONT PROTEA ROAD': 1,
'atp/bash/unknown_brand/GG CONSTANTIA COURTYARD COURTYARD 53, MAIN ROAD, W': 1,
'atp/bash/unknown_brand/GG ILLOVO SQUARE SANDTON': 1,
'atp/bash/unknown_brand/HM EASTGATE BEDFORDVIEW': 1,
'atp/bash/unknown_brand/Sportcene Pier 14': 1,
'atp/bash/unknown_brand/TFG MONEY ACCOUNT PAYMENT': 1,
'atp/bash/unknown_brand/UNION-DNM BT NGEBS MTHATHA': 1,
'atp/bash/unknown_brand/UNION-DNM CANAL WALK CAPE TOWN': 1, …
```
=> Refactor Bash spider

locations/spiders/signature_cosmetics.py
```
'atp/brand/Signature Cosmetics & Fragrances': 203,
'atp/brand_wikidata/Q116894514': 203,
'atp/category/shop/cosmetics': 203,
'atp/field/city/missing': 198,
'atp/field/country/missing': 2,
'atp/field/email/missing': 63,
'atp/field/image/missing': 203,
'atp/field/lat/missing': 18,
'atp/field/lon/missing': 18,
'atp/field/opening_hours/missing': 203,
'atp/field/operator/missing': 203,
'atp/field/operator_wikidata/missing': 203,
'atp/field/phone/missing': 61,
'atp/field/postcode/missing': 203,
'atp/field/state/missing': 203,
'atp/field/street_address/missing': 203,
'atp/field/twitter/missing': 203,
'atp/field/website/missing': 203,
'atp/item_scraped_host_count/www.signaturecosmetics.co.za': 203,
'atp/nsi/perfect_match': 203,
```
=> Add Signature Cosmetics

locations/spiders/grocery_outlet_us.py
```py
{'atp/brand/Grocery Outlet': 552,
'atp/brand_wikidata/Q5609934': 552,
'atp/category/shop/supermarket': 552,
'atp/field/country/from_spider_name': 552,
'atp/field/image/missing': 552,
'atp/field/lat/missing': 54,
'atp/field/lon/missing': 54,
'atp/field/operator/missing': 552,
'atp/field/operator_wikidata/missing': 552,
'atp/field/phone/missing': 62,
'atp/field/twitter/missing': 552,
'atp/field/website/missing': 552,
'atp/geometry/null_island': 54,
'atp/item_scraped_host_count/www.groceryoutlet.com': 552,
'atp/nsi/perfect_match': 552,
'downloader/request_bytes': 1014,
'downloader/response_bytes': 59497, …
```
=> Grocery Outlet (552 locations)

locations/spiders/living_spaces.py
```
{'atp/brand/Living Spaces': 38,
'atp/brand_wikidata/Q63626177': 38,
'atp/category/missing': 38,
'atp/field/country/from_reverse_geocoding': 38,
'atp/field/name/missing': 38,
'atp/item_scraped_host_count/www.livingspaces.com': 38,
'atp/nsi/brand_missing': 38,
'downloader/request_bytes': 328,
'downloader/response_bytes': 17799,
'elapsed_time_seconds': 1.721157,
'finish_time': …
```
=> [living_spaces] Fix Spider

locations/spiders/kirklands.py
```
{"atp/brand/Kirkland's": 324,
'atp/brand_wikidata/Q6415714': 324,
'atp/category/shop/interior_decoration': 324,
'atp/field/country/from_reverse_geocoding': 324,
'atp/field/email/missing': 324,
'atp/field/image/missing': 324,
'atp/field/opening_hours/missing': 324,
'atp/field/operator/missing': 324,
'atp/field/operator_wikidata/missing': 324,
'atp/field/twitter/missing': 324,
'atp/item_scraped_host_count/www.kirklands.com': 324,
'atp/nsi/perfect_match': 324,
'downloader/request_bytes': 640,
'downloader/response_bytes': 26506,
'elapsed_time_seconds': 3.882107,
'finish_time': …
```
=> [kirklands] fix spider

locations/spiders/keystore_gb.py
Rel: https://github.com/osmlab/name-suggestion-index/pull/9910
=> [KeyStore GB] Add spider

locations/spiders/brow_art_23_us.py
When looking at #10131 I saw this which is basically the same, so have neatened things up a bit.
Not sure if this counts as a storefinder, or what it is?
=> Refactor BrowArt23USSpider to JSONBlobSpider and collect opening hours

locations/spiders/paris_baguette_ca.py, locations/spiders/paris_baguette_us.py, locations/spiders/pet_valu_ca.py, locations/storefinders/stat.py
```py
{'atp/brand/Paris Baguette': 6,
'atp/brand_wikidata/Q62605260': 6,
'atp/category/shop/bakery': 6,
'atp/item_scraped_host_count/parisbaguette.ca': 6,
'atp/nsi/match_failed': 6,
'downloader/response_bytes': 2625,
'elapsed_time_seconds': 1.590801,
'finish_time': datetime.datetime(2024, 9, 5, 18, 16, 16, 786087, tzinfo=datetime.timezone.utc),
'httpcompression/response_bytes': 7606,
'httpcompression/response_count': …
```
=> Paris Baguette in CA (6 locations) and US (178 locations)

locations/spiders/amathole_za.py
No coordinates, but mostly reasonable addresses
```
'atp/brand/Amathole Funerals': 56,
'atp/brand_wikidata/Q122593900': 56,
'atp/category/shop/funeral_directors': 56,
'atp/field/city/missing': 56,
'atp/field/country/from_spider_name': 56,
'atp/field/email/invalid': 8,
'atp/field/lat/missing': 56,
'atp/field/lon/missing': 56,
'atp/field/opening_hours/missing': 56,
'atp/field/postcode/missing': 56,
'atp/field/state/missing': 56,
'atp/field/website/missing': 56,
'atp/item_scraped_host_count/amatholefunerals.co.za': 56,
'atp/nsi/perfect_match': 56,
```
=> Add AmatholeZASpider

locations/spiders/old_mutual_za.py
Thanks @Firefishy
See https://github.com/alltheplaces/alltheplaces/pull/10040
=> [old_mutual_za] Fix to dynamically get js asset

locations/spiders/galitos_za.py, locations/spiders/maxis_za.py, locations/storefinders/go_review_api.py
Identifier: a request is made to `https://admin.goreview.co.za/website/api/locations/search` and we need the `domain` value from that request
=> Add Maxi's Spider, GoReviewApi storefinder and refactor galitos_za

locations/categories.py, locations/dict_parser.py, locations/spiders/panarottis.py, locations/spiders/rocomamas.py
Both are under Spur Corporation and have identical store finders
Awaiting NSI update for categories
```
'atp/brand/RocoGo': 4,
'atp/brand/RocoMamas': 104,
'atp/brand_wikidata/Q123034964': 108,
'atp/category/missing': 108,
'atp/field/image/missing': 108,
'atp/field/name/missing': 108,
'atp/field/operator/missing': 108,
'atp/field/operator_wikidata/missing': 108,
'atp/field/twitter/missing': 108,
'atp/item_scraped_host_count/rocomamas.com': 108,
'atp/nsi/brand_missing': 108,
```
=> RocoMamas and Panarottis add spiders

locations/spiders/century_21.py
**Fix:** _new approach has been implemented as sitemap page has been vanished from the official website._
**Stats:**
{'atp/brand/Century 21': 9619,
'atp/brand_wikidata/Q1054480': 9619,
'atp/category/office/estate_agent': 9618,
'atp/cdn/cloudflare/response_count': 252,
'atp/cdn/cloudflare/response_status_count/200': 251,
'atp/cdn/cloudflare/response_status_count/500': 1,
'atp/field/branch/missing': 9619,
'atp/field/city/missing': 2302,
'atp/field/country/invalid': 53,
'atp/field/email/missing': 9619,
'atp/field/image/missing': 9619,
'atp/field/lat/missing': 991,
'atp/field/lon/missing': 991,
'atp/field/opening_hours/missing': 9619,
'atp/field/operator/missing': 9619,
'atp/field/operator_wikidata/missing': 9619, …
=> Fix Century 21 Spider

locations/exporters/geojson.py, tests/test_item_attributes.py
Improved the test so it's not looping over all files for each spider.
Also wrapped iteration of spider classes for all modules into a function.
=> [TESTS] speed up item_attributes test

locations/spiders/spur.py
```python
{'atp/brand/Spur': 332,
'atp/brand_wikidata/Q7581546': 332,
'atp/category/amenity/restaurant': 332,
'atp/cdn/cloudflare/response_count': 395,
'atp/cdn/cloudflare/response_status_count/200': 395,
'atp/field/branch/missing': 332,
'atp/field/image/missing': 332,
'atp/field/lat/missing': 6,
'atp/field/lon/missing': 6,
'atp/field/operator/missing': 332,
'atp/field/operator_wikidata/missing': 332,
'atp/field/postcode/missing': 314,
'atp/field/state/missing': 29,
'atp/field/twitter/missing': 332,
'atp/item_scraped_host_count/www.spursteakranches.com': 332,
'atp/nsi/perfect_match': 332,
'downloader/request_bytes': 251674, …
```
=> [Spur] Use CrawlSpider and StructuredDataSpider

locations/spiders/superverd_es.py
=> Add superverd_es

locations/spiders/volkswagen.py
Many countries use a common dealer finder, so here we try all countries to see what we get back. This seems to get North and South America, Western Europe, Southern Africa, Australia, Taiwan, Vietnam.
I'll open an issue to investigate the other countries that don't use this system, and they can then be excluded.
There are lots of services and features, some more of which may be of interest.
<details>
<summary>Crawler stats</summary>
<code>'atp/brand/Volkswagen': 5608,
'atp/brand_wikidata/Q246': 5608,
'atp/category/shop/car': 5608,
'atp/field/branch/missing': 5608,
'atp/field/country/from_reverse_geocoding': 364,
'atp/field/country/from_website_url': 220,
'atp/field/email/invalid': 13,
'atp/field/email/missing': 1621,
'atp/field/image/missing': 5608, …
=> Add Volkswagen spider (5608 locations)

locations/spiders/manhattan_bagel.py
```
{'atp/brand/Manhattan Bagel': 75,
'atp/brand_wikidata/Q64517333': 75,
'atp/category/amenity/fast_food': 75,
'atp/field/country/from_reverse_geocoding': 75,
'atp/field/email/missing': 75,
'atp/item_scraped_host_count/www.manhattanbagel.com': 75,
'atp/nsi/perfect_match': 75,
'downloader/request_bytes': 756,
'downloader/response_bytes': 6744, …
```
=> [manhattan_bagel] fix spider

locations/spiders/cardenas_us.py, locations/storefinders/stat.py
```py
{'atp/brand/Cardenas': 65,
'atp/brand_wikidata/Q64149543': 65,
'atp/category/shop/supermarket': 65,
'atp/field/branch/missing': 65,
'atp/item_scraped_host_count/locations.cardenasmarkets.com': 65,
'downloader/request_bytes': 667,
'downloader/response_bytes': 6694,
'elapsed_time_seconds': 2.200871, …
```
=> Cardenas (65 locations)

locations/spiders/porsche_holding.py
Fixes https://github.com/alltheplaces/alltheplaces/issues/10156 for [some countries](https://github.com/alltheplaces/alltheplaces/issues/10156#issuecomment-2336428610).
```json
{
"atp/brand/Volkswagen": 797,
"atp/brand_wikidata/Q246": 797,
"atp/category/shop/car": 448,
"atp/category/shop/car_repair": 349,
"atp/field/branch/missing": 797,
"atp/field/city/missing": 1,
"atp/field/email/invalid": 12,
"atp/field/email/missing": 30,
"atp/field/image/missing": 797,
"atp/field/lat/missing": 10,
"atp/field/lon/missing": 10,
"atp/field/opening_hours/missing": 614,
"atp/field/operator/missing": 797,
"atp/field/operator_wikidata/missing": 797,
"atp/field/phone/invalid": 41,
"atp/field/phone/missing": 23,
"atp/field/postcode/missing": 17,
"atp/field/state/missing": 797, …
```
=> [porsche_holding] add spider (797 locations)

locations/spiders/kfc_au.py
I think this was my fault in the first place
=> KFC AU and inherited: should remove prefix, not lstrip

locations/spiders/black_bear_diner_us.py
```py
{'atp/brand/Black Bear Diner': 160,
'atp/brand_wikidata/Q4920343': 160,
'atp/category/amenity/restaurant': 160,
'atp/field/country/from_spider_name': 160,
'atp/field/email/missing': 160,
'atp/field/image/missing': 160,
'atp/field/opening_hours/missing': 160,
'atp/field/operator/missing': 160,
'atp/field/operator_wikidata/missing': 160,
'atp/field/twitter/missing': 160,
'atp/item_scraped_host_count/blackbeardiner.com': 160,
'atp/nsi/perfect_match': 160,
'downloader/request_bytes': 618,
'downloader/response_bytes': 38911, …
```
=> Black Bear Diner (160 locations)

locations/spiders/sport_clips_ca.py, locations/spiders/sport_clips_us.py
```py
{'atp/brand/Sport Clips': 36,
'atp/brand_wikidata/Q7579310': 36,
'atp/category/shop/hairdresser': 36,
'atp/item_scraped_host_count/sportclips.ca': 36,
'atp/nsi/perfect_match': 36,
'downloader/request_bytes': 611,
'downloader/response_bytes': 71675,
'elapsed_time_seconds': 2.912451,
'finish_time': datetime.datetime(2024, 9, 7, 23, 32, 17, 290181, …
```
=> Sport Clips CA (36 locations) and US (1830 locations)

locations/spiders/heron_foods_gb.py, locations/storefinders/wordpress_heron_foods_spider.py
I've also tested all `WordpressHeronFoodsSpider` spiders.
=> [Heron Foods GB] Collect opening hours and more attributes

locations/hours.py, locations/spiders/kfc_tr.py, locations/spiders/kfc_us.py
[KFC as toilets operator appeared in NSI](https://github.com/osmlab/name-suggestion-index/commit/d6eabcc91a3080a9ae021cce1e0b73e8bf43942b), so our matching will not assign category automatically anymore.
KFC TR stats:
```json
{
"atp/brand/KFC": 252,
"atp/brand_wikidata/Q524757": 252,
"atp/category/amenity/fast_food": 252,
"atp/cdn/cloudflare/response_count": 255,
"atp/cdn/cloudflare/response_status_count/200": 255,
"atp/field/city/missing": 252,
"atp/field/country/from_spider_name": 252,
"atp/field/email/missing": 252,
"atp/field/image/missing": 252,
"atp/field/lat/missing": 252,
"atp/field/lon/missing": 252,
"atp/field/operator/missing": 252,
"atp/field/operator_wikidata/missing": 252,
"atp/field/phone/missing": 252,
"atp/field/postcode/missing": …
```
=> Add category to KFC shared attributes, Add KFC TR spider

locations/spiders/toyota_au.py, locations/spiders/toyota_eu.py, locations/spiders/toyota_nz.py, locations/spiders/toyota_sacu.py, locations/spiders/toyota_us.py
SACU = South African Customs Union, i.e. ZA, BW, NA, LS, SZ
Also refactor to use shared attributes, except for toyota_us which had been failing, so will be fixed in a separate PR
=> Add Toyota SACU (264 items) and NZ spiders (64 items)

locations/spiders/krispy_kreme_gb.py
Noticed my local one was missing, I save up to go there sometimes.
=> [krispy_kreme_gb] 120 health giving locations

locations/spiders/jd_sports_de.py, locations/spiders/jd_sports_es.py, locations/spiders/jd_sports_fr.py, locations/spiders/jd_sports_ie.py, locations/spiders/jd_sports_it.py, locations/spiders/jd_sports_pt.py
JD sports locations added for Germany, Spain, France, Ireland, Italy, and Portugal.
=> [jd_sports] add locations for de, es, fr, ie, it, pt

locations/spiders/exclusive_books_bw_na_za.py
No coordinates available
```
'atp/brand/Exclusive Books': 44,
'atp/brand_wikidata/Q5419679': 44,
'atp/category/shop/books': 44,
'atp/field/city/missing': 44,
'atp/field/image/missing': 44,
'atp/field/lat/missing': 44,
'atp/field/lon/missing': 44,
'atp/field/opening_hours/missing': 44,
'atp/field/operator/missing': 44,
'atp/field/operator_wikidata/missing': 44,
'atp/field/street_address/missing': 44,
'atp/field/twitter/missing': 44,
'atp/field/website/missing': 44,
'atp/item_scraped_host_count/exclusivebooks.co.za': 44,
'atp/nsi/perfect_match': 44,
```
=> [exclusive_books_bw_na_za] Add spider (44 locations)

locations/spiders/dunns.py, locations/spiders/legit_za.py
Ref #10032
```
'atp/brand/LEGiT': 191,
'atp/brand_wikidata/Q122959274': 191,
'atp/category/shop/clothes': 191,
'atp/field/image/missing': 191,
'atp/field/opening_hours/missing': 191,
'atp/field/operator/missing': 191,
'atp/field/operator_wikidata/missing': 191,
'atp/field/postcode/missing': 15,
'atp/field/street_address/missing': 191,
'atp/field/twitter/missing': 191,
'atp/field/website/missing': 191,
'atp/item_scraped_host_count/amaicdn.com': 191,
'atp/nsi/perfect_match': 191,
```
```
'atp/brand/Dunns': 195,
'atp/brand_wikidata/Q116619823': 195,
'atp/category/shop/clothes': 195, …
```
=> [legit_za] and [dunns] Fix fetching of js, refactor to share code

locations/spiders/clicks.py
It ran when I made it, but not in the latest run, or locally anymore.
```
'atp/brand/Clicks': 933,
'atp/brand_wikidata/Q62563622': 933,
'atp/category/amenity/pharmacy': 933,
'atp/category/multiple': 933,
'atp/cdn/cloudflare/response_count': 937,
'atp/cdn/cloudflare/response_status_count/200': 936,
'atp/field/city/missing': 933,
'atp/field/country/from_reverse_geocoding': 933,
'atp/field/email/missing': 933,
'atp/field/image/missing': 933,
'atp/field/operator/missing': 933,
'atp/field/operator_wikidata/missing': 933,
'atp/field/phone/invalid': 36,
'atp/field/postcode/missing': 933,
'atp/field/street_address/missing': 933, …
```
=> [clicks] Fix spider and fix opening hours (933 locations)

locations/spiders/sos_br.py
=> [SOS Tecnologia e Educação BR] Fix brand

locations/spiders/healthy_planet_ca.py, locations/storefinders/amasty_store_locator.py
Fix https://github.com/alltheplaces/alltheplaces/issues/10285
=> Add Healthy Planet and deal with an edge case in AmastyStoreLocator

locations/spiders/game_gb.py
Fix https://github.com/alltheplaces/alltheplaces/issues/10252
=> Fix Game GB

locations/spiders/cukiernia_sowa_pl.py
=> [cukiernia_sowa_pl] Swap the field extract into street over to street_address

locations/spiders/goldmark_au.py, locations/spiders/goldmark_nz.py
=> Add Goldmark (AU/NZ) (71 stores)

locations/spiders/strandbags_au.py, locations/spiders/strandbags_nz.py
=> Add Strandbags (AU/NZ) (259 stores)

locations/spiders/big_brand_tire_and_service_us.py
=> Add Big Brand Tire & Service (US) (86 stores)

locations/spiders/hyundai_id.py
=> Add Hyundai (ID) (159 dealers)

locations/spiders/albert_cz.py
Fixes #919
GraphQL API is similar to Albert Heijn with some fields having different names.
Opening hours are published for the next 14 days. Not sure if that's what we want as it will probably return closed during holidays.
=> Add Albert CZ (347 locations)

locations/spiders/hyundai_kr.py
=> Add Hyundai (KR) (681 dealers)

locations/dict_parser.py, locations/spiders/hyundai_au.py, locations/spiders/hyundai_kr.py
'atp/brand/Hyundai': 543,
'atp/brand_wikidata/Q55931': 543,
'atp/category/shop/car': 179,
'atp/category/shop/car_parts': 180,
'atp/category/shop/car_repair': 184,
=> Add Hyundai (AU) (543 features)

locations/spiders/hyundai_kr.py, locations/spiders/hyundai_nz.py
'atp/brand/Hyundai': 122,
'atp/brand_wikidata/Q55931': 122,
'atp/category/shop/boat': 15,
'atp/category/shop/car': 29,
'atp/category/shop/car_repair': 44,
'atp/category/shop/truck': 17,
'atp/category/shop/truck_repair': 17,
Fixes #8433
=> Add Hyundai (NZ) (122 features)
