locations/spiders/yard_house.py

```py
{'atp/brand/Yard House': 88,
'atp/brand_wikidata/Q21189156': 88,
'atp/category/amenity/restaurant': 88,
'atp/field/opening_hours/missing': 88,
'downloader/request_bytes': 659,
'downloader/response_bytes': 26655,
'elapsed_time_seconds': 2.323425,
'finish_time': datetime.datetime(2024, 7, 31, 2, 59, 22, 307244, tzinfo=datetime.timezone.utc),
'httpcompression/response_bytes': 248132,
'item_scraped_count': 88, …
```

[YardHouse] New spider (88 locations)

---

locations/spiders/boconcept.py

```py
{'atp/brand/BoConcept': 295,
'atp/brand_wikidata/Q11338915': 295,
'atp/category/shop/furniture': 295,
'atp/closed_poi': 3,
'atp/field/city/missing': 33,
'atp/field/image/missing': 251,
'atp/field/operator/missing': 295,
'atp/field/operator_wikidata/missing': 295,
'atp/field/phone/invalid': 21,
'atp/field/postcode/missing': 51,
'atp/field/state/missing': 219,
'atp/field/twitter/missing': 295,
'atp/field/website/missing': 180,
'atp/nsi/perfect_match': 295,
'downloader/request_bytes': 353, …
```

[Boconcept] New spider (295 items)

---

locations/spiders/pandora.py

```
{'atp/brand/Pandora': 6472,
'atp/brand_wikidata/Q2241604': 6472,
'atp/category/shop/jewelry': 6472,
'atp/field/country/from_reverse_geocoding': 2959,
'atp/field/email/missing': 6472,
'atp/field/image/missing': 6472,
'atp/field/opening_hours/missing': 1874,
'atp/field/operator/missing': 6472,
'atp/field/operator_wikidata/missing': 6472,
'atp/field/phone/invalid': 156,
'atp/field/phone/missing': 564,
'atp/field/postcode/missing': 397,
'atp/field/state/missing': 3514,
'atp/field/twitter/missing': 6472,
'atp/item_scraped_host_count/maps.pandora.net': 6472,
'atp/nsi/perfect_match': 6472,
'downloader/request_bytes': 714, …
```

[Pandora] Refactor spider using RioSeoSpider to cover more countries, missing in the sitemap (6472 locations)

---

locations/spiders/carbon_health_us.py

```py
{'atp/brand/Carbon Health': 116,
'atp/brand_wikidata/Q110076263': 116,
'atp/category/amenity/clinic': 116,
'atp/category/multiple': 116,
'atp/field/country/from_spider_name': 116,
'atp/field/email/missing': 116,
'atp/nsi/perfect_match': 116,
'atp/operator/Carbon Health': 116,
'atp/operator_wikidata/Q110076263': 116,
'downloader/request_bytes': 739,
'downloader/response_bytes': 77852,
'elapsed_time_seconds': 2.345416,
'finish_time': …
```

[CarbonHealthUS] New spider(116 locations)

---

locations/spiders/jb_hi_fi_au.py
locations/spiders/jb_hifi_au.py

```py
{'atp/brand/JB Hi-Fi': 148,
'atp/brand/JB Hi-Fi Home': 63,
'atp/brand_wikidata/Q3310113': 211,
'atp/category/shop/electronics': 211,
'atp/field/country/from_website_url': 15,
'atp/field/email/missing': 211,
'atp/field/image/missing': 211,
'atp/field/operator/missing': 211,
'atp/field/operator_wikidata/missing': 211,
'atp/field/twitter/missing': 211,
'atp/nsi/perfect_match': 211,
'downloader/request_bytes': 1133,
'downloader/response_bytes': 61570,
'elapsed_time_seconds': 4.30783, …
```

[JbHiFiAU] Rename spider, filter non-stores, move name to branch

---

locations/spiders/cb2.py
locations/spiders/crateandbarrel.py

```py
{'atp/brand/CB2': 23,
'atp/brand_wikidata/Q113164236': 23,
'atp/category/shop/furniture': 23,
'downloader/request_bytes': 24218,
'downloader/request_count': 41,
'downloader/request_method_count/GET': 41,
'downloader/response_bytes': 4325930,
'downloader/response_count': 41,
'downloader/response_status_count/200': 41,
'dupefilter/filtered': 30,
'elapsed_time_seconds': 49.773888,
'finish_time': datetime.datetime(2024, 8, 3, 3, 58, 59, 624257, tzinfo=datetime.timezone.utc),
'httpcompression/response_bytes': 23534817,
'httpcompression/response_count': 41,
'item_scraped_count': 23, …
```

[Cb2, Crateandbarrel] New spider for spinoff brand (23 locations), and tweak Crateandbarrel tagging

---

locations/spiders/blyzenko_ua.py

Fix #9111
This API does list "services", but I didn't go after them for the moment as it was ambiguous if "Coffee" meant cafe, or they sell coffee.

Add Blyzenko (UA)

---

locations/spiders/urban_plates.py
locations/spiders/urban_plates_us.py

```py
{'atp/brand/Urban Plates': 19,
'atp/brand_wikidata/Q96413021': 19,
'atp/category/amenity/fast_food': 19,
'atp/nsi/brand_missing': 19,
'downloader/request_bytes': 715,
'downloader/response_bytes': 4601,
'elapsed_time_seconds': 1.792028, …
```

[UrbanPlatesUS] New spider (19 locations)

---

ci/run_all_spiders.sh

Fixes #4255
Fixes #3657 
This adds code to the weekly spider run that writes S3 redirects for each spider's output geojson and the collected zip and parquet outputs.

Create 'latest' redirects for spider output

---

locations/spiders/le_pain_quotidien.py

```py
{'atp/brand/Le Pain Quotidien': 177,
'atp/brand_wikidata/Q2046903': 177,
'atp/category/amenity/cafe': 177,
'atp/field/email/missing': 177,
'atp/field/image/missing': 177,
'atp/field/operator/missing': 177,
'atp/field/operator_wikidata/missing': 177,
'atp/field/state/from_reverse_geocoding': 49,
'atp/field/state/missing': 128,
'atp/field/twitter/missing': 177,
'atp/item_scraped_host_count/api.obenan.com': 177,
'atp/nsi/perfect_match': 177,
'downloader/request_bytes': 792,
'downloader/response_bytes': 27128, …
```

[LePainQuotidien] New spider (177 locations) (fixes #9158)

---

locations/spiders/the_athletes_foot.py

Fix https://github.com/alltheplaces/alltheplaces/issues/7562
> The Athlete’s Foot has over 400 stores in over 24 countries around the globe. You can find a TAF store in almost every continent. From Atlanta USA to Copenhagen Denmark all the way to Jakarta Indonesia, we are there to serve and inspire you.
So I went for the whole world point files.

Add The Athelete's Foot

---

locations/spiders/big_o_tires_ca.py
locations/spiders/big_o_tires_us.py

```py
{'atp/brand/Big O Tires': 464,
'atp/brand_wikidata/Q4906085': 464,
'atp/category/shop/tyres': 464,
'atp/field/country/from_spider_name': 464,
'atp/field/image/missing': 464,
'atp/field/operator/missing': 464,
'atp/field/operator_wikidata/missing': 464,
'atp/field/twitter/missing': 464,
'atp/item_scraped_host_count/www.bigotires.com': 898,
'atp/nsi/perfect_match': 464,
'downloader/request_bytes': 390840,
'downloader/request_count': 477,
'downloader/request_method_count/POST': 476,
'downloader/response_bytes': 1082690,
'downloader/response_count': 477,
'downloader/response_status_count/200': 477,
'elapsed_time_seconds': 577.376104,
'finish_time': …
```

Big O Tires (473 locations) (fix #9001)

---

locations/categories.py
locations/spiders/pick_n_pay.py

Follow up to #7221, link to #6052 
All brand types should now correctly be dealt with and all have appropriate wikidata, having checked lots of Pick n Pay documentation as well as local knowledge.
Province field had been returning dict of code and name for many locations before.
Ping @michaelgrahamevans and maybe @Firefishy as you had interest in the previous PR.

Update Pick n Pay spider brands, wikidata and province fixes

---

locations/spiders/bash_za.py

Bash spider has been broken for a few runs, it needed a new hash for the graphql query.
Link #5105 
```
'atp/brand/@Home': 103,
'atp/brand/@Home Livingspace': 23,
'atp/brand/American Swiss': 239,
'atp/brand/Archive': 34,
'atp/brand/Coricraft': 46,
'atp/brand/Dial-a-Bed': 81,
'atp/brand/Duesouth': 3,
'atp/brand/Exact': 363,
'atp/brand/Fabiani': 78,
'atp/brand/Foschini': 265,
'atp/brand/G-Star RAW': 32,
'atp/brand/Jet': 489,
'atp/brand/Markham': 377,
'atp/brand/Next': 1,
'atp/brand/Relay Jeans': 129,
'atp/brand/Renegade Fashion Outlet': 66,
'atp/brand/SODA Bloc': 4,
'atp/brand/Sportscene': 395,
'atp/brand/Sterns': 192,
'atp/brand/The Bed Store': 26,
'atp/brand/The FIX': 221,
'atp/brand/The Scene': 1,
'atp/brand/The Sneaker Factory': 236,
'atp/brand/Totalsports': 341,
'atp/brand/Volpes': 58, …
```

Fix bash_za spider

---

locations/spiders/kirklands.py

Last few weekly runs are 0 items; as their site is cactus:
I'm inclined to leave the spider in place; assuming they fix it.

StructuredDataSpiders - Kirklands - Drop usage of deprecated inspect_item 

---

locations/spiders/crocs_eu.py
locations/storefinders/aheadworks.py
locations/storefinders/locally.py

pre_process - None of the child spiders implement it; so safe to rename.
post_process - Only used by one spider

Storefinders - Locally - Rename pre_process method, slightly refactor post process method

---

locations/spiders/migros_tr.py

Migros is one of the largest supermarket chains in Turkey.
Wikidata: https://www.wikidata.org/wiki/Q1754510
A note: Turkish provinces (*il*) are not distributed as part of the `geonamescache`. The cities provided in `geonamescache` is a mixture of both provinces and districts (*ilçe*) and there is no way to distinguish them, so I added a list of provinces in the spider (the API is queried by province names). I would prefer to move them to a seperate file but I don't know where to move them.

Add migros_tr spider (>3000 locations across Turkey)

---

locations/dict_parser.py
locations/spiders/pep.py

This appears to cover South Africa, Lesotho, eSwatini, Namibia and Botswana.
I only very recently updated NSI with separate wikidata for Pep Cell and Pep Home, so they are not yet being matched.
```
'atp/brand/Pep': 1646,
'atp/brand/Pep Cell': 551,
'atp/brand/Pep Home': 311,
'atp/brand_wikidata/Q128802022': 311,
'atp/brand_wikidata/Q128802743': 551,
'atp/brand_wikidata/Q7166182': 1646,
'atp/category/missing': 2256,
'atp/category/shop/clothes': 252,
'atp/field/city/missing': 2508,
'atp/field/country/from_reverse_geocoding': 2508,
'atp/field/email/missing': 2508,
'atp/field/image/missing': 2508,
'atp/field/operator/missing': 2508,
'atp/field/operator_wikidata/missing': 2508,
'atp/field/phone/invalid': 166,
'atp/field/postcode/missing': 2508, …
```

Pep spider (Southern Africa) (2508 locations)

---

locations/spiders/gratis_tr.py

Gratis is a personal care store with 700 locations across Turkey.
NSI: https://nsi.guide/index.html?t=brands&k=shop&v=cosmetics&tt=gratis
Wikidata: https://www.wikidata.org/wiki/Q28605813
The sitemap of [Gratis](https://www.gratis.com) references each store page; however, there is no structured data on individual store's pages and even latitude and longitude is not on those pages. I used an API on the ["Mağazalarımız" (Our Stores)](https://www.gratis.com/magazalarimiz) page, which lists all stores.

Add gratis_tr spider (~700 locations across Turkey)

---

locations/commands/duplicate_wikidata.py
locations/commands/nsi.py

Some light changes:
- support writing an output report in JSON format as an option
- have an option to report on wikidata duplicates across spider directories

extend duplicate_wikidata command, multi spider directory support

---

locations/exporters/osm.py

This is the exporter only used by me to load data into JOSM. It's not for production and it's a lot more complainy about not receiving string=string, I like this. However it is sometimes hard to identify field is causing the issue.

[OSM Exporter] Be verbose when receving none string values

---

locations/spiders/subway_qa.py
locations/spiders/subway_th.py

Added QA locations and fixed address for Subway Worldwide Spider.
Stats for `subway_qa`:
```
{'atp/brand/Subway': 31,
'atp/brand_wikidata/Q244457': 31,
'atp/category/amenity/fast_food': 31,
'atp/field/opening_hours/missing': 31,
'atp/field/phone/missing': 31,
'atp/field/state/missing': 31,
'atp/field/website/missing': 31,
'atp/item_scraped_host_count/locator-svc.subway.com': 155,
'atp/nsi/cc_match': 31,
'downloader/request_bytes': 7523,
'downloader/response_bytes': 1094292,
'downloader/response_count': 6, …
```

[SubwayQA] Add spider (31 locations)

---

locations/spiders/e_leclerc.py

This PR rectifies the Leclerc Drive category from supermarket to outpost

[E Leclerc] fix category 'Drive'

---

DATA_FORMAT.md
locations/pipelines/phone_clean_up.py

I spotted in #9531 that multiple phone numbers are being dealt with inconsistently. The split requires `; ` but the merge uses only `;` so I'm making the whitespace optional and updating the documentation for phone numbers to match what is happening.

Documentation: multiple phone numbers and phone cleaning

---

locations/middlewares/track_sources.py

As pointed out by https://github.com/alltheplaces/alltheplaces/pull/9075#discussion_r1703102202 this is now the first "pipeline", so any errors regarding a lack of `extras` would happen here. I don't think this is a real issue, a spider would have to go out of it's way to not have `extras`, but may as well be safer.

[Core] Make TrackSourcesMiddleware safer

---

locations/spiders/petrol_bg.py

All items are missing `amenity=fuel` in the latest run. This was not the case in the preview in #6033.

Apply `amenity=fuel` category for petrol_bg

---

locations/spiders/wingstop_mx.py

@iandees - would you prefer to change the name of wingstop spider to wingstop_us?  or just leave as is?
```
{'atp/brand/Wingstop': 114,
'atp/brand_wikidata/Q8025339': 114,
'atp/category/amenity/fast_food': 114,
'atp/field/image/missing': 114,
'atp/field/opening_hours/missing': 114,
'atp/field/operator/missing': 114,
'atp/field/operator_wikidata/missing': 114,
'atp/field/twitter/missing': 114,
'atp/field/website/missing': 113,
'atp/item_scraped_host_count/wingstopmexico.com': 114,
'atp/nsi/perfect_match': 114,
'downloader/request_bytes': 700, …
```

[wingstop_mx] add spider (114 locations)

---

locations/spiders/ok_foods.py

Some of the items are not getting a clean country code and are keeping the value from the source, e.g. "SOUTH AFRICA", but I can't tell why.
```
'atp/brand/Megasave': 13,
'atp/brand/OK Express': 102,
'atp/brand/OK Foods': 135,
'atp/brand/OK Grocer': 65,
'atp/brand/OK Liquor': 117,
'atp/brand/OK Minimark': 126,
'atp/brand/OK Urban': 1,
'atp/brand/OK Value': 1,
'atp/brand/President Hyper': 3,
'atp/brand/Sentra': 12,
'atp/brand_wikidata/Q116520377': 217,
'atp/brand_wikidata/Q116520407': 102,
'atp/brand_wikidata/Q116520424': 117,
'atp/brand_wikidata/Q116520457': 126,
'atp/brand_wikidata/Q116520541': 13,
'atp/category/shop/alcohol': 117,
'atp/category/shop/convenience': 230,
'atp/category/shop/supermarket': 215,
'atp/category/shop/wholesale': 13,
```

OK Foods spider (ZA, SZ, NA) (576 locations)

---

locations/spiders/road_runner_sports_us.py

```py
{'atp/brand/Road Runner Sports': 48,
'atp/brand_wikidata/Q113494713': 48,
'atp/category/shop/shoes': 48,
'atp/field/country/from_spider_name': 48,
'atp/field/email/missing': 48,
'atp/field/image/missing': 48,
'atp/field/operator/missing': 48,
'atp/field/operator_wikidata/missing': 48,
'atp/field/twitter/missing': 48,
'atp/item_scraped_host_count/maps.stores.roadrunnersports.com': 48,
'atp/nsi/perfect_match': 48,
'downloader/request_bytes': 1181,
'downloader/response_bytes': 12852,
'elapsed_time_seconds': 3.170044,
'finish_time': datetime.datetime(2024, 8, 16, 0, …
```

[RoadRunnerSportsUS] New spider (48 locations)

---

locations/categories.py
locations/spiders/santander_us.py

```py
{'atp/brand/Santander': 1902,
'atp/brand_wikidata/Q5835668': 1902,
'atp/category/amenity/atm': 1497,
'atp/category/amenity/bank': 401,
'atp/category/office/financial_advisor': 4,
'atp/field/email/missing': 1902,
'atp/field/image/missing': 1902,
'atp/field/opening_hours/missing': 336,
'atp/field/operator/missing': 405,
'atp/field/operator_wikidata/missing': 405,
'atp/field/twitter/missing': 1902,
'atp/item_scraped_host_count/maps.locations.santanderbank.com': 1902,
'atp/nsi/cc_match': 1898,
'atp/nsi/match_failed': 4,
'atp/operator/Santander': 1497,
'atp/operator_wikidata/Q5835668': 1497,
'downloader/request_bytes': 1182,
'downloader/response_bytes': 466358, …
```

[SantanderUS] New spider (1902 locations)

---

locations/spiders/our_airports.py

`ele` is unusually defined as meters only, no option for us adding units like other OSM fields. However we weren't adding units anyway, so we were lying.

[Our Airports] Fix ele

---

locations/categories.py
locations/spiders/icebolethu_za.py

There's nothing I can see to use for `ref`, but I don't seem to be able to leave it out. Using the name seems wrong, so what is a better option?
Website was messier than it first appeared, so some items/properties get dropped.
```
'atp/brand/Icebolethu Funerals': 132,
'atp/brand_wikidata/Q122594408': 132,
'atp/category/amenity/mortuary': 29,
'atp/category/shop/funeral_directors': 103,
'atp/field/city/missing': 132,
'atp/field/country/from_spider_name': 132,
'atp/field/email/missing': 132,
'atp/field/image/missing': 132,
'atp/field/opening_hours/missing': 132,
'atp/field/operator/missing': 132,
'atp/field/operator_wikidata/missing': 132,
'atp/field/postcode/missing': 132, …
```

Add IcebolethuZASpider (132 locations)

---

locations/spiders/medirite_za.py
locations/spiders/usave_za.py

```
'atp/brand/Usave': 423,
'atp/brand_wikidata/Q115696368': 423,
'atp/category/shop/supermarket': 423,
'atp/field/email/missing': 423,
'atp/field/image/missing': 423,
'atp/field/operator/missing': 423,
'atp/field/operator_wikidata/missing': 423,
'atp/field/twitter/missing': 423,
'atp/field/website/missing': 423,
'atp/item_scraped_host_count/www.usave.co.za': 423,
'atp/nsi/cc_match': 423,
```

Usave ZA spider (423 locations)

---

locations/spiders/lewis_stores.py

* Ignore closed stores
* Postcodes outside of ZA appeared to be placeholders (9000 and 9999).
* Handle multiple phone numbers.
* Opening hours are a bit messy in the source data, but are now handled.
Follow up to #9566

Lewis stores opening hours and fixes

---

locations/spiders/cum_books_za.py

```
'atp/brand/CUM Books': 35,
'atp/brand_wikidata/Q128930625': 35,
'atp/category/shop/books': 35,
'atp/field/city/missing': 35,
'atp/field/country/from_spider_name': 35,
'atp/field/opening_hours/missing': 35,
'atp/field/phone/missing': 35,
'atp/field/website/missing': 35,
'atp/item_scraped_host_count/storage.googleapis.com': 35,
'atp/nsi/perfect_match': 35,
```

Add CUM Books ZA Spider (35 locations)

---

locations/json_blob_spider.py
locations/spiders/banca_sella_it.py

Saw what @CloCkWeRX had done with the `JSONBlobSpider` and thought we could default `extract_json` to treating the body response as JSON which is a regular pattern and then having an optional single level key to get the location array which is also a common pattern leading into the `DictParser` dance.

[banca_sella_it] new spider (282 locations)

---

locations/spiders/location_bank_company.py
locations/storefinders/location_bank.py

Location Bank are used by Nandos in some countries (#9531), as well as African Bank (#9668) so I will plan to refactor those after this has been merged.
Location Bank only have 5 office locations, so I have not added them to NSI.
There are then at least 6 more spiders to be added that use Location Bank that I have found so far.

Location Bank storefinder and spider

---

locations/categories.py
locations/spiders/guild_mortgage_us.py
locations/spiders/standard_bank_mw.py
locations/spiders/standard_bank_za.py
locations/spiders/standard_bank_zw.py

Fixes #825
These are all the countries I can see that use this format and I can get to work with searches. More countries may be possible however. Although, there are also some badly located items which are meant to be in Uganda but show up in Egypt.
ZA:
```
'atp/brand/Standard Bank': 2299,
'atp/brand_wikidata/Q1576610': 2299,
'atp/category/amenity/atm': 1830,
'atp/category/amenity/bank': 469,
'atp/field/email/missing': 2299,
'atp/field/image/missing': 2299,
'atp/field/name/missing': 1830,
'atp/field/opening_hours/missing': 1830,
'atp/field/operator/missing': 469,
'atp/field/operator_wikidata/missing': 469,
'atp/field/phone/missing': 2299,
'atp/field/postcode/missing': 40,
'atp/field/street_address/missing': 66,
'atp/field/twitter/missing': 2299, …
```

Standard Bank Spider (ZA, MW, ZW)

---

locations/categories.py
locations/spiders/peoples_bank_us.py
locations/storefinders/rio_seo.py

```py
{'atp/brand/Peoples Bank': 151,
'atp/brand_wikidata/Q65716607': 151,
'atp/category/amenity/atm': 16,
'atp/category/amenity/bank': 132,
'atp/category/office/insurance': 3,
'atp/field/country/from_spider_name': 151,
'atp/field/email/missing': 151,
'atp/field/image/missing': 151,
'atp/field/name/missing': 16,
'atp/field/operator/missing': 135,
'atp/field/operator_wikidata/missing': 135,
'atp/field/twitter/missing': 151,
'atp/item_scraped_host_count/maps.locations.peoplesbancorp.com': 151,
'atp/nsi/match_failed': 151,
'atp/operator/Peoples Bank': 16,
'atp/operator_wikidata/Q65716607': 16,
'atp/peoples_bank_us/unmapped_type/': 1,
'downloader/request_bytes': 1166, …
```

[PeoplesBankUS] New spider (151 locations)

---

locations/spiders/sasol_za.py

```
'atp/brand/Sasol': 397,
'atp/brand_wikidata/Q905998': 397,
'atp/category/amenity/fuel': 397,
'atp/field/country/from_spider_name': 397,
'atp/field/email/missing': 397,
'atp/field/image/missing': 397,
'atp/field/opening_hours/invalid': 77,
'atp/field/operator/missing': 397,
'atp/field/operator_wikidata/missing': 397,
'atp/field/street_address/missing': 397,
'atp/field/twitter/missing': 397,
'atp/item_scraped_host_count/locator.sasol.com': 397,
'atp/nsi/cc_match': 397,
```

Add Sasol ZA spider (397 locations)

---

locations/spiders/mr_price.py

Awaiting NSI update for categories.
Obviously, there aren't really locations in the middle of the Atlantic, but they also show that on their own website. Stores seem mostly close to their correct location other than the outliers.
```
'atp/brand/Mr Price': 656,
'atp/brand/Mr Price Home': 234,
'atp/brand/Mr Price Sport': 184,
'atp/brand_wikidata/Q129561257': 656,
'atp/brand_wikidata/Q129561262': 184,
'atp/brand_wikidata/Q129561270': 234,
'atp/category/missing': 1074,
'atp/field/city/missing': 72,
'atp/field/country/from_spider_name': 72,
'atp/field/email/missing': 1074,
'atp/field/image/missing': 1074,
'atp/field/lat/invalid': 4, …
```

Mr Price Group spider (1074 locations)

---

locations/spiders/storage_king_au.py
locations/spiders/storage_king_au_nz.py

Fixes #8506 Fixes #8507
```python
{'atp/brand/Storage King': 198,
'atp/brand_wikidata/Q114353097': 198,
'atp/category/shop/storage_rental': 198,
'atp/field/branch/missing': 64,
'atp/field/image/missing': 198,
'atp/field/operator/missing': 198,
'atp/field/operator_wikidata/missing': 198,
'atp/field/twitter/missing': 198,
'atp/item_scraped_host_count/www.storageking.co.nz': 24,
'atp/item_scraped_host_count/www.storageking.com.au': 176,
'atp/nsi/perfect_match': 198,
'downloader/request_bytes': 665,
'downloader/response_bytes': 141014, …
```

[StorageKing AU NZ] Add spider

---

locations/categories.py
locations/spiders/mkrf_ru.py

There are few locations that require correction, but in general this is very good dataset.
Stats for parks only:
```json
{
"atp/category/leisure/park": 502,
"atp/field/branch/missing": 502,
"atp/field/brand/missing": 502,
"atp/field/brand_wikidata/missing": 502,
"atp/field/city/missing": 502,
"atp/field/country/from_spider_name": 502,
"atp/field/email/missing": 150,
"atp/field/opening_hours/missing": 18,
"atp/field/operator/missing": 502,
"atp/field/operator_wikidata/missing": 502,
"atp/field/phone/invalid": 4,
"atp/field/phone/missing": 130,
"atp/field/postcode/missing": 502,
"atp/field/state/missing": 502,
"atp/field/street_address/missing": 78,
"atp/field/twitter/missing": 502,
"atp/field/website/invalid": 26,
"atp/field/website/missing": 140, …
```

[mkrf_ru] add parks (502 locations)

---

locations/spiders/total_energies.py

The intent was just to map a bit more fuels, but I ended up changing from multiple `apply_yes_no` to looping over SERVICES_MAPPING dict.
<details><summary> Stats </summary>
```json
{
"atp/brand/AS 24": 494,
"atp/brand/Agip": 417,
"atp/brand/Aral": 2314,
"atp/brand/Avia": 699,
"atp/brand/BP": 2349,
"atp/brand/Cepsa": 3067,
"atp/brand/Dyneff": 113,
"atp/brand/Elan": 323,
"atp/brand/Esso": 533,
"atp/brand/Filoil": 103,
"atp/brand/Gulf": 107,
"atp/brand/MOL": 746,
"atp/brand/OMV": 15,
"atp/brand/Shell": 202,
"atp/brand/Slovnaft": 188,
"atp/brand/Total Access": 775,
"atp/brand/TotalEnergies": 11696,
"atp/brand/TotalEnergies Express": 170,
"atp/brand/TotalErg": 1791,
"atp/brand/Westfalen": 258,
"atp/brand_wikidata/Q110716465": 202,
"atp/brand_wikidata/Q1411209": 258, …
```

[total_energies] use services mapping, map more fuels

---

locations/spiders/caliber_collision_us.py

```py
{'atp/brand/Caliber Collision': 2477,
'atp/brand_wikidata/Q109329782': 2477,
'atp/category/shop/car_repair': 2477,
'atp/field/city/missing': 76,
'atp/field/country/from_spider_name': 2477,
'atp/field/email/missing': 498,
'atp/field/image/missing': 2477,
'atp/field/lat/missing': 118,
'atp/field/lon/missing': 118,
'atp/field/opening_hours/missing': 91,
'atp/field/operator/missing': 2477,
'atp/field/operator_wikidata/missing': 2477,
'atp/field/phone/missing': 177,
'atp/field/postcode/missing': 203,
'atp/field/state/missing': 76,
'atp/field/street_address/missing': 76,
'atp/field/twitter/missing': 2477,
'atp/field/website/invalid': 76,
'atp/item_scraped_host_count/www.caliber.com': 2477,
'atp/nsi/perfect_match': 2477, …
```

New spider: Caliber Collision (2477 locations)

---

locations/spiders/jasons_deli.py

Opening Hours were not added as they were inconsistent from the website and google.
````
{"atp/brand/Jason's Deli": 244,
'atp/brand_wikidata/Q16997641': 244,
'atp/category/amenity/restaurant': 244,
'atp/field/branch/missing': 244,
'atp/field/country/from_reverse_geocoding': 244,
'atp/field/email/missing': 244,
'atp/field/image/missing': 244,
'atp/field/opening_hours/missing': 244,
'atp/field/operator/missing': 244,
'atp/field/operator_wikidata/missing': 244,
'atp/field/twitter/missing': 244,
'atp/field/website/missing': 244,
'atp/item_scraped_host_count/jdapi.jasonsdeli.com': 244,
'atp/nsi/perfect_match': 244,
'downloader/request_bytes': 1027, …
```

[Jasons_deli] Fix spider (244 locations)

---

locations/spiders/bambu.py

```py
{'atp/brand/Bambu': 66,
'atp/brand_wikidata/Q83437245': 66,
'atp/category/amenity/cafe': 66,
'atp/field/email/invalid': 23,
'atp/field/image/missing': 66,
'atp/field/operator/missing': 66,
'atp/field/operator_wikidata/missing': 66,
'atp/field/street_address/missing': 66,
'atp/field/twitter/missing': 66,
'atp/item_scraped_host_count/www.drinkbambu.com': 66,
'atp/nsi/perfect_match': 66,
'downloader/request_bytes': 2076,
'downloader/response_bytes': 52569, …
```

New spider: Bambu (66 locations)

---

locations/spiders/engen.py
locations/spiders/engen_quickshop.py

Quickshop is Engen's own brand convenience store, so this is basically first party information for the locations
Engen: Move name to branch and also collect AdBlue availability

Add EngenQuickshopSpider and refine EngenSpider

---

locations/spiders/lilly_rs.py

```
{'atp/brand/Lilly': 236,
'atp/brand_wikidata/Q111764460': 236,
'atp/category/shop/chemist': 236,
'atp/field/country/from_spider_name': 236,
'atp/field/email/missing': 236,
'atp/field/image/missing': 236,
'atp/field/operator/missing': 236,
'atp/field/operator_wikidata/missing': 236,
'atp/field/postcode/missing': 236,
'atp/field/state/missing': 236,
'atp/field/twitter/missing': 236,
'atp/field/website/missing': 236,
'atp/item_scraped_host_count/www.lilly.rs': 236,
'atp/nsi/cc_match': 236,
'downloader/request_bytes': 786,
'downloader/response_bytes': 29860, …
```

[lilly_rs] Fix Spider (236 locations)

---

locations/spiders/fnb_atm_za.py
locations/spiders/fnb_banks_za.py

Fixes #823 and fixes #824
All of this feels very messy, not least having to do `response.xpath('.//p[@class="      "]')`, and the fact that it actually returns useful information.
Also, a total hack of search results for the branches, which is strange since the ATM search seems to work just fine by provinces. Fortunately, scrapy's deduplication of requests makes it not as bad as it might seem at first.
```
'atp/brand/FNB': 4654,
'atp/brand_wikidata/Q3072956': 4654,
'atp/category/amenity/atm': 4654,
'atp/field/city/missing': 4654,
'atp/field/country/from_spider_name': 4654,
'atp/field/email/missing': 4654,
'atp/field/image/missing': 4654,
'atp/field/name/missing': 4654,
'atp/field/opening_hours/missing': 4654, …
```

FNB (ZA) ATMs and branches

---

locations/spiders/porsche.py
locations/spiders/porsche_north_america.py

<details><summary>Canada Stats</summary>
```python
{'atp/brand/Porsche': 23,
'atp/brand_wikidata/Q40993': 23,
'atp/category/shop/car': 23,
'atp/field/state/from_reverse_geocoding': 23,
'atp/item_scraped_host_count/configurator.porsche.com': 278,
'atp/nsi/cc_match': 23,
'downloader/request_bytes': 37642,
'downloader/request_count': 103,
'downloader/request_method_count/GET': 103,
'downloader/response_bytes': 385419,
'downloader/response_count': 103,
'downloader/response_status_count/200': 103,
'elapsed_time_seconds': 124.036028, …
```

[porsche] Added Spider for USA & CAN (930 items)

---

locations/spiders/lees_sandwiches_us.py

```py
{"atp/brand/Lee's Sandwiches": 65,
'atp/brand_wikidata/Q6512823': 65,
'atp/category/amenity/fast_food': 65,
'atp/field/website/missing': 64,
'atp/geo_search/hits': 28,
'atp/geo_search/max_features_returned': 36,
'atp/geo_search/misses': 197,
'atp/item_scraped_host_count/leesandwiches.com': 187,
'downloader/request_bytes': 97923,
'downloader/request_count': 225,
'downloader/request_method_count/POST': 225,
'downloader/response_bytes': 259815,
'downloader/response_count': 225, …
```

Add Lee's Sandwiches spider (65 locations)

---

locations/spiders/capitec_bank_za.py

It was set to `no_refs` because atms have a ref, but branches don't. However this meant that duplicates were not being dropped. So I've used a dummy ref from the name for the branches, I hope that's a reasonable compromise.
Also switch to JsonBlobSpider while I'm there.
This is using the 48km radius for lat, long points but I also did a test with 24km radius.
48km:
```
'atp/brand/Capitec Bank': 3611,
'atp/brand_wikidata/Q5035822': 3611,
'atp/category/amenity/atm': 2975,
'atp/category/amenity/bank': 636,
'atp/cdn/cloudflare/response_count': 262,
```
24km:
```
'atp/brand/Capitec Bank': 4302,
'atp/brand_wikidata/Q5035822': 4302,
'atp/category/amenity/atm': 3524,
'atp/category/amenity/bank': 778,
'atp/cdn/cloudflare/response_count': 964,
```
So the 700 extra requests get about 700 extra …

Deduplicate capitec_bank_za

---

locations/spiders/fishaways_za.py

As noted in #10045, there does not seem to be a consistent key for branch in YextSearchSpiders, so it needs to be done on an individual basis

Collect branch for fishaways_za

---

locations/spiders/l_and_l_hawaiian_barbecue_us.py

```py
{'atp/brand/L&L Hawaiian Barbecue': 246,
'atp/brand/Mixplate': 3,
'atp/brand_wikidata/Q6455441': 249,
'atp/category/amenity/fast_food': 249,
'atp/field/country/from_spider_name': 247,
'atp/field/email/missing': 249,
'atp/field/image/missing': 249,
'atp/field/operator/missing': 249,
'atp/field/operator_wikidata/missing': 249,
'atp/field/twitter/missing': 249,
'atp/item_scraped_host_count/www.hawaiianbarbecue.com': 249,
'atp/nsi/match_failed': 249,
'downloader/request_bytes': 650, …
```

Add spider for L&L Hawaiian Barbecue (249 locations)

---

locations/spiders/hungry_lion_ao.py
locations/spiders/hungry_lion_bw.py
locations/spiders/hungry_lion_na.py
locations/spiders/hungry_lion_za.py
locations/spiders/hungry_lion_zm.py
locations/spiders/pie_city_za.py
locations/spiders/tiger_wheel_and_tyre_za.py
locations/storefinders/go_review.py

Such store finder pages have something like `https://hlinfo.goreview.co.za/store-locator/store-information` embedded in a the page and an icon on that page says "Powered by Social Places".
Fixes #9778

Add GoReviewSpider storefinder and HungryLionZASpider and refactor existing spiders

---

locations/items.py
locations/storefinder_detector.py
locations/storefinders/storefrontgateway.py

Part of #10063
```
ubuntu@codespaces-dc76c9:/workspaces/alltheplaces$ pipenv run scrapy sf https://www.saveonfoods.com/
from locations.storefinders.storefrontgateway import StorefrontgatewaySpider
class SaveOnFoodsCASpider(StorefrontgatewaySpider):
name = "saveonfoods_ca"
item_attributes = {
"brand_wikidata": "Q7427974",
"brand": "Save-On-Foods",
}
start_urls = [
"https://storefrontgateway.saveonfoods.com/api/",
]
```
Fixes bug with GeneratedSpider and new extras pipeline.

Autodetect storefrontgateway

---

locations/spiders/tesla.py

User agent added to get the response with desired data. Without this response is not reachable. Also tried `playwright`, but didn't work. 
Many POIs have [response](https://www.tesla.com/cua-api/tesla-location?translate=en_US&usetrt=true&id=cnsc10155)  with garbage text (error message) `Error: 400` appended, cleaned to fix the JSON decode error which was resulting in loss of POIs count. 
Note: `downloader/response_status_count/500': 1401` : It looks these are not random but are specific responses with 500 error [page](https://www.tesla.com/cua-api/tesla-location?translate=en_US&usetrt=true&id=cnsc9070).
```
{'atp/brand/Tesla': 1139,
'atp/brand/Tesla Supercharger': 6163,
'atp/brand_wikidata/Q17089620': 6163,
'atp/brand_wikidata/Q478214': 1139,
'atp/category/amenity/charging_station': 6163, …
```

[Tesla] Fix spider

---

locations/spiders/bluff_meat_supply_za.py

```
'atp/brand/Bluff Meat Supply': 25,
'atp/brand_wikidata/Q116981518': 25,
'atp/category/shop/butcher': 25,
'atp/field/postcode/missing': 24,
'atp/field/street_address/missing': 25,
'atp/field/website/missing': 25,
'atp/item_scraped_host_count/bluffmeatsupply.co.za': 25,
'atp/nsi/perfect_match': 25,
```

Add BluffMeatSupplyZASpider

---

locations/spiders/bargain_books_za.py

No coordinates, but good addresses, as well as opening hours
```
'atp/brand/Bargain Books': 86,
'atp/brand_wikidata/Q116741024': 86,
'atp/category/shop/books': 86,
'atp/field/city/missing': 86,
'atp/field/country/from_spider_name': 86,
'atp/field/lat/missing': 86,
'atp/field/lon/missing': 86,
'atp/field/postcode/missing': 86,
'atp/field/street_address/missing': 86,
'atp/field/website/missing': 86,
'atp/item_scraped_host_count/www.bargainbooks.co.za': 86,
'atp/nsi/perfect_match': 86,
```

Add BargainBooksZASpider

---

locations/spiders/paris_baguette_kr.py

```py
{'atp/brand/파리바게뜨': 3511,
'atp/brand_wikidata/Q62605260': 3511,
'atp/category/shop/bakery': 3511,
'atp/field/city/missing': 3511,
'atp/field/country/from_spider_name': 3511,
'atp/field/email/missing': 3511,
'atp/field/image/missing': 3511,
'atp/field/lat/missing': 13,
'atp/field/lon/missing': 13,
'atp/field/opening_hours/missing': 3511,
'atp/field/operator/missing': 3511,
'atp/field/operator_wikidata/missing': 3511,
'atp/field/phone/missing': 43,
'atp/field/postcode/missing': 3511,
'atp/field/street_address/missing': 3511,
'atp/field/twitter/missing': 3511,
'atp/item_scraped_host_count/www.paris.co.kr': 3554,
'atp/nsi/cc_match': 3511,
'downloader/request_bytes': 8334,
'downloader/request_count': 19,
'downloader/request_method_count/GET': 19, …
```

Paris Baguette in KR (3511 locations)

---

locations/spiders/longhorn_steakhouse.py

Opening hours only provided for day of.  Not simple to parse, so left out.
```
{'atp/brand/LongHorn Steakhouse': 600,
'atp/brand_wikidata/Q3259007': 600,
'atp/category/amenity/restaurant': 600,
'atp/field/country/from_reverse_geocoding': 587,
'atp/field/email/missing': 600,
'atp/field/image/missing': 600,
'atp/field/opening_hours/missing': 600,
'atp/field/operator/missing': 600,
'atp/field/operator_wikidata/missing': 600,
'atp/field/twitter/missing': 600,
'atp/field/website/missing': 600,
'atp/item_scraped_host_count/m.longhornsteakhouse.com': 600, …
```

[longhorn_steakhouse] Fix spider

---

locations/spiders/mediamarkt_de.py

**Stats:**
{'atp/brand/MediaMarkt': 308,
'atp/brand_wikidata/Q2381223': 308,
'atp/category/shop/electronics': 308,
'atp/field/branch/missing': 308,
'atp/field/image/missing': 308,
'atp/field/operator/missing': 308,
'atp/field/operator_wikidata/missing': 308,
'atp/field/phone/invalid': 300,
'atp/field/state/missing': 30,
'atp/field/street_address/missing': 308,
'atp/field/twitter/missing': 308,
'atp/item_scraped_host_count/www.mediamarkt.de': 308,
'atp/nsi/cc_match': 308,
'downloader/request_bytes': 1462,
'downloader/response_bytes': 51185, …

Fix Mediamarkt DE Spider

---

locations/spiders/coinstar.py

```py
{'atp/brand/Coinstar': 24910,
'atp/brand_wikidata/Q5141641': 24910,
'atp/category/amenity/payment_terminal': 24910,
'atp/cdn/cloudflare/response_count': 505,
'atp/cdn/cloudflare/response_status_count/200': 505,
'atp/field/branch/missing': 24910,
'atp/field/email/missing': 24910,
'atp/field/image/missing': 24910,
'atp/field/opening_hours/missing': 24910,
'atp/field/operator/missing': 24910,
'atp/field/operator_wikidata/missing': 24910,
'atp/field/phone/missing': 24910,
'atp/field/postcode/missing': 130,
'atp/field/state/missing': 1280,
'atp/field/twitter/missing': 24910,
'atp/item_scraped_host_count/coinstar.com': 30944,
'atp/nsi/perfect_match': 24910,
'downloader/request_bytes': 211731,
'downloader/request_count': 506, …
```

New spider: Coinstar kiosks (24910 locations)

---

locations/spiders/hertz.py

Fixes https://github.com/alltheplaces/alltheplaces/issues/3899
```py
{'atp/brand/Hertz': 2485,
'atp/brand_wikidata/Q1543874': 2485,
'atp/category/amenity/car_rental': 4538,
'atp/field/branch/missing': 2053,
'atp/field/brand/missing': 2053,
'atp/field/brand_wikidata/missing': 2053,
'atp/field/email/missing': 1693,
'atp/field/image/missing': 4538,
'atp/field/lat/missing': 9,
'atp/field/lon/missing': 9,
'atp/field/operator/missing': 4538,
'atp/field/operator_wikidata/missing': 4538,
'atp/field/phone/invalid': 62,
'atp/field/phone/missing': 53,
'atp/field/postcode/missing': 357,
'atp/field/state/missing': 1886,
'atp/field/twitter/missing': 4538,
'atp/geometry/null_island': 8,
'atp/item_scraped_host_count/ecom.mss.hertz.io': 5034,
'atp/nsi/perfect_match': 2485, …
```

Add spider for Hertz (4538 locations)

---

locations/spiders/debonairs_pizza_africa.py
locations/spiders/debonairs_pizza_na.py
locations/storefinders/yext_search.py

I don't know why they have a great YextSearch thing set up, but Namibia isn't included, so we get a lot less data for Namibia.
'Africa':
```
'atp/brand/Debonairs Pizza': 72,
'atp/brand_wikidata/Q65079407': 72,
'atp/category/amenity/fast_food': 72,
'atp/field/image/missing': 72,
'atp/field/postcode/missing': 29,
'atp/field/state/missing': 63,
'atp/field/twitter/missing': 72,
'atp/item_scraped_host_count/location.debonairspizza.africa': 72,
'atp/nsi/perfect_match': 72,
```
Namibia:
```
'atp/brand/Debonairs Pizza': 11, …
```

debonairs_pizza_africa and debonairs_pizza_na spiders

---

locations/spiders/carpetright_gb.py

Fixes #10108
```python
{'atp/brand/Carpetright': 54,
'atp/brand_wikidata/Q5045782': 54,
'atp/category/shop/carpet': 54,
'atp/cdn/cloudflare/response_count': 56,
'atp/cdn/cloudflare/response_status_count/200': 56,
'atp/field/city/missing': 14,
'atp/field/country/from_spider_name': 54,
'atp/field/state/missing': 54,
'atp/item_scraped_host_count/www.carpet-right.co.uk': 54,
'downloader/request_bytes': 203750,
'downloader/request_count': 56,
'downloader/request_method_count/GET': 56,
'downloader/response_bytes': 861114,
'downloader/response_count': 56,
'downloader/response_status_count/200': 56, …
```

[Carpetright GB] Use new website

---

locations/open_graph_parser.py

I noticed that my [local Franco Manca](https://www.francomanca.co.uk/restaurants/edinburgh-stockbridge/) was no longer in the output! Traced to new property keys appearing on the page and the code to build dict for `DictParser` taking away too much of the context.

[open_graph_parser] play a little bit less fast and loose with the namespace

---

locations/spiders/jet_at.py

```
{'atp/brand/Jet': 155,
'atp/brand_wikidata/Q568940': 155,
'atp/category/amenity/fuel': 155,
'atp/field/country/from_spider_name': 155,
'atp/field/email/missing': 155,
'atp/field/image/missing': 155,
'atp/field/opening_hours/missing': 155,
'atp/field/operator/missing': 155,
'atp/field/operator_wikidata/missing': 155,
'atp/field/state/missing': 155,
'atp/field/twitter/missing': 155,
'atp/item_scraped_host_count/www.jet-austria.at': 155,
'atp/nsi/cc_match': 155,
'downloader/response_bytes': 28557,
'elapsed_time_seconds': 3.037926, …
```

[jet_at] Fix Spider (155 locations)

---

locations/spiders/marie_callenders_us.py

Ironically, I suspect this one (or maybe all metalocators) is using OSM for geocoding! :smile: 
```py
{"atp/brand/Marie Callender's": 23,
'atp/brand_wikidata/Q6762784': 23,
'atp/category/amenity/restaurant': 23,
'atp/item_scraped_host_count/code.metalocator.com': 23,
'atp/nsi/perfect_match': 23,
'downloader/request_bytes': 360,
'downloader/response_bytes': 4129,
'elapsed_time_seconds': 0.987684, …
```

Marie Callender's (23 locations)

---

locations/spiders/mtn_deals_za.py
locations/spiders/mtn_za.py

MTN deals is an authorised reseller of MTN, but stores appear to be branded as MTN, so I'm not doing a different Wikidata for them.
mtn_za:
```
'atp/brand/MTN': 376,
'atp/brand_wikidata/Q1813361': 376,
'atp/category/shop/mobile_phone': 376,
'atp/field/country/from_spider_name': 376,
'atp/field/email/invalid': 3,
'atp/field/image/missing': 376,
'atp/field/operator/missing': 376,
'atp/field/operator_wikidata/missing': 376,
'atp/field/postcode/missing': 376,
'atp/field/state/missing': 376,
'atp/field/twitter/missing': 376,
'atp/item_scraped_host_count/www.mtn.co.za': 376,
'atp/nsi/cc_match': 376,
```
mtn_deals_za:
```
'atp/brand/MTN': 75,
'atp/brand_wikidata/Q1813361': 75,
'atp/category/shop/mobile_phone': 75,
'atp/field/branch/missing': 75, …
```

MTN ZA and MTN Deals ZA spiders

---

docs/WIKIDATA.md
locations/commands/nsi.py
locations/name_suggestion_index.py

Checking NSI by category is one thing, and the discussion posts on missing brands by @CloCkWeRX are interesting, but I don't know much about e.g. Japanese supermarkets so found myself searching the posts for "co.za" to find a brand I might know something about, or using https://nsi.guide and searching by country code.
I thought it would be easier to combine the two and so added this.
However, maybe it would be best if searching by location and by category were different commands?
You can search by country code or whatever can be in `["locationSet"]["include"]`, e.g. "us-ct.geojson".
e.g.
```
$ pipenv run scrapy nsi --detect-missing za
Missing by wikidata: 66
Astron Energy
fuel stations in South Africa
Q120752181
https://www.wikidata.org/wiki/Q120752181 …
```

Allow checking missing from NSI by location code

---

locations/spiders/raleys_us.py

```py
{'atp/brand/Bel Air': 21,
'atp/brand/Nob Hill Foods': 18,
"atp/brand/Raley's": 75,
"atp/brand/Raley's ONE Market": 4,
'atp/brand_wikidata/Q112922067': 21,
'atp/brand_wikidata/Q121816894': 18,
'atp/brand_wikidata/Q7286970': 79,
'atp/category/shop/supermarket': 118,
'atp/field/branch/missing': 118,
'atp/field/country/from_spider_name': 118,
'atp/field/image/missing': 118,
'atp/field/operator/missing': 118,
'atp/field/operator_wikidata/missing': 118,
'atp/item_scraped_host_count/www.raleys.com': 118,
'atp/nsi/brand_missing': 18,
'atp/nsi/perfect_match': 100,
'downloader/request_bytes': 905, …
```

Add Raley's and sub-brands (118 locations)

---

locations/spiders/postalannex_us.py

```py
{'atp/brand/PostalAnnex': 328,
'atp/brand_wikidata/Q61960357': 328,
'atp/category/amenity/post_office': 328,
'atp/field/email/missing': 328,
'atp/field/image/missing': 328,
'atp/field/name/missing': 328,
'atp/field/opening_hours/missing': 328,
'atp/field/twitter/missing': 328,
'atp/item_scraped_host_count/www.postalannex.com': 328,
'atp/nsi/cc_match': 328,
'atp/operator/PostalAnnex': 328,
'atp/operator_wikidata/Q61960357': 328,
'downloader/request_bytes': 626,
'downloader/response_bytes': 82353, …
```

PostalAnnex (328 locations)

---

locations/spiders/philz_coffee_us.py

```py
{'atp/brand/Philz Coffee': 71,
'atp/brand_wikidata/Q18156812': 71,
'atp/category/amenity/cafe': 71,
'atp/field/country/from_spider_name': 71,
'atp/field/email/missing': 71,
'atp/field/operator/missing': 71,
'atp/field/operator_wikidata/missing': 71,
'atp/field/postcode/missing': 71,
'atp/field/street_address/missing': 71,
'atp/field/twitter/missing': 71,
'atp/item_scraped_host_count/philzcoffee.com': 71,
'atp/nsi/perfect_match': 71,
'downloader/request_bytes': 1080,
'downloader/response_bytes': 32402, …
```

Philz Coffee (71 locations)

---

locations/spiders/wetzels_pretzels_ca_us.py

```py
{"atp/brand/Wetzel's Pretzels": 391,
'atp/brand_wikidata/Q7990205': 391,
'atp/category/amenity/fast_food': 391,
'atp/field/branch/missing': 391,
'atp/field/city/missing': 391,
'atp/field/country/from_reverse_geocoding': 391,
'atp/field/email/missing': 390,
'atp/field/image/missing': 391,
'atp/field/opening_hours/missing': 391,
'atp/field/operator/missing': 391,
'atp/field/operator_wikidata/missing': 391,
'atp/field/phone/missing': 26,
'atp/field/postcode/missing': 391,
'atp/field/street_address/missing': 391,
'atp/field/twitter/missing': 391,
'atp/field/website/missing': 391,
'atp/item_scraped_host_count/storemapper-herokuapp-com.global.ssl.fastly.net': 391,
'atp/nsi/perfect_match': 391,
'downloader/request_bytes': 368, …
```

Wetzel's Pretzels (391 locations)

---

locations/spiders/hertz.py

rel: #3899 
A general improvement of the spider - using another API we get all locations in 9 requests (26 seconds). In exchange there is no payment types information. 
Authorization might be a bit brittle, if it's a problem we can try another API, as there are 3 of them with different data...
```json
{
"atp/brand/Hertz": 6661,
"atp/brand_wikidata/Q1543874": 6661,
"atp/category/amenity/car_rental": 6661,
"atp/field/city/missing": 14,
"atp/field/email/invalid": 1,
"atp/field/email/missing": 2753,
"atp/field/image/missing": 6661,
"atp/field/lat/invalid": 1,
"atp/field/lat/missing": 14,
"atp/field/lon/missing": 14,
"atp/field/operator/missing": 6661,
"atp/field/operator_wikidata/missing": 6661,
"atp/field/phone/invalid": 366,
"atp/field/postcode/missing": 426, …
```

[hertz] use different API, parse all POIs (6661 locations)

---

locations/spiders/ozk_bank_us.py

```python
{'atp/brand/Bank OZK': 464,
'atp/brand_wikidata/Q20708654': 464,
'atp/category/amenity/atm': 230,
'atp/category/amenity/bank': 234,
'atp/cdn/cloudflare/response_count': 414,
'atp/cdn/cloudflare/response_status_count/200': 413,
'atp/field/branch/missing': 464,
'atp/field/city/missing': 230,
'atp/field/country/from_spider_name': 230,
'atp/field/email/missing': 464,
'atp/field/image/missing': 464,
'atp/field/name/missing': 230,
'atp/field/operator/missing': 464,
'atp/field/operator_wikidata/missing': 464,
'atp/field/phone/missing': 230,
'atp/field/postcode/missing': 230,
'atp/field/state/from_reverse_geocoding': 230,
'atp/field/street_address/missing': 230,
'atp/field/twitter/missing': 230, …
```

[Bank OZK US] Add spider

---

locations/spiders/formula_one_autocentres_gb.py

```python
{'atp/brand/Formula One Autocentres': 154,
'atp/brand_wikidata/Q79239635': 154,
'atp/category/shop/car_repair': 154,
'atp/cdn/cloudflare/response_count': 156,
'atp/cdn/cloudflare/response_status_count/200': 156,
'atp/field/email/missing': 154,
'atp/field/image/missing': 154,
'atp/field/operator/missing': 154,
'atp/field/operator_wikidata/missing': 154,
'atp/field/state/missing': 142,
'atp/item_scraped_host_count/www.f1autocentres.co.uk': 154,
'atp/nsi/perfect_match': 154,
'downloader/request_bytes': 172471,
'downloader/request_count': 156,
'downloader/request_method_count/GET': 156,
'downloader/response_bytes': 2262895,
'downloader/response_count': 156,
'downloader/response_status_count/200': 156,
'elapsed_time_seconds': 1.629022, …
```

[Formula One Autocentres GB] Add spider

---

locations/spiders/kaporal_fr.py

Rel: https://github.com/osmlab/name-suggestion-index/pull/9938
```python
{'atp/brand/Kaporal': 55,
'atp/brand_wikidata/Q125660181': 55,
'atp/category/missing': 55,
'atp/field/name/missing': 55,
'atp/field/opening_hours/missing': 55,
'atp/field/state/missing': 55,
'atp/item_scraped_host_count/www.kaporal.com': 55,
'atp/nsi/brand_missing': 55,
'downloader/request_bytes': 613,
'downloader/response_bytes': 122132,
'elapsed_time_seconds': 2.994328, …
```

[Kaporal FR] Add spider

---

locations/spiders/shell.py

I see that many are just copied city/state name
for example:
```
{
'amenity': 'fuel',
'fuel:engineoil': 'yes',
'@source_uri': 'https://shellgsllocator.geoapp.me/api/v2/locations/nearest_to?lat=7.66634&lng=-5.02748&limit=50',
'@spider': 'shell',
'addr:street_address': 'Béoumi Route Seguela',
'addr:city': 'BEOUMI',
'addr:state': 'BEOUMI',
'addr:postcode': '15 BP 378',
'addr:country': 'CI',
'phone': '+225 01 53 60 0145',
'brand': 'Shell',
'brand:wikidata': 'Q110716465',
'atp_listing_name': 'BEOUMI',
'name': 'Shell',
'atp_ref': 'CI_28100166'
}
```

shell - remove names

---

locations/spiders/avia_eu.py

[Sitemap](https://avia.nl/sitemap_index.xml) contains [Avia stations urls](https://avia.nl/ww-avia-station-sitemap.xml), but POI [pages](https://avia.nl/tankstations/avia-xpress-callantsoog) don't have coordinates, hence ignored Sitemap.
`'atp/field/brand/missing': 144` : This is mainly because of few locations `brand` identification doesn't look feasible, as `item["name"]` fails to indicated info regarding `brand` . Few might belong to `Avia` or others.
```
{'atp/brand/Avia': 417,
'atp/brand/Avia XPress': 239,
'atp/brand/DCB Energy': 6,
'atp/brand/Esso': 192,
'atp/brand/Esso Express': 113,
'atp/brand/Firezone': 31,
'atp/brand/IDS': 91,
'atp/brand/Kuster Olie': 27,
'atp/brand/Rolande': 18,
'atp/brand/Swing': 7,
'atp/brand/T-Energy': 3,
'atp/brand/T-Energy express': 1,
'atp/brand/Tamoil': …
```

[AviaEU] Add spider covering Avia, Avia Xpress and other brands for NL and  other EU countries (1512 locations)

---

locations/spiders/lidl_ch.py
locations/spiders/lidl_cy.py
locations/spiders/lidl_cz.py
locations/spiders/lidl_dk.py
locations/spiders/lidl_ee.py
locations/spiders/lidl_es.py
locations/spiders/lidl_fi.py
locations/spiders/lidl_fr.py
locations/spiders/lidl_gr.py
locations/spiders/lidl_hu.py
locations/spiders/lidl_it.py
locations/spiders/lidl_lt.py
locations/spiders/lidl_lv.py
locations/spiders/lidl_nl.py
locations/spiders/lidl_pl.py
locations/spiders/lidl_pt.py
locations/spiders/lidl_se.py
locations/spiders/lidl_sk.py

rel: https://github.com/alltheplaces/alltheplaces/pull/9507
LidlATSpider and LidlBESpider were refactored, but their descendant classes were not.

[lidl spiders] fixes after virtualearth spider refactoring

---

locations/pipelines/phone_clean_up.py
locations/spiders/toyota_br.py
tests/test_pipeline_phone_cleanup.py

Waiting on merge of #10186 for shared attributes.
```
'atp/brand/Toyota': 294,
'atp/brand_wikidata/Q53268': 294,
'atp/category/shop/car': 294,
'atp/field/branch/missing': 294,
'atp/field/country/from_spider_name': 294,
'atp/field/email/invalid': 184,
'atp/field/email/missing': 185,
'atp/field/image/missing': 294,
'atp/field/operator/missing': 294,
'atp/field/operator_wikidata/missing': 294,
'atp/field/street_address/missing': 294,
'atp/field/twitter/missing': 294,
'atp/field/website/invalid': 257,
'atp/item_scraped_host_count/www.toyota.com.br': 294,
'atp/nsi/cc_match': 294,
```

[toyota_br] Add spider (294 locations)

---

locations/spiders/toyota_mx.py

Waiting on merge of #10186 for shared attributes.
```
'atp/brand/Toyota': 98,
'atp/brand_wikidata/Q53268': 98,
'atp/category/shop/car': 98,
'atp/cdn/cloudflare/response_count': 131,
'atp/cdn/cloudflare/response_status_count/200': 131,
'atp/field/branch/missing': 98,
'atp/field/city/missing': 98,
'atp/field/country/from_spider_name': 98,
'atp/field/email/invalid': 86,
'atp/field/operator/missing': 98,
'atp/field/operator_wikidata/missing': 98,
'atp/field/postcode/missing': 98,
'atp/field/street_address/missing': 98,
'atp/field/twitter/missing': 98,
'atp/field/website/invalid': 9,
'atp/item_scraped_host_count/www.toyota.mx': 98,
'atp/nsi/cc_match': 98,
```

[toyota_mx] Add spider (98 locations)

---

locations/spiders/scouts_gb.py
locations/spiders/scouts_gg_gb_im_je.py

```
'atp/brand/The Scout Association': 9824,
'atp/brand_wikidata/Q849740': 9824,
'atp/category/club/scout': 9824,
'atp/field/branch/missing': 9824,
'atp/field/city/missing': 9824,
'atp/field/country/from_spider_name': 9824,
'atp/field/email/missing': 9824,
'atp/field/image/missing': 9824,
'atp/field/opening_hours/missing': 9824,
'atp/field/operator/missing': 9824,
'atp/field/operator_wikidata/missing': 9824,
'atp/field/phone/missing': 9824,
'atp/field/postcode/missing': 4068,
'atp/field/state/missing': 9824,
'atp/field/street_address/missing': 9824,
'atp/field/twitter/missing': 9824,
'atp/item_scraped_host_count/groupfinder.azurewebsites.net': 9824,
'atp/nsi/perfect_match': 9824,
'downloader/request_bytes': 13548,
'downloader/request_count': 21,
'downloader/request_method_count/GET': 21, …
```

[scouts_gb] Add spider (9824 locations)

---

locations/spiders/zebros_za.py

No coordinates available, but there are decent addresses
```
"atp/brand/Zebro's": 14,
'atp/brand_wikidata/Q116619443': 14,
'atp/category/amenity/fast_food': 14,
'atp/field/city/missing': 14,
'atp/field/country/from_spider_name': 14,
'atp/field/lat/missing': 14,
'atp/field/lon/missing': 14,
'atp/field/opening_hours/missing': 14,
'atp/field/postcode/missing': 14,
'atp/field/state/missing': 14,
'atp/field/street_address/missing': 14,
'atp/item_scraped_host_count/www.zebros.co.za': 14,
'atp/nsi/perfect_match': 14,
```

[zebros_za] Add spider (14 locations)

---

locations/categories.py
locations/spiders/scouts_za.py

```
'atp/brand/Scouts South Africa': 257,
'atp/brand_wikidata/Q7565791': 257,
'atp/category/club/scout': 257,
'atp/field/branch/missing': 257,
'atp/field/city/missing': 257,
'atp/field/country/from_spider_name': 257,
'atp/field/email/missing': 257,
'atp/field/image/missing': 257,
'atp/field/opening_hours/missing': 257,
'atp/field/operator/missing': 257,
'atp/field/operator_wikidata/missing': 257,
'atp/field/phone/missing': 257,
'atp/field/postcode/missing': 257,
'atp/field/state/missing': 257,
'atp/field/street_address/missing': 257,
'atp/field/twitter/missing': 257,
'atp/item_scraped_host_count/easterncapenorth.scouts.org.za': 16,
'atp/item_scraped_host_count/easterncapesouth.scouts.org.za': 13,
'atp/item_scraped_host_count/freestate.scouts.org.za': 21, …
```

[scouts_za] Add spider (257 locations)

---

locations/spiders/starbucks_cn.py

```
'atp/brand/星巴克': 7432,
'atp/brand_wikidata/Q37158': 7432,
'atp/category/amenity/cafe': 7432,
'atp/field/country/from_spider_name': 7432,
'atp/field/email/missing': 7432,
'atp/field/image/missing': 7432,
'atp/field/opening_hours/missing': 7432,
'atp/field/operator/missing': 7432,
'atp/field/operator_wikidata/missing': 7432,
'atp/field/phone/missing': 7432,
'atp/field/state/missing': 7432,
'atp/field/twitter/missing': 7432,
'atp/field/website/missing': 7432,
'atp/item_scraped_host_count/www.starbucks.com.cn': 13152,
'atp/nsi/cc_match': 7432,
'atp/starbucks_cn/unhandled_feature/BE': 742,
'atp/starbucks_cn/unhandled_feature/MIC': 10972,
'atp/starbucks_cn/unhandled_feature/MOP': 18474,
'atp/starbucks_cn/unhandled_feature/NCB': 1960,
'atp/starbucks_cn/unhandled_feature/OG': 26304, …
```

[starbucks_cn] Add spider (7432 locations)

---

locations/categories.py
locations/json_blob_spider.py
locations/spiders/toyota_ca.py

Waiting on merge of https://github.com/alltheplaces/alltheplaces/pull/10226 for shared attributes
Also I found here that for a feature dict, the pre_process_data had not been applying in JSONBlobSpider, so I added that.
```
'atp/brand/Toyota': 247,
'atp/brand_wikidata/Q53268': 247,
'atp/category/shop/car': 247,
'atp/field/branch/missing': 247,
'atp/field/country/from_spider_name': 247,
'atp/field/email/missing': 247,
'atp/field/image/missing': 247,
'atp/field/operator/missing': 247,
'atp/field/operator_wikidata/missing': 247,
'atp/field/twitter/missing': 247,
'atp/field/website/missing': 247,
'atp/item_scraped_host_count/www.toyota.ca': 247,
'atp/nsi/cc_match': 247,
```

[toyota_ca] Add spider (247 locations)

---

locations/categories.py
locations/spiders/gov_dfe_gias_gb.py

Maybe there could be a better spider name? DfE = Department for Education, GIAS = Get Information About Schools, but writing them in full seems too long
```
'atp/category/amenity/college': 281,
'atp/category/amenity/kindergarten': 412,
'atp/category/amenity/school': 29062,
'atp/category/amenity/university': 130,
'atp/closed_poi': 3032,
'atp/field/branch/missing': 29885,
'atp/field/brand/missing': 29885,
'atp/field/brand_wikidata/missing': 29885,
'atp/field/city/missing': 787,
'atp/field/country/from_reverse_geocoding': 21663,
'atp/field/country/from_website_url': 7481,
'atp/field/country/missing': 741,
'atp/field/email/missing': 29885,
'atp/field/image/missing': 29885,
'atp/field/lat/missing': 839,
'atp/field/lon/missing': 839,
'atp/field/opening_hours/missing': 29885, …
```

[gov_dfe_gias_gb] Add spider for GB educational establishments (29885 locations)

---

locations/spiders/dreams_gb.py

The dreams_gb spider is currently not returning any results. I don't know if this will fix everything (I'm unable to test code locally), but certainly the LinkedData type that the Dreams website uses has recently changed from LocalBusiness to FurnitureStore.

[Dreams GB] Fix spider

---

locations/json_blob_spider.py
locations/spiders/winmart_vn.py

Source data is a bit patchy--for example, some locations do not have coordinates provided.
There are other alternative APIs available, all requiring different forms of search and with different fields of data returned. The selected API of this spider is the only one found to return all stores in a single query, and seems to contain most data fields that are of interest.
Fixes #9103

Add WinMart and WinMart+ (VN) (2422 stores)

---

locations/spiders/hsbc_uk_gb.py

```python
{'atp/brand/HSBC UK': 395,
'atp/brand_wikidata/Q64767453': 395,
'atp/category/amenity/bank': 395,
'atp/field/branch/missing': 395,
'atp/field/email/missing': 395,
'atp/field/image/missing': 395,
'atp/field/operator/missing': 395,
'atp/field/operator_wikidata/missing': 395,
'atp/field/phone/missing': 395,
'atp/field/state/missing': 395,
'atp/field/twitter/missing': 395,
'atp/item_scraped_host_count/www.hsbc.co.uk': 395,
'atp/nsi/cc_match': 395,
'downloader/request_bytes': 169221,
'downloader/request_count': 425,
'downloader/request_method_count/GET': 425,
'downloader/response_bytes': 14651576,
'downloader/response_count': 425,
'downloader/response_status_count/200': 397,
'downloader/response_status_count/404': 28, …
```

[HSBC UK] Fix spider (Fixes #10258)

---

locations/spiders/bastide_fr.py

```python
{'atp/brand/Bastide le confort médical': 160,
'atp/brand_wikidata/Q2887693': 160,
'atp/category/shop/medical_supply': 160,
'atp/field/image/dropped': 160,
'atp/field/image/missing': 160,
'atp/field/lat/missing': 160,
'atp/field/lon/missing': 160,
'atp/field/opening_hours/missing': 160,
'atp/field/operator/missing': 160,
'atp/field/operator_wikidata/missing': 160,
'atp/field/twitter/missing': 160,
'atp/nsi/perfect_match': 160,
'downloader/request_bytes': 83028,
'downloader/request_count': 162,
'downloader/request_method_count/GET': 162,
'downloader/response_bytes': 29554204,
'downloader/response_count': 162,
'downloader/response_status_count/200': 162,
'elapsed_time_seconds': 199.024548,
'finish_time': datetime.datetime(2024, 9, 16, 21, 41, 58, …
```

[BastideFR] Added Spider for Bastide (160 locations)

---

locations/storefinders/yext_search.py

I don't think the absence of a payment method can be taken to mean that it is definitely not accepted. Also, I think these do not all apply globally.

[YextSearch] Don't always apply payments

---

locations/spiders/salvation_army_gb.py

Fixes #10341
```python
{'atp/brand/Salvation Army': 383,
'atp/brand_wikidata/Q188307': 383,
'atp/category/shop/charity': 383,
'atp/field/branch/missing': 383,
'atp/field/country/from_spider_name': 383,
'atp/field/email/missing': 383,
'atp/field/image/missing': 383,
'atp/field/opening_hours/missing': 383,
'atp/field/operator/missing': 383,
'atp/field/operator_wikidata/missing': 383,
'atp/field/phone/missing': 383,
'atp/field/state/missing': 383,
'atp/field/street_address/missing': 383,
'atp/field/twitter/missing': 383,
'atp/item_scraped_host_count/www.salvationarmy.org.uk': 383,
'atp/nsi/cc_match': 383,
'downloader/request_bytes': 151513,
'downloader/request_count': 389,
'downloader/request_method_count/GET': 389,
'downloader/response_bytes': 5690907,
'downloader/response_count': 389, …
```

[Salvation Army GB] Improve sitemap regex

---

locations/spiders/dream_doors_gb.py

Fixes #9836
```python
{'atp/brand/Dream Doors': 89,
'atp/brand_wikidata/Q84702301': 89,
'atp/category/shop/kitchen': 89,
'atp/cdn/cloudflare/response_count': 91,
'atp/cdn/cloudflare/response_status_count/200': 91,
'atp/field/branch/missing': 89,
'atp/item_scraped_host_count/www.dreamdoors.co.uk': 89,
'atp/nsi/perfect_match': 89,
'downloader/request_bytes': 65721, …
```

[Dream Doors GB] Add spider

---

locations/spiders/ben_and_jerrys.py
locations/storefinders/where2getit.py

#8893 appears to be abandoned, so I had a look.
```
"atp/brand/Ben & Jerry's": 2492,
'atp/brand_wikidata/Q816412': 2492,
'atp/category/amenity/ice_cream': 2492,
'atp/field/email/missing': 2492,
'atp/field/image/missing': 2492,
'atp/field/opening_hours/missing': 2273,
'atp/field/operator/missing': 2492,
'atp/field/operator_wikidata/missing': 2492,
'atp/field/phone/missing': 2231,
'atp/field/state/missing': 2234,
'atp/field/twitter/missing': 2492,
'atp/field/website/missing': 2278,
'atp/item_scraped_host_count/hosted.where2getit.com': 2492,
'atp/nsi/perfect_match': 2492,
```

[ben_and_jerrys] Add spider

---

ci/check_spider_naming_consistency.py
locations/spiders/power_fashion_ls_sz_za.py
locations/spiders/power_fashion_za.py

Appears to have some not very accurate reverse geocoding for a number of locations
```
'atp/brand/Power': 316,
'atp/brand_wikidata/Q118185713': 316,
'atp/category/shop/clothes': 316,
'atp/field/city/missing': 316,
'atp/field/country/from_reverse_geocoding': 316,
'atp/field/email/missing': 316,
'atp/field/image/missing': 316,
'atp/field/opening_hours/missing': 315,
'atp/field/operator/missing': 316,
'atp/field/operator_wikidata/missing': 316,
'atp/field/phone/invalid': 11,
'atp/field/postcode/missing': 316,
'atp/field/street_address/missing': 316,
'atp/field/twitter/missing': 316,
'atp/field/website/missing': 316,
'atp/item_scraped_host_count/api.storepoint.co': 316,
'atp/nsi/perfect_match': 316,
'downloader/request_bytes': 340, …
```

[power_fashion_ls_sz_za] Add spider (316 locations)

---

locations/spiders/rite_aid_us.py
locations/spiders/walgreens.py

Changed the `rite_aid_us` spider to only output Pharmacy Category POIs as well as addind `opening_hours:pharmacy` to extras for `rite_aid_us` and `walgreens`. I made this PR so that the big 3 pharmacy brands in US are similar in what they produce. As `cvs_us` spider only outputs Pharmacy POIs and not `shop=chemist` I think `rite_aid_us` should as well. I get why `rite_aid_us` were outputting both. One for retail and one for pharmacy, but I think it is unnecessary as most Americans including myself think of them as Pharmacy. Especially as you can get almost everything in the retail section at Walmart or Target for cheaper prices.
<details><summary>Rite Aid Stats</summary>
```json
{
"atp/brand/Rite Aid": 1383,
"atp/brand_wikidata/Q3433273": 1383,
"atp/category/amenity/pharmacy": 1383, …
```

[rite_aid_us][walgreens.py] Only output Pharmacy Category POIs

---

locations/json_blob_spider.py
locations/spiders/starbucks_hk_mo.py

Also adding an option in JsonBlobSpider to force a JsonRequest, as I have now come across that a few times
```
'atp/brand/Starbucks': 180,
'atp/brand_wikidata/Q37158': 180,
'atp/category/amenity/cafe': 180,
'atp/field/city/missing': 180,
'atp/field/email/missing': 180,
'atp/field/image/missing': 180,
'atp/field/operator/missing': 180,
'atp/field/operator_wikidata/missing': 180,
'atp/field/postcode/missing': 180,
'atp/field/state/missing': 180,
'atp/field/street_address/missing': 180,
'atp/field/twitter/missing': 180,
'atp/field/website/missing': 180,
'atp/item_scraped_host_count/www.starbucks.com.hk': 180,
'atp/nsi/cc_match': 180,
'downloader/request_bytes': 661,
'downloader/response_bytes': 662534, …
```

[starbucks_hk_mo] Add spider

---

locations/dict_parser.py
locations/spiders/starbucks_reserve.py

Waiting on https://github.com/osmlab/name-suggestion-index/commit/3f6575cfd152a742b60f3668ec04b8d0b1311ad8 for categories
There are now a few spiders like this, `https://storage.googleapis.com/maps-solutions-.../locator-plus/.../locator-plus-config.js`. Might be worth a storefinder
```
'atp/brand/Starbucks Reserve': 9,
'atp/brand_wikidata/Q71150001': 9,
'atp/category/missing': 9,
'atp/field/branch/missing': 9,
'atp/field/city/missing': 9,
'atp/field/country/from_reverse_geocoding': 9,
'atp/field/opening_hours/missing': 9,
'atp/field/website/missing': 9, …
```

[starbucks_reserve] Add spider

---

locations/spiders/micro_center_us.py
locations/structured_data_spider.py

After updating Micro Center I realised I've seen a few spiders where we only want linked data, not the micro data due to duplicates.

[StructuredDataSpider] Allow disabling of micro data parsing

---

locations/spiders/gautrain_za.py

```
'atp/category/railway/station': 10,
'atp/field/branch/missing': 10,
'atp/field/brand/missing': 10,
'atp/field/brand_wikidata/missing': 10,
'atp/field/city/missing': 10,
'atp/item_scraped_host_count/www.gautrain.co.za': 10,
'atp/nsi/operator_missing': 10,
'atp/operator/Gautrain': 10,
'atp/operator_wikidata/Q1476881': 10,
```

[gautrain_za] Add spider

---

locations/spiders/sweetgreen_us.py

Arguably this could also crawl https://www.sweetgreen.com/locations ; but individual pages don't have coordinates.
The request to hit ratio of this is pretty low; I'm up to 194 pages/0 hits.

Fix sweetgreen_us domain

---

locations/spiders/fastrak_za.py

Locations have a Google Maps link, but mostly without coordinates
```
'atp/brand/Fastrak': 73,
'atp/brand_wikidata/Q120799603': 73,
'atp/category/shop/hifi': 73,
'atp/field/city/missing': 73,
'atp/field/country/from_spider_name': 73,
'atp/field/image/missing': 73,
'atp/field/lat/missing': 72,
'atp/field/lon/missing': 72,
'atp/field/opening_hours/missing': 73,
'atp/field/operator/missing': 73,
'atp/field/operator_wikidata/missing': 73,
'atp/field/postcode/missing': 73,
'atp/field/street_address/missing': 73,
'atp/field/twitter/missing': 73,
'atp/field/website/missing': 73, …
```

[fastrak_za] Add spider

---

locations/spiders/pna_na_za.py

Waiting on https://github.com/osmlab/name-suggestion-index/commit/fcabf78b5b36eb00d2b9da13017b00d98f4d41f1 for categories
Embedded maps, but no coordinates available from them
```
'atp/brand/PNA': 128,
'atp/brand_wikidata/Q126911439': 128,
'atp/category/missing': 128,
'atp/field/city/missing': 128,
'atp/field/country/missing': 128,
'atp/field/image/missing': 128,
'atp/field/lat/missing': 128,
'atp/field/lon/missing': 128,
'atp/field/name/missing': 128,
'atp/field/operator/missing': 128,
'atp/field/operator_wikidata/missing': 128,
'atp/field/phone/invalid': 127,
'atp/field/twitter/missing': 128, …
```

[pna_na_za] Add spider

---

locations/pipelines/email_clean_up.py
locations/spiders/cash_crusaders_bw_na_za.py

Also fix the email pipeline to correctly return multiple emails
```
'atp/brand/Cash Crusaders': 192,
'atp/brand_wikidata/Q116895402': 192,
'atp/category/shop/pawnbroker': 192,
'atp/field/email/invalid': 98,
'atp/field/image/missing': 192,
'atp/field/operator/missing': 192,
'atp/field/operator_wikidata/missing': 192,
'atp/field/twitter/missing': 192,
'atp/item_scraped_host_count/api.locationbank.net': 192,
'atp/nsi/perfect_match': 192,
````

[cash_crusaders_bw_na_za] Add spider

---

locations/spiders/barko_loans_za.py

No coordinates available. The data includes Google Maps links, but they seem to be just auto-generated search links from the address
```
'atp/brand/Barko Loans': 202,
'atp/brand_wikidata/Q118185897': 202,
'atp/category/shop/money_lender': 202,
'atp/field/country/from_spider_name': 202,
'atp/field/image/missing': 202,
'atp/field/lat/missing': 202,
'atp/field/lon/missing': 202,
'atp/field/opening_hours/missing': 202,
'atp/field/operator/missing': 202,
'atp/field/operator_wikidata/missing': 202,
'atp/field/postcode/missing': 202,
'atp/field/twitter/missing': 202,
'atp/field/website/missing': 202,
'atp/item_scraped_host_count/www.barko.co.za': 202,
'atp/nsi/perfect_match': 202,
```

[barko_loans_za] Add spider

---

locations/spiders/miladys_za.py
locations/spiders/sheet_street_za.py

Miladys and Sheet Street are both under Mr Price Group, hence having almost identical websites
```
'atp/brand/Sheet Street': 316,
'atp/brand_wikidata/Q118185878': 316,
'atp/category/shop/houseware': 316,
'atp/cdn/cloudflare/response_count': 326,
'atp/cdn/cloudflare/response_status_count/200': 326,
'atp/field/city/missing': 316,
'atp/field/country/from_spider_name': 316,
'atp/field/email/missing': 316,
'atp/field/image/missing': 316,
'atp/field/operator/missing': 316,
'atp/field/operator_wikidata/missing': 316,
'atp/field/phone/missing': 316,
'atp/field/postcode/missing': 316,
'atp/field/state/missing': 316,
'atp/field/street_address/missing': 316,
'atp/field/twitter/missing': 316, …
```

[sheet_street_za] Add spider

---

locations/spiders/charleys_philly_steaks.py

```python
{"atp/brand/Charley's Philly Steaks": 872,
'atp/brand_wikidata/Q1066777': 872,
'atp/category/amenity/fast_food': 872,
'atp/field/country/from_reverse_geocoding': 872,
'atp/field/email/missing': 872,
'atp/field/image/missing': 872,
'atp/field/opening_hours/missing': 124,
'atp/field/operator/missing': 872,
'atp/field/operator_wikidata/missing': 872,
'atp/field/phone/invalid': 18,
'atp/field/phone/missing': 27,
'atp/field/postcode/missing': 37,
'atp/item_scraped_host_count/www.charleys.com': 872,
'atp/nsi/perfect_match': 872,
'downloader/request_bytes': 389692,
'downloader/request_count': 896, …
```

[Charley's Philly Steaks] Fix spider (Fixes #10482)

---

locations/spiders/panera_bread_us.py

There is a sitemap but the location pages don't seem to have any structured data (or even any data! it's all through the API). Unfortunately this endpoint does not include opening hours. There are two other endpoints that do: one is a geographic search but has a max result cap of 15, which is too small; and one requires the store ID, so would need an extra request per store just to get the opening hours.

Rewrite Panera Bread spider to use API

---

locations/spiders/tesco_eu.py

Tesco revamped their EU sites to use different APIs etc. old API still works, but we lost individual links. I'll comeback to this spider once I figure out auth on the website.

[tesco_eu] fix spider

---

locations/spiders/simply_asia_za.py

Waiting on https://github.com/osmlab/name-suggestion-index/commit/7cec7803ae777683ad301cae9017455dad06e27c for categories
Ref #10030
```
'atp/brand/Simply Asia': 55,
'atp/brand_wikidata/Q130358521': 55,
'atp/category/missing': 55,
'atp/field/city/missing': 55,
'atp/field/name/missing': 55,
'atp/field/opening_hours/missing': 55,
'atp/field/postcode/missing': 55,
'atp/field/state/missing': 55,
'atp/field/street_address/missing': 55,
'atp/item_scraped_host_count/admin.goreview.co.za': 55,
'atp/nsi/brand_missing': 55,
```

[simply_asia_za] Add spider

---

locations/spiders/ee_gb.py

Some EE store URLs only have two or three geographic levels rather than the currently assumed four, e.g. https://ee.co.uk/stores/england/one_braham and https://ee.co.uk/stores/england/suffolk/bury_st_edmunds and https://ee.co.uk/stores/england/isle_of_wight/isle_of_wight_newport

Fix sitemap_rules regex in EE spider

---

locations/spiders/bensons_for_beds_gb.py

There are a couple of Bensons stores whose URL slugs contain a forward slash:
* https://stores.bensonsforbeds.co.uk/murton/unit-28/29-dalton-park
* https://stores.bensonsforbeds.co.uk/bristol/unit-10/11-imperial-retail-park
These two stores are currently missed by the spider, as it allows only two directory levels in the URL. We can't simply allow another level since the sitemap also lists sub-pages under each store, such as  https://stores.bensonsforbeds.co.uk/luton/unit-4-hatters-way-retail-park/mattresses , which we don't want to process.
I think this PR will do the job though, allowing a slash in the store slug provided that it's followed by a number.

Correct store regex in bensons_for_beds_gb.py

---

locations/spiders/bensons_for_beds_gb.py

Fixes #10594
```python
{'atp/brand/Bensons for Beds': 174,
'atp/brand_wikidata/Q4890299': 174,
'atp/category/shop/bed': 174,
'atp/cdn/cloudflare/response_count': 178,
'atp/cdn/cloudflare/response_status_count/200': 178,
'atp/field/email/missing': 174,
'atp/field/image/dropped': 174,
'atp/field/image/missing': 174,
'atp/field/opening_hours/missing': 13,
'atp/field/operator/missing': 174,
'atp/field/operator_wikidata/missing': 174,
'atp/field/state/missing': 174,
'atp/field/twitter/missing': 174,
'atp/item_scraped_host_count/stores.bensonsforbeds.co.uk': 174,
'atp/nsi/perfect_match': 174,
'downloader/request_bytes': 101103,
'downloader/request_count': 178,
'downloader/request_method_count/GET': 178,
'downloader/response_bytes': 4324411,
'downloader/response_count': 178, …
```

[Bensons for Beds GB] Collect website

---

locations/spiders/tmobile_cz.py

Parsed from [map](https://coveragemap-tmcz.position.cz/#el=TMCZ:Store@pos=49.854414;15.567853@sc=6200000) API, all branches are visible is the screen size is wide enough.
No good "name" field available, I constructed the name from address. Website for each branch not available.
Opening hours parsed correctly.

[tmobile_cz] Add spider (102 locations)

---

locations/categories.py
locations/spiders/akhona_za.py

While `landuse` on a point is weird, so are parks and other typically area POIs are. The [wiki says](https://wiki.openstreetmap.org/wiki/Tag:industrial%3Dwarehouse) `industrial` requires `landuse=industrial`.

[Akhona ZA] Alter warehouse category

---

locations/linked_data_parser.py
locations/spiders/meny_dk.py
tests/test_ld_parser.py

#10366 introduced a situation where `_parse_opening_hours_specification` can null itself 
https://github.com/alltheplaces/alltheplaces/blob/015713a839f21d2f6cad9a871fae2de22ed64af6/locations/linked_data_parser.py#L241-L244
Combined with https://github.com/alltheplaces/alltheplaces/blob/015713a839f21d2f6cad9a871fae2de22ed64af6/locations/linked_data_parser.py#L130-L131 makes it quite a noisy error.

[LinkedDataParser] Fix openingHoursSpecification parsing with empty rule

---

locations/spiders/burger_king_no.py

There really do seem to be exactly 100 locations, I've tried a coordinate search including other locations, but it just gets duplicates.
```
'atp/brand/Burger King': 100,
'atp/brand_wikidata/Q177054': 100,
'atp/category/amenity/fast_food': 100,
'atp/field/city/missing': 100,
'atp/field/country/from_spider_name': 100,
'atp/field/image/missing': 100,
'atp/field/operator/missing': 100,
'atp/field/operator_wikidata/missing': 100,
'atp/field/phone/missing': 100,
'atp/field/postcode/missing': 100,
'atp/field/state/missing': 100,
'atp/field/street_address/missing': 100,
'atp/field/twitter/missing': 100,
'atp/item_scraped_host_count/bk-no-ordering-api-fd-ebghbnd6ebadc7fz.z01.azurefd.net': 100,
'atp/nsi/cc_match': 100,
```

[burger_king_no] Add spider

---

locations/spiders/hyundai_ca.py
locations/spiders/hyundai_us.py

```python
{'atp/brand/Hyundai': 2535,
'atp/brand_wikidata/Q55931': 2535,
'atp/category/shop/car': 845,
'atp/category/shop/car_parts': 845,
'atp/category/shop/car_repair': 845,
'atp/field/branch/missing': 2535,
'atp/field/country/from_spider_name': 2535,
'atp/field/email/invalid': 72,
'atp/field/email/missing': 948,
'atp/field/image/missing': 2535,
'atp/field/operator/missing': 2535,
'atp/field/operator_wikidata/missing': 2535,
'atp/field/state/from_reverse_geocoding': 1506,
'atp/field/twitter/missing': 2535,
'atp/field/website/invalid': 9,
'atp/item_scraped_host_count/www.hyundaiusa.com': 25563,
'atp/nsi/cc_match': 1690,
'atp/nsi/match_failed': 845, …
```

[Hyundai US] Fix spider

---

locations/spiders/dominos_pizza_gb.py

The image field is not of individual stores but rather logos and other brand imagery.

dominos_pizza_gb: drop image field

---

locations/spiders/burlington_us.py

burlington_us: drop image field

---

locations/spiders/lloyds_bank_gb.py

lloyds_bank_gb: drop image field

---

locations/spiders/cato_us.py

The image field is always the same brand logo, not an individual image of each location.

cato_us: drop image field

---

locations/spiders/baskin_robbins_us.py

The image field is always the same brand logo, not an individual image of each location.

baskin_robbins_us: drop image field

---

locations/spiders/food_lion_us.py

food_lion_us: drop image field

---

locations/spiders/nationwide_gb.py

nationwide_gb: drop image field

---

locations/spiders/albertsons.py

The image field is always a brand logo, not an individual image of each branch.

albertsons: drop image field

---

locations/spiders/penske.py

penske: drop image field

---

locations/spiders/big_lots.py

big_lots: drop image field

---

locations/spiders/ameriprise_us.py

The image field is always either a brand logo or a photo of the financial advisor (or group of advisors) at a given office, rather than an image of an actual physical location/office.

ameriprise_us: drop image field

---

locations/spiders/vans.py

The image field is populated with a banner/advertising image.

vans: drop image field

---

locations/spiders/bestone_gb.py

bestone_gb: drop image field

---

locations/spiders/costcutter_gb.py

costcutter_gb: drop image field

---

locations/spiders/subway.py

The image field is either always the same brand logo, or is an invalid link to the store's individual website.

subway: drop image field

---

locations/spiders/gnc.py

gnc: drop image field

---

locations/spiders/papa_murphys.py

papa_murphys: drop image field

---

locations/spiders/societe_generale.py

Some stores for this brand do not have an individual/specific store image and instead have a generic store image instead.

societe_generale: drop image field where not of specific store

---

locations/spiders/bojangles.py

bojangles: drop image field

---

locations/spiders/netto_salling.py

netto_salling: drop image field

---

locations/spiders/fifth_third_bank.py

fifth_third_bank: drop image field

---

locations/spiders/maurices.py

maurices: drop image field

---

locations/spiders/jackson_hewitt.py

jackson_hewitt: drop image field

---

locations/spiders/salon_centric_us.py

salon_centric_us: drop image field

---

locations/spiders/jamba_juice.py

The image field is a generic stock art image, and not an individual image for each store.

jamba_juice: drop image field

---

locations/spiders/massage_envy.py

massage_envy: drop image field

---

locations/spiders/nike.py

Some stores for this brand do not have an individual/specific store image and instead have a generic image of a store interior.

nike: drop image field where not of specific store

---

locations/spiders/rainbow_shops.py

Some stores for this brand do not have an individual/specific store image and instead have a generic brand logo as the image.

rainbow_shops: drop image field where not of specific store

---

locations/spiders/aldi_sud_au.py

adli_sud_au: drop image field

---

locations/spiders/moes_southwest_grill.py

The image field is a generic stock art image, and not an individual image for each store.

moes_southwest_grill: drop image field

---

locations/spiders/ups_store.py

ups_store: drop image field

---

locations/spiders/american_eagle_outfitters.py

The image field is either always the same brand logo, or is an invalid link to the store's individual website.

american_eagle_outfitters: drop image field

---

locations/spiders/picard_fr.py

picard_fr: drop image field

---

locations/spiders/petco.py

The image field is either always the same brand logo, or is an invalid link to the store's individual website.

petco: drop image field

---

locations/spiders/the_cooperative_group.py

The image field contains a single invalid image file for all locations.

the_cooperative_group: drop image field

---

locations/spiders/mercy_health_us.py

Some image field values are just provided as the primary website, not a valid image file.

mercy_health_us: drop invalid image field values

---

locations/spiders/wendys.py

wendys: drop image field

---

locations/spiders/bealls_us.py

Some stores for this brand do not have an individual/specific store image and instead have a generic store image instead.

bealls_us: drop image where not of specific store

---

locations/spiders/levis.py

Some stores for this brand do not have an individual/specific store image and instead have a generic brand logo as the image.

levis: drop image field where not of specific store

---

locations/spiders/bhf_gb.py

bhf_gb: drop image field

---

locations/spiders/virginia_health_inspection_blue_ridge.py

Mostly here for discussion since this may be out of scope to include in ATP.
There are 136 districts available on https://inspections.myhealthdepartment.com/ spanning several states, but for now I've hard-coded it to a single district in Virginia.
The main benefit to including this source is having access to recent data "on the ground" from a health inspector. A lot of the restaurants in OSM are quite old, and may or may not still exist.
I've been geocoding this data for the state of Virginia to find missing restaurants in OSM, corroborated with public sources like the restaurant's website.
Although it's not super useful to include by itself because the source is not geocoded, a geocoding step in the pipeline would make this quite valuable for auditing OSM data.

Add spider for virginia blue ridge distrinct health inspection data

---

locations/spiders/hifi_corp.py

```
'atp/brand/HiFiCorp': 54,
'atp/brand_wikidata/Q130331336': 54,
'atp/category/shop/electronics': 54,
'atp/field/street_address/missing': 54,
'atp/item_scraped_host_count/www.hificorp.co.za': 54,
```

[hifi_corp] Add spider

---

locations/spiders/cuisinella_fr.py

```python
{'atp/brand/Cuisinella': 324,
'atp/brand_wikidata/Q3007012': 324,
'atp/category/shop/kitchen': 324,
'atp/field/email/missing': 324,
'atp/field/image/invalid': 324,
'atp/field/operator/missing': 324,
'atp/field/operator_wikidata/missing': 324,
'atp/field/state/missing': 318,
'atp/field/twitter/missing': 324,
'atp/item_scraped_host_count/www.ma.cuisinella': 324,
'atp/nsi/perfect_match': 324,
'downloader/request_bytes': 237103,
'downloader/request_count': 337,
'downloader/request_method_count/GET': 337,
'downloader/response_bytes': 10829140,
'downloader/response_count': 337,
'downloader/response_status_count/200': 330,
'downloader/response_status_count/301': …
```

[Cuisinella FR] Fix coords

---

locations/spiders/hyundai_gb.py
locations/spiders/hyundai_ie.py
locations/spiders/hyundai_nz.py
locations/spiders/hyundai_us.py
locations/spiders/intermarche.py
locations/spiders/walmart_us.py

`.copy()` doesn't work as expected for nested dicts (`extras`). (cc @davidhicks)
```
>>> a = {"a":"abc"}
>>> b = a.copy()
>>> a["1"] = 123
>>> print(b)
{'a': 'abc'}
>>> print(a)
{'a': 'abc', '1': 123}
```
With shallow dicts/strings, it works as expected, you get a copy.
```
>>> a = {"a": "abc", "extras": {"shop": "yes"}}
>>> b = a.copy()
>>> a["extras"]["shop"] = "no"
>>> print(a)
{'a': 'abc', 'extras': {'shop': 'no'}}
>>> print(b)
{'a': 'abc', 'extras': {'shop': 'no'}}
```
But with dicts you get pointers so changing one, changes both.

[Refactor] Use deepcopy over copy

---

locations/spiders/mica_hardware.py

```
'atp/brand/Mica Hardware': 133,
'atp/brand_wikidata/Q116771560': 133,
'atp/category/shop/hardware': 133,
'atp/field/branch/missing': 133,
'atp/field/city/missing': 133,
'atp/field/country/from_reverse_geocoding': 132,
'atp/field/email/missing': 133,
'atp/field/image/missing': 133,
'atp/field/operator/missing': 133,
'atp/field/operator_wikidata/missing': 133,
'atp/field/postcode/missing': 133,
'atp/field/street_address/missing': 133,
'atp/field/twitter/missing': 133,
'atp/item_scraped_host_count/www.mica.co.za': 133,
'atp/nsi/perfect_match': 133,
```

[mica_hardware] Add spider

---

locations/spiders/assupol_za.py

Wikidata was a redirect to the correct one, NSI had the correct one so we weren't getting categories.

[assupol_za] Fix wikidata

---

locations/spiders/zenith_bank_atm_gh.py
locations/spiders/zenith_bank_branch_gh.py

```
'atp/brand/Zenith Bank': 43,
'atp/brand_wikidata/Q5978240': 43,
'atp/category/amenity/bank': 43,
'atp/field/city/missing': 43,
'atp/field/country/from_spider_name': 43,
'atp/field/email/missing': 43,
'atp/field/image/missing': 43,
'atp/field/opening_hours/missing': 43,
'atp/field/phone/missing': 43,
'atp/field/postcode/missing': 43,
'atp/field/state/missing': 43,
'atp/field/street_address/missing': 43,
'atp/field/twitter/missing': 43,
'atp/field/website/missing': 43,
'atp/item_scraped_host_count/www.zenithbank.com.gh': 43,
'atp/nsi/cc_match': 43,
```
```
'atp/brand/Zenith Bank': 71,
'atp/brand_wikidata/Q5978240': 71,
'atp/category/amenity/atm': 71, …
```

[zenith_bank_branch_gh] and [zenith_bank_atm_gh] Add spiders

---

locations/spiders/citiwood_za.py

Too small for NSI, so not added there
```
'atp/brand/Citiwood': 3,
'atp/brand_wikidata/Q130407139': 3,
'atp/category/shop/trade': 3,
'atp/item_scraped_host_count/cw001.goreview.co.za': 1,
'atp/item_scraped_host_count/cw002.goreview.co.za': 1,
'atp/item_scraped_host_count/cw003.goreview.co.za': 1,

[citiwood_za] Add spider

---

locations/spiders/ctm.py

Waiting on https://github.com/osmlab/name-suggestion-index/commit/de877764c56924937ff1114841e72c408085b05f for category
```
'atp/brand/CTM': 77,
'atp/brand_wikidata/Q127378361': 77,
'atp/category/missing': 77,
'atp/field/city/missing': 77,
'atp/field/image/missing': 77,
'atp/field/name/missing': 77,
'atp/field/operator/missing': 77,
'atp/field/operator_wikidata/missing': 77,
'atp/field/postcode/missing': 77,
'atp/field/street_address/missing': 77,
'atp/field/twitter/missing': 77,
'atp/item_scraped_host_count/www.ctm.co.za': 77,
'atp/nsi/brand_missing': 77,
```

[ctm] Add spider

---

locations/spiders/invitro_ru.py

```json
{
"atp/brand/Инвитро": 1495,
"atp/brand_wikidata/Q4200546": 1495,
"atp/category/healthcare/laboratory": 1495,
"atp/field/branch/missing": 1495,
"atp/field/opening_hours/missing": 19,
"atp/field/operator/missing": 1495,
"atp/field/operator_wikidata/missing": 1495,
"atp/field/postcode/missing": 1495,
"atp/field/state/missing": 1495,
"atp/field/twitter/missing": 1495,
"atp/item_scraped_host_count/www.invitro.ru": 1495,
"atp/nsi/perfect_match": 1495,
"downloader/request_bytes": 1339569,
"downloader/request_count": 1604,
"downloader/request_method_count/GET": 1604,
"downloader/response_bytes": 565990169,
"downloader/response_count": 1604,
"downloader/response_status_count/200": 1502,
"downloader/response_status_count/301": 23,
"downloader/response_status_count/302": 8, …
```

[invitro_ru] add spider (1.5k locations)

---

locations/spiders/hilti_us.py

Rel: https://github.com/osmlab/name-suggestion-index/issues/9823
```python
{'atp/brand/Hilti': 74,
'atp/brand_wikidata/Q1361530': 74,
'atp/category/shop/hardware': 74,
'atp/field/country/from_reverse_geocoding': 74,
'atp/field/email/missing': 74,
'atp/field/image/missing': 74,
'atp/field/operator/missing': 74,
'atp/field/operator_wikidata/missing': 74,
'atp/field/phone/missing': 74,
'atp/field/twitter/missing': 74,
'atp/item_scraped_host_count/www.hilti.com': 74,
'atp/nsi/perfect_match': 74,
'downloader/request_bytes': 808,
'downloader/response_bytes': 40419,
'elapsed_time_seconds': 0.713997,
'finish_time': …
```

[Hilti US] Add spider

---

locations/spiders/matalan_gb.py

We need the call back on the directory url because when they are redirects (eg `https://www.matalan.co.uk/stores/uk/east-of-england/luton` -> `https://www.matalan.co.uk/store/luton/luton`) it goes to the CrawlSpider callback, not `parse_sd`. 
```python
{'atp/brand/Matalan': 232,
'atp/brand_wikidata/Q12061509': 232,
'atp/category/shop/clothes': 232,
'atp/closed_poi': 10,
'atp/field/email/missing': 232,
'atp/field/image/missing': 232,
'atp/field/operator/missing': 232,
'atp/field/operator_wikidata/missing': 232,
'atp/field/phone/missing': 232,
'atp/item_scraped_host_count/www.matalan.co.uk': 232,
'atp/nsi/perfect_match': 232,
'downloader/request_bytes': 353792,
'downloader/request_count': 453,
'downloader/request_method_count/GET': 453, …
```

[Matalan GB] Collect all locations

---

locations/spiders/virgin_active_au.py
locations/spiders/virgin_active_bw_na_za.py
locations/spiders/virgin_active_gb.py
locations/spiders/virgin_active_it.py
locations/spiders/virgin_active_sg.py
locations/spiders/virgin_active_th.py

Fixes #9973, fixes #9974
For IT, which has structured data, I felt like I should have been able to specify `days = DAYS_IT` in the same way I can specify `time_format`. However, it felt like a bit too much of a refactor to do that now.
GB:
```
'atp/brand/Virgin Active': 32,
'atp/brand_wikidata/Q4013942': 32,
'atp/category/leisure/fitness_centre': 32,
'atp/field/city/missing': 32,
'atp/field/country/from_spider_name': 32,
'atp/field/email/missing': 32,
'atp/field/image/missing': 32,
'atp/field/operator/missing': 32,
'atp/field/operator_wikidata/missing': 32,
'atp/field/state/missing': 32,
'atp/field/street_address/missing': 32,
'atp/field/twitter/missing': 32,
'atp/item_scraped_host_count/www.virginactive.co.uk': 32,
'atp/nsi/perfect_match': 32,
```
SG:
```
'atp/brand/Virgin Active': 5, …
```

Virgin Active AU, GB, IT, SG, TH spiders

---

locations/spiders/citiwood_za.py
locations/spiders/hudsons_za.py
locations/spiders/kauai_za.py
locations/spiders/nu_za.py
locations/storefinders/go_review.py

Not all of the urls have digits at the start, although most do. From a sample, this gets a few extra locations per spider.

GoReviewSpider adjust url regex

---

locations/spiders/vida_e_caffe.py

Parse address details where available, fix skipping of vending only locations, fix hours.
```
'atp/brand/Vida e Caffè': 382,
'atp/brand_wikidata/Q7927650': 382,
'atp/category/amenity/cafe': 382,
'atp/field/city/missing': 304,
'atp/field/country/from_reverse_geocoding': 286,
'atp/field/country/missing': 17,
'atp/field/email/missing': 304,
'atp/field/image/missing': 382,
'atp/field/lat/missing': 17,
'atp/field/lon/missing': 17,
'atp/field/opening_hours/missing': 158,
'atp/field/operator/missing': 382,
'atp/field/operator_wikidata/missing': 382,
'atp/field/phone/missing': 119,
'atp/field/postcode/missing': 322,
'atp/field/street_address/missing': 382,
'atp/field/twitter/missing': 382,
'atp/field/website/missing': 382, …
```

[vida_e_caffe] Rename, fix and parse more features

---

locations/spiders/payomatic_us.py

```py
{'atp/brand/Payomatic': 117,
'atp/brand_wikidata/Q48742899': 117,
'atp/category/shop/money_lender': 117,
'atp/field/branch/missing': 117,
'atp/field/country/from_spider_name': 117,
'atp/field/phone/missing': 110,
'atp/item_scraped_host_count/www.payomatic.com': 117,
'atp/nsi/brand_missing': 117,
'downloader/request_bytes': 620,
'downloader/response_bytes': 25672, …
```

New spider: Payomatic (117 locations)

---

locations/spiders/netto_de.py

```python
{'atp/brand/Netto City': 184,
'atp/brand/Netto Getränke-Discount': 81,
'atp/brand/Netto Marken-Discount': 4144,
'atp/category/shop/beverages': 81,
'atp/category/shop/supermarket': 4328,
'atp/field/branch/missing': 4409,
'atp/field/brand_wikidata/missing': 4409,
'atp/field/email/missing': 4409,
'atp/field/image/missing': 4409,
'atp/field/operator/missing': 4409,
'atp/field/operator_wikidata/missing': 4409,
'atp/field/phone/missing': 4409,
'atp/field/twitter/missing': 4409,
'atp/item_scraped_host_count/www.netto-online.de': 4409,
'downloader/request_bytes': 14652711,
'downloader/request_count': 4411,
'downloader/request_method_count/GET': 4411,
'downloader/response_bytes': 170621368,
'downloader/response_count': 4411, …
```

[Netto DE] Fix spider

---

locations/spiders/mountain_america_credit_union_us.py

```py
{'atp/brand/Mountain America Credit Union': 106,
'atp/brand_wikidata/Q6924862': 106,
'atp/category/amenity/bank': 106,
'atp/field/city/missing': 106,
'atp/field/country/from_spider_name': 106,
'atp/field/email/missing': 106,
'atp/field/image/missing': 106,
'atp/field/operator/missing': 106,
'atp/field/operator_wikidata/missing': 106,
'atp/field/postcode/missing': 106,
'atp/field/twitter/missing': 106,
'atp/item_scraped_host_count/www.macu.com': 106,
'atp/nsi/cc_match': 106,
'downloader/request_bytes': 874, …
```

New spider: Mountain America Credit Union (105 locations)

---

locations/spiders/simply_asia_za.py
locations/storefinders/location_bank.py

Broken in the most recent run, they appear to have changed storefinder.
```
'atp/brand/Simply Asia': 54,
'atp/brand_wikidata/Q130358521': 54,
'atp/category/amenity/restaurant': 54,
'atp/item_scraped_host_count/api.locationbank.net': 54,
```

[simply_asia_za] Fix spider and parse addr_full in LocationBankSpider

---

locations/name_suggestion_index.py

`elif "dissolutions" not in wd_json:` was failing due to `wd_json` being `None` when a look up failed.

[Core] Make lookup_wikidata safer

---

locations/spiders/lagkagehuset_dk.py

[Sitemap](https://lagkagehuset.dk/sitemap.xml) approach doesn't look efficient one, hence ignored.
Some of the POIs identified as `closed`, verified with google maps info.
```
{'atp/brand/Lagkagehuset': 110,
'atp/brand_wikidata/Q12323572': 110,
'atp/category/shop/bakery': 110,
'atp/closed_poi': 4,
'atp/field/image/missing': 110,
'atp/field/operator/missing': 110,
'atp/field/operator_wikidata/missing': 110,
'atp/field/state/missing': 110,
'atp/field/twitter/missing': 110,
'atp/item_scraped_host_count/lagkagehuset.dk': 110,
'atp/nsi/cc_match': 110,
'downloader/request_bytes': 613,
'downloader/response_bytes': 30877, …
```

[LagkagehusetDK] Fix spider

---

ci/check_spider_naming_consistency.py
locations/spiders/vodacom_cd.py
locations/spiders/vodacom_mz.py
locations/spiders/vodacom_tz.py
locations/spiders/vodacom_za.py

CD:
```
'atp/brand/Vodacom': 73,
'atp/brand_wikidata/Q1856518': 73,
'atp/category/shop/mobile_phone': 73,
'atp/field/country/from_spider_name': 73,
'atp/field/email/missing': 73,
'atp/field/image/missing': 73,
'atp/field/opening_hours/missing': 73,
'atp/field/operator/missing': 73,
'atp/field/operator_wikidata/missing': 73,
'atp/field/phone/missing': 73,
'atp/field/postcode/missing': 73,
'atp/field/twitter/missing': 73,
'atp/field/website/missing': 73,
'atp/item_scraped_host_count/www.vodacom.cd': 73,
'atp/nsi/cc_match': 73,
```
MZ:
```
'atp/brand/Vodacom': 169,
'atp/brand_wikidata/Q1856518': 169,
'atp/category/shop/mobile_phone': 169,
'atp/field/city/missing': 169,
'atp/field/country/from_spider_name': 169,
'atp/field/email/missing': 169,
'atp/field/image/missing': 169, …
```

Vodacom CD, MZ and TZ spiders

---

locations/spiders/suitsupply.py

```py
{'atp/brand/Suitsupply': 107,
'atp/brand_wikidata/Q17149142': 107,
'atp/category/shop/clothes': 107,
'atp/cdn/cloudflare/response_count': 22,
'atp/cdn/cloudflare/response_status_count/200': 22,
'atp/field/city/missing': 24,
'atp/field/country/from_reverse_geocoding': 24,
'atp/field/image/missing': 107,
'atp/field/operator/missing': 107,
'atp/field/operator_wikidata/missing': 107,
'atp/field/postcode/missing': 24,
'atp/field/state/missing': 50,
'atp/field/street_address/missing': 24,
'atp/field/twitter/missing': 107,
'atp/item_scraped_host_count/suitsupply.com': 190,
'atp/nsi/perfect_match': 107,
'downloader/request_bytes': 21902, …
```

New spider: Suitsupply (107 locations)

---

locations/spiders/krefel_be.py

```
{'atp/brand/Krëfel': 73,
'atp/brand_wikidata/Q3200093': 73,
'atp/category/shop/electronics': 73,
'atp/field/country/from_spider_name': 73,
'atp/field/email/missing': 73,
'atp/field/image/missing': 73,
'atp/field/opening_hours/missing': 73,
'atp/field/operator/missing': 73,
'atp/field/operator_wikidata/missing': 73,
'atp/field/state/missing': 73,
'atp/field/street_address/missing': 73,
'atp/field/twitter/missing': 73,
'atp/item_scraped_host_count/api.krefel.be': 73,
'atp/nsi/perfect_match': 73,
'downloader/request_bytes': 1038,
'downloader/response_bytes': 11317,
'elapsed_time_seconds': 1.750119, …
```

[KrefelBE] Fix spider

---

locations/spiders/mcdonalds_it.py

Fixes #11016
```python
{'atp/brand/McCafé': 619,
"atp/brand/McDonald's": 726,
'atp/brand_wikidata/Q3114287': 619,
'atp/brand_wikidata/Q38076': 726,
'atp/category/amenity/cafe': 619,
'atp/category/amenity/fast_food': 726,
'atp/field/country/from_spider_name': 1345,
'atp/field/email/missing': 1345,
'atp/field/image/missing': 1345,
'atp/field/operator/missing': 1345,
'atp/field/operator_wikidata/missing': 1345,
'atp/field/state/missing': 1345,
'atp/field/twitter/missing': 1345,
'atp/item_scraped_host_count/www.mcdonalds.it': 1345,
'atp/nsi/cc_match': 726,
'atp/nsi/perfect_match': 619,
'downloader/request_bytes': 634,
'downloader/response_bytes': 109273, …
```

[Mcdonalds IT] Flag proxy and collect opening hours

---

locations/spiders/benugo_gb.py

~~still needs improvements, need to figure out how to take the 'cafe' or 'restaurant' bit from the URL (eg. https://www.benugo.com/sites/cafes/greenwich-tea-pavilion/) and convert it to an OSM type~~ 
done
there's also facilites info, not sure how to get that or if it's even supported by ATP

New Spider: Benugo (GB - 84 places)

---

locations/spiders/playa_bowls_us.py

This fixes the `playa_bowls_us` scraper. Previously, it only included the "street address" part of the address in `addr:full`.
Fixes #11116

[playa_bowls_us] Fix address parsing

---

locations/spiders/trade_point_gb.py

store_type is used also elsewhere, lets use the same key for the same type of info in various spiders

use store_type not storeType for trade_point_gb

---

locations/spiders/duffys.py

spotted by comparing to OSM, verified by looking at https://www.duffysmvp.com/
note: OSM often has longer name version. Not sure is it some import, actually used name (dubious, even in logo suffix is in small letters) or some systematic mistake

fix name in duffys

---

locations/spiders/delifrance.py

maybe they use ASCII name somewhere? But Délifrance seems to be at least more dominant (spot check at OSM and their website)

fix name in delifrance

---

locations/spiders/korian_fr.py

```
{'atp/brand/Korian': 267,
'atp/brand_wikidata/Q3198944': 267,
'atp/category/amenity/social_facility': 267,
'atp/field/branch/missing': 267,
'atp/field/opening_hours/missing': 267,
'atp/field/state/missing': 267,
'atp/field/twitter/missing': 5,
'atp/item_scraped_host_count/www.korian.fr': 267,
'atp/nsi/perfect_match': 267,
'atp/operator/Korian': 267,
'atp/operator_wikidata/Q3198944': 267,
'downloader/request_bytes': 116617,
'downloader/request_count': 269,
'downloader/request_method_count/GET': 269,
'downloader/response_bytes': 17293871,
'downloader/response_count': 269,
'downloader/response_status_count/200': 269,
'elapsed_time_seconds': 6.854602,
'finish_time': datetime.datetime(2024, 10, 15, 15, 14, 45, 382946, …
```

[Korian FR] Fix Spider

---

locations/spiders/taco_palenque.py

Adds a spider for [Taco Palenque](https://tacopalenque.com/) a fast food chain in the US and Mexico.
The addresses from the store locator are very messy, so I had to try to extract the state from the string to help the geocoder disambiguate restaurants that are very close to the US-Mexico border. This could be avoided by only matching within the country boundaries, but I'm not sure if this is possible.
Additionally, I have manually applied the fast food category, since NSI has not released since I added it (https://github.com/osmlab/name-suggestion-index/pull/10041)
This is my first spider, so please let me know if I am reinventing the wheel with the state matching!

Add taco_palenque spider

---

locations/spiders/eathappy.py
locations/spiders/yuzu_de.py

[Eat Happy](https://www.eathappygroup.com/en/) is a sushi store-in-store chain in supermarkets in AT, DE and IT.
This also adds [Yuzu](https://www.yuzu-food.com/) which is a smaller sub-brand of the same group in DE.
```
2024-10-15 22:45:10 [scrapy.statscollectors] INFO: Dumping Scrapy stats:
{'atp/brand/Eat Happy': 3343,
'atp/brand_wikidata/Q125578025': 3343,
'atp/category/amenity/fast_food': 3343,
'atp/field/branch/missing': 3343,
'atp/field/city/missing': 3343,
'atp/field/email/missing': 3343,
'atp/field/image/missing': 3343,
'atp/field/operator/missing': 3343,
'atp/field/operator_wikidata/missing': 3343,
'atp/field/phone/missing': 3343,
'atp/field/postcode/missing': 3343,
'atp/field/state/missing': 3343,
'atp/field/street_address/missing': 3343, …
```

[eathappy] Add spider (3343 locations)

---

locations/spiders/papa_johns.py

Dropped duplicates and dropped address as "branch", 
```python
{"atp/brand/Papa John's": 3366,
'atp/brand_wikidata/Q2759586': 3366,
'atp/category/amenity/fast_food': 3366,
'atp/cdn/cloudflare/response_count': 3370,
'atp/cdn/cloudflare/response_status_count/200': 3370,
'atp/field/branch/missing': 3366,
'atp/field/email/missing': 3366,
'atp/field/image/missing': 3366,
'atp/field/opening_hours/invalid': 7,
'atp/field/operator/missing': 3366,
'atp/field/operator_wikidata/missing': 3366,
'atp/field/twitter/missing': 3366,
'atp/item_scraped_host_count/locations.papajohns.com': 3366,
'atp/nsi/cc_match': 3366,
'downloader/request_bytes': 1887582,
'downloader/request_count': 3372,
'downloader/request_method_count/GET': 3372, …
```

[Papa John's] Fix spider

---

tests/test_name_suggestion_index.py

The NSI test was failing because the Wikidata record for McDonald's got other social media identities than the one we were testing for. Website seems to come back pretty reliably, so switching to that.

Fix McDonald's lookup test for NSI

---

locations/spiders/kum_and_go.py
locations/spiders/kum_and_go_us.py

```
{'atp/brand/Kum & Go': 304,
'atp/brand_wikidata/Q6443340': 304,
'atp/category/amenity/fuel': 303,
'atp/category/shop/convenience': 1,
'atp/cdn/cloudflare/response_count': 368,
'atp/cdn/cloudflare/response_status_count/200': 368,
'atp/field/branch/missing': 304,
'atp/field/email/missing': 304,
'atp/field/opening_hours/missing': 13,
'atp/field/operator/missing': 304,
'atp/field/operator_wikidata/missing': 304,
'atp/item_scraped_host_count/locations.kumandgo.com': 304,
'atp/nsi/cc_match': 304,
'downloader/request_bytes': 139736,
'downloader/request_count': 368,
'downloader/request_method_count/GET': 368,
'downloader/response_bytes': 4375471,
'downloader/response_count': 368,
'downloader/response_status_count/200': 368,
'dupefilter/filtered': 51,
'elapsed_time_seconds': 6.657869, …
```

[KumAndGo] Fix spider

---

locations/spiders/la_salsa.py
locations/spiders/la_salsa_us.py

No. of locations reduced to `5`. 
Ref: https://en.wikipedia.org/wiki/La_Salsa 
```
{'atp/brand/La Salsa': 5,
'atp/brand_wikidata/Q48835190': 5,
'atp/category/amenity/fast_food': 5,
'atp/field/branch/missing': 5,
'atp/field/country/from_reverse_geocoding': 5,
'atp/field/operator/missing': 5,
'atp/field/operator_wikidata/missing': 5,
'atp/item_scraped_host_count/www.lasalsa.com': 5,
'atp/nsi/perfect_match': 5,
'downloader/request_bytes': 2710,
'downloader/request_count': 7,
'downloader/request_method_count/GET': 7,
'downloader/response_bytes': 51576,
'downloader/response_count': 7,
'elapsed_time_seconds': 7.859487, …
```

[LaSalsa] Fix spider

---

locations/spiders/middys_au.py

Fixes : code has been refactored to fix spider.
{"atp/brand/Middy's": 111,
'atp/brand_wikidata/Q117157352': 111,
'atp/category/shop/trade': 111,
'atp/field/branch/missing': 111,
'atp/field/country/from_spider_name': 111,
'atp/field/image/missing': 111,
'atp/field/opening_hours/missing': 111,
'atp/field/operator/missing': 111,
'atp/field/operator_wikidata/missing': 111,
'atp/field/twitter/missing': 111,
'atp/item_scraped_host_count/www.middys.com.au': 111,
'atp/nsi/perfect_match': 111,
'downloader/request_bytes': 1438,
'downloader/response_bytes': 191777,
'elapsed_time_seconds': 4.184181,
'finish_time': …

[MiddysAU] Fix Spider

---

locations/spiders/intersport_fr.py

[Intersport](https://www.intersport.fr/) shops in FR and BE.
```
2024-10-16 22:41:39 [scrapy.statscollectors] INFO: Dumping Scrapy stats:
{'atp/brand/Intersport': 832,
'atp/brand_wikidata/Q666888': 832,
'atp/category/shop/sports': 832,
'atp/field/branch/missing': 832,
'atp/field/city/missing': 832,
'atp/field/email/missing': 832,
'atp/field/image/missing': 832,
'atp/field/opening_hours/missing': 832,
'atp/field/operator/missing': 832,
'atp/field/operator_wikidata/missing': 832,
'atp/field/phone/invalid': 225,
'atp/field/phone/missing': 47,
'atp/field/postcode/missing': 832,
'atp/field/state/missing': 832,
'atp/field/street_address/missing': 832,
'atp/field/twitter/missing': 832,
'atp/field/website/missing': 832,
'atp/item_scraped_host_count/www.intersport.fr': 832,
'atp/nsi/cc_match': …
```

[intersport_fr] Add spider (832 locations)

---

locations/spiders/leaders_gb.py
locations/spiders/leaders_romans_group_gb.py

Fixed `LeadersGBSpider` and modified it to add [Romans](https://www.wikidata.org/wiki/Q113562519) brand locations, which belongs to the same parent group called [Leaders Romans Group](https://www.wikidata.org/wiki/Q113562584).
```
{'atp/brand/Leaders': 96,
'atp/brand/Romans': 30,
'atp/brand_wikidata/Q111522674': 96,
'atp/brand_wikidata/Q113562519': 30,
'atp/category/office/estate_agent': 126,
'atp/field/city/missing': 126,
'atp/field/country/from_spider_name': 126,
'atp/field/email/missing': 126,
'atp/field/image/missing': 126,
'atp/field/opening_hours/missing': 126,
'atp/field/operator/missing': 126,
'atp/field/operator_wikidata/missing': 126,
'atp/field/state/missing': 126,
'atp/field/street_address/missing': 126,
'atp/field/twitter/missing': 126, …
```

[LeadersRomansGroupGB] Fix Leaders Spider and update it to add Romans brand  belonging to Leaders Romans Group

---

locations/spiders/house_au.py

Resolves #10985
I used `shop=household_linen` to match the other House Bed & Bath locations, but I can update to `shop=houseware` (across the board?) if that's preferred, per the comments on #10985

Update House AU spider for additional B&B locations

---

locations/spiders/white_castle.py

Review notes/potential outstanding issues:
- https://whitecastle.com/locations/0000000 and https://www.whitecastle.com/locations/1402 seem to represent the same restaurant. They have "different addresses" in the sense that that is on "Daryl Carter Parkway" and the other "Daryl Carter Pkwy", and different `storeNumber`s (and, somehow, different hours?) but otherwise seem to represent the same store. Not sure if this is something alltheplaces wants to try to filter out somehow.
- I'm not sure I got all the date parsing right, though spot checks look okay.
- I _think_ their `robots.txt` is probably not intended to block everything (why would they block GoogleBot?), but regardless, are we okay with ignoring that? I wasn't able to find anything about alltheplaces' stance on that. I'm happy to …

Update White Castle spider

---

locations/microdata_parser.py
locations/spiders/comerica_bank_us.py

Depends on  #11171.
```py
{'atp/brand/Comerica Bank': 474,
'atp/brand_wikidata/Q1114148': 474,
'atp/category/amenity/atm': 83,
'atp/category/amenity/bank': 381,
'atp/category/office/financial': 10,
'atp/field/branch/missing': 83,
'atp/field/email/missing': 474,
'atp/field/image/missing': 474,
'atp/field/name/missing': 93,
'atp/field/opening_hours/missing': 101,
'atp/field/operator/missing': 391,
'atp/field/operator_wikidata/missing': 391,
'atp/field/twitter/missing': 474,
'atp/item_scraped_host_count/locations.comerica.com': 475,
'atp/nsi/cc_match': 464,
'atp/nsi/match_failed': 10,
'atp/operator/Comerica Bank': 83,
'atp/operator_wikidata/Q1114148': 83,
'downloader/request_bytes': 180778,
'downloader/request_count': 477, …
```

 New spider: Comerica Bank (474 locations) 

---

locations/microdata_parser.py
locations/spiders/the_coffee_bean_and_tea_leaf.py

This does overlap some with the_coffee_bean_and_tea_leaf_sg, but that has more locations inside Singapore and this has more locations inside Singapore. Depends on #11171.
```py
{'atp/brand/The Coffee Bean & Tea Leaf': 860,
'atp/brand_wikidata/Q1141384': 860,
'atp/category/amenity/cafe': 860,
'atp/field/city/missing': 119,
'atp/field/country/from_reverse_geocoding': 333,
'atp/field/email/missing': 860,
'atp/field/image/dropped': 110,
'atp/field/image/missing': 860,
'atp/field/opening_hours/missing': 774,
'atp/field/operator/missing': 860,
'atp/field/operator_wikidata/missing': 860,
'atp/field/phone/missing': 693,
'atp/field/postcode/missing': 243, …
```

New spider: The Coffee Bean & Tea Leaf (860 locations)

---

locations/spiders/sushi_daily.py

Add [Sushi Daily](https://sushidaily.com/), a sushi store-in-store chain in GB, FR, IT, NL, ES, DE, PT, BE, MX, SE, FI, AE.

[sushi_daily] Add spider (1584 locations)

---

locations/spiders/mavis_us.py

`Structured Data` is no longer present, hence spider code refactored to utilize `JSON Blob`.
```
{'atp/brand/Mavis': 1553,
'atp/brand_wikidata/Q65058420': 1553,
'atp/category/shop/tyres': 1553,
'atp/field/branch/missing': 1553,
'atp/field/city/missing': 1553,
'atp/field/country/from_spider_name': 1553,
'atp/field/email/missing': 1553,
'atp/field/image/missing': 1553,
'atp/field/opening_hours/missing': 1553,
'atp/field/operator/missing': 1553,
'atp/field/operator_wikidata/missing': 1553,
'atp/field/postcode/missing': 1553,
'atp/field/street_address/missing': 1553,
'atp/field/twitter/missing': 1553,
'atp/item_scraped_host_count/www.mavis.com': 1553,
'atp/nsi/perfect_match': 1553, …
```

[Mavis US] Fix spider

---

locations/spiders/johnstones_decorating_centre.py

Fixes : Code has been refactored to fix spider.
{"atp/brand/Johnstone's Decorating Centre": 197,
'atp/brand_wikidata/Q121742106': 197,
'atp/category/shop/paint': 197,
'atp/field/branch/missing': 197,
'atp/field/city/missing': 197,
'atp/field/country/from_reverse_geocoding': 197,
'atp/field/email/missing': 197,
'atp/field/image/missing': 197,
'atp/field/opening_hours/missing': 197,
'atp/field/operator/missing': 197,
'atp/field/operator_wikidata/missing': 197,
'atp/field/phone/missing': 197,
'atp/field/street_address/missing': 197,
'atp/field/twitter/missing': 197,
'atp/field/website/missing': 197,
'atp/item_scraped_host_count/www.johnstonesdc.com': 197,
'atp/nsi/perfect_match': 197, …

[Johnstone's Decorating Centre] Fix Spider

---

locations/spiders/mens_wearhouse.py

`Fixes : Code has been refactored to fix spider`
{"atp/brand/Men's Wearhouse": 629,
'atp/brand_wikidata/Q57405513': 629,
'atp/category/shop/clothes': 629,
'atp/cdn/cloudflare/response_count': 630,
'atp/cdn/cloudflare/response_status_count/200': 630,
'atp/field/branch/missing': 629,
'atp/field/email/missing': 629,
'atp/field/image/dropped': 629,
'atp/field/image/missing': 629,
'atp/field/operator/missing': 629,
'atp/field/operator_wikidata/missing': 629,
'atp/field/twitter/missing': 629,
'atp/item_scraped_host_count/www.menswearhouse.com': 629,
'atp/nsi/perfect_match': 629,
'downloader/request_bytes': 1755872,
'downloader/request_count': 642,
'downloader/request_method_count/GET': 642,
'downloader/response_bytes': 52729641,
'downloader/response_count': 642, …

[MensWearhouse] Fix Spider

---

locations/spiders/fraser_gb.py
locations/spiders/frasers_gb.py
locations/spiders/sports_direct.py

```python
{'atp/brand/Field & Trek': 13,
'atp/brand/Sportmaster': 24,
'atp/brand/Sports Direct': 757,
'atp/brand_wikidata/Q61062124': 37,
'atp/brand_wikidata/Q7579661': 757,
'atp/category/shop/sports': 794,
'atp/field/city/missing': 794,
'atp/field/country/from_reverse_geocoding': 794,
'atp/field/email/missing': 794,
'atp/field/image/missing': 794,
'atp/field/operator/missing': 794,
'atp/field/operator_wikidata/missing': 794,
'atp/field/postcode/missing': 278,
'atp/field/twitter/missing': 794,
'atp/item_scraped_host_count/www.sportsdirect.com': 794,
'atp/nsi/perfect_match': 794,
'downloader/request_bytes': 1480638,
'downloader/request_count': 809,
'downloader/request_method_count/GET': 809, …
```

[Sports Direct] Add spider

---

locations/spiders/intersport_gr.py
locations/spiders/metro_cash_and_carry.py

```
{'atp/brand/Intersport': 61,
'atp/brand_wikidata/Q666888': 61,
'atp/category/shop/sports': 61,
'atp/field/country/from_spider_name': 61,
'atp/field/image/missing': 61,
'atp/field/opening_hours/missing': 61,
'atp/field/operator/missing': 61,
'atp/field/operator_wikidata/missing': 61,
'atp/field/twitter/missing': 61,
'atp/item_scraped_host_count/www.intersport.gr': 122,
'atp/nsi/cc_match': 61,
'downloader/request_bytes': 547,
'downloader/response_bytes': 116614,
'elapsed_time_seconds': 2.171875,
'finish_time': datetime.datetime(2024, 10, 23, 15, 48, 35, 486563, tzinfo=datetime.timezone.utc), …
```

[Intersport GR] Fix spider

---

locations/spiders/kruidvat.py
locations/spiders/metro_cash_and_carry.py

{'atp/brand/Kruidvat': 1462,
'atp/brand_wikidata/Q2226366': 1462,
'atp/category/missing': 1462,
'atp/field/branch/missing': 1462,
'atp/field/city/missing': 1462,
'atp/field/country/from_website_url': 1462,
'atp/field/email/missing': 1462,
'atp/field/image/missing': 1462,
'atp/field/lat/missing': 178,
'atp/field/lon/missing': 178,
'atp/field/operator/missing': 1462,
'atp/field/operator_wikidata/missing': 1462,
'atp/field/phone/missing': 1462,
'atp/field/street_address/missing': 1462,
'atp/field/twitter/missing': 1462,
'atp/geometry/null_island': 178,
'atp/item_scraped_host_count/www.kruidvat.be': 340,
'atp/item_scraped_host_count/www.kruidvat.nl': 1122,
'atp/nsi/match_failed': 1462, …

[Kruidvat] Fix Spider

---

locations/spiders/publix_us.py

```python
{'atp/brand/Publix': 3114,
'atp/brand_wikidata/Q672170': 3114,
'atp/category/amenity/pharmacy': 1305,
'atp/category/multiple': 1305,
'atp/category/shop/alcohol': 371,
'atp/category/shop/supermarket': 1438,
'atp/closed_poi': 3,
'atp/field/branch/missing': 1665,
'atp/field/country/from_spider_name': 3114,
'atp/field/email/missing': 3114,
'atp/field/opening_hours/missing': 68,
'atp/field/operator/missing': 3114,
'atp/field/operator_wikidata/missing': 3114,
'atp/field/phone/missing': 58,
'atp/field/twitter/missing': 3114,
'atp/item_scraped_host_count/services.publix.com': 3114,
'atp/nsi/cc_match': 2743,
'atp/nsi/match_failed': 371,
'downloader/request_bytes': 749,
'downloader/response_bytes': 408134, …
```

[Publix US] Fix spider

---

locations/hours.py

In Slovak, `Utorok` and `Ut` is the correct spelling of Tuesday, but I found `Útorok` and `Út` in the wid. We already allow `Útorok`, so it makes sense to also accept `Út`.

Add Út alias for Tuesday in Slovak

---

locations/google_url.py
tests/test_google_url.py

I encountered some sites in Czechia which use `maps.google.cz` domain instead of `maps.google.com`. There are probably many, so it would make sense to allow unified parsing for all of them.
I chose the regex `google(\.[a-z]{2,3})?\.[a-z]{2,3}/` to account also for two-level domains such as `.co.uk`.
Also, I saw that URL are often percent-encoded. I hope it does not break anything to run `urllib.parse.unquote` before any parsing starts. It passes the test suite.

Allow alternative Google domains

---

locations/spiders/guitar_center.py
locations/storefinders/rio_seo.py

This is something I noticed while developing RioSeoSpider. Most, but not all, Rio sites use the "maps"-less domain for the initial getAutocompleteData request. I saw that the "maps"-ful domain worked the same for that request so used it instead, to make the code simpler. Apparently it doesn't always work. If this also changes for other spiders I/we might want to find some way to encode the differences.
Since this affects all RioSeo spiders, I re-ran all of them to make sure they don't error.

Workaround to fix Guitar Center

---

locations/spiders/meta.py

Used `chompjs` to fix JSON decode error.
```
{'atp/brand/Meta': 127,
'atp/brand_wikidata/Q380': 127,
'atp/category/office/it': 81,
'atp/category/telecom/data_center': 46,
'atp/field/city/missing': 127,
'atp/field/country/from_reverse_geocoding': 127,
'atp/field/email/missing': 127,
'atp/field/image/missing': 127,
'atp/field/opening_hours/missing': 127,
'atp/field/operator/missing': 81,
'atp/field/operator_wikidata/missing': 81,
'atp/field/phone/missing': 127,
'atp/field/postcode/missing': 127,
'atp/field/street_address/missing': 127,
'atp/field/twitter/missing': 127,
'atp/item_scraped_host_count/www.metacareers.com': 127,
'atp/nsi/cc_match': 127,
'atp/operator/Meta': 46,
'atp/operator_wikidata/Q380': 46, …
```

[Meta] Fix  Spider

---

locations/spiders/bonmarche_gb.py

I've just done a comparison between OSM and the store finder and I think at least 3 stores are missing from the spider which are on the website - Folkestone, Oban and Ayr. 
So I assume that the population number needs adjusting down. I'm not sure what value it should be though.

[Bonmarche GB] Add more towns

---

locations/categories.py
locations/spiders/avalon_us.py

```py
{'atp/brand/AVA': 30,
'atp/brand/Avalon': 185,
'atp/brand/Kanso': 3,
'atp/brand/eaves': 45,
'atp/brand_wikidata/Q64665938': 263,
'atp/category/landuse/residential': 263,
'atp/field/branch/missing': 263,
'atp/field/country/from_spider_name': 263,
'atp/field/opening_hours/missing': 263,
'atp/field/operator/missing': 263,
'atp/field/operator_wikidata/missing': 263,
'atp/field/twitter/missing': 263,
'atp/item_scraped_host_count/www.avaloncommunities.com': 263,
'atp/nsi/perfect_match': 263,
'downloader/request_bytes': 131525,
'downloader/request_count': 267,
'downloader/request_method_count/GET': 267,
'downloader/response_bytes': 23585799,
'downloader/response_count': 267,
'downloader/response_status_count/200': 265, …
```

New spider: Avalon apartments (263 locations)

---

Pipfile.lock
locations/spiders/gbfs.py

There has been a [PR](https://github.com/alltheplaces/alltheplaces/pull/10217) open for a while related to improving brand mapping.
The brand Dott represents a large number of POIs (65k +) in this spider.  The master .csv contains links to station information that include several duplicates under different "Name".  (eg. Dott Marseille, Dott Seville, Dott Namur, amongst many others, all link to the same station information jsons)   "Name" is being applied as brand if not provided in the brand mapping dict.  Causing incorrect brand names to be applied to various locations.  
My thought was to quickly fix this brand for now, and in the above mentioned PR other work could still be done to streamline branding.
```
{'atp/brand/2EM Car Sharing': 1779,
'atp/brand/AAR Bike': 120,
'atp/brand/AB mit …
```

[gbfs] Update Brand Mapping for Dott

---

locations/spiders/fio_banka_atm.py

Follow-up to #11249, this one contains ATMs.
Peculiarities:
- No ref-like field, using goo.gl identifier where available, street as a fallback
- City is parsed from header by removing notes in parantheses
- Some branches contain Google Maps links, coordinates parsing as a fallback
- Most branches are non-stop
- There is currently no way to specify holiday (PH) opening hours

[fio_banka_atm] Add spider (242 locations)

---

locations/spiders/fio_banka_atm.py

I originally thought that parsing the coordinates from the page might be prone to bugs. But is turns out that geocoding in Google Maps URL is far less accurate. Most locations remain unchanged, but 30 are moved a little, one confused Google Maps with the same street in a different city and one Czech ATM appeared in USA.

[fio_banka_atm] Drop Google Maps coordinates extraction

---

locations/mapy_cz_url.py
tests/test_mapy_cz_url.py

[Mapy.cz](https://mapy.cz) is a popular online map in Central Europe built upon OSM data. I have seen some website using it instead of Google Maps to link to the coordinates. Their "share" feature and [iframe](https://developer.mapy.cz/en/further-uses-of-mapycz/iframe/) both use magic short-links, but they support URL with [coordinates](https://developer.mapy.cz/en/further-uses-of-mapycz/mapy-cz-url/) as well (e.g. [here](https://manufakturashop.com/stores/506)).
I built an implementation prototype which covers my use case. Happy to hear comments whether this is desired in ATP.

Add mapy_cz_url extractor

---

locations/spiders/optiker_bode_de.py

Add [Optiker Bode](https://www.optiker-bode.de/), an optician chain in DE

[optiker_bode_de] Add spider (81 locations)

---

locations/spiders/ibis_nl.py

We get desired 25 POIs from `Accor` spider. Broken `Ibis NL` spider can be deleted, instead of fixing.

[Ibis NL] Delete  broken spider, locations already covered by Accor Spider

---

locations/spiders/intersport_es.py

https://www.intersport.es/tiendas – Spanish shops of the sport goods chain
```
2024-11-05 20:16:24 [scrapy.statscollectors] INFO: Dumping Scrapy stats:
{'atp/brand/Intersport': 131,
'atp/brand_wikidata/Q666888': 131,
'atp/category/shop/sports': 131,
'atp/field/branch/missing': 131,
'atp/field/image/missing': 131,
'atp/field/operator/missing': 131,
'atp/field/operator_wikidata/missing': 131,
'atp/field/state/missing': 131,
'atp/field/twitter/missing': 131,
'atp/item_scraped_host_count/www.intersport.es': 131,
'atp/nsi/cc_match': 131,
```

[intersport_es] Add spider (131 locations)

---

locations/spiders/hyundai_ee_fi_lt_lv.py

Fix non running spider
File "/home/ubuntu/locations/spiders/hyundai_ee_fi_lt_lv.py", line 25, in post_process_item
item["state"] = feature["region"]["fi"] or None
~~~~~~~^^^^^^^^^^
KeyError: 'region'

[Hyundai EE FI LT LV] Remove state as not populated

---

locations/spiders/lasik_plus_us.py

Works fine from `IN`, failed in previous runs. Might require proxy.
```
{'atp/brand/LasikPlus': 52,
'atp/brand_wikidata/Q126111242': 52,
'atp/category/amenity/clinic': 52,
'atp/category/multiple': 52,
'atp/cdn/cloudflare/response_count': 143,
'atp/cdn/cloudflare/response_status_count/200': 143,
'atp/field/branch/missing': 52,
'atp/field/email/missing': 52,
'atp/field/state/from_reverse_geocoding': 52,
'atp/item_scraped_host_count/www.lasikplus.com': 52,
'atp/nsi/perfect_match': 52,
'atp/structured_data/unmapped/payment_accepted/Care Credit': 139,
'atp/structured_data/unmapped/payment_accepted/etc.': 139,
'atp/structured_data/unmapped/payment_accepted/in-house financing': …
```

[Lasik Plus US] Flag as requires proxy

---

locations/dict_parser.py
locations/spiders/vodafone_cz.py

```python
{'atp/brand/Vodafone': 80,
'atp/brand_wikidata/Q122141': 80,
'atp/category/shop/mobile_phone': 80,
'atp/field/branch/missing': 80,
'atp/field/country/from_spider_name': 80,
'atp/field/image/missing': 80,
'atp/field/operator/missing': 80,
'atp/field/operator_wikidata/missing': 80,
'atp/field/state/missing': 80,
'atp/field/twitter/missing': 80,
'atp/item_scraped_host_count/www.vodafone.cz': 80,
'atp/nsi/cc_match': 80,
'downloader/request_bytes': 833,
'downloader/response_bytes': 38417,
'elapsed_time_seconds': 2.35174, …
```

[vodafone_cz] Add spider (80 locations)

---

locations/spiders/harvester_gb.py

[Sitemap](https://www.harvester.co.uk/sitemap.xml) is not reachable, hence switched to `CrawlSpider` .
```
{'atp/brand/Harvester': 150,
'atp/brand_wikidata/Q5676915': 150,
'atp/category/amenity/restaurant': 150,
'atp/cdn/cloudflare/response_count': 157,
'atp/cdn/cloudflare/response_status_count/200': 157,
'atp/field/branch/missing': 150,
'atp/field/email/missing': 150,
'atp/field/image/dropped': 150,
'atp/field/image/missing': 150,
'atp/field/operator/missing': 150,
'atp/field/operator_wikidata/missing': 150,
'atp/item_scraped_host_count/www.harvester.co.uk': 150,
'atp/nsi/perfect_match': 150,
'downloader/request_bytes': 88451,
'downloader/request_count': 157,
'downloader/request_method_count/GET': 157, …
```

[Harvester GB] Fix spider

---

locations/spiders/leen_bakker_nl.py

Fixes : removed redundant spaces using replace to update the time for opening_hours
{'atp/brand/Leen Bakker': 101,
'atp/brand_wikidata/Q3333662': 101,
'atp/category/shop/furniture': 101,
'atp/field/country/from_spider_name': 101,
'atp/field/email/missing': 101,
'atp/field/state/missing': 101,
'atp/item_scraped_host_count/www.leenbakker.nl': 101,
'atp/nsi/perfect_match': 101,
'downloader/request_bytes': 622,
'downloader/response_bytes': 8134,
'elapsed_time_seconds': 2.765944, …

[LeenBakkerNL] Fix Spider

---

locations/spiders/debra_gb.py

Updated `sitemap_rules` and `xpaths` to fix the spider.  Added more attributes available.
```
{'atp/brand/Debra': 89,
'atp/brand_wikidata/Q104535435': 89,
'atp/category/shop/charity': 89,
'atp/item_scraped_host_count/www.debra.org.uk': 89,
'atp/nsi/perfect_match': 89,
'downloader/request_bytes': 35826,
'downloader/request_count': 97,
'downloader/request_method_count/GET': 97,
'downloader/response_bytes': 2307095,
'downloader/response_count': 97, …
```

[Debra GB] Fix spider

---

locations/spiders/woolworths_au.py
locations/spiders/woolworths_nz.py

User agent spoofing required for both spiders or else timeouts occur.
Countdown was rebranded to Woolworths per
https://www.woolworthsgroup.com.au/au/en/media/latest-news/2023/countdown-to-woolworths.html and this process has partially completed, even though the old Countdown store locator API is still being used for the timebeing.

woolworths_au: fix, countdown_nz: fix and rebrand to woolworths_nz

---

locations/spiders/a101_tr.py

The website API expect more characters in geohash, throwing error message:
```
{
"message": "Invalid input/output data for queryStringModel: NearestStoresParameters.",
"modelName": "NearestStoresParameters",
"modelType": "queryStringModel",
"code": "VALIDATION",
"issues": [
{
"instancePath": "/geoHash",
"schemaPath": "#/properties/geoHash/minLength",
"keyword": "minLength",
"params": {
"limit": 9
},
"message": "must NOT have fewer than 9 characters"
}
]
}
```

[a101_tr] fix spider

---

locations/spiders/fuzzys_taco_shop_us.py

Ultimate POI page url is no longer available for `CrawlSpider` , hence code updated to fix the spider.
```
{"atp/brand/Fuzzy's Taco Shop": 117,
'atp/brand_wikidata/Q85762348': 117,
'atp/category/amenity/fast_food': 117,
'atp/field/branch/missing': 117,
'atp/field/opening_hours/missing': 117,
'atp/item_scraped_host_count/fuzzystacoshop.com': 117,
'atp/nsi/perfect_match': 117,
'downloader/request_bytes': 88709,
'downloader/request_count': 229,
'downloader/request_method_count/GET': 229,
'downloader/response_bytes': 10177697,
'downloader/response_count': 229,
'downloader/response_status_count/200': 229, …
```

[Fuzzys Taco Shop US] Fix spider

---

locations/spiders/douglas.py

Add [Douglas](https://www.douglas.de/), a perfumery/cosmetics chain in Europe.
| country | count |
| ------- | -----:|
| IT      |   371 |
| DE      |   333 |
| PL      |   154 |
| NL      |   106 |
| ES      |    76 |
| AT      |    36 |
| CH      |    11 |
| BE      |     5 |
| AD      |     4 |
```
2024-11-14 21:01:12 [scrapy.statscollectors] INFO: Dumping Scrapy stats:
{'atp/brand/Douglas': 1095,
'atp/brand_wikidata/Q2052213': 1095,
'atp/category/shop/perfumery': 1095,
'atp/field/branch/missing': 1095,
'atp/field/email/missing': 1095,
'atp/field/image/missing': 1095,
'atp/field/operator/missing': 1095,
'atp/field/operator_wikidata/missing': 1095,
'atp/field/phone/missing': 1095,
'atp/field/state/missing': 901,
'atp/field/street_address/missing': …
```

[douglas] Add spider (1096 locations)

---

locations/spiders/fitness19_us.py

`Structured Data` is no longer available, hence code refactored to adapt website changes. Also [sitemap](https://www.fitness19.com/page-sitemap.xml) doesn't contain ultimate POI urls.
Some `urls` redirect to alternate [website](https://www.fit19.com/locations) of this brand, e.g. https://www.fitness19.com/centers/american-canyon/
```
{'atp/brand/Fitness 19': 64,
'atp/brand_wikidata/Q121787953': 64,
'atp/category/leisure/fitness_centre': 64,
'atp/cdn/cloudflare/response_count': 68,
'atp/cdn/cloudflare/response_status_count/200': 68,
'atp/field/city/missing': 34,
'atp/field/email/missing': 64,
'atp/field/image/missing': 64,
'atp/field/operator/missing': 64,
'atp/field/operator_wikidata/missing': 64, …
```

[Fitness19 US] Fix spider

---

locations/spiders/spar_dk.py

Add Danish branches of the [Spar](https://spar.dk/) supermarket chain.
```
2024-11-16 16:09:54 [scrapy.statscollectors] INFO: Dumping Scrapy stats:
{'atp/brand/Spar': 142,
'atp/brand_wikidata/Q610492': 142,
'atp/category/shop/supermarket': 142,
'atp/field/branch/missing': 142,
'atp/field/country/from_spider_name': 142,
'atp/field/email/missing': 142,
'atp/field/image/missing': 142,
'atp/field/operator/missing': 142,
'atp/field/operator_wikidata/missing': 142,
'atp/field/state/missing': 142,
'atp/field/twitter/missing': 142,
'atp/field/website/missing': 109,
'atp/item_scraped_host_count/spar.dk': 142,
'atp/nsi/cc_match': 142,
```

[spar_dk] Add spider (142 locations)

---

locations/spiders/cosmo_de.py
locations/spiders/essanelle_de.py
locations/spiders/hair_express_de.py
locations/spiders/klier_de.py
locations/spiders/supercut_de.py
locations/storefinders/klier_hair_group.py

Klier Hair Group is a hairdresser chain in DE with several brands:
- Cosmo
- Essanelle
- Hair Express
- Klier
- Supercut
They share the same website structure, so they can be scraped using a common storefinder class.

[klier_hair_group] Add spiders (728 locations)

---

locations/spiders/burgerme_de.py

Add [burgerme](https://www.burgerme.de/), a burger chain in DE.
```
2024-11-17 17:43:57 [scrapy.statscollectors] INFO: Dumping Scrapy stats:
{'atp/brand/burgerme': 140,
'atp/brand_wikidata/Q108866856': 140,
'atp/category/amenity/fast_food': 140,
'atp/field/branch/missing': 140,
'atp/field/country/from_spider_name': 140,
'atp/field/email/missing': 140,
'atp/field/image/missing': 140,
'atp/field/opening_hours/missing': 140,
'atp/field/operator/missing': 140,
'atp/field/operator_wikidata/missing': 140,
'atp/field/phone/missing': 140,
'atp/field/state/missing': 140,
'atp/item_scraped_host_count/www.burgerme.de': 140,
'atp/nsi/perfect_match': 140,
```

[burgerme_de] Add spider (140 locations)

---

locations/spiders/das_futterhaus.py

{'atp/brand/Das Futterhaus': 442,
'atp/brand_wikidata/Q1167914': 442,
'atp/category/shop/pet': 442,
'atp/field/branch/missing': 442,
'atp/field/email/missing': 442,
'atp/field/image/missing': 442,
'atp/field/operator/missing': 442,
'atp/field/operator_wikidata/missing': 442,
'atp/field/twitter/missing': 442,
'atp/item_scraped_host_count/www.futterhaus.de': 442,
'atp/nsi/perfect_match': 442,
'downloader/request_bytes': 1233075,
'downloader/request_count': 447,
'downloader/request_method_count/GET': 447,
'downloader/response_bytes': 42452729,
'downloader/response_count': 447,
'downloader/response_status_count/200': 447,
'elapsed_time_seconds': 545.850732, …

[DasFutterhaus] Fix Spider

---

locations/spiders/elysium_healthcare.py

`Fixes : set robots.txt as False to fix spider`
{'atp/brand/Elysium Healthcare': 98,
'atp/brand_wikidata/Q39086513': 98,
'atp/category/amenity/social_facility': 44,
'atp/category/healthcare/centre': 54,
'atp/category/multiple': 5,
'atp/field/branch/missing': 98,
'atp/field/city/missing': 98,
'atp/field/email/missing': 98,
'atp/field/image/missing': 98,
'atp/field/opening_hours/missing': 98,
'atp/field/operator/missing': 98,
'atp/field/operator_wikidata/missing': 98,
'atp/field/phone/missing': 49,
'atp/field/postcode/missing': 24,
'atp/field/state/missing': 98,
'atp/field/street_address/missing': 98,
'atp/field/twitter/missing': 98,
'atp/item_scraped_host_count/www.elysiumhealthcare.co.uk': 98, …

[ElysiumHealthcare] Fix Spider

---

locations/spiders/fit_active.py

Add [FitActive](https://www.fitactive.it/), a fitness chain from IT.
141 locations are in IT (of which 2 with invalid coordinates), but also 2 in RO, 1 in ES and 1 in BR.
```
2024-11-20 21:30:27 [scrapy.statscollectors] INFO: Dumping Scrapy stats:
{'atp/brand/FitActive': 145,
'atp/brand_wikidata/Q123807531': 145,
'atp/category/leisure/fitness_centre': 145,
'atp/field/branch/missing': 145,
'atp/field/city/missing': 145,
'atp/field/country/from_website_url': 143,
'atp/field/image/missing': 145,
'atp/field/opening_hours/missing': 145,
'atp/field/operator/missing': 145,
'atp/field/operator_wikidata/missing': 145,
'atp/field/postcode/missing': 145,
'atp/field/state/missing': 145, …
```

[fit_active] Add spider (145 locations)

---

locations/spiders/decathlon_tw.py

Code refactored using `API` to fix the broken spider.
```
{'atp/brand/Decathlon': 19,
'atp/brand_wikidata/Q509349': 19,
'atp/category/shop/sports': 19,
'atp/item_scraped_host_count/www.decathlon.tw': 19,
'atp/nsi/cc_match': 19,
'downloader/request_bytes': 729,
'downloader/response_bytes': 4005,
'elapsed_time_seconds': 2.609389, …
```

[Decathlon TW] Fix spider

---

locations/spiders/usps.py

US ZIP code is 5 digits followed by optional 4 digits. Where both occur, they are separated by a hyphen.

[USPS] Fix postcode errors

---

locations/spiders/loblaws.py

Some of the smaller ones are too small for NSI, but also Loblaws was about to lose it's [category](https://github.com/osmlab/name-suggestion-index/commit/109d36bb82715324c3742326d8fcdbf367771516).

[Loblaws] Improve categories

---

locations/spiders/dangerfield.py

`Fixes : added condition to opening_hours to fix spider`
{'atp/brand/Dangerfield': 63,
'atp/brand_wikidata/Q119220880': 63,
'atp/category/shop/clothes': 63,
'atp/field/branch/missing': 63,
'atp/field/email/missing': 63,
'atp/field/image/missing': 63,
'atp/field/operator/missing': 63,
'atp/field/operator_wikidata/missing': 63,
'atp/field/twitter/missing': 63,
'atp/field/website/missing': 61,
'atp/item_scraped_host_count/stockist.co': 63,
'atp/nsi/perfect_match': 63,
'downloader/response_bytes': 9674, …

[Dangerfield] Fix Spider

---

locations/spiders/pioneer_ca.py

```python
{'atp/brand/Pioneer': 214,
'atp/brand_wikidata/Q7196684': 214,
'atp/category/amenity/fuel': 214,
'atp/cdn/cloudflare/response_count': 216,
'atp/cdn/cloudflare/response_status_count/200': 216,
'atp/field/branch/missing': 214,
'atp/field/country/from_spider_name': 214,
'atp/field/email/missing': 214,
'atp/field/image/missing': 214,
'atp/field/opening_hours/missing': 214,
'atp/field/operator/missing': 214,
'atp/field/operator_wikidata/missing': 214,
'atp/item_scraped_host_count/www.pioneer.ca': 214,
'atp/nsi/cc_match': 214,
'downloader/request_bytes': 133397,
'downloader/request_count': 216,
'downloader/request_method_count/GET': 216,
'downloader/response_bytes': 1093351,
'downloader/response_count': 216,
'downloader/response_status_count/200': 216, …
```

[Pioneer CA] Add spider

---

locations/spiders/farmhouse_inns.py
locations/spiders/farmhouse_inns_gb.py

`Fixes : updated sitemap_url and sitemap_rules to fix spider`
{'atp/brand/Farmhouse Inns': 66,
'atp/brand_wikidata/Q105504972': 66,
'atp/category/amenity/restaurant': 66,
'atp/field/branch/missing': 66,
'atp/field/city/missing': 66,
'atp/field/operator/missing': 66,
'atp/field/operator_wikidata/missing': 66,
'atp/field/state/missing': 66,
'atp/field/street_address/missing': 66,
'atp/field/twitter/missing': 66,
'atp/item_scraped_host_count/www.farmhouseinns.co.uk': 66,
'atp/nsi/perfect_match': 66,
'downloader/request_bytes': 38785,
'downloader/request_count': 68,
'downloader/request_method_count/GET': 68,
'downloader/response_bytes': 2785197,
'downloader/response_count': 68,
'downloader/response_status_count/200': 68,
'elapsed_time_seconds': 83.358586, …

[FarmhouseInns] Fix Spider

---

locations/storefinders/go_review_api.py

`Fixes : updated go_review_api module to fix galitos_za spider`
{"atp/brand/Galito's": 177,
'atp/brand_wikidata/Q116619555': 177,
'atp/category/amenity/fast_food': 177,
'atp/field/city/missing': 177,
'atp/field/country/from_spider_name': 177,
'atp/field/email/missing': 177,
'atp/field/opening_hours/missing': 177,
'atp/field/operator/missing': 177,
'atp/field/operator_wikidata/missing': 177,
'atp/field/phone/missing': 177,
'atp/field/postcode/missing': 177,
'atp/field/state/missing': 177,
'atp/field/street_address/missing': 177,
'atp/field/twitter/missing': 177,
'atp/item_scraped_host_count/admin.goreview.co.za': 177,
'atp/nsi/perfect_match': 177,
'downloader/request_bytes': 501,
'downloader/response_bytes': 51101, …

[GalitosZA] Fix Spider

---

locations/spiders/scotrail_gb.py

Link Extractor was now finding only selected major stations (8), so converted to sitemap to get them all.

[ScotRail GB] Convert to use sitemap

---

locations/spiders/frischs.py
locations/spiders/frischs_us.py

There was some issue with `ld+json`  parsing due to that spider was failing, used  `chompjs` as a `json_parser` to fix the spider.
`downloader/response_status_count/302': 34`  too many redirects, investigated few links, they no longer are valid store pages, that's why redirecting.
```
{"atp/brand/Frisch's Big Boy": 54,
'atp/brand_wikidata/Q5504660': 54,
'atp/category/amenity/restaurant': 54,
'atp/item_scraped_host_count/locations.frischs.com': 54,
'downloader/request_bytes': 39346,
'downloader/request_count': 99,
'downloader/request_method_count/GET': 99,
'downloader/response_bytes': 2654641,
'downloader/response_count': 99, …
```

[Frischs] Fix spider

---

locations/spiders/fatface.py
locations/spiders/fatface_gb.py

Fix done by splitting into two separate spiders one for [GB](https://www.fatface.com/storelocator) and another for rest of the countries (currently only [US](https://www.fatface.com/us/en/store-locator) and [IE](https://www.fatface.com/ie/en/store-locator) is there), because they need different approach. `coordinates` are available only for `GB` spider.
`GB`:
```
{'atp/brand/FATFACE': 183,
'atp/brand_wikidata/Q5437186': 183,
'atp/category/shop/clothes': 183,
'atp/field/email/missing': 183,
'atp/field/image/missing': 183,
'atp/field/operator/missing': 183,
'atp/field/operator_wikidata/missing': 183,
'atp/field/state/missing': 183,
'atp/item_scraped_host_count/www.fatface.com': 183,
'atp/nsi/perfect_match': 183,
'downloader/request_bytes': 279202, …
```

[Fatface] Fix spider

---

locations/spiders/davids_tea.py

`Sitemap` and `Structured Data` are no longer available. Hence, code refactored to fix the spider.
```
{"atp/brand/David's Tea": 20,
'atp/brand_wikidata/Q3019129': 20,
'atp/category/shop/tea': 20,
'atp/field/phone/missing': 20,
'atp/field/state/from_reverse_geocoding': 20,
'atp/item_scraped_host_count/davidstea.com': 20,
'atp/nsi/perfect_match': 20,
'downloader/request_bytes': 1428,
'downloader/response_bytes': 73296, …
```

[DavidsTea] Fix spider

---

locations/spiders/new_england_511_us.py

The following states have a combined Travel-IQ backed transport information system:
- Maine
- New Hampshire
- Vermont
Note TravelIQSpider does not work here because the API endpoints have been disabled. An alternative approach has been used instead.

Add New England 511 (US) (354 traffic cameras)

---

locations/middlewares/cdnstats.py

While looking at starbucks_ar_cl which doesn't run from my location but works on weeklys I noticed that this website is under CloudFront CDN. It would be interesting to see stats for it.

[cdnstats middleware] count CloudFront

---

locations/spiders/brillen_de.py

Add [brillen.de](https://www.brillen.de/), an optician chain in DE.
```
2024-12-02 00:39:12 [scrapy.statscollectors] INFO: Dumping Scrapy stats:
{'atp/brand/brillen.de': 198,
'atp/brand_wikidata/Q105275794': 198,
'atp/category/shop/optician': 198,
'atp/field/branch/missing': 198,
'atp/field/image/missing': 198,
'atp/field/opening_hours/missing': 198,
'atp/field/operator/missing': 198,
'atp/field/operator_wikidata/missing': 198,
'atp/field/twitter/missing': 198,
'atp/field/website/missing': 198,
'atp/item_scraped_host_count/cal.supervista.de': 30353,
'atp/nsi/perfect_match': 198,
```

[brillen_de] Add spider (198 locations)

---

locations/spiders/cancer_research_uk_gb.py

This wasn't coming from the spider name because of `_uk`, nor was it coming from the coords, because there isn't any.

[Cancer Research UK GB] Add country code

---

locations/spiders/homesense.py
locations/spiders/homesense_us.py

{'atp/brand/HomeSense': 67,
'atp/brand_wikidata/Q16844433': 67,
'atp/category/shop/interior_decoration': 67,
'atp/field/branch/missing': 67,
'atp/field/city/missing': 67,
'atp/field/country/from_reverse_geocoding': 67,
'atp/field/email/missing': 67,
'atp/field/image/missing': 67,
'atp/field/opening_hours/missing': 67,
'atp/field/operator/missing': 67,
'atp/field/operator_wikidata/missing': 67,
'atp/field/postcode/missing': 67,
'atp/field/street_address/missing': 67,
'atp/field/twitter/missing': 67,
'atp/item_scraped_host_count/us.homesense.com': 67,
'atp/nsi/perfect_match': 67,
'downloader/request_bytes': 104789,
'downloader/request_count': 69,
'downloader/request_method_count/GET': 69,
'downloader/response_bytes': 1115053, …

[Homesense] Fix Spider

---

locations/spiders/cinemark.py

```python
{'atp/brand/Cinemark': 329,
'atp/brand_wikidata/Q707530': 329,
'atp/category/amenity/cinema': 329,
'atp/cdn/cloudflare/response_count': 332,
'atp/cdn/cloudflare/response_status_count/200': 332,
'atp/closed_poi': 21,
'atp/field/branch/missing': 329,
'atp/field/email/invalid': 28,
'atp/field/image/missing': 329,
'atp/field/opening_hours/missing': 329,
'atp/field/operator/missing': 329,
'atp/field/operator_wikidata/missing': 329,
'atp/item_scraped_host_count/www.cinemark.com': 329,
'atp/nsi/perfect_match': 329,
'downloader/request_bytes': 333967,
'downloader/request_count': 334,
'downloader/request_method_count/GET': 334,
'downloader/response_bytes': 11601163, …
```

[Cinemark] Fix coords

---

locations/spiders/golf_town_ca.py

API earlier used by spider is no longer working. Code refactored using `Sitemap` and `Structured Data`. Alternate [API](https://liveapi.yext.com/v2/accounts/me/entities/geosearch?radius=500&location=Canada&limit=50&api_key=0adeda99c3ae3befa04d7a409e35e26a&v=20181201&resolvePlaceholders=true&languages=en&entityTypes=location&savedFilterIds=117937) is also there.
```
{'atp/brand/Golf Town': 47,
'atp/brand_wikidata/Q112966691': 47,
'atp/category/shop/sports': 47,
'atp/cdn/cloudflare/response_count': 49,
'atp/cdn/cloudflare/response_status_count/200': 48,
'atp/field/branch/missing': 47,
'atp/field/country/from_spider_name': 47, …
```

[Golf Town CA] Fix Spider

---

locations/spiders/la_porchetta.py

Previous API is no longer functional, hence switched to `WPStoreLocator` API. Order pages (eg: https://parnell.order.laporchetta.co.nz/store) have `SD` but that requires fix.
```
{'atp/brand/La Porchetta': 33,
'atp/brand_wikidata/Q6464528': 33,
'atp/category/amenity/restaurant': 33,
'atp/field/image/missing': 33,
'atp/field/opening_hours/missing': 33,
'atp/field/operator/missing': 33,
'atp/field/operator_wikidata/missing': 33,
'atp/field/twitter/missing': 33,
'atp/item_scraped_host_count/laporchetta.com.au': 33,
'atp/nsi/perfect_match': 33,
'downloader/response_bytes': 4033, …
```

[La porchetta] Fix spider

---

locations/spiders/reiss_gb.py

When I renamed the John Lewis spider, I didn't catch this. This may not run without a proxy as it didn't in the last weekly, but it works locally.
```python
{'atp/brand/Reiss': 95,
'atp/brand_wikidata/Q7310479': 95,
'atp/category/shop/clothes': 95,
'atp/field/branch/missing': 95,
'atp/field/email/missing': 95,
'atp/field/image/missing': 95,
'atp/field/operator/missing': 95,
'atp/field/operator_wikidata/missing': 95,
'atp/field/state/missing': 95,
'atp/field/twitter/missing': 95,
'atp/item_scraped_host_count/www.reiss.com': 96,
'atp/nsi/perfect_match': 95,
'downloader/request_bytes': 142179,
'downloader/request_count': 98,
'downloader/request_method_count/GET': 98,
'downloader/response_bytes': 4837321, …
```

[BUILDFIX] Fix ReissGBSpider import

---

locations/spiders/drummond_golf_au.py

{'atp/brand/Drummond Golf': 50,
'atp/brand_wikidata/Q124065894': 50,
'atp/category/shop/golf': 50,
'atp/field/branch/missing': 50,
'atp/field/country/from_spider_name': 50,
'atp/field/opening_hours/missing': 50,
'atp/field/phone/missing': 50,
'atp/item_scraped_host_count/www.drummondgolf.com.au': 50,
'atp/nsi/brand_missing': 50,
'downloader/request_bytes': 4217,
'downloader/request_count': 11,
'downloader/request_method_count/GET': 11,
'downloader/response_bytes': 122898,
'downloader/response_count': 11,
'downloader/response_status_count/200': 11, …

[DrummondGolfAU] Fix Spider

---

locations/spiders/five_guys_cn.py

The previously used `Yext API` is no longer working. The changed [version](https://cdn.yextapis.com/v2/accounts/me/search/vertical/query?experienceKey=search-backend-cn&api_key=e9a586fc4400f344829f350f07a7e367&v=20220511&locale=en-CN&input=&verticalKey=locations) is also an option but doesn't directly support the existed `yext` store_finders, also in future might get change again, hence used `sitemap` and `SD` to fix the spider.
```
{'atp/brand/Five Guys': 5,
'atp/brand_wikidata/Q1131810': 5,
'atp/category/amenity/fast_food': 5,
'atp/cdn/cloudflare/response_count': 9,
'atp/cdn/cloudflare/response_status_count/200': 8,
'atp/field/branch/missing': 5,
'atp/field/operator/missing': 5, …
```

[Five Guys CN] Fix Spider

---

contrib/hooks/pre-commit
docs/CATEGORIES.md
docs/EXTRA_ATTRIBUTES.md
templates/spiders/basic.tmpl
templates/spiders/crawl.tmpl
templates/spiders/csvfeed.tmpl
templates/spiders/json_blob.tmpl
templates/spiders/structured_data_crawl.tmpl
templates/spiders/structured_data_sitemap.tmpl
templates/spiders/wp_go_maps.tmpl
templates/spiders/xmlfeed.tmpl

`item_attributes = {"extras": Categories.XYZ.value}` should be discouraged.
1. In cases where we do `item.update(SpecificSpider.item_attributes)` it will nuke any already given `extras`.
2. And for future proofing `apply_category` should be centralised so we can change it once for everything not have to edit 4k spiders. Otherwise we'll be heading back to when some spiders we're assigning things like `amenity:atm=True`.

[DOCS] Add apply_category info

---

locations/spiders/nandos.py
locations/spiders/nandos_gb_ie.py

```python
{"atp/brand/Nando's": 486,
"atp/brand/Nino Nando's": 1,
'atp/brand_wikidata/Q111753283': 1,
'atp/brand_wikidata/Q3472954': 486,
'atp/category/amenity/fast_food': 1,
'atp/category/amenity/restaurant': 486,
'atp/field/country/from_reverse_geocoding': 486,
'atp/field/email/missing': 487,
'atp/field/image/missing': 487,
'atp/field/operator/missing': 487,
'atp/field/operator_wikidata/missing': 487,
'atp/field/postcode/missing': 12,
'atp/item_scraped_host_count/www.nandos.co.uk': 990,
'atp/nsi/perfect_match': 487,
'downloader/request_bytes': 331013,
'downloader/request_count': 491, …
```

[Nandos GB] Split and improve branding

---

locations/spiders/juice_press_us.py

{'atp/brand/Juice Press': 65,
'atp/brand_wikidata/Q27150131': 65,
'atp/category/amenity/fast_food': 65,
'atp/field/branch/missing': 65,
'atp/field/city/missing': 65,
'atp/field/country/from_spider_name': 65,
'atp/field/opening_hours/missing': 65,
'atp/field/phone/missing': 65,
'atp/field/postcode/missing': 65,
'atp/field/state/from_reverse_geocoding': 65,
'atp/field/website/missing': 65,
'atp/item_scraped_host_count/www.juicepress.com': 65, …

[JuicePressUS] Fix Spider

---

locations/spiders/dusk_nz.py

`robotstxt` ignored to remove the spider blockage. Fixed error due to change in the address string. Few more changes added.
```
{'atp/brand/dusk': 3,
'atp/brand_wikidata/Q120669167': 3,
'atp/category/shop/houseware': 3,
'atp/field/name/missing': 3,
'atp/item_scraped_host_count/www.duskcandles.co.nz': 3,
'downloader/request_bytes': 323, …
```

[Dusk NZ] Fix spider

---

locations/spiders/hipermaxi_bo.py

The new API used, requires `access_token`, couldn't find any working way to remove the dependency on the hard coded token, but looks like not going to expire soon. `street_address` for few POIs don't have sufficient info, but coordinates are consistently present.
```
{'atp/brand/Hipermaxi': 44,
'atp/brand_wikidata/Q81968262': 44,
'atp/category/amenity/pharmacy': 26,
'atp/category/multiple': 26,
'atp/category/shop/supermarket': 18,
'atp/field/city/missing': 44,
'atp/field/country/from_spider_name': 44,
'atp/field/email/missing': 44,
'atp/field/image/missing': 44,
'atp/field/name/missing': 26,
'atp/field/opening_hours/missing': 44,
'atp/field/operator/missing': 44,
'atp/field/operator_wikidata/missing': 44,
'atp/field/phone/missing': 44,
'atp/field/postcode/missing': 44, …
```

[Hipermaxi BO] Fix spider

---

locations/spiders/opentransportdata_swiss.py

The upstream data source has waived the attribution requirement for All The Places (”database”) and its data consumers (“licence holders of the database”).
* https://opentransportdata.swiss/en/authorised-databases/
* https://opentransportdata.swiss/en/terms-of-use/#511_Exemption_for_databases

[opentransportdata.swiss] Change dataset attribution to optional

---

locations/commands/insights.py

OSM can contain broken data. When this is an invalid value, processes fall down.

[Insights] Only collect valid Qcodes from taginfo

---

locations/spiders/nordsee.py

`JsonBlob` utilized to fix the broken spider. Covers `DE` & `AT` both. `NSI` suggests that brand has presence in other countries  as well like [SK](https://www.nordsee.sk/prevadzky/) etc, but they can't be added in this spider, also not much count count is there.
```
{'atp/brand/Nordsee': 217,
'atp/brand_wikidata/Q74866': 217,
'atp/category/amenity/fast_food': 217,
'atp/field/branch/missing': 217,
'atp/field/city/missing': 217,
'atp/field/email/missing': 217,
'atp/field/image/missing': 217,
'atp/field/operator/missing': 217,
'atp/field/operator_wikidata/missing': 217,
'atp/field/postcode/missing': 217,
'atp/field/state/missing': 217,
'atp/field/street_address/missing': 217,
'atp/field/twitter/missing': 217, …
```

[Nordsee] Fix spider

---

locations/spiders/maurices.py

```python
{'atp/brand/Maurices': 866,
'atp/brand_wikidata/Q6793571': 866,
'atp/category/shop/clothes': 866,
'atp/cdn/cloudflare/response_count': 868,
'atp/cdn/cloudflare/response_status_count/200': 868,
'atp/field/email/missing': 866,
'atp/field/image/missing': 866,
'atp/field/operator/missing': 866,
'atp/field/operator_wikidata/missing': 866,
'atp/field/twitter/missing': 866,
'atp/item_scraped_host_count/locations.maurices.com': 866,
'atp/nsi/perfect_match': 866,
'downloader/request_bytes': 483537,
'downloader/request_count': 868,
'downloader/request_method_count/GET': 868,
'downloader/response_bytes': 19995451,
'downloader/response_count': 868,
'downloader/response_status_count/200': 868,
'elapsed_time_seconds': 170.870837, …
```

[Maurices] Improve brand and branch

---

locations/spiders/lagerhaus_at.py

`Fixes : code refactored to use sitemap to fix spider`
{'atp/brand/Lagerhaus': 872,
'atp/brand_wikidata/Q1232873': 872,
'atp/category/shop/doityourself': 872,
'atp/field/branch/missing': 872,
'atp/field/city/missing': 872,
'atp/field/country/from_spider_name': 872,
'atp/field/email/missing': 872,
'atp/field/image/missing': 872,
'atp/field/lat/missing': 498,
'atp/field/lon/missing': 498,
'atp/field/operator/missing': 872,
'atp/field/operator_wikidata/missing': 872,
'atp/field/phone/missing': 872,
'atp/field/postcode/missing': 872,
'atp/field/state/missing': 872,
'atp/field/street_address/missing': 872,
'atp/field/twitter/missing': 872,
'atp/item_scraped_host_count/lagerhaus.at': 872,
'atp/nsi/perfect_match': 872,
'downloader/request_bytes': 322085, …

[LagerhausAT] Fix Spider

---

locations/spiders/dickeys_barbecue_pit.py
locations/spiders/dickeys_barbecue_pit_us.py

[Sitemap](https://www.dickeys.com/sitemap.xml) is also there but store [pages](https://www.dickeys.com/locations/texas/dallas/highland-park-hillcrest-ave) have `Structured Data` that is different from convention and requires code adjustment/fix, hence ignored and used `API` approach to fix the spider. Also added `CA` locations. Checked other countries like [JP](https://www.dickeys.com/jp/en-jp/locations), [SG](https://dickeys.com.sg/) etc , either they don't have POI info or can't be added to this spider.
```
{"atp/brand/Dickey's Barbecue Pit": 398,
'atp/brand_wikidata/Q19880747': 398,
'atp/category/amenity/restaurant': 398,
'atp/field/image/missing': 398,
'atp/field/opening_hours/missing': 30,
'atp/field/operator/missing': 398,
'atp/field/operator_wikidata/missing': 398, …
```

[Dickeys Barbecue Pit] Fix spider and add CA locations

---

locations/categories.py
locations/json_blob_spider.py
locations/spiders/poste_italiane_it.py

```js
{'atp/brand/Poste Italiane': 41405,
'atp/brand_wikidata/Q495026': 41405,
'atp/category/amenity/fuel': 4086,
'atp/category/amenity/parcel_locker': 41,
'atp/category/amenity/post_box': 28400,
'atp/category/amenity/post_office': 12954,
'atp/category/missing': 24251,
'atp/category/shop/clothes': 1157,
'atp/category/shop/collector': 10,
'atp/category/shop/supermarket': 11563,
'atp/category/shop/tobacco': 16488,
'atp/field/branch/missing': 85996,
'atp/field/brand/missing': 57545,
'atp/field/brand_wikidata/missing': 57545,
'atp/field/city/missing': 20,
'atp/field/country/from_spider_name': 98950,
'atp/field/email/missing': 98176,
'atp/field/image/missing': 98950,
'atp/field/name/missing': 28443,
'atp/field/opening_hours/missing': 67570, …
```

feat: improve Poste Italiane (IT, 74/98k)

---

locations/spiders/taco_bell_in.py

Cloudflare is blocking the [POI locator](https://www.tacobell.co.in/find-us). [API](https://www.tacobell.co.in/storelocator/storelocator/advancesearch
) with post data e.g.` queryType=findStore&state=Delhi&city=allCity&locality=allLocality
` also getting blocked. One more [store page](https://www.tacobell.co.in/store-locator
) is there, but that is also blocked.

[Taco Bell IN] Flag as requires proxy, might fix cloudflare blockage

---

locations/spiders/wycon_cosmetics.py

Add [Wycon Cosmetics](https://www.wyconcosmetics.com/), a cosmetics chain from IT but also present in several other countries.
```
2024-12-17 22:26:12 [scrapy.statscollectors] INFO: Dumping Scrapy stats:
{'atp/brand/Wycon Cosmetics': 252,
'atp/brand_wikidata/Q55831243': 252,
'atp/category/shop/cosmetics': 252,
'atp/field/branch/missing': 252,
'atp/field/email/missing': 252,
'atp/field/image/missing': 252,
'atp/field/opening_hours/missing': 252,
'atp/field/operator/missing': 252,
'atp/field/operator_wikidata/missing': 252,
'atp/field/postcode/missing': 15,
'atp/field/state/missing': 252, …
```

[wycon_cosmetics] Add spider (252 locations)

---

locations/spiders/zabka_pl.py

New API utilized by the [POI locator](https://www.zabka.pl/znajdz-sklep/), used for fixing the spider.
```
{'atp/brand/Żabka': 11022,
'atp/brand_wikidata/Q2589061': 11022,
'atp/category/shop/convenience': 11022,
'atp/field/branch/missing': 11022,
'atp/field/country/from_spider_name': 11022,
'atp/field/email/missing': 11022,
'atp/field/image/missing': 11022,
'atp/field/operator/missing': 11022,
'atp/field/operator_wikidata/missing': 11022,
'atp/field/phone/missing': 11022,
'atp/field/postcode/missing': 11022,
'atp/field/state/missing': 11022,
'atp/field/street_address/missing': 11022,
'atp/field/twitter/missing': 11022,
'atp/item_scraped_host_count/www.zabka.pl': 11022,
'atp/nsi/perfect_match': 11022,
'downloader/request_bytes': 328, …
```

[Zabka PL] Fix spider

---

locations/spiders/cyclebar.py

```py
{'atp/brand/CycleBar': 204,
'atp/brand_wikidata/Q121459827': 204,
'atp/category/leisure/fitness_centre': 204,
'atp/field/image/missing': 204,
'atp/field/opening_hours/missing': 204,
'atp/field/operator/missing': 204,
'atp/field/operator_wikidata/missing': 204,
'atp/field/twitter/missing': 204,
'atp/item_scraped_host_count/members.cyclebar.com': 204,
'atp/nsi/perfect_match': 204,
'downloader/request_bytes': 662,
'downloader/response_bytes': 39251,
'elapsed_time_seconds': 2.415844, …
```

Add CycleBar (204 locations)

---

locations/spiders/burger_king_gt.py

Playing with the [Locator](https://app.bk.gt/#/geolocation/address?latitude=25.6180224&longitude=85.2000768), only gives one API that gives POI details, used in the spider for the fix. Not sure about the POI count, one more [API](https://api.bk.gt/v1/restaurant/nearby?latitude=14.587041&longitude=-90.5210362) is there which might give better count but unfortunately not working and results in HTTP Error `500`.
`Opening Hours` don't match with google maps data, didn't look reliable, hence ignored.
```
{'atp/brand/Burger King': 16,
'atp/brand_wikidata/Q177054': 16,
'atp/category/amenity/fast_food': 16,
'atp/cdn/cloudflare/response_count': 103,
'atp/cdn/cloudflare/response_status_count/201': 102,
'atp/field/city/missing': 16, …
```

[Burger King GT] Fix spider

---

locations/spiders/dixy_ru.py

API updated to fix the spider.
```
{'atp/brand/Дикси': 2179,
'atp/brand_wikidata/Q4161561': 2179,
'atp/category/shop/supermarket': 2179,
'atp/field/branch/missing': 2179,
'atp/field/city/missing': 2179,
'atp/field/country/from_spider_name': 2179,
'atp/field/email/missing': 2179,
'atp/field/image/missing': 2179,
'atp/field/operator/missing': 2179,
'atp/field/operator_wikidata/missing': 2179,
'atp/field/phone/missing': 2179,
'atp/field/postcode/missing': 2179,
'atp/field/state/missing': 2179,
'atp/field/street_address/missing': 2179,
'atp/field/twitter/missing': 2179,
'atp/field/website/missing': 2179,
'atp/item_scraped_host_count/dixy.ru': 2179,
'atp/nsi/perfect_match': 2179,
'downloader/request_bytes': 308, …
```

[Dixy RU] Fix Spider

---

locations/spiders/banxico_mx.py

```
{'atp/brand/Actinver': 16,
'atp/brand/Afirme': 1922,
'atp/brand/Autofin': 28,
'atp/brand/BBVA': 14212,
'atp/brand/BanBajío': 941,
'atp/brand/BanCoppel': 3141,
'atp/brand/BanRegio': 618,
'atp/brand/Banamex': 8322,
'atp/brand/Banca Mifel': 103,
'atp/brand/Banco Azteca': 3281,
'atp/brand/Banco Multiva': 214,
'atp/brand/Banco del Bienestar': 6103,
'atp/brand/Banjercito': 931,
'atp/brand/Bank of America': 1,
'atp/brand/Banorte': 10101,
'atp/brand/Bansí': 217,
'atp/brand/CIBanco': 482,
'atp/brand/Compartamos Banco ICR': 85,
'atp/brand/Consubanco': 1,
'atp/brand/HSBC': 3929,
'atp/brand/ICR Inbursa': 747,
'atp/brand/Interacciones': 1,
'atp/brand/Intercam Banco': 511,
'atp/brand/Santander': 8612,
'atp/brand/Scotiabank': 2025,
'atp/brand_wikidata/Q126192396': 3141, …
```

[Banxico MX ] Add  Spider (67287 locations)

---

locations/spiders/pizza_hut_in.py

[Sitemap](https://restaurants.pizzahut.co.in/sitemap.xml) gives count less than `400`. [Store pages](https://restaurants.pizzahut.co.in/?page=1) give around `460`, but the [API](https://api.pizzahut.io/v1/huts?sectors=in-1) gives the max count, same API `GB` Spider utilizes, only the parameter `sectors` varies for the two countries.
```
{'atp/brand/Pizza Hut': 194,
'atp/brand/Pizza Hut Delivery': 811,
'atp/brand_wikidata/Q107293079': 811,
'atp/brand_wikidata/Q191615': 194,
'atp/category/amenity/fast_food': 811,
'atp/category/amenity/restaurant': 194,
'atp/field/city/missing': 1005,
'atp/field/country/from_spider_name': 1005,
'atp/field/email/missing': 1005,
'atp/field/image/missing': 1005,
'atp/field/opening_hours/missing': 1005,
'atp/field/operator/missing': 1005, …
```

[Pizza Hut IN] Fix spider

---

locations/spiders/blackstore_fr.py

Add [Blackstore](https://www.blackstore.fr/), a clothes chain in FR.
```
2024-12-22 22:05:09 [scrapy.statscollectors] INFO: Dumping Scrapy stats:
{'atp/brand/Blackstore': 114,
'atp/brand_wikidata/Q125446765': 114,
'atp/category/shop/clothes': 114,
'atp/field/city/missing': 114,
'atp/field/country/from_spider_name': 114,
'atp/field/email/missing': 114,
'atp/field/image/missing': 114,
'atp/field/operator/missing': 114,
'atp/field/operator_wikidata/missing': 114,
'atp/field/phone/missing': 114,
'atp/field/postcode/missing': 114,
'atp/field/state/missing': 114,
'atp/field/street_address/missing': 114,
'atp/field/twitter/missing': 114,
'atp/field/website/missing': 114,
'atp/item_scraped_host_count/www.blackstore.fr': 114,
'atp/nsi/perfect_match': 114,
```

[blackstore_fr] Add spider (114 locations)

---

locations/spiders/kiko_milano.py

Add [KIKO Milano](https://www.kikocosmetics.com/), a global cosmetics store chain.
```
2024-12-22 22:11:56 [scrapy.statscollectors] INFO: Dumping Scrapy stats:
{'atp/brand/KIKO Milano': 1082,
'atp/brand_wikidata/Q3812045': 1082,
'atp/category/shop/cosmetics': 1082,
'atp/field/branch/missing': 1082,
'atp/field/country/from_reverse_geocoding': 1082,
'atp/field/email/missing': 154,
'atp/field/image/missing': 1082,
'atp/field/opening_hours/missing': 1082,
'atp/field/operator/missing': 1082,
'atp/field/operator_wikidata/missing': 1082,
'atp/field/phone/missing': 94,
'atp/field/postcode/missing': 54,
'atp/field/state/missing': 15,
'atp/field/twitter/missing': 1082, …
```

[kiko_milano] Add spider (1082 locations)

---

locations/spiders/anaconda_au.py

`Fixes: updated start_urls to fix spider`
{'atp/brand/Anaconda': 88,
'atp/brand_wikidata/Q105981238': 88,
'atp/category/shop/outdoor': 88,
'atp/field/branch/missing': 88,
'atp/field/city/missing': 88,
'atp/field/postcode/missing': 88,
'atp/field/street_address/missing': 88,
'atp/item_scraped_host_count/www.anacondastores.com': 88,
'downloader/request_bytes': 87639,
'downloader/request_count': 96,
'downloader/request_method_count/GET': 96,
'downloader/response_bytes': 4546158,
'downloader/response_count': 96, …

[AnacondaAU] Fix Spider

---

locations/spiders/dino_pl.py

Updated start request url and added authorization token for accessing  the API to fix the spider.
```
{'atp/brand/Dino': 2663,
'atp/brand_wikidata/Q11694239': 2663,
'atp/category/shop/supermarket': 2663,
'atp/field/branch/missing': 2663,
'atp/field/city/missing': 2663,
'atp/field/country/from_spider_name': 2663,
'atp/field/email/missing': 2663,
'atp/field/image/missing': 2663,
'atp/field/operator/missing': 2663,
'atp/field/operator_wikidata/missing': 2663,
'atp/field/phone/missing': 2663,
'atp/field/postcode/missing': 2663,
'atp/field/state/missing': 2663,
'atp/field/street_address/missing': 2663,
'atp/field/twitter/missing': 2663,
'atp/item_scraped_host_count/api.marketdino.pl': 2663, …
```

[Dino PL] Fix spider

---

locations/spiders/harris_scarfe_au.py

`Fixes : updated sitemap url to fix spider`
{'atp/brand/Harris Scarfe': 60,
'atp/brand_wikidata/Q5665029': 60,
'atp/category/shop/department_store': 60,
'atp/field/branch/missing': 60,
'atp/field/country/from_spider_name': 60,
'atp/field/email/missing': 60,
'atp/field/state/missing': 60,
'atp/item_scraped_host_count/www.harrisscarfe.com.au': 60,
'atp/nsi/perfect_match': 60,
'downloader/request_bytes': 58281,
'downloader/request_count': 65,
'downloader/request_method_count/GET': 65,
'downloader/response_bytes': 2743023, …

[HarrisScarfeAU] Fix Spider

---

locations/spiders/newspower_au.py

`Fixes : code refactored to use StoreifySpider to fix spider`
{'atp/brand/Newspower': 326,
'atp/brand_wikidata/Q120670137': 326,
'atp/category/shop/newsagent': 326,
'atp/field/branch/missing': 326,
'atp/field/email/missing': 326,
'atp/field/image/invalid': 3,
'atp/field/image/missing': 215,
'atp/field/opening_hours/missing': 326,
'atp/field/operator/missing': 326,
'atp/field/operator_wikidata/missing': 326,
'atp/field/postcode/missing': 326,
'atp/field/state/missing': 326,
'atp/field/street_address/missing': 326,
'atp/field/twitter/missing': 326,
'atp/item_scraped_host_count/sl.storeify.app': 326, …

[NewspowerAU] Fix Spider

---

locations/spiders/nravizza_by.py

Maybe it can be generally dropped somewhere
```
{
'@source_uri': 'https://nravizza.by/page9609244.html',
'@spider': 'nravizza_by',
'amenity': 'fast_food',
'cuisine': 'pizza',
'takeaway': 'yes',
'addr:street_address': 'Лида, ул. Рыбиновского, 78',
'addr:country': 'BY',
'name': 'Nravizza Pizza',
'website': 'null',
'brand': 'Nravizza',
'brand:wikidata': 'Q125747982',
'nsi_id': 'nravizzapizza-381458'
}
```

[nravizza_by] drop website=null

---

locations/spiders/noodles_and_company_us.py

`Fixes : updated sitemap_rule to fix spider`
{'atp/brand/Noodles and Company': 464,
'atp/brand_wikidata/Q7049673': 464,
'atp/category/amenity/restaurant': 464,
'atp/cdn/cloudflare/response_count': 466,
'atp/cdn/cloudflare/response_status_count/200': 466,
'atp/field/branch/missing': 464,
'atp/field/email/missing': 464,
'atp/field/operator/missing': 464,
'atp/field/operator_wikidata/missing': 464,
'atp/item_scraped_host_count/locations.noodles.com': 464,
'atp/nsi/perfect_match': 464,
'downloader/request_bytes': 179835,
'downloader/request_count': 466,
'downloader/request_method_count/GET': 466,
'downloader/response_bytes': 9177859,
'downloader/response_count': 466,
'downloader/response_status_count/200': 466,
'elapsed_time_seconds': 566.405148, …

[NoodlesAndCompanyUS] Fix Spider

---

locations/spiders/cookout.py
locations/spiders/cookout_us.py

Updated `start_url` to get max count of POIs, also code simplified, removed `opening_hours` code as it was resulting in `key_error`, also `hours` data is not reliable because it doesn't match with google maps info.
```
{'atp/brand/Cook Out': 339,
'atp/brand_wikidata/Q5166992': 339,
'atp/category/amenity/fast_food': 339,
'atp/field/email/missing': 339,
'atp/field/image/missing': 339,
'atp/field/opening_hours/missing': 339,
'atp/field/operator/missing': 339,
'atp/field/operator_wikidata/missing': 339,
'atp/field/phone/missing': 336,
'atp/field/twitter/missing': 339,
'atp/item_scraped_host_count/cookout.com': 339,
'atp/nsi/perfect_match': 339, …
```

[Cookout] Fix spider to get all locations 

---

locations/spiders/food_city_southeast_us.py

`xpaths`  updated to fix the spider and fetching missing attributes.
```
{'atp/brand/Food City': 153,
'atp/brand_wikidata/Q16981107': 153,
'atp/category/shop/supermarket': 153,
'atp/field/branch/missing': 153,
'atp/field/city/missing': 153,
'atp/field/country/from_spider_name': 153,
'atp/field/email/missing': 153,
'atp/field/image/missing': 153,
'atp/field/operator/missing': 153,
'atp/field/operator_wikidata/missing': 153,
'atp/field/postcode/missing': 153,
'atp/field/state/from_reverse_geocoding': 153,
'atp/field/street_address/missing': 153,
'atp/field/twitter/missing': 153,
'atp/item_scraped_host_count/www.foodcity.com': 153,
'atp/nsi/perfect_match': 153,
'downloader/request_bytes': 19863, …
```

[Food City Southeast US] Fix spider

---

locations/spiders/source_london_gb.py

`Fixes : added start request to fix spider`
{'atp/brand/Source London': 1149,
'atp/brand_wikidata/Q7565133': 1149,
'atp/category/amenity/charging_station': 1149,
'atp/field/branch/missing': 1149,
'atp/field/country/from_spider_name': 1149,
'atp/field/email/missing': 1149,
'atp/field/image/missing': 1149,
'atp/field/opening_hours/missing': 1149,
'atp/field/phone/missing': 1149,
'atp/field/state/missing': 1149,
'atp/field/street_address/missing': 1149,
'atp/field/twitter/missing': 1149,
'atp/field/website/missing': 1149,
'atp/item_scraped_host_count/www.sourcelondon.net': 1149,
'atp/nsi/cc_match': 1149,
'atp/operator/Source London': 1149,
'atp/operator_wikidata/Q7565133': 1149, …

[SourceLondonGB] Fix Spider

---

locations/spiders/nutrition_warehouse_au.py

`Stockinstore` API is no longer working, used new API to fix the spider and code refactored accordingly.
```
{'atp/brand/Nutrition Warehouse': 117,
'atp/brand_wikidata/Q117747424': 117,
'atp/category/shop/nutrition_supplements': 117,
'atp/field/street_address/missing': 117,
'atp/field/website/missing': 117,
'atp/item_scraped_host_count/brauz-api-netlify-v2.netlify.app': 117,
'atp/nsi/brand_missing': 117,
'downloader/request_bytes': 746,
'downloader/response_bytes': 17645, …
```

[Nutrition Warehouse AU] Fix spider

---

locations/spiders/obi_ru.py

`GraphQL` query is used to fix the spider replacing non functional API url.
```
{'atp/brand/OBI': 29,
'atp/brand_wikidata/Q300518': 29,
'atp/category/shop/doityourself': 29,
'atp/item_scraped_host_count/obi.ru': 29,
'atp/nsi/perfect_match': 29,
'downloader/request_bytes': 1469,
'downloader/response_bytes': 31412,
'elapsed_time_seconds': 16.401311, …
```

[Obi RU] Fix spider

---

locations/spiders/auchan_lu.py

`Fixes : updated start_urls to fix spider`
{'atp/brand/Auchan': 29,
'atp/brand_wikidata/Q758603': 29,
'atp/category/shop/supermarket': 29,
'atp/field/branch/missing': 29,
'atp/field/street_address/missing': 29,
'atp/item_scraped_host_count/api.ari.auchan.com': 29,
'atp/nsi/cc_match': 29,
'downloader/request_bytes': 745, …

[Auchan LU] Fix Spider

---

locations/spiders/dfs_gb.py

Crawling the site isn't as reliable as it should be: https://www.alltheplaces.xyz/spiders.html?search=dfs_gb
```python
{'atp/brand/DFS': 116,
'atp/brand_wikidata/Q5204927': 116,
'atp/category/shop/furniture': 116,
'atp/field/email/missing': 116,
'atp/field/operator/missing': 116,
'atp/field/operator_wikidata/missing': 116,
'atp/field/phone/missing': 116,
'atp/field/state/missing': 66,
'atp/item_scraped_host_count/www.dfs.co.uk': 116,
'atp/nsi/perfect_match': 116,
'downloader/request_bytes': 336,
'downloader/response_bytes': 14273, …
```

[DFS GB] Use API

---

locations/spiders/starbucks_us.py

I'm not expecting this to run, since it didn't in the last few weeklies, but I did a partial run locally:
```python
{'atp/brand/Starbucks': 80,
'atp/brand_wikidata/Q37158': 80,
'atp/category/amenity/cafe': 80,
'atp/field/email/missing': 80,
'atp/field/image/missing': 80,
'atp/field/operator/missing': 80,
'atp/field/operator_wikidata/missing': 80,
'atp/field/twitter/missing': 80,
'atp/item_scraped_host_count/www.starbucks.com': 156,
'atp/nsi/cc_match': 80,
'downloader/request_bytes': 125046,
'downloader/request_count': 283,
'downloader/request_method_count/GET': 283,
'downloader/response_bytes': 519978,
'downloader/response_count': 283,
'downloader/response_status_count/200': 283,
'elapsed_time_seconds': 260.181315, …
```

[Starbucks US] Clean name

---

locations/spiders/next.py

https://stores.next.co.uk/ is unstable and sometimes redirects to https://www.next.co.uk/storelocator
Updated `start_url` to make country selection stable using https://www.next.co.uk/countryselect
```
{'atp/brand/Next': 826,
'atp/brand/Next Home': 52,
"atp/brand/Victoria's Secret": 1,
'atp/brand_wikidata/Q116897680': 52,
'atp/brand_wikidata/Q246655': 826,
'atp/brand_wikidata/Q332477': 1,
'atp/category/shop/clothes': 827,
'atp/category/shop/furniture': 52,
'atp/field/branch/missing': 879,
'atp/field/email/missing': 879,
'atp/field/image/missing': 879,
'atp/field/opening_hours/missing': 177,
'atp/field/operator/missing': 879,
'atp/field/operator_wikidata/missing': 879,
'atp/field/phone/invalid': 47,
'atp/field/postcode/missing': …
```

[Next] Use stable url for country selection

---

locations/spiders/food_city_southeast_us.py

`extras.delivery` was not being parsed correctly.
Address parts can be pulled from sibling hidden inputs with `id="Address123"` etc.
```py
{'atp/brand/Food City': 153,
'atp/brand_wikidata/Q16981107': 153,
'atp/category/shop/supermarket': 153,
'atp/field/branch/missing': 153,
'atp/field/country/from_spider_name': 153,
'atp/field/email/missing': 153,
'atp/field/image/missing': 153,
'atp/field/operator/missing': 153,
'atp/field/operator_wikidata/missing': 153,
'atp/field/twitter/missing': 153,
'atp/item_scraped_host_count/www.foodcity.com': 153,
'atp/nsi/perfect_match': 153,
'downloader/request_bytes': 19743,
'downloader/request_method_count/GET': 17,
'downloader/response_bytes': 161849,
'downloader/response_count': 17, …
```

[Food City Southeast US] Extract address parts directly. Fix delivery tag.

---

locations/spiders/shake_shack.py

Sitemap is no longer available, switched to `CrawlSpider` and utilized `Structured Data` to fix the spider.
```
{'atp/brand/Shake Shack': 544,
'atp/brand_wikidata/Q1058722': 544,
'atp/category/amenity/fast_food': 544,
'atp/cdn/cloudflare/response_count': 546,
'atp/cdn/cloudflare/response_status_count/200': 546,
'atp/field/branch/missing': 544,
'atp/field/city/missing': 13,
'atp/field/email/missing': 544,
'atp/field/image/missing': 544,
'atp/field/lat/missing': 46,
'atp/field/lon/missing': 46,
'atp/field/opening_hours/missing': 544,
'atp/field/operator/missing': 544,
'atp/field/operator_wikidata/missing': 544,
'atp/field/phone/missing': 151,
'atp/field/postcode/missing': 136,
'atp/field/state/missing': 166, …
```

[Shake Shack] Fix spider

---

locations/spiders/national_tyres_and_autocare_gb.py

```python
{'atp/brand/National Tyres and Autocare': 194,
'atp/brand_wikidata/Q6979055': 194,
'atp/category/shop/car_repair': 194,
'atp/field/city/missing': 194,
'atp/field/email/missing': 194,
'atp/field/operator/missing': 194,
'atp/field/operator_wikidata/missing': 194,
'atp/field/state/missing': 194,
'atp/item_scraped_host_count/www.national.co.uk': 194,
'atp/nsi/perfect_match': 194,
'downloader/request_bytes': 87182,
'downloader/request_count': 196,
'downloader/request_method_count/GET': 196,
'downloader/response_bytes': 4440559,
'downloader/response_count': 196,
'downloader/response_status_count/200': 196,
'elapsed_time_seconds': 239.190516,
'finish_time': datetime.datetime(2025, 1, 1, 17, 4, 50, 400389, tzinfo=datetime.timezone.utc), …
```

[National Tyres and Autocare GB] Add spider

---

locations/spiders/best_western.py

Used `playwright` to access the `sitemap`. Still captcha page comes up during the run, increasing `download_delay` may incease the items scraped.
```
{'atp/brand/Aiden by Best Western': 2,
'atp/brand/Best Western': 106,
'atp/brand/Best Western Plus': 36,
'atp/brand/Best Western Premier': 13,
'atp/brand/Sure Hotel': 1,
'atp/brand/Surestay': 4,
'atp/brand/Surestay Plus': 3,
'atp/brand_wikidata/Q830334': 165,
'atp/category/tourism/hotel': 165,
'atp/field/branch/missing': 165,
'atp/field/email/missing': 165,
'atp/field/operator/missing': 165,
'atp/field/operator_wikidata/missing': 165,
'atp/field/state/missing': 159, …
```

[BestWestern] Fix Spider

---

locations/spiders/avera_us.py

`API` earlier used, is now blocked, hence code refactored using `sitemap` and `SD` to fix the spider. Additional `headers` are required to get rid of blockage.
```
{'atp/brand/Avera': 441,
'atp/brand_wikidata/Q4828238': 441,
'atp/category/amenity/hospital': 441,
'atp/category/multiple': 441,
'atp/field/branch/missing': 441,
'atp/field/country/from_spider_name': 441,
'atp/field/email/missing': 436,
'atp/field/image/invalid': 10,
'atp/field/lat/missing': 11,
'atp/field/lon/missing': 11,
'atp/field/opening_hours/missing': 129,
'atp/item_scraped_host_count/www.avera.org': 443,
'atp/nsi/perfect_match': 441,
'atp/operator/Avera Health': 441,
'atp/operator_wikidata/Q4828238': 441,
'downloader/request_bytes': 235638, …
```

[Avera US] Fix spider

---

locations/spiders/mattress_warehouse_us.py

In response to https://github.com/alltheplaces/alltheplaces/issues/10951, this removes the brand's email, instagram, and twitter from `mattress_warehouse_us`.
As mentioned in https://github.com/alltheplaces/alltheplaces/issues/11212, it might be better to add a pipeline to remove redundant brand data for all spiders, instead of making PRs for each spider.

Mattress Warehouse: Remove brand data from POI

---

locations/spiders/hobby_lobby.py
locations/spiders/hobby_lobby_us.py

This has a bug that I can't figure out. 
The `ld_data` has
```py
'openingHoursSpecification': [..., {'dayOfWeek': 'Monday', 'opens': '09:00 AM', 'closes': '08:00 PM', '@type': 'OpeningHoursSpecification'}, ...]
```
but if I set
```py
time_format = "%H:%M %p"
```
the closing time is parsed as `08:00`. The "PM" is ignored. Is this a bug with `StructuredDataSpider` or `OpeningHours`?
Also, this is my second spider I've written. Could I request general feedback?

Add Hobby Lobby spider (1040 locations)

---

locations/spiders/trung_nguyen_coffee_vn.py

`Fixes : added user_agent to fix spider`
{'atp/brand/Trung Nguyên': 660,
'atp/brand_wikidata/Q3541154': 660,
'atp/category/amenity/cafe': 660,
'atp/field/branch/missing': 660,
'atp/field/city/missing': 660,
'atp/field/country/from_spider_name': 660,
'atp/field/email/missing': 660,
'atp/field/image/missing': 660,
'atp/field/opening_hours/missing': 660,
'atp/field/operator/missing': 660,
'atp/field/operator_wikidata/missing': 660,
'atp/field/phone/missing': 53,
'atp/field/postcode/missing': 660,
'atp/field/state/missing': 660,
'atp/field/street_address/missing': 660,
'atp/field/twitter/missing': 660,
'atp/field/website/missing': 660,
'atp/item_scraped_host_count/trungnguyenlegend.com': 660,
'atp/nsi/perfect_match': 660,
'downloader/request_bytes': 575, …

[Trung Nguyen Coffee VN] Fix Spider

---

locations/pipelines/check_item_properties.py

* Ensure country codes for items are valid (assigned) ISO 3166-1 alpha-2 codes and not unassigned codes such as "ZZ".
* Collect statistics on the number of items extracted per country code. This is helpful to debug multinational spiders to determine if features of all expected countries are being extracted. It is also helpful to alert to spiders named e.g. "_gb" for the UK, but also including features in territories such as "IM" (Isle of Man), and thus the spider should be renamed.

pipelines/check_item_properties: improve country code matching, stats

---

locations/spiders/cotton_on_group.py

'atp/brand/Cotton On': 548,
'atp/brand/Cotton On Body': 107,
'atp/brand/Cotton On Kids': 170,
'atp/brand/Factorie': 112,
'atp/brand/Rubi': 22,
'atp/brand/Supré': 79,
'atp/brand/Typo': 212,
'atp/brand_wikidata/Q113961498': 170,
'atp/brand_wikidata/Q5175717': 548,
'atp/brand_wikidata/Q7645153': 79,
'atp/category/shop/clothes': 1016,
'atp/category/shop/shoes': 22,
'atp/category/shop/stationery': 212,
'atp/country/AE': 28,
'atp/country/AU': 580,
'atp/country/BR': 24,
'atp/country/BW': 3,
'atp/country/GB': 20,
'atp/country/HK': 4,
'atp/country/ID': 34,
'atp/country/MY': 79,
'atp/country/NA': 4,
'atp/country/NZ': 97,
'atp/country/PH': 40,
'atp/country/SG': 37,
'atp/country/US': 156,
'atp/country/VN': 14,
'atp/country/ZA': 130,
Fixes #9215

Add Cotton On Group brands (worldwide) (1250 stores)

---

locations/spiders/call_a_pizza_de.py

Add [Call a Pizza](https://www.call-a-pizza.de/bestellen), a pizza chain in DE.
```
2024-12-10 08:32:00 [scrapy.statscollectors] INFO: Dumping Scrapy stats:
{'atp/brand/Call a Pizza': 116,
'atp/brand_wikidata/Q1027107': 116,
'atp/category/amenity/fast_food': 116,
'atp/field/country/from_spider_name': 116,
'atp/field/email/missing': 116,
'atp/field/image/missing': 116,
'atp/field/operator/missing': 116,
'atp/field/operator_wikidata/missing': 116,
'atp/field/state/missing': 116,
'atp/item_scraped_host_count/www.call-a-pizza.de': 116,
'atp/nsi/perfect_match': 116,
```

[call_a_pizza_de] Add spider (127 locations)

---

locations/spiders/shurgard.py

German locations also use the `/self-storage/` URL format.
```
2025-01-09 22:46:30 [scrapy.statscollectors] INFO: Dumping Scrapy stats:
{'atp/brand/Shurgard': 220,
'atp/brand_wikidata/Q3482670': 220,
'atp/category/shop/storage_rental': 220,
'atp/field/branch/missing': 220,
'atp/field/city/missing': 143,
'atp/field/country/from_reverse_geocoding': 220,
'atp/field/email/missing': 220,
'atp/field/image/missing': 220,
'atp/field/opening_hours/missing': 220,
'atp/field/operator/missing': 220,
'atp/field/operator_wikidata/missing': 220,
'atp/field/postcode/missing': 69,
'atp/field/street_address/missing': 69,
'atp/item_scraped_host_count/www.shurgard.com': 220,
'atp/nsi/perfect_match': 220,
```

[shurgard] add locations in Germany

---

locations/spiders/burger_king_co.py

API found on [website](https://bk.com.co/)'s order [page](https://pideenlinea.bk.com.co/pide-a-domicilio), utilized to replace the non-functional API.
```
{'atp/brand/Burger King': 36,
'atp/brand_wikidata/Q177054': 36,
'atp/category/amenity/fast_food': 36,
'atp/country/CO': 36,
'atp/field/country/from_spider_name': 17,
'atp/field/phone/invalid': 29,
'atp/field/postcode/missing': 36,
'atp/field/state/missing': 36,
'atp/field/website/missing': 36,
'atp/item_scraped_host_count/api01.inoutdelivery.com.co': 36,
'atp/nsi/cc_match': 36,
'downloader/request_bytes': 359, …
```

[Burger King CO] Fix spider

---

locations/spiders/alaska_commercial_company.py

sometimes has state, but more often just street address and never full address
```
examples:
['209 Airport Road', '125 Main St.', '131 Akakeek St.', '811 3rd Avenue', '295 Main St.',
'345 Main St.', '155 Main St.', '6th and H Street', 'Box 109', 'PO Box 9', '1 Bayview Dr.',
'365 Main St.', '395 Bison St.', '175 Main St.', 'Mile 1 Teller Hwy', '100 Pausana St.',
'231 Main St.', '741 Qalgi Ave', '100 Main St.', '377 State Street', '265 Main St.', 
'255 Main St.', '285 Main St.', '215 Main St.', '135 Ridgecrest St.', '106 Nicholoff Way',
'1300 Craig/Klawock Highway', '100 Southside Eskimo Creek', '6488 Klawock Hollis Hwy. #9',
'1st and Lower Milton', '30 Reynolds Ave.', '716 Ocean Cape Road']
counter_examples
['P.O. Box 70 70 First Street, AK', '705 Halibut Point Road, Suite B',
'101 Front …
```

[alaska_commercial_company] street_address

---

locations/spiders/cricket_wireless.py

{'atp/brand/Cricket Wireless': 3340,
'atp/brand_wikidata/Q5184987': 3340,
'atp/category/shop/mobile_phone': 3340,
'atp/country/US': 3340,
'atp/field/branch/missing': 3340,
'atp/field/email/missing': 3340,
'atp/field/operator/missing': 3340,
'atp/field/operator_wikidata/missing': 3340,
'atp/field/twitter/missing': 3340,
'atp/item_scraped_host_count/www.cricketwireless.com': 3340,
'atp/nsi/perfect_match': 3340,
'downloader/request_bytes': 8727004,
'downloader/request_count': 5815,
'downloader/request_method_count/GET': 5815,
'downloader/response_bytes': 183211383,
'downloader/response_count': 5815,
'downloader/response_status_count/200': 5815,
'elapsed_time_seconds': 7141.127307, …

[Cricket Wireless] Fix Spider

---

locations/spiders/q_park.py

I missed some deals urls to filter out. Refactored code slightly to have deals as a list.
```json
{
"atp/brand/Q-Park": 1020,
"atp/brand_wikidata/Q1127798": 1020,
"atp/category/amenity/parking": 1020,
"atp/field/branch/missing": 1020,
"atp/field/city/missing": 118,
"atp/field/country/from_website_url": 288,
"atp/field/email/missing": 1020,
"atp/field/image/missing": 1020,
"atp/field/lat/missing": 13,
"atp/field/lon/missing": 13,
"atp/field/opening_hours/missing": 1020,
"atp/field/phone/missing": 536,
"atp/field/postcode/missing": 99,
"atp/field/state/missing": 1020,
"atp/field/street_address/missing": 98,
"atp/field/twitter/missing": 1020,
"atp/geometry/null_island": 13,
"atp/item_scraped_host_count/www.q-park.be": 42, …
```

[q_park] Changed deals to a list 

---

locations/spiders/giant_eagle_us.py

Replaced non functional API by `GraphQL` one and code refactored accordingly to fix the spider. POIs count saturates with the current `zipcode` based search requests.
```
{'atp/brand/GetGo': 14,
'atp/brand/Giant Eagle': 191,
'atp/brand/Giant Eagle Pharmacy': 197,
'atp/brand/Market District': 22,
'atp/brand_wikidata/Q1522721': 191,
'atp/brand_wikidata/Q5553766': 14,
'atp/brand_wikidata/Q98550869': 22,
'atp/category/amenity/pharmacy': 197,
'atp/category/multiple': 197,
'atp/category/shop/convenience': 14,
'atp/category/shop/supermarket': 213,
'atp/field/branch/missing': 424,
'atp/field/brand_wikidata/missing': 197,
'atp/field/country/from_spider_name': 424,
'atp/field/email/missing': 424,
'atp/field/image/missing': 424,
'atp/field/operator/missing': …
```

[Giant Eagle US] Fix spider

---

locations/categories.py
locations/spiders/rosneft_ru.py

it is used more widely in OSM https://overpass-turbo.eu/s/1WXD https://overpass-turbo.eu/s/1WXF
it is used in docs, see https://github.com/alltheplaces/alltheplaces/blob/0403f55d4f5773d83a2cde2925287b0f09d37084/docs/EXTRA_ATTRIBUTES.md?plain=1#L38
`fuel:electricity` is also more common in ATP itself
```
rg "fuel:electric\"" | wc -l
1165
rg "fuel:electricity" | wc -l
4484
```
though neither is listed at https://wiki.openstreetmap.org/wiki/Key:fuel:* (I started https://wiki.openstreetmap.org/wiki/Talk:Key:fuel:*#fuel%3Aelectricity )

fuel:electric -> fuel:electricity

---

locations/spiders/tgi_fridays_gr.py

{'atp/brand/TGI Fridays': 9,
'atp/brand_wikidata/Q1524184': 9,
'atp/category/amenity/restaurant': 9,
'atp/field/branch/missing': 9,
'atp/field/city/missing': 9,
'atp/field/country/from_spider_name': 9,
'atp/field/opening_hours/missing': 9,
'atp/field/street_address/missing': 9,
'atp/item_scraped_host_count/www.fridays.gr': 9,
'atp/nsi/perfect_match': 9,
'downloader/request_bytes': 666,
'downloader/response_bytes': 55522, …

[Tgi Fridays GR] Fix Spider

---

locations/spiders/rotpunkt_apotheken_ch.py

maybe gmaps should be preserved, but they definitely should not occupy `website` key while actual website is pushed to `source:website`
if gmaps should be kept - into which key it would go?
(and source website is in `@source_uri` anyway)

drop gmaps links, put website in website tag

---

locations/pipelines/check_item_properties.py

It's useful to see this log during development, but not in weekly runs.

[check properties pipeline] switch regex error to warning

---

locations/spiders/kbp_foods_us.py

{"atp/brand/Arby's": 118,
'atp/brand/KFC': 832,
'atp/brand/Sonic Drive-In': 85,
'atp/brand_wikidata/Q524757': 832,
'atp/brand_wikidata/Q630866': 118,
'atp/brand_wikidata/Q7561808': 85,
'atp/category/amenity/fast_food': 1089,
'atp/country/US': 1089,
'atp/field/branch/missing': 1089,
'atp/field/brand/missing': 54,
'atp/field/brand_wikidata/missing': 54,
'atp/field/country/from_spider_name': 1089,
'atp/field/email/missing': 1089,
'atp/field/image/missing': 1089,
'atp/field/opening_hours/missing': 1089,
'atp/field/operator_wikidata/missing': 1089,
'atp/field/phone/invalid': 19,
'atp/field/state/from_reverse_geocoding': 854, …

[KBP Foods US] Fix Spider

---

locations/spiders/iccu_it.py

Trial to fix #11627 
locally: `'elapsed_time_seconds': 94.763347,`

fix(iccu_it): proxy trial

---

locations/spiders/bpb_xk.py

I committed this spider with `--no-verify` flag, there are two small things to fix:
- [XK](https://www.wikidata.org/wiki/Q1246) is treated as invalid country code in `CheckItemPropertiesPipeline`
-  spider name validation fires with `Spider name 'bpb_xk' should use class name 'BpbXkSpider' instead of 'BpbXKSpider'`
Stats:
```json
{
"atp/brand/Banka Për Biznes": 66,
"atp/brand_wikidata/Q16349919": 66,
"atp/category/amenity/atm": 39,
"atp/category/amenity/bank": 27,
"atp/country/XK": 66,
"atp/field/branch/missing": 66,
"atp/field/city/missing": 66,
"atp/field/country/from_spider_name": 66,
"atp/field/country/invalid": 66,
"atp/field/email/missing": 66,
"atp/field/image/missing": 66,
"atp/field/lat/missing": 1,
"atp/field/lon/missing": 1,
"atp/field/name/missing": 66, …
```

[bpb_xk] add spider (66 locations)

---

locations/spiders/mol.py
locations/spiders/total_energies.py

Total Erg was sold to IP Gruppo API, thus will be rebranding.
And Total Access has been rebranded as part of larger rebranding to TotalEnergies. I plan on deleting from NSI as well.

[total_energies] TotalErg to IP Gruppo API and Total Access to TotalEnergies

---

locations/pipelines/check_item_properties.py
tests/test_pipeline_check_item_properties.py

Rel to https://github.com/alltheplaces/alltheplaces/pull/11946#issue-2782670540, it makes sense that check properties pipeline should do a country code check based on the same library as in country code cleanup pipeline. Otherwise Kosovo (XK) will be reported as invalid country code.

[check properties pipeline] change country_regex to use geonames

---

locations/spiders/jumbo_nl.py

Used `GraphQL` API to fix the broken spider.
```
{'atp/brand/Jumbo': 724,
'atp/brand_wikidata/Q2262314': 724,
'atp/category/shop/supermarket': 724,
'atp/country/NL': 724,
'atp/field/country/from_spider_name': 724,
'atp/field/email/missing': 724,
'atp/field/image/missing': 724,
'atp/field/operator/missing': 724,
'atp/field/operator_wikidata/missing': 724,
'atp/field/phone/missing': 724,
'atp/field/state/missing': 724,
'atp/field/street_address/missing': 724,
'atp/field/twitter/missing': 724,
'atp/item_scraped_host_count/www.jumbo.com': 724,
'atp/nsi/perfect_match': 724,
'downloader/request_bytes': 124176,
'downloader/request_count': 25,
'downloader/request_method_count/POST': 25,
'downloader/response_bytes': 89982, …
```

[Jumbo NL] Fix spider

---

locations/spiders/toyota_mx.py

{'atp/brand/Toyota': 101,
'atp/brand_wikidata/Q53268': 101,
'atp/category/shop/car': 101,
'atp/country/MX': 101,
'atp/field/branch/missing': 101,
'atp/field/city/missing': 101,
'atp/field/country/from_spider_name': 101,
'atp/field/email/missing': 101,
'atp/field/opening_hours/missing': 101,
'atp/field/postcode/missing': 101,
'atp/field/street_address/missing': 101,
'atp/item_scraped_host_count/www.toyota.mx': 103,
'atp/nsi/cc_match': 101,
'downloader/response_bytes': 14076, …

[Toyota MX] Fix Spider

---

locations/spiders/omv.py

Fixed fetching of  essential parameters to make the API calls successful.
```
{'atp/brand/Avanti': 134,
'atp/brand/Hofer Diskont': 78,
'atp/brand/OMV': 999,
'atp/brand/Petrom': 455,
'atp/brand_wikidata/Q107803455': 78,
'atp/brand_wikidata/Q168238': 1133,
'atp/brand_wikidata/Q1755034': 455,
'atp/category/amenity/fuel': 1666,
'atp/country/AT': 418,
'atp/country/BG': 93,
'atp/country/CZ': 138,
'atp/country/HU': 202,
'atp/country/MD': 65,
'atp/country/RO': 556,
'atp/country/RS': 64,
'atp/country/SK': 130,
'atp/field/branch/missing': 1666,
'atp/field/email/missing': 1666,
'atp/field/image/missing': 1666,
'atp/field/operator/missing': 1666,
'atp/field/operator_wikidata/missing': 1666,
'atp/field/phone/missing': 132,
'atp/field/state/missing': 1666, …
```

[Omv] Fix spider

---

locations/spiders/mol.py

Replaced non functional API and refactored code accordingly to fix the broken spider.
```
{'atp/brand/Energopetrol': 54,
'atp/brand/INA': 513,
'atp/brand/Lotos': 129,
'atp/brand/MOL': 1576,
'atp/brand/PapOil': 11,
'atp/brand/Slovnaft': 283,
'atp/brand/Tifon': 52,
'atp/brand/Total': 3259,
'atp/brand/TotalEnergies': 683,
'atp/brand_wikidata/Q120433': 54,
'atp/brand_wikidata/Q1256909': 129,
'atp/brand_wikidata/Q154037': 3942,
'atp/brand_wikidata/Q1587563': 283,
'atp/brand_wikidata/Q1662137': 513,
'atp/brand_wikidata/Q549181': 1576,
'atp/category/amenity/fuel': 7091,
'atp/country/AT': 12,
'atp/country/BA': 107,
'atp/country/BE': 517,
'atp/country/CZ': 311,
'atp/country/DE': 835,
'atp/country/FR': 2232,
'atp/country/HR': 477,
'atp/country/HU': 498,
'atp/country/LU': 41,
'atp/country/ME': 12, …
```

[Mol] Fix spider

---

locations/spiders/powercor_au.py

Powercor and Citipower are separate electricity grid operators but have common ownership and common ICT systems. As a result, this spider combines assets such as substations and transformers under the Powercor brand only, as there is no method in the source data for determining whether an asset is a Powercor asset or Citipower asset.
Feature types extracted:
'atp/category/power/substation': 97,
'atp/category/power/transformer': 93682,

Add Powercor (power/(substation|transformer)) (AU) (93779 features)

---

locations/spiders/ernst_young.py

{'atp/brand/EY': 780,
'atp/brand_wikidata/Q489097': 780,
'atp/category/office/consulting': 780,
'atp/country/AE': 3,
'atp/country/AF': 1,
'atp/country/AL': 2,
'atp/country/AM': 1,
'atp/country/AO': 1,
'atp/country/AR': 6,
'atp/country/AT': 4,
'atp/country/AU': 11,
'atp/country/AW': 1,
'atp/country/AZ': 1,
'atp/country/BA': 2,
'atp/country/BB': 1,
'atp/country/BD': 1,
'atp/country/BE': 10,
'atp/country/BG': 1,
'atp/country/BH': 1,
'atp/country/BM': 2,
'atp/country/BN': 2,
'atp/country/BO': 2,
'atp/country/BR': 16,
'atp/country/BS': 2,
'atp/country/BW': 1,
'atp/country/CA': 17,
'atp/country/CG': 1,
'atp/country/CH': 12,
'atp/country/CI': 1,
'atp/country/CL': 4,
'atp/country/CM': 1,
'atp/country/CN': 28,
'atp/country/CO': 4,
'atp/country/CR': 4, …

[ErnstYoung] Fix Spider

---

locations/spiders/captain_d.py

Tried with [Sitemap](https://locations.captainds.com/robots.txt) but POIs count scraped `443` , switched to `CrawlSpider` to match the expected count, and we get `520` POIs. `opening_hours` fixed for missing data.
```
{"atp/brand/Captain D's": 520,
'atp/brand_wikidata/Q5036616': 520,
'atp/category/amenity/fast_food': 520,
'atp/country/US': 520,
'atp/field/email/missing': 520,
'atp/field/operator/missing': 520,
'atp/field/operator_wikidata/missing': 520,
'atp/item_scraped_host_count/locations.captainds.com': 520,
'atp/nsi/perfect_match': 520,
'downloader/request_bytes': 487025,
'downloader/request_count': 971,
'downloader/request_method_count/GET': 971,
'downloader/response_bytes': 26266884,
'downloader/response_count': 971, …
```

[Captain D] Fix spider

---

locations/archive_utils.py
locations/categories.py
locations/crypto_utils.py
locations/pipelines/geojson_multipoint_simplification.py
locations/settings.py
locations/spiders/ausgrid_au.py
locations/spiders/ausnet_dapr_au.py
locations/spiders/ausnet_gridview_au.py
locations/spiders/endeavour_energy_au.py
locations/spiders/essential_energy_au.py
locations/spiders/evoenergy_au.py
locations/spiders/powercor_au.py
locations/spiders/transgrid_au.py
locations/spiders/united_energy_au.py
locations/storefinders/rosetta_apr.py
tests/test_pipeline_geojson_multipoint_simplification.py

Rosetta APR is used by most Australian energy grid operators for displaying maps of electricity grid assets such as substations and lines. Rosetta APR and this type of data is generally made publicly available.
Depending on the energy grid operator, different types of files may be served by the Rosetta APR platform such as geojson files (for features with coordinates) and csv or zipped csv spreadsheet files for detailed data on features such as capacities of substations or transformers. This storefinder provides a means to make second and subsequent requests for additional data files to allow extracted features to be supplemented with more detailed data such as capacity ratings of transformers.

Add Rosetta APR "storefinder" for Australian electricity features

---

ci/run_all_spiders.sh

The latest run failed because Tippecanoe couldn't make tile 10/521/342 small enough. This is attempting to let Tippecanoe figure it out.

Adjust tippecanoe drop rate

---

locations/spiders/burger_king_kr.py

Previously used API no longer working, new API used and code refactored accordingly to fix the spider.
```
{'atp/brand/Burger King': 514,
'atp/brand_wikidata/Q177054': 514,
'atp/category/amenity/fast_food': 514,
'atp/country/KR': 514,
'atp/field/city/missing': 514,
'atp/field/country/from_spider_name': 514,
'atp/field/email/missing': 514,
'atp/field/image/missing': 514,
'atp/field/operator/missing': 514,
'atp/field/operator_wikidata/missing': 514,
'atp/field/postcode/missing': 514,
'atp/field/state/missing': 514,
'atp/field/street_address/missing': 514,
'atp/field/twitter/missing': 514,
'atp/field/website/missing': 514,
'atp/item_scraped_host_count/www.burgerking.co.kr': 514,
'atp/nsi/cc_match': 514,
'downloader/request_bytes': 1267, …
```

[Burger King KR] Fix spider

---

locations/spiders/styleboxx_de.py

[Klier Hair Group](https://klierhairgroup.de/) is the biggest hairdresser chain in Germany with several brands. [Styleboxx](https://www.styleboxx-klier.de/) is one of them. When I submitted #11426, Styleboxx had a different website than the other brands. In the meantime they switched to the same structure, so they are easy to add using the common spider class.
```
2025-01-21 20:53:29 [scrapy.statscollectors] INFO: Dumping Scrapy stats:
{'atp/brand/Styleboxx': 47,
'atp/brand_wikidata/Q121888237': 47,
'atp/category/shop/hairdresser': 47,
'atp/country/DE': 47,
'atp/field/branch/missing': 47,
'atp/field/country/from_spider_name': 47, …
```

[styleboxx_de] Add spider (47 locations)

---

locations/spiders/picard_fr.py

```python
{'atp/brand/Picard': 1189,
'atp/brand_wikidata/Q3382454': 1189,
'atp/category/shop/frozen_food': 1189,
'atp/country/BE': 16,
'atp/country/FR': 1155,
'atp/country/GP': 2,
'atp/country/GY': 1,
'atp/country/LU': 2,
'atp/country/NC': 3,
'atp/country/RE': 10,
'atp/field/image/missing': 1189,
'atp/field/operator/missing': 1189,
'atp/field/operator_wikidata/missing': 1189,
'atp/field/state/missing': 1189,
'atp/field/twitter/missing': 1189,
'atp/item_scraped_host_count/magasins.picard.fr': 1189,
'atp/nsi/perfect_match': 1189,
'downloader/request_bytes': 620545,
'downloader/request_count': 1200,
'downloader/request_method_count/GET': 1200,
'downloader/response_bytes': 21463932,
'downloader/response_count': 1200,
'downloader/response_status_count/200': 1194, …
```

[Picard] Sync brand with NSI

---

locations/spiders/optical_center.py

`Fixes : code updated to use sitemap to fix spider`
{'atp/brand/Optical Center': 908,
'atp/brand_wikidata/Q3354448': 908,
'atp/category/shop/optician': 908,
'atp/country/BE': 15,
'atp/country/CA': 10,
'atp/country/CH': 7,
'atp/country/ES': 3,
'atp/country/FR': 801,
'atp/country/GB': 10,
'atp/country/GP': 1,
'atp/country/IL': 45,
'atp/country/LU': 7,
'atp/country/MQ': 4,
'atp/country/RE': 5,
'atp/field/branch/missing': 908,
'atp/field/image/missing': 908,
'atp/field/operator/missing': 908,
'atp/field/operator_wikidata/missing': 908,
'atp/field/state/from_reverse_geocoding': 10,
'atp/field/state/missing': 898,
'atp/field/twitter/missing': 908, …

[Optical Center] Fix Spider

---

locations/spiders/starbucks_eu.py

Fixed  [AttributeError](https://alltheplaces-data.openaddresses.io/runs/2025-01-11-13-32-30/logs/starbucks_eu.txt) in `opening_hours` code to recover lost POIs count. Not going for the full run, summary generated by `CLOSESPIDER_ITEMCOUNT = 1000`, last [ATP Run](https://alltheplaces-data.openaddresses.io/runs/2025-01-11-13-32-30/stats/starbucks_eu.json) with [errors](https://alltheplaces-data.openaddresses.io/runs/2025-01-11-13-32-30/logs/starbucks_eu.txt) resulted [251](https://alltheplaces-data.openaddresses.io/runs/2025-01-11-13-32-30/stats/starbucks_eu.json) POIs. So I think now after fix full run will again result in more than `3k` POIs.
```
{'atp/brand/Starbucks': 1008,
'atp/brand_wikidata/Q37158': 1008,
'atp/category/amenity/cafe': 1008,
'atp/cdn/cloudflare/response_count': 2062, …
```

[Starbuck EU] Fix opening hours and recover lost POIs

---

locations/spiders/j_d_wetherspoon.py

`Fixes : updated xpath to fix spider`
{'atp/brand/Wetherspoon': 799,
'atp/brand_wikidata/Q6109362': 799,
'atp/category/amenity/pub': 799,
'atp/country/GB': 793,
'atp/country/IE': 6,
'atp/field/branch/missing': 799,
'atp/field/city/missing': 799,
'atp/field/country/from_reverse_geocoding': 799,
'atp/field/email/missing': 799,
'atp/field/image/missing': 799,
'atp/field/opening_hours/missing': 799,
'atp/field/operator/missing': 799,
'atp/field/operator_wikidata/missing': 799,
'atp/field/phone/missing': 799,
'atp/field/street_address/missing': 799,
'atp/field/twitter/missing': 799,
'atp/item_scraped_host_count/www.jdwetherspoon.com': 799,
'atp/nsi/perfect_match': 799,
'downloader/request_bytes': 792, …

[JD Wetherspoon] Fix Spider

---

locations/spiders/phillips_66_conoco_76.py

Conoco (Q1126518) is not a company at all, though it used to be one. Still, it is a brand used by one of (or multiples of?) ConocoPhillips/Phillips 66
See 
- https://en.wikipedia.org/wiki/Phillips_66 
- https://en.wikipedia.org/wiki/ConocoPhillips 
- https://en.wikipedia.org/wiki/Conoco

[Phillips66 Conoco76] Update wikidata

---

locations/spiders/tuev_nord_de.py

In Germany [TÜV Nord](https://www.tuev-nord.de/) is one of the licensed companies that perform the legally mandated regular automobile inspections. This scraper adds their inspection stations.
```
2025-01-25 00:08:19 [scrapy.statscollectors] INFO: Dumping Scrapy stats:
{'atp/brand/TÜV Nord': 402,
'atp/brand_wikidata/Q2463547': 402,
'atp/category/amenity/vehicle_inspection': 402,
'atp/country/DE': 402,
'atp/field/branch/missing': 402,
'atp/field/country/from_spider_name': 402,
'atp/field/email/missing': 402,
'atp/field/image/missing': 402,
'atp/field/opening_hours/missing': 402,
'atp/field/operator/missing': 402,
'atp/field/operator_wikidata/missing': 402, …
```

[tuev_nord_de] Add spider (402 locations)

---

locations/spiders/martins_us.py

BTW, in NSI it is also Q6774803 - matching state after this PR ( https://github.com/osmlab/name-suggestion-index/blob/main/data/brands/shop/supermarket.json#L5053C28-L5053C36 ) - though this by itself it does not mean it is correct

[Martin's Super Markets US] Fix brand:wikidata

---

locations/spiders/stadt_zuerich_ch.py

`Fixes : fix attribute error & recover lost POI's`
{'atp/category/amenity/bench': 7267,
'atp/category/amenity/bicycle_parking': 1927,
'atp/category/amenity/fountain': 1287,
'atp/category/amenity/kindergarten': 371,
'atp/category/amenity/motorcycle_parking': 122,
'atp/category/amenity/police': 81,
'atp/category/amenity/recycling': 178,
'atp/category/amenity/school': 657,
'atp/category/amenity/toilets': 91,
'atp/category/highway/street_lamp': 41926,
'atp/category/leisure/park': 124,
'atp/category/multiple': 1,
'atp/country/CH': 54032,
'atp/field/branch/missing': 54032,
'atp/field/brand/missing': 54032,
'atp/field/brand_wikidata/missing': 54032,
'atp/field/email/missing': 53854,
'atp/field/image/missing': 54032,
'atp/field/name/missing': 52707, …

[Stadt Zuerich CH] Fix Attribute Error & Recover Lost POI's Spider

---

locations/spiders/migros_ch.py

{'atp/brand/Alnatura': 25,
'atp/brand/Do It + Garden': 42,
'atp/brand/Florissimo': 285,
'atp/brand/Micasa': 39,
'atp/brand/Migrolino': 317,
'atp/brand/Migros': 666,
'atp/brand/Migros Café': 5,
'atp/brand/Migros Change': 14,
'atp/brand/Migros Partner': 45,
'atp/brand/Migros Restaurant': 140,
'atp/brand/Migros Take Away': 90,
'atp/brand/OBI': 7,
'atp/brand/Outlet Migros': 28,
'atp/brand/PickMup Box': 186,
'atp/brand/SportXX': 49,
'atp/brand/VOI': 76,
'atp/brand_wikidata/Q108866119': 42,
'atp/brand_wikidata/Q110277616': 76,
'atp/brand_wikidata/Q111803848': 140,
'atp/brand_wikidata/Q111826610': 90,
'atp/brand_wikidata/Q115659418': 285,
'atp/brand_wikidata/Q115659564': 28,
'atp/brand_wikidata/Q115659823': 14,
'atp/brand_wikidata/Q115661152': 666, …

[Migros CH] Fix Spider

---

locations/spiders/pizza_hut_tr.py

Spider some times failed because of `TimeOutError`,  increased `download_timeout`  value, to avoid this kind of failure as it already happened in one of the [run](https://alltheplaces-data.openaddresses.io/runs/2024-12-21-13-32-12/logs/pizza_hut_tr.txt) in past. 
```
{'atp/brand/Pizza Hut': 258,
'atp/brand_wikidata/Q191615': 258,
'atp/category/amenity/restaurant': 258,
'atp/cdn/cloudflare/response_status_count/200': 4,
'atp/cdn/cloudflare/response_status_count/404': 2,
'atp/country/TR': 258,
'atp/field/branch/missing': 258,
'atp/field/city/missing': 258,
'atp/field/country/from_spider_name': 258,
'atp/field/email/missing': 258,
'atp/field/image/missing': 258,
'atp/field/lat/missing': 38,
'atp/field/lon/missing': 38, …
```

[Pizza Hut TR] Make spider stable against TimeOutError

---

locations/spiders/e_leclerc.py

I kind of want structural solution for such typos in the code. [test_item_attributes](https://github.com/alltheplaces/alltheplaces/blob/master/tests/test_item_attributes.py) can probably be updated to spot starting and trailing spaces in item_attributes... but it does not save when typo is in other parts of spider code.

[e_leclerc] fix starting space in brand name

---

locations/spiders/pizza_hut_fr.py

`Fixes : added user_agent to fix spider`
{'atp/brand/Pizza Hut Delivery': 117,
'atp/brand_wikidata/Q107293079': 117,
'atp/category/amenity/fast_food': 117,
'atp/country/FR': 117,
'atp/field/branch/missing': 117,
'atp/field/image/dropped': 117,
'atp/item_scraped_host_count/www.pizzahut.fr': 117,
'atp/nsi/perfect_match': 117,
'downloader/request_bytes': 127090,
'downloader/request_count': 120,
'downloader/request_method_count/GET': 120,
'downloader/response_bytes': 1492646,
'downloader/response_count': 120,
'downloader/response_status_count/200': 120,
'elapsed_time_seconds': 148.377338, …

[Pizza Hut FR] Fix Spider

---

locations/spiders/smythstoys_gb.py

To match their website, Wikipedia, NSI ( https://nsi.guide/index.html?t=brands&k=shop&v=toys&tt=smyths ), OpenStreetMap

[smythstoys_gb] brand=Smyths

---

locations/spiders/burger_king_pe.py

Non functional API is replaced by functional one to fix the spider.
```
{'atp/brand/Burger King': 28,
'atp/brand_wikidata/Q177054': 28,
'atp/category/amenity/fast_food': 28,
'atp/country/PE': 28,
'atp/field/branch/missing': 28,
'atp/field/city/missing': 28,
'atp/field/country/from_spider_name': 28,
'atp/field/state/missing': 28,
'atp/field/street_address/missing': 28,
'atp/item_scraped_host_count/apiprod.pidelo.digital': 28,
'atp/nsi/cc_match': 28, …
```

[Burger King PE] Fix spider

---

locations/spiders/change_group.py

API url updated to fix the spider.
```
{'atp/brand/Change Group': 185,
'atp/brand_wikidata/Q5071758': 185,
'atp/category/amenity/bureau_de_change': 185,
'atp/country/AT': 2,
'atp/country/AU': 27,
'atp/country/CY': 5,
'atp/country/DE': 8,
'atp/country/DK': 7,
'atp/country/ES': 21,
'atp/country/FI': 7,
'atp/country/FR': 23,
'atp/country/GB': 53,
'atp/country/IS': 3,
'atp/country/NZ': 2,
'atp/country/SE': 27,
'atp/field/branch/missing': 185,
'atp/field/email/missing': 185,
'atp/field/image/missing': 185,
'atp/field/lat/missing': 10,
'atp/field/lon/missing': 10,
'atp/field/operator/missing': 185,
'atp/field/operator_wikidata/missing': 185,
'atp/field/phone/missing': 76,
'atp/field/state/missing': 151, …
```

[Change Group] Fix  Spider

---

locations/spiders/harris_scarfe_au.py

`Fix : code refactored to use sitemap to fix spider`
{'atp/brand/Harris Scarfe': 60,
'atp/brand_wikidata/Q5665029': 60,
'atp/category/shop/department_store': 60,
'atp/country/AU': 60,
'atp/field/branch/missing': 60,
'atp/field/country/from_spider_name': 60,
'atp/field/email/missing': 60,
'atp/field/state/missing': 60,
'atp/item_scraped_host_count/www.harrisscarfe.com.au': 60,
'atp/nsi/perfect_match': 60,
'downloader/request_bytes': 45876,
'downloader/request_count': 63,
'downloader/request_method_count/GET': 63, …

[Harris Scarfe AU] Fix Spider

---

locations/spiders/carls_jr_nz.py

```
{"atp/brand/Carl's Jr.": 18,
'atp/brand_wikidata/Q1043486': 18,
'atp/category/amenity/fast_food': 18,
'atp/country/NZ': 18,
'atp/field/branch/missing': 18,
'atp/field/city/missing': 18,
'atp/field/country/from_website_url': 18,
'atp/field/opening_hours/missing': 18,
'atp/field/phone/missing': 18,
'atp/field/postcode/missing': 18,
'atp/field/street_address/missing': 18,
'atp/item_scraped_host_count/www.carlsjr.co.nz': 18,
'atp/nsi/perfect_match': 18, …
```

[Carls Jr NZ] Fix  Spider

---

locations/spiders/fust_ch.py

Sitemap can still be used after updating sitemap urls but `xpaths` have been changed, also POIs data is available from the store finder page itself using a single request, hence utilized JSON Bolb to fix the spider.
```
{'atp/brand/Fust': 134,
'atp/brand_wikidata/Q1227164': 134,
'atp/category/shop/electronics': 134,
'atp/country/CH': 134,
'atp/field/image/missing': 134,
'atp/field/operator/missing': 134,
'atp/field/operator_wikidata/missing': 134,
'atp/field/state/missing': 134,
'atp/field/twitter/missing': 134,
'atp/item_scraped_host_count/www.fust.ch': 134,
'atp/nsi/perfect_match': 134,
'downloader/request_bytes': 606, …
```

[Fust CH] Fix spider

---

locations/spiders/german_american_us.py

Can't remember writing this one or why I didn't do a PR at the time, but here it is.
```python
{'atp/brand/German American': 43,
'atp/brand_wikidata/Q120753420': 43,
'atp/category/amenity/bank': 43,
'atp/country/US': 43,
'atp/field/email/missing': 43,
'atp/field/image/dropped': 35,
'atp/item_scraped_host_count/germanamerican.com': 43,
'atp/nsi/cc_match': 43,
'downloader/request_bytes': 94213,
'downloader/request_count': 148,
'downloader/request_method_count/GET': 148,
'downloader/response_bytes': 790842,
'downloader/response_count': 148, …
```

[German American US] Add spider

---

locations/spiders/casino_fr.py

{'atp/brand/Casino': 220,
'atp/brand_wikidata/Q89029184': 220,
'atp/category/shop/supermarket': 220,
'atp/country/FR': 220,
'atp/field/branch/missing': 220,
'atp/field/city/missing': 59,
'atp/field/country/from_spider_name': 220,
'atp/field/email/missing': 220,
'atp/field/image/missing': 220,
'atp/field/operator/missing': 220,
'atp/field/operator_wikidata/missing': 220,
'atp/field/phone/missing': 220,
'atp/field/postcode/missing': 95,
'atp/field/state/missing': 220,
'atp/field/street_address/missing': 220,
'atp/field/twitter/missing': 220,
'atp/item_scraped_host_count/petitcasino.casino.fr': 220,
'atp/nsi/cc_match': 220,
'downloader/request_bytes': 92993,
'downloader/request_count': 222,
'downloader/request_method_count/GET': 222, …

[Casino FR] Fix Spider

---

locations/spiders/anaconda_au.py

Sitemap's behavior is not stable, saying based on [last fix](https://github.com/alltheplaces/alltheplaces/pull/11689). Now it's accessible straight away, so using it again. If it breaks again then we'll think of alternate approach.
```
{'atp/brand/Anaconda': 88,
'atp/brand_wikidata/Q105981238': 88,
'atp/category/shop/outdoor': 88,
'atp/country/AU': 88,
'atp/field/city/missing': 88,
'atp/field/postcode/missing': 88,
'atp/field/street_address/missing': 88,
'atp/item_scraped_host_count/www.anacondastores.com': 88, …
```

[Anaconda AU] Fix spider

---

locations/spiders/one_medical_us.py

```py
{'atp/category/amenity/clinic': 213,
'atp/category/multiple': 213,
'atp/country/US': 213,
'atp/field/brand/missing': 213,
'atp/field/brand_wikidata/missing': 213,
'atp/field/country/from_spider_name': 213,
'atp/field/email/missing': 213,
'atp/field/phone/missing': 213,
'atp/field/twitter/missing': 213,
'atp/item_scraped_host_count/www.onemedical.com': 213,
'atp/nsi/perfect_match': 213,
'atp/operator/1Life Healthcare': 213,
'atp/operator_wikidata/Q85727717': 213,
'downloader/request_bytes': 15842,
'downloader/request_count': 36,
'downloader/request_method_count/GET': 36,
'downloader/response_bytes': 72092,
'downloader/response_count': 36,
'downloader/response_status_count/200': 36,
'elapsed_time_seconds': 41.825671, …
```

New spider: One Medical (213 locations)

---

locations/spiders/madison_reed_us.py

```py
{'atp/brand/Madison Reed': 93,
'atp/brand_wikidata/Q60770929': 93,
'atp/category/shop/beauty': 93,
'atp/country/US': 93,
'atp/field/country/from_spider_name': 93,
'atp/field/email/missing': 93,
'atp/field/image/missing': 93,
'atp/field/opening_hours/missing': 93,
'atp/field/phone/missing': 93,
'atp/field/twitter/missing': 93,
'atp/field/website/missing': 93,
'atp/item_scraped_host_count/www.madison-reed.com': 93,
'downloader/request_bytes': 2049,
'downloader/response_bytes': 189717, …
```

New spider: Madison Reed (93 locations)

---

locations/spiders/the_halal_guys.py

```py
{'atp/brand/The Halal Guys': 98,
'atp/brand_wikidata/Q10846129': 98,
'atp/category/amenity/fast_food': 98,
'atp/country/CA': 3,
'atp/country/GB': 1,
'atp/country/ID': 3,
'atp/country/KR': 3,
'atp/country/US': 88,
'atp/field/branch/missing': 98,
'atp/field/email/missing': 98,
'atp/field/image/missing': 98,
'atp/field/operator/missing': 98,
'atp/field/operator_wikidata/missing': 98,
'atp/field/twitter/missing': 98,
'atp/item_scraped_host_count/thehalalguys.com': 98,
'atp/nsi/perfect_match': 98,
'downloader/request_bytes': 808,
'downloader/response_bytes': 14458, …
```

New spider: The Halal Guys (98 locations)

---

locations/spiders/melbourne_city_council_barbecues_au.py
locations/spiders/melbourne_city_council_dog_parks_au.py
locations/spiders/melbourne_city_council_drinking_fountains_au.py
locations/spiders/melbourne_city_council_playgrounds_au.py
locations/spiders/melbourne_city_council_sharps_waste_baskets_au.py
locations/spiders/melbourne_city_council_toilets_au.py

Use Melbourne City Council (the government organisation/council operating features) and not City of Melbourne (the administrative region which Melbourne City Council is responsible for).

Fix name/Wikidata item of Melbourne City Council features

---

locations/spiders/santander_pl.py

Updated API to fix the spider.
```
{'atp/brand/Santander': 3084,
'atp/brand_wikidata/Q806653': 3084,
'atp/category/amenity/atm': 2598,
'atp/category/amenity/bank': 486,
'atp/country/PL': 3084,
'atp/field/branch/missing': 2598,
'atp/field/country/from_spider_name': 3084,
'atp/field/email/missing': 3084,
'atp/field/image/missing': 3084,
'atp/field/name/missing': 2598,
'atp/field/operator/missing': 486,
'atp/field/operator_wikidata/missing': 486,
'atp/field/phone/missing': 2602,
'atp/field/postcode/missing': 2575,
'atp/field/state/missing': 3084,
'atp/field/twitter/missing': 3084,
'atp/field/website/missing': 3084,
'atp/item_scraped_host_count/www.santander.pl': 3084, …
```

[Santander PL] Fix Spider

---

locations/spiders/seven_eleven_mx.py

Non-functional API replaced by new one, and code refactored accordingly.
```
{'atp/brand/7-Eleven': 2079,
'atp/brand_wikidata/Q259340': 2079,
'atp/category/shop/convenience': 2079,
'atp/country/MX': 2079,
'atp/field/city/missing': 2079,
'atp/field/country/from_spider_name': 2079,
'atp/field/email/missing': 2079,
'atp/field/image/missing': 2079,
'atp/field/opening_hours/missing': 2079,
'atp/field/operator/missing': 2079,
'atp/field/operator_wikidata/missing': 2079,
'atp/field/phone/missing': 2079,
'atp/field/state/missing': 2079,
'atp/field/twitter/missing': 2079,
'atp/field/website/missing': 2079,
'atp/item_scraped_host_count/www.7-eleven.com.mx': 2079,
'atp/nsi/cc_match': 2079,
'downloader/request_bytes': 1381, …
```

[Seven Eleven MX] Fix Spider

---

locations/categories.py
locations/spiders/melbourne_city_council_parking_spaces_au.py

* Only includes parking spaces with occupancy sensors
* Source data of parking restrictions for each parking space is not the best quality data (even though official). Sometimes provides contradictory restrictions (e.g. overlapping restrictions for the same day where one says it is free parking, the other says it is paid parking). This spider ensures both overlapping/contradictory restrictions are extracted so that users can decide how to handle the ambiguity.

Add Melbourne City Council parking spaces (3307 parking spaces)

---

locations/categories.py

It turned out that `payment:omv_card` is more common in OSM, `payment:omv` is not used at all: https://taginfo.openstreetmap.org/search?q=payment%3Aomv.

Sync FuelCards.OMV with value used in OSM

---

locations/categories.py
locations/spiders/discover_swiss.py

disover.swiss is the IT backend platform of the Swiss hotels association.

[discover.swiss] Add spider for 3843 hotels and 54 serviced apartments

---

locations/spiders/healius_au.py

```
{'atp/brand/Abbott Pathology': 25,
'atp/brand/Dorevitch Pathology': 467,
'atp/brand/Laverty Pathology': 568,
'atp/brand/Lumus Imaging': 130,
'atp/brand/QML Pathology': 495,
'atp/brand/TML Pathology': 19,
'atp/brand/Western Diagnostic Pathology': 207,
'atp/brand_wikidata/Q105256033': 568,
'atp/brand_wikidata/Q126165490': 467,
'atp/brand_wikidata/Q126165557': 495,
'atp/brand_wikidata/Q126165699': 207,
'atp/brand_wikidata/Q126165721': 25,
'atp/brand_wikidata/Q126165745': 19,
'atp/brand_wikidata/Q130311754': 130,
'atp/category/healthcare/medical_imaging': 130,
'atp/category/healthcare/sample_collection': 1781,
'atp/country/AU': 1911, …
```

[Healius AU] Fix spider

---

locations/spiders/bauhaus_ch.py

{'atp/brand/Bauhaus': 5,
'atp/brand_wikidata/Q672043': 5,
'atp/category/shop/doityourself': 5,
'atp/country/CH': 5,
'atp/field/operator/missing': 5,
'atp/field/operator_wikidata/missing': 5,
'atp/field/twitter/missing': 5,
'atp/item_scraped_host_count/api.woosmap.com': 5,
'atp/nsi/cc_match': 5,
'downloader/request_bytes': 727,
'downloader/response_bytes': 2777, …

[Bauhaus CH] Fix Spider

---

locations/spiders/bright_now_dental_us.py

```py
{'atp/brand/Bright Now! Dental': 180,
'atp/brand_wikidata/Q108286875': 180,
'atp/category/amenity/dentist': 180,
'atp/category/multiple': 180,
'atp/country/US': 180,
'atp/field/email/missing': 180,
'atp/field/image/invalid': 1,
'atp/field/operator/missing': 180,
'atp/field/operator_wikidata/missing': 180,
'atp/field/twitter/missing': 180,
'atp/item_scraped_host_count/www.brightnow.com': 180,
'atp/nsi/perfect_match': 180,
'downloader/request_bytes': 86135,
'downloader/request_count': 184,
'downloader/request_method_count/GET': 184,
'downloader/response_bytes': 4151172,
'downloader/response_count': 184,
'downloader/response_status_count/200': 184,
'elapsed_time_seconds': 226.486599,
'finish_time': …
```

New spider: Bright Now! Dental (180 locations)

---

locations/spiders/evereve_us.py

{'atp/brand/Evereve': 119,
'atp/brand_wikidata/Q69891997': 119,
'atp/category/shop/clothes': 119,
'atp/country/US': 119,
'atp/field/branch/missing': 119,
'atp/field/city/missing': 119,
'atp/field/country/from_spider_name': 119,
'atp/field/email/missing': 119,
'atp/field/image/missing': 119,
'atp/field/opening_hours/missing': 119,
'atp/field/operator/missing': 119,
'atp/field/operator_wikidata/missing': 119,
'atp/field/phone/missing': 119,
'atp/field/postcode/missing': 119,
'atp/field/state/from_reverse_geocoding': 119,
'atp/field/street_address/missing': 119,
'atp/field/twitter/missing': 119,
'atp/field/website/missing': 119,
'atp/item_scraped_host_count/evereve-prod.labs.wesupply.xyz': 120,
'atp/nsi/perfect_match': 119, …

[Evereve US] Fix Spider

---

locations/spiders/fcbanking.py

Utilized `Structured Data` to fix the spider, also identified `ATM`s.
```python
{'atp/brand/First Commonwealth Bank': 125,
'atp/brand_wikidata/Q5452773': 125,
'atp/category/amenity/bank': 125,
'atp/country/US': 125,
'atp/field/country/from_reverse_geocoding': 125,
'atp/field/image/dropped': 125,
'atp/field/image/missing': 125,
'atp/field/operator/missing': 125,
'atp/field/operator_wikidata/missing': 125,
'atp/item_scraped_host_count/www.fcbanking.com': 125,
'atp/nsi/cc_match': 125,
'downloader/request_bytes': 138590,
'downloader/request_count': 128,
'downloader/request_method_count/GET': 128,
'downloader/response_bytes': 18799071,
'downloader/response_count': 128,
'downloader/response_status_count/200': 128,
'elapsed_time_seconds': 8.132148, …
```

[Fcbanking] Fix spider

---

locations/spiders/porsche_holding.py

```python
{'atp/brand/Volkswagen': 792,
'atp/brand_wikidata/Q246': 792,
'atp/category/shop/car': 449,
'atp/category/shop/car_repair': 343,
'atp/country/AL': 2,
'atp/country/AT': 245,
'atp/country/BA': 11,
'atp/country/BG': 10,
'atp/country/CL': 35,
'atp/country/CO': 33,
'atp/country/CZ': 90,
'atp/country/HR': 39,
'atp/country/HU': 61,
'atp/country/MK': 7,
'atp/country/MY': 17,
'atp/country/PT': 55,
'atp/country/RO': 62,
'atp/country/RS': 12,
'atp/country/SG': 5,
'atp/country/SI': 33,
'atp/country/SK': 45,
'atp/country/UA': 30,
'atp/field/branch/missing': 792,
'atp/field/email/invalid': 4,
'atp/field/image/missing': 792, …
```

[Porsche Holding] Fix spider

---

locations/spiders/superdrug.py

Fixes #12169
```python
{'atp/brand/Superdrug': 839,
'atp/brand_wikidata/Q7643261': 839,
'atp/category/shop/chemist': 839,
'atp/country/GB': 758,
'atp/country/IE': 10,
'atp/field/country/missing': 71,
'atp/field/email/missing': 839,
'atp/field/image/missing': 839,
'atp/field/lat/missing': 71,
'atp/field/lon/missing': 71,
'atp/field/operator/missing': 839,
'atp/field/operator_wikidata/missing': 839,
'atp/field/phone/invalid': 72,
'atp/field/state/missing': 118,
'atp/field/twitter/missing': 839,
'atp/item_scraped_host_count/api.superdrug.com': 839,
'atp/nsi/category_match': 71,
'atp/nsi/cc_match': 768,
'downloader/request_bytes': 20713,
'downloader/request_count': 11,
'downloader/request_method_count/GET': 11,
'downloader/response_bytes': 186007, …
```

[Superdrug] Fix crash

---

locations/spiders/mcdonalds_au.py

```python
{"atp/brand/McDonald's": 1049,
'atp/brand_wikidata/Q38076': 1049,
'atp/category/amenity/fast_food': 1049,
'atp/country/AU': 1049,
'atp/field/branch/missing': 1049,
'atp/field/country/from_spider_name': 1049,
'atp/field/email/missing': 1049,
'atp/field/image/missing': 1049,
'atp/field/operator/missing': 1049,
'atp/field/operator_wikidata/missing': 1049,
'atp/field/twitter/missing': 1049,
'atp/field/website/missing': 1049,
'atp/item_scraped_host_count/mcdonalds.com.au': 1049,
'atp/mcdonalds_au/facilities/fail/24 Hours': 713,
'atp/mcdonalds_au/facilities/fail/Birthday Parties': 335,
'atp/mcdonalds_au/facilities/fail/McCafé': 922,
'atp/mcdonalds_au/facilities/fail/Playland': 812, …
```

[Mcdonalds AU] Increase download timeout to fix the spider

---

locations/spiders/burger_king_be_lu.py

**_Fixes : code refactored to fix to use uberall spider_**
```python
{'atp/brand/Burger King': 68,
'atp/brand_wikidata/Q177054': 68,
'atp/category/amenity/fast_food': 68,
'atp/country/BE': 58,
'atp/country/LU': 10,
'atp/field/branch/missing': 68,
'atp/field/image/missing': 67,
'atp/field/website/missing': 68,
'atp/item_scraped_host_count/uberall.com': 68,
'atp/nsi/cc_match': 68,
'downloader/response_bytes': 9338, …
```

[Burger King BE LU] Fix Spider

---

locations/spiders/greater_geelong_city_council_trees_au.py
locations/storefinders/opendatasoft_explore.py

Includes new Opendatasoft Explore "storefinder" for exporting and downloading datasets from Opendatasoft Explore, an open data API software system often used by governments for publishing their own open data.

Add Greater Geelong City Council trees (AU) (185k trees)

---

locations/categories.py
locations/spiders/city_of_sydney_playgrounds_fitness_stations_au.py

'atp/category/leisure/fitness_station': 24,
'atp/category/leisure/playground': 138,

Add City of Sydney playgrounds and fitness stations (AU) (162 features)

---

locations/spiders/keke.py

Not sure if this will be any more or less stable than the sitemap, but it's fewer requests and it does work.
```py
{"atp/brand/Keke's Breakfast Cafe": 70,
'atp/brand_wikidata/Q115930150': 70,
'atp/category/amenity/restaurant': 70,
'atp/category/multiple': 61,
'atp/country/US': 70,
'atp/field/email/missing': 70,
'atp/field/image/missing': 70,
'atp/field/operator/missing': 70,
'atp/field/operator_wikidata/missing': 70,
'atp/field/twitter/missing': 70,
'atp/item_scraped_host_count/www.kekes.com': 70,
'atp/nsi/perfect_match': 70,
'downloader/request_bytes': 1552,
'downloader/response_bytes': 42301, …
```

Keke's Breakfast Cafe: Rewrite to use API

---

locations/spiders/burger_king_sg.py

`phone` details is not available at all  for any of the POIs. Done code clean up to fix the error.
```python
{'atp/brand/Burger King': 68,
'atp/brand_wikidata/Q177054': 68,
'atp/category/amenity/fast_food': 68,
'atp/country/SG': 68,
'atp/field/city/missing': 68,
'atp/field/country/from_spider_name': 68,
'atp/field/image/missing': 68,
'atp/field/phone/missing': 68,
'atp/field/state/missing': 68,
'atp/field/street_address/missing': 68,
'atp/item_scraped_host_count/www.burgerking.com.sg': 68,
'atp/nsi/cc_match': 68, …
```

[Burger King SG] Fix spider

---

locations/spiders/pizza_hut_vn.py

API request updated to fix the spider.
```python
{'atp/brand/Pizza Hut': 122,
'atp/brand_wikidata/Q191615': 122,
'atp/category/amenity/restaurant': 122,
'atp/country/VN': 122,
'atp/field/city/missing': 122,
'atp/field/country/from_spider_name': 122,
'atp/field/email/missing': 122,
'atp/field/image/missing': 122,
'atp/field/operator/missing': 122,
'atp/field/operator_wikidata/missing': 122,
'atp/field/phone/missing': 122,
'atp/field/postcode/missing': 122,
'atp/field/state/missing': 122,
'atp/field/street_address/missing': 122,
'atp/field/twitter/missing': 122,
'atp/field/website/missing': 122,
'atp/item_scraped_host_count/rwapi.pizzahut.vn': 122,
'atp/nsi/cc_match': 122,
'downloader/request_bytes': 850, …
```

[Pizza Hut VN] Fix  Spider

---

locations/spiders/costco_ca.py

{'atp/brand/Costco': 109,
'atp/brand_wikidata/Q715583': 109,
'atp/category/shop/wholesale': 109,
'atp/country/CA': 109,
'atp/field/email/missing': 109,
'atp/field/image/missing': 109,
'atp/field/opening_hours/missing': 109,
'atp/field/operator/missing': 109,
'atp/field/operator_wikidata/missing': 109,
'atp/field/twitter/missing': 109,
'atp/field/website/invalid': 49,
'atp/item_scraped_host_count/www.costco.ca': 109,
'atp/nsi/match_failed': 109,
'downloader/request_bytes': 292,
'downloader/response_bytes': 19601,
'elapsed_time_seconds': 2.21845,
'finish_time': …

[Costco CA] Fix Spider

---

locations/spiders/insta_volt_gb.py

_Fixes :updated operator name to fix key error_
```python
{'atp/category/amenity/charging_station': 713,
'atp/country/GB': 713,
'atp/field/brand/missing': 713,
'atp/field/brand_wikidata/missing': 713,
'atp/field/country/from_spider_name': 713,
'atp/field/email/missing': 713,
'atp/field/image/missing': 713,
'atp/field/name/missing': 713,
'atp/field/opening_hours/missing': 713,
'atp/field/phone/missing': 713,
'atp/field/state/missing': 713,
'atp/field/street_address/missing': 713,
'atp/field/twitter/missing': 713,
'atp/item_scraped_host_count/instavolt.co.uk': 713,
'atp/nsi/cc_match': 713,
'atp/operator/InstaVolt': 713,
'atp/operator_wikidata/Q111173904': 713,
'downloader/request_bytes': 1118, …
```

[Insta Volt GB] Fix Spider

---

locations/spiders/insomnia_cookies.py

This spider stood out to me in the [build report](https://alltheplaces-data.openaddresses.io/runs/2025-01-25-13-31-58/stats/_results.json) for how long it took and how many errors it generated. I tried my best to come up with something that worked with the site's highly aggressive rate limiting. It still takes a while (45min), but not as long as before (5hr30min); and it still isn't comprehensive (315 items), but still more complete than before (93 items).
```py
{'atp/brand/Insomnia Cookies': 315,
'atp/brand_wikidata/Q16997024': 315,
'atp/category/shop/pastry': 315,
'atp/country/CA': 2,
'atp/country/GB': 5,
'atp/country/US': 308,
'atp/field/email/missing': 315,
'atp/field/image/invalid': 29,
'atp/field/operator/missing': 315,
'atp/field/operator_wikidata/missing': 315, …
```

Insomnia Cookies: Rewrite to fix spider

---

locations/spiders/coccinelle_fr.py

```python
{'atp/brand/CocciMarket': 502,
'atp/brand/CocciMarket City': 41,
'atp/brand/CocciMarket Easy': 8,
'atp/brand/Coccinelle Express': 168,
'atp/brand/Coccinelle Supermarché': 81,
'atp/brand_wikidata/Q90020459': 81,
'atp/brand_wikidata/Q90020479': 168,
'atp/brand_wikidata/Q90020480': 502,
'atp/brand_wikidata/Q90020481': 41,
'atp/category/shop/convenience': 551,
'atp/category/shop/supermarket': 249,
'atp/country/FR': 800,
'atp/field/brand_wikidata/missing': 8,
'atp/field/country/from_spider_name': 800,
'atp/field/email/missing': 800,
'atp/field/image/missing': 800,
'atp/field/opening_hours/missing': 800,
'atp/field/operator/missing': 800,
'atp/field/operator_wikidata/missing': 800,
'atp/field/phone/missing': 73, …
```

[Coccinelle FR] Fix spider

---

locations/spiders/boost_mobile_us.py

The previously used `API` is only working for the website, but outside browser, even using all headers etc it says `The requested URL was rejected. Please consult with your administrator.`, hence code refactored using `Sitemap` and  `SD` to fix the spider.
Scraped count is reasonable, because [Boost owned stores count is around 4000](https://www.fierce-network.com/wireless/boost-mobile-expands-distribution-walgreens).
```python
{'atp/brand/Boost Mobile': 3521,
'atp/brand_wikidata/Q4943790': 3521,
'atp/category/shop/mobile_phone': 3521,
'atp/country/US': 3521,
'atp/field/branch/missing': 3521,
'atp/field/email/missing': 3479,
'atp/field/image/missing': 3521,
'atp/field/opening_hours/invalid': 95,
'atp/field/operator/missing': 3521,
'atp/field/operator_wikidata/missing': 3521, …
```

[Boost Mobile US] Fix spider

---

locations/spiders/fastned.py

```python
{'atp/category/amenity/charging_station': 345,
'atp/country/BE': 36,
'atp/country/CH': 10,
'atp/country/DE': 42,
'atp/country/DK': 3,
'atp/country/FR': 44,
'atp/country/GB': 30,
'atp/country/NL': 180,
'atp/field/branch/missing': 345,
'atp/field/brand/missing': 345,
'atp/field/brand_wikidata/missing': 345,
'atp/field/email/missing': 345,
'atp/field/image/missing': 345,
'atp/field/opening_hours/missing': 345,
'atp/field/phone/missing': 345,
'atp/field/postcode/missing': 345,
'atp/field/state/missing': 345,
'atp/field/twitter/missing': 345,
'atp/field/website/missing': 345,
'atp/item_scraped_host_count/route.fastned.nl': 345,
'atp/nsi/cc_match': 288,
'atp/nsi/match_failed': 57,
'atp/operator/Fastned': 345,
'atp/operator_wikidata/Q19935749': 345,
'downloader/request_bytes': 618, …
```

[Fastned] Fix Spider

---

locations/spiders/western_power_operated_street_lamps_au.py

These lamps are owned by councils of Western Australia but operated and maintained by Western Power.
This source data has MANY (4M+) duplicate features and no way to filter them server-side, so this spider has to download all 4M+ features to deduplicate client-side instead. This results in the spider having to raise 2000+ requests for paginated features even though the total number of features extracted is 4 queries worth of data if no source data duplication existed.

Add Western Power operated street lamps (AU) (7625 lamps)

---

locations/spiders/frankston_city_council_facilities_au.py

'atp/category/amenity/library': 5,
'atp/category/healthcare/nurse': 13,
'atp/category/leisure/sports_centre': 2,
'atp/category/man_made/antenna': 12,      (free public WiFi)

Add Frankston City Council facilities (AU) (32 facilities)

---

locations/spiders/pizza_hut_vn.py

```python
{'atp/brand/Pizza Hut': 121,
'atp/brand_wikidata/Q191615': 121,
'atp/category/amenity/restaurant': 121,
'atp/country/VN': 121,
'atp/field/city/missing': 121,
'atp/field/country/from_spider_name': 121,
'atp/field/email/missing': 121,
'atp/field/image/missing': 121,
'atp/field/operator/missing': 121,
'atp/field/operator_wikidata/missing': 121,
'atp/field/phone/missing': 121,
'atp/field/postcode/missing': 121,
'atp/field/state/missing': 121,
'atp/field/street_address/missing': 121,
'atp/field/twitter/missing': 121,
'atp/field/website/missing': 121,
'atp/item_scraped_host_count/rwapi.pizzahut.vn': 121,
'atp/nsi/cc_match': 121,
'downloader/request_bytes': 2986, …
```

[Pizza Hut VN ] Generate access token to fix spider

---

locations/spiders/avia_pl.py

_**Fixes : added fuel details**_
```python
{'atp/brand/Avia': 138,
'atp/brand_wikidata/Q300147': 138,
'atp/category/amenity/fuel': 138,
'atp/country/PL': 138,
'atp/field/branch/missing': 138,
'atp/field/country/from_spider_name': 138,
'atp/field/image/missing': 138,
'atp/field/state/missing': 138,
'atp/field/street_address/missing': 138,
'atp/field/website/missing': 138,
'atp/item_scraped_host_count/api.mapa.aviapolska.pl': 138,
'atp/nsi/cc_match': 138,
'downloader/request_bytes': 981, …
```

[Avia PL] Added fuel details

---

locations/spiders/sally_beauty.py
locations/spiders/sally_beauty_ca.py
locations/spiders/sally_beauty_us.py

The API used previously still works, so a minimal fix would just be to remove or update `allowed_domains`. But as far as I can tell the API is limited to 30 results per query, so capturing all locations would require ~7k requests, more than the ~2k required for a sitemap crawler. And it has rate limiting.
```py
{'atp/brand/Sally Beauty': 2284,
'atp/brand_wikidata/Q7405065': 2284,
'atp/category/shop/hairdresser_supply': 2284,
'atp/country/MX': 2,
'atp/country/PR': 36,
'atp/country/US': 2246,
'atp/field/branch/missing': 2284,
'atp/field/country/from_reverse_geocoding': 2284,
'atp/field/email/missing': 2284,
'atp/field/image/dropped': 2284,
'atp/field/image/missing': 2284,
'atp/field/operator/missing': 2284,
'atp/field/operator_wikidata/missing': 2284, …
```

Sally Beauty US/CA: Switch to structured-data

---

locations/spiders/pko_bank_polski_pl.py

```python
{'atp/brand/PKO BP': 3145,
'atp/brand_wikidata/Q578832': 3145,
'atp/category/amenity/atm': 2696,
'atp/category/amenity/bank': 449,
'atp/country/PL': 3145,
'atp/field/branch/missing': 3145,
'atp/field/country/from_spider_name': 3145,
'atp/field/email/missing': 3145,
'atp/field/image/missing': 3145,
'atp/field/name/missing': 2696,
'atp/field/opening_hours/missing': 3145,
'atp/field/operator/missing': 449,
'atp/field/operator_wikidata/missing': 449,
'atp/field/phone/invalid': 70,
'atp/field/phone/missing': 2696,
'atp/field/state/missing': 3145,
'atp/field/street_address/missing': 3145,
'atp/field/twitter/missing': 3145,
'atp/field/website/missing': 3145,
'atp/item_scraped_host_count/www.pkobp.pl': 3932,
'atp/nsi/cc_match': 3145,
'atp/operator/PKO BP': 2696, …
```

[PKO Bank PL] Fix non running spider

---

locations/spiders/echte_bakker_nl.py

```python
{'atp/brand/De Echte Bakker': 298,
'atp/brand_wikidata/Q16920716': 298,
'atp/category/shop/bakery': 298,
'atp/country/NL': 298,
'atp/field/branch/missing': 298,
'atp/field/country/from_spider_name': 298,
'atp/field/image/missing': 298,
'atp/field/operator/missing': 298,
'atp/field/operator_wikidata/missing': 298,
'atp/field/phone/missing': 233,
'atp/field/state/missing': 292,
'atp/field/street_address/missing': 298,
'atp/field/twitter/missing': 298,
'atp/field/website/missing': 18,
'atp/geometry/null_island': 6,
'atp/item_scraped_host_count/echtebakker.nl': 298,
'atp/nsi/perfect_match': 298,
'downloader/request_bytes': 8108, …
```

[Echte Bakker NL] Fix  Spider

---

locations/spiders/southern_coop.py

`StructuredData` no longer present in the location pages, hence utilized `Uberall` API to fix the spider.
```python
{'atp/brand/The Co-operative Food': 194,
'atp/brand/Welcome': 74,
'atp/brand_wikidata/Q107617274': 194,
'atp/brand_wikidata/Q123004215': 74,
'atp/category/shop/convenience': 268,
'atp/closed_poi': 2,
'atp/country/GB': 268,
'atp/field/email/missing': 268,
'atp/field/image/missing': 219,
'atp/field/opening_hours/invalid': 2,
'atp/field/twitter/missing': 268,
'atp/item_scraped_host_count/uberall.com': 268,
'atp/nsi/match_failed': 194,
'atp/nsi/perfect_match': 74,
'atp/operator/The Southern Co-operative': 268,
'atp/operator_wikidata/Q7569773': 268, …
```

[Southern Coop] Fix spider

---

locations/spiders/seven_eleven_th.py

Backend API url has changed on the site.
The spider will fail in our CI most probably.
Stats from partial test run:
```json
{
"atp/brand/7-Eleven": 375,
"atp/brand_wikidata/Q259340": 375,
"atp/category/shop/convenience": 375,
"atp/country/TH": 375,
"atp/field/city/missing": 375,
"atp/field/country/from_spider_name": 375,
"atp/field/email/missing": 375,
"atp/field/image/missing": 375,
"atp/field/opening_hours/missing": 375,
"atp/field/operator/missing": 375,
"atp/field/operator_wikidata/missing": 375,
"atp/field/phone/invalid": 122,
"atp/field/street_address/missing": 375,
"atp/field/twitter/missing": 375,
"atp/field/website/missing": 375,
"atp/item_scraped_host_count/web-api-ro.7eleven.co.th": 437,
"atp/nsi/cc_match": 375,
"downloader/request_bytes": 9584,
"downloader/request_count": 21, …
```

[seven_eleven_th] fix spider

---

locations/spiders/busy_beaver_us.py

_**Fixes : code refactored to fix spider**_
```python
{'atp/brand/Busy Beaver': 19,
'atp/brand_wikidata/Q108394482': 19,
'atp/category/shop/doityourself': 19,
'atp/cdn/cloudfront/response_count': 1,
'atp/cdn/cloudfront/response_status_count/200': 1,
'atp/country/US': 19,
'atp/field/branch/missing': 19,
'atp/item_scraped_host_count/cdn.builder.io': 19,
'atp/nsi/brand_missing': 19,
'downloader/request_bytes': 668,
'downloader/response_bytes': 4248, …
```

[Busy Beaver US] Fix Spider

---

locations/spiders/alltown_us.py

**_Fixes : code updated to use uberall spider_**
```python
{'atp/brand/Alltown': 80,
'atp/brand_wikidata/Q119586667': 80,
'atp/category/shop/convenience': 80,
'atp/country/US': 80,
'atp/field/branch/missing': 80,
'atp/field/email/missing': 80,
'atp/field/image/missing': 80,
'atp/field/operator/missing': 80,
'atp/field/operator_wikidata/missing': 80,
'atp/field/twitter/missing': 80,
'atp/field/website/missing': 80,
'atp/item_scraped_host_count/uberall.com': 80,
'atp/nsi/cc_match': 80,
'downloader/response_bytes': 8674,
'elapsed_time_seconds': 3.15122,
'finish_time': …
```

[Alltown US] Fix Spider

---

DATA_FORMAT.md
locations/hours.py
tests/test_opening_hours.py

see https://github.com/alltheplaces/alltheplaces/discussions/4959 this way opening hours now are not having a change from OSM syntax previously ATP was using ; in meaning of ,
this mattered only for opening hours extending past midnight and only there ATP was changed to use ,
far more complicated processing can be used to avoid using , in rare cases of over midnight opening hours where ; can be used anyway - but instead much simpler one was used
Disclaimer: that falls under work that was funded by EU via NGI 0 via nl.net grant (I can also process it on my side, but others would not benefit from it - so I hope that it is fine to send it here)
see also https://openingh.ypid.de/evaluation_tool/?EXP=Mo-Sa%2010%3A00-02%3A00%2C%20Su%2009%3A00-02%3A00&lat=48.7769&lon=9.1844&mode=0 and …

follow OpenStreetMap opening_hours over midnight

---

locations/spiders/starbucks_eu.py

Ignored `robots.txt` rules to fix the spider. Summary generated using `CLOSESPIDER_ITEMCOUNT = 1000`
```python
{'atp/brand/Starbucks': 1006,
'atp/brand_wikidata/Q37158': 1006,
'atp/category/amenity/cafe': 1006,
'atp/cdn/cloudflare/response_count': 2070,
'atp/cdn/cloudflare/response_status_count/200': 2070,
'atp/country/AT': 24,
'atp/country/BE': 36,
'atp/country/BG': 17,
'atp/country/CH': 53,
'atp/country/CY': 17,
'atp/country/CZ': 56,
'atp/country/DE': 181,
'atp/country/DK': 17,
'atp/country/FR': 65,
'atp/country/GB': 21,
'atp/country/GR': 32,
'atp/country/HU': 30,
'atp/country/IT': 30,
'atp/country/LB': 34,
'atp/country/LU': 5,
'atp/country/NL': 91,
'atp/country/NO': 18,
'atp/country/PL': 60,
'atp/country/RO': 53,
'atp/country/RS': 9,
'atp/country/SK': 14,
'atp/country/TR': 143, …
```

[Starbucks EU] Fix spider

---

locations/spiders/zumiez.py

**_Fixes : Flag robotstxt as False to fix spider_**
```python
{'atp/brand/Zumiez': 615,
'atp/brand_wikidata/Q8075252': 615,
'atp/category/shop/clothes': 615,
'atp/country/CA': 46,
'atp/country/MX': 1,
'atp/country/PR': 5,
'atp/country/US': 563,
'atp/field/branch/missing': 615,
'atp/field/country/from_reverse_geocoding': 615,
'atp/field/email/missing': 615,
'atp/field/image/missing': 615,
'atp/field/operator/missing': 615,
'atp/field/operator_wikidata/missing': 615,
'atp/field/street_address/missing': 615,
'atp/field/twitter/missing': 615,
'atp/item_scraped_host_count/www.zumiez.com': 615,
'atp/nsi/perfect_match': 615,
'downloader/request_bytes': 317,
'downloader/response_bytes': 122799, …
```

[Zumiez] Fix Spider

---

locations/spiders/matalan_gb.py

```python
{'atp/brand/Matalan': 236,
'atp/brand_wikidata/Q12061509': 236,
'atp/category/shop/clothes': 236,
'atp/closed_poi': 10,
'atp/country/GB': 236,
'atp/field/email/missing': 236,
'atp/field/image/missing': 236,
'atp/field/operator/missing': 236,
'atp/field/operator_wikidata/missing': 236,
'atp/field/phone/missing': 236,
'atp/item_scraped_host_count/www.matalan.co.uk': 236,
'atp/nsi/perfect_match': 236,
'downloader/request_bytes': 211975,
'downloader/request_count': 249,
'downloader/request_method_count/GET': 249,
'downloader/response_bytes': 66532011,
'downloader/response_count': 249,
'downloader/response_status_count/200': 249,
'elapsed_time_seconds': 287.912603,
'finish_time': datetime.datetime(2025, 2, 26, 11, 6, …
```

[Matalan GB] Fix spider

---

locations/spiders/prix_quality_it.py

Fixed [KeyError](https://alltheplaces-data.openaddresses.io/runs/2025-02-22-13-32-08/stats/prix_quality_it.json).
```python
{'atp/brand/Prix': 192,
'atp/brand_wikidata/Q61994819': 192,
'atp/category/shop/supermarket': 192,
'atp/country/IT': 192,
'atp/field/country/from_spider_name': 192,
'atp/field/email/missing': 192,
'atp/field/image/missing': 192,
'atp/field/operator/missing': 192,
'atp/field/operator_wikidata/missing': 192,
'atp/field/phone/missing': 192,
'atp/field/twitter/missing': 192,
'atp/field/website/missing': 192,
'atp/item_scraped_host_count/www.prixquality.com': 194,
'atp/nsi/perfect_match': 192,
'downloader/request_bytes': 656,
'downloader/response_bytes': 11276, …
```

[Prix Quality IT] Fix spider

---

locations/spiders/jaguar_land_rover.py

```py
{'atp/brand/Jaguar': 1351,
'atp/brand/Land Rover': 1142,
'atp/brand_wikidata/Q21170490': 1351,
'atp/brand_wikidata/Q26777551': 1142,
'atp/category/missing': 8,
'atp/category/shop/car': 1920,
'atp/category/shop/car_repair': 1584,
'atp/country/AE': 11,
'atp/country/AL': 1,
'atp/country/AM': 4,
'atp/country/AO': 2,
'atp/country/AR': 3,
'atp/country/AT': 33,
'atp/country/AU': 135,
'atp/country/AZ': 2,
'atp/country/BA': 1,
'atp/country/BE': 56,
'atp/country/BG': 6,
'atp/country/BH': 2,
'atp/country/BN': 2,
'atp/country/BR': 41,
'atp/country/CA': 95,
'atp/country/CH': 31,
'atp/country/CI': 2,
'atp/country/CL': 2,
'atp/country/CN': 516,
'atp/country/CO': 2,
'atp/country/CR': 3,
'atp/country/CY': 4,
'atp/country/CZ': 18,
'atp/country/DE': 181,
'atp/country/DK': 7,
'atp/country/DO': 2, …
```

New spider: Jaguar Land Rover (3512 locations)

---

locations/spiders/panda_express.py

`DataDome` captcha will come when we send multiple requests and `IP` will get blocked, so not going to fetch `opening_hours` from individual location pages. `SitemapSpider` or `CrawlSpider` approach doesn't look feasible.
```python
{'atp/brand/Panda Express': 2338,
'atp/brand_wikidata/Q1358690': 2338,
'atp/category/amenity/fast_food': 2338,
'atp/country/CA': 9,
'atp/country/US': 2329,
'atp/field/email/missing': 2338,
'atp/field/image/missing': 2338,
'atp/field/opening_hours/missing': 2338,
'atp/field/operator/missing': 2338,
'atp/field/operator_wikidata/missing': 2338,
'atp/field/twitter/missing': 2338,
'atp/item_scraped_host_count/nomnom-prod-api.pandaexpress.com': …
```

[Panda Express] Fix spider using API, with max available POIs count

---

locations/pipelines/clean_strings.py
locations/settings.py
tests/test_pipeline_clean_strings.py

I've thought about this before, and was a little nervous that `html.unescape` could be destructive to none escaped strings. I don't think this is the case.
Tests still need to be written.

[CleanStringsPipeline] Add pipeline to unescape strings

---

locations/spiders/econofitness_ca.py

**_Fixes : Flag robotstxt as False to fix spider_**
```python
{'atp/brand/Éconofitness': 76,
'atp/brand_wikidata/Q123073582': 76,
'atp/category/leisure/fitness_centre': 76,
'atp/country/CA': 76,
'atp/field/image/dropped': 76,
'atp/field/image/missing': 76,
'atp/field/operator/missing': 76,
'atp/field/operator_wikidata/missing': 76,
'atp/field/state/from_reverse_geocoding': 76,
'atp/field/twitter/missing': 76,
'atp/item_scraped_host_count/econofitness.ca': 76,
'atp/nsi/perfect_match': 76,
'atp/structured_data/unmapped/amenity_features': 4,
'downloader/request_bytes': 53732,
'downloader/request_count': 78,
'downloader/request_method_count/GET': 78,
'downloader/response_bytes': 2414678,
'downloader/response_count': 78, …
```

[Éconofitness CA] Fix Spider

---

locations/spiders/omv.py

Ether a mistake or NSI was updated since creation of the spider: https://nsi.guide/index.html?t=brands&k=amenity&v=fuel&tt=avanti. This PR fixes it.

[omv] fix Avanti wikidata

---

locations/spiders/western_dental_us.py

```py
{'atp/brand/Western Dental': 245,
'atp/brand_wikidata/Q64211989': 245,
'atp/category/amenity/dentist': 245,
'atp/category/multiple': 245,
'atp/clean_strings/street_address': 4,
'atp/country/US': 245,
'atp/field/country/from_spider_name': 245,
'atp/field/email/missing': 245,
'atp/field/image/missing': 245,
'atp/field/opening_hours/missing': 245,
'atp/field/operator/missing': 245,
'atp/field/operator_wikidata/missing': 245,
'atp/field/twitter/missing': 245,
'atp/item_scraped_host_count/www.westerndental.com': 246,
'atp/nsi/match_failed': 245,
'downloader/request_bytes': 770,
'downloader/response_bytes': 52498, …
```

New spider: Western Dental (245 locations)

---

locations/spiders/dds_discounts_us.py

```py
{"atp/brand/dd's Discounts": 358,
'atp/brand_wikidata/Q83743863': 358,
'atp/category/shop/department_store': 358,
'atp/country/US': 358,
'atp/field/email/missing': 358,
'atp/field/image/missing': 358,
'atp/field/operator/missing': 358,
'atp/field/operator_wikidata/missing': 358,
'atp/field/twitter/missing': 358,
'atp/field/website/missing': 358,
'atp/item_scraped_host_count/hosted.where2getit.com': 358,
'atp/nsi/perfect_match': 358,
'downloader/request_bytes': 466,
'downloader/response_bytes': 34396,
'elapsed_time_seconds': 1.02455, …
```

New spider: dd's Discounts (358 locations)

---

locations/spiders/les_schwab_us.py

```py
{'atp/brand/Les Schwab Tire Center': 543,
'atp/brand_wikidata/Q6529977': 543,
'atp/category/shop/tyres': 543,
'atp/cdn/cloudflare/response_count': 12,
'atp/cdn/cloudflare/response_status_count/200': 12,
'atp/clean_strings/addr_full': 543,
'atp/clean_strings/street_address': 543,
'atp/country/US': 543,
'atp/field/city/missing': 543,
'atp/field/country/from_spider_name': 543,
'atp/field/email/missing': 543,
'atp/field/image/missing': 543,
'atp/field/operator/missing': 543,
'atp/field/operator_wikidata/missing': 543,
'atp/field/postcode/missing': 543,
'atp/field/state/from_reverse_geocoding': 543,
'atp/field/twitter/missing': 543,
'atp/item_scraped_host_count/www.lesschwab.com': 543,
'atp/nsi/perfect_match': 543,
'downloader/request_bytes': 8261, …
```

New spider: Les Schwab Tire Center (543 locations)

---

locations/spiders/cat_scale_ca_us.py

```py
{'atp/brand/CAT Scale': 2259,
'atp/brand_wikidata/Q111631907': 2259,
'atp/category/amenity/weighbridge': 2259,
'atp/clean_strings/city': 27,
'atp/clean_strings/lat': 4,
'atp/clean_strings/located_in': 44,
'atp/clean_strings/lon': 10,
'atp/clean_strings/phone': 39,
'atp/clean_strings/postcode': 1,
'atp/clean_strings/street_address': 15,
'atp/country/CA': 51,
'atp/country/US': 2208,
'atp/field/branch/missing': 2259,
'atp/field/email/missing': 2259,
'atp/field/image/missing': 2259,
'atp/field/opening_hours/missing': 2259,
'atp/field/operator/missing': 2259,
'atp/field/operator_wikidata/missing': 2259,
'atp/field/phone/invalid': 15,
'atp/field/state/from_reverse_geocoding': 5, …
```

New spider: CAT Scale (2259 locations)

---

locations/spiders/smashburger.py

**_Fixes : updated start_urls to fix spider_**
```python
{'atp/brand/Smashburger': 196,
'atp/brand_wikidata/Q17061332': 196,
'atp/category/amenity/fast_food': 196,
'atp/cdn/cloudflare/response_count': 261,
'atp/cdn/cloudflare/response_status_count/200': 258,
'atp/cdn/cloudflare/response_status_count/404': 3,
'atp/country/CA': 6,
'atp/country/US': 190,
'atp/field/branch/missing': 196,
'atp/field/email/missing': 196,
'atp/field/image/missing': 196,
'atp/field/opening_hours/missing': 196,
'atp/field/operator/missing': 196,
'atp/field/operator_wikidata/missing': 196,
'atp/field/twitter/missing': 196,
'atp/item_scraped_host_count/smashburger.com': 196,
'atp/nsi/perfect_match': 196,
'atp/structured_data/unmapped/amenity_features': 181,
'downloader/request_bytes': 207365, …
```

[Smashburger] Fix Spider

---

locations/spiders/cenex.py

**_Fixes : updated start_requests to fix spider_**
```python
{'atp/brand/Cenex': 1223,
'atp/brand_wikidata/Q62127191': 1223,
'atp/category/amenity/fuel': 1223,
'atp/clean_strings/name': 39,
'atp/country/US': 1223,
'atp/field/branch/missing': 1223,
'atp/field/city/missing': 1223,
'atp/field/email/missing': 1223,
'atp/field/image/missing': 1223,
'atp/field/opening_hours/missing': 308,
'atp/field/operator/missing': 1223,
'atp/field/operator_wikidata/missing': 1223,
'atp/field/postcode/missing': 1223,
'atp/field/state/from_reverse_geocoding': 1223,
'atp/field/street_address/missing': 1223,
'atp/field/twitter/missing': 1223,
'atp/field/website/missing': 1223,
'atp/item_scraped_host_count/www.cenex.com': 1223,
'atp/nsi/cc_match': 1223, …
```

[Cenex] Fix Spider

---

locations/categories.py
locations/spiders/ikea.py

```python
{'atp/brand/IKEA': 1588,
'atp/brand_wikidata/Q54078': 1588,
'atp/category/amenity/cafe': 85,
'atp/category/amenity/fast_food': 649,
'atp/category/leisure/indoor_play': 274,
'atp/category/shop/convenience': 134,
'atp/category/shop/furniture': 446,
'atp/country/AE': 11,
'atp/country/AT': 32,
'atp/country/AU': 47,
'atp/country/BE': 8,
'atp/country/BH': 5,
'atp/country/CA': 60,
'atp/country/CH': 40,
'atp/country/CL': 2,
'atp/country/CN': 71,
'atp/country/CZ': 14,
'atp/country/DE': 211,
'atp/country/DK': 27,
'atp/country/EG': 6,
'atp/country/ES': 114,
'atp/country/FI': 25,
'atp/country/FR': 92,
'atp/country/GB': 97,
'atp/country/HR': 6,
'atp/country/HU': 18,
'atp/country/IE': 5,
'atp/country/IL': 5,
'atp/country/IN': 13,
'atp/country/IT': 111, …
```

[IKEA] Collect more location types

---

locations/spiders/mcdonalds_latin_america.py

```python
{"atp/brand/McDonald's": 3718,
'atp/brand_wikidata/Q38076': 3718,
'atp/category/amenity/fast_food': 3718,
'atp/clean_strings/name': 17,
'atp/clean_strings/street_address': 39,
'atp/country/AR': 404,
'atp/country/BR': 2240,
'atp/country/CL': 190,
'atp/country/CO': 67,
'atp/country/CR': 76,
'atp/country/EC': 32,
'atp/country/GF': 3,
'atp/country/GP': 9,
'atp/country/MQ': 5,
'atp/country/MX': 365,
'atp/country/PA': 80,
'atp/country/PE': 26,
'atp/country/PR': 57,
'atp/country/UY': 46,
'atp/country/VE': 118,
'atp/field/branch/missing': 3718,
'atp/field/city/missing': 285,
'atp/field/email/missing': 3718,
'atp/field/image/missing': 3718, …
```

[Mcdonalds Latin America] Fix KeyError to recover lost POIs count for the spider

---

locations/spiders/regions_bank_us.py

```py
{'atp/brand/Regions Bank': 1454,
'atp/brand_wikidata/Q917131': 1454,
'atp/category/amenity/atm': 197,
'atp/category/amenity/bank': 1257,
'atp/country/US': 1454,
'atp/field/email/missing': 1454,
'atp/field/image/dropped': 197,
'atp/field/image/missing': 197,
'atp/field/name/missing': 197,
'atp/field/operator/missing': 1257,
'atp/field/operator_wikidata/missing': 1257,
'atp/field/phone/missing': 197,
'atp/field/twitter/missing': 1454,
'atp/item_scraped_host_count/www.regions.com': 1454,
'atp/nsi/cc_match': 1454,
'atp/operator/Regions Bank': 197,
'atp/operator_wikidata/Q917131': 197,
'downloader/request_bytes': 733798,
'downloader/request_count': 1456,
'downloader/request_method_count/GET': 1456,
'downloader/response_bytes': 27522749,
'downloader/response_count': 1456, …
```

New spider: Regions Bank (1454 locations)

---

locations/spiders/supa_roof_za.py

`start_url` updated and code refactored to use `JSON Blob` to fix the spider.
```python
{'atp/brand/Supa-Roof': 30,
'atp/brand_wikidata/Q116474839': 30,
'atp/category/shop/trade': 30,
'atp/country/ZA': 30,
'atp/field/country/from_spider_name': 30,
'atp/field/postcode/missing': 30,
'atp/field/street_address/missing': 30,
'atp/item_scraped_host_count/shop.suparoof.co.za': 30,
'atp/nsi/perfect_match': 30,
'downloader/request_bytes': 621, …
```

[Supa Roof ZA] Fix spider

---

locations/spiders/dm.py

**_Fixes : Fixes key error to fix spider_**
```python
{'atp/brand/dm': 3569,
'atp/brand_wikidata/Q266572': 3569,
'atp/category/shop/chemist': 3569,
'atp/country/AT': 378,
'atp/country/BA': 93,
'atp/country/BG': 120,
'atp/country/CZ': 237,
'atp/country/DE': 1648,
'atp/country/HR': 178,
'atp/country/HU': 256,
'atp/country/IT': 28,
'atp/country/MK': 26,
'atp/country/PL': 53,
'atp/country/RO': 158,
'atp/country/RS': 134,
'atp/country/SI': 101,
'atp/country/SK': 159,
'atp/field/branch/missing': 3569,
'atp/field/email/missing': 3569,
'atp/field/image/missing': 3569,
'atp/field/operator/missing': 3569, …
```

[DM] Fix Spider

---

locations/spiders/floorworld_au.py

**_Fixes : updated parse method to fix spider_**
```python
{'atp/brand/Floorworld': 52,
'atp/brand_wikidata/Q117156913': 52,
'atp/category/shop/flooring': 52,
'atp/clean_strings/city': 7,
'atp/clean_strings/name': 12,
'atp/clean_strings/phone': 6,
'atp/country/AU': 52,
'atp/field/branch/missing': 52,
'atp/field/country/from_spider_name': 52,
'atp/field/image/missing': 52,
'atp/field/twitter/missing': 52,
'atp/item_scraped_host_count/www.floorworld.com.au': 52,
'atp/nsi/perfect_match': 52, …
```

[Floorworld AU] Fix Spider

---

locations/spiders/td_bank.py

```py
{'atp/brand/TD': 1983,
'atp/brand/TD Bank': 1665,
'atp/brand_wikidata/Q1080670': 1983,
'atp/brand_wikidata/Q7669891': 1665,
'atp/category/amenity/atm': 1461,
'atp/category/amenity/bank': 2187,
'atp/country/CA': 1983,
'atp/country/US': 1665,
'atp/field/branch/missing': 3648,
'atp/field/city/missing': 3648,
'atp/field/email/missing': 3648,
'atp/field/image/missing': 3648,
'atp/field/name/missing': 1461,
'atp/field/opening_hours/missing': 1461,
'atp/field/operator/missing': 2187,
'atp/field/operator_wikidata/missing': 2187,
'atp/field/phone/missing': 1471,
'atp/field/postcode/missing': 3648,
'atp/field/state/from_reverse_geocoding': 3648,
'atp/field/street_address/missing': 3648,
'atp/field/twitter/missing': 3648, …
```

New spider: TD Bank (3648 locations)

---

locations/spiders/pet_food_express_us.py

```py
{'atp/brand/Pet Food Express': 69,
'atp/brand_wikidata/Q7171541': 69,
'atp/category/shop/pet': 69,
'atp/country/US': 69,
'atp/field/country/from_spider_name': 69,
'atp/field/email/missing': 69,
'atp/field/image/missing': 69,
'atp/field/opening_hours/missing': 69,
'atp/field/operator/missing': 69,
'atp/field/operator_wikidata/missing': 69,
'atp/field/state/from_reverse_geocoding': 69,
'atp/field/twitter/missing': 69,
'atp/field/website/missing': 69,
'atp/item_scraped_host_count/apis.petfood.express': 69,
'atp/nsi/perfect_match': 69,
'downloader/request_bytes': 679,
'downloader/response_bytes': 7757, …
```

New spider: Pet Food Express (69 locations)

---

locations/spiders/baja_fresh_us.py

```py
{'atp/brand/Baja Fresh': 75,
'atp/brand_wikidata/Q2880019': 75,
'atp/category/amenity/fast_food': 75,
'atp/clean_strings/street_address': 32,
'atp/country/US': 75,
'atp/field/email/missing': 75,
'atp/item_scraped_host_count/www.bajafresh.com': 75,
'atp/nsi/perfect_match': 75,
'downloader/request_bytes': 667,
'downloader/response_bytes': 40927,
'elapsed_time_seconds': 2.722402, …
```

New spider: Baja Fresh (75 locations)

---

locations/spiders/sigma_it.py

```python
{'atp/brand/Sigma': 532,
'atp/brand_wikidata/Q3977979': 532,
'atp/category/shop/supermarket': 532,
'atp/clean_strings/street_address': 2,
'atp/country/IT': 532,
'atp/field/branch/missing': 532,
'atp/field/city/missing': 532,
'atp/field/country/from_spider_name': 532,
'atp/field/email/missing': 139,
'atp/field/image/missing': 532,
'atp/field/operator/missing': 532,
'atp/field/operator_wikidata/missing': 532,
'atp/field/phone/invalid': 22,
'atp/field/phone/missing': 36,
'atp/field/postcode/missing': 532,
'atp/field/state/missing': 532,
'atp/field/twitter/missing': 532,
'atp/item_scraped_host_count/www.supersigma.com': 532, …
```

[Sigma IT] Fix Spider

---

locations/spiders/sola_salon_studios.py

```python
{'atp/brand/Sola Salons': 747,
'atp/brand_wikidata/Q64337426': 747,
'atp/category/shop/beauty': 747,
'atp/cdn/cloudflare/response_count': 748,
'atp/cdn/cloudflare/response_status_count/200': 748,
'atp/clean_strings/city': 3,
'atp/clean_strings/postcode': 69,
'atp/country/CA': 5,
'atp/country/US': 742,
'atp/field/branch/missing': 747,
'atp/field/email/missing': 747,
'atp/field/image/missing': 747,
'atp/field/opening_hours/missing': 747,
'atp/field/operator/missing': 747,
'atp/field/operator_wikidata/missing': 747,
'atp/field/twitter/missing': 747,
'atp/item_scraped_host_count/www.solasalonstudios.com': 747,
'atp/nsi/perfect_match': 747, …
```

[Sola Salon Studios] Update API URL to fix the spider

---

locations/spiders/banner_health.py

```python
{'atp/category/amenity/clinic': 577,
'atp/category/multiple': 577,
'atp/cdn/cloudflare/response_count': 578,
'atp/cdn/cloudflare/response_status_count/200': 578,
'atp/clean_strings/name': 34,
'atp/country/US': 577,
'atp/field/branch/missing': 577,
'atp/field/brand/missing': 577,
'atp/field/brand_wikidata/missing': 577,
'atp/field/email/missing': 577,
'atp/item_scraped_host_count/www.bannerhealth.com': 577,
'atp/nsi/cc_match': 577,
'atp/operator/Banner Health': 577,
'atp/operator_wikidata/Q4856918': 577,
'downloader/exception_count': 8,
'downloader/exception_type_count/twisted.internet.error.TimeoutError': 8,
'downloader/request_bytes': 441320,
'downloader/request_count': 586, …
```

[Banner Health] Fix Spider

---

locations/spiders/hsbc.py

HSBC has been acquired by some other groups and no longer operates in [AR](https://www.hsbc.com.ar/anuncio/despedida/) & [AM](https://www.hsbc.am/en-am/announcements/goodbye/).

[HSBC] Remove AR & AM countries urls where HSBC no longer operates

---

locations/spiders/decathlon_ma.py

#12121
```
{'atp/brand/Decathlon': 18,
'atp/brand_wikidata/Q509349': 18,
'atp/category/shop/sports': 18,
'atp/country/MA': 18,
'atp/field/branch/missing': 18,
'atp/field/country/from_spider_name': 18,
'atp/item_scraped_host_count/www.decathlon.ma': 18,
'atp/nsi/cc_match': 18,
'downloader/request_bytes': 907, …
```

New spider: Decathlon MA (18 locations)

---

locations/spiders/mcgrath_au.py

Doesn't actually result in more results, since those pages didn't have any locations to scrape. It's just better to catch known issues instead of raising exceptions.

McGrath: Fix IndexError

---

locations/spiders/pdq_us.py

Yield more locations by removing opening hours parsing. Not worth effort to fix it as opening hours fields now contain address occasionally as well as multiple opening hours formats.

[PDQ US] Remove opening hours as bad data

---

locations/spiders/armaguard_au.py

```python
{'atp/brand/Armaguard': 1743,
'atp/brand_wikidata/Q118898974': 1743,
'atp/category/amenity/atm': 1743,
'atp/country/AU': 1743,
'atp/field/email/missing': 1743,
'atp/field/image/missing': 1743,
'atp/field/name/missing': 1743,
'atp/field/operator/missing': 1743,
'atp/field/operator_wikidata/missing': 1743,
'atp/field/phone/missing': 1743,
'atp/field/twitter/missing': 1743,
'atp/field/website/missing': 1743,
'atp/item_scraped_host_count/app.ehoundplatform.com': 1743,
'atp/nsi/perfect_match': 1743,
'downloader/request_bytes': 569,
'downloader/response_bytes': 158947, …
```

[Armaguard AU] Add Spider (1743 locations)

---

locations/spiders/blink.py

Makes one request to get a list of all station locations, then two requests for each station: first to get station information, then to get information about the chargers at each station. It seems annoying to me to have to make so many requests, but it's far from the only spider that makes around 1 request per location, so whatever. If the maintainers request, I can reduce the level of detail and reduce the number of requests: either remove the second request per station and don't collect information about chargers, or remove both requests per station and only get coordinates.
```py
{'atp/blink/unknown_socket/GBT': 8,
'atp/brand/Blink': 34308,
'atp/brand_wikidata/Q62065645': 34308,
'atp/category/amenity/charging_station': 7893,
'atp/category/man_made/charge_point': 26415, …
```

New spider: Blink (7893 charging stations + 26415 charge points)

---

locations/spiders/mitsubishi_tw.py

This site stores car shops and repairs as separate locations even if address is the same (refs are different though). I'm not convinced enough to write some custom code that will merge these items.
```json
{
"atp/brand/Mitsubishi": 222,
"atp/brand_wikidata/Q36033": 222,
"atp/category/shop/car": 103,
"atp/category/shop/car_repair": 119,
"atp/clean_strings/addr_full": 2,
"atp/country/TW": 222,
"atp/field/branch/missing": 222,
"atp/field/city/missing": 222,
"atp/field/country/from_spider_name": 222,
"atp/field/email/missing": 222,
"atp/field/image/missing": 222,
"atp/field/opening_hours/missing": 222,
"atp/field/operator/missing": 222,
"atp/field/operator_wikidata/missing": 222,
"atp/field/postcode/missing": 222,
"atp/field/state/missing": 222, …
```

[mitsubishi_tw] add spider (222 locations)

---

locations/spiders/murphy_usa_us.py

```python
{'atp/brand/Murphy Express': 420,
'atp/brand/Murphy USA': 1172,
'atp/brand_wikidata/Q19604459': 1592,
'atp/category/amenity/fuel': 1592,
'atp/country/US': 1592,
'atp/field/branch/missing': 1592,
'atp/field/email/missing': 1592,
'atp/field/image/missing': 1592,
'atp/field/operator/missing': 1592,
'atp/field/operator_wikidata/missing': 1592,
'atp/field/twitter/missing': 1592,
'atp/field/website/missing': 1592,
'atp/item_scraped_host_count/service.murphydriverewards.com': 1592,
'atp/nsi/match_failed': 1592,
'downloader/request_bytes': 1059045,
'downloader/request_count': 1594,
'downloader/request_method_count/GET': 1594,
'downloader/response_bytes': 2869632,
'downloader/response_count': 1594,
'downloader/response_status_count/200': 1594,
'elapsed_time_seconds': 5.853244, …
```

[Murphy USA] Improve branding

---

locations/spiders/pizza_hut_vn.py

Updated API bearer token generation method to fix the spider.
```python
{'atp/brand/Pizza Hut': 119,
'atp/brand_wikidata/Q191615': 119,
'atp/category/amenity/restaurant': 119,
'atp/clean_strings/addr_full': 8,
'atp/clean_strings/branch': 2,
'atp/clean_strings/lat': 1,
'atp/clean_strings/lon': 118,
'atp/country/VN': 119,
'atp/field/city/missing': 119,
'atp/field/country/from_spider_name': 119,
'atp/field/email/missing': 119,
'atp/field/image/missing': 119,
'atp/field/operator/missing': 119,
'atp/field/operator_wikidata/missing': 119,
'atp/field/phone/missing': 119,
'atp/field/postcode/missing': 119,
'atp/field/state/missing': 119,
'atp/field/street_address/missing': 119,
'atp/field/twitter/missing': 119,
'atp/field/website/missing': 119,
'atp/item_scraped_host_count/rwapi.pizzahut.vn': …
```

[Pizza Hut VN] Fix spider

---

locations/spiders/coinstar.py

**_The spider works fine from IN, so flag as requires proxy_** 
```python
{'atp/brand/Coinstar': 24968,
'atp/brand_wikidata/Q5141641': 24968,
'atp/category/amenity/payment_terminal': 24968,
'atp/cdn/cloudflare/response_count': 505,
'atp/cdn/cloudflare/response_status_count/200': 505,
'atp/clean_strings/postcode': 23194,
'atp/clean_strings/street_address': 8,
'atp/country/CA': 572,
'atp/country/DE': 2499,
'atp/country/ES': 683,
'atp/country/FR': 1279,
'atp/country/GB': 1977,
'atp/country/IE': 105,
'atp/country/IT': 335,
'atp/country/US': 17518,
'atp/field/branch/missing': 24968,
'atp/field/email/missing': 24968,
'atp/field/image/missing': 24968,
'atp/field/opening_hours/missing': 24968,
'atp/field/operator/missing': 24968, …
```

[Coinstar] Flag coinstar spider as requires proxy

---

locations/spiders/allpoint.py

```python
{'atp/brand/Allpoint': 35440,
'atp/brand_wikidata/Q4733264': 35440,
'atp/category/amenity/atm': 35440,
'atp/clean_strings/city': 4,
'atp/clean_strings/street': 3,
'atp/country/AU': 263,
'atp/country/CA': 352,
'atp/country/GB': 8722,
'atp/country/MX': 325,
'atp/country/US': 25778,
'atp/field/branch/missing': 35440,
'atp/field/email/missing': 35440,
'atp/field/image/missing': 35440,
'atp/field/name/missing': 35440,
'atp/field/opening_hours/missing': 35440,
'atp/field/operator/missing': 35440,
'atp/field/operator_wikidata/missing': 35440,
'atp/field/phone/missing': 35440,
'atp/field/street_address/missing': 35440,
'atp/item_scraped_host_count/clsws.locatorsearch.net': 55644,
'atp/nsi/perfect_match': 35440,
'downloader/request_bytes': 470990,
'downloader/request_count': 558, …
```

[Allpoint] Add Spider (35440 locations)

---

locations/spiders/aarons.py

`Sitemap` no longer has location urls, hence switched to `CrawlSpider`.
```python
{"atp/brand/Aaron's": 961,
'atp/brand_wikidata/Q10397787': 961,
'atp/category/shop/furniture': 961,
'atp/country/CA': 18,
'atp/country/US': 943,
'atp/field/branch/missing': 961,
'atp/field/email/missing': 961,
'atp/field/image/missing': 961,
'atp/field/operator/missing': 961,
'atp/field/operator_wikidata/missing': 961,
'atp/field/twitter/missing': 961,
'atp/item_scraped_host_count/www.aarons.com': 961,
'atp/nsi/perfect_match': 961,
'downloader/request_bytes': 423308,
'downloader/request_count': 1100,
'downloader/request_method_count/GET': 1100,
'downloader/response_bytes': 56094521,
'downloader/response_count': 1100,
'downloader/response_status_count/200': 1097, …
```

[Aarons ] Switch to API to fix spider

---

locations/spiders/burlington_us.py

```python
{'atp/brand/Burlington': 1112,
'atp/brand_wikidata/Q4999220': 1112,
'atp/category/shop/department_store': 1112,
'atp/cdn/cloudflare/response_count': 1114,
'atp/cdn/cloudflare/response_status_count/200': 1114,
'atp/country/US': 1112,
'atp/field/branch/missing': 1112,
'atp/field/email/missing': 1112,
'atp/field/image/missing': 1112,
'atp/field/operator/missing': 1112,
'atp/field/operator_wikidata/missing': 1112,
'atp/field/twitter/missing': 1112,
'atp/item_scraped_host_count/stores.burlington.com': 1112,
'atp/nsi/perfect_match': 1112,
'downloader/request_bytes': 413600,
'downloader/request_count': 1114,
'downloader/request_method_count/GET': 1114,
'downloader/response_bytes': 42955985,
'downloader/response_count': 1114, …
```

[Burlington US] Update sitmap url to fix  spider

---

locations/spiders/marcos.py

```py
{"atp/brand/Marco's Pizza": 1241,
'atp/brand_wikidata/Q6757382': 1241,
'atp/category/amenity/fast_food': 1241,
'atp/clean_strings/street_address': 9,
'atp/country/BH': 6,
'atp/country/PR': 53,
'atp/country/US': 1182,
'atp/field/branch/missing': 1241,
'atp/field/email/missing': 1241,
'atp/field/image/missing': 1241,
'atp/field/operator/missing': 1241,
'atp/field/operator_wikidata/missing': 1241,
'atp/field/state/from_reverse_geocoding': 6,
'atp/field/twitter/missing': 1241,
'atp/field/website/missing': 1241,
'atp/item_scraped_host_count/order.marcos.com': 1241,
'atp/nsi/perfect_match': 1241,
'downloader/request_bytes': 1459, …
```

New spider: Marco's Pizza (1241 locations)

---

locations/hours.py
tests/test_opening_hours.py

adds a regression test and fixes problem reported in https://github.com/alltheplaces/alltheplaces/pull/12568#discussion_r1987046526
this problem existed in past (`10:00-0:00` and `10:00-00:00` was resulting in a different output) but become more noticeable with #11989
I am quite unhappy about this fix as it leaves close_time ending at 24:00 (specified in unusual formats) with the same bug
but problem here is that using `time.strptime` on `24:00` makes it explode (at least with `"%H:%M"`) so you cannot parse and then check what is going on
but I have no better ideas right now

harden close_time parsing

---

locations/spiders/truist_us.py

The site does have an API, but it's limited to 100 results per query, which would end up needing more requests than locations. :disappointed: 
```py
{'atp/brand/Truist': 3197,
'atp/brand_wikidata/Q795486': 3197,
'atp/category/amenity/atm': 1294,
'atp/category/amenity/bank': 1903,
'atp/country/US': 3197,
'atp/field/email/missing': 3197,
'atp/field/image/dropped': 3197,
'atp/field/image/missing': 3197,
'atp/field/name/missing': 1294,
'atp/field/operator/missing': 1903,
'atp/field/operator_wikidata/missing': 1903,
'atp/field/twitter/missing': 3197,
'atp/item_scraped_host_count/www.truist.com': 3532,
'atp/nsi/cc_match': 3197,
'atp/operator/Truist': 1294,
'atp/operator_wikidata/Q795486': 1294,
'downloader/exception_count': 3, …
```

New spider: Truist Financial (3197 locations)

---

ci/buildspec.yml
ci/run_pr_spiders.sh
locations/spiders/dicks_sporting_goods.py

The Personal Access Token that I was using through @scraperbot to post comments on these PRs stopped working at some point this weekend. I tried to regenerate it but couldn't get the permissions right for whatever reason. It seems that the "right" way to do it is to use a GitHub App, so I created one of those and adjusted the script to use that flow to generate an access token instead.

Attempt to change from PAT to GitHub App installation token

---

docs/CATEGORIES.md
locations/categories.py
locations/spiders/czech_post_cz.py

The only interesting thing here I'm using `amenity=yes` as a "This is a POI, but we don't know the category". I think a fair US example of this is a 7-Eleven that also offers a UPS drop off, it isn't a stand alone POI, it's an attribute of 7-Eleven. That 7-Eleven probably also does FedEx and Western Union money transfers, it is 1 POI, not 4.
In this spider, the majority of the POIs are not `amenity=post_office` as the current output suggests, but a different shop (could be `shop=supermarket`, `shop=convenience`, `shop=newsagent` etc) but we don't know.
We had previously softly agreed with Matkoniecz that these types of POIs shouldn't get a category, but it didn't work. Here with errors/stats complaining ended up with bad categories being added and he ended up just excluding the spiders …

[Česká Pošta] Clean brand and categories

---

locations/spiders/mitsubishi_dk.py

```python
{'atp/brand/Mitsubishi': 30,
'atp/brand_wikidata/Q36033': 30,
'atp/category/shop/car': 24,
'atp/category/shop/car_repair': 6,
'atp/country/DK': 28,
'atp/country/FO': 1,
'atp/country/GL': 1,
'atp/field/branch/missing': 30,
'atp/field/image/missing': 30,
'atp/field/opening_hours/missing': 30,
'atp/field/state/missing': 30,
'atp/item_scraped_host_count/mitsubishi-motors.dk': 30,
'atp/nsi/cc_match': 30,
'downloader/request_bytes': 658,
'downloader/response_bytes': 5048, …
```

[Mitsubishi DK] Add spider (30 locations)

---

locations/spiders/mitsubishi_be_lu.py

```python
{'atp/brand/Mitsubishi': 60,
'atp/brand_wikidata/Q36033': 60,
'atp/category/shop/car_repair': 60,
'atp/country/BE': 56,
'atp/country/LU': 4,
'atp/field/branch/missing': 60,
'atp/field/country/from_website_url': 59,
'atp/field/state/missing': 59,
'atp/item_scraped_host_count/mitsubishi-motors.be': 60,
'atp/nsi/cc_match': 60,
'downloader/response_bytes': 14121, …
```

[Mitsubishi BE LU] Update  Mitsubishi BE Spider to distinguish LU locations

---

locations/spiders/mitsubishi_pr.py

```python
{'atp/brand/Mitsubishi': 20,
'atp/brand_wikidata/Q36033': 20,
'atp/category/shop/car': 20,
'atp/country/PR': 20,
'atp/field/city/missing': 20,
'atp/field/state/missing': 20,
'atp/item_scraped_host_count/www.mitsubishimotors.pr': 20,
'atp/nsi/cc_match': 20,
'downloader/request_bytes': 318,
'downloader/response_bytes': 32980, …
```

[Mitsubishi PR] Add Spider (20 locations)

---

locations/spiders/mitsubishi_by_ru.py

```python
{'atp/brand/Mitsubishi': 89,
'atp/brand_wikidata/Q36033': 89,
'atp/category/shop/car': 89,
'atp/country/BY': 4,
'atp/country/RU': 85,
'atp/field/branch/missing': 89,
'atp/field/country/from_website_url': 89,
'atp/field/opening_hours/missing': 89,
'atp/field/postcode/missing': 89,
'atp/item_scraped_host_count/www.mitsubishi-motors.ru': 89,
'atp/nsi/cc_match': 89,
'downloader/request_bytes': 685, …
```

[Mitsubishi BY RU] Add spider (89 locations)

---

locations/spiders/mcdonalds_at.py

```
{'atp/brand/McCafé': 198,
"atp/brand/McDonald's": 205,
'atp/brand_wikidata/Q3114287': 198,
'atp/brand_wikidata/Q38076': 205,
'atp/category/amenity/cafe': 198,
'atp/category/amenity/fast_food': 205,
'atp/country/AT': 403,
'atp/field/branch/missing': 403,
'atp/field/city/missing': 403,
'atp/field/country/from_spider_name': 403,
'atp/field/email/missing': 403,
'atp/field/image/missing': 403,
'atp/field/operator/missing': 403,
'atp/field/operator_wikidata/missing': 403,
'atp/field/phone/missing': 403,
'atp/field/postcode/missing': 403,
'atp/field/state/missing': 403,
'atp/field/street_address/missing': 403,
'atp/field/twitter/missing': 403,
'atp/item_scraped_host_count/www.mcdonalds.at': 403,
'atp/nsi/cc_match': 205,
'atp/nsi/perfect_match': 198,
'downloader/request_bytes': 118681, …
```

[mcdonalds_at] Add McCafe locations and Opening Hours

---

locations/spiders/mitsubishi_ch.py

```python
{'atp/brand/Mitsubishi': 105,
'atp/brand_wikidata/Q36033': 105,
'atp/category/shop/car': 44,
'atp/category/shop/car_repair': 61,
'atp/country/CH': 105,
'atp/field/branch/missing': 105,
'atp/field/country/from_spider_name': 105,
'atp/field/opening_hours/missing': 105,
'atp/field/operator/missing': 105,
'atp/field/operator_wikidata/missing': 105,
'atp/field/state/missing': 105,
'atp/field/twitter/missing': 105,
'atp/item_scraped_host_count/www.mitsubishi-motors.ch': 105,
'atp/nsi/cc_match': 105,
'downloader/request_bytes': 40635,
'downloader/request_count': 107, …
```

[Mitsubishi CH] Add spider (105 locations)

---

locations/spiders/mitsubishi_dk_se.py

```python
{'atp/brand/Mitsubishi': 92,
'atp/brand_wikidata/Q36033': 92,
'atp/category/shop/car': 52,
'atp/category/shop/car_repair': 40,
'atp/country/DK': 28,
'atp/country/FO': 1,
'atp/country/GL': 1,
'atp/country/SE': 62,
'atp/field/branch/missing': 92,
'atp/field/image/missing': 92,
'atp/field/opening_hours/missing': 92,
'atp/field/operator/missing': 92,
'atp/field/operator_wikidata/missing': 92,
'atp/field/state/missing': 92,
'atp/field/twitter/missing': 92,
'atp/item_scraped_host_count/mitsubishi-motors.dk': 30,
'atp/item_scraped_host_count/mitsubishi-motors.se': 62,
'atp/nsi/cc_match': 92,
'downloader/request_bytes': 1631, …
```

[Mitsubishi DK SE] Update Mitsubishi DK Spider to add SE locations

---

locations/spiders/gbfs.py

I made a [PR](https://github.com/alltheplaces/alltheplaces/pull/10184) adding brands from the name of the dataset back in September. As you can see the majority (for brands I added which were not all) are bicycle rentals. The dataset titles must have changed as the stop_positions have increased since then. Now as this is a bike share feed I think we can change the default to bicycle rental.

[gbfs] Changed default category to Bicycle_rental

---

locations/spiders/mcdonalds.py

for available countries added mccafe brand pois
```{'atp/brand/McCafé': 2694,
"atp/brand/McDonald's": 15792,
'atp/brand_wikidata/Q3114287': 2694,
'atp/brand_wikidata/Q38076': 15792,
'atp/category/amenity/cafe': 2694,
'atp/category/amenity/fast_food': 15792,
'atp/clean_strings/city': 3,
'atp/clean_strings/email': 17,
'atp/clean_strings/phone': 977,
'atp/clean_strings/postcode': 9,
'atp/country/AE': 91,
'atp/country/BH': 18,
'atp/country/CA': 2187,
'atp/country/CH': 277,
'atp/country/DE': 2123,
'atp/country/DK': 120,
'atp/country/FI': 86,
'atp/country/GB': 1472,
'atp/country/HU': 180,
'atp/country/IE': 91,
'atp/country/KW': 53,
'atp/country/NL': 474,
'atp/country/NO': 22,
'atp/country/OM': 25,
'atp/country/QA': 106,
'atp/country/SA': 103,
'atp/country/SE': 89, …
```

[mcondalds] add mccafe pois (2694 locations)

---

locations/spiders/mitsubishi_br.py

```python
'atp/clean_strings/branch': 4,
'atp/clean_strings/city': 17,
'atp/clean_strings/state': 5,
'atp/country/BR': 138,
'atp/field/country/from_spider_name': 138,
'atp/field/image/missing': 138,
'atp/field/name/missing': 5,
'atp/field/street_address/missing': 138,
'atp/field/website/missing': 84,
'atp/item_scraped_host_count/api.mitsubishimotors.com.br': 138,
'atp/nsi/cc_match': 133,
'atp/nsi/match_failed': 5,
'downloader/request_bytes': 355, …
```

[Mitsubishi BR] Add Spider (138 locations)

---

locations/spiders/mitsubishi_africa.py

```python
{'atp/brand/Mitsubishi': 33,
'atp/brand_wikidata/Q36033': 33,
'atp/category/shop/car': 33,
'atp/country/BJ': 2,
'atp/country/CF': 1,
'atp/country/CI': 5,
'atp/country/GA': 2,
'atp/country/GH': 4,
'atp/country/LR': 1,
'atp/country/MG': 4,
'atp/country/MR': 3,
'atp/country/NG': 10,
'atp/country/TG': 1,
'atp/field/city/missing': 33,
'atp/field/country/from_reverse_geocoding': 7,
'atp/field/country/from_website_url': 26,
'atp/field/email/missing': 33,
'atp/field/image/missing': 33,
'atp/field/opening_hours/missing': 33,
'atp/field/operator/missing': 33,
'atp/field/operator_wikidata/missing': 33,
'atp/field/postcode/missing': 33,
'atp/field/state/missing': 26,
'atp/field/twitter/missing': 33,
'atp/item_scraped_host_count/mitsubishimotors.cfaomotors-gabon. …
```

[Mitsubishi Africa] Add Spider (33 locations)

---

locations/spiders/mcdonalds_pl.py

```
{'atp/brand/McCafé': 550,
"atp/brand/McDonald's": 583,
'atp/brand_wikidata/Q3114287': 550,
'atp/brand_wikidata/Q38076': 583,
'atp/category/amenity/cafe': 550,
'atp/category/amenity/fast_food': 583,
'atp/clean_strings/street_address': 27,
'atp/country/PL': 1133,
'atp/field/branch/missing': 1133,
'atp/field/country/from_spider_name': 1133,
'atp/field/email/missing': 1133,
'atp/field/image/missing': 1133,
'atp/field/operator/missing': 1133,
'atp/field/operator_wikidata/missing': 1133,
'atp/field/twitter/missing': 1133,
'atp/item_scraped_host_count/mcdonalds.pl': 1133,
'atp/nsi/cc_match': 583,
'atp/nsi/perfect_match': 550,
'downloader/request_bytes': 607,
'downloader/response_bytes': 94076, …
```

[mcdonalds_pl] add mccafe pois (550 locations)

---

locations/spiders/mitsubishi_tr.py

```python
{'atp/brand/Mitsubishi': 49,
'atp/brand_wikidata/Q36033': 49,
'atp/category/shop/car': 11,
'atp/category/shop/car_repair': 38,
'atp/clean_strings/lon': 2,
'atp/clean_strings/phone': 3,
'atp/country/TR': 49,
'atp/field/branch/missing': 49,
'atp/field/country/from_spider_name': 49,
'atp/field/image/missing': 49,
'atp/field/opening_hours/missing': 49,
'atp/field/operator/missing': 49,
'atp/field/operator_wikidata/missing': 49,
'atp/field/postcode/missing': 49,
'atp/field/state/missing': 49,
'atp/field/street_address/missing': 49,
'atp/field/twitter/missing': 49, …
```

[Mitsubishi TR] Add  Spider (49 locations)

---

locations/spiders/betts_au.py
locations/spiders/carbon_health_us.py
locations/spiders/cum_books_za.py
locations/spiders/ernstings_family.py
locations/spiders/ikea.py
locations/spiders/ismash_gb.py
locations/spiders/kfc_fr.py
locations/spiders/linde_direct_us.py
locations/spiders/misenso_ch.py
locations/spiders/mister_minit_asia_pacific.py
locations/spiders/natwest_gb.py
locations/spiders/scribbler_gb.py
locations/spiders/starbucks_reserve.py
locations/spiders/veggie_grill_us.py

There are other types of Google IDs such as Google Maps CID which differ from Google Maps Place IDs. Split the ref:google tag into more specific tags to allow for both CIDs and Place IDs.
Note that from
https://taginfo.openstreetmap.org/keys/ref%3Agoogle#values it appears Google Maps redirect URLs are used for ref:google. These appear to be deprecated, as will the goo.gl redirector some time later in 2025. There appears to be no other existing ref tags used for extracing Google Maps CIDs or Place IDs so we're free to make something up.

Switch ref:google tag to ref:google:place_id

---

locations/categories.py
locations/hours.py

Per discussion in PR #12568.
If source data has two features:
{
"feature_id": "1",
"services": ["Showers", "Toilets"],
"cards_accepted": ["MasterCard", "Visa"],
"open_days": ["Monday", "Wednesday"],
}
{
"feature_id": "2",
"services": ["Showers"],
"cards_accepted": ["Visa"],
"open_days": ["Tuesday", "Thursday"],
}
Spiders should not assume that feature 2 lacks Toilets, refuses to accept MasterCard and is closed Monday, Wednesday and Friday-Sunday each week unless there is other data available to confirm such facts.
Spiders should not assume that feature 1 is closed on Tuesday and Thursday-Sunday each week unless there is other data available to confirm such facts.
Spiders can confirm that feature 2 lacks Toilets if the front end website displaying this data states for feature 2, "Toilets: …

Update function documentation for handling ambiguous data

---

locations/spiders/kfc_au.py
locations/spiders/kfc_th.py

**_Fixes: added user_agent to kfc_au spider to fix dependent spiders i.e. kfc_th,kfc_ca,kfc_za _**
**_kfc_th_**:
```python
{'atp/brand/KFC': 1200,
'atp/brand_wikidata/Q524757': 1200,
'atp/category/amenity/fast_food': 1200,
'atp/clean_strings/city': 17,
'atp/clean_strings/state': 3,
'atp/country/TH': 1200,
'atp/field/image/missing': 1200,
'atp/field/operator/missing': 1200,
'atp/field/operator_wikidata/missing': 1200,
'atp/field/phone/invalid': 1111,
'atp/field/twitter/missing': 1200,
'atp/field/website/missing': 1200,
'atp/item_scraped_host_count/orderserv-kfc-apac-olo-api.yum.com': 1200,
'atp/nsi/cc_match': 1200,
'downloader/request_bytes': 1071101,
'downloader/request_count': 1207, …
```

[KFC TH][KFC CA][KFC ZA] Fix Spider

---

locations/spiders/ace_hardware.py

**_The spider works fine from IN, so flag as requires proxy_**
```python
{'atp/brand/Ace Hardware': 4693,
'atp/brand_wikidata/Q4672981': 4693,
'atp/category/shop/doityourself': 4693,
'atp/country/US': 4693,
'atp/field/branch/missing': 4693,
'atp/field/email/missing': 1132,
'atp/field/image/missing': 4693,
'atp/field/operator/missing': 4693,
'atp/field/operator_wikidata/missing': 4693,
'atp/field/twitter/missing': 4693,
'atp/field/website/missing': 4693,
'atp/item_scraped_host_count/www.acehardware.com': 4693,
'atp/nsi/cc_match': 4693,
'downloader/request_bytes': 12908, …
```

[Ace Hardware] Flag ace_hardware spider as requires proxy

---

ci/run_pr_spiders.sh

https://github.com/alltheplaces/alltheplaces/pull/12483 is an example of a PR where a large file is slow to download (over 60s) and an increased timeout is desirable to allow the CI process a chance to complete.

run_pr_spiders: increase timeout from 60s to 120s for running spiders

---

locations/spiders/radisson_hotels.py

```python
{'atp/brand/Art’otel': 7,
'atp/brand/Country Inn & Suites by Radisson': 12,
'atp/brand/Park Inn & Suites by Radisson': 2,
'atp/brand/Park Inn by Radisson': 92,
'atp/brand/Park Plaza Hotels & Resorts': 35,
'atp/brand/Prizeotel': 15,
'atp/brand/Radisson': 124,
'atp/brand/Radisson Blu': 335,
'atp/brand/Radisson Collection': 40,
'atp/brand/Radisson Individuals': 73,
'atp/brand/Radisson RED': 27,
'atp/brand_wikidata/Q14516231': 7,
'atp/brand_wikidata/Q1751979': 124,
'atp/brand_wikidata/Q2052550': 35,
'atp/brand_wikidata/Q28233721': 27,
'atp/brand_wikidata/Q5177332': 12,
'atp/brand_wikidata/Q60711675': 92,
'atp/brand_wikidata/Q60716706': 40,
'atp/brand_wikidata/Q7281341': 335,
'atp/category/tourism/hotel': 762,
'atp/clean_strings/email': 26,
'atp/clean_strings/phone': 30, …
```

[Radisson Hotels] Switch to API to fix the broken spider

---

locations/exporters/geojson.py
locations/spiders/infrastructure/san_francisco_mta_bicycle_parking_us.py
locations/storefinders/arcgis_feature_server.py
tests/test_geojson.py

The build failed this weekend because tippecanoe couldn't handle a feature with an invalid geometry like this (empty coordinates):
```json
{
"type":"Feature",
"id":9214,
"geometry":{"type":"Point","coordinates":[]},
"properties":{}
}
```
It sucks that ESRI generates invalid GeoJSON like this, so we should protect against it as much as possible.

Fix San Francisco spider geometries

---

locations/spiders/starbucks_za.py

**_Fixes : flag robots.txt as False to fix spider_**
```python
{'atp/brand/Starbucks': 72,
'atp/brand_wikidata/Q37158': 72,
'atp/category/amenity/cafe': 72,
'atp/cdn/cloudflare/response_count': 35,
'atp/cdn/cloudflare/response_status_count/200': 35,
'atp/country/ZA': 72,
'atp/field/image/missing': 72,
'atp/field/opening_hours/missing': 72,
'atp/field/state/missing': 72,
'atp/field/street_address/missing': 72,
'atp/field/twitter/missing': 72,
'atp/item_scraped_host_count/www.starbucks.co.za': 231,
'atp/nsi/cc_match': 72,
'downloader/request_bytes': 16988,
'downloader/request_count': 35, …
```

[Starbucks ZA] Fix Spider

---

locations/spiders/krispy_krunchy_chicken_us.py

**_Fixes : code refactored to use structured data to fix spider_**
```python
{'atp/brand/Krispy Krunchy Chicken': 3210,
'atp/brand_wikidata/Q65087447': 3210,
'atp/category/amenity/fast_food': 3210,
'atp/cdn/cloudflare/response_count': 3226,
'atp/cdn/cloudflare/response_status_count/200': 3213,
'atp/cdn/cloudflare/response_status_count/404': 13,
'atp/country/US': 3210,
'atp/field/branch/missing': 3210,
'atp/field/email/missing': 3210,
'atp/field/operator/missing': 3210,
'atp/field/operator_wikidata/missing': 3210,
'atp/field/twitter/missing': 3210,
'atp/item_scraped_host_count/locations.krispykrunchy.com': 3210,
'atp/nsi/perfect_match': 3210,
'downloader/request_bytes': 1888231, …
```

[Krispy Krunchy Chicken US] Fix Spider

---

locations/spiders/anthonys.py

Code refactored to fix the spider, since API is no longer functional.
```python
{"atp/brand/Anthony's Coal Fired Pizza": 50,
'atp/brand_wikidata/Q117536208': 50,
'atp/category/amenity/restaurant': 50,
'atp/country/US': 50,
'atp/field/city/missing': 50,
'atp/field/postcode/missing': 50,
'atp/field/state/from_reverse_geocoding': 50,
'atp/field/street_address/missing': 50,
'atp/item_scraped_host_count/acfp.com': 50,
'atp/nsi/perfect_match': 50,
'downloader/request_bytes': 598, …
```

[Anthonys] Fix spider

---

locations/spiders/pizza_express_ae.py

```python
{'atp/brand/PizzaExpress': 12,
'atp/brand_wikidata/Q662845': 12,
'atp/category/amenity/restaurant': 12,
'atp/country/AE': 12,
'atp/field/city/missing': 12,
'atp/field/country/from_spider_name': 12,
'atp/field/postcode/missing': 12,
'atp/item_scraped_host_count/www.pizzaexpress.ae': 12,
'atp/nsi/perfect_match': 12,
'downloader/request_bytes': 6450,
'downloader/request_count': 15,
'downloader/request_method_count/GET': 15,
'downloader/response_bytes': 358884, …
```

[Pizza Express AE] Fix spider

---

locations/spiders/allpoint.py

```
{'atp/brand/Allpoint': 37806,
'atp/brand_wikidata/Q4733264': 37806,
'atp/category/amenity/atm': 37806,
'atp/clean_strings/city': 10,
'atp/country/AU': 130,
'atp/country/CA': 377,
'atp/country/GB': 8129,
'atp/country/MX': 367,
'atp/country/US': 28803,
'atp/field/branch/missing': 37806,
'atp/field/email/missing': 37806,
'atp/field/image/missing': 37806,
'atp/field/name/missing': 37806,
'atp/field/opening_hours/missing': 37806,
'atp/field/operator/missing': 37806,
'atp/field/operator_wikidata/missing': 37806,
'atp/field/phone/missing': 37806,
'atp/field/twitter/missing': 37806,
'atp/field/website/missing': 37806,
'atp/item_scraped_host_count/clsws.locatorsearch.net': 59848, …
```

[Allpoint] Fix low scraped count

---

locations/spiders/hardees_us.py

**_Fixes : updated sitemap url to fix spider_**
```python
{"atp/brand/Hardee's": 1567,
'atp/brand_wikidata/Q1585088': 1567,
'atp/category/amenity/fast_food': 1567,
'atp/cdn/cloudflare/response_count': 1569,
'atp/cdn/cloudflare/response_status_count/200': 1569,
'atp/country/US': 1567,
'atp/field/branch/missing': 1567,
'atp/field/email/missing': 1567,
'atp/field/image/dropped': 1567,
'atp/field/image/missing': 1567,
'atp/field/opening_hours/missing': 1567,
'atp/field/operator/missing': 1567,
'atp/field/operator_wikidata/missing': 1567,
'atp/item_scraped_host_count/locations.hardees.com': 1567,
'atp/nsi/perfect_match': 1567,
'downloader/request_bytes': 604142,
'downloader/request_count': 1569,
'downloader/request_method_count/GET': 1569, …
```

[Hardees US] Fix Spider

---

locations/spiders/carls_jr_us.py

**_Fixes : updated sitemap_urls to fix spider_**
```python
{"atp/brand/Carl's Jr.": 1031,
'atp/brand_wikidata/Q1043486': 1031,
'atp/category/amenity/fast_food': 1031,
'atp/cdn/cloudflare/response_count': 1033,
'atp/cdn/cloudflare/response_status_count/200': 1033,
'atp/country/US': 1031,
'atp/field/branch/missing': 1031,
'atp/field/email/missing': 1031,
'atp/field/image/dropped': 1031,
'atp/field/image/missing': 1031,
'atp/field/opening_hours/missing': 1031,
'atp/field/operator/missing': 1031,
'atp/field/operator_wikidata/missing': 1031,
'atp/item_scraped_host_count/locations.carlsjr.com': 1031,
'atp/nsi/perfect_match': 1031,
'downloader/request_bytes': 397802,
'downloader/request_count': 1033,
'downloader/request_method_count/GET': 1033, …
```

[Carls JR US] Fix Spider

---

Dockerfile

The path doesn't exist anymore now that we're not in the Ubuntu image.
This caused the build to fail the last couple tries.

Fix the Dockerfile command

---

locations/spiders/car_max_us.py

**_Fixes : updated if condition to fix spider_**
```python
{'atp/brand/CarMax': 253,
'atp/brand_wikidata/Q5037190': 253,
'atp/category/shop/car': 253,
'atp/country/US': 253,
'atp/field/country/from_spider_name': 253,
'atp/field/email/missing': 253,
'atp/field/image/missing': 253,
'atp/field/opening_hours/missing': 253,
'atp/field/operator/missing': 253,
'atp/field/operator_wikidata/missing': 253,
'atp/field/phone/missing': 253,
'atp/field/twitter/missing': 253,
'atp/item_scraped_host_count/www.carmax.com': 253,
'atp/nsi/perfect_match': 253,
'downloader/request_bytes': 1027,
'downloader/response_bytes': 468576, …
```

[Car Max US ] Fix Spider

---

locations/spiders/ninety_nine_restaurant_us.py
locations/storefinders/nomnom.py

```py
{'atp/brand/Ninety Nine Restaurant & Pub': 93,
'atp/brand_wikidata/Q64358371': 93,
'atp/category/amenity/restaurant': 93,
'atp/country/US': 93,
'atp/field/email/missing': 93,
'atp/field/image/missing': 93,
'atp/field/opening_hours/missing': 93,
'atp/field/twitter/missing': 93,
'atp/field/website/missing': 93,
'atp/item_scraped_host_count/order.99restaurants.com': 93,
'downloader/request_bytes': 633,
'downloader/response_bytes': 12783, …
```

New spider: Ninety Nine Restaurant & Pub (93 locations)

---

locations/spiders/mego_lv.py

```python
{'atp/brand/Mego': 90,
'atp/brand_wikidata/Q16363314': 90,
'atp/category/shop/supermarket': 90,
'atp/country/LV': 90,
'atp/field/branch/missing': 90,
'atp/field/country/from_spider_name': 90,
'atp/field/email/missing': 90,
'atp/field/image/missing': 90,
'atp/field/operator/missing': 90,
'atp/field/operator_wikidata/missing': 90,
'atp/field/phone/missing': 90,
'atp/field/state/missing': 68,
'atp/field/street_address/missing': 90,
'atp/field/twitter/missing': 90,
'atp/field/website/missing': 90,
'atp/item_scraped_host_count/mego.lv': 90,
'atp/nsi/perfect_match': 90,
'downloader/request_bytes': 629,
'downloader/response_bytes': 227140, …
```

[Mego LV] Fix spider

---

locations/spiders/starbucks_ae.py

```python
{'atp/brand/Starbucks': 325,
'atp/brand_wikidata/Q37158': 325,
'atp/category/amenity/cafe': 325,
'atp/cdn/cloudflare/response_count': 328,
'atp/cdn/cloudflare/response_status_count/200': 328,
'atp/country/AE': 325,
'atp/field/city/missing': 325,
'atp/field/country/from_spider_name': 325,
'atp/field/email/missing': 325,
'atp/field/operator/missing': 325,
'atp/field/operator_wikidata/missing': 325,
'atp/field/postcode/missing': 325,
'atp/field/state/missing': 325,
'atp/field/twitter/missing': 325,
'atp/item_scraped_host_count/locations.starbucks.ae': 325,
'atp/nsi/cc_match': 325,
'downloader/request_bytes': 191654,
'downloader/request_count': 328, …
```

[Starbucks AE] Add spider

---

locations/spiders/pizza_hut_fr.py

```python
{'atp/brand/Pizza Hut': 118,
'atp/brand_wikidata/Q191615': 118,
'atp/category/amenity/restaurant': 118,
'atp/closed_poi': 1,
'atp/country/FR': 118,
'atp/field/email/missing': 118,
'atp/field/image/dropped': 118,
'atp/field/image/missing': 118,
'atp/field/operator/missing': 118,
'atp/field/operator_wikidata/missing': 118,
'atp/item_scraped_host_count/www.pizzahut.fr': 118,
'atp/nsi/cc_match': 118,
'downloader/request_bytes': 38738,
'downloader/request_count': 120,
'downloader/request_method_count/GET': 120,
'downloader/response_bytes': 1438756,
'downloader/response_count': 120,
'downloader/response_status_count/200': 120,
'elapsed_time_seconds': 1.189478, …
```

[Pizza Hut FR] Fix branding

---

ci/run_all_spiders.sh

We're still running into problems with the all spiders run, so this gives more room to the very dense tiles.

Allow larger tiles in the global run

---

ci/run_all_spiders.sh

Continuation from #12833
The gravestones are causing individual tiles to get very busy and fail the build.

Increase max-zoom during run_all_spiders again, again

---

locations/spiders/aldi_sud_cn.py

**_Fixes : updated parse method to fix spider_**
```python
{'atp/brand/Aldi': 70,
'atp/brand_wikidata/Q41171672': 70,
'atp/category/shop/supermarket': 70,
'atp/country/CN': 70,
'atp/field/city/missing': 70,
'atp/field/email/missing': 70,
'atp/field/image/missing': 70,
'atp/field/lat/missing': 70,
'atp/field/lon/missing': 70,
'atp/field/operator/missing': 70,
'atp/field/operator_wikidata/missing': 70,
'atp/field/phone/missing': 70,
'atp/field/postcode/missing': 70,
'atp/field/state/missing': 70,
'atp/field/street_address/missing': 70,
'atp/field/twitter/missing': 70,
'atp/field/website/missing': 70,
'atp/item_scraped_host_count/aldi.cn': 70,
'atp/nsi/cc_match': 70,
'atp/tt_locate/fail': 70,
'downloader/request_bytes': 318, …
```

[Aldi Sud CN] Fix Spider

---

locations/spiders/shell_au.py

```python
{'atp/brand/OTR': 139,
'atp/brand/Reddy Express': 565,
'atp/brand/Shell': 1112,
'atp/brand_wikidata/Q110716465': 1112,
'atp/brand_wikidata/Q116394019': 139,
'atp/brand_wikidata/Q5144653': 565,
'atp/category/amenity/fuel': 1112,
'atp/category/shop/convenience': 1056,
'atp/clean_strings/street_address': 2,
'atp/country/AU': 2168,
'atp/field/branch/missing': 1354,
'atp/field/brand/missing': 352,
'atp/field/brand_wikidata/missing': 352,
'atp/field/email/missing': 2168,
'atp/field/image/missing': 2168,
'atp/field/name/missing': 352,
'atp/field/opening_hours/missing': 1668,
'atp/field/operator/missing': 2168,
'atp/field/operator_wikidata/missing': 2168, …
```

[Shell AU] Fix Spider

---

locations/spiders/stc_se.py

```python
{'atp/brand/STC': 257,
'atp/brand_wikidata/Q124061743': 257,
'atp/category/leisure/fitness_centre': 257,
'atp/country/SE': 257,
'atp/field/country/from_spider_name': 257,
'atp/field/email/missing': 257,
'atp/field/image/missing': 257,
'atp/field/name/missing': 257,
'atp/field/opening_hours/missing': 257,
'atp/field/operator/missing': 257,
'atp/field/operator_wikidata/missing': 257,
'atp/field/phone/missing': 257,
'atp/field/state/missing': 257,
'atp/field/street_address/missing': 257,
'atp/field/twitter/missing': 257,
'atp/item_scraped_host_count/www.stc.se': 257,
'atp/nsi/brand_missing': 257,
'downloader/request_bytes': 595, …
```

[STC SE] Fix Spider

---

locations/spiders/starbucks_us.py

`API` url updated to fix the spider.
Summary generated for small item count.
```python
{'atp/brand/Starbucks': 56,
'atp/brand_wikidata/Q37158': 56,
'atp/category/amenity/cafe': 56,
'atp/country/US': 56,
'atp/item_scraped_host_count/www.starbucks.com': 56,
'atp/nsi/cc_match': 56,
'downloader/request_bytes': 108644,
'downloader/request_count': 277,
'downloader/request_method_count/GET': 277,
'downloader/response_bytes': 301657,
'downloader/response_count': 277,
'downloader/response_status_count/200': 277,
'elapsed_time_seconds': 338.406565,
'finish_reason': 'closespider_itemcount',
'finish_time': …
```

[Starbucks US] Fix  Spider

---

locations/spiders/gbfs.py

**_Fixes : updated keys to fix spider_**
```python
{'atp/brand/AAR Bike': 120,
'atp/brand/AB mit Lara': 13,
'atp/brand/AQTA': 10,
'atp/brand/ARVAL': 1,
'atp/brand/AW-bike': 17,
'atp/brand/Accès Vélo': 14,
'atp/brand/Altervelo Libre-service': 31,
'atp/brand/Ambici': 215,
'atp/brand/Arizona': 119,
'atp/brand/Arriva Nitra Slovakia': 16,
'atp/brand/Aventura BCycle': 5,
'atp/brand/BARshare Barnim All': 20,
'atp/brand/BARshare Barnim Cars': 20,
'atp/brand/BBK Klimabizi': 4,
'atp/brand/BIKER Białystok Poland': 64,
'atp/brand/BIKETOWN': 250,
'atp/brand/BL bike': 5,
'atp/brand/Bay Wheels': 568,
'atp/brand/BelfastBikes': 59,
'atp/brand/Bentonville BCycle': 22,
'atp/brand/Bergen City Bike': 108,
'atp/brand/Bergisches e-Bike': 56,
'atp/brand/Beryl - BCP': 467,
'atp/brand/Beryl - Brighton': 109, …
```

[Gbfs] Fix Spider

---

ci/check_spider_naming_consistency.py

https://countrycode.org/georgia (chains like https://willmart.ge/)
https://countrycode.org/britishvirginislands (chains like https://riteway.vg)

Add missing country code for Georgia, British Virgin Islands

---

locations/spiders/royal_lepage.py

```python
{'atp/brand/Royal LePage': 491,
'atp/brand_wikidata/Q7374385': 491,
'atp/category/office/estate_agent': 491,
'atp/country/CA': 491,
'atp/field/branch/missing': 491,
'atp/field/city/missing': 491,
'atp/field/email/missing': 491,
'atp/field/image/missing': 491,
'atp/field/opening_hours/missing': 491,
'atp/field/operator/missing': 491,
'atp/field/operator_wikidata/missing': 491,
'atp/field/postcode/missing': 491,
'atp/field/state/from_reverse_geocoding': 491,
'atp/field/street_address/missing': 491,
'atp/field/twitter/missing': 491,
'atp/item_scraped_host_count/www.royallepage.ca': 491,
'atp/nsi/perfect_match': 491,
'downloader/exception_count': 21, …
```

[Royal Lepage] Fix spider

---

locations/storefinders/agile_store_locator.py

Allow AgileStoreLocatorSpider to process opening hours where a day is specified with hours of an integer 0. This appears to be used to denote a closed day.

ultra_tune_au: fix spider

---

locations/spiders/odido_nl.py

```python
{'atp/brand/Odido': 117,
'atp/brand_wikidata/Q28406140': 117,
'atp/category/shop/mobile_phone': 117,
'atp/country/NL': 117,
'atp/field/opening_hours/missing': 117,
'atp/field/phone/missing': 117,
'atp/item_scraped_host_count/www.odido.nl': 117,
'atp/nsi/perfect_match': 117,
'downloader/request_bytes': 74687,
'downloader/request_count': 123,
'downloader/request_method_count/GET': 123,
'downloader/response_bytes': 6134094,
'downloader/response_count': 123,
'downloader/response_status_count/200': 120,
'downloader/response_status_count/500': 3,
'elapsed_time_seconds': 1.654599, …
```

[Odido NL] Add spider

---

locations/spiders/blaze_pizza.py

**_Fixes : code refactored to use sitemap to fix spider_**
```python
{'atp/brand/Blaze Pizza': 315,
'atp/brand_wikidata/Q23016666': 315,
'atp/category/amenity/restaurant': 315,
'atp/cdn/cloudflare/response_count': 317,
'atp/cdn/cloudflare/response_status_count/200': 317,
'atp/country/CA': 17,
'atp/country/US': 298,
'atp/field/branch/missing': 315,
'atp/field/email/missing': 315,
'atp/field/lat/missing': 315,
'atp/field/lon/missing': 315,
'atp/field/operator/missing': 315,
'atp/field/operator_wikidata/missing': 315,
'atp/item_scraped_host_count/locations.blazepizza.com': 315,
'atp/nsi/perfect_match': 315,
'downloader/request_bytes': 183868,
'downloader/request_count': 317,
'downloader/request_method_count/GET': 317, …
```

[Blaze Pizza] Fix Spider

---

locations/spiders/batteries_plus_bulbs_pr_us.py

* API key has changed.
* API endpoint on official website is blocked by Cloudflare, but it was just a proxy for the hosted Where2GetIt API, so we can directly use this hosted Where2GetIt API instead.
* Sync name of spider with NSI branding.

batteries_plus: fix spider and rename to batteries_plus_bulbs_pr_us

---

locations/spiders/a1_mk.py

**_code cleaned up and fixes drop count_**
```python
{'atp/brand/A1': 28,
'atp/brand_wikidata/Q24589907': 28,
'atp/category/shop/telecommunication': 28,
'atp/country/MK': 28,
'atp/field/country/from_reverse_geocoding': 28,
'atp/item_scraped_host_count/www.a1.mk': 28,
'atp/nsi/perfect_match': 28,
'downloader/request_bytes': 327,
'downloader/response_bytes': 8219, …
```

[A1 MK] Fix Drop Count 

---

locations/spiders/coinstar.py

Reverts alltheplaces/alltheplaces#12616. Previous runs worked fine without the proxy flag. Now it fails due to Zyte limits (this spider makes lots of requests).

Revert "[Coinstar] Flag coinstar spider as requires proxy"

---

locations/spiders/sixt.py

state was being populated with country.  and all countries incorrectly populated as GB.   
```
{'atp/brand/SIXT': 2066,
'atp/brand_wikidata/Q705664': 2066,
'atp/category/amenity/car_rental': 2066,
'atp/country/AE': 5,
'atp/country/AL': 5,
'atp/country/AM': 3,
'atp/country/AO': 1,
'atp/country/AR': 23,
'atp/country/AT': 21,
'atp/country/AU': 140,
'atp/country/AW': 1,
'atp/country/AZ': 2,
'atp/country/BA': 5,
'atp/country/BB': 2,
'atp/country/BE': 9,
'atp/country/BG': 10,
'atp/country/BH': 5,
'atp/country/BL': 2,
'atp/country/CA': 4,
'atp/country/CH': 19,
'atp/country/CO': 5,
'atp/country/CR': 11,
'atp/country/CS': 10,
'atp/country/CW': 4,
'atp/country/CY': 6,
'atp/country/CZ': 7,
'atp/country/DE': 336,
'atp/country/DK': 13,
'atp/country/DO': 3,
'atp/country/EC': 4,
'atp/country/EE': 7, …
```

[sixt]  Fix country

---

locations/spiders/mcdonalds_si.py

```python
{"atp/brand/McDonald's": 28,
'atp/brand_wikidata/Q38076': 28,
'atp/category/amenity/fast_food': 28,
'atp/country/SI': 28,
'atp/field/branch/missing': 28,
'atp/field/country/from_spider_name': 28,
'atp/field/state/missing': 28,
'atp/field/street_address/missing': 28,
'atp/item_scraped_host_count/mcdonalds.si': 28,
'atp/nsi/cc_match': 28,
'downloader/request_bytes': 608, …
```

[Mcdonalds SI] Fix spider

---

locations/spiders/an_post_ie.py

**_Fixes : added condition to avoid null values_**
```python
{'atp/category/amenity/parcel_locker': 9,
'atp/category/amenity/post_office': 898,
'atp/category/missing': 204,
'atp/country/IE': 1111,
'atp/field/branch/missing': 1111,
'atp/field/brand/missing': 1111,
'atp/field/brand_wikidata/missing': 1111,
'atp/field/email/missing': 1111,
'atp/field/image/missing': 1111,
'atp/field/phone/missing': 30,
'atp/field/street_address/missing': 1111,
'atp/field/twitter/missing': 1111,
'atp/item_scraped_host_count/www.anpost.com': 1121,
'atp/nsi/cc_match': 898,
'atp/nsi/match_failed': 213,
'atp/operator/An Post': 1111,
'atp/operator_wikidata/Q482490': 1111, …
```

[An Post IE] Fix Spider

---

locations/spiders/swarovski_us.py

**_Fixes : updated user_agents to fix spider_**
```python
{'atp/brand/Swarovski': 220,
'atp/brand_wikidata/Q611115': 220,
'atp/category/shop/jewelry': 220,
'atp/country/US': 220,
'atp/field/branch/missing': 220,
'atp/field/country/from_spider_name': 220,
'atp/field/email/missing': 220,
'atp/field/image/dropped': 220,
'atp/field/image/missing': 220,
'atp/field/operator/missing': 220,
'atp/field/operator_wikidata/missing': 220,
'atp/field/state/from_reverse_geocoding': 178,
'atp/field/street_address/missing': 220,
'atp/field/twitter/missing': 220,
'atp/item_scraped_host_count/www.swarovski.com': 220,
'atp/nsi/perfect_match': 220,
'downloader/request_bytes': 1323588, …
```

[Swarovski US] Fix Spider

---

locations/spiders/sport2000_fr.py

```
{'atp/brand/Degrif Sport': 5,
'atp/brand/Espace Montagne': 23,
'atp/brand/Mondovélo': 93,
'atp/brand/ProSport': 10,
'atp/brand/S2 Sneakers Specialist': 39,
'atp/brand/Sport 2000': 451,
'atp/brand/We Are Select': 42,
'atp/brand_wikidata/Q130216213': 93,
'atp/brand_wikidata/Q130221137': 23,
'atp/brand_wikidata/Q130288375': 5,
'atp/brand_wikidata/Q130288466': 10,
'atp/brand_wikidata/Q130288490': 39,
'atp/brand_wikidata/Q130293185': 42,
'atp/brand_wikidata/Q262394': 451,
'atp/category/shop/bicycle': 93,
'atp/category/shop/clothes': 42,
'atp/category/shop/outdoor': 23,
'atp/category/shop/shoes': 39,
'atp/category/shop/sports': 466,
'atp/country/FR': 663,
'atp/field/branch/missing': 663,
'atp/field/country/from_spider_name': 663,
'atp/field/email/missing': 663,
'atp/field/image/missing': …
```

[sport2000_fr] Add Sport2000 and its sub-brands (663 locations)

---

locations/spiders/tgi_fridays_us.py

```python
{'atp/brand/TGI Fridays': 85,
'atp/brand_wikidata/Q1524184': 85,
'atp/category/amenity/restaurant': 85,
'atp/cdn/cloudflare/response_count': 88,
'atp/cdn/cloudflare/response_status_count/200': 88,
'atp/country/US': 85,
'atp/field/email/missing': 85,
'atp/field/image/dropped': 85,
'atp/field/image/missing': 85,
'atp/field/operator/missing': 85,
'atp/field/operator_wikidata/missing': 85,
'atp/field/twitter/missing': 85,
'atp/item_scraped_host_count/locations.tgifridays.com': 85,
'atp/nsi/perfect_match': 85,
'downloader/request_bytes': 35131,
'downloader/request_count': 88,
'downloader/request_method_count/GET': 88,
'downloader/response_bytes': 6751696,
'downloader/response_count': 88,
'downloader/response_status_count/200': 88, …
```

[Tgi Fridays US] Fix spider

---

locations/spiders/tmobile_cz.py

**_Fixes : updated raw string to fix spider_**
```python
{'atp/brand/T-Mobile': 101,
'atp/brand_wikidata/Q327634': 101,
'atp/category/shop/mobile_phone': 101,
'atp/country/CZ': 101,
'atp/field/branch/missing': 101,
'atp/field/country/from_spider_name': 101,
'atp/field/phone/missing': 79,
'atp/field/state/missing': 101,
'atp/field/website/missing': 101,
'atp/item_scraped_host_count/coveragemap-tmcz.position.cz': 101,
'atp/nsi/cc_match': 101,
'downloader/request_bytes': 364,
'downloader/response_bytes': 9481, …
```

[Tmobile CZ] Fix Spider

---

locations/storefinders/where2getit.py

There has been (or is now) a limit parameter for the Where2GetIt storefinder API method which was used, allowing a limit of up to 10000 results per query to be returned. Previously this wasn't observed to be required for the ross_dress_for_less_us spider but more recently the default limit for this brand appears to have been changed to 1000 results per query, versus the 1847 features this spider should be expected to return. All 1847 features of this spider are again returned if we manually set the limit to 10000 results per query.

storefinders/where2getit: add limit=10000 parameter

---

locations/spiders/infrastructure/seattle_city_council_trees_us.py

Add Seattle City Council and associated entities trees (US) (67k trees)

---

locations/spiders/kruidvat.py

```python
{'atp/brand/Kruidvat': 1477,
'atp/brand_wikidata/Q2226366': 1477,
'atp/category/shop/chemist': 1477,
'atp/country/BE': 347,
'atp/country/NL': 1130,
'atp/field/branch/missing': 1477,
'atp/field/city/missing': 1477,
'atp/field/country/from_website_url': 1477,
'atp/field/email/missing': 1477,
'atp/field/image/missing': 1477,
'atp/field/lat/missing': 187,
'atp/field/lon/missing': 187,
'atp/field/operator/missing': 1477,
'atp/field/operator_wikidata/missing': 1477,
'atp/field/phone/missing': 1477,
'atp/field/twitter/missing': 1477,
'atp/geometry/null_island': 187,
'atp/item_scraped_host_count/www.kruidvat.be': 347,
'atp/item_scraped_host_count/www.kruidvat.nl': 1130, …
```

[Kruidvat ] Add custom settings to fix Spider

---

locations/spiders/sdek.py

Making request for individual POI details (`phone`, `email` etc) for about `8k` POIs is no longer feasible. Tried with `custom-settings` and increasing `download_delay`, nothing works and after a certain no. of requests, captch page is served as response. Hence, Alternate API is used to utilize the best possible option.
```python
{'atp/brand/СДЭК': 8249,
'atp/brand_wikidata/Q28665980': 8249,
'atp/category/amenity/parcel_locker': 2556,
'atp/category/amenity/post_office': 5693,
'atp/clean_strings/street_address': 23,
'atp/country/RU': 8249,
'atp/field/branch/missing': 8249,
'atp/field/city/missing': 8249,
'atp/field/country/from_website_url': 8249,
'atp/field/email/missing': 8249,
'atp/field/image/missing': 8249,
'atp/field/name/missing': 2556,
'atp/field/opening_hours/missing': 32, …
```

[Sdek] Fix spider

---

locations/spiders/bcc_it.py

[bcc_it] normalize values

---

locations/spiders/hsbc_us.py

```python
{'atp/brand/HSBC': 21,
'atp/brand_wikidata/Q190464': 21,
'atp/category/amenity/bank': 21,
'atp/clean_strings/street_address': 2,
'atp/country/US': 21,
'atp/field/branch/missing': 21,
'atp/field/opening_hours/missing': 21,
'atp/field/phone/missing': 21,
'atp/field/state/from_reverse_geocoding': 21,
'atp/item_scraped_host_count/www.us.hsbc.com': 21,
'atp/nsi/cc_match': 21,
'downloader/request_bytes': 17262,
'downloader/response_bytes': 499641, …
```

[HSBC US] Fix Spider

---

locations/spiders/radisson_hotels.py

```python
{'atp/brand/Art’otel': 7,
'atp/brand/Country Inn & Suites by Radisson': 12,
'atp/brand/Park Inn & Suites by Radisson': 2,
'atp/brand/Park Inn by Radisson': 92,
'atp/brand/Park Plaza Hotels & Resorts': 35,
'atp/brand/Prizeotel': 15,
'atp/brand/Radisson': 129,
'atp/brand/Radisson Blu': 336,
'atp/brand/Radisson Collection': 40,
'atp/brand/Radisson Individuals': 75,
'atp/brand/Radisson RED': 26,
'atp/brand_wikidata/Q14516231': 7,
'atp/brand_wikidata/Q1751979': 129,
'atp/brand_wikidata/Q2052550': 35,
'atp/brand_wikidata/Q28233721': 26,
'atp/brand_wikidata/Q5177332': 12,
'atp/brand_wikidata/Q60711675': 92,
'atp/brand_wikidata/Q60716706': 40,
'atp/brand_wikidata/Q7281341': 336,
'atp/category/tourism/hotel': 769,
'atp/clean_strings/email': 26,
'atp/clean_strings/name': 86, …
```

[Radisson Hotels] Fix spider

---

locations/spiders/budni_de.py

The budni.de website was restructured. Shop info is now embedded into the page in a weird Next.js format in <script> blocks.
```
{'atp/brand/Budni': 191,
'atp/brand_wikidata/Q1001516': 191,
'atp/category/shop/chemist': 191,
'atp/country/DE': 191,
'atp/field/country/from_spider_name': 191,
'atp/field/email/missing': 191,
'atp/field/image/missing': 191,
'atp/field/operator/missing': 191,
'atp/field/operator_wikidata/missing': 191,
'atp/field/phone/missing': 191,
'atp/field/state/missing': 191,
'atp/field/twitter/missing': 191,
'atp/field/website/missing': 191,
'atp/item_scraped_host_count/www.budni.de': 191,
'atp/nsi/perfect_match': 191,
```

[budni_de] Rewrite spider after website change

---

locations/spiders/mac_cosmetics.py

Add [MAC Cosmetics](https://www.maccosmetics.com/), an international cosmetics store chain with 3599 stores globally, out of which 1964 in the US.
```
{'atp/brand/MAC Cosmetics': 3599,
'atp/brand_wikidata/Q2624442': 3599,
'atp/category/shop/cosmetics': 3599,
'atp/clean_strings/name': 3,
'atp/clean_strings/phone': 79,
'atp/clean_strings/postcode': 6,
'atp/clean_strings/street_address': 236,
'atp/country/AE': 38,
'atp/country/AM': 1,
'atp/country/AR': 15,
'atp/country/AT': 22,
'atp/country/AU': 75,
'atp/country/AW': 1,
'atp/country/AZ': 3,
'atp/country/BA': 1,
'atp/country/BB': 2,
'atp/country/BE': 5,
'atp/country/BG': 3,
'atp/country/BH': 3,
'atp/country/BR': 66,
'atp/country/BS': 3,
'atp/country/CH': 27,
'atp/country/CI': 3,
'atp/country/CL': 21, …
```

[mac_cosmetics] Add spider (3599 locations)

---

locations/spiders/sleep_number_us.py

**_Fixes : added start_request to fix spider_**
```python
{'atp/brand/Sleep Number': 636,
'atp/brand_wikidata/Q7447640': 636,
'atp/category/shop/bed': 636,
'atp/country/US': 636,
'atp/field/branch/missing': 636,
'atp/field/email/missing': 636,
'atp/field/image/missing': 636,
'atp/field/operator/missing': 636,
'atp/field/operator_wikidata/missing': 636,
'atp/field/twitter/missing': 636,
'atp/item_scraped_host_count/www.sleepnumber.com': 950,
'atp/nsi/perfect_match': 636,
'downloader/request_bytes': 1976,
'downloader/response_bytes': 224604,
'downloader/response_count': 5,
'downloader/response_status_count/200': 5,
'elapsed_time_seconds': 3.616159,
'finish_time': …
```

[Sleep Number US] Fix Spider

---

locations/spiders/panera_bread_us.py

```python
{'atp/brand/Panera Bread': 2225,
'atp/brand_wikidata/Q7130852': 2225,
'atp/category/amenity/fast_food': 2225,
'atp/country/US': 2225,
'atp/field/email/missing': 2225,
'atp/field/image/missing': 2225,
'atp/field/opening_hours/missing': 2225,
'atp/field/operator/missing': 2225,
'atp/field/operator_wikidata/missing': 2225,
'atp/field/twitter/missing': 2225,
'atp/item_scraped_host_count/www-api.panerabread.com': 2225,
'atp/nsi/perfect_match': 2225,
'downloader/request_bytes': 70371,
'downloader/request_count': 54,
'downloader/request_method_count/GET': 54,
'downloader/response_bytes': 252030,
'downloader/response_count': 54,
'downloader/response_status_count/200': 52,
'downloader/response_status_count/302': 1, …
```

[Panera  Bread US] Try spider without proxy

---

locations/spiders/john_lewis_gb.py

**_Fixes : Flag john_lewis_gb as requires proxy to fix spider_**
```python
{'atp/brand/John Lewis': 36,
'atp/brand_wikidata/Q1918981': 36,
'atp/category/shop/department_store': 36,
'atp/country/GB': 36,
'atp/field/branch/missing': 36,
'atp/field/state/missing': 36,
'atp/item_scraped_host_count/www.johnlewis.com': 36,
'atp/nsi/perfect_match': 36,
'downloader/request_bytes': 28810,
'downloader/request_count': 40,
'downloader/request_method_count/GET': 40,
'downloader/response_bytes': 1648461,
'downloader/response_count': 40,
'downloader/response_status_count/200': 39, …
```

[John Lewis GB] Fix Spider

---

locations/spiders/sleep_number_us.py

Spider was not generating expected count, [last run](https://alltheplaces-data.openaddresses.io/runs/2025-05-10-13-32-08/stats/sleep_number_us.json) resulted `442`. Fixes have been applied to fix the low scraped count.
```python
{'atp/brand/Sleep Number': 636,
'atp/brand_wikidata/Q7447640': 636,
'atp/category/shop/bed': 636,
'atp/country/US': 636,
'atp/field/branch/missing': 636,
'atp/field/email/missing': 636,
'atp/field/image/missing': 636,
'atp/field/operator/missing': 636,
'atp/field/operator_wikidata/missing': 636,
'atp/field/twitter/missing': 636,
'atp/item_scraped_host_count/www.sleepnumber.com': 4200,
'atp/nsi/perfect_match': 636,
'downloader/request_bytes': 14989,
'downloader/request_count': 43,
'downloader/request_method_count/GET': 43, …
```

[Sleep Number US] Update custom settings & requests to fix low count for spider

---

locations/spiders/primark.py

**_Fixes : updated user_agent to fix spider_**
```python
{'atp/brand/Primark': 452,
'atp/brand_wikidata/Q137023': 452,
'atp/category/shop/clothes': 452,
'atp/country/AT': 5,
'atp/country/BE': 8,
'atp/country/CZ': 3,
'atp/country/DE': 27,
'atp/country/ES': 62,
'atp/country/FR': 27,
'atp/country/GB': 197,
'atp/country/IE': 35,
'atp/country/IT': 19,
'atp/country/NL': 20,
'atp/country/PL': 7,
'atp/country/PT': 11,
'atp/country/RO': 2,
'atp/country/SI': 1,
'atp/country/SK': 1,
'atp/country/US': 27,
'atp/field/city/missing': 81,
'atp/field/email/missing': 452,
'atp/field/image/missing': 452,
'atp/field/operator/missing': 452,
'atp/field/operator_wikidata/missing': 452,
'atp/field/postcode/missing': 81, …
```

[Primark] Fix Spider

---

locations/spiders/relay_fr.py

Now extracts 3x the number of features in France but there are a small number of features probably still missed in France. This miss is likely due to a single ISEADGG centroid search currently returning the maximum (100) features, meaning some features above 100 have been truncated/forgotten. Further improvements to WPStoreLocatorSpider or smaller ISEADGG centroid grids <24km will be required to overcome this current limitation.

relay_fr: modernise by converting to WPStoreLocatorSpider

---

locations/spiders/maxmara.py

```python
{'atp/brand/Max Mara': 540,
'atp/brand_wikidata/Q1151774': 540,
'atp/category/shop/clothes': 540,
'atp/clean_strings/name': 13,
'atp/country/AE': 3,
'atp/country/AM': 1,
'atp/country/AR': 1,
'atp/country/AT': 3,
'atp/country/AU': 6,
'atp/country/AZ': 1,
'atp/country/BE': 7,
'atp/country/BG': 1,
'atp/country/BH': 1,
'atp/country/BR': 1,
'atp/country/CA': 8,
'atp/country/CH': 6,
'atp/country/CL': 1,
'atp/country/CN': 69,
'atp/country/CO': 1,
'atp/country/CY': 1,
'atp/country/CZ': 2,
'atp/country/DE': 16,
'atp/country/DK': 3,
'atp/country/EE': 1,
'atp/country/EG': 1,
'atp/country/ES': 27,
'atp/country/FR': 20,
'atp/country/GB': 7,
'atp/country/GE': 1,
'atp/country/GR': 6,
'atp/country/GT': 1,
'atp/country/HK': 5,
'atp/country/HR': 3,
'atp/country/HU': 1,
'atp/country/ID': 1, …
```

[Maxmara] Fix spider

---

locations/spiders/subway.py
locations/spiders/subway_hk.py
locations/spiders/subway_kr.py
locations/spiders/subway_sg.py
locations/spiders/subway_th.py
locations/spiders/subway_tw.py

Spiders lost categories because NSI match failed ([we have cameras entry](https://nsi.guide/index.html?t=operators&k=man_made&v=surveillance&tt=subway)).
I tested all of the changes in this PR.

[Subway spiders] apply category explicitly

---

locations/spiders/iceland_foods.py

`POI` data is dynamically loaded in the ultimate page, so `sitemap` is no longer useful. Hence, code refactored using `API` to fix the spider.
````python
{'atp/brand/Iceland': 801,
'atp/brand_wikidata/Q721810': 801,
'atp/category/shop/frozen_food': 801,
'atp/country/GB': 789,
'atp/country/IE': 12,
'atp/field/city/missing': 35,
'atp/field/email/missing': 797,
'atp/field/image/missing': 801,
'atp/field/operator/missing': 801,
'atp/field/operator_wikidata/missing': 801,
'atp/field/state/missing': 31,
'atp/field/twitter/missing': 801,
'atp/item_scraped_host_count/prd.cc-iceland.co.uk': 801, …
```

[Iceland Foods] Fix spider

---

locations/spiders/rema_1000_dk.py

```python
{'atp/brand/Rema 1000': 427,
'atp/brand_wikidata/Q28459': 427,
'atp/category/shop/supermarket': 427,
'atp/country/DK': 427,
'atp/field/country/from_spider_name': 427,
'atp/field/email/missing': 427,
'atp/field/image/missing': 427,
'atp/field/operator/missing': 427,
'atp/field/operator_wikidata/missing': 427,
'atp/field/state/missing': 427,
'atp/field/twitter/missing': 427,
'atp/item_scraped_host_count/cphapp.rema1000.dk': 427,
'atp/nsi/perfect_match': 427,
'downloader/response_bytes': 623535, …
```

[Rema 1000 DK] Fix spider

---

locations/spiders/mcdonalds_ph.py

Server is unstable, sometimes throws `504` and sometimes `500` error. Used `playwright` with `custom_settings` to fix the spider.
```python
{"atp/brand/McDonald's": 746,
'atp/brand_wikidata/Q38076': 746,
'atp/category/amenity/fast_food': 746,
'atp/country/PH': 746,
'atp/field/branch/missing': 746,
'atp/field/country/from_spider_name': 746,
'atp/field/email/missing': 746,
'atp/field/image/missing': 746,
'atp/field/opening_hours/missing': 45,
'atp/field/operator/missing': 746,
'atp/field/operator_wikidata/missing': 746,
'atp/field/phone/missing': 746,
'atp/field/postcode/missing': 746,
'atp/field/street_address/missing': 746,
'atp/field/twitter/missing': 746,
'atp/field/website/missing': 746,
'atp/item_scraped_host_count/www.mcdonalds.com.ph': 746,
'atp/nsi/cc_match': …
```

[Mcdonalds PH] Try playwright with custom settings to fix spider

---

locations/spiders/the_body_shop_tw.py

Not much data to scrape from `google_map_url` , only `address` & `coordinates`.
```python
{'atp/brand/The Body Shop': 38,
'atp/brand_wikidata/Q837851': 38,
'atp/category/shop/cosmetics': 38,
'atp/country/TW': 38,
'atp/field/branch/missing': 38,
'atp/field/website/missing': 38,
'atp/item_scraped_host_count/shop.thebodyshop.com.tw': 39, …
```

[The Body Shop TW] Fix  Spider

---

locations/spiders/penningtons_ca.py

```python
{'atp/brand/Penningtons': 86,
'atp/brand_wikidata/Q16956527': 86,
'atp/category/shop/clothes': 86,
'atp/country/CA': 86,
'atp/field/branch/missing': 86,
'atp/field/email/missing': 86,
'atp/field/image/missing': 81,
'atp/field/state/from_reverse_geocoding': 14,
'atp/item_scraped_host_count/uberall.com': 86,
'atp/nsi/perfect_match': 86,
'downloader/request_bytes': 724,
'downloader/response_bytes': 13036,
'elapsed_time_seconds': 3.373204,
'finish_time': datetime.datetime(2025, …
```

[Penningtons CA] Fix spider

---

locations/spiders/talisman_hire.py

```python
{'atp/brand/Talisman Hire': 138,
'atp/brand_wikidata/Q120885726': 138,
'atp/category/shop/tool_hire': 138,
'atp/country/BW': 1,
'atp/country/NA': 1,
'atp/country/ZA': 135,
'atp/country/ZM': 1,
'atp/field/country/from_reverse_geocoding': 128,
'atp/field/image/missing': 138,
'atp/item_scraped_host_count/www.talisman.co.za': 138,
'atp/nsi/perfect_match': 138,
'downloader/request_bytes': 66942,
'downloader/request_count': 140,
'downloader/request_method_count/GET': 140,
'downloader/response_bytes': 2785187,
'downloader/response_count': 140, …
```

[Talisman Hire] Fix spider

---

locations/spiders/kidstuff_au.py
locations/storefinders/stockinstore.py

```python
{'atp/brand/Kidstuff': 57,
'atp/brand_wikidata/Q117746407': 57,
'atp/category/shop/toys': 57,
'atp/country/AU': 57,
'atp/field/image/missing': 57,
'atp/field/operator/missing': 57,
'atp/field/operator_wikidata/missing': 57,
'atp/field/twitter/missing': 57,
'atp/item_scraped_host_count/stockinstore.net': 57,
'atp/nsi/perfect_match': 57,
'downloader/request_bytes': 515,
'downloader/response_bytes': 11534,
'elapsed_time_seconds': 2.237879,
'finish_time': datetime.datetime(2025, 5, 23, 6, 52, 41, …
```

[Kidstuff AU] Fix spider

---

locations/spiders/hemkop_se.py

Prevents `AttributeError` in spider execution like that happened in [last run](https://alltheplaces-data.openaddresses.io/runs/2025-05-17-13-31-55/logs/hemkop_se.txt). Though, currently it is not happening for me, but it will protect if it occurs again in future.
```
{'atp/brand/Hemköp': 203,
'atp/brand_wikidata/Q10521746': 203,
'atp/category/shop/supermarket': 203,
'atp/cdn/cloudfront/response_count': 1,
'atp/cdn/cloudfront/response_status_count/200': 1,
'atp/country/SE': 203,
'atp/field/country/from_spider_name': 203,
'atp/field/email/missing': 203,
'atp/field/image/missing': 203,
'atp/field/operator/missing': 203,
'atp/field/operator_wikidata/missing': 203,
'atp/field/state/missing': 203,
'atp/field/twitter/missing': 203, …
```

[Hemkop SE] Fix spider

---

locations/spiders/leeann_chin_us.py

`JSON Blob` earlier used, is giving some decode error, hence `Structured Data` is used to refactor and fix the spider. [Sitemap](https://www.leeannchin.com/sitemap.xml) gives one POI less (url redirects to store locator) , hence ignored.
```python
{'atp/brand/Leeann Chin': 41,
'atp/brand_wikidata/Q6515716': 41,
'atp/category/amenity/restaurant': 41,
'atp/country/US': 41,
'atp/field/branch/missing': 41,
'atp/field/image/dropped': 41,
'atp/item_scraped_host_count/www.leeannchin.com': 41,
'atp/nsi/perfect_match': 41,
'downloader/request_bytes': 18190,
'downloader/request_count': 43, …
```

[Leeann Chin US] Fix spider

---

locations/pipelines/duplicates.py

Rel: https://github.com/alltheplaces/alltheplaces/pull/13196
When there are no duplicates the log says "None", this changes it to "0".
```patch
-2025-05-27 12:53:06 [locations.pipelines.duplicates] INFO: Dropped None duplicate items
+2025-05-27 12:53:06 [locations.pipelines.duplicates] INFO: Dropped 0 duplicate items
```

[Core] Prettier duplicate log output

---

locations/spiders/triumph.py

`StockInStoreSpider` not working, hence code refactored using `Structured Data` to fix the spider. It gives better worldwide POIs count.
```python
{'atp/brand/Triumph': 323,
'atp/brand_wikidata/Q671216': 323,
'atp/category/shop/clothes': 323,
'atp/country/AT': 49,
'atp/country/BE': 2,
'atp/country/BG': 8,
'atp/country/CH': 9,
'atp/country/CZ': 11,
'atp/country/DE': 46,
'atp/country/DK': 8,
'atp/country/ES': 8,
'atp/country/FR': 22,
'atp/country/GG': 2,
'atp/country/GR': 11,
'atp/country/HR': 2,
'atp/country/HU': 18,
'atp/country/IL': 3,
'atp/country/IT': 32,
'atp/country/JE': 2,
'atp/country/LU': 1,
'atp/country/MT': 1,
'atp/country/NL': 12,
'atp/country/NO': 5,
'atp/country/PL': 35,
'atp/country/PT': 23,
'atp/country/SE': 8,
'atp/country/SI': 5,
'atp/field/branch/missing': 323, …
```

[Triumph] Fix spider

---

locations/spiders/cycle_lab_za.py

`cycle_lab_za` fixed and consequently `the_pro_shop_za` is also fixed, since the later inherits the first.
**cycle_lab_za**
```python
{'atp/brand/Cycle Lab': 8,
'atp/brand_wikidata/Q130487839': 8,
'atp/category/shop/bicycle': 8,
'atp/clean_strings/phone': 8,
'atp/country/ZA': 8,
'atp/field/city/missing': 8,
'atp/field/country/from_spider_name': 8,
'atp/item_scraped_host_count/www.cyclelab.com': 8, …
```

[Cycle Lab ZA] [The Pro Shop ZA] Fix spiders

---

locations/spiders/euromobil_nl.py

```python
{'atp/brand/Euromobil': 65,
'atp/brand_wikidata/Q1375118': 65,
'atp/category/amenity/car_rental': 65,
'atp/country/NL': 65,
'atp/field/branch/missing': 65,
'atp/field/country/from_spider_name': 65,
'atp/field/opening_hours/missing': 65,
'atp/field/postcode/missing': 64,
'atp/field/state/missing': 65,
'atp/field/website/missing': 4,
'atp/item_scraped_host_count/euromobil.nl': 65, …
```

[Euromobil NL] Fix Spider

---

locations/spiders/argos.py

Available `Yext` API is utilized to refactor and fix the spider to get better `POI` data. Also, it helps to get rid of proxy requirement.
```python
{'atp/brand/Argos': 665,
'atp/brand_wikidata/Q4789707': 665,
'atp/category/shop/catalogue': 665,
'atp/cdn/cloudflare/response_count': 25,
'atp/cdn/cloudflare/response_status_count/200': 24,
'atp/country/GB': 665,
'atp/field/email/missing': 665,
'atp/field/image/missing': 665,
'atp/field/operator/missing': 665,
'atp/field/operator_wikidata/missing': 665,
'atp/field/twitter/missing': 665,
'atp/item_scraped_host_count/prod-cdn.us.yextapis.com': 665,
'atp/nsi/perfect_match': 665,
'downloader/request_bytes': 22854, …
```

[Argos] Fix spider

---

locations/spiders/teremok_ru.py

Tried to fix spider failure like in last [run](https://alltheplaces-data.openaddresses.io/runs/2025-05-17-13-31-55/stats/teremok_ru.json) because of non-responsive server, also performed some code optimization.
```python
{'atp/brand/Теремок': 339,
'atp/brand_wikidata/Q4455593': 339,
'atp/category/amenity/fast_food': 339,
'atp/country/RU': 339,
'atp/field/branch/missing': 339,
'atp/field/city/missing': 339,
'atp/field/country/from_spider_name': 339,
'atp/field/email/missing': 339,
'atp/field/image/missing': 339,
'atp/field/operator/missing': 339,
'atp/field/operator_wikidata/missing': 339,
'atp/field/phone/missing': 339,
'atp/field/postcode/missing': 339,
'atp/field/state/missing': 339, …
```

[Teremok RU] Fix spider

---

locations/spiders/sleep_outfitters_us.py

```python
{'atp/brand/Sleep Outfitters': 104,
'atp/brand_wikidata/Q120509459': 104,
'atp/category/shop/bed': 104,
'atp/cdn/cloudflare/response_count': 199,
'atp/cdn/cloudflare/response_status_count/200': 199,
'atp/country/US': 104,
'atp/field/city/missing': 104,
'atp/field/country/from_spider_name': 104,
'atp/field/image/missing': 104,
'atp/field/opening_hours/missing': 104,
'atp/field/operator/missing': 104,
'atp/field/operator_wikidata/missing': 104,
'atp/field/postcode/missing': 104,
'atp/field/state/from_reverse_geocoding': 104,
'atp/field/street_address/missing': 104,
'atp/field/twitter/missing': 104,
'atp/item_scraped_host_count/sleepoutfitters.com': 104,
'atp/nsi/perfect_match': 104, …
```

[Sleep Outfitters US] Fix Spider

---

locations/spiders/staples.py

**_Fixes : code refactored to use YextSpider to fix spider_**
```python
{'atp/brand/Staples': 2807,
'atp/brand_wikidata/Q785943': 2807,
'atp/category/shop/stationery': 2807,
'atp/cdn/cloudflare/response_count': 91,
'atp/cdn/cloudflare/response_status_count/200': 90,
'atp/country/US': 2807,
'atp/field/branch/missing': 2807,
'atp/field/email/missing': 2807,
'atp/field/image/missing': 2807,
'atp/field/operator/missing': 2807,
'atp/field/operator_wikidata/missing': 2807,
'atp/item_scraped_host_count/cdn.yextapis.com': 2807,
'atp/nsi/perfect_match': 2807,
'downloader/request_bytes': 57641,
'downloader/request_count': 91,
'downloader/request_method_count/GET': 91, …
```

[Staples] Fix Spider

---

locations/spiders/vodafone_it.py

**_Fixes: updated parse_item method to fix spider_**
```python
{'atp/brand/Vodafone': 328,
'atp/brand_wikidata/Q122141': 328,
'atp/category/shop/mobile_phone': 328,
'atp/cdn/cloudflare/response_count': 89,
'atp/cdn/cloudflare/response_status_count/200': 88,
'atp/country/IT': 328,
'atp/duplicate_count': 108,
'atp/field/email/invalid': 6,
'atp/field/email/missing': 179,
'atp/field/image/missing': 328,
'atp/field/operator/missing': 328,
'atp/field/operator_wikidata/missing': 328,
'atp/field/twitter/missing': 326,
'atp/item_scraped_host_count/liveapi.yext.com': 436,
'atp/nsi/cc_match': 328,
'downloader/request_bytes': 92662,
'downloader/request_count': 89, …
```

[Vodafone IT] Fix Spider

---

locations/spiders/applegreen.py
locations/spiders/applegreen_ie.py

```python
{'atp/brand/Applegreen': 186,
'atp/brand_wikidata/Q7178908': 186,
'atp/category/amenity/fuel': 186,
'atp/country/IE': 186,
'atp/field/country/from_reverse_geocoding': 186,
'atp/field/email/missing': 186,
'atp/field/image/missing': 186,
'atp/field/opening_hours/missing': 186,
'atp/field/operator/missing': 186,
'atp/field/operator_wikidata/missing': 186,
'atp/field/phone/missing': 186,
'atp/field/postcode/missing': 186,
'atp/field/twitter/missing': 186,
'atp/item_scraped_host_count/locations.applegreen.com': 186,
'atp/nsi/cc_match': 186,
'downloader/request_bytes': 372, …
```

[Applegreen] Fix Spider

---

locations/spiders/toyota_sacu.py

**_Flag toyota_sacu as requires proxy to fix spider_**
```python
{'atp/brand/Hino Motors': 50,
'atp/brand/Lexus': 15,
'atp/brand/Toyota': 167,
'atp/brand/Toyota;Hino Motors': 20,
'atp/brand/Toyota;Lexus': 15,
'atp/brand/Toyota;Lexus;Hino Motors': 1,
'atp/brand_wikidata/Q35919': 15,
'atp/brand_wikidata/Q53268': 167,
'atp/brand_wikidata/Q53268;Q35919': 15,
'atp/brand_wikidata/Q53268;Q35919;Q867667': 1,
'atp/brand_wikidata/Q53268;Q867667': 20,
'atp/brand_wikidata/Q867667': 50,
'atp/category/shop/car': 209,
'atp/category/shop/car_repair': 10,
'atp/category/shop/truck': 50,
'atp/clean_strings/street_address': 101,
'atp/country/BW': 10,
'atp/country/LS': 1,
'atp/country/NA': 16,
'atp/country/SZ': 3,
'atp/country/ZA': 239,
'atp/field/branch/missing': 269,
'atp/field/brand/missing': 1, …
```

[Toyota Sacu] Fix Spider

---

locations/spiders/supercor_es.py

```python
{'atp/brand/Supercor': 131,
'atp/brand_wikidata/Q6135841': 131,
'atp/category/shop/supermarket': 131,
'atp/country/ES': 131,
'atp/field/branch/missing': 131,
'atp/field/country/from_spider_name': 131,
'atp/field/email/missing': 131,
'atp/field/image/missing': 131,
'atp/field/operator/missing': 131,
'atp/field/operator_wikidata/missing': 131,
'atp/field/postcode/missing': 20,
'atp/field/state/missing': 131,
'atp/field/street_address/missing': 131,
'atp/field/twitter/missing': 131,
'atp/field/website/missing': 131,
'atp/item_scraped_host_count/www.supercor.es': 131,
'atp/nsi/cc_match': 131,
'downloader/request_bytes': 534, …
```

[Supercor ES] Fix spider

---

locations/spiders/libro_at.py

```python
{'atp/brand/Libro': 165,
'atp/brand_wikidata/Q1823138': 165,
'atp/category/shop/books': 165,
'atp/country/AT': 165,
'atp/field/branch/missing': 165,
'atp/field/city/missing': 165,
'atp/field/country/from_spider_name': 165,
'atp/field/email/missing': 165,
'atp/field/image/missing': 165,
'atp/field/operator/missing': 165,
'atp/field/operator_wikidata/missing': 165,
'atp/field/phone/missing': 165,
'atp/field/postcode/missing': 165,
'atp/field/state/missing': 165,
'atp/item_scraped_host_count/www.libro.at': 165,
'atp/nsi/perfect_match': 165,
'downloader/request_bytes': 745,
'downloader/response_bytes': 29514, …
```

[Libro AT] Fix spider

---

locations/spiders/laseraway_us.py

**_Fixes : code refactored to use sitemap to fix spider_**
```python
{'atp/brand/LaserAway': 195,
'atp/brand_wikidata/Q119982751': 195,
'atp/category/shop/beauty': 195,
'atp/cdn/cloudflare/response_count': 210,
'atp/cdn/cloudflare/response_status_count/200': 210,
'atp/clean_strings/branch': 51,
'atp/country/US': 195,
'atp/field/country/from_spider_name': 195,
'atp/field/email/missing': 195,
'atp/field/image/missing': 195,
'atp/field/operator/missing': 195,
'atp/field/operator_wikidata/missing': 195,
'atp/item_scraped_host_count/www.laseraway.com': 195,
'atp/nsi/perfect_match': 195,
'downloader/request_bytes': 71520,
'downloader/request_count': 210,
'downloader/request_method_count/GET': 210,
'downloader/response_bytes': 7912973, …
```

[Laser Away US] Fix Spider

---

locations/spiders/sainsburys.py

```python
{"atp/brand/Sainsbury's": 1152,
"atp/brand/Sainsbury's Local": 858,
'atp/brand_wikidata/Q13218434': 858,
'atp/brand_wikidata/Q152096': 1152,
'atp/category/amenity/bureau_de_change': 227,
'atp/category/amenity/cafe': 1,
'atp/category/amenity/fuel': 317,
'atp/category/shop/convenience': 858,
'atp/category/shop/supermarket': 607,
'atp/country/GB': 2010,
'atp/field/email/missing': 2010,
'atp/field/image/missing': 2010,
'atp/field/name/missing': 228,
'atp/field/operator/missing': 2010,
'atp/field/operator_wikidata/missing': 2010,
'atp/field/state/missing': 1987, …
```

[Sainsburys] Fix spider

---

locations/spiders/aesop.py

**_Fixes : updated sitemap_urls to fix spider_**
```python
{'atp/brand/Aesop': 276,
'atp/brand_wikidata/Q4688560': 276,
'atp/category/shop/cosmetics': 276,
'atp/clean_strings/addr_full': 8,
'atp/clean_strings/branch': 5,
'atp/clean_strings/email': 8,
'atp/clean_strings/phone': 4,
'atp/clean_strings/postcode': 2,
'atp/clean_strings/street_address': 6,
'atp/country/AT': 1,
'atp/country/AU': 42,
'atp/country/BE': 2,
'atp/country/CA': 11,
'atp/country/CH': 7,
'atp/country/CN': 1,
'atp/country/DE': 11,
'atp/country/DK': 3,
'atp/country/ES': 4,
'atp/country/FR': 13,
'atp/country/GB': 29,
'atp/country/HK': 13,
'atp/country/IT': 7,
'atp/country/JP': 24,
'atp/country/KR': 9,
'atp/country/MO': 3,
'atp/country/MY': 1,
'atp/country/NL': 3,
'atp/country/NO': 2, …
```

[Aesop] Fix Spider

---

locations/spiders/bissu_mx.py

Add [Bissú](https://bissu.com/), a cosmetics brand from MX.
```
2025-06-08 22:14:41 [scrapy.statscollectors] INFO: Dumping Scrapy stats:
{'atp/brand/Bissú': 313,
'atp/brand_wikidata/Q130466489': 313,
'atp/category/missing': 313,
'atp/clean_strings/name': 134,
'atp/country/MX': 313,
'atp/field/branch/missing': 313,
'atp/field/country/from_spider_name': 313,
'atp/field/email/missing': 313,
'atp/field/image/missing': 313,
'atp/field/opening_hours/missing': 313,
'atp/field/operator/missing': 313,
'atp/field/operator_wikidata/missing': 313,
'atp/field/phone/invalid': 14,
'atp/field/state/missing': 313,
'atp/field/twitter/missing': 313,
'atp/item_scraped_host_count/bissu.com': 313,
'atp/nsi/brand_missing': 313,
```

Add Bissú MX (313 shops)

---

locations/spiders/independent_financial_us.py

```python
{'atp/brand/Independent Financial': 86,
'atp/brand_wikidata/Q6016398': 86,
'atp/category/amenity/atm': 12,
'atp/category/amenity/bank': 57,
'atp/category/office/financial': 17,
'atp/clean_strings/branch': 8,
'atp/country/US': 86,
'atp/field/city/missing': 86,
'atp/field/country/from_spider_name': 86,
'atp/field/email/missing': 86,
'atp/field/opening_hours/missing': 86,
'atp/field/phone/missing': 86,
'atp/field/postcode/missing': 86,
'atp/field/state/from_reverse_geocoding': 86, …
```

[Independent Financial US] Fix Spider

---

locations/spiders/sams_club_mx.py

```python
{"atp/brand/Sam's Club": 173,
'atp/brand_wikidata/Q1972120': 173,
'atp/category/shop/wholesale': 173,
'atp/country/MX': 173,
'atp/duplicate_count': 1649,
'atp/field/email/missing': 173,
'atp/field/image/missing': 173,
'atp/field/opening_hours/missing': 173,
'atp/field/operator/missing': 173,
'atp/field/operator_wikidata/missing': 173,
'atp/field/phone/missing': 173,
'atp/field/twitter/missing': 173,
'atp/field/website/missing': 173,
'atp/item_scraped_host_count/www.sams.com.mx': 1822,
'atp/nsi/cc_match': 173,
'downloader/request_bytes': 963335,
'downloader/request_count': 207,
'downloader/request_method_count/POST': 206,
'downloader/response_bytes': 821668, …
```

[Sams Club MX] Fix Spider

---

locations/spiders/chestertons_gb.py

```py
{'atp/brand/Chestertons': 38,
'atp/brand_wikidata/Q24298789': 38,
'atp/category/office/estate_agent': 38,
'atp/country/GB': 38,
'atp/field/name/missing': 38,
'atp/item_scraped_host_count/www.chestertons.co.uk': 38,
'atp/nsi/brand_missing': 38, …
```

Add Chestertons (GB) (38 locations) (fix #13363)

---

locations/spiders/accenture.py

```python
{'atp/brand/Accenture': 321,
'atp/brand_wikidata/Q29123313': 321,
'atp/category/missing': 321,
'atp/country/AE': 2,
'atp/country/AR': 4,
'atp/country/AT': 1,
'atp/country/AU': 6,
'atp/country/BE': 1,
'atp/country/BG': 2,
'atp/country/BR': 11,
'atp/country/CA': 13,
'atp/country/CH': 9,
'atp/country/CL': 1,
'atp/country/CN': 12,
'atp/country/CO': 3,
'atp/country/CR': 1,
'atp/country/CZ': 2,
'atp/country/DE': 21,
'atp/country/DK': 3,
'atp/country/ES': 13,
'atp/country/FI': 2,
'atp/country/FR': 6,
'atp/country/GB': 7,
'atp/country/GR': 2,
'atp/country/HK': 1,
'atp/country/HU': 2,
'atp/country/ID': 2,
'atp/country/IE': 4,
'atp/country/IL': 2,
'atp/country/IN': 29,
'atp/country/IT': 16,
'atp/country/JP': 12,
'atp/country/LT': 1, …
```

[Accenture] Fix Spider

---

locations/spiders/dominos_pizza_au.py

**_Fixes : updated sitemap_rules to fix spider_**
```python
{"atp/brand/Domino's": 724,
'atp/brand_wikidata/Q839466': 724,
'atp/category/amenity/fast_food': 724,
'atp/country/AU': 724,
'atp/field/branch/missing': 724,
'atp/field/city/missing': 724,
'atp/field/country/from_spider_name': 724,
'atp/field/email/missing': 724,
'atp/field/operator/missing': 724,
'atp/field/operator_wikidata/missing': 724,
'atp/field/postcode/missing': 724,
'atp/field/state/missing': 724,
'atp/field/street_address/missing': 724,
'atp/field/twitter/missing': 724,
'atp/item_scraped_host_count/www.dominos.com.au': 724,
'atp/nsi/cc_match': 724,
'downloader/exception_count': 6,
'downloader/exception_type_count/twisted.internet.error.TimeoutError': 6,
'downloader/request_bytes': 721028, …
```

[Dominos Pizza AU] Fix Spider

---

locations/spiders/porsche.py

**_Fixes : flagged robotstxt_obey as False to fix spider_**
```python
{'atp/brand/Porsche': 956,
'atp/brand_wikidata/Q40993': 956,
'atp/category/shop/car': 956,
'atp/country/AE': 5,
'atp/country/AM': 1,
'atp/country/AR': 2,
'atp/country/AT': 7,
'atp/country/AU': 16,
'atp/country/AZ': 1,
'atp/country/BA': 1,
'atp/country/BE': 9,
'atp/country/BG': 2,
'atp/country/BH': 1,
'atp/country/BN': 1,
'atp/country/BR': 16,
'atp/country/CA': 23,
'atp/country/CH': 14,
'atp/country/CL': 2,
'atp/country/CN': 132,
'atp/country/CO': 4,
'atp/country/CR': 1,
'atp/country/CW': 1,
'atp/country/CY': 2,
'atp/country/CZ': 3,
'atp/country/DE': 89,
'atp/country/DK': 2,
'atp/country/DO': 1,
'atp/country/EC': 1,
'atp/country/EE': 1,
'atp/country/EG': 3,
'atp/country/ES': 27,
'atp/country/FI': 5,
'atp/country/FR': 38, …
```

[Porsche] Fix Spider

---

locations/spiders/astron_energy_za.py

```python
{'atp/brand/Astron Energy': 527,
'atp/brand_wikidata/Q120752181': 527,
'atp/category/amenity/fuel': 527,
'atp/clean_strings/city': 5,
'atp/clean_strings/street_address': 520,
'atp/country/ZA': 527,
'atp/field/country/from_spider_name': 527,
'atp/field/email/missing': 527,
'atp/field/image/missing': 433,
'atp/field/operator/missing': 527,
'atp/field/operator_wikidata/missing': 527,
'atp/field/postcode/missing': 527,
'atp/field/twitter/missing': 527,
'atp/field/website/missing': 527,
'atp/item_scraped_host_count/www.astronenergy.co.za': 527,
'atp/lineage': …
```

[Astron Energy ZA] Fix spider

---

locations/spiders/cex.py

The URLs for the individual CeX store pages have changed slightly. Rather than https://uk.webuy.com/site/storeDetail/?branchId=91 they are now https://uk.webuy.com/site/storeDetail?branchId=91 . (No terminal forward slash before the query string.)

Correct constructed website URL in CeX spider

---

locations/spiders/greystar.py

```py
{'atp/category/landuse/residential': 3687,
'atp/country/AT': 1,
'atp/country/AU': 2,
'atp/country/BR': 1,
'atp/country/CA': 4,
'atp/country/CL': 3,
'atp/country/DE': 3,
'atp/country/ES': 23,
'atp/country/FR': 2,
'atp/country/GB': 99,
'atp/country/IE': 3,
'atp/country/NL': 7,
'atp/country/US': 3538,
'atp/field/branch/missing': 3687,
'atp/field/brand/missing': 3687,
'atp/field/brand_wikidata/missing': 3687,
'atp/field/country/from_reverse_geocoding': 13,
'atp/field/email/invalid': 200,
'atp/field/email/missing': 281,
'atp/field/lat/missing': 51,
'atp/field/lon/missing': 51,
'atp/field/opening_hours/missing': 3687,
'atp/field/phone/missing': 18, …
```

New spider: Greystar apartments (3687 locations)

---

locations/spiders/cashbuild.py

**_Fixes : Flag spider as requires proxy to fix spider_**
```python
{'atp/brand/Cashbuild': 284,
'atp/brand_wikidata/Q116474606': 284,
'atp/category/shop/doityourself': 284,
'atp/cdn/cloudflare/response_count': 7,
'atp/cdn/cloudflare/response_status_count/200': 7,
'atp/country/BW': 9,
'atp/country/LS': 8,
'atp/country/MW': 2,
'atp/country/NA': 4,
'atp/country/SZ': 6,
'atp/country/ZA': 255,
'atp/field/image/missing': 284,
'atp/field/operator/missing': 284,
'atp/field/operator_wikidata/missing': 284,
'atp/field/postcode/missing': 11,
'atp/field/state/missing': 284,
'atp/field/street_address/missing': 284,
'atp/field/twitter/missing': 284,
'atp/field/website/missing': 284,
'atp/item_scraped_host_count/www.cashbuild.co.za': 284, …
```

[Cashbuild] Fix Spider

---

locations/spiders/scotrail_gb.py

```python
{'atp/category/railway/station': 364,
'atp/cdn/cloudflare/response_count': 366,
'atp/cdn/cloudflare/response_status_count/200': 366,
'atp/country/GB': 364,
'atp/field/branch/missing': 364,
'atp/field/brand/missing': 364,
'atp/field/brand_wikidata/missing': 364,
'atp/field/city/missing': 364,
'atp/field/country/from_spider_name': 364,
'atp/field/email/missing': 364,
'atp/field/image/missing': 364,
'atp/field/opening_hours/missing': 364,
'atp/field/phone/missing': 364,
'atp/field/postcode/missing': 364,
'atp/field/state/missing': 364,
'atp/field/street_address/missing': 364,
'atp/field/twitter/missing': 364,
'atp/item_scraped_host_count/www.scotrail.co.uk': 364,
'atp/nsi/operator_missing': 364,
'atp/operator/ScotRail': 364, …
```

[ScotRail GB] Fix coord extraction

---

locations/spiders/infrastructure/fdsn_seismic_stations.py

Note: FDSN contains a list of "datacenters" which are repositories that different country/organisation seismic networks report to. This spider crawls each datacenter API endpoint to list stations which are connected to the repository.
Note: historical seismic stations are also extracted as features as there was once data recorded at a location, and this is a useful geographic feature to be aware of for possible users of ATP. For example, someone scrolling around a map near a dormant volcano might notice that 10 years ago there was a monitoring station present, and archival records exist, and these records are interesting from a historical perspective of understanding a volcanic eruption that occurred 10 years ago.

[FDSN] Add spider for federated network of seismic stations (89k stations)

---

locations/spiders/citiwood_za.py

`coordinates` are not available.
```python
{'atp/brand/Citiwood': 3,
'atp/brand_wikidata/Q130407139': 3,
'atp/category/shop/trade': 3,
'atp/cdn/cloudflare/response_count': 5,
'atp/cdn/cloudflare/response_status_count/200': 5,
'atp/country/ZA': 3,
'atp/field/name/missing': 3,
'atp/item_scraped_host_count/citiwood.co.za': 3, …
```

[Citiwood ZA] Fix spider

---

locations/spiders/citgo.py

`API` is also there but requires `cookies` which gets expire, so doesn't look feasible to utilize. Hence ignored and used `Structured Data` with `Sitemap` to fix the spider.
```python
{'atp/brand/Citgo': 4249,
'atp/brand_wikidata/Q2974437': 4249,
'atp/category/amenity/fuel': 4249,
'atp/country/US': 4249,
'atp/field/branch/missing': 4249,
'atp/field/country/from_reverse_geocoding': 20,
'atp/field/email/missing': 4249,
'atp/field/image/missing': 4249,
'atp/field/operator/missing': 4249,
'atp/field/operator_wikidata/missing': 4249,
'atp/field/phone/missing': 49,
'atp/field/twitter/missing': 4249,
'atp/item_scraped_host_count/www.citgo.com': 4249, …
```

[Citgo] Fix spider

---

locations/spiders/dominos_pizza_tw.py

**_Fixes : code updated to use sitemap to fix spider_**
```python
{"atp/brand/Domino's": 181,
'atp/brand_wikidata/Q839466': 181,
'atp/category/amenity/fast_food': 181,
'atp/country/TW': 181,
'atp/field/city/missing': 181,
'atp/field/country/from_spider_name': 181,
'atp/field/email/missing': 181,
'atp/field/image/missing': 181,
'atp/field/opening_hours/missing': 181,
'atp/field/phone/missing': 181,
'atp/field/postcode/missing': 181,
'atp/field/state/missing': 181,
'atp/field/street_address/missing': 181,
'atp/field/twitter/missing': 181,
'atp/item_scraped_host_count/www.dominos.com.tw': 181,
'atp/nsi/cc_match': 181,
'atp/operator/晶華國際酒店集團': 181,
'atp/operator_wikidata/Q11090227': 181,
'downloader/request_bytes': 165734,
'downloader/request_count': 183, …
```

[Dominos Pizza TW] Fix Spider

---

locations/spiders/dominos_pizza_fr.py

**_Fixes : updated sitemap rules to fix spider_**
```python
{"atp/brand/Domino's": 435,
'atp/brand_wikidata/Q839466': 435,
'atp/category/amenity/fast_food': 435,
'atp/country/FR': 435,
'atp/field/branch/missing': 435,
'atp/field/city/missing': 435,
'atp/field/country/from_spider_name': 435,
'atp/field/email/missing': 435,
'atp/field/image/missing': 435,
'atp/field/opening_hours/missing': 435,
'atp/field/operator/missing': 435,
'atp/field/operator_wikidata/missing': 435,
'atp/field/postcode/missing': 435,
'atp/field/state/missing': 435,
'atp/field/street_address/missing': 435,
'atp/field/twitter/missing': 435,
'atp/item_scraped_host_count/www.dominos.fr': 435,
'atp/nsi/cc_match': 435,
'downloader/request_bytes': 419982,
'downloader/request_count': 440, …
```

[Dominos Pizza FR] Fix Spider

---

locations/spiders/dominos_pizza_de.py

```python
{"atp/brand/Domino's": 398,
'atp/brand_wikidata/Q839466': 398,
'atp/category/amenity/fast_food': 398,
'atp/country/DE': 398,
'atp/field/country/from_spider_name': 15,
'atp/field/email/missing': 398,
'atp/field/image/missing': 398,
'atp/field/opening_hours/missing': 398,
'atp/field/operator/missing': 398,
'atp/field/operator_wikidata/missing': 398,
'atp/field/phone/missing': 398,
'atp/field/state/missing': 398,
'atp/field/twitter/missing': 398,
'atp/item_scraped_host_count/www.dominos.de': 398,
'atp/nsi/cc_match': 398,
'downloader/request_bytes': 384066,
'downloader/request_count': 400,
'downloader/request_method_count/GET': 400,
'downloader/response_bytes': 14544586, …
```

[Dominos Pizza DE] Fix spider

---

locations/spiders/repont_hu.py

```python
{'atp/brand/REpont': 4124,
'atp/brand_wikidata/Q130348902': 4124,
'atp/category/amenity/vending_machine': 4124,
'atp/clean_strings/city': 130,
'atp/clean_strings/email': 9,
'atp/clean_strings/name': 65,
'atp/clean_strings/phone': 6,
'atp/clean_strings/postcode': 1,
'atp/clean_strings/street_address': 289,
'atp/country/HU': 4124,
'atp/field/branch/missing': 4124,
'atp/field/country/from_spider_name': 4124,
'atp/field/email/invalid': 61,
'atp/field/email/missing': 3856,
'atp/field/image/missing': 4124,
'atp/field/name/missing': 682,
'atp/field/opening_hours/missing': 4124,
'atp/field/phone/invalid': 15,
'atp/field/phone/missing': 3718,
'atp/field/state/missing': 4124, …
```

[Repont HU] Fix Spider

---

locations/spiders/walmart_ca.py

```python
{'atp/brand/Walmart': 387,
'atp/brand_wikidata/Q483551': 387,
'atp/category/shop/department_store': 387,
'atp/country/CA': 387,
'atp/duplicate_count': 11691,
'atp/field/email/missing': 387,
'atp/field/image/missing': 387,
'atp/field/operator/missing': 387,
'atp/field/operator_wikidata/missing': 387,
'atp/field/phone/missing': 387,
'atp/field/twitter/missing': 387,
'atp/field/website/missing': 387,
'atp/item_scraped_host_count/www.walmart.ca': 12078,
'atp/nsi/cc_match': 387,
'downloader/request_bytes': 725972,
'downloader/request_count': 330,
'downloader/request_method_count/GET': 330,
'downloader/response_bytes': 4056394,
'downloader/response_count': 330,
'downloader/response_status_count/200': 330,
'elapsed_time_seconds': 16.081036, …
```

[Walmart CA] Fix spider

---

locations/spiders/blink.py

Fixed low scraped count. Also added `custom_settings` to avoid API rate limit error. Setting lower than `download_delay=5`, results `http 429` error.

[Blink] Fix low scraped count and add download delay to avoid http 429 error

---

locations/spiders/spar_al.py

Works fine from `IN`. 
```python
{'atp/brand/Spar': 75,
'atp/brand_wikidata/Q610492': 75,
'atp/category/shop/supermarket': 75,
'atp/clean_strings/lon': 1,
'atp/country/AL': 75,
'atp/field/branch/missing': 75,
'atp/field/city/missing': 75,
'atp/field/country/from_spider_name': 75,
'atp/field/email/missing': 75,
'atp/field/phone/missing': 75,
'atp/field/postcode/missing': 75,
'atp/field/state/missing': 75,
'atp/field/street_address/missing': 75,
'atp/field/website/missing': 75,
'atp/item_scraped_host_count/www.spar.al': 75,
'atp/nsi/cc_match': 75, …
```

[Spar AL] Try with proxy to fix spider

---

locations/spiders/chicos.py

This only fixes an error that wasn't affecting scraping. chicosofftherack.com doesn't exist any more, instead all OTR locations are on the main chicos.com. That means that we can't use the website domain to get the specific brand, but the brand is in the structured data, so use that.
Also get the branch name.

Chico's: Remove Off The Rack from start_urls; use name as brand key

---

locations/spiders/bred_fr.py

```python
{'atp/brand/BRED': 376,
'atp/brand_wikidata/Q2877455': 376,
'atp/category/amenity/bank': 376,
'atp/country/FR': 376,
'atp/field/country/from_spider_name': 376,
'atp/field/image/missing': 376,
'atp/field/operator/missing': 376,
'atp/field/operator_wikidata/missing': 376,
'atp/field/state/missing': 376,
'atp/field/twitter/missing': 376,
'atp/item_scraped_host_count/www.bred.fr': 376,
'atp/nsi/cc_match': 376,
'downloader/request_bytes': 183504,
'downloader/request_count': 378,
'downloader/request_method_count/GET': 378,
'downloader/response_bytes': 44759614,
'downloader/response_count': 378,
'downloader/response_status_count/200': 378, …
```

[Bred FR] Add Spider (376 locations)

---

locations/pipelines/address_clean_up.py
tests/test_address_clean_up.py

Address clean up pipeline removes address components with less than 2 character address components not taking into account Chinese/Japanese/Korean languages where words can consists from one or two characters. Quite some `city` from `tesla` spider is removed because of this ([example](https://www.tesla.com/cua-api/tesla-location?translate=en_US&usetrt=true&id=cnsc10343)).
For implementation I took unicode  ranges from https://jrgraphix.net/research/unicode_blocks.php.

[address clean up pipeline] do not remove short Chinese address components

---

locations/spiders/argenta_be.py

Brand is mainly present in `BE`. Couldn't find POI locator for [NL](https://www.argenta.nl/) and [LU](https://www.argenta.lu/).
```python
{'atp/brand/Argenta': 351,
'atp/brand_wikidata/Q932856': 351,
'atp/category/amenity/bank': 351,
'atp/country/BE': 351,
'atp/field/branch/missing': 351,
'atp/field/country/from_spider_name': 351,
'atp/field/image/missing': 351,
'atp/field/operator/missing': 351,
'atp/field/operator_wikidata/missing': 351,
'atp/field/street_address/missing': 351,
'atp/field/twitter/missing': 351,
'atp/item_scraped_host_count/www.argenta.be': 351,
'atp/nsi/cc_match': 351,
'downloader/request_bytes': 711, …
```

[Argenta BE] Add spider (351 locations)

---

locations/spiders/gscaltex_kr.py

```python
{'atp/brand/GS칼텍스': 2287,
'atp/brand_wikidata/Q624012': 2287,
'atp/category/amenity/fuel': 2287,
'atp/clean_strings/street_address': 7,
'atp/country/KR': 2287,
'atp/field/branch/missing': 2287,
'atp/field/city/missing': 2287,
'atp/field/country/from_spider_name': 2287,
'atp/field/email/missing': 2287,
'atp/field/image/missing': 2287,
'atp/field/opening_hours/missing': 2287,
'atp/field/operator/missing': 2287,
'atp/field/operator_wikidata/missing': 2287,
'atp/field/state/missing': 2287,
'atp/field/twitter/missing': 2287,
'atp/field/website/missing': 2287,
'atp/item_scraped_host_count/www.gscenergyplus.com': 2287,
'atp/nsi/cc_match': 2287, …
```

[Gscaltex KR] Fix spider

---

locations/spiders/fnbc_ca.py

`'item_dropped_count': 152` is due to actual duplicate entries in the data.
```python
{'atp/brand/First Nations Bank of Canada': 31,
'atp/brand_wikidata/Q1419511': 31,
'atp/category/amenity/atm': 3558,
'atp/category/amenity/bank': 22,
'atp/clean_strings/name': 54,
'atp/country/CA': 3580,
'atp/duplicate_count': 152,
'atp/field/branch/missing': 3558,
'atp/field/brand/missing': 3549,
'atp/field/brand_wikidata/missing': 3549,
'atp/field/country/from_spider_name': 3580,
'atp/field/email/missing': 3580,
'atp/field/image/missing': 3580,
'atp/field/opening_hours/missing': 3558,
'atp/field/operator/missing': 3580,
'atp/field/operator_wikidata/missing': 3580,
'atp/field/phone/missing': 3558,
'atp/field/twitter/missing': 3580,
'atp/field/website/missing': 3558, …
```

[Fnbc CA] Add spider (3580 locations)

---

locations/spiders/fulton_bank_us.py

```python
{'atp/brand/Fulton Bank': 222,
'atp/brand_wikidata/Q16976594': 222,
'atp/category/amenity/atm': 17,
'atp/category/amenity/bank': 205,
'atp/clean_strings/branch': 5,
'atp/country/US': 222,
'atp/field/city/missing': 222,
'atp/field/country/from_spider_name': 222,
'atp/field/email/missing': 222,
'atp/field/image/missing': 222,
'atp/field/name/missing': 17,
'atp/field/operator/missing': 205,
'atp/field/operator_wikidata/missing': 205,
'atp/field/postcode/missing': 222,
'atp/field/state/from_reverse_geocoding': 222,
'atp/field/street_address/missing': 222,
'atp/field/twitter/missing': 222,
'atp/field/website/missing': 222,
'atp/item_scraped_host_count/www.fultonbank.com': 222, …
```

[Fulton Bank US] Add spider (222 locations)

---

locations/name_suggestion_index.py

Changed `lstrip()` to `removeprefix()`.
`lstrip()`'s argument is a string specifying the set of characters to be removed **not a prefix.**
`removeprefix()`is a method that will remove a single prefix string rather than all of a set of characters. 
For example in our case:
```
site = "www.wikipedia.com"
site.lstrip("www.wikipedia.com")
site.removeprefix("www.wikipedia.com")
```
For Reference:  https://docs.python.org/3/library/stdtypes.html#str.lstrip

Using removeprefix() instead of lstrip(). 

---

locations/spiders/cadence_bank_us.py

```python
{'atp/brand/Cadence Bank': 391,
'atp/brand_wikidata/Q4854138': 391,
'atp/category/amenity/bank': 391,
'atp/cdn/cloudflare/response_count': 394,
'atp/cdn/cloudflare/response_status_count/200': 394,
'atp/country/US': 391,
'atp/field/branch/missing': 391,
'atp/field/country/from_spider_name': 391,
'atp/field/email/missing': 391,
'atp/field/operator/missing': 391,
'atp/field/operator_wikidata/missing': 391,
'atp/item_scraped_host_count/cadencebank.com': 391,
'atp/nsi/cc_match': 391,
'downloader/request_bytes': 291758,
'downloader/request_count': 395,
'downloader/request_method_count/GET': 395,
'downloader/response_bytes': 8300939,
'downloader/response_count': 395, …
```

[Cadence Bank US] Add Spider (391 locations)

---

locations/spiders/barclays_gb.py

```python
{'atp/brand/Barclays': 1132,
'atp/brand_wikidata/Q245343': 1132,
'atp/category/amenity/atm': 369,
'atp/category/amenity/bank': 763,
'atp/clean_strings/city': 17,
'atp/clean_strings/postcode': 12,
'atp/clean_strings/state': 19,
'atp/clean_strings/street_address': 107,
'atp/country/GB': 1132,
'atp/duplicate_count': 15228,
'atp/field/email/missing': 1132,
'atp/field/name/missing': 369,
'atp/field/operator/missing': 763,
'atp/field/operator_wikidata/missing': 763,
'atp/field/phone/missing': 1132,
'atp/field/state/missing': 64,
'atp/item_scraped_host_count/search.barclays.co.uk': 16360,
'atp/nsi/cc_match': 1132,
'atp/operator/Barclays': 369,
'atp/operator_wikidata/Q245343': 369, …
```

[Barclays GB] Add Spider (1132 locations)

---

locations/categories.py
locations/spiders/mercedes_benz_group.py

This is probably questionable, so I'm fine if it's not merged.
```python
{'atp/brand/Fuso': 1816,
'atp/brand/Mercedes-Benz': 6359,
'atp/brand/Mercedes-Benz Buses': 1478,
'atp/brand/Mercedes-Benz Trucks': 2817,
'atp/brand/Mercedes-Benz Vans': 5538,
'atp/brand/OMNIplus': 564,
'atp/brand/Setra': 611,
'atp/brand/Smart': 1704,
'atp/brand_wikidata/Q1190247': 1816,
'atp/brand_wikidata/Q122922653': 564,
'atp/brand_wikidata/Q1427345': 1478,
'atp/brand_wikidata/Q156490': 1704,
'atp/brand_wikidata/Q36008': 9176,
'atp/brand_wikidata/Q55383469': 5538,
'atp/brand_wikidata/Q938615': 611,
'atp/category/amenity/car_rental': 580,
'atp/category/shop/bus': 431,
'atp/category/shop/bus_repair': 2222,
'atp/category/shop/car': 4931,
'atp/category/shop/car_repair': 8090,
'atp/category/shop/truck': 1638, …
```

[mercedes_benz_group] parse more countries, brands and types

---

locations/spiders/unicredit_bank_it.py

```python
{'atp/brand/UniCredit Bank': 7279,
'atp/brand_wikidata/Q45568': 7279,
'atp/category/amenity/atm': 5067,
'atp/category/amenity/bank': 2212,
'atp/country/IT': 7279,
'atp/field/branch/missing': 7279,
'atp/field/country/from_spider_name': 7279,
'atp/field/email/missing': 5080,
'atp/field/image/missing': 7279,
'atp/field/name/missing': 5067,
'atp/field/opening_hours/missing': 5328,
'atp/field/operator/missing': 2212,
'atp/field/operator_wikidata/missing': 2212,
'atp/field/phone/missing': 5180,
'atp/field/postcode/missing': 5067,
'atp/field/twitter/missing': 7279,
'atp/item_scraped_host_count/www.geocms.it': 7279,
'atp/nsi/cc_match': 7279,
'atp/operator/UniCredit Bank': 5067,
'atp/operator_wikidata/Q45568': 5067,
'downloader/request_bytes': 9177957, …
```

[Unicredit Bank IT] Add spider (7279 locations)

---

locations/storefinders/amai_promap.py

[Amai ProMap](https://amai.com/apps/promap-store-locator/) URL redirects to [Roseperl ProMap](https://roseperl.com/promap-store-locator/), suggests that the app has migrated. Fix applied to handle both domains in `AmaiPromapSpider`. `Roseperl` domain is now used by `AmericanMattressUSSpider`, that's why it was failing, now fixed.
```python
{'atp/brand/American Mattress': 73,
'atp/brand_wikidata/Q126896153': 73,
'atp/category/shop/bed': 73,
'atp/country/US': 73,
'atp/field/branch/missing': 73,
'atp/field/operator/missing': 73,
'atp/field/operator_wikidata/missing': 73,
'atp/field/state/from_reverse_geocoding': 3, …
```

[American Mattress US] Fix spider by updating Amai Promap Spider

---

locations/hours.py
locations/spiders/athena.py
locations/storefinders/storerocket.py
tests/test_opening_hours.py

To support this new spider, the existing StoreRocket storefinder has been significantly improved to add geographic search methods for returning features. Athena's StoreRocket instance caps features returned to 25 by default, and this can be increased to 1000, but this still isn't enough to capture all features particularly across the US. Therefore a large ISEADGG search radius is used to keep result sets under 1000 features per search.

[Athena] Add spider for cryptocurrency ATMs in US, CO, SV, AR

---

locations/spiders/auchan_pt.py

Rel: https://github.com/osmlab/name-suggestion-index/pull/11163
```python
{'atp/brand/Auchan': 63,
'atp/brand/Auchan Supermercado': 36,
'atp/brand/My Auchan': 192,
'atp/brand_wikidata/Q105857776': 36,
'atp/brand_wikidata/Q115800307': 192,
'atp/brand_wikidata/Q758603': 63,
'atp/category/amenity/fuel': 31,
'atp/category/shop/convenience': 192,
'atp/category/shop/supermarket': 68,
'atp/cdn/cloudflare/response_count': 293,
'atp/cdn/cloudflare/response_status_count/200': 293,
'atp/clean_strings/phone': 290,
'atp/country/PT': 291,
'atp/field/image/invalid': 2,
'atp/field/image/missing': 206,
'atp/field/name/missing': 31,
'atp/field/opening_hours/missing': 61,
'atp/field/operator/missing': 291,
'atp/field/operator_wikidata/missing': 291, …
```

[Auchan PT] Sync brands with NSI

---

locations/spiders/mcdonalds_be.py

**_Fixes : added custom_settings to fix spider_**
```python
{"atp/brand/McDonald's": 124,
'atp/brand_wikidata/Q38076': 124,
'atp/category/amenity/fast_food': 124,
'atp/clean_strings/phone': 9,
'atp/clean_strings/street': 7,
'atp/country/BE': 124,
'atp/field/branch/missing': 124,
'atp/field/country/from_spider_name': 124,
'atp/field/email/missing': 124,
'atp/field/image/missing': 124,
'atp/field/operator/missing': 124,
'atp/field/operator_wikidata/missing': 124,
'atp/field/state/missing': 124,
'atp/field/street_address/missing': 124,
'atp/field/twitter/missing': 124,
'atp/item_scraped_host_count/www.mcdonalds.be': 124,
'atp/nsi/cc_match': 124,
'downloader/request_bytes': 301, …
```

[McDonalds BE] Fix Spider

---

locations/spiders/banco_mercantil_br.py

```python
{'atp/brand/Banco Mercantil do Brasil': 146,
'atp/brand_wikidata/Q9645252': 146,
'atp/category/amenity/bank': 146,
'atp/country/BR': 146,
'atp/field/city/missing': 146,
'atp/field/country/from_spider_name': 146,
'atp/field/image/missing': 146,
'atp/field/opening_hours/missing': 146,
'atp/field/operator/missing': 146,
'atp/field/operator_wikidata/missing': 146,
'atp/field/phone/missing': 24,
'atp/field/postcode/missing': 146,
'atp/field/state/missing': 146,
'atp/field/street_address/missing': 146,
'atp/field/website/missing': 146,
'atp/item_scraped_host_count/bancomercantil.com.br': 146,
'atp/nsi/cc_match': 146,
'downloader/request_bytes': 863, …
```

[Banco Mercantil BR] Add Spider (146 locations)

---

locations/spiders/arvest_bank_us.py
locations/storefinders/momentfeed.py

```python
{'atp/brand/Arvest Bank': 294,
'atp/brand_wikidata/Q4802393': 294,
'atp/category/amenity/atm': 75,
'atp/category/amenity/bank': 219,
'atp/country/US': 294,
'atp/field/branch/missing': 294,
'atp/field/email/missing': 294,
'atp/field/image/missing': 294,
'atp/field/opening_hours/missing': 58,
'atp/field/operator/missing': 219,
'atp/field/operator_wikidata/missing': 219,
'atp/field/twitter/missing': 294,
'atp/item_scraped_host_count/uberall.com': 294,
'atp/nsi/cc_match': 294,
'atp/operator/Arvest Bank': 75,
'atp/operator_wikidata/Q4802393': 75,
'downloader/request_bytes': 1917,
'downloader/response_bytes': 2553234, …
```

[Arvest Bank US] Add Spider (294 locations)

---

locations/spiders/carrefour_ar.py

Used `GraphQL` query and dropped volatile persisted query to fix the spider.
```python
{'atp/brand/Carrefour': 118,
'atp/brand/Carrefour Express': 460,
'atp/brand/Carrefour Market': 85,
'atp/brand_wikidata/Q217599': 118,
'atp/brand_wikidata/Q2689639': 85,
'atp/brand_wikidata/Q2940190': 460,
'atp/category/shop/convenience': 460,
'atp/category/shop/supermarket': 203,
'atp/country/AR': 663,
'atp/field/branch/missing': 663,
'atp/field/country/from_spider_name': 663,
'atp/field/email/missing': 663,
'atp/field/image/missing': 663,
'atp/field/operator/missing': 663,
'atp/field/operator_wikidata/missing': 663, …
```

[Carrefour AR] Fix spider

---

locations/spiders/tmobile_us.py

Applied some `custom_settings` to avoid http `408` error and fix the [low scraped count](https://alltheplaces-data.openaddresses.io/runs/2025-07-22-02-29-22/stats/tmobile_us.json).
```python
{'atp/brand/T-Mobile': 6137,
'atp/brand_wikidata/Q3511885': 6137,
'atp/category/shop/mobile_phone': 6137,
'atp/clean_strings/addr_full': 7,
'atp/clean_strings/name': 3521,
'atp/country/US': 6137,
'atp/field/branch/missing': 6137,
'atp/field/email/missing': 6137,
'atp/field/opening_hours/missing': 32,
'atp/field/operator/missing': 6137,
'atp/field/operator_wikidata/missing': 6137,
'atp/field/street_address/missing': 6137,
'atp/field/twitter/missing': 6137,
'atp/item_scraped_host_count/www.t-mobile.com': 6137,
'atp/nsi/perfect_match': 6137,
'downloader/request_bytes': 9434766, …
```

[T Mobile US] Fix low scraped count for the spider

---

locations/storefinders/yext_answers.py

Commit aed3b661c3f97000133f35e9f921c51690e32235 caused `TypeError: Object of type OpeningHours is not JSON serializable` errors.
Should be ok to call `parse_opening_hours().as_opening_hours()` in these cases because `parse_opening_hours` only returns `None` if the input is `None`, and that's already checked for.

[YextAnswers] Fix opening_hours parsing

---

locations/categories.py
locations/spiders/spotless_water_gb.py

Rel: https://community.openstreetmap.org/t/distilled-water-vending-machine-how-to-tag/133034
```python
{'atp/brand/SpotlessWater': 143,
'atp/category/amenity/vending_machine': 143,
'atp/country/GB': 143,
'atp/field/branch/missing': 143,
'atp/field/brand_wikidata/missing': 143,
'atp/field/city/missing': 143,
'atp/field/country/from_spider_name': 143,
'atp/field/email/missing': 143,
'atp/field/name/missing': 143,
'atp/field/opening_hours/missing': 143,
'atp/field/operator/missing': 143,
'atp/field/operator_wikidata/missing': 143,
'atp/field/phone/missing': 143,
'atp/field/postcode/missing': 18,
'atp/field/state/missing': 143,
'atp/field/street_address/missing': 143,
'atp/field/twitter/missing': 143,
'atp/field/website/missing': 12, …
```

[SpotlessWater GB] Add spider

---

locations/spiders/banca_sella_it.py

```python
{'atp/brand/Banca Sella': 279,
'atp/brand_wikidata/Q3633749': 279,
'atp/category/amenity/bank': 279,
'atp/country/IT': 279,
'atp/field/branch/missing': 279,
'atp/field/country/from_spider_name': 279,
'atp/field/email/missing': 279,
'atp/field/image/missing': 279,
'atp/field/opening_hours/missing': 279,
'atp/field/operator/missing': 279,
'atp/field/operator_wikidata/missing': 279,
'atp/field/state/missing': 279,
'atp/field/twitter/missing': 279,
'atp/field/website/missing': 279,
'atp/item_scraped_host_count/www.sella.it': 279,
'atp/nsi/cc_match': 279,
'downloader/request_bytes': 361,
'downloader/response_bytes': 19185, …
```

[Banca Sella IT] Added ATM Info

---

locations/spiders/hackett_london.py

Fixes #13857
```python
{'atp/brand/Hackett London': 121,
'atp/brand_wikidata/Q1136426': 121,
'atp/category/shop/clothes': 121,
'atp/cdn/cloudflare/response_count': 125,
'atp/cdn/cloudflare/response_status_count/200': 124,
'atp/country/AT': 1,
'atp/country/BE': 4,
'atp/country/CH': 3,
'atp/country/CL': 1,
'atp/country/DE': 7,
'atp/country/ES': 63,
'atp/country/FR': 7,
'atp/country/GB': 20,
'atp/country/IE': 1,
'atp/country/MX': 8,
'atp/country/PT': 6,
'atp/duplicate_count': 2,
'atp/field/country/from_reverse_geocoding': 121,
'atp/field/operator/missing': 121,
'atp/field/operator_wikidata/missing': 121, …
```

[Hackett London] Add spider

---

locations/spiders/goldsmiths_gb.py

**_Fixes : updated request url to fix spider_**
```python
{'atp/brand/Goldsmiths': 136,
'atp/brand_wikidata/Q16993095': 136,
'atp/category/shop/jewelry': 136,
'atp/country/GB': 136,
'atp/field/image/missing': 136,
'atp/field/operator/missing': 136,
'atp/field/operator_wikidata/missing': 136,
'atp/field/state/missing': 136,
'atp/field/twitter/missing': 136,
'atp/item_scraped_host_count/api.thewosgroup.com': 136,
'atp/nsi/perfect_match': 136,
'downloader/request_bytes': 795,
'downloader/response_bytes': 92391, …
```

[Goldsmiths GB] Fix Spider

---

locations/spiders/mitsubishi_jp.py

Car dealers are just stores, not independent businesses, so the "name" is just the branch.

change mitsubishi_jp location from "name" to "branch"

---

locations/spiders/consum_es.py

```python
{'atp/brand/Charter': 495,
'atp/brand/Consum': 510,
'atp/brand_wikidata/Q8350308': 510,
'atp/brand_wikidata/Q95916752': 495,
'atp/category/shop/supermarket': 1005,
'atp/country/ES': 1005,
'atp/field/email/missing': 1005,
'atp/field/image/missing': 1005,
'atp/field/opening_hours/missing': 1005,
'atp/field/operator/missing': 1005,
'atp/field/operator_wikidata/missing': 1005,
'atp/field/postcode/missing': 1005,
'atp/item_scraped_host_count/www.consum.es': 1005,
'atp/nsi/perfect_match': 1005,
'downloader/request_bytes': 595562,
'downloader/request_count': 1024,
'downloader/request_method_count/GET': 1024,
'downloader/response_bytes': 46313430,
'downloader/response_count': 1024, …
```

[Consum ES] Add spider

---

locations/spiders/natwest_gb.py

```python
{'atp/brand/NatWest': 847,
'atp/brand_wikidata/Q2740021': 847,
'atp/category/amenity/atm': 509,
'atp/category/amenity/bank': 338,
'atp/country/GB': 847,
'atp/duplicate_count': 50253,
'atp/field/branch/missing': 847,
'atp/field/email/missing': 847,
'atp/field/image/missing': 847,
'atp/field/opening_hours/missing': 510,
'atp/field/operator/missing': 338,
'atp/field/operator_wikidata/missing': 338,
'atp/field/phone/missing': 847,
'atp/field/state/missing': 56,
'atp/field/twitter/missing': 847,
'atp/field/website/missing': 11,
'atp/item_scraped_host_count/www.natwest.com': 51100,
'atp/nsi/cc_match': 847,
'atp/operator/NatWest': 509,
'atp/operator_wikidata/Q2740021': 509,
'downloader/request_bytes': 830907,
'downloader/request_count': 1086, …
```

[Natwest GB] Add ATM locations for spider

---

locations/spiders/marks_ca.py

**_Fixes : updated user agent to fix spider_**
```python
{"atp/brand/Mark's": 384,
'atp/brand_wikidata/Q6766373': 384,
'atp/category/shop/clothes': 384,
'atp/country/CA': 384,
'atp/field/city/missing': 384,
'atp/field/image/missing': 384,
'atp/field/name/missing': 384,
'atp/field/operator/missing': 384,
'atp/field/operator_wikidata/missing': 384,
'atp/field/twitter/missing': 384,
'atp/item_scraped_host_count/apim.marks.com': 384,
'atp/nsi/match_failed': 384,
'downloader/request_bytes': 821271,
'downloader/request_count': 387,
'downloader/request_method_count/GET': 387,
'downloader/response_bytes': 1013156,
'downloader/response_count': 387, …
```

[Marks CA] Fix Spider

---

locations/spiders/yha_au.py
locations/spiders/yha_gb.py

NSI/Wikidata both split "YHA" into country-specific brands/items. Use the correct names and Wikidata IDs per NSI.

[YHA AU GB] Fix brand names and Wikidata IDs

---

locations/spiders/halifax_gb.py

```python
{'atp/brand/Halifax': 760,
'atp/brand_wikidata/Q3310164': 760,
'atp/category/amenity/atm': 326,
'atp/category/amenity/bank': 434,
'atp/cdn/cloudflare/response_count': 1292,
'atp/cdn/cloudflare/response_status_count/200': 1292,
'atp/country/GB': 760,
'atp/field/branch/missing': 760,
'atp/field/email/missing': 760,
'atp/field/image/missing': 760,
'atp/field/opening_hours/missing': 112,
'atp/field/operator/missing': 434,
'atp/field/operator_wikidata/missing': 434,
'atp/field/phone/missing': 438,
'atp/field/state/missing': 760,
'atp/item_scraped_host_count/branches.halifax.co.uk': 760,
'atp/nsi/cc_match': 760,
'atp/operator/Halifax': 326,
'atp/operator_wikidata/Q3310164': 326,
'atp/structured_data/unmapped/amenity_features': 1289, …
```

[Halifax GB] Add ATM locations for spider

---

locations/spiders/lloyds_bank_gb.py

```python
{'atp/brand/Lloyds Bank': 1103,
'atp/brand_wikidata/Q1152847': 1103,
'atp/category/amenity/atm': 444,
'atp/category/amenity/bank': 659,
'atp/cdn/cloudflare/response_count': 1530,
'atp/cdn/cloudflare/response_status_count/200': 1529,
'atp/cdn/cloudflare/response_status_count/502': 1,
'atp/country/GB': 1103,
'atp/field/branch/missing': 1103,
'atp/field/email/missing': 1103,
'atp/field/image/missing': 1103,
'atp/field/opening_hours/missing': 230,
'atp/field/operator/missing': 659,
'atp/field/operator_wikidata/missing': 659,
'atp/field/phone/missing': 674,
'atp/field/state/missing': 1103,
'atp/item_scraped_host_count/branches.lloydsbank.com': 1103,
'atp/nsi/cc_match': 1103,
'atp/operator/Lloyds Bank': 444,
'atp/operator_wikidata/Q1152847': 444, …
```

[Lloyds Bank GB] Update spider to add ATM locations

---

locations/spiders/wimpy_gb.py

```python
{'atp/brand/Wimpy': 57,
'atp/brand_wikidata/Q2811992': 57,
'atp/category/amenity/fast_food': 57,
'atp/country/GB': 57,
'atp/field/branch/missing': 57,
'atp/field/image/missing': 57,
'atp/field/opening_hours/missing': 57,
'atp/field/operator/missing': 57,
'atp/field/operator_wikidata/missing': 57,
'atp/field/twitter/missing': 57,
'atp/item_scraped_host_count/wimpy.uk.com': 57,
'atp/nsi/perfect_match': 57,
'downloader/request_bytes': 675,
'downloader/response_bytes': 16938,
'elapsed_time_seconds': 3.409263, …
```

[Wimpy GB] Fix Spider

---

locations/spiders/burger_king.py
locations/spiders/burger_king_cl.py

Broken `Burger King CL Spider` deleted and added `CL` locations to `Burger King Global Spider`.
```python
{'atp/brand/Burger King': 9113,
'atp/brand_wikidata/Q177054': 9113,
'atp/category/amenity/fast_food': 9113,
'atp/clean_strings/branch': 3,
'atp/clean_strings/city': 20,
'atp/clean_strings/operator': 142,
'atp/clean_strings/street_address': 12,
'atp/country/AR': 116,
'atp/country/AT': 63,
'atp/country/CA': 322,
'atp/country/CH': 93,
'atp/country/CL': 83,
'atp/country/CZ': 58,
'atp/country/DE': 760,
'atp/country/ES': 918,
'atp/country/NL': 68,
'atp/country/PL': 72,
'atp/country/PT': 203,
'atp/country/RO': 37,
'atp/country/US': 6320,
```

[Burger King CL] Add CL to Burger King Global Spider and Delete broken Spider

---

locations/spiders/mitsubishi_by_ru.py

```python
{'atp/brand/Mitsubishi': 87,
'atp/brand_wikidata/Q36033': 87,
'atp/category/shop/car': 87,
'atp/country/BY': 4,
'atp/country/RU': 83,
'atp/field/branch/missing': 87,
'atp/field/city/missing': 87,
'atp/field/country/from_website_url': 87,
'atp/field/image/missing': 87,
'atp/field/opening_hours/missing': 87,
'atp/field/operator/missing': 87,
'atp/field/operator_wikidata/missing': 87,
'atp/field/postcode/missing': 87,
'atp/field/state/missing': 87,
'atp/field/street_address/missing': 87,
'atp/field/twitter/missing': 87,
'atp/item_scraped_host_count/www.mitsubishi-motors.ru': 87,
'atp/nsi/cc_match': 87,
'downloader/request_bytes': 739, …
```

[Mitsubishi BY RU] Fix  spider

---

locations/spiders/cisalfa_sport_it.py

Add [Cisalfa Sport](https://www.cisalfasport.it/), a sports store chain in IT.
```
2025-08-14 19:06:36 [scrapy.statscollectors] INFO: Dumping Scrapy stats:
{'atp/brand/Cisalfa Sport': 165,
'atp/brand_wikidata/Q113535511': 165,
'atp/category/shop/sports': 165,
'atp/country/IT': 165,
'atp/field/branch/missing': 165,
'atp/field/country/from_spider_name': 165,
'atp/field/email/missing': 165,
'atp/field/image/missing': 165,
'atp/field/operator/missing': 165,
'atp/field/operator_wikidata/missing': 165,
'atp/item_scraped_host_count/api.retailtune.com': 165,
'atp/nsi/perfect_match': 165,
```

[Cisalfa Sport IT] Add spider (165 locations)

---

locations/spiders/palm_beach_tan_us.py

**_Fixes : updated sitemap rules to fix spider_**
```python
{'atp/brand/Palm Beach Tan': 644,
'atp/brand_wikidata/Q64027086': 644,
'atp/category/shop/beauty': 644,
'atp/country/US': 644,
'atp/field/branch/missing': 644,
'atp/field/city/missing': 644,
'atp/field/country/from_spider_name': 644,
'atp/field/email/missing': 644,
'atp/field/image/missing': 644,
'atp/field/operator/missing': 644,
'atp/field/operator_wikidata/missing': 644,
'atp/field/postcode/missing': 644,
'atp/field/state/from_reverse_geocoding': 644,
'atp/field/street_address/missing': 644,
'atp/field/twitter/missing': 644,
'atp/item_scraped_host_count/palmbeachtan.com': 644,
'atp/nsi/perfect_match': 644, …
```

[Palm Beach Tan US] Fix Spider

---

locations/spiders/pudostation_jp.py

this was built by a company called GOGA so their other storefinders should be similar. [Check the bottom of this page under "その他の実績."](https://www.goga.co.jp/works) But there is no central URL or consistency in data format so there is no point in making a storefinder.

[PUDO parcel lockers JP] add spider

---

locations/spiders/ingo_dk.py

**_Fixes : updated sitemap_urls to fix spider_**
```python
{'atp/brand/Ingo': 197,
'atp/brand_wikidata/Q17048617': 197,
'atp/category/amenity/fuel': 197,
'atp/country/DK': 197,
'atp/field/email/missing': 197,
'atp/field/image/missing': 197,
'atp/field/opening_hours/missing': 194,
'atp/field/operator/missing': 197,
'atp/field/operator_wikidata/missing': 197,
'atp/field/state/missing': 197,
'atp/field/twitter/missing': 197,
'atp/item_scraped_host_count/www.ingo.dk': 197,
'atp/nsi/cc_match': 197,
'downloader/request_bytes': 80769,
'downloader/request_count': 199,
'downloader/request_method_count/GET': 199,
'downloader/response_bytes': 1667612,
'downloader/response_count': 199,
'downloader/response_status_count/200': 199,
'elapsed_time_seconds': 241.113286, …
```

[Ingo DK] Fix Spider

---

locations/spiders/oakley.py

```py
{'atp/brand/Oakley': 189,
'atp/brand_wikidata/Q161906': 189,
'atp/category/shop/optician': 189,
'atp/cdn/cloudflare/response_count': 191,
'atp/cdn/cloudflare/response_status_count/200': 191,
'atp/country/CA': 9,
'atp/country/GB': 4,
'atp/country/IT': 1,
'atp/country/NL': 2,
'atp/country/PR': 2,
'atp/country/US': 171,
'atp/field/branch/missing': 7,
'atp/field/email/missing': 189,
'atp/field/operator/missing': 189,
'atp/field/operator_wikidata/missing': 189,
'atp/field/twitter/missing': 189,
'atp/item_scraped_host_count/stores.oakley.com': 189,
'atp/nsi/match_failed': 189,
'downloader/request_bytes': 114123,
'downloader/request_count': 191,
'downloader/request_method_count/GET': 191,
'downloader/response_bytes': 3600269, …
```

[Oakley] New spider (189 locations)

---

locations/spiders/swarovski_eu.py
locations/spiders/swarovski_us.py

Summaries created for limited count.
**US**
```python
{'atp/brand/Swarovski': 53,
'atp/brand_wikidata/Q611115': 53,
'atp/category/shop/jewelry': 53,
'atp/country/US': 53,
'atp/field/branch/missing': 53,
'atp/field/country/from_spider_name': 53,
'atp/field/email/missing': 53,
'atp/field/image/dropped': 53,
'atp/field/image/missing': 53,
'atp/field/operator/missing': 53,
'atp/field/operator_wikidata/missing': 53,
'atp/field/state/from_reverse_geocoding': 53,
'atp/field/street_address/missing': 53,
'atp/field/twitter/missing': 53,
'atp/item_scraped_host_count/www.swarovski.com': 53,
'atp/nsi/perfect_match': 53,
'downloader/request_bytes': 169975,
'downloader/request_count': 294,
'downloader/request_method_count/GET': 294, …
```

[Swarovski US][Swarovski EU] Fix spiders

---

locations/spiders/seims_jp.py

```
'atp/brand/アメリカンドラッグ': 89,
'atp/brand/スーパードラッグキリン': 4,
'atp/brand/ドラッグストアスマイル': 9,
'atp/brand/ドラッグセイムス': 774,
'atp/brand/ドラッグユタカ': 224,
'atp/brand_wikidata/Q11456137': 1100,
'atp/category/amenity/pharmacy': 522,
'atp/category/multiple': 522,
'atp/category/shop/chemist': 578,
'atp/clean_strings/postcode': 1,
'atp/country/JP': 1100,
'atp/field/branch/missing': 1100,
'atp/field/city/missing': 1100,
'atp/field/country/from_spider_name': 1100,
'atp/field/email/missing': 1100,
'atp/field/image/missing': 1100,
'atp/field/opening_hours/missing': 1100,
'atp/field/operator/missing': 1100,
'atp/field/operator_wikidata/missing': 1100,
'atp/field/state/missing': 1100,
'atp/field/street_address/missing': 1100,
'atp/field/twitter/missing': 1100, …
```

[Seims JP] add spider

---

locations/spiders/banco_mercantil_br.py

**_Fixes : Flag banco_mercantil_br spider as requires proxy_**
```python
{'atp/brand/Banco Mercantil do Brasil': 146,
'atp/brand_wikidata/Q9645252': 146,
'atp/category/amenity/bank': 146,
'atp/country/BR': 146,
'atp/field/city/missing': 146,
'atp/field/country/from_spider_name': 146,
'atp/field/image/missing': 146,
'atp/field/opening_hours/missing': 146,
'atp/field/operator/missing': 146,
'atp/field/operator_wikidata/missing': 146,
'atp/field/phone/missing': 24,
'atp/field/postcode/missing': 146,
'atp/field/state/missing': 146,
'atp/field/street_address/missing': 146,
'atp/field/website/missing': 146,
'atp/item_scraped_host_count/bancomercantil.com.br': 146,
'atp/nsi/cc_match': 146, …
```

[Banco Mercantil BR] Fix Spider

---

locations/spiders/bmo.py
locations/storefinders/where2getit.py

```python
{'atp/brand/BMO': 47616,
'atp/brand_wikidata/Q4835981': 47616,
'atp/category/amenity/atm': 45794,
'atp/category/amenity/bank': 1822,
'atp/cdn/cloudflare/response_count': 142,
'atp/cdn/cloudflare/response_status_count/200': 142,
'atp/country/CA': 3008,
'atp/country/US': 44608,
'atp/field/branch/missing': 47616,
'atp/field/email/missing': 47615,
'atp/field/image/missing': 47616,
'atp/field/opening_hours/missing': 43637,
'atp/field/operator/missing': 3998,
'atp/field/operator_wikidata/missing': 3998,
'atp/field/phone/missing': 45792,
'atp/field/twitter/missing': 47616,
'atp/item_scraped_host_count/branchlocator.bmo.com': 47616,
'atp/nsi/cc_match': 44608,
'atp/nsi/match_failed': 3008, …
```

[Bmo] Recover lost US POIs for the spider and fix missing fields

---

locations/spiders/osterreichische_post_at.py

```python
{'atp/brand/Post Abholstation': 1492,
'atp/brand_wikidata/Q110748491': 1492,
'atp/category/amenity/parcel_locker': 1492,
'atp/category/amenity/post_box': 13758,
'atp/category/amenity/post_office': 356,
'atp/category/amenity/yes': 1344,
'atp/clean_strings/name': 86,
'atp/clean_strings/phone': 6,
'atp/clean_strings/street': 5,
'atp/country/AT': 16950,
'atp/field/branch/missing': 16950,
'atp/field/brand/missing': 15458,
'atp/field/brand_wikidata/missing': 15458,
'atp/field/email/missing': 15251,
'atp/field/image/missing': 16950,
'atp/field/name/missing': 13761,
'atp/field/opening_hours/missing': 14930,
'atp/field/phone/missing': 15436,
'atp/field/state/missing': 16950, …
```

[Österreichische Post AT] Add spider

---

locations/spiders/alpha_bank_gr.py

**_Fixes : updated request url to fix spider_**
```python
{'atp/brand/Alpha Bank': 1388,
'atp/brand_wikidata/Q747394': 1388,
'atp/category/amenity/atm': 1134,
'atp/category/amenity/bank': 254,
'atp/country/GR': 1388,
'atp/field/city/missing': 1134,
'atp/field/country/from_spider_name': 1388,
'atp/field/email/missing': 1135,
'atp/field/image/missing': 1388,
'atp/field/name/missing': 1134,
'atp/field/opening_hours/missing': 133,
'atp/field/operator/missing': 254,
'atp/field/operator_wikidata/missing': 254,
'atp/field/phone/invalid': 37,
'atp/field/phone/missing': 557,
'atp/field/state/missing': 1388,
'atp/field/twitter/missing': 1388,
'atp/field/website/missing': 1388,
'atp/item_scraped_host_count/www.alpha.gr': 1388,
'atp/nsi/cc_match': 1388,
'atp/operator/Alpha …
```

[Alpha Bank GR] Fix Spider

---

locations/spiders/the_perfume_shop_gb.py

**_Fixes : Flag the_perfume_shop_gb spider as requires proxy to fix spider_**
```python
{'atp/brand/The Perfume Shop': 224,
'atp/brand_wikidata/Q7756719': 224,
'atp/category/shop/perfumery': 224,
'atp/country/GB': 204,
'atp/country/IE': 20,
'atp/field/email/missing': 224,
'atp/field/lat/missing': 23,
'atp/field/lon/missing': 23,
'atp/field/operator/missing': 224,
'atp/field/operator_wikidata/missing': 224,
'atp/field/state/missing': 224,
'atp/field/twitter/missing': 224,
'atp/geometry/null_island': 23,
'atp/item_scraped_host_count/www.theperfumeshop.com': 224,
'atp/nsi/perfect_match': 224,
'downloader/request_bytes': 908836, …
```

[The Perfume Shop GB] Fix Spider

---

locations/spiders/macys.py

**_Fixes : Flag macys as requires proxy to fix spider_**
```python
{"atp/brand/Macy's": 443,
'atp/brand_wikidata/Q629269': 443,
'atp/category/shop/department_store': 443,
'atp/country/GU': 1,
'atp/country/PR': 2,
'atp/country/US': 440,
'atp/field/branch/missing': 443,
'atp/field/country/from_reverse_geocoding': 443,
'atp/field/email/missing': 442,
'atp/field/image/dropped': 443,
'atp/field/image/missing': 443,
'atp/field/operator/missing': 443,
'atp/field/operator_wikidata/missing': 443,
'atp/field/twitter/missing': 443,
'atp/item_scraped_host_count/www.macys.com': 443,
'atp/nsi/perfect_match': 443,
'downloader/exception_count': 4,
'downloader/exception_type_count/scrapy.exceptions.IgnoreRequest': 4,
'downloader/request_bytes': 2311721, …
```

[Macys] Fix Spider

---

locations/spiders/denner_ch.py

`Sitemap` is not available. `API` provides better data than `Structured Data` here, with lesser no. of requests.
```python
{'atp/brand/Denner': 885,
'atp/brand_wikidata/Q379911': 885,
'atp/category/shop/supermarket': 885,
'atp/country/CH': 885,
'atp/field/branch/missing': 885,
'atp/field/country/from_spider_name': 885,
'atp/field/email/missing': 885,
'atp/field/image/missing': 885,
'atp/field/operator/missing': 885,
'atp/field/operator_wikidata/missing': 885,
'atp/field/phone/missing': 611,
'atp/field/state/missing': 885,
'atp/field/street_address/missing': 885,
'atp/field/twitter/missing': 885,
'atp/item_scraped_host_count/www.denner.ch': 885,
'atp/nsi/cc_match': 885,
'downloader/request_bytes': 41591,
'downloader/request_count': 90, …
```

[Denner CH] Fix spider

---

locations/spiders/terminix.py

**_Fixes : added user_agent to fix spider_**
```python
{'atp/brand/Terminix': 533,
'atp/brand_wikidata/Q7702831': 533,
'atp/category/shop/pest_control': 533,
'atp/cdn/cloudflare/response_count': 544,
'atp/cdn/cloudflare/response_status_count/200': 544,
'atp/country/US': 533,
'atp/duplicate_count': 2,
'atp/field/branch/missing': 533,
'atp/field/email/missing': 533,
'atp/field/image/missing': 533,
'atp/field/operator/missing': 533,
'atp/field/operator_wikidata/missing': 533,
'atp/field/twitter/missing': 533,
'atp/item_scraped_host_count/missouri.bugoutservice.com': 1,
'atp/item_scraped_host_count/www.terminix.com': 534,
'atp/nsi/brand_missing': 533, …
```

[Terminix] Fix Spier

---

locations/spiders/kfc_ph.py

```python
{'atp/brand/KFC': 425,
'atp/brand_wikidata/Q524757': 425,
'atp/category/amenity/fast_food': 425,
'atp/clean_strings/street_address': 41,
'atp/country/PH': 425,
'atp/field/branch/missing': 425,
'atp/field/email/missing': 425,
'atp/field/image/missing': 425,
'atp/field/operator/missing': 425,
'atp/field/operator_wikidata/missing': 425,
'atp/field/phone/invalid': 31,
'atp/item_scraped_host_count/stores.kfc.com.ph': 425,
'atp/nsi/cc_match': 425,
'downloader/request_bytes': 277196,
'downloader/request_count': 563,
'downloader/request_method_count/GET': 563,
'downloader/response_bytes': 4745934,
'downloader/response_count': 563,
'downloader/response_status_count/200': 563,
'elapsed_time_seconds': 675.727251, …
```

[KFC PH] Fix XMLSyntaxError for spider

---

locations/spiders/gulf_pr_us.py

```python
{'atp/brand/Gulf': 1102,
'atp/brand_wikidata/Q5617505': 1102,
'atp/category/amenity/fuel': 1102,
'atp/clean_strings/street': 149,
'atp/country/PR': 251,
'atp/country/US': 851,
'atp/field/branch/missing': 1102,
'atp/field/email/missing': 1102,
'atp/field/image/missing': 1102,
'atp/field/opening_hours/missing': 1102,
'atp/field/operator/missing': 1102,
'atp/field/operator_wikidata/missing': 1102,
'atp/field/phone/missing': 253,
'atp/field/state/missing': 251,
'atp/field/street_address/missing': 1102,
'atp/field/twitter/missing': 1102,
'atp/item_scraped_host_count/www.gulfinc.com': 1102,
'atp/nsi/cc_match': 1102,
'downloader/exception_type_count/twisted.internet.error.TimeoutError': 1,
'downloader/request_bytes': 506496, …
```

[Gulf PR US] Fix spider

---

locations/spiders/mitsubishi_be_lu.py

**_Fixes : updated start_urls to fix spider_**
```python
{'atp/brand/Mitsubishi': 60,
'atp/brand_wikidata/Q36033': 60,
'atp/category/shop/car_repair': 60,
'atp/country/BE': 56,
'atp/country/LU': 4,
'atp/field/branch/missing': 60,
'atp/field/country/from_website_url': 59,
'atp/field/state/missing': 59,
'atp/item_scraped_host_count/service.mitsubishi-motors.be': 60,
'atp/nsi/cc_match': 60,
'downloader/request_bytes': 694, …
```

[Mitsubishi BE LU] Fix Spider

---

locations/pipelines/duplicates.py

`message` is now required on DropItem
https://github.com/scrapy/scrapy/commit/ca345a3b73904ffd6d2e8ffb17c45ebb69639d26

Add DropItem message

---

locations/spiders/mondadori_it.py

**_Fixes : added start request to avoid xml response_**
```python
{'atp/brand/Mondadori': 518,
'atp/brand/Mondolibri': 42,
'atp/brand/Rizzoli': 1,
'atp/brand_wikidata/Q119942453': 42,
'atp/brand_wikidata/Q1327389': 1,
'atp/brand_wikidata/Q85355': 518,
'atp/category/shop/books': 453,
'atp/category/shop/newsagent': 108,
'atp/country/IT': 561,
'atp/field/image/missing': 561,
'atp/field/name/missing': 43,
'atp/field/operator/missing': 561,
'atp/field/operator_wikidata/missing': 561,
'atp/field/twitter/missing': 561,
'atp/item_scraped_host_count/www.mondadoristore.it': 561,
'atp/nsi/brand_missing': 43,
'atp/nsi/perfect_match': 518,
'downloader/request_bytes': 813, …
```

[Mondadori IT ] Fix Spider

---

locations/spiders/edible_arrangements.py

**_Fixes : strip time to fix spider_**
```python
{'atp/brand/Edible Arrangements': 620,
'atp/brand_wikidata/Q5337996': 620,
'atp/category/shop/gift': 620,
'atp/clean_strings/addr_full': 19,
'atp/country/PR': 2,
'atp/country/US': 618,
'atp/field/branch/missing': 620,
'atp/field/city/missing': 620,
'atp/field/country/from_reverse_geocoding': 620,
'atp/field/email/missing': 620,
'atp/field/image/missing': 620,
'atp/field/operator/missing': 620,
'atp/field/operator_wikidata/missing': 620,
'atp/field/postcode/missing': 620,
'atp/field/street_address/missing': 620,
'atp/field/twitter/missing': 620,
'atp/item_scraped_host_count/www.ediblearrangements.com': 620,
'atp/nsi/perfect_match': 620,
'downloader/request_bytes': 1187, …
```

[Edible Arrangements] Fix Spider

---

locations/spiders/rebel_architette.py

**_Fixes : Flag rebel_architette as requires proxy to fix spider_**
```python
{'atp/category/office/architect': 1129,
'atp/clean_strings/name': 59,
'atp/country/AO': 2,
'atp/country/AR': 11,
'atp/country/AT': 18,
'atp/country/AU': 30,
'atp/country/BD': 1,
'atp/country/BE': 8,
'atp/country/BG': 1,
'atp/country/BR': 21,
'atp/country/CA': 32,
'atp/country/CG': 1,
'atp/country/CH': 20,
'atp/country/CI': 1,
'atp/country/CL': 4,
'atp/country/CM': 1,
'atp/country/CN': 39,
'atp/country/CO': 1,
'atp/country/CR': 1,
'atp/country/CV': 2,
'atp/country/CY': 2,
'atp/country/CZ': 10,
'atp/country/DE': 21,
'atp/country/DK': 9,
'atp/country/DO': 1,
'atp/country/EC': 1,
'atp/country/EE': 1,
'atp/country/ES': 77,
'atp/country/ET': 1,
'atp/country/FI': 6,
'atp/country/FR': 96,
'atp/country/GB': 78, …
```

[Rebel Architette] Fix Spider

---

locations/spiders/birkenstock.py

**_Fixes : Flag robotstxt_obey as False to fix spider_**
```python
{'atp/brand/Birkenstock': 78,
'atp/brand_wikidata/Q648458': 78,
'atp/category/shop/shoes': 78,
'atp/cdn/cloudflare/response_count': 17,
'atp/cdn/cloudflare/response_status_count/200': 17,
'atp/country/AT': 5,
'atp/country/DE': 28,
'atp/country/DK': 1,
'atp/country/ES': 2,
'atp/country/GB': 5,
'atp/country/IT': 2,
'atp/country/JP': 11,
'atp/country/NL': 2,
'atp/country/US': 22,
'atp/field/branch/missing': 78,
'atp/field/email/missing': 59,
'atp/field/image/missing': 78,
'atp/field/opening_hours/missing': 78,
'atp/field/operator/missing': 78,
'atp/field/operator_wikidata/missing': 78,
'atp/field/phone/invalid': 24,
'atp/field/phone/missing': 21, …
```

[Birkenstock] Fix Spider

---

locations/spiders/walmart_us.py

[Last run](https://alltheplaces-data.openaddresses.io/runs/2025-09-20-13-32-33/stats/walmart_us.json) resulted just `220` POIs.
Increased download delay to avoid request failure.
```
{'atp/brand/Walmart': 4357,
'atp/brand_wikidata/Q483551': 4357,
'atp/category/amenity/pharmacy': 2,
'atp/category/multiple': 2,
'atp/category/shop/department_store': 332,
'atp/category/shop/supermarket': 4023,
'atp/country/US': 4357,
'atp/duplicate_count': 79018,
'atp/field/email/missing': 4357,
'atp/field/image/missing': 4357,
'atp/field/operator/missing': 4357,
'atp/field/operator_wikidata/missing': 4357,
'atp/field/phone/missing': 4357,
'atp/field/twitter/missing': 4357,
'atp/item_scraped_host_count/www.walmart.com': 83375,
'atp/nsi/cc_match': 4357,
'downloader/exception_count': 3, …
```

[Walmart US] Increase download delay to avoid request failure for the spider

---

locations/spiders/truist_us.py

```python
{'atp/brand/Truist': 1979,
'atp/brand_wikidata/Q795486': 1979,
'atp/category/amenity/atm': 81,
'atp/category/amenity/bank': 1898,
'atp/country/US': 1979,
'atp/duplicate_count': 238,
'atp/field/email/missing': 1979,
'atp/field/image/dropped': 1979,
'atp/field/image/missing': 1979,
'atp/field/name/missing': 81,
'atp/field/operator/missing': 1898,
'atp/field/operator_wikidata/missing': 1898,
'atp/field/twitter/missing': 1979,
'atp/item_scraped_host_count/www.truist.com': 2217,
'atp/nsi/cc_match': 1979,
'atp/operator/Truist': 81,
'atp/operator_wikidata/Q795486': 81,
'downloader/exception_count': 75,
'downloader/exception_type_count/twisted.internet.error.TimeoutError': 75,
'downloader/request_bytes': 2301818,
'downloader/request_count': 3692, …
```

[Truist US] Fix spider

---

locations/spiders/pizza_hut_fr.py
locations/spiders/pizza_hut_gb.py
locations/spiders/pizza_hut_in.py

For some the locations, it fails to decode `SD`, was resulting lower count. Hence refactor to fix it.
```python
{'atp/brand/Pizza Hut': 117,
'atp/brand_wikidata/Q191615': 117,
'atp/category/amenity/fast_food': 117,
'atp/country/FR': 117,
'atp/field/city/missing': 117,
'atp/field/country/from_spider_name': 117,
'atp/field/opening_hours/missing': 117,
'atp/field/state/missing': 117,
'atp/field/website/missing': 117,
'atp/item_scraped_host_count/api.pizzahut.io': 117,
'atp/nsi/cc_match': 117,
'downloader/request_bytes': 676, …
```

[Pizza Hut FR] Fix low scraped count for spider

---

locations/spiders/nordea_se.py

```python
{'atp/brand/Nordea': 209,
'atp/brand_wikidata/Q1123823': 209,
'atp/category/amenity/bank': 209,
'atp/clean_strings/postcode': 4,
'atp/country/SE': 209,
'atp/field/branch/missing': 209,
'atp/field/city/missing': 209,
'atp/field/email/missing': 209,
'atp/field/image/missing': 209,
'atp/field/opening_hours/missing': 209,
'atp/field/operator/missing': 209,
'atp/field/operator_wikidata/missing': 209,
'atp/field/phone/missing': 209,
'atp/field/twitter/missing': 209,
'atp/field/website/missing': 209,
'atp/item_scraped_host_count/public-api.nordea.com': 209,
'atp/nsi/cc_match': 209,
'downloader/request_bytes': 1518, …
```

[Nordea SE] Fix Spider

---

locations/spiders/vitalant.py

They occasionally add information text in place of address. Should not prevent the POI being created, but we don't want this in the address fields.

[Vitalant] Improve address error handling

---

locations/spiders/steers_za.py

```python
{'atp/brand/Steers': 666,
'atp/brand_wikidata/Q3056765': 666,
'atp/category/amenity/fast_food': 666,
'atp/country/ZA': 666,
'atp/field/city/missing': 666,
'atp/field/email/missing': 666,
'atp/field/image/missing': 666,
'atp/field/opening_hours/missing': 666,
'atp/field/operator/missing': 666,
'atp/field/operator_wikidata/missing': 666,
'atp/field/postcode/missing': 666,
'atp/field/state/missing': 666,
'atp/field/street_address/missing': 666,
'atp/item_scraped_host_count/admin.goreview.co.za': 666,
'atp/nsi/perfect_match': 666,
'atp/steers_za/attribute/24 Hours': 60,
'atp/steers_za/attribute/Breakfast': 601,
'atp/steers_za/attribute/Brunch': 658,
'atp/steers_za/attribute/Call & Collect': …
```

[Steers ZA] Fix Spider
